### ISSUE TITLE
kubelet:  kubelet delete running podes after restart when /var/lib/kubelet is not writable

### ISSUE THREAD

**Issue by chenyw1990** [kubernetes/kubernetes#94305]
**What happened**:

kubelet delete running podes after restart when /var/lib/kubelet is not writable

log is:
Line 81243: W0805 14:50:25.334153   30356 predicate.go:83] Failed to admit pod demo_default(f05ac3a3-fc1c-428b-8800-af2b6598992d) - Update plugin resources failed due to failed to write checkpoint file "kubelet_internal_checkpoint": write /var/lib/kubelet/device-plugins/.288934392: no space left on device, which is unexpected.

**What you expected to happen**:
if pod does not use thirdpart device，kubelet don't delete the running pod after restart.

**How to reproduce it (as minimally and precisely as possible)**:

stop kubelet。

Run the mount command to create a memory disk,like this:
`mount -t tmpfs -o size=100m tmpfs /var/lib/kubelet`

start kubelet，wait pod running。

stop kubelet。

Run the dd command to use up the /var/lib/kubelet directory. like this：
`dd if=/dev/zero of=/var/lib/kubelet/test bs=1M count=1000`

then restart kubelet, the running pod on the node while admit failed and deleted.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.15.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): EulerOS 2.0
- Kernel (e.g. `uname -a`): Linux 4.19.36
- Install tools: 
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
this is an unsupported version of k8s:
> Kubernetes version (use kubectl version):1.15.1

can you reproduce the problem with 1.17+?

**Comment by chenyw1990** [comment]
@neolit123 I have test with kubelet v1.18.1，The bug still exists.
before kubelet restart
![image](https://user-images.githubusercontent.com/1468240/96118841-ad8bfc00-0f1e-11eb-9a50-c44f20bf235e.png)

after restart kubelet，container be restart
![image](https://user-images.githubusercontent.com/1468240/96118863-ba105480-0f1e-11eb-9c71-32f22002c968.png)

log is：
`I1015 19:53:34.784437  104589 kubelet.go:1907] SyncLoop (ADD, "api"): "kube-proxy-b5qd2_kube-system(79b7175f-e88e-41f4-9dcf-51bf7b2db9ef)"
I1015 19:53:34.784543  104589 topology_manager.go:233] [topologymanager] Topology Admit Handler
I1015 19:53:34.784560  104589 reflector.go:175] Starting reflector *v1.Secret (0s) from object-"kube-system"/"kube-proxy-token-7cww5"
W1015 19:53:34.784675  104589 manager.go:582] failed to write checkpoint file "kubelet_internal_checkpoint": write /var/lib/kubelet/device-plugins/.021367929: no space left on device
I1015 19:53:34.784742  104589 reflector.go:175] Starting reflector *v1.ConfigMap (0s) from object-"kube-system"/"kube-proxy"
I1015 19:53:34.784736  104589 kubelet.go:1952] SyncLoop (PLEG): "kube-proxy-b5qd2_kube-system(79b7175f-e88e-41f4-9dcf-51bf7b2db9ef)", event: &pleg.PodLifecycleEvent{ID:"79b7175f-e88e-41f4-9dcf-51bf7b2db9ef", Type:"ContainerStarted", Data:"541b0bc4abc515c2879cd8f0a629f783d30cd23d293c9651c4af4947277c334c"}
I1015 19:53:34.785380  104589 kubelet_node_status.go:486] Recording NodeHasSufficientMemory event message for node huangbenhao
I1015 19:53:34.785397  104589 kubelet_node_status.go:486] Recording NodeHasDiskPressure event message for node huangbenhao
I1015 19:53:34.785410  104589 kubelet_node_status.go:486] Recording NodeHasSufficientPID event message for node huangbenhao
I1015 19:53:34.785431  104589 kubelet_node_status.go:70] Attempting to register node huangbenhao
I1015 19:53:34.794707  104589 reflector.go:181] Stopping reflector *v1.ConfigMap (0s) from object-"kube-system"/"kube-proxy"
I1015 19:53:34.794740  104589 reflector.go:181] Stopping reflector *v1.Secret (0s) from object-"kube-system"/"kube-proxy-token-7cww5"
I1015 19:53:34.796103  104589 kubelet_node_status.go:112] Node huangbenhao was previously registered
I1015 19:53:34.796157  104589 kubelet_node_status.go:73] Successfully registered node huangbenhao
I1015 19:53:34.802281  104589 kubelet.go:1923] SyncLoop (DELETE, "api"): "kube-proxy-b5qd2_kube-system(79b7175f-e88e-41f4-9dcf-51bf7b2db9ef)"
I1015 19:53:34.807341  104589 kubelet.go:1917] SyncLoop (REMOVE, "api"): "kube-proxy-b5qd2_kube-system(79b7175f-e88e-41f4-9dcf-51bf7b2db9ef)"
I1015 19:53:34.809006  104589 kubelet_pods.go:1117] Killing unwanted pod "kube-proxy-b5qd2"`

**Comment by neolit123** [comment]
Ok this is up to the Sig Node group to triage.

**Comment by chenyw1990** [comment]
i have create a pull request to fix it
[#95602](https://github.com/kubernetes/kubernetes/pull/95602)

**Comment by RenaudWasTaken** [comment]
Hello!

I'm having a hard time understanding what is the context / use case you are trying to fix, would you mind dumbing it down for me 😅?

Thanks a lot!

**Comment by chenyw1990** [comment]
@RenaudWasTaken 

In our use case, we hope that some pods can run properly when the disk pressure. We set a tolerance policy for these pods to tolerate disk-pressure stains and set the pod to Critical Pod use priority = 2000001000.

When kubelet restarts, it obtains the list of pods that should run on the node from kube-apiserver and invokes the Kubelet.HandlePodAdditions function again for these pods, 

```
 func (kl *Kubelet) HandlePodAdditions(pods []*v1.Pod) {
	start := kl.clock.Now()
	sort.Sort(sliceutils.PodsByCreationTime(pods))
	for _, pod := range pods {
		existingPods := kl.podManager.GetPods()
		// Always add the pod to the pod manager. Kubelet relies on the pod
		// manager as the source of truth for the desired state. If a pod does
		// not exist in the pod manager, it means that it has been deleted in
		// the apiserver and no action (other than cleanup) is required.
		kl.podManager.AddPod(pod)

		if kubetypes.IsMirrorPod(pod) {
			kl.handleMirrorPod(pod, start)
			continue
		}

		if !kl.podIsTerminated(pod) {
			// Only go through the admission process if the pod is not
			// terminated.

			// We failed pods that we rejected, so activePods include all admitted
			// pods that are alive.
			activePods := kl.filterOutTerminatedPods(existingPods)

			// Check if we can admit the pod; if not, reject it.
			if ok, reason, message := kl.canAdmitPod(activePods, pod); !ok {
				kl.rejectPod(pod, reason, message)
				continue
			}
		}
		mirrorPod, _ := kl.podManager.GetMirrorPodByPod(pod)
		kl.dispatchWork(pod, kubetypes.SyncPodCreate, mirrorPod, start)
		kl.probeManager.AddPod(pod)
	}
}
 ```

in the Kubelet.HandlePodAdditions function, it call kl.canAdmitPod(activePods, pod),
```
func (kl *Kubelet) canAdmitPod(pods []*v1.Pod, pod *v1.Pod) (bool, string, string) {
	// the kubelet will invoke each pod admit handler in sequence
	// if any handler rejects, the pod is rejected.
	// TODO: move out of disk check into a pod admitter
	// TODO: out of resource eviction should have a pod admitter call-out
	attrs := &lifecycle.PodAdmitAttributes{Pod: pod, OtherPods: pods}
	for _, podAdmitHandler := range kl.admitHandlers {
		if result := podAdmitHandler.Admit(attrs); !result.Admit {
			return false, result.Reason, result.Message
		}
	}

	return true, "", ""
}
```

In kl.admitHandlers, a handler is resourceAllocator. This handler invokes the Allocate method of DeviceManager to check whether the device used by the pod exists and updates the kubelet_internal_checkpoint file.

`klet.admitHandlers.AddPodAdmitHandler(klet.containerManager.GetAllocateResourcesPodAdmitHandler())`

```
func (cm *containerManagerImpl) GetAllocateResourcesPodAdmitHandler() lifecycle.PodAdmitHandler {
	if utilfeature.DefaultFeatureGate.Enabled(kubefeatures.TopologyManager) {
		return cm.topologyManager
	}
	// TODO: we need to think about a better way to do this. This will work for
	// now so long as we have only the cpuManager and deviceManager relying on
	// allocations here. However, going forward it is not generalized enough to
	// work as we add more and more hint providers that the TopologyManager
	// needs to call Allocate() on (that may not be directly intstantiated
	// inside this component).
	return &resourceAllocator{cm.cpuManager, cm.deviceManager}
}
```

resourceAllocator's Admit function will call the Allocate function of deviceManager
```
func (m *resourceAllocator) Admit(attrs *lifecycle.PodAdmitAttributes) lifecycle.PodAdmitResult {
	pod := attrs.Pod

	for _, container := range append(pod.Spec.InitContainers, pod.Spec.Containers...) {
		err := m.deviceManager.Allocate(pod, &container)
		if err != nil {
			return lifecycle.PodAdmitResult{
				Message: fmt.Sprintf("Allocate failed due to %v, which is unexpected", err),
				Reason:  "UnexpectedAdmissionError",
				Admit:   false,
			}
		}
```

![image](https://user-images.githubusercontent.com/1468240/96204676-81f92800-0f97-11eb-8c41-6ed84d727277.png)

![image](https://user-images.githubusercontent.com/1468240/96204698-8d4c5380-0f97-11eb-8664-007e752a8abe.png)

If the usage of the disk where /var/lib/kubelet is located reaches 100%, m.writeCheckpoint() will return err, and the pod will be recreate due to an admit failure.

I think, if a pod does not use device, the kubelet_internal_checkpoint file should not be refreshed. In this way, admit will success, and the pod will not be recreate.

**Comment by chenyw1990** [comment]
@RenaudWasTaken 
Do I need to provide more information？

**Comment by sjenning** [comment]
If `/var/lib/kubelet` is full, you are going to have a lot of issues.  This is just one of them.

**Comment by chenyw1990** [comment]
@sjenning 
Yes, The /var/lib/kubelet directory is used as the metadata storage directory of kubelet, When the /var/lib/kubelet directory is full, some problems may occur, For example, new pods cannot be created,
However, if the pods on the node is not changed, the metadata should not be refreshed and the running critical pod should not be rebuilt.

**Comment by sjenning** [comment]
Fair enough.  I approved the PR and deferred lgtm from one of the more recent contributors to the component.  Thanks!

**Comment by RenaudWasTaken** [comment]
Sorry for the lag and thanks for the detailed explanation!
I had the same concern that @sjenning raised, but if this is the only issue, let me look up the PR!
