### ISSUE TITLE
Add kubelet /metric endpoints to measure and debug per pod startup latency 

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#9430]
To measure the latency of starting a single pod on a 30 pod node we need an accurate depiction of how long it took start. Currently we use `time created - time started of last container`. This has the following problems:
1. includes scheduler overhead
2. time started is updated on restart

What we want to know is how long it took the kubelet from when it saw a pod in Pending, to update it to Running, and what part of that pipeline was slowest. We need to get this information from an e2e test.

/ref https://github.com/GoogleCloudPlatform/kubernetes/issues/3954

**Comment by yujuhong** [comment]
Does e2e test look at /metrics at all? It already provides a bunch of information, but lacks the startup latency. I have a pending PR (just uploaded, #9457) that records the latency from seeing the pod for the first time to start a pod worker for it. This is not exactly what you want, but may help anyway for the breakdown. 

> 2. time started is updated on restart

There is also a `StartTime` timestamp in the pod status that is recorded *after* starting all the containers in the pod for the first time. It could be used to measure how long it takes to actually send out the status update.

**Comment by pmorie** [comment]
@detiber

**Comment by erictune** [comment]
You could add an event to kubelet when it notices a pod for the first time.  This would be generally be useful, and since it is events, you can process that at the end of the test.

**Comment by yujuhong** [comment]
I think this is already done in various performance tests.
