### ISSUE TITLE
[Flaky Test]  SSL: no alternative certificate subject name matches target host name 'kind.sigs.k8s.io'

### ISSUE THREAD

**Issue by MarcPow** [kubernetes/kubernetes#94311]
**Which jobs are flaking**:
pull-kubernetes-e2e-kind-ipv6

**Which test(s) are flaking**:

**Testgrid link**:
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-kind-ipv6

**Reason for failure**:
wrapper.sh] [TEST] Running Test Command: `bash -c curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && e2e-k8s.sh` ...
curl: (60) SSL: no alternative certificate subject name matches target host name 'kind.sigs.k8s.io'
More details here: https://curl.haxx.se/docs/sslcerts.html
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Anything else we need to know**:

**Comment by neolit123** [comment]
/sig testing

seems like some sort of a domain flake?
cc @BenTheElder

**Comment by BenTheElder** [comment]
this domain is netlify behind github.com/kubernetes/k8s.io
I think we should probably just update the job to retry (looks like curl can do this natively?)

**Comment by BenTheElder** [comment]
it's also weird because the domain has a legitimate letsencrypt certificate. I think there must be some flake on netlify's end.

looking around for similar issues
/assign

**Comment by BenTheElder** [comment]
I think the netlify / DNS is mismatched between netlify and kubernetes DNS settings, at some point someone added a different domain to the site that we don't use. this is causing hiccups in renewing the certs, but it's not clear if that is the root cause here.

discussing in sig-docs-tools https://kubernetes.slack.com/archives/CCTBSCVB9/p1598647924000400?thread_ts=1598647801.000200&cid=CCTBSCVB9

**Comment by BenTheElder** [comment]
I removed kind.docs.kubernetes.io from the netlify end (which doesn't appear to be quite right in DNS) and requested that netlify renew the cert.

I'm not sure if that was the cause though, or some other flake.

**Comment by BenTheElder** [comment]
Please let me know if you see any further instances of this. Currently it's difficult to find these and the root cause is not easily proven.

**Comment by BenTheElder** [comment]
Lacking evidence of this happening again, I'm going to close for now
/close
