### ISSUE TITLE
Default VolumeSnapshotClass should depend on provisioner of PVC

### ISSUE THREAD

**Issue by chrishenzie** [kubernetes/kubernetes#94312]
**What would you like to be added**:

When creating a VolumeSnapshot of a PVC, the default logic (when no VolumeSnapshotClass is provided) should use the VolumeSnapshotClass with the correct driver for that PVC.

More specifically, the VolumeSnapshotClass picked should be the one whose `driver` matches the `provisioner` of the StorageClass that created the PVC.

**Why is this needed**:

Right now the default VolumeSnapshotClass is determined by the `snapshot.storage.kubernetes.io/is-default-class: "true"` annotation.

If you create a VolumeSnapshot of a PVC and the default VolumeSnapshotClass uses a different driver than the provisioner for that PVC it won't work.

This should be a blocker for GA of VolumeSnapshots in 1.20.

@saad-ali @msau42

**Comment by msau42** [comment]
This also allows you to have a default snapshotclass per driver in a single cluster.

**Comment by chrishenzie** [comment]
How would this interact with the current annotation? I would imagine relying on the suggested behavior first and falling back to the annotation. Should the annotation be deprecated?

**Comment by saad-ali** [comment]
@xing-yang @yuxiangqian thoughts? Seems like a GA blocker?

**Comment by xing-yang** [comment]
> Right now the default VolumeSnapshotClass is determined by the snapshot.storage.kubernetes.io/is-default-class: "true" annotation.
> If you create a VolumeSnapshot of a PVC and the default VolumeSnapshotClass uses a different driver than the provisioner for that PVC it won't work.

I think this is the correct behavior.  We can't completely dependent on existing VolumeSnapshotClasses as there could be multiple of them for the same driver.  We can't determine which one is the one user intends to use.

**Comment by xing-yang** [comment]
> I think the annotation can remain the same. It's just when we search for the default storageclass, we search for one with the annotation + the driver matches.

I think we already have logic to make sure that driver in the default snapshot class matches the driver for the PVC.

**Comment by xing-yang** [comment]
@yuxiangqian please chime in if you have any comments.

**Comment by yuxiangqian** [comment]
First of all, I dislike the idea of default as it brings certain degree of uncertainty. Having said that, it does executes end users from dealing with/understanding non-namespaced volume snapshot class, and shifts the management of those classes to storage admins.

> When creating a VolumeSnapshot of a PVC, the default logic (when no VolumeSnapshotClass is provided) should use the VolumeSnapshotClass with the correct driver for that PVC.
> 
> More specifically, the VolumeSnapshotClass picked should be the one whose `driver` matches the `provisioner` of the StorageClass that created the PVC.
> 

This is the current behavior already. If no VolumeSnapshotClass is provided, [getStorageClassFromVolumeSnapshot](https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/common-controller/snapshot_controller.go#L1150) will be called in [SetDefaultSnapshotClass](https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/common-controller/snapshot_controller.go#L1189). It takes the PVC's driver from PVC storage class, and try to find any `VolumeSnapshot` class  with the default annotation **AND** has the same driver PVC driver. If there are multiple matches or no match, the snapshot will fail.
**NOTE**: There can be more than one VolumeSnapshotClasses marked as default in a cluster for different drivers; however there can not exist more than one default VolumeSnapshotClass for a specific driver, or any VolumeSnapshot with a PVC provisioned from that driver and without specifying a VolumeSnapshotClass will fail.

> Right now the default VolumeSnapshotClass is determined by the `snapshot.storage.kubernetes.io/is-default-class: "true"` annotation.
This is not accurate,  see above.

> If you create a VolumeSnapshot of a PVC and the default VolumeSnapshotClass uses a different driver than the provisioner for that PVC it won't work.
Should not this be the desired behavior? if the chosen VolumeSnapshotClass has a different driver than the PVC storage class, the snapshot should **not** be created.

**Comment by msau42** [comment]
> This is the current behavior already. If no VolumeSnapshotClass is provided, [getStorageClassFromVolumeSnapshot](https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/common-controller/snapshot_controller.go#L1150) will be called in [SetDefaultSnapshotClass](https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/common-controller/snapshot_controller.go#L1189). It takes the PVC's driver from PVC storage class, and try to find any `VolumeSnapshot` class with the default annotation **AND** has the same driver PVC driver. If there are multiple matches or no match, the snapshot will fail.

This is the behavior we want. We want to be able to have 2 different drivers installed in the cluster, and each of them has their own default snapshotclass. @chrishenzie can you verify if this is working as intended?

**Comment by msau42** [comment]
Although @yuxiangqian I think it is unnecesary to lookup the Storageclass to get the driver name.

1. We should not depend on storageclass after a volume has been provisioned, because the storageclass is only used for provisioning and can be changed.
2. Driver name is available in the PV object.

**Comment by xing-yang** [comment]
> This is the behavior we want. We want to be able to have 2 different drivers installed in the cluster, and each of them has their own default snapshotclass. @chrishenzie can you verify if this is working as intended?

So if there is only 1 snapshot class per driver, we use that as the default class; if there are 2 or more snapshot classes per driver, we fail it?

**Comment by msau42** [comment]
Yes fail if there's multiple snapshot classes set for the same driver.

**Comment by msau42** [comment]
Note that in the StorageClass case, we use an admission controller to actually fill in the default storageclass name in the PVC. This makes it clear which storageclass we used. Do we do something similar for snapshots?

**Comment by yuxiangqian** [comment]
> Note that in the StorageClass case, we use an admission controller to actually fill in the default storageclass name in the PVC. This makes it clear which storageclass we used. Do we do something similar for snapshots?
>

yes, but instead of using admission controller, the snapshot controller itself will fill in that information on the Snapshot CR if one exists.

**Comment by yuxiangqian** [comment]
> Although @yuxiangqian I think it is unnecesary to lookup the Storageclass to get the driver name.
> 
This is a fair point but I have some minor concerns.

> 1. We should not depend on storageclass after a volume has been provisioned, because the storageclass is only used for provisioning and can be changed.
>
Not the `provisioner` field though, it's immutable. Though a SC can be deleted.

> 2. Driver name is available in the PV object.
>
PV does not have a driver/provisioner field in its spec however it does have a storage class name AFAIK, I assume you were taking about using the value of this `pv.kubernetes.io/provisioned-by` annotation. I always feel more comfortable to refer to a spec field than annotation field.

**Comment by msau42** [comment]
Yeah, the scenario that you can delete and recreate a storageclass with same name but completely different arguments (including changing the driver name).

PV.spec.csi.driver can be used instead of storageclass.

**Comment by chrishenzie** [comment]
Confirmed this behaves as expected. Created two VolumeSnapshotClasses with different CSI drivers, both marked as default. Created a VolumeSnapshot without providing a `volumeSnapshotClassName`, and it used the correct VolumeSnapshotClass based on the provisioner of the PVC.

**Comment by yuxiangqian** [comment]
> Yeah, the scenario that you can delete and recreate a storageclass with same name but completely different arguments (including changing the driver name).
> 
> PV.spec.csi.driver can be used instead of storageclass.provisioner
>

created 404 issue :) https://github.com/kubernetes-csi/external-snapshotter/issues/404
