### ISSUE TITLE
PVCs specified with quantity containing suffix `m` are not counted in ResourceQuota and block ResourceQuota updates

### ISSUE THREAD

**Issue by gabbifish** [kubernetes/kubernetes#94313]
**What happened**:
When a pvc was specified with a quantity including the suffix `m`:
```yaml
...
spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100m
...
```

attempts to include that quantity in the resourcequota's storage  resulted in the following error, which blocked all other updates to the resourcequota:

```
E0827 23:17:08.653750 1744486 resource_quota_controller.go:251] ResourceQuota "namespaced-quota" is invalid: status.used[scaleio.storageclass.storage.k8s.io/requests.storage]: Invalid value: resource.Quantity{i:resource.int64Amount{value:518617300992100, scale:-3}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"518617300992100m", Format:"DecimalSI"}: must be an integer
```

**What you expected to happen**:
- Updates to all other quantities in the resourcequota should not have been blocked by the error above
- In general, `m` as a suffix (milli) doesn't really make sense when used in the context of memory, and causes issues like the above. Would it be possible to deny the usage of this suffix at admission time for things like pvcs? (Our mitigation right now is to add a rule that does this in Open Policy Agent).

**How to reproduce it (as minimally and precisely as possible)**:

Create a resourcequota object with limits on pvcs and the a storage type, e.g.
```
...
  spec:
    hard:
      count/persistentvolumeclaims: "100"
      scaleio.storageclass.storage.k8s.io/requests.storage: 3Ti
...
```

Then create a PVC with the following spec:
```
spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100m
```

The resource quota controller should start producing the error log above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.17.3
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
i guess we should leave api-machinery!
/sig api-machinery

**Comment by knight42** [comment]
/assign

I think we should validate the value of `storage` field.

**Comment by knight42** [comment]
I've filed #94333 to address this issue.

**Comment by knight42** [comment]
looks like it is not easy to tighten the validation and that requires careful consideration
xref: https://github.com/kubernetes/kubernetes/issues/59984 https://github.com/kubernetes/kubernetes/issues/64841

**Comment by yliaog** [comment]
"Updates to all other quantities in the resourcequota should not have been blocked by the error above" should be fixed separately

**Comment by liggitt** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/94620 to round storage requests up to the nearest byte in the quota evaluator.
