### ISSUE TITLE
API client fails to recover when server returns "Timeout: Too large resource version" error

### ISSUE THREAD

**Issue by janeczku** [kubernetes/kubernetes#94315]
**What happened**:

- Using client-go v1.18.8 to watch resources on API server versions 1.17.x and 1.18.0 - 1.18.5
- After the connection to the server is temporarily interrupted the client never recovers from `Too large resource version` error

See the earlier issue for steps to reproduce: https://github.com/kubernetes/kubernetes/issues/91073

This was assumed fixed by https://github.com/kubernetes/kubernetes/pull/92537

But it appears the fix for the client was (probably inadvertently) implemented in a non-backward-compatible fashion and only solves the issue when the server is running v1.18.6 or later as well.

```
E0828 13:04:17.404984       6 reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1.ReplicationController: Timeout: Too large resource version: 750, current: 1
I0828 13:04:25.561465       6 trace.go:116] Trace[1614394438]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-08-28 13:03:46.405986919 +0000 UTC m=+1932.339601604) (total time: 39.15545352s):
Trace[1614394438]: [39.15545352s] [39.15545352s] END
E0828 13:04:25.561490       6 reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1beta1.CronJob: Timeout: Too large resource version: 1389, current: 1
I0828 13:04:27.175925       6 trace.go:116] Trace[1577718691]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-08-28 13:03:48.004473198 +0000 UTC m=+1933.938087858) (total time: 39.171388567s):
Trace[1577718691]: [39.171388567s] [39.171388567s] END
```

**Comment by liggitt** [comment]
Cc @jpbetz @wojtek-t

**Comment by janeczku** [comment]
PR https://github.com/kubernetes/kubernetes/pull/94316

**Comment by wojtek-t** [comment]
> implemented in a non-backward-compatible fashion and only solves the issue when the server is running v1.18.6 or later as well.

We generally recommend having apiservers be updated first before all other components.

But yeah - it's true that this doesn't work for clients being more fresh - let me take a look at your PR.

**Comment by wojtek-t** [comment]
This will be addressed by https://github.com/kubernetes/kubernetes/pull/94316 (and the cherrypicking it back).

**Comment by wojtek-t** [comment]
This has been fixed by https://github.com/kubernetes/kubernetes/pull/94316 and corresponding cherrypicks.
