### ISSUE TITLE
Trying to get client real-ip to restrict some access at pod on kubernetes environemnt

### ISSUE THREAD

**Issue by a2z-ice** [kubernetes/kubernetes#94330]
Hi I'm trying to get client real-ip to restrict some access at pod. But unfortunately I'm always getting 10.244.1.1 at every pod. I have tried with https://kubernetes.io/docs/tutorials/services/source-ip/ but unfortunately no luck. Please help.

I'm using kubernetes 1.8.2 version on cent os 7 bare metal servers for kubernetes cluster. I do not have any choice bu to use bare metal . As an ingress controller I'm using kong. My kong ingress controller is always getting 10.244.1.1. In kong there is a feature called IP restriction. I'm trying to use it.

So other suggested to use another kong hop as a loadbalancer which is not a good solution for my situation.

I also tried with version v1.18.6 as well but unfortunately getting same result

**Comment by neolit123** [comment]
hi, we try to delegate requests for help to the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

if you are convinced that this a bug in kubernetes please reopen the ticket.

/close
/sig network
