### ISSUE TITLE
Add warning messages about deprecated seccomp annotation usage

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/kubernetes#94365]
The [Pod Creation](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/20190717-seccomp-ga.md#pod-creation) and [PodTemplates](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/20190717-seccomp-ga.md#podtemplates) sections of the seccomp GA KEP mention that we should populate a warning message to the client if they're used. This issue should be the tracking issue for that last bit of the KEP.

I'm wondering which part of the sources would be a good fit to add the warning. The version skew [is handled there](https://github.com/kubernetes/kubernetes/blob/02b5b60ecdf663acc00bafe534ce7483aaf2d782/pkg/registry/core/pod/strategy.go#L578), but I think this might be not the right place.

cc @pjbgf @hasheddan @liggitt 
/sig node
/priority important-soon

**Comment by liggitt** [comment]
for 1.20, I'm working on adding a helper that can be used by validation and REST handlers to add warnings about specific fields

**Comment by saschagrunert** [comment]
> for 1.20, I'm working on adding a helper that can be used by validation and REST handlers to add warnings about specific fields

That's what I was looking for! Nice, thank you so much! :heart:

**Comment by liggitt** [comment]
Tracking in #94626
