### ISSUE TITLE
[Failing Test] [sig-scalability] ci-kubernetes-e2e-gce-scale-performance failed due to slow GET services proxy calls

### ISSUE THREAD

**Issue by jkaniuk** [kubernetes/kubernetes#94368]
**Which jobs are failing**:
ci-kubernetes-e2e-gce-scale-performance
**Which test(s) are failing**:
density & load
**Since when has it been failing**:
31 Aug
**Testgrid link**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1300116668424392704
**Reason for failure**:
```
testing/density/config.yaml expand_less	1h58m16s

[measurement call APIResponsivenessPrometheus - APIResponsivenessPrometheusSimple error: top latency metric: there should be no high-latency requests, but: [
got: &{Resource:services Subresource:proxy Verb:GET Scope:resource Latency:perc50: 1.168918918s, perc90: 1.403846153s, perc99: 1.490384615s Count:50 SlowCount:50}; expected perc99 <= 1s]]

testing/load/config.yaml expand_less	9h44m33s

[measurement call APIResponsivenessPrometheus - APIResponsivenessPrometheusSimple error: top latency metric: there should be no high-latency requests, but: [
got: &{Resource:services Subresource:proxy Verb:GET Scope:resource Latency:perc50: 1.236607142s, perc90: 1.484523809s, perc99: 1.716874999s Count:53 SlowCount:53}; expected perc99 <= 1s]]
```

**Anything else we need to know**:
/sig scalability
/assign

**Comment by wojtek-t** [comment]
"proxy" subresource should be excluded from our SLO (as it can be literally arbitraly long).

**Comment by wojtek-t** [comment]
Same failure second time - I don't think that was a flake:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1300479056172552194

@kubernetes/ci-signal - FYI

Also - see my comment above - we should not count "proxy" subresource into the SLO.
