### ISSUE TITLE
Control manager logs: CPU Throttling request took seconds

### ISSUE THREAD

**Issue by saraAlizadeh** [kubernetes/kubernetes#94362]
/sig node
/sig storage
/area controller-manager

**What happened**:
Hello everyone,
I've had his cpu throttling delays as mentioned in [here](https://github.com/ceph/ceph-csi/issues/1109), with k8s 1.18.2.
additional links: 
https://github.com/kubernetes/kubernetes/pull/91307
https://github.com/kubernetes/kubernetes/pull/92015

So as they suggest I upgraded to 1.18.5, where this issue is solved.
but again I see some cpu throttling logs in kube-controller-manager.
```
$ kubectl logs kube-controller-manager-master1 -n kube-system | grep I0831 | grep Throttling

I0831 04:59:38.943580       1 request.go:621] Throttling request took 1.048144864s, request: GET:https://myIP:6443/apis/authorization.k8s.io/v1?timeout=32s
I0831 05:00:11.746582       1 request.go:621] Throttling request took 1.047269948s, request: GET:https://myIP:6443/apis/objectbucket.io/v1alpha1?timeout=32s
I0831 05:00:44.548868       1 request.go:621] Throttling request took 1.047943136s, request: GET:https://myIP:6443/apis/discovery.k8s.io/v1beta1?timeout=32s
I0831 05:01:17.351293       1 request.go:621] Throttling request took 1.047916871s, request: GET:https://myIP:6443/apis/coordination.k8s.io/v1?timeout=32s
I0831 05:01:50.153706       1 request.go:621] Throttling request took 1.048254098s, request: GET:https://myIP:6443/apis/batch/v1?timeout=32s
I0831 05:02:22.956631       1 request.go:621] Throttling request took 1.048141565s, request: GET:https://myIP:6443/apis/apiextensions.k8s.io/v1?timeout=32s
```

Is this normal or I must be worried? the throttling time does not increase over time, its about one second.
and also the logs are much fewer than the previous version (1.18.2). right now, last cpu throttling log I get, is for 5 hours ago.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.5
- OS (e.g: `cat /etc/os-release`):  centos 7
- Kernel (e.g. `uname -a`):
Linux master1 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
docker-ce.x86_64                      3:19.03.8-3.el7
kubeadm.x86_64                      1.18.5-0     
kubectl.x86_64                          1.18.5-0       
kubelet.x86_64                          1.18.5-0     
kubernetes-cni.x86_64              0.8.6-0

**Comment by liggitt** [comment]
that's not CPU throttling, that is request throttling, which occurs when many requests are made at once. occurring once a minute or so is not concerning

/remove-kind bug
/triage support
/close

**Comment by bukowa** [comment]
> 
> 
> that's not CPU throttling, that is request throttling, which occurs when many requests are made at once. occurring once a minute or so is not concerning
> 
> /remove-kind bug
> /triage support
> /close

Where can we find more info about this, specifically how to remove this throttling ?

**Comment by theJaxon** [comment]
> > that's not CPU throttling, that is request throttling, which occurs when many requests are made at once. occurring once a minute or so is not concerning
> > /remove-kind bug
> > /triage support
> > /close
> 
> Where can we find more info about this, specifically how to remove this throttling ?

For me the issue was that the permissions of $HOME/.kube dir were root:root so when i executed a command like `k get all -A --v=10` i got the following error 
> failed to write cache to /home/vagrant/.kube/cache/discovery/192.168.100.10_6443/autoscaling/v2beta1/serverresources.json due to mkdir /home/vagrant/.kube/cache: permission denied
When i changed the permissions of .kube to my current user and group vagrant:vagrant the error didn't occur again because the cache directory now gets created

**Comment by j3ffyang** [comment]
@theJaxon - changing the ownership of `~/.kube` to `nonroot` user fixes the problem. Thanks
