### ISSUE TITLE
Unable to open TCP/IP to server for a service running inside the cluster when a new ec2 machine joins the cluster (which has nothing to do with the service)

### ISSUE THREAD

**Issue by 27claudia** [kubernetes/kubernetes#94360]
**What happened**:
Hi there! I would like to report a peculiar behavior regarding kubernetes networking setup (i think).
Maybe it's aws kops related?

Arhitecture context: some nodes running a flask/gunicorn application, which process HTTP requests from our clients; this service is always running.
We use kubernetes batch jobs, which run on their own instance, to train our ML models. Daily a between 2 to 3 new nodes join and leave the cluster. 
 
The problem:
Every now & then ( frequency max 10 times a month, sometimes twice a week, sometimes 1 a week, going on since approx 4 months now), when a new node is launched into kops (1.16) cluster on aws, after approx 4 1/2 minutes of runtime (*), the client http requests directed at the server (where a flask service is running and processing these requests) throws the series of errors:

First the flask server runs into a timeout (i assume for the http request currently processed) OR I get a 401 from my Kong GW (sometimes I get timeout, sometimes I get a 401).
Then this: ERROR #6059: Unable to open TCP/IP socket to server (myapp:80)
i.e. they do not reach my service inside the cluster (i assume, am I wrong?)

But the next http request is processed ok, i.e. only the following 2 requests are affected by this behavior, afterwards everything works as expected. 

It is always like this. 

**What you expected to happen**:
The http requests find their way into the cluster and are being processed.
I would like to know the reason for the second error; why does it seems like my services is not available?

**How to reproduce it (as minimally and precisely as possible)**:
Launch new nodes in the cluster, while constanty sending HTTP requests to the service inside the cluster, port 80. 
Sometimes the errors does not occur! 

**Anything else we need to know?**:
I would need some hints where to look exactly, I don't know where to beging debuging, since it does not happen so frequently; (it's annoying though)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16 
- Cloud provider or hardware configuration: aws - kops (ami k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17 (ami-0f57f24ebb600bc3d)
- OS (e.g: `cat /etc/os-release`): ubuntu
- Kernel (e.g. `uname -a`): debian strech - kernel image: 4.9.0-11-amd64
- Install tools:
- Network plugin and version (if this is a network-related bug): CNI ( calico/cni:v3.9.5 docker image)
- Others: kong gw - kong ingress controller (kong 1.5, kong-ingress-controller:0.7.1)

More details about the new node: we have cronjobs running (in Docker) bash scripts, which download something from an s3 bucket then the start R and do some calculations. 
They are scheduled on their own nodes, not to interfere with live business. The ones under which the "Unable to open TCP/IP socket" error arises, run daily, but this error does not occur daily.

(*)
The scenario is following: the ec2 machine joined the cluster, the docker has started and inside the bash script there is a 4 minute sleep built in. After the 4 minutes are passed by, then we call the s3 bucket to get some files from there. 
The error occurs 4min and 30 seconds afterwards, so i guess in the middle of file-download / seconds after, during unzipping the files). 

I check the master nodes for kubelet journal; i greped for errors, but did not find anything (do not have full application logging in place):
I checked the kubelet, daemon log and found following:
1. i did find some issues with the eviciton manager / image garbage collection who was complaining it remove one particular image, but that's it in terms of errors)
2. calico, kops controller, but then they worker fine (Pod attempted illegal phase transition from Failed to Running: kube-rbac-proxy, node-exporte (prometheus), calico, kops controller)

Any hint where to check would be highly appreciated!

Many thanks for your time!

**Comment by neolit123** [comment]
> Any hint where to check would be highly appreciated!

hi, i the occasional failures that you are seeing could be AWS related.
hard to tell, and i don't think this problem can be easily reproduced by the core kubernetes maintainers.

we try to close similar tickets until there is more proof that this is an actual problem in core.
if you confirm that please re-open it.

also note that 1.16 is out of support so you must provide the proof for a failing 1.17+ cluster.

thanks
/close

**Comment by neolit123** [comment]
you also try asking at the support channels here:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

to see if someone using kops /aws has seen this.
