### ISSUE TITLE
[Flaky Test] [k8s.io] ResourceMetricsAPI [NodeFeature:ResourceMetrics] when querying /resource/metrics should report resource usage through the resouce metrics api

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#94370]
**Which jobs are flaking**:

`node-kubelet-features-master (ci-kubernetes-node-kubelet-features)`

**Which test(s) are flaking**:

`[k8s.io] ResourceMetricsAPI [NodeFeature:ResourceMetrics] when querying /resource/metrics should report resource usage through the resouce metrics api`

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-informing#node-kubelet-features-master

**Reason for failure**:

```
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/resource_metrics_test.go:66
Timed out after 60.000s.
Expected
    <string>: KubeletMetrics
to match keys: {
."container_memory_working_set_bytes":
	unexpected element node-problem-detector-443::node-problem-detector-edba338b-6b0b-4006-ac7e-7ae9a8393284::node-problem-detector-edba338b-6b0b-4006-ac7e-7ae9a8393284
}

_output/local/go/src/k8s.io/kubernetes/test/e2e_node/resource_metrics_test.go:92
```

**Anything else we need to know**:

/cc @kubernetes/ci-signal @kubernetes/sig-node-bugs @bart0sh @dashpole @MHBauer 
/sig node
/priority important-soon
/milestone v1.20

Looks like this _might_ be related to https://github.com/kubernetes/kubernetes/issues/94103

**Comment by MHBauer** [comment]
looks like my fault, whoops. https://github.com/kubernetes/kubernetes/pull/93868 
/assign
As far as I can tell the test is sensitive to the environment it runs in. I'll try to make it match less, and if that doesn't work it may need to become serial.

**Comment by MHBauer** [comment]
attempt based on my understanding, https://github.com/kubernetes/kubernetes/pull/94373
