### ISSUE TITLE
test/integration/scheduler_perf: check for unused template parameters

### ISSUE THREAD

**Issue by adtac** [kubernetes/kubernetes#94404]
Note: this issue should be viewed in the context of #93252.

If this happens, this is very likely a typo where someone used a parameter in a way they didn't mean to (for example, `CreateNodes: $initPods`).

/sig scheduling
/assign

**Comment by rajpratyush** [comment]
@adtac Hi this is my first time contributing to kubernetes. can you provide me some guidance on how to to get started?

**Comment by henrjan** [comment]
Hi, is this issue still valid to work on?

**Comment by adtac** [comment]
@henrjan yes, this is still valid.

@rajpratyush I recommend starting with the [contributor's guide](https://www.kubernetes.dev/docs/guide/) and reading from there.

**Comment by almas33** [comment]
@henrjan are you still working on this issue or should I work on it.

**Comment by pravarag** [comment]
@almas33 I would like to work on this issue if you haven't started already.

**Comment by nicomitchell** [comment]
@pravarag @almas33 would it be ok if I took a look at this?

**Comment by vaibhav2107** [comment]
Hi @adtac
Can you help me in why its not assigning the values to createNodes and createPods directly and using the opcode and countParam in performance-config.yaml.

**Comment by adtac** [comment]
@vaibhav2107 We use a `opcode` field to differentiate between different operations. The value of the `opcode` field (e.g. "createNodes") determines the operation. The `countParam` field defines the number of pods/nodes to create. What do you mean by "assigning the values to createNodes and createPods directly"?

**Comment by vaibhav2107** [comment]
@adtac Thanks for the information. 
By assigning, I just meant that whether we can assign createNodes directly like ( createNodes: $initNodes ).

**Comment by nicomitchell** [comment]
@vaibhav2107 I don't think that's possible since there can potentially be other parameters besides the countParam. For example: 
```go
- opcode: createPods
    countParam: $initPods
    persistentVolumeTemplatePath: config/pv-aws.yaml
    persistentVolumeClaimTemplatePath: config/pvc.yaml
```

Different operations could potentially have different parameters.

**Comment by adtac** [comment]
@vaibhav2107 createNodes and createPods aren't the only operations. Other operations (e.g. churn and barrier), including future ones, may not fit that format. It's also easier to parse and more explicit this way.

**Comment by vaibhav2107** [comment]
Thanks @adtac , @nicomitchell 
Having a doubt more, in performance-config.yaml under the name:SchedulingPodAntiAffinity,
![values](https://user-images.githubusercontent.com/79974025/115578268-c4067c00-a2e2-11eb-8e14-a129b9d91046.png)

why are we giving the same values in 5000Nodes as given in 500Nodes, or this is an error.

**Comment by adtac** [comment]
that sounds like a typo indeed

**Comment by sanposhiho** [comment]
Hello @vaibhav2107 
Are you still going to work on this issue?

**Comment by SahilPatidar** [comment]
hey! I am beginner and I interested in scheduling and I know basics of scheduling , so how can I start to contribute on this issue.

**Comment by sanposhiho** [comment]
@SahilPatidar Sorry, PR for this issue has already created. https://github.com/kubernetes/kubernetes/pull/104716
