### ISSUE TITLE
Limit privileged access for CSI driver

### ISSUE THREAD

**Issue by saiteja313** [kubernetes/kubernetes#94400]
**What would you like to be added**:
- Limit `securityContext.privileged` access for CSI drivers pods [1]
- For example: EFS CSI driver requires Privileged access due to `spec.template.spec.containers[0].volumeMounts.mountPropagation` property set to value `Bidirectional`.
- `Bidirectional` is needed  to allow Kubelet on the host to see mounts created by the CSI driver container. Documentation from CSI driver page [1]

---

- *The node plugin needs direct access to the host for making block devices and/or filesystem mounts available to the Kubernetes kubelet.*
- *The mount point used by the CSI driver must be set to Bidirectional to allow Kubelet on the host to see mounts created by the CSI driver container. See the example below:*
---

**Why is this needed**:
- Due to organization security policies, pods should not run with privileged access on the cluster.

#### References
[1] https://kubernetes-csi.github.io/docs/deploying.html#driver-volume-mounts

**Comment by pacoxu** [comment]
According to https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation

> Caution: Bidirectional mount propagation can be dangerous. It can damage the host operating system and therefore it is allowed only in privileged Containers. Familiarity with Linux kernel behavior is strongly recommended. In addition, any volume mounts created by Containers in Pods must be destroyed (unmounted) by the Containers on termination.

Another choice for you is running csi driver on the host directly.

**Comment by themish95** [comment]
Is there any update on this?
