### ISSUE TITLE
Does this repo have a branching and release policy

### ISSUE THREAD

**Issue by reselbobasg** [kubernetes/kubernetes#94402]
I am doing an article on branching and release policies for the most popular open-source projects. To say Kubernetes is not popular is an extreme understatement.

Thus, I ask, do you have have a branching and release policy/pattern that I can read? Or is it a matter of convention and tribal knowledge? If so, what is the policy/pattern?

Thanks  in advance,
Bob Reselman

**Comment by neolit123** [comment]
hi, we try to use this tracker for bugs/features.

this is more suited as a discussion for the kubernetes-dev mailing list:
https://groups.google.com/g/kubernetes-dev/

thanks
/close
