### ISSUE TITLE
int fields should probably not set omitempty

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#9441]
In v1beta3, ReplicationControllerSpec.Replicas is defined as:

```
Replicas int `json:"replicas,omitempty" description:"number of replicas desired"`
```

In v1, it is:

```
Replicas *int `json:"replicas,omitempty" description:"number of replicas desired; defaults to 1"`
```

omitempty means a value of 0 will not be serialized in v1beta3 (see http://play.golang.org/p/INjWh33QnH).

Removing a user-set value of 0 when building v1beta3 API responses, and treating the absence of that value as a different default in the next version of the API is surprising. The conversions handle the cases correctly, but I would expect this to trip up users.

**Comment by bgrant0607** [comment]
Ref #8190
