### ISSUE TITLE
Add standardised way for infra components to reach API server

### ISSUE THREAD

**Issue by fasaxc** [kubernetes/kubernetes#94419]
**What would you like to be added**:

Some way for "infrastructure" pods (such as networking providers) to get the underlying connection details for the API server (as used by kubelet and kube-proxy to talk directly to the API server for bootstrapping).

**Why is this needed**:

For components such as networking providers (e.g. Calico, which I work on) it's useful to be able to reach the API server even when 

* `kube-proxy` is down.
* Before kube-proxy starts (we often get bug reports to Calico that turn out to be kube-proxy not being up yet).
* When the networking provider is providing kube-proxy function and kube-proxy is completely disabled.

Unfortunately, there's no standardised way of getting that information; the various installers all take a different (snowflake) approach to configuring `kubelet` and `kube-proxy`

This could take the form of an option on the pod:
```
spec:
  apiAccessMode: ClusterIP|Direct
```
and then kubelet could provision the in-cluster kubeconfig appropriately.

Or, it could be something that's exposed to all pods so that the API client can have an option `TryDirect: true` 

Our current solution for when we're providing kube-proxy functionality is to ask the user to configure a config map with the information.  However, that's not great since finding the right host/port is error prone.  Some users try to use the cluster IP by mistake, some use the current IP of the API server when they should use its DN, etc...

**Comment by krmayankk** [comment]
i am not sure if this belongs to sig-apps, adding sig-network , they may have some insight
/sig-network
