### ISSUE TITLE
kubelet‘s goroutinues was blocked and a memory leak occurred.

### ISSUE THREAD

**Issue by yangcheng-icbc** [kubernetes/kubernetes#94415]
**What happened**:
**What you expected to happen**:
 When cadvisor failed to pull meccis information, the goroutinue of kubelet was blocked and a memory leak occurred.
**How to reproduce it (as minimally and precisely as possible)**:
No specific method has been found
**Anything else we need to [know?**:]
memory leak occurred in 
**Environment**:
- Kubernetes version (use `kubectl version`):
kubelet version：1.5.6
- Cloud provider or hardware configuration:
huawei cloud 
- OS (e.g: `cat /etc/os-release`):
suse
- Kernel (e.g. `uname -a`):
4.44.103-6.38-default
- Install tools:
ansible
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
> kubelet version：1.5.6

hi, all versions < 1.17 are not supported.
please confirm if this happens with newer versions.

/sig node
/close

**Comment by wu0407** [comment]
this happen on 1.18 when docker socket is stuck

**Comment by wu0407** [comment]
containerd stucked when runc is block, so docker stucked too. 
https://github.com/opencontainers/runc/issues/2828
