### ISSUE TITLE
'kubectl descirbe node' shows preempting pods and their requested resources

### ISSUE THREAD

**Issue by hex108** [kubernetes/kubernetes#94411]
**What would you like to be added**:

`kubectl describe node XXX` shows preempting pods and their requested resources.

**Why is this needed**:

When [scheduler preemption](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#preemption) is enabled(it is enabled by default), there might be some preempting pods on nodes.

Suppose this case: a node's allocatable resource is <10 CPU, 20G>, and pod A (request is <2 CPU, 4 G>, proirity is 0) is running on it.  Then pod B( request is <9 CPU, 10 G>, priority is 5) comes, and it preempts pod A, then the node's resource is occupied by pod B from scheduler's perspective now. Before pod B is actually scheduled to the node(its `.spec.nodename` is set to this node), `kubectl describe node` only shows pod A, and does not show pod B. If there is another pod C( request is <3 CPU, 5 G>, priority is 5) coming, it will not be scheduled because there is no sufficient CPU, but it can be scheduled to the node according to the output of `kubectl describe node`, it is really confusing. It will make things clear if it shows preempting pods and their requested resources, we know that the resource is being occupied by pod B.

/sig cli

**Comment by Pingan2017** [comment]
the version of `kubectl ` u use is ?
