### ISSUE TITLE
 elasticsearch_logging_discovery.go:142] Found []

### ISSUE THREAD

**Issue by qq282485068** [kubernetes/kubernetes#94429]
**What happened:**
I download fluentd-elasticsearch in addons.  The following error occurs  then I use "kubectl apply -f es-statefulset.yaml  "
Then, i find the elasticsearch-logging pod restart lots of time, and keep status with CrashLoopBackOff.

[root@istackvip ~]# kubectl logs -f elasticsearch-logging-0 -n kube-system
+ export NODE_NAME=elasticsearch-logging-0
+ NODE_NAME=elasticsearch-logging-0
+ export NODE_MASTER=true
+ NODE_MASTER=true
+ export NODE_DATA=true
+ NODE_DATA=true
+ export HTTP_PORT=9200
+ HTTP_PORT=9200
+ export TRANSPORT_PORT=9300
+ TRANSPORT_PORT=9300
+ export MINIMUM_MASTER_NODES=2
+ MINIMUM_MASTER_NODES=2
+ chown -R elasticsearch:elasticsearch /data
+ ./bin/elasticsearch_logging_discovery
I0902 14:25:06.694669       9 elasticsearch_logging_discovery.go:85] Kubernetes Elasticsearch logging discovery
I0902 14:25:06.706965       9 elasticsearch_logging_discovery.go:142] Found []
I0902 14:25:16.710309       9 elasticsearch_logging_discovery.go:142] Found []
I0902 14:25:26.713044       9 elasticsearch_logging_discovery.go:142] Found []
I0902 14:25:36.715882       9 elasticsearch_logging_discovery.go:142] Found []
I0902 14:25:46.718867       9 elasticsearch_logging_discovery.go:142] Found []
I0902 14:25:56.721760       9 elasticsearch_logging_discovery.go:142] Found []

**Comment by neolit123** [comment]
unclear whether the addon is up to date and supported at this point.
/sig instrumentation

**Comment by brancz** [comment]
cc @coffeepac @serathius

**Comment by coffeepac** [comment]
/assign

I will take a look this week.

**Comment by DesistDaydream** [comment]
I have the same problem
k8s version:v1.18.8

**Comment by jsaguiar** [comment]
same

**Comment by coffeepac** [comment]
I've pushed a change to the stateful set that should unblock people as there was a 1.18 compatibility problem.

however, please make sure you are also creating the service via `kubectl apply -f es-service.yaml`, the discovery program finds the other elasticsearch nodes via service registration.

**Comment by coffeepac** [comment]
@qq282485068 @DesistDaydream @jsaguiar please feel free to re-open this issue if the latest version doesn't work for you.

**Comment by DesistDaydream** [comment]
> @qq282485068 @DesistDaydream @jsaguiar please feel free to re-open this issue if the latest version doesn't work for you.

Why was this PR added to v1.20?

**Comment by coffeepac** [comment]
@DesistDaydream probably because that is the next release.  most people who use this addon do so from master.  Do you need this packaged in some other way?
