### ISSUE TITLE
remove potential coredns mem overcommitment

### ISSUE THREAD

**Issue by rdxmb** [kubernetes/kubernetes#94434]
**What would you like to be added**:

Set the resource limits of coredns to the same size as the requests.

**Why is this needed**:

When initializing the kubernetes-cluster with kubeadm, the resource-request and -limit for coredns differs. That can cause to mem overcommitment and oom-killed pods in the cluster.

In my case:

syslog:
```
[...]
[Mon Jul 13 04:07:15 2020] Memory cgroup out of memory: Kill process 48615 (mongod) score 1954 or sacrifice child
[...]
```

```
kubectl describe node drei
[...]
  kube-system                   coredns-66bff467f8-fcx9g               100m (5%)     0 (0%)      70Mi (0%)        170Mi (1%)       57d
[...]
  memory             16518324992 (98%)  16623182592 (99%)
```

**Comment by neolit123** [comment]
hi, what is your kubeadm version?

for reference in 1.,19 (and older versions too):
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/addons/dns/manifests.go#L249-L254

```
        resources:
          limits:
            memory: 170Mi
          requests:
            cpu: 100m
            memory: 70Mi
```

> When initializing the kubernetes-cluster with kubeadm, the resource-request and -limit for coredns differs. That can cause to mem overcommitment and oom-killed pods in the cluster.

different limits / requests are common and cannot cause over commitment itself.
depending on the use case you can also patch the Deployment.

>   memory             16518324992 (98%)  16623182592 (99%)

do you have an explanation for the memory consumption here?

**Comment by rdxmb** [comment]
```
# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:39:11Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

> ```
>     resources:
>           limits:
>             memory: 170Mi
>           requests:
>             cpu: 100m
>             memory: 70Mi
> ```
same at my nodes.

> different limits / requests are common and cannot cause over commitment itself.
> do you have an explanation for the memory consumption here?

Oh, this is the summary, not coredns itself. Sorry.
`memory 16518324992 (98%) 16623182592 (99%)`

Coredns has
`kube-system                           coredns-66bff467f8-pzqxq                   100m (0%)     0 (0%)      70Mi (0%)        170Mi (0%)       68d`

When a node went into drain mode, pods were scheduled to other nodes and the memory consumtion limit can hit **over** 100%. This is why I want to have the memory requests and limits the same amount over all my pods.

**Comment by neolit123** [comment]
You could patch the coredns spec. Note that you have to do this after each
kubeadm upgrade because it is not preserved.

There are a lot prod clusters out there that use these values and don't
have the problem, or at least i have not seen reports about it.

**Comment by rdxmb** [comment]
> You could patch the coredns spec. Note that you have to do this after each
> kubeadm upgrade because it is not preserved.

ok ,thanks

> There are a lot prod clusters out there that use these values and don't
> have the problem, or at least i have not seen reports about it.

You mean the coredns values? Yes, I think without overcommitment and more RAM on the nodes than the summary of RAM-limits within the pods there is no problem ;)
