### ISSUE TITLE
Kube-schedular restarted many times

### ISSUE THREAD

**Issue by GauravAsthana1** [kubernetes/kubernetes#94467]
Kube-scheular is getting restarted contineously with following error. Can someone help please. 

kube-scheduler-sk8XXX01 1/1 Running 2 86d
kube-scheduler-sk8sXXX02 1/1 Running 241 2d12h
kube-scheduler-sk8sXXX03 1/1 Running 236 457d

LOG:-

I0825 17:18:57.662001 1 serving.go:318] Generated self-signed cert in-memory
W0825 17:18:58.548197 1 authentication.go:373] failed to read in-cluster kubeconfig for delegated authentication: failed to read token file “/var/run/secrets/kubernetes.io/serviceaccount/token”: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
W0825 17:18:58.548222 1 authentication.go:235] No authentication-kubeconfig provided in order to lookup client-ca-file in configmap/extension-apiserver-authentication in kube-system, so client certificate authentication won’t work.
W0825 17:18:58.548232 1 authentication.go:238] No authentication-kubeconfig provided in order to lookup requestheader-client-ca-file in configmap/extension-apiserver-authentication in kube-system, so request-header client certificate authentication won’t work.
W0825 17:18:58.548252 1 authorization.go:177] failed to read in-cluster kubeconfig for delegated authorization: failed to read token file “/var/run/secrets/kubernetes.io/serviceaccount/token”: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
W0825 17:18:58.548267 1 authorization.go:146] No authorization-kubeconfig provided, so SubjectAccessReview of authorization tokens won’t work.
I0825 17:18:58.552026 1 server.go:150] Version: v1.13.0
I0825 17:18:58.552075 1 defaults.go:210] TaintNodesByCondition is enabled, PodToleratesNodeTaints predicate is mandatory
W0825 17:18:58.553012 1 authorization.go:47] Authorization is disabled
W0825 17:18:58.553029 1 authentication.go:55] Authentication is disabled
I0825 17:18:58.553041 1 deprecated_insecure_serving.go:49] Serving healthz insecurely on 127.0.0.1:10251
I0825 17:18:58.553460 1 secure_serving.go:116] Serving securely on [::]:10259
I0825 17:18:59.454783 1 controller_utils.go:1027] Waiting for caches to sync for scheduler controller
I0825 17:18:59.558509 1 controller_utils.go:1034] Caches are synced for scheduler controller
I0825 17:18:59.558604 1 leaderelection.go:205] attempting to acquire leader lease kube-system/kube-scheduler…

**Comment by neolit123** [comment]
> I0825 17:18:58.552026 1 server.go:150] Version: v1.13.0

hi, 1.13 is no longer supported.
please try 1.17+ (if you can) to confirm if the problem still happens.

if so, reopen this ticket.

/close
/sig scheduling
