### ISSUE TITLE
Allow blocking unchunked requests to list pods

### ISSUE THREAD

**Issue by grosser** [kubernetes/kubernetes#94477]
We have lots of pods and requests to get all pods use lots of memory on the api-server ~150m atm.
It would be nice if we could block any client from doing a request without chunking (limit to 1k items per response) to improve api server availability.

/sig api-machinery

**Comment by fedebongio** [comment]
We had a short discussion over this one on the triage - the idea is not bad, but there is some risk of breaking something...
@lavalamp suspects @liggitt can have other thoughts. @cheftako mentioned opt in as a cluster owner.

**Comment by cheftako** [comment]
Clearly opting into a change like this has a significant chance of breaking the cluster. I wonder if that could be diminished my pairing this with priority and fairness. We could then block requests according to the priority level?

**Comment by liggitt** [comment]
@wojtek-t don't informers default to listing without chunking for some resources?

**Comment by MikeSpreitzer** [comment]
Here's a blast from the past: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/kubernetes-sig-api-machinery/SfCIk5MccOc

**Comment by MikeSpreitzer** [comment]
@liggitt : it is not simply a matter of resource type.  The code is a bit complicated, but the logic in https://github.com/kubernetes/client-go/blob/master/tools/cache/reflector.go and https://github.com/kubernetes/client-go/blob/master/tools/pager/pager.go does contemplate doing a full list in some circumstances.

So I do not think the apiservers should simply block unchunked (non-paginated) list operations.  It is more plausible to use API Priority and Fairness to put such requests in their own priority level.  We would want to think carefully about the concurrency shares for that priority level.

**Comment by wojtek-t** [comment]
> @wojtek-t don't informers default to listing without chunking for some resources?

@liggitt Yes and no :-)
They technically set the limit (reflector always sets it), but it is then ignored in watchache if RV="":
https://github.com/kubernetes/kubernetes/blob/02cf58102a61b6d1e021e256381ff750573ce55d/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go#L656

> So I do not think the apiservers should simply block unchunked (non-paginated) list operations. It is more plausible to use API Priority and Fairness to put such requests in their own priority level. We would want to think carefully about the concurrency shares for that priority level.

I agree with @MikeSpreitzer that we should NOT block unchunked list operations.
That said, I'm not convinced they really need their own priority level. In my opinion, we should simply introduce a concept of "cost" of a request, a LIST is obviously more expensive than GET of a single element.
I was thinking a little bit about that in the past, and I think it doesn't have to be super accurate, we may simply estimate it as `<limit> * <some constant>` (modulo the fact that limits are not respected with RV="", for which case we may estimate it as `<total number of objects of that type, for which we expose a metric so we can get this data relatively easily> * <some other smaller constant>`.

**Comment by grosser** [comment]
Cost sounds like a super neat extension to fairness and would encourage
users to request as little as possible :)

**Comment by MikeSpreitzer** [comment]
If we introduce a concept of cost into API Priority and Fairness, how would it fit in?

We have briefly discussed the idea of having the initial estimate of execution duration be a function of the request rather than a constant.  But that will not make a long-term difference; the errors in the initial estimates are corrected for once the actual execution durations are known.

**Comment by grosser** [comment]
Initially it would be a estimation, but the api-server could keep a record
of "list pods takes x" and then use that going forward

**Comment by wojtek-t** [comment]
> We have briefly discussed the idea of having the initial estimate of execution duration be a function of the request rather than a constant. But that will not make a long-term difference; the errors in the initial estimates are corrected for once the actual execution durations are known.

It would prevent us from accepting too much at the same time.
Imagine that your allowed concurrency is say 100 (it's what the infra can handle). So then we can accept 100 requests of "list all pods", which can actually significantly overload both etcd and kube-apiserver. I agree that eventually the initial estimated would be corrected, but that may already be too later for any corrections because by that time everything can already be down...

**Comment by MikeSpreitzer** [comment]
I think what I am hearing is the suggestion that the new issue is not about how long a request takes to execute but rather how big a bite out of the server's capacity a given request takes _while_ it is executing.  While a server may be able to run 100 GET requests concurrently, it can only run 20 LIST requests concurrently, as an example with made-up numbers.  So we would not manage against a fixed number of equal-width seats, but rather recognize that different requests have different "width" values, as well as "length" (execution duration).

**Comment by wojtek-t** [comment]
Yes - that's great summary of what I was trying to say - thanks Mike!

**Comment by MikeSpreitzer** [comment]
So I think we could approach the original issue with two enhancements to API Priority and Fairness:
1. Add the concept of request "width".  In particular, I suggest that each FlowSchema specify a request width.
2. Give FlowSchemas the ability to discriminate on the ResourceVersion and chunk size, if any, in the request's query parameters.

I considered letting FlowSchemas discriminate on quer parameters in general, and decided against it for the following reasons.
- Some, such as field selectors on `metadata.name`, are already interpreted so adding the general case would be mixing levels of abstraction.
- I expect someone will worry that field or label selectors could contain customer confidential information and so we should go nowhere near them (I do not find this one very convincing; the _ability_ to discriminate on something does not _require_ any particular one to do it).

**Comment by lavalamp** [comment]
I'd like to start with an internal (i.e. coded) estimation of width before we modify the API. In particular just letting the flow schema state a constant won't be enough, since paginated lists should have their width vary based on how big of a page they requested.

**Comment by wojtek-t** [comment]
> I'd like to start with an internal (i.e. coded) estimation of width before we modify the API.

+1 - let's have this ability in a coded way and prove that will prove us what exactly is useful to expose.

> In particular just letting the flow schema state a constant won't be enough, since paginated lists should have their width vary based on how big of a page they requested.

[Modulo the fact that listing from watchcache (with RV=0) ignores pagination. Which makes that even more tricky.]
But yes - constant doesn't seem to be enough.

So I fully agree with Daniel - let's incorporate something in an "non-exposed" way first and then we can think how to expose it in a reasonable way to users.
