### ISSUE TITLE
Remove alpha support for Hyper-v on Docker for Windows

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes/kubernetes#94490]
**What happened**:
Hyper-v support was added as an [experimental feature via annotations](https://github.com/kubernetes/kubernetes/pull/58751) for docker.  Hyper-v support is now focused on Containerd because of better support of HCSv2 in Containerd (for example allows for multiple containers in a pod in hyper-v).

There is still annotation support that should be removed in all the various locations:

https://github.com/kubernetes/kubernetes/blob/9d9d305017d688526e179cee6af8791716c330df/pkg/kubelet/apis/well_known_annotations_windows.go#L36

**What you expected to happen**:
hyper-v support for docker will not go past alpha so the annotations should be depreciated following the guidelines at https://kubernetes.io/docs/reference/using-api/deprecation-policy/

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Windows
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig windows

**Comment by wawa0210** [comment]
I can try to contribute to solve this issue

/assign

**Comment by wawa0210** [comment]
Do we need to discuss whether we confirm that we need to remove this feature in the kubernetes code? If it is removed, it will not support running hyper-v-based windows container through docker.

**Comment by jsturtevant** [comment]
We can add it to the agenda for sig-windows next week to confirm.  There is no path forward for hyper-v containers with docker so it should be ok to remove via standard depreciation mechanisms.

We have been working to get hyper-v working via containerd (still work in progress) and have tests passes: https://testgrid.k8s.io/sig-windows-containerd#aks-engine-azure-windows-master-containerd-hyperv

**Comment by wawa0210** [comment]
I submitted a simple pr for this issue, we can follow up the results of the discussion next week for further operations

**Comment by wawa0210** [comment]
> @neolit123 What is the process for announcing and removing an experimental annotation? I read through https://kubernetes.io/docs/reference/using-api/deprecation-policy/ but it mostly refers to api changes.

I also read this document and found that there is a short description related to this issue

https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-a-feature-or-behavior

I am confused about this point. It seems that the feature of hyper-v can be removed (because it has been in aplha, experimental feature), I don’t know if my understanding is correct.

**Comment by neolit123** [comment]
alpha feature gates can be removed without a deprecation period in release N+1 if added in release N - i.e. it could have been removed in 1.11 as per the minimum policy.
this is the recommended minimum and exceptions can happen...the feature existed for 10 releases and Windows containers support existed for a few releases as well, which means you could have production clusters using the feature.

my recommendation would be to announce this as deprecated in 1.20 and remove in 1.21.
PRs with release-notes prefixed with "action required: ..." would end up on top of the release change logs to alert users.

ideally sig-windows should decide on the timing.
cc @feiskyer @benmoss @ddebroy

**Comment by feiskyer** [comment]
> my recommendation would be to announce this as deprecated in 1.20 and remove in 1.21.

+1. Could we add a warning log and an announcement in v1.20 and then remove it in v1.21?

**Comment by wawa0210** [comment]
If sig-windows has the latest discussion results, please let me know and I can try to follow up this issue

**Comment by jsturtevant** [comment]
We [discussed this at sig-windows](https://www.youtube.com/watch?v=hW4BkgAqdtk&list=PL69nYSiGNLP2OH9InCcNkWNu2bl-gmIU4&index=5) and agree should be a log warning for depreciation in 1.20 and remove support in v1.21. 

@wawa0210 can you update the PR to log the warning and add the appropriate release note?

**Comment by wawa0210** [comment]
> @wawa0210 can you update the PR to log the warning and add the appropriate release note?

https://github.com/kubernetes/kubernetes/pull/95505

i open a new pr for log warning message for this issue

**Comment by jsturtevant** [comment]
This should stay open as a tracking issue untill the feature is removed in 1.21

/open
