### ISSUE TITLE
Flakey test NodeProblemDetector SystemLogMonitor should generate node condition and events for corresponding error

### ISSUE THREAD

**Issue by MHBauer** [kubernetes/kubernetes#94493]
Is this a valid test? My understanding is we cannot rely on events for programming against.

https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=should%20generate%20node%20condition%20and%20events%20for%20corresponding%20errors

**Which jobs are flaking**:
ci-cri-containerd-node-e2e-features
ci-kubernetes-node-kubelet-features
among others, mainly 'node-e2e-features' based tests.

**Which test(s) are flaking**:
https://github.com/kubernetes/kubernetes/blob/9d9d305017d688526e179cee6af8791716c330df/test/e2e_node/node_problem_detector_linux.go#L247

**Testgrid link**:
https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-features-master
https://testgrid.k8s.io/sig-node-containerd#node-e2e-features

**Reason for failure**:
expected total number of events was 4, actual events counted was 7

**Anything else we need to know**:
https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=should%20generate%20node%20condition%20and%20events%20for%20corresponding%20errors

**_It doesn't fail in a specific environment, should this test be running at all outside of this job?_**
https://testgrid.k8s.io/sig-node-node-problem-detector#ci-npd-e2e-node

The comments inside the test aren't very helpful for understanding why we're checking what we're checking.

**Comment by MHBauer** [comment]
I heard this is blocking you.
/sig node
/cc @mikebrow @dims

**Comment by MHBauer** [comment]
I see flakes going back at least a month https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cri-containerd-node-e2e-features/1290239646151741444

In addition to an earlier issue clarifying the error message https://github.com/kubernetes/kubernetes/issues/92907

This might be a spurious match, https://github.com/kubernetes/kubernetes/issues/78186

**Comment by mikebrow** [comment]
NodeProblemDetector is broken on nearly every run: https://github.com/containerd/cri/pull/1562

**Comment by MHBauer** [comment]
Maybe they should be marked [serial] or [disruptive]?

**Comment by MHBauer** [comment]
We can mark it `[Flaky]` and move it to the flake job, but I fear it will work fine over there.

**Comment by MHBauer** [comment]
Edit in upstream issue says "needs to be marked serial" https://github.com/kubernetes/node-problem-detector/issues/467#issuecomment-698660424

I'll make a PR
