### ISSUE TITLE
CustomResourceDefinition should support OpenAPI 3.1.0 (now including "patternProperties")

### ISSUE THREAD

**Issue by patricekrakow** [kubernetes/kubernetes#94519]
**What would you like to be added**:
I would like to use "patternProperties" within `spec.validation.openAPIV3Schema` when defining a CustomResourceDefinition.
I have understood that "patternProperties" is now supported in the latest version of OpenAIP 3.1.0, see https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#schemaObject

**Why is this needed**:
My use case is to define an "API" custom resource that will allow to store OpenAPI documents within Kubernetes. And the JSON schema defining OpenAPI itself does use "patternProperties", see
* https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v2.0/schema.json
* https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.yaml

**Comment by patricekrakow** [comment]
* /sig api-machinery

**Comment by patricekrakow** [comment]
Just find out that I have a workaround by using `additionalProperties` instead of `patternProperties`. It's just that I will not be able to use <https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.yaml> (for instance) as such, but that I will have to first edit it. Less convenient, but not impossible.
Anyway, I think it would still be nice to upgrade to OAS 3.1.0, but it's less urgent for me.

**Comment by sttts** [comment]
patternProperties allow the definition of schemas depending on field names. For my understanding this is an anti-pattern for Kube APIs because we aim at having complete and static knowledge of fields and of map keys.

With this feature one could e.g. define restrictions on labels, e.g. on `.*\.example.com/.*` versus all other map keys:
```
labels:
  foo.example.com/bla: abc
  bar.example.com/bla: def
  something.else.com/bla: some-non-conformant-value
```

Do we want that rather than enforcing the schema on `foo.example.com/bla` and `bar.example.com/bla` ?

**Comment by rajatjindal** [comment]
I think (based on my limited understanding of how kube api works internally), it should be allowed to restrict keys that matches a regex. 

the workaround people use today is additionalProperties and with that there is a good chance that invalid keys pass the validation and cause other issues that would show up only in controller logs while such issue should essentially show up at creation/update time.

another idea I was thinking was to have ability to pass in a custom function to validate the schema? e.g. I had this scenario where based on the value of a field in CRD, the validation mechanism differs for the other field within the same CRD.
