### ISSUE TITLE
[Failing Test] bazel-test-master (periodic-kubernetes-bazel-test-master)

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#94528]
**Which jobs are failing**:

`bazel-test-master (periodic-kubernetes-bazel-test-master)`

**Which test(s) are failing**:

```
//cmd/kube-scheduler/app/go_default_test:run_1_of_3
//cmd/kube-scheduler/app/go_default_test:run_3_of_3
//pkg/util/iptables/go_default_test:run_2_of_3
//cmd/kube-scheduler/app/go_default_test:run_2_of_3
...
```

**Since when has it been failing**:

```
09-04-20 01:03 CDT
```

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-blocking#bazel-test-master

**Reason for failure**:

Errors differ between each of the failing tests. Looks like failure started between `26d0f8460` and `fe8aa6eba`.

**Anything else we need to know**:

/cc @kubernetes/ci-signal 
/priority critical-urgent
/milestone v1.20

**Comment by liggitt** [comment]
Almost certainly https://github.com/kubernetes/kubernetes/pull/93605, which means we have remaining unit test flakes

**Comment by liggitt** [comment]
Looks like three primary packages are flaking:
- cmd/kube-scheduler/app
- pkg/probe/http
- k8s.io/apiserver/pkg/server/filters

**Comment by knight42** [comment]
I would like to help. I am investigating `TestClientReceivedGOAWAY` and `TestGOAWAYConcurrency` now.

**Comment by liggitt** [comment]
thanks, I've got TestHTTPProbeProxy

**Comment by knight42** [comment]
@liggitt `TestGOAWAYConcurrency` seems to be a bit different. 

> TestGOAWAYConcurrency tests GOAWAY frame will not affect concurrency requests in a single http client instance

This test is meant to use a single http client with http/2 transport, but as per the log:
```
==================
WARNING: DATA RACE
Write at 0x00c0007ad650 by goroutine 166:
  net/http.(*readTrackingBody).Read()
      GOROOT/src/net/http/transport.go:620 +0x44
  k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*clientStream).writeRequestBody()
      vendor/golang.org/x/net/http2/transport.go:1308 +0x761
  k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Transport).getBodyWriterState.func1()
      vendor/golang.org/x/net/http2/transport.go:2584 +0x13d

Previous read at 0x00c0007ad650 by goroutine 114:
  net/http.rewindBody()
      GOROOT/src/net/http/transport.go:642 +0xc9
  net/http.(*Transport).roundTrip()
      GOROOT/src/net/http/transport.go:605 +0xbe6
  net/http.(*Transport).RoundTrip()
      GOROOT/src/net/http/roundtrip.go:17 +0x46
  net/http.send()
      GOROOT/src/net/http/client.go:252 +0x6da
  net/http.(*Client).send()
      GOROOT/src/net/http/client.go:176 +0x1d5
  net/http.(*Client).do()
      GOROOT/src/net/http/client.go:718 +0x2d7
  net/http.(*Client).Do()
      GOROOT/src/net/http/client.go:586 +0x390
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.requestGOAWAYServer()
      staging/src/k8s.io/apiserver/pkg/server/filters/goaway_test.go:240 +0x37a
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.TestGOAWAYConcurrency.func1()
      staging/src/k8s.io/apiserver/pkg/server/filters/goaway_test.go:486 +0x132

Goroutine 166 (running) created at:
  k8s.io/kubernetes/vendor/golang.org/x/net/http2.bodyWriterState.scheduleBodyWrite()
      vendor/golang.org/x/net/http2/transport.go:2631 +0x12d
  k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*ClientConn).roundTrip()
      vendor/golang.org/x/net/http2/transport.go:1104 +0x913
  k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Transport).RoundTripOpt()
      vendor/golang.org/x/net/http2/transport.go:469 +0x276
  k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Transport).RoundTrip()
      vendor/golang.org/x/net/http2/transport.go:430 +0x4b
  net/http.(*Transport).roundTrip()
      GOROOT/src/net/http/transport.go:580 +0xb43
  net/http.(*Transport).RoundTrip()
      GOROOT/src/net/http/roundtrip.go:17 +0x46
  net/http.send()
      GOROOT/src/net/http/client.go:252 +0x6da
  net/http.(*Client).send()
      GOROOT/src/net/http/client.go:176 +0x1d5
  net/http.(*Client).do()
      GOROOT/src/net/http/client.go:718 +0x2d7
  net/http.(*Client).Do()
      GOROOT/src/net/http/client.go:586 +0x390
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.requestGOAWAYServer()
      staging/src/k8s.io/apiserver/pkg/server/filters/goaway_test.go:240 +0x37a
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.TestGOAWAYConcurrency.func1()
      staging/src/k8s.io/apiserver/pkg/server/filters/goaway_test.go:486 +0x132

Goroutine 114 (running) created at:
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.TestGOAWAYConcurrency()
      staging/src/k8s.io/apiserver/pkg/server/filters/goaway_test.go:477 +0x552
  testing.tRunner()
      GOROOT/src/testing/testing.go:1108 +0x202
==================
```
The client instance is not concurrency safe. I am not sure how to deal with this one.

**Comment by liggitt** [comment]
TestGOAWAYConcurrency seems fundamentally broken. This fails reproducibly for me:

```
go test -race k8s.io/apiserver/pkg/server/filters -run TestGOAWAYConcurrency -v
```

To mitigate, I will skip the test and open a critical issue for api-machinery to fix the test or the component

**Comment by knight42** [comment]
working on `pkg/util/iptables`

**Comment by knight42** [comment]
working on `k8s.io/legacy-cloud-providers/azure/cache`

**Comment by knight42** [comment]
filed #94570 to address this issue.

**Comment by zhouya0** [comment]
Can I try to work on  k8s.io/legacy-cloud-providers/vsphere ?

**Comment by knight42** [comment]
@zhouya0 please feel free to take it

**Comment by zhouya0** [comment]
But soon I found the race condition in `k8s.io/legacy-cloud-providers/vsphere`  relates to `runtime.SetFinalizer` and a little bit hard for me. I'll  leave this to others :(

**Comment by JornShen** [comment]
> working on `k8s.io/legacy-cloud-providers/azure/cache`

I find  and fix the problem of https://github.com/kubernetes/kubernetes/issues/94528#issuecomment-688156967 with https://github.com/kubernetes/kubernetes/pull/94676 yesterday. Maybe can deal with the problem. :)

**Comment by liggitt** [comment]
It looks like the 7 unresolved items in https://github.com/kubernetes/kubernetes/issues/94528#issuecomment-687208028 are the remaining issues with this job (the negative query at the bottom of that comment shows clean runs otherwise). I grouped them by sig. I think the next steps are:

1. Make sure there are open issues for each flake, assigned to the right SIG
2. Make sure those SIGs owners know they have reproducibly flaky unit test issues open and there are people assigned to those issues and actively working on them (in preference to 1.20 feature work)

**Comment by wojtek-t** [comment]
I marked cacher one as fixed - please reopen/ping me if this happens again.

**Comment by deads2k** [comment]
@rphillips can you have a look at the sig-node failure in https://github.com/kubernetes/kubernetes/issues/94528#issuecomment-687208028 ?

**Comment by rphillips** [comment]
@liggitt https://github.com/kubernetes/kubernetes/pull/96048

For the TestDevicePluginReRegistrationProbeMode test.

**Comment by spiffxp** [comment]
Does this still warrant `priority/critical-urgent`?

![Screen Shot 2020-11-20 at 5 45 47 PM](https://user-images.githubusercontent.com/49258/99856994-3b7b8800-2b58-11eb-8a80-d02cb576724e.png)

/remove-kind failing-test
/kind flake
This job is not continuously failing. It is occasionally flaking. I would suggest opening issues for the specific tests that are still hotspots mentioned by @liggitt in https://github.com/kubernetes/kubernetes/issues/94528#issuecomment-715454258 and then closing this out

**Comment by liggitt** [comment]
bazel job is removed, I opened individual issues for the remaining flakes I saw referenced from here and added to the 1.21 milestone

/close
