### ISSUE TITLE
Node flapping between Ready/NotReady with PLEG issues

### ISSUE THREAD

**Issue by nandeeshb09** [kubernetes/kubernetes#94525]
We are observing this issue all of sudden, here we have recently upgraded EKS cluster from 1.13 to 1.14.
post upgrade we are facing this issue, please help us here, what could be the issue.

When the node goes into NotReady status, kubelet is being restart and when we checked the kubelet logs found below errors.

Sep 04 09:23:20 kubelet[7981]: W0904 09:23:20.847245    7981 cni.go:309] CNI failed to retrieve network namespace path: Error: No such container: 0926ffb232ec02bdfe0855b09eb048e62d1c87db60605b72add262cd70633b28
Sep 04 09:23:20 kubelet[7981]: {"level":"info","ts":"2020-09-04T09:23:20.903Z","caller":"/usr/local/go/src/runtime/proc.go:203","msg":"CNI Plugin version: v1.6.2 ..."}
Sep 04 09:23:23 kubelet[7981]: I0904 09:23:23.844040    7981 kubelet.go:1830] skipping pod synchronization - [container runtime status check may not have completed yet., PLEG is not healthy: pleg was last seen active 6m56.630443527s ago; threshold is 3m0s.]
Sep 04 09:23:28 kubelet[7981]: I0904 09:23:28.844189    7981 kubelet.go:1830] skipping pod synchronization - [container runtime status check may not have completed yet., PLEG is not healthy: pleg was last seen active 7m1.630593033s ago; threshold is 3m0s.]
Sep 04 09:23:33 kubelet[7981]: I0904 09:23:33.844340    7981 kubelet.go:1830] skipping pod synchronization - [container runtime status check may not have completed yet., PLEG is not healthy: pleg was last seen active 7m6.630742624s ago; threshold is 3m0s.]

The versions which we are using:
EKS version : 1.14
AWS CNI network: 1.6.2
Docker version: 
Client:
 Version:           19.03.6-ce
 API version:       1.40
 Go version:        go1.13.4
 Git commit:        369ce74
 Built:             Fri May 29 04:01:26 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.4
  Git commit:       369ce74
  Built:            Fri May 29 04:01:57 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.2
  GitCommit:        ff48f57fc83a8c44cf4ad5d672424a98ba37ded6
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

And when the Node goes into NotReady status, pod will stuck in container creating and until the kubelet restarts.
Docker is not being restarted during this issue and below are the logs from docker.
Sep 04 07:50:39  dockerd[17172]: time="2020-09-04T07:50:39.322387228Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Sep 04 07:50:40 dockerd[17172]: time="2020-09-04T07:50:40.398870475Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Sep 04 07:50:41  dockerd[17172]: time="2020-09-04T07:50:41.498569937Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Sep 04 08:03:06 dockerd[17172]: time="2020-09-04T08:03:06.628859201Z" level=error msg="Handler for GET /v1.38/containers/61e17d1099d69c7d0acd10b705d8a88343d69305894a881a5b18b7cfd4395127/json returned error: write unix /var/run/docker.sock->@: write: broken pipe"
Sep 04 08:03:06  dockerd[17172]: http: superfluous response.WriteHeader call from github.com/docker/docker/api/server/httputils.WriteJSON (httputils_write_json.go:11)
Sep 04 08:03:06 dockerd[17172]: time="2020-09-04T08:03:06.648785703Z" level=error msg="Handler for GET /v1.38/containers/0c220dfd0bbb17323658ce0ff8d11fb39063524146c0e83281c5a58cd0e924af/json returned error: write unix /var/run/docker.sock->@: write: broken pipe"
Sep 04 08:03:06 dockerd[17172]: http: superfluous response.WriteHeader call from github.com/docker/docker/api/server/httputils.WriteJSON (httputils_write_json.go:11)
Sep 04 08:32:57  dockerd[17172]: time="2020-09-04T08:32:57.845276980Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Sep 04 08:40:10  dockerd[17172]: http: superfluous response.WriteHeader call from github.com/docker/docker/api/server/httputils.WriteJSON (httputils_write_json.go:11)
Sep 04 08:40:10  dockerd[17172]: http: superfluous response.WriteHeader call from github.com/docker/docker/api/server/httputils.WriteJSON (httputils_write_json.go:

It would be great , if you could help us here.

**Comment by vsxen** [comment]
Too many open file？
The Dockerd seems had some questions。

**Comment by nandeeshb09** [comment]
@vsxen  is it because of more number of open files?.
