### ISSUE TITLE
kube-apiserver (and other official images) for arm64 contain /go-runner built for amd64

### ISSUE THREAD

**Issue by smira** [kubernetes/kubernetes#94540]
**What happened**:

Image: `k8s.gcr.io/kube-apiserver-arm64:v1.19.0`

kube-apiserver fails to start on arm64 with command line like: `/go-runner /usr/local/bin/kube-apiserver ....` with an error:

```
2020-09-04T18:18:52.840446862Z stderr F standard_init_linux.go:211: exec user process caused "exec format error"
```

`kube-apiserver` binary is built for arm64, while `go-runner` is built for amd64.

**What you expected to happen**:

kube-apiserver running normally, `go-runner` built for arm64

**How to reproduce it (as minimally and precisely as possible)**:

Extract contents of `k8s.gcr.io/kube-apiserver-arm64:v1.19.0` and check the executable architecture:

```
 $ file ./usr/local/bin/kube-apiserver
usr/local/bin/kube-apiserver: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, stripped
 $  file ./go-runner
go-runner: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
```

**Anything else we need to know?**:

**Environment**: n/a
- Kubernetes version (use `kubectl version`): 1.19.0
- Cloud provider or hardware configuration: n/a
- OS (e.g: `cat /etc/os-release`): Talos
- Kernel (e.g. `uname -a`):
- Install tools: Talos/bootkube
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
cc @justaugustus

**Comment by justaugustus** [comment]
@smira -- thanks for the report!
I'll take a look.

/assign

**Comment by justaugustus** [comment]
Proposed fix in https://github.com/kubernetes/kubernetes/pull/94552.

**Comment by justaugustus** [comment]
FYI @kubernetes/release-engineering

**Comment by justaugustus** [comment]
Closing this now that [v1.19.1](https://groups.google.com/g/kubernetes-announce/c/1WdgO7uvXjM) has been released, which includes the [backport](https://github.com/kubernetes/kubernetes/pull/94613).

/close
