### ISSUE TITLE
[Failing Test] bazel-test-1.17 (periodic-kubernetes-bazel-test-1-17)

### ISSUE THREAD

**Issue by tpepper** [kubernetes/kubernetes#94548]
**Which jobs are failing**:
1.17 release blocking bazel test

**Which test(s) are failing**:
 * //cluster/images/conformance/go-runner:go_default_test
 * Overall
 * //pkg/kubelet/oom:go_default_test

**Since when has it been failing**:
Steady red since 2020-08-26

**Testgrid link**:
https://testgrid.k8s.io/sig-release-1.17-blocking#bazel-test-1.17

**Reason for failure**:
FAIL: //cluster/images/conformance/go-runner:go_default_test (see /bazel-scratch/.cache/bazel/_bazel_root/7989b31489f31aee54f32688da2f0120/execroot/io_k8s_kubernetes/bazel-out/k8-fastbuild/testlogs/cluster/images/conformance/go-runner/go_default_test/test_attempts/attempt_1.log)
FAIL: //cluster/images/conformance/go-runner:go_default_test (see /bazel-scratch/.cache/bazel/_bazel_root/7989b31489f31aee54f32688da2f0120/execroot/io_k8s_kubernetes/bazel-out/k8-fastbuild/testlogs/cluster/images/conformance/go-runner/go_default_test/test_attempts/attempt_2.log)
FAIL: //cluster/images/conformance/go-runner:go_default_test (see /bazel-scratch/.cache/bazel/_bazel_root/7989b31489f31aee54f32688da2f0120/execroot/io_k8s_kubernetes/bazel-out/k8-fastbuild/testlogs/cluster/images/conformance/go-runner/go_default_test/test.log)

**Anything else we need to know**:
Went steady red at a point where there were no k/k and no test-infra changes.

**Comment by liggitt** [comment]
Should be green again. https://github.com/kubernetes/kubernetes/pull/94326 removed the oom test (pick from master)

**Comment by liggitt** [comment]
Job is solidly green again
