### ISSUE TITLE
When kubelet triggers poststart or prestop, httpget is executed by kubelet process

### ISSUE THREAD

**Issue by Cweiping** [kubernetes/kubernetes#94558]
**What happened**:

When kubelet triggers `PostStart` or `PreStop`, `httpGet` action is executed by kubelet process.

**What you expected to happen**:

This behavior should be run within the container as expected and may become a security risk.

**How to reproduce it (as minimally and precisely as possible)**:
https://github.com/kubernetes/website/issues/23670#issuecomment-686412705

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
/kind bug

**Comment by liggitt** [comment]
This is currently working as designed, so it's not clear this is a bug.

**Comment by bryanchang15** [comment]
@liggitt Just to give an idea, I think the context of http health checks is totally different with the context of http hooks, though they looks similar at first time.

In http health checks, kubelet would only call a method that is exposed by the target container (if not, we can add constraints in the implementation level) and this is safe in some ways.

In http hooks, kubelet should be capable to call anything including the Kubernetes API Server (if we constrain it to only target the container then the hooks worth nothing) and this is not safe enough in some ways.
