### ISSUE TITLE
"--read-only-port" field description is confusing.

### ISSUE THREAD

**Issue by warmchang** [kubernetes/kubernetes#94550]
**What happened**:

As "kubelet --help" said, the default --read-only-port is 10255, but actually the default value is 0 (disabled):
```
 root@william  ~/go/src/k8s.io/kubernetes  _output/local/bin/linux/amd64/kubelet --version                                                      ✔  ⚡  7961  15:42:13
Kubernetes v1.19.0
 root@william  ~/go/src/k8s.io/kubernetes  _output/local/bin/linux/amd64/kubelet --help | grep read-only                                        ✔  ⚡  7962  15:42:18
      --read-only-port int32                                     The read-only port for the Kubelet to serve on with no authentication/authorization (set to 0 to disable) (default 10255) (DEPRECATED: This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.)
 root@william  ~/go/src/k8s.io/kubernetes                                                                                                       ✔  ⚡  7963  15:42:25
```
https://github.com/kubernetes/kubernetes/blob/1f708f6e6272a8f4c5b9a32cc3aea33ff79aeec1/staging/src/k8s.io/kubelet/config/v1beta1/types.go#L146

**What you expected to happen**:

Keep the context consistent, as a quick fix, we can set KubeletReadOnlyPort = 0.
https://github.com/kubernetes/kubernetes/blob/1f708f6e6272a8f4c5b9a32cc3aea33ff79aeec1/pkg/cluster/ports/ports.go#L39

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.19.0
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`):  Fedora 32 (Cloud Edition)
- Kernel (e.g. `uname -a`): 5.8.4-200.fc32.x86_64
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A

**Comment by liggitt** [comment]
The CLI documentation is saying to set it to 0 to disable, and that the default is still 10255.

**Comment by liggitt** [comment]
The CLI help is accurate... when starting the kubelet with CLI flags (not from a config file), the default is 10255. See https://github.com/kubernetes/kubernetes/pull/94551#issuecomment-688840878
