### ISSUE TITLE
[Flaky unit test] Test_Run_Positive_VolumeMountControllerAttachEnabledRace data race

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#94568]
**Which jobs are flaking**:

**Which test(s) are flaking**:

periodic-kubernetes-bazel-test-master (xref https://github.com/kubernetes/kubernetes/issues/94528#issuecomment-687208028)

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-blocking#bazel-test-master&width=20&sort-by-name=&include-filter-by-regex=pkg/kubelet/volumemanager/reconciler/go

**Reason for failure**:

```
WARNING: DATA RACE
Write at 0x00c00053f0d8 by goroutine 114:
  k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.Test_Run_Positive_VolumeMountControllerAttachEnabledRace()
      pkg/kubelet/volumemanager/reconciler/reconciler_test.go:1804 +0x13e6
  testing.tRunner()
      GOROOT/src/testing/testing.go:1108 +0x202

Previous read at 0x00c00053f0d8 by goroutine 42:
  k8s.io/kubernetes/pkg/volume/testing.(*FakeVolumePlugin).getFakeVolume()
      pkg/volume/testing/testing.go:415 +0x54e
  k8s.io/kubernetes/pkg/volume/testing.(*FakeVolumePlugin).NewAttacher()
      pkg/volume/testing/testing.go:560 +0xf9
  k8s.io/kubernetes/pkg/volume/testing.(*FakeVolumePlugin).NewDeviceMounter()
      pkg/volume/testing/testing.go:564 +0x3c
  k8s.io/kubernetes/pkg/volume/util/operationexecutor.(*operationGenerator).GenerateMountVolumeFunc.func1()
      pkg/volume/util/operationexecutor/operation_generator.go:540 +0x2251
  k8s.io/kubernetes/pkg/volume/util/types.(*GeneratedOperations).Run()
      pkg/volume/util/types/types.go:54 +0x142
  k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations.(*nestedPendingOperations).Run.func1()
      pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go:183 +0x159
```

**Anything else we need to know**:
- https://storage.googleapis.com/k8s-gubernator/triage/index.html?text=Test_Run_Positive_VolumeMountControllerAttachEnabledRace
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/periodic-kubernetes-bazel-test-master/1302035081157677056

to reproduce with [stress](https://godoc.org/golang.org/x/tools/cmd/stress):
```
go test -race -c  ./pkg/kubelet/volumemanager/reconciler
stress ./reconciler.test -test.run Test_Run_Positive_VolumeMountControllerAttachEnabledRace
```

/sig storage

**Comment by JornShen** [comment]
solved at https://github.com/kubernetes/kubernetes/pull/94676.

**Comment by liggitt** [comment]
still flaking - https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=VolumeMountControllerAttachEnabledRace

/reopen

**Comment by thejoycekung** [comment]
@liggitt -- No recent failures in the past 2 weeks, are you okay if we close this? https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=Test_Run_Positive_VolumeMountControllerAttachEnabledRace

**Comment by liggitt** [comment]
yeah, looks like https://github.com/kubernetes/kubernetes/pull/100215 resolved it

/close

**Comment by BenTheElder** [comment]
it's back 🙃  not sure if related to this issue but same test with a data race spotted last night looking into #102887 

https://github.com/kubernetes/kubernetes/issues/102932
