### ISSUE TITLE
..\pkg\mod\k8s.io\client-go@v11.0.0+incompatible\kubernetes\scheme\register.go:26:2: module k8s.io/api@latest found (v0.19.0), but does not contain package k8s.io/api/auditregistration /v1alpha1

### ISSUE THREAD

**Issue by HFeilx** [kubernetes/kubernetes#94571]
..\pkg\mod\k8s.io\client-go@v11.0.0+incompatible\kubernetes\scheme\register.go:26:2: module k8s.io/api@latest found (v0.19.0), but does not contain package k8s.io/api/auditregistration
/v1alpha1
---------------------------------------------------
module test-client-go

go 1.15

require (
	github.com/google/gofuzz v1.2.0 // indirect
	github.com/googleapis/gnostic v0.5.1 // indirect
	github.com/imdario/mergo v0.3.11 // indirect
	github.com/stretchr/testify v1.6.1 // indirect
	golang.org/x/crypto v0.0.0-20200820211705-5c72a883971a // indirect
	golang.org/x/net v0.0.0-20200904194848-62affa334b73 // indirect
	golang.org/x/oauth2 v0.0.0-20200902213428-5d25da1a8d43 // indirect
	golang.org/x/time v0.0.0-20200630173020-3af7569d3a1e // indirect
	k8s.io/api v0.19.0 // indirect
	k8s.io/client-go v11.0.0+incompatible
	k8s.io/klog v1.0.0 // indirect
	k8s.io/utils v0.0.0-20200821003339-5e75c0163111 // indirect
)
@freeformz

**Comment by liggitt** [comment]
You need to use matching levels of client-go and api/apimachinery libraries. See https://github.com/kubernetes/client-go/issues/862#issuecomment-686790080
