### ISSUE TITLE
Inotify:memory leak due to blocked operation

### ISSUE THREAD

**Issue by yanghaichao12** [kubernetes/kubernetes#94583]
**What happened**:
i wrote a shell：
```bash
#!/bin/bash

while [ true ]
do
        echo "reduce pod..."
        kubectl scale --replicas=0 rc ubuntu
        kubectl get pod -A | grep Running | wc -l
        sleep 60s
        kubectl get pod -A | grep Running | wc -l

        echo "add pod ..."
        kubectl scale --replicas=110 rc ubuntu
        kubectl get pod -A | grep Running | wc -l
        sleep 60s
        kubectl get pod -A | grep Running | wc -l
done

```
then the kubelet's RSS increases continuously and does not release，
i make some trace and found some watched objects have never been released  even these objects have not existed in real word
https://github.com/kubernetes/kubernetes/blob/16ea9dc6bc260c37589e6b104a47009680c26772/vendor/k8s.io/utils/inotify/inotify_linux.go#L103-L104

i notice the fucntion readEvent  is producer for these abnormal objects 
https://github.com/kubernetes/kubernetes/blob/16ea9dc6bc260c37589e6b104a47009680c26772/vendor/k8s.io/utils/inotify/inotify_linux.go#L135

and print the length of every event，some of which is beyond the length of buf：
https://github.com/kubernetes/kubernetes/blob/16ea9dc6bc260c37589e6b104a47009680c26772/vendor/k8s.io/utils/inotify/inotify_linux.go#L136

even when i increase the array by 10 times，the problem is still there and  the limits are broken through again and again.
so i realized the process of reading cannot be blocked.

now i added a queue for  the  buf of every inotify event and added another goroutine to consume the queue. everythings 
seems good for now.

**What you expected to happen**:
fixed the bug
**How to reproduce it (as minimally and precisely as possible)**:
running the shell :
```bash
#!/bin/bash

while [ true ]
do
        echo "reduce pod..."
        kubectl scale --replicas=0 rc ubuntu
        kubectl get pod -A | grep Running | wc -l
        sleep 60s
        kubectl get pod -A | grep Running | wc -l

        echo "add pod ..."
        kubectl scale --replicas=50 rc ubuntu
        kubectl get pod -A | grep Running | wc -l
        sleep 60s
        kubectl get pod -A | grep Running | wc -l
done

```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.17.9 
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```bash
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial

```
- Kernel (e.g. `uname -a`):
```bash
uname -a
Linux k8s 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Cweiping** [comment]
I didn't repeat the question.

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"cae93a63867", GitTreeState:"clean", BuildDate:"2020-08-11T08:41:18Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Is there a way of stable recurrence?
Thx! @yanghaichao12

**Comment by yanghaichao12** [comment]
you could use the shell i'v paste above, or make "add" more faster than "delete".....

**Comment by SergeyKanzhelev** [comment]
> * Kubernetes version (use `kubectl version`):1.17.9

The version mentioned is quite old. Can you please try to repro this on supported version of Kubernetes?


/unassign @wzshiming
/triage needs-information
/remove-triage unresolved
