### ISSUE TITLE
Server Side Apply does not detect Deployment Replicas conflict after applying HPA with different replica number

### ISSUE THREAD

**Issue by inductor** [kubernetes/kubernetes#94585]
**What happened**:
Deployment resource with replicas is handled differently in client side and server side apply with HPA

**What you expected to happen**:
With HPA, Deployment should not have `replicas` and server side apply should detect the conflict. HPA controller does not seem to manege the replica field with mangedFields.

**How to reproduce it (as minimally and precisely as possible)**:

https://gist.github.com/inductor/2ff5b8f7e04cde3d649878b761ce31e5

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.3
- Cloud provider or hardware configuration: minikube on Docker
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04
- Kernel (e.g. `uname -a`): Linux DESKTOP-0DH0Q95 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: minikube
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by apelisse** [comment]
It looks like a duplicate of: #82046

**Comment by inductor** [comment]
https://github.com/kubernetes/kubernetes/issues/82046

**Comment by palnabarun** [comment]
@inductor -- since SSA has opted out of the v1.21, can I retarget this for v1.22?

**Comment by inductor** [comment]
@palnabarun Sorry I thought I replied but that is fine.
