### ISSUE TITLE
core v1 Event API needs improvement?

### ISSUE THREAD

**Issue by tengqm** [kubernetes/kubernetes#94602]
**What happened**:

```yaml
apiVersion: v1
kind: Event
```

When creating the above resource (for testing), I'm getting this:

```
error: error validating "event-v1.yaml": error validating data: [ValidationError(Event): missing required field "metadata" in io.k8s.api.core.v1.Event, ValidationError(Event): missing required field "involvedObject" in io.k8s.api.core.v1.Event]; if you choose to ignore these errors, turn validation off with --validate=false
```

After checking the source code (https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L4569-L4576):

```go
type Event struct {
	metav1.TypeMeta
	// +optional
	metav1.ObjectMeta

	// Required. The object that this event is about. Mapped to events.Event.regarding
	// +optional
	InvolvedObject ObjectReference
         ...
```

The declaration says metadata is optional, which is wrong.  So the API spec generated is wrong.

The declaration of `InvolvedObject` is contradictary. It is both "Required" and "+optional".

**What you expected to happen**:

Be consistent about field definitions.

**How to reproduce it (as minimally and precisely as possible)**:

```
kubectl create -f config.yaml
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19

**Comment by lavalamp** [comment]
Yes, that does seem wrong. @liggitt may have an idea about who'd be good to fix it.

**Comment by Akhilesh2412** [comment]
May I work on this?

**Comment by wojtek-t** [comment]
I think it's just a documentation issue - given our validation it's not really optional...

**Comment by liggitt** [comment]
If validation actually requires the field, we should drop the optional comment and regenerate the v1 openapi schema

**Comment by yashvardhan-kukreja** [comment]
can I pick this up? would love to start contributing to k8s from this issue :D

**Comment by wojtek-t** [comment]
@yashvardhan-kukreja - will you be able to prepare a PR for it? Do you have any estimation when this will happen?

BTW - https://github.com/kubernetes/kubernetes/issues/94748 is quite similar (at least part of it).

**Comment by yashvardhan-kukreja** [comment]
@wojtek-t , I ll do it by today EOD (IST) or latest by tomorrow

**Comment by wojtek-t** [comment]
awesome - thanks a lot!

**Comment by yashvardhan-kukreja** [comment]
Also, I had a small doubt regarsing "ObjectMeta". I noticed that just like here, even other resources like `type Pod` have +optional mentioned for "ObjectMeta".

But ideally ObjectMeta (which is the "metadata" in incoming manifest) is supposed to be filled right (coz if its not then it gives the error saying that it expects the "name" field)

Hence, even there to "+optional" is misleading right?

**Comment by wojtek-t** [comment]
@liggitt - thoughts on the above?

**Comment by tengqm** [comment]
For most of the resource creation requests, the `metadata` field is required. Which means you will either provide `name` or provide a `generateName` to name the resource.
There are some rare cases where `metadata` field is not required even for resource creation.  

- a `LimitRange` object without a name/generateName specified will be assigned a name of UUID
- a `TokenReview` doesn't need a `metadata`, because it is a special resource

**Comment by wojtek-t** [comment]
Let's ignore the `metadata` for a moment and fix the remaining ones in the Event. We will adjust `metadata` based on @liggitt `s comment later.

**Comment by liggitt** [comment]
if server-side validation fails a write that does not contain metadata, then marking it optional doesn't make much sense, I agree

**Comment by LookImHigh** [comment]
Yes
