### ISSUE TITLE
How to assign a range of ip to my pods under a namespace? 

### ISSUE THREAD

**Issue by zeromsi** [kubernetes/kubernetes#94604]
I want to make sure, my pods under a namespace are assigned a specific ip addresses. Can anyone help me on how may I do this!

/sig network

**Comment by neolit123** [comment]
i don't think this is possible. please use the support channels or e.g. #sig-network on k8s slack for general questions:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

if this becomes a feature request please open a new FR ticket.

thanks
/close
/sig network
