### ISSUE TITLE
[flaky unit test] TestCSI_VolumeAll/PersistentVolume_with_driver_info

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#94619]
**Which jobs are flaking**:

pull-kubernetes-bazel-test

**Which test(s) are flaking**:

TestCSI_VolumeAll/PersistentVolume_with_driver_info

**Testgrid link**:

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-bazel-test&include-filter-by-regex=csi%2Fgo_default_test

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/93305/pull-kubernetes-bazel-test/1303342948955459585

**Reason for failure**:

Can't really tell

/sig storage

**Comment by neolit123** [comment]
/retitle [flaky test] TestCSI_VolumeAll/PersistentVolume_with_driver_info

**Comment by zhouya0** [comment]
@alculquicondor I hope my [PR](https://github.com/kubernetes/kubernetes/pull/94674) will solve this flaky :)
