### ISSUE TITLE
is kube-cross open

### ISSUE THREAD

**Issue by nvrgngyup** [kubernetes/kubernetes#94618]
https://github.com/kubernetes/kubernetes/blob/3fc1bc76a95d8a6a6cd33394526f00c00a98ce07/build/build-image/Dockerfile#L16

Hello,
Where can-I find the Dockerfile used to publish the k8s.gcr.io/build-image/kube-cross images ?

**Comment by neolit123** [comment]
the image is here:
https://github.com/kubernetes/kubernetes/pull/89275

/remove-sig docs
/sig release
/triage support
/close

**Comment by nvrgngyup** [comment]
Thanks, but... 
On this merge https://github.com/kubernetes/kubernetes/blob/d20b6cd44d64864761a8a7913ba54e5cb52a1ee6/build/build-image/cross/Dockerfile
has been removed long ago
is that Dockerfile still public on a different projet in order to produce and public the kube-cross images ?

**Comment by nvrgngyup** [comment]
Maybe I just misunderstand the workflow : is this dockerfile recreate every time golang is updated ?

**Comment by neolit123** [comment]
please try asking in the #sig-release channel on k8s slack.
