### ISSUE TITLE
Alternate image field

### ISSUE THREAD

**Issue by rajeshkodali** [kubernetes/kubernetes#94621]
**What would you like to be added**:
alternateImage: 
**Why is this needed**:
image field is the only current field to pull any images. As the image hosting providers can also go down, it will be great to provide alternate images that can be tried in case of failure. The field can be an array so that users can add multiple alternate image locations.

**Comment by liggitt** [comment]
/remove-sig architecture

This looks like a duplicate of https://github.com/kubernetes/kubernetes/issues/79389

**Comment by rajeshkodali** [comment]
@liggitt I agree. I am looking through the conversation now.

**Comment by icelynjennings** [comment]
Related sig-node meeting notes (July 16 2019) https://github.com/kubernetes/community/blob/master/sig-node/archive/meeting-notes-2019.md#july-16
