### ISSUE TITLE
TestClientReceivedGOAWAY flakes

### ISSUE THREAD

**Issue by answer1991** [kubernetes/kubernetes#94622]
* https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=GOAWAY
* https://testgrid.k8s.io/sig-testing-canaries#ci-kubernetes-generate-make-test-count10&include-filter-by-regex=GOAWAY

Before #94530 merged, TestClientReceivedGOAWAY failed with data race on [localAddr](https://github.com/kubernetes/kubernetes/blob/3fc1bc76a95d8a6a6cd33394526f00c00a98ce07/staging/src/k8s.io/apiserver/pkg/server/filters/goaway_test.go#L356). However, as far as I know, it's not the root cause of TestClientReceivedGOAWAY flake, because dial a new connection only when client send a new request, and in this case, requests are sent one by one. In other words, if data race on [localAddr](https://github.com/kubernetes/kubernetes/blob/3fc1bc76a95d8a6a6cd33394526f00c00a98ce07/staging/src/k8s.io/apiserver/pkg/server/filters/goaway_test.go#L356), then the additional unexpected connection set up, which means the test case or the configuration has problem.

After #94530 merged, TestClientReceivedGOAWAY still failed in many jobs, such as [job](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/periodic-kubernetes-bazel-test-master/1302013439975100416), [job2](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/94556/pull-kubernetes-bazel-test/1302300454738202625), which may be  a good proof of my suspect. And I got a failed job with data race issue that read at `if tc.expectConnections != len(localAddr)`(main testing goroutine) and write at `localAddr = append(localAddr, conn.LocalAddr().String())`, which told us the http client try to set-up a new connection even when we had already finished all requests(may caused by goroutine leak/block in http client).

I'm still debug the root cause of TestClientReceivedGOAWAY flake, for now, I doubt that I used an incorrect http2 server/client configuration(`http.Transport.MaxConnsPerHost=1` or SETTINGS_MAX_CONCURRENT_STREAMS limited), or the dial function ignored context.Context which will cause more than one goroutine dial the connection when the first canceled(not found any where will cancel the requests).

I still can not reproduce this failed case and it's hard to find the root cause. Couple of days may be needed to find the root cause, and I will post a PR to skip TestClientReceivedGOAWAY before I solved the problem.

Sorry for any inconvenient.

**Comment by answer1991** [comment]
cc @liggitt @knight42

**Comment by lavalamp** [comment]
Thank you for working on this!!

How often does it flake? I'm just wondering if we should disable it in the mean time to avoid angry contributors.

**Comment by answer1991** [comment]
> How often does it flake?

On my PC, about 1/1000.

>  I'm just wondering if we should disable it in the mean time to avoid angry contributors.

I will post a PR to disable it for now.

**Comment by lavalamp** [comment]
Thank you so much! That's not a bad rate at all, but we run a lot of tests.
This is super helpful!

**Comment by answer1991** [comment]
/lifecycle stale

I'm still working on it, a new golang version(1.16 or 1.15.7+) release required

**Comment by BenTheElder** [comment]
/sig api-machinery
/remove-sig testing
AFAICT this is specific to these tests, not the test framework or CI infrastructure.

**Comment by liggitt** [comment]
the tests re-enabled in https://github.com/kubernetes/kubernetes/pull/98809 started flaking again immediately

* https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=GOAWAY
* https://testgrid.k8s.io/sig-testing-canaries#ci-kubernetes-generate-make-test-count10&include-filter-by-regex=GOAWAY

/milestone v1.21

the tests should be deflaked or disabled for 1.21

**Comment by pacoxu** [comment]
+1 in recent PR tests

**Comment by answer1991** [comment]
Sorry for my slow response. I'm working on it, looks like I need to debug golang HTTP client again :-P

**Comment by caesarxuchao** [comment]
Shall we revert #98809 in the meantime?

**Comment by answer1991** [comment]
> Shall we revert #98809 in the meantime?

No, [TestGOAWAYConcurrency](https://github.com/kubernetes/kubernetes/issues/94532#event-4427772632) has already fixed by golang 1.15.8 I think. This one is caused another problem.

**Comment by answer1991** [comment]
I will disable TestClientReceivedGOAWAY case again if I can find the root cause this night.

**Comment by answer1991** [comment]
Can not reproduce on my PC, disable this test case before I figure out the root cause: https://github.com/kubernetes/kubernetes/pull/100250.

**Comment by answer1991** [comment]
I run this test case with this command `go test -race k8s.io/apiserver/pkg/server/filters -run TestClientReceivedGOAWAY -v -count=1` and can not reproduce.

Does any thing different with command `make test KUBE_RACE=-race KUBE_TIMEOUT=--timeout=240s`.

**Comment by liggitt** [comment]
moving out of the milestone and lowering priority becuase #100250 merged, leaving open because the fundamental issue is unresolved

/milestone clear

**Comment by BenTheElder** [comment]
`make test KUBE_RACE=-race KUBE_TIMEOUT=--timeout=240s WHAT=k8s.io/apiserver/pkg/server/filters GOFLAGS=-count=1` will do something comparable under make.

There's a bunch of stuff in there, generally it's not relevant for a unit test bug like this but the answer to what exactly it does is not easily concise.

Note that CI may have more load than your local machine running it once, and also currently runs as root.

https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/flaky-tests.md#deflaking-unit-tests

**Comment by BenTheElder** [comment]
/lifecycle active
/assign @aojea 
ref: https://github.com/kubernetes/kubernetes/pull/102967
