### ISSUE TITLE
ownerReference should have namespace as well as name

### ISSUE THREAD

**Issue by llamahunter** [kubernetes/kubernetes#94631]
**What would you like to be added**:

Add the 'namespace' of the owning object to the ownerReference subobjects of ObjectMeta structure.

**Why is this needed**:

Right now, there is a name, which is not globally unique to the cluster, and uuid, which is globally unique but there is no way to lookup the owner by uuid. 

It seems that the ownerReference object should allow you to actually _find_ the owner somehow.

**Comment by liggitt** [comment]
this limitation is intentional… cross-namespace ownerReferences are an explicit non-goal

If the kind referenced by the ownerReference is cluster-scoped, no namespace is required to look up the object. If it is a namespaced kind, then the current namespace is used. 

See https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/ for details:


> Cross-namespace owner references are disallowed by design. This means:
> 
> * Namespace-scoped dependents can only specify owners in the same namespace, and owners that are cluster-scoped.
> * Cluster-scoped dependents can only specify cluster-scoped owners, but not namespace-scoped owners.

**Comment by llamahunter** [comment]
Okaayyyy... but then why do some namespaced objects not have namespaces on them when they are submitted to admission controller webhooks?  In particular, Pods generated by ReplicaSets?

**Comment by liggitt** [comment]
Namespaced objects submitted to the api server with an empty namespace have the namespace forcibly set in the object by the server prior to persisting. Currently that is done after mutating admission is called. The effective namespace is explicitly set in the admission request as a distinct attribute, apart from the object definition. See example admission requests in https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#request

https://github.com/kubernetes/kubernetes/issues/88282 was opened to track documenting that nuance. 

Separately, I'd like to see the namespace setting moved ahead of admission to simplify behavior for webhooks, but that hasn't been done yet.

**Comment by llamahunter** [comment]
Yeah, any _mandatory mutation_ done by the api server should happen _before_ the webhooks are called. Where can the webhooks get this information from in the meantime?
