### ISSUE TITLE
Migrate node E2E off insecure port

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#94658]
The insecure port is being removed, but the node E2E test suite still depends no it. We need to migrate the test suite off the insecure port.

/milestone 1.20
/sig node
/priority important-soon
/help

**Comment by tallclair** [comment]
I have a WIP PR here, but I'd appreciate it if anyone else can pick this up since I don't know when I'll be able to get to it: https://github.com/tallclair/kubernetes/pull/2

That approach seems to be running into some sort of race condition. I'd also like to get it off the fixed "insecure-token" (though the fixed token approach should be acceptable as a temporary solution, as long as it's only served on local host).

**Comment by tallclair** [comment]
Blocking https://github.com/kubernetes/kubernetes/issues/91506

**Comment by knight42** [comment]
I would like to give it a try.
/assign

@tallclair Is it okay that I continue with the insecure token approach? Which approach is ideal as for e2e tests? using x509 certs?

**Comment by knight42** [comment]
@tallclair I have filed #94723 to migrate node e2e tests and `pull-kubernetes-node-e2e` passed.

**Comment by tallclair** [comment]
> Is it okay that I continue with the insecure token approach? Which approach is ideal as for e2e tests? using x509 certs?

I think the known-token route is acceptable, but I'd like to generate a random token with each test run rather than the fixed `"insecure-token"`.

**Comment by mkorbi** [comment]
Heyho @tallclair  I wanted to check how it is going?
The code freeze is starting 12.11.2020 (about 3-4 weeks from now) and while there is still plenty of time, we want to ensure that each relevant issue has a chance to be considered.

As the issue is tagged for 1.20, is it still planned for this release?

**Comment by tallclair** [comment]
I think this is on track. I just approved the node e2e change, and I think the apiserver change should be straightforward.
