### ISSUE TITLE
Add a metric tracking pod priorities used in a cluster

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#94659]
**What would you like to be added**:
A histogram that tracks the priorities used in a cluster.

**Why is this needed**:
Helps platform operators track feature usage. Priorities in particular are important since they trigger preemption in the scheduler, and so understanding how they are used helps inform optimizations related to preemption.

/sig scheduling

**Comment by Nit123** [comment]
\assign

**Comment by arghya88** [comment]
@ahg-g is there any existing metrics which is similar to this?

**Comment by arghya88** [comment]
@ahg-g I can work on it

**Comment by arghya88** [comment]
@ahg-g So histogram of how many pods have PriorityClassName mentioned in the pod spec is what is needed?

**Comment by ahg-g** [comment]
this will be addressed as part of https://github.com/kubernetes/enhancements/pull/1916
