### ISSUE TITLE
csi-snapshotter v1: "selfLink was empty, can't make reference"

### ISSUE THREAD

**Issue by gman0** [kubernetes/kubernetes#94660]
**What happened**:
I've hit an error while creating a snapshot of a PVC:

```
E0909 15:43:35.798659       1 event.go:247] Could not construct reference to: '&v1alpha1.VolumeSnapshot{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"new-nfs-share-snap", GenerateName:"", Namespace:"default", SelfLink:"", UID:"c06ae5a9-7a84-441a-8fe2-b2b3eea805b0", ResourceVersion:"470", Generation:2, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63735262998, loc:(*time.Location)(0x238f460)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string{"snapshot.storage.kubernetes.io/volumesnapshot-protection"}, ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry{v1.ManagedFieldsEntry{Manager:"kubectl", Operation:"Update", APIVersion:"snapshot.storage.k8s.io/v1alpha1", Time:(*v1.Time)(0xc000319bc0), Fields:(*v1.Fields)(nil)}, v1.ManagedFieldsEntry{Manager:"csi-snapshotter", Operation:"Update", APIVersion:"snapshot.storage.k8s.io/v1alpha1", Time:(*v1.Time)(0xc000319c20), Fields:(*v1.Fields)(nil)}}}, Spec:v1alpha1.VolumeSnapshotSpec{Source:(*v1.TypedLocalObjectReference)(0xc0002f16e0), SnapshotContentName:"", VolumeSnapshotClassName:(*string)(0xc000698610)}, Status:v1alpha1.VolumeSnapshotStatus{CreationTime:(*v1.Time)(0xc000319c40), RestoreSize:(*resource.Quantity)(0xc000649dc0), ReadyToUse:false, Error:(*v1beta1.VolumeError)(0xc0002f1710)}}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Warning' 'SnapshotCreationFailed' 'Failed to create snapshot: selfLink was empty, can't make reference'
E0909 15:43:35.798716       1 snapshot_controller.go:370] createSnapshot [create-default/new-nfs-share-snap[c06ae5a9-7a84-441a-8fe2-b2b3eea805b0]]: error occurred in createSnapshotOperation: selfLink was empty, can't make reference
```

Full logs of all components may be found [here](https://logs.openlabtesting.org/logs/51/1151/c300b97dcbc9f68842d7c51f9aedcda6f3811525/cloud-provider-openstack-acceptance-test-csi-manila/cloud-provider-openstack-acceptance-test-csi-manila/339c57a/logs/kubernetes/)

**What you expected to happen**:
Snapshots are successfully created with csi-snapshotter v1.

**How to reproduce it (as minimally and precisely as possible)**:

* csi-snapshotter v1.2.2
* Compiled latest Kubernetes from source (HEAD was at 47c450776f2731955ee7a4e8cc7ec1b4b6f14851)
* Any CSI driver will do. This was discovered in a CI job for csi-manila in this PR https://github.com/kubernetes/cloud-provider-openstack/pull/1151 (related comment https://github.com/kubernetes/cloud-provider-openstack/pull/1151#issuecomment-688805829). Local tests confirmed this bug.

1. Create a PVC
2. Create a snapshot of that PVC

Step 2 will always fail.

**Anything else we need to know?**:
I believe this is a regression. K8s v1.19.0 + csi-snapshotter v1.2.2 works just fine.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.0-alpha.0.1346+47c450776f2731", GitCommit:"47c450776f2731955ee7a4e8cc7ec1b4b6f14851", GitTreeState:"clean", BuildDate:"2020-09-09T15:32:12Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.0-alpha.0.1346+47c450776f2731", GitCommit:"47c450776f2731955ee7a4e8cc7ec1b4b6f14851", GitTreeState:"clean", BuildDate:"2020-09-09T15:32:12Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: KVM VM
- OS (e.g: `cat /etc/os-release`): Alpine Linux 3.12.0
- Kernel (e.g. `uname -a`): 5.4.43-1-virt x86_64
- Install tools: `hack/local-cluster-up.sh`
- Network plugin and version (if this is a network-related bug):
- Others:

/kind bug
/sig storage

**Comment by liggitt** [comment]
That message was removed in 1.16 in https://github.com/kubernetes/kubernetes/commit/399d09ce4ad1728fcecdce09503a07cf1bfecef6#diff-11d7e42f9dbb8d78ea8589f9506dee5b

What version of kubernetes server and libraries are being used?

**Comment by liggitt** [comment]
Looks like https://github.com/kubernetes/kubernetes/pull/94397 is merging in 1.20, which stops setting selfLink. cc @wojtek-t

**Comment by liggitt** [comment]
It seems likely that the snapshot controller needs to update k8s libraries to use a fixed version of the GetReference function, but I also want @wojtek-t to have visibility to downstream impact of the selfLink change

**Comment by liggitt** [comment]
it looks like csi-snapshotter 1.2.2 is using client-go from kubernetes 1.14:

https://github.com/kubernetes-csi/external-snapshotter/blob/v1.2.2/Gopkg.toml#L25-L27

using client-go 1.16+ should resolve this issue

**Comment by liggitt** [comment]
cc @msau42

**Comment by msau42** [comment]
The snapshot feature is beta starting in 1.17, so I recommend using > v2.0 on 1.17+

**Comment by wojtek-t** [comment]
yeah - we were updating couple storage components to not rely on that around 1.16. 
@gman0 - please use a newer version of snapshotter (as Michelle recommended above)

**Comment by gman0** [comment]
Alright, thanks guys! Closing.
