### ISSUE TITLE
scheduler_perf: use time.Ticker in throughput measurement

### ISSUE THREAD

**Issue by adtac** [kubernetes/kubernetes#94665]
https://github.com/kubernetes/kubernetes/blob/b56d0acaf5bead31bd17d3b88d4a167fcbac7866/test/integration/scheduler_perf/util.go#L244

https://golang.org/pkg/time/#Ticker

/sig scheduling
/sig testing
/assign

**Comment by tangwz** [comment]
@adtac @neolit123 May I give a try?

**Comment by adtac** [comment]
@tangwz please go ahead. Un-assigning myself.

**Comment by tangwz** [comment]
/assign
@adtac What should I do just replace  `time.After` with ` time.Ticker`?

**Comment by adtac** [comment]
Please see the go docs for `Ticker` and the example they have there: https://golang.org/pkg/time/#Ticker

They do a better job than I possibly can :)
