### ISSUE TITLE
error: storage/cacher.go:/csinodes: Failed to list *storage.CSINode: no kind "CSINode" is registered for version "storage.k8s.io/v1"

### ISSUE THREAD

**Issue by misteruly** [kubernetes/kubernetes#94675]
this is my  apiserver  error

k8s  version  v1.15.11

kube-apiserver   parameter   as follow

/usr/bin/kube-apiserver --token-auth-file=/etc/kubernetes/token_auth_file --requestheader-client-ca-file=/etc/kubernetes/ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --requestheader-allowed-names=aggregator --allow-privileged=true --etcd-servers=http://192.168.1.110:2379,http://192.168.1.111:2379,http://192.168.1.114:2379 --client-ca-file=/etc/kubernetes/ca.crt --tls-private-key-file=/etc/kubernetes/server.key --tls-cert-file=/etc/kubernetes/server.crt --insecure-bind-address=0.0.0.0 --secure-port=6443 --insecure-port=8080 --service-cluster-ip-range=10.96.0.0/16 --service-node-port-range=8000-65535 --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,SecurityContextDeny,ResourceQuota,DefaultStorageClass --logtostderr=false --log-dir=/var/log/kubernetes --v=2

What's the solution?

**Comment by liggitt** [comment]
The API server gained the ability to read CSINode objects in v1 format in 1.17 (https://github.com/kubernetes/kubernetes/pull/83474) and began persisting CSI node objects in etcd in v1 format in 1.18 (https://github.com/kubernetes/kubernetes/pull/84477)

The error you are getting means a 1.18+ API server was run against the etcd instance you are using and persisted v1 CSINode data. That means the oldest API server that can be run against that etcd instance and successfully read data out of it is now 1.17.

**Comment by misteruly** [comment]
> The API server gained the ability to read CSINode objects in v1 format in 1.17 (#83474) and began persisting CSI node objects in etcd in v1 format in 1.18 (#84477)
> 
> The error you are getting means a 1.18+ API server was run against the etcd instance you are using and persisted v1 CSINode data. That means the oldest API server that can be run against that etcd instance and successfully read data out of it is now 1.17.



think you!!   I'm starting to upgrade  1.18  api.  Does not support the calico-v2.5.  restore  1.15.11 api. How do I block this error???

**Comment by liggitt** [comment]
> think you!! I'm starting to upgrade 1.18 api. Does not support the calico-v2.5. restore 1.15.11 api. How do I block this error???

Upgrading across multiple minor versions of the API server at once is not supported for this reason... it prevents the old API server from successfully reading the data. The supported method for upgrading is to go one minor version at a time.

To recover from this, you could do one of the following:
1. Try to get those objects rewritten to etcd in v1beta1 format by:
  * Starting a 1.17 API server
  * Triggering all the CSINode and CSIDriver objects to be rewritten (with something like `kubectl label csinodes,csidrivers --all rewritten=1.17 --overwrite`)
  * Then start your 1.15 API server
2. Remove the CSINode objects from etcd directly ... deleting things directly from etcd is pretty fragile and is obviously losing that data

**Comment by ysaakpr** [comment]
I too have similar error happening, `Starting a 1.17 API server` can i start a api server connecting to existing cluster while other API server of version 1.15 running?
