### ISSUE TITLE
Rolling update of addon RCs

### ISSUE THREAD

**Issue by marekbiskup** [kubernetes/kubernetes#9467]
During upgrade, the replication controllers of addons are stopped and then started. But they should be rolling updated.

**Comment by marekbiskup** [comment]
cc @zmerlynn @davidopp @fgrzadkowski @satnam6502

**Comment by davidopp** [comment]
This would definitely be nice but I think the question is whether @marekbiskup thinks he can finish this by Friday. I guess it partially depends on how the following question is resolved:
https://github.com/GoogleCloudPlatform/kubernetes/issues/9394#issuecomment-110436841

**Comment by fgrzadkowski** [comment]
@davidopp My personal feeling is that this is issue is far less important than moving kube-addon to a pod or updating services.

**Comment by bgrant0607** [comment]
We should wait for Deployment for this.

cc @nikhiljindal

**Comment by bgrant0607** [comment]
We're using Deployment
