### ISSUE TITLE
Update addon services when their definition changes

### ISSUE THREAD

**Issue by marekbiskup** [kubernetes/kubernetes#9468]
Currently the add-on services are updated only if the name changes (new service is created and the old one is deleted). But it should be possible to update them without changing the name.

**Comment by marekbiskup** [comment]
cc @zmerlynn @davidopp @fgrzadkowski @satnam6502

**Comment by davidopp** [comment]
I don't think this is 1.0-worthy. The instructions for doing update of addons says to use a new RC/service name for the new version. I don't think this is a particularly significant burden.

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/addons/README.md

**Comment by davidopp** [comment]
Sorry that should say RC, not RC/service.

**Comment by fgrzadkowski** [comment]
+1

This should be fixed relatively soon, but it doesn't block 1.0. We can fix this after the release.

**Comment by bgrant0607** [comment]
We should wait until we have Deployment (#1743).

**Comment by roberthbailey** [comment]
Is this still a pain point almost two years later? The cluster lifecycle SIG is working on revamping the addon manager (see https://docs.google.com/document/d/1Laov9RCOPIexxTMACG6Ffkko9sFMrrZ2ClWEecjYYVg/edit#heading=h.rwtjflxdmlmi) so I'm going to close this issue and propose that we address any lingering concerns as part of that process. 

@justinsb FYI.
