### ISSUE TITLE
Can no longer call DecodeParameters with url.Values in 1.19.0 client-go

### ISSUE THREAD

**Issue by ibuildthecloud** [kubernetes/kubernetes#94688]
**What happened**:
The following code works in 1.18 but is broken in 1.19.0
```go
import (
	"k8s.io/client-go/kubernetes/scheme"
	corev1 "k8s.io/api/core/v1"
)
...
       	target := &corev1.PodLogOptions{}
	return scheme.ParameterCodec.DecodeParameters(req.URL.Query(), corev1.SchemeGroupVersion, target)
```

This results in the error: `converting (url.Values) to (v1.PodLogOptions): unknown conversion`

**Anything else we need to know?**:

This seems to be caused by this line which seems like a mistake because it's an early exit and the comment right below indicates this should be removed in 1.20.  https://github.com/kubernetes/kubernetes/blob/v1.19.0/staging/src/k8s.io/apimachinery/pkg/conversion/converter.go#L454

Is there a different way to decode PodLogOptions?  If you remove the the default converter I don't understand how I'm supposed to do this anymore because there is no converter registered for url.Values that I'm aware of. 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.0 client-go/api

**Comment by ibuildthecloud** [comment]
I put in a PR for this, but I have no clue if it's the write procedure for submitting fixes for releases.  Feel free to close the PR and make the one line change yourself following the proper procedure. https://github.com/kubernetes/kubernetes/pull/94689

**Comment by wojtek-t** [comment]
There should be auto-generated conversion for tihs:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L4983

And there is:
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/v1/zz_generated.conversion.go#L5911


> t's an early exit and the comment right below indicates this should be removed in 1.20.

No - it's not a mistake - it was consciously added - we're getting rid of default conversions.

@ibuildthecloud - how to reproduce your error?

**Comment by wojtek-t** [comment]
@liggitt - FYI

**Comment by wojtek-t** [comment]
xref https://github.com/kubernetes/kubernetes/issues/87006

**Comment by liggitt** [comment]
Reflect-based conversions are not supported in 1.19+ because they mask data loss errors.

Conversions must now be explicit. You can add the generated conversions @wojtek-t mentioned to your scheme like this:

```go
import (
	"k8s.io/client-go/kubernetes/scheme"
	corev1 "k8s.io/api/core/v1"
	corev1conversions "k8s.io/kubernetes/pkg/apis/core/v1"
)
...
       	// register v1 conversions
       	corev1conversions.AddToScheme(scheme.Scheme)

       	target := &corev1.PodLogOptions{}
	return scheme.ParameterCodec.DecodeParameters(req.URL.Query(), corev1.SchemeGroupVersion, target)
```

**Comment by knight42** [comment]
@liggitt Does it mean users have to import `"k8s.io/kubernetes"` if they want to do conversion using client-go 1.19+? Would it be better to move the conversion funcs to a common place?

**Comment by liggitt** [comment]
> @liggitt Does it mean users have to import "k8s.io/kubernetes" if they want to do conversion using client-go 1.19+? 

Yes, conversion responsibilities explicitly belong to the server.

**Comment by lavalamp** [comment]
@ibuildthecloud can you say why you need to do this? I'd expect client-go users to be constructing url.Values, not parsing them.

@liggitt I don't think we can recommend that people import "k8s.io/kubernetes" if we did something that broke compatibility for a use case that we intend client-go to support

**Comment by liggitt** [comment]
> I don't think we can recommend that people import "k8s.io/kubernetes" if we did something that broke compatibility for a use case that we intend client-go to support

We don't intend client-go users to be converting objects... that is the responsibility of the server.

**Comment by lavalamp** [comment]
Yeah, I agree, that's why I want to hear what @ibuildthecloud is doing, maybe there's a use case we hadn't thought of.

**Comment by ibuildthecloud** [comment]
@liggitt @lavalamp We have a component that takes an API request and then makes a pod log API request.  The API request is intended to have the same query string args that get passed to the pod log API request.  So we would use the decoder to keep exact parity with the k8s API.

If the answer is I just can't do that anymore officially (since I officially shouldn't be importing k/k), then that's fine.  I only opened this issue because the code seemed to indicate the functionality should work in 1.19.

**Comment by ibuildthecloud** [comment]
@wojtek-t This is probably already clean, but this can be reproduce with basically the snippet I put in the issue. This is because the converter is only registered in the internal k/k api package, not the public k8s.io/api one.

**Comment by lavalamp** [comment]
@ibuildthecloud thanks for explaining--

I actually recommend passing the parameters through directly without parsing, including ones you don't know about, because then you'll automatically be compatible with whatever cluster you're operating on. You can consider using a dry run request to pre-validate if the concern is giving the user a good error message early on. (If that doesn't work as expected then definitely file a bug.)

If you parse the query parameters, then there's a potential version skew problem, even if you're using the right code to do it.

I actually suspect it doesn't make much difference for the pods log subresource, which we haven't changed in ages and have no plans to change (that I know of), so you should do whatever is expedient. But it's a concern for other, more common requests.

In the general case, conversion really needs to be something clients ask apiserver to do for them, because e.g. there's no way we can expect a client to build in a CR conversion, and we don't want things to randomly break for CRs for users. Unfortunately we have no way to ask apiserver to just convert some data, and most ways I can think of doing that wouldn't work for the URL parameter conversion, so there's definitely something missing here.

**Comment by wojtek-t** [comment]
Just got to it again - yes I fully agree with Daniel (this is great write up btw).

@ibuildthecloud - please close the issue you agree with that (or let us know if you have other questions about that).

**Comment by caesarxuchao** [comment]
/close

based on https://github.com/kubernetes/kubernetes/issues/94688#issuecomment-692147049
