### ISSUE TITLE
Run addon update process as a pod

### ISSUE THREAD

**Issue by marekbiskup** [kubernetes/kubernetes#9469]
Addon updater is a linux service on the master. It should be replaced by a pod

**Comment by marekbiskup** [comment]
cc @zmerlynn @davidopp @fgrzadkowski @satnam6502

**Comment by bgrant0607** [comment]
We should use some combination of Deployment and Deployment Manager to do this.
cc @nikhiljindal @jackgr

**Comment by bgrant0607** [comment]
Superseded by #23233
