### ISSUE TITLE
Remove usage of reflect.DeepEqual in framework/runtime tests

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#94696]
The use of `reflect.DeepEqual` makes it harder to swap implementations. We should be using `cmp` package instead, preferring `cmp.Diff` to print the differences. In the cases where this is not possible due to unexported members, we should:

1. Check if we can simply export all fields
1. If 1 is not possible and the structs are only compared in one test file, implement an explicit Comparer there, or:
1. Provide a comparer for the type.

In the case of errors, `cmpopts.EquateErrors` should be preferred.

A clear offender of this issue is `pkg/scheduler/framework/runtime/framework_test.go`. But we should fix #94695 first.

/sig scheduling

**Comment by HaonanFeng** [comment]
I'm a new contributor and I'm interested in this issue.

**Comment by alculquicondor** [comment]
Feel free to take it. You can start anywhere in `pkg/scheduler`, specially if the change doesn't depend on #94695.

Please submit small contained PRs (affecting one file and it's corresponding test if possible).

**Comment by alculquicondor** [comment]
/remove-help

Removing tag because it is already assigned.

@HaonanFeng do you have any progress to share?

**Comment by HaonanFeng** [comment]
Sorry, I was business trip for the last few days and I'm working on this.

**Comment by Huang-Wei** [comment]
> * If 1 is not possible and the structs are only compared in one test file, implement an explicit Comparer there, or:

We can use `cmp.AllowUnexported()` as an option:

```go
if diff := cmp.Diff(gotStatus, tt.wantStatus, cmp.AllowUnexported(framework.Status{})); diff != "" {
```

**Comment by alculquicondor** [comment]
-1 on `AllowUnexported`

I think we should define clear semantics of when 2 statuses are equal. Otherwise we are not wining anything from moving off `reflect.Equal`

**Comment by Huang-Wei** [comment]
> I think we should define clear semantics of when 2 statuses are equal.

If the comparison semantics is not ambiguous, why don't we use `AllowUnexported` directly? Take the `framework.Status` for example, it's clear that we're going to compare all (private) fields (reason, code, etc.).

**Comment by alculquicondor** [comment]
It is actually a bit ambiguous.

Say a plugin returns `{Unschedulable, "not enough CPU"}`. Then we annotate that as coming from the FitPlugin in runtime.go:
So `{Unschedulable, "FitPlugin failed: not enough CPU"}`. Now they are different, but they shouldn't be.

Arguably, we are wrapping statuses the wrong way. That's precisely what https://blog.golang.org/go1.13-errors is trying to solve. However, we are not talking about errors here.

/unassign @HaonanFeng
Sorry, we need more deliberation here.

**Comment by alculquicondor** [comment]
That said, I don't think we do decision making with "reasons", only with "errors". So we don't need to redefine the Status struct.

But we should fix how we compare errors. I think a proper comparison, at least for now would be:
code is equal, reasons are equal, errors compare the same with `errors.Is`

**Comment by Huang-Wei** [comment]
> That said, I don't think we do decision making with "reasons", only with "errors".

That's true.

> But we should fix how we compare errors. I think a proper comparison, at least for now would be:
> code is equal, reasons are equal, errors compare the same with `errors.Is`

I got your point. How about defining a generic `ComparerFn` in framework/interface.go (rough logic, can be tweaked):

```go
func ComparerFn(x, y *Status) bool {
	return x.code == y.code && cmp.Equal(x.reasons, y.reasons) && errors.Is(x.err, y.err)
}
```

Then in tests, call the `ComparerFn` to have a unified comparing behavior:

```go
if diff := cmp.Diff(gotStatus, tt.wantStatus, cmp.Comparer(framework.ComparerFn)); diff != "" {
	t.Errorf("Unexpected status (-want, +got): %s", diff)
}
```

**Comment by alculquicondor** [comment]
alternatively, we expose all the attributes and just use `cmpopt.EquateErrors`.

**Comment by Huang-Wei** [comment]
`cmpopt.EquateErrors` sounds good to me as well, I don't have a strong option.

BTW: if we go with the customized `ComparerFn`, it seems we should make the error comparison symmetric:

```
errors.Is(x.err, y.err) || errors.Is(y.err, x.err)
```

Ref: 

https://github.com/kubernetes/kubernetes/blob/0dd6bf625814ab6ef9f93fbee40cde6d6206d932/vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go#L155

**Comment by HaonanFeng** [comment]
Did you mean use  `cmpopts.EquateErrors()` like this?
```
			if diff:= cmp.Diff(gotStatus,tt.wantStatus,cmpopts.EquateErrors(),cmp.Exporter(func(r reflect.Type) bool {
				return true
			})); diff != "" {
```

**Comment by HaonanFeng** [comment]
Did you mean use `cmpopts.EquateErrors()` like this?

```
if diff:= cmp.Diff(gotStatus,tt.wantStatus,cmpopts.EquateErrors(),cmp.Exporter(func(r reflect.Type) bool {
	return true
})); diff != "" {
```

**Comment by alculquicondor** [comment]
Kind of. Export the Status fields (make the first letter uppercase) instead of using `cmp.Exporter`

**Comment by HaonanFeng** [comment]
> Kind of. Export the Status fields (make the first letter uppercase) instead of using `cmp.Exporter`
Can we define a function `allowUnExportedType` export the "Status" fields .
```
func allowUnExportedType(t reflect.Type) bool{
	if t.Name()=="Status"{
		return true
	}
	return false
}
```
Then in `Diff`, `cmp.Exporter` judge whether it is "Status", if it is, then return the field of status:
`if diff:= cmp.Diff(gotStatus,tt.wantStatus,cmpopts.EquateErrors(),cmp.Exporter(allowUnExportedType)); diff != "" {`

**Comment by Huang-Wei** [comment]
> Then in `Diff`, `cmp.Exporter` judge whether it is "Status", if it is, then return the field of status:

I don't think we'd like to do that way. Just simply make the private fields of Status to public, and use `cmpopts.EquateErrors()`.

**Comment by ahg-g** [comment]
-1 on exporting the Status fields. nil is a valid Status, I am concerned that exporting the fields will make it easier to fall into nil pointer dereference bugs. Creating a compare function for Status is the safer option.

**Comment by alculquicondor** [comment]
I'm fine with just having a compare function.

**Comment by Huang-Wei** [comment]
Generic comparer(s) looks good, and here are some examples in k8s code case:

```
staging/src/k8s.io/apiextensions-apiserver/pkg/controller/openapi/v2/conversion_test.go
685:					t.Errorf("unexpected result:\n  want=%v\n   got=%v\n\n%s", *test.expected, *out, cmp.Diff(*test.expected, *out, cmp.Comparer(refEqual)))

staging/src/k8s.io/apiextensions-apiserver/pkg/controller/openapi/v2/conversion_test.go
685:					t.Errorf("unexpected result:\n  want=%v\n   got=%v\n\n%s", *test.expected, *out, cmp.Diff(*test.expected, *out, cmp.Comparer(refEqual)))

staging/src/k8s.io/apiextensions-apiserver/pkg/controller/openapi/v2/conversion_test.go
685:					t.Errorf("unexpected result:\n  want=%v\n   got=%v\n\n%s", *test.expected, *out, cmp.Diff(*test.expected, *out, cmp.Comparer(refEqual)))

pkg/controller/certificates/authority/authority_test.go
190:				cmp.Comparer(func(x, y *url.URL) bool {
```

Add a TODO here, refactor `TestFindFitSomeError` and `TestFindFitAllError` (and maybe more) in pkg/scheduler/core/generic_scheduler_test.go using the generic Status comparer.

**Comment by alculquicondor** [comment]
It looks like we have consensus in adding a comparer function. @gavinfish could you update your PR?

**Comment by gavinfish** [comment]
> It looks like we have consensus in adding a comparer function. @gavinfish could you update your PR?

@alculquicondor sure, let us wait the pre-PR #98266 to get merged first.

**Comment by gavinfish** [comment]
for `NodeInfo`, I think it is ok to remove `Node()` function and export `node` field, considering
- it is not special as status which takes nil as success status
- similar struct `PodInfo` exports `Pod` field

https://github.com/kubernetes/kubernetes/blob/26744ac58dd31ceb342b54a2a9d71d66aa95811d/pkg/scheduler/framework/types.go#L470-L476

Have I missed any restrictions with this? @ahg-g @alculquicondor @Huang-Wei

**Comment by alculquicondor** [comment]
Can you check if there any instances where `n *NodeInfo` can be nil? I don't think so, but maybe.

**Comment by alculquicondor** [comment]
/remove-lifecycle stale


@gavinfish can you still gradually remove the remaining usages?
