### ISSUE TITLE
Conversion generation isn't fully deterministic

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#94691]
When working on https://github.com/kubernetes/kubernetes/pull/94480 I faced a strange issue.

It seems that while auto-generating conversions it works fine,
but during things like `command: bash "verify-generated-swagger-docs.sh` or `make vet` in the presubmits what is generated is different.
Looking into test results:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/94480/pull-kubernetes-verify/1304065207634497536/build-log.txt
it seems that the order in which the files are processed is different then.

/kind bug
/sig api-machinery

**Comment by wojtek-t** [comment]
FTR: The log from above has some debug-logging and panics added and the conversion-generator logs are those with `-->`

**Comment by roycaihw** [comment]
https://github.com/kubernetes/kubernetes/pull/94480 modifies conversion-gen, but doesn't change the generated files. Did you intentionally exclude those changes? 

> It seems that while auto-generating conversions it works fine

I wonder if it's similar to https://github.com/kubernetes/kubernetes/issues/78499. I checked out https://github.com/wojtek-t/kubernetes/commit/50792c6e5b6ae9bb4cdff4eac9c37e6e7011ab3c, ran 
```
$ rm pkg/scheduler/apis/config/v1beta1/zz_generated.conversion.go
$ make generated_files
```
I was able to reproduce the error in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/94480/pull-kubernetes-verify/1303980145115140096. 
```
errors in package "k8s.io/kubernetes/pkg/scheduler/apis/config/v1beta1":
unable to format file ".../k8s.io/kubernetes/pkg/scheduler/apis/config/v1beta1/zz_generated.conversion.go" (152:1: expected declaration, found 'if').
```

**Comment by wojtek-t** [comment]
> #94480 modifies conversion-gen, but doesn't change the generated files. Did you intentionally exclude those changes?

This is supposed to be no-op :) no auto-generated files should change


> If that's the case, a workaround to fix the auto-generating is to first remove the affected files and re-generate them locally.

That's not the fix. The problem is with the test jobs themselves:
- for generating swagger doc, they actually generate different things than they generate when you call "make generated-files"

My PR is only a trigger for the problem, it's not a root cause.
The auto-generated files are correct, but as part of running swagger docs, we're in-process generating a different stuff.

**Comment by roycaihw** [comment]
It looks that packages were missing. `verify-generated-swagger-docs` has a shorter [InputDirs](https://github.com/kubernetes/kubernetes/blob/303810c7a22d6dc4f940d7e183f7b0518c00569a/staging/src/k8s.io/code-generator/cmd/conversion-gen/main.go#L110)/[packages](https://github.com/kubernetes/kubernetes/blob/303810c7a22d6dc4f940d7e183f7b0518c00569a/staging/src/k8s.io/code-generator/cmd/conversion-gen/generators/conversion.go#L356) list compared to the other checks (e.g. `verify.generated-files`) when I ran `make verify`. In the case of #94480, the component-base config package was missing, thus the FIXME code path got hit. 

The list of packages was derived from [here](https://github.com/kubernetes/kubernetes/blob/303810c7a22d6dc4f940d7e183f7b0518c00569a/build/root/Makefile.generated_files#L465-L470). It seems that the dir was dirty during `verify-generated-swagger-docs`. I'm exploring if we can clean up the [temp dir](https://github.com/kubernetes/kubernetes/blob/303810c7a22d6dc4f940d7e183f7b0518c00569a/hack/verify-generated-swagger-docs.sh#L79-L80) like [verify-generated-files](https://github.com/kubernetes/kubernetes/blob/303810c7a22d6dc4f940d7e183f7b0518c00569a/hack/verify-generated-files.sh#L41-L42) does.

**Comment by wojtek-t** [comment]
It seems that this one isn't yet fully fixed.
I have updated the https://github.com/kubernetes/kubernetes/pull/94480#issuecomment-718619842 based on the comments on it and faced a similar issue on that (which I think has a very similar root cause).

However, now "govet" and "staticcheck" are failing:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/94480/pull-kubernetes-verify/1321753498307530752

[Ironically all other tests are passing, so I think this is again connected to some garbage somewhere]

@roycaihw - can you please help with this?

**Comment by wojtek-t** [comment]
As previously, I can reproduce it by:
```
make clean
make vet
mv pkg/scheduler/apis/config/v1beta1/zz_generated.conversion.go .
make vet
```

**Comment by wojtek-t** [comment]
I'm fairly sure at this point that the inputdirs param here is too restrictive:
https://github.com/kubernetes/kubernetes/blob/master/build/code_generation.bzl#L86

**Comment by wojtek-t** [comment]
It seems that this commit might be addressing this:
https://github.com/kubernetes/kubernetes/pull/94480/commits/8004ccea28137084001e1bc3d019a07c28410619

**Comment by wojtek-t** [comment]
Heh - I think it helped me locally, but it doesn't help for #94480 - I probably did something wrong.
But I'm fairly sure it's something along those lines that we need to do.

@roycaihw - will you be able to help with it?

**Comment by wojtek-t** [comment]
So yeah - I was completely wrong.
Basically, running with with DBG it clearly is a problem with gen-conversion.
And the problem is that we pass only limited input to it:
https://github.com/kubernetes/kubernetes/blob/master/build/root/Makefile.generated_files#L445

I think we should always pass all inputs - but we should look a bit deeper into it.

**Comment by wojtek-t** [comment]
OK - so this is the problematic part:
https://github.com/kubernetes/gengo/blob/master/parser/parse.go#L465-L470

We basically process only packages that are explicitly requested by the user and ignore ones that are imported.
So in order to have the conversion func imported by the generator, the package where it lives has to be explicitly imported.

So we should basically always pass all input packages to conversion generator.

**Comment by wojtek-t** [comment]
I actually created a new one, as it seems to be a different thing. Closing in favor of https://github.com/kubernetes/kubernetes/issues/96015
