### ISSUE TITLE
Improve Error handling in framework

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#94695]
Starting from golang 1.13, it's possible to wrap errors to be able to detect and compare root errors more easily.

In the scheduler framework, we only handled messages and used a status code to identify errors. This loses error information. #94437 is fixing this for a specific case, but we need to do a sweep through all the framework runtime and the plugins to **always** wrap errors.

Stretch:
It might also be worth introducing an error type for the framework that also holds the error code and implements `Is(target error) bool` and `Unwrap() error`

/sig scheduling

**Comment by krishchow** [comment]
@alculquicondor unless you were planning on working on this, I would be happy to take a look at this issue and start working on a fix :)

**Comment by alculquicondor** [comment]
Sounds good. Just wait for #94692 to get merged first :)

**Comment by alculquicondor** [comment]
It is merged

**Comment by alculquicondor** [comment]
Whenever possible, send small self-contained PRs (affecting a particular extension point and it's corresponding test).

**Comment by arghya88** [comment]
@SataQiu I have submitted PRs for volume-zone, taint-toleration, service-affinity, podtoplogyspread, selectorspread plugins

**Comment by Huang-Wei** [comment]
@alculquicondor could you help to negotiate to assign the tasks?

**Comment by alculquicondor** [comment]
/remove-help

My bad for making this so open ended.

But as general guidance, please leave some time for the contributor already assigned to start the work. Specially given that we are so far from code freeze and this work is low priority.

In this particular case, I would like to give @krishchow and @SataQiu to work on this, as they were the first ones to offer help.

**Comment by alculquicondor** [comment]
Also please try to coordinate in slack before sending PRs.

**Comment by alculquicondor** [comment]
I closed some PRs that haven't been reviewed yet. I left the others open to avoid losing the work done.

**Comment by alculquicondor** [comment]
@SataQiu would you mind putting a list of all the packages or plugins that already have open/merged PRs?

**Comment by alculquicondor** [comment]
@SataQiu is there more pending work?

**Comment by gavinfish** [comment]
@SataQiu @krishchow I am working on #94696 which has some dependencies on this issue, I will pick this up if you are working on this anymore.

**Comment by krishchow** [comment]
Go ahead @gavinfish :)
