### ISSUE TITLE
Should we extend the beta-API-removal window?

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#94694]
Today, https://kubernetes.io/docs/reference/using-api/deprecation-policy says that a beta API can be removed 9 months after GA.  Given our version support policies, this means that an arbitrary external controller has very little wiggle-room for which API they support, which practically forces them to support multiple API versions.

E.g.
* vX: v1beta1
* vX+1: v1beta1 + v1
* vX+2: v1beta1 + v1
* vX+3: v1beta1 + v1
* vX+4: v1

We know that, in reality, when vX goes out of the window, it takes some customers time to move forward.  We also know that managed providers tend to lag.  The question here is whether we should be more "gracious" here, and make the overlap window longer (e.g. 4 or even 5 releases), or whether we should just endorse "you should always support multiple API versions" in cases like this.

**Comment by neolit123** [comment]
i think extending the minimal support window for beta might be better for end-users, but it might partially conflict with the general idea of https://github.com/kubernetes/enhancements/issues/1635 to push to GA faster from the perspective of developers. so there is some trade off.

https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-parts-of-the-api
(adding link to the policy)

**Comment by sftim** [comment]
> you should always support multiple API versions

I think I'd approach this with a blog article: _why_ you should always support multiple API versions.

(and if people agree, I can help draft / edit that article)

**Comment by thockin** [comment]
I don't think extending the beta window conflicts with the need to go GA in
a reasonable time.  It just means that the API would stick around much
longer.  I like deleting code as much as anyone, so I ACK the downside here
:)

**Comment by liggitt** [comment]
I lean toward the "support multiple versions" position, at least for beta. One of the explicit goals of the "prevent permabeta" proposal was "Prevent beta APIs from being treated as GA by users and vendors." I think if you ship something using a beta API, you should be prepared to update it to use the GA version once available, falling back to the beta version if not available.

What you are describing seems much more reasonable for a v1 -> v2 transition, where v1 should not be removed until all supported versions support v2.
