### ISSUE TITLE
error: choose one of: [metrics-server metrics-server-nanny]

### ISSUE THREAD

**Issue by tom20180101** [kubernetes/kubernetes#94710]
when i install metrics-server  on k8s ,i find pod metrics-server  status is  CrashLoopBackOff  , i use  "kubectl logs   metrics-server-v0.3.6-*******.  " ,the result show "error: a container name must be specified for pod metrics-server-v0.3.6-86b7b5b85d-bw7x4, choose one of: [metrics-server metrics-server-nanny]" , i don't know how to fix it . is this a bug?  i‘m looking forward to who can help me resolv it .

os:  CentOS Linux release 7.6.1810 (Core)
k8s : 1.18.8 
metrics-server.yaml:    https://github.com/kubernetes/kubernetes/tree/release-1.18/cluster/addons/metrics-server/

**Comment by BenTheElder** [comment]
There are multiple containers in the pod. See https://kubectl.docs.kubernetes.io/pages/container_debugging/container_logs.html selecting a container, or use --all-containers

**Comment by tom20180101** [comment]
i know how to fix it . thank you @BenTheElder  .
