### ISSUE TITLE
Field selector podIPs not supported but enabled

### ISSUE THREAD

**Issue by zhouya0** [kubernetes/kubernetes#94719]
**What happened**:
When doing something like:
```
kubectl get pods --field-selector status.podIPs=10.100.6.153,fd00::6
```
It will report error:
```
Error from server (BadRequest): Unable to find "/v1, Resource=pods" that match label selector "", field selector "status.podIPs==10.100.6.153,fd00::6": invalid selector: 'status.podIPs==10.100.6.153,fd00::6'; can't understand 'fd00::6'
```
Because the logic to handle the field selector will separate `,`:
```
func splitTerms(fieldSelector string) []string {
	if len(fieldSelector) == 0 {
		return nil
	}

	terms := make([]string, 0, 1)
	startIndex := 0
	inSlash := false
	for i, c := range fieldSelector {
		switch {
		case inSlash:
			inSlash = false
		case c == '\\':
			inSlash = true
		case c == ',':
			terms = append(terms, fieldSelector[startIndex:i])
			startIndex = i + 1
		}
	}

	terms = append(terms, fieldSelector[startIndex:])

	return terms
}
```
Which I think `--fied-selector` should not support arrays. But `podIPs` was enable by https://github.com/kubernetes/kubernetes/pull/83123.

**What you expected to happen**:
1. Tell user not supported like:
```
[root@master ~]# kubectl get pods --field-selector spec.priority=0
Error from server (BadRequest): Unable to find "/v1, Resource=pods" that match label selector "", field selector "spec.priority=0": field label not supported: spec.priority
```
2. Provide a way to use array in `field selector`

**How to reproduce it (as minimally and precisely as possible)**:
```
kubectl get pods --field-selector status.podIPs=10.100.6.153,fd00::6
```

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`): 1.19
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
The value for this field contains a comma. Commas are significant in field selectors to separate terms.

That means to match this value you need to escape the comma:

```
kubectl get pods --field-selector 'status.podIPs=10.100.6.153\,fd00::6'
```
