### ISSUE TITLE
DaemonSet not respecting Namespace defaultTolerations

### ISSUE THREAD

**Issue by danielkucera** [kubernetes/kubernetes#94722]
**What happened**:

Scheduler doesn't plan DaemonSet pods to nodes with taints although there is namespace wide default toleration defined, see configs:
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator": "Equal", "effect":"NoSchedule",
      "key":"security_zone", "value":"dmz"}]'
  name: keepalived-operator
```
```
$ kubectl get ds keepalived-dmz -n keepalived-operator
NAME             DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR       AGE
keepalived-dmz   0         0         0       0            0           security_zone=dmz   27m
```
```
$ kubectl get nodes -l security_zone=dmz -o custom-columns=name:metadata.name,taints:spec.taints
name         taints
dmzworker1   [map[effect:NoSchedule key:security_zone value:dmz]]
dmzworker2   [map[effect:NoSchedule key:security_zone value:dmz]]
```

**What you expected to happen**:

Pods scheduled to nodes with taints.

**How to reproduce it (as minimally and precisely as possible)**:

- configure taint on one node
- add defaultTolerations to namespace
- create daemonset

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.1+9d33dd3", GitCommit:"9d33dd3", GitTreeState:"clean", BuildDate:"2020-06-21T18:17:38Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
vSphere
- OS (e.g: `cat /etc/os-release`):
Red Hat Enterprise Linux CoreOS 44.81.202006220834-0 (Ootpa)
- Kernel (e.g. `uname -a`):
 4.18.0-147.20.1.el8_1.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
The namespace tolerations only apply to pods as they are created. The scheduler does not look at those. Expanding the scheduler to incorporate these is more of a feature than a bug

**Comment by danielkucera** [comment]
@liggitt then what's the difference between Deployment and DaemonSet when Deployment respects them?

**Comment by liggitt** [comment]
Deployments don't respect those namespace annotations, they just produce replicasets, which produce pods. The admission plugin sets tolerations on the pod objects based on the namespace annotations as the pods are created. The scheduler honors the tolerations on the pods.

**Comment by danielkucera** [comment]
I see now. I've found the code where DeamonSet rules out nodes which doesn't fit the tolerations from DS template:
https://github.com/kubernetes/kubernetes/blob/e6287b05c0bfcf6b0ecf098ba83a231625522f1f/pkg/controller/daemon/daemon_controller.go#L1339
So there is no pod created and cannot be evaluated in the admission plugin.

Wouldn't it be more systematic to leave this work on scheduler as there can be plugins which may want to modify the decision?

**Comment by soulxu** [comment]
It also can be done by add toleration to the pod at

https://github.com/kubernetes/kubernetes/blob/51184187b9cc8e54bb51dc921bfb80de3d638635/pkg/controller/daemon/util/daemonset_util.go#L49

when the `PodTolerationRestriction` admission plugin enabled

**Comment by liggitt** [comment]
> Wouldn't it be more systematic to leave this work on scheduler as there can be plugins which may want to modify the decision?

That would result in unschedulable pods for all the tainted nodes whenever the pod was created as-is without something injecting a toleration. I would defer to the scheduling and scalability teams to determine if that is acceptable overhead.

> It also can be done by add toleration to the pod at kubernetes/pkg/controller/daemon/util/daemonset_util.go when the PodTolerationRestriction admission plugin enabled

I would not expect to make the daemonset controller aware of that admission plugin. It runs in a separate process and doesn't have visibility to enablement of that admission plugin, and as @danielkucera points out, other webhook admission plugins could make similar adjustments, so special-casing one integration doesn't seem great.

**Comment by danielkucera** [comment]
/remove-lifecycle rotten
no way my friend

**Comment by danielkucera** [comment]
Whatever... Your problem...

**Comment by dannysauer** [comment]
This was seemingly deferred

> to the scheduling and scalability teams

by @liggitt , but then seemingly dropped on the floor.  Was the problem solved elsewhere without linking to this issue?  I stumbled across this as a way to avoid having to add tolerations to every daemonset I create, instead preferring to just put them in a common namespace.  I'm leaving knowing little more than I knew before about good solutions to my problem. :)

**Comment by yogeek** [comment]
is it possible to re-open this issue please ?
