### ISSUE TITLE
Event from events group not cleanly separated from core group

### ISSUE THREAD

**Issue by tengqm** [kubernetes/kubernetes#94748]
**What happened**:

When I tried create an Event resource in `events.k8s.io/v1` group, I found that the following fields are required:

```json
  "required": [
    "action",
    "apiVersion",
    "eventTime",
    "kind",
    "metadata",
    "reason",
    "regarding",
    "reportingController",
    "reportingInstance",
    "type"
  ]
```

but our API spec failed to convey the accurate information. Some more interesting phenomena I observed:

- The `eventTime` has to be something like `2020-09-11T02:42:23.123456Z`. A RFC3339 string `2020-09-11T02:42:23Z` is always rejected.  The error message is:
   ```
   unmarshalerDecoder: parsing time "2020-09-11T02:42:23Z" as "2006-01-02T15:04:05.000000Z07:00": cannot parse "Z" as ".000000", error found in #10 byte of ...
   ```
   Not a big deal but it is something we want to improve.
- If I'm not specifying the `regarding` field, the error message is something like
  ```
   involvedObject.namespace: Invalid value: "": does not match event.namespace
  ```
  So I tried specifying the `regarding` field instead, the error is gone.

**What you expected to happen**:

The Event type may needs its own definition in the `events` group. Sharing the same definition and validation code with the `core` group may have some problems in addition to what I have discovered from purely API perspective.

**How to reproduce it (as minimally and precisely as possible)**:

Define a minimal YAML by following the API spec.

```yaml
apiVersion: events.k8s.io/v1
kind: Event
```

Then step by step, try `kubectl create -f` with errors.

**Comment by fedebongio** [comment]
/assign @wojtek-t 
would you mind taking a look to this one? thanks!

**Comment by wojtek-t** [comment]
Addressed by https://github.com/kubernetes/kubernetes/pull/94910
