### ISSUE TITLE
k8s 1.19 - Cannot exec commands in running containers with --tty option with cri-o as runtime

### ISSUE THREAD

**Issue by kubealex** [kubernetes/kubernetes#94750]
**What happened**:
K8s 1.19 fresh install with cri-o 1.18.3, following the documentation.

**What you expected to happen**:

Being able to execute commands in a running container

**How to reproduce it (as minimally and precisely as possible)**:

Install k8s 1.19 with kubeadm
Use cri-o as runtime
launch "kubectl exec -it calico-node-58rdv -n kube-system /bash" or any other command in any other container 

error: Internal error occurred: error executing command in container: fork/exec /usr/bin/runc: Setctty set but Ctty not valid in child

Running crictl exec has the same output:

sudo crictl exec -it 968e74ed4204f bash
FATA[0000] execing command in container failed: Internal error occurred: error executing command in container: fork/exec /usr/bin/runc: Setctty set but Ctty not valid in child

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19
- Cloud provider or hardware configuration: VM with 4 vcp and 16g ram
- OS (e.g: `cat /etc/os-release`): CentOS 7
- Kernel (e.g. `uname -a`): Linux k8s-worker-2.k8s.lab 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): calico
- Others:

**Comment by saschagrunert** [comment]
Xref: https://github.com/cri-o/cri-o/issues/4189
Maybe related: https://github.com/cri-o/cri-o/issues/4189

**Comment by kubealex** [comment]
Confirm, it was related to cri-o reference. 
Closed the related issue, tested with cri-o 1.19 release, thank you.
