### ISSUE TITLE
Kubectl create deployment

### ISSUE THREAD

**Issue by saurabhIU** [kubernetes/kubernetes#94755]
While creating deployment with Kubectl , Command and argument is not working. I am using version 1.18. Attached are the screenshots.

As per the Kubectl Create command [https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-deployment-em-](url) , I should be able to pass in commands and arguments. Either the reference document is wrong or I am missing something.

![Screen Shot 2020-09-13 at 11 15 14 AM](https://user-images.githubusercontent.com/22183178/93025397-7f7b6b00-f5b2-11ea-8c3c-aea650b5bf3e.png)
![Screen Shot 2020-09-13 at 11 15 40 AM](https://user-images.githubusercontent.com/22183178/93025400-84d8b580-f5b2-11ea-821f-de33649cd5cf.png)

**Comment by neolit123** [comment]
/sig cli
/remove triage-support
/kind documentation

i confirmed that [here](https://www.katacoda.com/courses/kubernetes/playground) with 1.18.0, that `kubectl create deployment my-dep --image=busybox -- date` does not create a deployment with the `date` command, so if this way of imputing a command was removed the reference documentation has to be updated:

> Create a deployment with command
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-deployment-em-

**Comment by pacoxu** [comment]
`  # Start the nginx pod using the default command, but use custom arguments (arg1 .. argN) for that command.
  kubectl run nginx --image=nginx -- <arg1> <arg2> ... <argN> `

You can add args after "kubectl run ", but not "kubectl create"

```
[root@master-dce3 ~]# kubectl create deployment my-dep --image=busybox --help
Create a deployment with the specified name.

Aliases:
deployment, deploy

Examples:
  # Create a new deployment named my-dep that runs the busybox image.
  kubectl create deployment my-dep --image=busybox

Options:
      --allow-missing-template-keys=true: If true, ignore any errors in templates when a field or map key is missing in
the template. Only applies to golang and jsonpath output formats.
      --dry-run='none': Must be "none", "server", or "client". If client strategy, only print the object that would be
sent, without sending it. If server strategy, submit server-side request without persisting the resource.
      --image=[]: Image name to run.
  -o, --output='': Output format. One of:
json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-file.
      --save-config=false: If true, the configuration of current object will be saved in its annotation. Otherwise, the
annotation will be unchanged. This flag is useful when you want to perform kubectl apply on this object in the future.
      --template='': Template string or path to template file to use when -o=go-template, -o=go-template-file. The
template format is golang templates [http://golang.org/pkg/text/template/#pkg-overview].
      --validate=true: If true, use a schema to validate the input before sending it

Usage:
  kubectl create deployment NAME --image=image [--dry-run=server|client|none] [options]

Use "kubectl options" for a list of global command-line options (applies to all commands).
```

**Comment by tengqm** [comment]
The reference doc is generated from the upstream source code. If you want fix this, please raise an issue in the kubernetes/kubernetes repo.

```
Usage:
  kubectl create deployment NAME --image=image -- [COMMAND] [args...] [options]
```

**Comment by tengqm** [comment]
The upstream source code is here:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/create/create_deployment.go#L96

**Comment by pacoxu** [comment]
> The upstream source code is here:
> 
> https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/create/create_deployment.go#L96

opened  #94763 
/assign

**Comment by zhouya0** [comment]
`kubectl create deployment -- [command]` start from 1.19:
Ref: https://github.com/kubernetes/kubernetes/pull/91113

**Comment by pacoxu** [comment]
@saurabhIU  Please check 1.18 docs in https://v1-18.docs.kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-deployment-em-

This is new feature in 1.19

**Comment by afirth** [comment]
/close
Sounds like this is new in 1.19 but you were using 1.18
Please reopen if I'm missing something
