### ISSUE TITLE
FailedMount due to MountVolume.WaitForAttach timed out waiting for condition

### ISSUE THREAD

**Issue by jakob-kr** [kubernetes/kubernetes#94764]
**What happened**:
MountVolume ran into timeout while trying to mount a PVC to a pod on Azure.
The pod events show `MountVolume.WaitForAttach ... timed out waiting for condition`.
After ~6 hours the volume got attached successfully.

**What you expected to happen**:
The volume should be mounted without timeout.

**How to reproduce it (as minimally and precisely as possible)**:
- Delete the pod by setting replicas of custom resource to 0
- Delete the pvc
- Get a new pod created by setting replicas to 1 in the custom resource
- Wait for pod coming up
- Repeat until pod doesn't come up and stays in ContainerCreating status showing a FailedMount event

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.14
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): SLES 15.1 (suse-chost)
- Kernel (e.g. `uname -a`): 4.12.14-197.37-default
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by jakob-kr** [comment]
Kubelet logs:

`I0909 17:28:29.377212    4600 operation_generator.go:661] MountVolume.WaitForAttach entering for volume "<pvc_name>" (UniqueName: "kubernetes.io/azure-disk//subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Compute/disks/<disk_name>") pod "prometheus-prometheus-0" (UID: "<uid>") DevicePath "1"`

`E0909 17:38:31.353608    4600 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/azure-disk//subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Compute/disks/<disk_name> podName: nodeName:}" failed. No retries permitted until 2020-09-09 17:40:33.353562183 +0000 UTC m=+36545.516186045 (durationBeforeRetry 2m2s). Error: "MountVolume.WaitForAttach failed for volume \"<pvc_name>\" (UniqueName: \"kubernetes.io/azure-disk//subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Compute/disks/<disk_name>\") pod \"prometheus-prometheus-0\" (UID: \"<uid>\") : timed out waiting for the condition"
--`

After 6 hours:
`E0909 18:37:34.876850   19967 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/azure-disk//subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Compute/disks/<disk_name> podName: nodeName:}" failed. No retries permitted until 2020-09-09 18:37:35.37680734 +0000 UTC m=+3.646989126 (durationBeforeRetry 500ms). Error: "Volume has not been added to the list of VolumesInUse in the node's volume status for volume \"<pvc_name>\" (UniqueName: \"kubernetes.io/azure-disk//subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Compute/disks/<disk_name>\") pod \"prometheus-prometheus-0\" (UID: \"<uid>\")
--`

`I0909 18:37:50.512024   19967 operation_generator.go:1422] Controller attach succeeded for volume "pvc_name" (UniqueName: "kubernetes.io/azure-disk//subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Compute/disks/<disk_name>") pod "prometheus-prometheus-0" (UID: "<uid>") device path: "1"`

`I0909 19:05:10.090646   84475 desired_state_of_world_populator.go:481] Found bound PV for PVC (ClaimName "default"/"prometheus-prometheus-db-prometheus-prometheus-0" pvcUID <uid>): pvName="<pv_name>"`

`I0909 19:15:42.206232   84475 operation_generator.go:670] MountVolume.WaitForAttach succeeded for volume "<pvc_name>" (UniqueName: "kubernetes.io/azure-disk//subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Compute/disks/<disk_name>") pod "prometheus-prometheus-0" (UID: "<uid>") DevicePath "/dev/disk/azure/scsi1/lun1"`

`I0909 19:15:42.652720   84475 operation_generator.go:697] MountVolume.MountDevice succeeded for volume "<pvc_name>" (UniqueName: "kubernetes.io/azure-disk//subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Compute/disks/<disk_name>") pod "prometheus-prometheus-0" (UID: "<uid>") device mount path "/var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/m2966595132"
...`

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/blob/e23d83eead3b5ae57731afb0209f4a2aaa4009dd/pkg/kubelet/volumemanager/volume_manager.go#L92

the timeout seems to be a 10 minutes timeout here

**Comment by andyzhangx** [comment]
/sig cloud-provider
/area provider/azure
is this still an issue now?

**Comment by jakob-kr** [comment]
I don't know if the issue still occurs, at least it was not reported to me again in the last month.
From my side this can be closed for now, I will reopen it if it happens again.

**Comment by rendhalver** [comment]
I just ran into this in a recently upgraded 1.16.7 cluster running in Azure.
Was there a fix in progress?

**Comment by andyzhangx** [comment]
> I just ran into this in a recently upgraded 1.16.7 cluster running in Azure.
> Was there a fix in progress?

@rendhalver can you paste detailed pod description events? If that disk is already attached to the node, while it could not be recognized, then it could be vm level issue, need to provide more details: https://github.com/andyzhangx/demo/blob/master/linux/azuredisk/azuredisk-attachment-debugging.md

**Comment by rendhalver** [comment]
Apologies, this may have been a false alarm.
I only saw the issue with the install we have of prometheus-operator.
I was upgrading from v5.13.1 to v6.2.1 of the Chart.
Later versions of the Chart didn't have the problem.
I tried to replicate the issue with other StatefulSets and Deployments but they had no issues either.

**Comment by Mitali-Y-sap** [comment]
We are observing the same issue and its happening more frequently in our setup. Steps are similar to what @jakob-kr  has mentioned in the issue description except that we are not deleting the PVCs or PVs but we are creating and deleting pod in a loop.

1) Kubelet log during PVC mount failure (`<pvc1>` (aka azure managed disk `<disk1>`) is unable to mount):
```
I0201 09:44:03.654938    4818 reconciler.go:254] operationExecutor.MountVolume started for volume "<pvc1>" (UniqueName: "kubernetes.io/azure-disk//subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Compute/disks/<disk1>") pod "<pod>" (UID: "<uid>")
...
I0201 09:44:03.655140    4818 operation_generator.go:551] MountVolume.WaitForAttach entering for volume "<pvc1>" (UniqueName: "kubernetes.io/azure-disk//subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Compute/disks/<disk1>") pod "<pod>" (UID: "<uid>") DevicePath "3"
...
E0201 09:45:21.233550    4818 kubelet.go:1683] Unable to attach or mount volumes for pod "<pod>": unmounted volumes=[<pvc1>], unattached volumes=[<other volumes>]: timed out waiting for the condition
```

2) Based on the debug link that @andyzhangx has posted ([https://github.com/andyzhangx/demo/blob/master/linux/azuredisk/azuredisk-attachment-debugging.md](https://github.com/andyzhangx/demo/blob/master/linux/azuredisk/azuredisk-attachment-debugging.md)), we also collected:
i) The disk status shown under the node details:
```
$ kubectl get node <node> -o yaml | grep volumesAttached -A 50
  volumesAttached:
  - devicePath: "3"
    name: kubernetes.io/azure-disk//subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Compute/disks/<disk1>
  - devicePath: "0"
    name: kubernetes.io/azure-disk//subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Compute/disks/<disk2>
  - devicePath: "1"
    name: kubernetes.io/azure-disk//subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Compute/disks/<disk3>
  - devicePath: "2"
    name: kubernetes.io/azure-disk//subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Compute/disks/<disk4>
  volumesInUse:
  - kubernetes.io/azure-disk//subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Compute/disks/<disk1>
  - kubernetes.io/azure-disk//subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Compute/disks/<disk2>
  - kubernetes.io/azure-disk//subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Compute/disks/<disk3>
  - kubernetes.io/azure-disk//subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Compute/disks/<disk4>
```
We can see 4 azure managed disks are attached to the node.

ii) Entered inside the node, check what azure managed disks were mounted.
```
$ kubectl-enter <node>
<node>:/ # ls -l /dev/disk/azure/*
lrwxrwxrwx 1 root root   9 Feb  1 11:09 /dev/disk/azure/resource -> ../../sdb
lrwxrwxrwx 1 root root  10 Feb  1 11:09 /dev/disk/azure/resource-part1 -> ../../sdb1
lrwxrwxrwx 1 root root   9 Feb  1 11:09 /dev/disk/azure/root -> ../../sda
lrwxrwxrwx 1 root root  10 Feb  1 11:09 /dev/disk/azure/root-part1 -> ../../sda1
lrwxrwxrwx 1 root root  10 Feb  1 11:09 /dev/disk/azure/root-part2 -> ../../sda2
lrwxrwxrwx 1 root root  10 Feb  1 11:09 /dev/disk/azure/root-part3 -> ../../sda3
lrwxrwxrwx 1 root root  10 Feb  1 11:09 /dev/disk/azure/root-part4 -> ../../sda4
/dev/disk/azure/scsi1:
total 0
lrwxrwxrwx 1 root root 12 Feb  1 11:09 lun0 -> ../../../sdc     |<- We can see only 3 azure managed disks are mounted
lrwxrwxrwx 1 root root 12 Feb  1 11:09 lun1 -> ../../../sdd     |   inside Azure node
lrwxrwxrwx 1 root root 12 Feb  1 11:09 lun2 -> ../../../sde     |

<node>:/ # df -hT /dev/sd*
Filesystem Type Size Used Avail Use% Mounted on
...
/dev/sdc ext4 32G 32G 16M 100% /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/m3467332939
/dev/sdd ext4 32G 32G 16M 100% /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/m3508444875
/dev/sde ext4 32G 32G 16M 100% /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/m3894707421
```
Note here we can see out of 4 azure managed disks only 3 azure disks (`<disk2>`, `<disk3>`, `<disk4>`) were mounted.


3) After around 4.5 hrs it was able to mount the `<disk1>` into the node successfully:
Kubelet logs after successfully mounting of `<disk1>`:
```
I0201 14:21:04.628809    4818 reconciler.go:254] operationExecutor.MountVolume started for volume "<pvc1>" (UniqueName: "kubernetes.io/azure-disk//subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Compute/disks/<disk1>") pod "<pod>" (UID: "<uid>")
...
I0201 14:21:04.629092    4818 operation_generator.go:551] MountVolume.WaitForAttach entering for volume "<pvc1>" (UniqueName: "kubernetes.io/azure-disk//subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Compute/disks/<disk1>") pod "<pod>" (UID: "<uid>") DevicePath "3"
...
I0201 14:21:05.382228    4818 operation_generator.go:560] MountVolume.WaitForAttach succeeded for volume "<pvc1>" (UniqueName: "kubernetes.io/azure-disk//subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Compute/disks/<disk1>") pod "<pod>" (UID: "<uid>") DevicePath "/dev/disk/azure/scsi1/lun3"
I0201 14:21:05.627603    4818 operation_generator.go:587] MountVolume.MountDevice succeeded for volume "<pvc1>" (UniqueName: "kubernetes.io/azure-disk//subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Compute/disks/<disk1>") pod "<pod>" (UID: "<uid>") device mount path "/var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/m1938088991"
...
I0201 14:21:05.697667    4818 azure_mounter.go:170] azureDisk - successfully mounted disk <disk1> on /var/lib/kubelet/pods/<uid>/volumes/kubernetes.io~azure-disk/<disk1>
...
I0201 14:21:05.697730    4818 operation_generator.go:634] MountVolume.SetUp succeeded for volume "<pvc1>" (UniqueName: "kubernetes.io/azure-disk//subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Compute/disks/<disk1>") pod "<pod>" (UID: "<uid>")
```

4) Again entering into the node to see the mounted disks:
```
$ kubectl-enter <node>
<node>:/ # ls -l /dev/disk/azure/*
lrwxrwxrwx 1 root root   9 Feb  1 11:09 /dev/disk/azure/resource -> ../../sdb
lrwxrwxrwx 1 root root  10 Feb  1 11:09 /dev/disk/azure/resource-part1 -> ../../sdb1
lrwxrwxrwx 1 root root   9 Feb  1 11:09 /dev/disk/azure/root -> ../../sda
lrwxrwxrwx 1 root root  10 Feb  1 11:09 /dev/disk/azure/root-part1 -> ../../sda1
lrwxrwxrwx 1 root root  10 Feb  1 11:09 /dev/disk/azure/root-part2 -> ../../sda2
lrwxrwxrwx 1 root root  10 Feb  1 11:09 /dev/disk/azure/root-part3 -> ../../sda3
lrwxrwxrwx 1 root root  10 Feb  1 11:09 /dev/disk/azure/root-part4 -> ../../sda4
/dev/disk/azure/scsi1:
total 0
lrwxrwxrwx 1 root root 12 Feb  1 11:09 lun0 -> ../../../sdc     |<- We can see now 4 azure managed disks are mounted
lrwxrwxrwx 1 root root 12 Feb  1 11:09 lun1 -> ../../../sdd     |   inside Azure node
lrwxrwxrwx 1 root root 12 Feb  1 11:09 lun2 -> ../../../sde     |
lrwxrwxrwx 1 root root 12 Feb  1 14:21 lun3 -> ../../../sdf     |

<node>:/ # df -hT /dev/sd*
Filesystem     Type      Size  Used Avail Use% Mounted on
...
/dev/sdc       ext4       32G   32G   16M 100% /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/m3467332939
/dev/sdd       ext4       32G   32G   16M 100% /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/m3508444875
/dev/sde       ext4       32G   32G   16M 100% /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/m3894707421
/dev/sdf       ext4       32G   32G   16M 100% /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/m1938088991
```
Note this time we can see all the 4 azure managed disks are mounted successfully.

**Comment by MSSedusch** [comment]
I believe this issue is fixed with https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/797

**Comment by andyzhangx** [comment]
> I believe this issue is fixed with [kubernetes-sigs/azuredisk-csi-driver#797](https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/797)

that means the node with problem is actually in `failed` state, disk attach return succeed while actually that disk is not attached?

**Comment by MSSedusch** [comment]
basically yes. The disk attach does not return success but fails, the second attach attempt from cloud controller is not attempted because the disk is already part of the goal state of the VM. With your fix, the second attempt is executed because now the cloud controller also looks at the VM state. @jakob-kr is from the same team I was working with to analyze the issue.

**Comment by andyzhangx** [comment]
this issue was already fixed in Azure Disk CSI driver: https://github.com/kubernetes-sigs/azuredisk-csi-driver/releases/tag/v1.2.0
