### ISSUE TITLE
docs: The default PV Reclaim Policy is different with the document

### ISSUE THREAD

**Issue by scbizu** [kubernetes/kubernetes#94798]
**What would you like to be added**:

Change the default PV Reclaim Policy in the codebase or the document

**Why is this needed**:

Really misunderstanding when we just read the document and use the api package .

### The main issue 

The default PV Reclaim Policy documented [here](https://kubernetes.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/#why-change-reclaim-policy-of-a-persistentvolume) is `Delete` ,  but the real default Reclaim Policy we use is `Retain` which defined [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L386). It seems that the document is not correct anymore ?

/sig docs

**Comment by wawa0210** [comment]
> The default PV Reclaim Policy documented here is Delete

This should refer to dynamic-provisioning
https://kubernetes.io/blog/2017/03/dynamic-provisioning-and-storage-classes-kubernetes/

**Comment by scbizu** [comment]
> > The default PV Reclaim Policy documented here is Delete
> 
> This should refer to dynamic-provisioning
> https://kubernetes.io/blog/2017/03/dynamic-provisioning-and-storage-classes-kubernetes/

Still `Delete` not `Retain`?

**Comment by knight42** [comment]
According to the comment here: https://github.com/kubernetes/kubernetes/blob/e36e68f5f6964a3e612b36bfea0bb17c8f05e083/staging/src/k8s.io/api/core/v1/types.go#L343-L349

The default policy is `Retain` when pv is manually created and `Delete` when  dynamically provisioned.

/remove-kind feature

**Comment by scbizu** [comment]
OK ,  docs here https://kubernetes.io/docs/concepts/storage/persistent-volumes/#delete is correct , thanks for your time @knight42 .
