### ISSUE TITLE
pod is ContainerCreating for long time when create a pod in large cluster while kubelet report configmap is forbidden

### ISSUE THREAD

**Issue by yuanhuaiwang** [kubernetes/kubernetes#94795]
**What happened**:
create a pod with a new configmap as volume in a large cluster(node more than 10k, pod more then 100k), the pod's status is ContainerCreating for a long time more than 1 hour, after long time or scale down the number of pods, this pod will change status to Running
`Warning  FailedMount  2m18s                 kubelet, nodexx  Unable to mount volumes for pod "test-jialuo_default(ba526e46-f71c-11ea-aa2c-5254003f2346)": timeout expired waiting for volumes to attach or mount for pod "default"/"test-jialuo". list of unmounted volumes=[test]. list of unattached volumes=[test default-token-n58rd]
  Warning  FailedMount  10s (x10 over 4m21s)  kubelet, nodexx  MountVolume.SetUp failed for volume "test" : configmaps "confign1" is forbidden: User "system:node:nodexx" cannot get resource "configmaps" in API group "" in the namespace "default": no relationship found between node "nodexx" and this object`
while the configmap is exist
`confign1   3      159m`
`test-jialuo       0/1     ContainerCreating   0          40m`
When this happens it usually affects multiple, but not all pods, and it affects multiple nodes at the same time.
**What you expected to happen**:
the status of pod should not stay at ContainerCreating stale for long time
**How to reproduce it (as minimally and precisely as possible)**:
create a large fake cluster (node 10k, pod 100k  )
create a new configmap
create a real pod with configmap
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):v1.14.4
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):CentOS-7
- Kernel (e.g. `uname -a`):4.19.95-13 x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by yuanhuaiwang** [comment]
> **What happened**:
> create a pod with a new configmap as volume in a large cluster(node more than 10k, pod more then 100k), the pod's status is ContainerCreating for a long time more than 1 hour, after long time or scale down the number of pods, this pod will change status to Running
> `Warning FailedMount 2m18s kubelet, nodexx Unable to mount volumes for pod "test-jialuo_default(ba526e46-f71c-11ea-aa2c-5254003f2346)": timeout expired waiting for volumes to attach or mount for pod "default"/"test-jialuo". list of unmounted volumes=[test]. list of unattached volumes=[test default-token-n58rd] Warning FailedMount 10s (x10 over 4m21s) kubelet, nodexx MountVolume.SetUp failed for volume "test" : configmaps "confign1" is forbidden: User "system:node:nodexx" cannot get resource "configmaps" in API group "" in the namespace "default": no relationship found between node "nodexx" and this object`
> while the configmap is exist
> `confign1 3 159m`
> When this happens it usually affects multiple, but not all pods, and it affects multiple nodes at the same time.
> **What you expected to happen**:
> the status of pod should not stay at ContainerCreating stale for long time
> **How to reproduce it (as minimally and precisely as possible)**:
> create a large fake cluster (node 10k, pod 100k )
> create a new configmap
> create a real pod with configmap
> **Anything else we need to know?**:
> 
> **Environment**:
> 
> * Kubernetes version (use `kubectl version`):v1.14.4
> * Cloud provider or hardware configuration:
> * OS (e.g: `cat /etc/os-release`):CentOS-7
> * Kernel (e.g. `uname -a`):4.19.95-13 x86_64
> * Install tools:
> * Network plugin and version (if this is a network-related bug):
> * Others:

> /sig auth

**Comment by yuanhuaiwang** [comment]
> @yuanhuaiwang: There are no sig labels on this issue. Please add an appropriate label by using one of the following commands:
> 
> * `/sig <group-name>`
> * `/wg <group-name>`
> * `/committee <group-name>`
> 
> Please see the [group list](https://git.k8s.io/community/sig-list.md) for a listing of the SIGs, working groups, and committees available.

> * `/sig auth`

**Comment by yuanhuaiwang** [comment]
> @yuanhuaiwang: There are no sig labels on this issue. Please add an appropriate label by using one of the following commands:
> 
> * `/sig <group-name>`
> * `/wg <group-name>`
> * `/committee <group-name>`
> 
> Please see the [group list](https://git.k8s.io/community/sig-list.md) for a listing of the SIGs, working groups, and committees available.

> /sig auth

**Comment by yuanhuaiwang** [comment]
> > @yuanhuaiwang: There are no sig labels on this issue. Please add an appropriate label by using one of the following commands:
> > 
> > * `/sig <group-name>`
> > * `/wg <group-name>`
> > * `/committee <group-name>`
> > 
> > Please see the [group list](https://git.k8s.io/community/sig-list.md) for a listing of the SIGs, working groups, and committees available.
> 
> > * `/sig <auth>`



> > @yuanhuaiwang: There are no sig labels on this issue. Please add an appropriate label by using one of the following commands:
> > 
> > * `/sig <group-name>`
> > * `/wg <group-name>`
> > * `/committee <group-name>`
> > 
> > Please see the [group list](https://git.k8s.io/community/sig-list.md) for a listing of the SIGs, working groups, and committees available.
> 
> /sig node

**Comment by yuanhuaiwang** [comment]
> /sig node
> /sig api-machinery

**Comment by liggitt** [comment]
Releases older than 1.17 are no longer supported. In 1.18, dramatic improvements were made to the performance of the node authorizer, which likely resolves this issue. Is this able to be reproduced on 1.18 or newer?

**Comment by yuanhuaiwang** [comment]
yeah, i cherry-pick the commits of 1.18 pr and have resolved this problem, thank you very much

**Comment by liggitt** [comment]
glad that worked for you.

/close
