### ISSUE TITLE
Metadata Concealment test exercises endpoints due to be removed 2020-09-30

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#94791]
https://cloud.google.com/compute/docs/migrating-to-v1-metadata-server

>Warning: The v0.1 and v1beta1 metadata server endpoints are deprecated and scheduled for shutdown on September 30, 2020.

This test (which runs in most e2e jobs that run on GCE): https://github.com/kubernetes/kubernetes/blob/master/test/e2e/auth/metadata_concealment.go#L34

Schedules a container that runs this: https://github.com/kubernetes/kubernetes/blob/master/test/images/metadata-concealment/check_metadata_concealment.go

Resulting in a number of legacy metadata endpoints getting hit.

To see if this test is going to start failing across all release branches on Sep 30th, we could try disabling the endpoints ahead of time via: https://cloud.google.com/compute/docs/storing-retrieving-metadata#disable-legacy-endpoints. In fact https://github.com/kubernetes/kubernetes/pull/69593 and https://github.com/kubernetes/kubernetes/pull/70253 added support for expecting different results based on whether `disable-legacy-endpoints` is set.  

My concern is the test expects 200 for some root endpoints, and 403 for disabled endpoints. However the e-mail I received as a GCP customer tells me any legacy endpoints may return 404.

I'm inclined to suggest we remove the legacy endpoints from the check, bump the image version, and cherry-pick use of the new image version back to all release-branches.

WDYT @dekkagaijin @ixdy @idealhack @mikedanese since you were involved with the earlier PRs
@kubernetes/sig-auth-misc 
/sig auth
/sig cloud-provider
/provider gcp
/sig testing
/priority important-soon
(I'm tempted to critical-urgent this but it's not drop-everything yet)
/milestone v1.20

**Comment by mkorbi** [comment]
Heyho @spiffxp  I wanted to check how it is going?
The code freeze is starting 12.11.2020 (about 3-4 weeks from now) and while there is still plenty of time, we want to ensure that each relevant issue has a chance to be considered.

As the issue is tagged for 1.20, is it still planned for this release?

**Comment by erismaster** [comment]
👋  Bug Triage here, we're pretty late into code freeze and it doesn't look like there has been much activity recently. I am going to clear the milestone on this issue. 

/milestone clear

**Comment by liggitt** [comment]
any update here?

**Comment by pacoxu** [comment]
Try to cleanup the legacy endpoints in #97789

**Comment by spiffxp** [comment]
/reopen
@pacoxu This needs to stay open until the new image has been verified to work and has been promoted (ref: https://github.com/kubernetes/kubernetes/pull/97789#issuecomment-763977809)
