### ISSUE TITLE
kubeadm init phase upload-config: questions about annotation kubeadm.alpha.kubernetes.io/cri-socket

### ISSUE THREAD

**Issue by zhanw15** [kubernetes/kubernetes#94793]
Guys, I has two questions about the follow step:
https://github.com/kubernetes/kubernetes/blob/37cf1d6aaa5c5d0dba6e545a70d91e77d730e478/cmd/kubeadm/app/cmd/phases/init/uploadconfig.go#L127-L130

- Why add the annotation `kubeadm.alpha.kubernetes.io/cri-socket=xxx` for nodes, and where is it used ?
- I think it shoudn't add the annotations this step, because this phase is used to upload-config, not related with nodes. May be more appropriate to add the annotation at `kubeadm init phase mark-control-plane`

**Comment by zhanw15** [comment]
@neolit123 Can you explain for me ? I want use `kubeadm init phase upload-config` create rbac and upload config, but I don't have a node named myhostname. I think is more appropriate do it at `kubeadm init phase mark-control-plane`.

**Comment by neolit123** [comment]
Its the kubelet that would create the Node object.

**Comment by neolit123** [comment]
duplicate of:
https://github.com/kubernetes/kubeadm/issues/1924

/close
