### ISSUE TITLE
Scheduler Plugins: Node order in NodeScoreList can change in calls to Normalize

### ISSUE THREAD

**Issue by zorro786** [kubernetes/kubernetes#94808]
**What happened**: The score of some nodes after normalizing were swapped

**What you expected to happen**: Scores remain as it is per node name

**How to reproduce it (as minimally and precisely as possible)**: Modify the order of `scores` in the call to `NormalizeScore(ctx context.Context, state *framework.CycleState, pod *v1.Pod, scores framework.NodeScoreList)`

**Anything else we need to know?**:
The problem lies in the following code:

```
	for i := range nodes {
		result = append(result, framework.NodeScore{Name: nodes[i].Name, Score: 0})
		for j := range scoresMap {
			result[i].Score += scoresMap[j][i].Score
		}
	}
```
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/core/generic_scheduler.go#L521
Here it implicitly assumes that `scoresMap[j][i].Name == nodes[i].Name`
**Environment**:
- Kubernetes version (use `kubectl version`): All containing the above code, starting from master branch and older releases
- Cloud provider or hardware configuration: NA
- OS (e.g: `cat /etc/os-release`): NA
- Kernel (e.g. `uname -a`): NA
- Install tools: NA
- Network plugin and version (if this is a network-related bug): NA
- Others: NA

**Comment by zorro786** [comment]
@ahg-g If this bug is valid, I would like to submit a fix for this.

**Comment by adtac** [comment]
I don't think the scheduler expects the plugin to switch order of scores in NormalizeScore, so I believe the plugin is at fault here. Is this happening with an in-tree scoring plugin?

**Comment by zorro786** [comment]
I see framework at fault for two reasons:

1) Scheduler shouldn't depend on the order of scores returned by the plugins IMO. Normalization can involve several things including sorting etc. that can change the order of scores.
2) Since plugins are exposed to users this needs to be taken care in the framework as defensive programming.

Not happening with in-tree scoring plugin.

**Comment by adtac** [comment]
>Since plugins are exposed to users this needs to be taken care in the framework as defensive programming.

Plugins are assumed to be trusted. For example, any plugin can modify the cycle state data of any other plugin.

**Comment by zorro786** [comment]
Thats's right. By defensive programming I meant inadvertent errors.

**Comment by ahg-g** [comment]
I agree with @adtac, I can't think of a reason why one would want to reorder the list in NormalizeScore. I think we can address this with proper documentation. The [comment](https://github.com/kubernetes/kubernetes/blob/303810c7a22d6dc4f940d7e183f7b0518c00569a/pkg/scheduler/framework/v1alpha1/interface.go#L308) on NormalizeScore already explains that "A successful run of NormalizeScore will update the scores list and return a success status.".

**Comment by zorro786** [comment]
@ahg-g Already mentioned one reason above - sorting. The comment just reinforces it is okay to "update" the list. Definition of update includes reordering of elements. 

If this is strictly not intended then I am okay with documenting it properly too -> where updating doesn't include reordering elements.

**Comment by ahg-g** [comment]
> @ahg-g Already mentioned one reason above - sorting

My question is for what purpose.

> The comment just reinforces it is okay to "update" the list

We need to update the docs, but the intention was "update the scores in the list"

**Comment by zorro786** [comment]
> > @ahg-g Already mentioned one reason above - sorting
> 
> My question is for what purpose.
> 
I have a custom algorithm where I normalize different ranges of scores separately, for this I need to sort the scores for efficiency. While I can also do this by placing sorted elements in a new list, I used existing list.
