### ISSUE TITLE
The kubelet should skip hostpath check if the type is empty

### ISSUE THREAD

**Issue by cheyang** [kubernetes/kubernetes#94826]
**What happened**:

1. The user of kubelet don't have authority to run stat command(permission denied) in the specified directory
2. Then I deploy the pod with hostpath volume，it's failed due to the kubelet can't access the target directory
3.but according to the document， if it’s empty string, no checks will be performed, but seems it doesn’t work: https://kubernetes.io/docs/concepts/storage/volumes/#hostpath
4. I think it’s not supported in source code level : https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/hostpath/host_path.go#L436

**What you expected to happen**:

I think it should work as document described. No checks if not hostpath type specified. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by dixudx** [comment]
> No checks if not hostpath type specified.

Right. Pls refer to below code.

https://github.com/kubernetes/kubernetes/blob/3fd5f367d698bd59460adf8a05b77e2c419d9d50/pkg/volume/hostpath/host_path.go#L235-L238

No check will be performed if `HostPathType` is unset. @cheyang

**Comment by ZihanJiang96** [comment]
> > No checks if not hostpath type specified.
> 
> Right. Pls refer to below code.
> 
> https://github.com/kubernetes/kubernetes/blob/3fd5f367d698bd59460adf8a05b77e2c419d9d50/pkg/volume/hostpath/host_path.go#L235-L238
> 
> No check will be performed if `HostPathType` is unset. @cheyang

I would like to fix this if this is a valid bug. But seems that we will skip the typecheck if the hostpath is unset.

**Comment by liggitt** [comment]
> according to the document， if it’s empty string, no checks will be performed

That means that the specified path can be any of file/dir/socket/block/char device, and is not required to already exist. It does not mean that the kubelet can mount a location without having permission to introspect the type and permissions of the item at that path.

> I would like to fix this if this is a valid bug.

This is not a valid bug. The kubelet must have access to the items it is expected to mount into containers.

**Comment by cheyang** [comment]
> 
> > I would like to fix this if this is a valid bug.
> 
> This is not a valid bug. The kubelet must have access to the items it is expected to mount into containers.

Kubelet doesn't have to access to  the hostpath of mount point, we just need to set 

```yaml
securityContext:
            runAsUser: 1000
            runAsGroup: 1000
```

And the uid 1000 has the permission to mount the volume to containers.

**Comment by liggitt** [comment]
Verifications the kubelet does to ensure unsafe symlinks are not followed and only supported types of files/directories/devices are mounted require the kubelet to have access to the item
