### ISSUE TITLE
CRI getFsInfo logs errors for valid filesystems mounted after kubelet start

### ISSUE THREAD

**Issue by paulnivin** [kubernetes/kubernetes#94825]
**What happened**:

New overlay filesystems created for Pods after kubelet start trigger repeated error messages. For example:

```
cri_stats_provider.go:375] Failed to get the info of the filesystem with mountpoint "/var/lib/containers/storage/overlay/2243263dc8ba6c55d8867d3e47bcaaa145d15f0ace19420824d639d86defe2e3/merged": failed to get device for dir "/var/lib/containers/storage/overlay/2243263dc8ba6c55d8867d3e47bcaaa145d15f0ace19420824d639d86defe2e3/merged": could not find device with major: 0, minor: 83 in cached partitions map.
```

Error messages are logged every 10 seconds for every filesystem created after kubelet start. For large kubelet nodes, this issue creates an excessive amount of error logs.

**What you expected to happen**:

New overlay filesystems created for Pods after kubelet start should not log error messages.

**How to reproduce it (as minimally and precisely as possible)**:

Use cri_stats_provider with cri-o and configure overlay storage. UsingLegacyCadvisorStats() needs to return false per https://github.com/cri-o/cri-o/pull/3054 for cri_stats_provider to be used. Start with an empty /var/lib/containers/storage and schedule Pods on the node.

**Anything else we need to know?**:

As part of https://github.com/kubernetes/kubernetes/pull/59475, cadvisor.GetFsInfoByFsUUID() was changed to cadvisor.GetDirFsInfo() in getFsInfo(); however, the test for cadvisorfs.ErrNoSuchDevice was not modified, changing how getFsInfo() handles a cache miss from cadvisor. 

cadvisor caches UUIDs/partitions/mounts on kubelet start and the cache is never refreshed. Given that it's expected that getFsInfo() will fail to retrieve data from cadvisor (see comments in ImageFsStats() and https://github.com/kubernetes/heapster/issues/1793), this condition should not be logged as an error. Alternatively, cadvisor fs could be modified to refresh on cache miss enabling getFsInfo() to return data on these filesystems.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.6
- CRI: CRI-O

**Comment by paulnivin** [comment]
/sig node
cc @mrunalp

**Comment by mrunalp** [comment]
@harche @haircommander ptal

**Comment by harche** [comment]
@paulnivin thanks for reporting the issue. 

I will take a look at in upcoming week.

**Comment by harche** [comment]
Sorry this is taking slightly longer. Currently held up in something little urgent, but as soon as that's over I will look into this one.

**Comment by r10r** [comment]
@harche Do you have the time to look at this issue ? I can help with testing / debugging if required.

Environment

* Kubernetes 1.19.3
* Cri-o 1.19.0

**Comment by harche** [comment]
Sorry I haven't gotten a chance to look into it yet, I would certainly appreciate any help in debugging. Thanks.

**Comment by harche** [comment]
Right now I am thinking of either handling the cache miss better,

```diff
diff --git a/pkg/kubelet/stats/cri_stats_provider.go b/pkg/kubelet/stats/cri_stats_provider.go
index 32802f9b823..9f2754f2310 100644
--- a/pkg/kubelet/stats/cri_stats_provider.go
+++ b/pkg/kubelet/stats/cri_stats_provider.go
@@ -370,7 +370,7 @@ func (p *criStatsProvider) getFsInfo(fsID *runtimeapi.FilesystemIdentifier) *cad
        fsInfo, err := p.cadvisor.GetDirFsInfo(mountpoint)
        if err != nil {
                msg := fmt.Sprintf("Failed to get the info of the filesystem with mountpoint %q: %v.", mountpoint, err)
-               if err == cadvisorfs.ErrNoSuchDevice {
+               if err == cadvisorfs.ErrNoSuchDevice || strings.Contains(err.Error(), "in cached partitions map") {
                        klog.V(2).Info(msg)
                } else {
                        klog.Error(msg)
```

or returning the `DeviceInfo` even if the fs type is not `btrfs` in cadvisor,

```diff
diff --git a/vendor/github.com/google/cadvisor/fs/fs.go b/vendor/github.com/google/cadvisor/fs/fs.go
index cb45c33c933..906f4a6e1c1 100644
--- a/vendor/github.com/google/cadvisor/fs/fs.go
+++ b/vendor/github.com/google/cadvisor/fs/fs.go
@@ -559,6 +559,10 @@ func (i *RealFsInfo) GetDirFsDevice(dir string) (*DeviceInfo, error) {
                mount, found = i.mounts[dir]
        }
 
+       if found && mount.FsType != "btrfs" && mount.Major != 0 && strings.HasPrefix(mount.Source, "/dev/") {
+               return &DeviceInfo{mount.Source, uint(mount.Major), mount.uint(mount.Minor)}, nil
+       }
+
        if found && mount.FsType == "btrfs" && mount.Major == 0 && strings.HasPrefix(mount.Source, "/dev/") {
                major, minor, err := getBtrfsMajorMinorIds(&mount)
                if err != nil {
```

**Comment by r10r** [comment]
kindly ping @harche - has this already been implemented ?

**Comment by saschagrunert** [comment]
Fix for k/k in https://github.com/kubernetes/kubernetes/pull/100448

**Comment by r10r** [comment]
hi @saschagrunert do you know when the fixes will be released ? Thanks!

**Comment by saschagrunert** [comment]
> hi @saschagrunert do you know when the fixes will be released ? Thanks!

I don't, unfortunately.

**Comment by haircommander** [comment]
the fix has made it into https://github.com/google/cadvisor/releases/tag/v0.40.0-rc.1, so I imagine the change will come in by 1.22

**Comment by r10r** [comment]
/remove-lifecycle stale 

So v1.22 is out for a while now. 
Is there someone who has already upgraded to v1.22  and can confirm that the getFsInfo errors  are fixed?

**Comment by r10r** [comment]
So v1.22 is out for a while now. 
Is there someone who has already upgraded to v1.22  and can confirm that the getFsInfo errors  are fixed?

**Comment by ml-** [comment]
haircommander mentioned that the fix made it into cadvisor 0.40.0-rc.1. But cadvisor version bump did not happen in k8s yet, probably due to issues mentioned here: https://github.com/kubernetes/kubernetes/pull/104392

iirc kind did not work with image kindest/node v1.22.1, I did not look into logs however. Will update post once I have access to the affected device.

**Comment by Jean-Daniel** [comment]
I still have this logs with version 1.22.2

**Comment by allenjol** [comment]
I have got the same error log of kubelet
kubernetes version 1.22.2
containerd: 1.4.11
```
$ journalctl -f -u kubelet
-- Logs begin at Tue 2021-08-24 16:07:10 CST. --
Nov 12 11:01:59 sit-kubernetes-master-srv1 kubelet[385618]: E1112 11:01:59.407635  385618 stats/cri_stats_provider.go:372] "Failed to get the info of the filesystem with mountpoint" err="unable to finddata in memory cache" mountpoint="/data/containerd/io.containerd.snapshotter.v1.overlayfs"
Nov 12 11:01:59 sit-kubernetes-master-srv1 kubelet[385618]: E1112 11:01:59.407659  385618 kubelet/kubelet.go:1343] "Image garbage collection failed once. Stats initialization may not have completed yet" err="invalid capacity 0 on image filesystem"
Nov 12 11:01:59 sit-kubernetes-master-srv1 kubelet[385618]: E1112 11:01:59.635668  385618 kubelet/kubelet.go:1991] "Skipping pod synchronization" err="[container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet to be successful]"
Nov 12 11:03:43 sit-kubernetes-master-srv1 kubelet[385618]: E1112 11:03:43.753192  385618 pleg/generic.go:409] "PLEG: Write status" pod="kube-system/calico-node-cnckd" podStatus=&{ID:14cc3a96-06a4-4798-ad90-4d5e56ec7fa5 Name:calico-node-cnckd Namespace:kube-system IPs:[] ContainerStatuses:[] SandboxStatuses:[&PodSandboxStatus{Id:da6732a3ab6149d12201f58355deec74d508500ff0aa4ecd1201aa4abb866a19,Metadata:&PodSandboxMetadata{Name:calico-node-cnckd,Uid:14cc3a96-06a4-4798-ad90-4d5e56ec7fa5,Namespace:kube-system,Attempt:0,},State:SANDBOX_READY,CreatedAt:1636686223306711718,Network:&PodSandboxNetworkStatus{Ip:,AdditionalIps:[]*PodIP{},},Linux:&LinuxPodSandboxStatus{Namespaces:&Namespace{Options:&NamespaceOption{Network:NODE,Pid:CONTAINER,Ipc:POD,TargetId:,},},},Labels:map[string]string{controller-revision-hash: 69dfc55c65,io.kubernetes.pod.name: calico-node-cnckd,io.kubernetes.pod.namespace: kube-system,io.kubernetes.pod.uid: 14cc3a96-06a4-4798-ad90-4d5e56ec7fa5,k8s-app: calico-node,pod-template-generation: 1,},Annotations:map[string]string{kubernetes.io/config.seen: 2021-11-12T11:03:42.407267423+08:00,kubernetes.io/config.source: api,},RuntimeHandler:,}]}
```
Is this problem have been resolve?

**Comment by mosaicwang** [comment]
I still have these logs with version 1.23.1

**Comment by haircommander** [comment]
turns out we ended up being blocked on https://github.com/google/cadvisor/pull/3018, so the fix has yet to be merged. let's push for it in 1.24

**Comment by Jeansen** [comment]
I'll wait for 1.24. With 1.22.5 My cluster has some of these messages but is stable. But with 1.23.x I get disk pressure because my sys logs get spammed quickly.

**Comment by saschagrunert** [comment]
This is still relevant and requires a fix with https://github.com/kubernetes/kubernetes/pull/100448

**Comment by Jean-Daniel** [comment]
/remove-lifecycle stale

Related PR still not merged.

**Comment by Jille** [comment]
SnoozeThis is useful if we don't want to keep polling until that PR is closed.

@SnoozeThis https://github.com/kubernetes/kubernetes/pull/100448

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/c0wl_vYdha0) I will wait until https://github.com/kubernetes/kubernetes/pull/100448 is merged and then add a comment.

**Comment by 111andre111** [comment]
Hi folks,
I still have this issue in most recent Kubernetes 1.24.6.
cAdvisor 0.44.0 that fix [google/cadvisor/pull/3018](https://github.com/google/cadvisor/pull/3018) went into that version, is now a long time ago already in 1.24.0.
            https://github.com/kubernetes/kubernetes/pull/109029  Dep bump to runc 1.1.0, cadvisor 0.44.0
            https://github.com/kubernetes/kubernetes/pull/109675  Automated cherry pick of #109658: Bump cAdvisor to v0.44.1 28.4.2022

So is there possibly any chance to progress with a review of this PR please?
https://github.com/kubernetes/kubernetes/pull/100448

@haircommander @ml-

**Comment by 111andre111** [comment]
Can we have any news on that topic please?

**Comment by SnoozeThis** [comment]
Resolved.
