### ISSUE TITLE
scheduler_perf: create a more realistic preemption benchmark

### ISSUE THREAD

**Issue by adtac** [kubernetes/kubernetes#94836]
**What would you like to be added**: Add a more realistic preemption workload to the scheduler_perf.

**Why is this needed**: The current workload has two priorities. I propose adding a benchmark that:

1. Has more than two priorities.
1. Preemptor has a priority somewhere in the middle.
1. Preemptor need not preempt all pods on every node (currently, resource restrictions require preempting all pods)

/sig scheduling
/cc @ahg-g @alculquicondor

**Comment by alculquicondor** [comment]
Should we modify the existing one instead of creating a new one? With the objective of keeping the benchmarks running in post submit with a decent period.

**Comment by adtac** [comment]
I think we should/can freely modify the existing one until such a post-submit job exists because there's nothing to compare it to; we don't have past data right now.
