### ISSUE TITLE
`ResourceList`'s `Cpu()` function claim to return "the CPU limit if specified" while returning the content of `"cpu"` instead of `"limits.cpu"`

### ISSUE THREAD

**Issue by ArchangelX360** [kubernetes/kubernetes#94831]
**What happened**:

`ResourceList`'s [`Cpu()` function ](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/resource.go#L29) claim to return "the CPU limit if specified" while returning the content of `ResourceName` `"cpu"` instead of `ResourceName` `"limits.cpu"`.

**What you expected to happen**:

I would expect `Cpu()` to return `"limits.cpu"` key content instead of `"cpu"` key content. Meaning using [`ResourceLimitsCPU` `ResourceName`](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L5474) instead of [`ResourceCPU` `ResourceName`](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L4765).

It could be that the documentation of the function is invalid.

It seems as well that the confusion is coming from the fact that `ResourceList` struct is both used in the context of [`ResourceQuotaSpec`](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L5511) but also in [`ResourceRequirements`](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L2173). Even though the manifest overall structure of these two is a little bit different.
Indeed, the information about wether the key is a limit or a request is fundamentally different in the two contexts:
- in `ResourceQuotaSpec` withing the `ResourceList` [we need to prefix the *keys* by `limits.` or `requests.`](https://kubernetes.io/docs/concepts/policy/resource-quotas/#compute-resource-quota).
- while in `ResourceRequirements`, the manifest itself is declaring [`Limits`](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L2177) and [`Requests`](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L2183) being two different `ResourceLists`s.

**How to reproduce it (as minimally and precisely as possible)**:

Non relevant.

**Anything else we need to know?**:

This is linked to the issue reported on the (I assume) wrong issue board: https://github.com/kubernetes/api/issues/31

**Environment**:
- Kubernetes version (use `kubectl version`): non relevant
- Cloud provider or hardware configuration: non relevant
- OS (e.g: `cat /etc/os-release`): non relevant
- Kernel (e.g. `uname -a`): non relevant
- Install tools: non relevant
- Network plugin and version (if this is a network-related bug): non relevant
- Others: non relevant

**Comment by ZihanJiang96** [comment]
I could work on this issue if this is a valid bug @ArchangelX360

**Comment by fedebongio** [comment]
/sig node
in any case, if needs to be fixed it's going to be hard to make it backward compatible, so copying also the api reviewers label
/api-review

**Comment by liggitt** [comment]
I would recommend:

* fixing the documentation to accurately describe what is returned ("returns the value of the `cpu` resource")
* sweeping in-tree uses to make sure we're only using it correctly

/remove-label api-review

**Comment by apoland** [comment]
I'm willing to fix documentation and audit the use of this function.
