### ISSUE TITLE
Remove deprecated scheduler metrics

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#94852]
Remove all metrics marked as deprecated in https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/metrics/metrics.go#L135

/sig scheduling
/cc @logicalhan 
/help

**Comment by arghya88** [comment]
Does it mean to remove any metrics with name "Deprecated" need to be removed?

**Comment by ahg-g** [comment]
correct

**Comment by arghya88** [comment]
@ahg-g I can work on it

**Comment by ahg-g** [comment]
Thanks

/assign @arghya88

**Comment by Huang-Wei** [comment]
> @ahg-g Does it mean any metrics with name "Deprecated" need to be removed?

Hold on for a second, I thought the same before. But the actual semantics is to deprecate the metrics on release `X` - `X` = `DeprecatedVersion` + 3. See https://github.com/kubernetes/kubernetes/pull/91385#issuecomment-633337016

**Comment by ahg-g** [comment]
Those are alpha metrics, we are free to remove them. We didn't remove them before because we wanted to migrate the metrics used by the scalability tests, which we already did.
