### ISSUE TITLE
kubectl patch service account not having any effect

### ISSUE THREAD

**Issue by chrissound** [kubernetes/kubernetes#94865]
**What happened**: 
```
root@docker-ubuntu-s-1vcpu-1gb-lon1-01:~/multitenant-manager# kubectl patch serviceaccount default -p '{"imagepullsecrets": [{"name": "gcp-cr-read-access"}]}'
serviceaccount/default patched (no change)
root@docker-ubuntu-s-1vcpu-1gb-lon1-01:~/multitenant-manager# kubectl describe serviceaccount default
Name:                default
Namespace:           app-1
Labels:              <none>
Annotations:         <none>
Image pull secrets:  <none>
Mountable secrets:   default-token-tqp58
Tokens:              default-token-tqp58
Events:              <none>
root@docker-ubuntu-s-1vcpu-1gb-lon1-01:~/multitenant-manager# kubectl get serviceaccount -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2020-09-17T15:50:34Z"
    name: default
    namespace: app-1
    resourceVersion: "111538"
    selfLink: /api/v1/namespaces/app-1/serviceaccounts/default
    uid: 5fe21574-67bf-485c-b9aa-d09c1fe3350c
  secrets:
  - name: default-token-tqp58
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
root@docker-ubuntu-s-1vcpu-1gb-lon1-01:~/multitenant-manager# kubectl patch -n app-1 serviceaccount default -p '{"imagepullsecrets": [{"name": "gcp-cr-read-access"}]}'
serviceaccount/default patched (no change)
```

**What you expected to happen**:

For `kubectl patch serviceaccount default -p '{"imagepullsecrets": [{"name": "gcp-cr-read-access"}]}` to make the correct change.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by fedebongio** [comment]
let's start with sig-cli, and if it turns out is a problem on our side we will take a look

**Comment by roycaihw** [comment]
The json path is case-sensitive. Please try use `imagePullSecrets` instead of `imagepullsecrets`

**Comment by chrissound** [comment]
Great that seems to have been the issue after all. Thank you. Perhaps the API should respond with a non success response in the event a value is patched that does not exist?

**Comment by roycaihw** [comment]
The API server silently drops unknown fields to achieve forward compatibility (a new field was added in a newer version, but the server was rolled-back), so I don't think we can change the behavior on server side. 

It might be better if kubectl can do a client-side validation and raise an error, and the users can choice to skip client-side validation if they want. But still this behavior change will be backwards incompatible for people using kubectl in automation. I guess there were similar issues in the past about this topic. SIG CLI folk may have more context.

**Comment by liggitt** [comment]
Correct on all counts, the field name is case-sensitive, the API server drops unknown fields, and clients do not validate patches (patch application is done server side)

In the future, we could consider warning server-side on unrecognized fields, but the parsing stacks are not set up well to recognize/preserve that information efficiently while still succeeding
