### ISSUE TITLE
Kube-apiserver can't handle pod creation request

### ISSUE THREAD

**Issue by lw8008** [kubernetes/kubernetes#94874]
**What happened**:
All of worker nodes was reboot at same time accidently.
after those nodes back, the cluster(master, etcd, worker) is normal and can create any type of resource except pod.

The error message as below:
:~/cindertest> cat pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: default
spec:
  containers:
    - name: test
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"

> kubectl apply -f pod.yaml
Error from server (Timeout): error when creating "pod.yaml": Timeout: request did not complete within requested timeout

I think when create pod type resouce, it only need kube-apiserver and scheduler, scheduler will work only after kube-apiserver create pod key in etcd, during my test, i didn't observe the key created in etcd(etcd works properly.)
I try to enable loglevel 10 for apiserver but not see any Warning/Error there.
Pls let me know if you need anything, thanks.

**How to reproduce it (as minimally and precisely as possible)**:
May not easy to reproduce.

**Anything else we need to know?**:
kubectl output with loglevel 10

...
I0918 03:12:42.969951   18628 round_trippers.go:443] POST https://10.237.8.11:6443/api/v1/namespaces/default/pods 504 Gateway Timeout in 34002 milliseconds
I0918 03:12:42.969973   18628 round_trippers.go:449] Response Headers:
I0918 03:12:42.969979   18628 round_trippers.go:452]     Content-Type: application/json
I0918 03:12:42.970009   18628 round_trippers.go:452]     Content-Length: 183
I0918 03:12:42.970014   18628 round_trippers.go:452]     Date: Fri, 18 Sep 2020 03:12:42 GMT
I0918 03:12:42.970039   18628 request.go:1017] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Timeout: request did not complete within requested timeout","reason":"Timeout","details":{},"code":504}
I0918 03:12:42.970282   18628 helpers.go:203] server response object: [{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "error when creating \"deploy.yaml\": Timeout: request did not complete within requested timeout",
  "reason": "Timeout",
  "details": {},
  "code": 504
}]
F0918 03:12:42.970301   18628 helpers.go:114] Error from server (Timeout): error when creating "deploy.yaml": Timeout: request did not complete within requested timeout

**Environment**:
- Kubernetes version (use `kubectl version`):
~> kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

~> kubectl get nodes
NAME          STATUS   ROLES               AGE   VERSION
sc25k8s1004   Ready    controlplane,etcd   98d   v1.17.4
sc25k8s1005   Ready    controlplane,etcd   98d   v1.17.4
sc25k8s1006   Ready    controlplane,etcd   14d   v1.17.4
sc25k8s2002   Ready    worker              81d   v1.17.4
sc25k8s2003   Ready    worker              85d   v1.17.4
sc25k8s2004   Ready    worker              80d   v1.17.4
sc25k8s2006   Ready    worker              81d   v1.17.4
sc25k8s2007   Ready    worker              80d   v1.17.4
sc25k8s2010   Ready    worker              81d   v1.17.4

- Cloud provider or hardware configuration:
Openstack

- OS (e.g: `cat /etc/os-release`):
NAME="SLES"
VERSION="12-SP5"
VERSION_ID="12.5"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP5"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp5"

- Kernel (e.g. `uname -a`):
Linux sc25k8s1004 4.12.14-122.32-default #1 SMP Wed Aug 5 12:59:08 UTC 2020 (477c426) x86_64 x86_64 x86_64 GNU/Linux

- Network plugin and version (if this is a network-related bug):
canal

- Others:
We are using Rancher RKE to setup the cluster.

**Comment by neolit123** [comment]
/sig api-machinery

> after those nodes back, the cluster(master, etcd, worker) is normal and can create any type of resource except pod.

hi, this is very odd...

- are you sure pods are the only object type that cannot be created?
- can you show from the logs of the api-server that this POST request is reaching?
- do you have anything running in the cluster like an admission controller that may be blocking this?

**Comment by lw8008** [comment]
Yes, it's really odd.
After reboot several times it works now. thanks.
