### ISSUE TITLE
If calling the 'login' word in metadata.name, an error occurs in calling api.

### ISSUE THREAD

**Issue by nayoungson** [kubernetes/kubernetes#94877]
If calling the 'login' word in metadata.name of any object, an error occurs in calling api.

**spec**
kubernetes v1.17.6

**example - secret**
```
$ cat secret.yaml
$ kubectl apply -f secret.yaml 

apiVersion: v1
kind: Secret
metadata:
  name: login ==========> including 'login'
  namespace: default
type: Opaque
stringData:
  username: admin
  password: damin
```

```
$ kubectl get secret|grep login
login                                        Opaque                                2      10s
```

```
curl 'https://{ip}/api/kubernetes/apis/v1/namespaces/default/secrets/login' -H 'authorization: Bearer eyJhbGciOiJSU.......'  -k -v
* About to connect() to {ip} port 443 (#0)
*   Trying {ip}...
* Connected to {ip} ({ip}) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: E={user},CN=....
* 	start date: Mar 17 04:54:17 2020 GMT
* 	expire date: Dec 15 04:54:17 2029 GMT
* 	common name: {user}
* 	issuer: E={user}...
> GET /api/kubernetes/apis/v1/namespaces/default/secrets/login HTTP/1.1
> User-Agent: curl/7.29.0
> Host: {ip}
> Accept: */*
> authorization: Bearer eyJhbGciOiJSU...
> 
* Empty reply from server
* Connection #0 to host {ip} left intact
curl: (52) Empty reply from server
```

Pods, Configmaps, ... All Object are the same phenomenon.

Any idea why this is happening?

**Comment by nayoungson** [comment]
> If calling the 'login' word in metadata.name of any object, an error occurs in calling api.
> 
> **spec**
> kubernetes v1.17.6
> 
> **example - secret**
> 
> ```
> $ cat secret.yaml
> $ kubectl apply -f secret.yaml 
> 
> apiVersion: v1
> kind: Secret
> metadata:
>   name: login ==========> including 'login'
>   namespace: default
> type: Opaque
> stringData:
>   username: admin
>   password: damin
> ```
> 
> ```
> $ kubectl get secret|grep login
> login                                        Opaque                                2      10s
> ```
> 
> ```
> curl 'https://{ip}/api/kubernetes/apis/v1/namespaces/default/secrets/login' -H 'authorization: Bearer eyJhbGciOiJSU.......'  -k -v
> * About to connect() to {ip} port 443 (#0)
> *   Trying {ip}...
> * Connected to {ip} ({ip}) port 443 (#0)
> * Initializing NSS with certpath: sql:/etc/pki/nssdb
> * skipping SSL peer certificate verification
> * SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
> * Server certificate:
> * 	subject: E={user},CN=....
> * 	start date: Mar 17 04:54:17 2020 GMT
> * 	expire date: Dec 15 04:54:17 2029 GMT
> * 	common name: {user}
> * 	issuer: E={user}...
> > GET /api/kubernetes/apis/v1/namespaces/default/secrets/login HTTP/1.1
> > User-Agent: curl/7.29.0
> > Host: {ip}
> > Accept: */*
> > authorization: Bearer eyJhbGciOiJSU...
> > 
> * Empty reply from server
> * Connection #0 to host {ip} left intact
> curl: (52) Empty reply from server
> ```
> 
> Pods, Configmaps, ... All Object are the same phenomenon.
> 
> Any idea why this is happening?

**Comment by knight42** [comment]
The correct url should be `https://{ip}/api/v1/namespaces/default/secrets/login`. You could verify it by running `kubectl get secret login -v=6`

Feel free to reopen if this is not the case.

/close
