### ISSUE TITLE
Redirect container stdout / stderr to file

### ISSUE THREAD

**Issue by BorjaEst** [kubernetes/kubernetes#94892]
**What would you like to be added**:
Configuration field to redirect container stdout/stderr to a file, for example:
``` yaml
 containers:
  - name: my-container
    image: google/my-container:v1
    volumeMounts:
    - name: varlog
      mountPath: /var/log

  - name: third-party
    image:  google/third-party:v1 
    stdout: /var/log/stdout
    stderr: /var/log/stderr

 volumes:
  - name: varlog
    emptyDir: {}
```
See [How to access from one container to another container stdout and stderr inside Kubernetes pod](https://stackoverflow.com/questions/57075546/how-to-access-from-one-container-to-another-container-stdout-and-stderr-inside-k)

**Why is this needed**:
Some applications (specially CLI) do not write to "/var/log", therefore some result values have to be collected from the stdout.

Currently this is possible adding a "command" field shuch as "main arg1 arg2 > stdout.file", however that modifies the ENTRYPOINT of the container, which is generally not a good idea. The ENTRYPOINT normally directs to the main application script insde the container.

**Example**
Consider you are maintaining a container RPC cluster based in kubernetes Jobs.
Your clients would develop a container which they would like to run in the cluster.
Your client does not know kubernetes (it is a backend service you are offering).
So you provide a CLI that they can use to submit the container image: `$ cli_rpc myrep/myimage`.

Your Jobs would have "cooperating containers", and those need to access to the client container output.
You cannot modify the ENTRYPOINT as you do not know which is the name of the "main" script at your client container.
You do not know the name of your client process so you cannot collect the stdout from the "shareProcessNamespace".

**thanks**

**Comment by kevtheappdev** [comment]
Hi! I'm interested in working on this along with some colleagues of mine as part of a course on Virtualiztion at UT Austin. Can we work on this issue? Thanks!

**Comment by dims** [comment]
@kevtheappdev please go ahead

**Comment by krmayankk** [comment]
Is this a common enough use case ?
@kevtheappdev  can you confirm that in your use case, your dont have access to the containers code where you can redirect file io ?

**Comment by aistein** [comment]
@kevtheappdev are y'all working on this issue already?  If so please self-assign.   Otherwise I'd quite like to tackle this issue.

**Comment by kevtheappdev** [comment]
@aistein Go ahead, my team and I have decided to pursue other issues.

**Comment by yehiyam** [comment]
@aistein are you working on this, or can I give it a try?

**Comment by kspviswa** [comment]
Also interested to contribute if @aistein or @yehiyam is not pursuing this.

**Comment by yehiyam** [comment]
@kspviswa I'd like to do this. Waiting on @aistein to hear that he is not working on it

**Comment by aistein** [comment]
@kspviswa @yehiyam please accept my apologies for the unacceptable delay.   You may assume work on this.

/unassign

**Comment by yehiyam** [comment]
@dims or anyone else familiar with the area. I'd like to get some pointers as to how to approach this.
1. should I create a KEP as this is an enhancement?
2. Where in the code should I update the pod API? 
3. Is there a way to control (redirect) the output of the process via the CRI?

**Comment by jayunit100** [comment]
https://github.com/kubernetes/community/tree/master/sig-node <-- might be worth going to the sig node weekly meeting, adding your q to the agenda, and asking there what the next steps would be? 

I assume eventually this would result in a KEP bc, I assume some folks would expect this to be solved by something like fluentd or some other Container runtime logging solution

**Comment by gjkim42** [comment]
@yehiyam are you working on this? else maybe I'd like to try this!

**Comment by yehiyam** [comment]
@gjkim42 I'm trying to reach sig-node (as @jayunit100 suggested). No luck so far. If you want to you can give it a try

**Comment by ehashman** [comment]
@yehiyam I would suggest you add this to the SIG Node meeting agenda and attend a meeting to discuss: https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg/edit

If the SIG response is positive, the next step would likely be to add a KEP. The required effort to implement this and the required doc changes/user comms would suggest to me this is too large to cover in an issue. https://github.com/kubernetes/enhancements/tree/master/keps#do-i-have-to-use-the-kep-process

Cheers!

**Comment by wzshiming** [comment]
@yehiyam @gjkim42 are you working on this? else maybe I'd like to try this!

**Comment by gjkim42** [comment]
@wzshiming No, I am not, I think you can try this!

**Comment by almas33** [comment]
@wzshiming @yehiyam are you working on this? I am new here and would like to try this!

**Comment by wzshiming** [comment]
@almas33 I found that there were a lot of points involved, I don't think I can hold them. you're welcome to try!

**Comment by BLasan** [comment]
@almas33 Are you still working on this? If not I would like to take up this issue. I'm also new to the community @wzshiming

**Comment by almas33** [comment]
you're welcome to try this @BLasan I'm currently working on some other issues

**Comment by BLasan** [comment]
> you're welcome to try this @BLasan I'm currently working on some other issues

Thanks

**Comment by ehashman** [comment]
Hi all,

Thanks a bunch for your interest in this! As I suggested above, please attend a SIG Node meeting and raise this as a topic. If the response is positive, you can then work on an enhancement proposal (aka a KEP). We could then target development for the 1.22 release cycle as we're in enhancement freeze for 1.21 already.

Cheers!

**Comment by jai** [comment]
seems like this issue has made the rounds 🤣  @BLasan you putting time into this currently?

**Comment by BLasan** [comment]
/unassign
No. You can pickup this issue 👍

**Comment by Meegada-Mahesh** [comment]
@jai hey man you working on this ??

otherwise i will assign my self

**Comment by jai** [comment]
Haven't assigned myself as I was going to bring it up at the upcoming SIG Node meeting but if you're ready to get started go for it.

Let me know if you end up not working on it, this issue has been bouncing around a while and I'd like to make sure it gets moving at some point.

FYI minutes/agenda of SIG Node https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg/edit#heading=h.9dy16yiykh6f (meeting is in about 8-9 hours)

**Comment by n4j** [comment]
What is the status on this issue? If no one has picked it up yet then I can take a stab at it.

**Comment by jai** [comment]
I think you want to ask @Meegada-Mahesh - I didn't assign this issue to myself since I hadn't started work on it. He assigned himself so one would assume he's spending time on it.

**Comment by Meegada-Mahesh** [comment]
@n4j Please pick it up if you want. I am spending time on something else right now

**Comment by n4j** [comment]
> Haven't assigned myself as I was going to bring it up at the upcoming SIG Node meeting but if you're ready to get started go for it.
> 
> Let me know if you end up not working on it, this issue has been bouncing around a while and I'd like to make sure it gets moving at some point.
> 
> FYI minutes/agenda of SIG Node https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg/edit#heading=h.9dy16yiykh6f (meeting is in about 8-9 hours)

@jai Was this discussed in the SIG meeting? If not I can attend one of the SIG meetings and bring this up for discussion.

**Comment by jai** [comment]
I have not brought it up - link to agenda and schedule is a few comments up ⤴️

**Comment by Random-Liu** [comment]
Today, when using containerd/cri-o, kubelet already redirect the container stdout/stderr to a file on the node, e.g. `/var/log/pods/kube-system_kube-proxy-5c95n_70a72385-e8cf-4825-8fe8-3ce35356f558/kube-proxy/0.log` for the kube-proxy container. It includes both stderr and stdout in the [CRI logging format](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/kubelet-cri-logging.md).

Does it work for you to:
1) Mount `/var/log` into `my-container`;
2) Parse the corresponding log file of the `third-party` container.

In this way, you get access to the stderr and stdout of the `third-party` container, and no need to change the `third-party` container image.

**Comment by n4j** [comment]
> Today, when using containerd/cri-o, kubelet already redirect the container stdout/stderr to a file on the node, e.g. `/var/log/pods/kube-system_kube-proxy-5c95n_70a72385-e8cf-4825-8fe8-3ce35356f558/kube-proxy/0.log` for the kube-proxy container. It includes both stderr and stdout in the [CRI logging format](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/kubelet-cri-logging.md). This is always done to all containers, you can find stderr/stdout of any container in this way.
> 
> Does it work for you to:
> 
> 1. Mount `/var/log` into `my-container`;
> 2. Parse the corresponding log file of the `third-party` container.
> 
> In this way, you get access to the stderr and stdout of the `third-party` container, and no need to change the `third-party` container image.
> 
> NOTE: This also works with Docker too, but the log path will be in `/var/log/docker`, see https://sematext.com/blog/docker-logs-location/

@BorjaEst See the comment above from @Random-Liu and let us know if this works for you or not?

**Comment by yehiyam** [comment]
@n4j @Random-Liu This will only work (at least for docker) if the container is privileged. 
Openshift does not allow privileged containers nor it allows host path mount

**Comment by n4j** [comment]
@Random-Liu I agree with @yehiyam.

Is there any other approach which works without privilege escalation? If not can we bring-up this issue again in the next `sig\node` meeting?

**Comment by Random-Liu** [comment]
> Is there any other approach which works without privilege escalation? If not can we bring-up this issue again in the next sig\node meeting?

Another possible solution is to let the other container run `kubectl logs` to get the output of the third party container, but that would require going through apiserver.

As is mentioned in the meeting, if needed, one possible solution is to support log volume, and let kubelet store the stdout/stderr log into the log volume for a pod. That is a useful feature in general, but will need further design.

**Comment by BorjaEst** [comment]
One of the requirements is to be able to differentiate stdout from stderr. We could expect the result from the container in stdout and the logs in stderr but not mixed, otherwise it might be harder for the "cooperating containers" to retrieve the output.

In option 1, I do not see that [kubectl logs](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#logs)  is able to make that differentiation. 
Would it be possible to have it in option 2?
Would it be possible to have different log paths for different containers running in the pod?

For example:
```yaml

  - name: third-party-1
    image:  google/third-party-2:v1 
    logs:
        stdout: /var/log/stdout
        stderr: /var/log/stderr
        ....

  - name: third-party-2
    image:  google/third-party-2:v1 
    logs:
        stdout: /var/log/stdout
        stderr: /var/log/stderr
        ....

```

**Comment by Random-Liu** [comment]
> In option 1, I do not see that kubectl logs is able to make that differentiation.

Yeah, that is an issue. Make sense.

> Would it be possible to have it in option 2?

Yeah, if we do option 2, I think we will also need to keep stdout and stderr separated.

> Would it be possible to have different log paths for different containers running in the pod?

Different container already has different log path today. If we do option 2, it should be in different log path as well.

It seems that the container log file on the host does contain all the information you need, but the concern is that we want to do this without host path mounting, which does make sense to me as well.

In this case, I feel like the log volume could be a proper solution for your case, and is also what we wanted to do for a long time. https://github.com/yujuhong/kubernetes/blob/7e5c03a0e840c5505d628165b6336ba503426bff/docs/proposals/kubelet-cri-logging.md#references

**Comment by BorjaEst** [comment]
> In this case, I feel like the log volume could be a proper solution for your case, and is also what we wanted to do for a long time. https://github.com/yujuhong/kubernetes/blob/7e5c03a0e840c5505d628165b6336ba503426bff/docs/proposals/kubelet-cri-logging.md#references

Indeed I think that could be a proper solution. Probably better than what I suggested.

> A hacky work around for this would be getting the image manifest of your client container, and you will see the ENTRYPOINT there, and you add redirect with the ENTRYPOINT in your pod yaml.

Yes, the problem then is  that I cannot provide my cluster as a service, or it would be too complicated to automate this ENTRYPOINT identification.

**Comment by yehiyam** [comment]
I think that parsing and changing the ENTRY POINT is very error prone in the general case

The log volume solution seem like a good way to go. Is there anything I can help with?

**Comment by BorjaEst** [comment]
It looks the proposal for log volume is from 2016.
Is that feauture planned or was abandoned? I did not find any topic related on 2020.

**Comment by Random-Liu** [comment]
> Is that feauture planned or was abandoned? I did not find any topic related on 2021.

It is not abandoned, just not prioritized.

Please feel free bring back the topic back to sig-node, and explain your concern about the suggested approach above, e.g. host path mounting.

**Comment by sfrank-mc** [comment]
/remove-lifecycle stale

Any news about this?

**Comment by srfrnk** [comment]
Any plans of working on that at some point?

**Comment by Ansudeen** [comment]
Hi, is this feature available now ?

**Comment by yxxhero** [comment]
any updates?

**Comment by eddyekofo94** [comment]
Any updates concerning this issue? thanks

**Comment by Ansudeen** [comment]
Hi,

I Handle this case on the application side so for me there are no issues as
of now.

**Comment by uhthomas** [comment]
I think this request needs a [KEP](https://github.com/kubernetes/enhancements/blob/8f94a4c2121497f42110f8d41951726d5f438da3/keps/README.md) to make progress, like with https://github.com/kubernetes/enhancements/issues/661#issuecomment-1339532933.
