### ISSUE TITLE
Update test/e2e/framework to use the term "Control Plane"

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#94901]
There are a number of variable and functions that can outright be renamed to refer to "control plane" instead of "master".  There are also some flags which should be deprecated (and corresponding changes made in jobs)

```
$ ag -l master test/e2e/framework | sort
test/e2e/framework/config/config.go
test/e2e/framework/framework.go
test/e2e/framework/gpu/gpu_util.go
test/e2e/framework/ingress/ingress_utils.go
test/e2e/framework/kubelet/stats.go
test/e2e/framework/kubesystem/kubesystem.go
test/e2e/framework/log_size_monitoring.go
test/e2e/framework/network/utils.go
test/e2e/framework/node/resource.go
test/e2e/framework/node/wait.go
test/e2e/framework/node/wait_test.go
test/e2e/framework/nodes_util.go
test/e2e/framework/providers/gce/firewall.go
test/e2e/framework/resource_usage_gatherer.go
test/e2e/framework/skipper/skipper.go
test/e2e/framework/ssh/ssh.go
test/e2e/framework/test_context.go
test/e2e/framework/util.go
```

/kind cleanup
/wg naming
/sig testing
/area test

**Comment by xiaopeng-han** [comment]
can we get some test from it，this issue is contained of too many test ?

**Comment by tanjunchen** [comment]
test/e2e/framework/ingress/ingress_utils.go
test/e2e/framework/node/resource.go
test/e2e/framework/node/wait.go
test/e2e/framework/ssh/ssh.go

These files have been modified.

**Comment by vishsangale** [comment]
@dims I have added PR for the changes, I have some questions, about the changes. With current attached PR I have not changed in command line parameters, I guess we need to retire them and provide new ones. is that right? I would like create a different PR reieiw for those changes. Another question, you also talked about changing jobs? Can you please explain more which jobs need to be changed? Are those need to be updated after change in cmd line params only? Where can I references to them? Thanks.

**Comment by spiffxp** [comment]
/reopen
Please don't "Fixes:" this issue via PR's

**Comment by spiffxp** [comment]
/triage accepted

/remove-good-first-issue
We are lacking a guide to ensure we consistently rename things, and I'm seeing a lot of blind s/master/instance which I believe is inappropriate

**Comment by oomichi** [comment]
Really nice to have guideline to explain how to fix this issue.
I am checking whole PRs for this issue and those points with priority order are
- Replace `master` with actual component name like `etcd`, `apiserver`, `scheduler`, `controller-manager` etc. if possible
- Even if `node` is not added after `master`, we need to replace the `master` with `control plane node`
- Replace `nodes excluding master node` with `schedulable nodes`
- Replace `master node` with `control plane node`

I still have questions like
- How to capitalize in comments? (Control plane? control plane? Control Plane?)

**Comment by neolit123** [comment]
> How to capitalize in comments? (Control plane? control plane? Control Plane?)

this seems like a question for @kubernetes/sig-docs-en-owners 

this search query at k8s.io reveals that the capitalization varies:
https://kubernetes.io/search/?q=%22control%20plane%22

i would recommend :control plane", because it is not the name of an object, it is the object.
an example of that is the following - if one is talking about a k8s node topology wise, then "node" does not have to be capitalized. yet if one is talking about the API object named "Node", then we should capitalize it.

maybe we should clarify "control plane" here https://kubernetes.io/docs/contribute/style/style-guide/ too.

**Comment by neolit123** [comment]
> Even if node is not added after master, we need to replace the master with control plane node

yes, but only if this is not a case of:

> Replace master with actual component name like etcd, apiserver, scheduler, controller-manager etc. if possible

i think saw a few cases of that.

**Comment by oomichi** [comment]
@neolit123 Thanks for your comment!

>> Even if node is not added after master, we need to replace the master with control plane node
>
> yes, but only if this is not a case of:
>
>> Replace master with actual component name like etcd, apiserver, scheduler, controller-manager etc. if possible
>
> i think saw a few cases of that.

Yes, I agree with you here.
I think these rules should be applied with the order.

**Comment by spiffxp** [comment]
@oomichi thank you for enumerating my concerns, I think I want to explain the reasoning a bit more though:

Master is used interchangeably to refer to different concepts.  Our goal here is not just to use more inclusive language, but to be more specific about what we're referring to.  This includes maintaining the appropriate level of abstraction; sometimes we want to talk about the group as a whole, sometimes we want to talk about a specific instance or member of the group.
- "The thing that hosts all components responsible for controlling my kubernetes cluster" -> **control plane**
- "The thing I talk to in order to interact with my kubernetes cluster" -> **control plane, endpoint**
- "A specific kube-apiserver instance that is part of the kubernetes control plane" -> **apiserver, instance** (this is what I understand `controlplane.Instance` to be)
- "A node that hosts components that are part of the control plane" -> **control plane node**
- "A node that is unschedulable" -> **unschedulable node**
- "A specific component that is part of the control plane" -> **apiserver, controller-manager, scheduler, etcd**

When using terminology that could be seen as generic, ask yourself, is there enough context available to disambiguate potential meanings for the reader? e.g.
- "instance" - an instance of what?
- "apiserver" - is this a generic apiserver? is this a kubernetes apiserver? is this part of the kubernetes control plane?
- "endpoint" - what's at the other end of this endpoint?

I completely agree with @neolit123's comments on capitalization.  I would almost always go with "control plane" in docs or comments.

@oomichi so having said all that, I think your recommendations are solid, except

>Even if node is not added after master, we need to replace the master with control plane node

This is really going to depend on which of the above concepts "master" is referring to.

**Comment by oomichi** [comment]
@spiffxp Thank you for your guideline!
That is very clear and I understand what we need to take care of during PR reviews.
We are ready to go forward.

**Comment by spiffxp** [comment]
One other set of assumptions / definition I see come up (in tests, anyway):
- there is exactly one instance of each control plane component
- there is exactly one control plane node that hosts these components

Basically these are assumptions that are tangled up with the e2e framework's concept of a "provider", usually assuming the kube-up.sh gce implementation with a set of default parameters.

We should really be untangling this while we're renaming things, but I don't have a concrete proposal on the best path forward.  Extract operations into the provider interface?  Make a new kind of provider (control plane provider)? Look at cluster provider?

At the very least we should probably ensure names refer to whether they're trying to mutate a single instance of a specific control plane component, all instances, or the control plane in its entirety,

**Comment by spiffxp** [comment]
/priority important-longterm
I will circle back on the PR's I blocked now that https://github.com/kubernetes/community/pull/5243 is merged

**Comment by spiffxp** [comment]
/remove-help
Going to take off /help until I can provide clearer breakout/instructions

**Comment by spiffxp** [comment]
/milestone v1.21
Would like to see if we can drive this completion in v1.21 timeframe

**Comment by desponda** [comment]
👋 Hello! This issue has not been updated for a long time, so I'd like to check what's the status. The code freeze is starting March 9th, 2021 (about 1 week from now).
As the Issue is tagged for 1.21, is it still planned for this release?

**Comment by spiffxp** [comment]
/milestone clear
Parts of this could qualify for test freeze but it is unlikely I am going to find time to push this forward

**Comment by justaugustus** [comment]
/help
This currently has no assignee. Is someone interested in taking this up?

**Comment by irvifa** [comment]
Hi, I'm interesting in taking this task, however I'd like to ask if let's say we have something like this [line](https://github.com/kubernetes/kubernetes/blob/6181a2c7d8efd1d05211f38254e787f4d74f09e9/test/e2e/framework/config/config.go#L45) which actually refer to csi plugin, do we need to change it as well?

**Comment by mgutierrez98** [comment]
I can try to work on this if it's still available?

**Comment by MorrisLaw** [comment]
Made a PR that's ready for review @justaugustus @spiffxp @oomichi ^
