### ISSUE TITLE
Pod recreation gets stuck due to dangling attach

### ISSUE THREAD

**Issue by yuga711** [kubernetes/kubernetes#94912]
**What happened**:
New pod creation gets stuck in `"Container creating"`

**What you expected to happen**:
Pod recreation should have succeeded. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy a statefulset application
2. While the pod creation is in-progress, restart kube-controller-manager and delete the pod
3. New pod creation gets stuck in `"Container creating"`
4. `kubectl describe pod` shows the below failure:
```kubelet, node-khjt  Unable to attach or mount volumes: unmounted volumes=[test-pv], unattached volumes=[test-pv]: timed out waiting for the condition```

Note: To increase the likelihood of hitting the race, you can introduce delay [here](https://github.com/kubernetes/kubernetes/blob/e23d83eead3b5ae57731afb0209f4a2aaa4009dd/pkg/volume/util/operationexecutor/operation_generator.go#L338).  While the kube-controller hits this logic, restart the kube-controller and delete the pod. 

**Anything else we need to know?**:
If kube-controller is restarted after the volume is attached to the node, but before the node.status is updated, the restarted kube-controller doesn't know about this volume attachment (as the incore state is lost). If the pod is deleted before kube-controller re-initializes its incore state, the volume-attachment doesn't make into the DSW for that node. Eventually, when statefulset creates the pod on a different node, it will be stuck waiting for the volume to be attached.

Note that the in-tree volume plugins that implement danglingAttach error handling (eg: [here](https://github.com/kubernetes/kubernetes/blob/f4e39afea082afac7bf6f6936c34e012b7cb3c25/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L2550)) will auto-recover from the failure. The issue would likely hit all other in-tree volume types that support `attach`.

**Environment**:
- Kubernetes version (use `kubectl version`): 
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by yuga711** [comment]
/sig storage
cc @msau42 @misterikkit

**Comment by jingxu97** [comment]
cc /jingxu97

**Comment by tonymeng** [comment]
I'm also hitting this, @yuga711 did you find any work arounds?

**Comment by yuga711** [comment]
> I'm also hitting this, @yuga711 did you find any work arounds?
On which volume plugin you are hitting this? For CSI, we have a fix https://github.com/kubernetes/kubernetes/pull/96617.
