### ISSUE TITLE
bash completion for `kubectl exec POD -c`

### ISSUE THREAD

**Issue by rdxmb** [kubernetes/kubernetes#94927]
**What would you like to be added**:

Bash-completion for `kubectl exec POD -c` into a specific container. Actually, choosing the container with bash_completion works with `kubectl logs`, but not with `exec`.

Let's make an example:

```
# kubectl -n build-storage get po
NAME             READY   STATUS    RESTARTS   AGE
static-sites-0   2/2     Running   0          4d
# k -n build-storage logs static-sites-0  [TAB-TAB]
http  ssh   
```

BUT

```
kubectl -n build-storage exec -ti static-sites-0 -c [TAB-TAB] static-sites-0 static-sites-0 static-sites-0 static-sites-0`
```

**Why is this needed**:

Because it is missing :)

**Comment by bhumijgupta** [comment]
I would like to pick this up

**Comment by bhumijgupta** [comment]
As per the conversation on slack, will be unassigning myself in interest of https://github.com/kubernetes/kubernetes/pull/96087 to be merged
/unassign bhumijgupta

**Comment by marckhouzam** [comment]
I was really missing this feature so I posted a PR:
https://github.com/kubernetes/kubernetes/pull/106755
