### ISSUE TITLE
Untested Priority Class Life Cycle Test - 5 endpoints not covered by Conformance test

### ISSUE THREAD

**Issue by Riaankl** [kubernetes/kubernetes#94954]
# PriorityClassLifeCycleTest

The following PriorityClass endpoints was Promoted it 1.14 without Conformance tests, and remain untested:
 replace-, read-, patch-, list-, delete-collection- SchedulingV1PriorityClass 

# Identifying an untested feature Using APISnoop

According to this APIsnoop query, there are still some remaining PriorityClass endpoints which are untested.

with this query you can filter untested endpoints by their category and eligiblity for conformance. e.g below shows a query to find all conformance eligible untested,stable,core endpoints

```sql-mode
SELECT
  endpoint,
  -- k8s_action,
  -- path,
  -- description,
  kind
  FROM testing.untested_stable_endpoint
  where eligible is true
  -- and category = 'core'
    and endpoint ilike '%PriorityClass%'
  order by kind, endpoint desc
  limit 25;
```

```example
                 endpoint                  |     kind
-------------------------------------------|---------------
 replaceSchedulingV1PriorityClass          | PriorityClass
 readSchedulingV1PriorityClass             | PriorityClass
 patchSchedulingV1PriorityClass            | PriorityClass
 listSchedulingV1PriorityClass             | PriorityClass
 deleteSchedulingV1CollectionPriorityClass | PriorityClass
(5 rows)

```

# API Reference and feature documentation

-   [Kubernetes API Reference Docs](https://kubernetes.io/docs/reference/scheduling/)
-   [client-go - Priority Class](https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/scheduling/v1/priorityclass.go)

# [APISnoop](https://apisnoop.cncf.io/conformance-progress/endpoints/1.14.0?filter=promotedWithoutTests) Output

![image](https://user-images.githubusercontent.com/61125752/94071671-760ec000-fe48-11ea-9f66-5c346bf5d66e.png)

# Priority Class Endpoints with Conformance test:
createSchedulingV1PriorityClass
deleteSchedulingV1PriorityClass
Promoted to Conformance 1.19 with [PR#80545](https://github.com/kubernetes/kubernetes/pull/80545) 
[preemption.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/scheduling/preemption.go)

# Test grid link:
[Test grid](https://testgrid.k8s.io/sig-scheduling#gce-serial&include-filter-by-regex=verify%20PriorityClass%20endpoints%20can%20be%20operated%20with%20different%20HTTP%20methods&include-filter-by-regex=verify%20PriorityClass%20endpoints%20can%20be%20operated%20with%20different%20HTTP%20methods&include-filter-by-regex=PriorityClass&include-filter-by-regex=Priority&include-filter-by-regex=PriorityClass)

/sig testing
/sig architecture
/area conformance

**Comment by Huang-Wei** [comment]
@Riaankl Is the ultimiate goal to use conformance tests to **explicitly** issue all CRUD requests against PriorityClass? And, is `replaceSchedulingV1PriorityClass` equivalent to "update PriorityClass"?

**Comment by Riaankl** [comment]
@Huang-Wei all APIs must have Conformance tests unless they are not eligible for Conformance due to the [rules](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md#conformance-test-requirements) There is other APIGroups that have both Replace and Update as endpoints. That is the prerogative of the SIG to decide.

**Comment by ahg-g** [comment]
@Riaankl can you please point us to similar conformance tests used for core objects such as pods and nodes?

**Comment by Riaankl** [comment]
@ahg-g 
This  is a life cycle test for Create, List, Update, Patch, DeleteCollection [PR#90939](https://github.com/kubernetes/kubernetes/pull/90939/files)
More can be found in the test/e2e folder.
Also look for examples on the Conformance [Project Board](https://github.com/orgs/kubernetes/projects/9?card_filter_query=promote) at previously Promoted Conformance test
Reach out if we can help with more information on our approach to Conformance testing.

**Comment by Riaankl** [comment]
@ahg-g I remembered about this PR. Last week a few lines of code was added to cover the last of the "Lease" endpoint group for conformance. The one file contain the Conformance tests for the complete life cycle of Lease endpoints.
https://github.com/kubernetes/kubernetes/pull/94969/files#

**Comment by Huang-Wei** [comment]
/assign

I will work on it.

**Comment by Riaankl** [comment]
/reopen
Will monitor in test grid to move to Conformance after 2 weeks soak.
