### ISSUE TITLE
AWS NLB UpdateLoadBalancerFailed during instance shutting down

### ISSUE THREAD

**Issue by ischenkomari** [kubernetes/kubernetes#94966]
**What happened**:
Recieveng warning during LoadBalancer(NLB) service update, if some EC2 is shutting down at this moment. It leads to timeout, especially if cluster continiously scale up/down.

Warning  UpdateLoadBalancerFailed  service-controller  Error updating load balancer with new hosts map[...]: error registering new targets in target group: "InvalidTarget: The following targets are not in a running state and cannot be registered: ‘i-XXXXXX’

The key point is it try register target, not deregister, when instance is shutting down.
**What you expected to happen**:
Kubernetes(autoscaler) deregister instance before scaledown.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create service with NLB
2. Shut down any EC2 in cluster

**Anything else we need to know?**:
1. ec2_instance / node is deing
2. AWS health check failed in ASG
3. k8s remove node from actual[1] (use AWS API)
4. k8s found it as Ready and keep in expected
5. It became as candidate for adding (additions)
6. AWS can’t add it, as healthcheck’s failed
=======
		actual := sets.NewString(actualIDs...)
		expected := sets.NewString(instances...)

		additions := expected.Difference(actual)
		removals := actual.Difference(expected)

		if len(additions) > 0 {
                               …
				return nil, fmt.Errorf("error registering new targets in target group: %q", err)

		if len(removals) > 0 {
                               …
				return nil, fmt.Errorf("error trying to deregister targets in target group: %q", err)

======
[1] actual:
https://github.com/kubernetes/kubernetes/blob/02b5b60ecdf663acc00bafe534ce7483aaf2d782/staging/src/k8s.io/legacy-cloud-providers/aws/aws_loadbalancer.go#L624

**Environment**:
- Kubernetes version (use `kubectl version`): v1.17.11
- Cloud provider or hardware configuration: aws
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ryanli-me** [comment]
Any updates? I've been getting `"DuplicateListener: A listener already exists on this port for this load balancer` and `InvalidConfigurationRequest: You cannot change the health check protocol for a target group with the TCP protocol` (which I'm not changing health check protocol)

**Comment by BobDu** [comment]
Any updates? 
I've been getting 
Warning UpdateLoadBalancerFailed 14m (x115 over 116m)  service-controller (combined from similar events): Error updating load balancer with new hosts map[................:{}]: error creating load balancer listener: "DuplicateListener: A listener already exists on this port for this load balancer 'arn:aws:elasticloadbalancing:us-east-1:<account id>:loadbalancer/net/...../......'\n\tstatus code: 400, request id: ....

when i update aws eks 1.19 to 1.20
