### ISSUE TITLE
kubectl apply -f file.yaml --dry-run=client seems to query server

### ISSUE THREAD

**Issue by lynx-coding** [kubernetes/kubernetes#94965]
**What happened**:
When applying a Service to a cluster with dry-run using kubectl, the output looks like the server version of the Service instead the one from the file.

**What you expected to happen**:
The content of the returned json should contain my local resource

**How to reproduce it (as minimally and precisely as possible)**:
Create a YAML File with a service with annotations and apply it to a server.
Change the annotations in the file and run `kubectl apply -f service.yaml --dry-run=client -o json`
The result will show the server-side annotations, not the changed ones.

**Anything else we need to know?**:
Using `-dry-run=server` seems to fix it. Maybe something switched internally?

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g: `cat /etc/os-release`): Ubuntu 16.04.6
- Kernel (e.g. `uname -a`): 4.19.108-0419108-generic
- Install tools: Installed via kubeadm

**Comment by liggitt** [comment]
Seems like a duplicate of https://github.com/kubernetes/kubernetes/issues/72644#issuecomment-451965417

**Comment by lynx-coding** [comment]
Thanks for that response. So using `--dry-run=server` for the dry-run of an update seems like the correct way.

**Comment by soltysh** [comment]
Like Jordan explained before, client-side dry-run is not quite reliable and we'd encourage using serve-side apply, instead.
