### ISSUE TITLE
MountDevice failed for volum xxx fsck found errors on device xxx but could not correct them

### ISSUE THREAD

**Issue by lyyao09** [kubernetes/kubernetes#94970]
**What happened**:
The pod was pending because it waiting for mount pvc(use `iscsi` device),however, error occur when `fsck -a /dev/sda`.
similar issue related to https://github.com/kubernetes/kubernetes/issues/86406#issue-540038375 but no solution.

**What you expected to happen**:
in `pkg/util/mount/mount_linux.go#433`,we can see fsck use -a parameter to check and repair disk. however, `fsck -a` can not work well when fix disk, `fsck -y` can resolve problem.can we use `-y` parameter in the code ?
```
if !readOnly {
		// Run fsck on the disk to fix repairable issues, only do this for volumes requested as rw.
		klog.V(4).Infof("Checking for issues with fsck on disk: %s", source)
		args := []string{"-a", source}
		out, err := mounter.Exec.Run("fsck", args...)
		if err != nil {
			ee, isExitError := err.(utilexec.ExitError)
			switch {
			case err == utilexec.ErrExecutableNotFound:
				klog.Warningf("'fsck' not found on system; continuing mount without running 'fsck'.")
			case isExitError && ee.ExitStatus() == fsckErrorsCorrected:
				klog.Infof("Device %s has errors which were corrected by fsck.", source)
			case isExitError && ee.ExitStatus() == fsckErrorsUncorrected:
				return fmt.Errorf("'fsck' found errors on device %s but could not correct them: %s.", source, string(out))
			case isExitError && ee.ExitStatus() > fsckErrorsUncorrected:
				klog.Infof("`fsck` error %s", string(out))
			}
		}
	}
```

**How to reproduce it (as minimally and precisely as possible)**:
Abnormal power failure of nodes in the k8s cluster may cause this problem.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:20:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2020-08-28T11:18:26Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
[root@node19222 ~]# cat /etc/os-release
NAME="CentOS 7.6"
```
- Kernel (e.g. `uname -a`):
```
Linux node19222 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by eplightning** [comment]
This still happens, needed to do `fsck -y /dev/sdc` manually

**Comment by pacoxu** [comment]
/triage accepted
/cc @msau42@mengjiao-liu

Is there a reason that we don't use `fsck -y /dev/sdc` here?  Is there any side effect?

@eplightning  I cannot find `-y` option in https://man7.org/linux/man-pages/man8/fsck.8.html. Does this option `-y` supported in all linux? Which version?

**Comment by mengjiao-liu** [comment]
code is here https://github.com/kubernetes/kubernetes/blob/b0010c2d9ea8f2d20ffca20da7846eb4bba6e456/staging/src/k8s.io/mount-utils/mount_linux.go#L339-L358

**Comment by eplightning** [comment]
@pacoxu 

`fsck` passes through unknown options to the filesystem-specific fsck tool. From what I could find it's only really relevant for `ext4` filesystem (`e2fsck` tool):

```
       -y     Assume an answer of `yes' to all questions; allows e2fsck
              to be used non-interactively.  This option may not be
              specified at the same time as the -n or -p options.
```
https://man7.org/linux/man-pages/man8/e2fsck.8.html

I don't really know how safe it is compared to the standard `-a` option, it was the only thing that worked for me at the very least.

**Comment by pacoxu** [comment]
Could you PTAL?  @jingxu97 @jsafrane
cc some experts on this area.
