### ISSUE TITLE
Improve license transparency for vendor/ in Kubernetes

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#94976]
This request is inspired by the recent Debian bug flagged to the Debian Technical Committee: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=970717

Accompanying discussion in #release-management thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1600787651044700

**Why is this needed**:

There is a concern that the libraries in `vendor/` potentially pose DSFG (Debian Free Software Guidelines) concerns: https://lists.debian.org/debian-devel/2020/03/msg00378.html

What does this mean? Under the DFSG, Debian needs to ensure that:

- each dependency is properly listed/inventoried
- each dependency's license is clear
- the requirements of each dependency's license is satisfied (i.e. attribution requirements)

I believe that the open source compatibility of all dependencies and their licenses in Kubernetes' `vendor/` directory have been thoroughly audited upstream (i.e. here, within the context of Kubernetes and k/k) but this information is not currently easy to consume for a downstream project such as Debian. If it were, I believe that Debian would not be raising such concerns.

**What would you like to be added**:

An automated way to list, audit and verify the licenses of all components in the Kubernetes codebase, including dependencies in `vendor/`, and perhaps an attestation that all dependencies' license terms have been met. This should be compatible with existing standards and tools such as SPDX and ClearlyDefined (see e.g. https://clearlydefined.io/definitions/git/github/kubernetes/kubernetes/63dad40a0391b7af32c34fdbf41fa199c3b247ad )

/kind cleanup
/area licensing
cc @kubernetes/licensing @kubernetes/sig-release-leads

**Comment by dims** [comment]
cc @swinslow @nikhita 

fyi, CNCF folks run automation to check if kubernetes conforms to licenses listed here:
https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#cncf-allowlist-license-policy

and publishes exceptions blessed by CNCF GB:
https://github.com/cncf/foundation/tree/master/license-exceptions

**Comment by dims** [comment]
/area code-organization

the code organization (sig-arch) folks including the @kubernetes/dep-approvers work on reviewing incoming dependencies and making sure the licenses are captured here:
https://github.com/kubernetes/kubernetes/tree/master/LICENSES

**Comment by dims** [comment]
@ehashman can we please close this if there isn't anything to do?

**Comment by ehashman** [comment]
@dims sure, I don't think the ask in the original comment has been met :) There currently is not a machine-readable format available for consuming k8s licenses. The CNCF exceptions list, which is, is not for k8s itself.

Ideally, the issues described in the ClearlyDefined report could be addressed.

**Comment by BenTheElder** [comment]
> There currently is not a machine-readable format available for consuming k8s licenses.

I would say that https://github.com/kubernetes/kubernetes/tree/master/LICENSES is fairly machine-readable, simply by matching the text of the license ..? And 1:1 with source directories. This "format" works pretty well because it doesn't require us to modify `vendor/`, leaving it how go defines it *

\* except `vendor/OWNERS`


Other than somehow mutating all files to use an SPDX header, is there some guidance on what this machine readable format should look like? Or is that the expecation?

> Ideally, the issues described in the ClearlyDefined report could be addressed.


I don't see how to view any specific issues in https://clearlydefined.io/definitions/git/github/kubernetes/kubernetes/63dad40a0391b7af32c34fdbf41fa199c3b247ad, which IMHO does not seem very clear, despite the name :|

Are there specific action items / can you point to how this is meant to be interpreted?
Poking around the UI I can't find anything actionable.

**Comment by dims** [comment]
cc @puerco @xmudrii @hasheddan - please add this to the BOM discussion

**Comment by ehashman** [comment]
@BenTheElder I regret that ClearlyDefined's docs are less clear than they could be... I don't have a ton of bandwidth to look into this right now, but I'd consider reaching out to them and asking for help, perhaps on their GH repo? They are probably the most prominent org driving standards right now for this.

**Comment by ehashman** [comment]
@puerco is https://github.com/kubernetes/release/issues/1837 superseding this as a tracking issue? it looks like and actionable, I'd be happy to close

**Comment by puerco** [comment]
In a sense yes, this issue is one of the goals of the Bill of Materials effort. Once we are done scanning the licenses to SPDX I was planning to mark this issue as done.

**Comment by ehashman** [comment]
Excellent, thanks! I'll leave it open then for tracking.
