### ISSUE TITLE
[Flaky test] [sig-node] PreStop should call prestop when killing a pod [Conformance]

### ISSUE THREAD

**Issue by tosi3k** [kubernetes/kubernetes#94994]
**Which jobs are flaking**:
gce-master-scale-correctness

**Which test(s) are flaking**:
[k8s.io] [sig-node] PreStop should call prestop when killing a pod [Conformance]

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-master-scale-correctness

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:629
Sep 22 12:24:26.492: waiting for server pod to start
Unexpected error:
    <*errors.errorString | 0xc000244200>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node/pre_stop.go:74
```

**Anything else we need to know**:
Prow job results: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1308375896645701632

**Comment by nilo19** [comment]
Any update on this? This one is really flaky.

**Comment by nilo19** [comment]
logs from the server pod:
```
default/nettest has 0 endpoints ([]), which is less than 8 as expected. Waiting for all endpoints to come up
```
