### ISSUE TITLE
The filed type of hostPath may not work well

### ISSUE THREAD

**Issue by Aisuko** [kubernetes/kubernetes#94993]
**What happened**:

I write a deployment use `hostPath` and get the error

```
  volumeMounts:
    - mountPath: /kube_config_cluster.yml
      name: kubeconfig
volumes:
  - name: kubeconfig
    hostPath:
    path: /home/aisuko/Documents/cluster/kube_config_cluster.yml
    type: File
```

```
  Warning  FailedMount  57s (x8 over 2m)  kubelet, 172.16.4.12  MountVolume.SetUp failed for volume "kubeconfig" : hostPath type check failed: /home/aisuko/Documents/cluster/kube_config_cluster.yml is not a file
```

If I use optional filed named `type: File/FileOrCreate` I will get the error log above. The document show the filed

Value|Behavior
-- | --
FileOrCreate | If  nothing exists at the given path, an empty file will be created there  as needed with permission set to 0644, having the same group and  ownership with Kubelet.
File | A file must exist at the given path

When I add the filed `type` I will get the error above like `not a file or directory`. 

What's the really mean of the field `type`? 

I'm not sure it's a good way to create this with an issue type bug, if with any maintainer advice I can create this to StackOverflow.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
Is the dir '/home/aisuko/Documents/cluster/' created?

have you seen discussions in https://github.com/kubernetes/kubernetes/pull/87113#issuecomment-592056328

**Comment by Aisuko** [comment]
> Is the dir '/home/aisuko/Documents/cluster/' created?
> 
> have you seen discussions in [#87113 (comment)](https://github.com/kubernetes/kubernetes/pull/87113#issuecomment-592056328)

Thanks for your quickly reply, sir. The path you said was exist at my local cluster nodes which the deployment was scheduled on it, I can confirm that.  If I remove the filed named type the deployment can deploy normal and work well. I will got to watch the issue you said and get something more deeper.
