### ISSUE TITLE
[Flaky Test] [sig-cloud-provider-gcp] Reboot each node by dropping all inbound packets for a while and ensure they function afterwards

### ISSUE THREAD

**Issue by thejoycekung** [kubernetes/kubernetes#95004]
**Which jobs are flaking**:
[
ci-kubernetes-e2e-gci-gce-reboot](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-reboot/1308719603391664128)

**Which test(s) are flaking**:
`Reboot [Disruptive] [Feature:Reboot] each node by dropping all inbound packets for a while and ensure they function afterwards`

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-reboot

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cloud/gcp/reboot.go:135
Sep 23 10:55:53.673: Test failed; at least one node failed to reboot in the time given.
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cloud/gcp/reboot.go:189
```

**Anything else we need to know**:

https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=ach%20node%20by%20dropping%20all%20inbound%20packets%20for%20a%20while%20and%20ensure%20they%20function%20afterwards

**Comment by thejoycekung** [comment]
This test hasn't flaked again since this issue was reported 12 days ago, so we'll be moving it to "Observing" on the CI Signal board. https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=each%20node%20by%20dropping%20all%20inbound%20packets%20for%20a%20while%20and%20ensure%20they%20function%20afterwards

I'm also going to leave this issue open in case there's any want for further discussion. @neolit123 Would it be possible to find the root cause for this flake given there's only one instance recently of non-deterministic results?

**Comment by neolit123** [comment]
@thejoycekung hi, best to ask in #sig-cloud-provider
these tests are maintained by the GCP subproject of SIG Cloud Provider.

**Comment by RobertKielty** [comment]
Passing since Oct 3rd. Will mark as Resolved 2+ weeks and close for now.

/close
