### ISSUE TITLE
[Flaky Test] sig-release-master-blocking/ci-kubernetes-build

### ISSUE THREAD

**Issue by ScrapCodes** [kubernetes/kubernetes#95026]
**Which jobs are flaking**:
ci-kubernetes-build

**Which test(s) are flaking**:
Build

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-blocking#build-master

**Reason for failure**:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-build/1308818253157502976

```
I0923 21:08:54.203] +++ [0923 21:08:54] Building tarball: server linux-amd64
278
I0923 21:12:03.011] +++ [0923 21:12:02] Building tarball: server linux-arm
279
I0923 21:14:58.365] +++ [0923 21:14:58] Building tarball: server linux-arm64
280
I0923 21:18:03.174] +++ [0923 21:18:03] Building tarball: server linux-s390x
281
I0923 21:20:20.101] Terminate 480 on timeout
282
E0923 21:20:20.262] Build timed out
283
E0923 21:20:20.263] Command failed
284
I0923 21:20:20.265] process 480 exited with code -15 after 235.9m
285
E0923 21:20:20.271] FAIL: ci-kubernetes-build
286
I0923 21:20:20.275] Call:  gcloud auth activate-service-account --key-file=/etc/service-account/service-account.json
287
W0923 21:20:26.486] Activated service account credentials for: [pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com]
288
I0923 21:20:26.917] process 351408 exited with code 0 after 0.1m
289
I0923 21:20:26.918] Call:  gcloud config get-value account
290
I0923 21:20:29.187] process 351421 exited with code 0 after 0.0m
```

The average time of this build seems to be 180.
But when we see the graph of build times, they are widely spread, even within the same commit id.

![g1](https://user-images.githubusercontent.com/992952/94129467-ffd68180-fe78-11ea-9572-609d76921a7a.png)

**Anything else we need to know**:
- links to go.k8s.io/triage appreciated

- links to specific failures in spyglass appreciated

**Comment by ScrapCodes** [comment]
It would be great to know, why the build times graph is so wide in spread. Range over 50-200 minutes for even same commit id.

**Comment by BenTheElder** [comment]
/sig release
This is primarily SIG release.

**Comment by ScrapCodes** [comment]
One more recent failure. https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-build/1310989366012678144

**Comment by ScrapCodes** [comment]
Hi @BenTheElder — where can we find more information regarding this issue? Or whom can we approach?

**Comment by justaugustus** [comment]
@kubernetes/release-engineering -- can you look into this?

**Comment by cpanato** [comment]
I will take a look at this job and try to see what is happening
/assign

**Comment by MushuEE** [comment]
@cpanato looks like similar behavior tohttps://github.com/kubernetes/kubernetes/issues/95173

**Comment by thejoycekung** [comment]
closing this one too since #95173 got closed as well

/close
