### ISSUE TITLE
make quick-release on macOS 10.15 fails.

### ISSUE THREAD

**Issue by kvaradhan3** [kubernetes/kubernetes#95020]
System Version: macOS 10.15.6 (19G2021)
      Kernel Version: Darwin 19.6.0
      Time since boot: 19:10

kubernetes [master✗]➜ git remote -v            
origin  https://github.com/kubernetes/kubernetes.git (fetch)
origin  https://github.com/kubernetes/kubernetes.git (push)
kubernetes [master✗]➜ git log --oneline | head -1

*   aad834b0733 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #94438 from claudiubelu/tests/agnhost-usage-refactor-4

```
diff --git a/build/root/Makefile b/build/root/Makefile
index a392aef3248..9644e752fee 100644
--- a/build/root/Makefile
+++ b/build/root/Makefile
@@ -12,7 +12,7 @@
 # See the License for the specific languag
[buildLogs.txt](https://github.com/kubernetes/kubernetes/files/5273314/buildLogs.txt)
e governing permissions and
 # limitations under the License.
 
-DBG_MAKEFILE ?=
+DBG_MAKEFILE ?= 1
 ifeq ($(DBG_MAKEFILE),1)
     $(warning ***** starting Makefile for goal(s) "$(MAKECMDGOALS)")
     $(warning ***** $(shell date))

```
When I do a `make-quick-release`, the kube-build docker container gets stuck and hangs, and eventually terminates with an error:  

```
    test/e2e/e2e.test
    cluster/images/conformance/go-runner
/usr/local/go/pkg/tool/linux_amd64/link: signal: killed
!!! [0923 19:35:45] Call tree:
!!! [0923 19:35:45]  1: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:719 kube::golang::build_some_binaries(...)
!!! [0923 19:35:45]  2: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:863 kube::golang::build_binaries_for_platform(...)
!!! [0923 19:35:45]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0923 19:35:45] Call tree:
!!! [0923 19:35:45]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0923 19:35:45] Call tree:
!!! [0923 19:35:45]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make[1]: *** [Makefile:93: all] Error 1
make[1]: Leaving directory '/go/src/k8s.io/kubernetes'
make: *** [Makefile:507: cross] Error 1
```

**Comment by kvaradhan3** [comment]
/sig architecture
/sig cluster life cycle

(I dont see a specific for build failure, or mac support, so tagging it wtih architecture and cluster-ife-cycle (there are projects around image-builder).  If I am wrong, please correct me.)

**Comment by kvaradhan3** [comment]
Throwing 45G to the build container (configure docker-for-desktop -> Resources)
fixed the issue.

**Comment by BenTheElder** [comment]
for future finders of this: you should only need 40+gb for `make release` (cross compiling all platforms) if you want it to build in parallel (less if not)

you do however need more than the docker default to build quick-release, I think at least 4gb? but I typically give it at least 8 for doing kubernetes compiles etc. 45gb should be much more than necessary for `make quick-release`.
