### ISSUE TITLE
Clean up kubelet --experimental-mounter-path 

### ISSUE THREAD

**Issue by harche** [kubernetes/kubernetes#95030]
**What would you like to be added**:
Kubelet has an experimental GCE specific flag `--experimental-mounter-path`, we need to see if this can be cleaned up. 

**Why is this needed**:
Kubelet has an experimental and GCE specific flag, that needs to be either graduated or removed.

**Comment by harche** [comment]
@dims cc

**Comment by dims** [comment]
@SergeyKanzhelev Any idea if this is still needed in our CI?

**Comment by knabben** [comment]
@harche @dims It was agreed to deprecate them in 1.19 and they will be removed in 1.23.

https://github.com/kubernetes/kubernetes/pull/91373

Here is more context: https://github.com/kubernetes/kubernetes/issues/86843#issuecomment-631173428

**Comment by dims** [comment]
Excellent @knabben , let's leave this issue open to track cleaning up CI scripts that use those flags.

**Comment by SergeyKanzhelev** [comment]
/close

there is no use of this flag any longer: https://github.com/search?q=org%3Akubernetes+experimental-mounter-path&type=code
