### ISSUE TITLE
Graduate scheduler framework to GA

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#95037]
The scheduler framework has been in development since 1.16. It was marked as alpha, but strictly speaking, the framework is not a feature that implements a new user-facing behavior, it is more of a restructuring of the scheduler's code base to allow developers more flexibility to add new functionality.

Since k/k isn't a library and doesn't offer any guarantees around the stability of the interfaces, and since the framework itself is still under `k/k/pkg/scheduler`, I propose the following:
1) Mark the framework KEP as implemented.
2) Move the interfaces out of the `pkg/scheduler/framework/v1alpha1` to `pkg/scheduler/framework`.
3) In the future, move the framework interfaces out to the staging repo, and versioning will follow k8s versions.

/sig scheduling
/cc @Huang-Wei @alculquicondor @damemi

**Comment by damemi** [comment]
I agree with 1 and 3, but should we drop the versioning for the framework? It's probably unlikely that it will be drastically changed but maybe changing to `pkg/scheduler/framework/v1` would also signify the promotion to GA more?

I'm fine with doing it as proposed, just want to bring that possibility up

**Comment by ahg-g** [comment]
I am not sure what purpose that serves if we want to link the api version with k8s version.

**Comment by draveness** [comment]
I think we should also expose `internal/cache` package or provider helper to test the customize scheduling framework plugin.

https://github.com/kubernetes/kubernetes/blob/db9f1e91d977c45fe7df8e1e1bd415a3292995e1/pkg/scheduler/framework/plugins/noderesources/least_allocated_test.go#L289

**Comment by alculquicondor** [comment]
But we already have an interface for it. Maybe we can provide a `testing` package with an implementation of the interface, but the cache itself should remain internal.

**Comment by draveness** [comment]
> But we already have an interface for it. Maybe we can provide a `testing` package with an implementation of the interface, but the cache itself should remain internal.

Yes, provide helper function is also an option.

**Comment by ahg-g** [comment]
https://github.com/kubernetes/enhancements/pull/2054
