### ISSUE TITLE
Use errors.Is in PluginArgs validation tests

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#95047]
/sig scheduling
/kind cleanup

Files:

- https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/apis/config/validation/validation_test.go
- https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/apis/config/validation/validation_pluginargs_test.go

We currently compare the error strings instead of leveraging `errors.Is`, which will ensure the correct types are used.

**Comment by krol3** [comment]
I'd like to give a try :)

**Comment by alculquicondor** [comment]
assign to @pancernik for reviews

**Comment by changshuchao** [comment]
I'd like to give a try too

**Comment by alculquicondor** [comment]
/remove-help

@changshuchao this issue has already people working on it. Keep an eye on open issues :)

**Comment by AliceZhang2016** [comment]
Hi @krol3, are you still working on this? If not, I want to have a try : )
