### ISSUE TITLE
HostToContainer Mount Propagation not working with StorageClass gce-pd

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [kubernetes/kubernetes#95049]
**What happened**:
Pods with HostToContainer mount propagation do not receive existing overlay mounts on a GCP PD.

**What you expected to happen**:
Pods that are use `HostToContainer` value for `mountPropagation`, inherit the relevant mounts on the host.

**How to reproduce it (as minimally and precisely as possible)**:
We have one pod, mounter, that has a GCP PD where it creates overlay mounts. It is configured with Bidirectional mount propagation. [PVC and Mounter deployment manifest](https://gist.github.com/taylorsilva/b38c4d59cf56f46f3d3d8d2aeae4311b#file-pvc-mounter-yml).

```
kubectl create ns vt
kubectl apply -n vt -f pvc-mounter.yml
# wait for pod to come up then check logs to verify mounts were created
kubectl logs -n vt deployment/mounter
```

After creating overlay mounts we create a second pod, consumer, which is configured with HostToContainer mount propagation. [Consumer manifest](https://gist.github.com/taylorsilva/b38c4d59cf56f46f3d3d8d2aeae4311b#file-consumer-yml)

```
kubectl apply -n vt -f consumer.yml
# check logs to see that the mount under `some-pvc` did not propagate.
# The mount under `some-hostpath` does proagate
kubectl logs -n vt deployment/consumer
```

Expected: Mounts under /some-pvc propagate to all future containers.
Actual: Mounts under /some-pvc do not propagate to future containers. They only propagate to containers that exist before the mount was created.

**Anything else we need to know?**:

Our initial experiments were with GCP PD's. We then tried hostPath and found that mount propagation worked as expected. We haven't tried other CSI drivers. Not sure what information is relevant to y'all so here's some of what we thought may be useful.

```
$ k describe sc/standard
Name:                  standard
IsDefaultClass:        Yes
Annotations:           storageclass.beta.kubernetes.io/is-default-class=true
Provisioner:           kubernetes.io/gce-pd
Parameters:            type=pd-standard
AllowVolumeExpansion:  <unset>
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>
```

Side-note: after following the reproducible steps we try and clean up everything in the namespace but everything hangs in a terminating state. This might be a more k8s specific issue but we're unsure what's causing all the various k8s objects (deployments, pods, pvc, pv, etc.) to get stuck in a terminating state and never finish. We can eventually clear everything out with --force --grace-period=0 on all the objects.

**Environment**:
- Kubernetes version (use `kubectl version`): Node Version: `v1.15.9-gke.8` & Master Version: `1.15.12-gke.2`
- Cloud provider or hardware configuration: GCP
- OS (e.g: `cat /etc/os-release`):
```
        BUILD_ID=12371.89.0
	NAME="Container-Optimized OS"
	KERNEL_COMMIT_ID=33b407437b03b80bb02ce71ae6a9caa3a4b2cdf3
	GOOGLE_CRASH_ID=Lakitu
	VERSION_ID=77
	BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
	PRETTY_NAME="Container-Optimized OS from Google"
	VERSION=77
	GOOGLE_METRICS_PRODUCT_ID=26
	HOME_URL="https://cloud.google.com/container-optimized-os/docs"
	ID=cos
```
- Kernel (e.g. `uname -a`):
```
        Linux gke-cluster-1-cos-aa72a8fb-20x1 4.19.76+ #1 SMP Tue Oct 8 23:17:06 PDT 2019 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux
```
- Install tools: n/a
- Network plugin and version (if this is a network-related bug): n/a

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs 
cc @jsafrane do you know if mount propgation works on another mount, or is it only the root directory?

**Comment by jsafrane** [comment]
The pods mount PVC, not a hostpath. I tested with AWS EBS, with the same result. What happens from the host point of view:

1. Kubernetes mounts /dev/xvdck to global mount dir, `/var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/aws/us-east-1d/vol-0bcc0774302141385` (it's a different directory on GCE, but the idea is the same)
2. Kubernetes bind-mounts the blobal dir to pod local dir `/var/lib/kubelet/pods/12b02b97-a56a-4659-b884-97cf95070e5c/volumes/kubernetes.io~aws-ebs/pvc-c9f32e73-0653-4fc4-96cd-a7e341950bcc`
3. Kubernets starts a pod with bidirectional mount propagation with the pod local directory as docker volume.
4. The pod creates /some-pvc/my-merged in the container, which is propagated into the pod local dir on the host, `/var/lib/kubelet/pods/12b02b97-a56a-4659-b884-97cf95070e5c/volumes/kubernetes.io~aws-ebs/pvc-c9f32e73-0653-4fc4-96cd-a7e341950bcc`. **The volume global mount is not affected!**
5. User starts 2nd container and bind-mounts the global dir to new pod local dir, `/var/lib/kubelet/pods/fd49967d-182b-4f31-b233-53e2b1cd6c49/volumes/kubernetes.io~aws-ebs/pvc-c9f32e73-0653-4fc4-96cd-a7e341950bcc`. This bind-mount does not have the overlay! It has been propagated only to the pod local bind-mount!

Mount propagation really works only for hostpath volumes, where there are no global/local bind-mounts and a container gets directly the host directory as a docker volume.

Not sure how to fix this and if it's a good idea.

**Comment by xtreme-sameer-vohra** [comment]
We also observed that if the `overlay mount` in pod1 is executed after pod2 is running, then the mount is propagated to pod2, so the order operations does matter.

From the flow above, is it possible to obtain the global path `/var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/aws/us-east-1d/vol-0bcc0774302141385` and mount that as a `hostPath` mount ?

**Comment by jsafrane** [comment]
There is nothing that would stop you to do that, however, it makes your application not portable. The paths depend on used volume plugin.

**Comment by xtreme-sameer-vohra** [comment]
Right, I meant is there a programatic way of obtaining the path and can it be done prior to the creation of the deployment/pod as it would be used to populate the pod spec ?

**Comment by msau42** [comment]
Is there a way to set mount propagation between the global mount and pod bind mount?

**Comment by xtreme-sameer-vohra** [comment]
We also observed this issue with vSphere volumes as well
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: some-name
provisioner: kubernetes.io/vsphere-volume
```

**Comment by jsafrane** [comment]
It is possible to make the bind mount shared, still... I am not sure it's the right thing to do. All CSI drivers would need to be updated to make NodePublish shared, if they use bind mounts. The same for all bind-mounts we do for subpaths.

IMO, it's much safer to declare that mount propagation works only for HostPath volumes.

@xtreme-sameer-vohra, what is your use case for using GCE PD as a base for mount propagated volumes? None of the data that you mount there are actually stored on the GCE disk. Only the directory structure. How is it better than hostpath or emptyDir?

**Comment by jsafrane** [comment]
> All CSI drivers would need to be updated to make NodePublish shared, if they use bind mounts.

Correction: kubelet can make result of NodePublish shared, if it is a mount point. But we get into the area where kubelet expects that the root of the volume is a mount point. What if there is a subdir on the volume that's used as a mount point?

**Comment by xtreme-sameer-vohra** [comment]
We were trying to come up with a performant local cache to be used in [Concourse](https://concourse-ci.org/) which is a CI tool. The tool would be creating a high volume of short lived workloads and require passing files between these workloads. 

Particularly, we were working around
- creating/deleting IaaS disks is quite slow
- there are IaaS limits on the # of volumes per node

We have had some success by deploying the `cache manager` component as a CSI implementation. This might appears to be a better suited option for what we're trying to accomplish.
