### ISSUE TITLE
Updating Service from LoadBalancer to ClusterIp is resulting with orphaned NLB in AWS

### ISSUE THREAD

**Issue by saiteja313** [kubernetes/kubernetes#95042]
**What happened**:
- When a Service in Kubernetes is updated from type `LoadBalancer` (NLB) to `ClusterIp`, Network Load Balancer and its resources (Target Groups and Worker nodes Security Group NLB ingress rule) were orphaned

**What you expected to happen**:
- NLB, Target Group, Worker nodes Security Group NLB ingress rule should be Deleted.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Pod/Deployment in EKS
   ```
   kubectl create deployment nginx --image nginx
   ```
2. Expose Deployment as Service with type Load Balancer with NLB  `metadata.annotations.service.beta.kubernetes.io/aws-load-balancer-type: nlb`

```
cat << EOF > nginx-nlb-svc.yml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
EOF
```
    kubectl apply -f nginx-nlb-svc.yml
3. Validate NLB created in AWS
4. Update Service in EKS and change it from type `LoadBalancer` to `ClusterIp` by deleting following properties.

    ```
    metadata.annotations.service.beta.kubernetes.io/aws-load-balancer-type: nlb
    spec.externalTrafficPolicy: Cluster
    spec.ports.nodePort: 32188
    spec.type: LoadBalancer
    ```
5. Service will be updated to type `ClusterIp` but Network Load Balancer will be orphaned in AWS.

**Anything else we need to know?**:
1. **Workaround**
- While updating the Service from type `LoadBalancer` to `ClusterIp` in EKS, do not delete annotation `metadata.annotations.service.beta.kubernetes.io/aws-load-balancer-type: nlb`. 
  - This will result in successful update of Service from `LoadBalancer` to `ClusterIp`,
  - NLB and its resources will be deleted in AWS.

2. **Why is `kube-controller-manager` Cloud integration not deleting Network Load Balancer and its resources in AWS?**
   1. kube-controller-logs during the Service update
      
      ```
      1. 1600873003000,"I0923 14:56:43.454663       1 event.go:274] Event(v1.ObjectReference{Kind:""Service"",   Namespace:""default"", Name:""nginx"", UID:""a9b48a4b-dc8f-400b-bc6c-86e4f2603a16"", APIVersion:""v1"", ResourceVersion:""4785364"", FieldPath:""""}): type: 'Normal' reason: 'Type' LoadBalancer -> ClusterIP"

      2. 1600873003000,I0923 14:56:43.474010       1 service_controller.go:850] Removing finalizer from service default/nginx
      3. 1600873003000,I0923 14:56:43.477145       1 service_controller.go:877] Patching status for service default/nginx

      4. 1600873003000,"I0923 14:56:43.477220       1 event.go:274] Event(v1.ObjectReference{Kind:""Service"",  Namespace:""default"", Name:""nginx"", UID:""a9b48a4b-dc8f-400b-bc6c-86e4f2603a16"", APIVersion:""v1"", ResourceVersion:""4785364"", FieldPath:""""}): type: 'Normal' reason: 'DeletedLoadBalancer' Deleted load balancer"
      ```
      1. Reason: 'Type' LoadBalancer -> ClusterIP"
      2. Removing finalizer from service default/nginx
      3. Patching status for service default/nginx
      4. reason: 'DeletedLoadBalancer' Deleted load balancer"
   2. `kube-controller-manager` code base,
      1. Checking Step 2 of above log entries, [`Removing finalizer from service`](https://github.com/kubernetes/kubernetes/blob/3a51aaf8b4baff1242ea30b08d599d913fe7a127/staging/src/k8s.io/cloud-provider/controllers/service/controller.go#L868 ) is invoked part of `removeFinalizer()` function part of `controller.go` file.

        ```
        klog.V(2).Infof("Removing finalizer from service %s/%s", updated.Namespace, updated.Name)
        ```

       2. `removeFinalizer()` function is part of [`syncLoadBalancerIfNeeded()`](https://github.com/kubernetes/kubernetes/blob/3a51aaf8b4baff1242ea30b08d599d913fe7a127/staging/src/k8s.io/cloud-provider/controllers/service/controller.go#L334) function.
          1. syncLoadBalancerIfNeeded() function ensures that service's status is synced up with loadbalancer i.e,
             1. creates loadbalancer for service if requested and
             2. deletes loadbalancer if the service doesn't want a loadbalancer no more.
          2. When a [Service needs Cleanup of Load Balancer](https://github.com/kubernetes/kubernetes/blob/3a51aaf8b4baff1242ea30b08d599d913fe7a127/staging/src/k8s.io/cloud-provider/controllers/service/controller.go#L344), `syncLoadBalancerIfNeeded()` invokes `EnsureLoadBalancerDeleted()` function.
             1. [EnsureLoadBalancerDeleted()](https://github.com/kubernetes/kubernetes/blob/d9bb58fc49d3d4e6e816a45eb8c8ac3e146621e3/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L4453) function is specific to Cloud provider.
             2. [EnsureLoadBalancerDeleted](https://github.com/kubernetes/kubernetes/blob/d9bb58fc49d3d4e6e816a45eb8c8ac3e146621e3/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L4453) function validates Load Balancer type as CLB or NLB using [following condition block](https://github.com/kubernetes/kubernetes/blob/d9bb58fc49d3d4e6e816a45eb8c8ac3e146621e3/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L4459)
                ```
                   if isNLB(service.Annotations) {
   		            lb, err := c.describeLoadBalancerv2(loadBalancerName)
                       <TRUNCATED>
                   }
                   lb, err := c.describeLoadBalancer(loadBalancerName)
                ```
                - If annotation is not available for Service Manifest, it falls back to describe Classic Load Balancer in AWS.
                - Due to this, describeLoadBalancer() (v1 -> CLB) API call was triggered with Network Load Balancer name and resulting with `there is no ACTIVE Load Balancer named xxxxx` from AWS Cloud provider.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15, 1.16, 1.17
- Cloud provider or hardware configuration: AWS
- Others: Tested on AWS EKS Cluster

**Comment by iamchuckss** [comment]
I'd love to give this a try but I'm still getting familiar with the code in AWS cloud provider so it'll help a lot if you could clear out some of my doubts. 

Are there any other ways to check if a load balancer is a NLB other than checking it through the annotations?
Otherwise would it be a good idea to just call `describeLoadBalancerv2` outside of the condition block to check if a NLB exists?

**Comment by mohag** [comment]
This still seems to be an issue, at least on older EKS versions (1.22, which is out of Kubernetes support but still supported by AWS)... I haven't checked against the ALB controller though...
