### ISSUE TITLE
[Flaky Test] DumpClusterLogs can't ssh (invalid format)

### ISSUE THREAD

**Issue by thejoycekung** [kubernetes/kubernetes#95068]
**Which jobs are flaking**:
[gce-cos-master-default](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1309495593508278272)
[gce-cos-master-reboot](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-reboot/1309496346633310208)

**Which test(s) are flaking**:
DumpClusterLogs

**Testgrid link**:
- https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-reboot&sort-by-flakiness=
- https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&sort-by-flakiness=

**Reason for failure**:
```
error during ./cluster/log-dump/log-dump.sh /workspace/_artifacts: exit status 1
```

Backtracking in the build log a bit, it looks like there's something wrong with the gcloud SSH key:
```
W0925 14:37:42.959] load pubkey "/workspace/.ssh/google_compute_engine": invalid format
W0925 14:37:43.649] scp: /var/log/fluentd.log*: No such file or directory
W0925 14:37:43.649] scp: /var/log/node-problem-detector.log*: No such file or directory
W0925 14:37:43.649] scp: /var/log/kubelet.cov*: No such file or directory
W0925 14:37:43.650] scp: /var/log/startupscript.log*: No such file or directory
W0925 14:37:43.659] ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
```

**Anything else we need to know**:
https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=dumpclusterlogs

For both jobs it flaked on commit `3a7d7101c`

**Comment by spiffxp** [comment]
Are you sure this is the actual error?   Do you have links to specific occurrences?

FWIW this doesn't seem to be a new behavior that started recently (e.g. was present as far 
 back as 2020-02-11 https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2020-02-11&pr=1&test=dumpclusterlogs)

**Comment by thejoycekung** [comment]
Sorry it wasn't more clear in the ticket itself - I included two prow links that both flaked on commit `3a7d7101c`:
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-reboot/1309496346633310208
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1309495593508278272

Looking back in triage it looks like this specific ssh-related error doesn't seem to happen *too* frequently (I couldn't find evidence for it in the last two weeks or so) but there are a few jobs from August that have it as well:
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest-1-16/1296316060370210818
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sbeta-alphafeatures/1296343239858589698
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1296335187495358465

My guess currently is that it is to do with ssh purely for the line `load pubkey "/workspace/.ssh/google_compute_engine": invalid format`.

**Comment by thejoycekung** [comment]
It looks like there was [a huge spike with DumpClusterLogs failures/flakes](https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=DumpClusterLogs#9752ffe9b750fef3c11b) a few days ago (when this issue was logged) but it seems to have been resolved now.

![image](https://user-images.githubusercontent.com/13409103/94694134-81f3f980-0302-11eb-9134-9e13b0f54fc6.png)

I do want to dig into the reasons why it spiked, though.

**Comment by RobertKielty** [comment]
Will close this for now and place this in the observing col on the [board](https://github.com/orgs/kubernetes/projects/11).

/close
