### ISSUE TITLE
Alpine Linux _ Kubernetes source code build fail

### ISSUE THREAD

**Issue by bibinphilip** [kubernetes/kubernetes#95062]
Hi,

After installing "go", I had cloned the Kubernetes source code and tried to build it locally by 'root' user on Alpine Linux. However, it is failing at the initial step. Please find attached error image. Please guide how to move further.
![error](https://user-images.githubusercontent.com/35682900/94243374-f1e63680-ff34-11ea-8427-c81b46578c23.png)

**Comment by BenTheElder** [comment]
You need GNU userspace. The shell scripts do not target BusyBox.

**Comment by bibinphilip** [comment]
Thank you @BenTheElder for the response.
Is there any way I can have kubelet on Alpine Linux machine?

**Comment by BenTheElder** [comment]
> Is there any way I can have kubelet on Alpine Linux machine?

You can compile from another machine or use pre-compiled upstream binaries?

`hack/local-up-cluster.sh` is not intended for serious usage, it's a tool for developing kubernetes itself.

you should take a look at the installation docs if you're not trying to develop kubernetes changes.
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

**Comment by BenTheElder** [comment]
https://kind.sigs.k8s.io/ is also an alternative to local-up-cluster.
