### ISSUE TITLE
Support autocomplete more intensively?

### ISSUE THREAD

**Issue by utkarsh2102** [kubernetes/kubernetes#95074]
Hello all,

First of all, really thanks for all the hard work that you put into this! ❤️ 

Whilst trying to get a hang of kubernetes (more specifically, `kubectl`), I noticed that it doesn't support autocomplete.
For example, I have to write `kubectl describe deployment` completely.

(yeah, I have gotten lazy there, that's on me 🙈)
But I think it'd really help all if it could provide autocompletion, for example, `kubectl des<tab>` should autocomplete to `kubectl describe` and then another `<tab>` might list the things that it could _possibly_ describe.

This was just an example, but I am sure you'd know by now what I mean! 😅 

Please let me know if:
- I am missing something? 😞 
- I can help explain this more verbosely.

Thanks, again, for all the work! Y'all rock! \o/

**Comment by utkarsh2102** [comment]
My best guess is:

/sig cli

**Comment by Mackiovello** [comment]
This already exists, take a look at https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-autocomplete 🙂

**Comment by dougsland** [comment]
@utkarsh2102 agree with comment from @Mackiovello. Please consider closing this issue.

**Comment by eddiezane** [comment]
As others have pointed out we kubectl has completion and we're actively working to improve that.

A good issue to follow is https://github.com/kubernetes/kubectl/issues/882.

/close

**Comment by utkarsh2102** [comment]
Right, thanks! :)
