### ISSUE TITLE
Disruption controller handles PodDisruptionBudget with empty selector incorrectly

### ISSUE THREAD

**Issue by seh** [kubernetes/kubernetes#95083]
**What happened**:

[The disruption controller](https://sourcegraph.com/github.com/kubernetes/kubernetes@0f39af90ed39794ceea426aa0f77de67b1392308/-/blob/pkg/controller/disruption/disruption.go#L69-L101) that enforces _PodDisruptionBudgets_ interprets an empty label selector incorrectly—in conflict with how the API machinery treats such an empty selector—defeating attempts to cover all pods in a namespace with a _PDB_.

In a namespace with at least one pod running, create two _PodDisruptionBudgets_:
```yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: inconseqential
spec:
  # NB: The "selector" field is absent.
  minAvailable: 1
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: total
spec:
  selector: {}
  minAvailable: 1
```
I named these "inconsequential" and "total" to clarify their intended interpretation and effect:
- _PDB_ "inconsequential" has no selector, and selects no pods.  
  Since [the `PodDisruptionBudget.Selector` field is optional](https://github.com/kubernetes/api/blob/master/policy/v1beta1/types.go#L34-L37), the validation procedure [allows its omission](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/apis/policy/validation/validation.go#L66).
- _PDB_ "total" has an empty selector, selecting all pods.  
  An empty selector—one that imposes no restricting constraints—[selects everything](https://sourcegraph.com/github.com/kubernetes/apimachinery@master/-/blob/pkg/apis/meta/v1/helpers.go#L38-L40).

[The disruption controller uses the _PDB_'s selector](https://sourcegraph.com/github.com/kubernetes/kubernetes@0f39af90ed39794ceea426aa0f77de67b1392308/-/blob/pkg/controller/disruption/disruption.go#L470-L485) to find pods covered by the budget. There, it mistakenly interprets [the `v1.Labels.Empty` function returning true as meaning that the selector covers no pods](https://sourcegraph.com/github.com/kubernetes/kubernetes@0f39af90ed39794ceea426aa0f77de67b1392308/-/blob/pkg/controller/disruption/disruption.go#L474-L476).
```go
sel, err := metav1.LabelSelectorAsSelector(pdb.Spec.Selector)
if sel.Empty() {
	return []*v1.Pod{}, nil
}
```
Note that [`labels.Selector.Empty`](https://sourcegraph.com/github.com/kubernetes/apimachinery@master/-/blob/pkg/labels/selector.go#L40-L41) means something different. Quoting the documentation:
> Empty returns true if this selector does not restrict the selection space.

That is, the empty label selector selects the universe. Adding restrictions—taking it from empty to populated—narrows its scope, selecting fewer target objects. The `labels.nothingSelector` returned by [`labels.Nothing`](https://sourcegraph.com/github.com/kubernetes/apimachinery@master/-/blob/pkg/labels/selector.go#L81-L84) is [_not_ empty](https://sourcegraph.com/github.com/kubernetes/apimachinery@master/-/blob/pkg/labels/selector.go#L72). It is as full as can be, with so many restrictions that no target can satisfy it. By contrast, the selector returned by [`labels.Everything`](https://sourcegraph.com/github.com/kubernetes/apimachinery@master/-/blob/pkg/labels/selector.go#L64-L67) is empty, because [it contains no restrictions](https://sourcegraph.com/github.com/kubernetes/apimachinery@master/-/blob/pkg/labels/selector.go#L265-L271).

Bringing this back to _PodDisruptionBudget_, a budget with no selector (`PodDisruptionBudget.Selector` is nil) uses `labels.Nothing`. A budget with a present but empty selector (`PodDisruptionBudget.Selector` is non-nil, but an empty map) uses `lables.Everything`. Even though `lables.Everything` is empty, that does not mean that it selects nothing. That means that it imposes no restrictions, and therefore selects the entire universe.

Looking at the _kubectl describe poddisruptionbudgets_ output, we can see this mistaken interpretation:
```
Name:           inconseqential
Namespace:      test
Min available:  1
Selector:       <unset>
Status:
    Allowed disruptions:  0
    Current:              0
    Desired:              1
    Total:                0
Events:
  Type    Reason  Age                From               Message
  ----    ------  ----               ----               -------
  Normal  NoPods  17s (x3 over 39s)  controllermanager  No matching pods found


Name:           total
Namespace:      test
Min available:  1
Selector:       <none>
Status:
    Allowed disruptions:  0
    Current:              0
    Desired:              1
    Total:                0
Events:
  Type    Reason  Age               From               Message
  ----    ------  ----              ----               -------
  Normal  NoPods  3s (x5 over 38s)  controllermanager  No matching pods found
```
Observe that _PDB_ "total" matches no pods, even though there are pods running in that namespace. Its selector is described as "\<none\>", which is how the API machinery's `v1.FormatLabelSelector` [shows a selector with no restrictions](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/helpers.go#L173-L176). There, "none" means "nothing less than the universe".

**What you expected to happen**:

_PDB_ "total" defined above should have covered all the pods in the namespace, instead of none of them.

**How to reproduce it (as minimally and precisely as possible)**:

1. Choose a namespace with at least one running pod.
1. Create a _PodDisruptionBudget_ similar to "total" above, with its "selector" field set to an empty YAML sequence or JSON object (`{}`).
1. Inspect the _PodDisruptionBudget_'s status via _kubectl describe_ or _kubectl get poddisruptionbudget total --output=jsonpath='{.status.expectedPods}'_.
1. Observe that the "expected pods" count is zero, instead of the count of the pods running in the namespace (assuming use of the `PodDisruptionBudget.MinAvailable` field with an integer value).

**Anything else we need to know?**:
This code in the disruption controller came in with commit d60ba3c6e2b7d57441405a108fbfe2b8e38495cc as part of #25921. @davidopp noted in review twice (https://github.com/kubernetes/kubernetes/pull/25921#discussion_r70173015 and https://github.com/kubernetes/kubernetes/pull/25921#discussion_r70173627) that an empty selector matches everything. @mml responded (https://github.com/kubernetes/kubernetes/pull/25921#discussion_r70309635) that he was mimicking behavior from elsewhere, and that we'd trap empty selectors during validation, but as of today we don't. There's also [a comment in the code](https://github.com/kubernetes/kubernetes/pull/25921#discussion_r70309635) that clarifies that @mml intended an empty selector to select nothing, rather than everything.
> // If a PDB with a nil or empty selector creeps in, it should match nothing, not everything.

If we don't intend for _PDBs_ with empty selectors to be meaningful, we should make the `PodDisruptionBudget.Selector` field mandatory, and validate that it's not empty upon creation or update. See kubernetes/enhancements#904 for the latest graduation criteria for _PodDisruptionBudget_.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:  
  AWS EC2
- OS (e.g: `cat /etc/os-release`):  
```
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=2605.4.0
VERSION_ID=2605.4.0
BUILD_ID=2020-09-14-1802
PRETTY_NAME="Flatcar Container Linux by Kinvolk 2605.4.0 (Oklo)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar-linux.org/"
BUG_REPORT_URL="https://issues.flatcar-linux.org"
FLATCAR_BOARD="amd64-usr"
```
- Kernel (e.g. `uname -a`):  
  `Linux ip-10-3-2-117.us-east-2.compute.internal 5.4.65-flatcar #1 SMP Mon Sep 14 17:27:17 -00 2020 x86_64 Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz GenuineIntel GNU/Linux`
- Install tools:  
  _kops_
- Network plugin and version (if this is a network-related bug):  
  Calico version 3.15.3

**Comment by mortent** [comment]
/assign
@seh I agree with your analysis here. Are you interested in making a PR to fix it?

**Comment by seh** [comment]
Yes, though I have several questions in advance:
- Is such a change tolerable, given that it breaks backward compatibility?  
  There's nothing in the current API documentation that prescribes or guarantees the current behavior, but it _is_ a detectable change: _PodDisruptionBudgets_ that used to ignore all pods would now include all pods in the namespace.
- Are we talking about changing the interpretation of a present-but-empty selector?  
  I would delete the conditional mentioned above that checks if the selector is `Empty`, so that an empty selector would now match all the pods in the namespace.
- Are we talking about making the "selector" field mandatory, and disallowing empty selectors?  
  That sounds like something we'd need to consider for the coming _policy/v1_ version of _PodDisruptionBudget_, and not something we could change for _policy/v1beta1_.

**Comment by liggitt** [comment]
> * Is such a change tolerable, given that it breaks backward compatibility?

Probably not.

> * Are we talking about changing the interpretation of a present-but-empty selector?

Doing so for v1beta1 doesn't isn't backwards-compatible. I'm trying to think how that could be compatibly adjusted in v1 to allow the "select all pods" scenario.

> * Are we talking about making the "selector" field mandatory, and disallowing empty selectors?

If we intend to allow full power in the selector field (select no pods, select all pods, select some pods), allowing no selector to mean "select no pods" would make sense, which means it could not be made required.

**Comment by seh** [comment]
I'll hold on proposing any changes until we can agree on a plan.

I had noticed that in one of the abandoned PRs to introduce the _policy/v1_ version of _PodDisruptionBudget_, there was no change in the treatment of the "selector" field. I don't think we should push too quickly forward with that new version without some change on this front, even if it's only documenting this unusual treatment of a label selector.

**Comment by liggitt** [comment]
Agreed. It wasn't an intentional decision, but an oversight on treatment of this field. Added to the list of issues to resolve for GA

**Comment by liggitt** [comment]
one possible way to make v1 behave the way we want while preserving compatibility with v1beta1 (label names are just placeholders):

to make sure a v1beta1 `{}` selector continues to match no pods, we could convert it to/from this internally and in v1:
* v1beta1: `{}`
* internal, v1: `{"matchExpressions":[{"key":"pdb.kubernetes.io/deprecated-v1beta1-empty-selector-match","operator":"Exists"}]}`

to make sure a v1 `{}` selector matches all pods even when round-tripped via v1beta1, we could convert it to/from this in v1beta1:
* internal, v1: `{}`
* v1beta1: `{"matchExpressions":[{"key":"pdb.kubernetes.io/deprecated-v1beta1-empty-selector-match","operator":"DoesNotExist"}]}`

Then, if the controller was using the v1 API, it could treat nil selectors as matching no pods, empty selectors as matching all pods, and selectors converted from v1beta1 would continue to work with the current semantics

**Comment by seh** [comment]
I was immediately thinking of the threat that your last parenthetical remark might address: What if users wind up applying that _pdb.kubernetes.io/..._ label to their pods?

Are you saying that we would restrict users including those labels in their _PDBs_ such that they only matched either of these two constraints (that it is, either it exists, or it doesn't exist)? Would we try to prohibit users from applying that label to pods?

**Comment by liggitt** [comment]
I was saying we would validate the PDBs to make sure the label was only used in exactly those two constructions
