### ISSUE TITLE
Anti-affinity using Pod Annotations doesn't work

### ISSUE THREAD

**Issue by aservera** [kubernetes/kubernetes#95107]
**What happened**:
When I try to apply pod antiaffinity configuration using Pod Annotations in a Replica Set it doesn't be applied
The purpose is to ensure that any new pod created is deployed in a different node than the existing ones.

**What you expected to happen**:
New Pods are created in different nodes
app1-5vwdh   0/1     Running   0          56s   xxx.xxx.35.22    aks-pool-vmss00009c   <none>           <none>
app1-fbkkt   0/1     Running   0          56s   xxx.xxx.35.19    aks-pool-vmss00009c   <none>           <none>
app1-hlhmt   0/1     Running   0          56s   xxx.xxx.35.23    aks-pool-vmss00009c   <none>           <none>
app1-mbv5b   0/1     Running   0          56s   xxx.xxx.9.27     aks-pool-vmss000013   <none>           <none>
app1-p9fcg   0/1     Running   0          56s   xxx.xxx.34.33    aks-pool-vmss00009b   <none>           <none>
app1-pf9n4   0/1     Running   0          56s   xxx.xxx.30.48    aks-pool-vmss000097   <none>           <none>
app1-qgc5t   0/1     Running   0          56s   xxx.xxx.27.123   aks-pool-vmss000094   <none>           <none>
app1-xxh7x   0/1     Running   0          56s   xxx.xxx.35.21    aks-pool-vmss00009c   <none>           <none>
app1-z9drv   0/1     Running   0          56s   xxx.xxx.35.20    aks-pool-vmss00009c   <none>           <none>

**How to reproduce it (as minimally and precisely as possible)**:
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  creationTimestamp: "2020-09-22T12:08:23Z"
  generation: 87
  name: app1-v017
  namespace: ns-d
  resourceVersion: "34090544"
  selfLink: /apis/apps/v1/namespaces/app1-v017
  uid: 7527b6de-e0e8-4875-a40f-3deeb2ea709a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
      cluster: app1
      replication-controller: app1-v017
      version: "17"
      app1-v017: "true"
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/affinity: '["nodeAntiAffinity": { "requiredDuringSchedulingIgnoredDuringExecution":
          { "labelSelector": [ { "matchExpressions": [ { "key": "app", "operator":
          "In", "values": [ "app1" ] } ] } ] }]'
      creationTimestamp: null
      labels:
        app: app1
        cluster: app1
        load-balancer-app1: "true"
        replication-controller: app1-v017
        version: "17"
        app1-v017: "true"
    spec:
      containers:
      - args:
        [...]
status:
  availableReplicas: 9
  fullyLabeledReplicas: 9
  observedGeneration: 87
  readyReplicas: 0
  replicas: 1

**Anything else we need to know?**:
I am using Spinnaker which it doesn't support to use Affinity section

**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"2b13e288f94dd2577d4ff7261f9eb76b1d5692a1", GitTreeState:"clean", BuildDate:"2020-06-01T21:55:34Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: AKS
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ahg-g** [comment]
Annotations is not something the scheduler current supports, see https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity on how node affinity can be used.

**Comment by aservera** [comment]
Thanks we are using Spinnaker and based on some articles that was the way to apply it.
Best
