### ISSUE TITLE
Could not resolve host: github.com

### ISSUE THREAD

**Issue by lixiaobing1** [kubernetes/kubernetes#95104]
When I download code from github.com, it appears : "Could not resolve host: github.com", I add ip and github.com in /etc/hosts, but failure continue, is there other method to solve?

git clone https://github.com/xxx/xxx
Cloning into '/go/src/github.com/xxx/xxx'...
fatal: unable to access 'https://github.com/xxx/xxx/': Could not resolve host: github.com
package github.com/xxx/xxx: exit status 128

**Comment by neolit123** [comment]
Please try the support channels
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
