### ISSUE TITLE
Kubernetes cluster unavailable Unable to connect to the server: EOF

### ISSUE THREAD

**Issue by jakepaw** [kubernetes/kubernetes#95116]
Hello all,

Over the weekend two of our master servers were bounced for updates. One of the servers' kubelet services did not start up which was causing our access to the cluster to fail (see below with EOF error). We have gone with the stacked HA topology as it works best for our use case and we had assumed that with an issue of a master being bounced we would still be able to communicate with our cluster via another master server. Just here looking for more information as to why this may have happened, or to hopefully help someone who experienced this issue. Thank you.

**What happened**:
kubectl commands were not being passed to the control plane due to a single master our of our HA environments kubelet being down. On each master I was receiving

'Unable to connect to the server: EOF'

**What you expected to happen**:
kubectl commands to work correctly since we have HA kubernetes. Why would a single kubelet instance being down out of 3 residing on 3 different masters cause the entire cluster to be unresponsive?

**How to reproduce it (as minimally and precisely as possible)**:
Within a HA cluster (3 masters) shut down or disable kubelet on a single master. Try to connect to your cluster via kubectl.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.17.3
- Cloud provider or hardware configuration:
on prem HA kubernetes cluster. 3 masters with etcd on top. Our VIP is load balanced using HA proxy and keepalived between two load balancing servers. We experienced no issues with the VIP, API services or the like during this issue. 
- OS (e.g: `cat /etc/os-release`):
RHEL 7.7
- Kernel (e.g. `uname -a`):
- Install tools:
Manual install of kubernetes via yum package installs and in-house automation for provisioning
- Network plugin and version (if this is a network-related bug):
Weavenet 
- Others:

**Comment by neolit123** [comment]
/remove-kind bug
/triage support

> We have gone with the stacked HA topology as it works best for our use case and we had assumed that with an issue of a master being bounced we would still be able to communicate with our cluster via another master server.

hi, i'm going to assume kubeadm's stacked topology concept.

/area kubeadm
/sig cluster-lifecycle

> kubectl commands were not being passed to the control plane due to a single master our of our HA environments kubelet being down. On each master I was receiving
> 'Unable to connect to the server: EOF'

this sounds like a stale kubeconfig file, e.g see:
https://stackoverflow.com/questions/48928330/how-to-fix-issue-of-unable-to-connect-to-the-server-eof-kubernetes-kubectl

to regenerate a new `/etc/kubernetes/admin.conf` execute `kubeadm init phase kubeconfig admin` on a control-plane node that has `ca.{key|crt}`.
then you can pass this file explicitly to kubectl using `--kubeconfig`, or move it to the user home dir as instructed here:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#more-information

we usually close similar support tickets and delegate to the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

thanks
/close

**Comment by MurzNN** [comment]
I've got exactly the same problem and now I am tinkering with it already several days without any good progress :( I've asked in support channels, bug get no working advice how to resolve it.

Provided solution using `kubeadm init phase kubeconfig admin` doesn't help, it successfully regenerates the file (if I move previous one, if not - shows the error `[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/admin.conf"`), but the problem is still here: 

- When I shutting down any control-plane node, the whole cluster stops responding! When this node goes back - it starts responding!

I think that many other k8s users can got this problem, so I decided to ask help or advice or some more detailed explanation of this problem here, in this closed issue, because it can be easily find using search engines and will help many users!

**Comment by MurzNN** [comment]
The source of my problem was that I've configured only 2 master nodes, instead of minimal amount of 3 nodes. So when the one of two noes goes down, in `apiserver` pod I've catched the output, describing this problem:
```
{"level":"warn","ts":"2022-03-01T09:19:00.404Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc005d4c000/#initially=[https://127.0.0.1:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
I0301 09:19:01.329907       1 controller.go:611] quota admission added evaluator for: leases.coordination.k8s.io
E0301 09:19:01.815060       1 watcher.go:227] watch chan error: etcdserver: no leader
W0301 09:19:01.815255       1 reflector.go:442] storage/cacher.go:/clusterrolebindings: watch of *rbac.ClusterRoleBinding ended with: Internal error occurred: etcdserver: no leader
E0301 09:19:01.815457       1 watcher.go:227] watch chan error: etcdserver: no leader
E0301 09:19:01.815546       1 watcher.go:227] watch chan error: etcdserver: no leader
```

Viewing logs after node2 is already down is tricky because they are not duplicated to syslog and `kubectl logs` stops working, so to catch this you need to run log watcher in advance, via:
```
kubectl logs -f kube-apiserver-node1 -n kube-system
kubectl logs -f kube-apiserver-node2 -n kube-system
```

**Comment by neolit123** [comment]
In the latest kubeadm HA guide we recommend 3 or more odd number CP
machines.

**Comment by neolit123** [comment]
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/

**Comment by MurzNN** [comment]
> In the latest kubeadm HA guide we recommend 3 or more odd number CP machines.

The problem is that you *recommend*, not *require* them. Can you explicitly describe in the documentation that with only 2 CP users will face unavailability of both nodes, if one of them goes down? Thanks!

**Comment by neolit123** [comment]
Well i guess it is more of a requirement because it is under the prerequisites section.

You are probably seeing this problem as well
https://github.com/kubernetes/kubeadm/issues/2567
I am hoping we can fix it soon.

**Comment by MurzNN** [comment]
> Well i guess it is more of a requirement because it is under the prerequisites section.

Yes, but maybe add a little note there, that with 2 CP nodes unavailability of any single node will lead unavailability of whole cluster API?

**Comment by neolit123** [comment]
> unavailability of any single node will lead unavailability of whole cluster API

Thats actually the bug in etcd that we want to fix with https://github.com/kubernetes/kubeadm/issues/2567

**Comment by mascosta** [comment]
Hi guys, how are you doing?

Well, try to ensure if kubelet service is running, I had the same issue here and a simple 

```bash
systemctl enable --now kubelet
```

Make it work :D
