### ISSUE TITLE
Kubernetes kubelet-certificate-authority on premise with kubespray causes certificate validation error for master node

### ISSUE THREAD

**Issue by papiveron** [kubernetes/kubernetes#95112]
I'm setting up a k8s cluster on premise using kubespray.

I'm trying to harden the kubernetes cluster using CIS Benchmark documentation.

For the `--kubelet-certificate-authority` argument I set up the TLS connection between the apiserver and kubelets. Then, I edited the API server pod specification file `/etc/kubernetes/manifests/kube-apiserver.yaml` on the master node and set the `--kubelet-certificate-authority` parameter for the certificate authority like this : `--kubelet-certificate-authority=/etc/kubernetes/ssl/ca.crt`

But with that I'm not longer able top deploy pods (using helm), having the known error : 

> [centos@infra-vm ~]$ helm list
Error: forwarding ports: error upgrading connection: error dialing backend: x509: cannot validate certificate for 192.168.33.143 because it doesn't contain any IP SANs

Where `192.168.33.143` is the master node IP address.

I've checked the above certificate autority and as you can see it has Notice `Certificate Sign` extension that allows for signing certificates, but it doesn't have IP SANs. 

<img width="603" alt="Screenshot 2020-09-28 at 13 44 23" src="https://user-images.githubusercontent.com/5762296/94428864-bf854500-0191-11eb-89ff-983273d4a87f.png">

I even try to set the above parameter like this using `apiserver.crt` which has no `Certificate Sign` extention but has IP SANs : `--kubelet-certificate-authority=/etc/kubernetes/ssl/apiserver..crt` but got the same error.

So I really can't figure out where the issue comes from .

    [centos@infra-vm ~]$ kubectl get pod --namespace kube-system
    NAME                                        READY   STATUS    RESTARTS   AGE
    calico-kube-controllers-7555c9885c-tjz78    1/1     Running   0          3d21h
    calico-node-2p4p4                           1/1     Running   0          3d21h
    calico-node-4rhzj                           1/1     Running   0          3d21h
    coredns-56bc6b976d-wrxsl                    1/1     Running   0          3d21h
    coredns-56bc6b976d-zlvxb                    1/1     Running   0          3d21h
    dns-autoscaler-5fc5fdbf6-sl6gg              1/1     Running   0          3d21h
    kube-apiserver-cpu-node0                    1/1     Running   0          3d21h
    kube-controller-manager-cpu-node0           1/1     Running   0          3d21h
    nvidia-device-plugin-daemonset-1.12-zj82x   1/1     Running   0          3d20h
    tiller-deploy-677fbf76bb-hcgtw              1/1     Running   0          3d21h

    [centos@infra-vm ~]$ kubectl logs tiller-deploy-677fbf76bb-hcgtw  --namespace kube-system
    Error from server: Get https://192.168.33.143:10250/containerLogs/kube-system/tiller-deploy-677fbf76bb-hcgtw/tiller: x509: cannot validate certificate for 192.168.33.143 because it doesn't contain any IP SANs
    [centos@infra-vm ~]$

From my reading notes I heard I should do this  to make it work.

- Use `/etc/kubernetes/ssl/ca.crt `to sign new certificate for kubelet with valid IP SANs.
- Set` --kubelet-certificate-authority=/etc/kubernetes/ssl/ca.crt` (valid CA).
- In `/var/lib/kubelet/config.yaml` (kubelet config file) set tlsCertFile and tlsPrivateKeyFile to point to newly created kubelet crt and key files.

But please  where do I stand to properly setup the TLS encryption between kubelet and apiserver for hardening purposes as stated above? It's very confusing from the k8s documentation, and in my case I'm working on a kubespray setup.  I'd really appreciate some precise explanation.

Please could one here give a help?

Thank you so much for your attention.

Regards.

**Comment by papiveron** [comment]
`/sig cluster-lifecycle`

**Comment by papiveron** [comment]
Hello,

Please I don't know to apply labels to my issue as indicated above. Can you let me know how? Or it's a matter of rights?

**Comment by neolit123** [comment]
hi, kubespray issues should be logged in:
https://github.com/kubernetes-sigs/kubespray

this repository is for core k8s.

thanks
/close
/triage support
