### ISSUE TITLE
the start time for pod_scheduling_duration_seconds metric should be pod creation time

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#95122]
We currently have a metric named `pod_scheduling_duration_seconds` that measures the time it takes to schedule a pod, specifically from the time the pod was first observed by the scheduler (InitialAttemptTimestamp) to the time the binding request is successfully done: https://github.com/kubernetes/kubernetes/blob/44cd4fcedccbf35c2b674f9d53faa6fc3230b8fa/pkg/scheduler/scheduler.go#L587

The current semantics are asymmetric, we account for the time it take the api server to bind the pod, but we don't account for the time it takes the scheduler to get notified of a pod when it first gets created.

I suggest we change the start time to be that of the pod creation time to properly cover the time it actually takes to schedule a pod.

/sig scheduling

**Comment by arghya88** [comment]
@ahg-g I can work on it..if this is okay to be picked up.

**Comment by ahg-g** [comment]
@wojtek-t since this might be in the millisecond granularity, I am concerned about the the api-server clock and the scheduler clock not being in sync (e.g., in a regional cluster, the active scheduler may be running on a different master instance than the api-server that created the pod), what are you thoughts on this?

**Comment by wojtek-t** [comment]
1. I wouldn't worry about clock skew. There are already other SLOs where we face this same problem, e.g. pod-startup time to not look to far from here (https://github.com/kubernetes/community/blob/master/sig-scalability/slos/pod_startup_latency.md)
All large cloud providers (like GCE) have some mechanisms to eliminate clock skew too.

2. There is a bigger problem that we have though (we have this for pod startup time already, but for this it will be even bigger), which is the fact that "pod creation timestamp" has seconds granularity, e.g. mentioned here https://github.com/kubernetes/perf-tests/issues/1468.
I would ideally get to the point where we switch creation timestamp to microseconds precision (as we have in events: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/events/v1/types.go#L34), but that's a significant thing to do.
[To be more specific, we should ideally figure out a way to migrate both `CreateTimestamp` and `ManagedFieldEntry.Time` to MicroTime.]

**Comment by ahg-g** [comment]
Thanks, I guess then we can't pursue this until the pod creation timestamp is fixed.
