### ISSUE TITLE
Should the function `AreLabelsInWhiteList` return false when the whitelist is empty?

### ISSUE THREAD

**Issue by stevenshuang** [kubernetes/kubernetes#95137]
**What happened**:
The function `AreLabelsInWhiteList` return `false` when whitelist is empty.
The function is implemented as follows:
https://github.com/kubernetes/apimachinery/blob/829ed199f4e0454344a5bc5ef7859a01ef9b8e22/pkg/labels/labels.go#L146
```golang
func AreLabelsInWhiteList(labels, whitelist Set) bool {
	if len(whitelist) == 0 {
		return true
	}

	for k, v := range labels {
		value, ok := whitelist[k]
		if !ok {
			return false
		}
		if value != v {
			return false
		}
	}
	return true
}
```

**What you expected to happen**:
When the whitelist is empty, any key of labels can not in it. Should the function return `false` when whitelist is empty?

**Comment by fedebongio** [comment]
/assign @lavalamp 
/cc @liggitt 
(we think you might have opinions on fixing this)

**Comment by deads2k** [comment]
I only see one consumer.  Rather than change the semantic, I would suggest moving it to the point of use and renaming it.

**Comment by lavalamp** [comment]
Yes, this function is wrong, I agree with David.

P.S. we don't advertise interface stability for this library so this is OK. But even if we did, I think callers of this function are probably not expecting this behavior and should be examined.)

P.P.S. The way it should work is via set difference, the labels should be a subset of the list.

P.P.P.S. These are sets and not lists, and the names should be changed to reflect that.

P.P.P.P.S. If you're making a change here anyway, please lose the word "whitelist".

**Comment by stevenshuang** [comment]
Okay,  I will submit a pr.
