### ISSUE TITLE
defaultpreemption: refactor out support for out-of-tree plugins

### ISSUE THREAD

**Issue by adtac** [kubernetes/kubernetes#95131]
**What would you like to be added**: defaultpreemption plugin has some exported functions that are designed to be reused by out-of-tree plugins. Refactor these out of default_preemption.go. Also, refactor the functions themselves to be cleaner, they're kinda ugly right now.

**Why is this needed**: default_preemption.go is very confusing right now.

/sig scheduling
/kind cleanup
/cc @Huang-Wei @ahg-g @alculquicondor

**Comment by Huang-Wei** [comment]
@adtac do you want to incorporate this into #94814, or in a separate PR?

**Comment by ahg-g** [comment]
I think we could just simplify things in #94814 to not assume that the functions it modifies are stateless (and so no need for the With pattern etc.), then in a followup PR we move those to a type named `PreemptionEvaluator`.

**Comment by Huang-Wei** [comment]
SGTM, so far no consumer is vendoring the 1.20 codebase, so we have enough time finishing the refactoring in a followup.

@adtac apologize for the comments back and forth.

**Comment by adtac** [comment]
np, update the PR -- FindCandidates now uses state from `DefaultPreemption`. I'll refactor that out in a followup.

**Comment by Huang-Wei** [comment]
@adtac A data point FYI on how out-of-tree plugin uses the utilities in `DefaultPreemption`: https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/pkg/crossnodepreemption

**Comment by adtac** [comment]
@Huang-Wei ack. IIRC scheduler-plugins's release cycle is synced with k/k? So if this is the first out-of-tree plugin making use of defaultpreemption methods, we should be fine, yes?

**Comment by Huang-Wei** [comment]
@adtac, it's one release behind, i.e., currently `master` branch of scheduler-plugins is vendoring k/k 1.19.x.

> So if this is the first out-of-tree plugin making use of defaultpreemption methods, we should be fine, yes?

Yes, it should be good. scheduler-plugin will update the deps once 1.20 is cut.

**Comment by adtac** [comment]
/unassign
I don't have the time to work on this

**Comment by Huang-Wei** [comment]
@chendave As you're familiar with the preemption code, are you interested in taking this over?

**Comment by chendave** [comment]
sure, happy to take this over. 

/assign

**Comment by alculquicondor** [comment]
This issue was somewhat purposely vague, as we were not sure what was the right shape for this architecture.

To avoid wasting your time, try to share a couple of high level proposals. But as I said in the PR, you can grab some inspiration from the node resources plugins.

**Comment by chendave** [comment]
> try to share a couple of high level proposals

thanks @alculquicondor , pls let me think about this.

**Comment by chendave** [comment]
@alculquicondor I have sent out the proposal, I tend to go with your idea and make the change accordingly if there is no further comments.
