### ISSUE TITLE
Make Profile an interface

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#95158]
/sig scheduling
/kind cleanup

pkg/scheduler/profile.Profile is no longer necessary as a struct. All its fields are now part of the framework implementation (pkg/scheduler/framework/runtime). Then, Profile can be converted into an interface that the framework implements.

**Comment by tangwz** [comment]
I will give a try.But what should we do about `type Map map[string]*Profile` if we remove `pkg/scheduler/profile.Profile`.

**Comment by alculquicondor** [comment]
`type Map map[string]Profile`

where `Profile` is now an interface.

**Comment by Huang-Wei** [comment]
@tangwz any progress on this?

**Comment by tangwz** [comment]
Sorry I push this PR too late.

@Huang-Wei @alculquicondor PTAL.
