### ISSUE TITLE
Configuration of allowed taint/label keys for NodeRestriction admission controller

### ISSUE THREAD

**Issue by adammw** [kubernetes/kubernetes#95159]
**What would you like to be added**:
AdmissionConfiguration for NodeRestriction admission controller, adding configuration for:
* explicitly allowed taint keys (currently all taints are denied from modification)
* explicitly denied label keys (currently only kubernetes.io labels are prevented from modification)

**Why is this needed**:
Custom node conditions that are used to taint a node based on custom readiness/health checks are a common usecase where it makes sense for the node to self-register with a taint, then untaint itself based on a node-level decision/condition. Currently, NodeRestriction does not allow the taint to be updated forcing the use of an external controller or user to update the node, which is then not limited in scope to only the current node. A configurable allowlist of taint keys would allow the cluster administrator to tell which taint keys NodeRestriction should treat as 'safe' for the node to self-update rather than denying it outright.

On the flipside, there may be labels that the cluster administrator uses for steering workloads that they do not want nodes updating, but the current NodeRestriction plugin only applies the prevention of changes to specific kubernetes.io-prefixed labels.

I think a similar allowlisting was alluded to by @liggitt in the original PR introducing NodeRestriction preventing taint update: https://github.com/kubernetes/kubernetes/pull/63167#issuecomment-384665384

> If we want the kubelet to start setting/updating/removing taints on itself directly, we can discuss the pros/cons of whitelisting specific taints at that point. I could see whitelisting the set that is automatically translated from node-reported conditions->taints, but would want that to be an intentional decision.

While this could also be achieved by a custom admission controller, doing so adds an extra runtime dependency with its own availability problems in what I would suggest is a critical path (node updates) and requires essentially reimplementing what NodeRestriction already does.

/sig auth
/sig node

**Comment by mikedanese** [comment]
> Custom node conditions that are used to taint a node based on custom readiness/health checks are a common usecase where it makes sense for the node to self-register with a taint, then untaint itself based on a node-level decision/condition.

What would be modifying these taints? Kubelet? Some other node agent?

**Comment by adammw** [comment]
> What would be modifying these taints? Kubelet? Some other node agent?

In our setup, we have our bootstrap logic (ie a shell script on boot) running and verifying all checks are passing before sending a request to the API to untaint the node using the node/kubelet identity. While we could use a separate service account/user to allow the request via RBAC, that leaves a larger attack surface where if any node is compromised arbitrary taints can be modified on any node, not just the status taint and not just on the node itself.

**Comment by adammw** [comment]
@mikedanese what should be the next steps here - are you awaiting more evidence from us or the rest of the community to see if its a wider issue?

**Comment by pdbogen** [comment]
I'm not sure whether I can:

/reopen
/remove-lifecycle rotten

But I'd also quite enjoy this feature, for a very similar reason to @adammw.

**Comment by maulerjan** [comment]
Currently Talos Linux has a config option `nodeTaints` which doesn't work on worker nodes because of this admission controller. It would be really nice to be able to configure worker node taints in the same declarative way as all the other config options within Talos.
