### ISSUE TITLE
K8S 容器无法识别JAVA_OPTS参数

### ISSUE THREAD

**Issue by jiamine** [kubernetes/kubernetes#95151]
kubenetes version:1.18.6    jdk:1.8.0_231
我的configmap里配置如下：
apiVersion: v1
kind: ConfigMap
metadata:
  name: cpb-user-map
data:
  JAVA_OPTS: |-
     -XX:InitialHeapSize=1024M -XX:MaxHeapSize=1024m -XX:MetaspaceSize=84m -XX:MaxMetaspaceSize=240m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=logs/java_heapdump.hprof -Xloggc:logs/cbp_user_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M
我的deployment的yaml如下：
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"2"},"creationTimestamp":"2020-09-22T10:43:06Z","generation":2,"labels":{"app":"bian-us"},"name":"bian-us-deployment","namespace":"default","resourceVersion":"2452519","selfLink":"/apis/apps/v1/namespaces/default/deployments/bian-us-deployment","uid":"95652f1a-231e-418f-a512-4f4d563f1b55"},"spec":{"progressDeadlineSeconds":600,"replicas":2,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"bian-us"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"bian-us"}},"spec":{"containers":[{"name":"bian-us","ports":[{"containerPort":8081,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/data/logs","name":"cbp-user-log-volume"}]}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"regcred"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"hostPath":{"path":"/data/logs/cbp-user","type":"Directory"},"name":"cbp-user-log-volume"}]}}}}
  generation: 1
  labels:
    app: bian-us
  name: bian-us-deployment
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bian-us
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bian-us
    spec:
      containers:
      - name: cbp-user
        image: harbor.test.com/bian-us/bian-us:pre-release-test-1.1.6
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "2Gi"
          limits:
            memory: "2Gi"
        command:
        - /usr/bin/java/bin/java
       # - -jar
        - $(JAVA_OPTS)
        - -jar
        - /data/bian-use-1.0.0.jar
        envFrom:
        - configMapRef:
            name: cpb-user-map
         #   name: test-config1
        ports:
        - containerPort: 8081
          protocol: TCP
...................................................................................
pod报错,自动的将-XX:initialHeapSize前面的-XX:给去掉了，如下所示：
[root@master01 ~]# kubectl logs bian-us-deployment-57cdd68487-8llqf
Improperly specified VM option 'InitialHeapSize=1024M -XX:MaxHeapSize=1024m -XX:MetaspaceSize=84m -XX:MaxMetaspaceSize=240m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=logs/java_heapdump.hprof -Xloggc:logs/cbp_user_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M'

这是啥问题？

**Comment by jiamine** [comment]
改变configmap下的JAVA_OPTS参数，kubect apply -f后，启动POD又报如下错误：
[root@master01 ~]# kubectl logs cbp-user-deployment-57cdd68487-cwxrk
Invalid initial heap size: -Xms1024m -Xmx1024m -XX:MetaspaceSize=84m -XX:MaxMetaspaceSize=240m -XX:+HeapDumpOnOutOfMemoryError
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by neolit123** [comment]
hi, please try the support forums, like slack / discuss:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

thanks
/close

**Comment by jiamine** [comment]
> hi, please try the support forums, like slack / discuss:
> https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
> 
> thanks
> /close

ok，thank you!
