### ISSUE TITLE
Add ProcessCollectorMetrics into componet_base

### ISSUE THREAD

**Issue by Jiawei0227** [kubernetes/kubernetes#95152]
**What would you like to be added**:
https://github.com/prometheus/client_golang/blob/6007b2b5cae01203111de55f753e76d8dac1f529/prometheus/process_collector.go#L63

There are some handy metrics in the default registry of prometheus. I am looking at the KubeRegistry in component_base repo here:
https://github.com/kubernetes/component-base/blob/c985e940ef8ffde448c517479bf260be98ce596b/metrics/registry.go#L106
And found that we are building a complete new registry. 

And I also noticed we have https://github.com/kubernetes/component-base/blob/master/metrics/processstarttime.go which is already part of the process metric from prometheus. So I am wondering if anyone has more context about this. And why we are building this instead of just using the default registry which has more already defined metrics. It would be good if we could have some interfaces to add those metrics in the KubeRegistry

**Comment by RainbowMango** [comment]
> And why we are building this instead of just using the default registry which has more already defined metrics.

The reason for that is we want to offer stability guarantees for metrics. For more details, you can refer to [the proposal](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/20190404-kubernetes-control-plane-metrics-stability.md).

**Comment by Jiawei0227** [comment]
> The reason for that is we want to offer stability guarantees for metrics. For more details, you can refer to the proposal.

I see. So I am wondering if there should be a set of default metrics in the KubeRegistry? The reason is that the default registry in prometheus offers some default metrics like process and go related metrics[1]. Some library depends on the metrics to have some of these metrics, like `process_start_time_seconds` to properly parse or process the metrics. I do notice that we have a function[2] in component-base repo which add this `process_start_time_seconds` metric.

I am just wondering if we have considered to add more default metrics in? Or the user should decide which metrics need to be included here, in which case we might need to provide some other functions like [2] for the library user to utilize.

[1] https://github.com/prometheus/client_golang/blob/6007b2b5cae01203111de55f753e76d8dac1f529/prometheus/registry.go#L62
[2] https://github.com/kubernetes/component-base/blob/master/metrics/processstarttime.go
