### ISSUE TITLE
Error For Kubernetes Log "Path "/var/lib/kubelet/pods/xxxx/volumes" does not exist"

### ISSUE THREAD

**Issue by yuanyiran** [kubernetes/kubernetes#95164]
**What happened**:

My kubelet log has been outputting this alarm. I have checked that there is no pod container and folder. How should I check this error?

![image](https://user-images.githubusercontent.com/64528937/94636694-3f352000-0308-11eb-947f-68c3065f6cf7.png)

**What you expected to happen**:

I hope to solve this alarm problem

**How to reproduce it (as minimally and precisely as possible)**:

I restart the underlying docker service, and then all the services in kubernetes are restarted. After the restart, the log is available

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 

![image](https://user-images.githubusercontent.com/64528937/94636813-9d620300-0308-11eb-949c-36de04bebf89.png)

- Cloud provider or hardware configuration:

Alicloud server

- OS (e.g: `cat /etc/os-release`):

![image](https://user-images.githubusercontent.com/64528937/94636877-c8e4ed80-0308-11eb-94ef-42d9c3deb406.png)

- Kernel (e.g. `uname -a`):

Linux node1 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by yuanyiran** [comment]
/sig/storage

**Comment by yuanyiran** [comment]
@k8s-ci-robot

**Comment by neolit123** [comment]
> How to reproduce it (as minimally and precisely as possible):

you'd have to provide a detailed guide on how to reproduce the error.

but also, 1.14.x is no longer in support.
please try reproducing with a newer version (1.17+).

/close

**Comment by pacoxu** [comment]
I have seen similar issues before. However, I cannot find these logs in my cluster which is 1.18.
