### ISSUE TITLE
client-go (and/or api-machinery): given an object with managed fields metadata, make it easy to look up a field's owner

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#95162]
**What would you like to be added**

Given an object with managed fields metadata, make it easy to look up a field's owner.

**Why is this needed**:

It's not obvious how to access the managed fields metadata, which makes it hard for people to see how useful it is / build on it.

**Comment by apelisse** [comment]
Right, this is mostly a question of providing the right API, which I don't think is challenging and makes a lot of sense, thanks!
