### ISSUE TITLE
[Flaky Test] job ci-kubernetes-build-fast flaking due to build timeout.

### ISSUE THREAD

**Issue by ScrapCodes** [kubernetes/kubernetes#95173]
**Which jobs are flaking**:
ci-kubernetes-build-fast #1311141874039263232

**Which test(s) are flaking**:
BUILD FAIL

**Testgrid link**:
https://testgrid.k8s.io/google-unit#build-master-fast

**Reason for failure**:
Build timeout. 

ECG Report:

![g2](https://user-images.githubusercontent.com/992952/94665458-cc3ca100-0329-11eb-84af-41cdf7f31bf1.png)

Wonder why the build time varies so much? Is it due to resource constraints on build machines or something else.

**Anything else we need to know**:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-build-fast/1311141874039263232

**Comment by ScrapCodes** [comment]
Hello All, Last three consecutive builds have failed for this job, I wanted to learn or be coached on how to debug/deflake it.

**Comment by justaugustus** [comment]
@kubernetes/release-engineering -- can you look into this?

**Comment by MushuEE** [comment]
Taking two jobs: [Failed](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-build-fast/1313898308795633664) and [Success](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-build-fast/1313923221132677120). It looks like the major difference in time is running `make clean` and `make quick-release`.

There are [Make runs](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-build-fast/1313879934942318592) that pass but also take very long. If I have more time later I can look into what triggers these being run

**Comment by MushuEE** [comment]
I would almost lean towards increasing the timeout... It seems like the run times come very close to 40m when the `('make', 'clean')` and `('make', 'quick-release')` stages are run

**Comment by spiffxp** [comment]
It's worth noting these still run in the "default" cluster, where most jobs don't declare their resource usage.  Thus it's very possible to land on a node with a noisy neighbor and insufficient resources to complete the job in a timely manner.

I would be more interested in us pushing to migrate all of the build jobs to k8s-infra-prow-build, where all jobs are required to declare resource usage, and the cluster can thus schedule and scale to meet demand.

Lack of progress on https://github.com/kubernetes/k8s.io/issues/846 is the main thing preventing us from doing this

**Comment by spiffxp** [comment]
https://github.com/kubernetes/test-infra/issues/19484 covers migrating this job over

**Comment by ScrapCodes** [comment]
@spiffxp and @cpanato It appears, this build is all green now. I am going to move it to close soon.
