### ISSUE TITLE
Kubelet register fail if a node object already exists with no "Status.Capacity"

### ISSUE THREAD

**Issue by TeddyAndrieux** [kubernetes/kubernetes#95188]
**What happened**:

Kubelet not able to register on ApiServer if a node object already exists and has no "capacity" in "status"

```
kubelet[15418]: E0930 14:11:27.149098   15418 runtime.go:78] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
kubelet[15418]: goroutine 315 [running]:
kubelet[15418]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3d4f200, 0x4b33420)
kubelet[15418]: /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa6
kubelet[15418]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
kubelet[15418]: /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
kubelet[15418]: panic(0x3d4f200, 0x4b33420)
kubelet[15418]: /usr/local/go/src/runtime/panic.go:969 +0x175
kubelet[15418]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).reconcileHugePageResource(0xc000016a80, 0xc000024900, 0xc000bfa000, 0x0)
kubelet[15418]: /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go:146 +0x47b
kubelet[15418]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).tryRegisterWithAPIServer(0xc000016a80, 0xc000024900, 0x0)
kubelet[15418]: /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go:116 +0x48b
kubelet[15418]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).registerWithAPIServer(0xc000016a80)
kubelet[15418]: /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go:71 +0x205
kubelet[15418]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncNodeStatus(0xc000016a80)
kubelet[15418]: /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go:426 +0x14d
kubelet[15418]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000ff9120)
kubelet[15418]: /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
kubelet[15418]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000ff9120, 0x4becee0, 0xc000d015f0, 0x1, 0xc0000b60c0)
kubelet[15418]: /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
kubelet[15418]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000ff9120, 0x2540be400, 0x0, 0x1, 0xc0000b60c0)
kubelet[15418]: /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
kubelet[15418]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc000ff9120, 0x2540be400, 0xc0000b60c0)
kubelet[15418]: /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
kubelet[15418]: created by k8s.io/kubernetes/pkg/kubelet.(*Kubelet).Run
kubelet[15418]: /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1337 +0x397
```

**What you expected to happen**:

Kubelet well registered, even if the node already exists and do not have any "status.capacity" filled.

**How to reproduce it (as minimally and precisely as possible)**:

- Create a simple cluster `kubeadm init`
- Stop kubelet
- Delete node object `kubectl delete node <node_name>`
- Create manually the node 
```
# cat node.yaml 
kind: Node
apiVersion: v1
metadata:
  name: <node_name>
# kubectl apply -f node.yaml
```
- Start kubelet again
- Panic !

(Another approach, you want to extend your cluster and you create the node object before deploying/starting kubelet on the new node then the new kubelet node will not be able to register and get this Panic)

**Anything else we need to know?**:

After some investigation, it seems the `reconcileHugePageResource` function rely on the fact that "Status.Capacity" is a non-nil map, which could not be the case.
I would just add an "if" to initialize the "Capacity" map if this one is nil.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
```
kubeadm version: &version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:38:53Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by derekwaynecarr** [comment]
@TeddyAndrieux thanks for the report.  I suspect the `reconcileExtendedResource` function possibly has the same bug.  I suspect this was introduced when we added support to handle dynamically allocated hugepages rather than pre-allocated.  If you can open a PR, and ping when ready, I would be happy to help get a fix and we can backport.

**Comment by ghouscht** [comment]
FYI: This issue currently block us from updating to 1.19, hope a fix lands in the next point release.
Thanks in advance.

**Comment by NicolasT** [comment]
@ghouscht We didn't manage to get the the fix in #95269 (and its backport to `release-1.19` in #96297) reviewed/LGTM'd before the code freeze deadline for 1.19.5 and 1.20.0, but they should get merged after code thaw next week and be included in 1.19.6 and 1.20.1.

**Comment by TeddyAndrieux** [comment]
Up, (I'm not really familiar with Kubernetes "waterflow" for that kind of bug fixes) from what I see it also needs to be backported to release-1.20 to be part of future 1.20.x versions right ? (I can open the PR if you confirm this)

**Comment by NicolasT** [comment]
@TeddyAndrieux Kubernetes doesn't really use the 'GitWaterflow' approach to branching :disappointed: Instead, indeed, similar to https://github.com/kubernetes/kubernetes/pull/96297 a PR to `release-1.20` which cherry-picks the patch that went into `master` will be needed to get this into 1.20.2 (ideally), since `release-1.20` was cut off `master` after the fix of https://github.com/kubernetes/kubernetes/pull/95269 went in.

**Comment by TeddyAndrieux** [comment]
It's done here #97803
