### ISSUE TITLE
Kubelet does not adequately detected unformatted disk

### ISSUE THREAD

**Issue by jlarriba** [kubernetes/kubernetes#95183]
**What happened**: 
We are using baremetal nodes connected to SAN disks via Fiberchannel. As they are remote, sometimes (as happens with remotely connected systems), the disks stop being available. This causes naturally issues with the pods, and it is not he subject of this issue. The issue is that in this situation, after a failed mount, the kubelet tries to detect if the disk has a correct filesystem. If it does not, it runs mkfs on the disk. When the disks are remote, what could happen is that the disk is unavailable at the moment of testing the filesystem, but becomes available right before the mkfs. In this situation, the kubelet formats a valid disk, erasing the information that it is stored inside.

I have been looking at the code, and I think the blkid check that the kubelet runs on the disk is too broad in this line https://github.com/kubernetes/kubernetes/blob/b4455102ef392bf7d594ef96b97a4caa79d729d9/vendor/k8s.io/utils/mount/mount_linux.go#L353

An exit status of 2 in blkid does not always mean that the disk is unformatted, it only means that the disk had some trouble. The answer should not be "run mkfs" every time blkid returns an exit status of 2.

Would it be possible to make this check more narrow, so the kubelet does not try to format disks just because they are unavailable?

**Environment**:
- Kubernetes version (use `kubectl version`): {Major:"1", Minor:"17", GitVersion:"v1.17.7", GitCommit:"b4455102ef392bf7d594ef96b97a4caa79d729d9", GitTreeState:"clean", BuildDate:"2020-06-17T11:32:20Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: Bare metal server with FC connections

- OS (e.g: `cat /etc/os-release`): Fedora CoreOS 31.20200323.3.2

- Kernel (e.g. `uname -a`): 5.5.10-200.fc31.x86_64

- Install tools: Kubeadm

- Network plugin and version (if this is a network-related bug): n/a

**Comment by lukasmetzner** [comment]
/reopen
/remove-lifecycle rotten

Hey, we ran into a similar issue. The disk was not available “fast enough” and `blkid` returned status code 2. After that, `mkfs` was run and in the meantime the disk appeared. This led to an already formatted disk being formatted again.

Should there maybe be a check if the device exists? Or should this be done in a csi-driver?

For context:
https://github.com/kubernetes/kubernetes/blob/f352123f2e8fbddfbb59d3daa59234c07ddef2ab/staging/src/k8s.io/mount-utils/mount_linux.go#L667-L686
