### ISSUE TITLE
Unix domain socket cause crashes in Windows certain versions

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#95199]
While testing GCE PD CSI driver for Windows, we noticed that it randomly crashes. The root cause is related to Windows unix domain socket. Based on information from Microsoft, the fix is release at this patch https://support.microsoft.com/en-us/help/4559004/windows-10-update-kb4559004. Need to update test Windows image version.

**Comment by jsturtevant** [comment]
Did this get fixed by #95168? could this be closed?

**Comment by jingxu97** [comment]
yes, this issue can be closed.
