### ISSUE TITLE
config.Plugins should not be composed of pointers

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#95190]
There is no benefit of having `pkg/scheduler/apis/config.Plugins` be composed of Pointers rather than concrete `PluginSet`s

We require configurations to explicitly set `disabled: ["*"]` if they want to indicate that they don't want the default plugins. We even create an empty `PluginSet` when we are merging plugin configurations

https://github.com/kubernetes/kubernetes/blob/aa1f91286838d373a6d9217ad9f4fe0647a1c859/pkg/scheduler/apis/config/types.go#L307-L310

The inconvenience of having them as pointers is that sometimes we have to use `nil` and sometimes an empty `PluginSet` in unit tests.

/sig scheduling
/kind cleanup

**Comment by arghya88** [comment]
I am interested to work on this.

**Comment by arghya88** [comment]
It seems if we change all of the fields from pointer to non pointer in kubernetes/pkg/scheduler/apis/config/types.go we also have do same change in https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kube-scheduler/config/v1beta1/types.go#L158.

Otherwise the conversion fails

**Comment by alculquicondor** [comment]
You have to call `make generated_files`

**Comment by gavinfish** [comment]
@alculquicondor I think it should be fine to get rid of the pointers in staging for v1beta2? If so, could you please add this to the umbrella issue?

The PR is a little rough(UT all pass), will wait v1beta2 api getting merged first and polish it.

**Comment by alculquicondor** [comment]
The request is to this only for internal

**Comment by alculquicondor** [comment]
Actually, v1beta2 should be fine too

**Comment by gavinfish** [comment]
yeah, but we need update the conversion anyway. Since we decide to hold on v1beta2, I think it is time for reviewing.
