### ISSUE TITLE
Matched kubectl client/server versions throw "could not find requested resource" errors

### ISSUE THREAD

**Issue by crcsmnky** [kubernetes/kubernetes#9521]
Cluster deployed in GKE (0.18.1) and downloaded matching Kubernetes release tarball. 

Once I set the appropriate context, this command works as expected:

    $ kubectl get pods
    ...

This does not (it did work back in 0.17.0 days):

    $ kubectl create -f controller.yaml
    Error from server: the server could not find the requested resource

Only changes in controller were to `apiVersion` from `v1beta3` to `v1`. All `create` commands seem to have this issue. Any other troubleshooting I can do?

**Comment by crcsmnky** [comment]
Update: retried `create` with specific `api-version` and increased verbosity.

    > kubectl create -f locust-master-controller.yaml --api-version=v1 --v=10
    I0610 10:42:13.327680   70965 helpers.go:82] server response object: [{
      "metadata": {},
      "status": "Failure",
      "message": "the server could not find the requested resource",
      "reason": "NotFound",
      "details": {},
      "code": 404
    }]
    F0610 10:42:13.328129   70965 create.go:51] Error from server: the server could not find the requested resource

Switched back to `v1beta3` and now `create` is working and creating controllers/services.

**Comment by paulbakker** [comment]
Having the same problem (trying to create a service), both when using the Go client and REST. Switching to beta3 works.

**Comment by sameersbn** [comment]
I see the same. switching to `v1beta3` works.

**Comment by nikhiljindal** [comment]
I just tried ```./cluster/kubectl.sh create -f examples/replication.yaml``` on HEAD and it worked fine for me.
Do you face the same issue on HEAD?

**Comment by bprashanth** [comment]
I've run into the same problem on older installations. Don't think it'll repro on upstream/master. We shold clarify the error message for sure, especially since it can happen in the getting-started-flow.

@crcsmnky does curl http://apiserver:port show you v1 as a supported version, or do you just see v1beta{1,2,3}?

**Comment by goltermann** [comment]
Now that we're on v1.x, I suspect this isn't a valid issue anymore.  Please reopen if you disagree.

**Comment by xxlaila** [comment]
I also encountered such a problem, when prompted to create a ui can not find resources, this should be so?
[root@linux1 ~]# kubectl create -f dashboard-controller.yaml
Error from server (NotFound): the server could not find the requested resource
[root@linux1 ~]# kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
Error from server (NotFound): the server could not find the requested resource

**Comment by jhondge** [comment]
I'm reinstall the [kubectl](https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-on-macos) with the same version with minikube version, and it's working now.
