### ISSUE TITLE
[1.19.0] Failed to make webhook authenticator request: converting (v1.TokenReview) to (v1beta1.TokenReview): unknown conversion

### ISSUE THREAD

**Issue by weinong** [kubernetes/kubernetes#95211]
**What happened**:
in [1.19](https://kubernetes.io/docs/setup/release/notes/#deprecation), `authentication.k8s.io/v1beta1` and `authorization.k8s.io/v1beta1` are deprecated in favor of `v1` levels. But the conversion should continue to work I suppose? Instead, when configured with authentication webhook, I see this error
```
E0930 20:32:45.586714       1 webhook.go:111] Failed to make webhook authenticator request: converting (v1.TokenReview) to (v1beta1.TokenReview): unknown conversion
E0930 20:32:45.586886 1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, converting (v1.TokenReview) to (v1beta1.TokenReview): unknown conversion]
``` 
this error goes away when I set `--authentication-token-webhook-version=v1`

since `v1beta1` is just deprecated, should `v1beta1` continue to work? 
Also, should `--authentication-token-webhook-version` default to `v1`?

**What you expected to happen**:
Deprecated API should continue to work until removed

**How to reproduce it (as minimally and precisely as possible)**:
Deploy 1.19.0 on AKS with AAD

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.0
- Cloud provider or hardware configuration: AKS

**Comment by liggitt** [comment]
token webhooks must respond with the same version they were sent. is your webhook responding with v1?

**Comment by liggitt** [comment]
Fallback to reflect-based conversions was removed in 1.19 because they are lossy and mask missing field conversions. There is no defined conversion directly from v1beta1 to v1 TokenReview objects

**Comment by weinong** [comment]
> token webhooks must respond with the same version they were sent. is your webhook responding with v1?

yes. it used to work.

> Fallback to reflect-based conversions was removed in 1.19 because they are lossy and mask missing field conversions. There is no defined conversion directly from v1beta1 to v1 TokenReview objects

is it documented in release note? besides, should `--authentication-token-webhook-version` default to `v1`?

**Comment by liggitt** [comment]
>> is your webhook responding with v1?
>
> yes. it used to work.

Then configuring the API server to send/expect v1 is the correct change to make. 

> is it documented in release note?

The 1.19 release notes called out removal of reflect-based conversions:

> K8s.io/apimachinery - scheme.Convert() now uses only explicitly registered conversions - default reflection based conversion is no longer available.

> should --authentication-token-webhook-version default to v1?

No, it remains at v1beta1 for backwards compatibility with webhooks configured before v1 was an option

**Comment by liggitt** [comment]
clarified docs in https://github.com/kubernetes/website/pull/24349
