### ISSUE TITLE
Error FailedGetResourceMetric is logged in events for test "Kubernetes e2e suite.[sig-autoscaling] [Feature:HPA] Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] ReplicationController light Should scale from 1 pod to 2 pods" on windows docker, process containerd, hyperv containerd server 2019 and server 2004

### ISSUE THREAD

**Issue by bingbing8** [kubernetes/kubernetes#95213]
**What happened**:
When upstream test (Kubernetes e2e suite.[sig-autoscaling] [Feature:HPA] Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] ReplicationController light Should scale from 1 pod to 2 pods) on windows, no matter on docker server 2019, process isolation on server 2019, 2004,hyperv isolation on server 2019, 2004. no matter tests passed or failed, most time there are error events like below. Because events are not displayed for passed tests, so people only see it when test failed. 

Sep 30 02:48:32.823: INFO: At 2020-09-30 02:33:18 +0000 UTC - event for rc-light: {horizontal-pod-autoscaler } FailedGetResourceMetric: unable to get metrics for resource cpu: no metrics returned from resource metrics API
Sep 30 02:48:32.823: INFO: At 2020-09-30 02:33:18 +0000 UTC - event for rc-light: {horizontal-pod-autoscaler } FailedComputeMetricsReplicas: invalid metrics (1 invalid out of 1), first error is: failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API

Investigation details:
combined kubelet logs with test log (both attached), we can confirm containerd returns metrics right after the pod is in ready state and kubelet received the metrics right away.  
But tons of metrics queries are issued before the pod is created, before pod is running, before first success query even and even before hpa is created so the response is empty metric. Even after kubelet received the metrics,  FailedGetResourceMetric event are still loged in the namepace.  but If test wait 1 mins before create hpa, no such error is seen in events.

Here are the timestamps:
1.	Pod creation time: At 2020-09-30 02:32:33 +0000 UTC - event for rc-light-mvl2v: {kubelet 1867k8s001} Created: Created container rc-light
2.	Pod running (container started) 2020-09-30 02:32:42 +0000 UTC - event for rc-light-mvl2v: {kubelet 1867k8s001} Started: Started container rc-light
3.	Start to create hpa at Sep 30 02:33:02.834: INFO: CreateCPUHorizontalPodAutoscaler...
4.	There are ton of metrics query time stamp all the time before timestamp 02:32:41.396051. response is empty metrics. Query is like:
I0930 02:32:31.381777    5140 remote_runtime.go:538] [RemoteRuntimeService] ListContainerStats (filter=&ContainerStatsFilter{Id:,PodSandboxId:,LabelSelector:map[string]string{},})

5.	First success query:
I0930 02:32:41.396051    5140 remote_runtime.go:538] [RemoteRuntimeService] ListContainerStats (filter=&ContainerStatsFilter{Id:,PodSandboxId:,LabelSelector:map[string]string{},})
First metrics return
Line 63066: I0930 02:32:41.408015    5140 remote_runtime.go:551] [RemoteRuntimeService] ListContainerStats Response (filter=&ContainerStatsFilter{Id:,PodSandboxId:,LabelSelector:map[string]string{},}, stats=[&ContainerStats{Attributes:&ContainerAttributes{Id:8eebaa6b960c43374954b5a7fb7f2a2849807a02b06a595178486beeb0b01d4d,Metadata:&ContainerMetadata{Name:rc-light,Attempt:0,},Labels:map[string]string{io.kubernetes.container.name: rc-light,io.kubernetes.pod.name: rc-light-mvl2v,io.kubernetes.pod.namespace: horizontal-pod-autoscaling-1256,io.kubernetes.pod.uid: 445c46a6-5634-4e1d-aa6b-158700200e51,},Annotations:map[string]string{io.kubernetes.container.hash: c633ca3e,io.kubernetes.container.ports: [{"containerPort":80,"protocol":"TCP"}],io.kubernetes.container.restartCount: 0,io.kubernetes.container.terminationMessagePath: /dev/termination-log,io.kubernetes.container.terminationMessagePolicy: File,io.kubernetes.pod.terminationGracePeriod: 1,},},Cpu:&CpuUsage{Timestamp:1601433161404059300,UsageCoreNanoSeco...

6.	Time to FailedGetResourceMetric
2020-09-30 02:33:18 +0000 UTC - event for rc-light: {horizontal-pod-autoscaler } FailedGetResourceMetric: unable to get metrics for resource cpu: no metrics returned from resource metrics API

logs are attached.

**What you expected to happen**:
No error logged in namespace events

**How to reproduce it (as minimally and precisely as possible)**:
Run test "Kubernetes e2e suite.[sig-autoscaling] [Feature:HPA] Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] ReplicationController light Should scale from 1 pod to 2 pods"

**Anything else we need to know?**:
n/a

**Environment**:
- Kubernetes version (use `kubectl version`): v1.19.0 and v1,20
- Cloud provider or hardware configuration: we test on Standard D2 v3 and Standard D4 v3 
- OS (e.g: `cat /etc/os-release`): Windows
- Kernel (e.g. `uname -a`): Linux k8s-master-27464512-0 5.3.0-1032-azure #33~18.04.1-Ubuntu SMP Fri Jun 26 15:01:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: n/a
- Network plugin and version (if this is a network-related bug):
- Others:

[hypberv-2004.log](https://github.com/kubernetes/kubernetes/files/5308825/hypberv-2004.log)
[kubelet.err-20200930T023936.296.log](https://github.com/kubernetes/kubernetes/files/5308830/kubelet.err-20200930T023936.296.log)

**Comment by bingbing8** [comment]
@marosset , this seems a product issue instead of test issue. It is just easy repro by running a tests.

**Comment by ravisantoshgudimetla** [comment]
/assign

Thank you for creating this issue @bingbing8. IIUC, the issue seems to be HPA controller creating those events before those metrics are available. To me, it is ok considering Kubernetes is an eventually consistent system. There will be times where there are errors but eventually the should be sorted out. I also think that this particular test is not flaking out and this issue was created to look at the events created by HPA controller, so we can close this issue. Let me know if you think otherwise

**Comment by ravisantoshgudimetla** [comment]
I am closing this @bingbing8. Please feel free to open this if you think otherwise

/close
