### ISSUE TITLE
Kubernetes 1.16 Ingress apiVersion networking.k8s.io/v1beta does not persist when resource is created

### ISSUE THREAD

**Issue by Mr-Howard-Roark** [kubernetes/kubernetes#95217]
**What happened**:
The 1.16 [deprecation doc](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/) advises to start using the apiVersion `networking.k8s.io/v1beta1` in place of `extensions/v1beta1`.  However, when I apply a basic ingress yaml file that uses that apiVersion and then output the subsequently created resource's yaml I see that the apiVersion switches back to `extensions/v1beta1`.

**What you expected to happen**:
I expect that when I use the apiVersion `networking.k8s.io/v1beta1 `, the subsequently created resource will use that version.

**How to reproduce it (as minimally and precisely as possible)**:
You can apply a basic ingress file with the apiVersion `networking.k8s.io/v1beta1 ` and then `kubectl get ing <name-of-ingress> -o yaml` and you will see that the apiVersion has somehow switched back to `extensions/v1beta1`.

**Anything else we need to know?**:
I raised this as a case with AWS, and they confirmed they see the same behavior in both EKS 1.16 and 1.17.  But, they then said since it is a Kubernetes issue and not an EKS issue, they can only offer "best effort" support or something like that.

**Environment**:
- Kubernetes version: 1.16.13
- Cloud provider or hardware configuration: EKS

/sig  usability
/committee @kubernetes/sig-usability-api-reviews

**Comment by knight42** [comment]
dup of https://github.com/kubernetes/kubernetes/issues/95100
/remove-kind bug api-change
/close

**Comment by Mr-Howard-Roark** [comment]
Ok, I think that is strange that the doc says to use that apiVersion for 1.16 even though apparently you cannot, and it is unexpected that the apiVersion gets swapped out without notifying the user that the apiVersion they're using isn't supported.
