### ISSUE TITLE
[Flaky Test] [sig-storage] Downward API volume should provide container's memory limit [NodeConformance] [Conformance]

### ISSUE THREAD

**Issue by ScrapCodes** [kubernetes/kubernetes#95226]
**Which jobs are flaking**:
node-kubelet-master
**Which test(s) are flaking**:
[sig-storage] Downward API volume should provide container's memory limit [NodeConformance] [Conformance] [cos-stable1]
[sig-storage] Downward API volume should provide container's cpu limit [NodeConformance] [Conformance] [ubuntu]

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-release-master-blocking#node-kubelet-master&width=20
**Reason for failure**:

Both of these tests are failing with same reason.

```
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:629
Unexpected error:
    <*errors.errorString | 0xc001284970>: {
        s: "expected pod \"downwardapi-volume-7241f623-b626-474e-a516-63a30ffccf34\" success: pod \"downwardapi-volume-7241f623-b626-474e-a516-63a30ffccf34\" failed with status: {Phase:Failed Conditions:[] Message:Pod Node didn't have enough resource: cpu, requested: 250, used: 1000, capacity: 1000 Reason:OutOfcpu NominatedNodeName: HostIP: PodIP: PodIPs:[] StartTime:2020-09-30 23:27:58 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[] QOSClass: EphemeralContainerStatuses:[]}",
    }
    expected pod "downwardapi-volume-7241f623-b626-474e-a516-63a30ffccf34" success: pod "downwardapi-volume-7241f623-b626-474e-a516-63a30ffccf34" failed with status: {Phase:Failed Conditions:[] Message:Pod Node didn't have enough resource: cpu, requested: 250, used: 1000, capacity: 1000 Reason:OutOfcpu NominatedNodeName: HostIP: PodIP: PodIPs:[] StartTime:2020-09-30 23:27:58 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[] QOSClass: EphemeralContainerStatuses:[]}
occurred
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:732
```

**Anything else we need to know**:
- links to go.k8s.io/triage appreciated
https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=Downward%20API%20volume%20should%20provide%20container%27s%20memory%20limit

```

Time | Job | Test
-- | -- | --
01/10/2020, 06:04:01 | ci-kubernetes-e2e-windows-containerd-gce-1-18 | [sig-storage] Downward API volume should provide container's memory limit [NodeConformance] [Conformance]
01/10/2020, 01:48:10 | ci-kubernetes-e2e-windows-containerd-gce-1-18 | [sig-storage] Downward API volume should provide container's memory limit [NodeConformance] [Conformance]
30/09/2020, 17:46:43 | ci-kubernetes-e2e-windows-containerd-gce-1-18 | [sig-storage] Downward API volume should provide container's memory limit [NodeConformance] [Conformance]
30/09/2020, 05:40:57 | ci-kubernetes-e2e-windows-containerd-gce-1-18 | [sig-storage] Downward API volume should provide container's memory limit [NodeConformance] [Conformance]
30/09/2020, 01:38:53 | ci-kubernetes-e2e-windows-containerd-gce-1-18 | [sig-storage] Downward API volume should provide container's memory limit [NodeConformance] [Conformance]


```
- links to specific failures in spyglass appreciated
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet/1311445687300263936

/sig storage

**Comment by ScrapCodes** [comment]
Hi @kubernetes/sig-storage-bugs this issue needs your attention.

**Comment by RobertKielty** [comment]
https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=Downward%20API%20volume%20should%20provide%20container%27s%20memory%20limit

**Comment by ScrapCodes** [comment]
Hi @msau42, can you call attention of the relevant folks here as well ?

**Comment by jingxu97** [comment]
For the first test failure posted here on 09/30. The reason is not enough CPU available.  The type of error only happened once, it never happen again for this test.

```
Node didn't have enough resource: cpu, requested: 250, used: 1000, capacity: 1000
```

For the test failure @RobertKielty mentioned, more than half of the tests (150+) failed including this Downward API tests. It happened quite often for ci-kubernetes-e2e-windows-containerd. It seems something wrong with container runtime. The pods are all stuck on pulling image phase, no other events after that and then timed out. Seems containerd for windows have some issues.. 

So I think this specific test is not considered as flaky test.

**Comment by ScrapCodes** [comment]
Latest failure: 

Time | Job | Test
-- | -- | --
01/12/2020, 06:31:17 | ci-kubernetes-e2e-windows-containerd-gce-1-18 | [sig-storage] Downward API volume should provide container's memory limit [NodeConformance] [Conformance]

@jingxu97 Though most flakes are on windows related jobs. But, there are other instances too. Do you think, above failure is for the same reason.

**Comment by jsturtevant** [comment]
I am seeing downward api flakes in the Windows tests as well.  If I broaden the search a bit it seems to happen for more than just memory limit but also:

 Test
--
[sig-storage] Downward API volume should provide container's cpu request [NodeConformance] [Conformance]
 [sig-storage] Downward API volume should provide container's memory request [NodeConformance] [Conformance]
 [sig-storage] Downward API volume should provide container's cpu limit [NodeConformance] [Conformance]
 [sig-storage] Downward API volume should provide container's cpu request [NodeConformance] [Conformance]
[sig-storage] Downward API volume should provide container's cpu request [NodeConformance] [Conformance]


https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=Downward%20API%20volume%20should%20provide%20container%27s%20&xtext=Gave%20up%20after%20waiting%205m0s


For Windows they seem to be failing with the following (both docker and containerd):

```
 Jan 20 03:04:25.127: INFO: Output of node "4302k8s001" pod "downwardapi-volume-3956f3fb-d5fa-4409-b2b5-1f1034f1a228" container "client-container": runtime: VirtualAlloc of 8192 bytes failed with errno=1455
fatal error: out of memory
runtime stack:
runtime.throw(0x1dcb859, 0xd)
	/usr/local/go/src/runtime/panic.go:1116 +0x79
runtime.sysUsed(0xc00027a000, 0x2000)
	/usr/local/go/src/runtime/mem_windows.go:83 +0x22e
runtime.(*mheap).allocSpan(0x2947480, 0x1, 0xf2037f2400, 0x2963128, 0xc00004e000)
	/usr/local/go/src/runtime/mheap.go:1276 +0x3c7
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:907 +0x6b
runtime.systemstack(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:370 +0x6b
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1116
```

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1351723280888762368
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-staging-windows/1351718748989427712
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-2019/1352303041184796672

I will can look into this from a Windows perspective.  
/assign

**Comment by jsturtevant** [comment]
For Windows, I do not believe this is an issue with the test it's self.  I ran this subset of tests continuously over the weekend and got the following results:

```
./hack/ginkgo-e2e.sh --node-os-distro=windows --ginkgo.focus=Downward.API.volume.should.provide.container --ginkgo.skip="\[LinuxOnly\]" --report-dir=/home/jstur/out/kubetest --disable-log-dump=true 

....

Ran 4 of 5708 Specs in 29.746 seconds
SUCCESS! -- 4 Passed | 0 Failed | 0 Pending | 5704 Skipped


All tests passed...
Will keep running them until they fail.
This was attempt #1298
No, seriously... you can probably stop now.
```

The `errno=1455` is "paging file is too small": https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--1300-1699-

> ERROR_COMMITMENT_LIMIT
> 1455 (0x5AF)
> The paging file is too small for this operation to complete.

I was able to force similar (but not exactly the same) errors by over consuming memory via a test pod.   I believe this might be happening due to other tests running on the cluster at the same time.  I am looking into this further.

**Comment by jsturtevant** [comment]
Two tests failed similar to this over the weekend: 
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-1-18-windows/1353402103036383232
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-1-17-windows/1353255640755081216

**Comment by jayunit100** [comment]
FYI , during this @jsturtevant saw some of the issues w/ containerd leaks https://github.com/kubernetes/kubernetes/issues/98102

**Comment by jsturtevant** [comment]
For the aks-engine Containerd test cases we lowered the number of [concurrent tests](https://github.com/kubernetes/test-infra/pull/20613) running to the tests concurrency value we had prior to 1.19 and this has gone away. I am continuing to looking into if this was a regression or if #98102 is releated.

**Comment by jsturtevant** [comment]
We haven't seen this in a long time but it came up today: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1380291921158606848

**Comment by jsturtevant** [comment]
Another failure in gce windows test: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-2019/1381848368606613504

**Comment by jsturtevant** [comment]
another failure here: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-2019/1384388796144947200

**Comment by ravisantoshgudimetla** [comment]
another failure: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-2019/1392067672711106560

**Comment by ravisantoshgudimetla** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-2019-1-21/1391831866138431488

**Comment by marosset** [comment]
/reopen
/remove-lifecycle rotten

We saw this again in master
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows/1615054683896811520

**Comment by jsturtevant** [comment]
We have a lead this might be related to working set bytes vs commit bytes and the way that windows handles memory.

**Comment by pacoxu** [comment]
This still flakes. An example: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-crio-cgroupv1-node-e2e-conformance/1711181558498463744

@jsturtevant are you still working on this?

**Comment by jsturtevant** [comment]
I haven't looked it from a Linux perspective.  From Windows side, it seems this is caused by a mis-match between the commit memory and working set: https://github.com/kubernetes/kubernetes/pull/119238#issue-1799623906

**Comment by jsturtevant** [comment]
> The memory limit set is 64MB, which is a bit low for a Windows Pod, even if it's nanoserver-based (also, the agnhost golang binary is not that small either, it has 44.2 MB on Linux). IMO, we could increase the memory limit to 128MB and we should see fewer flakes.

+1
