### ISSUE TITLE
code-generator: Generation fails if --go-header-file flag is not set

### ISSUE THREAD

**Issue by adambkaplan** [kubernetes/kubernetes#95257]
**What happened**:

When running the code generator (version v0.18.9), not providing the `--go-header-file` flag results in the following error:

```
Failed loading boilerplate: open k8s.io/code-generator/hack/boilerplate.go.txt: no such file or director
```

**What you expected to happen**:

Code generation succeeds without providing a header file.

**How to reproduce it (as minimally and precisely as possible)**:

Run the code generator against the CRD example [1], without providing the `--go-header-file` flag.

**Anything else we need to know?**:

[1] https://github.com/kubernetes/code-generator/tree/master/_examples/crd

**Comment by nikhita** [comment]
@adambkaplan By any chance, did you run the code-generator from the staging directory in k/k? Can you elaborate more on how to reproduce this issue?

When `--go-header-file` is not set, the code-generator defaults the boilerplate to https://github.com/kubernetes/code-generator/blob/master/hack/boilerplate.go.txt. It calculates the path of this file by calculating the relative path to `k8s.io/code-generator` - https://github.com/kubernetes/kubernetes/pull/57656. 

> Run the code generator against the CRD example [1], without providing the --go-header-file flag.

I tried this at the root of the `$GOPATH/k8s.io/code-generator` repo and it worked fine.

> Failed loading boilerplate: open k8s.io/code-generator/hack/boilerplate.go.txt: no such file or director

I only recieved this error when I tried running the script from the staging code-generator directory in k/k _and_ without having k8s.io/code-generator in my $GOPATH. Given that this is not how code-generator is intended to be used, I wouldn't call this a bug.

**Comment by adambkaplan** [comment]
The project I'm working on (github.com/shipwright-io/build) vendors `k8s.io/code-generator`, then calls `generate-groups.sh` in the vendor directory to generate clientsets and deep copies. We are on `v0.17` right now, which doesn't explicitly require the flag. I noticed this issue upgrading the code generator to `v0.18.8`.

With no flag set the `v0.17.x` version generates the k8s copyright boilerplate. In this regard @liggitt is right to call this issue a feature - an error generating incorrect copyright in v0.18 and beyond is better than generating a bad copyright for non-k8s parties.

**Comment by caesarxuchao** [comment]
cc @DirectXMan12 @sttts 
/triage accepted

**Comment by adambkaplan** [comment]
@nikhita also good call out with not having code-generator in the $GOPATH. In my environment $GOPATH was not set, which led the code generator to write the clientset in an incorrect location.
