### ISSUE TITLE
New Fields machinery makes kubectl unusable

### ISSUE THREAD

**Issue by fasaxc** [kubernetes/kubernetes#95255]
**What happened**:

Since the Fields API was added, now every object inherits a huge blob of JSON-encoded data . This make `kubectl` really hard to use; if I try to examine the YAML of a small resource, it's completely dwarfed by all the new metadata and the content is lost.

**What you expected to happen**:

Fields should be a separate, optional resource that only tools should care about.  `kubectl` shouldn't show it by default.

**How to reproduce it (as minimally and precisely as possible)**:

Get any resource on a recent Kubernetes version, with `kubectl -o yaml`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.19

**Comment by liggitt** [comment]
Thanks for the report. Closing as a duplicate of https://github.com/kubernetes/kubernetes/issues/90066
