### ISSUE TITLE
CRD: bad map key type: map keys must be strings

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#95250]
**What would you like to be added**:

We are using Kubebuilder/controller-tools to generate YAMLs for CRDs. We see that it does not allow any maps without string as key.

https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/markers/parse.go#L609-L613

**Why is this needed**:
I am trying to use kubebuilder to generate CRD YAML for VPA. But it uses `map[int]uint32` as seen here:
https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go#L355-L356

My question is whether `map keys must be strings` is a limitation for CRDs from Kubernetes project itself or is this is a limitation of kubebuilder controller-tools generation. Also, where can we find out such restrictions for CRDs?

**Comment by tamalsaha** [comment]
/sig apimachinery
/area custom-resources

cc: @sttts @@bskiba

**Comment by tamalsaha** [comment]
This seems like a restriction of CRD structural schema

https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190425-structural-openapi.md

**Comment by liggitt** [comment]
Yes, map keys must be strings. It is also a restriction of JSON serialization, which only supports strings as map keys
