### ISSUE TITLE
informers: allow some way to tweak syncedPollPeriod

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#95262]
**What would you like to be added**:

Currently our tests call this code very often:
```go
	informers.SharedInformerFactory.Start(stop)
	informers.SharedInformerFactory.WaitForCacheSync(stop)
```

where the informer is backed by a fake client.

While the informer gets synced super quick (under 1ms), it is virtually never synced on the first call to WaitForCacheSync. This triggers a 100ms backoff. This adds up significantly in our testing as we call this 100s of times.

What I would like is **some** way for this to be avoided. I can think of a number of options:

* Expose syncedPollPeriod
* Use backoff instead of fixed syncedPollPeriod
* Expose the informers set by the SharedInformerFactory so we can do the syncing ourselves out of band

**Why is this needed**:

Speed up slow tests

/sig client

**Comment by howardjohn** [comment]
I realize this is not a super important problem, but it has a non trivial impact. By simply adding a 5ms delay before we wait for the sync, we sped up our test times from 25s to 2s.

**Comment by bharath-123** [comment]
Hi @howardjohn. I would like to pick this issue up and submit a PR. As a first time contributes to k8s, this seems like a reasonable place for me to start! :)

**Comment by liggitt** [comment]
> * Expose the informers set by the SharedInformerFactory so we can do the syncing ourselves out of band

You can pass in a closed channel and get an immediate return value with the list of synced informers and poll at your own desired interval like this:

```go
	returnImmediately := make(chan struct{})
	close(returnImmediately)
	if err := wait.PollImmediate(time.Nanosecond, wait.ForeverTestTimeout, func() (bool, error) {
		for informerType, synced := range informerFactory.WaitForCacheSync(returnImmediately) {
			if !synced {
				t.Logf("not yet synced: %v", informerType)
				return false, nil
			}
		}
		return true, nil
	}); err != nil {
		t.Fatal(err)
	}
```

**Comment by howardjohn** [comment]
@liggitt thank you! That works great. I would be happy with closing this, but will let you decide if a more first class solution would be useful for others.
