### ISSUE TITLE
Error: Package: kubelet-1.19.2-0.aarch64 (kubernetes)

### ISSUE THREAD

**Issue by striver619** [kubernetes/kubernetes#95279]
```
[root@localhost ~]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (AltArch) 
[root@localhost ~]# 
[root@localhost ~]# hostnamectl 
   Static hostname: localhost.localdomain
Transient hostname: localhost
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 65a539173aca43bca524c9829d298907
           Boot ID: 1e1074e1bf9b466c8c44774276cfd8c5
    Virtualization: kvm
  Operating System: CentOS Linux 7 (AltArch)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 4.14.0-115.el7a.0.1.aarch64
      Architecture: arm64
[root@localhost ~]#
```

```
[root@localhost ~]# yum -y install kubeadm-1.19.2-0.aarch64 kubectl-1.19.2-0.aarch64 kubelet-1.19.2-0.aarch64
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
Resolving Dependencies
--> Running transaction check
---> Package kubeadm.aarch64 0:1.19.2-0 will be installed
--> Processing Dependency: kubernetes-cni >= 0.8.6 for package: kubeadm-1.19.2-0.aarch64
--> Processing Dependency: cri-tools >= 1.13.0 for package: kubeadm-1.19.2-0.aarch64
---> Package kubectl.aarch64 0:1.19.2-0 will be installed
---> Package kubelet.aarch64 0:1.19.2-0 will be installed
--> Processing Dependency: socat for package: kubelet-1.19.2-0.aarch64
--> Processing Dependency: conntrack for package: kubelet-1.19.2-0.aarch64
--> Running transaction check
---> Package cri-tools.aarch64 0:1.13.0-0 will be installed
---> Package kubelet.aarch64 0:1.19.2-0 will be installed
--> Processing Dependency: socat for package: kubelet-1.19.2-0.aarch64
--> Processing Dependency: conntrack for package: kubelet-1.19.2-0.aarch64
---> Package kubernetes-cni.aarch64 0:0.8.7-0 will be installed
--> Finished Dependency Resolution
Error: Package: kubelet-1.19.2-0.aarch64 (kubernetes)
           Requires: socat
Error: Package: kubelet-1.19.2-0.aarch64 (kubernetes)
           Requires: conntrack
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
[root@localhost ~]#
```

**Comment by striver619** [comment]
> @striver619: There are no sig labels on this issue. Please add an appropriate label by using one of the following commands:
> 
> * `/sig <group-name>`
> * `/wg <group-name>`
> * `/committee <group-name>`
> 
> Please see the [group list](https://git.k8s.io/community/sig-list.md) for a listing of the SIGs, working groups, and committees available.

@k8s-ci-robot  thank you!

**Comment by striver619** [comment]
> /sig release

@liggitt  what do you mean? could you please help me?

```
[root@localhost ~]# yum -y install kubeadm-1.19.2-0.aarch64 kubectl-1.19.2-0.aarch64 kubelet-1.19.2-0.aarch64 /sig release
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
No package /sig available.
No package release available.
Resolving Dependencies
--> Running transaction check
---> Package kubeadm.aarch64 0:1.19.2-0 will be installed
--> Processing Dependency: kubernetes-cni >= 0.8.6 for package: kubeadm-1.19.2-0.aarch64
---> Package kubectl.aarch64 0:1.19.2-0 will be installed
---> Package kubelet.aarch64 0:1.19.2-0 will be installed
--> Processing Dependency: socat for package: kubelet-1.19.2-0.aarch64
--> Processing Dependency: conntrack for package: kubelet-1.19.2-0.aarch64
--> Running transaction check
---> Package kubelet.aarch64 0:1.19.2-0 will be installed
--> Processing Dependency: socat for package: kubelet-1.19.2-0.aarch64
--> Processing Dependency: conntrack for package: kubelet-1.19.2-0.aarch64
---> Package kubernetes-cni.aarch64 0:0.8.7-0 will be installed
--> Finished Dependency Resolution
Error: Package: kubelet-1.19.2-0.aarch64 (kubernetes)
           Requires: socat
Error: Package: kubelet-1.19.2-0.aarch64 (kubernetes)
           Requires: conntrack
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
[root@localhost ~]#
```

**Comment by liggitt** [comment]
[sig-release](https://github.com/kubernetes/community/tree/master/sig-release) is responsible for packaging and artifacts, I'm routing it to the responsible owners

**Comment by striver619** [comment]
> [sig-release](https://github.com/kubernetes/community/tree/master/sig-release) is responsible for packaging and artifacts, I'm routing it to the responsible owners

thank you!

**Comment by justaugustus** [comment]
@kubernetes/release-engineering -- can you look into this?
/area release-eng

**Comment by MonzElmasry** [comment]
Hey :wave: Bug Triage here. Wanted to follow up on the status of this issue as we're approaching code freeze on 12.11.2020. This issue is tagged for 1.20, is it still planned for this release?

**Comment by striver619** [comment]
> Hey 👋 Bug Triage here. Wanted to follow up on the status of this issue as we're approaching code freeze on 12.11.2020. This issue is tagged for 1.20, is it still planned for this release?

Thank you!

**Comment by erismaster** [comment]
👋  Hi, Bug Triage here. We're pretty late into code freeze, so I'm going to bump this to 1.21

/milestone v1.21

**Comment by striver619** [comment]
I'm looking forward to it!

**Comment by LappleApple** [comment]
Hi @striver619, we're having a triage session and reviewed this issue. We'd like to help you find a way to solve this. Are you still interested? If so, @Verolop is happy to work with you. Please let us know, and sorry for the delay in response. 

/priority important-long-term

**Comment by pmmalinov01** [comment]
Have a look at : https://github.com/kubernetes/kubernetes/issues/92242 It seems it is close but not a similar issue.

**Comment by puerco** [comment]
It looks like there is not much to do here. The CentOS variant for `aarch64` does not have the `socat` and `conntrack` packages ([not even in the latest 8 release](http://mirror.jaleco.com/centos/8.3.2011/BaseOS/aarch64/os/Packages/) ) so this dependency cannot be satisfied with just the packages in the base repo.

**Comment by striver619** [comment]
> Hi @striver619, we're having a triage session and reviewed this issue. We'd like to help you find a way to solve this. Are you still interested? If so, @Verolop is happy to work with you. Please let us know, and sorry for the delay in response.

@Verolop

**Comment by striver619** [comment]
Now I'm in Beijing, China. Recently, I don't know why I can't log in to the community, so I've lost contact with you. Today I finally log in. 
I have a thought: if we could not solve this problem based on aarch64 architecture, I'll choose x86_ 64 architecture, but I still hope to have a breakthrough in aarch64 architecture, I hope you can help me! Thank you very much!
In addition, due to the huge delay of visiting GitHub in China, would you like to give me some suggestions?
And my Gmail address is zhangqichenv@gmail.com
and the email address in China is sdzqcainiforever@163.com

**Comment by striver619** [comment]
Just like this, the access is broken and cannot be accessed

![image](https://user-images.githubusercontent.com/51977051/117051090-bde3b700-ad48-11eb-9f47-c682e7286f5c.png)

**Comment by striver619** [comment]
@LappleApple 
Could you please do me a favor?

**Comment by striver619** [comment]
Hi, friends! I'd like to know how's it going?

@erismaster 
@justaugustus 
@liggitt 
@puerco 
@LappleApple

**Comment by voigt** [comment]
Hey there (@striver619 , @puerco, @liggitt, @justaugustus ), Bug-Triage here 👋 ,
looks like this issue hasn't received any update for a couple of weeks. Given the fact that the code freeze for this release already started, do you think this one is still realistic for 1.22?

Otherwise, I'd like to suggest moving this issue to `milestone 1.23` or even clear the milestone label (as this issue seems to be related to k8s 1.19 which will soon run out of maintenance). What do you think?

**Comment by striver619** [comment]
> Hey there (@striver619 , @puerco, @liggitt, @justaugustus ), Bug-Triage here 👋 ,
> looks like this issue hasn't received any update for a couple of weeks. Given the fact that the code freeze for this release already started, do you think this one is still realistic for 1.22?
> 
> Otherwise, I'd like to suggest moving this issue to `milestone 1.23` or even clear the milestone label (as this issue seems to be related to k8s 1.19 which will soon run out of maintenance). What do you think?

Well, I will try my best to deploy k8s 1.19 on aarch64 through source code complation. I believe I can!
By the way, I also believe that we can deploy k8s on aarch64! How about you?

@liggitt @puerco @justaugustus @LappleApple @erismaster @voigt

**Comment by striver619** [comment]
well done!

> @voigt: The provided milestone is not valid for this repository. Milestones in this repository: [`next-candidate`, `v1.16`, `v1.17`, `v1.18`, `v1.19`, `v1.20`, `v1.21`, `v1.22`, `v1.23`, `v1.24`, `v1.25`, `v1.26`]
> 
> Use `/milestone clear` to clear the milestone.
> 
> In response to [this](https://github.com/kubernetes/kubernetes/issues/95279#issuecomment-882118666):
> 
> > /milestone 1.23
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.

**Comment by nannancy** [comment]
Hi 👋 I'm the bug triage shadow. I wanted to nudge the conversation again in the context of 1.23 release. Do we need to follow this up in 1.23?

**Comment by nannancy** [comment]
Hey there (@liggitt ), Bug-Triage here 👋 ,
There hasn't been any activity on this issue. Just want to make sure this issue is still on track for the 1.23?

**Comment by liggitt** [comment]
I'm not tracking this issue, I just routed it to the correct sig

**Comment by justaugustus** [comment]
I'm closing this out, as Kubernetes v1.19 is no longer supported: https://kubernetes.io/releases/patch-releases/#non-active-branch-history

Please feel free to reopen this (with logs), if you're still encountering the issue on a supported version of Kubernetes.
/close
