### ISSUE TITLE
Create a "group" for accessing webhooks via kubectl

### ISSUE THREAD

**Issue by mattmoor** [kubernetes/kubernetes#95280]
**What would you like to be added**:

Adding a "webhooks" group to kubectl to show mutating/validating webhooks would be super useful

```
kubectl get webhooks
```

**Why is this needed**:

There are a few reasons this is useful (to me):
1. I often cannot remember the right names for these resources,
2. They are very long and I often have a typo
3. I often want to enumerate all of them on the system.

cc @soltysh

**Comment by joonas** [comment]
I think this is a great idea, definitely something I could've used in the past.

I'd be interested in taking a pass at implementing this if the proposal gets accepted.

**Comment by deads2k** [comment]
Instead of building a category based on the types we have, I would build the category based on why people look at them.  I suspect a category like `kubectl get api-extensions` which returned

1. mutating admission config
2. validating admission config
3. CRDs
4. APIServices
5. recommendation for various CSI types to list in CRD

would be very helpful.

**Comment by sttts** [comment]
Webhook is far too generic. By putting admission webhooks in there we basically steal that word from the ecosystem to be used for other purposes. "admissionwebhooks" I could agree with.

**Comment by lavalamp** [comment]
Yeah, there are other webhooks, e.g. CRD conversion webhooks or authz webhooks...

**Comment by lavalamp** [comment]
I'd expect the short names "mwc" and "vwc" to be set up, are they not?

**Comment by soltysh** [comment]
> I'd expect the short names "mwc" and "vwc" to be set up, are they not?

Unfortunately, they are not.

**Comment by DirectXMan12** [comment]
does category tolerate namespacing?  i.e. would `webhooks.k8s.io` be tolerated?  Still a bit long, but shorter than `mutatingwebhookconfigurations`

**Comment by soltysh** [comment]
It's a string, so you could theoretically namespace that.
