### ISSUE TITLE
How to get client ip in Kubernetes hosted application?

### ISSUE THREAD

**Issue by EvgenyKhaliper** [kubernetes/kubernetes#95290]
Hi,

I have an application made of a few microservices. UI has is served via Nginx and accesses the API via reverse proxy. This is a local Kubernetes deployed with Rancher.

UI service is NodePort so I can access it outside of the cluster and API can be either NodePort or ClusterIP. In API microservice there is an IP logger that always shows the IP of the Node on which the UI is deployed, no matter what I'm doing.

So far I did try 'externalTrafficPolicy: Local' for the NodePort services in combination with setting Nginx headers (X-Forwarded-For and X-Forwarded-Proto) for reverse proxying. Nothing seems to work.

Is it possible to get client IP in the application hosted in Kubernetes?

Kubernetes Version: v1.17.3

**Comment by neolit123** [comment]
hi, please try the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
