### ISSUE TITLE
Page refresh makes the nodes page hard to operate.

### ISSUE THREAD

**Issue by sleekweasel** [kubernetes/kubernetes#95294]
/sig ui

**What happened**:

Every time I try to update a machine on the nodes page: scrolling to find it, clicking to open the menu, moving to choose the menu item... and then the page refreshes before I click on the menu item.

Similarly, trying to read labels from the 'show all' dynamic link: before I can read all the node labels, and then the page refreshes with its 5 second march.

It's like playing Crossy Road, but without the intellectual rigour.

**What you expected to happen**:

1. When I scroll or click anywhere on a page (even the background), the refresh timer should reset.

2. The local configuration should be able to set the refresh time, in addition to changing the background colour.

3. The local configuration should be able to prevent the page from jumping to the top on refresh - at least, if the user has been active within some locally configurable time.

4. The interface should detect that a press action has (or proactively, might) land in a region of the screen where the resulting operation has changed within a normal human reaction time - different machine, etc - and take suitable action, particularly if the region appears similar: proactively alerting the user of the locally-pertinent change (e.g. displaying a slowly fading a circle around the hovering pointer, beeping, etc) and/or ignoring the probably accidental operation (but with feedback at the site of the click similar to the proactive alert to explain why the operation was ignored).

**How to reproduce it (as minimally and precisely as possible)**:

Have enough things on the nodes page to cause you to need to scroll, and/or be trying to read the labels from the 'Show all' dropdown.

**Anything else we need to know?**:

I can't use the command-line because business reasons mean I only have a token to copy/paste into the website.

Even if there's a global configuration setting for refresh period, this remains a UI issue, because someone's going to be just about to click on something when the page changes underneath their pointer.

This probably happens on other auto-refreshing pages - the nodes page is just my example.

**Environment**:

Dashboard v2.0.1+0.g5b83803
General-purpose web UI for Kubernetes clusters

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
Linux. Unlikely to be relevant.

- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
hi, dashboard tickets should be logged here:
https://github.com/kubernetes/dashboard

/close
