### ISSUE TITLE
mutating requests time out when apiserver has not received any mutating requests in a long time

### ISSUE THREAD

**Issue by staebler** [kubernetes/kubernetes#95300]
**What happened**:
I am running an admission webhook using https://github.com/openshift/generic-admission-server. If there it has been hours since the last mutating request to the webhook, then the next mutating request will take many seconds to be processed. This may even take long enough to have the request time out.

**What you expected to happen**:
A request takes approximately the same amount of time to be processed regardless of how long it has been since the last request.

**How to reproduce it (as minimally and precisely as possible)**:
Create an API server for handling a new API group. Wait a couple hours. Send a CREATE request to the API server. Observe that the CREATE request takes a few seconds to complete.

**Anything else we need to know?**:
This is the offending code. It must loop through once for every second since the last request.
https://github.com/kubernetes/kubernetes/tree/v1.19.0/staging/src/k8s.io/apiserver/pkg/util/flowcontrol/metrics/sample_and_watermark.go#L185-L191

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.0

**Comment by lavalamp** [comment]
I thought we'd already merged a fix for this from @MikeSpreitzer before the release?

**Comment by staebler** [comment]
> I thought we'd already merged a fix for this from @MikeSpreitzer before the release?

I assume that the fix was supposed to be https://github.com/kubernetes/kubernetes/pull/94146. From my understanding, those changes only are in effect if the apiserver is running with priority and fairness enabled. In my situation, I do not have that enabled.

**Comment by lavalamp** [comment]
Ack, if we have the problem in both places we need the fix in both places :)

**Comment by MikeSpreitzer** [comment]
I think we have fixed this in `master`, do you guys agree?
