### ISSUE TITLE
Forward audit-id when following redirects

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#95306]
When following redirects, Kubernetes clients should forward the `audit-id` from the original response in the redirected request. This will make it easier to trace requests that were redirected across servers, and detect malicious redirect attacks. This change is superseded by https://github.com/kubernetes/enhancements/issues/1906, if that enhancement moves forward.

/cc @cjcullen @pwittrock 

/sig auth
/milestone v1.20
/help

**Comment by liggitt** [comment]
Do we allow clients to dictate the audit id today or surface it to them?

**Comment by tallclair** [comment]
We reuse the audit ID from the request header, if specified:
https://github.com/kubernetes/kubernetes/blob/f5a0250800309017e667e82067d704b6ed28513a/staging/src/k8s.io/apiserver/pkg/audit/request.go#L55-L62

Although, there is an open TODO there about whether this should be generally allowed. My thinking is that the audit ID is more useful for debugging an convenience than as a tamper-resistant identifier. It _would_ be problematic if an audit backend was just deduplicating audit events based on the audit ID, discarding messages as a result. One solution would be to append audit IDs (similar to what we did with source IPs), so request & response on the same server would have the same primary audit ID that can't be tampered with, but you could still link server hops (and redirects) with the ID chain.

**Comment by sayanchowdhury** [comment]
👋🏽 Hello @tallclair ! I'm from the Bug Triage Team! I'm dropping a gentle reminder as the code freeze for 1.20 release is starting November 12th which is about 3 weeks from now. Is this issue still intended for the 1.20 release?

**Comment by tallclair** [comment]
I'm going to drop the milestone. I think this needs a bit more discussion, and I'm not going to get to the code before freeze.

**Comment by tallclair** [comment]
- Needs a KEP.
- Add an `AuditIDChain` field to the audit event API
- When API server receives request w/ Audit-ID header, set the audit ID chain to the audit-ID header, but still generate a unique ID for that request
- Response contains full audit ID chain (request chain + new ID)
- When following a redirect, forward the response chain.

**Comment by erismaster** [comment]
Hi @tallclair! I am from the bug triage team, and it's about that time again. Code Freeze is March 9th, 2021. Do you think this issue will make it in this release? Thanks!

**Comment by tallclair** [comment]
I filed a separate issue, https://github.com/kubernetes/kubernetes/issues/101597 to track the work from https://github.com/kubernetes/kubernetes/issues/95306#issuecomment-718140341
