### ISSUE TITLE
Add Kubelet server metrics for response status

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#95307]
The kubelet exposes some metrics HTTP server metrics: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/server/metrics/metrics.go

However, none of the metrics include response status. Response status metrics are useful for identifying authorization problems, or malformed client requests.

/sig instrumentation
/sig node
/help

**Comment by suramrit** [comment]
Im a first time contributor looking for good-first-issues, however this issue does not seem to have a clear indication of where to start with it. Am I missing something ? 
Appreciate any help!

**Comment by JornShen** [comment]
let' s talk about  in https://github.com/kubernetes/kubernetes/pull/95429.:)

**Comment by utkarsh231** [comment]
Hello there, 
I am new to kubernetes and GitHub, a first time contributor . I really want to start working and contributing. A little guidance and support over the topic will be highly appreciated. 
I am looking forward for it. 
Thank you.

**Comment by leilajal** [comment]
@ITonyLi do you still need any help with this?

**Comment by ITonyLi** [comment]
> @ITonyLi do you still need any help with this?

Yes，I don't know how to implement the request hook with golang.

**Comment by ITonyLi** [comment]
@tallclair @leilajal Can you help me review PR?

**Comment by ehashman** [comment]
Glad to see lots of interest on this issue!

@changshuchao @suramrit @ITonyLi @leilajal @vineelyalamarthy please note that @JornShen has already submitted a PR for this issue and discussion on the implementation is happening there: #95429

We do not need additional contributors for this at this time.

/remove-help
