### ISSUE TITLE
Rewriting json-iterator package, to allow compiling k8s with gollvm/llvm-goc and detach from unmaintained reflect2 package

### ISSUE THREAD

**Issue by advancedwebdeveloper** [kubernetes/kubernetes#95302]
Hi. @estesp sent me here.

**What happened**:
Everything was fine - until my build process, in which I used [gollvm](https://go.googlesource.com/gollvm/) compiler, was terminated with such critical errors:

> modern-go/reflect2/type_map.go:74: error: undefined reference to 'reflect.typelinks'
> modern-go/reflect2/type_map.go:78: error: undefined reference to 'reflect.resolveTypeOff'
> modern-go/reflect2/type_map.go:42: error: undefined reference to 'reflect.typelinks'
> 

**What you expected to happen**:
Probably some bugs - but surely not those which originate from such a core feature, like reflection.

**How to reproduce it (as minimally and precisely as possible)**:
Since this bug blocks building nearly all main CNCF projects - I had to use "brute force" approach, by executing

> $go build -i -v -x

in all sub-folders.
You can take the latest available ["release"](https://drive.google.com/file/d/15KD-isorTza_pLjg6l43Bxb1f0QNx4f5/view?usp=sharing) build of gollvm (targeting [Clang 11 RC4](https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0-rc4/clang+llvm-11.0.0-rc4-x86_64-linux-gnu-ubuntu-20.04.tar.xz) build ).
Ensure that your VM, container image or a bare metal OS does not have "ordinary" Golang distribution installed (to avoid any conflicts) or ensure that no LLVM/Clang/libc++ was installed and extract both Clang and gollvm distribution via
> $sudo cp -R * /usr/
. This should be enough to start reproducing this.

**Anything else we need to know?**:
Everything that I was able to investigate/received references from others:
[Reduce sizes of binaries](https://github.com/kubernetes/kubernetes/issues/76506)
[Use json-iterator instead of ugorji for JSON](https://github.com/kubernetes/kubernetes/pull/48287)
[undefined reference to 'reflect.typelinks' for gccgo and gollvm](https://github.com/modern-go/reflect2/issues/9)
[Build kubernetes with gollvm](https://groups.google.com/g/golang-nuts/c/DM6QYVGqyZE)
[bugs with gollvm](https://github.com/modern-go/reflect2/issues/16)

**Environment**:

- OS (e.g: `cat /etc/os-release`):

NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

- Kernel (e.g. `uname -a`):
 Linux oceanfish81-VirtualBox 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by liggitt** [comment]
The gollvm project appears to be in a pre-release state, and has various statements in its FAQ that suggest that incompatibilities with the go compiler are expected. I would suggest opening an issue against the gollvm project instead.

/close
