### ISSUE TITLE
missing a non-Slow, targetted UDP NodePort test  in the sig-network testing suite

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#95315]
**What happened**:

In CAPA clusters, NodePorts are disabled for UDP but not for TCP, so when testing, we see a small hole in coverage that was luckily caught by the `Conntrack` tests....   So, I noticed that we thus don't have a targetted ginkgo test for UDP + nodeports, but we do seem to have the Contract one, which I guess tests two things at once:

- UDP NodePort service works
- Conntrack can persist the service

We **do** have

```
should be able to change the type and ports of a service [Slow] [DisabledForLargeClusters]
```
but this test is obviously testing many other things as well.

So, would like to have a `should verify that NodePort services work with UDP` test....

**What you expected to happen**:

running the sig-network test suite, while skipping `Slow` with UDP not working would result in a test failure specific to  UDP and NodePorts.

**How to reproduce it (as minimally and precisely as possible)**:

Run the `sig-network` test suite, skip `Conntrack|Slow`, with a UDP firewall up - you'll see no relevant failures. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): master

**Comment by aojea** [comment]
There is already one testing NodePort UDP in `Service Granular Checks` https://github.com/kubernetes/kubernetes/blob/9646d5998c49cb2ab8a6be96925ca992b1d2b1b3/test/e2e/network/networking.go#L347-L357

**Comment by aojea** [comment]
However, the more tests the better :+1:

**Comment by jayunit100** [comment]
Hiya Antonio. 

I think the one your talking about in granular checks is also tagged as "Slow".....


Is there a Fast one? If so I'll close this issue don't want to make a redundant test .

**Comment by aojea** [comment]
> Is there a **FAST** one? If so I'll close this issue don't want to make a redundant test . :)

I honestly don't know the history of the Slow tag and I don't see it consistently applied, but if you think that you can improve the Granular check and have an additional faster test, then just go for it :muscle:

**Comment by jayunit100** [comment]
ok cool
