### ISSUE TITLE
The connection to the server localhost:8080 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by venkateshreddy1388** [kubernetes/kubernetes#95317]

**Comment by gaurav-gupta-gtm** [comment]
Check issue #44665. Issue already solved.

**Comment by neolit123** [comment]
this can be caused by a stale kubeconfig file.
for general support questions please try the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
