### ISSUE TITLE
cAdvisor metrics are missing Kubernetes labels

### ISSUE THREAD

**Issue by kamsz** [kubernetes/kubernetes#95322]
**What happened**:

cAdvisor metrics are missing Kubernetes labels e.g. namespace

```
container_network_receive_bytes_total{endpoint="https-metrics",id="/",instance="10.10.10.6:10250",interface="cali0987905a120",job="kubelet",metrics_path="/metrics/cadvisor",node="2",service="prometheus-operator-kube-p-kubelet"}
```

**What you expected to happen**:

cAdvisor metrics to have Kubernetes labels.

**How to reproduce it (as minimally and precisely as possible)**:

* Deploy a cluster with kubeadm
* Deploy Calico as CNI
* Deploy Prometheus using prometheus-operator Helm chart
* Take a look at gathered metrics

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.2
- Cloud provider or hardware configuration: Baremetal
- OS (e.g: `cat /etc/os-release`): CentOS 7
- Kernel (e.g. `uname -a`): 5.8.12-1.el7.elrepo.x86_64
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): Calico 3.16.1
- Others: None

**Comment by veeshall** [comment]
We are facing similar issue with as well. Is there any workaround for this?

**Comment by pacoxu** [comment]
I tried in 1.21.0-beta.0 with Prometheus operator. I cannot reproduce it.

As Cadvisor is upgrading rapidly, would you try v1.19.8 (github.com/google/cadvisor:   v0.37.4)
Kubernetes v1.19.2 is using Cadivsorv0.37.0. 

If you have many nodes, upgrading the kubelet on one node to test is enough.
