### ISSUE TITLE
NodeIP isn't consistent with the probing client, when running "should update nodePort: udp [Slow]" tests, resulting in inconsistent results.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#95339]
**What happened**

When we test  nodeports (see the various granular checks in networking.go) , you can get unpredictable results if your firewall is up.  For example, 

if you have blocked UDP traffic in your cluster, 1/n of the time the `should support nodePort on udp` test will pass (even if you have a firewall around nodes), b/c 1/n times, your probe container is on the same node as the node port of the first node.

The other (n-1)/n times, your client is on a DIFFERENT node then the `NodeIP` (which is the first node in your cluster), and thus, this test will fail . 

```
	// External ip of first node for use in nodePort testing.
	NodeIP string
```

This basically means that this test has a random behaviour due to the fact that polling results will differ depending on where the TEST POD is relative to the NODE PORT.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

I guess to make the test results consistent when running this test, we should either:
- run the probing container "TestContainerPod" on the **same node** as the NodeIP, every time
- run the probing container on a **different node** then the NodeIP, every time (anti-affinity or direct schedule it to `Node2IP` which should work since these tests skip on clusters w/ nodes < 2

**Comment by jayunit100** [comment]
@aojea curious your thoughts on this: 

```
node1:                         node2:
   test-container
   nodeport
```

vs

```
node1:                         node2:
     nodeport                           test-container
```

**Comment by aojea** [comment]
Personally, I think that we we should validate everything that is supposed to work, so we should test both if we can.

> test container is outside of node1

Absolutely agree that this is the most important, is just how people use NodePorts, so we need to be sure we never break that and we have to gate on that.


Great catch by the way

**Comment by bridgetkromhout** [comment]
@danwinship says: should always probe from a different node

/assign @danwinship

**Comment by thockin** [comment]
Why are we running e2e with firewalls up?

**Comment by bridgetkromhout** [comment]
discussion on SIG-network: these tests need adjustment - either test both, or just from outside to NodePort.
/assign @aojea

**Comment by aojea** [comment]
I'm going to close this because:
- I can't remember the last bug on NodePort, that kind of says we are not doing too bad on the testing area :)
- is not easy to scale the test for large number of nodes if we poll every node, we run tests with 100,500 and 1k nodes
- the e2e test is not meant to verify a deployment, it's for testing the project, so if you use a firewall you should be carefull
- it was open for more than 3 months, and is stale, if we find out that closing was wrong we can always reopen
/close
