### ISSUE TITLE
SERVICE object in kubernetes 

### ISSUE THREAD

**Issue by mseewooth** [kubernetes/kubernetes#95349]
Hello, 

I'm currently using metallb-system on my k8s cluster. i have a question regarding SERVICE object. 

Are services replicated across workers in a kubernetes cluster ? 

For e.g metallb assigned an IP to a service type loadbalancer.  In the logs of pod metallb that the assigned IP is on workerA .

Which means the service is on workerA and the traffic will come directly in workerA and then distributed across other nodes.

Please let me know if a Service in k8s is replicated across nodes or its scheduled to run on specific node ? 

THank you very much

**Comment by neolit123** [comment]
hi, please try the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
