### ISSUE TITLE
Summary API test is a bit flaky

### ISSUE THREAD

**Issue by harche** [kubernetes/kubernetes#95344]
**Which jobs are flaking**:
[Kubelet-node-master](https://k8s-testgrid.appspot.com/sig-release-master-blocking#node-kubelet-master)

**Which test(s) are flaking**:
[Summary API NodeConformance](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/summary_test.go#L41)

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-release-master-blocking#node-kubelet-master

**Reason for failure**:
Based on the execution conditions sometimes the value of `Node.SystemContainers[pods].CPU.UsageNanoCores` could be 0 instead of expected 10000

**Anything else we need to know**:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

**Comment by harche** [comment]
This particular test also fails on CRIO with Fedora CoreOS platform because the return value of `/stats/summary` is slightly different on that platform.

https://github.com/kubernetes/kubernetes/issues/95343

**Comment by alejandrox1** [comment]
@harche thank you for opening this issue.
Just to have more visibility in the future, and avoid duplicated work, could you please share issues like this one in #sig-node or with the mailist list for CI improvements https://groups.google.com/g/kubernetes-sig-node-test-failures ?

I also see you opened so will assign you this issue https://github.com/kubernetes/kubernetes/pull/95345
/assign @harche 

/triage accepted
/priority important-longterm
/cc @kubernetes/sig-node-test-failures

**Comment by RobertKielty** [comment]
@harce thank you for opening and working on this issue.

You can check the [CI Signal project board ](https://github.com/orgs/kubernetes/projects/11#card-46917235) for issues logged against tests that are producing non-deterministic results. 

And also it is worth noting that #95017 that @thejoycekung logged has a [triage link](https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=when%20querying%20%2Fstats%2Fsummary%20should%20report%20resource%20usage%20through%20the%20stats%20api) for this problem along with the following specific failures

- [ci-kubernetes-node-kubelet/1308821020399898624](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet/1308821020399898624) 

- [ci-kubernetes-node-kubelet/1308774969034936320](prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet/1308774969034936320)

**Comment by harche** [comment]
@RobertKielty sorry I wasn't aware of CI Signal project board. Thanks for the link.

**Comment by harche** [comment]
@alejandrox1 sorry my bad, I didn't realize there was already an issue for this.

**Comment by harche** [comment]
More failures around not having NetworkStats and MemoryStats,
https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=when%20querying%20%2Fstats%2Fsummary%20should%20report%20resource%20usage%20through%20the%20stats%20api

**Comment by harche** [comment]
```
Oct 08 06:52:06 tmp-node-e2e-03246eac-ubuntu-gke-1804-1-16-v20200330 kubelet[3462]: I1008 06:52:06.388156    3462 container.go:490] Start housekeeping for container "/kubepods/besteffort/podb29673ff-eb3c-43d0-a298-12f8d81178de"
Oct 08 06:52:06 tmp-node-e2e-03246eac-ubuntu-gke-1804-1-16-v20200330 kubelet[3462]: I1008 06:52:06.388223    3462 handler.go:181] Unable to get Process Stats: couldn't open cpu cgroup procs file /sys/fs/cgroup/cpu,cpuacct/kubepods/besteffort/podb29673ff-eb3c-43d0-a298-12f8d81178de/cgroup.procs : open /sys/fs/cgroup/cpu,cpuacct/kubepods/besteffort/podb29673ff-eb3c-43d0-a298-12f8d81178de/cgroup.procs: no such file or directory
Oct 08 06:52:06 tmp-node-e2e-03246eac-ubuntu-gke-1804-1-16-v20200330 kubelet[3462]: I1008 06:52:06.388242    3462 container.go:490] Start housekeeping for container "/kubepods/besteffort/pod5357fc89-a43b-4d69-932d-ce1932046256"
Oct 08 06:52:06 tmp-node-e2e-03246eac-ubuntu-gke-1804-1-16-v20200330 kubelet[3462]: I1008 06:52:06.388289    3462 handler.go:181] Unable to get Process Stats: couldn't open cpu cgroup procs file /sys/fs/cgroup/cpu,cpuacct/kubepods/besteffort/pod5357fc89-a43b-4d69-932d-ce1932046256/cgroup.procs : open /sys/fs/cgroup/cpu,cpuacct/kubepods/besteffort/pod5357fc89-a43b-4d69-932d-ce1932046256/cgroup.procs: no such file or directory
Oct 08 06:52:06 tmp-node-e2e-03246eac-ubuntu-gke-1804-1-16-v20200330 kubelet[3462]: I1008 06:52:06.399049    3462 cri_stats_provider.go:443] Unable to find network stats for sandbox 
```
From the kubelet logs of one of the failed jobs. https://storage.googleapis.com/kubernetes-jenkins/logs/ci-cri-containerd-node-e2e/1314090071145582592/artifacts/tmp-node-e2e-03246eac-ubuntu-gke-1804-1-16-v20200330/kubelet.log

Open the failed job's kubelet.log and look for `cri_stats_provider.go`

**Comment by harche** [comment]
```diff
diff --git a/vendor/github.com/google/cadvisor/fs/fs.go b/vendor/github.com/google/cadvisor/fs/fs.go
index cb45c33c933..421a6186fa3 100644
--- a/vendor/github.com/google/cadvisor/fs/fs.go
+++ b/vendor/github.com/google/cadvisor/fs/fs.go
@@ -559,6 +559,14 @@ func (i *RealFsInfo) GetDirFsDevice(dir string) (*DeviceInfo, error) {
                mount, found = i.mounts[dir]
        }
 
+       if found && mount.FsType == "xfs" {
+               if err != nil {
+                       klog.Warningf("%s", err)
+               } else {
+                       return &DeviceInfo{mount.Source, uint(mount.Major), uint(mount.Minor)}, nil
+               }
+       }
+
        if found && mount.FsType == "btrfs" && mount.Major == 0 && strings.HasPrefix(mount.Source, "/dev/") {
                major, minor, err := getBtrfsMajorMinorIds(&mount)
                if err != nil {
``` 

helped me to get rid of errors related fsinfo not available. I do some more testing. It's just a temporary patch which looks for `xfs` because that's what I am using. If it really works, I could make it more generic.
