### ISSUE TITLE
NodeProblemDetector [NodeFeature:NodeProblemDetector] is flaky

### ISSUE THREAD

**Issue by harche** [kubernetes/kubernetes#95357]
**Which jobs are flaking**:
ci-kubernetes-node-kubelet-features

**Which test(s) are flaking**:
NodeProblemDetector [NodeFeature:NodeProblemDetector]

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-node-kubelet#node-kubelet-features-master

**Reason for failure**:
The time during set for the event in past is too short. https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/node_problem_detector_linux.go#L267

**Anything else we need to know**:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

**Comment by harche** [comment]
I am looking into it.

**Comment by MHBauer** [comment]
looks like dup of https://github.com/kubernetes/kubernetes/issues/94493

I'm generally wary of "increase the timeouts" or "increase the resources" as solutions to problems.

**Comment by karan** [comment]
This may be fixed by https://github.com/kubernetes/kubernetes/pull/96050.

**Comment by harche** [comment]
@karan it indeed seems to be fixed. I had 3 runs of node e2e using Fedora CoreOS as host and that test passed all the time.

**Comment by karan** [comment]
@harche The node npd grid still shows it as failing (#96272)

**Comment by harche** [comment]
@karan interesting, I had several runs in last few hours and on Fedora CoreOS the test didn't fail at all. But looking at the failures you are seeing, I will reopen the issue.
