### ISSUE TITLE
Pass secret in NodeExpansion Call for the CSI driver

### ISSUE THREAD

**Issue by humblec** [kubernetes/kubernetes#95367]
In different use cases we need "secret" passed to the CSI driver to perform NodeExpansion which is missing atm .  One of the very visible use case is that, the expansion on LUKS enabled device, which needs the passphrase in order to resize the device on the node.

One other use case is that, at times we need to check the actual size of the image ( for ex: RBD image size in Ceph Cluster) before proceeding on FS resize to avoid false positive returns on fs resize operation. For that we have to connect to the backend cluster which need secret in the request.

Reference#
CSI spec issue # https://github.com/container-storage-interface/spec/issues/445
CSI spec PR # https://github.com/container-storage-interface/spec/pull/457 

**What happened**:

**What you expected to happen**:

CSI plugin/driver get `NodeExpandSecret` which is same as `ControllerExpandSecret`.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by gnufied** [comment]
How would this work for existing PVs which don't have the secret? We will have similar problem when we first started copying secrets from storageclass onto PVs.

**Comment by humblec** [comment]
> How would this work for existing PVs which don't have the secret? We will have similar problem when we first started copying secrets from storageclass onto PVs.

I think copying it from the SC is not a good idea as we expect the SC to go away at any point in time. So existing PVCs can be left with "unsupported" ..

**Comment by humblec** [comment]
@gnufied are you already on this ? if not, please feel free to assign to me.
