### ISSUE TITLE
cpumanager "ignoring terminated container" should not be a warning

### ISSUE THREAD

**Issue by grosser** [kubernetes/kubernetes#95380]
kubernetes 1.19.2

seeing tons of these, feels like something that should be debug or info ... not really actionable or something that it should warn about ?

```
W1007 20:33:44.086277    4842 cpu_manager.go:397] [cpumanager] reconcileState: ignoring terminated container
```

/sig node

**Comment by jdambly-ns** [comment]
I am also seeing this same issue
`W1215 05:19:33.418996 1804473 cpu_manager.go:397] [cpumanager] reconcileState: ignoring terminated container (pod: rook-ceph-crashcollector-knode01.c1.sv5.nskope.net-7bb9d99d8s6z, container id: c4b50b26767f78cc00e75f5603f571925a1589d7227d83b7cddd0d03a6805842)

root@knode01:~# docker container ls -a --no-trunc -q     | grep c4b50b26767f78cc00e75f5603f571925a1589d7227d83b7cddd0d03a6805842`

what's odd is that I cannot find the container it's looking for which is probably why its giving this message, so my question would be why is it looking for this container ID?

**Comment by matthyx** [comment]
I agree this should be lower than warning...

/triage accepted
/help

**Comment by cynepco3hahue** [comment]
I think all InfoS messages under the https://github.com/kubernetes/kubernetes/blob/b0010c2d9ea8f2d20ffca20da7846eb4bba6e456/pkg/kubelet/cm/cpumanager/cpu_manager.go#L370 should be moved to debug messages because it flood the log when the CPU manager enabled with the static policy.
