### ISSUE TITLE
[Doc] k8s upgrading document missing "cert upgrade manually" on additional control plane nodes 

### ISSUE THREAD

**Issue by foreversunyao** [kubernetes/kubernetes#95386]
**What happened**:
In https://v1-16.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#upgrade-additional-control-plane-nodes , it only upgrades binary but missing renew certs like what is done on first control plane node https://v1-16.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#upgrade-the-first-control-plane-node . seems "upgrade apply" has different behaviour with "upgrade node"  ?
```
Note: kubeadm upgrade also automatically renews the certificates that it manages on this node. To opt-out of certificate renewal the flag --certificate-renewal=false can be used. For more information see the certificate management guide.
```

**What you expected to happen**:
there should be a **NOTE** about manually upgrade cert on additional-control-plane-nodes

**How to reproduce it (as minimally and precisely as possible)**:
upgrade cluster from v1.15.4 to v1.16.4
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): kubectl version v1.15.4
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Ubuntu 16.04.6 LTS
- Kernel (e.g. `uname -a`):  4.4.0-122-generic
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by foreversunyao** [comment]
anyone is looking at this case ?
I wonder  **kubeadm upgrade "node"** is supposed to renew the certs if it's control plane nodes, no matter it's first one or additional one

**Comment by neolit123** [comment]
> Kubernetes version (use kubectl version): kubectl version v1.15.4

this version is no longer supported by the k8s team. you should upgrade to 1.17+

> seems "upgrade apply" has different behaviour with "upgrade node" ?

`kubeadm upgrade node` also has `--certificate-renewal`, so i don't see the problem.

> I wonder kubeadm upgrade "node" is supposed to renew the certs if it's control plane nodes, no matter it's first one or additional one

"node" will also renew on CP nodes, as confirmed by:
https://github.com/kubernetes/kubernetes/blob/release-1.17/cmd/kubeadm/app/cmd/upgrade/node.go#L170
and
https://github.com/kubernetes/kubernetes/blob/release-1.17/cmd/kubeadm/app/cmd/phases/upgrade/node/controlplane.go#L77

/remove-sig cli
/sig cluster-lifecycle
/area kubeadm
/remove-kind bug
/kind support

**Comment by neolit123** [comment]
for support questions please use the support channels and #kubeadm on k8s slack:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

thanks
/close

**Comment by foreversunyao** [comment]
@neolit123  thanks for answering this questions
actually I understand what you are saying, but there is only one thing I have doubt  is the doc is for ugprading from v1.15 to v1.16, and it mentioned certficates will be renew automatically(event without --certificate-renewal) , but it did not do it on additional nodes automatically. That's the confusion part for us, no matter v1.15.4 supported or not.

```
Note: kubeadm upgrade also automatically renews the certificates that it manages on this node. To opt-out of certificate renewal the flag --certificate-renewal=false can be used. For more information see the certificate management guide.
```

or can I say this way , document for upgrading from v1.15 to v1.16 should be updated with more clear comments ?

https://v1-16.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#upgrade-additional-control-plane-nodes

**Comment by neolit123** [comment]
the docs for 1.16 are no longer maintained, but you can try sending a PR for the dev-1.16 branch of the kubernetes/website repository.

**Comment by foreversunyao** [comment]
sounds great, will do soon. thanks for helping

**Comment by foreversunyao** [comment]
seems no that branch anymore, is it possible to make it to release-1.16 ?

**Comment by neolit123** [comment]
commented on the PR.
