### ISSUE TITLE
Disk filling up under /var/lib/docker/overlay2 causing the nodes to crash.

### ISSUE THREAD

**Issue by polinchw** [kubernetes/kubernetes#95408]
**What happened**:
I installed Kubernetes 1.19.2 with Kubespray.  The cluster comes up and is functional but in less than 24 hours all of the nodes fill up their /var/lib/docker/overlay2 directories.  The nodes then start crashing when they reach 100% disk space under /var.  I'm aware that this directory is where Docker stores its images.  I did limit the logs files to 100k and keeping one copy per log to rule out the logs causing the program.  I'm not sure if this is a Kubernetes issue or a Docker issue, so I decided to start here.

I'm not installing any deployments or Helm charts.  

**What you expected to happen**:
I expected Kubernetes 1.19.2 to run fine over time and not have any of the nodes crash.

**How to reproduce it (as minimally and precisely as possible)**:
Install Kubernetes 1.19.2 on Ubuntu 20.04 using Kubespray v2.14.1.  The cloud provider is Openstack.

**Anything else we need to know?**:  
This is what the directory disk consumption looks like.  It's currently at 48% but it will eventually grow to 100%

root@node-1:/var/lib/docker# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            2.0G     0  2.0G   0% /dev
tmpfs           394M  1.9M  392M   1% /run
/dev/vda1        39G   19G   21G  48% /
tmpfs           2.0G     0  2.0G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/vda15      105M  3.9M  101M   4% /boot/efi
/dev/loop1       56M   56M     0 100% /snap/core18/1885
/dev/loop0       31M   31M     0 100% /snap/snapd/9279
/dev/loop2       71M   71M     0 100% /snap/lxd/16922
overlay          39G   19G   21G  48% /var/lib/docker/overlay2/cbae5471a00ace7ab491ba1de4778045ec92b980d17c15f5571d14044b279523/merged
overlay          39G   19G   21G  48% /var/lib/docker/overlay2/c5b754a6aeb913694c70e2312130910f6707d6c530bad1d36b760e0e0d18a543/merged
overlay          39G   19G   21G  48% /var/lib/docker/overlay2/fadc349ce9779613d75726b92241b97493a8e45a0d7afb12f9870aa0de5efcea/merged

**Environment**:
- Kubernetes version (use `kubectl version`):  1.19.2
- Cloud provider or hardware configuration: Openstack
- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
- Kernel (e.g. `uname -a`): 
Linux node-1 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: Kubespray v2.14.1
- Network plugin and version (if this is a network-related bug): Calico
- Others:
Docker Version:
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

Docker Info:
Client:
 Debug Mode: false

Server:
 Containers: 17
  Running: 15
  Paused: 0
  Stopped: 2
 Images: 10
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-48-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.844GiB
 Name: node-1
 ID: LIKS:DIES:PLKC:2AUY:XKPW:FVZN:KH2Y:KBAH:QK4D:DFF3:QES2:IZNE
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

**Comment by neolit123** [comment]
hi, the contents of /var/lib/docker/overlay2 are the responsibility of the overlayFS driver for docker.
this is not directly a k8s problem, but our cluster could be setup to contribute negatively to this scenario.

i think the proposed change request belongs to docker, but this comment identifies as a "feature and not a bug":
https://forums.docker.com/t/some-way-to-clean-up-identify-contents-of-var-lib-docker-overlay/30604/21

you could try some of the workarounds in the above thread, or even log a ticket for the overlayFS driver.

/close

**Comment by PBTests** [comment]
I have this exact issue with ContainerD. Rather than fill the thread with pointless nonsense, can anyone point people with this issue in the correct direction?
