### ISSUE TITLE
Flaking kubemark-master-500 job

### ISSUE THREAD

**Issue by tosi3k** [kubernetes/kubernetes#95401]
**Which jobs are flaking**:
`kubemark-master-500`

**Which test(s) are flaking**:
https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-master-500

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-master-500

**Reason for failure**:
All of the failures are due to kubetest timeout kicking in, not due to any clusterloader-related failures. Either we lack resources for the test pod or the kubetest `--timeout` flag value is too low (80m at the moment).

**Anything else we need to know**:
Job definition: [sig-scalability-periodic-jobs.yaml#229](https://github.com/kubernetes/test-infra/blob/57ad925dc9e3ea65695a5f9c840998921438fdb9/config/jobs/kubernetes/sig-scalability/sig-scalability-periodic-jobs.yaml#L229).

/sig scalability
/assign

**Comment by jprzychodzen** [comment]
I've rechecked the values from Metric Explorer - we are not throttled by CPU. 
![cpu-kubemark](https://user-images.githubusercontent.com/29059230/95582137-832bd180-0a3a-11eb-9a2e-4ed98d37d2c9.png)

**Comment by jprzychodzen** [comment]
From logs: for failing run it can take up to 45 minutes form job start to Prometheus check passing. For other jobs, it can take about 25 minutes.

**Comment by jprzychodzen** [comment]
It might be memory throttled, increasing.
![Uploading memory-kubemark.png…]()

**Comment by jprzychodzen** [comment]
Reupload
![memory-kubemark](https://user-images.githubusercontent.com/29059230/95589782-85475d80-0a45-11eb-8d6e-4df42e94171a.png)

**Comment by tosi3k** [comment]
Got fixed by https://github.com/kubernetes/test-infra/pull/19543.
