### ISSUE TITLE
Unable to pull some images from k8s container registry filesystem layer verification failed 

### ISSUE THREAD

**Issue by holynakamoto** [kubernetes/kubernetes#95406]
**Bold** Images won't pull due to filesystem layer verification failed 
_Italics_ pull successful 
_k8s.gcr.io/kube-apiserver:v1.19.2_
**k8s.gcr.io/kube-controller-manager:v1.19.2**
_k8s.gcr.io/kube-scheduler:v1.19.2_
**k8s.gcr.io/kube-proxy:v1.19.2**
_k8s.gcr.io/pause:3.2_
**k8s.gcr.io/etcd:3.4.13-0**
_k8s.gcr.io/coredns:1.7.0_

```
root@kubemaster:~# docker pull k8s.gcr.io/etcd:3.4.13-0
3.4.13-0: Pulling from etcd
4000adbbc3eb: Pull complete
d72167780652: Pull complete
d60490a768b5: Downloading [=========>                                         ]  13.48MB/74.03MB
4a4b5535d134: Download complete
0dac37e8b31a: Verifying Checksum
filesystem layer verification failed for digest sha256:0dac37e8b31a9abb933416b482b0046f50ec329d35cadfcbf8bcc381fa531114
root@kubemaster:~# docker pull k8s.gcr.io/coredns:1.7.0
1.7.0: Pulling from coredns
Digest: sha256:73ca82b4ce829766d4f1f10947c3a338888f876fbed0540dc849c89ff256e90c
Status: Image is up to date for k8s.gcr.io/coredns:1.7.0
k8s.gcr.io/coredns:1.7.0
```
(edit: neolit123 formatted above blob)

I have tried pulling the images with both kubedm and docker

## Versions

kubeadm version: v1.19.2

**Environment**:
- Kubernetes Version: v1.19.2
- Vagrant Version: 2.2.10
- Ubuntu Version: "18.04.5 LTS (Bionic Beaver)
- Kernel Version: 4.15.0-117-generic
- Docker Version: 19.03.11

**Comment by holynakamoto** [comment]
tag https://github.com/kubernetes/kubernetes/labels/sig%2Frelease

**Comment by holynakamoto** [comment]
Virtualbox combined with hyper v breaks sha256 calculations for some reason.

**Comment by bankershours** [comment]
You can close this, it's larger issue with Virtualbox and Hashes, was getting the same on apt-update
