### ISSUE TITLE
tls-cert-file and tls-key-file options is not used by daemons in curl

### ISSUE THREAD

**Issue by nlzv** [kubernetes/kubernetes#95416]
ps -eo pid,args | grep kube-controller-manager
 179356 /opt/kubernetes/v1.19/bin/kube-controller-manager --logtostderr=false --v=9 --master=https://127.0.0.1:6443 --service-account-private-key-file /etc/pki/kubernetes/kubernetes.key.pem --client-ca-file /etc/pki/nz/nzroot.cert.pem --tls-cert-file /etc/pki/kubernetes/kubernetes.cert.pem --tls-private-key-file /etc/pki/kubernetes/kubernetes.key.pem --log-file /var/log/kubernetes/controller-manager.log

excerpt from controller-manager.log

I1009 00:00:54.859942  179356 flags.go:59] FLAG: --client-ca-file="/etc/pki/nz/nzroot.cert.pem"
I1009 00:00:54.860107  179356 flags.go:59] FLAG: --tls-cert-file="/etc/pki/kubernetes/kubernetes.cert.pem"
I1009 00:00:54.860115  179356 flags.go:59] FLAG: --tls-private-key-file="/etc/pki/kubernetes/kubernetes.key.pem"

I1009 00:10:33.173900  179356 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/vnd.kubernetes.protobuf, */*" -H "User-Agent: kube-controller-manager/v1.19.0 (linux/amd64) kubernetes/e199641/leader-election" 'https://127.0.0.1:6443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s'
I1009 00:10:33.186241  179356 round_trippers.go:443] GET https://127.0.0.1:6443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s  in 12 milliseconds
I1009 00:10:33.186267  179356 round_trippers.go:449] Response Headers:
E1009 00:10:33.186505  179356 leaderelection.go:321] error retrieving resource lock kube-system/kube-controller-manager: Get "https://127.0.0.1:6443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s": x509: certificate signed by unknown authority

curl doesn't use tls cert key option of daemon.
take curl 'command' from log and  add appropriate tls options then https request and certificate check is ok.
example run in shell
curl -k -v -XGET  -H "Accept: application/vnd.kubernetes.protobuf, */*" -H "User-Agent: kube-controller-manager/v1.19.0 (linux/amd64) kubernetes/e199641/leader-election" 'https://127.0.0.1:6443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s' --conf /etc/kubernetes/curl_tls.conf
cat /etc/kubernetes/curl_tls.conf
cert = /etc/pki/kubernetes/kubernetes.cert.pem 
key = /etc/pki/kubernetes/kubernetes.key.pem 
cacert = /etc/pki/nz/nzroot.cert.pem

It seems all daemons ( beside apiserver) suffer not using tls-cert-file and tls-key-file options for curl ?lib call?

**Comment by liggitt** [comment]
The example curl output is generated at the request layer, which does not know about the connection level options like cert/key file. The output shown does not represent an actual call to a curl library, the golang http client is used to make all calls

**Comment by nlzv** [comment]
If I use --kubeconfig file where one is pointed kubelet cert and key and root cert then there is no 401 error.
kubelet --kubeconfig kubelet.kubeconfig <other options not related to api server connectivity>

generate_kubelet_kubeconfig.sh

kubeconfig='kubelet.kubeconfig'
apiserverip='...'
apiserveriport='...'
host='...'
server="https://$apiserverip:$apiserverport"
cluster="..."
tlscert=/etc/pki/k8s/kubelet.cert.pem
tlskey=/etc/pki/k8s/kubelet.key.pem
tlsca="/etc/pki/k8s/kubelet.cert.pem"

kubectl config set-cluster $cluster \
  --certificate-authority=$ltsca \
  --embed-certs=true \
  --server=$server \
  --kubeconfig=$kubeconfig

kubectl config set-credentials system:node:$host \
  --client-certificate=$tlscert \
  --client-key=$tlskey \
  --embed-certs=true \
  --kubeconfig=$kubeconfig

kubectl config set-context default \
  --cluster=$cluster \
  --user=system:node:$host \
  --kubeconfig=$kubeconfig

kubectl config use-context default --kubeconfig=$kubeconfig

I wonder why I can not set kubelet cert key and ca cert pure in command options of kubelet.
it seems that kubeconfig is a litle bit more than information of files cubelet cer and key file and ca cert file
