### ISSUE TITLE
Issue using metrics fakeclient to test simple API

### ISSUE THREAD

**Issue by monchier** [kubernetes/kubernetes#95421]
**What happened**:
I am running the following unit test against to test the `metrics` API. The test fails with:
```
"pods.metrics.k8s.io \"some pod\" not found",
```

```
import (
	"github.com/stretchr/testify/assert"
	apiv1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/metrics/pkg/apis/metrics/v1beta1"
	mfake "k8s.io/metrics/pkg/client/clientset/versioned/fake"
	"testing"
	"time"
)

func Test_MetricsWatcher(t *testing.T) {
	objects := []runtime.Object{&v1beta1.PodMetrics{
		ObjectMeta: metav1.ObjectMeta{
			Name: "some pod",
			Namespace: metav1.NamespaceDefault,
		},
		Timestamp:metav1.Time{Time: time.Now()},
		Window:metav1.Duration{Duration:time.Second},
		Containers: []v1beta1.ContainerMetrics{
			{
				Usage: map[apiv1.ResourceName]resource.Quantity{
					apiv1.ResourceCPU:    *resource.NewMilliQuantity(1, resource.DecimalSI),
					apiv1.ResourceMemory: *resource.NewQuantity(100, resource.DecimalSI),
				},
			},
		},
	}}
	metricsClient := mfake.NewSimpleClientset(objects...)
	_, err := metricsClient.MetricsV1beta1().PodMetricses(apiv1.NamespaceDefault).Get("some pod", metav1.GetOptions{})
	assert.Nil(t, err)
}
```

I see [here](https://github.com/kubernetes/metrics/blob/master/pkg/client/clientset/versioned/typed/metrics/v1beta1/fake/fake_podmetrics.go#L38) resource is `pods`, while I would expect this to be `podmetrics`.

**What you expected to happen**: test succeeds.

**How to reproduce it (as minimally and precisely as possible)**: Run the above test

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.13
- Cloud provider or hardware configuration: local
- OS (e.g: `cat /etc/os-release`): MacOS 
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by monchier** [comment]
Adding some color to this to help clarify:
What made me think this is a bug is this line: https://github.com/kubernetes/metrics/blob/master/pkg/client/clientset/versioned/typed/metrics/v1beta1/fake/fake_podmetrics.go#L38
```
var podmetricsesResource = schema.GroupVersionResource{Group: "metrics.k8s.io", Version: "v1beta1", Resource: "pods"}
```

and if I debug the tracker, it turns out that everything would be fine if Resource were `podmetrics`.

Since this is automatically generated, the fix could be actually here: https://github.com/kubernetes/metrics/blob/master/pkg/apis/metrics/types.go#L58
```
// +resourceName=pods
```

**Comment by zhouya0** [comment]
The problem is:
https://github.com/kubernetes/kubernetes/blob/fa15799f7409b8644221c2b43a494c74aac0c5ee/staging/src/k8s.io/client-go/testing/fixture.go#L324-L334

For others resources, `resource` is just the plural form for `kind`. But not for `podMetrics` and `nodeMetrics`.

**Comment by monchier** [comment]
Thank you for the quick PR! @zhouya0
