### ISSUE TITLE
Kubectl delete/patch/edit behavior in kubectl proxy mode

### ISSUE THREAD

**Issue by hasan4791** [kubernetes/kubernetes#95434]
**What happened**:
I'm trying to access the kubernetes api server through the apiserver proxy which is running in "--disable-filter=true" mode. When using kubectl delete/patch/edit commands, following error is being thrown

[chasan@chasan-linux]$ kubectl delete po redis-server-5 -n $n
Error from server (MethodNotAllowed): the server does not allow this method on the requested resource (delete pods redis-server-5)

[chasan@chasan-linux]$ kubectl edit sts redis-server-6 -n $n
error: statefulsets.apps "epc-redis-server-6" could not be patched: the server does not allow this method on the requested resource (patch statefulsets.apps redis-server-6)
You can run `kubectl replace -f /tmp/kubectl-edit-szey8.yaml` to try this update again.

**What you expected to happen**:
Since the filter is disabled, ideally it should allow all these commands to run as usual

**Environment**:
- Kubernetes version (use `kubectl version`):
[chasan@chasan-linux]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2020-09-11T19:11:19Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: Internal
- OS (e.g: `cat /etc/os-release`): Oracle Linux 7.x

**Comment by eddiezane** [comment]
@hasan4791 could please provide the output of `-v=6` and the set of commands you're using to reproduce?

/triage needs-information

**Comment by hasan4791** [comment]
@eddiezane  Logs are attached here.

[kubectl_delete.log](https://github.com/kubernetes/kubernetes/files/5402730/kubectl_delete.log)
[kubectl_edit.log](https://github.com/kubernetes/kubernetes/files/5402731/kubectl_edit.log)

**Comment by eddiezane** [comment]
I think your API server is restricting the methods - most likely from your auth/rbac. Double check the permissions and role.

`kubectl proxy` does not return those errors.

```
 /tmp/95434 kubectl proxy -v 6
I0217 16:18:39.129249   59882 loader.go:379] Config loaded from file:  /Users/ezaneski/.kube/config
Starting to serve on 127.0.0.1:8001
I0217 16:18:54.594636   59882 proxy_server.go:88]  matched ^.*
I0217 16:18:54.594728   59882 proxy_server.go:132] Filter rejecting GET  test.localhost
```

```
 /tmp/95434 curl test.localhost:8001 -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to test.localhost (127.0.0.1) port 8001 (#0)
> GET / HTTP/1.1
> Host: test.localhost:8001
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Wed, 17 Feb 2021 23:20:59 GMT
< Content-Length: 10
<
Forbidden
* Connection #0 to host test.localhost left intact
* Closing connection 0
```
https://github.com/kubernetes/kubernetes/blob/b2860a360441d15a2f1a7b63e9ca247e5b0ec784/staging/src/k8s.io/kubectl/pkg/proxy/proxy_server.go#L37-L46

https://github.com/kubernetes/kubernetes/blob/b2860a360441d15a2f1a7b63e9ca247e5b0ec784/staging/src/k8s.io/kubectl/pkg/proxy/proxy_server.go#L125-L134

/close
