### ISSUE TITLE
Kubectl patch not idempotent when setting nodeSelector label value to null

### ISSUE THREAD

**Issue by sbocinec** [kubernetes/kubernetes#95440]
**What happened**:
Patching (`kubectl patch`) a deployment with a `nodeSelector` label value set to `null` is not idempotent (when using default `strategic` merge patch):
* when a `nodeSelector` constraint exists with a `key:value` label set for the deployment, setting the `nodeSelector` label value to `null` by patching the deployment removes the `nodeSelector` constraint
* when a `nodeSelector` constraint does not exist, setting the `nodeSelector` label value to `null` by using the same patch command results in the `nodeSelector` constraint being set with the label value set to `""` (empty string)
* when the same patch command is ran again, it removes the `nodeSelector` constraint
* when the same patch command is ran again, it creates the `nodeSelector` constraint with the label value set to `""` (empty string)
* and so on

**What you expected to happen**:
Setting a `nodeSelector` label value to `null` by patching the deployment should be idempotent and mutliple execution of the same command should results in the same deployment resource state, either:
* remove the constraint/keep it removed or 
* set the constraint to an empty string/keep the empty string set

**How to reproduce it (as minimally and precisely as possible)**:
```
# Create a sample deployment
$ kubectl create deployment nginx --image nginx
deployment.apps/nginx created

# Check the nodeSelector is not set:
$ kubectl get deploy nginx -o json |jq '.spec.template.spec.nodeSelector'
null 

# Set nodeSelector constraint by patching the deployment:
$ kubectl patch deployment nginx -p '{ "spec": { "template": { "spec": { "nodeSelector": { "cloud.google.com/gke-nodepool": "test" } } } } }'
deployment.apps/nginx patched

# Check the nodeSelector is properly set
$ kubectl get deploy nginx -o json |jq '.spec.template.spec.nodeSelector'                                                                    
{
  "cloud.google.com/gke-nodepool": "test"
}

# Unset/remove the nodeSelector by patching the label value to `null`:
$ kubectl patch deployment nginx -p '{ "spec": { "template": { "spec": { "nodeSelector": { "cloud.google.com/gke-nodepool": null } } } } }'
deployment.apps/nginx patched

# Verify nodeSelector is removed:
$ kubectl get deploy nginx -o json |jq '.spec.template.spec.nodeSelector'                                                                  
null

# Run the same patch command again:
$ kubectl patch deployment nginx -p '{ "spec": { "template": { "spec": { "nodeSelector": { "cloud.google.com/gke-nodepool": null } } } } }'
deployment.apps/nginx patched

# Surprisingly, nodeSelector field is created, but with the label value set to an empty string: 
$ kubectl get deploy nginx -o json |jq '.spec.template.spec.nodeSelector'                                                                  
{
  "cloud.google.com/gke-nodepool": ""
}

# Run the same patch command again setting the label value to `null`:
$ kubectl patch deployment nginx -p '{ "spec": { "template": { "spec": { "nodeSelector": { "cloud.google.com/gke-nodepool": null } } } } }'
deployment.apps/nginx patched

# nodeSelector field is removed
$ kubectl get deploy nginx -o json |jq '.spec.template.spec.nodeSelector'                                                                  
null
```

**Anything else we need to know?**:
* Using the [`JSON merge` patch type](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/#use-a-json-merge-patch-to-update-a-deployment) (`--type merge`) instead of the default `strategic` patch works as expected (executing the patch command is idempotent):
```
$ kubectl patch deployment nginx -p '{ "spec": { "template": { "spec": { "nodeSelector": { "cloud.google.com/gke-nodepool": null } } } } }' --type merge
deployment.apps/nginx patched (no change)
$ kubectl get deploy nginx -o json |jq '.spec.template.spec.nodeSelector'                                                                               
null
$ kubectl patch deployment nginx -p '{ "spec": { "template": { "spec": { "nodeSelector": { "cloud.google.com/gke-nodepool": null } } } } }' --type merge
deployment.apps/nginx patched (no change)
$ kubectl get deploy nginx -o json |jq '.spec.template.spec.nodeSelector'                                                                               
null
$ kubectl patch deployment nginx -p '{ "spec": { "template": { "spec": { "nodeSelector": { "cloud.google.com/gke-nodepool": "test" } } } } }' --type merge
deployment.apps/nginx patched
$ kubectl get deploy nginx -o json |jq '.spec.template.spec.nodeSelector'                                                                                 
{
  "cloud.google.com/gke-nodepool": "test"
}
$ kubectl patch deployment nginx -p '{ "spec": { "template": { "spec": { "nodeSelector": { "cloud.google.com/gke-nodepool": null } } } } }' --type merge  
deployment.apps/nginx patched
$ kubectl get deploy nginx -o json |jq '.spec.template.spec.nodeSelector'                                                                                 
null
$ kubectl get deploy nginx -o json |jq '.spec.template.spec.nodeSelector'
null
``` 
* I'm not sure, whether this is a bug or it is how it's expected to work, though, it looks suspicious, I would expect the `kubectl patch` behaves in an idempotent way even for default `strategic` merge patch operations.

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-dispatcher", GitCommit:"fd22db44e150011eccc8729db223945384460143", GitTreeState:"clean", BuildDate:"2020-07-24T07:27:52Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.401", GitCommit:"eb94c181eea5290e9da1238db02cfef263542f5f", GitTreeState:"clean", BuildDate:"2020-09-09T00:57:35Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```
Tested also with minikube with Kubernetes `v1.19.2` installed

- Cloud provider or hardware configuration: GKE/minikube
- OS (e.g: `cat /etc/os-release`): `Ubuntu 20.04.1 LTS`
- Kernel (e.g. `uname -a`): `Linux s 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux` 
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ZongqiangZhang** [comment]
how's the issue going on now. I cannot find a patchUpdate method to remove a nodeSelector filter from deployment.

**Comment by sbocinec** [comment]
@ZongqiangZhang have you tried setting the nodeSelector label value to `null` as I mentioned in the issue description? 

`kubectl patch deployment nginx -p '{ "spec": { "template": { "spec": { "nodeSelector": { "cloud.google.com/gke-nodepool": null } } } } }'`

**Comment by ZongqiangZhang** [comment]
@sbocinec  Thanks for your tips. I tried to `kubectl apply dp.yaml` with nodeSelector value=`null`, but got  error message as follows.  Is my k8s version toooo old?

``` Bash
$ kubectl apply -f dp.yaml
error: error validating "dp.yaml": error validating data: unknown object type "nil" in Deployment.spec.template.spec.nodeSelector.my_label
```

``` Bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.10-80+2bb7bffbbf159b", GitCommit:"2bb7bffbbf159b941557475fadf1294cb1211f31", GitTreeState:"clean", BuildDate:"2021-05-23T06:51:59Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
