### ISSUE TITLE
scheduler in-tree plugin names should be fully qualified

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#95445]
**What would you like to be added**:
in-tree plugin names should be fully qualified, something like `scheduler.kubernetes.io/${pluginname}`.

**Why is this needed**:
Makes it easier to distinguish between in-tree and out-of-tree plugins.

Now is the best time to do this since we are introducing v1beta2 api. For v1beta1, we will accept both names `scheduler.kubernetes.io/${pluginname}` and `${pluginname}`.

/sig scheduling
/cc @alculquicondor @Huang-Wei @damemi wdyt?

**Comment by alculquicondor** [comment]
It will be a bit painful to fix all unit tests, but yeah, it should make things more clear.

**Comment by damemi** [comment]
Good idea, it could also set a precedent for *all* developers to name their plugins with fully-qualified names (as plugins grow, it could be possible to import plugins from multiple 3rd parties)

**Comment by Huang-Wei** [comment]
SGTM.

One question, should we use the GroupName defined in scheduler CC? i.e., `kubescheduler.config.k8s.io`:

https://github.com/kubernetes/kubernetes/blob/ee297b6f4d78daaf2f71c78a05203698581ca40a/staging/src/k8s.io/kube-scheduler/config/v1beta1/register.go#L25

Or, we just use another group name to indicate it's "in-tree", such as `scheduling.k8s.io`; so that we use a different group, like in scheduler-plugins to be `scheduling.sigs.k8s.io`.

**Comment by ahg-g** [comment]
`kubescheduler.config.k8s.io` make sense to me.

**Comment by alculquicondor** [comment]
I think the plugin names are somewhat independent of the component config. I would prefer `scheduling.k8s.io` or the originally proposed `scheduler.k8s.io`.

**Comment by alculquicondor** [comment]
Recall that other binaries can use the framework directly without component config.

**Comment by Huang-Wei** [comment]
Scheduler-plugins adheres to scheduler CC to defined its versioned plugin args, and hence derives the API group/version: `kubescheduler.config.k8s.io/v1beta1` ([link](https://github.com/kubernetes-sigs/scheduler-plugins/blob/939c1c03521ce2117a7c370f7f730d81c3331590/pkg/apis/config/register.go#L26)).

But the qualified plugin name is slightly a different thing:

- if we want to (implicitly) **enforce** the qualified plugin name to be consistent with **CC API group name**, we should use `kubescheduler.config.k8s.io` as the prefix of qualified plugin name, in in-tree plugins as well as any out-of-tree plugin that leverages scheduler CC.
- if not (which makes more sense to me), I'm +1 to use `scheduling.k8s.io` in in-tree plugins and scheduler-plugins can use `scheduling.sigs.k8s.io` - this leaves flexibility and less likely to cause conflicts in naming.

**Comment by alculquicondor** [comment]
> Scheduler-plugins adheres to scheduler CC to defined its versioned plugin args, and hence derives the API group/version: `kubescheduler.config.k8s.io/v1beta1`

I'm thinking that scheduling-plugins should have it's own groupName. The downside is that all the users of custom plugins need to write the groupname and Kind of the corresponding PluginConfigs, and we might need other generalizations in [decoding](https://github.com/kubernetes/kubernetes/blob/b0ca7f1ea56dea9eccfb053c9837fe83f4bc5804/staging/src/k8s.io/kube-scheduler/config/v1beta1/types.go#L225) and [conversion](https://github.com/kubernetes/kubernetes/blob/b0ca7f1ea56dea9eccfb053c9837fe83f4bc5804/pkg/scheduler/apis/config/v1beta1/conversion.go#L59). But that's a separate topic.

**Comment by ahg-g** [comment]
> I'm thinking that scheduling-plugins should have it's own groupName. The downside is that all the users of custom plugins need to write the groupname and Kind of the corresponding PluginConfigs, and we might need other generalizations in decoding and conversion. But that's a separate topic.

we could enforce that all plugin names should use a subdomain of `plugin.kubescheduler.k8s.io` (i.e., the name should be `${something}.plugin.kubescheduler.k8s.io/${pluginName}`), and verify that plugins with the subdomain `intree.plugin.kubescheduler.k8s.io` exist in the in-tree registry (I am suggesting `kubescheduler` instead of scheduler or scheduling to be consistent with the `kubescheduler.config.k8s.io` subdomain used for CC).

**Comment by alculquicondor** [comment]
I would just leave the "intree" ones as `plugin.kubescheduler.k8s.io`. We shouldn't enforce external ones to a particular subdomain. In fact, if they want to do `plugin.scheduler.example.com`, that would be even better.

+1 to the rest of the comment

**Comment by damemi** [comment]
> I would just leave the "intree" ones as `plugin.kubescheduler.k8s.io`. We shouldn't enforce external ones to a particular subdomain. In fact, if they want to do `plugin.scheduler.example.com`, that would be even better.
> 
> +1 to the rest of the comment

+1 to this, that's exactly what I had in mind with my earlier comment (that 3rd party developers can use their own `example.com` domain)

**Comment by ahg-g** [comment]
ok, so we are circling back to the suggestion in the initial suggestion, and use the domain `plugin.kubescheduler.k8s.io/${pluginName}`. sgtm

**Comment by Huang-Wei** [comment]
`plugin.kubescheduler.k8s.io/${pluginName}` sounds good to me.

**Comment by alculquicondor** [comment]
@pancernik I think this is a good fit for you. Are you interested?

**Comment by obeyda** [comment]
Hello, I would like to help on this but I'am new to contributing to kubernetes so I'll need some guidance on how to proceed.

**Comment by alculquicondor** [comment]
I'm not sure if this issue is a good fit for a new contributor.

**Comment by obeyda** [comment]
Thanks for pointing that out @alculquicondor, I'll try to find another issue to work on.

**Comment by alculquicondor** [comment]
We don't have a contributor to work on this and code freeze is approaching.

Should we hold on a release of v1beta2 until 1.21?

**Comment by ahg-g** [comment]
sg, lets postpone v1beta2 to 1.21

**Comment by alculquicondor** [comment]
@gavinfish you can only work on this once we have a v1beta2 version of the API #95308

Users of v1beta1 should not be affected. i.e., they shouldn't need to do any changes.

**Comment by gavinfish** [comment]
@alculquicondor according to @ahg-g's proposal, it seems that we may be able to accept both origin in-tree plugin names and qualified ones for v1beta1?

> Why is this needed:
Makes it easier to distinguish between in-tree and out-of-tree plugins.

>Now is the best time to do this since we are introducing v1beta2 api. For v1beta1, we will accept both names scheduler.kubernetes.io/${pluginname} and ${pluginname}.

**Comment by alculquicondor** [comment]
If you make it work, I'm not against it. But it might be easier to just do it for v1beta2, which is fine.

**Comment by alculquicondor** [comment]
Freeze is over,
@gavinfish any chance you can get a PR ready before #95308 is merged?

**Comment by alculquicondor** [comment]
I'm thinking we should be using the prefix `kubescheduler.config.k8s.io` so that we know which scheme to load to do plugin conversions.

@Huang-Wei WDYT?

**Comment by Huang-Wei** [comment]
@alculquicondor SGTM - it was actually what I originally suggested https://github.com/kubernetes/kubernetes/issues/95445#issuecomment-706249438.

One question: if we place the logic to do conversion upon this prefix, I think the scheduler-plugins should be also using this prefix? As currently the plugins in that repo is following the XYZArgs naming pattern and also [reusing](https://github.com/kubernetes-sigs/scheduler-plugins/blob/1857f2d940e2e4383821ad070bb032b4983a7df0/pkg/apis/config/v1beta1/register.go#L22) the in-tree scheme's functionalities.

**Comment by alculquicondor** [comment]
I think they should define their own prefix, also to serve as an example for other projects to set their prefixes.

Maybe we can export a scheme registration function in pkg/scheduler/apis/config/v1beta2

**Comment by alculquicondor** [comment]
I would vote to abandon this idea.

**Comment by ahg-g** [comment]
I would insist on doing this if we are starting from scratch, bit may be now is too late.
