### ISSUE TITLE
kubectl --dry-run=server with Read Only Permissions

### ISSUE THREAD

**Issue by divy4** [kubernetes/kubernetes#95449]
**What would you like to be added**:

The ability to run `kubectl <command> --dry-run=server` with a user or service account that only has read permissions (i.e. the GET/HEAD verbs listed in https://kubernetes.io/docs/reference/access-authn-authz/authorization/#determine-the-request-verb).

**Why is this needed**:

This would be helpful for setting up a "dry run user/service account" that doesn't have as many access restrictions in CI/CD tools.

For example, you could setup 2 service accounts, called `deploy-sa` and `dry-run-sa`, where `dry-run-sa` executes a dry run deployment when a pull request is made to check if the deployment would be successful and `deploy-sa` executes the deployment after the pull request is merged (i.e. least privilege access). Then if `dry-run-sa` was compromised or some change was introduced that caused the `--dry-run` flag to be ignored (I've personally seen this happen with the Azure DevOps [Kubectl task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes?view=azure-devops)) , no cluster resources would be at risk.

**Comment by troy0820** [comment]
Hey @divy4 could you do: 
`kubectl create -f <something.yaml> --as=system:serviceaccount:namespace:dry-run-sa --dry-run` 
Doing this will validate the yaml but it will not create it and the service account that you are using to check it will have the reader permissions that you requested.

**Comment by divy4** [comment]
Hey @troy0820, sadly no. I'm interested in the `server` mode of dry run to check if there are any incompatibilities between the resource definitions and preexisting resources on the cluster.

For example, create a Service by running `kubectl create -f file.yml` on this file (which was copied from the [docs](https://kubernetes.io/docs/concepts/services-networking/service/)):

```
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
```

If you then edit add `nodePort: 30007` to the end of the file, `kubectl apply --dry-run=client -f file.yml` completes successfully while `kubectl apply --dry-run=server` will fail, outputting the same error as `kubectl apply -f file.yml`:

```
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
The Service "my-service" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
```

This is one example of where `--dry-run=client` isn't quite enough for what I want to test. And I see this exact situation happen on a semi-frequent basis where several people have cli access to a single cluster, since it's hard to expect everyone to remember to always use `apply` or `create --save-config` when debugging applications.

**Comment by troy0820** [comment]
@divy4 The feature you are requesting is dependent on a permissions model that will allow dry-run on service accounts to impersonate the creation of Kubernetes objects bypassing what the role was designed to do.

**Comment by divy4** [comment]
@troy0820 Sure, this is definitely going outside the current role definitions, which is why I made this thread. Do we want to extend the permissions of the read only verbs to include dry runs? In terms of actions being made to the cluster, a dry run doesn't actually create/delete/patch anything, as far as I'm aware. But I also acknowledge that this would make the output of `--dry-run=server` vs `--dry-run=none` different for these types of accounts. So there's definitely some tradeoffs here.

And that's why I brought this up. What are your thoughts? Are there different models that could be designed to fit the same goal (e.g. each verb involving writes has a `*_dry_run` equivalent)? I think this could be very helpful for designing least-privilege access to a cluster, however it's implemented.

**Comment by troy0820** [comment]
@divy4 I'm not in sig/auth but I can only make an assumption that changing how the authorization works for dry-run would impact other k8s objects because the authorization is identical for dry-run and non-dry-runs. _(https://kubernetes.io/docs/reference/using-api/api-concepts/#dry-run-authorization)_ 

/sig auth

**Comment by apelisse** [comment]
This has been discussed before (e.g. https://github.com/kubernetes/enhancements/pull/893). I agree that it'd be nice.

**Comment by apelisse** [comment]
@liggiitt, still no chance of seeing that happening one way or another?

**Comment by tonybenchsci** [comment]
Relates to https://github.com/kubernetes/kubectl/issues/981 and would be useful
