### ISSUE TITLE
Reorder default Filter plugins to have UnschedulableAndUnresolvable first

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#95442]
Inspired from https://github.com/kubernetes/kubernetes/pull/92866/files#r496160188

Our default Filter plugins have the following order:

https://github.com/kubernetes/kubernetes/blob/ee297b6f4d78daaf2f71c78a05203698581ca40a/pkg/scheduler/algorithmprovider/registry.go#L87-L104

IIUC, this order was chosen to have the fastest Filters or the most probability of reporting Unschedulable first. Arguably, some are pretty much equivalent and could be reordered.

The major problem with this order is that `NodeResourcesFit` plugin is almost at the beginning. This plugin only reports `Unschedulable`. A Node that fails this plugin will be evaluated during preemption. But perhaps this Node doesn't satisfy other UnschedulabeAndUnresolvable requirements (taints, node selectors, nodeaffinity).

Theoretically, having those Filters run first could improve preemption latency.

The only open question is whether or not the ordering we have today is an API guarantee. I believe it's not (at least in component config), because the only way to change the ordering of Plugins is disabling all of them first.

Decided order:

```
 		{Name: nodeunschedulable.Name}, 
 		{Name: nodename.Name}, 
 		{Name: tainttoleration.Name}, 
 		{Name: nodeaffinity.Name}, 
 		{Name: nodeports.Name}, 
 		{Name: noderesources.FitName}, 
 		{Name: volumerestrictions.Name}, 
 		{Name: nodevolumelimits.EBSName}, 
 		{Name: nodevolumelimits.GCEPDName}, 
 		{Name: nodevolumelimits.CSIName}, 
 		{Name: nodevolumelimits.AzureDiskName}, 
 		{Name: volumebinding.Name}, 
 		{Name: volumezone.Name}, 
 		{Name: podtopologyspread.Name}, 
 		{Name: interpodaffinity.Name},
```

/sig scheduling

**Comment by alculquicondor** [comment]
@ahg-g @Huang-Wei for comment

**Comment by alculquicondor** [comment]
and @cofyc :)

**Comment by soulxu** [comment]
RunFilterPlugins still returns early for `Unschedulable`, even with changing plugin order.

https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/runtime/framework.go#L502

So should we change to run the filter plugins until there is `UnschedulableAndUnresolvable`?

**Comment by alculquicondor** [comment]
> Even we changed the order of plugins, the framework.RunFilterPlugins still exits early when Unschedulable returned by plugin.

That is correct, and that's what it should be.

**Comment by alculquicondor** [comment]
> So should we change the current behavior to run the filter plugins until there is one plugin returned UnschedulableAndUnresolvable?

No, that's the original conversation suggested and it's likely not ideal in the average case.

**Comment by Huang-Wei** [comment]
+1.

_Lightweight_ plugins that may return `UnschedulabeAndUnresolvable` status can be moved ahead of other plugins that only return `Unschedulable` status.

**Comment by Huang-Wei** [comment]
FYI: from @alena1108 who also had this concern: https://kubernetes.slack.com/archives/C09TP78DV/p1589394566175200

So how about `nodeaffinity`, is it also a good candidate to be moved ahead of `noderesources`? NodeAffinity and NodeSelector both incorporated in `nodeaffinity`, I'm pretty sure NodeSelector logic is simply, but not 100% sure NodeAffinity logic falls into the category of "lightweight".

**Comment by alculquicondor** [comment]
Let me propose an order, for extra clarity:

```
 		{Name: nodeunschedulable.Name}, 
 		{Name: nodename.Name}, 
 		{Name: nodeaffinity.Name}, 
 		{Name: tainttoleration.Name}, 
 		{Name: noderesources.FitName}, 
 		{Name: nodeports.Name}, 
 		{Name: volumerestrictions.Name}, 
 		{Name: nodevolumelimits.EBSName}, 
 		{Name: nodevolumelimits.GCEPDName}, 
 		{Name: nodevolumelimits.CSIName}, 
 		{Name: nodevolumelimits.AzureDiskName}, 
 		{Name: volumebinding.Name}, 
 		{Name: volumezone.Name}, 
 		{Name: podtopologyspread.Name}, 
 		{Name: interpodaffinity.Name}, 
```

**Comment by Huang-Wei** [comment]
`nodeaffinity` internally composes [LabelSelector](https://github.com/kubernetes/kubernetes/blob/6268e6f990522289a6a2c25db5d9cacc0988171b/pkg/scheduler/framework/plugins/helper/node_affinity.go#L31) and invokes `Matches`, which IMO is a bit more expensive than `tainttoleration`.

`nodeports` should be cheaper than `noderesources`.

So my 2 cents is:

```
 		{Name: nodeunschedulable.Name}, 
 		{Name: nodename.Name}, 
 		{Name: tainttoleration.Name}, 
 		{Name: nodeaffinity.Name}, 
 		{Name: nodeports.Name}, 
 		{Name: noderesources.FitName}, 
 		{Name: volumerestrictions.Name}, 
 		{Name: nodevolumelimits.EBSName}, 
 		{Name: nodevolumelimits.GCEPDName}, 
 		{Name: nodevolumelimits.CSIName}, 
 		{Name: nodevolumelimits.AzureDiskName}, 
 		{Name: volumebinding.Name}, 
 		{Name: volumezone.Name}, 
 		{Name: podtopologyspread.Name}, 
 		{Name: interpodaffinity.Name},
```

**Comment by ahg-g** [comment]
Both proposals are fine by me.

**Comment by soulxu** [comment]
I want to help here :)
