### ISSUE TITLE
kubectl plugins doesnt work

### ISSUE THREAD

**Issue by korkin25** [kubernetes/kubernetes#95466]
**What happened**: I need to use kubectl plugins. I have installed a few plugins, but on any attempts to use plugin I see error messages.  for example:
kubectl minio:

Error: unknown command "minio" for "kubectl"
Run 'kubectl --help' for usage.

I have tried to investigate the problem using strace command, but the interesting fact - with strace command kubectl plugins works well:)

![image](https://user-images.githubusercontent.com/28926495/95650814-afa12580-0aee-11eb-99f5-19de399f1507.png)

the point - the problem doesnt depend on plugin.

**What you expected to happen**:
I have expected to use plugins:)

**How to reproduce it (as minimally and precisely as possible)**:
Just install any plugin and try to use.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

kubectl is installed to my ubuntu from "deb https://apt.kubernetes.io/ kubernetes-xenial main"

- Cloud provider or hardware configuration:
this is vmware vm.

- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- Kernel (e.g. `uname -a`):
Linux kk573-hp 5.4.0-48-generic #52~18.04.1-Ubuntu SMP Thu Sep 10 12:50:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
apt
- Network plugin and version (if this is a network-related bug):
https://github.com/minio/operator/releases/tag/v3.0.27
But it doesnt depend on plugin. cert-manager "works" by the same way.

- Others:
thank you for help.

**Comment by neolit123** [comment]
testing here:
https://www.katacoda.com/courses/kubernetes/playground
downloading the latest `kubectl-minio` plugin and adding it to `$PATH` then running `kubectl minio init` works fine.

```
controlplane $ kubectl minio init
CustomResourceDefinition tenants.minio.min.io: created
ClusterRole minio-operator-role: created
ServiceAccount minio-operator: created
ClusterRoleBinding minio-operator-binding: created
MinIO Operator Deployment minio-operator: created
```

/priority awaiting-more-evidence
/sig cli

**Comment by neolit123** [comment]
please provide detailed step-by-step guide on how you are installing the plugins.

**Comment by korkin25** [comment]
Just using https://www.katacoda.com/courses/kubernetes/playground:

1. Installing krew

(
  set -x; cd "$(mktemp -d)" &&
  curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/krew.tar.gz" &&
  tar zxvf krew.tar.gz &&
  KREW=./krew-"$(uname | tr '[:upper:]' '[:lower:]')_$(uname -m | sed -e 's/x86_64/amd64/' -e 's/arm.*$/arm/')" &&
  "$KREW" install krew
)

2. 

![image](https://user-images.githubusercontent.com/28926495/95695349-2b11ec80-0c3f-11eb-90f2-a1dd3b16d777.png)

I cant reproduce minio install at playground cause of I dont see krew working.

May be I do something wrong, but I do that according krew documentation (copy then paste script for krew install)

I can give more info from my host.

**Comment by neolit123** [comment]
the way i installed the plugin was just downloading it from without krew:
https://github.com/minio/operator/releases

i think it's better to start at the support channels first and if you confirm this is as bug in kubectl then this ticket can be re-opened:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

thanks
/close
