### ISSUE TITLE
kubeadm join hangs at preflight 

### ISSUE THREAD

**Issue by harshsingh1002** [kubernetes/kubernetes#95477]
I was provisioning a kubeadm cluster and performed following steps
1.  Installed all the dependencies like kubelet , kubeadm , kubectl , docker ( used official document )
2. kubeadm init --pod-network-cidr=192.168.0.0/16 --apiserver-advertise-address={{master-ip-address}}.
3. created the .kube/cofing file with the help of kubeadm output
4. Dowloaded calico.yaml curl https://docs.projectcalico.org/manifests/calico.yaml -O
5. kubectl apply -f calico.yaml 
6. copied the join command to run on worker nodes 
7. kubeadm join stuck on preflight and after some time i get the following error
     kubeadm join 172.16.6.4:6443 --token 3dwl8j.xquc9fiyk8lbbkb0 \
>     --discovery-token-ca-cert-hash sha256:757cede0cfad6432ebc2ea067be2e91c4f69f59083b812f90fc24dd3a874f77f
[preflight] Running pre-flight checks
error execution phase preflight: couldn't validate the identity of the API Server: Get "https://{master-IP}:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
To see the stack trace of this error execute with --v=5 or higher

NOTE: i have provisioned kubeadm clusters many times but never faced this issue .
 

**Environment**:
- Kubernetes version (use `kubectl version`):  Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2"
- Cloud provider or hardware configuration: Azure VM ( same error with GCP VMs also )
- OS (e.g: `cat /etc/os-release`): VERSION="18.04.5 LTS (Bionic Beaver)"
- Kernel (e.g. `uname -a`): Linux master 5.4.0-1026-azure #26~18.04.1-Ubuntu SMP Thu Sep 10 16:19:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Install tools: kubeadm,kubectl,kubelet,docker
- Network plugin and version (if this is a network-related bug): Calico 
- Others:

**Comment by harshsingh1002** [comment]
![2020-10-11 20_38_32-Window](https://user-images.githubusercontent.com/48350442/95682263-f92e6500-0c01-11eb-9004-be21d63e6ca9.png)

**Comment by wawa0210** [comment]
From the log, it appears that the apiserver of 172.16.6.4 does not work normally

**Comment by neolit123** [comment]
> From the log, it appears that the apiserver of 172.16.6.4 does not work normally

+1, the api server needs to be accessible.

this appears to be a request for support. please try the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

or #kubeadm on k8s slack.

thanks
/kind support
/remove-kind bug
/close
