### ISSUE TITLE
kubectl auth can-i doesn't validate verb 

### ISSUE THREAD

**Issue by troy0820** [kubernetes/kubernetes#95471]
**What happened**:
When using kubectl auth can-i <verb> <resources> the "verb" isn't check and returns yes on any resource regardless of what the verb is.

**What you expected to happen**:
I expected the cli to register an error like when you don't have enough arguments.

**How to reproduce it (as minimally and precisely as possible)**:
```
kubectl auth can-i dfkajfdlfjk pods  
yes
```

**Anything else we need to know?**:
`none`

**Environment**:
- Kubernetes version (use `kubectl version`): client version GitVersion: 1.19.2 server version: GitVersion: 1.19.0
- Cloud provider or hardware configuration: Mac OS X
- OS (e.g: `cat /etc/os-release`):  n/a
- Kernel (e.g. `uname -a`): Darwin 
- Install tools: brew 
- Network plugin and version (if this is a network-related bug): n/a
- Others: `none`

**Comment by liggitt** [comment]
This is working as intended. The authorization layer can answer questions about arbitrary verbs, and the response to can-i mirrors the response you would get from a subjectaccessreview permission check. Getting a "yes" response to arbitrary verbs likely means you are a superuser and would be authorized for any operation.

**Comment by troy0820** [comment]
@liggitt Wouldn't a superuser only have access to the Kubernetes verbs that exist and not the arbitrary verbs that it is allowed to query that is defined here (https://kubernetes.io/docs/reference/access-authn-authz/authorization/#determine-the-request-verb)

This seems to go against the selfsubjectaccessreview which will return a set of actions that a user can perform.  Arbitrary verbs seem like they shouldn't be allowed from that definition.

**Comment by liggitt** [comment]
> Wouldn't a superuser only have access to the Kubernetes verbs that exist and not the arbitrary verbs that it is allowed to query that is defined here (https://kubernetes.io/docs/reference/access-authn-authz/authorization/#determine-the-request-verb)
> 
> This seems to go against the selfsubjectaccessreview which will return a set of actions that a user can perform

No, the cluster-admin superuser role allows `*` verbs which allows any verb
