### ISSUE TITLE
Helper utilities to implement a k8s PROXY api server with support for watching

### ISSUE THREAD

**Issue by yichengliu58** [kubernetes/kubernetes#95485]
**What would you like to be added**:
I need to implement a k8s proxy server, that receives clients (kubectl) requests and proxy them to real upstream k8s api servers, the server also needs to support watch requests. For this to come to true, the server has to keep two-way alive connections with both clients and upstream kube-apiserver.

In k8s code, there is  a struct called `WatchServer` (defined in `k8s.io/apiserver/pkg/endpoints/handlers/watch.go`, you pass a `watch.Interface` as events source, and this watch server will deal client watch requests)

As a client of the upstream kube-apiserver, we also have to receive events from upstream continuously. `SharedInformer` can be used, using `ResourceEventHandlerFuncs` to define `add`, `delete` and `update` funcs to specify the action to do when events come.

However we don't have a utility helper to connect these two components together. In functions of `ResourceEventHandlerFuncs` the argument is an `obj interface{}` which doesn't have any k8s resource related info. It's not able to transform the original `obj` to a typed event as the event source to `watch.Interface`

In total I'm looking for some utilities to make this proxy api server as easy as possible.

**Why is this needed**:
In my use case, there is one central server running the 'proxy server' to receive all client requests and proxy them to each kube-apiserver living on different clusters. For now we only use short HTTP connections to proxy small data to upstream server, which only satisfies requests like `get` or `patch`, but not `list` with `watch`.

**Comment by fedebongio** [comment]
/assign @cheftako @caesarxuchao 
/cc @deads2k 
/triage accepted
During triage, we discussed how much we want to build a full flesh proxy or not. Requires further discussion.
