### ISSUE TITLE
Kubernetes won't run 50,000 Jobs

### ISSUE THREAD

**Issue by geerlingguy** [kubernetes/kubernetes#95492]
**What happened**:

I created a project, [50k-k8s-jobs](https://github.com/geerlingguy/50k-k8s-jobs), in support of a video I made [50,000 Kubernetes Jobs for 50k Subscribers](https://www.youtube.com/watch?v=O1iEBzY7-ok), and going into the project, I thought it would be a pretty straightforward task: create 50,000 Job resources. Wait for the Jobs to get to 'succeeded' state, then I'm done.

I used a tiny Job template for efficiency, with the same image and command for each one, deployed into the default namespace:

```yaml
---
apiVersion: batch/v1
kind: Job
metadata:
  name: '[unique job id goes here]'
  namespace: default
spec:
  template:
    metadata:
      name: '[unique job id goes here]'
      namespace: default
      labels:
        type: '50k'
    spec:
      containers:
      - name: test
        image: alpine:3
        command: ['echo', 'complete']
      restartPolicy: Never
```

I knew it would take some time, but I expected that—unlike deploying [10,000 persistent Pods](https://github.com/geerlingguy/youtube-10k-pods), the Jobs would fire off a Pod, the Pod would complete, then there would be nothing for the scheduler to schedule or track except for new Jobs that are still not complete.

The first time I attempted this, it was on a Linode cluster with 8 nodes (total about 64 vCPUs, 64GB of RAM—though I don't know the master/control plane specs). I deployed the Jobs in batches of 100, and monitored how many were successful... it seemed to progress okay until passing around 3,000 jobs. Then, around 3,500 or 4,000, things got really slow, and then before it reached 5,000 Jobs it seemed like Job/Pod deployment completely stopped (I waited about 30 minutes and saw no more Jobs being deployed.

I replicated this behavior (though hitting that ceiling before 3,000 Jobs) on a local Kind cluster on my i9 MacBook Pro—the logs from the K8s scheduler/controller running 1.19.1 are in this issue: https://github.com/geerlingguy/50k-k8s-jobs/issues/3

Anyways, after that failure, I tried deploying in smaller batches (25 at a time), and waiting for each of the 25 Jobs to get to 'succeeded' before moving on to the next batch of Jobs. I thought that since Pods don't have to keep running, and since this is basically a case of running through the queue of Jobs, etcd/the K8s scheduler would be fine with this, but it wasn't. It still stalled out before hitting 5,000 jobs (documentation of this process here: https://github.com/geerlingguy/50k-k8s-jobs/issues/2).

In the end, I had to build a process that goes like this:

  1. Deploy [batch size] Jobs.
  2. Wait for [batch size] Jobs to get to 'succeeded' state.
  3. Delete [batch size] Jobs (and delete orphaned Pods).
  4. Move on to next batch.

This worked, but I am still surprised by the behavior of the scheduler starting to fall over after a few thousand Jobs. I'm wondering if I'm missing something essential here, because I didn't see any warnings about Job limits in the documentation (only Pod limits—which I'm well under). There are surely people with thousands of Jobs in a given cluster, right?

Related issue: https://github.com/geerlingguy/50k-k8s-jobs/issues/4

**What you expected to happen**:

All 50,000 Jobs should be able to be deployed and end up in 'succeeded' state eventually.

**How to reproduce it (as minimally and precisely as possible)**:

  1. Create 50,000 Jobs via the API.
  2. Wait for 50,000 Jobs to be complete.

If you want to test the exact scenario that I was testing:

  1. Clone https://github.com/geerlingguy/50k-k8s-jobs
  2. Install Python requirements: `pip3 install ansible openshift`
  3. Install Ansible requirements: `ansible-galaxy install -r requirements.yml`
  4. Create a Kubernetes cluster and make sure its kubeconfig is found by Ansible: `export K8S_AUTH_KUBECONFIG=~/.kube/yourconfig`
  5. Run the Ansible playbook: `ansible-playbook main.yml --extra-vars="{'batch_size':500,'total_count':50000,'inflight_cleanup':false}"`

**Anything else we need to know?**:

I have not yet tested this on an EKS cluster on Amazon, but I figure that might be a good next step, to see if/when the scheduler stalls there.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.x (LKE), 1.19.1 (Kind)
- Cloud provider or hardware configuration: Linode Kubernetes Engine and local Kind cluster on 2019 i9 MacBook Pro
- OS (e.g: `cat /etc/os-release`): LKE (not sure), macOS Catalina
- Kernel (e.g. `uname -a`): LKE (not sure), macOS Catalina
- Install tools: LKE's UI, Kind
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A

**Comment by Huang-Wei** [comment]
@geerlingguy Thanks for reporting this.

Some questions:

1. When the Pods gets into a stuck state, can you run `k describe pod <pod name>` to check its events? (esp. check the string "Insufficient pods")
1. It's very suspicious that you hit the pods limit per node, esp. given that "Delete [batch size] Jobs" made the flow work. So could you provide the parameter that sets the pods limit per node (default value is 110)? - it's usually set by kubelet via "max-pods" option.
1. Can you also dump the output of `k get node <node name> -o yaml`, and paste the "Node.Status.Allocatable.*" portion?

**Comment by geerlingguy** [comment]
> `k describe pod <pod name>`

I will do this once I get another stuck cluster set up — I didn't paste results from any of the clusters I was testing on yet, but I did `describe` some of the completed Pods, at least, and the Events looked very normal (e.g. scheduling on node xyz ... completed). I forgot to check on any of the pending Pods though (d'oh!).

> It's very suspicious that you hit the pods limit per node

I did not reach this limit, I was pointing out that at no point did I reach the limit, so I was asking if maybe there are some invisible or unstated Job limits that I'm unaware of?

> `k get node <node name> -o yaml`

I'll do that as well.

**Comment by geerlingguy** [comment]
Responding to #1:

```
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  39m   default-scheduler  Successfully assigned default/3500-6n2sj to lke11534-14345-5f84975df743
  Normal  Pulled     39m   kubelet            Container image "alpine:3" already present on machine
  Normal  Created    39m   kubelet            Created container test
  Normal  Started    39m   kubelet            Started container test
```

That was for a Pod in 'Completed' status.

I found a Job that was not yet successful:

```
$ kubectl describe job 3470
...
Events:
  Type    Reason            Age   From            Message
  ----    ------            ----  ----            -------
  Normal  SuccessfulCreate  12m   job-controller  Created pod: 3470-x6xkp
```

Then I looked up that Pod:

```
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  13m   default-scheduler  Successfully assigned default/3470-x6xkp to lke11534-14345-5f84975e0378
  Normal  Pulled     13m   kubelet            Container image "alpine:3" already present on machine
  Normal  Created    13m   kubelet            Created container test
  Normal  Started    13m   kubelet            Started container test
```

The Pod had already done it's work:

```
$ kubectl logs 3470-x6xkp
complete
```

So it looks like the Pods are being created without issue, but then the scheduler code that is supposed to see the success of the Pod is just... really really slow. Some of these Pods sit after they run their command for 10-20 minutes before the scheduler finally stops them and marks the Job succeeded (and the time seems to get longer as time goes on—I'm letting this cluster run for a really long time to get a graph for how much slower things get over time).

Responding to #3:

Here's the full output for all the nodes: https://pastebin.com/hfHHYzC6

They all had space available and no restrictions that seemed to limit Pods from being deployed to them; each of the 8 nodes looked like this while the Job deployment slowed to a crawl:

```
    allocatable:
      cpu: "4"
      ephemeral-storage: "152189082987"
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 8054936Ki
      pods: "110"
    capacity:
      cpu: "4"
      ephemeral-storage: 165135724Ki
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 8157336Ki
      pods: "110"
```

**Comment by Huang-Wei** [comment]
> Events:
>   Type    Reason     Age   From               Message
>   ----    ------     ----  ----               -------
>   Normal  Scheduled  13m   default-scheduler  Successfully assigned default/3470-x6xkp to lke11534-14345-5f84975e0378
>   Normal  Pulled     13m   kubelet            Container image "alpine:3" already present on machine
>   Normal  Created    13m   kubelet            Created container test
>   Normal  Started    13m   kubelet            Started container test

This indicates that scheduler has done its work - schedule the pod to node "lke11534-14345-5f84975e0378".

> So it looks like the Pods are being created without issue, but then the scheduler code that is supposed to see the success of the Pod is just... really really slow.

I guess it's the issue. In a normal case, scheduler received a DELETE event from API server which indicated the pod has been deleted (or variation of deletion, like completed for a run-to-completion job pod), and hence scheduler can remove the pod's resource request from its internal cache. Otherwise, scheduler would assume the pod is still running and hence reserving a certain amount of resources.

However, please note that the following assumption is incorrect:

> before the scheduler finally marks the Job succeeded

It's kubelet or(and) controller manager's responsibility to report the pod's completion, to API server, and then asynchronously, scheduler can receive the event, and eventually remove the pod's resources from its internal cache (as aforementioned).

So this issue may need to involve sig-node or(and) sig-apps.

**Comment by geerlingguy** [comment]
Interesting—and to be honest, that's why I posted the issue here, I only know the basics of the internal scheduler architecture, but it seemed (according to my notes in this issue comment: https://github.com/geerlingguy/50k-k8s-jobs/issues/3#issuecomment-706779723) the scheduler itself was the component that got stuck in a CrashLoopBackOff (`kube-scheduler-kind-control-plane` in Kind), so I _assume_ the same is happening on the Linode cluster, though I have a support ticket in to see if their staff can confirm that is the case.

**Comment by Huang-Wei** [comment]
From https://github.com/geerlingguy/50k-k8s-jobs/issues/3#issuecomment-706779723, it seems both controller-manger and scheduler are crashing due to unable to renew its lease.

To narrow down the problem, can you turn off leader election` in both controller-manager and scheduler, and then retry? I suppose you're running a non-HA control plane.

**Comment by geerlingguy** [comment]
@Huang-Wei - To disable leader election in Kind (documenting here since I couldn't really find it anywhere else), I tried:

  1. Edit the control plane pod: `kubectl edit pod kube-scheduler-kind-control-plane -n kube-system`
  2. Set `--leader-elect=false` in the `spec.containers[0].command`.

But I got the message:

```
pods "kube-scheduler-kind-control-plane" was not valid:
* spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*    ].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)
```

Do you know how I may be able to disable it in a Kind cluster (or more generally in any type of Kubernetes cluster—I am not seeing any documentation for it, anywhere.)

**Comment by geerlingguy** [comment]
I just stopped the deployment to the Linode cluster after 3 hours, and here is a quick plot of the data for how many jobs were deployed over time (increments on the graph are in ~10 minute increments):

![Jobs Deployed over time](https://user-images.githubusercontent.com/481677/95789864-eec4a780-0ca3-11eb-8334-4def0c29146e.png)

Do you expect I may see different behavior on a cloud provider like EKS, where I know there will be a multi-node control plane with HA?

**Comment by Huang-Wei** [comment]
> Do you expect I may see different behavior on a cloud provider like EKS, where I know there will be a multi-node control plane with HA? I can spin up a cluster there and run the same test to see what happens.

Thanks for offering that. For now let's disable leader-election on a kind cluster and see how it goes.

**Comment by geerlingguy** [comment]
@Huang-Wei - Thanks! I'm booting up the local cluster now. I'll report back with results.

**Comment by Huang-Wei** [comment]
BTW: you can optionally disable leader election also:

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv4
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  metadata:
    name: config
  scheduler:
    extraArgs:
      "leader-elect": "false"
  controllerManager:
    extraArgs:
      "leader-elect": "false"
nodes:
# the control plane node
- role: control-plane
- role: worker
```

**Comment by geerlingguy** [comment]
All right, I created a new cluster using that config (`kind create cluster --config=kind-config.yaml`), and confirmed it had leader election disabled (`--leader-elect=false`). I'll do a new result set this way (deploying batches of 50 Jobs), then run the exact same job with `--leader-elect=true` again, for comparison.

The reason I'm going to run it again with `true` is because I set up a new cooling system for my poor overworked laptop earlier today (it kept overheating this week due to a new desk component I installed that had blocked some airflow), and I don't want a difference in CPU temperature to cause any issues with the results!

I'll post back in my next comment results from both tests.

**Comment by geerlingguy** [comment]
/me goes around changing multiple variables... This morning I had bumped my Docker for Mac RAM allocation to 8 GB (it was 2 GB), and now both the graphs look similar, and while they show a regression over time, it's not dramatic like the Linode example was, or my earlier example when I ran it with 2 GB of RAM on my MacBook Pro:

`--leader-elect=false`:

![jobs-local-leader-elect-false](https://user-images.githubusercontent.com/481677/95812488-2569e480-0cdb-11eb-8269-e5a4533be019.png)

`--leader-elect=true`:

![jobs-local-leader-elect-true](https://user-images.githubusercontent.com/481677/95812496-29960200-0cdb-11eb-84a4-82460664f6af.png)

I'm running the test again now, with Docker back down to 2 GB of RAM instead of 8 GB, and I'll see if that triggers the slowdown around 3k Jobs. I also asked Linode about their specs for the master/control plane, but mum's the word there. I understand since that's probably part of the reason you don't have to pay for it (not HA, and likely not a huge allocation of RAM either), but it would be nice to get an idea of whether that's the root issue—a lack of memory on the controller.

**Comment by geerlingguy** [comment]
I finished the two runs today with Docker limited to 2 GB of RAM, and both of them started running into issues around 3,000 jobs  (regardless of the `--leader-elect` value):

![jobs-local-2gb-ram-true](https://user-images.githubusercontent.com/481677/95865496-60483880-0d2c-11eb-87c8-ce9464fde4d8.png)

![jobs-local-2gb-ram-false](https://user-images.githubusercontent.com/481677/95865505-63432900-0d2c-11eb-82a7-cf24cf581714.png)

At this point, I guess the two questions I have are:

  1. Do Jobs need more RAM to scale to more Jobs, and could that be avoided? (Jobs definitely don't scale in a linear way.) It seems like even with 16/32/64 GB of RAM I'd start running into problems at some higher number—I've seen many clusters where the team managing the cluster doesn't even manage resource usage that much (e.g. I could see them having thousands of Jobs over the years).
  2. Is there any way besides manual GC on Jobs to prevent this issue on clusters with lower master memory limits?

**Comment by Huang-Wei** [comment]
> 2\. Is there any way besides manual GC on Jobs to prevent this issue on clusters with lower master memory limits?

Setting Job TTL would help on GC completed job automatically.

- https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/
- https://kubernetes.io/docs/concepts/workloads/controllers/job/#clean-up-finished-jobs-automatically

**Comment by geerlingguy** [comment]
@Huang-Wei - Unfortunately it seems that's behind an alpha flag, and is not enabled on at least LKE and EKS because it is in alpha.

**Comment by Huang-Wei** [comment]
> Unfortunately it seems that's behind an alpha flag, and is not enabled on at least LKE and EKS because it is in alpha.

True :(

> 1. Do Jobs need more RAM to scale to more Jobs, and could that be avoided? (Jobs definitely don't scale in a linear way.) It seems like even with 16/32/64 GB of RAM I'd start running into problems at some higher number—I've seen many clusters where the team managing the cluster doesn't even manage resource usage that much (e.g. I could see them having thousands of Jobs over the years).

Some questions:

- is that everytime controller-manager crashed when the number of Jobs come to a threshold? or both controller-manager and scheduler crashes?
- when it hits the threshold, what's the status of the pods? Are there purely 3k `Completed` pods, or 3k `Completed` pods plus a number (or thousands) of `Pending` pods?
- if there are `Pending` pods, could you check how many there are? and could you run `k describe pod <pending pod name>` (not describe job) to check its status?

---

Technically, scheduler don't track/watch Job, it only cares about Pod, and once a Pod enters "Completed" state, it's removed from scheduler memory, so scheduling thousands of Jobs is not a big deal.

In terms of controller manager, as the Jobs would sit there until being deleted, I guess it would consume both memory footprint as well as syncing time.

**Comment by geerlingguy** [comment]
I just wanted to mention this ticket was featured over in [Coffee and Cloud Native - E54](https://www.youtube.com/watch?v=7yWbxqwRMCU), and one potential workaround to running insane quantities of Jobs in K8s would be a separate tool like [armada by G-Research](https://github.com/G-Research/armada/).

I haven't had time to really dig into this yet, mostly because I'm super distracted right now by Raspberry Pi stuff, but A couple quick responses:

> is that everytime controller-manager crashed when the number of Jobs come to a threshold? or both controller-manager and scheduler crashes?

I'd have to bring up another cluster to confirm, but I believe only the controller manager was crashing.

> when it hits the threshold, what's the status of the pods? Are there purely 3k Completed pods, or 3k Completed pods plus a number (or thousands) of Pending pods?

Pods are Completed, no Pending pods at all.

> if there are Pending pods, could you check how many there are? and could you run k describe pod <pending pod name> (not describe job) to check its status?

N/A since there aren't any Pending pods.

**Comment by Huang-Wei** [comment]
Thanks @geerlingguy . Good to know that all Pods are completed, so it seems more a scalability issue in controller manager side.
