### ISSUE TITLE
[suggestion] consider explicitly defining String() on metav1.Time

### ISSUE THREAD

**Issue by justenwalker** [kubernetes/kubernetes#95496]
**What would you like to be added**:

explicitly define String on [metav1.Time](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/time.go)

```go
func (t Time) String() string {
  return t.Time.String()
}
```

or perhaps safer

```go
func (t *Time) String() string {
  if t == nil { // don't have to rely on panic()/recover() to print a "<nil>"
    return "<nil>"
  }
  return t.Time.String()
}
```

**Why is this needed**:

There is a bug when debugging certain types that embed other types having value receivers for String(); when they get called in a nil pointer context on MacOS. Basically, the `fmt` package relies on recovering from a nil panic to print the `<nil>` string, and on MacOS this gets intercepted by LLDB as a EXC_BAD_ACCESS which breakpoints before Go has an opportunity to panic/recover. Although the issue technically starts upstream in LLDB, a fix has seen little to no progress.

See:
- https://github.com/go-delve/delve/issues/2190
- https://github.com/go-delve/delve/issues/852
- https://bugs.llvm.org/show_bug.cgi?id=22868

The issue arrises in Kubernetes types that define pointers to `metav1.Time` such as `DeletionTimestamp`; When running a debugger on MacOS - If they are printed using `fmt` when they are null - they will cause MacOS to SEGV (EXC_BAD_ACCESS), instead of letting Go handle the panic and recover.  This creates problems for developers creating controllers or working with kubernetes code while on a Mac, since certain code paths are not debuggable due to this issue.

When not running in a debugger; Go will correctly handle this case by recovering from the panic and printing `<nil>` in its place. ([fmt/printer.go:537-544](https://github.com/golang/go/blob/99f179f55a66f35dc7861fa411b42ed61bd0df31/src/fmt/print.go#L537-L544))

In order to make this type behave better on MacOS, this work-around requires minimal (albeit redundant) code and seems to make the issue go away without any undesirable consequences. Overall I think it would be nice not to rely on panic()/recover() to get the desired string in the `nil` case; but both variants appear to work indistinguishably.

**Comment by lavalamp** [comment]
I don't hugely object to adding this function, but given the stated reason, I think an application level fix is not right, and I don't want to start a precedent of carrying patches for that reason. Like, this is probably not even the only place in k8s where a patch would be necessary. So, I'm really sorry, because the LLDB bug looks very unfortunate, but I don't think I can sign us up to solve that problem in this codebase.

You can appeal to @deads2k but I expect he'll say the same thing.

**Comment by justenwalker** [comment]
Thanks for the feedback @lavalamp.

Hope against all hope I'd like to appeal this decision (@deads2k)

I appreciate that this change may start a bad precedent of accepting patches for platform-specific reasons, but I'm not sure I agree that this down-side alone completely out-weighs the benefit to developers on MacOS debugging controllers and k8s resources.

While I'd love for this to be fixed upstream, given its long history and glacial pace, I'd consider this upstream bug as effectively marked "wont-fix". 

To your other point, although it's probably not the only place a patch would be necessary to fully fix the issue, `metav1.Time` is likely the only type that developers will encounter this bug. Given that this type is implicitly included in **every** Kubernetes resource, a fix targeting this one type will mitigate a high percentage of occurrences and deserve special exception, given that the change itself is so trivial.

**Comment by deads2k** [comment]
I'm not excited about the idea of picking up a chain of "create special case X for developer tool Y".  Like @lavalamp, I suspect that you'll hit many of these and special-casing each one will quickly become tedious and reactive over time.

Do you have a way to try to gather all the special cases we need to debug the kube-controller-manager as a whole?  That full list would be more compelling to me, since it would provide evidence that we've actually made a new thing possible instead of simply fixing the first of 100 platform specific developer tool failure cases.

**Comment by lavalamp** [comment]
Yeah, if this is literally the only thing needed, then it is small enough that it's hard to say no to.

**Comment by justenwalker** [comment]
> ... platform specific developer tool failure cases.

While I suppose it is technically a tool-specific problem, unless there is another practical way to debug Go programs on Mac OS: all developers are using Delve (via LLDB).  So they will all invariably experience this -- there is no obvious alternative tool or work-around.

> Do you have a way to try to gather all the special cases we need to debug the kube-controller-manager as a whole? That full list would be more compelling to me, since it would provide evidence that we've actually made a new thing possible instead of simply fixing the first of 100 platform specific developer tool failure cases.

I've tried my hand at [Semgrep](https://semgrep.dev/) but either it is not yet powerful enough to find what I need, or I'm simply not knowledgeable enough to express it in a way that it understands.

To describe it in words what I'd be looking for:

Find any type `T` in the form: 
```go
type T struct { 
  V
  ...
}
```

For which the following is true:

1. `V` implements `String() string` on its value receiver:

```go
func (v V) String() string {
 ...
}
```

2. `T` **does not** implement `String() string` at all (either via pointer or value) -- in other words, it inherits `String() string` via its embedded type `V`

3. `T` is a Field on a type `W` as a pointer

```go
type W struct {
  T *T
  ...
}
```

I'm not sure such a tool exists to find types with these constraints, and trying to do this manually is likely impractical. It would be nice to have definitive proof that `metav1.Time` is the only one that satisfies these constraints... if anyone has any ideas on how to prove this practically, I'd be really interested to know.
