### ISSUE TITLE
Accessing field 'firstUnhealthyPod.Name' may lead to nil pointer?

### ISSUE THREAD

**Issue by hantmac** [kubernetes/kubernetes#95507]
**What would you like to be added**:
Although once given that `firstUnhealthyOrdinal` is initialized with MAX_INT, the condition `ord := getOrdinal(condemned[i]); ord < firstUnhealthyOrdinal` will always met, in my opinion, the code in https://github.com/kubernetes/kubernetes/blob/475849eafaafb653c6c238d4947b7c17f191afee/pkg/controller/statefulset/stateful_set_control.go#L376 and https://github.com/kubernetes/kubernetes/blob/475849eafaafb653c6c238d4947b7c17f191afee/pkg/controller/statefulset/stateful_set_control.go#L490 , we accessing field 'firstUnhealthyPod.Name' may lead to nil pointer if the `firstUnhealthyPod` was not is assigned value.
Because `firstUnhealthyPod` is assigned only when meet the condition `ord := getOrdinal(condemned[i]); ord < firstUnhealthyOrdinal `. If not ( get some errors in condition),  `firstUnhealthyPod` is nil.

**Why is this needed**:
Add `&& firstUnhealthyPod != nil` in condition before using firstUnhealthyPod.name.

**Comment by kow3ns** [comment]
Both statements are wrapped in a test that will fail if no unhealthy Pod was found. This null is not a valid bug.

**Comment by hantmac** [comment]
> Both statements are wrapped in a test that will fail if no unhealthy Pod was found. This null is not a valid bug.

You mean this condition `ord := getOrdinal(condemned[i]); ord < firstUnhealthyOrdinal` will be met definitly?
