### ISSUE TITLE
kube-proxy bind-address flag definition is not correct for ipvs or iptables modes

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#95515]
**What happened**:

kube-proxy documents the bind-address flag as 

https://github.com/kubernetes/kubernetes/blob/01f3f6798953c0afbc224955445b9aaa125abf77/pkg/proxy/apis/config/types.go#L114-L116

however, this seems to apply only to kube-proxy in userspace mode, where it is used as ListenIP
https://github.com/kubernetes/kubernetes/blob/01f3f6798953c0afbc224955445b9aaa125abf77/pkg/proxy/userspace/proxier.go#L150

However, the `--bind-address` is also used to detect the kube-proxy IP family based on the NodeIP, it uses the the following logic to obtain the NodeIP

https://github.com/kubernetes/kubernetes/blob/01f3f6798953c0afbc224955445b9aaa125abf77/cmd/kube-proxy/app/server_others.go#L420-L425

For iptables and IPVS modes, this NodeIP seems to be only used for the filtering on LoadBalancer source ranges

https://github.com/kubernetes/kubernetes/blob/01f3f6798953c0afbc224955445b9aaa125abf77/pkg/proxy/ipvs/proxier.go#L1359-L1362

https://github.com/kubernetes/kubernetes/blob/01f3f6798953c0afbc224955445b9aaa125abf77/pkg/proxy/iptables/proxier.go#L1189-L1191

Another thing to highlight, is that in dual stack mode we are using the NodeIP Proxier parameted wrongly, 

https://github.com/kubernetes/kubernetes/blob/01f3f6798953c0afbc224955445b9aaa125abf77/cmd/kube-proxy/app/server_others.go#L223

we are passing to the proxiers the bind address directly (not the NodeIP obtained) and passing the unspecified IP address to the other IP family, but it should pass the NodeIP in each IP family:

https://github.com/kubernetes/kubernetes/blob/01f3f6798953c0afbc224955445b9aaa125abf77/cmd/kube-proxy/app/server_others.go#L553-L556

I just realised that we don't have userspace kube-proxy for dualstack, but we allow to create it:

https://github.com/kubernetes/kubernetes/blob/01f3f6798953c0afbc224955445b9aaa125abf77/cmd/kube-proxy/app/server_others.go#L342-L346

**What you expected to happen**:

- bind-address should keep having the same functionality, to not break users, just clarify the flag description to be more accurate, however, I can't find a right way of how can explain this :/
```
The IP address for the user-space proxy server to serve on (set to '0.0.0.0' by default). It will be used as NodeIP for ipvs and iptables modes, if 0.0.0.0, it will use the NodeIP reported by the kubelet. If this IP does not exist, it will default the NodeIP to 127.0.0.1
```

- should we allow it to use comma separated list to set the nodeIP in dual stack mode? 
It seems that we don't need to, since we are going to use both IP families, or is there any need to override the NodeIP?

- kube-proxy in ipvs and iptables-mode can use directly the NodeIP from the API, and not have any dependency on bind-address, allowing users to configure a node-ip that may be not present in the node seems wrong to me.

- should we forget about userspace proxier for dual stack?

**Comment by danwinship** [comment]
> bind-address should keep having the same functionality, to not break users, just clarify the flag description to be more accurate, however, I can't find a right way of how can explain this :/

I don't think there is any good way to explain it in the length of a command-line-option description.

It might make sense to deprecate the old flag and provide new ones with clearer semantics?

> should we allow it to use comma separated list to set the nodeIP in dual stack mode?

No, let's not make bind-address any worse than it is. If there is a need for being able to specify dual-stack node IPs for some part of kube-proxy functionality, let's figure out exactly what that functionality is, and add a non-overloaded way to configure it correctly.

> should we forget about userspace proxier for dual stack?

The userspace proxier is mostly deprecated. There is no reason to prioritize dual-stack support for it if no one is going to use it. (In particular, OpenShift still uses the userspace proxier for openshift-sdn's unidling mode, but we aren't supporting dual-stack with openshift-sdn (and ovn-kubernetes does unidling differently) so we don't care if userspace supports dual-stack.)

**Comment by aojea** [comment]
/close
The proxiers efforts should better be focused to improve what we have, this seems hard to fix now

**Comment by aojea** [comment]
/reopen
/assign @khenidak 

This will fixed by https://github.com/kubernetes/kubernetes/pull/104691/

**Comment by khenidak** [comment]
@aojea do we still need this open?

**Comment by aojea** [comment]
> @aojea do we still need this open?

/close

I can't remember exactly, but last comment I did mentions a PR that already merged, so let's close it
