### ISSUE TITLE
Update flaky test template with clearer instructions

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#95528]
Followup per https://github.com/kubernetes/community/pull/5205/files#r502665584

That PR updates https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/flaky-tests.md with clearer instructions on how to fill out https://github.com/kubernetes/kubernetes/issues/new?labels=kind%2Fflake&template=flaking-test.md

We should update the issue template itself with these instructions, so that we can avoid having instructions in two places that may drift apart.  Perhaps the template could recommend reading through the doc in its comments.

**Comment by spiffxp** [comment]
/sig release
FYI @kubernetes/ci-signal

**Comment by thejoycekung** [comment]
@spiffxp Should we also add https://github.com/kubernetes/community/pull/5449 to this template once that's merged?

**Comment by spiffxp** [comment]
Yeah.  Two different guides and another in-depth set of instructions in this template will lead to stale content and confusion for contributors.  Ultimately there should be one guide for "how to file a flake issue".  If most of those instructions could fit in this template, this could be the guide.  If not, the issue template could link to the guide.

I don't know where a guide should ultimately live if we need to link to it.  `k/c/.../sig-testing/monitoring.md`, `k/c/.../sig-testing/flaky-tests.md` both feel like supersets.  I'm wondering about something like `filing-issues.md#kind-flake` or `filing-flake-issues.md`, maybe homed in sig-testing, sig-release, or the contributor guide.  Setting up a go link like `go.k8s.io/howto-file-flake-issues` could reduce the places we'd need to change the link if we're having hard time deciding.

**Comment by thejoycekung** [comment]
I think having a doc in the contributor guide sounds like a good idea, even if it's just a list of links to other docs. Right now the CI Signal role handbook in sig-release houses some of this info, but I think having a central home with more docs would be more helpful, and it could help trim down the size of the handbook 😅 

How does this sound:

1. Finish reviewing https://github.com/kubernetes/community/pull/5449 and get that merged
2. Add a doc to the contributor guide that contains a link to that `monitoring.md` doc and the `flaky-tests.md` doc, and any other relevant information that might be useful (e.g. @RobertKielty and @hasheddan's Flake Finder series, or their Contributor Summit talk)
3. (this issue) Update the flaky test template with a link to said doc within the contributor guide.

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE/flaking-test.yaml is updated by https://github.com/kubernetes/kubernetes/pull/104468.

In https://github.com/kubernetes/kubernetes/issues/new?assignees=&labels=kind%2Fflake&projects=&template=flaking-test.yaml, we can see the link of flaking test now.

Do we need to add more instructions there? All that we may miss is about how to check multi job failure and multi test failure with similar reason, but this is already in the first link. 
- https://github.com/kubernetes/kubernetes/compare/master...pacoxu:kubernetes:patch-10
