### ISSUE TITLE
Extend kubectl api-resources to include API versions

### ISSUE THREAD

**Issue by lilic** [kubernetes/kubernetes#95523]
**What would you like to be added**:

Currently the `kubectl api-resources` command doesn't include an API version of the resources.

**Why is this needed**:

I would like to see which versions of the APIs are preferred by the apiserver in the cluster.

**Comment by soltysh** [comment]
It's already done in https://github.com/kubernetes/kubernetes/pull/95253

**Comment by lilic** [comment]
@soltysh nice, thanks! :D just in time when I need it.
