### ISSUE TITLE
Scheduler VolumeBinding plugin returns error instead of unschedulable

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#95538]
**What would you like to be added**:
Scheduler VolumeBinding plugin reports error when a PVC doesn't exist for example: https://github.com/kubernetes/kubernetes/blob/9891ac4d4dd648c3f38d12e4e16fc55573b6606d/pkg/controller/volume/scheduling/scheduler_binder.go#L291

We need to take a second look at the VolumeBinding plugin and make sure that errors are returned only when there is a system error, not a user error.

**Why is this needed**:
To fix the scheduler's error reporting metrics.

/sig scheduling
/sig storage
/cc @cofyc

**Comment by cofyc** [comment]
/assign 
I'll take a look.

**Comment by cofyc** [comment]
If the PVC object does not exist, the plugin will return `UnschedulableAndUnresolvable` status.

https://github.com/kubernetes/kubernetes/blob/9891ac4d4dd648c3f38d12e4e16fc55573b6606d/pkg/scheduler/framework/plugins/volumebinding/volume_binding.go#L123-L126

I guess you mean the plugin will return an error when a referenced PV does not exist?

I've created a PR for this: https://github.com/kubernetes/kubernetes/pull/95541

**Comment by ahg-g** [comment]
Thanks! The errors I am seeing are on 1.18 clusters, can we look at 1.18 and try to patch? This is still throwing the scheduler's error metrics off.

**Comment by cofyc** [comment]
sure

**Comment by cofyc** [comment]
I've submitted a patch for the 1.18 release branch: https://github.com/kubernetes/kubernetes/pull/96135

**Comment by cofyc** [comment]
I guess https://github.com/kubernetes/kubernetes/pull/95541 on the master branch should be reviewed and merged too? cc @msau42

**Comment by cpanato** [comment]
@cofyc hello! the fix you made only apply for 1.18? how about 1.19 and 1.17?
thanks!

**Comment by cofyc** [comment]
after the fix on the master branch (https://github.com/kubernetes/kubernetes/pull/95541) is merged, I'll cherry-pick it into the 1.19 branch (the code are almost the same).

I'm not sure if it's necessary to fix the 1.17 branch. It's 3 versions behind 1.20.

**Comment by cofyc** [comment]
hi, @ahg-g 

> If the PVC object does not exist, the plugin will return `UnschedulableAndUnresolvable` status.

This is because of this patch: https://github.com/kubernetes/kubernetes/pull/92846/files#diff-75e4458878912a7aef522a2eebd4928b91d7622445f2da897119450016cc8a49L96-L97

Do you think this fix needs to be cherry-picked into 1.19 and 1.18 branch too?

**Comment by ahg-g** [comment]
> after the fix on the master branch (#95541) is merged, I'll cherry-pick it into the 1.19 branch (the code are almost the same).
> 
> I'm not sure if it's necessary to fix the 1.17 branch. It's 3 versions behind 1.20.

can you send a patch for 1.19?

**Comment by ahg-g** [comment]
ah, here it is https://github.com/kubernetes/kubernetes/pull/96291

**Comment by cofyc** [comment]
to sum up:

- master: https://github.com/kubernetes/kubernetes/pull/95541
- 1.19: https://github.com/kubernetes/kubernetes/pull/96291
- 1.18: https://github.com/kubernetes/kubernetes/pull/96135

and I think this change should be backported to 1.19/1.18 too: 

https://github.com/kubernetes/kubernetes/pull/92846/files#diff-75e4458878912a7aef522a2eebd4928b91d7622445f2da897119450016cc8a49L96-L97

I'll send PRs soon.

**Comment by cofyc** [comment]
> to sum up:
> 
> * master: #95541
> * 1.19: #96291
> * 1.18: #96135
> 
> and I think this change should be backported to 1.19/1.18 too:
> 
> https://github.com/kubernetes/kubernetes/pull/92846/files#diff-75e4458878912a7aef522a2eebd4928b91d7622445f2da897119450016cc8a49L96-L97
> 
> I'll send PRs soon.

summary of the issue that an error will be reported instead of UnschedulableAndUnresolvable when PVC not found:

- master: already implemented, see [PR 92846](https://github.com/kubernetes/kubernetes/pull/92846/files#diff-75e4458878912a7aef522a2eebd4928b91d7622445f2da897119450016cc8a49L96-L97)
- 1.19: https://github.com/kubernetes/kubernetes/pull/96850
- 1.18: can't backport as it does not implement the PreFilter extension point
