### ISSUE TITLE
client-go DeleteCollection doesn't work as expected.

### ISSUE THREAD

**Issue by tanjunchen** [kubernetes/kubernetes#95537]
**What happened**:

see https://github.com/istio/istio/issues/27910

client-go DeleteCollection doesn't work as expected.The function call returns normally without any error but it doesn't  delete anything.

**What you expected to happen**:

I hope that deleting a non-existent resource will report an error. No error is reported when deleting non-existent resources. I don't know if it was designed like this on purpose. No error is reported, why is the return type error?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tanjunchen** [comment]
sig/api-machinery

**Comment by cheftako** [comment]
Which resource are you trying to delete?
So I believe the underlying HTTP method does as your suggesting. As far as I can tell the API Server is returning a 404 for an already deleted object.
kubectl -v 9 delete pod junk
I1026 20:25:02.778470 4055864 round_trippers.go:423] curl -k -v -XDELETE  -H "User-Agent: kubectl/v1.19.0 (linux/amd64) kubernetes/****" -H "Authorization: Bearer ***************" -H "Accept: application/json" -H "Content-Type: application/json" 'https://localhost:443/api/v1/namespaces/default/pods/junk'
I1026 20:25:02.788145 4055864 round_trippers.go:443] DELETE https://localhost:443/api/v1/namespaces/default/pods/junk 404 Not Found in 9 milliseconds

However the API was written an an API for Kubernetes controller authors and not a strict interface to the underlying REST API. The API was more meant to reflect an API of please make sure X does not exist. So if it was called with a non-existent X, it would return "ok X does not exist". Changing that at this point is not backward compatible and in fact would generate a significant number of bugs over time as we found all the places the code does not handle some sort of already deleted error. This becomes more true as many of the controller (and webhook and operator and ...) code sections do not exist in our code base.

I would suggest either A) do a GET before your DELETE if you are ok with the possible race condition or help us work out a reasonable REST level API which would do what you want but does not break our existing customers.
