### ISSUE TITLE
Improve the documentation for "RotateCertificates" config value

### ISSUE THREAD

**Issue by eranreshef** [kubernetes/kubernetes#95546]
**What happened**:

I tried to enable tls-bootstraping for master nodes while having control plane components created as static pods by kublet.
When kubelet started, it first tried to access the api-server to create a CSR before actually starting the api-server which caused sort of a dead-lock.
When I enabled the certificate rotation flag, the bootstrapping process moved to the background and didn't block kubelet from starting the api-server.

**What you expected to happen**:
I think it would be helpful to mention in this [config value's documentation](https://github.com/kubernetes/kubernetes/blob/46b5eb333850b851b44bcc11cbee06d257315fb6/staging/src/k8s.io/kubelet/config/v1beta1/types.go#L187)  that it also causes the bootstrapping process to move to the background. Also, [this article ](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/)should be updated to mention that tls-bootstraping can also work for master nodes.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.2
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): flatcar-linux

**Comment by adeniyistephen** [comment]
@eranreshef @liggitt @k8s-ci-robot Is this issue still open? if not I would need guidance on the documentation improvement.

**Comment by eranreshef** [comment]
@adeniyistephen seems that it is still open

**Comment by adeniyistephen** [comment]
@liggitt @k8s-ci-robot I would love to work on this, Please provide pointers and input on how to work on it. Thanks

**Comment by liggitt** [comment]
> I tried to enable tls-bootstraping for master nodes while having control plane components created as static pods by kublet.
> When kubelet started, it first tried to access the api-server to create a CSR before actually starting the api-server which caused sort of a dead-lock.
> When I enabled the certificate rotation flag, the bootstrapping process moved to the background and didn't block kubelet from starting the api-server.

That sounds more like a bug that should be fixed than something that should be documented... 

cc @smarterclayton for related issues like https://github.com/kubernetes/kubernetes/pull/58930

**Comment by eranreshef** [comment]
@liggitt please don't change the current behaviour, it is necessary for setup I (and some more k8s distributions) have.
Why do you think its a bug?

**Comment by liggitt** [comment]
Starting static pods should not depend on or be blocked by the kubelet having constructed a client to talk to the API server.

**Comment by adeniyistephen** [comment]
> I should have been clearer about what I thought was a bug.
> 
> Starting static pods should not depend on or be blocked by the kubelet having constructed a client to talk to the API server, regardless of whether certificate rotation is enabled or not.

@eranreshef Oh, OK. so what about the documentation?

**Comment by eranreshef** [comment]
well if the behaviour is fixed so that static pods are always started regardless of the certificate-rotation flag, than there will be no need to fixed the documentation.

**Comment by rajpratyush** [comment]
@liggitt Hi this is my first time contributing to kubernetes. can you provide me some guidance on how to to get started?

**Comment by liggitt** [comment]
I would start by reproducing the hang in a local build with the described config: TLS bootstrap on, RotateCertificates off.

To recreate, you can force the API calls made during TLS bootstrapping to block (e.g. putting a log message and long time.Sleep in the code paths that try to make synchronous requests to the API server during kubelet startup block).

Then work through the differences between RotateCertificates=true and RotateCertificates=false scenarios. I would expect handling of static pods to be the same between those two cases.
