### ISSUE TITLE
ExternalTrafficPolicy: local in iptables proxy impl intermittently fails if source is in pod CIDR, however not a part of the cluster.

### ISSUE THREAD

**Issue by tdihp** [kubernetes/kubernetes#95555]
**What happened**:

iptables implementation of kube-proxy will result in incorrect address conversion given the below condition:

1. Accessing a LoadBalancer service with ExternalTrafficPolicy: local.
2. At least two endpoints across two nodes.
3. Client accessing the service has a IP address inside the pod CIDR
4. Client is not a part of the cluster. (e.g. a VM in the same subnet)

Removing any of the 4 condition the traffic will work fine.

When making packet capture, we find the packet was converted at the server side so that:

* The src is unchanged and not mangled, the same client IP address
* The dest is converted to a random endpoint behind the loadBalancer.

When removing condition 4 (i.e. curl from a pod IP instead of a VM not a part of the subnet), we observe the same dest IP conversion from the **client side** instead of server side, the connectivity works well.

**What you expected to happen**:

Src IP in pod CIDR doesn't necessarily means it is a pod in the cluster. Since the client side conversion is only meant as a "shortcut", kubernetes should be able to detect and avoid the dest IP getting converted from the server side.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create AKS cluster with Azure-CNI configuration with two nodes.
2. Create a VM in the same subnet.
3. Create any http service with two pods, ExternalTrafficPolicy: local and internal loadBalancer configuration.
4. curl the http service with internal loadBalancer IP repeatedly.

**Anything else we need to know?**:

From the iptables rule the most related one is:

    -A KUBE-XLB-NKH4XARTV5JPXXTG -s 10.184.112.0/20 -m comment --comment "Redirect pods trying to reach external loadbalancer VIP to clusterIP" -j KUBE-SVC-NKH4XARTV5JPXXTG

Which converts loadbalancer VIP to clusterIP, it is then in turn converted to pod IP in the svc chain. From the rule it works on both side, i.e. it works if the client side has the rule, however if the client side doesn't have the rule, the server side will still be able to match this rule and convert. 

--> Probably also add `-m addrtype --src-type LOCAL` in https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/iptables/proxier.go#L1410?

Probably related: #74383

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.11
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): ubuntu 16.04
- Kernel (e.g. `uname -a`): Linux aks-nodepool1-32583918-vmss000000 4.15.0-1096-azure #106~16.04.1-Ubuntu SMP Thu Sep 10 18:51:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug): azure CNI
- Others:

**Comment by tdihp** [comment]
@kubernetes/sig-network-bugs

**Comment by thockin** [comment]
> Src IP in pod CIDR doesn't necessarily means it is a pod in the cluster

Actually, that is *exactly* what it means.

Having something in the cluster CIDR which is not in the cluster is not something any of this code is written to handle.   That said, we're trying to excise the need for cluster-cidr knowledge on nodes.  Can you use the `--detect-local-mode=NodeCIDR` instead?

**Comment by tdihp** [comment]
For the Azure CNI the current implementation uses the same CIDR for both nodes and pods so it's not a valid option for at least this platform.

**Comment by thockin** [comment]
That's not really a valid config, but I suspect it would work as long as it
was only cluster nodes and cluster pods.  Having something else use that
range is just wrong and is not something that was ever accounted for.

I am not against reasonable fixes to stop the bleeding, but I don't think
that is something we want to support in general.

Sorry to hear bad news...

I know Kal is on the this issue, he may have more context...

**Comment by khenidak** [comment]
Ack..

**Comment by paulgmiller** [comment]
We're doing some work in this area to make azure cni a bit more flexible. Stay tuned to the below for more details. 
https://github.com/Azure/azure-container-networking/issues/707

**Comment by thockin** [comment]
I don't think there's any response to this issue from the k/k codebase?
