### ISSUE TITLE
Calls with verb=GET are reported with verb=LIST in metrics

### ISSUE THREAD

**Issue by mborsz** [kubernetes/kubernetes#95556]
**What happened**:
While I was watching grafana for a single run, I noticed that GET requests are reported as LIST requests, e.g. grafana shows ~1K QPS for LIST of pods
![8vS47hgQ9GxtJhL](https://user-images.githubusercontent.com/2559168/95988213-dd58d800-0e28-11eb-9687-7c7c80dbc373.png)
while kube-apiserver's logs show:
```
I1014 12:24:03.449859      11 httplog.go:89] "HTTP" verb="GET" URI="/api/v1/namespaces/test-mxsrii-31/pods/small-deployment-65-75785d8948-rwmdg" latency="5.177181ms" userAgent="kubelet/v1.20.0 (linux/amd64) kubernetes/ee297b6" srcIP="10.40.7.26:46666" resp=200
I1014 12:24:03.449819      11 httplog.go:89] "HTTP" verb="GET" URI="/api/v1/namespaces/test-mxsrii-17/pods/medium-deployment-0-698b4b86b9-fchjq" latency="6.536801ms" userAgent="kubelet/v1.20.0 (linux/amd64) kubernetes/ee297b6" srcIP="10.40.17.27:33852" resp=200
I1014 12:24:03.450079      11 httplog.go:89] "HTTP" verb="GET" URI="/api/v1/namespaces/test-mxsrii-33/pods/big-deployment-0-76677bd886-hthls" latency="7.076651ms" userAgent="kubelet/v1.20.0 (linux/amd64) kubernetes/ee297b6" srcIP="10.40.10.81:53078" resp=200
I1014 12:24:03.450385      11 httplog.go:89] "HTTP" verb="GET" URI="/api/v1/namespaces/test-mxsrii-31/pods/small-deployment-231-588fb44685-6ntjv" latency="7.255073ms" userAgent="kubelet/v1.20.0 (linux/amd64) kubernetes/ee297b6" srcIP="10.40.17.89:36454" resp=200
```
(there are no pod lists that time).

I'm not sure if this is intended change to metrics reporting (kind of unexpected to be honest), but this definitely affects way our scalability tests validate latency metrics:
* We do not validate GET API call latency at all
* Validation for LIST requests is also affected, as usually GET API calls are way cheaper than LIST requests, so grouping GET-LISTs and LIST-LISTs together lowers p99 for LISTs.

Also perf-dash shows that GET requests simply disappeared at some point:
http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=APIServer&metricname=LoadRequestCount_Prometheus&Resource=deployments&Scope=namespace&Subresource=&Verb=GET

![image](https://user-images.githubusercontent.com/2559168/95988912-da121c00-0e29-11eb-801b-a1ee68e1edb0.png)

**What you expected to happen**:
GET requests should be reported with verb=GET in apiserver_request_total metric.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by wojtek-t** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by wojtek-t** [comment]
@lavalamp @deads2k @sttts - FYI

**Comment by tosi3k** [comment]
From the former run's artifacts:
```json
{
  "data": {
    "Perc50": 25,
    "Perc90": 45,
    "Perc99": 49.499999
  },
  "unit": "ms",
  "labels": {
    "Count": "355",
    "Resource": "deployments",
    "Scope": "namespace",
    "SlowCount": "0",
    "Subresource": "",
    "Verb": "GET"
  }
},
(...)
{
  "data": {
    "Perc50": 25,
    "Perc90": 45,
    "Perc99": 49.499999
  },
  "unit": "ms",
  "labels": {
    "Count": "43",
    "Resource": "deployments",
    "Scope": "namespace",
    "SlowCount": "0",
    "Subresource": "scale",
    "Verb": "GET"
  }
},
```
This is (among others) what we miss in the latter run - this is understandable from the point of view of this if condition: https://github.com/kubernetes/kubernetes/pull/93523/files#diff-c4f07ee44a4626c817dd95cf30e147a2125ea923804be5c3608fb4a845fc1c20R446.

Why do the reported GETs have `"namespace"` as the scope instead of `"resource"`, however?

**Comment by lavalamp** [comment]
cc @logicalhan 

There should probably be a unit test mapping URL paths to the expected label values.

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/kubernetes/pull/95562 is opened to fix that.
