### ISSUE TITLE
pkg/kubelet/container/helpers.go:The function  shouldRecordEvent will panic when the value of input object is nil

### ISSUE THREAD

**Issue by lala123912** [kubernetes/kubernetes#95552]
**What happened**:
The status of container always stucks in a state of "ContainerCreating".

kubelet log:
E0331 14:06:04.044168   17044 runtime.go:82] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 537686 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x354c360, 0x72a1e40)
	/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:78 +0x84
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:52 +0x7c
panic(0x354c360, 0x72a1e40)
	/opt/buildtools/godk_arm-0.9.30/goroot/go/src/runtime/panic.go:522 +0x1a0
k8s.io/kubernetes/pkg/kubelet/container.(*innerEventRecorder).shouldRecordEvent(...)
	/local/go/src/k8s.io/kubernetes/pkg/kubelet/container/helpers.go:193
k8s.io/kubernetes/pkg/kubelet/container.(*innerEventRecorder).Eventf(0x40010508f0, 0x45437c0, 0x0, 0x3d925bb, 0x7, 0x3dc4ed6, 0x16, 0x3de9361, 0x1d, 0x4000c071c0, ...)
	/local/go/src/k8s.io/kubernetes/pkg/kubelet/container/helpers.go:207 +0x5c
k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).SyncPod(0x4000c7afc0, 0x4004b5a800, 0x4004a9eea0, 0x73822d8, 0x0, 0x0, 0x4000b1e060, 0x40036daa40, 0x2, 0x2, ...)
	/local/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_manager.go:719 +0x220c
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncPod(0x4000ca0000, 0x0, 0x4004b5a800, 0x2, 0x4004a9eea0, 0x0, 0x0, 0x0, 0x4004fe7938, 0x2e965b4)
	/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1860 +0xc84
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).managePodLoop.func1(0x4004fe7d50, 0x4000bf0200, 0x40039f5cd8, 0x40008d3c80, 0x400628e280)
	/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:212 +0x3e0
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).managePodLoop(0x4000bf0200, 0x400535d0e0)
	/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:222 +0xd4
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod.func1(0x4000bf0200, 0x400535d0e0)
	/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:261 +0x58
created by k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod
	/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:259 +0x4a0

**What you expected to happen**:
file:pkg/kubelet/container/helpers.go
The function shouldRecordEvent will panic when the value of object is nil and the type is non-nil. For details, see https://golang.org/doc/faq#nil_error. Instead, we can use Reflection to avoid this risk.

**How to reproduce it (as minimally and precisely as possible)**:
deploying a container

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.15

**Comment by lala123912** [comment]
@derekwaynecarr

**Comment by SergeyKanzhelev** [comment]
Is there a code path that can pass the `object` that is typed `nil`? Or this is based on code analysis?

**Comment by lala123912** [comment]
> Is there a code path that can pass the `object` that is typed `nil`? Or this is based on code analysis?

This problem occured while deploying a container in our application.

**Comment by derekwaynecarr** [comment]
@lala123912 do you have a reproduction?

**Comment by MHBauer** [comment]
v1.15 is quite a while ago. This also looks like on arm?
I can't find a version of 1.15 that has and Eventf on kuberuntime_manager.go:719.

The most recent version has an info https://github.com/kubernetes/kubernetes/blob/v1.15.12/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L719

The helpers.go lines don't seem to match up quite right either
this one is okay https://github.com/kubernetes/kubernetes/blob/v1.15.12/pkg/kubelet/container/helpers.go#L207
this one is not https://github.com/kubernetes/kubernetes/blob/v1.15.12/pkg/kubelet/container/helpers.go#L193

**Comment by lala123912** [comment]
> @lala123912 do you have a reproduction that may have more specifics? is there a particular container runtime?

This problem occured when the container network was abnormal，and that was another problem of other component in our product which has been fixed.

**Comment by SergeyKanzhelev** [comment]
Fix for the nil check is here: https://github.com/kubernetes/kubernetes/pull/95662

We might need to analyze all code paths. If somebody has an idea for bigger refactoring to prevent these cases in the first place - let's discuss.

**Comment by dcbw** [comment]
Given the PR merged, should we close this issue?

**Comment by SergeyKanzhelev** [comment]
@lala123912 do you want to keep the issue to track cherry-picks? I don't think we can cherry pick to 1.15, do you have plans to upgrade to one of the supported versions? I think the best solution would be to fix the bug on callsite, but shouldn't be a problem to backport.

**Comment by lala123912** [comment]
> Given the PR merged, should we close this issue?

OK

**Comment by lala123912** [comment]
> supported

sorry，I have been busy with other affairs, not notice that the pr has merged,I will close this issue.
