### ISSUE TITLE
Adding multiple master to a single master cluster .  --control-plane-endpoint not specified

### ISSUE THREAD

**Issue by mseewooth** [kubernetes/kubernetes#95564]
Hello, 

I have a single k8s cluster v1.18. I wish to make that existing cluster a HA cluster with multiple masters. 
Unfortunately being newbie, i didn't flag --control-plane-endpoint while initialising the cluster. 

Can some please advise how to add the controlplaneendpoint in the kubeadm-config ? 

Thank you very much

**Comment by pacoxu** [comment]
Refer to kubeadm help docs:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join-phase/#tab-control-plane-join-4 ?

**Comment by mseewooth** [comment]
Okie solved. i just had to add the controlPlainEndpoint key in kubeadm-config 

kubectl -n kube-system get configmap kubeadm-config -o jsonpath='{.data.ClusterConfiguration}' > kubeadm.yaml
kubeadm config upload from-file --config kubeadm.yaml
