### ISSUE TITLE
Move ConfigurableFSGroupPolicy to beta

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#95589]
We need to move this field to beta in 1.20.

/sig storage

**Comment by pacoxu** [comment]
According to https://github.com/kubernetes/enhancements/pull/1879,  @jsafrane  is working on a better design on this.

**Comment by gnufied** [comment]
@pacoxu Nope. The current design is the design we are going to use to handle fsgroup. we discussed this at length in sig-storage call.

**Comment by arghya88** [comment]
@gnufied Is it okay if I make this change?
