### ISSUE TITLE
Auto scale down not sending SIGTERM signal

### ISSUE THREAD

**Issue by kpiyush17** [kubernetes/kubernetes#95584]
Hi,

I am using the https://github.com/kubernetes/autoscaler tool to do the auto-scaling of nodes. I have a golang application that uses signals to do the graceful shutdown. As the title says in case of an auto-scale down event using the tool, the application is not receiving the SIGTERM signal in case of pod deletion.
Is this expected? Is there any workaround/different signal that can be captured? I am using AWS EKS 1.15.

Thanks

**Comment by pacoxu** [comment]
The reason may be like https://github.com/kubernetes/autoscaler/blob/a80841eed5359df78c9bf806918c16af6a4aaf6d/cluster-autoscaler/cloudprovider/aws/README.md#common-notes-and-gotchas
```
By default, cluster autoscaler will not terminate nodes running pods in the kube-system namespace. You can override this default behaviour by passing in the --skip-nodes-with-system-pods=false flag.
```

Please provide some more info about the autoscale logs or environment information for further invesgating.

**Comment by kpiyush17** [comment]
@pacoxu Thanks for the reply. Can you tell me what kind of environment information you require?

**Comment by troy0820** [comment]
@kpiyush17 Could you use `preStop` in your deployment file?  I think this will help you gracefully terminate.
https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/
