### ISSUE TITLE
Report a metric for time taken to perform recursive permission change

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#95588]
As part of FSGroupPolicyChange, we need to emit a metric for time taken to perform recursive permission change.

/sig storage

**Comment by msau42** [comment]
@kubernetes/sig-storage-feature-requests

**Comment by JornShen** [comment]
Anything for help? @gnufied @msau42  @mattcary

**Comment by jsafrane** [comment]
@JornShen, a PR would be handy! There is some exploratory work how to read kubelet metrics, how to add a new metric, but the resulting code should be IMO small & easy to write. I see it's assigned to @mattcary, still, I believe he won't complain someone else doing the work.

I would re-use volume operation metric (`storage_operation_duration_seconds` and friends) and new operation there, say `volume_fsgroup_recursive_apply`, It's all in `pkg/volume/util/metrics.go`. This is a nice example how `OperationCompleteHook` is used to record `volume_delete` metrics: https://github.com/kubernetes/kubernetes/blob/f2e23afcf13fef805ad5341bd7a5625de5982d6c/pkg/controller/volume/persistentvolume/pv_controller.go#L1412-L1414

Part of that challenge could be to get `plugin_name` into `SetVolumeOwnership` that actually does chown and should record the metric.

**Comment by JornShen** [comment]
> @JornShen, a PR would be handy! There is some exploratory work how to read kubelet metrics, how to add a new metric, but the resulting code should be IMO small & easy to write. I see it's assigned to @mattcary, still, I believe he won't complain someone else doing the work.
> 
> I would re-use volume operation metric (`storage_operation_duration_seconds` and friends) and new operation there, say `volume_fsgroup_recursive_apply`, It's all in `pkg/volume/util/metrics.go`. This is a nice example how `OperationCompleteHook` is used to record `volume_delete` metrics:
> 
> https://github.com/kubernetes/kubernetes/blob/f2e23afcf13fef805ad5341bd7a5625de5982d6c/pkg/controller/volume/persistentvolume/pv_controller.go#L1412-L1414
> 
> Part of that challenge could be to get `plugin_name` into `SetVolumeOwnership` that actually does chown and should record the metric.

Thanks for reminding and guidance! 
And I would like to spend some time to learn about it. :)

**Comment by mattcary** [comment]
Sorry for the delayed response, I was OOO.

@JornShen I would be happy for you to contribute a PR! @jsafrane has given you excellent starting advice as usual.

Let me know if you plan to start a PR and/or if you need any additional help/guidance/encouragement :-)

**Comment by JornShen** [comment]
> Sorry for the delayed response, I was OOO.
> 
> @JornShen I would be happy for you to contribute a PR! @jsafrane has given you excellent starting advice as usual.
> 
> Let me know if you plan to start a PR and/or if you need any additional help/guidance/encouragement :-)

I' m Still working on in it. 
Thanks a lot!

**Comment by msau42** [comment]
Thanks @JornShen for working on this so quickly! I had a few followup comments, can you take a look?
https://github.com/kubernetes/kubernetes/pull/95866#pullrequestreview-517225836
