### ISSUE TITLE
Document info for the taint NodeWithImpairedVolumes=true:NoSchedule

### ISSUE THREAD

**Issue by kopal2212** [kubernetes/kubernetes#95597]
Hi Team,
We are running, Kubernetes on EKS v1.14 and cloud Provider AWS.
We ran into an issue where 4 out of total nodes were tainted with **NodeWithImpairedVolumes=true:NoSchedule,** 
This resulted in many pods not being scheduled, while I got the information from #55558 as to why it happens, I was unable to find this info in the official doc, it would be great if this is added to the official documentation as well, here https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/.

Let me know if this can be taken forward.
Any more information on this will be appreciated .

Thanks.

**Comment by kopal2212** [comment]
@kubernetes/sig-storage

**Comment by neolit123** [comment]
hi, this taint seems to originate from the legacy AWS provider and is not a "core" k8s taint:
https://github.com/kubernetes/kubernetes/blob/d9bb58fc49d3d4e6e816a45eb8c8ac3e146621e3/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L239-L240
with the extraction of providers to be outside of kubernetes/kubernetes it seems appropriate to not document this at k8s.io, but rather in places like the AWS provider book:
https://github.com/kubernetes/cloud-provider-aws/tree/master/docs/book

it might be more appropriate to log this ticket in https://github.com/kubernetes/cloud-provider-aws

> We are running, Kubernetes on EKS v1.14 and cloud Provider AWS.

this version is k8s is out of support, please try to upgrade to 1.17+ soon.

/sig cloud-provider
/area provider/aws
/remove-sig storage
/close

**Comment by kopal2212** [comment]
Sure, thanks for the info @neolit123
