### ISSUE TITLE
Add "Accept: */*" header to HTTP probes

### ISSUE THREAD

**Issue by fonsecas72** [kubernetes/kubernetes#95596]
**What would you like to be added**:

I would like that besides User-agent we added the Accept header as well with the "acept all" default. Just like curl does. 

**Why is this needed**:

Because it was my expectation that the probe would work similarly to a curl but is not the case.

I think more folks can hit this situation and waste some time to finally sort it out  

If this is **not** something you would like to add I would then like the docs to mention this specifically.

_
**PS:** I would love to propose the improvement my self

**Comment by thockin** [comment]
Is the goal simply to avoid tripping over servers that look for that header?

I don't think this presents any hazards - is that right?  If so, it seems like a simple PR if you want to tackle it.

/triage accepted
/kind feature

**Comment by fonsecas72** [comment]
cool! will look into it! thanks :)

**Comment by fonsecas72** [comment]
Hello @thockin sorry but be bugging you, but I have opened the PR but I had 0 response since then. I think I have met all the requirements, so I was wondering (as this is my first PR in k8s) if you could help me a bit.  Thanks anyway.
