### ISSUE TITLE
kubelet with --configure-cbr0=true failed to restart docker on systemd

### ISSUE THREAD

**Issue by bnprss** [kubernetes/kubernetes#9559]
Hi,

On https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/container_bridge.go#L57

kubelet asked for service binary to restart docker which failed on systemd powed systems (coreos).
That's an issue while docker still routing docker container on bad address until restarted.

Best regards

**Comment by roberthbailey** [comment]
This is known to not work on systemd distributions. 

@cjcullen @dchen1107

**Comment by dchen1107** [comment]
cc/ @yifan-gu

**Comment by bnprss** [comment]
By the way it works, ip on cbr0 is set if kubelet parameter is settup and docker is correctly restarted with:
		if err := exec.Command("systemctl", "restart", "docker").Run(); err != nil {

I don't know what shouldn't work.

Best regards

**Comment by yifan-gu** [comment]
@bnprss Sorry, you mean `exec.Command("systemctl", "restart", "docker").Run()` works, right?

**Comment by bnprss** [comment]
yes it's working, I made several test this moring.

**Comment by yifan-gu** [comment]
@bnprss Awesome! Would you like to send a PR on this?

**Comment by dchen1107** [comment]
I believe my pr https://github.com/kubernetes/kubernetes/pull/10312 fixed the issue for 1.0 release already. Close.
