### ISSUE TITLE
[Flaky Test][sig-storage] PVC Protection Verify that scheduling of a pod that uses PVC that is being deleted fails and the pod becomes Unschedulable

### ISSUE THREAD

**Issue by ScrapCodes** [kubernetes/kubernetes#95600]
**Which jobs are flaking**:
kind-master-parallel

**Which test(s) are flaking**:
[sig-storage] PVC Protection Verify that scheduling of a pod that uses PVC that is being deleted fails and the pod becomes Unschedulable

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#kind-master-parallel

**Reason for failure**:
```
test/e2e/storage/pvc_protection.go:143
Oct 15 07:26:34.723: While creating second pod that uses a PVC that is being deleted and that is Unschedulable
Unexpected error:
    <*errors.errorString | 0xc0021951f0>: {
        s: "pod \"pvc-tester-zq2dz\" is not Unschedulable: Gave up after waiting 5m0s for pod \"pvc-tester-zq2dz\" to be \"Unschedulable\"",
    }
    pod "pvc-tester-zq2dz" is not Unschedulable: Gave up after waiting 5m0s for pod "pvc-tester-zq2dz" to be "Unschedulable"
occurred
test/e2e/storage/pvc_protection.go:155
```

**Anything else we need to know**:
- links to go.k8s.io/triage appreciated
https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=PVC%20Protection%20Verify%20that%20scheduling%20of%20a%20pod%20that%20uses%20PVC%20that%20is%20being%20deleted%20fails%20and%20the%20pod%20becomes%20Unschedulable

- links to specific failures in spyglass appreciated

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1316636508949581824

/sig storage

**Comment by ScrapCodes** [comment]
@kubernetes/sig-storage-bugs  ping !

**Comment by ScrapCodes** [comment]
Hello @kubernetes/sig-storage-bugs , any update on this?

**Comment by msau42** [comment]
@yuga711 would you be able to look into this test flake?

**Comment by ScrapCodes** [comment]
Thank you @msau42 and @yuga711 for opting to look in.

Some of the recent failures are: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=%20PVC%20Protection%20Verify%20that%20scheduling%20of%20a%20pod%20that%20uses%20PVC%20that%20is%20being%20deleted%20fails%20and%20the%20pod%20becomes%20Unschedulable

Shows one failure on 8/11

**Comment by yuga711** [comment]
Looks like all recent failures show they are failing under azure-provider: https://testgrid.k8s.io/provider-azure-periodic#cloud-provider-azure-multiple-zones . 

The failure logs show authorization problems while attaching the disk.

```
Dec  2 03:43:32.829: INFO: At 2020-12-02 03:38:43 +0000 UTC - event for pvc-tester-dwc8l: {attachdetach-controller } FailedAttachVolume: AttachVolume.Attach failed for volume "pvc-1cb5df11-26c9-425e-8df9-8ffb4342a1c4" : rpc error: code = Unknown desc = Attach volume "/subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/kubetest-8e6b2ea3-344d-11eb-ad96-66e0f7df318d/providers/Microsoft.Compute/disks/pvc-1cb5df11-26c9-425e-8df9-8ffb4342a1c4" to instance "k8s-agentpool-26417359-vmss000000" failed with Retriable: false, RetryAfter: 0s, HTTPStatusCode: 403, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 403, RawError: {"error":{"code":"AuthorizationFailed","message":"The client 'e7810b59-9700-4905-86cb-ddeb13fb32d9' with object id 'e7810b59-9700-4905-86cb-ddeb13fb32d9' does not have authorization to perform action 'Microsoft.Compute/virtualMachineScaleSets/virtualMachines/write' over scope '/subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/kubetest-8e6b2ea3-344d-11eb-ad96-66e0f7df318d/providers/Microsoft.Compute/virtualMachineScaleSets/k8s-agentpool-26417359-vmss/virtualMachines/0' or the scope is invalid. If access was recently granted, please refresh your credentials."}}
```

@andyzhangx

**Comment by msau42** [comment]
I don't think the release team checks those jobs. Can you look at https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel-1-18/1332519126173749248?

**Comment by yuga711** [comment]
ha ok!! Thanks. Looking at the failure logs, I think the issue needs to be looked from the pod lifecycle pov. 

The test seems to be failing when it couldn't satisfy the condition at: https://github.com/kubernetes/kubernetes/blob/a744bddbf497ab718a40bee1c730e7e848e471ed/test/e2e/framework/pod/wait.go#L276

From the logs, the PVC deletion seems to have caused the expected failure during pod creation. So, the volume side logic seems ok:

```
Nov 28 03:22:47.226: INFO: At 2020-11-28 03:18:01 +0000 UTC - event for pvc-tester-vxhrs: {kubelet kind-worker2} FailedMount: Unable to attach or mount volumes: unmounted volumes=[volume1], unattached volumes=[volume1 default-token-8knjn]: error processing PVC pvc-protection-6737/pvc-protectionn4996: PVC is being deleted
```
The pod status shows `pending` as expected, but the conditions transitioned to `{PodScheduled, True}` where as the code above expects `{PodScheduled, false}`.

```
3:22:47.229: INFO: pvc-tester-vxhrs  kind-worker2  Pending         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2020-11-28 03:17:46 +0000 UTC  } 
{Ready False 0001-01-01 00:00:00 +0000 UTC 2020-11-28 03:17:46 +0000 UTC ContainersNotReady containers with unready status: [write-pod]} 
{ContainersReady False 0001-01-01 00:00:00 +0000 UTC 2020-11-28 03:17:46 +0000 UTC ContainersNotReady containers with unready status: [write-pod]} 
{PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2020-11-28 03:17:46 +0000 UTC  }]
```

**Comment by thejoycekung** [comment]
3 flakes recently:
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1357420032954470400
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1357481408146182144
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1359691802075992064

**Comment by yuga711** [comment]
The test failures are due to pod scheduling states. 
@msau42 do you know who can help look at the pod state transition logic?

**Comment by msau42** [comment]
Looking at https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1359691802075992064, the test seems to have failed in the very beginning when we're setting up the test case with a Pod and PVC:

```
ï¿½[1mSTEPï¿½[0m: Creating a PVC
Feb 11 02:56:12.129: INFO: Default storage class: "standard"
Feb 11 02:56:12.129: INFO: Warning: Making PVC: VolumeMode specified as invalid empty string, treating as nil
ï¿½[1mSTEPï¿½[0m: Creating a Pod that becomes Running and therefore is actively using the PVC
Feb 11 03:01:12.169: FAIL: While creating pod that uses the PVC or waiting for the Pod to become Running
Unexpected error:
    <*errors.errorString | 0xc002ea4240>: {
        s: "pod \"pvc-tester-bwsgk\" is not Running: timed out waiting for the condition",
    }
    pod "pvc-tester-bwsgk" is not Running: timed out waiting for the condition
occurred
```

It seems like the error is due to provisioning failure by the storage backend:
```
Feb 11 03:01:12.182: INFO: At 2021-02-11 02:56:12 +0000 UTC - event for pvc-protection4m7hd: {rancher.io/local-path_local-path-provisioner-78776bfc44-wvjv7_aadf70c2-f042-4fb0-9ed8-dd3acad54057 } Provisioning: External provisioner is provisioning volume for claim "pvc-protection-9726/pvc-protection4m7hd"
Feb 11 03:01:12.182: INFO: At 2021-02-11 02:58:13 +0000 UTC - event for pvc-protection4m7hd: {rancher.io/local-path_local-path-provisioner-78776bfc44-wvjv7_aadf70c2-f042-4fb0-9ed8-dd3acad54057 } ProvisioningFailed: failed to provision volume with StorageClass "standard": failed to create volume pvc-00c73ab7-3beb-494e-b5f3-d85346c31b86: create process timeout after 120 seconds
Feb 11 03:01:12.182: INFO: At 2021-02-11 02:58:15 +0000 UTC - event for pvc-protection4m7hd: {rancher.io/local-path_local-path-provisioner-78776bfc44-wvjv7_aadf70c2-f042-4fb0-9ed8-dd3acad54057 } ProvisioningFailed: failed to provision volume with StorageClass "standard": failed to create volume pvc-00c73ab7-3beb-494e-b5f3-d85346c31b86: pods "create-pvc-00c73ab7-3beb-494e-b5f3-d85346c31b86" not found
```

/assign @BenTheElder
to help take a look. This seems specific to the storage provider used in kind, not a general k8s issue.

**Comment by BenTheElder** [comment]
I think this is an I/O throttling issue in CI. Aaron and I are intermittently working on mitigations for the CI.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/k8s.io/issues/1187

**Comment by mkorbi** [comment]
seems solved
