### ISSUE TITLE
Kubernetes + iptables _strimzi operator for kafka

### ISSUE THREAD

**Issue by slaurencelle** [kubernetes/kubernetes#95616]
Hello,
I like to know how does iptables work in kubernetes versus strimzi operator for kafka.
When deploying all the different pod include with strimzi for kafka , i got strange comportement in iptables, i see that those kind of messages while the pod is getting deploy.

REJECT     tcp  --  anywhere             10.99.200.5          /* kafka/kafka-connect-cluster-connect-api:rest-api has no endpoints */ tcp dpt:us-srv reject-with icmp-port-unreachable

it can take around 5 to 6 restart before iptables let it go throught and that the pod is in the running state

What can cause this ?

Thanks in advance for the explanation.

Stephane

**Comment by neolit123** [comment]
hi, this appears to be a request for support. please try the support channels instead:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
