### ISSUE TITLE
Capability set incorrectly. CAP_NET_RAW should be NET_RAW.

### ISSUE THREAD

**Issue by MHBauer** [kubernetes/kubernetes#95612]
**Which jobs are failing**:
ci-cri-containerd-node-e2e

**Which test(s) are failing**:
Summary API [NodeConformance] when querying /stats/summary should report resource usage through the stats api

**Since when has it been failing**:
2020 10-12 09:04 PDT
Since https://github.com/kubernetes/kubernetes/pull/95321

**Testgrid link**:
https://testgrid.k8s.io/sig-node-containerd#node-e2e

**Reason for failure**:
Capability set incorrectly. CAP_NET_RAW should be NET_RAW.

I1013 18:39:19.058] Oct 13 18:10:51.403: INFO: At 2020-10-13 18:09:34 +0000 UTC - event for stats-busybox-0: {kubelet tmp-node-e2e-033aeade-cos-81-12871-1210-0} Failed: Error: failed to create containerd task: OCI runtime create failed: container_linux.go:370: starting container process caused: unknown capability "CAP_CAP_NET_RAW": unknown 

**Anything else we need to know**:
I have no idea where this is documented. It's a best guess.

**Comment by MHBauer** [comment]
it's a node_e2e test so
/sig node

**Comment by MHBauer** [comment]
Seems like there's some dispute on who is doing the correct thing.

**Comment by lala123912** [comment]
I would like to have a try.

**Comment by BenTheElder** [comment]
@lala123912 please see discussion in https://github.com/kubernetes/kubernetes/pull/95613 https://github.com/kubernetes/kubernetes/issues/95612#issuecomment-709551750
