### ISSUE TITLE
Make CSIDriver.spec.podInfoOnMount mutable

### ISSUE THREAD

**Issue by chrishenzie** [kubernetes/kubernetes#95627]
**What would you like to be added**:

I would like to make the `CSIDriver.spec.podInfoOnMount` field mutable.

**Why is this needed**:

Because there are CSI drivers that do not yet support this feature, but will in the near future (like the [AWS EFS CSI driver](https://github.com/kubernetes-sigs/aws-efs-csi-driver)). Allowing users to update this field when they upgrade their CSI driver without having to delete and recreate the `CSIDriver` object is more convenient.

**Comment by chrishenzie** [comment]
@wongma7 can you confirm if we will need `CSIDriver.spec.podInfoOnMount = true` for supporting IAM access point mounts?

**Comment by wongma7** [comment]
I am not sure, technically it is possible already if the csi driver gets creds or inherits node instance creds. If you mean using pod creds, then I think my preference is waiting for https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1855-csi-driver-service-account-token
