### ISSUE TITLE
[service-proxy] and [kube-proxy] tags

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#95633]
This might be best written out in a KEP since its a holistic change to the sig-net testing metadata, but could also do it in bite size chunks.

**What would you like to be added**:

ginkgo skip/focus metadata strings or tags which identify:
- service proxy tests,  
- kube proxy tests, 

for all of the current sig-network tests (there are roughly 157 current sig-net tests, 4 are labelled with kube-proxy, 56 are labelled with Services, and 302 in total that are "Conformance" tests.  I think about 1/3 or so sig-network tests rely on a svc proxy . 

**why this is needed**

Right now we have 3 categories of service proxy tests:

- things that are specific to kube-proxy, for example, tests in service.go which literally turn it off.
- things that depend on load balancers working properly (for example the granular tests in networking.go, which will not succeed unless all nodes behind a SEP service a request at least once)
- Conformance tests which, as an implementation detail, rely on service proxying to work properly

Lets make sure that
-  folks swapping out kube-proxy for a generic service proxy have. a clear ginkgo tag / string to filter on, by labelling "svc proxy" tests 
- folks who DONT want to test kube-proxy can filter it out explicitly as well, by labelling all "kube-proxy" tests 

1) i.e. a network vendor w/ a kube-proxy alternative, might run

```
--e2e-focus="[service-proxy]" --e2e-skip="kube-proxy"
```

2) someone who just modified kube-proxy to use a new ipvs mechanism, might use

```
--e2e-focus="[kube-proxy]"
```

3) someone wanting to run all conformance tests which DO NOT rely on a service proxy (i.e. maybe to diagnose a cluster with networking flakes, and determine wether or not svc proxy are to blame) might run

```
--e2e-focus="Conformance" --e2e-skip="service-proxy"
```

This is mainly needed because many emerging solutions and alternatives to kube-proxy (cillium being an increasingly popular one), but also, some folks have suggested using SRV records for services and so on, are getting more popular, and so we want to be able to document which tests are important for which vendors over time.

**Comment by jayunit100** [comment]
@cmluciano iirc you were working on this right ? i saw a flyby pr

**Comment by aojea** [comment]
@jayunit100 @cmluciano should we aggregate the info in one and close the other, this seems a duplicate of https://github.com/kubernetes/kubernetes/issues/95368

**Comment by cmluciano** [comment]
Ya we can aggregate these issues

/triage accepted

**Comment by aojea** [comment]
/close
the e2e tests that are kube-proxy specific are correctly tagged.
Services is a core API of kubernetes, hence is an inseparable part, not only from networking, most of the e2e tests use Services in one way or another.
