### ISSUE TITLE
More comprehensive test for mapping url paths to metrics labels

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#95636]
In https://github.com/kubernetes/kubernetes/issues/95556 we discovered a bug where kube-apiserver metrics were being incorrectly reported (GET vs LIST problem).
In https://github.com/kubernetes/kubernetes/pull/95562 this was addressed together with test exercising that proper metrics are exposed.

However, this test isn't ideal because if params wouldn't be swapped, it wouldn't catch them.
We should ideally develop a lower-level unit test for mapping url paths to exact values of labels/parameters.

@logicalhan 

/sig apimachinery

**Comment by fedebongio** [comment]
@wojtek-t are you planning on sending a fix for this one too? Thanks!

**Comment by wojtek-t** [comment]
Not very soon - if someone else could help with it, it would be great.

**Comment by leilajal** [comment]
cc @logicalhan
