### ISSUE TITLE
Fix internal loadbalancer configuration failure when truncated FrontendIPConfigName ended with special char

### ISSUE THREAD

**Issue by zqingqing1** [kubernetes/kubernetes#95663]
**What happened**:
when getting FrontendIPConfigName and subnet is too long, we truncated it but when it is ended with "." special char, controller manager will errr out with "invalid resource name"
```
 "code": "InvalidResourceName",^M
    "message": "Resource name ae4991b74c36845c7a88962364d9d14b-cus_pd1_subnet_hosting_aks_ml_staging_10.194.2. is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character
or with '_'. The name may contain word characters or '.', '-', '_'.",^M
    "details": []^M
```

**What you expected to happen**:
We shouldn't ended with special char

**How to reproduce it (as minimally and precisely as possible)**:
Use a subnet that has long name (>70 charactors) and with special "." within it and create ILB service.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
hi, i don't know where FrontendIPConfigName is coming from, but this value is too long. it should be <80 characters.

please try figuring out the reason for what / who is setting such a long value.

this does not appear to be a bug in core Kubernetes and the following requirement will not be changed:
> name can be up to 80 characters long. It must begin with a word character, and it must end with a word character
or with '_'. The name may contain word characters or '.', '-', '_'.",^M

/close
/kind support
/remove-kind bug
