### ISSUE TITLE
gcr.io/google-containers/kube-apiserver:v1.18.9 not found

### ISSUE THREAD

**Issue by zrks** [kubernetes/kubernetes#95670]
Hi,

hopefully I can get some support here - currently trying to deploy k8s cluster via kubespray v2.14.1.
Seems that latest k8s images are not available:
└─ $ ▶ docker image pull gcr.io/google-containers/kube-apiserver:v1.18.9 Error response from daemon: manifest for gcr.io/google-containers/kube-apiserver:v1.18.9 not found: manifest unknown: Failed to fetch "v1.18.9" from request "/v2/google-containers/kube-apiserver/manifests/v1.18.9".

What can we do about this issue? Is there a way to request these versions to be available on gcr and how?

**Comment by troy0820** [comment]
@zrks Have you tried `docker pull k8s.gcr.io/kube-apiserver:v1.18.9` 
I've tried this in a [katacode playground](https://www.katacoda.com/courses/kubernetes/playground) and it worked. 

Related issue: https://github.com/kubernetes/kubernetes/issues/94013

**Comment by neolit123** [comment]
> k8s.gcr.io/kube-apiserver:v1.18.9

yes please use the new format.

this was announced a long time ago and the change was scheduled for March 2020, but was delayed.
https://github.com/kubernetes/release/issues/270#issuecomment-594233197

/sig release
/close
