### ISSUE TITLE
Windows containers restart in vSphere cluster

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#95682]
**What happened**:
Windows Containers are restarting in vSphere cluster on Windows 1909 host with the following error:

```
failed to shutdown container: container 54c04719fab4bed4e7a791b3c57e6a0ab4308c5aac3843221fcf79e96d855081 encountered an error during hcsshim::System::Shutdown: failure in a Windows system call: The remote procedure call failed and did not execute. (0x6bf): subsequent terminate failed container 54c04719fab4bed4e7a791b3c57e6a0ab4308c5aac3843221fcf79e96d855081 encountered an error during hcsshim::System::Terminate: failure in a Windows system call: The remote procedure call failed and did not execute. (0x6bf)
```

**What you expected to happen**:
Windows Containers are running normally.

**How to reproduce it (as minimally and precisely as possible)**:
Add a Windows 1909 host to existing OpenShift cluster with ovn-kubernetes

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.19.0+f5121a6
- Cloud provider or hardware configuration: vSphere 6.7
- OS (e.g: `cat /etc/os-release`): Microsoft Windows 1909 
- Kernel (e.g. `uname -a`): 10.0.18363.1082 - This has custom VXLAN patch enabled
- Install tools: OpenShift installer
- Network plugin and version (if this is a network-related bug): ovn-kubernetes with hybrid-overlay enabled
- Others:

**Comment by ravisantoshgudimetla** [comment]
Network logs:[server.tar.gz](https://github.com/kubernetes/kubernetes/files/5398055/server.tar.gz)

System events log- [system.tar.gz](https://github.com/kubernetes/kubernetes/files/5398071/system.tar.gz)

[Repo](https://github.com/microsoft/SDN/tree/master/Kubernetes/windows/debug)

**Comment by ravisantoshgudimetla** [comment]
cc @aravindhp @gmarkley-VI @marosset @ambguo @JocelynBerrendonner

**Comment by marosset** [comment]
@ravisantoshgudimetla can you create a new issue at https://github.com/microsoft/Windows-Containers/issues ?
Problems at the HCS layer will have more tracking there since that repo gets triaged by the Windows kernel/container platform team.

**Comment by ravisantoshgudimetla** [comment]
> @ravisantoshgudimetla can you create a new issue at https://github.com/microsoft/Windows-Containers/issues ?
> Problems at the HCS layer will have more tracking there since that repo gets triaged by the Windows kernel/container platform team.

Thank you @marosset. I created issue there. Let me know if you want me to close this issue.

**Comment by brasmith-ms** [comment]
Hi all, this issue has been resolved in [https://github.com/microsoft/Windows-Containers/issues/68](https://github.com/microsoft/Windows-Containers/issues/68). If there are no further issues, I believe this ticket can be closed.

**Comment by ravisantoshgudimetla** [comment]
Closing this issue as @brasmith-ms suggested
