### ISSUE TITLE
Can't shrink by adding label pods when stateless application shrink

### ISSUE THREAD

**Issue by HaonanFeng** [kubernetes/kubernetes#95688]
**What happened**:
Can't shrink by adding label pods when stateless application shrink

**What you expected to happen**:
When deleting pods, add pods to be sorted by labels,  when shrinking, the labeled pods will be deleted first.

**How to reproduce it (as minimally and precisely as possible)**:
Remove pod when stateless application shrink

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.15

**Comment by liggitt** [comment]
Thanks for the feature request. Pod-level control over scale down is already proposed/tracked in https://github.com/kubernetes/enhancements/pull/1888 and https://github.com/kubernetes/enhancements/pull/1828

/close
as duplicate
