### ISSUE TITLE
Need a way to temporarily stop a deployment

### ISSUE THREAD

**Issue by bmaehr** [kubernetes/kubernetes#95695]
**What happened**:

Like described in #28603 I'm searching for a way to temporarily stop a deployment. As far as i understood it should be possible to scale down the pods to 0.

I have done this with the command
`kubectl scale deploy my-application --replicas=0`

The deploment has been scaled down to 0 like expected, but it started to scale up immediately to the minimum availability after that.

That happens to deployments with and without auto scaling active. 

**What you expected to happen**:

I expected the deployment to to stay at 0 replicas until I change the number of replicas again. 

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-gke.20", GitCommit:"0ac5f81eecab42bff5ef74f18b99d8896ba7b89b", GitTreeState:"clean", BuildDate:"2020-09-09T00:48:20Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Google Cloud

**Comment by bmaehr** [comment]
@liggitt Did I understand #28603 wrong?

**Comment by liggitt** [comment]
do you have a HPA also controlling the scale of the deployment? I thought this was asking for a new feature, not reporting an issue with an existing feature

**Comment by bmaehr** [comment]
In fact I'm not sure, but I think yes. Auto scaling is active and as far as I understood, auto scaling is done by HPA. But perhaps I just understand it wrong.

**Comment by liggitt** [comment]
is HPA pointing at the deployment or the replicaset?

**Comment by liggitt** [comment]
moved back from feature to support until the scenario is clearer

**Comment by bmaehr** [comment]
Thank you for your patience

As far as I understood it is scaling the deployment.
 
This is the output from kubectl from the application i tried to scale down to 0. It was scaled down but scaled up to 2 after some seconds again:
```
$ kubectl describe hpa my-application
Name:                                                  my-application
Namespace:                                             default
Labels:                                                <none>
Annotations:                                           helm.fluxcd.io/antecedent: default:helmrelease/my
CreationTimestamp:                                     Tue, 12 May 2020 11:52:15 +0200
Reference:                                             Deployment/my-application
Metrics:                                               ( current / target )
  resource memory on pods:                             279810048 / 1000Mi
  resource cpu on pods  (as a percentage of request):  1% (5m) / 80%
Min replicas:                                          2
Max replicas:                                          4
Deployment pods:                                       2 current / 2 desired
Conditions:
  Type            Status  Reason            Message
  ----            ------  ------            -------
  AbleToScale     True    ReadyForNewScale  recommended size matches current size
  ScalingActive   True    ValidMetricFound  the HPA was able to successfully calculate a replica count from memory resource
  ScalingLimited  True    TooFewReplicas    the desired replica count is more than the maximum replica count
Events:           <none>

```

**Comment by krmayankk** [comment]
the describe clearly shows HPA controlling the deployment object, in which case this is expected behavior . There was some discussion long back that replica count 0 would disable it, but seems like the latest implementation requires a `selectPolicy` to disable the HPA as documented [here](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#example-disable-scale-down)
