### ISSUE TITLE
apiserver bound to 0.0.0.0 fails when applying kernel parameter disable_ipv6 at runtime

### ISSUE THREAD

**Issue by ZaphodB** [kubernetes/kubernetes#95706]
**What happened**:

Upon deactivating IPv6 via kernel sysctl
```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
```

thus going from
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
```
to
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
```

kube-apiserver becomes unresponsive to requests and loops the following error messages:
```
E1019 14:47:23.291830       1 reflector.go:126] k8s.io/kube-aggregator/pkg/client/informers/internalversion/factory.go:117: Failed to list *apiregistration.APIService: Get https://[::1]:6443/apis/apiregistration.k8s.io/v1/apiservices?limit=500&resourceVersion=0: dial tcp [::1]:6443: connect: network is unreachable
E1019 14:47:23.294449       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.MutatingWebhookConfiguration: Get https://[::1]:6443/apis/admissionregistration.k8s.io/v1beta1/mutatingwebhookconfigurations?limit=500&resourceVersion=0: dial tcp [::1]:6443: connect: network is unreachable
E1019 14:47:23.296783       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Endpoints: Get https://[::1]:6443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp [::1]:6443: connect: network is unreachable
E1019 14:47:23.299011       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.ResourceQuota: Get https://[::1]:6443/api/v1/resourcequotas?limit=500&resourceVersion=0: dial tcp [::1]:6443: connect: network is unreachable
E1019 14:47:23.303222       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.PersistentVolume: Get https://[::1]:6443/api/v1/persistentvolumes?limit=500&resourceVersion=0: dial tcp [::1]:6443: connect: network is unreachable
E1019 14:47:23.305711       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.PriorityClass: Get https://[::1]:6443/apis/scheduling.k8s.io/v1beta1/priorityclasses?limit=500&resourceVersion=0: dial tcp [::1]:6443: connect: network is unreachable
E1019 14:47:23.308113       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Node: Get https://[::1]:6443/api/v1/nodes?limit=500&resourceVersion=0: dial tcp [::1]:6443: connect: network is unreachable
E1019 14:47:23.311567       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.StorageClass: Get https://[::1]:6443/apis/storage.k8s.io/v1/storageclasses?limit=500&resourceVersion=0: dial tcp [::1]:6443: connect: network is unreachable
E1019 14:47:23.313992       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.ValidatingWebhookConfiguration: Get https://[::1]:6443/apis/admissionregistration.k8s.io/v1beta1/validatingwebhookconfigurations?limit=500&resourceVersion=0: dial tcp [::1]:6443: connect: network is unreachable
E1019 14:47:23.314539       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Service: Get https://[::1]:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp [::1]:6443: connect: network is unreachable
E1019 14:47:23.315964       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.PodSecurityPolicy: Get https://[::1]:6443/apis/policy/v1beta1/podsecuritypolicies?limit=500&resourceVersion=0: dial tcp [::1]:6443: connect: network is unreachable
E1019 14:47:23.319747       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Secret: Get https://[::1]:6443/api/v1/secrets?limit=500&resourceVersion=0: dial tcp [::1]:6443: connect: network is unreachable
E1019 14:47:23.327160       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.ClusterRoleBinding: Get https://[::1]:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?limit=500&resourceVersion=0: dial tcp [::1]:6443: connect: network is unreachable
E1019 14:47:23.329666       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.ClusterRole: Get https://[::1]:6443/apis/rbac.authorization.k8s.io/v1/clusterroles?limit=500&resourceVersion=0: dial tcp [::1]:6443: connect: network is unreachable
E1019 14:47:23.331849       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Role: Get https://[::1]:6443/apis/rbac.authorization.k8s.io/v1/roles?limit=500&resourceVersion=0: dial tcp [::1]:6443: connect: network is unreachable
E1019 14:47:23.334168       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Pod: Get https://[::1]:6443/api/v1/pods?limit=500&resourceVersion=0: dial tcp [::1]:6443: connect: network is unreachable
E1019 14:47:23.339127       1 reflector.go:126] k8s.io/apiextensions-apiserver/pkg/client/informers/internalversion/factory.go:117: Failed to list *apiextensions.CustomResourceDefinition: Get https://[::1]:6443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions?limit=500&resourceVersion=0: dial tcp [::1]:6443: connect: network is unreachable
```

```
# grep bind /etc/kubernetes/manifests/kube-apiserver.yaml
    - --bind-address=0.0.0.0
```

apiserver will be able to answer to requests again upon process restart.

**What you expected to happen**:

The apiserver could recover from this failure mode by itself without the need for a restart it for example by falling back to 0.0.0.0 when the connection to ::1 repeatedly fails with network unreachable. This might be helpful to people having to disable IPv6 for compliance reasons.

**How to reproduce it (as minimally and precisely as possible)**:

Set up new k8s cluster with kubespray using the defaults (i.e. apiserver bind to 0.0.0.0) where IPv6 is not explicitly disabled, then setting
```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
```
kernel parameters via sysctl without rebooting the system.
Then trigger an event such as killing a pod or starting a new one.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.6
- Cloud provider or hardware configuration: VMware VM 4GB RAM, 20GB Disk
- OS (e.g: `cat /etc/os-release`): CentOS Linux release 7.8.2003 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-1127.19.1.el7.x86_64
- Install tools: kubespray commit ce0d111d ~v1.14.6 + docker 18.09 
- Network plugin and version (if this is a network-related bug): calico/node:v3.4.0
- Others:

**Comment by fedebongio** [comment]
We passed again on this one, nothing yet from sig network

**Comment by aojea** [comment]
There are several things in place here, let's take a simple example with this golang server:

```go
package main

import (
    "fmt"
    "net/http"
)

func main() {
    http.HandleFunc("/", HelloServer)
    http.ListenAndServe("0.0.0.0:8080", nil)
}

func HelloServer(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintf(w, "Hello, %s!", r.URL.Path[1:])
}
```

if we run the server `go run server.go`, we can see that it binds an IPv6 socket

```
[vagrant@localhost ~]$ ss -apn | grep 8080
tcp    LISTEN     0      128    [::]:8080               [::]:*                   users:(("server",pid=2758,fd=3))
[vagrant@localhost ~]$ lsof -P -n -i :8080
COMMAND  PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
server  2758 vagrant    3u  IPv6  25968      0t0  TCP *:8080 (LISTEN)
```

An IPv6 socket is able to handle both IPv4 and IPv6 families, more details https://man7.org/linux/man-pages/man7/ipv6.7.html. 
>    IPv4 connections can be handled with the v6 API by using the
  v4-mapped-on-v6 address type; thus a program needs to support only
  this API type to support both protocols. 

If we disable now IPv6:

```
sudo sysctl net.ipv6.conf.default.disable_ipv6=1
sudo sysctl net.ipv6.conf.all.disable_ipv6=1
```

The server keeps running:
```
lsof -P -n -i :8080
COMMAND  PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
server  2758 vagrant    3u  IPv6  25968      0t0  TCP *:8080 (LISTEN)
```

and working but ... only for IPv4,
```
[vagrant@localhost ~]$ echo GET | nc 127.0.0.1 8080
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Connection: close
```

because you have disabled IPv6:
```
[vagrant@localhost ~]$ echo GET | nc ::1 8080
Ncat: Network is unreachable.
```

so, based in your errors the problem does not seem to be the server
```
E1019 14:47:23.315964       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.PodSecurityPolicy: Get https://[::1]:6443/apis/policy/v1beta1/podsecuritypolicies?limit=500&resourceVersion=0: dial tcp [::1]:6443: connect: network is unreachable
```
is that those connections are trying to use an IPv6 address and IPv6 is disabled.

I personally don't think that this scenario should be handled by the apiserver or any kubernetes component, since you are doing a conscious decision to disable IPv6 you can disable it before running any component.
Another option is to be more specific on the addressing and not use 0.0.0.0, since in golang 0.0.0.0 and :: means bind to all addresses and all families https://github.com/kubernetes/kubernetes/issues/88458

**Comment by ZaphodB** [comment]
> I personally don't think that this scenario should be handled by the apiserver or any kubernetes component, since you are doing a conscious decision to disable IPv6 you can disable it before running any component.

I think that is a fair assessment and basically i wanted to let you know of this issue so it is documented as i was not able to find any previous reports or information on the issue on my search for it.
Sadly i am unaware of any part of the documentation that would be fitting for a short remark on this however i feel that more people might walk into this in the future and since it effectively shuts down the whole cluster if the change is performed live on all master nodes at once it might warrant a short word of advise somewhere.

**Comment by aojea** [comment]
> I think that is a fair assessment and basically i wanted to let you know of this issue so it is documented as i was not able to find any previous reports or information on the issue on my search for it.
Sadly i am unaware of any part of the documentation that would be fitting for a short remark on this however i feel that more people might walk into this in the future and since it effectively shuts down the whole cluster if the change is performed live on all master nodes at once it might warrant a short word of advise somewhere.

Thanks for reporting and your comments, I´m going to close it to avoid the bot closing it as stale

It is true that is not documented, but this falls more into the system/networking administration/installation area than into the Kubernetes project. In this case the problem relies on configuring the cluster to use an IPv6, in this case `::1` and then disabling IPv6, so nobody can no longer reach `::1` 

/close
