### ISSUE TITLE
scheduler: provide an option to not shuffle internal node index when using percentageOfNodesToScore

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#95709]
I got some requirement from users that run serverless workloads, who cares a lot about minimizing the running machines to reduce cost.

They've started to use the `NodeResourcesMostAllocated` Score plugin (just as AutoScaler did) to replace the default `NodeResourcesLeastAllocated` plugin, however, it seems not to be good enough. The problem is that when using `percentageOfNodesToScore`, internally scheduler maintains a node index to shuffle the starting searching position everytime it starts the Scoring. Suppose we have 500 nodes that passed Filtering phase, and due to `percentageOfNodesToScore`, we only Score 100 nodes. When scheduling Pod1, the searching scope is from [node1, node2, ..., node100]; while when scheduling Pod2, the scope switches to [node101, node102, ..., node200] - which sorts of balances the workloads across the cluster, and it disobeys the user's desire to pack workloads onto minimum machines as possible.

So I'm proposing to provide an option to disable shuffling the internal node's index, and if we got a consensus, the implementation may need to correlate with #93270 as we may consider making it a profile level parameter.

/sig scheduling
/kind feature

**Comment by SataQiu** [comment]
/cc 
I'm willing to help with this if needed.

**Comment by ahg-g** [comment]
Starting from index 0 will be expensive on the long run because the first nodes will be full, but still being evaluated in every cycle. 

I am wondering if node order should be a plugin; for bin-packing, the nodes would be ordered by how full they are. If we don't want to go that far, instead of resetting the index every time, may be start from the last selected node.

**Comment by adtac** [comment]
At the risk of stating the obvious, would setting PercentageOfNodesToScore to 100% solve this for the user? Performance will take a hit, of course, but it might be worth benchmarking for their use-case.

>So I'm proposing to provide an option to disable shuffling the internal node's index, and if we got a consensus, the implementation may need to correlate with #93270 as we may consider making it a profile level parameter.

I propose making this more generic. Instead of just disabling shuffling, we can make the starting index an enum of three values:

1. round robin, like we currently do
2. always start at zero
3. random index

The #3 option need not be added as a part of this issue, but making it an enum will make it more extensible in the future.

>Starting from index 0 will be expensive on the long run because the first nodes will be full, but still being evaluated in every cycle.

Wouldn't those nodes be filtered out in the filter phase? If they cannot fit the pod, I don't see why they'd be a part of the scoring phase.

**Comment by ahg-g** [comment]
> Wouldn't those nodes be filtered out in the filter phase? If they cannot fit the pod, I don't see why they'd be a part of the scoring phase.

They would, but we are still paying the overhead of evaluating them in the filter phase.

**Comment by Huang-Wei** [comment]
> Starting from index 0 will be expensive on the long run because the first nodes will be full, but still being evaluated in every cycle.

It's a fair point. But even with current logic, we cannot ensure everytime the searching scope (starting at a shuffled `nodeIndex`) is optimal - it's random, but agnostic. So overall I think the overhead is acceptable, and can be mitigated by the automatic-exposed `{Memory|CPU|Disk}Pressure` taint - i.e., nodes that are out of resource will return at the very early `TaintToleration` Filter plugin and hence won't cost much.

Another aspect, as I mentioned earlier, is to make this option in profile level, so it won't impact the global (or other profiles) behavior. This is similar to the discussion we had in profile-level percentageOfNodesToScore.

> I am wondering if node order should be a plugin; for bin-packing, the nodes would be ordered by how full they are.

I'm not sure it's practical enough as (1) the top ordered nodes may fail at the Filter phase due to capacity, and (2) we need to figure out the number of nodes to order.

> I propose making this more generic. Instead of an option to just disable shuffling, we can create an enum option for the starting index:
> 
> 1. round robin, like we currently do
> 2. always start at zero
> 3. random index

This makes sense to me. Enum can be more extensible than bool.

> At the risk of stating the obvious, would setting PercentageOfNodesToScore to 100% solve this for the user? Performance will take a hit, of course, but it might be worth benchmarking for their use-case.

Using a non-100% PercentageOfNodesToScore is the prerequisite of this issue. If the user goes with 100%, they can always get a consistent behavior and hence they don't need this proposal at all.

**Comment by alculquicondor** [comment]
It sounds like moving percentagesOfNodesToScore to the profile is the best first step. Then we can re-evaluate if more is needed.

**Comment by Huang-Wei** [comment]
> It sounds like moving percentagesOfNodesToScore to the profile is the best first step. Then we can re-evaluate if more is needed.

Agree.

**Comment by alculquicondor** [comment]
@Huang-Wei do you have any updates from your users?

**Comment by Huang-Wei** [comment]
@alculquicondor I can touch base with them again, but I think their requirement is clear here. Do you plan to get it implemented along with v1beta2?

**Comment by alculquicondor** [comment]
I was not planing to, as per https://github.com/kubernetes/kubernetes/issues/95709#issuecomment-714515168
