### ISSUE TITLE
Support for split-horizon DNS setups, DNS aliases and/or services with dotted names

### ISSUE THREAD

**Issue by segevfiner** [kubernetes/kubernetes#95712]
**What would you like to be added**:
Support in Kubernetes to remap/alias dotted DNS names inside the cluster. Either via allowing dotted service names (Or a new property to allow a service to have a dotted name in DNS), some new dedicated resource for such aliases, or some documented way to customize CoreDNS config that can be done automatically without conflicts by tools like helm, without needing to develop custom scripts to patch the single cluster wide configmap/file of CoreDNS.

**Why is this needed**:
A long standing issue with Kubernetes is how to externally access and expose pods that depend on their own DNS FQDN for either internal communication, or in generated URLs. Examples include:
* docker-registry (AKA distribution) &ndash; That uses its DNS name as part of the image name (e.g. `localhost:5000/foo/bar`), which makes it troublesome to expose both inside and outside a cluster, and led to hacks like the minikube [registry-aliases](https://github.com/kubernetes/minikube/tree/master/deploy/addons/registry-aliases) addon (It patches the CoreDNS config of the cluster).
* MongoDB &ndash; which ended up developing their own custom split horizon DNS setup by using TLS SNI, for their enterprise Kubernetes operator. (P.S. The code of it exists in the open source version too, but not documented ATM), so that MongoDB can serve a different set of hosts for communication outside the cluster.
* Elasticsearch &ndash; which requires you to disable sniffing (Sniffing is when the Elasticsearch client auto detects the available nodes by querying one of the nodes for them, which ends up returning cluster internal DNS names) and rely on external load balancing.
* Any HTTP service that needs to generate absolute redirects or URLs, if the service isn't written to be smart about reconstructing the URL based on HTTP headers like `Host` (Requires careful validation of them, see [Django - Host Header Validation](https://docs.djangoproject.com/en/3.1/topics/security/#host-header-validation)). For example: [Gitea's](https://gitea.io/) LFS server.

Using the public DNS inside the cluster, which resolves to a public IP, for such externally exposed services is not always possible and can often lead to unnecessary trips around the internet via load balancers which can degrade performance severely.

By supporting remapping such names, one can configure the service to use the same public name internally and externally. Having it remapped inside the cluster to the appropriate internal Kubernetes service, and resolvable externally using whatever public DNS setup was used for it.

Whether that's the best way to handle this issue is something that remains to be discussed, but a better "standard" solution ("Best Practice") will surely help as without it different services are each developing their own custom way of handling such issues which makes life hard for everyone that uses them in Kubernetes.

**Comment by jayunit100** [comment]
@distributethe6ix

**Comment by segevfiner** [comment]
Plain Docker supports this via [`--network-alias`](https://docs.docker.com/engine/reference/run/#network-settings) or [`aliases`](https://docs.docker.com/compose/compose-file/compose-file-v2/#aliases) in `docker-compose`. It simply allows dotted names there.

**Comment by aojea** [comment]
> but a better "standard" solution ("Best Practice") 

@chrisohaver is this something you can help us here?

**Comment by chrisohaver** [comment]
Sure. I think a good solution could be to define a CRD that holds alias names for Services, and a new plugin in CoreDNS that monitors the Custom Resource. I can propose something in more detail if that sounds reasonable. Should this be in the form of a KEP?

**Comment by aojea** [comment]
> Sure. I think a good solution could be to define a CRD that holds alias names for Services, and a new plugin in CoreDNS that monitors the Custom Resource. I can propose something in more detail if that sounds reasonable. Should this be in the form of a KEP?

let me summon @thockin , there was another request recently in [sig-network about DNS (unrelated to this)](https://groups.google.com/g/kubernetes-sig-network/c/JjonaXdWAr4/m/oydqaPS5AQAJ) and maybe is interesting explore this CRD via with DNS (ala service-api maybe?)

**Comment by thockin** [comment]
There are two distinct problems here. 

1) using a different, more flexible (e.g. allows dots) DNS schema for a different zone
2) returning different results based on client (split horizon)

I am not sure I understand the requirements on the second part well enough to comment.  The first part seems like what `External DNS` was designed to do, but maybe streamlined (the same CoreDNS instance or whatever syncs cluster DNS could sync 2 zones to the same server).

I'm not against that idea - it seems like a good escape hatch.  Open question of whether it should be a CoreDNS-specific thing or a kubernetes thing.

**Comment by segevfiner** [comment]
External DNS already has support for configuring CoreDNS via the etcd CoreDNS plugin: https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/coredns.md (The instructions are a bit outdated). Though that's quite a convoluted setup that requires another etcd deployment. (Tried packaging that as a minikube addon here https://github.com/kubernetes/minikube/issues/8980).

This doesn't handle the split-horizon case where you want the external DNS names to resolve differently from inside the cluster. Such a thing doesn't have to be handled by external DNS and can be handled by the in-cluster CoreDNS deployment using some other mechanism that just works out of the box.

**Comment by thockin** [comment]
Maybe there's a combination of parts to the solution.  Just spit-balling.

Imagine a new CRD "ClusterZone"

```
kind: ClusterZone
spec:
    zone: "example.com"
    serviceTemplate: "$(SVC).$(NS).$(ZONE)"
```

CoreDNS would consume ClusterZone resources and serve the spec.zone (example.com here).  A "foo" service in namespace "bar" would become "foo.bar.example.com".  Cluster-internal resolution would hit this and get internal answers.  NOTE: the node-local cache would have to forward the zone explicitly.

At the same time, the "foo.bar..." service could ALSO use ExternalDNS to program Route53 (or whatever) such that "foo.bar.example.com" routed to the service's external LB or to an Ingress IP.

The problem is that "foo.bar.example.com" exposes some internal details (the service and namespace name).  More likely you want a "vanity" name like "catalog.example.com", which opens the can of worms around which names a given Namespace is able to claim.  We have had only very general discussions about that (e.g. HostnameGrant).

Again, this is just tossing ideas out.  I barely know the requirements.

**Comment by thockin** [comment]
This has moved into "needs a KEP" territory.

/triage accepted

**Comment by ddurham2** [comment]
I believe another fitting scenario is when a pod needs to validate a JWT whose certificate URL uses the public hostname of the service that authorizes it, and that service is inside of the same cluster.
