### ISSUE TITLE
Add default node affinity constraints to NodeAffinity plugin

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#95738]
**What would you like to be added**:

/sig-scheduling

Configurable node affinity constraints to the NodeAffinity plugin args:

```golang
type NodeAffinityArgs struct {
  default *v1.NodeAffinity
}
```

These rules are always appended to the ones defined in PodSpecs.

**Why is this needed**:

Some scheduling profiles might only make sense for certain set of Nodes. Requiring PodSpecs to have node affinity additionally to the scheduler name is redundant in this scenario.
While this can be achieved with mutating webhooks, such implementation would increase Pod creation latency.

**Comment by alculquicondor** [comment]
@Huang-Wei @ahg-g wdyt?

**Comment by ahg-g** [comment]
+1, I think this will allow us to give users a direct replacement to the custom `NodeLabel` plugin.

To clarify, the idea here is to merge, and so the "default" will always be applied to the spec irrespective of whether or not the pod defines one (so it is different from default podtopologyspread which we apply only if the pod spec doesn't define one).

**Comment by Huang-Wei** [comment]
LGTM. One question: if `NodeAffinityArgs` contains **hard** constraints, I think we should honor it in PodTopologySpread? (which now honors **explicit hard** node selector/affinity constraints from pod spec.)

> To clarify, the idea here is to merge, and so the "default" will always be applied to the spec irrespective of whether or not the pod defines one (so it is different from default podtopologyspread which we apply only if the pod spec doesn't define one).

I think so - they're ANDed, but leave to @alculquicondor to confirm.

**Comment by alculquicondor** [comment]
The easy question first:
Yes, append == merge == AND

> if NodeAffinityArgs contains hard constraints, I think we should honor it in PodTopologySpread?

That should actually be the majority of use cases. What do you think of sharing the PreFilter state from NodeAffinity to PodTopologySpread to pass the calculated affinity?

**Comment by Huang-Wei** [comment]
> That should actually be the majority of use cases. What do you think of sharing the PreFilter state from NodeAffinity to PodTopologySpread to pass the calculated affinity?

I assume it wouldn't impose too much overhead on perf, right? BTW: we can make a minor improvement in PreFilter() for non-empty `metadata.name` (case of DasemonSet) - in which case, do an early return once we find a match.

**Comment by alculquicondor** [comment]
> I assume it wouldn't impose too much overhead on perf, right?

The alternative would be for users of profiles to provide a webhook, which would be worst for the system, but cause the same overhead in scheduler.

> BTW: we can make a minor improvement in PreFilter() for non-empty metadata.name (case of DasemonSet)

I guess in this case we should skip applying the extra node selectors.
But we have a semantics problem if a DaemonSet Pod template has a scheduler name with hard node affinity rules. Then the daemonset controller would create unschedulable Pods, as it wouldn't consider the profile node labels.

> in which case, do an early return once we find a match.

I'm not sure I follow. PreFilter is independent of Node.

**Comment by Huang-Wei** [comment]
> > in which case, do an early return once we find a match.
> 
> I'm not sure I follow. PreFilter is independent of Node.

Oh, you were just suggesting to pre-process the affinity spec in PreFilter(), instead of iterating over nodes to get a PreFilter result? If so, please ignore my comment about the overhead thing.




> > BTW: we can make a minor improvement in PreFilter() for non-empty metadata.name (case of DasemonSet)
> 
> I guess in this case we should skip applying the extra node selectors.
> But we have a semantics problem if a DaemonSet Pod template has a scheduler name with hard node affinity rules. Then the daemonset controller would create unschedulable Pods, as it wouldn't consider the profile node affinity.

I think we need to ensure DaemonSet controller to honor the profile's hard node affinity args, otherwise the DaemonSet's stauts will end up with X/Y available (X < Y, Y is the number of nodes which passed podTemplate's node affinity).

https://github.com/kubernetes/kubernetes/blob/5d49a6253c84c7f99264f0f95453ec666c998359/pkg/controller/daemon/daemon_controller.go#L891-L901

**Comment by alculquicondor** [comment]
> Oh, you were just suggesting to pre-process the affinity spec in PreFilter()

Correct.

> I think we need to ensure DaemonSet controller to honor the profile's hard node affinity args.

That would imply that we have to make the daemonset controller profile aware, which, other than being a lot of work (it doesn't currently run a framework), it's prone to be misconfigured by operators.

Would it make sense to exclude DaemonSet Pods from this feature of default affinity rules?

**Comment by Huang-Wei** [comment]
> Would it make sense to exclude DaemonSet Pods from this feature of default affinity rules?

In that case, it seems on the scheduler side, the only clue is to tell if `.spec.metadata.name` is nil (checking a Pod's controllerRef is too much IMO)? It's for sure doable, but it's a bit fragile as `.spec.metadata.name` may be used for general purposes (not just reserved for DaemonSet) in the future.

**Comment by ahg-g** [comment]
> Would it make sense to exclude DaemonSet Pods from this feature of default affinity rules?

I don't think so, we should just document it.

Note that this is the same problem with NodeLabel plugin that already exists.

**Comment by alculquicondor** [comment]
> Note that this is the same problem with NodeLabel plugin that already exists.

Do we have consensus? I would like to add this for 1.20

**Comment by ahg-g** [comment]
I am ok with this, it is a replacement to the NodeLabel plugin which we want to deprecate in this cycle.

**Comment by Huang-Wei** [comment]
> Do we have consensus?

Are we agreed on "exclude DaemonSet Pods from this feature of default affinity rules" by telling "if `.spec.metadata.name` is nil"?

**Comment by alculquicondor** [comment]
I'm not sure what you mean by `.spec.metadata.name` being nil. Whose? The Pod?

Unless you mean the node affinity using `metadata.name` that Daemonset pods get:
https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#scheduled-by-default-scheduler

@ahg-g stance is to not do anything special with Daemonset Pods

I'm in the fence. Are there any other kind of Pods that could get affected?
The most reliable way to tell Daemonset Pods is via the controller reference IMO. But is it worth? There are other ways a user could get unschedulable Pods. We would need to make sure we are surfacing the error properly so that the user can fix their PodSpec by using a different scheduler or setting NodeAffinity themselves.

**Comment by ahg-g** [comment]
> > Do we have consensus?
> 
> Are we agreed on "exclude DaemonSet Pods from this feature of default affinity rules" by telling "if `.spec.metadata.name` is nil"?

I don't think we should do anything special for daemonsets, we just need to document the behaviour and propose a best practice. As I mentioned, this is not new, the existing nodelabel plugin has the same behavior.

**Comment by Huang-Wei** [comment]
> I don't think we should do anything special for daemonsets, we just need to document the behaviour and propose a best practice. As I mentioned, this is not new, the existing nodelabel plugin has the same behavior.

To clarify: in a cluster admin's angle, they should understand that a non-nil `NodeAffinityArgs` may cause a DaemonSet to create extra Pods in pending (unschedulable and unresolvable) state as profile-level node affinity constraints are not honored at Pod creation time (by DaemonSet controller).

**Comment by ahg-g** [comment]
> To clarify: in a cluster admin's angle, they should understand that a non-nil NodeAffinityArgs may cause a DaemonSet to create extra Pods in pending (unschedulable and unresolvable) state as profile-level node affinity constraints are not honored at Pod creation time (by DaemonSet controller).

The best practice would be to always have a default profile that daemonsets should use. If a second profile is added that explicitly targets a specific set of nodes, then daemonsets that use this profile being deployed only on those nodes is I think working as intended.

**Comment by Huang-Wei** [comment]
> The best practice would be to always have a default profile that doesn't set NodeAffinityArgs that daemonsets should use. If a second profile is added that explicitly targets a specific set of nodes, then daemonsets that use this profile being deployed only on those nodes is I think working as intended.

LGTM, we should ensure end-user / cluster admin to be aware of this.
