### ISSUE TITLE
CSS not loading kubernetes.io docs

### ISSUE THREAD

**Issue by ankitabhopatkar13** [kubernetes/kubernetes#95749]
**What happened**:

Not able to read kubernetes documents as CSS is giving 404. Also other endpoints` CSS giving 404(https://kubernetes.io/blog/)

Source - https://kubernetes.io/scss/main.min.f276b50d1c71711c70ef4fa9d4b796c7d32e4fdc489e65604766e35fe9f4958d.css

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by troy0820** [comment]
Hey @ankitabhopatkar13 I'm trying to reproduce this issue.  I can see the docs when I go to the blog endpoint as well as other website endpoints.  What web browser are you using?

**Comment by SataQiu** [comment]
It seems to be OK!

![image](https://user-images.githubusercontent.com/9354727/96819661-aef58100-1456-11eb-80ad-140071de2385.png)

**Comment by ankitabhopatkar13** [comment]
Hi,

Thanks for the replies. It does work now. But it definitely didn't for around 5-10 minutes atleast yesterday between 9:45 to 10:00AM CEST time. Tried from different browsers and different networks :)

Anyway, I will close this issue now, as it no longer is valid.
