### ISSUE TITLE
ownerReference is not reconciled, leading to abandoned resources

### ISSUE THREAD

**Issue by grosser** [kubernetes/kubernetes#95742]
**What happened**: configmap we use for leader election was not deleted even though it's owner is gone

**What you expected to happen**: configmap is deleted

**How to reproduce it (as minimally and precisely as possible)**: idk

**Anything else we need to know?**:
it looks like there is a race-condition / bug in onerreference handling, I'd suggest some reconcile logic that takes care of these so things eventually get fixed

**Environment**:
- Kubernetes version 1.19.3

**Comment by roycaihw** [comment]
@grosser Without a reproduce this would be hard to triage. Some possibilities that I can think of:

- Were there any other owners that still existed? Could you print out the configmap and paste it here?
- The garbage collector is the reconcile logic that removes abandoned resources. Was the garbage collector healthy? Please try restart the garbage collector next time you see the issue to see if it's fixed.
- Was there anything like an admission webhook that prevents the garbage collector from deleting the object? You could increase the verbosity of the garbage collector to see if it prints any log related.

You mentioned "race-condition / bug in ownerreference handling". Do you have any other specific clue that we can follow?

**Comment by grosser** [comment]
thx, will reopen if it reappears ... did not check the garbage collector, might have been in trouble!
