### ISSUE TITLE
pod stuck on the nominated node cannot release resource timely 

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubernetes#95752]
**What would you like to be added**:
Set the capping of retrying on the nominated node so that other nodes in the cluster could be chosen for preemption.

**Why is this needed**:

After the pod preemption, a nominated could be set for the preemptor pod. After the restful API of deletion has been sent,
https://github.com/kubernetes/kubernetes/blob/9a6e35a16a92feac757bf0621a09a2661f617617/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go#L601-L603
the resource is not actually been deleted, this work needs to be done by `kubelet` and container runtime, docker for example. 

This is out of control of scheduler, something abnormal will make the resource never been released, docker is down for example, but when this happens, the scheduler should be able to preempt pods on other nodes  in the cluster to release resource for the high priority node, but this is  not true today cause the pod is not eligible to preempt resource from other node https://github.com/kubernetes/kubernetes/blob/9a6e35a16a92feac757bf0621a09a2661f617617/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go#L211-L213

This will lead to a infinite looping of scheduling and the checking for the preemption, even there are other healthy node that is able to schedule the pod after releasing enough resource.

filtering that have been evaluated that maybe impacted by the preemption 
- PodTopologySpread
preemptor pod can still be scheduled on the `nominatedNode` even the resource is not released, since the pod deletion on-the-fly is skipped
https://github.com/kubernetes/kubernetes/blob/9a6e35a16a92feac757bf0621a09a2661f617617/pkg/scheduler/framework/plugins/podtopologyspread/common.go#L91-L93

- NodeResourcesFit
preemptor pod will be stuck on the nominated node and the scheduler will loop forever!

**Comment by alculquicondor** [comment]
What is your proposal? number of retries or perhaps a time limit?
Should we make it configurable in the preemption plugin args?

**Comment by chendave** [comment]
> What is your proposal? number of retries or perhaps a time limit?
Should we make it configurable in the preemption plugin args?

+1, this is what I am thinking about, perhaps there are other options to address this issue, I will continue to do some investigation here and hopefully got more ideas from you.

**Comment by alculquicondor** [comment]
One more thing to think about: a Pod that requires more Pods to be preempted should have more retries.

**Comment by chendave** [comment]
> One more thing to think about: a Pod that requires more Pods to be preempted should have more retries.

retries = len(preempted pods) * 2?  for most of case, this should be enough? I also think it might be overkill to make it configurable, I don't have solid reason that user has knowledge on how to configure times of retry.

**Comment by alculquicondor** [comment]
That sounds reasonable to me. @Huang-Wei ?

**Comment by Huang-Wei** [comment]
I think we're talking two things here:

1. When to dishonorr a Pod's nominatedNodeName field?
1. The "over-relaxed" logic that checks whether a nominated node should continue, as @chendave mentioned:
    https://github.com/kubernetes/kubernetes/blob/9a6e35a16a92feac757bf0621a09a2661f617617/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go#L211-L213

I understand that add retrying times may resolve the problem (1), with a cost of maintaining a stateful counter, which I'm not quite sure I'm fond of. Instead of solving (1), I believe we should brainstorm on (2) so as to clear the issue thoroughly. Here are some rough ideas to resolve (or mitigate) it:

1. Once scheduler preempts a Pod, set a special .status.condition[*] to tag it as a victim of scheduler preemption. This not only helps with later scheduling, but also helps end-users to distinguish scheduler preemption from kubelet eviction. This condition can help us identify whether those low-priority terminating Pods are victims or not.
1. With the special condition being said, if the Pod is a victim, we can define a fixed timeout serving as a "tolerationGracePeriod" to check whether `victim.DeletionTimestamp.Before(preemptor.CreationTimestamp.Add(tolerationDurtion))`. If yes, it means we have waited enough time, so disregard the terminating victims; otherwise, still give some patience for victims to finish their teardown work. BTW: `preemptor.CreationTimestamp` is a draft idea, we may use lastScheuledTimestamp alternatively.

**Comment by alculquicondor** [comment]
I like the idea of a Condition. We just need to make sure we get the updates and that we are ignoring them to cause any scheduling retries.

**Comment by Huang-Wei** [comment]
> We just need to make sure we get the updates and that we are ignoring them to cause any scheduling retries.

The preemptor will be retried after N cycles (N depends on the pending high or equal priority pods in the internal queue), and during that time, IMO in most cases scheduler should be able to get the updated Pod object with that condition populated. If not for the first time, we can still get that eventually.

**Comment by chendave** [comment]
Pod condition sound good to me, some comments from me if we decide to go with Pod condition, 

- I come across an aged issue https://github.com/kubernetes/kubernetes/issues/50798, which has been discussed long time ago,  which in favor of deprecating the `Pod.status.condition`, is that still the case?
- I am not quit following the formula used as the example, 
`victim.DeletionTimestamp.Before(preemptor.CreationTimestamp.Add(tolerationDurtion))` 
Instead, I think something like below might wok, 
`victim.DeletionTimestamp.Add(tolerationDurtion)) > time.Now()` 
- Two points from @alculquicondor 's comments IIUC,  the first one is we need make sure pod condition could be updated successfully,  and the second, this kind of update should not enqueue the victim pods to scheduler's internal queue, right?
- Might consider to add a new `ConditionType` to `PodStatus.Conditions` beside the existing `ContainersReady`, `Ready`, `PodScheduled` etc. maybe `PodPreempted`?

So, @liggitt  are you awareing of any problem if adding a new `ConditionType` to Pod's API to tag the pod as a victim pod from pod preemption?

**Comment by liggitt** [comment]
> * I come across an aged issue #50798, which has been discussed long time ago,  which in favor of deprecating the `Pod.status.condition`, is that still the case?

That is no longer planned.

> So, @liggitt are you awareing of any problem if adding a new `ConditionType` to Pod's API to tag the pod as a victim pod from pod preemption?

Additional conditions can be added to pods, so that is not a problem. However, I would caution against using conditions as the system of record for pod states in such a way that they could not be recreated from scratch. Conditions are intended to reflect observations of the system.

From https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties:

> Condition type names should describe the current observed state of the resource, rather than describing the current state transitions.

I'm not sure where the proposed `PodPreempted` condition would fall in this chain of events. Is it "selected for preemption", "preemption requested", or "already preempted"? Is it guaranteed to be preempted? Is the preemption decision reversible? If the preemption condition was erased, could the preemption status of the pod be recreated from observation or re-derived?

**Comment by Huang-Wei** [comment]
> I'm not sure where the proposed `PodPreempted` condition would fall in this chain of events. Is it "selected for preemption", "preemption requested", or "already preempted"?

It's "already preempted".

> Is it guaranteed to be preempted?

Yes, scheduler sends a delete event to API server.

> Is the preemption decision reversible?

No. After the pod gets preempted, the last state it went through is just "terminating".

> If the preemption condition was erased, could the preemption status of the pod be recreated from observation or re-derived?

Two possible cases here:

- The preempted pod stays in "terminated" status, if the condition gets erased (which I don't quite think is possible, who would change overwrite conditions of a "deleted" pod?), the worse case is the preemption behavior falls back to current behavior (i.e., without optimization)
- The preempted pod gets deleted physically, it's the ideal case, so no side effect to the optimization we discussed here.

**Comment by Huang-Wei** [comment]
> * I am not quit following the formula used as the example,
>   `victim.DeletionTimestamp.Before(preemptor.CreationTimestamp.Add(tolerationDurtion))`
>   Instead, I think something like below might wok,
>   `victim.DeletionTimestamp.Add(tolerationDurtion)) > time.Now()`

Sure, I just gave a rough idea. We can talk about the concise formula later.

**Comment by Huang-Wei** [comment]
> * this kind of update should not enqueue the victim pods to scheduler's internal queue, right?

Good question. I think it depends on how we perform the preemption. Current behavior is to just sends a delete request to API server, and then API server actually **update** the Pod's deletetionTimstamp, and wait for kubelet the confirm the physical deletion of related containers, and then the API object gets deleted physically.

So, I'm not 100% sure, is it possible to use one action to (1) delete the pod, and also (2) append a particular condition? (the condition is just transient to be valid during the "terminating" period)

**Comment by chendave** [comment]
After some investigation on this issue, this looks like to me is not a big issue anymore,

- If the runtime is down for an while, taint will be set on the node which mark this node as `UnschedulableAndUnresolvable`, this has been fixed by this PR already: https://github.com/kubernetes/kubernetes/pull/92604, so that preempt pods on other nodes is possible.

- If the runtime is not down, but the remove process is very slowly, `kubelet` will forcibly delete the pod after `TerminationGracePeriodSeconds`, 30 seconds by default.

For the sake of not depending on kubelet, and some other corner cases (might be) which leads to a invalid looping, propose a simple PR here: https://github.com/kubernetes/kubernetes/pull/97546

**Comment by alculquicondor** [comment]
> For the sake of not depending on kubelet, and some other corner cases (might be) which leads to a invalid looping, propose a simple PR here: #97546

Or we can leave this as is. I'm not quite liking having a constant timeout.

**Comment by ahg-g** [comment]
Can we close this issue? I think the existing behavior is reasonable and we don't need to change anything.

**Comment by Huang-Wei** [comment]
> For the sake of not depending on kubelet

Hmm, I'm more inclined to stick to the current semantics to wait for the Pod deletion event to propagate.

BTW: Clayton raised a point in another issue to suggest coming up with a consistent mechanism to identify a "terminal" Pod earlier, in both scheduler and kubelet. If we have that in place, scheduler won't need to depend on the Pod deletion event, and hence resolve/mitigate some issues (like this one) naturally.

**Comment by chendave** [comment]
/close
As this issue is not big issue anymore after some code change in the upstream, close it as won't fix.
