### ISSUE TITLE
Priorityclass field support edit

### ISSUE THREAD

**Issue by wukong1992** [kubernetes/kubernetes#95751]
**Priorityclass field support edit**: 

**some task’s priority is changing by time; Also as platform，we need to support task  related to the time period **:

**Comment by krmayankk** [comment]
@wukong1992 can you provide more description of the the features you are looking for ? It seems you want PriorityClass to be editable/modifiable, is that right ? Can you describe the scenario why that should be modifiable ?

**Comment by wukong1992** [comment]
@krmayankk yeah, the scenario is, we want to support inerval  resourcequota, for user who have task only run for  fixed period of time， like 3：00～8：00.  Then， we want to  lower the priority of a task， when run out of the time period instead of killing the task。
