### ISSUE TITLE
waitForFirstConsumer PVCs fail to bind when Pod spec.nodeName is specified

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#95767]
If using waitForFirstConsumer mode, we cannot set Pod spec.nodeName. 

Issue https://github.com/openebs/openebs/issues/2915 has detailed explanation.

Should document this behavior in doc.

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Jiawei0227** [comment]
https://github.com/kubernetes/kubernetes/issues/89953

So this is the issue, right? Are you suggesting we fix the issue or just document it to use nodeaffinity?

**Comment by jingxu97** [comment]
I think this is by design (a limitation that is hard to avoid) @msau42 
So we just need to document it.

**Comment by msau42** [comment]
Yes this is a known limitation. Maybe https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode would be a good place to document it?
