### ISSUE TITLE
 LICENSE file refers to "Licensor" but there is no licensor stated in the LICENSE file or in the README file. #619 

### ISSUE THREAD

**Issue by designedforplaygames** [kubernetes/kubernetes#95765]
Re-posting this issue here from the original issue posted to the metrics server repo.

This is a documentation bug report. For legal compliance purposes within my organization, I am required to know the exact copyright holder of the software we are intending to use. There is no copyright notice in the README or LICENSE file nor any other indication in those files that I can find of who the "Licensor" referred to in the LICENSE file actually is.

The LICENSE file is a legal agreement, but you do not define the terms used within the agreement - specifically the copyright holder, to which the LICENSE refers as "Licensor".

Please define the copyright holder or the "Licensor" in your license file, in your readme file, or in a copyright file, in every repository which Kubernetes maintains.

**Comment by designedforplaygames** [comment]
Correction: i believe this is a "release" bug, as it deals with the license.

/sig release

**Comment by troy0820** [comment]
Each person who contributed to this repository is made to fill out a [individual contributor license agreement](https://github.com/cncf/cla/blob/master/individual-cla.pdf) that classifies everyone who contributed as a copyright owner, from my understanding.

**Comment by neolit123** [comment]
@dims @nikhita @swinslow @dankohn 
is the licensor of Kubernetes the CNCF?

**Comment by dims** [comment]
@neolit123 i believe it's the Linux Foundation

**Comment by swinslow** [comment]
Kubernetes does not record the specific copyright holders for contributions. Many Kubernetes source code files contain notices referring generally to "The Kubernetes Authors" -- as a random example, see https://github.com/kubernetes/kubernetes/blob/master/pkg/api/persistentvolume/util.go

@troy0820 is correct, contributors retain ownership of the copyrights that they contribute to Kubernetes, and license it under individual and/or corporate CLAs (depending on whether they are contributing on their individual behalf or on behalf of their employers).

I do not think this requires any changes to the repo. You can read more about CNCF's approach to copyright notices at https://github.com/cncf/foundation/blob/master/copyright-notices.md

**Comment by neolit123** [comment]
thank you very much for the clarification @swinslow 

@designedforplaygames this is a response you can reference to your employers.

i'm closing this and the metrics-server ticket:
https://github.com/kubernetes-sigs/metrics-server/issues/619

thanks
/close
