### ISSUE TITLE
BGP Unnumbered RFC 5549 ResolveBindAddress fails

### ISSUE THREAD

**Issue by eknudtson** [kubernetes/kubernetes#95779]
**What happened**:

When attempting to kubeadm join a control plane node or worker on a machine with global IPv4 unicast addresses on a loopback address (router to the host w/ BGP Unnumbered), the join fails with the following output:

```
I1009 00:03:38.372308    8018 interface.go:400] Looking for default routes with IPv4 addresses
I1009 00:03:38.372350    8018 interface.go:405] Default route transits interface "ens15f0.300"
I1009 00:03:38.372793    8018 interface.go:208] Interface ens15f0.300 is up
I1009 00:03:38.372911    8018 interface.go:256] Interface "ens15f0.300" has 1 addresses :[fe80::a236:9fff:fe80:8258/64].
I1009 00:03:38.372959    8018 interface.go:223] Checking addr  fe80::a236:9fff:fe80:8258/64.
I1009 00:03:38.372984    8018 interface.go:236] fe80::a236:9fff:fe80:8258 is not an IPv4 address
I1009 00:03:38.373017    8018 interface.go:400] Looking for default routes with IPv6 addresses
I1009 00:03:38.373034    8018 interface.go:405] Default route transits interface "ens15f1.300"
I1009 00:03:38.373375    8018 interface.go:208] Interface ens15f1.300 is up
I1009 00:03:38.373465    8018 interface.go:256] Interface "ens15f1.300" has 1 addresses :[fe80::a236:9fff:fe80:825a/64].
I1009 00:03:38.373502    8018 interface.go:223] Checking addr  fe80::a236:9fff:fe80:825a/64.
I1009 00:03:38.373523    8018 interface.go:233] Non-global unicast address found fe80::a236:9fff:fe80:825a
I1009 00:03:38.373542    8018 interface.go:405] Default route transits interface "ens15f0.300"
I1009 00:03:38.374553    8018 interface.go:208] Interface ens15f0.300 is up
I1009 00:03:38.374644    8018 interface.go:256] Interface "ens15f0.300" has 1 addresses :[fe80::a236:9fff:fe80:8258/64].
I1009 00:03:38.374696    8018 interface.go:223] Checking addr  fe80::a236:9fff:fe80:8258/64.
I1009 00:03:38.374720    8018 interface.go:233] Non-global unicast address found fe80::a236:9fff:fe80:8258
I1009 00:03:38.374741    8018 interface.go:416] No active IP found by looking at default routes
```

See this issue for details : https://github.com/kubernetes/kubeadm/issues/2323

Also:
https://github.com/kubernetes/kubeadm/issues/1156
https://github.com/kubernetes/kubernetes/pull/83475
https://github.com/kubernetes/kubernetes/pull/69578

**What you expected to happen**:
The correct IPv4 address should be selected from the loopback adapter, or we should be able to specify an IPv4 address to use for egress.  The IPv6 addresses on the network adapters themselves are only used to establish upstream peering.  IPv4 nexthops are fake 169.254.x.x addresses artificially programmed via RFC5549 into the ARP table.

**How to reproduce it (as minimally and precisely as possible)**:
On a node with the following conditions:
- Routing to the host with FRR
- IPv6 link locals on physical network interfaces
- No IPv4 addresses on physical network interfaces
- Unicast IPv4 on the loopback adapter
- IPv4 default route present via RFC5549

Attempt to kubeadm join a node, and it will fail.

**Anything else we need to know?**:
We've been patching kubeadm with https://github.com/kubernetes/kubernetes/pull/69578/files, which works as expected.

There was a fix applied [here](https://github.com/kubernetes/kubernetes/pull/83475) to allow initing control plane nodes w/ bind address 127.0.0.1 which would then select an IPv4 from the loopback, but it doesn't appear to have fixed the joining issues.

Pinging @neolit123 and @aojea by request on kubeadm issues.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.12
- Cloud provider or hardware configuration: baremetal
- OS (e.g: `cat /etc/os-release`): Centos 7
- Kernel (e.g. `uname -a`): 3.10.0-1127.19.1.el7.x86_64
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): Calico
- Others: FRR for peering with routers on physical network interfaces

**Comment by neolit123** [comment]
`ResolveBindAddress()` is defined [here](https://github.com/kubernetes/kubernetes/blob/323f34858de18b862d43c40b2cced65ad8e24052/staging/src/k8s.io/apimachinery/pkg/util/net/interface.go#L425)

/sig network
