### ISSUE TITLE
Add e2e test for Service ExternalIPs

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#95785]
**What would you like to be added**:

e2e test for service ExternalIPs

**Why is this needed**:

There is no test covering Service ExternalIPs

## How to test it

Since we can not assume that the e2e binary will have connectivity against the nodes
and that we can add routes to the environment, we are going to test it from a pod.

I've verified that this works locally with the following commands:

```sh
$ kubectl create deployment httpd --image httpd
deployment.apps/httpd created
$ kubectl expose deployment httpd --external-ip=19.19.19.19 --port 80
service/httpd exposed
$ kubectl run test -it --image=busybox -- sh
/ # ip a                                                                                                                                     
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000                                                                              
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00                                                                                    
    inet 127.0.0.1/8 scope host lo                                                                                                           
       valid_lft forever preferred_lft forever                                                                                               
    inet6 ::1/128 scope host                                                                                                                 
       valid_lft forever preferred_lft forever                                                                                               
3: eth0@if2: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue                                                                 
    link/ether a2:5c:4a:79:5f:fe brd ff:ff:ff:ff:ff:ff                                                                                       
    inet 10.244.2.2/24 brd 10.244.2.255 scope global eth0                                                                                    
       valid_lft forever preferred_lft forever
    inet6 fe80::a05c:4aff:fe79:5ffe/64 scope link 
       valid_lft forever preferred_lft forever
/ # echo GET | nc 19.19.19.19 80
HTTP/1.1 400 Bad Request
Date: Thu, 22 Oct 2020 08:06:55 GMT
```

The test should leverage current framework, maybe something as
`should be able to create a functioning ClusterIP service with ExternalIPs`

A good example is here, 
https://github.com/kubernetes/kubernetes/blob/ededd08ba131b727e60f663bd7217fffaaccd448/test/e2e/network/service.go#L1199-L1218

maybe adding a `testReachabilityOverExternalIP` ?
https://github.com/kubernetes/kubernetes/blob/ededd08ba131b727e60f663bd7217fffaaccd448/test/e2e/framework/service/jig.go#L820

**Comment by DP19** [comment]
I'd like to pick this up!

**Comment by zhouya0** [comment]
> I'd like to pick this up!

Ok,I'm not started :)
/unassign
/assign @DP19

**Comment by danwinship** [comment]
There are two different externalIP codepaths, one for the case where the claimed external IP exists as an IP on the default interface, and one for where it does not. I suppose we could just temporarily add an IP to the default interface...

> ```shell
> $ kubectl expose deployment httpd --external-ip=19.19.19.19 --port 80
> ```

That IP belongs to someone, somewhere. It would be better to use an IP in a reserved range. Though technically incorrect, we could probably use one of the ranges reserved for documentation (eg, `203.0.113.0/24`) since you're not allowed to use those for any normal purposes so they shouldn't conflict with anything the host is doing...)

**Comment by aojea** [comment]
good idea Dan
Please remember, it has to work for IPv6 and for IPv4 ... anyway, we can address these things during the review

**Comment by DP19** [comment]
This has been partially implemented with #96116 . Covering the code path for when an IP is does not exist on a node. 

@aojea I'll assign this back to you so you can split this issue or close it in favor of another issue. Thanks!

/unassign
/assign @aojea

**Comment by aojea** [comment]
> There are two different externalIP codepaths, one for the case where the claimed external IP exists as an IP on the default interface, 

what is the different codepath for the IP that exist on the host? 
My reading is that the only difference is that it opens a local socket on that port, can you expand on this?

**Comment by aojea** [comment]
so, it seems that this work in some environments because they are not using the bridge plugin

https://github.com/kubernetes/kubernetes/blob/e0a51c9e6b4881df78e046d9c6daf4e6f2a11f78/pkg/proxy/iptables/proxier.go#L1135-L1141

**Comment by thockin** [comment]
Wow, this is ancient and needs some fixing.  This is not about preventing pod traffic from reaching those IPs.  I had to really stare at it, and I am not 100% in my interpretation.

First, we recognize such traffic from "off machine" (!physdev-is-in &&  !src=LOCAL, which we should probably switch to localDetector) and steer it to the Service.

Second, we recognize ANY such traffic that is destined for a LOCAL address and shortcut that to the Service,

Implicitly, traffic destined for this IP where the IP is not local goes to the system's default routing logic. 

The reliance on the bridge plugin is awful and archaic and I will buy a beverage of your choice for whomever gets rid of that.  I  *think* localDetector can cover this, but not 100% sure

**Comment by aojea** [comment]
> Implicitly, traffic destined for this IP where the IP is not local goes to the system's default routing logic.

but the ExternalIP belongs to a service and we(kube-proxy) "knows" where to send it (to the service) , that is the part I'm not sure to understand, because whatever the user is doing with that ExternalIP it has to send it back to the cluster to reach the service. However, there is always context that is important and maybe I'm missing something.

Assuming we want to handle ALLl the ExternalIP traffic with kube-proxy, the logic will be much simpler:
- traffic to an externalIP will be ALWAYS sent to the Service (DNAT)
- if traffic is NOT LOCAL, we also SNAT
