### ISSUE TITLE
Deploying the k8s cluster on the openstack virtual machine Adding service causes the node noready！！！

### ISSUE THREAD

**Issue by Morride** [kubernetes/kubernetes#95788]
**What happened**:
Deploying the k8s cluster on the openstack virtual machine Adding service causes the node noready.
**What you expected to happen**:
I want to know why after I add the service service, the node will not be ready, whether this is related to the openstack network.
**How to reproduce it (as minimally and precisely as possible)**:
When you build a k8s service on openstack and add a service.
**Anything else we need to know?**:
The network component uses calico. The mtu value of the eth0 network card is changed to 1400. The mtu value of the eth0 network card is 1500. After the modification, it is 1450 (previously installed on other openstack virtual machines, but also encountered network problems. The mtu value of the eth0 network card over there It’s 1450 that the mtu of calico is set to 1400 successfully)
**Environment**:
- Kubernetes version (use `kubectl version`):V1.15.7
- Cloud provider or hardware configuration:8c16g
- OS (e.g: `cat /etc/os-release`):Red-Hat 7.6
- Kernel (e.g. `uname -a`):3.10.0-957
- Install tools:
- Network plugin and version (if this is a network-related bug):calico-v3.8
- Others:openstack

After kubernetes is built, the cluster status is normal. It is no problem to deploy the mysql cluster. When adding service to the service, it is found that the node-0 node is noready, (the LoadBalancer used by the service is bound to node-0) The configuration is as follows
```
apiVersion: v1
kind: Service
metadata:
  name: test-svc
  namespace: test
  labels:
    name: test
spec:
  type: LoadBalancer
  externalIPs:
  - 10.84.15.33
  ports:
  - port: 8300
    protocol: TCP
    targetPort: 8300
    nodePort: 30000
  selector:
    app: test
```
After node-0 is noready, the following is the kubelet log
```
Oct 22 14:14:42 node-0 kubelet[28641]: W1022 14:14:42.146793   28641 status_manager.go:485] Failed to get status for pod "calico-node-mmtpm_kube-system(9937bcd4-3cf1-4d3b-b4f9-76b603ff38f7)": Get https://10.84.155.33:6443/api/v1/namespaces/kube-system/pods/calico-node-mmtpm: read tcp 10.84.155.33:56470->10.84.155.33:6443: use of closed network connection
Oct 22 14:14:42 node-0 kubelet[28641]: E1022 14:14:42.146998   28641 reflector.go:125] object-"kube-system"/"calico-config": Failed to list *v1.ConfigMap: Get https://10.84.155.33:6443/api/v1/namespaces/kube-system/configmaps?fieldSelector=metadata.name%3Dcalico-config&limit=500&resourceVersion=0: read tcp 10.84.155.33:56470->10.84.155.33:6443: use of closed network connection
Oct 22 14:14:42 node-0 kubelet[28641]: I1022 14:14:42.613399   28641 prober.go:112] Readiness probe for "calico-node-mmtpm_kube-system(9937bcd4-3cf1-4d3b-b4f9-76b603ff38f7):calico-node" failed (failure): calico/node is not ready: BIRD is not ready: BGP not established with 10.84.155.35,10.84.155.36,10.84.155.592020-10-22 06:14:42.589 [INFO][7606] health.go 156: Number of node(s) with BGP peering established = 0
Oct 22 14:14:52 node-0 kubelet[28641]: E1022 14:14:52.145553   28641 kubelet_node_status.go:388] Error updating node status, will retry: error getting node "10.84.155.33": Get https://10.84.155.33:6443/api/v1/nodes/10.84.155.33?timeout=10s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Oct 22 14:14:52 node-0 kubelet[28641]: E1022 14:14:52.145574   28641 kubelet_node_status.go:375] Unable to update node status: update node status exceeds retry count
Oct 22 14:14:52 node-0 kubelet[28641]: E1022 14:14:52.146179   28641 controller.go:125] failed to ensure node lease exists, will retry in 7s, error: Get https://10.84.155.33:6443/apis/coordination.k8s.io/v1beta1/namespaces/kube-node-lease/leases/10.84.155.33?timeout=10s: read tcp 10.84.155.33:57166->10.84.155.33:6443: use of closed network connection
Oct 22 14:14:52 node-0 kubelet[28641]: E1022 14:14:52.146257
```
Then I found that there is a problem with calico-node, the log of this machine calico-node
```
Error from server: Get https://10.84.155.33:10250/containerLogs/kube-system/calico-node-mmtpm/calico-node?follow=true: dial tcp 10.84.155.33:10250: connect: connection refused
```
And I found that the machine 10.84.155.33 can't even ping other machines. I want to know why adding service will crash the 10.84.155.33 network

**Comment by neolit123** [comment]
> Kubernetes version (use kubectl version):V1.15.7

this version is no longer in support, please upgrade to 1.17+

this doesn't feel like a problem in core Kubernetes, please try asking for help in the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

or OpenStack experts.

if a bug in core, please confirm if it's still a problem in 1.17+.

thanks
/close
/kind support
/remove-kind bug
