### ISSUE TITLE
The node status  queried through kubectl is inconsistent with the status queried through the API

### ISSUE THREAD

**Issue by chymy** [kubernetes/kubernetes#95819]
**What happened**:
The node status  queried through kubectl is inconsistent with the status queried through the API
`kubectl get no`
![image](https://user-images.githubusercontent.com/9379950/96974279-96b35e00-154b-11eb-8101-db32bce83c97.png)

rest api:

"**conditions**": [{
				"status": "Unknown",
				"lasttransitiontime": "2020-10-16T06:25:28Z",
				"lastheartbeattime": "2020-10-16T06:23:25Z",
				"reason": "NodeStatusUnknown",
				"message": "Kubelet stopped posting node status.",
				"type": "MemoryPressure"
			},
			{
				"status": "Unknown",
				"lasttransitiontime": "2020-10-16T06:25:28Z",
				"lastheartbeattime": "2020-10-16T06:23:25Z",
				"reason": "NodeStatusUnknown",
				"message": "Kubelet stopped posting node status.",
				"type": "DiskPressure"
			},
			{
				"status": "Unknown",
				"lasttransitiontime": "2020-10-16T06:25:28Z",
				"lastheartbeattime": "2020-10-16T06:23:25Z",
				"reason": "NodeStatusUnknown",
				"message": "Kubelet stopped posting node status.",
				"type": "PIDPressure"
			},
			{
				"status": "**Unknown**",
				"lasttransitiontime": "2020-10-16T06:25:28Z",
				"lastheartbeattime": "2020-10-16T06:23:25Z",
				"reason": "NodeStatusUnknown",
				"message": "Kubelet stopped posting node status.",
				**"type": "Ready"**
			}]

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"archive", BuildDate:"2020-06-30T01:36:18Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"archive", BuildDate:"2020-06-30T01:32:48Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
kubectl uses information from the rest api. What is the full node object (fetched with `get node -o yaml`)

**Comment by chymy** [comment]
`rest api` result: Unknow
`kubectl get no` result: NotReady
