### ISSUE TITLE
Prometheus stats holding onto a fair amount of memory (potential unbounded rest stats)

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#9581]
Right now the faceted search stats from cadvisor, the rest client, and the apiserver are holding on to a fair amount of memory:

https://github.com/openshift/origin/issues/3053#issue-87005876

Prometheus is holding about 225mb, 35 from the rest client, probably 40-50 from the apiserver (we log more summary data there), and then the bulk is probably from cadvisor.

The growth is proportional to the number of containers running (cadvisor) but should be capped out for apiserver (because we only expose a limited number of endpoints). 

However REST is capturing the URL, which means that every URL endpoint that the API server uses to talk to itself (including every unique named resource fetched by a controller) creates one new summary.  I think we either need to:

a. limit the cardinality of the rest call
b. age out the stat points (does prometheus support this?)
c. garbage collect the stats on REST

This applies to both the kubelet and controller manager, since both hold a long running rest client that is used to fetch individual resources.

@fgrzadkowski

**Comment by smarterclayton** [comment]
The service account controller issues measured there will be tracked separately.

**Comment by vmarmol** [comment]
We *just* submitted a [change](https://github.com/google/cadvisor/pull/767) to cAdvisor to fix a leak which I suspect is behind most of this growth. Will build 0.15.1 today and integrate it into Kubernetes. Although, is this apiserver or controller-manager memory? The linked comment seems to be for that.

for (b), AFAIK Prometheus does not support it, although it sounds like a reasonable thing to ask them to support.

**Comment by smarterclayton** [comment]
OpenShift runs everything in one process (including etcd and skydns) in its all-in-one mode.  So this is the whole kit and caboodle :)

The REST growth was from observation of the rest client metric count (curl /metrics | grep rest_client -c)

**Comment by smarterclayton** [comment]
Actually, the rest client is almost clever enough - it substitutes out "{name}", but not "{namespace}".  Derek's test was adding hundreds of namespaces, which grows without bound.

**Comment by smarterclayton** [comment]
Fix is to do the same thing that we do for names.

**Comment by smarterclayton** [comment]
Do we want to allow rest_client to subdivide on query parameter values?  We'll get the same fanout on field selector and label selector values, effectively meaning infinite growth.  I can fairly easy cap it by making all the parameters empty value.

**Comment by smarterclayton** [comment]
REST client fixed in #9584, etcd metrics also are unbounded and fix is pending.

**Comment by smarterclayton** [comment]
With those two fixes (cadvisor and #9584) I think we're back to bounded growth.  Etcd is taking 6M but that may just be because we record a lot of latency metrics and the pool size is fine.  We have ~40 types going through etcd in openshift, so with the extra operations (i believe get / compareAndSwap / delete) that doesn't sound crazy.

**Comment by bprashanth** [comment]
Isn't this already behind a debug flag? https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/server.go#L124/ListerAnd

**Comment by smarterclayton** [comment]
The metrics are captured regardless of whether the handler is there.

----- Original Message -----

**Comment by bprashanth** [comment]
Can't we just send it down /dev/null or something instead of keeping it in memory when there are no handlers? I suppose this is prometheus side.

**Comment by smarterclayton** [comment]
It is.  Anyway, this is still an issue for controllers when debugging is on - OpenShift secures those endpoints via policy so we don't have an issue with them being enabled by default.

----- Original Message -----

**Comment by smarterclayton** [comment]
Fixed a while back
