### ISSUE TITLE
Kubernetes pod using all nodes vCPU

### ISSUE THREAD

**Issue by Ankur7890** [kubernetes/kubernetes#95827]
I have a 8vcpu/8core box worker node where we are running our nginx pods.  nginx pods are limited to use only 2cores max in
 
YAML definition i.e
request cpu:- 500m
limit cpu:- 2

nginx configuration as below,

worker_process 2
worker_cpu_affinity auto;

nginx is using only 1st 2 CPU00, CPU01 of the nodes with 2 child processes and rest of other 6 CPUs are idle.

whereas with below nginx configuration

worker_process auto
worker_cpu_affinity auto;

it is using all nodes CPU with that much number of processes.

Now query here is ,
1) Why nginx container is not limiting to use 2 cores which is defined in pod definition, why it is using all CPUs?
2) Why only first 2 CPU are utilized in former case where worker process are 2?
3) Can pod use all CPU cores of a node even after limiting it in YAML definition?

**Comment by neolit123** [comment]
please try the support channels:

**Comment by neolit123** [comment]
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
/close
