### ISSUE TITLE
k8s v1.19.3 fails to run on btrfs

### ISSUE THREAD

**Issue by sseneca** [kubernetes/kubernetes#95826]
**What happened**:

I tried to upgrade from v1.18.9 to v1.19.3, but v1.19.3 didn't work on my cluster:

```
Oct 23 10:39:03 sserver k3s[2828239]: F1023 10:39:03.536403 2828239 kubelet.go:1296] Failed to start ContainerManager failed to get rootfs info: failed to get device for dir "/var/lib/kubelet": could not find device with major: 0, minor: 46 in cached partitions map
```

What follows is impressively long (~1600 lines long), the start of which looks like this:

```
Oct 23 10:41:34 sserver k3s[2830467]: goroutine 30629 [running]:
Oct 23 10:41:34 sserver k3s[2830467]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.stacks(0xc000010001, 0xc011152400, 0xe4, 0x1fa)
Oct 23 10:41:34 sserver k3s[2830467]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:996 +0xb9
Oct 23 10:41:34 sserver k3s[2830467]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).output(0x6e952a0, 0xc000000003, 0x0, 0x0, 0xc0092dfc00, 0x6b4d561, 0xa, 0x510, 0x0)
Oct 23 10:41:34 sserver k3s[2830467]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:945 +0x191
Oct 23 10:41:34 sserver k3s[2830467]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).printf(0x6e952a0, 0xc000000003, 0x0, 0x0, 0x451eadb, 0x23, 0xc00ba71cb0, 0x1, 0x1)
Oct 23 10:41:34 sserver k3s[2830467]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:733 +0x17a
Oct 23 10:41:34 sserver k3s[2830467]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.Fatalf(...)
Oct 23 10:41:34 sserver k3s[2830467]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1456
Oct 23 10:41:34 sserver k3s[2830467]: github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet.(*Kubelet).initializeRuntimeDependentModules(0xc003fb8a80)
Oct 23 10:41:34 sserver k3s[2830467]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1296 +0x385 
Oct 23 10:41:34 sserver k3s[2830467]: sync.(*Once).doSlow(0xc003fb92b8, 0xc00b8fbdd0)
Oct 23 10:41:34 sserver k3s[2830467]:         /usr/local/go/src/sync/once.go:66 +0xec
Oct 23 10:41:34 sserver k3s[2830467]: sync.(*Once).Do(...)
```

**What you expected to happen**:

Cluster should be updated to v1.19.3 and run fine.

**How to reproduce it (as minimally and precisely as possible)**:

Install [k3s](k3s.io), version v1.18.9+k3s1. Try to upgrade to v1.19.3+k3s1.

**Anything else we need to know?**:

The drives the server runs on are in RAID 1 using btrfs. https://github.com/rancher/k3s/issues/2422#issuecomment-715255046 suggests that there is some special handling for btrfs that could result in this error message.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.9+k3s1
- Hardware configuration (machine is my own, not the cloud):

```
sserver% sudo btrfs su l /
ID 256 gen 109651 top level 5 path @
ID 259 gen 109650 top level 5 path @home
ID 260 gen 8 top level 5 path @snapshots
ID 261 gen 9 top level 5 path @root
ID 262 gen 31 top level 256 path var/lib/portables
ID 263 gen 32 top level 256 path var/lib/machines
ID 271 gen 109651 top level 256 path var/lib/databases
```
 
- OS (e.g: `cat /etc/os-release`): 
```
PRETTY_NAME="Parabola GNU/Linux-libre"
ID=parabola
ID_LIKE=arch
```
- Kernel (e.g. `uname -a`): `Linux sserver 5.4.69-gnu-1-lts #1 SMP Sun, 04 Oct 2020 20:19:52 +0000 x86_64 GNU/Linux`

**Comment by MarekPikula** [comment]
I had similar problem. I have btrfs root snapshot mounted on / (so no root subvolume), so `/var/lib/kubelet` subvolume is mounted automatically at the appropriate path. I followed kubernetes#65204 (in particular [this](https://github.com/kubernetes/kubernetes/issues/65204#issuecomment-473711839) comment) and saved `/var/lib/kubelet` in fstab with `subvol` flag, so it's explicitly mounted and kubelet starts normally.

**Comment by cr1st1p** [comment]
today I bumped into the same problem, trying to start k8s 1.20.1
Applying the same fix I suggested into https://github.com/kubernetes/kubernetes/issues/65204#issuecomment-473711839
made kubelet go past that step.
Today's fstab line was:
/dev/mapper/vgroot-root /var/lib/kubelet btrfs rw,relatime,ssd,space_cache,subvolid=269,subvol=/var/lib/kubelet 0 0

**Comment by arianvp** [comment]
https://github.com/kubernetes/kubernetes/issues/65204#issuecomment-473711839 suggests the issue comes from the usage of nested subvolumes. However I am running into this issue and do not have a subvolume for `/var` at all. So the mentione workaround doesn't apply.

```
$ sudo btrfs subvol list /
ID 258 gen 33868 top level 5 path nix
ID 260 gen 33884 top level 5 path etc
ID 261 gen 33893 top level 5 path home
ID 268 gen 28940 top level 5 path srv
```

```
Dec 31 16:08:43 ryzen kubelet[22611]: F1231 16:08:43.282774   22611 kubelet.go:1296] Failed to start ContainerManager failed to get rootfs info: failed to get device for dir "/var/lib/kubelet": could not find device with major: 0, minor: 28 in cached partitions map
```

**Comment by arianvp** [comment]
I also get the following error message from `cri_stats_provider.go`:

```
cri_stats_provider.go:376] Failed to get the info of the filesystem with mountpoint "/var/lib/containerd/io.containerd.snapshotter.v1.btrfs": failed to get device for dir "/var/lib/containerd/io.containerd.snapshotter.v1.btrfs": could not find device with major: 0, minor: 28 in cached partitions map.
```

**Comment by arianvp** [comment]
This looks like a duplicate of https://github.com/kubernetes/kubernetes/issues/94335 to me

**Comment by sseneca** [comment]
I think you're right. I've upgraded to k8s v1.20.4 and am not having this issue any more.
