### ISSUE TITLE
Services can select multiple backends

### ISSUE THREAD

**Issue by XanderStrike** [kubernetes/kubernetes#95838]
**What would you like to be added**:

I would like a system whereby Service objects can route to multiple backends that do not share labels (and who's labels I do not control).

https://github.com/kubernetes/kubernetes/issues/48528 describes one possible solution, but it was closed by a bot for no reason.

**Why is this needed**:

In a blue-green deploy case, I would like to have a service pointing at my A set of pods, then both A and B pods, then only B pods.

Changing labels in the pod template of a Deployment/Statefulset/etc causes downtime so this is not an option. Writing a tool to change these labels in an automated way on the pods seems like overkill given that this feature seems straightforward and uncontroversial.

**Comment by krmayankk** [comment]
Typically this use case is solved by uber controllers. A very good example is [ArgoRollouts](https://argoproj.github.io/argo-rollouts/) . While I agree such a solution at k/k is desirable, i think service object presents a low level  primitive(lowest common denominator) on which solutions like that can be built upon

**Comment by thockin** [comment]
Some of your statements aren't clear:

> ... backends that do not share labels

Why can't they share labels?

> ... (and who's labels I do not control).

This is what threw me - you're routing to backends in the same namespace, but you don't control the labels?  That's a pretty significant limitation.

> #48528 describes one possible solution

I commented there.  This is not impossible, and is probably long overdue, honestly, but it will require a KEP and someone to own it.

> In a blue-green deploy case, I would like to have a service pointing at my A set of pods, then both A and B pods, then only B pods.

The way I usually see this is to label the A pods "app=foo, version=a" and the B pods "app=foo, version=b".  Then you can change the service selector from "app=foo, version=a" to "app=foo" and then to "app=foo, version=b".

But that requires that you can dictate which label are applied to pods.  Without that, all sorts of things are impossible.

Ideally we could close this as a dup of #48528 and send all conversation there.  Is that fair?

**Comment by XanderStrike** [comment]
> This is what threw me - you're routing to backends in the same namespace, but you don't control the labels? That's a pretty significant limitation.

Yeah the Deployments are produced by a different [component](https://github.com/cloudfoundry-incubator/eirini) that doesn't know anything about routing. We could ask the developers on that component start keeping track of routing information, but that's an expansion of scope that we know already they're not interested in.

We could write a component to update the labels in the deployment spec, but that will result in pod restarts. We could write selectorless services and create endpoints, but that would potentially introduce misrouting when the endpoint list is out of date. For now our plan is to write a new CRD that has a set based selector and describes a multi-backend service, and a controller that will write the Service and labels the pods appropriately.

Hopefully that gives you a little more insight into our situation.

> Ideally we could close this as a dup of #48528 and send all conversation there. Is that fair?

That issue was closed when I created this one, so I made one that requested an outcome rather than dictating an implementation, hoping that it would create some conversation and potentially people could suggest other implementations that would be more popular.

If it's agreed that set-based selectors are the way to achieve the outcome, and there's some way to guarantee that issue won't be closed, I'm okay with closing this one. If that's not true, I'd rather keep this one around because I know I can reopen it when it's closed by the dumb bot 🙃

**Comment by thockin** [comment]
> Deployments are produced by a different component that doesn't know anything about routing

I thought "surely it lets you set labels" but it I took a look and honestly, I can't see it.  How can a tool purport to target Kubernetes workloads and NOT support setting labels?  It's pretty fundamental...

> For now our plan is to write a new CRD that has a set based selector and describes a multi-backend service

What labels DOES it set, so that you can select the pods at all?  What SetSelector expression would you use?

>> Ideally we could close this as a dup of #48528 and send all conversation there. Is that fair?
>
> That issue was closed when I created this one, so I made one that requested an outcome rather than dictating an implementation, hoping that it would create some conversation and potentially people could suggest other implementations that would be more popular.

Well, I can say with confidence that adding a "modern" selector to Service is totally reasonable and something I can endorse.  Adding something more bespoke to Service is far less interesting.  If you can show me that a new selector would solve your problem, it adds fuel to the fire to implement that.

**Comment by thockin** [comment]
ping on this?

**Comment by XanderStrike** [comment]
I didn't feel like I had confirmation the other issue would not be closed without being resolved. Should I have gotten that from your message? I'm happy to close this as long as there will exist an issue that will not be closed until the outcome in this issue is possible.

The only reason I'm being a stickler about this is that other issue was closed until I made this one. I don't have the ability to reopen that one, but I can keep this one open. Does that make sense?

**Comment by thockin** [comment]
I'm asking "Would #48528 actually solve your problem?"  If so, let's keep that open.  If not, what then?

**Comment by XanderStrike** [comment]
Yes it would solve my problem but it was closed before without being resolved, so there must be some problem with it... right? Why else would it be closed? Has the problem that resulted in it being closed been fixed?

If that issue will stay open until it's resolved then this issue can be closed. If it's going to be closed arbitrarily by a bot then I'll keep this one open. Seems straightforward to me, sorry I'm not communicating well.

**Comment by thockin** [comment]
There are bots that age out issues.  If nobody is working on it and nobody updates it and nobody freezes it, it will eventually be closed.  That doesn't meant there's something wrong, just that we have 2000+ issues and that "seems" dead.  The heuristic can be wrong.  I have frozen it now.

Thanks for the update!
