### ISSUE TITLE
Always-If-Available Image Pull Policy

### ISSUE THREAD

**Issue by Starttoaster** [kubernetes/kubernetes#95854]
**What would you like to be added**:

EDIT: I submitted what I think is a better idea to address the same problem here: https://github.com/kubernetes/kubernetes/issues/99009

An image pull policy that is very much like `Always` but with a catch. General flow on a new pod spinning up as follows:

1. Checks for the latest image on the remote registry
2. Checks for the presence of a locally-cached copy and leverages that first
3. If no locally-cached copy is available, fetches from remote
4. And finally, if the remote registry is unavailable, leverages the most recent locally-cached copy (if available)

**Why is this needed**:

Many people want to use the `Always` image pull policy to ensure that their pods are always getting the latest image version of a given tag on start. The `Always` pull policy assumes that the container registry is 100% available with 0 downtime. In the event that the registry is not available, instead of falling back on a local cache, the pod will fail to start up.

Note that I don't believe this is an issue with the `Always` image pull policy. I just think there is an appetite for something like `Always` but with a bit more flexibility.

These is an issue open with GitLab for the same image pull policy concept for their GitLab Runner project: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/26558

**Comment by snowsky** [comment]
This is a nice feature to have. Sometimes I need the image to be pulled so have to update this attribute to Always.

**Comment by chillosu** [comment]
Anyone want to take a shot at setting this standard? There is too high of a reliance upon the registry to always be up, and the benefits of always getting the latest is just as important as the resilience to be able to run an image you already have cached locally.

**Comment by ehashman** [comment]
This is sort of a duplicate of #99009 so I think we should keep that issue as the discussion issue, since it's more general. We can consider falling back on more limited scope like this and close it for now.

Seems like a fair idea but we don't have anyone currently working on such a thing, and we would need a detailed design proposal. Since this would involve an API change, we would likely need a KEP.

/close
