### ISSUE TITLE
Replace ETCD with other KV storage

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#95859]
**What would you like to be added**:

We'd like to have an interface for apiserver backend storage, so we can use other KV storage instead of 

**Why is this needed**:

We'd like to improve the performance and support DR :)

/sig api-machinery

**Comment by dims** [comment]
please start with a KEP :)

**Comment by k82cn** [comment]
> please start with a KEP :)

That's great if the direction is overall ok to us :)

**Comment by krmayankk** [comment]
Is it a requirement that the KV storage must support watch functionality ? How much of apiserver functionality is dependent on that feature ?

**Comment by krmayankk** [comment]
@k82cn  do you mean etcd performance is reaching its limit ? From an interface point of view, does [kine](https://github.com/rancher/kine) fit the bill

**Comment by dims** [comment]
> > please start with a KEP :)
> 
> That's great if the direction is overall ok to us :)

It's not ok. But you can try to convince :)

**Comment by k82cn** [comment]
> @k82cn do you mean etcd performance is reaching its limit ? From an interface point of view, does [kine](https://github.com/rancher/kine) fit the bill

maybe not; IMO, it's not ready on stability & performance.

**Comment by k82cn** [comment]
> > > please start with a KEP :)
> > 
> > 
> > That's great if the direction is overall ok to us :)
> 
> It's not ok. But you can try to convince :)

Aha, ok, I'll start with a KEP for that.

**Comment by hoyho** [comment]
> > > > please start with a KEP :)
> > > 
> > > 
> > > That's great if the direction is overall ok to us :)
> > 
> > 
> > It's not ok. But you can try to convince :)
> 
> Aha, ok, I'll start with a KEP for that.

Not sure what interface backend storage have. IMO, If there's a more common interface for generic backend storage can be better(not only KV storage) .
For example. Other Kubernetes distribution like Rancher K3s can use MySQL or even SQLite as the backend.

**Comment by dims** [comment]
@hoyho we have talked about this quite a few times in sig-architecture calls and consistently ended with the opposite result. So let's not waste time in debating this in an issue. If you want to do this, then please write a KEP and argue for it.

**Comment by k82cn** [comment]
/assign k82cn

I'm going to write a KEP and argue for it :) 

@deads2k , @dims , would you share some history about this discussion?

**Comment by deads2k** [comment]
> /assign k82cn
> 
> I'm going to write a KEP and argue for it :)
> 
> @deads2k , @dims , would you share some history about this discussion?

We (@lavalamp, myself, and a few others) wrote a position paper about storage extensions: https://docs.google.com/document/d/1i0xzRFB-uGLmLYueLMBTpHrOot9ScFxpkkcVcZHVbyA/edit# .  The bit that most concerns a different storage implementation is that we are not looking to merge "implementations of the existing interface that merely target a different storage vendor (i.e., anything not etcd3)".  We also enumerated what we would be looking for, closing with "We are interested in effort spent on making the existing storage.Interface cross process boundaries, as long as there is a path towards adding the above features in a backwards-compatible way".  

I'm still of the opinion that adding an alternative storage interface implementation to support a different vendor isn't the direction we want to go and looking back on what we came up with in that doc, I think it holds up three years later.  If you're interested in starting a design that aligns with the direction we outlined in option 3 of that doc, I think it's a lot of work and I would suggest trying to find a way to start out tree, but it would be valuable.  But simply swapping for a different storage that doesn't use the etcd3 API isn't a direction we're looking to go.

/close

**Comment by lavalamp** [comment]
A few additional thoughts:

Please use the approach of https://github.com/rancher/kine to solve this problem.

API Machinery doesn't have review bandwidth to tackle this right now, even if we were convinced it was necessary. And I really don't think you can convince us with the reasons given in the OP, "improve the performance and support DR" -- I don't see etcd as a barrier to either of those things, and I have disaster-recovered (well, near disaster--no total disasters so far) some very large clusters.

So, I don't recommend writing a KEP at this point. I don't think it's possible to gather consensus for this. I'm willing to have a small VC if you want to try and convince me.

**Comment by k82cn** [comment]
> Please use the approach of https://github.com/rancher/kine to solve this problem.

kine is not acceptable which reduce the stability of our system.

> If you're interested in starting a design that aligns with the direction we outlined in option 3 of that doc, I think it's a lot of work and I would suggest trying to find a way to start out tree, but it would be valuable. But simply swapping for a different storage that doesn't use the etcd3 API isn't a direction we're looking to go.

I'm going to go through the doc to see what we can do on that.

**Comment by lavalamp** [comment]
What is wrong with kine? And why can it not be fixed?
