### ISSUE TITLE
Control Plane level Image Caching

### ISSUE THREAD

**Issue by Starttoaster** [kubernetes/kubernetes#95862]
**What would you like to be added**:

Container image caching at the control plane level that pushes its cache to new nodes (such as when the cluster scales horizontally) as needed.

**Why is this needed**:

When new nodes are added to a cluster, they don't contain any of the local image caches yet that the other worker nodes have acquired. When pods are scheduled to this new node, they may be looking for a container image against a registry that has experienced some downtime (eg. Docker Hub becomes unavailable, and pods cannot pull the required image.) Since that pod was unable to pull an image, and it was scheduled on a new node with no locally cached version, the pod just fails to kick off.

What _would_ be nice is if the control plane could get acquire copies of the worker node caches, and the image is pulled to the control plane and pushed to the new worker. 

I could see this potentially being implemented a couple different ways, but just a couple ideas to describe what I was thinking:

1. The control plane contains a copy of all images cached on workers at all times. New nodes can either count on reaching out to the image registry, or else be given an image (if available) that was cached at the control plane layer.

2. Worker node requests an image that isn't locally available, and the image registry is down. The control plane recognizes this and begins making requests to the kubelet on other workers. If the image is found on a worker, the control plan receives a copy of that image from the kubelet, and sends it to the kubelet on the node that was originally asking for it to be cached locally over there.

**Comment by neolit123** [comment]
this feels like the responsibility of higher level infrastructure (that manages the nodes) than the core components such as the kubelet.

**Comment by pacoxu** [comment]
Some thoughts on this requirement.

Option 1: a pull through cache proxy
https://docs.docker.com/registry/recipes/mirror/#run-a-registry-as-a-pull-through-cache

Option 2: local caching registry
https://github.com/rpardini/docker-registry-proxy
An HTTPS Proxy for Docker providing centralized configuration and caching of any registry (quay.io, DockerHub, k8s.gcr.io)

Option 3: manage images in your servers with dragonfly or something
https://github.com/dragonflyoss/Dragonfly
