### ISSUE TITLE
Investigate node-kubelet-conformance test failures

### ISSUE THREAD

**Issue by mmerkes** [kubernetes/kubernetes#95877]
**Which jobs are failing**:

[node-kubelet-conformance suite](https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-conformance&show-stale-tests=)

**Which test(s) are failing**:

The tests are failing in the `BeforeSuite`.

**Since when has it been failing**:

10/23/2020

**Testgrid link**:

https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-conformance

**Reason for failure**:

It started failing at commit `237dae5a5`, but it's unknown if it's related to that.

**Anything else we need to know**:

We discussed in the Kubernetes SIG-Node CI subgroup and will start taking a look at it.

**Comment by mmerkes** [comment]
[Commit when it started failing looks benign.](https://github.com/kubernetes/kubernetes/commit/237dae5a5)

**Comment by mmerkes** [comment]
Investigation notes:

1. Compared `docker.log` between successful and unsuccessful runs and found no notable differences.
2. `cloud-init.log`, `kern.log` and `serial-1.log`
3. `kubelet-launcher.log` had a couple of failed health checks on initialization, which doesn't happen in the successful test runs, though there's only 2 seconds between starting readiness checks and an eventual successful check.
4. CNI config the same between runs
5. Started looking through the kubelet logs for [a run that succeeded](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-conformance/1319698696010469376) and [a run that failed](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-conformance/1321099408158232576), but I haven't found anything interesting yet.

**kubelet-launcher.log failed health checks**

```
I1027 14:48:18.894064    2832 util.go:48] Running readiness check for service "kubelet"
W1027 14:48:19.881473    2832 util.go:104] Health check on "http://127.0.0.1:10255/healthz" failed, error=Head "http://127.0.0.1:10255/healthz": dial tcp 127.0.0.1:10255: connect: connection refused
W1027 14:48:19.894487    2832 util.go:104] Health check on "http://127.0.0.1:10255/healthz" failed, error=Head "http://127.0.0.1:10255/healthz": dial tcp 127.0.0.1:10255: connect: connection refused
I1027 14:48:20.895858    2832 server.go:182] Initial health check passed for service "kubelet"
```

### Errors occurring in successful and unsuccessful runs

The below is a list of errors that occur in runs that succeeded and failed, which may be due to startup or specific testing scenarios.

```
kubelet[2882]: I1027 14:48:19.608207    2882 client.go:77] Connecting to docker on unix:///var/run/docker.sock
kubelet[2882]: I1027 14:48:19.608230    2882 client.go:94] Start docker client with request timeout=2m0s
kubelet[2882]: I1027 14:48:19.614155    2882 docker_service.go:241] Hairpin mode set to "promiscuous-bridge"
kubelet[2882]: I1027 14:48:19.617852    2882 cni.go:208] Using CNI configuration file /tmp/node-e2e-20201027T144755/cni/net.d/mynet.conf
kubelet[2882]: I1027 14:48:19.620223    2882 iptables.go:688] couldn't get iptables-restore version; assuming it doesn't support --wait
kubelet[2882]: I1027 14:48:19.622236    2882 iptables.go:688] couldn't get iptables-restore version; assuming it doesn't support --wait
kubelet[2882]: I1027 14:48:19.632916    2882 plugins.go:168] Loaded network plugin "kubenet"
```

Bunch of these for numerous containers:
```
kubelet[2973]: I1023 18:03:00.842429    2973 factory.go:216] Factory "containerd" was unable to handle container "/runtime.slice/kubelet-20201023T180230.service"
kubelet[2973]: I1023 18:03:00.842434    2973 factory.go:216] Factory "systemd" was unable to handle container "/runtime.slice/kubelet-20201023T180230.service"
kubelet[2973]: I1023 18:03:00.842439    2973 factory.go:216] Factory "docker" was unable to handle container "/runtime.slice/kubelet-20201023T180230.service"
kubelet[2973]: I1023 18:03:00.842450    2973 factory.go:209] Factory "raw" can handle container "/runtime.slice/kubelet-20201023T180230.service", but ignoring.
```

```
kubelet[2882]: E1027 14:48:20.360925    2882 kubelet.go:2238] node "tmp-node-e2e-4c860624-ubuntu-gke-1804-1-16-v20200330" not found
kubelet[2882]: I1027 14:48:20.370157    2882 setters.go:794] Error getting volume limit for plugin kubernetes.io/gce-pd
kubelet[2882]: I1027 14:48:20.370172    2882 setters.go:794] Error getting volume limit for plugin kubernetes.io/cinder
kubelet[2882]: I1027 14:48:20.370180    2882 setters.go:794] Error getting volume limit for plugin kubernetes.io/azure-disk
kubelet[2882]: I1027 14:48:20.370191    2882 setters.go:794] Error getting volume limit for plugin kubernetes.io/aws-ebs
```

```
kubelet[2882]: I1027 14:48:24.936458    2882 csi_plugin.go:994] Failed to contact API server when waiting for CSINode publishing: Get "https://127.0.0.1:6443/apis/storage.k8s.io/v1/csinodes/tmp-node-e2e-4c860624-ubuntu-gke-1804-1-16-v20200330": dial tcp 127.0.0.1:6443: connect: connection refused
```

```
kubelet[2973]: E1023 18:03:02.534424    2973 kubelet_node_status.go:92] Unable to register node "tmp-node-e2e-45e5bb9d-ubuntu-gke-1804-1-16-v20200330" with API server: Post "http://localhost:8080/api/v1/nodes": dial tcp 127.0.0.1:8080: connect: connection refused
```

**Comment by mmerkes** [comment]
Both new and old test runs have a bunch of logs like this, implying that it's been having issues for a while:

```
kubelet[2973]: I1023 18:03:15.736964    2973 csi_plugin.go:994] Failed to contact API server when waiting for CSINode publishing: Get "http://localhost:8080/apis/storage.k8s.io/v1/csinodes/tmp-node-e2e-45e5bb9d-ubuntu-gke-1804-1-16-v20200330": dial tcp 127.0.0.1:8080: connect: connection refused
kubelet[2973]: I1023 18:03:16.073737    2973 reflector.go:255] Listing and watching *v1.Node from k8s.io/kubernetes/pkg/kubelet/kubelet.go:437
kubelet[2973]: E1023 18:03:16.074648    2973 reflector.go:138] k8s.io/kubernetes/pkg/kubelet/kubelet.go:437: Failed to watch *v1.Node: failed to list *v1.Node: Get "http://localhost:8080/api/v1/nodes?fieldSelector=metadata.name%3Dtmp-node-e2e-45e5bb9d-ubuntu-gke-1804-1-16-v20200330&limit=500&resourceVersion=0": dial tcp 127.0.0.1:8080: connect: connection refused
```

The failed one has this additional line:

```
kubelet[2882]: E1027 14:48:19.936963    2882 controller.go:144] failed to ensure lease exists, will retry in 200ms, error: Get "https://127.0.0.1:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/tmp-node-e2e-4c860624-ubuntu-gke-1804-1-16-v20200330?timeout=10s": dial tcp 127.0.0.1:6443: connect: connection refused
```

However, the `node-kubelet-master` doesn't have the same issues. I don't see the connection timeouts at all. I also don't see anything else in the kubelet logs that appears different between successful and failed runs. Unfortunately, I don't know enough about the infrastructure setup, but here are my current theories:

1. Something about the infrastructure has gotten progressively more overloaded and now it's falling over.
  - The `node-kubelet-master` tests run on 8 nodes versus 1, so they have more capacity there.
  - Not totally buying this because why did it go from mostly successful to 100% failures rather than a mix for a bit.
2. Something changed in the GCE configuration. Not sure how that is managed.

**Comment by MHBauer** [comment]
Diff there suggests three merges from k/k https://github.com/kubernetes/kubernetes/compare/1fcd02cc2...237dae5a5
Only merge in test-infra is an image bump https://github.com/kubernetes/test-infra/compare/dcfd6f385...18bef7827
<img width="215" alt="image" src="https://user-images.githubusercontent.com/13337345/97486687-0729f880-1919-11eb-961d-d3edc233df82.png">

Interesting that a similar ci version and pull version of the job passes and the one ci version does not.
pull: https://github.com/kubernetes/test-infra/blob/8dcb569da563a3e43b10043ec1a4eac537db3af4/config/jobs/kubernetes/sig-node/sig-node-presubmit.yaml#L3-L43
passing ci: https://github.com/kubernetes/test-infra/blob/8dcb569da563a3e43b10043ec1a4eac537db3af4/config/jobs/kubernetes/sig-node/node-kubelet.yaml#L2-L41
failing ci: https://github.com/kubernetes/test-infra/blob/cad49738775e76f1ccec22702ad666bdfd81d5be/config/jobs/kubernetes/sig-node/node-kubelet.yaml#L73-L106

The failing ones do not have a node_e2e services.log, but I don't see any of the expected log messages for failure of the services to start.

**Comment by mmerkes** [comment]
@MHBauer It is interesting that one passes and one does not. Primary differences are the number of nodes, resource settings, and the fact that the conformance tests use Docker.

**Comment by MHBauer** [comment]
In addition to the services log missing, the overall system run logs are also missing.

May be related to any decision we make for https://github.com/kubernetes/test-infra/issues/18973

**Comment by mmerkes** [comment]
@MHBauer Would we be able to kick off a Prow job with custom configuration? In other words, to rule in or rule out something in the image change, can we kick off a job with the latest everything else but use the older image?

In reference to the decision on https://github.com/kubernetes/test-infra/issues/18973, are you suggesting we pause investigation and see if we decide to just move or change the conformance tests?

**Comment by alejandrox1** [comment]
Catching up on this. qq: has anyone vetted https://github.com/kubernetes/kubernetes/pull/94723/files ?
Ise that pr went in around the time this job began to fail https://github.com/kubernetes/kubernetes/compare/1fcd02cc2...237dae5a5

The beforesuite (**AI**: we should list out what it does), fails to communicate with nodes
```
I1023 20:03:09.965] Failure [15.352 seconds]
I1023 20:03:09.965] [BeforeSuite] BeforeSuite 
I1023 20:03:09.966] _output/local/go/src/k8s.io/kubernetes/test/e2e_node/e2e_node_suite_test.go:177
I1023 20:03:09.966] 
I1023 20:03:09.966]   should be able to list nodes.
      
I1023 20:03:09.966]   Unexpected error:
I1023 20:03:09.966]       <*url.Error | 0xc000b0a570>: {
I1023 20:03:09.966]           Op: "Get",
I1023 20:03:09.966]           URL: "https://127.0.0.1:6443/api/v1/nodes",
I1023 20:03:09.966]           Err: {
I1023 20:03:09.967]               Op: "dial",
I1023 20:03:09.967]               Net: "tcp",
I1023 20:03:09.967]               Source: nil,
I1023 20:03:09.967]               Addr: {
I1023 20:03:09.967]                   IP: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 127, 0, 0, 1],
I1023 20:03:09.967]                   Port: 6443,
I1023 20:03:09.967]                   Zone: "",
I1023 20:03:09.967]               },
I1023 20:03:09.968]               Err: {Syscall: "connect", Err: 0x6f},
I1023 20:03:09.968]           },
I1023 20:03:09.968]       }
I1023 20:03:09.968]       Get "https://127.0.0.1:6443/api/v1/nodes": dial tcp 127.0.0.1:6443: connect: connection refused
I1023 20:03:09.968]   occurred
I1023 20:03:09.968] 
I1023 20:03:09.968]   _output/local/go/src/k8s.io/kubernetes/test/e2e_node/e2e_node_suite_test.go:315
```

the mention of 6443 ports looks interesting here.

**Comment by mmerkes** [comment]
@alejandrox1 Good find. Definitely looks suspicious. I'll dig into that.

**Comment by mmerkes** [comment]
From [kubelet-launcher.log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-conformance/1323291406541787136/artifacts/tmp-node-e2e-f98b7645-ubuntu-gke-1804-1-16-v20200330/kubelet-launcher.log):

```
Unable to find in-cluster config, using default host : https://127.0.0.1:6443
```

This comes from [this file](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/remote/node_conformance.go), which has some node-conformance specific test setup, so maybe something interesting there.

**Comment by alejandrox1** [comment]
quick interruption for instructions on how to reproduce this one:
I think this may work

```
make test-e2e-node FOCUS="\[NodeConformance\]" SKIP="\[Flaky\]"  REMOTE=true DELETE_INSTANCES=true  IMAGE_CONFIG_FILE=node-test.yaml
```

**Focus and skip**
The FOCUS and SKIP arguments im getting from https://github.com/kubernetes/test-infra/blob/48f2834380836b283d700833975a8162b392dfe4/config/jobs/kubernetes/sig-node/node-kubelet.yaml#L95

**Image config file**
The job also uses the following config file https://github.com/kubernetes/test-infra/blob/48f2834380836b283d700833975a8162b392dfe4/config/jobs/kubernetes/sig-node/node-kubelet.yaml#L91
https://github.com/kubernetes/test-infra/blob/master/jobs/e2e_node/image-config.yaml
Make sure to copy it and name it `node-test.yaml` (the argument to IMAGE_CONFIG_FILE above).

**Additional arguments**
The test args to this job are 
https://github.com/kubernetes/test-infra/blob/48f2834380836b283d700833975a8162b392dfe4/config/jobs/kubernetes/sig-node/node-kubelet.yaml#L92

I think these are the defaults already but just in case may be actually useful to add the following to the above command
```
TEST_ARGS='--feature-gates=DynamicKubeletConfig=true --kubelet-flags="--cgroups-per-qos=true --cgroup-root=/"'
```

**Miscellaneous**
If you run into trouble with the above commands try going through https://github.com/contributing-to-kubernetes/gnosis/tree/master/stories/e2e-node-tests

The info here came from https://github.com/kubernetes/community/blob/master/contributors/devel/sig-node/e2e-node-tests.md

**Comment by mmerkes** [comment]
You'll also need to use the `--test-suite=conformance` flag to make sure it runs in Docker, I believe.

**Comment by alejandrox1** [comment]
ah yeah, good catch!
Thank you.
Don't know about your availability, but if you are all busy ima allocate sometime later today to dive deeper into the info we have here

**Comment by mmerkes** [comment]
I'm going to try to spend time of this in the afternoon (PDT). Specifically, I was going to try to verify that the logs from starting up the test suite look as expected and possibly try to run the case to reproduce.

**Comment by knabben** [comment]
My first suspicion was to have the server running in another port than 6443 (which Kubelet has configured), this is not the case:

```
tcp        0      0 127.0.0.1:6443          0.0.0.0:*               LISTEN      4852/e2e_node.test
```

Only o.SecureServing.BindAddress is being set explicitly. The port comes from o.NewServerRunOptions().

https://github.com/kubernetes/kubernetes/compare/1fcd02cc2...237dae5a5#diff-b5a4e5df0272f9d9dfff0c02b7ec81ab12c3fb598b11c3aced10c296bf8558cdR57

**Comment by MHBauer** [comment]
I think it's related to the movement of this line.
I couldn't figure out how to link to the PR so I made a comment.
https://github.com/kubernetes/kubernetes/pull/94723/files#r516304908

**Comment by knabben** [comment]
@MHBauer as you notice before there's no services.log, and we should be seeing

```
I1023 18:11:11.837] PASS
I1023 18:11:11.837] I1023 18:03:28.523263      13 server.go:102] Starting server "services" with command "/usr/local/bin/e2e_node.test --run-services-mode --test.timeout=24h0m0s --ginkgo.seed=1603476176 --ginkgo.focus=\\[Conformance\\] --ginkgo.skip=\\[Flaky\\]|\\[Serial\\] --ginkgo.flakeAttempts=2 --ginkgo.parallel.node=1 --ginkgo.parallel.total=8 --ginkgo.parallel.streamhost=http://127.0.0.1:35341 --ginkgo.parallel.synchost=http://127.0.0.1:35341 --ginkgo.slowSpecThreshold=5.00000 --conformance=true --prepull-images=false --report-dir=/var/result --system-spec-name= --system-spec-file= --extra-envs= --report-prefix=cos-stable1"
```

Before:

```
I1023 18:11:11.838] I1023 18:03:49.655233      13 e2e_node_suite_test.go:197] Node services started.  Running tests...
I1023 18:11:11.838] I1023 18:03:49.655269      13 e2e_node_suite_test.go:202] Wait for the node to be ready
```

**Comment by MHBauer** [comment]
I can repro the issue now, and I think the line was moved upward to generate the token before starting the kubelet.
Moving it up out of the if-statement may help partially, but in the conformance test the kubelet is manually started ahead of this code, so it may not matter.

**Comment by mmerkes** [comment]
Make sense. Do you mean moving this out of the conformance check?

```
if e.services, err = e.startInternalServices(); err != nil {
        return fmt.Errorf("failed to start internal services: %v", err)
}
```

**Comment by MHBauer** [comment]
Haha, yea, that message is deceptive... 

I think I'll make a PR to at least let it be more correct and give us more info.

**Comment by MHBauer** [comment]
for alerts to subscribers, PR #96128 created. Please comment.

**Comment by MHBauer** [comment]
looking green!

**Comment by MHBauer** [comment]
The output looks very strange, I have no idea why. 
Output has double-underscore-number for the different runs, instead of the image used. 
[__08] vs [cos-lts]

**Comment by mmerkes** [comment]
Ya, I noticed that. It's weird. Not sure how it's set, but you can see that the junit config names have a similar issue:

[master](https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet/1323994100789153792/artifacts/) ->  junit_cos-stable1_01.xml

[conformance](https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-conformance/1323991582642278400/artifacts/) ->  junit__01.xml

**Comment by mmerkes** [comment]
Ok, found the root of the problem. Here's the command for the master suite:

```
Starting server "services" with command "/tmp/node-e2e-20201104T173208/e2e_node.test --run-services-mode --bearer-token=P8SJh4nD-p-M40J- --test.timeout=24h0m0s --ginkgo.seed=1604511138 --ginkgo.focus=\\[NodeConformance\\] --ginkgo.skip=\\[Flaky\\]|\\[Serial\\] --ginkgo.parallel.node=1 --ginkgo.parallel.total=8 --ginkgo.parallel.streamhost=http://127.0.0.1:36665 --ginkgo.parallel.synchost=http://127.0.0.1:36665 --ginkgo.slowSpecThreshold=5.00000 --system-spec-name= --system-spec-file= --extra-envs= --logtostderr --v 4 --node-name=tmp-node-e2e-5d8b4411-cos-85-13310-1041-24 --report-dir=/tmp/node-e2e-20201104T173208/results --report-prefix=cos-stable1 --image-description=cos-85-13310-1041-24 --kubelet-flags=--experimental-mounter-path=/tmp/node-e2e-20201104T173208/mounter --kubelet-flags=--kernel-memcg-notification=true --kubelet-flags=--cgroups-per-qos=true --cgroup-root=/"
```

Note `--report-prefix=cos-stable1 `, which is not present in the conformance tests.
