### ISSUE TITLE
timeBudget shouldn't depend on the real clock

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#95875]
Instead of relying on the clock:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/cacher/time_budget.go#L60

 we should do something similar to the golang rate-limitter is doing:
https://github.com/kubernetes/kubernetes/blob/master/vendor/golang.org/x/time/rate/rate.go#L306-L331

**Comment by obeyda** [comment]
Hi, I would like to help on this.

**Comment by roycaihw** [comment]
/assign @obeyda
Thanks!
/triage accepted

**Comment by obeyda** [comment]
@wojtek-t, can you please provide more context or some guidance on how to proceed?

**Comment by wojtek-t** [comment]
Sorry for delayed response.

@obeyda - what we should do is to basically:
- instead of having an additional go-routine that every 1s refreshes the budget
- change it roughly to:
(a) keep the value of budget and the last time when we were refreshing it
(b) on takeAvailable method:
  - first recompute takeAvailable, which will be "min(current budget + time elapsed since last refresh * refreshValue, maxAllowedBudget)
 - update last refresh time to now
 - return that value

[We also would need to update the existing tests to match the new logic.]

@obeyda - would you be willing to work on it?

**Comment by palnabarun** [comment]
@wojtek-t -- I can take this up. One question I had was should the `takeAvailable` method rely on `time.Now()` or the current time should be passed on by the caller like in the following:

https://github.com/kubernetes/kubernetes/blob/master/vendor/golang.org/x/time/rate/rate.go#L307-L310

Having the caller pass the time completely removes the dependency on the clock.

**Comment by wojtek-t** [comment]
>  One question I had was should the takeAvailable method rely on time.Now() or the current time should be passed on by the caller like in the following:

Let's may be start with:
- passing `clock.Clock` on budget creation to it
- relying on `clock.Now()`

**Comment by palnabarun** [comment]
@wojtek-t -- thank you for the thoughts. I drafted a rough implementation in #96707 which still depends on `time`. I will make the change as you suggested and rely solely on a `clock.Clock` instance passed on initialization. I have to rethink the testing strategy a bit, possibly using a `clock.FakeClock`.

**Comment by wojtek-t** [comment]
Yes - FakeClock is the way to test this.

**Comment by wojtek-t** [comment]
Reopening - this didn't happen.
