### ISSUE TITLE
JSONpath support: change in behaviour over versions

### ISSUE THREAD

**Issue by rakshit-simha** [kubernetes/kubernetes#95882]
**What happened**: `kubectl get pods -o=jsonpath='{range .items[*]}.....{end}'` throws errors if no pods are found in v1.19.3, but returns success with empty response in v1.16.8

**What you expected to happen**: If there are no pods that return, no error should be thrown as the range should evaluate to "no op".

**How to reproduce it (as minimally and precisely as possible)**:  Adapt the example from https://kubernetes.io/docs/reference/kubectl/jsonpath/ to get the command `kubectl get pods -o=jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}'`.  Run this when there are pods in default namespace - all is well.  Run this when there are no pods in default namespace and you get the error:
```
error: error executing jsonpath "{range .items[*]}{.metadata.name}{\"\\n\"}{end}": Error executing template: not in range, nothing to end. Printing more information for debugging the template:
        template was:
                {range .items[*]}{.metadata.name}{"\n"}{end}
        object given to jsonpath engine was:
                map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":"", "selfLink":""}}
```

**Anything else we need to know?**: This breaks all kinds of code that relies on jsonpath's earlier behaviour.   I found an old report (https://github.com/kubernetes/kubernetes/issues/37991) that seems appropriate, but that is long since merged and closed.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.3
- Cloud provider or hardware configuration: x86-64
- OS (e.g: `cat /etc/os-release`): RedHat Enterprise Linux 7.6 (Maipo)
- Kernel (e.g. `uname -a`): `Linux master.example.com 3.10.0-1127.el7.x86_64 #1 SMP Wed Apr 1 10:20:09 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: n/a
- Network plugin and version (if this is a network-related bug): n/a
- Others: n/a

**Comment by roycaihw** [comment]
/assign @brianpursley 
cc @caesarxuchao 
/triage accepted
