### ISSUE TITLE
sched: concurrent map read/write when scheduler plugins write to `CycleState` during the Filter phase

### ISSUE THREAD

**Issue by fabiokung** [kubernetes/kubernetes#95887]
**What happened**:

kube-scheduler (`v1.18.8`) crashes due to a panic while running `FilterPlugins`:

```
fatal error: concurrent map read and map write
goroutine 2987 [running]:
runtime.throw(0x1c4d8ef, 0x21)
        /usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc0063e5aa8 sp=0xc0063e5a78 pc=0x4313a2
runtime.mapaccess2_faststr(0x1962280, 0xc007448a80, 0x1c3fb4e, 0x19, 0x2, 0xc00b429b00)
        /usr/local/go/src/runtime/map_faststr.go:116 +0x48f fp=0xc0063e5b18 sp=0xc0063e5aa8 pc=0x414def
k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1.(*CycleState).Read(...)
        /go/pkg/mod/k8s.io/kubernetes@v1.18.8/pkg/scheduler/framework/v1alpha1/cycle_state.go:92
k8s.io/kubernetes/pkg/scheduler/framework/plugins/interpodaffinity.getPreFilterState(0xc007448ab0, 0x171a100, 0xc007448960, 0x1)
        /go/pkg/mod/k8s.io/kubernetes@v1.18.8/pkg/scheduler/framework/plugins/interpodaffinity/filtering.go:389 +0x54 fp=0xc0063e5b90 sp=0xc0063e5b18 pc=0x17238f4
k8s.io/kubernetes/pkg/scheduler/framework/plugins/interpodaffinity.(*InterPodAffinity).Filter(0xc0004df400, 0x1f2a7c0, 0xc001a18c80, 0xc007448ab0, 0xc006f38c00, 0xc006944d00, 0x0)
        /go/pkg/mod/k8s.io/kubernetes@v1.18.8/pkg/scheduler/framework/plugins/interpodaffinity/filtering.go:517 +0x40 fp=0xc0063e5c48 sp=0xc0063e5b90 pc=0x1724690
k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1.(*framework).runFilterPlugin(0xc0000b1500, 0x1f2a7c0, 0xc001a18c80, 0x7f6dc63f0b30, 0xc0004df400, 0xc007448ab0, 0xc006f38c00, 0xc006944d00, 0x0)
        /go/pkg/mod/k8s.io/kubernetes@v1.18.8/pkg/scheduler/framework/v1alpha1/framework.go:457 +0x87 fp=0xc0063e5cc0 sp=0xc0063e5c48 pc=0x1710187
k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1.(*framework).RunFilterPlugins(0xc0000b1500, 0x1f2a7c0, 0xc001a18c80, 0xc007448ab0, 0xc006f38c00, 0xc006944d00, 0xc006944d00)
        /go/pkg/mod/k8s.io/kubernetes@v1.18.8/pkg/scheduler/framework/v1alpha1/framework.go:433 +0xf1 fp=0xc0063e5dd0 sp=0xc0063e5cc0 pc=0x170fca1
k8s.io/kubernetes/pkg/scheduler/core.(*genericScheduler).podPassesFiltersOnNode(0xc000449480, 0x1f2a7c0, 0xc001a18c80, 0xc000753e20, 0xc007448ab0, 0xc006f38c00, 0xc006944d00, 0xc0071ed700, 0xc006e67dc0
        /go/pkg/mod/k8s.io/kubernetes@v1.18.8/pkg/scheduler/core/generic_scheduler.go:611 +0x120 fp=0xc0063e5e58 sp=0xc0063e5dd0 pc=0x17895f0
k8s.io/kubernetes/pkg/scheduler/core.(*genericScheduler).findNodesThatPassFilters.func1(0x2d)
        /go/pkg/mod/k8s.io/kubernetes@v1.18.8/pkg/scheduler/core/generic_scheduler.go:457 +0xfc fp=0xc0063e5f08 sp=0xc0063e5e58 pc=0x178c82c
k8s.io/client-go/util/workqueue.ParallelizeUntil.func1(0xc006c28790, 0xc001210400, 0xc0002ab6c0, 0xc0071b3710)
        /go/pkg/mod/k8s.io/client-go@v0.18.8/util/workqueue/parallelizer.go:57 +0xbf fp=0xc0063e5fc0 sp=0xc0063e5f08 pc=0x1015f3f
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0063e5fc8 sp=0xc0063e5fc0 pc=0x460fd1
created by k8s.io/client-go/util/workqueue.ParallelizeUntil
        /go/pkg/mod/k8s.io/client-go@v0.18.8/util/workqueue/parallelizer.go:49 +0x148
```

The race condition is triggered when an out-of-tree plugin, that writes to `CycleState` during its Filter phase, is registered through `PluginFramework`. Access to `cycleState` in general happens from a single goroutine and there are no practical concurrency issues, with the exception of the `Filter` phase, that parallelizes calls for each node across plugins: https://github.com/kubernetes/kubernetes/blob/v1.18.8/pkg/scheduler/core/generic_scheduler.go#L490

A quick glance at the tip of the `main` branch seems to indicate the bug is still present there.

**What you expected to happen**:

Ideally access to `CycleState` should be synchronized everywhere for correctness, including by all in-tree plugins, since there are no guarantees about how `PluginFramework` will call multiple plugins concurrently. It seems to me it is something that was considered at some point, given that `type CycleState` has `Lock/Unlock` methods. Sadly, almost no in-tree plugins are synchronizing access.

For now, I will try to work around the problem by doing a single write to `CycleState` during `PreFilter` and storing a data bag structure where I will write state into during `Filter` (with proper synchronization), instead of writing to `CycleState` directly.

**How to reproduce it (as minimally and precisely as possible)**:

Install a scheduler plugin that writes to `CycleState` during its `Filter` phase. In-tree (builtin) plugins are not synchronizing their access to `CycleState`.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.8
- Cloud provider or hardware configuration: linux-amd64 (AWS)
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.5 LTS (Bionic Beaver)
- Others: custom kube-scheduler binary built with an out-of-tree plugin using `Go 1.13.15`

**Comment by adtac** [comment]
AFAICT all in-tree plugins write to the cycle state in PreFilter and then *only* read from cycle state in Filter. So this shouldn't be a problem with in-tree plugins as concurrent read access should be fine during RunFilterPlugins. But since your out-of-tree plugin writes in Filter, I can see why this can be a problem.

Aside from adding Lock/Unlock in in-tree plugin, offering mutual exclusion on each key as a built-in feature within CycleState could be an alternative solution. This way, reads from in-tree plugins during Filter wouldn't interfere with writes during Filter from out-of-tree plugins.

**Comment by adtac** [comment]
cc @ahg-g

**Comment by ahg-g** [comment]
@adtac @alculquicondor @Huang-Wei should we change the Read/Write CycleState methods to be thread safe?

**Comment by alculquicondor** [comment]
Adding locks without a proper reason would just increase the latency.

@fabiokung could you clarify your use case? Why do you need to write anything during Filter?

**Comment by ahg-g** [comment]
> Adding locks without a proper justification would just increase the latency.

yeah, we should measure it, but I don't expect it to have significant effect...

**Comment by adtac** [comment]
>Adding locks without a proper justification would just increase the latency.

Without contention (which is the case with in-tree plugins), I don't think this is a concern.

**Comment by adtac** [comment]
Adapting source from [here](https://stackoverflow.com/questions/57562606/why-does-sync-mutex-largely-drop-performance-when-goroutine-contention-is-more-t):

```
goos: linux
goarch: amd64
BenchmarkMutexWrite/goroutines-0-8         	90415360	        11.3 ns/op
BenchmarkMutexWrite/goroutines-8-8         	29660856	        47.4 ns/op
BenchmarkMutexWrite/goroutines-16-8        	18897295	        67.3 ns/op
BenchmarkMutexWrite/goroutines-24-8        	14859349	        79.1 ns/op
BenchmarkMutexWrite/goroutines-32-8        	12888097	        86.3 ns/op
BenchmarkMutexWrite/goroutines-40-8        	13035456	        93.2 ns/op
BenchmarkMutexWrite/goroutines-48-8        	11799319	        96.8 ns/op
BenchmarkMutexWrite/goroutines-56-8        	13199521	        99.6 ns/op
BenchmarkMutexWrite/goroutines-64-8        	12478797	       104 ns/op
BenchmarkMutexWrite/goroutines-72-8        	11350282	       108 ns/op
PASS
ok  	command-line-arguments	12.984s
```

source: http://ix.io/2Ckx

**Comment by alculquicondor** [comment]
I remember locks showing up in profiling for PreScore/Score for certain plugins. Although I have to admit that the accesses were not properly implemented.

I'd like to hear an answer for https://github.com/kubernetes/kubernetes/issues/95887#issuecomment-718175135 before doing any experiments.

**Comment by Huang-Wei** [comment]
+1 to @alculquicondor that I'd also like to understand the motivations / requirements of mutating CycleState in Filter().

**Comment by fabiokung** [comment]
My particular use-case, is that we have resources being dynamically added/removed from Nodes, and those resources need to be allocated (and tracked) in the scheduling loop.

Technically I could pre-compute all the available dynamic resources for all Nodes at the `PreFilter` phase, and snapshot it, but that would require me to pre-compute everything for all Nodes on all scheduling cycles.

Instead, what I'm currently doing is computing what dynamic resources can be utilized on-demand during the `Filter` phase (kind of a lazy loading of dynamic resources for each `(Pod, Node)` pair), and saving state of what extra resources were considered during `Filter` for each Node that was evaluated. Then, later in `Reserve` the scheduler plugin can lock-in the exact dynamic resources for the particular Node that was selected.

I understand the concern with adding extra synchronization overhead without a real need. Even if my use-case is not good enough to justify it, there is another argument for it: technically, the lack of access synchronization on `CycleState` violates the [Go memory model](https://golang.org/ref/mem). Even if in the end we decide synchronizing all access is not worth the overhead (for correctness), I would strongly encourage better documentation saying which plugin phases are allowed to modify `CycleState`, and perhaps even forcing a snapshot-read-only copy of `CycleState` to be used by `Filter` plugins.

**Comment by alculquicondor** [comment]
Using the scheduler to track resources is not a good idea. The scheduler should be stateless. Can't you track the resources with an external controller or with a device plugin and making it part of the Node spec?

**Comment by fabiokung** [comment]
@alculquicondor there may be some misunderstanding in my poor choice of words. What I mean by "tracking" is that the scheduler needs to track usage and availability of these extra per-Node resources, to be able to allocate them during placement/scheduling. Exactly the same it does with volumes, cpus, memory, ephemeral disk, etc

Doing computations in a controller outside of the scheduling loop would be similar to "precomputing" these resources. In my particular use case I chose a different way because:

1. It introduces another point of failure, if the external controller stops pre-computing extra resources and publishing them somewhere (CRD, Node spec, etc) scheduling halts (at least scheduling on these extra resources)
2. Extra Node resources in my use case are volatile (they are coming and going frequently), and the extra latency added by an extra controller (vs doing all computations right in the scheduling loop) may be problematic for my use case.

Even if you consider my use case not enough to add proper synchronization to `CycleState`, I'd still encourage making it explicit what scheduling phases are allowed to modify it (and even passing in a snapshot read-only version of `CycleState` to phases that are not expected to update it), to avoid confusion and race conditions.

**Comment by alculquicondor** [comment]
Ok, if you are not tracking the existence of resources in the scheduler, I wouldn't suggest the external controller.

Still, have you considered the device plugin framework? That way, the default kube-scheduler could keep track of resources usage.

Otherwise, I still don't see why you would need to update the CycleState during Filter. As its name indicates, CycleState only lives during a scheduling cycle.

**Comment by adtac** [comment]
Regardless of the correctness of usage of CycleState to do what @fabiokung wants, I still think we need to do one of the following:

1. document that writing to CycleState during Filter will lead to data races
2. pass a read-only CycleState to Filter plugins (whether we do this at the interface level or if we simply drop Write requests during Filter is an implementation detail)
3. actually make CycleState concurrency safe

**Comment by alculquicondor** [comment]
I'm leaning towards 1, but it's fair to continue the discussion before deciding.

**Comment by Huang-Wei** [comment]
> 1\. It introduces another point of failure, if the external controller stops pre-computing extra resources and publishing them somewhere (CRD, Node spec, etc) scheduling halts (at least scheduling on these extra resources)

Can you run the "controller" as a goroutine along with your scheduler plugin? So it's an external controller binary, and hence don't introduce another point of failure. It's pretty like how the default scheduler manages its internal cache.

But note that **cache** is only needed when you need a more efficient data structure. If a {key:value} map is good enough, spinning up a XYZInformer and obtain the latest XYZ resource on-demand is the most recommended way.

> 2\. Extra Node resources in my use case are volatile (they are coming and going frequently), and the extra latency added by an extra controller (vs doing all computations right in the scheduling loop) may be problematic for my use case.

I think it quite depends on how you design the internal XYZ cache. For example, it should only tweak the cache in an incremental manner - in other words, unchanged resource will be kept unmodified. You can check out the "doubly-pointer snapshot" of scheduler's cache.

With above said, if I understand your case correctly, you may need to build a _sophisticated_ XYZ cache, which runs in a separate goroutine and responds to your XYZ resource changes. And then upon each scheduling cycle, take a snapshot (may needs a specific snapshotting algorithm) in PreFilter() and WRITE to CycleState, and then in Filter() READ from CycleState.

My personal option is to suggest all plugin developers to read from CycleState in Filter().

**Comment by fabiokung** [comment]
@Huang-Wei nailed it. What you describe is almost exactly what I’m doing today. There are some details particular to my use case (e.g. just tracking current state with an informer and an incremental cache is not enough, because there’s some logic involved in deciding if currently available resources are usable by each `(Pod, Node)` pair, and I currently do that computation in `Filter` as pairs are evaluated).

In any case, I just wanted to share my use case to provide some color, but I don’t want what I’m doing distracting us from the more important questions, mentioned by @adtac above.

My personal preference would be #1 as a very short term next step, then #2 when someone has cycles to do it. I would be OK with punting on #3 until a more strong need shows up.

**Comment by fabiokung** [comment]
Note that limiting `Filter` to only reading from `CycleState` works for me, as long as I can still read my own data structure from it and do writes on it (i.e. don’t deepcopy `CycleState` for the `Filter` phase).

**Comment by alculquicondor** [comment]
`#2` also adds overhead (from copying the state, which can be very expensive).

**Comment by fabiokung** [comment]
Could implement `#2` just by changing the interface passed to `Filter` (e.g. `ReadOnlyCycleState`. That wouldn’t be backwards compatible, but very cheap.

**Comment by alculquicondor** [comment]
I guess that would work in the sense that you cannot change the high level values of the CycleState map, but you could still override what's inside them, if they have pointers. But maybe that's ok.

**Comment by adtac** [comment]
>but you could still override what's inside them, if they have pointers. But maybe that's ok.

yeah, if it was pointers and if the underlying data needed to be modified, I'd imagine it would have its own Lock/Unlock semantics

**Comment by alculquicondor** [comment]
for such implementation, the only remaining concern is backwards compatibility. So I would leave that decision to @Huang-Wei, who leads the scheduling-plugins repo.

**Comment by Huang-Wei** [comment]
I rethink @fabiokung 's original problem a little bit: the original racing issue occurs when reading CycleState in in-tree plugins, this indicates one of the (out-of-tree) plugins is (over)writing the most high-level value of the CycleState map. But if we control the locking inside the out-of-tree plugin, and mutate that particular `CycleState[key]` **in-place**, that would be good enough?

https://play.golang.org/p/C8l0BSafgf4

Case 3 in the above program demonstrates the correct way to manipulate the specific out-of-tree state.

Let me know your thoughts. If it resolves @fabiokung 's concern, we don't need to make any change on the Filter() interface.

**Comment by fabiokung** [comment]
Case 3 is how I am working around the problem today to avoid the race. I write a "data bag" once into `CycleState's` top level in `PreFilter`, then only modify my own inner structure (with proper locking) in `Filter`, without doing any further modifications to `CycleState` directly (top level) in `Filter`.

That is acceptable, but I'd encourage you to consider making the interface (and documentation) more explicit for `Filter` plugins, so they avoid the mistake of writing directly into `CycleState`.

**Comment by Huang-Wei** [comment]
Thanks for confirming that. Yes, documenting it, or(and) publishing examples would be quite helpful to clarify the semantics.

As a wrap-up:

- a keyed value can be read from CycleState, literally `cycle_state.go#Read()`, in any phase. It's always race-free.
- if you want to mutate the top-level keyed value in CycleState,
    - if it's a phase that CycleState is accessed consecutively, such as PreFilter, PreScore, it's safe to mutate CycleState in any manner
    - if it's a phase that CycleState is accessed parallelly, to be race-free, (for now) you only have 1 option:
        - keep the keyed value's pointer unchanged, and use an internal lock to mutate that pointer obj
        - [TBD] we may come up with changes to add read locks to all in-tree plugins when reading values from CycleState, so that the out-of-tree plugin can surround its mutating logic between `cycle_state.go#Lock()` and `cycle_state.go#Unlock()` - th mutating logic thereby can be any style

Any thoughts on the TBD item? I would assume read locks wouldn't cost too much.

**Comment by Huang-Wei** [comment]
> Without changing anything (no documentation, no readonly interface), it is pretty easy for a plugin to use `CycleState` in a way that you don't want to support.

For now, I think the documentation is correct, it clearly says Read() and Write() are not thread-safe:

https://github.com/kubernetes/kubernetes/blob/8bdd10b7d73cb0d705b895e0c9a5646dfbb19a24/pkg/scheduler/framework/cycle_state.go#L87-L90

The key thing here is whether in-tree plugin should use RLock/RUnlock or not. If yes, out-of-tree plugins can be freed to use Lock/Unlock. (see the TBD item in the previous comment)

**Comment by fabiokung** [comment]
I like the TBD, and optimizing for correctness in how in-tree plugins are accessing `CycleState`. I understand the concern with synchronization overhead, but I would be really surprised if it is the bottleneck in scheduling code.

**Comment by alculquicondor** [comment]
It can be, when you have 5k-nodes clusters, or bigger.

**Comment by ahg-g** [comment]
I don't think it will be expensive, a rlock should be equivalent to an atomic add operation (basically it increments the number of readers). Looking up the state from the map is way more expensive.

**Comment by ahg-g** [comment]
Of course we are assuming no contention in the default plugins.

**Comment by Huang-Wei** [comment]
> I don't think it will be expensive, a rlock should be equivalent to an atomic add operation (basically it increments the number of readers)

This is my impression as well. A vanilla version of scheduler doesn't impose write lock in Filter() and Score(), so should be good.

**Comment by alculquicondor** [comment]
We can always see with the benchmarks and revert if its not negligible.

**Comment by Huang-Wei** [comment]
I will run the benchmarks to see if there is perf downgrade.

/assign

**Comment by adtac** [comment]
/remove-lifecycle stale

This is still relevant, yes? IIUC the volumebinding plugin has been fixed, but external plugins can still shoot themselves in the foot.

**Comment by Huang-Wei** [comment]
@adtac Yes. I'm working on this, late this week I will send out a PR along with perf test result.
