### ISSUE TITLE
test logs FILLED with garbage noise

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#95893]
Any failed test has thousands of lines of:

```
W1026 21:42:28.689550 1571093 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {unix://localhost:68355049939536982930  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix localhost:68355049939536982930: connect: no such file or directory". Reconnecting...
W1026 21:42:28.693505 1571093 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {unix://localhost:71588269375977148510  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix localhost:71588269375977148510: connect: no such file or directory". Reconnecting...
I1026 21:42:28.726109 1571093 client.go:360] parsed scheme: "endpoint"
I1026 21:42:28.726183 1571093 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{unix://localhost:23399466854012311450  <nil> 0 <nil>}]
I1026 21:42:28.727875 1571093 client.go:360] parsed scheme: "endpoint"
```

- Kubernetes version (use `kubectl version`): HEAD
- Cloud provider or hardware configuration: kind

/sig testing

**Comment by BenTheElder** [comment]
Is this locally or CI? If the latter do you have a link or if the former can you say more about how you're running the tests?
/assign

**Comment by thockin** [comment]
Every unit test I run around REST code.  These are coming from inside the GRPC client (vendor/google.golang.org/grpc/clientconn.go) so I an not sure how to weed them out, honestly, but it makes test fails super obnoxious.

E.g. `make test` or `go test`

**Comment by BenTheElder** [comment]
FWIW I noticed the clientconn logging is super noisy in production components too (apiserver) lately and IMHO seems less than useful. I think we should be turning that down broadly.

**Comment by thockin** [comment]
Who can own this?  It's not clear to me who is making the gRPC call - is it the dialer work?  @cheftako ?

**Comment by cheftako** [comment]
I assume that "unix://" is the url scheme for UDS. In that case I would assume this is likely the gRPC call dictated by the egress selector to the konnectivity server. Short of either setting env GRPC_GO_LOG_SEVERITY_LEVEL to error or making changes to the gRPC library, not sure how to cut down on this. @BenTheElder what are your thoughts on setting the env variable for the tests to start?

**Comment by BenTheElder** [comment]
Sorry this dropped off my radar while OOO 🙃 

>  Short of either setting env GRPC_GO_LOG_SEVERITY_LEVEL to error or making changes to the gRPC library, not sure how to cut down on this. @BenTheElder what are your thoughts on setting the env variable for the tests to start?

I think it certainly makes sense, I think these logs are also very spammy in "real" clusters though, I think maybe the default should be adjusted in our binaries more generally.

**Comment by BenTheElder** [comment]
gRPC Go seems to have custom logger support already, we could shim it with a logger that remaps the log levels? I think the env only applies to the default built-in logger.

https://pkg.go.dev/google.golang.org/grpc@v1.34.0/grpclog

> I assume that "unix://" is the url scheme for UDS. In that case I would assume this is likely the gRPC call dictated by the egress selector to the konnectivity server

Why are we trying to connect to this anyhow?

**Comment by cheftako** [comment]
Not sure on the use case. The konnectivity server is the replacement for SSHTunnels.  One of the possible configurations is to connect to it via UDS. I would point out that it is disabled by default. So I would assume if it is the use case, its a use case where it has been deliberately turned on. I believe its already been adopted by more companies that SSHTunnels ever was.

**Comment by cheftako** [comment]
> Not sure on the use case Tim is referencing (and if it is a match). The konnectivity server is the replacement for SSHTunnels. One of the possible configurations is to connect to it via UDS. I would point out that it is disabled by default. So I would assume if it is the use case, its a use case where it has been deliberately turned on. I believe its already been adopted by more companies than SSHTunnels was.

**Comment by BenTheElder** [comment]
> Not sure on the use case Tim is referencing (and if it is a match). The konnectivity server is the replacement for SSHTunnels. One of the possible configurations is to connect to it via UDS. I would point out that it is disabled by default. So I would assume if it is the use case, its a use case where it has been deliberately turned on. I believe its already been adopted by more companies than SSHTunnels was.

I see these spam clientconn logs even in kind clusters, where I'm fairly certain we're not opting into sshtunnels. see also https://github.com/kubernetes/kubernetes/issues/98778

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/issues/98720 as well

**Comment by BenTheElder** [comment]
leaving this open for now, but I think https://github.com/kubernetes/kubernetes/issues/98720 which is assigned will track the ultimate fix 🤞

**Comment by BenTheElder** [comment]
it seems https://github.com/kubernetes/kubernetes/pull/84061/files is stalled out, but this still needs fixing in the core libraries, it's not test specific.

**Comment by jpbetz** [comment]
/assign @jingyih
Would you be willing to have a look at this one? It's been around for a while, so there might be multiple issues to close if you fix it.

**Comment by jingyih** [comment]
@gyuho I found a pending PR (#84061) from you trying to address this issue. Are you still planning to work on it?

**Comment by gyuho** [comment]
@jingyih Sorry for the delayed response.

No, I am not actively working on this, since we've made some big changes to how we set up the logging in etcd client and grpc logger (/cc @ptabor)

**Comment by liggitt** [comment]
updated the etcd client in unit/integration tests to only emit errors as part of the update to etcd 3.5.0 client in https://github.com/kubernetes/kubernetes/pull/100488

**Comment by BenTheElder** [comment]
Thank you! 

Hope we can fix this for production as well, the actual component logs are similarly annoying 🤨
