### ISSUE TITLE
Make correlator in event broadcaster optional

### ISSUE THREAD

**Issue by slinkydeveloper** [kubernetes/kubernetes#95902]
We have a use case where we use the event broadcaster to send test events to kubernetes events and we cannot lose events because they are correlated with other ones. We would love to have a way to disable such event correlator.

Is there a way to make it optional? If not, are you interested in such feature? I can take care of it.

Dup of https://github.com/kubernetes/client-go/issues/885

**Comment by slinkydeveloper** [comment]
Not sure it's the right sig

/sig api-machinery

**Comment by deads2k** [comment]
Try using `NewBroadcasterWithCorrelatorOptions`.  by setting a `KeyFunc` with message in the key or even just creating a UID, you can ensure that your events are never correlated and you have control over burst and qps settings.  I would recommend using care, if your app has a bug, you can create so many events that etcd struggles to keep up.  That's actually what drove us to create the correlator in the first place.

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/record/event.go#L170

/close

**Comment by slinkydeveloper** [comment]
@deads2k can we document this somewhere? If you point me in the right direction, I can take care of documenting it :smile:

**Comment by deads2k** [comment]
> @deads2k can we document this somewhere? If you point me in the right direction, I can take care of documenting it

You can godoc the new methods in here https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/record/event.go#L170 .  To create any broadcaster, you first had to find that package, so I think that's probably sufficient.
