### ISSUE TITLE
support container based scaling to HPA with custom-metrics server

### ISSUE THREAD

**Issue by zoux86** [kubernetes/kubernetes#95904]
I have a demand in hpa. for example:

I want to use custom metricName: container_cpu_used_1m with https://github.com/kubernetes-sigs/custom-metrics-apiserver, which mean 1min avage cpu usage of container, to decide scaled up or down？

I can get the value container_cpu_used_1m.

I see a new metric type ContainerResource is add by  https://github.com/kubernetes/kubernetes/pull/90691/files
but from the source code , it seems not support custom-metrics server.  @arjunrn

Am I right?  if not, how can i do?

Any comments or suggestions would be appreciated！！！

**Comment by arjunrn** [comment]
@zoux86 You can use multiple metric sources in the HPA. So if you are using a custom metrics provider you will have to specify a different metric source for each container. If you can pass the name of the container probably in a label then it should just work as you expect.
As a side note using averages over time is generally done to prevent sudden changes in the the target replica size. In v1.18 a new feature was introduced for scaling controls. You can achieve the same result by using [this feature](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-configurable-scaling-behavior).
