### ISSUE TITLE
failed to try resolving symlinks in path "/var/log/pods/default_polling-app-mysql-7f5ffd48b7-xrbpz_d704241f-2953-4dba-9b99-02c43f178039/mysql/3.log": lstat /var/log/pods/default_polling-app-mysql-7f5ffd48b7-xrbpz_d704241f-2953-4dba-9 b99-02c43f178039/mysql/3.log: no such file

### ISSUE THREAD

**Issue by Bghd34** [kubernetes/kubernetes#95914]
bonjour, de l'aide SVP !
j'ai cette erreur quand j'essaie de déployer 'mysql' sur GKE .

" failed to try resolving symlinks in path "/var/log/pods/default_polling-app-mysql-7f5ffd48b7-xrbpz_d704241f-2953-4dba-9b99-02c43f178039/mysql/3.log": lstat /var/log/pods/default_polling-app-mysql-7f5ffd48b7-xrbpz_d704241f-2953-4dba-9 b99-02c43f178039/mysql/3.log: no such file "

------------------------------------------------------
voici Voici le manifeste :

apiVersion: v1
kind: PersistentVolume            
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: standard      
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:                      
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain  
---    
apiVersion: v1
kind: PersistentVolumeClaim        
metadata:                          
  name: mysql-pv-claim
  labels:
    app: polling-app
spec:                              
  storageClassName: standard       
  accessModes:
    - ReadWriteOnce               
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1                    
kind: Service                     
metadata:
  name: polling-app-mysql         
  labels:                         
    app: polling-app
spec:
  ports:
    - port: 3306
  selector:                     
    app: polling-app
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment                   
metadata:
  name: polling-app-mysql           
  labels:                         
    app: polling-app
spec:
  selector:
    matchLabels:                  
      app: polling-app
      tier: mysql
  strategy:
    type: Recreate
  template:                         
    metadata:
      labels:                     
        app: polling-app
        tier: mysql
    spec:                          
      containers:
      - image: mysql:latest            
        name: mysql
        env:                       
        - name: MYSQL_ROOT_PASSWORD 
          valueFrom:               
            secretKeyRef:
              name: mysql-root-pass
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-db-url
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: password
        ports:
        - containerPort: 3306          
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage 
          mountPath: /var/lib/mysql
      volumes:                  
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

----------

**Comment by neolit123** [comment]
hi, please try the #fr-users channel (French users) on k8s slack or any of the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

thanks
/close
