### ISSUE TITLE
When creating a new Event, setting EventTime triggers an undocumented validation

### ISSUE THREAD

**Issue by slinkydeveloper** [kubernetes/kubernetes#95913]
**What happened**:
I'm trying to send a new `Event` to the api server manually creating the event and pushing it with client-go. Setting `EventTime` triggers a validation undocumented nor in api docs nor in struct definition: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/events.go#L122 . This validation blocks events without `ReportingController`, `ReportingInstance`, `Action` and with `Message` greater than 1024 chars.

**What you expected to happen**:
I can set `EventTime` without triggering additional validation. Or I can properly access to documentation that explains this validation behaviour

**How to reproduce it (as minimally and precisely as possible)**:
Try to push an event with `EventTime` without `ReportingController`, `ReportingInstance`, `Action` and with `Message` greater than 1024 chars.

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: `kind v0.9.0 go1.14.9 linux/amd64`

**Comment by slinkydeveloper** [comment]
Not sure it's the right wg

/wg api-expression

**Comment by deads2k** [comment]
EventTime is a field added in events.k8s.io/v1beta1.  Since the field is new, we know that the caller is aware of the new API and is subject to the rules documented in https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/events/v1/types.go#L28 .

If you don't use the new field associated with events.k8s.io, then the tighter validation rules do not apply to the request.

/close
