### ISSUE TITLE
Return duplicate events in Apiserver cache when relist 

### ISSUE THREAD

**Issue by fisherxu** [kubernetes/kubernetes#95919]
**What happened**:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/reflector.go#L293 
As comments said here, result is at least as fresh as provided RV, doesn't lead to going back in time, but watch cache in apiserver doesn't do filter in the scenario below, it maybe caused going back:

**when client do the relist with lastSyncResourceVersion(!=0), at this moment, apiserver will serve the list from cache, and object with lastSyncResourceVersion is just in the watch cache(startRV<lastSyncResourceVersion<endRV) in apiserver, list func will return all the objects in store to client.   https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go#L701**

Looks like  in apiserver it only does `waituntilfreshandblock` check, which is useful for `too old` or `too large` resourceversion, but  not for scenario above.

**What you expected to happen**:

Don't return all the objects in cache store, add some filter. Or am I missing anything? :)

/cc @lavalamp @liggitt @wojtek-t

**Comment by wojtek-t** [comment]
Sorry - I don't really understand what you're saying. Maybe you can try to provide an example?

**Comment by fisherxu** [comment]
> Sorry - I don't really understand what you're saying. Maybe you can try to provide an example?

Sorry for the confusing..

I mean when client does relist with `ResourceVersion A`(!=""&&!="0"), in apiserver [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go#L437), we only compare `w.resourceVersion`(latest in cache) with `ResourceVersion A`, if  `ResourceVersion A` < `w.resourceVersion`, we will return all the cached events.

And I think the events between oldest resourceVersion and `ResourceVersion A` should not be returned?

![image](https://user-images.githubusercontent.com/28776356/97322298-9f3cc900-18aa-11eb-84e0-805e120acdf8.png)

**Comment by fisherxu** [comment]
We hope that in scenarios like edge computing, the bandwidth is limited and the connection will be disconnected frequently, so 
 hope to avoid sending duplicate data. 
But I am not very sure if APIServer will send duplicate data, as described in my last comment https://github.com/kubernetes/kubernetes/issues/95919#issuecomment-717327815, and want to confirm it @wojtek-t  :)

**Comment by liggitt** [comment]
Listing returns all objects, not watch events. That is working as designed.

Reflectors will try to reestablish a watch before falling back to a full re-list to avoid needing to retrieve all objects. That is where the optimization takes place.

**Comment by fedebongio** [comment]
/assign @liggitt @wojtek-t 
Will let you decide if this needs further discussion or can be closed! thank you
/triage accepted

**Comment by fisherxu** [comment]
> Listing returns all objects, not watch events. That is working as designed.
> 
> Reflectors will try to reestablish a watch after getting disconnected before falling back to a full re-list to avoid needing to retrieve all objects. That is where the optimization takes place.

Get it, I think we can close it 
/close
