### ISSUE TITLE
[Failing Test] ReplicationController should test the lifecycle of a ReplicationController [Conformance]

### ISSUE THREAD

**Issue by thejoycekung** [kubernetes/kubernetes#95920]
**Which jobs are failing**:
- `gce-windows-1909-master`
- `gce-windows-2019-master`

Triage link for more jobs that are affected: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=%5C%5Bsig%5C-apps%5C%5D%5C%20ReplicationController%5C%20should%5C%20test%5C%20the%5C%20lifecycle%5C%20of%5C%20a%5C%20ReplicationController%5C%20%5C%5BConformance%5C%5D

**Which test(s) are failing**:
`[sig-apps] ReplicationController should test the lifecycle of a ReplicationController [Conformance]`

**Since when has it been failing**:
Since October 23

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#gce-windows-1909-master
https://testgrid.k8s.io/sig-release-master-informing#gce-windows-2019-master

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:629
Oct 27 10:28:15.917: Wait for condition with watch events should not return an error
Unexpected error:
    <*errors.errorString | 0xc0002721f0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/rc.go:186
```

**Anything else we need to know**:
Example spyglass link: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-1909/1321021135638237184

/sig apps
/cc @kubernetes/ci-signal 
/priority important-soon

**Comment by spiffxp** [comment]
/remove-priority important-soon
/priority critical-urgent
top flake for pull-kubernetes-conformance-kind-ipv6-parallel,  2nd top flake for `pull-kubernetes-e2e-gce-ubuntu-containerd` per http://storage.googleapis.com/k8s-metrics/flakes-latest.json
/area conformance
this is a conformance test
/remove-kind failing-test
/kind flake
this is not failing continuously, but is instead flaking

**Comment by hh** [comment]
I increased the timeout while waiting for available Replicas.

https://github.com/kubernetes/kubernetes/pull/96184#issuecomment-721351786

> All the errors I could find were a timeout waiting for the Replicas:
> 
> ```
> [It] should test the lifecycle of a ReplicationController [Conformance]
>   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:629
> STEP: creating a ReplicationController
> STEP: waiting for RC to be added
> STEP: waiting for available Replicas
> Oct 27 10:28:15.917: FAIL: Wait for condition with watch events should not return an error
> Unexpected error:
>     <*errors.errorString | 0xc0002721f0>: {
>         s: "timed out waiting for the condition",
>     }
>     timed out waiting for the condition
> occurred
> ```

**Comment by Riaankl** [comment]
Test grid green since #96184 Merge 5 Nov 2020
[Testgrid GCE Window 2019](https://testgrid.k8s.io/sig-release-master-informing#gce-windows-2019-master&include-filter-by-regex=ReplicationController%20should%20test%20the%20lifecycle%20of%20a%20ReplicationController&width=5)
[Testgrid GCE Windows1909](https://testgrid.k8s.io/sig-release-master-informing#gce-windows-1909-master&include-filter-by-regex=ReplicationController%20should%20test%20the%20lifecycle%20of%20a%20ReplicationController&width=5)
/cc @hh
