### ISSUE TITLE
NodeProxy endpoints can not be Conformance tested in their current state

### ISSUE THREAD

**Issue by Riaankl** [kubernetes/kubernetes#95930]
# Conformance tests for NodeProxy

These endpoints which are tracked by [APIsnoop Conformance Progress](https://apisnoop.cncf.io/conformance-progress) and need to have conformance tests that meet the [currrent conformance requirements](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md#conformance-test-requirements)

The [NodeProxy endpoints](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#-strong-proxy-operations-node-v1-core-strong-) are listed below.

|               endpoint                |               path                |       kind       |
|---------------------------------------|-----------------------------------|------------------|
| connectCoreV1PutNodeProxyWithPath     | /api/v1/nodes/{name}/proxy/{path} | NodeProxyOptions |
| connectCoreV1PutNodeProxy             | /api/v1/nodes/{name}/proxy        | NodeProxyOptions |
| connectCoreV1PostNodeProxyWithPath    | /api/v1/nodes/{name}/proxy/{path} | NodeProxyOptions |
| connectCoreV1PostNodeProxy            | /api/v1/nodes/{name}/proxy        | NodeProxyOptions |
| connectCoreV1PatchNodeProxyWithPath   | /api/v1/nodes/{name}/proxy/{path} | NodeProxyOptions |
| connectCoreV1PatchNodeProxy           | /api/v1/nodes/{name}/proxy        | NodeProxyOptions |
| connectCoreV1OptionsNodeProxyWithPath | /api/v1/nodes/{name}/proxy/{path} | NodeProxyOptions |
| connectCoreV1OptionsNodeProxy         | /api/v1/nodes/{name}/proxy        | NodeProxyOptions |
| connectCoreV1HeadNodeProxyWithPath    | /api/v1/nodes/{name}/proxy/{path} | NodeProxyOptions |
| connectCoreV1HeadNodeProxy            | /api/v1/nodes/{name}/proxy        | NodeProxyOptions |
| connectCoreV1GetNodeProxy             | /api/v1/nodes/{name}/proxy        | NodeProxyOptions |
| connectCoreV1DeleteNodeProxyWithPath  | /api/v1/nodes/{name}/proxy/{path} | NodeProxyOptions | 
| connectCoreV1DeleteNodeProxy          | /api/v1/nodes/{name}/proxy        | NodeProxyOptions |

## Feedback request 1

Should the endpoints for **connectCoreV1*NodeProxy          | /api/v1/nodes/{name}/proxy** be able to hit something valid?

- The apiserver is doing a blanket redirect for any of these at the moment.
- When testing with the *redirect* removed returns a set of 404 messages.
- What's the best action going forward for these endpoints?
- **Ticket:** Write NodeProxy Redirect Test - +7 endpoint coverage test [#94949](https://github.com/kubernetes/kubernetes/pull/94949)

## Fedback Request 2

Is there a some node api that we can use to confirm the actions of **/api/v1/nodes/{name}/proxy/{path}**? Using either 'configz' or '/metrics' is not an option as they are using kublet (which isn't allowed to be used for conformance tests)
- The test will need some way of confirming that the http method sent through the proxy hasn't beeen changed eg POST requrest must not change to a GET request.
- **Ticket:** Write NodeProxyWithPath test+promote - + 4 endpoint coverage [#95524](https://github.com/kubernetes/kubernetes/issues/95524)

## SIG Note meeting feedback
From the SIG Node meeting on 27 October 2020 it seem likely that the Node Proxy endpoints would be deprecated as it is an old feature from the beginning of K8s, likely not needed any more.

## The next steps
If there is no objections the Node Proxy endpoints would be marked as  [Ineligible for Conformance](https://apisnoop.cncf.io/conformance-progress/ineligible-endpoints) 
This status can be changed by either updating the endpoints as explained in the feedback requests above to support conformance testing or deprecating the endpoints.

**Comment by dashpole** [comment]
Discussing known use-cases for the node proxy at sig-instrumentation:

* Prometheus server can use the proxy endpoint, but it is discouraged.
* It is helpful to be able to query the summary API, for debugging.

**Comment by Riaankl** [comment]
The NodeProxy end points have now been marked at Endpoints Ineligible for conformance in [APISnoop](https://apisnoop.cncf.io/conformance-progress/ineligible-endpoints)
This does not affect the functionally of the endpoint in any way. 
![image](https://user-images.githubusercontent.com/61125752/99000981-f75c1680-259e-11eb-8a61-a661cead53bb.png)
