### ISSUE TITLE
Job should add waiting/pending status

### ISSUE THREAD

**Issue by junneyang** [kubernetes/kubernetes#95940]
at present, when a job is createed, it's status is active...
but, if the pod is waiting to schedule, the pod's status is containercreating, the job is pending therefor
so, i suggest add waiting/pending status for the job, when the job's pod are all running, the job's status should be active
thanks~~

**Comment by soltysh** [comment]
Pod status is different from job status, job controller started working on a job as soon as it's `.status.startTime` is non nil. This will be slightly different when we implement https://github.com/kubernetes/enhancements/blob/master/keps/sig-apps/2232-suspend-jobs/README.md but the notion of pending pod does not affect job state. 
/close
