### ISSUE TITLE
role associated with user via rolebinding per pod in same namespace

### ISSUE THREAD

**Issue by yaminisridaran** [kubernetes/kubernetes#95941]
**What would you like to be added**:
Currently K8S authentication user looks like a User can be associated to per namespace using rolebinding and role. We require multiple User associated with multiple roles associated with per pod (or) group of pods in same namespace. 

**Why is this needed**:
We have multiple user Eg: User A and User B in a k8s cluster and we have deployed pod X,Y,Z in Namespace test . We need to allow User A to do pod exec to pod  X,Y in Namespace test and we should not allow User A to do pod  exec to pod X in Namespace test.
We were able to get the above requirement working: User A  to do pod exec pod X,Y in Namespace A and User A not able to pod exec to pod Z in same Namespace  by configuring a rule with resourceName Mapped with podName.  Which may not be cleaner approach.

**Comment by cjcullen** [comment]
To do this through RBAC, your approach is the correct one: Use `resourceName` in the role to specify the pod names you want to allow exec to. For example, your Role might have a rule like:
```
- apiGroups: [""]
  resources: ["pods/exec"]
  resourceNames: ["X", "Y"]
  verbs: ["get", "create"]
```

In the case of exec, you can also restrict access through dynamic admission. For example, a ValidatingWebhookConfiguration with a rule like:
```
- apiGroups:   [""]
  resources:   ["pods/exec"]
  operations:  ["CONNECT"]
  scope:       "Namespaced"
```
would allow you to implement more fine-grained policy in a webhook.
