### ISSUE TITLE
subPath owner/group should be set to runAsUser/fsGroup instead of root

### ISSUE THREAD

**Issue by yongjie-gong** [kubernetes/kubernetes#95945]
**What happened**:
1) on NFS server(**nfs1.test.com**), setup one share like below
/no_root/var/vols/test1 *(rw,sync,no_root_squash)

2) Create PV( pv1/pvc1) with this nfs path
3) Create the pod with this pvc and setup subPath
apiVersion: v1
kind: Pod
metadata:
  name: test1
spec:
  containers:
  - name: test1
     image: busybox    
     volumeMounts:
     - name: log-dir
       mountPath: /shared
       subPath:  logs/test
  securityContext:
    runAsUser: 2000
    fsGroup: 3000
  volumes:
  - name: log-dir
    persistentVolumeClaim:
       claimName: pvc1

in pod, 
  check folder owner of /shared/logs/test
 its owner is set to "root" instead of "2000"

**What you expected to happen**:
If runAsUser/fsGruop is set in container/pod level,  directory created by "subPath" should use the same owner of runAsUser/fsGruoop instead of "root"

**How to reproduce it (as minimally and precisely as possible)**:
As describe above

**Anything else we need to know?**:
No

**Environment**:
- Kubernetes version (use `kubectl version`): from 1.17.x - 1.19.x
- Cloud provider or hardware configuration: kubeadm 
- OS (e.g: `cat /etc/os-release`): centos7.8
- Kernel (e.g. `uname -a`):  Linux  3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug): flannel
- Others:

**Comment by pacoxu** [comment]
> We don't support fsGroup on NFS because some NFS servers runs with root_squash and kubelet is not able to change ownership of files there.

Details can be found in PR comments here https://github.com/kubernetes/kubernetes/pull/96900#discussion_r649846650.
