### ISSUE TITLE
minikube not starting - 81476 server.go:154] unknown flag: --allow-privileged

### ISSUE THREAD

**Issue by sreenigaddam77** [kubernetes/kubernetes#95959]
I1028 12:25:46.008388   81186 config.go:125] Using kubeconfig:  /scratch/sreegadd/.kube/config
-   Pulling images required by Kubernetes v1.16.8 ...
I1028 12:25:46.054352   81186 exec_runner.go:39] Run: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml
X   Unable to pull images, which may be OK: running cmd: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml: running command: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml: exit status 1
:   Relaunching Kubernetes v1.16.8 using kubeadm ... 
I1028 12:25:46.225457   81186 exec_runner.go:39] Run: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml
I1028 12:25:46.385656   81186 exec_runner.go:50] Run with output: docker ps -a --filter="name=k8s_kube-apiserver" --format="{{.ID}}"
I1028 12:25:46.434063   81186 logs.go:144] 0 containers: []
W1028 12:25:46.434095   81186 logs.go:146] No container was found matching "kube-apiserver"
I1028 12:25:46.434126   81186 exec_runner.go:50] Run with output: docker ps -a --filter="name=k8s_coredns" --format="{{.ID}}"
I1028 12:25:46.484883   81186 logs.go:144] 0 containers: []
W1028 12:25:46.484947   81186 logs.go:146] No container was found matching "coredns"
I1028 12:25:46.484972   81186 exec_runner.go:50] Run with output: docker ps -a --filter="name=k8s_kube-scheduler" --format="{{.ID}}"
I1028 12:25:46.533407   81186 logs.go:144] 0 containers: []
W1028 12:25:46.533433   81186 logs.go:146] No container was found matching "kube-scheduler"
I1028 12:25:46.533444   81186 logs.go:69] Gathering logs for kubelet ...
I1028 12:25:46.533452   81186 exec_runner.go:50] Run with output: journalctl -u kubelet -n 200
W1028 12:25:46.547966   81186 logs.go:81] Found kubelet problem: Oct 28 12:25:46 slc11jlb kubelet[81476]: F1028 19:25:46.062988   81476 server.go:154] unknown flag: --allow-privileged
W1028 12:25:46.547990   81186 exit.go:87] Error restarting cluster: running cmd: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: running command: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: exit status 1
!   Error restarting cluster: running cmd: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: running command: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: exit status 1

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new
X   Problems detected in "kubelet":
    - Oct 28 12:25:46 slc11jlb kubelet[81476]: F1028 19:25:46.062988   81476 server.go:154] unknown flag: --allow-privileged

Please advise .how to solve this issue 
bash-4.2$ kubelet --version
Kubernetes v1.16.8
bash-4.2$ minikube version
minikube version: v0.35.0

**Comment by troy0820** [comment]
/kind support
/sig cluster-lifecycle
@sreenigaddam77 I would try upgrading to a newer version of minikube.  Minikube is on 1.14.2 now.

**Comment by neolit123** [comment]
hi, please log this ticket in the kubernetes/minikube repository.
this one is for core k8s.

thanks
/close
