### ISSUE TITLE
Fake client does not update a secrets Data field, when StringData field was used

### ISSUE THREAD

**Issue by creydr** [kubernetes/kubernetes#95956]
**What happened**:

When creating a secret using the fake client and storing data in a secrets `StringData` field, these values do not get populated to the secrets `Data` field after the secret was stored. Running the same test with the normal client (against a local cluster (e.g. minikube)), the secrets `Data` field gets populated.

I wrote a simple test, which reproduces this issue:

```
import (
	"context"
	"testing"

	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/kubernetes/fake"
	"k8s.io/client-go/tools/clientcmd"
)

func TestFakeClient(t *testing.T) {
	fakeclient := fake.NewSimpleClientset()

	testCreateSecret(fakeclient, t)
}

func TestLocalClient(t *testing.T) {
	client, err := localClientset()
	if err != nil {
		t.Fatal(err)
	}

	testCreateSecret(client, t)
}

func testCreateSecret(clientset kubernetes.Interface, t *testing.T) {
	ctx := context.Background()
	key := "somekey"

	secret := v1.Secret{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "my-secret",
			Namespace: "default",
		},
		StringData: map[string]string{
			key: "value",
		},
	}

	if _, err := clientset.CoreV1().Secrets(secret.Namespace).Create(ctx, &secret, metav1.CreateOptions{}); err != nil {
		t.Fatal(err)
	}

	foundSecret, err := clientset.CoreV1().Secrets(secret.Namespace).Get(ctx, secret.Name, metav1.GetOptions{})
	if err != nil {
		t.Fatal(err)
	}

	if _, ok := foundSecret.Data[key]; !ok {
		t.Error("Secret does not contain required key in Data field")
	}
}

func localClientset() (*kubernetes.Clientset, error) {
	configOverrides := &clientcmd.ConfigOverrides{}

	loadingRules := clientcmd.NewDefaultClientConfigLoadingRules()
	config, err := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(loadingRules, configOverrides).ClientConfig()
	if err != nil {
		return nil, err
	}

	return kubernetes.NewForConfig(config)
}

```

While `TestLocalClient` runs successfull, `TestFakeClient` fails with:
```
--- FAIL: TestFakeClient (0.00s)
    fakeclient_test.go:65: Secret does not contain required key in Data field
``` 

**What you expected to happen**:
I would expect the fake client populates a secrets `Data` field too, even if data was written with the `StringData` field.

**How to reproduce it (as minimally and precisely as possible)**:
Use the test above.

**Anything else we need to know?**:
no.

**Environment**:
- Kubernetes version (use `kubectl version`):
local Minikube cluster is 1.19.0
The following client libraries are used:
```
k8s.io/api v0.19.3
k8s.io/apimachinery v0.19.3
k8s.io/client-go v0.19.3
```
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.5 LTS
- Kernel (e.g. `uname -a`): 4.15.0-122-generic

**Comment by liggitt** [comment]
This is expected. The stringData->data transformation is done server-side in conversion, which is not included in the fake client. 

If you want to model/test a client that depends on this, you can prepend a reactor to the fake client to do this transformation
