### ISSUE TITLE
Pod status.containerStatuses[].imageId depends on container runtime

### ISSUE THREAD

**Issue by ezimanyi** [kubernetes/kubernetes#95968]
**What happened**:

The `status.containerStatuses[].imageId` for a `Pod` is different depending on whether the pod is running on a node with the `docker` runtime vs. the `containerd` runtime.

In particular, the docker runtime prefixes the repo digest with `docker-pullable://` whereas the containerd runtime does not.

For example, using `marketplace.gcr.io/google/nginx1:latest` as an example, the results are as follows:
* Docker runtime: `imageID: docker-pullable://marketplace.gcr.io/google/nginx1@sha256:....`
* Containerd runtime: `imageID: marketplace.gcr.io/google/nginx1@sha256:....`

**What you expected to happen**:

I expect that the container runtime should be an implementation detail and that this detail should not affect the observable status of a `pod`.

Of course there may be functionality differences between various runtimes; perhaps some runtimes would be unable to fill in certain fields.  But in this case, both runtimes are able to get the full repo digest of the running container, but report this differently.  I would expect that when functionality is supported by various runtimes, they should report the result in the  smae manner.

**How to reproduce it (as minimally and precisely as possible)**:

On a cluster whose nodes are running the `docker` container runtime:
```
$ kubectl create deployment my-deployment --image=marketplace.gcr.io/google/nginx1:latest
$ kubectl get pod [pod that was created] -o=jsonpath='{.status.containerStatuses[0].imageID}'
docker-pullable://marketplace.gcr.io/google/nginx1@sha256:e9377c6da6780edaf5ed1c5b06f2a5b4ada2e0271971a50802ea56870bacef55
```

Repeat on a cluster whose nodes are running the `containerd` runtime:
```
$ kubectl create deployment my-deployment --image=marketplace.gcr.io/google/nginx1:latest
$ kubectl get pod [pod that was created] -o=jsonpath='{.status.containerStatuses[0].imageID}'
marketplace.gcr.io/google/nginx1@sha256:e9377c6da6780edaf5ed1c5b06f2a5b4ada2e0271971a50802ea56870bacef55
```

**Anything else we need to know?**:

The reason I'm opening this against the `kubernetes` repo rather than the `containerd` implementation is that the [interface](https://godoc.org/k8s.io/cri-api/pkg/apis/runtime/v1alpha2#ContainerStatus) does not make any note of the meaning of the `docker-pullable://` prefix and when it should be present.  Ideally the documentation would indicate when implementations should include this prefix so that the meaning of the field does not depend on the implementation.

It looks like the `docker-pullable://` prefix was added in kubernetes/kubernetes#33014 (with some more context on kubernetes/kubernetes#31621) in order to indicate that the image id is a repo digest (rather than a local digest).  It's worth noting that the `containerd` implementation does the [exact same check](https://github.com/containerd/containerd/blob/656b487d333db8ad7134d26cfe12358c46c2b7f8/pkg/cri/server/container_status.go#L57) for a repo digest but does not add the `docker-pullable://` prefix.

**Environment**:
- Kubernetes version (use `kubectl version`): server: 1.18.9-gke.2501, client: v1.19.3 
- Cloud provider or hardware configuration: GKE

**Comment by karezza** [comment]
Recommend this one be revisited.
