### ISSUE TITLE
HEAD & OPTIONS http verbs don’t seem to show up in the apiserver audit logs when we hit proxy endpoints.

### ISSUE THREAD

**Issue by Riaankl** [kubernetes/kubernetes#95966]
### Description:
In the process of conformance testing of the '[PodProxyWithPath](https://github.com/kubernetes/kubernetes/pull/95503)' Endpoints we have ran into issue with testing `HEAD' and `OPTION` endpoints.

**Affected endpoints:**
- connectCoreV1OptionsNamespacedPodProxyWithPath
- connectCoreV1HeadNamespacedPodProxyWithPath
- connectCoreV1OptionsNamespacedServiceProxyWithPath
- connectCoreV1HeadNamespacedServiceProxyWithPath

 
The http.Method(HEAD) is hard coded into RestquestInfo.Verb(get) making some of the API inaccessible from what we see.
When special verbs "Proxy" are hit it is suppose to check if the current part of the URL has proxy in it and override the request verb. 
When running our test, we know that the http.Method is set to HEAD, but shows up in the audit logs as get.
![image](https://user-images.githubusercontent.com/61125752/97502548-30f62480-19d8-11eb-860a-7803f8f4b408.png)

In the audit log the K8s operation is not visible in the audit log. We rely on the a combination of the verb as stored by the audit logs and request URI to match up and find the operation ID. If the verb is not correct we identified the operation.
Request HEAD doesn’t make sense for APIs other than proxy. This might be an API Server bug.

### Write-up:
[HEAD & OPTIONS](https://github.com/cncf/apisnoop/blob/master/org/explorations/head-and-options.org
) write-up give more details.

### Conformance office hours discussion:
The topic was discussed in the Conformance office hours meeting on 20 Oct 2020 and can be reviewed in the [video](https://www.youtube.com/watch?v=gMnicvNQXZc&t=28m) from 28min - 35min

### Next steps:
Please review and help to move this forward.

**Comment by roycaihw** [comment]
> When running our test, we know that the http.Method is set to HEAD, but shows up in the audit logs as get.

by definition `verb` is the [kubernetes verb](https://github.com/kubernetes/kubernetes/blob/e54448a307e04773598b212bb3bbcc53eae01d49/staging/src/k8s.io/apiserver/pkg/apis/audit/v1/types.go#L85-L87) associated with the request. See https://kubernetes.io/docs/reference/access-authn-authz/authorization/#determine-the-request-verb on how kubernetes verbs are determined. 

I think the first question is for sig auth on whether this is working as intended. 

(p.s. the code that does `HEAD->get` is [here](https://github.com/kubernetes/kubernetes/blob/e54448a307e04773598b212bb3bbcc53eae01d49/staging/src/k8s.io/apiserver/pkg/endpoints/request/requestinfo.go#L166-L167), changing that will have impact on places including authorization, where you probably only want to change the audit events).

**Comment by roycaihw** [comment]
/remove-sig api-machinery

I think sig auth owns both the definition of Kubernetes request verb (given this [doc](https://kubernetes.io/docs/reference/access-authn-authz/authorization/#determine-the-request-verb) falls under auth), and the implementation of how audit log collects the verb from request info.

**Comment by liggitt** [comment]
> The http.Method(HEAD) is hard coded into RestquestInfo.Verb(get) making some of the API inaccessible from what we see.

The API is not inaccessible (the HEAD or OPTIONS requests should still be proxied through), but the audit event does not distinguish between them.

`HEAD` being treated as `get` for audit/authorization purposes is working as intended (they are authorized the same and according to the spec HEAD should be processed as a GET excluding body from the return)

**Comment by hh** [comment]
You are right, it's not inaccessible. We are hitting it!

I wonder about the intention for auditing purposes.

Should we be logging enough information information to map back to the OpenAPI spec?
If we don't and log both as GET, it's not possible to distinguish the two API Operations from each other.

I started a thread in #sig-auth mailing list, but might be good to pull this back here.
https://groups.google.com/g/kubernetes-sig-auth/c/k-1xNWS9BdA/m/fw2tCuM4AwAJ

**Our primary use case is to be able to map audit log entries back to the operationId of the openapi spec.**

It might be useful to share the effort and work arounds we've taken to map audit log path and k8s verb back to http methods so we can lookup operationIds in the OpenAPI swagger definition.

We had to figure out this mapping manually, and found ourselves surprised sometimes on the logic:

https://github.com/cncf/apisnoop/blob/39c1030f37a7d5094d753f7312bdae1bce6eccd8/apps/snoopdb/postgres/snoopUtils.py#L23-L38

```
# The k8s VERB (aka action) mapping to http METHOD
# Our audit logs do NOT contain any mention of METHOD, only the VERB
VERB_TO_METHOD={
'get': 'get',
'list': 'get',
'proxy': 'proxy',
'create': 'post',
'post':'post',
'put':'post',
'update':'put',
'patch':'patch',
'connect':'connect',
'delete':'delete',
'deletecollection':'delete',
'watch':'get'
}
```

And for audit entries where the k8s 'verb' is missing, our current hack is to set it to "options":

https://github.com/cncf/apisnoop/blob/39c1030f37a7d5094d753f7312bdae1bce6eccd8/apps/snoopdb/postgres/snoopUtils.py#L198-L204

```
def find_operation_id(openapi_spec, event):
  try:
    method=VERB_TO_METHOD[event['verb']]
  except:
    method='options'
    #return 'bugNoVerb' # Our alternative method if we find this happens again
  url = urlparse(event['requestURI'])
#continues...
```

Note the rest of our 'find_operation_id' function tries to cache lookups as processing gigabytes of logs used to take hours before we settled on this bit of caching / operationId lookup logic.

As we look into correcting the k8s verb recording to the audit logs, it would be extremely helpful if the audit logging mechanisms where updated to include the OpenAPI operationId so these type of manual audit log->k8s verb->http method->swagger->OperationId mapping lookups and caching are unnecessary.

(@liggitt I think we explored this before, but our use case may have been deemed to much of an outlier)

I think we are at a point where we have no way to understand (for some of the Audited API) to be able to tell which OpenAPI operation was called.

**Comment by liggitt** [comment]
> Should we be logging enough information information to map back to the OpenAPI spec?

Mapping audit events back to the openapi spec is not a particular goal of the audit log.

Understanding frequency and type of API access is (especially distinguishing read vs write, and distinguishing different types of write requests).

I think head/get → get is reasonable from an audit perspective

I'm not sure what I would expect `OPTIONS` to map to

**Comment by liggitt** [comment]
Discussed in sig-auth meeting on 2/17

From a requestinfo/audit/authorization perspective:
* The "head/get → get" behavior is working as intended.
* The "verbs other than get/put/post/patch/delete show up as `""` in authorization and audit" behavior is unexpected and should be corrected.

To unblock conformance-testing:
* explicit support for HEAD and OPTIONS methods in the openapi spec is limited to the proxy subresources; special-casing those to recognize coverage from the specific tests that are exercising those (looking for a specific path suffix in the audit log, etc), is reasonable.

**Comment by Riaankl** [comment]
@smarterclayton @liggitt should this be kept open?

**Comment by slaskawi** [comment]
Dear Sig Auth,

I'm a newcomer to the Kubernetes codebase and I would be more than happy to work on this as my first contribution. 

I hope this issue is not time-critical as it might take some time until I learn the codebase.

Thanks!

/assign

**Comment by Riaankl** [comment]
/remove-lifecycle stale
Thank you @slaskawi

**Comment by hh** [comment]
You can take your time, it's been open for a long while.

It'll definitely be a good deep dive into the pool!

Once you wrap your head around what's happening, I'm sure you'll find an excellent solution.

Let us know if you need help.

**Comment by slaskawi** [comment]
Hey @hh @liggitt @Riaankl,

Here's a proposed solution to enhance the audit logs https://github.com/kubernetes/kubernetes/pull/104795

I skimmed through the testsuite and I think it should be fine. If there are any test failures caused by this chance, I'll fix it right away.

**Comment by Riaankl** [comment]
This PR was fixed by https://github.com/kubernetes/kubernetes/pull/95128
/close
