### ISSUE TITLE
kubelet log: Could not get instat cpu stats: cumulative stats decrease

### ISSUE THREAD

**Issue by BedivereZero** [kubernetes/kubernetes#95970]
**What happened**:

kubelet log

> W1028 18:12:53.637170    7954 coversion.go:110] Could not get instat cpu stats: cumulative stats decrease

**What you expected to happen**:

kubelet not log this

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): centos 7
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ruiwen-zhao** [comment]
The error comes from cadvisor ([code](https://github.com/google/cadvisor/blob/bf8fe422ed25ff8046db89b866ca4e1df336f165/info/v2/conversion.go#L247)). It looks like an issue regarding how the CPU usage is measured. Would it make more sense to open an issue there?
