### ISSUE TITLE
API Priority and Fairness aims for even allocation rather than min-max fairness

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#95979]
**What happened**:
@yue9944882 noticed that when the demand is uneven, the QueueSet implementation builds up an ever-increasing imbalance.  See the problem statement in #91567 (which does not have a correct fix, but identifies the problem).  https://github.com/kubernetes/enhancements/pull/1857 fixes the design; you can see the old design in https://github.com/kubernetes/enhancements/blob/f2af06bea1025a084b032ad5eb2c47b786ffa4f6/keps/sig-api-machinery/20190228-priority-and-fairness.md#fair-queuing-for-server-requests .

**What you expected to happen**:
What is known as "max-min fairness".  This is described by the formula for `mu` given early in https://github.com/kubernetes/enhancements/tree/56f1ae1bb67055b8f67b3b0ed019ede5ac0abefc/keps/sig-api-machinery/1040-priority-and-fairness#re-casting-the-original-story .

**How to reproduce it (as minimally and precisely as possible)**:
#91567 outlines this.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by MikeSpreitzer** [comment]
@yue9944882 
@ahg-g 
@lavalamp 
@deads2k 
@tkashem 
@adtac

**Comment by yue9944882** [comment]
and there's also a test proves the existence of the bug: https://github.com/kubernetes/kubernetes/blob/ecfcd5fe596b2683d5419b8ce2460272889f2d94/staging/src/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset_test.go#L526-L559
and additionally i think that our current implementation can also be considered as a variation form of fair-queuing which also defined in the original paper named "B -- bid" (`Bi = MAX(Bi-1 + (Ai - ipsulum) + Pi)`). if the value of "ipsulum" is positive infinite, the fair-queuing will be allowing a big burst of share. so maybe there's a quicker fix for this bug, we explicitly check that the credit accumulation are bounded in certain range?

**Comment by MikeSpreitzer** [comment]
/remove-lifecycle rotten
There is progress here.  See https://github.com/kubernetes/enhancements/pull/2544
