### ISSUE TITLE
Deployment with node selector / tolerations has NodePorts pointing to wrong node IP?

### ISSUE THREAD

**Issue by GraysonCAdams** [kubernetes/kubernetes#95976]
**What happened**: My deployment has the following selector/toleration:
```
      tolerations:
      - effect: NoSchedule
        key: internal-lan
        operator: Exists
      nodeSelector:
        internal-lan: 'true'
```

The workload is running on the correct node...
```
grayson@DESKTOP-4PHPK8A:~/repos/Personal/unifi-kubernetes$ kubectl get pod
NAME                     READY   STATUS    RESTARTS   AGE
unifi-654dbd8754-lrbcf
```

```
grayson@DESKTOP-4PHPK8A:~/repos/Personal/unifi-kubernetes$ kubectl describe pod unifi-654dbd8754-lrbcf
Name:         unifi-654dbd8754-lrbcf
Namespace:    unifi
Priority:     0
Node:         192.168.1.45/192.168.1.45
```

.... but the NodePorts resolve to the wrong Node IP. `[{"addresses":["10.0.0.16"]...`
```
grayson@DESKTOP-4PHPK8A:~/repos/Personal/unifi-kubernetes$ kubectl describe service unifi-gui
Name:                     unifi-gui
Namespace:                unifi
Labels:                   app.kubernetes.io/instance=unifi
                          app.kubernetes.io/managed-by=Helm
                          app.kubernetes.io/name=unifi
                          helm.sh/chart=unifi-1.0.0
Annotations:              field.cattle.io/ipAddresses: null
                          field.cattle.io/publicEndpoints: [{"addresses":["10.0.0.16"],"port":30156,"protocol":"TCP","serviceName":"unifi:unifi-gui","allNodes":true}]
                          field.cattle.io/targetDnsRecordIds: null
                          field.cattle.io/targetWorkloadIds: null
                          meta.helm.sh/release-name: unifi
                          meta.helm.sh/release-namespace: unifi
Selector:                 app.kubernetes.io/instance=unifi,app.kubernetes.io/name=unifi
Type:                     NodePort
IP:                       10.43.222.108
Port:                     https-gui  8443/TCP
TargetPort:               8443/TCP
NodePort:                 https-gui  30156/TCP
Endpoints:                10.42.3.14:8443
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

**What you expected to happen**: NodePort service would resolve to the correct and only node running this deployment.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Rancher RKE On-Prem
- OS (e.g: `cat /etc/os-release`):  Ubuntu 18.04.4 LTS
- Kernel (e.g. `uname -a`): `Linux ranchernode4 4.15.0-122-generic #124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by uablrek** [comment]
Setting the "field.cattle.io/" is not done by K8s and can therefore not be fixed in K8s.

The service uses the default;
```
  externalTrafficPolicy: Cluster
```
which means that the service can be reached from any node. You _may_ try;
```
  externalTrafficPolicy: Local
```
and see if it helps. It might not because, as mentioned, the annotation setting is not done by K8s.

What kind of address is "10.0.0.16"? It should be a node address, but before a node seem to be "192.168.1.45".

**Comment by GraysonCAdams** [comment]
> Setting the "field.cattle.io/" is not done by K8s and can therefore not be fixed in K8s.
> 
> The service uses the default;
> 
> ```
>   externalTrafficPolicy: Cluster
> ```
> 
> which means that the service can be reached from any node. You _may_ try;
> 
> ```
>   externalTrafficPolicy: Local
> ```

I tried setting to local but did not observe any difference.

If I access the node port over the correct IP, it does in fact pull up as it should. However the service references in the UI of Rancher are incorrect.  Could this be a Rancher bug? Such a simple use case should be achievable, right? Am I approaching this wrong?

> and see if it helps. It might not because, as mentioned, the annotation setting is not done by K8s.
> 
> What kind of address is "10.0.0.16"? It should be a node address, but before a node seem to be "192.168.1.45".

10.0.0.16 is on my 10.0.0.0/24 subnet for my VLAN. I have a couple nodes on that VLAN.

The 192.168.1.45 is a node on my immediate LAN.

**Comment by aojea** [comment]
> Setting the "field.cattle.io/" is not done by K8s and can therefore not be fixed in K8s.

Lars is totally right in his comment, and the issue was acknoledged in rancher
https://github.com/rancher/rancher/issues/29833#issuecomment-718985143

Thanks for the detailed explanation ,though :smile: 
/close
