### ISSUE TITLE
Typed client support for Server Side Apply

### ISSUE THREAD

**Issue by jpbetz** [kubernetes/kubernetes#95989]
**What would you like to be added**:

There should be a typesafe, programmatic way to construct server side apply configurations and apply them via the typed client in client-go.

KEP: [Client-go Apply](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/2155-clientgo-apply)

- [ ] Generated builders - https://github.com/kubernetes/kubernetes/pull/99012
- [ ] Generated Apply functions in client-go's typed client
- [ ] BuildApply function support, depends on ExtractManifest support in SMD

**Why is this needed**:

Sending server side apply requests via patch is inconvenient, unergonomic and not in the spirit of the typed client. It also makes it too easy for developers to make non-obvious mistakes like serializing a builtin go struct and sending it as the applied configuration, resulting in the developer owning fields they never explicitly set or intended to own due to zero-values on the go struct being serialized.

/sig api-machinery
/wg api-expression

**Comment by alculquicondor** [comment]
This was actually solved. See https://kubernetes.io/blog/2021/08/06/server-side-apply-ga/#server-side-apply-support-in-client-go for reference.

**Comment by alculquicondor** [comment]
And as part of the godoc: https://pkg.go.dev/k8s.io/client-go@v0.22.1/applyconfigurations
