### ISSUE TITLE
Conversion generator doesn't correctly regenerate conversions if only some directories changed

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#96015]
In the codegenerator we have:
https://github.com/kubernetes/gengo/blob/master/parser/parse.go#L465-L470

So basically we process only packages that are explicitly requested by the user and ignore ones that are imported.
So in order to have the conversion func imported by the generator, the package where it lives has to be explicitly imported.

So we should basically always pass all input packages to conversion generator.

This is problematic, when regenerating conversions, we simply pass to input directories only those that were changed in the meantime:
https://github.com/kubernetes/kubernetes/blob/master/build/root/Makefile.generated_files#L437

We should fix that - probably by passing all CONVERSION_DIRS as inputs to conversion-gen

/kind-bug
@kubernetes/sig-api-machinery-bugs 
@roycaihw @lavalamp @sttts @deads2k

**Comment by roycaihw** [comment]
I think this caused https://github.com/kubernetes/kubernetes/issues/95803. Not sure if https://github.com/kubernetes/kubernetes/issues/78499 was related yet.

**Comment by wojtek-t** [comment]
It's the other way around - this is the main bug and root cause and the other that you linked is a consequence.

**Comment by wojtek-t** [comment]
Also @thockin - FYI

**Comment by wojtek-t** [comment]
I actually already started looking into it - so let me assign this.

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/kubernetes/pull/96041 is out for review
