### ISSUE TITLE
kube-proxy --cleanup don‘t clean ipvs rules

### ISSUE THREAD

**Issue by maaoBit** [kubernetes/kubernetes#96034]
**What happened**:
kube-proxy don’t clean ipvs rules with `--cleanup `. 

**What you expected to happen**:
kube-proxy clean ipvs rules with `--cleanup ` by default. 

**How to reproduce it (as minimally and precisely as possible)**:
Run kube-proxy in ipvs mode, and clean rules with `kube-proxy --cleanup`.

**Anything else we need to know?**:
 Based on https://github.com/kubernetes/kubernetes/pull/76109, `--cleanup` should cleanup all rules by default, including ipvs rules. And `--cleanup-ipvs` also retains functionality.

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.20.0-bate.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
centos7
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by aojea** [comment]
it seems that this flag entered deprecation, so I think that recovering functionaly is not the right approach

https://github.com/kubernetes/kubernetes/blob/aa1f91286838d373a6d9217ad9f4fe0647a1c859/cmd/kube-proxy/app/server.go#L166

@andrewsykim @thockin you were involved in the discussion with this flag in https://github.com/kubernetes/kubernetes/pull/76109, can you take a look at this?

**Comment by maaoBit** [comment]
thanks for your reply. The `--cleanup-IPVS` was added in https://github.com/kubernetes/kubernetes/pull/56036, to avoid removing IPVS rules which are not created by kube-proxy. According to https://github.com/kubernetes/kubernetes/issues/78797#issue-453627530, It seems that deleting ipvs rules by default is expected, but it is not so. I think that keeping --cleanup-ipvs is meaningful, unless kube-proxy can only delete the IPVS rules created by itself.

**Comment by aojea** [comment]
> thanks for your reply. The `--cleanup-IPVS` was added in #56036, to avoid removing IPVS rules which are not created by kube-proxy. According to [#78797 (comment)](https://github.com/kubernetes/kubernetes/issues/78797#issue-453627530), It seems that deleting ipvs rules by default is expected, but it is not so. I think that keeping --cleanup-ipvs is meaningful, unless kube-proxy can only delete the IPVS rules created by itself.

sorr for the late answer @maaoBit , but the flag `--cleanup` must have the same functionality than `--cleanup-ipvs`, actually I can see that it has implemented.

https://github.com/kubernetes/kubernetes/blob/58a1f1658dfecdbc03aef898f5ef8e26965861dd/cmd/kube-proxy/app/server.go#L164

In case that the `--cleanup` is not working we should fix it, but not recover the deprecated flag

**Comment by zouyee** [comment]
> In case that the --cleanup is not working we should fix it, but not recover the deprecated flag
Agreed

**Comment by maaoBit** [comment]
sorry if  I'm missing something. I just try to make the function of `—cleanup-ipvs` as described, not to recover the flag.  The problem I see is:
1.  The `--cleanup` can't flush IPVS. Because the IPVS flush process is still controlled by `ProxyServer.CleanupIPVS`. Beforce https://github.com/kubernetes/kubernetes/pull/76109 , it was assigned by `--cleanup-ipvs` flag, but now it is not assigned, always false.
https://github.com/kubernetes/kubernetes/blob/2b23e71f6c88a08b9ab43523a86e34c4ba0601ae/cmd/kube-proxy/app/server.go#L816
https://github.com/kubernetes/kubernetes/blob/2b23e71f6c88a08b9ab43523a86e34c4ba0601ae/pkg/proxy/ipvs/proxier.go#L806-L813
2. The `--cleanup-ipvs` currently does not have any functionality, just stored by `Options.CleanupIPVS`.

@aojea So, should we keep the function of `—cleanup-ipvs` temporarily by assigning it to `ProxyServer.CleanupIPVS`,or just make `--cleanup` always flushing IPVS regardless of the `--cleanup-ipvs`? I prefer the former because the `—cleanup-ipvs` flag is not completely abandoned :)

**Comment by aojea** [comment]
it seems that is what the flag description says, you have to use `kube-proxy --cleanup --cleanup-ipvs` to flush the ipvs entries

https://github.com/kubernetes/kubernetes/blob/2b23e71f6c88a08b9ab43523a86e34c4ba0601ae/cmd/kube-proxy/app/server.go#L165

if that is the case it seems that we are ok, right?

**Comment by maaoBit** [comment]
In fact, `kube-proxy --cleanup --cleanup-ipvs` can't flush ipvs entries. The reason is what I described above.

**Comment by aojea** [comment]
> In fact, `kube-proxy --cleanup --cleanup-ipvs` can't flush ipvs entries. The reason is what I described above.

I´m sorry, I think I got it know, the flag is not exposed, but the optios is there and initialized to true, this is what I see
```
# ./usr/local/bin/kube-proxy --cleanup -v7
I1215 09:52:01.908569     309 flags.go:59] FLAG: --add-dir-header="false"
I1215 09:52:01.908666     309 flags.go:59] FLAG: --alsologtostderr="false"
I1215 09:52:01.908672     309 flags.go:59] FLAG: --bind-address="0.0.0.0"
I1215 09:52:01.908679     309 flags.go:59] FLAG: --bind-address-hard-fail="false"
I1215 09:52:01.908684     309 flags.go:59] FLAG: --cleanup="true"
I1215 09:52:01.908687     309 flags.go:59] FLAG: --cleanup-ipvs="true"
```

**Comment by maaoBit** [comment]
> ```
> 908569     309 flags.go:59] FLAG: --add-dir-header="false"
> I1215 09:52:01.908666     309 flags.go:59] FLAG: --alsologtostderr="false"
> I1215 09:52:01.908672     309 flags.go:59] FLAG: --bind-address="0.0.0.0"
> I1215 09:52:01.908679     309 flags.go:59] FLAG: --bind-address-hard-fail="false"
> I1215 09:52:01.908684     309 flags.go:59] FLAG: --cleanup="true"
> I1215 09:52:01.908687     309 flags.go:59] FLAG: --cleanup-ipvs="true"
> ```
> 
> 
> so, it seems that `kube-proxy --cleanup` flush IPVS by default

yes, `kube-proxy --cleanup` should flush IPVS by default, but  it doesn’t actually

**Comment by aojea** [comment]
> yes, `kube-proxy --cleanup` should flush IPVS by default, but it doesn’t actually

... and finally I got it, so sorry :bow: the ProxyServer is not being instantiated with the flag, despite is set :facepalm: 

> @aojea So, should we keep the function of —cleanup-ipvs temporarily by assigning it to ProxyServer.CleanupIPVS,or just make --cleanup always flushing IPVS regardless of the --cleanup-ipvs? I prefer the former because the —cleanup-ipvs flag is not completely abandoned 

@andrewsykim @uablrek you are more familiar with the IPVS implementation than me, I personally think that, if the flag deprecation has started, we should make that `--cleanup` always flush IPVS and totally remove `--cleanup-ipvs` ... it seems aligned with the other proxy implementations

https://github.com/kubernetes/kubernetes/issues/96034#issuecomment-745132981

**Comment by aojea** [comment]
Actually, after doing some code archaeology, this was the expectation per https://github.com/kubernetes/kubernetes/pull/83832

And the flag clearly mentions that --cleanup must flush IPVS entries too

https://github.com/kubernetes/kubernetes/blob/2b23e71f6c88a08b9ab43523a86e34c4ba0601ae/cmd/kube-proxy/app/server.go#L166

I think that we can go ahead and remove the --cleanup-ipvs flag and make --cleanup to flush ipvs too, right now is a mess and is not working at all @maaoBit , are you going to submit a PR?

**Comment by andrewsykim** [comment]
@aojea thanks for digging up the history on this. That lines up with my recollection and the KEP around kube-proxy's clean up logic https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190324-remove-kube-proxy-autocleanup.md

**Comment by maaoBit** [comment]
> Actually, after doing some code archaeology, this was the expectation per #83832
> 
> And the flag clearly mentions that --cleanup must flush IPVS entries too
> 
> https://github.com/kubernetes/kubernetes/blob/2b23e71f6c88a08b9ab43523a86e34c4ba0601ae/cmd/kube-proxy/app/server.go#L166
> 
> I think that we can go ahead and remove the --cleanup-ipvs flag and make --cleanup to flush ipvs too, right now is a mess and is not working at all @maaoBit , are you going to submit a PR?

OK, I will create a PR to remove the `--cleanup-ipvs` flag
