### ISSUE TITLE
Statefulset can't have QoS Guaranteed 

### ISSUE THREAD

**Issue by frbimo** [kubernetes/kubernetes#96044]
I found that pod QoS isn't `Guaranteed` when i set resources limit and request equal. 
Moreover, under kubernetes configuration with `cpuManagerPolicy: static`, seeing from overall cpu usage, there is no _cpu isolation_ as i expected.

Did i miss something or this is by design?

**What happened**:
QoS Class is `Burstable` when` limits is equal requests` on `Statefulset`
**What you expected to happen**:
QoS Class `Guaranteed`
**How to reproduce it (as minimally and precisely as possible)**:
helm deploy apps with Statefulset  (in my case, default replicas=3)

**Anything else we need to know?**:
kubectl describe po <pod-name>
```
Name:         mongodb-ha-mongodb-replicaset-0
Namespace:    db
Priority:     0
Node:         k8s-node2/<redacted>
Start Time:   <redacted>
Labels:       app=mongodb-ha-mongodb-replicaset
              chart=mongodb-ha-loadbalancer
              controller-revision-hash=mongodb-ha-mongodb-replicaset-574654d876
              heritage=Helm
              release=mongodb-ha
              statefulset.kubernetes.io/pod-name=mongodb-ha-mongodb-replicaset-0
Annotations:  <none>
Status:       Running
IP:           10.233.64.20
IPs:
  IP:           10.233.64.20
Controlled By:  StatefulSet/mongodb-ha-mongodb-replicaset
Init Containers:
  install:
    Container ID:  containerd://e684c3d8414786366bab77cbb4ee40de9bc55206ab1c5f3714b7c8ed4953c3d6
    Image:         <redacted>
    Image ID:      <redacted>
    Port:          <none>
    Host Port:     <none>
    Args:
      --work-dir=/work-dir
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      <redacted>
      Finished:     <redacted>
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-szw4b (ro)
      /work-dir from workdir (rw)
  bootstrap:
    Container ID:  containerd://5b37086cd5b3903eb6f1f4665b25e1dda6df4d7c66f17f5286701703ff2fb94a
    Image:         mongo:4.2.8-bionic
    Image ID:      docker.io/library/mongo@sha256:ace03acac85f185981731116fa39bf01b3f2aa98620f5e5f04cf40815aa2aaec
    Port:          <none>
    Host Port:     <none>
    Command:
      /work-dir/bootstrap
    Args:
      -config
      /etc/config/mongod.conf
      -dbPath
      /data/db
      -replSet
      rs0
      -bindIP
      0.0.0.0
      -port
      27017
      -auth
      true
      -tls
      false
      -sts
      mongodb-ha-mongodb-replicaset
      -serviceType
      ClusterIP
      -cap
      2
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      <redacted>
      Finished:     <redacted>
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /data/db from mongodb-ha (rw)
      /etc/config from config-volume (rw)
      /etc/mongodb-auth from auth-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-szw4b (ro)
      /var/store/mongodb from keyfile-volume (rw)
      /work-dir from workdir (rw)
Containers:
  mongo:
    Container ID:  containerd://0d72f8d74d4a4282b47861f4c6525ca5a4b8ee905162d82259881b0b9f13d487
    Image:         mongo:4.2.8-bionic
    Image ID:      docker.io/library/mongo@sha256:ace03acac85f185981731116fa39bf01b3f2aa98620f5e5f04cf40815aa2aaec
    Port:          27017/TCP
    Host Port:     0/TCP
    Command:
      mongod
      --auth
      --replSet
      rs0
      --port
      27017
      --config
      /etc/config/mongod.conf
    State:          Running
      Started:      <redacted>
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  8Gi
    Requests:
      cpu:        2
      memory:     8Gi
    Environment:  <none>
    Mounts:
      /data/db from mongodb-ha (rw)
      /etc/config from config-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-szw4b (ro)
      /var/store/mongodb from keyfile-volume (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  mongodb-ha:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  mongodb-ha-mongodb-ha-mongodb-replicaset-0
    ReadOnly:   false
  workdir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  keyfile-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  mongodb-ha-mongodb-replicaset-keyfile
    Optional:    false
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      mongodb-ha-mongodb-replicaset-configmap
    Optional:  false
  auth-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  mongodb-ha-mongodb-replicaset-auth
    Optional:    false
  default-token-szw4b:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-szw4b
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
```
**Environment**:
~~Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}~~
~~Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}~~

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g: `cat /etc/os-release`): 18.04.5 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`): Linux k8s-node2 5.4.0-52-generic #57~18.04.1-Ubuntu

- Install tools: kubespray
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by frbimo** [comment]
v1.19.2 also have similar problem

**Comment by frbimo** [comment]
After investigating for hours, i found there are `Init Containers`  that use different resources values. 
Fixed the issue by setting resource identical with `containers` 's resource value.

https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed does not have a particular example of `statefulset`.  Since `statefulset` kind can have container and Init container and they are a different entity, thus the term `Every Container` is quite unclear. Briefly read the document i have assumed it refers to `containers `only.

It will save me sometimes if the documentation has example using `init Containers` since in my case, this related to `cpu-manager-policy` behavior.

/kind doc 
/remove-kind bug

Otherwise, you can close the issue.

**Comment by ruiwen-zhao** [comment]
Yes you are right, the doc on qos (https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/) does not mention anything about init containers. However, the doc on [Init Contianers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#resources) does mention it:
> The QoS (quality of service) tier of the Pod's effective QoS tier is the QoS tier for init containers and app containers alike.

I guess one thing we could improve here is to mention that init containers on our QoS doc.

**Comment by ruiwen-zhao** [comment]
I am closing this issue since the doc has been updated.
