### ISSUE TITLE
Secret resources claim created but doesn't exist

### ISSUE THREAD

**Issue by ASAPHAANING** [kubernetes/kubernetes#96046]
**What happened**: Tried to modify this secret. Didn't get reflected. Deleted it, recreaed it. Then the following happens:

```
➜ kubectl apply -f postgresql-creds2.yml -n default && kubectl get secret database-psql -n default
secret/database-psql created
Error from server (NotFound): secrets "database-psql" not found

...

➜ kubectl apply -f postgresql-creds2.yml -n default && kubectl get secret database-psql -n default
secret/database-psql created
Error from server (NotFound): secrets "database-psql" not found
```

**What you expected to happen**: Create the secret.

**How to reproduce it (as minimally and precisely as possible)**: Not sure.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-dispatcher", GitCommit:"f2a77f678d6baccda27740d700f6cba2754dfacf", GitTreeState:"clean", BuildDate:"2020-04-21T04:42:07Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-14T00:06:38Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```
- Cloud provider or hardware configuration: Azure AKS
- OS (e.g: `cat /etc/os-release`): 
```
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
``` 
- Kernel (e.g. `uname -a`): `Linux haaningDesktop 5.4.72-1-MANJARO #1 SMP PREEMPT Sat Oct 17 11:06:19 UTC 2020 x86_64 GNU/Linux`
- Install tools: `yay`
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
/remove-sig auth
/kind support

Is something else deleting the secret in the background? If you start this in another tab before doing the apply, do you see a delete event?

```
kubectl get secrets -n default --watch --output-watch-events
```

**Comment by ASAPHAANING** [comment]
@liggitt It was a service account secret as opposed to a generic one. Thanks for paying attention to it though.
