### ISSUE TITLE
[Failing Test] Services should be able to change the type from {ClusterIP, NodePort} to ExternalName [Conformance]

### ISSUE THREAD

**Issue by thejoycekung** [kubernetes/kubernetes#96055]
**Which jobs are failing**:
`ci-cluster-api-provider-gcp-make-conformance-v1alpha3-k8s-ci-artifacts`

**Which test(s) are failing**:
`[sig-network] Services should be able to change the type from ClusterIP to ExternalName [Conformance]`
`[sig-network] Services should be able to change the type from NodePort to ExternalName [Conformance]`

**Since when has it been failing**:
Oct 29

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#capg-conformance-v1alpha3-k8s-master

**Reason for failure**:
NodePort:
```
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:629
Oct 30 04:29:08.220: Unexpected error:
    <*errors.errorString | 0xc00453d130>: {
        s: "failed to update Service \"nodeport-service\": Service \"nodeport-service\" is invalid: spec.clusterIP: Forbidden: must be empty for ExternalName services",
    }
    failed to update Service "nodeport-service": Service "nodeport-service" is invalid: spec.clusterIP: Forbidden: must be empty for ExternalName services
occurred
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1819
```

ClusterIP:
```
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:629
Oct 30 04:47:14.336: Unexpected error:
    <*errors.errorString | 0xc002c00e90>: {
        s: "failed to update Service \"clusterip-service\": Service \"clusterip-service\" is invalid: spec.clusterIP: Forbidden: must be empty for ExternalName services",
    }
    failed to update Service "clusterip-service": Service "clusterip-service" is invalid: spec.clusterIP: Forbidden: must be empty for ExternalName services
occurred
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1775
```

**Anything else we need to know**:
Example spyglass link: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cluster-api-provider-gcp-make-conformance-v1alpha3-k8s-ci-artifacts/1322004114833412096

Triage link: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=%20should%20be%20able%20to%20change%20the%20type%20from%20ClusterIP%20to%20ExternalName#36196c1107a0324e2698

/cc @kubernetes/ci-signal 
/priority important-soon
/sig network

**Comment by jayunit100** [comment]
Looks like a magic number in the retry ... should we make it bigger or do a different retry ? + also looks like this isn't a common failure... not necessarily the "root" cause, but presumably if this value was higher, this would be less likely to abruptly blow up.  

```
func (j *TestJig) UpdateService(update func(*v1.Service)) (*v1.Service, error) {
	for i := 0; i < 3; i++ {
```

Are there guidelines on how many times a single instant transaction API call should be retried in the e2es?

**Comment by alejandrox1** [comment]
Gonna work on the magic number thing separate from this issue in https://github.com/kubernetes/kubernetes/issues/96078 - just to keep things organized - since Carlos is working on this one for the cluster API job.

**Comment by hasheddan** [comment]
Did some digging and this changed in https://github.com/kubernetes/kubernetes/commit/4f8fb1d3ca5ac8cbacf814a75fbe92f7093bc23e, but is causing issues because of CAPG using new conformance tests against an old k8s version as describe in #96577. I'm going to see if we can address this skew.

**Comment by cpanato** [comment]
job is green again, saw one test failed but then passed in the next run

closing this issue
/close
