### ISSUE TITLE
invalid bearer token, square/go-jose: error in cryptographic primitive

### ISSUE THREAD

**Issue by orlakwahr** [kubernetes/kubernetes#96053]
this is a fresh install with kubeadm init.
all by https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/
the only addition I had to do was mount --bind /var/lib/kubelet /var/lib/kubelet because of btrfs

I have a lot of

Oct 30 18:12:14 lhost kubelet[5451]: W1030 18:12:14.385578    5451 container.go:549] Failed to update stats for container "/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podb79782dc_dcf6_457f_9659_a29fda9cc7f3.slice/docker-a135471346b107f81dfdd57ef6f92b9a257c1370746cd23d8c71e15b172afe82.scope": unable to determine device info for dir: /var/lib/docker/overlay2/5875157d56748eb5a1cd09464e3bd72ecf40f173bbd906a2dda7eaa9d7d97f6a/diff: could not find device with major: 0, minor: 23 in cached partitions map, continuing to push stats
Oct 30 18:12:17 lhost kubelet[5451]: W1030 18:12:17.137666    5451 container.go:549] Failed to update stats for container "/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podc51f9a96_34eb_4cc1_897f_d5bf81e91fb2.slice/docker-55ed432cfe5dbc9b2be4a5401e84773f0ae07c279496f375d06d4ceab679ce9b.scope": unable to determine device info for dir: /var/lib/docker/overlay2/99ef78c54cc9f17d8c1fbdad0c0a0a36e06f7a6bda5ced878012947e5af356f9/diff: could not find device with major: 0, minor: 23 in cached partitions map, continuing to push stats
Oct 30 18:12:19 lhost kubelet[5451]: W1030 18:12:19.493022    5451 container.go:549] Failed to update stats for container "/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod2eeea5ebc1e6847fb0d92169c8fd647a.slice/docker-08eb979fab4c5fcfc71ede03b4cd8f6057f552cef623446725a9738bf5aa75fa.scope": unable to determine device info for dir: /var/lib/docker/overlay2/b9494d39f1b6017038e7f72ead413d2cd97c4e1ae5e50178250dfa1aa6355431/diff: could not find device with major: 0, minor: 23 in cached partitions map, continuing to push stats
Oct 30 18:12:19 lhost kubelet[5451]: W1030 18:12:19.968628    5451 container.go:549] Failed to update stats for container "/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod4fc2afac33a8cd91d90c1959e302f551.slice/docker-f5cb8d5744bd3d1ce8b23c39625e5f0b1a6dc487959aedab44e58e4d1ee6b5b4.scope": unable to determine device info for dir: /var/lib/docker/overlay2/aff6cb9334f0f1fac13191fde056ff8211e6b9acc0ed4f75e0f0a40af36226a9/diff: could not find device with major: 0, minor: 23 in cached partitions map, continuing to push stats
Oct 30 18:12:22 lhost kubelet[5451]: E1030 18:12:22.907576    5451 server.go:265] Unable to authenticate the request due to an error: [invalid bearer token, square/go-jose: error in cryptographic primitive]

if I do:

#!/bin/bash

token=$(echo $1|base64 -d)
echo $token
curl -XGET -H "Authorization:Bearer $token" -k https://127.0.0.1:10248/healthz

I receive nothing

**Environment**:
kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

Debian GNU/Linux 10 (buster)
Linux lhost 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux

using flannel

**Comment by neolit123** [comment]
hi, please try the support channels first:
hi, please try the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

if this is a confirmed bug in core k8s then re-open this ticket.

/close
