### ISSUE TITLE
apiserver lacks validation for duplicate owner reference entries

### ISSUE THREAD

**Issue by roycaihw** [kubernetes/kubernetes#96065]
**What happened**:
apiserver allows objects being created/updated with duplicate owner reference entries, which may lead to huge objects being created in the system.
```
$ kubectl get configmaps child -oyaml
...
  ownerReferences:
  - apiVersion: v1
    kind: ConfigMap
    name: owner
    uid: f78b92c5-d24c-410e-9bda-ab298ffe7f7d
  - apiVersion: v1
    kind: ConfigMap
    name: owner
    uid: f78b92c5-d24c-410e-9bda-ab298ffe7f7d
  - apiVersion: v1
    kind: ConfigMap
    name: owner
    uid: f78b92c5-d24c-410e-9bda-ab298ffe7f7d
...
```

**What you expected to happen**:
The apiserver either rejects the request, or silently removes the duplicates. 

Rejecting the requests is going to break the clients that is doing this, plus people won't be able to write to the existing objects without fixing the owner references. I'm going to add a validation and see if it breaks any in-tree components in tests [UPDATE: #96069- I didn't find any in-tree controller doing this]. OTOH silently removing the duplicates seems to be a safer path. Comments and suggestions are welcome.

**How to reproduce it (as minimally and precisely as possible)**:
Run https://gist.github.com/roycaihw/e4990f45fae50dbd0a69d44842191ea5. The result is similar to:
```
owner: &ConfigMap{ObjectMeta:{owner  default  0847a511-2e7b-4e20-9044-050a637f2320 702 0 2020-10-30 15:38:55 -0700 PDT <nil> <nil> map[] map[] [] []  []},Data:map[string]string{},BinaryData:map[string][]byte{},Immutable:nil,}
child: &ConfigMap{ObjectMeta:{child  default  d7c01603-8f9f-426d-9d6a-564c99118968 713 0 2020-10-30 15:38:55 -0700 PDT <nil> <nil> map[] map[] [{v1 ConfigMap owner 0847a511-2e7b-4e20-9044-050a637f2320 <nil> <nil>} {v1 ConfigMap owner 0847a511-2e7b-4e20-9044-050a637f2320 <nil> <nil>} {v1 ConfigMap owner 0847a511-2e7b-4e20-9044-050a637f2320 <nil> <nil>} {v1 ConfigMap owner 0847a511-2e7b-4e20-9044-050a637f2320 <nil> <nil>} {v1 ConfigMap owner 0847a511-2e7b-4e20-9044-050a637f2320 <nil> <nil>} {v1 ConfigMap owner 0847a511-2e7b-4e20-9044-050a637f2320 <nil> <nil>} {v1 ConfigMap owner 0847a511-2e7b-4e20-9044-050a637f2320 <nil> <nil>} {v1 ConfigMap owner 0847a511-2e7b-4e20-9044-050a637f2320 <nil> <nil>} {v1 ConfigMap owner 0847a511-2e7b-4e20-9044-050a637f2320 <nil> <nil>} {v1 ConfigMap owner 0847a511-2e7b-4e20-9044-050a637f2320 <nil> <nil>} {v1 ConfigMap owner 0847a511-2e7b-4e20-9044-050a637f2320 <nil> <nil>}] []  []},Data:map[string]string{},BinaryData:map[string][]byte{},Immutable:nil,}
```

**Anything else we need to know?**:
The garbage collector is capable of clean up the duplicates for both [in-tree resources](https://github.com/kubernetes/kubernetes/blob/c0c0aa341f0a3311db69f92a67caed88c9e36eb1/pkg/controller/garbagecollector/patch.go#L44) and [custom resources](https://github.com/kubernetes/kubernetes/blob/c0c0aa341f0a3311db69f92a67caed88c9e36eb1/pkg/controller/garbagecollector/patch.go#L145). 

**Environment**:
- Kubernetes version (use `kubectl version`): master HEAD

/sig api-machinery
cc @lavalamp @deads2k

**Comment by roycaihw** [comment]
Such requests will also cause the `managedFields` to be [cleared](https://github.com/kubernetes/kubernetes/blob/ac996a37f65a8f11640808a883e9522832ed364f/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/create.go#L164).
```
E1103 11:24:56.284054 3850496 fieldmanager.go:186] [SHOULD NOT HAPPEN] failed to update managedFields for /, Kind=: failed to convert new object (/v1, Kind=ConfigMap) to smd typed: .metadata.ownerReferences: duplicate entries for key [uid="2c0020f2-7d51-4d27-9101-a8cc1d7e1ee5"]
```

@apelisse @jennybuckley FYI

**Comment by fedebongio** [comment]
/cc @liggitt 
the sig is interested in knowing your opinion
/triage accepted

**Comment by roycaihw** [comment]
Added the issue to the SIG meeting agenda tomorrow as well.

**Comment by apelisse** [comment]
> Such requests will also cause the managedFields to be cleared.

yeah, we assume that this is a "set" (which is the same assumption you're making), and I think that's right.

**Comment by liggitt** [comment]
> apiserver allows objects being created/updated with duplicate owner reference entries, which may lead to huge objects being created in the system

Is the concern about malicious clients or naive clients that append duplicate owner references? Are there actual examples of the latter?

> we assume that this is a "set"

with `uid` as the key?

**Comment by apelisse** [comment]
> with uid as the key?

[Correct](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L240-L247).

**Comment by roycaihw** [comment]
> Is the concern about malicious clients or naive clients that append duplicate owner references? Are there actual examples of the latter?

the latter. The one that I'm aware of: https://github.com/operator-framework/operator-lifecycle-manager/issues/1237

**Comment by lavalamp** [comment]
In the meeting earlier today, the SIG more or less decided to a) add a warning header and b) dedup without failing requests.

Deduping should be over the entire entry, not just the UID field.
