### ISSUE TITLE
Allowing activeDeadlineSeconds to be set for deployments

### ISSUE THREAD

**Issue by andy-v-h** [kubernetes/kubernetes#96067]
**What would you like to be added**:

I would like to be able to set a `deployment.spec.template.spec.activeDeadlineSeconds`. 

**Why is this needed**:

One of the teams on the k8s platform I manage is having a memory leak. Which is an issue they are working on, however in the mean time a `SIGTERM` to the pod triggers a graceful shut down. However when the memory limit is reached we get a `SIGKILL` - expected behavior. This `SIGKILL` causes Production issues when customer payloads get stuck in processing. I for one, and i think many other in the community, would be able to leverage this feature for better application stability. This [response](https://github.com/kubernetes/kubernetes/issues/70790#issuecomment-437635926)  from 2018 doesn't consider all use cases and is based in principals, which seldom are respected by production environments.

** Related issues**:
https://github.com/kubernetes/kubernetes/issues/40157
https://github.com/kubernetes/kubernetes/issues/70790
https://github.com/kubernetes/kubernetes/issues/38684

**Comment by kradalby** [comment]
I agree with @andy-v-h  that the blanket statement "it does not make sense" for ReplicaSet. There is multiple usecases for this, in additional to the original post, we have one were we are fitting an off the shelf app into our auth system, requiring it to fetch the token every 12h, were cycling the pods would make complete sense.
