### ISSUE TITLE
A single resource cache sync failure shouldn't break the entire ResourceQuota controller logic

### ISSUE THREAD

**Issue by alena1108** [kubernetes/kubernetes#96066]
**What happened**:

1. Had a failing conversion webhook for one of the CRDs
2. ResourceQuota controller started throwing errors "timed out waiting for quota monitor sync", and the resource subtraction logic stopped working: https://github.com/kubernetes/kubernetes/blob/f2ed1b55803177c9b02b0acf134a011a5fb20544/pkg/controller/resourcequota/resource_quota_controller.go#L448

**What you expected to happen**:

I think that a single cache failure for a countable resource shouldn't break the entire resource controller logic. Or there should be a configuration to exclude a complimentary resource like CRDs, from the countable resource quota calculations.
As in many cases people care about compute/storage quota enforcement the most. 

I also accept that I might be missing something, and looking forward to understand the reasons behind the current design.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a resource quota with cpu requests/limits. Create pod with cpu requests/limits. Watch resource quota used field being updated. 
2. Add a conversion webhook for any CRD, and make this webhook fail. Make sure that you have a CRD object requiring conversion, present on the etcd to trigger the conversion.
3. Delete the pod created on step 1). Watch that resourceQuota used field doesn't get updated. You'll start seeing "timed out waiting for quota monitor sync" in controller-manager logs. 

**Anything else we need to know?**:

Same scenario breaks a GC controller as well.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18 or higher
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by lavalamp** [comment]
/sig api-machinery

(so we see it in our triage meeting)

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/74747 was intended to address the issue described here. It lets the "wait for cache sync" step time out and resume quota operations for the resources that are synced.

It added a unit test for this (quota-missing-status-with-partial-calculation-error) that sets up a quota that uses pods and configmaps, sets up informers that work for configmaps and fail for pods, and verifies the configmap status gets computed successfully on the quota object.

It's possible there's a different path being taken for custom resources that needs to be tested/addressed.

**Comment by alena1108** [comment]
@liggitt the issue doesn't present on k8s 1.17, and surfaced on k8s 1.18 on the very same environment, with the same broken webhook. Not sure what changes in 1.18 made it start happening.

**Comment by liggitt** [comment]
That's helpful to know, thanks. Interestingly, there were no changes to the resource quota controller or framework between those releases:

```
$ git diff v1.17.0 upstream/release-1.18 -- pkg/quota
<no changes>

$ git diff v1.17.0 upstream/release-1.18 -- pkg/controller/resourcequota
diff --git a/pkg/controller/resourcequota/resource_quota_controller.go b/pkg/controller/resourcequota/resource_quota_controller.go
index 363e077850d..4b1062bad5f 100644
--- a/pkg/controller/resourcequota/resource_quota_controller.go
+++ b/pkg/controller/resourcequota/resource_quota_controller.go
@@ -17,6 +17,7 @@ limitations under the License.
 package resourcequota
 
 import (
+       "context"
        "fmt"
        "reflect"
        "sync"
@@ -355,7 +356,7 @@ func (rq *ResourceQuotaController) syncResourceQuota(resourceQuota *v1.ResourceQ
 
        // there was a change observed by this controller that requires we update quota
        if dirty {
-               _, err = rq.rqClient.ResourceQuotas(usage.Namespace).UpdateStatus(usage)
+               _, err = rq.rqClient.ResourceQuotas(usage.Namespace).UpdateStatus(context.TODO(), usage, metav1.UpdateOptions{})
                if err != nil {
                        errors = append(errors, err)
                }
```

**Comment by liggitt** [comment]
I'm having a hard time reproducing this on master. I did the following:

1. Created a CRD with a v1alpha1 version
2. Created a CR instance of the CRD at v1alpha2
3. Updated the CRD to have a second version that was marked as the storage version, and a conversion webhook pointing at a dummy service
4. Verified the controller manager started logging sync timeouts for the bogus CR: `E1102 15:39:45.603280   38483 resource_quota_controller.go:448] timed out waiting for quota monitor sync` (this is expected, since the quota controller is not able to sync all caches for all resources)
5. Created resourcequota objects with count quotas for configmaps, secrets, and the custom resource
6. The quota status was updated for configmaps and secrets
7. Created configmap and secret resources. The quota status was incremented.
8. Deleted the configmaps. The quota status was decremented.

**Comment by liggitt** [comment]
Detailed steps with manifests:

1. Create CRD 
[1-webhookcrd.yaml.txt](https://github.com/kubernetes/kubernetes/files/5478025/1-webhookcrd.yaml.txt)

2. Create CR instance
[2-cr.yaml.txt](https://github.com/kubernetes/kubernetes/files/5478026/2-cr.yaml.txt)

3. Update CRD to add new version, stop serving original version, add broken conversion webhook
[3-webhookcrd.yaml.txt](https://github.com/kubernetes/kubernetes/files/5478027/3-webhookcrd.yaml.txt)

... wait for kube-controller-manager to start logging quota sync timeouts

4. Add quota objects
[4-quota.yaml.txt](https://github.com/kubernetes/kubernetes/files/5478028/4-quota.yaml.txt)

5. Create objects [5-objects.yaml.txt](https://github.com/kubernetes/kubernetes/files/5478029/5-objects.yaml.txt), see quota use jump immediately

6. Delete objects, see quota use drop

**Comment by liggitt** [comment]
I also tried reproducing on 1.18 and was unable to.

**Comment by liggitt** [comment]
Are you deleting the pod directly, or are you deleting a parent resource like a replicaset or deployment and waiting on garbage collection to remove the pod?

**Comment by alena1108** [comment]
@liggitt let me check with the team, and I'll get back to you! Thank you for looking into it.

**Comment by alena1108** [comment]
@liggitt looks like it's been a mix of managed (replicaset/deployment managed) and non-managed pods being deleted when we've observed the issue in prod. If it doesn't reproduce on your end for the managed pods, we'll run more tests in house to hopefully narrow it down.

**Comment by liggitt** [comment]
> looks like it's been a mix of managed (replicaset/deployment managed) and non-managed pods being deleted

GC *will* block on a persistently failing resource... GC requires recognized resource types to be resolveable

**Comment by alena1108** [comment]
@liggitt 

> GC will block on a persistently failing resource... GC requires recognized resource types to be resolveable

Does it mean that it's by design? And failing CRD can cause the entire GC to block, and that in turn affected the resource quota controller?

**Comment by liggitt** [comment]
Because of two-way relationships between objects caused by things like `blockOwnerDeletion`, if GC knows it has an inconsistent view of objects (because it cannot sync a resource type), it will fail safe and stop deleting things.

Quota will not release used resources until the objects are deleted.

**Comment by alena1108** [comment]
@liggitt just to confirm - this GC logic was the same in 1.17? Or did anything change in 1.18. Trying to figure out why the issue has surfaced in 1.18 only in our environment, will take any theory :)

**Comment by liggitt** [comment]
No, that has always been the GC behavior

**Comment by aojea** [comment]
> > looks like it's been a mix of managed (replicaset/deployment managed) and non-managed pods being deleted
> 
> GC _will_ block on a persistently failing resource... GC requires recognized resource types to be resolveable


/close
