### ISSUE TITLE
How to distinguish between manual and HPA modification of replicas

### ISSUE THREAD

**Issue by jacky68147527** [kubernetes/kubernetes#96074]
I used admission webhook to intercept the changes of replicas, because I need to call the external interface to approve the resources when it is triggered by HPA, but manual changes do not need to be intercepted, please help me,thanks!

**Comment by jacky68147527** [comment]
I used admission webhook to intercept the changes of replicas, because I need to call the external interface to approve the resources when it is triggered by HPA, but manual changes do not need to be intercepted, please help me,thans!

**Comment by neolit123** [comment]
hi, please try the support channels (e.g. #sig-autoscaling) first:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

this repository is for feature requests and bugs (if confirmed)

thanks
/close
