### ISSUE TITLE
[Failing Test] gce-master-scale-correctness (ci-kubernetes-e2e-gce-scale-correctness)

### ISSUE THREAD

**Issue by hkamel** [kubernetes/kubernetes#96078]
**Which jobs are failing**:
`ci-kubernetes-e2e-gce-scale-correctness`

**Which test(s) are failing**:
- `Kubernetes e2e suite.[sig-network] Services should be able to change the type from NodePort to ExternalName [Conformance]`
- `Overall`
- `Test`

**Since when has it been failing**:
`10-31 16:01 UTC+04`

**Testgrid link**:
`https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-master-scale-correctness`

**Reason for failure**:
`/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:629
Oct 31 12:42:54.971: Unexpected error:
    <*errors.errorString | 0xc00a2a64b0>: {
        s: "ExternalName service \"services-4494/execpod6pwjf\" must resolve to IP",
    }
    ExternalName service "services-4494/execpod6pwjf" must resolve to IP
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1818`

**Anything else we need to know**:
/sig network
/priority important-soon
/cc @kubernetes/ci-signal

**Comment by jayunit100** [comment]
Looks like a magic number in the retry ... should we make it bigger or do a different retry ? + also looks like this isn't a common failure... 
```
func (j *TestJig) UpdateService(update func(*v1.Service)) (*v1.Service, error) {
	for i := 0; i < 3; i++ {

```

**Comment by thejoycekung** [comment]
dupe of #96055

@jayunit100 there's a related PR open for this currently: kubernetes/test-infra#19752 if you want to take a look

/close

**Comment by alejandrox1** [comment]
Actually, let's reopen this one.
This is not a dupe of #96055 - #96055 is failing [potentially] because of cluster API configuration issues.
This one failure is a "flake" because of the test has uses a magic number to check for a condition, as @jayunit100 mentioned in https://github.com/kubernetes/kubernetes/issues/96078#issuecomment-720103036

@hkamel would you like to work on this one with me?

/reopen
/triage accepted

**Comment by hkamel** [comment]
> Actually, let's reopen this one.
> This is not a dupe of #96055 - #96055 is failing [potentially] because of cluster API configuration issues.
> This one failure is a "flake" because of the test has uses a magic number to check for a condition, as @jayunit100 mentioned in [#96078 (comment)](https://github.com/kubernetes/kubernetes/issues/96078#issuecomment-720103036)
> 
> @hkamel would you like to work on this one with me?
> 
> /reopen
> /triage accepted

thanks, @alejandrox1 ... sure let me know how can I help

**Comment by thejoycekung** [comment]
This issue is now a few months old and the test is no longer failing with this error message, so I'm going to go ahead and close it

/close
