### ISSUE TITLE
unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined

### ISSUE THREAD

**Issue by virendrasuryavanshi** [kubernetes/kubernetes#96070]
**What happened**:
I'm using `kubeCfg,err := rest.InClusterConfig()` for getting the cluster config inside of minikube for the dynamic informer.
```
//go run main.go

FATA[0000] could not get config                          error="unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined"
exit status 1
```

**How to reproduce it (as minimally and precisely as possible)**:
- export GO111MODULE=on

- go mod init ([go.mod file](https://codeshare.io/5wm9LP))

- Run the [dynamic informer](https://codeshare.io/GAPpLl) 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T21:54:15Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: minikube 

- Kernel (e.g. `uname -a`): Darwin Kernel Version 19.5.0

I found various similar issues related to this but couldn't find any solution or workaround.
- https://github.com/kubernetes/kubernetes/issues/40973
- https://github.com/coreos/etcd-operator/issues/731

**Comment by jayunit100** [comment]
This is not a sig-net issue, but its just that your client doesn't have the metadata passed into it properly can you take a quick look at the docs for https://github.com/kubernetes/client-go and make sure nothing solves it for you ?

**Comment by alejandrox1** [comment]
Not a sig node issue either but let's figure this one out.
@virendrasuryavanshi how were you running the code? Can you post the yaml, please?
Did you define the environment variable `KUBECONFIG` in the pod running the code?

/remove sig-node
/assign

**Comment by virendrasuryavanshi** [comment]
@alejandrox1 Thanks for taking your interest in this issue, really appreciated. I just figured out that this was because I was trying to get the cluster config from outside of the cluster which was leading the program on my local machine (127.0.0.1) from where I am not able to access the cluster. Is there a way through which I can access the cluster configuration from outside the cluster and can run the dynamic informer? As I don't want to implement this via deployment controller!

**Comment by neolit123** [comment]
for InClusterConfig
/sig api-machinery
/remove-kind bug
/triage support

**Comment by yliaog** [comment]
InClusterConfig is used for running inside cluster use case, when running outside cluster, please use something like the following:

config, err = clientcmd.BuildConfigFromFlags("", *kubeconfigPath)

then use: clientset, err := kubernetes.NewForConfig(config)

or: client, err := dynamic.NewForConfig(config)

**Comment by virendrasuryavanshi** [comment]
@yliaog Did you mean [this](https://codeshare.io/2jQ7bP)? It didn't work.

It gives the following error
```
W1107 13:38:03.643218   13476 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W1107 13:38:03.643323   13476 client_config.go:548] error creating inClusterConfig, falling back to default config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
FATA[0000] could not get config                          error="invalid configuration: no configuration has been provided"
exit status 1
```

**Comment by yliaog** [comment]
did you specify --kubeconfig in the command line (or via env variable)? the above error message said (Neither --kubeconfig nor --master was specified. )

**Comment by alejandrox1** [comment]
@virendrasuryavanshi in the new version of your code, do you have something like this https://github.com/kubernetes/client-go/blob/a2cda5636dc9c8c961930bb6b7183d38b429a606/examples/out-of-cluster-client-configuration/main.go#L44-L50 ?

**Comment by virendrasuryavanshi** [comment]
Thanks, @alejandrox1, and @yliaog. The final changes after a suggestion by @alejandrox1 worked. [This](https://codeshare.io/2jQ7bP) is the final working code. Thank you for helping with this, really appreciate it.
