### ISSUE TITLE
[Failing Test] ci-kubernetes-build / ci-kubernetes-build-canary

### ISSUE THREAD

**Issue by thejoycekung** [kubernetes/kubernetes#96085]
**Which jobs are failing**:
`ci-kubernetes-build`
`ci-kubernetes-build-canary`

**Which test(s) are failing**:
`Overall`

**Since when has it been failing**:
Nov 1 7AM PST, since commit a0d23de08 ?

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#build-master
https://testgrid.k8s.io/sig-release-master-informing#build-master-canary

**Reason for failure**:
`make release` failed while building Go targets for `cmd/kubectl`
```
I1101 14:24:07.578] +++ [1101 14:24:07] Building go targets for {linux/amd64 linux/386 linux/arm linux/arm64 linux/s390x linux/ppc64le darwin/amd64 windows/amd64 windows/386} in parallel (output will appear in a burst when complete):
I1101 14:24:07.579]     cmd/kubectl
[ ... ]
I1101 14:26:49.666] # k8s.io/kubernetes/vendor/github.com/moby/term
I1101 14:26:49.667] vendor/github.com/moby/term/tc.go:13:28: undefined: unix.SYS_IOCTL
I1101 14:26:49.667] vendor/github.com/moby/term/tc.go:18:28: undefined: unix.SYS_IOCTL
I1101 14:26:49.668] vendor/github.com/moby/term/termios_bsd.go:24:31: undefined: unix.SYS_IOCTL
I1101 14:26:49.668] vendor/github.com/moby/term/termios_bsd.go:37:31: undefined: unix.SYS_IOCTL
I1101 14:26:49.668] !!! [1101 14:26:39] Call tree:
I1101 14:26:49.668] !!! [1101 14:26:39]  1: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:708 kube::golang::build_some_binaries(...)
I1101 14:26:49.668] !!! [1101 14:26:39]  2: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:843 kube::golang::build_binaries_for_platform(...)
I1101 14:26:49.669] !!! [1101 14:26:39]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
I1101 14:26:49.669] +++ [1101 14:24:07] windows/amd64: build started
I1101 14:26:49.669] +++ [1101 14:26:01] windows/amd64: build finished
I1101 14:26:49.669] +++ [1101 14:24:07] windows/386: build started
I1101 14:26:49.669] +++ [1101 14:26:49] windows/386: build finished
W1101 14:26:49.770] !!! [1101 14:26:49] Call tree:
W1101 14:26:49.770] !!! [1101 14:26:49]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
W1101 14:26:49.770] make[1]: *** [Makefile:93: all] Error 1
W1101 14:26:49.770] make: *** [Makefile:507: cross] Error 1
W1101 14:26:51.739] !!! [1101 14:26:51] Call tree:
W1101 14:26:51.742] !!! [1101 14:26:51]  1: build/../build/common.sh:526 kube::build::run_build_command_ex(...)
W1101 14:26:51.745] !!! [1101 14:26:51]  2: build/release.sh:36 kube::build::run_build_command(...)
W1101 14:26:51.745] make: *** [Makefile:407: release] Error 1
W1101 14:26:51.747] Traceback (most recent call last):
W1101 14:26:51.747]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_build.py", line 167, in <module>
W1101 14:26:51.747]     main(ARGS)
W1101 14:26:51.747]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_build.py", line 138, in main
W1101 14:26:51.747]     check('make', 'release')
W1101 14:26:51.748]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_build.py", line 32, in check
W1101 14:26:51.748]     subprocess.check_call(cmd)
W1101 14:26:51.748]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W1101 14:26:51.748]     raise CalledProcessError(retcode, cmd)
W1101 14:26:51.748] subprocess.CalledProcessError: Command '('make', 'release')' returned non-zero exit status 2
```

**Anything else we need to know**:
_Probably_ related to #96076, which updated a bunch of Go stuff

Spyglass link: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-build/1322900327501926400
Spyglass link (canary): https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-build-canary/1322906871559884800

/priority critical-urgent
/sig api-machinery
/cc @kubernetes/ci-signal

**Comment by aojea** [comment]
ping @liggitt

**Comment by aojea** [comment]
seems a docker issue trying to build on darwin
https://github.com/ory/dockertest/issues/212#issuecomment-685162574

**Comment by aojea** [comment]
/assign
I have a Pr to fix, testing it now

**Comment by liggitt** [comment]
Very strange… at first glance, that implies:
* the sys update breaks compatibility
* the pull-kubernetes-typecheck job does not accurately check Darwin compile compatibility

**Comment by aojea** [comment]
> Very strange… at first glance, that implies:
> 
> * the sys update breaks compatibility (which is unexpected)
> * the pull-kubernetes-typecheck job does not accurately check Darwin compile compatibility (which is unexpected)

I' ve sent a PR with the details, basically sys dropped support for direct syscalls in https://github.com/golang/sys/commit/6fcdbc0bbc04dcd9e7dc145879ceaf9bf1c6ff03 , and docker was using it. Fortunately all the docker ecosystem was already fixed

**Comment by liggitt** [comment]
Reverting in https://github.com/kubernetes/kubernetes/pull/96108 until the dependency fixes are resolved

**Comment by liggitt** [comment]
> * the pull-kubernetes-typecheck job does not accurately check Darwin compile compatibility (which is unexpected)

that's especially concerning to me since it means we don't have good presubmit coverage that master can even build on all supported platforms

**Comment by aojea** [comment]
/unassign

This PR https://github.com/kubernetes/kubernetes/pull/96100 is working on update the docker dependencies, we need to get the docker fixes so it is safe to update golang/x/sys without breaking darwin

**Comment by thejoycekung** [comment]
closing this because it's no longer happening
