### ISSUE TITLE
wsl wsl2 kubernetes kind windows 10  /usr/local/bin/kind: 1: Not: not found 

### ISSUE THREAD

**Issue by ngmariusz** [kubernetes/kubernetes#96086]
in
https://kubernetes.io/blog/2020/05/21/wsl-docker-kubernetes-on-the-windows-desktop/ 

there is
``` 
curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-$(uname)-amd64
```
which evaluates to 

```
curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-Linux-amd64 
```

but there is no such file and it is erroring quietly

what actualy works: 

```
curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-linux-amd64 
```

**Comment by BenTheElder** [comment]
Please follow our updated installation guides 
https://kind.sigs.k8s.io/docs/user/quick-start/#installation
https://github.com/kubernetes-sigs/kind/#installation-and-usage

The repo for kubernetes.io site is github.com/kubernetes/website. I'm not sure if blogposts accept updates like this.

**Comment by BenTheElder** [comment]
/assign
https://github.com/kubernetes/website/pull/24855

**Comment by BenTheElder** [comment]
This was fixed
/close
