### ISSUE TITLE
Compatibility LXD and Kubernetes

### ISSUE THREAD

**Issue by srkunze** [kubernetes/kubernetes#96081]
Hi folks, I am playing around with Kubernetes again. This time, I wanted to box Kubernetes up into its own linux container to keep things clean on the host machines.

During preflight checking, the following error/warning popped up: `unable to load kernel module "configs"`

Solution in this case was:

https://github.com/corneliusweig/kubernetes-lxd

> In case you obtain an error like failed to parse kernel config in the preflight check, copy your host kernel config to from /boot to your lxc-guest /boot

Thus, this work-around:
```
lxc file push /boot/config-5.4.0-52-generic kube-lxc/boot/config-5.4.0-52-generic
```
I reached out to LXD to see what is the issue here and it seems to be expected behavior:

https://github.com/lxc/lxd/issues/8107#issuecomment-720022855

> This file ships with the kernel packages, containers don't run kernels and therefore do not have the package installed.
So this is really expected behavior.

I wanted to make you aware of this.

Maybe there is something that can be done from Kubernetes side to address that problem.

**Comment by BenTheElder** [comment]
you can skip/ ignore the kubeadm preflight check
you can also run kubernetes in a container upstream with https://sigs.k8s.io/kind

**Comment by neolit123** [comment]
> unable to load kernel module "configs"

this comes from git.k8s.io/system-validators.

> This file ships with the kernel packages, containers don't run kernels and therefore do not have the package installed.
So this is really expected behavior

agreed, your container must include the kernel configuration if you want to use kubeadm inside.

/sig cluster-lifecycle
/close

**Comment by srkunze** [comment]
> you can skip/ ignore the kubeadm preflight check

Well, that is not really the point of this issue isn't it?

> you can also run kubernetes in a container upstream with https://sigs.k8s.io/kind

Thanks for pointing out this alternative.

**Comment by srkunze** [comment]
> > This file ships with the kernel packages, containers don't run kernels and therefore do not have the package installed.
So this is really expected behavior

> agreed, your container must include the kernel configuration if you want to use kubeadm inside.

Not sure why that kernel configuration is needed but I have two packages here being incompatible with each other because - let me quote @stgraber :

> Whatever software thinks it needs this is likely flawed in some way. A workaround like the one you used will only work until the next update of the host kernel.

Even though the work-around is not really robust against host kernel updates it seems to me that it is the only solution if both maintainers don't even want to discuss other approaches.

**Comment by neolit123** [comment]
> but I have two packages here being incompatible with each other

i recall discussions that the kubelet doesn't really support LXD, but i don't know what is the current state.

>> Whatever software thinks it needs this is likely flawed in some way. A workaround like the one you used will only work until the next update of the host kernel.

i would agree only for a case where an application is specifically designed to run inside a container. kubeadm manages a kubelet which does depend on kernel enabled features, so if they are run in an isolated environment some entity needs to expose the host kernel configuration inside the container.

> Not sure why that kernel configuration is needed

kubeadm runs validation on the kernel configuration on a "node", trying to understand what features are present and warn the user if critical ones required by k8s are missing:
https://github.com/kubernetes/system-validators/blob/master/validators/kernel_validator.go

the validation loads the config from these paths:
https://github.com/kubernetes/system-validators/blob/7c469b5590acac91b9771d9e24b4c66222a0540d/validators/kernel_validator.go#L181-L189
which are inside the "node".

spec:
https://github.com/kubernetes/system-validators/blob/7c469b5590acac91b9771d9e24b4c66222a0540d/validators/types_unix.go#L33-L59

this validation existed for a long time and without it users can log tickets which are difficult for the maintainers to decipher.

>> you can also run kubernetes in a container upstream with https://sigs.k8s.io/kind
> Thanks for pointing out this alternative.

i would also recommend kind for your use case.

**Comment by BenTheElder** [comment]
> Well, that is not really the point of this issue isn't it

Preflight checks are advisory, to help catch running on broken environments (as explained in more detail above by neolit123). *kubernetes* (core components) doesn't check this. Kubeadm does, but kubeadm exposes the ability to ignore or skip this check.
I don't think the check can reasonably function without access to these files.

In KIND we skip this check currently.

Also, Kubernetes is not intended to run inside a container for serious usage.

**Comment by srkunze** [comment]
> kubelet doesn't really support LXD

I think that is a message I can live with.

**Comment by neolit123** [comment]
don't take my word for it.

> i recall discussions that the kubelet doesn't really support LXD, but i don't know what is the current state.

**Comment by srkunze** [comment]
No issue for me. As @BenTheElder mentioned LXC is a container for systemd the helps me to keep my host system clean when trying quickly out different projects and/or setups before running them in the wild using costly resources.
