### ISSUE TITLE
Static policy (CPU Management Policies) just pin 1 cpu on Guaranteed QoS for Pod

### ISSUE THREAD

**Issue by thanhlong9x** [kubernetes/kubernetes#96091]
**What happened:**
I'm using guaranteed Qos with static policy to pin cpu into my pod. Althought I check right number cpu-pin on container at file /var/lib/kubelet/cpu_manager_state, my app is only run 1 cpu when run my pod.  
**What you expected to happen:**
I expect that my pod use all cpu-pinned as request resource in my deployment file.
**How to reproduce it (as minimally and precisely as possible):**
- Config static mode in file /var/lib/kubelet/config.yaml.
- Restart kubelet.service
- Deployment:

![image](https://user-images.githubusercontent.com/29721257/98060939-6dfd6380-1e7d-11eb-8ff0-788feeb04c03.png)

- Check cpu pin to container at /var/lib/kubelet/cpu_manager_state

![image](https://user-images.githubusercontent.com/29721257/98064819-d05a6200-1e85-11eb-84f9-4251cfe17723.png)

and check process running:

![image](https://user-images.githubusercontent.com/29721257/98064945-013a9700-1e86-11eb-8e16-a60251d499c6.png)

but, my pod just run on 1 cpu:
 
![image](https://user-images.githubusercontent.com/29721257/98064991-1f07fc00-1e86-11eb-8214-96cf94197474.png)

And my app just consume about 100% cpu. And hence performance of app is decrease. 
When taskset cpu for my app on baremetal, it run about 150% cpu. 

**Environment:**
- Kubernetes version (use kubectl version): v1.17.0
- Cloud provider or hardware configuration: bare metal
- OS (e.g: cat /etc/os-release): Redhat 7.8
- Kernel (e.g. uname -a): 3.10.
- Install tools: kubeadm
- Network plugin and version: Multus CNI, whereabouts, sriov

**Comment by frbimo** [comment]
can you elaborate more? how many resources you assigned. Can you post output `kubectl describe <pod_name>`

**Comment by thanhlong9x** [comment]
@frbimo I try with 2 or 4 cpu on pod but only 1 cpu run. On server, My app run with 150% cpu. This is my pod config:

![image](https://user-images.githubusercontent.com/29721257/97844029-dd0f7680-1d1c-11eb-8d2c-638a062aea6a.png)

**Comment by neolit123** [comment]
> Hi, I'm using guaranteed Qos with static policy to pin cpu into my pod. Althought I check right number cpu-pin on container at file /var/lib/kubelet/cpu_manager_state, my app is only run 1 cpu when run my pod. How can I use more cpu on all cpu-pinned ?

please fill the template properly and provide k8s versions and detailed reproductions steps.

a member of SIG Node should have a look if they see your ticket.
