### ISSUE TITLE
Unable to remove or add Owner References for pods via kubectl commands patch / edit.

### ISSUE THREAD

**Issue by kaushiksrinivas** [kubernetes/kubernetes#96107]
We are trying to remove or add the owner references set on a pod via kubectl commands.
But unable to succeed in the same.

But able to do the same on the pvc, but not on the pods.
Is this the expected behavior ?

**Comment by pacoxu** [comment]
`[root@dce-10-7-177-8 ~]# kubectl get pod  spring-46phs-deployment-5dd8d6646-8xsz5 -o yaml | grep  ownerRe -C 2
  name: spring-46phs-deployment-5dd8d6646-8xsz5
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
[root@dce-10-7-177-8 ~]# kubectl patch pod  spring-46phs-deployment-5dd8d6646-8xsz5  -p '{"metadata": {"ownerReferences":[]}}'
pod/spring-46phs-deployment-5dd8d6646-8xsz5 patched (no change)`

Would you share the command?  It works in my env, but the ownerReferences is not changed.

**Comment by kaushiksrinivas** [comment]
Yes, i tried to remove the owner references. It says no change.
And if u do get the pod -o yaml after patching, owner references would still exist.

**Comment by roycaihw** [comment]
> -p '{"metadata": {"ownerReferences":[]}}'

@pacoxu please use `"ownerReferences":null` to delete the list. I tried `kubectl edit` and it did the same. 

xref: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md

```
$ kubectl get configmaps child -oyaml
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2020-11-05T21:46:08Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          .: {}
          k:{"uid":"c42241df-f401-481e-b345-1f02bea5a351"}:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
    manager: main
    operation: Update
    time: "2020-11-05T21:46:08Z"
  name: child
  namespace: default
  ownerReferences:
  - apiVersion: v1
    kind: ConfigMap
    name: owner
    uid: c42241df-f401-481e-b345-1f02bea5a351
  resourceVersion: "505"
  uid: 9c10d76e-44f3-4bd8-a2aa-d531e39aefdc

$ kubectl patch configmaps child -p '{"metadata": {"ownerReferences":null}}'
configmap/child patched

$ kubectl get configmaps child -oyaml
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2020-11-05T21:46:08Z"
  name: child
  namespace: default
  resourceVersion: "509"
  uid: 9c10d76e-44f3-4bd8-a2aa-d531e39aefdc
```

/close

**Comment by pacoxu** [comment]
![image](https://user-images.githubusercontent.com/2010320/98316630-bc456a80-2015-11eb-9d7f-6b63a3e0fa8d.png)
 
@roycaihw  patched but owner reference is still not removed

**Comment by pacoxu** [comment]
kubectl delete replicaset.apps/nginx-f89759699 --cascade=false

The command above with ' --cascade=false' will delete rs without removing the pods. This may be a user case why someone what to remove the owner reference of a pod.


```
xupaco@Paco-deMacBook-Pro ~ % kubectl get all
NAME                        READY   STATUS    RESTARTS   AGE
pod/nginx-f89759699-nhbsv   1/1     Running   0          16s
pod/nodejs                  1/1     Running   8          83d

NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   84d

NAME                              DESIRED   CURRENT   READY   AGE
replicaset.apps/nginx-f89759699   1         1         1       16s
xupaco@Paco-deMacBook-Pro ~ % kubectl delete replicaset.apps/nginx-f89759699 --cascade=false
replicaset.apps "nginx-f89759699" deleted
xupaco@Paco-deMacBook-Pro ~ % kubectl get all
NAME                        READY   STATUS    RESTARTS   AGE
pod/nginx-f89759699-nhbsv   1/1     Running   0          2m7s
pod/nodejs                  1/1     Running   8          83d

NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   84d
```

**Comment by roycaihw** [comment]
Thanks @pacoxu. https://github.com/kubernetes/kubernetes/issues/96107#issuecomment-722757805 was unexpected. I will take a look

**Comment by BrianHuf** [comment]
Since this pages comes to top of my Google search.  This works for me

```
kubectl patch pod test-85469b5798-d8lkz -p '{"metadata": {"ownerReferences":null, "labels": {"pod-template-hash":null}}}'
```
