### ISSUE TITLE
Drop deprecated beta workload APIs in client-go

### ISSUE THREAD

**Issue by pigletfly** [kubernetes/kubernetes#96104]
**What would you like to be added**:

As deprecated beta workload APIs  are dropped serving since 1.16, should we drop support in client-go ?

xref: https://github.com/kubernetes/kubernetes/pull/70672

**Why is this needed**:

**Comment by victor-timofei** [comment]
Hello, I would like to help out with this. Would this be a good issue for a new contributor?

**Comment by fedebongio** [comment]
We just triaged this one. 
Short answers: yes, we should remove it. Can be a good issue to try out yes. Adding Sig apps to see what their thoughts are.
/sig apps

**Comment by liggitt** [comment]
to be clear, this is proposing removing support from client-go only, not from k8s.io/api and k8s.io/kubernetes? until we have a GA and required storage migration story, we still need the type definitions / defaults / conversions in place to be able to read and convert not-yet-migrated deprecated versions out of etcd

**Comment by pigletfly** [comment]
> to be clear, this is proposing removing support from client-go only, not from k8s.io/api and k8s.io/kubernetes? until we have a GA and required storage migration story, we still need the type definitions / defaults / conversions in place to be able to read and convert not-yet-migrated deprecated versions out of etcd

yeah, client-go only

**Comment by liggitt** [comment]
I don't object in principle. Would like input from @sttts or @deads2k

**Comment by sttts** [comment]
I expect that there might be a number of projects that support (much) older and newer cluster versions, using the same new'ish client-go. Has anybody done a review of publicly available projects on github?

**Comment by soltysh** [comment]
FYI, those API groups (apps/v1beta1 & apps/v1beta2) are not served for quite some time and since 1.18 (https://github.com/kubernetes/kubernetes/pull/85903) you can't even enable them back.

**Comment by pigletfly** [comment]
So can make a consensus that they should be removed in client-go ?

**Comment by liggitt** [comment]
> Has anybody done a review of publicly available projects on github?

That seems like a good thing to do, as well as ask on the developer mailing list and discuss forum.

**Comment by victor-timofei** [comment]
@sttts how would you suggest to proceed with reviewing the public projects on GitHub? Would it be enough to use the GitHub search?

**Comment by alculquicondor** [comment]
> FYI, those API groups (apps/v1beta1 & apps/v1beta2) are not served for quite some time and since 1.18 (#85903) you can't even enable them back.

Given this, why can't we remove the APIs from k8s.io/api? Or start the deprecation process

**Comment by liggitt** [comment]
because a client built from master can still be talking with older servers, and because the API server itself still requires those definitions to exist (along with the internal conversions) in order to decode data that is still persisted in etcd in those versions and convert it to apps/v1
