### ISSUE TITLE
Fork /usr/bin/nice : can not allocate memory

### ISSUE THREAD

**Issue by saurabhtmba2005** [kubernetes/kubernetes#96106]
Hi,

I am facing lots of issue due to fork error coming on my k8s nodes intermittently. Some memory is there but showing the same error. daily basis one server needs to reboot due to this error.

Please help me out on this as this is urgent and facing issue on my prod cluster

**Environment**: Production
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:18:16Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:10:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: Bare metal 250 GB ram and 32 Cpu intel 64 and 2 TB ssd drives on each node.
- OS (e.g: `cat /etc/os-release`): Centos 7.8
- Kernel (e.g. `uname -a`): Linux  3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: containerd github.com/containerd/containerd v1.3.2 ff48f57fc83a8c44cf4ad5d672424a98ba37ded6
- Network plugin and version (if this is a network-related bug): CNI flannel plugin v0.8.4
- Others: Etcd 3.4.1

**Comment by pacoxu** [comment]
have you checked the pid_max ？

You may refer to https://access.redhat.com/solutions/22105

**Comment by saurabhtmba2005** [comment]
Hi,

In My case that is not the  issue actually but i have verify the config once again and it is more then this.

# uname -a
Linux kube1.yatra.com 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
# ulimit
unlimited
[root@kube1 ~]# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 1030675
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1048576
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited


As i m getting given below errors which is i think related to kmemalloc with runc. "Can not allocate memory"

memory on each node: 252 GB
Node count: 40

While getting these error i have checked some how the used memory status some time only around 60 to 70 %.

Errors Some time:
failed command 'du' ($ nice -n 19 du -x -s -B 1) on path /var/log/pods/default_activitiessupplierscheduler-6bf6874bcd-78fpz_5c558623-6a54-45fe-8aca-0b0f92a0a224/ with error fork/exec /usr/bin/nice: cannot allocate memory

or
some time: 
Could not set up iptables canary mangle/KUBE-KUBELET-CANARY: error creating chain "KUBE-KUBELET-CANARY": fork/exec /usr/sbin/iptables: cannot allocate memory:

Some time: 

OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "process_linux.go:93: starting setns process caused \"fork/exec /proc/self/exe: cannot allocate memory\"": unknown

Please help me to dig out this as i have more then 9 TB memory in my cluster and only 50% we have used till now.
