### ISSUE TITLE
Failed to install the new version of the component health check

### ISSUE THREAD

**Issue by FreeManNumOne** [kubernetes/kubernetes#96101]
logs info 
api-server logs 
I1102 11:40:28.342662       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://127.0.0.1:2379  <nil> 0 <nil>}] <nil> <nil>}
I1102 11:40:28.342670       1 clientconn.go:948] ClientConn switching balancer to "pick_first"

kubectl  get cs 
Warning: v1 ComponentStatus is deprecated in v1.19+
NAME                 STATUS      MESSAGE                                                                                       ERROR
controller-manager   Unhealthy   Get "http://127.0.0.1:10252/healthz": dial tcp 127.0.0.1:10252: connect: connection refused   
scheduler            Unhealthy   Get "http://127.0.0.1:10251/healthz": dial tcp 127.0.0.1:10251: connect: connection refused   
etcd-0               Healthy     {"health":"true"}

**Comment by knight42** [comment]
How did you deploy your cluster? Were controller-manager and scheduler already running?

**Comment by neolit123** [comment]
but component status is deprecated and should not be used.

if you are using kubeadm the HTTP ports are disabled for the KCM and scheduler.
instead of passing --port=0 to them you should remove this flag, which will make the component status API work again.


/close
/kind support
