### ISSUE TITLE
Service name cannot start with a leading number

### ISSUE THREAD

**Issue by simonvane** [kubernetes/kubernetes#96147]
For reasons a won't go into, I want to create a service with either:
- A GUID as the name e.g. **2a2bf003-4054-4fb9-9521-887090e797c8** => **2a2bf003-4054-4fb9-9521-887090e797c8-apiserver**
- A customer's domain name e.g. **1stclass.co.uk** => **1stclass-co-uk-apiserver**

The problem is that both of these can have a leading number. When that is the case, I get the following error when the service name is validated:
`a DNS-1035 label must consist of lower case alphanumeric characters or ''-'', start with an alphabetic character, and end with an alphanumeric character (e.g. ''my-name'',  or ''abc-123'', regex used for validation is ''[a-z]([-a-z0-9]*[a-z0-9])?'')`

Could the DNS 1123 spec, which allows a leading number, be used to validate the service name?

(If I were able to get past the issue of the service name there may be other objects that also have this restriction that may cause me problems)

Thanks.

**Additional details**
Kubernetes version: 1.18.8

Full error: Service "1a96fdd8-bb46-46d1-8bff-6b708a09343c-apiserver" is
            invalid: metadata.name: Invalid value: "1a96fdd8-bb46-46d1-8bff-6b708a09343c-apiserver":
            a DNS-1035 label must consist of lower case alphanumeric characters or
            ''-'', start with an alphabetic character, and end with an alphanumeric
            character (e.g. ''my-name'',  or ''abc-123'', regex used for validation
            is ''[a-z]([-a-z0-9]*[a-z0-9])?'')

/sig api-machinery

**Comment by neolit123** [comment]
/remove-kind bug
/kind feature

> Could the DNS 1123 spec, which allows a leading number, be used to validate the service name?

/sig api-machinery
https://github.com/kubernetes/kubernetes/blob/6675eba3eff1c8e565c4060a9c1396f75da7cc3e/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go

**Comment by fedebongio** [comment]
/sig network
some discussion during triage, it feels we can't change this right now, may break some clients.

**Comment by aojea** [comment]
This is a recurring topic https://github.com/kubernetes/kubernetes/search?p=2&q=dns-1123+OR+dns-1035&type=issues

Some answes that apply from Jordan and Tim https://github.com/kubernetes/kubernetes/issues/71140#issuecomment-441703265

**Comment by fedebongio** [comment]
Thank you @aojea for pointing out.

Closing as per the quoted discussion on relevant threads on the same topic.

/close
/triage accepted
