### ISSUE TITLE
Move away from go-bindata/go-bindata

### ISSUE THREAD

**Issue by LorbusChris** [kubernetes/kubernetes#96169]
**What would you like to be added**:
I would like to propose the removal of the fork of go-bindata used in kubernetes: go-bindata/go-bindata

**Why is this needed**:
The currently vendored fork of go-bindata (https://github.com/go-bindata/go-bindata) is not actively maintained (as e.g. seen in https://github.com/go-bindata/go-bindata/pull/66).

## Alternative 1: Switch to a maintained fork
@kevinburke's fork (https://github.com/kevinburke/go-bindata) is actively maintained and is the one that is registered with Homebrew (https://formulae.brew.sh/formula/go-bindata)

## Alternative 2: Use Go 1.16's built-in `embed` package
Use native Go 1.16 capability for embedding files (https://tip.golang.org/pkg/embed/)

**Comment by dims** [comment]
Sigh! we gotta do this once more :(

**Comment by boddumanohar** [comment]
@dims this looks like a simple task. I would like to take this up.

**Comment by dims** [comment]
@boddumanohar go for it!

**Comment by dims** [comment]
May be we should wait until go 1.16 comes out and use the new capability in there?

**Comment by LorbusChris** [comment]
Sounds fine to me. I'll rename/repurpose this issue.

**Comment by boddumanohar** [comment]
go 1.16 is out. Will try to get this working with the new capability.

**Comment by warmchang** [comment]
/remove-lifecycle rotten

FYI: https://github.com/kubernetes/kubernetes/pull/99829

**Comment by palnabarun** [comment]
We have gone with alternative 2 in #99829.

/assign
/triage accepted
/close
