### ISSUE TITLE
System tests related to NodePort are continuously failing 

### ISSUE THREAD

**Issue by YuraHrunyk** [kubernetes/kubernetes#96166]
**What happened**: System tests related to NodePort service creation failed:

[sig-network] Services [It] should be able to create a functioning NodePort service [Conformance]

[sig-network] Services [It] should be able to change the type from ExternalName to NodePort [Conformance]

**What you expected to happen**: System tests related to NodePort service creation pass

**How to reproduce it (as minimally and precisely as possible)**: Run system tests

**Anything else we need to know?**: These both tests only fail on one node from the whole cluster and pass on other nodes. Even after re-creating the cluster, I'm seeing the same issue. All the nodes are similar, they are created by the same AutoScaling group.

These tests are failing with **service is not reachable within 2m0s timeout on endpoint** error.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.12
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): 
  NAME="CentOS Linux"
  VERSION="7 (Core)"
- Kernel (e.g. `uname -a`): 3.10.0-1127.18.2.el7.x86_64 #1 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug): Calico - v3.14.1
- Others:

**Comment by caseydavenport** [comment]
@YuraHrunyk how did you create this cluster? 

It looks like the sig-network testgrid has both of those tests as green.

Could you also please share the error message returned from the test? i.e., which assertion is failing?
