### ISSUE TITLE
Make nodeaffinity parsing functions return field.Error

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#96167]
The `k8s.io/component-helpers/scheduling/corev1/nodeaffinity` constructors return a parsed version of the input types. While doing that, they detect parsing errors that can be aggregated in higher level validators, such as `ValidateNodeAffinityArgs`.

For a proper implementation, all the returned errors should be of the type field.Error.

/sig scheduling

**Comment by lingsamuel** [comment]
These constructors raise errors mainly from `labels.Requirement`, which is a quite generic function. It's hard to change a `fmt.Errorf` to `field.Error`.
I noticed `ValidateNodeSelectorRequirement` in `pkg/apis/core/validation/validation.go` has similar logic compare with `labels.NewRequirement`, so write new validate functions instead change this constructor maybe a better choice?

**Comment by alculquicondor** [comment]
/remove-good-first-issue

This is actually not trivial :(

**Comment by alculquicondor** [comment]
> so write new validate functions instead change this constructor maybe a better choice?

No, the whole point is to avoid code duplication. We can change all the functions that are called to return field.Error or an aggregation of them. But we have to keep the same function signatures.

**Comment by lingsamuel** [comment]
Then I guess this will be a big refactoring task, not just sig/scheduling.

**Comment by alculquicondor** [comment]
It's not too big, but indeed beyond scheduling OWNERship

/sig api-machinery

**Comment by lingsamuel** [comment]
I am handling other funcs in `pkg/scheduler/apis/config/validation/validation_pluginargs.go`
