### ISSUE TITLE
api resourceVersion ignores limit

### ISSUE THREAD

**Issue by grosser** [kubernetes/kubernetes#96182]
```
kubectl get --raw '/api/v1/nodes?limit=1&resourceVersion=0' | jq '.items | length'
-> 55
```

I'd expect it to return 1 or fail with 400.

kubernetes v1.19.3

/sig api-machinery

**Comment by liggitt** [comment]
limit is optional for the server to honor. with resourceVersion=0, the response is served from the in-memory cache for efficiency, which does not support the limit parameter
