### ISSUE TITLE
Misleading "Pending" status is returned when pod fails with "Error: ErrImagePull"

### ISSUE THREAD

**Issue by adombeck** [kubernetes/kubernetes#96187]
Quoting #66828, which describes the issue well, but was closed after inactivity.

If a pod fails to pull a docker image, the pod status seems to inconsistent:

    $ kubectl get pods
    NAME READY STATUS RESTARTS AGE
    my_pod_1 0/1 ErrImagePull 0 59m
    my_pod_2 0/1 ImagePullBackOff 0 39m

    $ kubectl get pod my_pod_1 -o jsonpath={.status.phase}
    Pending

    $ kubectl get pod my_pod_2 -o jsonpath={.status.phase}
    Pending

I expected the status of the pod to be set to `Failed` when an ImagePullBackoff error occurs.

**Comment by troy0820** [comment]
You created the same issue in #96186.
/close

**Comment by dombeck** [comment]
> You created the same issue in #96186.
 
Oh, sorry, I got an error message when I first submitted the issue, so I assumed that it wasn't created.

**Comment by yashvardhan-kukreja** [comment]
I would like to pick this up

**Comment by yashvardhan-kukreja** [comment]
@troy0820 can I start working on this?
