### ISSUE TITLE
Unreachable node no longer gets Unreachable taint with NoExecute effect

### ISSUE THREAD

**Issue by mrajashree** [kubernetes/kubernetes#96183]
**What happened**:
1. Created a k8s 1.19.3 cluster.
2. Powered off one node.
3. The node got the following taint: `node.kubernetes.io/unreachable:NoSchedule`

**What you expected to happen**:
Along with the unreachable taint with NoSchedule effect, it should also get the taint with NoExecute effect (`node.kubernetes.io/unreachable:NoExecute`). Those are the two taints a powered off/unreachable node got till k8s 1.18.10

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a k8s 1.19.3 cluster.
2. Power off any node.
It reproduces every time (not intermittent)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.3
- Cloud provider or hardware configuration: Digital Ocean 
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04

**Comment by mrajashree** [comment]
I see this is the only change in that area since 1.18 https://github.com/kubernetes/kubernetes/pull/89059
could be related?

**Comment by wawa0210** [comment]
/assign 

I can try to fix

**Comment by yastij** [comment]
related to https://github.com/kubernetes/kubernetes/pull/94274

**Comment by yastij** [comment]
let's close this as a dupe of https://github.com/kubernetes/kubernetes/issues/94183

/close

**Comment by mrajashree** [comment]
@yastij it's not a dupe, the version on which that user reported the bug actually works for me

**Comment by mrajashree** [comment]
@yastij it's not a dupe, the version on which that user reported the bug actually works for me

/reopen

**Comment by rkojedzinszky** [comment]
To confirm, I am experiencing the same. I had some nodes powered off, I expected that some pods managed by deployments will get rescheduled on other nodes. Nothing happened. The nodes just got one node.kubernetes.io/unreachable:NoSchedule taint.

**Comment by adampl** [comment]
Isn't it fixed by https://github.com/kubernetes/kubernetes/pull/96876 and related cherrypicks?

**Comment by wzshiming** [comment]
This bug appears to have been addressed now that #96876 has merged.

/close
