### ISSUE TITLE
tokencleaner controller is not deleting expired bootstrap token secrets objects

### ISSUE THREAD

**Issue by bjhaid** [kubernetes/kubernetes#96191]
**What happened**:

The tokencleaner controller does not clean up bootstrap token secrets after
they expire after it has been started.

The tokencleaner controller is expected to clean up bootstrap tokens secret
objects that are
stale(https://kubernetes.io/docs/reference/access-authn-authz/bootstrap-tokens/#enabling-bootstrap-token-authentication):

> Expired tokens can be deleted automatically by enabling the tokencleaner controller on the controller manager.

it has however been observed to only clean up bootstrap tokens on startup and
not periodically.

From reviewing the controller code it was observed that the controller is
setup with a resync period set to 0 as seen in the below code paths:

- https://github.com/kubernetes/kubernetes/blob/ac996a37f65a8f11640808a883e9522832ed364f/cmd/kube-controller-manager/app/bootstrap.go#L45
- https://github.com/kubernetes/kubernetes/blob/ac996a37f65a8f11640808a883e9522832ed364f/pkg/controller/bootstrap/tokencleaner.go#L54-L58

The
[`SecretResync`](https://github.com/kubernetes/kubernetes/blob/ac996a37f65a8f11640808a883e9522832ed364f/pkg/controller/bootstrap/tokencleaner.go#L47-L49)
is not set hence its zero value of `0` is used, the underlying sharedInformer
skips
[resyncing](https://github.com/kubernetes/kubernetes/blob/ac996a37f65a8f11640808a883e9522832ed364f/staging/src/k8s.io/client-go/tools/cache/shared_informer.go#L789-L800)
when the resyncPeriod is `0` this leads to the tokencleaner controller
ignoring all bootstrap tokens after its initial seeding by the sharedInformer
and introduces bloat in the `kube-system` namespace, in some observed cases of
over 3000 bootstrap tokens. When an encryption provider is used, listing
secrets in any namespace with over a thousand secret objects becomes expensive
causing a drain on tools that rely on listing secret objects in such
namespace.

**What you expected to happen**:

The tokencontroller deletes expired bootstrap tokens at some time after their expiry as
described by the documenation:

> Expired tokens can be deleted automatically by enabling the tokencleaner controller on the controller manager.

**How to reproduce it (as minimally and precisely as possible)**:

Create a bootstrap token secret in the kube-system namespace and wait for a few days, the
token will be there unless the tokencleaner controller was restarted.

**Comment by liggitt** [comment]
Commented at https://github.com/kubernetes/kubernetes/pull/96192#issuecomment-721416319, resync is not the way this controller revisits tokens when their expiration is up. If the ttl requeue is not working, that is what should be fixed

**Comment by bjhaid** [comment]
This is not an issue in 1.19, I'll close for now if any of the supported releases have this issue, then I might figure out what fixed it and maybe hunt for a backport if it is reasonable.
