### ISSUE TITLE
a central place to list out all deprecated API

### ISSUE THREAD

**Issue by gaorong** [kubernetes/kubernetes#96209]
For now, we just announce the API to be deprecated in the release note, mixed with other notes and not clear.   Maybe we need a central place to list out all deprecated API, make the description clear and well-formated, such as below:

|           api                             |  not served at   |  migrate to | 
|-------------------------------------------|------------------|-------------|
| apps/v1beta1                              |      v1.16       |  apps/v1    |
| apps/v1beta2                              |      v1.16       |  apps/v1    |
| extensions/v1beta1/daemonsets             |      v1.16       |  apps/v1    |
| extensions/v1beta1/deployments            |      v1.16       |  apps/v1    |
| extensions/v1beta1/replicasets            |      v1.16       |  apps/v1    |
| extensions/v1beta1/networkpolicies        |      v1.16       |networking.k8s.io/v1  | 
| extensions/v1beta1/podsecuritypolicies    |      v1.16       |policy/v1beta1        |
| scheduling.k8s.io/v1beta1/PriorityClass   |  v1.17       |   scheduling.k8s.io/v1 | 
| scheduling.k8s.io/v1alpha1/PriorityClass  |  v1.17       |   scheduling.k8s.io/v1 | 
| apiextensions.k8s.io/v1beta1/CustomResourceDefinition                     |  v1.19  | apiextensions.k8s.io/v1          |      
| admissionregistration.k8s.io/v1beta1/MutatingWebhookConfiguration         |  v1.19  | admissionregistration.k8s.io/v1  |
| admissionregistration.k8s.io/v1beta1/ValidatingWebhookConfiguration       |  v1.19  | admissionregistration.k8s.io/v1  |
| authorization.k8s.io/v1alpha1/rbac                                        |   v1.20   |   rbac.authorization.k8s.io/v1 |
| authorization.k8s.io/v1beta1/rbac                                         |   v1.20   |   rbac.authorization.k8s.io/v1 |
| extensions/v1beta1/ingress(class)                |  v1.22       |   networking.k8s.io/v1 |
| networking.k8s.io/v1beta1/*               |  v1.22       |    networking.k8s.io/v1 | 

In v1.16's ChangeLog, we have a note as below:
> PriorityClass resources will no longer be served from scheduling.k8s.io/v1beta1 and scheduling.k8s.io/v1alpha1 in v1.17. Migrate to the scheduling.k8s.io/v1 API, available since v1.14. Existing persisted data can be retrieved via the scheduling.k8s.io/v1 API.

the ` scheduling.k8s.io/v1alpha1` will be deprecated in v1.17, but in v1.17's ChangeLog, I can not find any note about this. does this API remove silently?  the note seems not to be consistent across the release.

**Comment by pacoxu** [comment]
Similar with https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-graduated-or-deprecated-features.

We may have a page to list all apiversions for core api groups and the deprecated versions history

**Comment by fedebongio** [comment]
This sounds like a topic for api reviewers, not api-machinery
@kubernetes/api-reviewers 
/remove-sig api-machinery

**Comment by liggitt** [comment]
probably better tracked in https://github.com/kubernetes/website/issues/18675 or https://github.com/kubernetes/website/issues/20617

**Comment by saschagrunert** [comment]
I agree this does not seem to be SIG Release related, because we only maintain release notes and not the API documentation. I will therefore remove the sig/release label. I think SIG docs could support us with this kind of enhancement, right?

/sig docs

**Comment by pacoxu** [comment]
> we have one here https://kubernetes.io/docs/reference/using-api/deprecation-guide/ thanks to liggitt 's PR [kubernetes/website#26483](https://github.com/kubernetes/website/pull/26483)

The official doc is here.

And there are several opensource tools that may help

- https://github.com/FairwindsOps/pluto
- https://github.com/doitintl/kube-no-trouble
- https://kaniuse.vercel.app/kind/Deployment
