### ISSUE TITLE
Image access control is not multi-tenant.

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#9620]
Docker does a credential check when pulling images, but not when using them. It will let you run an image that is already pulled even if you don't present credentials.

That is reasonable behavior from the standpoint of the docker tool since it is not trying to be multi-user.

However, it makes it hard to make Kubernetes multi-user. If an image is already pulled, (e.g. using `imagePullSecrets`, then anyone else can use that image by setting pull policy to `IfNotPresent`, even if they lack proper credentials.

 We could try to fix this by disallowing `IfNotPresent` pull policy on all pods, thus forcing a docker pull before each docker run, and failing the pod if the docker pull failed.  We would need to implement and e2e test that.

**Comment by erictune** [comment]
@ncdc @deads2k tell me if I stated this right.  And what does openshift do?

**Comment by deads2k** [comment]
One possibility we considered was attempting to perform an image pull no matter what the pull policy was.  If we got a 401/403, then reject the pod.  If we started to get back layers, then either allow the pull or cancel it and use the existing image.  The biggest problem with the approach was what to do in the case of non-401/403 rejection.  If the Docker registry is down and your policy is `IfNotPresent`, then it is surprising to be unable to use the image for your pod.

Currently, OpenShift operates the same way as kube.  We would be able to do some additional checks with our SubjectAcccessReview API for images originating from our Docker registry, but we don't perform any of them today.

**Comment by ncdc** [comment]
A better solution would be to use the v2 registry client from docker/distribution to attempt to retrieve the image manifest. This would be much faster than trying to do a pull, but it obviously only works with v2 registries. But it would still have the same problem David describes, where if the image was previously pulled successfully, but the registry is down, you won't be able to use the image.

**Comment by erictune** [comment]
This sounds workable.

Aren't you running the registry in the same node as the apiserver and scheduler for openshift?  So, if any of those are down, they are all down, and you can't start new pods.  What I'm saying is it doesn't seem like a big loss in availability.

The other concern is bootstrapping; need to be able to restart file-based pods without registry started.  I think that can be addressed by exempting file-based pods from the pull check.

**Comment by ncdc** [comment]
The registry runs as 1 or more pods via a replication controller.

**Comment by redbaron** [comment]
Any ideas since 2015? :)

**Comment by redbaron** [comment]
Here is one: kubelet should mark images as they belong to serviceaccount. Then apply policy to marked images only. If no marked image found locally it is always "Always".

Probably there are more sophisticated ways to mark it like sign it with SA key, but as an example lets just mark it with re-tagging to show proposed flow.

Lets say pod with default/default SA pulls "alpine:3.7",  kubelet is doing following:
 - uses "alpine:3.7-default-default" image  name as if POD specified exactly that, it then applies imagePullPolicy to this image name
 - if kubelet decides to pull image, it then pulls real image and then retags it to 'alpine:3.7-default-default' and continues with pod startup using retagged name for the rest of the process

This way multi tenancy can be achieved without causing inconvenience to `IfNotPresent` PODs when registry is not available.

**Comment by liggitt** [comment]
duplicate of https://github.com/kubernetes/kubernetes/issues/18787

/close
