### ISSUE TITLE
kubelet: could not retrieve port mappings: checkpoint is corrupted

### ISSUE THREAD

**Issue by chymy** [kubernetes/kubernetes#96203]
**What happened**:
After upgrading from 1.10 to 1.13.6, when deleting the StatefulSet pod, kubelet reports error stack:
```shell
E1021 11:03:36.422212   33091 cni.go:334] Error deleting network when building cni runtime conf: could not retrieve port mappings: checkpoint is corrupted
E1021 11:03:36.766605   33091 remote_runtime.go:119] StopPodSandbox "fe39e8e1cb973e551493e1d54fcab16d6c349bfa0aee1835e681e8430fbd934a" from runtime service failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod "7eef2f47-07a7-4350-8e17-5db8d91d4e6f-haredis-1_opcs" network: could not retrieve port mappings: checkpoint is corrupted
E1021 11:03:36.766646   33091 kuberuntime_manager.go:851] Failed to stop sandbox {"docker" "fe39e8e1cb973e551493e1d54fcab16d6c349bfa0aee1835e681e8430fbd934a"}
E1021 11:03:36.766668   33091 kubelet_pods.go:1076] Failed killing the pod "7eef2f47-07a7-4350-8e17-5db8d91d4e6f-haredis-1": failed to "KillPodSandbox" for "066d35a0-7508-11ea-9af3-3cfdfeda0651" with KillPodSandboxError: "rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod \"7eef2f47-07a7-4350-8e17-5db8d91d4e6f-haredis-1_opcs\" network: could not retrieve port mappings: checkpoint is corrupted"

```

**What you expected to happen**:
remove corrupt checkpoints immediately upon detection

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by andrewsykim** [comment]
> After upgrading from 1.10 to 1.13.6,

Upgrading 3 minor versions is not supported.

**Comment by chymy** [comment]
The upgrade was successful, but it took 10-20 minutes to delete the old pod and create a new one
