### ISSUE TITLE
Pod gets stuck in ContainerCreating state if first attempt of CNI ADD fails (Multus CNI, Whereabouts IPAM)

### ISSUE THREAD

**Issue by TothFerenc** [kubernetes/kubernetes#96200]
**What happened**:
We are using Multus CNI for having multiple network interfaces inside Pod network namespace. Whereabouts IPAM is being used to serve unique IPs within an IP Pool.
In case the IP Pool is fully allocated, if we delete a Pod (under Deployment), a new Pod is started. The deleted Pod is still in Terminating state for a while holding its IP addresses. At this specific point in time the new Pod fails to start, because Multus CNI calls Whereabouts IPAM to request an IP, but it throws an error due to depleted IP Pool. That is expected.
The problem is that the new Pod gets stuck in ContainerCreating state forever. In the meantime the IP address of the old Pod is released, so the next attempt of CNI ADD would pass, but it seems K8s does not retry that.

**What you expected to happen**:
We expect that in case of such failures K8s retries the failing CNI ADD operation to be able to start the Pod. It should not be stuck in a state which requires manual intervention. 

**How to reproduce it (as minimally and precisely as possible)**:
Multus NetworkAttachmentDefinition:
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: whereabouts-nad2
 namespace: whereabouts
spec:
 config: '{
  "cniVersion": "0.3.1",
  "type": "ipvlan",
  "master": "eno6",
  "mode": "l2",
  "ipam": {
   "type": "whereabouts",
   "range": "10.10.10.0/24",
   "range_start": "10.10.10.100",
   "range_end": "10.10.10.128",
   "exclude": ["10.10.10.0/25"]
  }
 }'
```
As you can see the pool size is reduced to a single IP intentionally, so whereabouts can serve 10.10.10.128 only.

Deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
  run: multustest2
 name: multustest2
 namespace: whereabouts
spec:
 replicas: 1
 selector:
  matchLabels:
   run: multustest2
 template:
  metadata:
   namespace: whereabouts
   labels:
    run: multustest2
   annotations:
    k8s.v1.cni.cncf.io/networks: whereabouts-nad2
  spec:
   containers:
   - image: busybox:latest
     name: multustest2
     command: [ "/bin/sh", "-c", "while true; do date; sleep 10; done"]
     securityContext:
       runAsNonRoot: true
       runAsUser: 1000
```
Once they are applied, the Pod is running fine:
```
# kubectl get pods -n whereabouts -w
NAME                           READY   STATUS    RESTARTS   AGE
multustest2-594975985d-clp6z   1/1     Running   0          27s
```
Let's delete this Pod and see what happens:
```
# kubectl get pods -n whereabouts -w
NAME                           READY   STATUS    RESTARTS   AGE
multustest2-594975985d-clp6z   1/1     Running   0          27s
multustest2-594975985d-clp6z   1/1     Terminating   0          51s
multustest2-594975985d-fwpms   0/1     Pending       0          0s
multustest2-594975985d-fwpms   0/1     Pending       0          0s
multustest2-594975985d-fwpms   0/1     ContainerCreating   0          0s
multustest2-594975985d-clp6z   0/1     Terminating         0          86s
multustest2-594975985d-clp6z   0/1     Terminating         0          93s
multustest2-594975985d-clp6z   0/1     Terminating         0          93s
```
The new Pod (`multustest2-594975985d-fwpms`) gets stuck in ContainerCreating status.

Events part of Pod describe output:
```
Events:
  Type     Reason                  Age                    From                              Message
  ----     ------                  ----                   ----                              -------
  Normal   Scheduled               <unknown>              default-scheduler                 Successfully assigned whereabouts/multustest2-594975985d-fwpms to tb26-cscf261-workerbm-3
  Warning  FailedCreatePodSandBox  33m                    kubelet, tb26-cscf261-workerbm-3  Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "7a3efb8f68da62fb22a60271c183b6eb796ebd76225455d025273f25939a4da8" network for pod "multustest2-594975985d-fwpms": networkPlugin cni failed to set up pod "multustest2-594975985d-fwpms_whereabouts" network: Multus: [whereabouts/multustest2-594975985d-fwpms]: error adding container to network "whereabouts-nad2": delegateAdd: error invoking DelegateAdd - "ipvlan": error in getting result from AddNetwork: Error at storage engine: Could not allocate IP in range: ip: 10.10.10.100 / - 10.10.10.128 / range: net.IPNet{IP:net.IP{0xa, 0xa, 0xa, 0x0}, Mask:net.IPMask{0xff, 0xff, 0xff, 0x0}}, failed to clean up sandbox container "7a3efb8f68da62fb22a60271c183b6eb796ebd76225455d025273f25939a4da8" network for pod "multustest2-594975985d-fwpms": networkPlugin cni failed to teardown pod "multustest2-594975985d-fwpms_whereabouts" network: delegateDel: error invoking DelegateDel - "ipvlan": error in getting result from DelNetwork: Error deallocating IP: Did not find reserved IP for container 7a3efb8f68da62fb22a60271c183b6eb796ebd76225455d025273f25939a4da8]
  Normal   SandboxChanged          3m21s (x129 over 33m)  kubelet, tb26-cscf261-workerbm-3  Pod sandbox changed, it will be killed and re-created.
```

**Anything else we need to know?**:
Even if it is a special case, we don't think that Multus CNI or Whereabouts IPAM is guilty. It seems K8s is missing a retry mechanism when Pod is being created.
The new Pod can be started if we use low `terminationGracePeriodSeconds` time (<5 sec), because CNI DEL happens earlier than CNI ADD for the new Pod.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.8
- Cloud provider or hardware configuration: bare metal
- OS (e.g: `cat /etc/os-release`): CentOS 7
- Kernel (e.g. `uname -a`): 4.18
- Install tools: custom deployment method using ansible
- Network plugin and version (if this is a network-related bug): Multus CNI v3.4.1, whereabouts v0.1-04ed52b
- Others:

**Comment by shivakumargn** [comment]
Is this a whereabouts IPAM specific issue ? Since

**Comment by TothFerenc** [comment]
> 
> 
> Is this a whereabouts IPAM specific issue ?

No. For few seconds Whereabouts fails to provide an IP because the pool is depleted. But that circumstance gets resolved by Pod termination, which releases an IP.
The problem is that Kubernetes does not retry the CNI operation, if it fails for the first time.

**Comment by eth0xFEED** [comment]
hi @TothFerenc thanks for opening this issue , is this the ipam plugin you are using https://github.com/openshift/whereabouts-cni ?

Do you experience the same behavior when using the host-local ipam plugin ?

**Comment by TothFerenc** [comment]
> 
> 
> hi @TothFerenc thanks for opening this issue , is this the ipam plugin you are using https://github.com/openshift/whereabouts-cni ?
> 
> Do you experience the same behavior when using the host-local ipam plugin ?

Hi @eth0xFEED !
It seems Whereabouts CNI is being developed here: https://github.com/dougbtv/whereabouts/

In the meantime Whereabouts author made this potential fix: https://github.com/intel/multus-cni/issues/578 -> https://github.com/dougbtv/whereabouts/issues/70 which looks good based on initial test results.

Even if the Multus delegated CNI fails like this, why Kubernetes does not retry the last failing step and stuck in ContainerCreating state forever?

And answering to your question: no, I haven't tried any other IPAM (as we would like to use Whereabouts). If time permits, I will try to recreate it with other IPAMs...

**Comment by eth0xFEED** [comment]
I would expect kubelet to continue to reconcile until the desired state is reached, however i have seen times when the return code of the underlying CNI can cause deviation from this behavior. Looking at the comments here seems that this return code behavior is being updated https://github.com/dougbtv/whereabouts/issues/70#issuecomment-724573996 

Please let me know if we can resolve the issue as I believe the error lies in the cni/plugin side.

**Comment by jayunit100** [comment]
https://github.com/containernetworking/cni/blob/master/SPEC.md <-- looks like ADD can only be called once, so its a CNI bug?

**Comment by dcbw** [comment]
@jayunit100 ADD will be called once-per-sandbox. So it can certainly be called multiple times for the same pod, because there is a 1:N relationship between Pod:Sandbox.

@TothFerenc What I think the real problem may be is `error invoking DelegateDel - "ipvlan": error in getting result from DelNetwork: Error deallocating IP: Did not find reserved IP for container 7a3efb8f68da62fb22a60271c183b6eb796ebd76225455d025273f25939a4da8]`. That would indicate a problem in the (whereabouts?) plugin, because CNI Plugin delete is supposed to be permissive and clean up what it can. In this case, if the reserved IP is not found, the IPAM plugin should just ignore the problem.

The issue is that if a plugin continuously returns errors for CNI DEL, kubelet cannot clean up the container sandbox.

**Comment by dcbw** [comment]
@dougbtv

**Comment by TothFerenc** [comment]
@dcbw : Whereabouts IPAM is going to be fixed by @dougbtv. If there is nothing else to improve on Kubernetes side, then this issue can be closed. Thanks!

**Comment by GaneshVKadam** [comment]
Hello Dough,

We are facing the attached issue with multus network attachments , none of the multus PODS are comming up.
Below is the error from teh POD:

Warning  FailedCreatePodSandBox  14m (x11860 over 27h)  kubelet  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "4e5a8ac872e8f5ff13ef33ab71d4250959a3e8f4fb2e70c720ae27cede18e43c" network for pod "bcs01s1-prov-gls-684cc899bc-4b7j5": networkPlugin cni failed to set up pod "bcs01s1-prov-gls-684cc899bc-4b7j5_bcs01s1" network: [bcs01s1/bcs01s1-prov-gls-684cc899bc-4b7j5:n99prov]: error adding container to network "n99prov": Error at storage engine: Could not allocate IP in range: ip: 172.24.1.120 / - 172.24.1.123 / range: net.IPNet{IP:net.IP{0xac, 0x18, 0x0, 0x0}, Mask:net.IPMask{0xff, 0xff, 0xfe, 0x0}}

The NetAttach definition is attached.

Name:         n99prov
Namespace:    bcs01s1
Labels:       <none>
Annotations:  <none>
API Version:  k8s.cni.cncf.io/v1
Kind:         NetworkAttachmentDefinition
Metadata:
  Creation Timestamp:  2021-10-28T19:02:23Z
  Generation:          2
  Managed Fields:
    API Version:  k8s.cni.cncf.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2021-10-28T19:02:23Z
    API Version:  k8s.cni.cncf.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:config:
    Manager:         kubectl-edit
    Operation:       Update
    Time:            2021-10-29T23:40:18Z
  Resource Version:  161026868
  Self Link:         /apis/k8s.cni.cncf.io/v1/namespaces/bcs01s1/network-attachment-definitions/n99prov
  UID:               18e72b48-1122-47b4-94f6-0299efc28700
Spec:
  Config:  { "cniVersion":"0.3.1", "type":"ipvlan", "capabilities":{ "ips":true }, "master":"eth1", "ipam":{ "type":"whereabouts", "range": "172.24.0.0/23", "range_start": "172.24.1.120", "range_end": "172.24.1.123", "routes": [ { "dst": "172.24.0.0/23", "gw": "172.24.1.254" } ], "log_file" : "/tmp/whereabouts.log", "log_level" : "debug"} }
Events:    <none>

The detailed wher about logs detalls the belwo error
2021-10-29T23:40:48Z [error] Error deallocating IP: Did not find reserved IP for container 248a82d1a013fb4c9234b22ba100b6e93ee07aa5bcb32bb232f57f2cf9d2db1a

attacherd is teh wherabouts file with teh error
[Whereabouts.log](https://github.com/kubernetes/kubernetes/files/7445423/Whereabouts.log)


Kindly let me know which CNI version will it be corrected.

**Comment by AbeOwlu** [comment]
Hi @GaneshVKadam, your reported issue didn't get any info, it seems. 
Do you have an update on work around, please? Facing the same whatbout error. Thanks
