### ISSUE TITLE
StatefulSet PodManagementPolicy Parallel affects updates

### ISSUE THREAD

**Issue by behos** [kubernetes/kubernetes#96218]
**What happened**:

Hi,

I'm trying to understand whether a behaviour we are observing in stateful sets with `Parallel` `PodManagementPolicy` is expected or if we are hitting a bug.

From the docs:

> Parallel pod management tells the StatefulSet controller to launch or terminate all Pods in parallel, and to not wait for Pods to become Running and Ready or completely terminated prior to launching or terminating another Pod. This option only affects the behavior for scaling operations. Updates are not affected.

I'm trying to understand the last bit "Updates are not affected". Unless I am misunderstanding the intention here, we expect that during scale up and down pods will be created and terminated in parallel. However, for the pods which will not be removed or added, I expected this to work similarly to `OrderedReady`.

The behaviour we are seeing does not match this expectation however.

Starting with this state:

```
NAME       READY   STATUS    RESTARTS   AGE
my-sts-0   0/1     Running   0          32m
my-sts-1   1/1     Running   0          32m
my-sts-2   1/1     Running   0          33m
```

Running a rolling update ignores the unready pod `0` and results in:

```
NAME       READY   STATUS    RESTARTS   AGE
my-sts-0   0/1     Running   0          32m
my-sts-1   1/1     Running   0          32m
my-sts-2   0/1     Terminating   0          33m
```
 
Is this the intended behaviour? If so, what do the docs mean by "Updates are not affected"?

**What you expected to happen**:

Since pod `0` is unready I would expect the StatefulSet update to not proceed until both pod `0` and `1` are ready.

**How to reproduce it (as minimally and precisely as possible)**:

* Create a StatefulSet with `Parallel` pod management policy.
* Get pod `0` to an unready state.
* Trigger a rolling update for the statefulset.

**Anything else we need to know?**:

Diving in the code I came across this line: https://github.com/kubernetes/kubernetes/blob/792b4b1e32394a13c27741f71f14dd134d663a5f/pkg/controller/statefulset/stateful_set_control.go#L442

Which appears to be skipping waiting for pods to become ready for `Parallel` pod management policies regardless of whether the action which is about to take place is a scale up/down or an update.

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.3-dd1", GitCommit:"cca64583d7846303a3e9d3137e19e62a4be6bb58", GitTreeState:"clean", BuildDate:"2020-10-15T07:50:03Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by behos** [comment]
Hi, is there an update on this? Is it a bug or intended behaviour?

**Comment by chentaoz** [comment]
Hey, In my opinion,  "Updates are not affected" applies when all replicas are fully ready and running before rolling update. In your case, my-sts-0 is not ready, which is approximately same as the case a statefulset is still in middle of parall scaling, which will not prevent program from reaching  the point of rollupdate  https://github.com/kubernetes/kubernetes/blob/792b4b1e32394a13c27741f71f14dd134d663a5f/pkg/controller/statefulset/stateful_set_control.go#L519 can be reached.

**Comment by behos** [comment]
Hey 🙂 that code path can definitely be reached when the statefulset is in this state, but I think it should be prevented.

It's not quite the same as a parallel scale up even though it technically looks like one. For instance, it would be acceptable to add new pods while a pod is down, but terminating a second existing pod could violate disruption budgets and compromise quorums.

**Comment by behos** [comment]
I'm still unsure if this is intended behaviour or a bug which needs to be fixed

**Comment by ahilsend** [comment]
I just stumbled on this issue. I was looking into introducing parallel to some of our StatefulSets. But if updates behave as described in this issue, then it's a no go for us. Would be great if someone could confirm whether it's intended or a bug.

**Comment by alvinlin123** [comment]
I am hitting the same issue. 

We switched to Parallel pod management policy because of https://github.com/kubernetes/kubernetes/issues/78007, but we also have a requirement to restart only one pod at a time. 

I've tried to set the pod disruption budget's `maxUnavailable` to 0, but still got two pads being unavailable as describe in the issue.

**Comment by FillZpp** [comment]
@behos Now you can update pods parallelly using StatefulSet since maxUnavailable is supported https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#maximum-unavailable-pods

**Comment by FillZpp** [comment]
> edit: @FillZpp I went over the code and it looks that the value MaxUnavailable=1 fixes this issue. Should this be the default and only put overriding the value behind the feature flag?

It will be default when the `MaxUnavailableStatefulSet` featureGate become beta or GA.
cc @krmayankk

**Comment by behos** [comment]
> It will be default when the MaxUnavailableStatefulSet featureGate become beta or GA.

With this available, the issue no longer applies. Closing this

**Comment by pfrybar** [comment]
We really need this feature (or should I call it a bug fix?) - unfortunately we can't control the feature gates in our cluster (GKE) so we won't be able to use it until it becomes beta.

Does anyone know if there's a way to find out when this may happen, or to try and push for a feature to get promoted from alpha to beta?
