### ISSUE TITLE
[Failing Test] gce-ubuntu-master-default (ci-kubernetes-e2e-ubuntu-gce)

### ISSUE THREAD

**Issue by hkamel** [kubernetes/kubernetes#96222]
**Which jobs are failing**:
`ci-kubernetes-e2e-ubuntu-gce`

**Which test(s) are failing**:

- `Kubernetes e2e suite.[sig-network] Services should be possible to connect to a service via ExternalIP when the external IP is not assigned to a node`
- `Overall`
- `Test`

**Since when has it been failing**:
`11-04 19:33 PST `

**Testgrid link**:
`https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-ubuntu-master-default`

**Reason for failure**:
`/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1187
Nov  4 11:59:41.385: Unexpected error:
    <*errors.errorString | 0xc00298c3d0>: {
        s: "service is not reachable within 2m0s timeout on endpoint 203.0.113.250:80 over TCP protocol",
    }
    service is not reachable within 2m0s timeout on endpoint 203.0.113.250:80 over TCP protocol
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1210`

**Anything else we need to know**:
/priority important-soon
/sig network
/cc @kubernetes/ci-signal

**Comment by rikatz** [comment]
Apparently this is related to https://github.com/kubernetes/kubernetes/pull/96116

/cc @aojea

**Comment by rikatz** [comment]
@aojea if you're busy and want me to take a look tomorrow you can assign that to me and I can deep dive into what's missing/happening :) 

Happy to help and to understand better the flakiness life

**Comment by aojea** [comment]
so, the test adds a "fake" external IP that should be nated to the service endpoint
It went through the CI, more details in the issue I opened explaining the test
https://github.com/kubernetes/kubernetes/issues/95785

**Comment by aojea** [comment]
ok, this is interesting

the test is failing when using container runtime DOCKER
https://k8s-testgrid.appspot.com/google-gce#gce-ubuntu-master-default

https://github.com/kubernetes/test-infra/blob/fbee53880054ac5acfe992a58b4e35e81a19aa95/config/jobs/kubernetes/sig-cloud-provider/gcp/gcp-gce.yaml#L532

```
      - --env=KUBE_CONTAINER_RUNTIME=docker
```

the same periodic job that uses container runtime CONTAINERD (same as the PR) is working

https://k8s-testgrid.appspot.com/google-gce#gce-ubuntu-master-containerd&include-filter-by-regex=external

We need to understand what is different regarding the network in GCE jbos, when using docker as runtime, kubenet???

cc: @BenTheElder

**Comment by aojea** [comment]
one diff between the working jobs with containerd and the failing ones with docker is that the failing ones use this part of the code

```
I1104 19:55:00.295281   10740 kubenet_linux.go:710] Adding services-284/execpod7jbcv to 'kubenet' with CNI 'bridge' plugin and runtime: &{ContainerID:5de860c2de2597873fe576075668a4d53d6f8af996cd18b64ac9ae5fe760612f NetNS:/proc/47631/ns/net IfName:eth0 Args:[] CapabilityArgs:map[] CacheDir:/var/lib/cni/cache}
```

**Comment by aojea** [comment]
@aramase IIRC you are using kubenet for azure jobs, are you using docker as runtime, can you please check if this tests fails there too?

**Comment by aojea** [comment]
The problem happens on environment that are using the bridge plugin, seems I got wrong the feature
https://github.com/kubernetes/kubernetes/issues/95785#issuecomment-722255763 
will revert until we have the right test.

**Comment by aramase** [comment]
> @aramase IIRC you are using kubenet for azure jobs, are you using docker as runtime, can you please check if this tests fails there too?

@aojea We use kubenet only for IPv6 and dualstack jobs. Rest of the tests use Azure CNI. Default is docker runtime for all jobs.
