### ISSUE TITLE
Adding the host's trusted certificates or /etc/docker/certs.d/ to app container automatically

### ISSUE THREAD

**Issue by viju2008** [kubernetes/kubernetes#96232]
**What would you like to be added**:

**Why is this needed**:

Currently i have 50 pods and 20 services. I have to add a trusted CA certificate internal to all these pods.

However in the present scenario I will have to create a configmap and add it to all the Yaml file and redeploy them

If Kubernetes pods could directly pick from the  /etc/docker/certs.d/ as they containers will be spawned by docker ultimately  OR  from  nodes system trusted store  it would be easier to do the same .

A feature of applying the Trusted certificate to all pods in cluster or to a particular namespace  will be very helpful or it could pick from system or /etc/docker/certs.d/  . This will save a lot of redeployment and yaml changes

**Comment by neolit123** [comment]
this seems out of scope for core k8s, but deferring to these SIGs to provide feedback:
/sig node auth

**Comment by liggitt** [comment]
> this seems out of scope for core k8s, but deferring to these SIGs to provide feedback:

I agree. Knowledge of where/how trusted certificates should be mounted is very dependent on the containers you are running.

You can accomplish this yourself with an admission plugin injecting volume mounts (either from the node or from a configmap if the data is small enough) to the locations you want them.

/close
