### ISSUE TITLE
Clean up / remove suffixes from generated StorageClasses and VolumeSnapshotClasses in E2E tests

### ISSUE THREAD

**Issue by chrishenzie** [kubernetes/kubernetes#96234]
**What would you like to be added**:
Suffixes for generated `StorageClass` and `VolumeSnapshotClass` objects can be removed since they already have randomly generated names.
https://github.com/kubernetes/kubernetes/blob/396b90f06ca29c754a81eb6c03cff50b7d9bf265/test/e2e/storage/testsuites/driveroperations.go#L76

**Why is this needed**:
This is a small cleanup to remove an argument that isn't needed (it's hardcoded in callers) and / or repeats the name of the snapshotter in the suffix which can reduce readability:
https://github.com/kubernetes/kubernetes/blob/396b90f06ca29c754a81eb6c03cff50b7d9bf265/test/e2e/storage/drivers/csi.go#L163-L170

/sig storage

**Comment by lala123912** [comment]
Can I have a try to fix it?
