### ISSUE TITLE
APF metrics: use snake_case for metric labels instead of camelCase

### ISSUE THREAD

**Issue by adtac** [kubernetes/kubernetes#96233]
**What would you like to be added**: API priority and fairness metrics have labels such as "priorityLevel" and "flowSchema". These should be "priority_level" and "flow_schema" respectively. These metrics have been added to an exception list:

https://github.com/kubernetes/kubernetes/blob/396b90f06ca29c754a81eb6c03cff50b7d9bf265/staging/src/k8s.io/component-base/metrics/testutil/promlint.go#L36-L39

**Why is this needed**: snake_case is consistent with other metrics.

/sig api-machinery
/kind cleanup
/cc @MikeSpreitzer @ahg-g 

Do we want to do this before 1.20 beta?

**Comment by ahg-g** [comment]
yes, lets do that.

**Comment by MikeSpreitzer** [comment]
/triage accepted
Yes, we do not want to go to beta with known wrongness in the metrics.
