### ISSUE TITLE
[Flaky test] data race panic in k8s.io/apiserver/pkg/server/filters.TestApfExecuteMultipleRequests

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#96243]
**Which jobs are flaking**:

pull-kubernetes-bazel-test

**Which test(s) are flaking**:

`k8s.io/apiserver/pkg/server/filters`

**Testgrid link**:

* https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-bazel-test&include-filter-by-regex=k8s.io%2Fapiserver%2Fpkg%2Fserver%2Ffilters&width=5

**Reason for failure**:

```
WARNING: DATA RACE
Write at 0x00c0001c2d40 by goroutine 108:
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.TestApfExecuteMultipleRequests.func5()
      staging/src/k8s.io/apiserver/pkg/server/filters/priority-and-fairness_test.go:300 +0xf2
```

**Anything else we need to know**:
- This just started in the past few days:
  - https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=DATA%20RACE&test=k8s.io%2Fapiserver%2Fpkg%2Fserver%2Ffilters
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/96197/pull-kubernetes-bazel-test/1324157206030979072

/sig api-machinery
/priority critical-urgent

**Comment by yue9944882** [comment]
@liggitt it will be fixed by https://github.com/kubernetes/kubernetes/pull/96244

**Comment by eddiezane** [comment]
Both PR's landed and this appears fixed.

@kubernetes/ci-signal will continue to monitor on our board.

/close
