### ISSUE TITLE
HPA scheduling implementation doesn't scale well with custom/external metrics - all checks are sequential by one goroutine

### ISSUE THREAD

**Issue by scr-oath** [kubernetes/kubernetes#96242]
**What happened**:
I created an external metric that took roughly 100ms; then to see what happened if there were many of them, I created 1,000 HPAs using it.  Usually every HPA checks every 15s, but this resulted in each HPA check checking every 120 seconds - a drift/delay of over 100 seconds.

**What you expected to happen**:

- Each HPA with a custom/external metric should only drift by maximum 100ms every 15s or delay a second every 3-5 minutes
- Other HPAs not using custom/external metrics should not be impacted by duration of custom/external metrics
- The quantity of deployments with HPAs should not degrade each HPAs ability to respond to signals requiring scaling up (spikes e.g.)

**How to reproduce it (as minimally and precisely as possible)**:
* Create and install the https://github.com/kubernetes-sigs/custom-metrics-apiserver and alter its code to add a delay in the `GetExternalMetric` method of the [Testing Provider](https://github.com/kubernetes-sigs/custom-metrics-apiserver/blob/master/test-adapter/provider/provider.go#L327)
* Also add logging to the method with timestamps [logrus](https://github.com/Sirupsen/logrus) supports timestamps, e.g.
* Create 1,000 HPA objects referring to that test metric - possibly 1,000 deployments as well, but one will work fine too even if not a _real_ use case.
* Pick one of your HPA's and watch for the time between its call to `GetExternalMetric`.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Docker CE for Mac
- OS (e.g: `cat /etc/os-release`):
Mac OS Catalina 10.15.7 
- Kernel (e.g. `uname -a`):
Darwin <REMOVED> 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ITonyLi** [comment]
> * Other metrics not using custom/external metrics should not be impacted by duration of custom/external metrics

In my opinion, different scenarios need different options. Can a configurable option be added to realize the timeout degradation of extended indicators? Prevent excessive drift of indicators. @deads2k @luxas @mtaufen

**Comment by ITonyLi** [comment]
> > * Other metrics not using custom/external metrics should not be impacted by duration of custom/external metrics
> 
> In my opinion, different scenarios need different options. Can a configurable option be added to realize the timeout degradation of extended indicators? Prevent excessive drift of indicators. @deads2k @luxas @mtaufen

If the calculation time difference between indicators is large, there will be frequent adjustment of pod quantity in the next copy index calculation.

**Comment by scr-oath** [comment]
As I understand it, the current implementation just has a queue/chan, a timer of some sort, and a single goroutine to process the queue of work. There is a comment "[start a single worker (we may wish to start more in the future)](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal.go#L176)"

I would imagine that many scheduling implementations solve for requirements such as
- Scheduling is separate from running - this _may_ be solved by current implementation
- Run isolation (a run of one thing doesn't block/delay another from running)
- Wrap-around protection - don't start another run of a recurring task if it's still running the last one

I don't think that "timeout" is really the issue - what if you had some external metric like - what's the temperature on the moon - and it took 8 minutes to get an update (just contrived example)… That _should_ still be possible and not drag down all the other HPA checks in the system, right?

**Comment by arjunrn** [comment]
@scr-oath As I see it there are 2 issues here:
1. Time drift caused by sequential execution.
2. Independent evaluation of each metric source.

With regards to 1 I suppose increasing the worker count should alleviate the problem. Maybe even making it configurable for larger clusters like yours.
However 2 is not possible because the HPA always make a scaling proposal based on the highest value from each of the metric sources. Consider the situation where one of the metrics, which has currently the highest proposed value is down for a few seconds. The HPA would then ignore it and start scaling down the target. Subsequently when the metric source is available again the HPA controller would start scaling up the target. This could be too disruptive for many workloads.

**Comment by scr-oath** [comment]
I don't recall describing 2 in quite the same terms as you - I was saying more that each HPA should make its call outs independent from each other - sure you could also parallelize all of its metrics, but as you point out, would need to join/wait for them all to return; I'm more concerned with isolating the work of each HPA from each other, or at least as you've also suggested adding more workers to drain the queue faster rather than piling up.

**Comment by arjunrn** [comment]
> Other metrics not using custom/external metrics should not be impacted by duration of custom/external metrics

I guess you meant "Other HPAs not using custom/external metrics should not be impacted..."

**Comment by scr-oath** [comment]
ohhhh… thanks clarifying for the semantic typo - you got it! other HPAs

**Comment by lorenzo-biava** [comment]
Just faced the very same issue (and it took me a while to discover that the delay in scaling was caused by this - somehow I expected the HPA to work in parallel, and there are no debug logs to tell otherwise).

In our case we're using Keda to setup HPAs and provide external metrics, which in turn come from Prometheus. Unfortunately Prometheus got overloaded (see https://github.com/prometheus/prometheus/issues/8014) and started responding with >2s delay.
So with around 130 HPAs that creates a scale up delay of more than 4 minutes.
Of course we need to tune Prometheus on our side to get it back to reasonable performance, but it definitely should not have such a snowball effect on the scale up time of every HPA (15sec vs 260sec).

@itonyli / @arjunrn Can you consider actually implementing the multiple workers approach?

**Comment by scr-oath** [comment]
I tried a test of external metrics that only has a 100µs response time, added 1000 keda metrics, and saw only 25 fetched in an 8m period (I would have expected 4x8=32) so that's something like a 20% loss of metric gathering points over time.  When using that external metrics directly, I see about 3% loss (one drop in 8m), so clearly Keda doesn't completely workaround the HPA limitations; it would be really great if HPA, itself would do the right thing and not drift, skip, or penalize other metrics gathering for one HPA that has a slow one.

**Comment by bpinske** [comment]
I've unfortunately independently discovered this very same problem with external metrics scaling very poorly, particularly under Keda querying prometheus.

Is there any particular reason that the solution cannot be a naive increase to the number of goroutines spawned to process the HPA objects concurrently on every 15 second loop execution? There was an acknowledgement above that an HPA object may itself hold multiple metrics to be calculated: so at the very least we would need to ensure that for each metric is returned  an HPA remains serial, but each HPA object should be independent such that they can be concurrently processed. 

I'm shocked to see that the HPA loop is single threaded serially calculates each HPA in core Kubernetes.

**Comment by jjcaballero** [comment]
Does anyone know if this limitation affects the vanilla CPU/memory metrics? or this only has effect when checking custom metrics?

**Comment by pbetkier** [comment]
@jjcaballero if you only have HPAs with CPU/memory metrics the effect should be less visible. It's still serial, blocking calls to fetch the metrics, but the response times on these calls should be lower – the metrics-server component responds immediately with what it has in its cache as opposed to making a synchronous call to the custom metrics source (e.g. Prometheus).

**Comment by scr-oath** [comment]
That makes me think... it would be a really interesting feature if there could be a feature for async metrics. The idea being... 

What if things aware of metrics - whether scanners at some frequency or notified from events could update some status fields of the HPA (or otherwise update the HPA cache)?

Then there would be zero latency added to the system (beyond having more metrics to consider - but at least no I/O scale latency)

Would that be an easier pill to swallow than making the schedule run with more concurrency/parallelism?

**Comment by pbetkier** [comment]
> (...) it would be a really interesting feature if there could be a feature for async metrics (...) could update some status fields of the HPA (...)

Do you mean update with metric values directly or update with a flag saying "new metrics are available to read from metrics-server"?

I believe storing metric values would be prohibitively costly in large clusters, but theoretically we could store a map (config map?) of hpa name to new metric readiness. In this case this problem is IMO orthogonal to concurrent processing: async metrics would make the HPA run as soon as metrics are available to read (saving 7.5s on average, 15s worst case) while concurrent processing would help with scaling the calls to metrics-server.

WDYT @scr-oath? Would you be willing to pursue this idea further, see what would need to happen for this to work?

**Comment by scr-oath** [comment]
> Do you mean update with metric values directly or update with a flag saying "new metrics are available to read from metrics-server"?

I meant altering the HPA with the info... HPA already stores it's external fetch result in the status field doesn't it? So just having access to store that or something like it asynchronously would seem fine. Essentially, I'm suggesting that external metrics have a way of communicating updates - maybe write to a kevent like endpoint - so that when the HPA considers that object next, it can look at a field rather than doing more I/O that may be slow.  

One contrived example is, say you have a sensor on the moon - query would take roughly 5s over and back… but if it could send updates, you wouldn't care how much the delivery overhead/latency was.

> I believe storing metric values would be prohibitively costly in large clusters

See above - isn't the data stored with the HPA object anyway in status field for each external metric? (I don't know the answer for sure but I suspect it does)

**Comment by pbetkier** [comment]
> HPA already stores it's external fetch result in the status field doesn't it?

It stores an aggregate: the sum of all metric values. If your external metric has a single series (e.g. queue size) then it's the same as what we store in status, but you can define metrics having multiple series, e.g. reported for each application instance.

Also I thought you meant change the architecture to async for all metric types, not only external. This would allow us to recalculate HPA as soon as new metrics arrive, not having to wait 15s intervals. If we're speaking just external and not affecting reconciliation trigger then IMO parallel HPA is a better way to move forward: requires less change and helps with all metric types.

**Comment by lanshunfang** [comment]
This is painful. With my PSR testing, it needs 3-5 minutes to obtain the metrics (native and/or custom metrics) and scale out. Not sure why this obvious non-scalable flaw ticket was closed, and no further solutions were discussed.

I even saw someone offered a PR, but it was not merged https://github.com/kubernetes/kubernetes/pull/99688 

It's discussed and offered by this [Chinese guy](https://qingwave.github.io/k8s-hpa-enchance/)

**Comment by lanshunfang** [comment]
For you guys who are not aware, here is the new flag meant to solve this issue  https://github.com/kubernetes/kubernetes/pull/108501
`--concurrent-horizontal-pod-autoscaler-syncs `
