### ISSUE TITLE
k8s kubelet certificate rotation doesn't work | The currently active client certificate has expired, but the server is not responsive

### ISSUE THREAD

**Issue by Tcooop** [kubernetes/kubernetes#96256]
i follow the official document
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/#token-authentication-file
to set a certification auto rotation on my cluster

**What you expected to happen**:
all steps have follow and when i change my cluster node time , kubelet log is show below:
`
 restart may be necessary to retrieve new initial credentials.
Nov 11 00:15:46 10.233.0.100 kubelet[66610]: I1111 00:15:46.509278   66610 kubelet_node_status.go:450] Using node IP: "10.161.110.11"
Nov 11 00:15:53 10.233.0.100 kubelet[66610]: E1111 00:15:53.851634   66610 transport.go:113] The currently active client certificate has expired, but the server is not responsive. A restart may be necessary to retrieve new initial credentials.
Nov 11 00:15:56 10.233.0.100 kubelet[66610]: I1111 00:15:56.524732   66610 kubelet_node_status.go:450] Using node IP: "10.161.110.11"
Nov 11 00:16:03 10.233.0.100 kubelet[66610]: E1111 00:16:03.851909   66610 transport.go:113] The currently active client certificate has expired, but the server is not responsive. A restart may be necessary to retrieve new initial credentials.
Nov 11 00:16:06 10.233.0.100 kubelet[66610]: I1111 00:16:06.542159   66610 kubelet_node_status.go:450] Using node IP: "10.161.110.11"
Nov 11 00:16:13 10.233.0.100 kubelet[66610]: E1111 00:16:13.852201   66610 transport.go:113] The currently active client certificate has expired, but the server is not responsive. A restart may be necessary to retrieve new initial credentials.
Nov 11 00:16:16 10.233.0.100 kubelet[66610]: I1111 00:16:16.559484   66610 kubelet_node_status.go:450] Using node IP: "10.161.110.11"
Nov 11 00:16:23 10.233.0.100 kubelet[66610]: E1111 00:16:23.852449   66610 transport.go:113] The currently active client certificate has expired, but the server is not responsive. A restart may be necessary to retrieve new initial credentials.
Nov 11 00:16:26 10.233.0.100 kubelet[66610]: I1111 00:16:26.575728   66610 kubelet_node_status.go:450] Using node IP: "10.161.110.11"
Nov 11 00:16:33 10.233.0.100 kubelet[66610]: E1111 00:16:33.852715   66610 transport.go:113] The currently active client certificate has expired, but the server is not responsive. A restart may be necessary to retrieve new initial credentials.
`
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):Centos7.3
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
hi, this appears to be a request for support. please use the support channels instead:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

thanks
/close
/kind support
/remove-kind bug
