### ISSUE TITLE
kube-apiserver will leak cacheWatcher  when time jump to the future and jump back

### ISSUE THREAD

**Issue by chenyw1990** [kubernetes/kubernetes#96259]
**What happened**:

kube-apiserver will leak cacheWatcher when time jump to the future and jump back。

In telecom application scenarios, We expect kubernetes to work properly when time changes.

It is found that when the time of the node where kube-apiserver resides changes to the future for several minutes and change back, memory leak occurs on kube-apiserver.

before time change
![image](https://user-images.githubusercontent.com/1468240/98235618-05a5a380-1f9d-11eb-8615-5feb1a47ac2e.png)

change time to future then change back, wait 1 hour
![image](https://user-images.githubusercontent.com/1468240/98235628-08a09400-1f9d-11eb-9c4e-7e053ed8efdc.png)

**What you expected to happen**:

kubernetes to work properly when time changes, no memroy leak

**How to reproduce it (as minimally and precisely as possible)**:

1. change the time of the node where kube-apiserver resides to the future (for example, one day),
2. wait several minutes 
3. change time back

**Anything else we need to know?**:
I confirmed the code in v1.19 and the problem exists.

**Environment**:
- Kubernetes version (use `kubectl version`):1.15.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): EulerOS 2.0
- Kernel (e.g. `uname -a`): Linux 4.19.36
- Install tools: 
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by chenyw1990** [comment]
/assign @chenyw1990 
I will fix it

**Comment by wojtek-t** [comment]
@chenyw1990 - so are you saying that the time can go forth and back without the components (in this case kube-apiserver) being even restarted? Can you briefly describe how that happens?

**Comment by wojtek-t** [comment]
> change the time of the node where kube-apiserver resides to the future (for example, one day),

Can it really change by one day? If you repro-ed it by changing by one day, the memory will free-up after that one day actually...

**Comment by chenyw1990** [comment]
We simulate the scenario of NTP server failure, In the scenario of NTP server failure, the time may jump to the future. When we repair the NTP server, the time will be corrected.
When the time jumps to the future and then jumps back, cacheWatcher will be cached in watchersBuckets and will not be recycled by gc. memory will leak. In large-scale clusters, memory leaks are fast, and kube-apiserver will oom after a few hours

**Comment by wojtek-t** [comment]
That's not entirely true - they will be GC-ed once we reach the previous time. So unless it won't jump by hours, but rather minutes/seconds, you won't leak the memory.
How much it can change? I would like to avoid non-trivial logic if it's not absolutely needed.

**Comment by chenyw1990** [comment]
@wojtek-t 

we test in 2000 nodes cluster，When the cluster runs stably，before cacheWatcher leak，the memory used by kube-apiserver is 14 GB.
![image](https://user-images.githubusercontent.com/1468240/98537738-ae694100-22c4-11eb-91da-5ef0ed7e30fc.png)

when cacheWatcher leak， the memory usage increases to 43.85 GB after 4.5 hours, and about 6.6 GB memory is leaked every hour.
![aftermemoryleak](https://user-images.githubusercontent.com/1468240/98538182-5717a080-22c5-11eb-8226-b06934915305.png)

If some applications are being installed, or nodes are being joined in batches，memory leaks faster

so, if the time changes by hour, the memory leakage problem is serious.

**Comment by lala123912** [comment]
mark

**Comment by wojtek-t** [comment]
The fix was merged at head.

I also opened cherrypicks - they are waiting for approval.
https://github.com/kubernetes/kubernetes/pull/96601
https://github.com/kubernetes/kubernetes/pull/96602
https://github.com/kubernetes/kubernetes/pull/96603

Closing since there is nothing else left to do here.
