### ISSUE TITLE
kubectl debug setting images without specifying container name returns error

### ISSUE THREAD

**Issue by verb** [kubernetes/kubernetes#96261]
**What happened**: 

Using `kubectl debug --set-image` without specifying `--image` should modify existing container images without trying to create a new one. Instead it tries to create a new container and returns an error that `--image` isn't set:

```
% kubectl debug myapp --copy-to=myapp-debug --set-image=*=ubuntu
Defaulting debug container name to debugger-mfzpc.
error: you must specify image when creating new container
```

**What you expected to happen**:

This command should change all container images to `ubuntu` instead of returning an error.

/sig cli
/kind bug
/priority important-soon

**Comment by allenjol** [comment]
My kubernetes cluster version is 1.19.0,and i use kubectl-debug version 0.1.1 try to debug my pod,bug i got error:
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/28972707/164878418-a0052d4d-68d0-47cf-8171-e41fba7643f4.png">
Who one know about that？
