### ISSUE TITLE
make allow_privileged configurable at cluster startup time (providers using salt)

### ISSUE THREAD

**Issue by pwais** [kubernetes/kubernetes#9626]
For providers that use salt, currently the way to enable privileged containers is to check out k8s from source, manually edit a salt config, build tarballs (which is very slow, even just `make quick-release`), and start.  I propose introducing an env var so that this property can be toggled at cluster startup time on a k8s binary release.  

I have a draft of said changed here (see top portion, this branch includes some unrelated changes):
 * https://github.com/GoogleCloudPlatform/kubernetes/compare/master...pwais:pwais_run_proxy_on_master_and_make_priv_nicer_0.18.1

Does this sound like a good idea?  If so, I'd be happy to put together a pull request based on my draft if that helps.

**Comment by bgrant0607** [comment]
Seems reasonable.

Eventually we should replace this flag with an admission control policy. cc @csrwng 

cc @thockin @evandbrown

**Comment by pwais** [comment]
FWIW I have ported the old branch to a new branch based upon master (~v1.0 at the time of porting) and verified the change still works in GCE.  Here is the new branch/diff: https://github.com/GoogleCloudPlatform/kubernetes/compare/master...pwais:pwais_run_proxy_on_master_and_make_priv_nicer_1.0_master

**Comment by bgrant0607** [comment]
We enabled privileged containers by default for 1.0.

I don't think we should do something custom for this one option. We should fix the way we configure our components.

**Comment by thockin** [comment]
Actuallym we didn't in the end we didn't get to hammer it out enough before
Dawn had to take off.  :(

**Comment by thockin** [comment]
I agree with the "we should do a general fix", but I think we should leave this open until we can close it with an "obsoleted by"

**Comment by bgrant0607** [comment]
Ok, sorry. I thought that change went in. :-(

**Comment by pwais** [comment]
Agree that this branch is a bit of an ugly hack-- it's the minimal work to propagate the flag to the bash provider (~configuration) scripts while keeping with how other salt parameters work.  Mainly trying to create a paper trail here since I spent a lot of time looking for prior work on this issue and found none.  Yes, please do cite this issue when the nicer fix hits a release! <3

**Comment by zmerlynn** [comment]
#11027 was the attempt right before v1.0, FWIW. But #11027 would be a breaking behavioral change now for upgrades, so I think we'd need to be a little bit more careful to distinguish new clusters versus existing clusters.

**Comment by thockin** [comment]
Yeah, there's some trailblazing to be done here.  Good point Zach.

**Comment by bgrant0607** [comment]
Privileged is enabled by default. Control over that is superseded by PodSecurityPolicy.
