### ISSUE TITLE
allow options when creating volumes with nfs

### ISSUE THREAD

**Issue by rdxmb** [kubernetes/kubernetes#96284]
**What would you like to be added**:

Within NFS volumes defined in pods, I miss a key to add mount options like

```
volumes:
  - name: external-nfs-share
    nfs:
      server: "10.1.2.3"
      path: "/share"
      mountOptions: "nfsvers=3,sync" # or
      # options: "nfsvers=3,sync" 
```

like there is a key `mountOptions:` in https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistent-volumes 

**Why is this needed**:

Actually, when mounting external NFS-Data within a pod, the NFS-client of the kubernetes-worker seems to define the NFS-version for the mount. 

In my case, after a release-upgrade of my kubernetes-worker from xenial to bionic, my pod cannot be started anymore - because the NFS denied the NFSv4-mount.

Trying myself with cli on the host:

works:
`mount -t nfs -o nfsvers=3`

does not work:
`mount -t nfs -o nfsvers=4`

For the NFS-Server has a problem with NFSv4 here - and this cannot be changed :facepalm: 

Here is the output of another `describe pod`.

```
Events:
  Type     Reason       Age                     From     Message
  ----     ------       ----                    ----     -------
  Warning  FailedMount  2m15s (x297 over 7h5m)  kubelet  (combined from similar events): MountVolume.SetUp failed for volume "mypod" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/6517a1ad-868d-4b27-ba54-63c4c738b2e6/volumes/kubernetes.io~nfs/mypod --scope -- mount -t nfs 192.168.73.10:/backup/backups/applications /var/lib/kubelet/pods/6517a1ad-868d-4b27-ba54-63c4c738b2e6/volumes/kubernetes.io~nfs/mypod
Output: Running scope as unit: run-ree2c6faf0d774e99b8581fa9058b5e52.scope
mount.nfs: mount system call failed
```

**Comment by marklester** [comment]
I also need to this to specify the nfs version

**Comment by matinjugou** [comment]
According to (design proposal)[https://stupefied-goodall-e282f7.netlify.app/contributors/design-proposals/storage/mount-options/#preventing-users-from-specifying-mount-options-in-inline-volume-specs-of-pod]
> After much deliberation it was decided that - mountOptions as an API parameter will not be supported for inline volume specs

However, this feature is quite essential for our performance tuning. We want a vote to enable this feature.

**Comment by matinjugou** [comment]
@rdxmb You can try this as a temporary solution: Change mount options globally by modifying configuration file nfsmount.conf -- (reference)[https://manpages.debian.org/unstable/nfs-common/nfsmount.conf.5.en.html]
Kubernetes uses system-run or exec.Command to execute mount behavior. So global configuration may do help.

**Comment by rdxmb** [comment]
@matinjugou Thank you very much for this idea. I will see if this is an option - as I actually have multiple NFS-exports with different versions ...

**Comment by matinjugou** [comment]
If you do solve it, I hope you can share with us. ^ _ ^


| |
黄超
|
|
***@***.***
|
签名由网易邮箱大师定制


On 05/26/2021 14:07，Marc ***@***.***> wrote：

@matinjugou Thank you very much for this idea. I will see if this is an option - as I actually have multiple NFS-exports with different versions ...

**Comment by rdxmb** [comment]
As this is a global configuration, this is actually not a solution for me. 

As a workaround, I've created dedicated PVs and PVCs for that NFS-exports. If I changed the nfsmount.conf to NFS version 3, I'd have to create PVs and PVCs to change my other mounts manually to version 4.

**Comment by matinjugou** [comment]
In other words, if your pods use same version nfs-protocol, it will work, right?


| |
黄超
|
|
***@***.***
|
签名由网易邮箱大师定制


On 05/26/2021 15:51，Marc ***@***.***> wrote：

As this is a global configuration, this is actually not a solution for me.

As a workaround, I've created dedicated PVs and PVCs for that NFS-exports. If I changed the nfsmount.conf to NFS version 3, I'd have to create PVs and PVCs to change my other mounts manually to version 4.

**Comment by rdxmb** [comment]
I think this would be a solution then. I've not tried it.

**Comment by matinjugou** [comment]
It's quite confusing why can't we specify the mount options of inline volume.

**Comment by rdxmb** [comment]
hey community,

as commented in https://github.com/kubernetes/kubernetes/issues/96284#issuecomment-848414212 this does not seem as it will be fixed at any time. So we close this?

**Comment by colearendt** [comment]
Does that design proposal live elsewhere? I haven't seen it and the link appears to be dead. It would be nice if there were a way to illustrate that this demand exists, and it seems to me that this issue being open does that 😅 But I also know little about how the formalities around the kubernetes project work.

**Comment by colearendt** [comment]
Happy November! Tis a great month for NFS volume mount parameters!

**Comment by gnufied** [comment]
When mount options were implemented for persistent volumes, we made a conscious decision to not support mount options for inline volumes, because a bad user can use the mount option to crash a kernel or create other problems. 

I don't think if we are ever going to allow mount options for inline volumes in pods, unless we change security model and may be allow only for a subset of pods. Users who want mount options are recommended to use PVs.  The details of the discussion are captured in original mount option proposal - https://github.com/kubernetes/community/pull/321

**Comment by xing-yang** [comment]
Discussed at SIG Storage issue triage meeting and decided we should not support this feature.

/close

**Comment by onedr0p** [comment]
@xing-yang it would be pretty beneficial to summarize what was mentioned as I'm sure a lot of people were not included in that meeting.

**Comment by gnufied** [comment]
All kubernetes sig-storage meetings are public and recorded. Anyone can subscribe to sig-storage calendar and join the meetings. Having said that - it was agreed that allowing inline mount options in pods will be unsafe for general use case. Most of the past discussion is captured in https://github.com/kubernetes/community/pull/321 

The only additional info is - allowing it only in certain kind of pods such as privileged will also run into problems, because now at API level we will have to find a way to reject  pods that use inline mount options.  Given all these issues, we decided it isn't currently feasible to implement this feature.

**Comment by onedr0p** [comment]
I'm not sure why it wasn't mentioned by the maintainers commenting on this issue but you can get around this partly by putting a nfs config file on the host OS as described here: https://kubernetes.io/docs/concepts/storage/volumes/#nfs

> Also note that you can't specify NFS mount options in a Pod spec. You can either set mount options server-side or use [/etc/nfsmount.conf](https://man7.org/linux/man-pages/man5/nfsmount.conf.5.html). You can also mount NFS volumes via PersistentVolumes which do allow you to set mount options.
