### ISSUE TITLE
Allow for multiple crontab expressions in a single CronJob

### ISSUE THREAD

**Issue by atzawada** [kubernetes/kubernetes#96283]
I would like to see the kubernetes cronjob template allow for accepting multiple crontab expressions in an array, so that the same job definition can be used on multiple schedules. This would promote reuse of code by preventing the need to create multiple cronjob definitions for the same action solely based on schedule. I have several cronjobs that run on multiple different schedules even though they execute the same action, and I would prefer to define them once rather than separately.

Related to #82659

**Comment by lukasz-mitka** [comment]
@atzawada Could you reopen this issue. It's still relevant.
