### ISSUE TITLE
[Failing Test] [sig-node] SetHostnameAsFQDN tests are failing (ci-kubernetes-node-kubelet-features)

### ISSUE THREAD

**Issue by thejoycekung** [kubernetes/kubernetes#96288]
**Which jobs are failing**:
`node-kubelet-features-master` / `ci-kubernetes-node-kubelet-features`

**Which test(s) are failing**:

- `Hostname of Pod [Feature:SetHostnameAsFQDN][NodeFeature:SetHostnameAsFQDN] a pod with subdomain field has FQDN, hostname is shortname [cos-stable1, cos-stable2, ubuntu]`
- `Hostname of Pod [Feature:SetHostnameAsFQDN][NodeFeature:SetHostnameAsFQDN] a pod with subdomain field has FQDN, when setHostnameAsFQDN is set to true, the FQDN is set as hostname [cos-stable1, cos-stable2, ubuntu]`

**Since when has it been failing**:
Since #96173 was merged

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#node-kubelet-features-master

**Reason for failure**:
Example:
```
Expected
        <string>: hostfqdn-29843;hostfqdn-29843.t.hostfqdn-3619.svc.;
        
    to contain substring
        <string>: hostfqdn-29843;hostfqdn-29843.t.hostfqdn-3619.svc.cluster.local;
```

Looks like the `dnsDomain` at L122 and L144 doesn't actually get printed? https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/pod_hostnamefqdn_test.go 

**Anything else we need to know**:
/sig node
/cc @kubernetes/ci-signal @kubernetes/sig-node-test-failures 
/priority important-soon

**Comment by javidiaz** [comment]
Hi @thejoycekung, sorry about that, I will work on it asap. Are you aware of any difference between the CI that executes NodeFeature and NodeAlphaFeature? 
FYI this other PR merged at the same time https://github.com/kubernetes/kubernetes/pull/95187

**Comment by javidiaz** [comment]
Somehow, the /etc/hosts of the pod does not have subdomain

`          # Kubernetes-managed hosts file.
          127.0.0.1	localhost
          ::1	localhost ip6-localhost ip6-loopback
          fe00::0	ip6-localnet
          fe00::0	ip6-mcastprefix
          fe00::1	ip6-allnodes
          fe00::2	ip6-allrouters
          172.17.0.2	hostfqdn-65330.t.hostfqdn-886.svc.	hostfqdn-65330`

I think the issue is that framework.TestContext.ClusterDNSDomain is empty String.

**Comment by javidiaz** [comment]
Hi @spiffxp , any idea of why cluster-subdomain is empty String in e2e node tests? 

These tests are failing because I made the wrong assumption that cluster-subdomain should be cluster.local by default. So I set cluster.local as the expected subdomain when framework.TestContext.ClusterDNSDomain is empty.

**Comment by javidiaz** [comment]
Hi @thejoycekung can you add priority to https://github.com/kubernetes/kubernetes/pull/96305?

**Comment by alejandrox1** [comment]
/triage accepted
Thank you @javidiaz for looking into this, and @thejoycekung for opening the issue :pray: 

Given https://github.com/kubernetes/kubernetes/pull/96315 i think you found the issue.
node e2e tests have theirwn entrypoint so i guess we forgot to completely account for all the settings the e2e framework sets and to use those to configure the kubelet.
I think in general we need to refactor the node test suite to prevent this sort of issue.
