### ISSUE TITLE
Eliminate dependency on go-openapi/spec

### ISSUE THREAD

**Issue by gautierdelorme** [kubernetes/kubernetes#96303]
Thanks to the work done in https://github.com/kubernetes/kubernetes/pull/95954 we should be able to completely remove the dependency on `go-openapi/spec`. It requires to bring back a few types (and related constructors) that were removed in https://github.com/kubernetes/kube-openapi/commit/73fa09a8495ec96b58cf5844be1ec467520a0541.

Refer to https://kubernetes.slack.com/archives/C0EG7JC6T/p1604659881491000?thread_ts=1592287631.273100&cid=C0EG7JC6T for additional context.

**Comment by fedebongio** [comment]
@gautierdelorme looks like you are planning to send a PR on this one, yes? Thank you!
/triage accepted

**Comment by carlory** [comment]
@gautierdelorme Any update about it? If not, I'm happy to work on

**Comment by gautierdelorme** [comment]
@carlory Yes I’m still on it. I’m just having a hard time testing my local kubernetes/kube-openapi changes in my local kubernetes/kubernetes branch. A simple replace directive in the go.mod doesn’t seem to work and running update-vendors.sh removes it.

**Comment by howardjohn** [comment]
Is this still planned? in another thread I saw this was blocked by kustomize update which appears to have merged

**Comment by gautierdelorme** [comment]
@howardjohn yes this is still planned. The kustomize update just got merged recently so I need to take another look at it.

**Comment by howardjohn** [comment]
Great, thanks for the update!
