### ISSUE TITLE
kubelet config flag using "--logging-format" and "--vmodule" raises a FATAL error

### ISSUE THREAD

**Issue by eatwithforks** [kubernetes/kubernetes#96314]
**What happened**:
```
--logging-format="json" --vmodule="cpu_manager*=1"
```

returns this error message via `journalctl -u kubelet`
```
{"level":"FATAL","message":"non-default logging format doesn't honor flag: vmodule"}
```
**What you expected to happen**:
vmodule and json format to work. I would like my logs to be in json and still be silencing all but cpu_manager errors. 

**How to reproduce it (as minimally and precisely as possible)**:
in what happened step

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by liggitt** [comment]
This is not yet supported by the klog library. This can be raised as a feature request against that component's repo at https://github.com/kubernetes/klog

**Comment by adammw** [comment]
JSON logging doesn't appear involve klog at all, instead component-base/logs package uses its own JSONLogger package based on zap.
