### ISSUE TITLE
Install pigz to GCE Windows Node Image

### ISSUE THREAD

**Issue by jeremyje** [kubernetes/kubernetes#96313]
**What would you like to be added**:
pigz for GCE Windows
**Why is this needed**:
Pigz improves the image layer extraction performance for multi-core systems.
Pigz is usually preinstalled on Linux. 
This enhancement is scoped specifically for the GKE Windows node scripts.

For Context: https://github.com/moby/moby/issues/34787

**Comment by BenTheElder** [comment]
s/GKE/GCE/? as in kube-up?

**Comment by jeremyje** [comment]
Replaced but I don't understand the kube-up part.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/blob/master/cluster/kube-up.sh is how one creates a GCE cluster from this repo. Otherwise we'd be talking about something that isn't part of kubernetes.
