### ISSUE TITLE
kubectl exec to pod failed, the response is "error: unable to upgrade connection: unexpected EOF"

### ISSUE THREAD

**Issue by webPageDev** [kubernetes/kubernetes#96333]
**What happened**:
**An error occurred when I executed the kubectl exec command on the master node to enter the pod.**
**The error printed after executing the kubectl exec command is "error: unable to upgrade connection: unexpected EOF".**
**And  it is printed in the log of kubelet, the log is "server.go:731] Error while proxying request: unexpected EOF".**

**I saw the information in the api-server log:**
I1106 03:16:34.266641       1 handler.go:153] kube-aggregator: POST "/api/v1/namespaces/kube-system/pods/grafana-798659d584-w29v2/exec" satisfied by nonGoRestful
I1106 03:16:34.266671       1 pathrecorder.go:247] kube-aggregator: "/api/v1/namespaces/kube-system/pods/grafana-798659d584-w29v2/exec" satisfied by prefix /api/
I1106 03:16:34.266682       1 handler.go:143] kube-apiserver: POST "/api/v1/namespaces/kube-system/pods/grafana-798659d584-w29v2/exec" satisfied by gorestful with webservice /api/v1
I1106 03:16:34.270475       1 upgradeaware.go:261] Connecting to backend proxy (intercepting redirects) https://172.36.33.51:10250/exec/kube-system/grafana-798659d584-w29v2/grafana?command=sh&input=1&output=1&tty=1
  Headers: map[Connection:[Upgrade] Content-Length:[0] Upgrade:[SPDY/3.1] User-Agent:[kubectl/v1.15.12 (linux/amd64) kubernetes/e2a822d] X-Forwarded-For:[172.36.33.54] X-Stream-Protocol-Version:[v4.channel.k8s.io v3.channel.k8s.io v2.channel.k8s.io channel.k8s.io]]
I1106 03:16:34.335564       1 upgradeaware.go:305] Proxy upgrade error, status code 500

**In addition, I use kubectl exec -it -v=10 -n kube-system grafana-798659d584-w29v2 in the environment, and the log information is as follows:**
I1106 11:07:07.437990   29457 loader.go:359] Config loaded from file:  /etc/kubernetes/admin.conf
I1106 11:07:07.440143   29457 cached_discovery.go:114] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/servergroups.json
I1106 11:07:07.443728   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/rbac.authorization.k8s.io/v1/serverresources.json
I1106 11:07:07.443883   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/storage.k8s.io/v1/serverresources.json
I1106 11:07:07.443532   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/batch/v1/serverresources.json
I1106 11:07:07.445472   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/scheduling.k8s.io/v1beta1/serverresources.json
I1106 11:07:07.445194   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/autoscaling/v2beta1/serverresources.json
I1106 11:07:07.446232   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/authorization.k8s.io/v1/serverresources.json
I1106 11:07:07.446458   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/apiregistration.k8s.io/v1/serverresources.json
I1106 11:07:07.446759   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/node.k8s.io/v1beta1/serverresources.json
I1106 11:07:07.446223   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/storage.k8s.io/v1beta1/serverresources.json
I1106 11:07:07.447360   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/apps/v1beta2/serverresources.json
I1106 11:07:07.447371   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/authentication.k8s.io/v1beta1/serverresources.json
I1106 11:07:07.446601   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/apps/v1beta1/serverresources.json
I1106 11:07:07.447615   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/autoscaling/v2beta2/serverresources.json
I1106 11:07:07.447717   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/authorization.k8s.io/v1beta1/serverresources.json
I1106 11:07:07.446226   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/networking.k8s.io/v1beta1/serverresources.json
I1106 11:07:07.446078   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/certificates.k8s.io/v1beta1/serverresources.json
I1106 11:07:07.448071   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/extensions/v1beta1/serverresources.json
I1106 11:07:07.448094   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/scheduling.k8s.io/v1/serverresources.json
I1106 11:07:07.448110   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/apiextensions.k8s.io/v1beta1/serverresources.json
I1106 11:07:07.447653   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/staticegressips.nirmata.io/v1alpha1/serverresources.json
I1106 11:07:07.448081   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/autoscaling/v1/serverresources.json
I1106 11:07:07.447494   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/apps/v1/serverresources.json
I1106 11:07:07.447321   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/networking.k8s.io/v1/serverresources.json
I1106 11:07:07.447722   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/apiregistration.k8s.io/v1beta1/serverresources.json
I1106 11:07:07.448572   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/batch/v1beta1/serverresources.json
I1106 11:07:07.448744   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/coordination.k8s.io/v1/serverresources.json
I1106 11:07:07.448793   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/k8s.cni.cncf.io/v1/serverresources.json
I1106 11:07:07.448859   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/rbac.authorization.k8s.io/v1beta1/serverresources.json
I1106 11:07:07.446181   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/policy/v1beta1/serverresources.json
I1106 11:07:07.448874   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/coordination.k8s.io/v1beta1/serverresources.json
I1106 11:07:07.449281   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/events.k8s.io/v1beta1/serverresources.json
I1106 11:07:07.449349   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/admissionregistration.k8s.io/v1beta1/serverresources.json
I1106 11:07:07.449413   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/authentication.k8s.io/v1/serverresources.json
I1106 11:07:07.449471   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/v1/serverresources.json
I1106 11:07:07.449707   29457 cached_discovery.go:114] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/servergroups.json
I1106 11:07:07.449864   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/autoscaling/v2beta1/serverresources.json
I1106 11:07:07.449864   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/staticegressips.nirmata.io/v1alpha1/serverresources.json
I1106 11:07:07.449902   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/authentication.k8s.io/v1/serverresources.json
I1106 11:07:07.449938   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/apiregistration.k8s.io/v1/serverresources.json
I1106 11:07:07.449960   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/authentication.k8s.io/v1beta1/serverresources.json
I1106 11:07:07.449986   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/storage.k8s.io/v1beta1/serverresources.json
I1106 11:07:07.449987   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/storage.k8s.io/v1/serverresources.json
I1106 11:07:07.450015   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/extensions/v1beta1/serverresources.json
I1106 11:07:07.450057   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/authorization.k8s.io/v1/serverresources.json
I1106 11:07:07.450114   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/admissionregistration.k8s.io/v1beta1/serverresources.json
I1106 11:07:07.450114   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/autoscaling/v2beta2/serverresources.json
I1106 11:07:07.450136   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/apps/v1/serverresources.json
I1106 11:07:07.450160   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/coordination.k8s.io/v1/serverresources.json
I1106 11:07:07.450167   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/authorization.k8s.io/v1beta1/serverresources.json
I1106 11:07:07.450161   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/apiregistration.k8s.io/v1beta1/serverresources.json
I1106 11:07:07.450197   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/coordination.k8s.io/v1beta1/serverresources.json
I1106 11:07:07.450268   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/node.k8s.io/v1beta1/serverresources.json
I1106 11:07:07.450306   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/apiextensions.k8s.io/v1beta1/serverresources.json
I1106 11:07:07.450312   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/k8s.cni.cncf.io/v1/serverresources.json
I1106 11:07:07.450354   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/batch/v1/serverresources.json
I1106 11:07:07.450368   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/scheduling.k8s.io/v1/serverresources.json
I1106 11:07:07.450372   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/v1/serverresources.json
I1106 11:07:07.450379   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/autoscaling/v1/serverresources.json
I1106 11:07:07.450383   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/events.k8s.io/v1beta1/serverresources.json
I1106 11:07:07.450380   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/networking.k8s.io/v1beta1/serverresources.json
I1106 11:07:07.450464   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/batch/v1beta1/serverresources.json
I1106 11:07:07.450466   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/certificates.k8s.io/v1beta1/serverresources.json
I1106 11:07:07.450474   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/apps/v1beta2/serverresources.json
I1106 11:07:07.450496   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/apps/v1beta1/serverresources.json
I1106 11:07:07.450502   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/rbac.authorization.k8s.io/v1beta1/serverresources.json
I1106 11:07:07.450522   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/networking.k8s.io/v1/serverresources.json
I1106 11:07:07.450579   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/scheduling.k8s.io/v1beta1/serverresources.json
I1106 11:07:07.450614   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/rbac.authorization.k8s.io/v1/serverresources.json
I1106 11:07:07.450632   29457 cached_discovery.go:71] returning cached discovery info from /home/admin/.kube/cache/discovery/172.36.33.54_6443/policy/v1beta1/serverresources.json
I1106 11:07:07.453043   29457 round_trippers.go:419] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.15.12 (linux/amd64) kubernetes/e2a822d" 'https://172.36.33.54:6443/api/v1/namespaces/kube-system/pods/grafana-798659d584-w29v2'
I1106 11:07:07.466115   29457 round_trippers.go:438] GET https://172.36.33.54:6443/api/v1/namespaces/kube-system/pods/grafana-798659d584-w29v2 200 OK in 13 milliseconds
I1106 11:07:07.466157   29457 round_trippers.go:444] Response Headers:
I1106 11:07:07.466164   29457 round_trippers.go:447]     Content-Length: 3319
I1106 11:07:07.466171   29457 round_trippers.go:447]     Date: Fri, 06 Nov 2020 03:07:07 GMT
I1106 11:07:07.466178   29457 round_trippers.go:447]     Content-Type: application/json
I1106 11:07:07.466262   29457 request.go:947] Response Body: {"kind":"Pod","apiVersion":"v1","metadata":{"name":"grafana-798659d584-w29v2","generateName":"grafana-798659d584-","namespace":"kube-system","selfLink":"/api/v1/namespaces/kube-system/pods/grafana-798659d584-w29v2","uid":"39a9b4b9-5eaa-4bd0-b59f-fd062113b808","resourceVersion":"688913","creationTimestamp":"2020-11-06T02:44:16Z","labels":{"app":"grafana","pod-template-hash":"798659d584"},"ownerReferences":[{"apiVersion":"apps/v1","kind":"ReplicaSet","name":"grafana-798659d584","uid":"567eee66-afbe-407e-b3f2-617cd810cb8c","controller":true,"blockOwnerDeletion":true}]},"spec":{"volumes":[{"name":"grafana-conf","hostPath":{"path":"/opt/matrix/k8s/conf/grafana","type":""}},{"name":"grafana-log","hostPath":{"path":"/var/log/matrix-diag/Matrix/grafana","type":""}},{"name":"default-token-nmxtv","secret":{"secretName":"default-token-nmxtv","defaultMode":420}}],"containers":[{"name":"grafana","image":"matrix-registry.h3c.com:8088/matrix/grafana:6.6.1.1","ports":[{"containerPort":3000,"protocol":"TCP"}],"resources":{},"volumeMounts":[{"name":"grafana-conf","mountPath":"/etc/grafana"},{"name":"grafana-log","mountPath":"/var/log/grafana"},{"name":"default-token-nmxtv","readOnly":true,"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"}],"readinessProbe":{"httpGet":{"path":"/login","port":3000,"scheme":"HTTP"},"timeoutSeconds":1,"periodSeconds":10,"successThreshold":1,"failureThreshold":3},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","nodeSelector":{"role":"master"},"serviceAccountName":"default","serviceAccount":"default","nodeName":"uc51","securityContext":{},"affinity":{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchExpressions":[{"key":"app","operator":"In","values":["grafana"]}]},"topologyKey":"kubernetes.io/hostname"}]}},"schedulerName":"default-scheduler","tolerations":[{"key":"node.kubernetes.io/not-ready","operator":"Exists","effect":"NoExecute","tolerationSeconds":300},{"key":"node.kubernetes.io/unreachable","operator":"Exists","effect":"NoExecute","tolerationSeconds":300}],"priorityClassName":"system-node-critical","priority":2000001000,"enableServiceLinks":true},"status":{"phase":"Running","conditions":[{"type":"Initialized","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-11-06T02:44:19Z"},{"type":"Ready","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-11-06T02:44:25Z"},{"type":"ContainersReady","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-11-06T02:44:25Z"},{"type":"PodScheduled","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-11-06T02:44:19Z"}],"hostIP":"172.36.33.51","podIP":"177.177.165.54","startTime":"2020-11-06T02:44:19Z","containerStatuses":[{"name":"grafana","state":{"running":{"startedAt":"2020-11-06T02:44:20Z"}},"lastState":{},"ready":true,"restartCount":0,"image":"matrix-registry.h3c.com:8088/matrix/grafana:6.6.1.1","imageID":"docker-pullable://matrix-registry.h3c.com:8088/matrix/grafana@sha256:d8211e1d3ba82e2c418bc79a2cdc36675812440657ebdd8364de97be6a719c04","containerID":"docker://c25f1c22ed91fa87072f7943c88779dfda4ae923af76e271e390f4c937f6b199"}],"qosClass":"BestEffort"}}
I1106 11:07:07.475591   29457 round_trippers.go:419] curl -k -v -XPOST  -H "User-Agent: kubectl/v1.15.12 (linux/amd64) kubernetes/e2a822d" -H "X-Stream-Protocol-Version: v4.channel.k8s.io" -H "X-Stream-Protocol-Version: v3.channel.k8s.io" -H "X-Stream-Protocol-Version: v2.channel.k8s.io" -H "X-Stream-Protocol-Version: channel.k8s.io" 'https://172.36.33.54:6443/api/v1/namespaces/kube-system/pods/grafana-798659d584-w29v2/exec?command=sh&command=shell&command=comand&container=grafana&stdin=true&stdout=true&tty=true'
I1106 11:07:07.545522   29457 round_trippers.go:438] POST https://172.36.33.54:6443/api/v1/namespaces/kube-system/pods/grafana-798659d584-w29v2/exec?command=sh&command=shell&command=comand&container=grafana&stdin=true&stdout=true&tty=true 500 Internal Server Error in 69 milliseconds
I1106 11:07:07.545563   29457 round_trippers.go:444] Response Headers:
I1106 11:07:07.545572   29457 round_trippers.go:447]     Content-Length: 15
I1106 11:07:07.545579   29457 round_trippers.go:447]     Content-Type: text/plain; charset=utf-8
I1106 11:07:07.545586   29457 round_trippers.go:447]     Date: Fri, 06 Nov 2020 03:07:07 GMT
I1106 11:07:07.545592   29457 round_trippers.go:447]     X-Content-Type-Options: nosniff
F1106 11:07:07.545990   29457 helpers.go:114] error: unable to upgrade connection: unexpected EOF

**What you expected to happen**:
I want to know why this happened, and how can I avoid this problem in the future.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"archive", BuildDate:"2020-09-22T02:51:54Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:11:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
Linux 161 3.10.0-957.21.3.el7.x86_64 #1 SMP Wed Jul 17 06:57:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by lala123912** [comment]
It sounds like that it's timeout for waiting response, and you could check  whether  the format of the response  is abnormal or not.

**Comment by neolit123** [comment]
> I1106 11:07:07.545522 29457 round_trippers.go:438] POST https://172.36.33.54:6443/api/v1/namespaces/kube-system/pods/grafana-798659d584-w29v2/exec?command=sh&command=shell&command=comand&container=grafana&stdin=true&stdout=true&tty=true 500 Internal Server Error in 69 milliseconds

hi, this seems like a request for support. please make sure the server is working fine.

> Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6",

this version is no longer supported. you'd have to upgrade to 1.18 soon.
if you confirm this as a bug in newer versions, please re-open this ticket.

/remove-kind bug
/kind support
/close
