### ISSUE TITLE
kubectl prompts credentials

### ISSUE THREAD

**Issue by movinglightspeed** [kubernetes/kubernetes#96349]
**What happened**:
I am randomly now getting kubectl credential prompts everytime i use kubectl

**What you expected to happen**:
kubectl should not be prompting for username and password

**How to reproduce it (as minimally and precisely as possible)**:
Follow these steps
https://cloud.ibm.com/docs/containers?topic=containers-cs_cli_install#cs_cli_configure

Then try to use kubectl 
PS C:\Users\User> kubectl config current-context
mycluster/abcdp36d05k27abcdef0
PS C:\Users\User> kubectl get nodes
Please enter Username:
error: EOF
PS C:\Users\User> ^C
PS C:\Users\User> ^C
PS C:\Users\User> kubectl version
Please enter Username: ""
Please enter Password: Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+2fbd7c7", GitCommit:"2fbd7c7", GitTreeState:"clean", BuildDate:"2020-10-09T11:41:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

It should not be prompting for kubectl credentials

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+2fbd7c7", GitCommit:"2fbd7c7", GitTreeState:"clean", BuildDate:"2020-10-09T11:41:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
IBM Cloud Kubernetes Services (IKS)

- OS (e.g: `cat /etc/os-release`): Windows 10 Pro
- Kernel (e.g. `uname -a`): Build 19042.610
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
C:\Users\user\.kube\config file contents

apiVersion: v1
clusters:
- cluster:
    server: https://c114-e.us-south.containers.cloud.ibm.com:30844
  name: mycluster/abcdp36d05k27abcdef0
contexts:
- context:
    cluster: mycluster/abcdp36d05k27abcdef0
    namespace: default
    user: ""
  name: mycluster/abcdp36d05k27abcdef0
current-context: mycluster/abcdp36d05k27abcdef0
kind: Config
preferences: {}
users: null

**Comment by neolit123** [comment]
this doesn't seem like a bug.
please try the support channels until a bug is confirmed:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
/remove-sig cluster-lifecycle
