### ISSUE TITLE
  ["kubelet"] cgroup does not exist

### ISSUE THREAD

**Issue by system51** [kubernetes/kubernetes#96352]
**What happened**:

Try to add the kube-reserved parameter to the kubelet and prompt an error。
```
F1109 08:37:28.100763   10542 kubelet.go:1384] Failed to start ContainerManager Failed to enforce Kube Reserved Cgroup Limits on "/kubelet.slice": ["kubelet"] cgroup does not exist
```

I know by looking up that some parameters need to be added, but I don't know why these parameters need to be added.
```
$ mkdir -p /sys/fs/cgroup/cpu,cpuacct/kubelet.slice
$ mkdir -p /sys/fs/cgroup/memory/kubelet.slice
$ mkdir -p /sys/fs/cgroup/systemd/kubelet.slice
$ mkdir -p /sys/fs/cgroup/pids/kubelet.slice
$ mkdir -p /sys/fs/cgroup/cpu,cpuacct/kubelet.slice
$ mkdir -p /sys/fs/cgroup/cpuset/kubelet.slice
```

![image](https://user-images.githubusercontent.com/26198108/98490545-bf866380-226c-11eb-8d3a-09f118e2ba22.png)

The Kubelet error does not indicate that these directories are missing., but why are these?I don't think its cues are friendly

**What you expected to happen**:
I want to limit kubernetes resources，Start Kubelet normally

**How to reproduce it (as minimally and precisely as possible)**:
```
vim /var/lib/kubelet/config.yaml
```
```
enforceNodeAllocatable:
- pods
- kube-reserved 
kubeReserved:
  cpu: 500m
  memory: 1Gi
  ephemeral-storage: 1Gi
kubeReservedCgroup: /kubelet.slice 
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:

```
vmware
```

- OS (e.g: `cat /etc/os-release`):
```
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
```

- Kernel (e.g. `uname -a`):
```
Linux k8s-m3 4.18.0-147.el8.x86_64 #1 SMP Wed Dec 4 21:51:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
```
kubeadm
```
- Network plugin and version (if this is a network-related bug):
- Others:

/sig node
/close

**Comment by lingsamuel** [comment]
If I understand [the document](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#kube-reserved) correctly, you could use flag `-kube-reserved-cgroup` to config it.

> Note that Kubelet does not create --kube-reserved-cgroup if it doesn't exist. Kubelet will fail if an invalid cgroup is specified.

**Comment by system51** [comment]
@lingsamuel 
I need to add --kube-reserved -- CGroup to restrict kube resources. The Cgroup file will not be created automatically when I add the parameter. I need to create them manually. How do I know which directories I need to create? For example, how do I make sure I need the catalogs mentioned above

**Comment by lingsamuel** [comment]
As far as I know, they simply pointsto the cgroup controllers with the same name. `ephemeral-storage` is an exception.

**Comment by system51** [comment]
I cannot confirm which directories I need to create kubelet.slice. How do I confirm which directories I need to create kubelet.slice


![image](https://user-images.githubusercontent.com/26198108/98513514-f1b2b800-22a2-11eb-85bd-218bc597c598.png)

**Comment by lingsamuel** [comment]
> "why are these directories", is because *you claim them in the yaml*...
So you need `cpu` and `memory`.

**Comment by system51** [comment]
@lingsamuel  ok, tks I seem to have found something in the code https://github.com/kubernetes/kubernetes/blob/v1.18.10/pkg/kubelet/cm/cgroup_manager_linux.go



```
func (m *cgroupManagerImpl) Exists(name CgroupName) bool {
	// Get map of all cgroup paths on the system for the particular cgroup
	cgroupPaths := m.buildCgroupPaths(name)

	// the presence of alternative control groups not known to runc confuses
	// the kubelet existence checks.
	// ideally, we would have a mechanism in runc to support Exists() logic
	// scoped to the set control groups it understands.  this is being discussed
	// in https://github.com/opencontainers/runc/issues/1440
	// once resolved, we can remove this code.
	whitelistControllers := sets.NewString("cpu", "cpuacct", "cpuset", "memory", "systemd")
	if utilfeature.DefaultFeatureGate.Enabled(kubefeatures.SupportPodPidsLimit) || utilfeature.DefaultFeatureGate.Enabled(kubefeatures.SupportNodePidsLimit) {
		whitelistControllers.Insert("pids")
	}
	if _, ok := m.subsystems.MountPoints["hugetlb"]; ok {
		whitelistControllers.Insert("hugetlb")
	}
	var missingPaths []string
	// If even one cgroup path doesn't exist, then the cgroup doesn't exist.
	for controller, path := range cgroupPaths {
		// ignore mounts we don't care about
		if !whitelistControllers.Has(controller) {
			continue
		}
		if !libcontainercgroups.PathExists(path) {
			missingPaths = append(missingPaths, path)
		}
	}

	if len(missingPaths) > 0 {
		klog.V(4).Infof("The Cgroup %v has some missing paths: %v", name, missingPaths)
		return false
	}

	return true
}
```

**Comment by lingsamuel** [comment]
Is this issue solved? I suspect this can be closed.
