### ISSUE TITLE
cgroupDriver: systemd not working in kubelet 1.19.3

### ISSUE THREAD

**Issue by raz3k** [kubernetes/kubernetes#96366]
**What happened**: 
Tried using kubeneretes 1.19.3 and set docker to systemd as in 1.18.10, then gave kubelet config to kubeadm init because automatic detection did not work.
**What you expected to happen**: 
kubelet load and init the cluster

**How to reproduce it (as minimally and precisely as possible)**: Use this config below when initiating or just set docker to systemd by adding --exec-opt native.cgroupdriver=systemd
```
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
```

**Anything else we need to know?**: 
/var/lib/kubelet/config.yaml has `cgroupDriver: systemd` set

systemd log of kubelet: https://pastebin.com/Z4AL7r91

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.3
- Cloud provider or hardware configuration: 8 cores 2.3 Ghz / 16 Gb of ram
- OS (e.g: `cat /etc/os-release`): CentOS 7.8
- Kernel (e.g. `uname -a`):  3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
would you check the  file /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf for 

```
Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml"
```

or something override the config. 

ps aux | grep kubelet to see whole process args

**Comment by raz3k** [comment]
yep, that was the issue, didn't have the --config set.

Thanks for your help.

Closing this.
