### ISSUE TITLE
Fuse mount "Transport endpoint is not connected" error

### ISSUE THREAD

**Issue by zizon** [kubernetes/kubernetes#96361]
**What happened**:
can not mount Cephfs/fuse volumes when fuse process was crash and latter pod crash restart or kubelet restart which will eventually try to recreate the silly mount on the same path.

**What you expected to happen**:
volume umount/remount

**How to reproduce it (as minimally and precisely as possible)**:
kill fuse, restart kubelet

**Anything else we need to know?**:

similar to https://github.com/kubernetes/kubernetes/issues/41141
there are chance that fuse volumes are present in actual_state_of_world with mounted or unmounted state.
when fuse process crashed, pods can not access or with an-ENOTCONN.

the same occurs when kubelt try to access the mounted path.
like fix this [PR](https://github.com/kubernetes/kubernetes/pull/52324/files) introduced, it is a corrupted mount.

take a look at the code path here [GenerateMountVolumeFunc](https://github.com/kubernetes/kubernetes/blob/v1.19.2/pkg/volume/util/operationexecutor/operation_generator.go#L651).
when mountErr  == -ENOTCONN eventually fail.

A quick fix can be added to operator.MountVolume. when volume mounter setup return an -ENOTCONN or some kind error.
but it makes the sematic of MountVolume a bit confuseed.

another approach maybe add a special routine in volume reconciler loop.
stat each volume to check readable/writable, and do umount/remount respective.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
Not familar with ceph. I find that Azure disk has a similar logic as you expected in  https://github.com/kubernetes/kubernetes/pull/57953/files  remount the volume after some check.

Are you using ceph fs https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/cephfs/cephfs.go ?

**Comment by zizon** [comment]
Yep.  

The mount code path is merely a /sbin/mount.fuse command which should be common to all fuse base volume.  
Issue #41141 mention above  is GlusterFS  which is also base on top of fuse.

**Comment by zizon** [comment]
one can reproduce something similar in following step.  

- setup a container with fuse mount.
- kill the corresponding fuse process.
- trigger container restart, which will try to mount the same path on node but when checking mount point, getting  a -ENOTCONN  thus resulting an early give up of mounting action.

**Comment by xieydd** [comment]
@zizon Is some progress?

**Comment by zizon** [comment]
> @zizon Is some progress?

It seems not.
Maybe because the fix require a bunch code involved(recognize fuse and non-fuse mounter) but brings litter benefit.

Your can walk around this issue by a simple crontab check or better, a daemonset/agent.

**Comment by xieydd** [comment]
I am thinking, if we can do some work in csi, control the volume remount while pod is running.

**Comment by zizon** [comment]
As the Azure fix  @pacoxu mentioned above, It can be done in implementation specified way, but a bit mess to be generic.

It may not be aways recoverable by simply doing a umount/remount for a fuse fs.
If it can`t be ensured, that fix is at least not completed, and may introduce  extra unexpected because of vendor specific behavior.
