### ISSUE TITLE
Draining nodes with stand-alone pods managed by custom controllers

### ISSUE THREAD

**Issue by exdx** [kubernetes/kubernetes#96382]
Currently the `kubectl drain` command requires usage of the `--force` flag in the case where the node has standalone pods running on it not backed by a deployment or replicaset (or other built-in controllers). 

In the case where there are pods that are managed by custom controllers and do not fit the deployment model (for example, stateful gRPC servers with long-lived connections and custom scaling rules) is there any way to enable draining a node with these pods running on them (aside from having them be backed by built-in controllers)? These pods are backed by an operator with more fine-grained controls over rescheduling them than the deployment controller provides. 

For example, if the `ownerRef` of the pod in question is a controller, would allowing the eviction to take place make sense? That's more of a feature request. 

Or if the pod has a `minAvailable:0` PodDisruptionBudget associated with it, should that enable the eviction to succeed? 

This issue is just to ask for some guidance around this topic, since users are attempting to drain nodes in their cluster and finding that they have to use the `--force` option

**Comment by neolit123** [comment]
/sig apps
/kind feature

the sig apps contact details (slack, zoom meeting, etc) can be found here:
https://github.com/kubernetes/community/tree/master/sig-apps

**Comment by michaelgugino** [comment]
Drain implies you want everything that's running on a node to be removed, thus force is required to utilize for pods not owned by a built in controller.  "force" is probably the wrong name for the option, it should be "ok-to-remove-pods-without-replica-controller" but it's just "force."

In most cases, you will want to use the force option.

If your use case is you want to remove only pods with controllers, but not any unmanaged pods, then force will not work.  Perhaps there could be another option such as "--force-with-controllers" (or another better name) to achieve this.

This would be a pretty straight forward change, I think.

/sig cli

**Comment by exdx** [comment]
> If your use case is you want to remove only pods with controllers, but not any unmanaged pods, then force will not work. Perhaps there could be another option such as "--force-with-controllers" (or another better name) to achieve this.

The original use case is for the user to be able to drain the node of all pods (both managed by a RS and managed by a controller) without the need for `--force` explicitly. So pods managed by custom controllers are deletable just like pods managed by built-in controllers. 

This could be achieved by an additional `--force-with-controllers` flag alongside the `drain` command as you suggested. I think the user objects to the term "force" in the flag because it suggests the pod is unmanaged and deleting it is unsafe somehow. 

One solution is to have a new flag like `--all-controllers` or something that when combined with the `drain` command will delete all pods managed by any type of controller on the node. It's entirely opt-in it and should be a safe api change. Versus changing the underlying delete machinery to be more permissive which could surprise users. If that sounds reasonable, I could open an exploratory PR implementing such a flag.

**Comment by michaelgugino** [comment]
> One solution is to have a new flag like `--all-controllers` or something that when combined with the `drain` command will delete all pods managed by any type of controller on the node. It's entirely opt-in it and should be a safe api change. Versus changing the underlying delete machinery to be more permissive which could surprise users. If that sounds reasonable, I could open an exploratory PR implementing such a flag.

I think we are in agreement here.  Maybe `--any-controller` is better than `--all-controllers`?  Anyway, I'm not too concerned with the name of the option, they are all not great names due to `--force`` existing already.

This seems like a reasonable change if you want to do a PR, I think people would probably accept it.

**Comment by exdx** [comment]
I'm probably just going to close this unless there is some more traction from other members of the community. Seems like if my project is the only one potentially asking for this feature, then we should reassess our own implementation

**Comment by michaelgugino** [comment]
> I'm probably just going to close this unless there is some more traction from other members of the community. Seems like if my project is the only one potentially asking for this feature, then we should reassess our own implementation

I think most people are probably happy with the `--force` option.  In most cases, you probably just want to remove all the pods that you can remove from a node.  Without `--force` specified, with the change being discussed here, if there are any pods without a controller, nothing will be drained as those pods will block all draining.

Personally, I would never run drain without force.  If you have a singleton pod that you want replaced, you have a controller for it.  If you don't, and there's not a PDB, it wasn't important anyway.

**Comment by exdx** [comment]
> Personally, I would never run drain without force. If you have a singleton pod that you want replaced, you have a controller for it. If you don't, and there's not a PDB, it wasn't important anyway.

That's an interesting viewpoint. I think some users naturally hesitate to add the `--force` flag to anything, but given the existing predicates around draining I think it makes sense. I can pass this issue along to some folks who were interested in this functionality.

Will close for now, thanks for taking a look 👍
