### ISSUE TITLE
Add option to disable rotate certificates for kubelet in kubeadm

### ISSUE THREAD

**Issue by ironyman** [kubernetes/kubernetes#96394]
This is both an issue and an enhancement request but the template for the latter is simpler so here goes the issue.

kubeadm enables kubelet rotateCertificates option in /var/lib/kubelet/config.yaml regardless of configuration passed to kubeadm. To my understanding config values in /var/lib/kubelet/config.yaml should be able to be configured by supplying a config file to kubeadm via the --config parameter. But this does not work rotateCertificates presumably because of the following lines of code

https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/componentconfigs/kubelet.go#L194
```
	// We cannot show a warning for RotateCertificates==false and we must hardcode it to true.
	// There is no way to determine if the user has set this or not, given the field is a non-pointer.
	kc.config.RotateCertificates = kubeletRotateCertificates
```

I assume this is because this RotateCertificates configuration needs to be on for tls bootstrap to work. I also assume RotateCertificates is not set to the user supplied value to kubeadm because kubeadm cannot determine if the config value was explicitly set to false or if the config value is set to false by default because there's not a user supplied config value.

**What would you like to be added**:
I propose we add an command line flag to kubeadm to disable rotateCertificates after tls bootstrap finishes. There's already a phase that changes this flag at the end of the init subcommand but it only enables rotateCertificates and does not disable.
```
kubelet-finalize             Updates settings relevant to the kubelet after TLS bootstrap
  /experimental-cert-rotation  Enable kubelet client certificate rotation
```

This would be a minor change to allow a flag to disable rotateCertificates and this phase would be added to the join subcommand as well.
**Why is this needed**:
We don't want cert rotation sometimes.

**Comment by neolit123** [comment]
hello and thank you for logging this ticket.
as you may have noticed the field not being a pointer is problematic.

> I propose we add an command line flag to kubeadm to disable rotateCertificates after tls bootstrap finishes. There's already a phase that changes this flag at the end of the init subcommand but it only enables rotateCertificates and does not disable.

IIRC, adding an explicit flag or field in the kubeadm config was already discussed but its not ideal.
the problem here is really on the side of the kubelet configuration and the field should be made into a pointer so that we have 3 states of the field instead of 2 (nil, true, false). adding a workaround for that by introducing kubeadm options is not desired, thus we have to hardcode it.

one workaround is to:
- start `kubeadm init` by default but pass `--skip-phases=kubelet-finalize/experimental-cert-rotation`
- modify the kubelet config file to disable rotation
- update kubelet-config-x.yy in kube-system
- restart the kubelet
- proceed to join more workers which will use the configuration with disabled rotation

hope that helps.
/area kubeadm
/close

**Comment by ironyman** [comment]
@neolit123  What is the correct way to modify kubelet config.yaml? I tried using sigs.k8s.io/yaml to unmarshal and marshal into KubeletConfiguration but upon marshaling the output yaml document is severely different from the original. The ordering of fields are changed and the typemeta field which is marked as inline in the KubeletConfiguration definition is not inlined.
```
typemeta:
  kind: KubeletConfiguration
  apiversion: kubelet.config.k8s.io/v1beta1
```

**Comment by neolit123** [comment]
> the ordering of fields are changed

they are likely sorted, which is expected when fields are marshaled with most libraries.

> typemeta field which is marked as inline

i cannot reproduce that. the following snipped:
```go
package main

import (
	"fmt"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/kubelet/config/v1beta1"
	"sigs.k8s.io/yaml"
)

func main() {
	c := &v1beta1.KubeletConfiguration{
		TypeMeta: metav1.TypeMeta{
			Kind:       "KubeletConfiguration",
			APIVersion: "kubelet.config.k8s.io/v1beta1",
		},
	}
	b, _ := yaml.Marshal(c)
	fmt.Printf("%s\n", b)
}
```

gives me:
```
apiVersion: kubelet.config.k8s.io/v1beta1
...
kind: KubeletConfiguration
```

> What is the correct way to modify kubelet config.yaml?

depends on the use case. you could just `sed`, or [patch](https://github.com/krishicks/yaml-patch) the YAML file too.

**Comment by ironyman** [comment]
Ah you're right. My mistake. Thank you!
