### ISSUE TITLE
Installing Keptn in AKS Via Helm command, getting exception

### ISSUE THREAD

**Issue by SaveethaRavi** [kubernetes/kubernetes#96415]
Hi team,

I tried installing keptn in AKS via HELM upgrade command, getting issues as "Error: validation: chart.metadata is required". Can anyone please suggest to overcome this issue and installing keptn in AKS. 

Please refer attached screenshot.
<img width="887" alt="keptn error" src="https://user-images.githubusercontent.com/57527241/98673497-6ce89c80-237d-11eb-8a6a-9b3dee276f2d.PNG">

**Comment by troy0820** [comment]
/kind support
This looks like a Keptn issue and not a Kubernetes issue.  I see that you opened up an issue there and are getting help with it.
/close
