### ISSUE TITLE
e2e storage subpath test function waitForPodSubpathError returns too may values

### ISSUE THREAD

**Issue by DavidCsaki** [kubernetes/kubernetes#96419]
**What happened**:
Test failed:
[sig-storage] In-tree Volumes [Driver: ceph][Feature:Volumes][Serial] [Testpattern: Pre-provisioned PV (default fs)] subPath should verify container cannot write to subpath readonly volumes [Slow]

with error:
"error waiting for pod subpath error to occur: subpath container unexpectedly terminated"

**What you expected to happen**:
Test should have passed with no error, since allowContainerTerminationError argument in  waitForPodSubpathError function, in 
test/e2e/storage/testsuites/subpath.go is set to true.

However in the snippet below, instead of returning only: nil
the function returns:   true, nil

				case status.State.Terminated != nil:
					if status.State.Terminated.ExitCode != 0 && allowContainerTerminationError {
						return true, nil
					}

**How to reproduce it (as minimally and precisely as possible)**:
execute the test on a system where subpath container is terminated

**Anything else we need to know?**:
There are a number of other places in this function where there are 2 return values instead of one. 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.3
- OS (e.g: `cat /etc/os-release`):"SUSE Linux Enterprise Server 15 SP1"
- Kernel (e.g. `uname -a`):Linux xxx 4.12.14-197.64-default #1 SMP Thu Oct 15 11:23:18 UTC 2020 (18f88c8) x86_64 x86_64 x86_64

**Comment by wawa0210** [comment]
https://github.com/kubernetes/kubernetes/blob/198b2fdb145e85e94494441bacc2692f8718ac4a/test/e2e/storage/testsuites/subpath.go#L724-L761

`waitErr` is an anonymous method with an anonymous method nested inside

https://github.com/kubernetes/kubernetes/blob/198b2fdb145e85e94494441bacc2692f8718ac4a/test/e2e/storage/testsuites/subpath.go#L739-L742
There are two return values ​​as expected

**Comment by DavidCsaki** [comment]
My misunderstanding of inner function. I should not have made any conclusion of why we received the error:
"error waiting for pod subpath error to occur: subpath container unexpectedly terminated"
But in our environment we get this error every time we run the test.
