### ISSUE TITLE
Kubelet: expose metrics about time to first successful probe return

### ISSUE THREAD

**Issue by sylr** [kubernetes/kubernetes#96411]
**What would you like to be added**:

I'd like kubelet to generate histograms about the time it takes between container start and the first successful status for each defined probes (readiness, liveness, startup).

**Why is this needed**:

This would allow to graphs the startup times of containers for fine tuning delays and give indications that containers takes more time to start on some nodes.

https://github.com/kubernetes/kubernetes/issues/96411#tasklist-block-f828d8f9-6c6e-4ad4-a2d2-85c699b54869

**Comment by EmilyM1** [comment]
Not a histogram, which would be a nice add -- but there's init containers that may be useful to you:
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

**Comment by SergeyKanzhelev** [comment]
@jackfrancis , when working on https://github.com/kubernetes/kubernetes/issues/101035, can you please consider if adding these metrics will also be beneficial

**Comment by jackfrancis** [comment]
/remove-lifecycle stale

I think that this PR will address this request, as it adds metrics for *all* successful probe durations (which is inclusive of the *first* successful probe duration):

https://github.com/kubernetes/kubernetes/pull/104484

**Comment by jackfrancis** [comment]
https://github.com/kubernetes/kubernetes/pull/104484 is still active

**Comment by jackfrancis** [comment]
https://github.com/kubernetes/kubernetes/pull/104484 landed in 1.25, I think we can close this issue
