### ISSUE TITLE
Double counting in the IPAM

### ISSUE THREAD

**Issue by hvenev-vmware** [kubernetes/kubernetes#96416]
**What happened**:
With a /22 pod network and a /24 assigned to each node, a third node cannot get a pod CIDR if kube-controller-manager has ever been restarted.

**What you expected to happen**:
Once a third or fourth node joins, it gets a /24.

**How to reproduce it (as minimally and precisely as possible)**:
```
minikube start -n 3 --extra-config kubeadm.pod-network-cidr=10.244.0.0/22
sleep 10
minikube ssh -- sudo curl -sk https://127.0.0.1:10257/metrics --key /var/lib/minikube/certs/apiserver-kubelet-client.key --cert /var/lib/minikube/certs/apiserver-kubelet-client.crt | grep '^node_ipam'
minikube ssh -- sudo pkill -9 -ef kube-controller-manager
sleep 30
minikube ssh -- sudo curl -sk https://127.0.0.1:10257/metrics --key /var/lib/minikube/certs/apiserver-kubelet-client.key --cert /var/lib/minikube/certs/apiserver-kubelet-client.crt | grep '^node_ipam'
```

150% usage on the IPAM controller is not a good sign.

**Anything else we need to know?**:
During the creation of the rangeAllocator, Occupy() is called twice on the pod networks. The first time is before subscribing to the node informer. The second time is during the node informer callbacks because on subscribing it calls Add for all existing nodes.

I will submit a proposed fix shortly.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.2

**Comment by aojea** [comment]
/triage accepted
thanks for finding the bug I 've introduced :)
