### ISSUE TITLE
API to access kube-scheduler's options and configuration parameters

### ISSUE THREAD

**Issue by yuanchen8911** [kubernetes/kubernetes#96427]
**What would you like to be added**:

Provide APIs  for out-of-tree scheduler plugins to access kube-scheduler's options and configuration parameters, such as `kubeconfig` path and `Master`. 

**Why is this needed**:

Out-of-tree scheduler plugins often need `kubeconfig` path and `Master` information to create `clientset` and `informers`. A plugin has to process and manage these parameters separately, e.g., using additional plugin arguments. It puts additional burden on developers. Users have to provide addiontal parameters as well.

As these parameters are already available as the command line arguments and/or in the scheduler configuration, it will simplify the developer's work and improve user experience if a plugin can have a simple way to access `kubeconfig` path and `Master` information from the existing configurations/options data.

**Comment by Huang-Wei** [comment]
In general, we have several ways to tweak the framework handle:

https://github.com/kubernetes/kubernetes/blob/30a261d97c65f3e1e46a93eb368376f68935a057/pkg/scheduler/framework/interface.go#L588-L589

- Keep current `ClientSet` function, and add an additional `ClientBuilder` function for out-of-tree plugins to obtain Config (restclient.Config) and DynamicClient
- Mark current `ClientSet` function as deprecated, and add an additional `ClientBuilder` function for out-of-tree plugins to obtain Config (restclient.Config), ClientSet and DynamicClient
- Expose a single `ClientBuilder` function to surface Config (restclient.Config), ClientSet and DynamicClient - it's similar to how [ControllerClientBuilder](https://github.com/kubernetes/kubernetes/blob/30a261d97c65f3e1e46a93eb368376f68935a057/staging/src/k8s.io/controller-manager/pkg/clientbuilder/client_builder.go#L26-L36) is built

@ahg-g @alculquicondor @damemi thoughts?

**Comment by alculquicondor** [comment]
Before exposing more internals.

> Out-of-tree scheduler plugins often need kubeconfig path and Master information to create clientset and informers.

I believe both of these are already covered with the current Handler interface. You can get a `ClientSet` and the `SharedInformerFactory`. 

@yuanchen8911 Have you tried those?
Do you have other use cases where you absolutely need the `restclient.Config`?
Could you describe your use case with more detail so we can brainstorm other solutions other than what you propose?

**Comment by Huang-Wei** [comment]
> I believe both of these are already covered with the current Handler interface. You can get a `ClientSet` and the `SharedInformerFactory`.

What we are referring to is particular CientSets based on custom resources, see [here](https://github.com/kubernetes-sigs/scheduler-plugins/blob/268c1b71a08fb6fa1a5fbcebac85c6fe543622be/pkg/capacityscheduling/capacity_scheduling.go#L117).

For now, it's inconvinient to reuse the same clientConnection to construct CRD based informers. We had to work it around by re-configuting the client path in pluginArgs.

**Comment by alculquicondor** [comment]
In that case, I prefer minimal changes: Add a method that returns `restclient.Config`

**Comment by Huang-Wei** [comment]
`restclient.Config` exposes too much info like password, bearerToken, so woundn't be a good option:

https://github.com/kubernetes/kubernetes/blob/e29c568c4a9cd45d15665345aa015e21bcff52dd/staging/src/k8s.io/client-go/rest/config.go#L53

**Comment by alculquicondor** [comment]
The plugins are already running in the same binary, why wouldn't it be trusted?

**Comment by Huang-Wei** [comment]
> In that case, I prefer minimal changes: Add a method that returns restclient.Config

I rethink it a bit, and honestly believe this the most viable way. Also it seems unnecessary to expose an extra `DiscoveryClient` as users can [obtain it](https://github.com/kubernetes-sigs/scheduler-plugins/blob/268c1b71a08fb6fa1a5fbcebac85c6fe543622be/pkg/generated/clientset/versioned/clientset.go#L73) from the CRD clientset.

I will go with an implementation to expose the `restclient.Config`. Thanks Aldo.
