### ISSUE TITLE
Process Handle Leak on Windows Nodes

### ISSUE THREAD

**Issue by henrik-m** [kubernetes/kubernetes#96428]
**What happened**:

We have an internal hybrid Kubernetes Cluster which is setup with kubeadm, containing 3 master nodes, 3 linux worker nodes, and 2 windows worker nodes. During the process of migrating internal workloads from our old application platform (Windows Scheduled Tasks) to Kubernetes, we noticed that after a while the windows nodes become unresponsive because of continuously using 100% CPU, if they don't run out of memory first. Apart from the flannel and kube-proxy daemonsets, we currently run only Kubernetes Jobs on these nodes (via TZCronjob).

We noticed the process handle count increasing continually, and with it memory and CPU consumption. This does not correspond to the number of active pods, but rather increases over time with every pod that gets created. Which are a lot since we have jobs that are triggered every minute.

I managed to reproduce the resource leak with a 3 node cluster on the Azure platform, without even creating a single job. I just installed the cluster, activated monitoring for the Guest OS via the Azure facilities and let it sit for a few days. This is what it looks like now:
![image](https://user-images.githubusercontent.com/8522449/98729083-a976c100-239a-11eb-9c64-bac915020505.png)
![image](https://user-images.githubusercontent.com/8522449/98729254-ecd12f80-239a-11eb-96d1-f688e377e82c.png)

This is all that is running on the cluster: 
```
PS C:\WINDOWS\System32> kubectl get pods --all-namespaces
NAMESPACE     NAME                                    READY   STATUS             RESTARTS   AGE
kube-system   coredns-f9fd979d6-gkg25                 1/1     Running            0          11d
kube-system   coredns-f9fd979d6-hwbcd                 1/1     Running            0          11d
kube-system   etcd-kubemaster-01                      1/1     Running            0          11d
kube-system   kube-apiserver-kubemaster-01            1/1     Running            0          11d
kube-system   kube-controller-manager-kubemaster-01   1/1     Running            0          11d
kube-system   kube-flannel-ds-626q7                   1/1     Running            8          11d
kube-system   kube-flannel-ds-kq4pz                   1/1     Running            0          11d
kube-system   kube-flannel-ds-windows-amd64-q4lmm     1/1     Running            0          11d
kube-system   kube-proxy-p42l8                        1/1     Running            0          11d
kube-system   kube-proxy-windows-cxklq                0/1     CrashLoopBackOff   3000       11d
kube-system   kube-proxy-x8msx                        1/1     Running            0          11d
kube-system   kube-scheduler-kubemaster-01            1/1     Running            0          11d
```

I guess the kube-proxy crashloop created enough pods over time so I didn't even need to create a job to see the resource drain.

**What you expected to happen**:

The system resource consumption should correspond to the number of active pods. Instead it continuously grows over time, regardless of the number of currently active pods.

**How to reproduce it (as minimally and precisely as possible)**:

I was able to reproduce this on the Microsoft Azure platform doing the following:

  * Create 3 VMs (I used the size Standard_B2s for each, don't know if it matters)
    * 2 VMs using the Ubuntu 20.04 Server image from Canonical (you probably only need the Kubernetes master for a minimal repro though)
    * 1 VM using the Windows Server 2019 Datacenter image with containers

  * Setup the Kubernetes Cluster with kubeadm using the documentation [here](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/) and [here](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/), designating one of the Linux VMs as master, using an overlay network with flannel as CNI
  * Setup the Azure monitoring to see resource usage of the windows machine
  * Create a Kubernetes Cronjob that continuously creates new pods in short order on the windows node (or, as in my case, send the kube-proxy into a crash loop. I don't know how it got there - at the start it was working properly - but the current error message is "failed to make a new HNSEndpoint: error while ipam.ExecAdd: failed to allocate for range 0: no IP addresses available in range set: 10.244.2.1-10.244.2.254", so I guess specifying a small enough IP range for the container network would be an easy repro)
  * Wait a few days to see the resource drain. I suppose this can be sped up by creating more jobs/pods

**Anything else we need to know?**:

Please tell me if the repro works for you. I can provide more details if it does not. If this is a known issue, I was not able to find it in the issue tracker. If there is a workaround I should try, please tell. The only thing that works for us right now is automatically draining and restarting the Windows VMs every few days.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.3
- Cloud provider or hardware configuration: Microsoft Azure VMs (repro), VMware vSphere ESX VMs (original issue)
- OS (e.g: `cat /etc/os-release`): Windows Server 2019
- Kernel (e.g. `uname -a`):
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): sigwindowstools/flannel:0.12.0
- Others:

**Comment by neolit123** [comment]
seems critical enough to try to fix for 1.20.
/priority important-soon

**Comment by neolit123** [comment]
do you see indication which component (process) has ownership of the handles? i would presume it is the kubelet.

**Comment by ravisantoshgudimetla** [comment]
> how are you setup-ing the container runtime and which one? are you using a named pipe as the "socket"?

You can get this info from the kubelet log file when the kubelet starts:

```unix:///var/run/docker.sock``` or whatever the container runtime is...

**Comment by neolit123** [comment]
i did some debugging, but on an expired Windows Server Evaluation copy that i had while we worked on the kubeadm on Windows support becoming Alpha.

i started a 1.19.x kubelet without even having an apiserver to connect to and started adding and removing static pods in a loop. the static pod has a valid spec and seemed to be created properly. docker ps indicates that the containers are started properly too. after 1 hour of adding removing the same pod i did not see any increase in the number of threads and handles for the kubelet process.

this somewhat tells me that the kubelet and its relation to the container runtime might not be the component leaking handles...or at least for this setup.

> Create a Kubernetes Cronjob that continuously creates new pods in short order on the windows node (or, as in my case, send the kube-proxy into a crash loop. I don't know how it got there - at the start it was working properly - but the current error message is "failed to make a new HNSEndpoint: error while ipam.ExecAdd: failed to allocate for range 0: no IP addresses available in range set: 10.244.2.1-10.244.2.254", so I guess specifying a small enough IP range for the container network would be an easy repro)

`HNSEndpoint` comes from hcsshim, which is used for HCS integration:
https://github.com/microsoft/hcsshim

@henrik-m 
> do you see indication which component (process) has ownership of the handles?

please help us answer this question. if you can obtain a poweshell on a worker node you could type `Get-Process` and see what process has suspicious high number of handles, high memory and CPU. you can also print only certain tabs in the output:

```
Get-Process | select ProcessName, Handles, CPU, PrivateMemorySize
```

**Comment by henrik-m** [comment]
@neolit123 has asked:
```quote
do you see indication which component (process) has ownership of the handles? i would presume it is the kubelet, and you could restart the kubelet to verify that.
```

No, the process leaking handles is not the kubelet itself (which is why restarting it does not yield any results). This is the task manager output from the affected machine:
![pcasvc-handles](https://user-images.githubusercontent.com/8522449/98835657-fad98b80-2440-11eb-8c32-11ac0764c0fa.png)

The description of this service in the services overview is:
```quote
This service provides support for the Program Compatibility Assistant (PCA).  PCA monitors programs installed and run by the user and detects known compatibility problems. If this service is stopped, PCA will not function properly.
```

I've not yet been able to verify if the leak still occurs when this service is disabled. I don't know if any parts of the system would stop to work if it is. It seems to be enabled by default on a stock Windows 2019 installation. The startup type is "manual", but it starts automatically nonetheless.

@neolit123 has asked:
```quote
how are you setup-ing the container runtime and which one? are you using a named pipe as the "socket"?
```

Kubelet startup log from the windows node:
```quote
Log file created at: 2020/11/11 14:58:58
Running on machine: kubewin-01
Binary: Built with gc go1.15.2 for windows/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1111 14:58:58.569051    2896 server.go:411] Version: v1.19.3
I1111 14:58:58.796049    2896 server.go:831] Client rotation is on, will bootstrap in background
I1111 14:58:58.834280    2896 certificate_store.go:130] Loading cert/key pair from "C:\\var\\lib\\kubelet\\pki\\kubelet-client-current.pem".
I1111 14:58:58.843279    2896 dynamic_cafile_content.go:167] Starting client-ca-bundle::C:\var\lib\kubelet\etc\kubernetes\pki\ca.crt
E1111 14:59:00.491963    2896 server.go:748] kubelet needs to run as uid `0`. It is being run as -1
W1111 14:59:00.506077    2896 server.go:756] setting OOM scores is unsupported in this build
I1111 14:59:00.506142    2896 client.go:94] Start docker client with request timeout=2m0s
W1111 14:59:00.506963    2896 docker_service.go:565] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling back to "hairpin-veth"
I1111 14:59:00.506963    2896 docker_service.go:241] Hairpin mode set to "hairpin-veth"
I1111 14:59:00.671013    2896 docker_service.go:256] Docker cri networking managed by cni
I1111 14:59:00.684418    2896 docker_service.go:261] Docker Info: &{ID:UOGE:ZCVA:U4MO:HFBP:UCG5:IIF7:PKEF:RSFW:VRFX:G4LN:5MMU:HQC7 Containers:4 ContainersRunning:4 ContainersPaused:0 ContainersStopped:0 Images:6 Driver:windowsfilter DriverStatus:[[Windows ]] SystemStatus:[] Plugins:{Volume:[local] Network:[ics internal l2bridge l2tunnel nat null overlay private transparent] Authorization:[] Log:[awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog]} MemoryLimit:false SwapLimit:false KernelMemory:false KernelMemoryTCP:false CPUCfsPeriod:false CPUCfsQuota:false CPUShares:false CPUSet:false PidsLimit:false IPv4Forwarding:true BridgeNfIptables:true BridgeNfIP6tables:true Debug:false NFd:-1 OomKillDisable:false NGoroutines:42 SystemTime:2020-11-11T14:59:00.6710138Z LoggingDriver:json-file CgroupDriver: NEventsListener:0 KernelVersion:10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434) OperatingSystem:Windows Server 2019 Datacenter Version 1809 (OS Build 17763.1577) OSType:windows Architecture:x86_64 IndexServerAddress:https://index.docker.io/v1/ RegistryConfig:0xc00007fa40 NCPU:2 MemTotal:4294496256 GenericResources:[] DockerRootDir:C:\ProgramData\docker HTTPProxy: HTTPSProxy: NoProxy: Name:kubewin-01 Labels:[] ExperimentalBuild:false ServerVersion:19.03.12 ClusterStore: ClusterAdvertise: Runtimes:map[] DefaultRuntime: Swarm:{NodeID: NodeAddr: LocalNodeState:inactive ControlAvailable:false Error: RemoteManagers:[] Nodes:0 Managers:0 Cluster:<nil> Warnings:[]} LiveRestoreEnabled:false Isolation:process InitBinary: ContainerdCommit:{ID: Expected:} RuncCommit:{ID: Expected:} InitCommit:{ID: Expected:} SecurityOptions:[] ProductLicense: Warnings:[]}
W1111 14:59:00.684418    2896 docker_service.go:266] No cgroup driver is set in Docker
W1111 14:59:00.684418    2896 docker_service.go:267] Falling back to use the default driver: "cgroupfs"
I1111 14:59:00.684418    2896 docker_service.go:274] Setting cgroupDriver to cgroupfs
W1111 14:59:00.694209    2896 docker_service.go:429] initialization error: unable to list values under registry key "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Virtualization\\Containers\\CredentialSpecs": Access is denied.
I1111 14:59:00.767983    2896 remote_runtime.go:59] parsed scheme: ""
I1111 14:59:00.767983    2896 remote_runtime.go:59] scheme "" not registered, fallback to default scheme
I1111 14:59:00.767983    2896 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{//./pipe/dockershim  <nil> 0 <nil>}] <nil> <nil>}
I1111 14:59:00.767983    2896 clientconn.go:948] ClientConn switching balancer to "pick_first"
I1111 14:59:00.767983    2896 remote_image.go:50] parsed scheme: ""
I1111 14:59:00.767983    2896 remote_image.go:50] scheme "" not registered, fallback to default scheme
I1111 14:59:00.767983    2896 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{//./pipe/dockershim  <nil> 0 <nil>}] <nil> <nil>}
I1111 14:59:00.767983    2896 clientconn.go:948] ClientConn switching balancer to "pick_first"
I1111 14:59:00.767983    2896 kubelet.go:261] Adding pod path: C:\var\lib\kubelet\etc\kubernetes\manifests
E1111 14:59:00.767983    2896 file_unsupported.go:28] Watching source file is unsupported in this build
I1111 14:59:00.794980    2896 kubelet.go:273] Watching apiserver
E1111 14:59:00.810977    2896 file.go:98] Unable to read config path "C:\\var\\lib\\kubelet\\etc\\kubernetes\\manifests": path does not exist, ignoring
W1111 14:59:00.849119    2896 iptables.go:209] Error checking iptables version, assuming version at least 1.4.11: executable file not found in %PATH%
I1111 14:59:01.242708    2896 state_mem.go:36] [cpumanager] initializing new in-memory state store
I1111 14:59:01.242708    2896 fake_topology_manager.go:29] [fake topologymanager] NewFakeManager
E1111 14:59:01.452748    2896 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
I1111 14:59:02.492761    2896 kuberuntime_manager.go:214] Container runtime docker initialized, version: 19.03.12, apiVersion: 1.40.0
E1111 14:59:02.502143    2896 server.go:1136] Failed to set rlimit on max file handles: SetRLimit unsupported in this platform
I1111 14:59:02.502766    2896 server.go:1147] Started kubelet
I1111 14:59:02.512002    2896 fs_resource_analyzer.go:64] Starting FS ResourceAnalyzer
I1111 14:59:02.512002    2896 status_manager.go:158] Starting to sync pod status with apiserver
I1111 14:59:02.512002    2896 kubelet.go:1741] Starting kubelet main sync loop.
E1111 14:59:02.512002    2896 kubelet.go:1765] skipping pod synchronization - [container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet to be successful]
I1111 14:59:02.512764    2896 server.go:152] Starting to listen on 0.0.0.0:10250
E1111 14:59:02.522763    2896 processstarttime.go:43] Could not get process start time, could not read /proc: CreateFile /proc: The system cannot find the file specified.
I1111 14:59:02.531912    2896 server.go:424] Adding debug handlers to kubelet server.
I1111 14:59:02.512764    2896 volume_manager.go:265] Starting Kubelet Volume Manager
I1111 14:59:02.512764    2896 desired_state_of_world_populator.go:139] Desired state populator starts to run
I1111 14:59:02.561550    2896 plugin_manager.go:114] Starting Kubelet Plugin Manager
I1111 14:59:02.620957    2896 kuberuntime_manager.go:981] updating runtime config through cri with podcidr 10.244.2.0/24
I1111 14:59:02.630615    2896 docker_service.go:357] docker cri received runtime config &RuntimeConfig{NetworkConfig:&NetworkConfig{PodCidr:10.244.2.0/24,},}
I1111 14:59:02.651762    2896 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "host" (UniqueName: "kubernetes.io/host-path/4af20751-bdee-4e47-8d91-faa2681c187a-host") pod "kube-flannel-ds-windows-amd64-q4lmm" (UID: "4af20751-bdee-4e47-8d91-faa2681c187a") 
I1111 14:59:02.651762    2896 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "cni" (UniqueName: "kubernetes.io/host-path/4af20751-bdee-4e47-8d91-faa2681c187a-cni") pod "kube-flannel-ds-windows-amd64-q4lmm" (UID: "4af20751-bdee-4e47-8d91-faa2681c187a") 
I1111 14:59:02.659920    2896 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "flannel-cfg" (UniqueName: "kubernetes.io/configmap/4af20751-bdee-4e47-8d91-faa2681c187a-flannel-cfg") pod "kube-flannel-ds-windows-amd64-q4lmm" (UID: "4af20751-bdee-4e47-8d91-faa2681c187a") 
I1111 14:59:02.659920    2896 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "flannel-windows-cfg" (UniqueName: "kubernetes.io/configmap/4af20751-bdee-4e47-8d91-faa2681c187a-flannel-windows-cfg") pod "kube-flannel-ds-windows-amd64-q4lmm" (UID: "4af20751-bdee-4e47-8d91-faa2681c187a") 
I1111 14:59:02.659920    2896 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "kube-proxy" (UniqueName: "kubernetes.io/configmap/4af20751-bdee-4e47-8d91-faa2681c187a-kube-proxy") pod "kube-flannel-ds-windows-amd64-q4lmm" (UID: "4af20751-bdee-4e47-8d91-faa2681c187a") 
I1111 14:59:02.659984    2896 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "kubeadm-config" (UniqueName: "kubernetes.io/configmap/4af20751-bdee-4e47-8d91-faa2681c187a-kubeadm-config") pod "kube-flannel-ds-windows-amd64-q4lmm" (UID: "4af20751-bdee-4e47-8d91-faa2681c187a") 
I1111 14:59:02.659984    2896 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "wins" (UniqueName: "kubernetes.io/host-path/4af20751-bdee-4e47-8d91-faa2681c187a-wins") pod "kube-flannel-ds-windows-amd64-q4lmm" (UID: "4af20751-bdee-4e47-8d91-faa2681c187a") 
I1111 14:59:02.659984    2896 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "flannel-token-58wfb" (UniqueName: "kubernetes.io/secret/4af20751-bdee-4e47-8d91-faa2681c187a-flannel-token-58wfb") pod "kube-flannel-ds-windows-amd64-q4lmm" (UID: "4af20751-bdee-4e47-8d91-faa2681c187a") 
I1111 14:59:02.659984    2896 reconciler.go:157] Reconciler: start to sync state
I1111 14:59:02.661763    2896 kubelet_network.go:77] Setting Pod CIDR:  -> 10.244.2.0/24
I1111 14:59:02.740821    2896 kubelet_node_status.go:70] Attempting to register node kubewin-01
I1111 14:59:02.827762    2896 kubelet_node_status.go:108] Node kubewin-01 was previously registered
I1111 14:59:02.827762    2896 kubelet_node_status.go:73] Successfully registered node kubewin-01
```

Is the information you seek in there? I really just created a new Windows 2019 datacenter VM without any modifications of my own and joined it to the Cluster exactly as described in the [docs](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/).

I guess Server Core machines may be unaffected if they lack the Windows services that cause the problems.

**Comment by neolit123** [comment]
> This service provides support for the Program Compatibility Assistant (PCA).  PCA monitors programs installed and run by the user and detects known compatibility problems. If this service is stopped, PCA will not function properly.

> I've not yet been able to verify if the leak still occurs when this service is disabled. I don't know if any parts of the system would stop to work if it is.

my non-expert evaluation is that PCA is not system-critical for Kubernetes to operate:
https://docs.microsoft.com/en-us/previous-versions/bb756937(v=msdn.10)?redirectedfrom=MSDN

you can turn it off and see how that goes.
https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.ApplicationCompatibility::AppCompatTurnOffProgramCompatibilityAssistant_2

the problem could be in PCA itself:
https://twitter.com/BruceDawson0xB/status/963476981273604096
https://twitter.com/appcompatguy/status/963837005795942401

SIG Windows members from Microsoft should be able to provide more insight on this topic.

**Comment by ravisantoshgudimetla** [comment]
cc @jsturtevant @marosset @michmike

**Comment by marosset** [comment]
cc @immuzz

**Comment by neolit123** [comment]
will clear the milestone here, please readjust if needed.
/milestone clear

**Comment by henrik-m** [comment]
We had another pretty extreme case of one of our Windows nodes going nuts out of nowhere yesterday. In hope this might help you get to the bottom of this, I am providing a few screenshot from the VM before it was rebooted and the kubelet log from yesterday when it happened.

This is what we saw in out monitoring system:
![image](https://user-images.githubusercontent.com/8522449/99230121-34b6e300-27ef-11eb-9194-26afd0f01e13.png)

Top processes on the node itself (before rebooting):
![image](https://user-images.githubusercontent.com/8522449/99230870-21f0de00-27f0-11eb-89ce-1c4f0441eb5f.png)

CPU utilization almost entirely by the WMI provider (I guess because of the large number of process handles?), even after kubelet service was already stopped:
![image](https://user-images.githubusercontent.com/8522449/99231051-60869880-27f0-11eb-8fa0-472c07095e66.png)

And last but not least, the kubelet log from the day's reboot at 01:00 am until the log rotation happened: 
[2020-11-15-kubewin-01-kubelet-log.txt](https://github.com/kubernetes/kubernetes/files/5545122/2020-11-15-kubewin-01-kubelet-log.txt)

The errors that correlate to the resource drain start appearing at 18:49 and then continue on for the rest of the day and the next until reboot:
```quote
E1115 18:49:39.302122    5928 docker_stats_windows.go:42] Error opening container (stats will be missing) '77f1deee380ef8b473b527f86ab27bc20b10b089e7d15ae59590f1f1204e59dc': hcsshim::System::Properties 77f1deee380ef8b473b527f86ab27bc20b10b089e7d15ae59590f1f1204e59dc: The requested virtual machine or container operation is not valid in the current state.
```

If you need additional logs and information, I will be happy to provide it.

**Comment by marosset** [comment]
Can someone extract some ETW events and see if anything in there looks interested?

https://github.com/Azure/aks-engine/blob/f5bdb8b94cc62b03480e7430537d122828e21c27/scripts/collect-windows-logs.ps1#L36-L50

would be a good starting point.

Also, is there fairly easy to repro?

**Comment by marosset** [comment]
I can start looking into this but probably not until after Thanksgiving...

**Comment by henrik-m** [comment]
> Can someone extract some ETW events and see if anything in there looks interestings?
> 
> https://github.com/Azure/aks-engine/blob/f5bdb8b94cc62b03480e7430537d122828e21c27/scripts/collect-windows-logs.ps1#L36-L50
> 
> would be a good starting point.

@marosset I ran the script on a machine that is emitting the described behaviour. Since the data is from an intranet cluster I am not comfortable posting the logs into the public domain though. Is there an email address where I can send you a download link to?

System info:
We switched to Windows Server 2019 Core in the meantime and the resource leaks are a bit slower, but still apparent. This is the output from our dashboards for the affected machine from today (so it is from the same timeframe as the collected logs):
![image](https://user-images.githubusercontent.com/8522449/103876359-d3ffa480-50d3-11eb-9e0c-d8f5a1b36f3f.png)

A machine restart always frees up the accumulated handlers, memory and disk space and the cycle starts anew.

Workload info:
Most of our workloads are Kubernetes Cronjobs that load a custom docker image built with the following Dockerfile:
```Dockerfile
FROM mcr.microsoft.com/dotnet/framework/runtime:4.7.2-windowsservercore-ltsc2019

ADD company-root.cer c:/

RUN powershell -Command Import-Certificate -FilePath c:/company-root.cer -CertStoreLocation 'Cert:/LocalMachine/Root/'

RUN powershell -Command Set-Culture -CultureInfo "de-DE"

ENTRYPOINT [ "powershell" ]

CMD [ "C:/startup.ps1" ]

ADD startup.ps1 c:/
```

The ```startup.ps1``` powershell script looks like this:
```powershell
$env:ERRORLEVEL = 0

Function MapDrive(
    [Parameter(Mandatory=$true)]
    $Server
) {
    $retryCount = 0
    $maxRetries = 10
    $waitInterval = 10
    $secondsWaited = 0
    do {
        net use \\$Server $env:NETSHARE_PW /USER:$env:NETSHARE_USER
        if($LASTEXITCODE -eq 0) {
            Write-Host "Mapped network share $Server (after $retryCount retries and ${secondsWaited}s)."
            return $true
        } else {
            $retryCount += 1
            Start-Sleep -Seconds $waitInterval
            $secondsWaited += $waitInterval
        }
    }
    until ($retryCount -eq $maxRetries)

    Write-Host "There is no connection to server $Server after ${secondsWaited}s."
    Write-Host "The network share \\$Server is not available."
	$env:ERRORLEVEL = 2
    return $false
}

Function Subst {
    New-PSDrive -Name "L" -PSProvider FileSystem -Root \\$env:NETSHARE_SERVER\L

    cmd /c "MKLINK /D C:\TaskPlanerTools \\%NETSHARE_SERVER%\TaskPlanerTools"
}

Function RunTask {
    $expression = $env:TASK.Split()
    $command = $expression[0]
    $arguments = ($expression | select -Skip 1)

    try {
	    & .\$command $arguments
	}
	catch {
	    Write-Host $_
	    exit 1
	}
    $env:ERRORLEVEL = $LASTEXITCODE
}

$networkshares = $env:NETWORKSHARES.Split()

foreach($networkshare in $networkshares) {
	    if((MapDrive -Server $networkshare) -eq $false) {
		    Exit $env:ERRORLEVEL
	    }
}

if((MapDrive -Server $env:NETSHARE_SERVER) -eq $true) {
    Subst
    Set-Location "C:\TaskPlanerTools\$env:TASKDIR"
    RunTask
}
Exit $env:ERRORLEVEL
```

Story behind it: We are in the process of moving our Windows scheduled tasks that reside on a dedicated server to Kubernetes. So we use a network share to access the individual binary and run it on a container in the cluster. There are over a hundred tasks thet get executed on a daily basis (some of them every few minutes). Most of them are .NET binaries (hence the base image). We have a similar image for pure Powershell workloads (different base image).

So maybe the resource leaks can be reproduced with this kind of workload. Unfortunately there is a bit of setup required, since a separate server with an accessible network share must be configured.

**Comment by henrik-m** [comment]
We are still employing a workaround for this (frequent automatic node reboots). Is there anything else I can do to help move this forward? My last post from Jan 7th did not get a response...

/remove-lifecycle rotten
