### ISSUE TITLE
`kubectl get <resource>.<group>` invalidates discovery

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#96430]
**What happened**:

Ran the following on a cluster with many custom resources installed:

```
kubectl api-resources --verbs=list --namespaced -o name | \
  xargs -n 1 kubectl get --show-kind --ignore-not-found -n my-namespace
```

The command took longer to run than expected. Adding trace logging with `--v=6`, the `kubectl get` call was invalidating discovery data on every invocation, meaning every `kubectl get` call fully re-fetched discovery data.

This can be reproduced by making a `kubectl get` call with a single `<resource>.<group>` argument as output by `api-resources -o name`:

```
... install a CRD that defines a `foos` resource in the `example.com` API group ...

# fetch to ensure discovery data including the new custom resource is cached
kubectl get foos.example.com

# refetch and observe discovery data is invalidated
kubectl get foos.example.com --v=6
I1109 15:06:06.874348   74544 loader.go:375] Config loaded from file:  /Users/liggitt/go/src/k8s.io/kubernetes/_output/certs/admin.kubeconfig
I1109 15:06:06.879882   74544 discovery.go:214] Invalidating discovery information
I1109 15:06:06.889069   74544 round_trippers.go:444] GET https://localhost:6443/api?timeout=32s 200 OK in 9 milliseconds
I1109 15:06:06.912802   74544 round_trippers.go:444] GET https://localhost:6443/apis?timeout=32s 200 OK in 1 milliseconds
I1109 15:06:06.939306   74544 round_trippers.go:444] GET https://localhost:6443/apis/certificates.k8s.io/v1beta1?timeout=32s 200 OK in 2 milliseconds
I1109 15:06:06.940452   74544 round_trippers.go:444] GET https://localhost:6443/apis/authorization.k8s.io/v1?timeout=32s 200 OK in 3 milliseconds
...
```

**What you expected to happen**:

Cached discovery data to be used

**Comment by lingsamuel** [comment]
The reason seems to be we falsely parse, for example, `endpointslice.discovery.k8s.io` to `k8s.io/discovery, Resource=endpointslice`.

https://github.com/kubernetes/kubernetes/blob/307278029cbf69bc35a7795594d970b7781de2b8/staging/src/k8s.io/apimachinery/pkg/runtime/schema/group_version.go#L29-L37

So the match failed, `err != nil` is true, triggered reset here.

https://github.com/kubernetes/kubernetes/blob/307278029cbf69bc35a7795594d970b7781de2b8/staging/src/k8s.io/client-go/restmapper/discovery.go#L230-L231

![image](https://user-images.githubusercontent.com/14567045/98931711-55deb180-2519-11eb-90c8-f960855627a5.png)

Note that the second param is `endpointslice.v1beta1.discovery.k8s.io`.

**Comment by liggitt** [comment]
> We could change the parse function per [the doc](https://kubernetes.io/docs/reference/using-api/#api-versioning) to fix this issue.

I think the parse function is doing the right thing ... both the `<resource>.<group>` and `<resource>.<version>.<group>` forms are allowed, and the parse function returns both.

The code that uses those return values to locate a resource is triggering cache invalidation when the first check fails. The rest mapper interface doesn't have a "KindForButDoNotInvalidateIfNotFound" method, which is what we really want when we're calling from mappingFor (we want to see if fullySpecifiedGVR or groupResource.WithVersion("") resolve, and only if neither do, then invalidate

**Comment by lingsamuel** [comment]
I think we shouldn't keep a wrong parsed result if we can make it right.

**Comment by liggitt** [comment]
> I think we shouldn't keep a wrong parsed result if we can make it right.

it's not wrong. there are two supported ways to parse a.b.c, and we have to try both:

* resource=a, group=b.c
* resource=a, version=b, group=c

**Comment by lingsamuel** [comment]
I know this. But in this situation (`endpointslice.discovery.k8s.io`), it treats `discovery` as version.

**Comment by liggitt** [comment]
> in this situation (`endpointslice.discovery.k8s.io`), it treats `discovery` as version.

it checks both, which is expected:

```
 	if fullySpecifiedGVR != nil { 
 		gvk, _ = restMapper.KindFor(*fullySpecifiedGVR) 
 	} 
 	if gvk.Empty() { 
 		gvk, _ = restMapper.KindFor(groupResource.WithVersion("")) 
 	} 
```

what is not expected is that the first failed lookup invalidates cached discovery so the second triggers a full re-fetch

**Comment by lingsamuel** [comment]
Why we have to call KindFor twice if we could done the task once?

**Comment by liggitt** [comment]
because we don't know whether `a.b.c.d` represents `resource=a, version=b, group=c.d` or `resource=a, group=b.c.d`, and calling `KindFor` is currently how we determine which is correct.

Resolving this will likely require a new signature or mechanism for interrogating the restmapper

**Comment by lingsamuel** [comment]
We already have a [version definition](https://kubernetes.io/docs/reference/using-api/#api-versioning).

> Alpha: The version names contain alpha (for example, v1alpha1).
Beta: The version names contain beta (for example, v2beta3).
Stable: The version name is vX where X is an integer.

**Comment by liggitt** [comment]
that's a convention, but is not guaranteed:

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: weirds.example.com
spec:
  group: example.com
  scope: Namespaced
  versions:
  - name: mylevel1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
  - name: mylevel2
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
  names:
    singular: weird
    plural: weirds
    kind: Weird
    listKind: WeirdList
---
kind: Weird
apiVersion: example.com/mylevel1
metadata:
  name: test
```

```
kubectl get weirds.mylevel1.example.com
NAME   AGE
test   15s
```

if the a.b.c.d matches a group, version, and kind, we should prefer that since it is fully qualified

**Comment by lingsamuel** [comment]
Could you provide advice on how to resolve this?
IMO I will add a pair enable/disable function to `CachedDiscoveryInterface` to control how function `Fresh` works, instead of add a `KindForButDoNotInvalidateIfNotFound` because we may need many `XXXButNotInvalidation` functions further.

**Comment by liggitt** [comment]
I'm not sure off the top of my head... @deads2k might have some advice

**Comment by deads2k** [comment]
> I'm not sure off the top of my head... @deads2k might have some advice

We added etags to open-api, what if we did similar to discovery to inform the caching?  Do etags allow us arbitrarily set a different etag even when content has not changed?  If we could do that, then we could have a discovery rule that says etags are updated whenever a "lower" discovery doc changes.  So a version discovery change (adding a resource) would ripple out to update etags for the group, and for the list of apis.  This would allow a clever REST mapper to only traverse requests as far the last change to discovery.  If nothing changed, then only two requests would be needed (/api and /apis).

Caveat: I'm not sure if the etag spec allows arbitrary etag changes.

**Comment by lingsamuel** [comment]
Maybe related: #44957

**Comment by howardjohn** [comment]
Not sure if this is the same, but it looks like `kubectl get <category>` (CRDs) also invalidates

**Comment by ardaguclu** [comment]
We have switched to aggregated discovery in addition to the etags. I think, we can close this issue as done.

**Comment by ardaguclu** [comment]
/close
with respect to my above comment ^
