### ISSUE TITLE
Make runtime.NewFramework accept KubeSchedulerProfile

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#96436]
The signature of `runtime.NewFramework` accepts `config.Plugins` and `[]config.PluginConfig`, and separate (via an Option), the scheduler name. It makes sense to just accept `config.KubeSchedulerProfile` instead.

This is a follow up to #95158

/kind cleanup
/sig scheduling
/triage accepted

Too late for doing this in 1.20, but we can do it for 1.21

**Comment by alculquicondor** [comment]
@tangwz FYI

**Comment by alculquicondor** [comment]
FYI on related PR #96438

**Comment by alculquicondor** [comment]
Actually
/remove-triage

@ahg-g  would it be enough to do this AND update cluster autoscaler to use the new signature?

**Comment by tangwz** [comment]
@alculquicondor This issue remove triage, should I still develop it?

**Comment by alculquicondor** [comment]
I'm still awaiting for an answer to https://github.com/kubernetes/kubernetes/issues/96436#issuecomment-725056542

**Comment by alculquicondor** [comment]
/unassign @tangwz 
as we haven't heard back.
