### ISSUE TITLE
DefaultPreemption plugin is not created when Policy API is used?

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#96437]
The test is not expecting any DefaultPreemption plugin:

https://github.com/kubernetes/kubernetes/blob/8ed6ca58bc29c341e69efe6a66deedf77db196db/pkg/scheduler/factory_test.go#L143

/sig scheduling
/assign @Huang-Wei

**Comment by tangwz** [comment]
May I give a try when this issue is accepted ?

**Comment by alculquicondor** [comment]
it might be urgent, so better leave it to @Huang-Wei

**Comment by Huang-Wei** [comment]
I will give a fix later.

/assign
