### ISSUE TITLE
[Failing Test] ci-kubernetes-e2e-gci-gce-scalability keeps leaking a resource (compute disk)

### ISSUE THREAD

**Issue by thejoycekung** [kubernetes/kubernetes#96431]
**Which jobs are failing**:
`gce-cos-master-scalability-100` / `ci-kubernetes-e2e-gci-gce-scalability`

**Which test(s) are failing**:
`diffResources`

**Since when has it been failing**:
d2fd46712...0cba30d89 (between 06:49 PST and 08:20 PST Nov 9)

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-scalability-100

**Reason for failure**:
Unsure, but here's where it went wrong:
```
W1109 17:06:35.681] 2020/11/09 17:06:35 process.go:153: Running: diff -sw -U0 -F^\[.*\]$ /workspace/_artifacts/gcp-resources-before.txt /workspace/_artifacts/gcp-resources-after.txt
W1109 17:06:35.682] 2020/11/09 17:06:35 process.go:155: Step 'diff -sw -U0 -F^\[.*\]$ /workspace/_artifacts/gcp-resources-before.txt /workspace/_artifacts/gcp-resources-after.txt' finished in 1.560887ms
W1109 17:06:35.683] 2020/11/09 17:06:35 process.go:96: Saved XML output to /workspace/_artifacts/junit_runner.xml.
W1109 17:06:35.695] 2020/11/09 17:06:35 main.go:316: Something went wrong: encountered 1 errors: [Error: 2 leaked resources
W1109 17:06:35.696] +NAME                                                      LOCATION    LOCATION_SCOPE  SIZE_GB  TYPE    STATUS
W1109 17:06:35.696] +e2e-big-dynamic-pvc-f50aa2f5-a779-4c9e-aede-4150aace06fe  us-east1-b  zone            10       pd-ssd  READY]
```
Also the log says `2 leaked resources` but it only lists one (I can also only find one in the `before`/`after` files).

Spyglass link for reference: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1325835563500048384

**Anything else we need to know**:
/sig scalability
/cc @kubernetes/ci-signal 
/priority important/soon

**Comment by RobertKielty** [comment]
Triage link on  **Error: 2 leaked resources** https://storage.googleapis.com/k8s-gubernator/triage/index.html?text=Error%3A%202%20leaked%20resources

**Comment by RobertKielty** [comment]
Related issue #38680 

@jingxu97 would you be able to take a look at this?

**Comment by wojtek-t** [comment]
Debuged in https://github.com/kubernetes/kubernetes/issues/96509

**Comment by thejoycekung** [comment]
Closing since TestGrid seems to be green now
