### ISSUE TITLE
kube-proxy not update ipvs rules when My  pod infomation change

### ISSUE THREAD

**Issue by zhutongcloud** [kubernetes/kubernetes#96449]
**What happened**:
I open k8s ipv4/IPv6,Old ipv6 ipvs rule still exist  when my pod chanaged,cause curl service failed;but ipv4 ipvs rules can right now update.
**What you expected to happen**:
I wish kube-proxy can right now update ipvs rules
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.0
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): Centos7 
- Kernel (e.g. `uname -a`):5.9.6-1.el7.elrepo.x86_64
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): calico
- Others:
[root@master ~]# kubectl get ep
NAME            ENDPOINTS                             AGE
kubernetes      6.6.6.18:6443                         32m
nginx           [fc00::db4d:f2f2:402d:3b99:a182]:80   21m
nginx-service   10.244.219.67:80                      19m
[root@master ~]# ipvsadm -L
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  master:https rr
  -> master:sun-sr-https          Masq    1      0          0
TCP  master:domain rr
  -> 10.244.219.65:domain         Masq    1      0          0
  -> 10.244.219.66:domain         Masq    1      0          0
TCP  master:9153 rr
  -> 10.244.219.65:9153           Masq    1      0          0
  -> 10.244.219.66:9153           Masq    1      0          0
TCP  master:http rr
  -> 10.244.219.67:http           Masq    1      0          0
UDP  master:domain rr
  -> 10.244.219.65:domain         Masq    1      0          0
  -> 10.244.219.66:domain         Masq    1      0          0
TCP  [fd00::7598]:http rr
  -> [fc00::db4d:f2f2:402d:3b99:a182]:http Masq    1      0          0
  -> [fc00::db4d:f2f2:402d:3b99:a183]:http Masq    1      0          0
  -> [fc00::db4d:f2f2:402d:3b99:a184]:http Masq    1      0          0

**Comment by neolit123** [comment]
> Kubernetes version (use kubectl version): 1.17.0

hi, please note this version of k8s will be out of support with the release of 1.20 in december.

kube-proxy is owned by SIG network:
/sig network

**Comment by andrewsykim** [comment]
ipvs proxier did not really support IPv6 before v1.18 I believe. @zhutongcloud can you share the logs from kube-proxy please?

**Comment by andrewsykim** [comment]
Circling back to this, there's a known bug with IPv6 + CentOS 7 on IPVS that was not fixed until v1.18.

**Comment by andrewsykim** [comment]
I'm also curious how your kernel version `5.9.6-1.el7.elrepo.x86_64` on CentOS 7, isn't CentOS 7 typically on 3.10?

**Comment by aojea** [comment]
> I'm also curious how your kernel version 5.9.6-1.el7.elrepo.x86_64 on CentOS 7, isn't CentOS 7 typically on 3.10?

http://elrepo.org/tiki/HomePage :)

**Comment by zhutongcloud** [comment]
> Circling back to this, there's a known bug with IPv6 + CentOS 7 on IPVS that was not fixed until v1.18.

yeah, I also find there's  a known bug with IPv6 + Centos 7 on IPvs,so I  now test IPv6 function on v1.19.0

**Comment by thockin** [comment]
Should we close this, then?

**Comment by andrewsykim** [comment]
@zhutongcloud feel free to re-open if you run into issues on v1.19

/close
