### ISSUE TITLE
In IPv4/IPv6 dual stack cluster, kube-proxy use ip6tables-restore restore rules failed and ipv6 fails due to Couldn't load target `KUBE-MARK-DROP`

### ISSUE THREAD

**Issue by daniel-ke** [kubernetes/kubernetes#96468]
**What happened**:
In an IPV4/IPV6 dual Stack cluster some **type: NodePort/ipFamily: IPV6** service nodePorts are not created by the kube-proxy pods, resulting in us being unable to use IPV6 with externalTrafficPolicy: Local to track connecting IPv6 source IP's, which our use case requires.
( cluster : - pseudo HA config with 2 masters and one worker ) 

checking the kube-proxy logs for all 3 nodes we repeatedly see the error

 proxier.go:1570] Failed to execute iptables-restore: exit status 2 (ip6tables-restore v1.8.3 (legacy): Couldn't load target `KUBE-MARK-DROP':No such file or directory

e.g.

...
I1110 22:35:32.340339       1 shared_informer.go:247] Caches are synced for service config 
E1110 22:50:28.892923       1 proxier.go:1570] Failed to execute iptables-restore: exit status 2 (ip6tables-restore v1.8.3 (legacy): Couldn't load target `KUBE-MARK-DROP':No such file or directory

Error occurred at line: 269
Try `ip6tables-restore -h' or 'ip6tables-restore --help' for more information.
)
I1110 22:50:28.893183       1 proxier.go:850] Sync failed; retrying in 30s
E1110 22:50:58.937102       1 proxier.go:1570] Failed to execute iptables-restore: exit status 2 (ip6tables-restore v1.8.3 (legacy): Couldn't load target `KUBE-MARK-DROP':No such file or directory

Error occurred at line: 269
Try `ip6tables-restore -h' or 'ip6tables-restore --help' for more information.
)

using netstat -an it was clear particular tcp6 ports were not listening.

When we changed to **externalTrafficPolicy: Cluster** for all IPV6 services the nodePorts were created, but we then lost the source IP tracking of course. 
netstat -an showed that the tcp6 ports were now listening.

This issue consistently occurred with **externalTrafficPolicy: Local** , but not necessarily with the same services.

We have an equivalent set of NodePort IPV4 services which all behave correctly (equivalent in all but ipFamily: IPv4 )

I assume this may be related to [#73658](https://github.com/kubernetes/kubernetes/issues/73658)

**What you expected to happen**:

all IPV6 nodePorts should be available and accessible with source IP tracked. In this case  to allow an external load balancer to access those ports.
The equivalent IPV4 nodePort services work as expected.

**How to reproduce it (as minimally and precisely as possible)**:

create a set of nodePort services ipFamily: IPv6 services (assuming appropriate backing deployment/daemonset/pods )  with setting externalTrafficPolicy: Local 

In this case 5 services were create, two of which have 80 exposed nodePorts the rest a single nodePort

**Anything else we need to know?**:
[#73658](https://github.com/kubernetes/kubernetes/issues/73658)

Not as critical but something we have noticed which affects how we configure load balancer health checks - when there is no endpoint on a node, the IPV6 nodePort does **not** drop the packet on connection, it ACCEPTs the connection but does nothing further with it, whereas the IPV4 drops the packets which we can easily detect via the load balancer with a tcp 'half open' check.  

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.19.2
- Cloud provider or hardware configuration:
VMWare
- OS (e.g: `cat /etc/os-release`):
Red Hat Enterprise Linux Server release 7.8 (Maipo)
- Kernel (e.g. `uname -a`):
Linux <hostname> 3.10.0-1127.10.1.el7.x86_64 #1 SMP Tue May 26 15:05:43 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
kubadm v1.19.2 kubectl v1.19.2
- Network plugin and version (if this is a network-related bug):
calico v3.16.3
- Others:
None.

**Comment by daniel-ke** [comment]
It's basically missing all the KUBE-FIREWALL/KUBE-MARK-DROP rules that the ipv4 iptables has.

If we manually add the same rules to ip6tables as below, it works correctly, including correctly dropping packets if a pod is not on a node in "Local" service mode, and kube-proxy stops logging errors - until reboot when the rules are lost

`ip6tables -N KUBE-FIREWALL;ip6tables -A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP;ip6tables -A KUBE-FIREWALL ! -s ::1/128 -d ::1/128 -m comment --comment "block incoming localnet connections" -m conntrack ! --ctstate RELATED,ESTABLISHED,DNAT -j DROP;ip6tables -A INPUT -j KUBE-FIREWALL;ip6tables -A OUTPUT -j KUBE-FIREWALL; ip6tables -t nat -N KUBE-MARK-DROP;ip6tables -t nat -A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000`

**Comment by aojea** [comment]
/close
This was fixed by https://github.com/kubernetes/kubernetes/pull/94474
It will be available in 1.20, not likely to be backported to 1.19 since dual-stack is still alpha
