### ISSUE TITLE
[Failing Test] [k8s.io] Probing container should be restarted with a docker exec liveness probe with timeout [ci-kubernetes-e2e-ubuntu-gce]

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#96463]
**Which jobs are failing**:

`gce-ubuntu-master-default (ci-kubernetes-e2e-ubuntu-gce)`

**Which test(s) are failing**:

`[k8s.io] Probing container should be restarted with a docker exec liveness probe with timeout`

**Since when has it been failing**:

`11-09-20 18:43 PST`

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-informing#gce-ubuntu-master-default

**Reason for failure**:

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/container_probe.go:214
Nov 10 03:11:15.973: pod container-probe-9373/busybox-723ec292-164c-46d1-b47b-b0761bee2121 - expected number of restarts: 1, found restarts: 0
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/container_probe.go:223
```

**Anything else we need to know**:

Test flipped to failing and has consistently been failing since.
Commit failure started on: https://github.com/kubernetes/kubernetes/commits/734889ed8
Looks like it is related to this PR: https://github.com/kubernetes/kubernetes/pull/94115

/sig node
/priority critical-urgent
/cc @kubernetes/ci-signal 
/assign @hasheddan 
/milestone v1.20

**Comment by hasheddan** [comment]
@oomichi @andrewsykim hey folks, noticed this was discussed on https://github.com/kubernetes/kubernetes/pull/94115. Interestingly, the enabled test is passing on [COS nodes](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default) and [Ubuntu Containerd nodes](https://testgrid.k8s.io/sig-release-master-blocking#gce-ubuntu-master-containerd), but not on Ubuntu. I would be surprised if this is actually due to the different OS / container runtime, but I noticed that the Ubuntu job is using a different version marker than others (`ci/latest` vs `ci/latest-fast`), which would be more likely to be the causing the divergence IMO (although I would expect the `ci/latest` to catch up, but there has been some modifications to version marker behavior semi-recently, so this could be related. I am thinking about bumping the Ubuntu jobs to you latest-fast and see if that changes anything. I realize this is out of the purview of the PR, but just wanted to see if y'all had any thoughts?

/cc @justaugustus @saschagrunert

**Comment by andrewsykim** [comment]
Is the containerd version the same across those versions?

**Comment by andrewsykim** [comment]
FYI @SergeyKanzhelev

**Comment by hasheddan** [comment]
@andrewsykim let me double check on that

**Comment by justaugustus** [comment]
> but I noticed that the Ubuntu job is using a different version marker than others (`ci/latest` vs `ci/latest-fast`), which would be more likely to be the causing the divergence IMO (although I would expect the `ci/latest` to catch up, but there has been some modifications to version marker behavior semi-recently, so this could be related. I am thinking about bumping the Ubuntu jobs to you latest-fast and see if that changes anything.

Opened https://github.com/kubernetes/test-infra/pull/19920 for this.

**Comment by hasheddan** [comment]
@andrewsykim @justaugustus did a little digging and see that the Ubuntu job is using Docker v19.3.13 ([logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce/1326479434944876544/build-log.txt)):
```
,NodeInfo:NodeSystemInfo{MachineID:691dc4962e719b97e344053493261033,SystemUUID:691dc496-2e71-9b97-e344-053493261033,BootID:e0fb445c-7db3-435c-be14-bd3678033fe8,KernelVersion:5.4.0-1009-gcp,OSImage:Ubuntu 20.04 LTS,ContainerRuntimeVersion:docker://19.3.13,KubeletVersion:v1.20.0-beta.1.425+1cd2ed816a5c22,KubeProxyVersion:v1.20.0-beta.1.425+1cd2ed816a5c22,OperatingSystem:linux,Architecture:amd64,}
```
which I believe uses containerd v1.3.7 ([ref](https://docs.docker.com/engine/release-notes/)). This is in contrast to the COS job and Ubuntu containerd job, which use v1.4.0 ([logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1326479434965848064/build-log.txt)):
```
v1.NodeSystemInfo{MachineID: "4df6acec5355f0decfc1270f3cce9cce", SystemUUID: "4df6acec-5355-f0de-cfc1-270f3cce9cce", BootID: "65aa8d3e-f3cd-4f34-85f2-53ffda71615a", KernelVersion: "5.4.0-1009-gcp", OSImage: "Ubuntu 20.04 LTS", ContainerRuntimeVersion: "containerd://1.4.0", KubeletVersion: "v1.20.0-beta.1.430+f5e4a732663269", KubeProxyVersion: "v1.20.0-beta.1.430+f5e4a732663269", OperatingSystem: "linux", Architecture: "amd64"},
```

I think the purpose of the vanilla Ubuntu job is to, well, test on vanilla Ubuntu, so I don't think we should try to mess with container runtime there. It would likely be best strategy for now to add a gate on this test based on container runtime version. Any thoughts?

**Comment by andrewsykim** [comment]
The test _should_ be passing on docker though, so it's possibly a legitable failure

**Comment by andrewsykim** [comment]
Can you give me access to a cluster with that runtime? I can dig in a little deeper to figure out what's up

**Comment by andrewsykim** [comment]
Also, is this flaking or failing always?

**Comment by hasheddan** [comment]
@andrewsykim I believe a GKE cluster with Ubtuntu image nodes should use this runtime by default. And it is failing always

**Comment by andrewsykim** [comment]
Okay, I also thought some of the GKE presubmit tests were using dockershim too, wondering why those passed during presubmit

**Comment by andrewsykim** [comment]
Are there any presubmit tests that run dockershim? That would help us narrow down if it's a docker problem or a containerd version specific problem.

**Comment by hasheddan** [comment]
@andrewsykim I don't think there are. Looks like we only run node-e2e (which I am guessing is COS) and ubuntu-containerd https://testgrid.k8s.io/presubmits-kubernetes-blocking#Summary

**Comment by andrewsykim** [comment]
ack, is this test also failing on vanilla ubuntu? 

https://github.com/kubernetes/kubernetes/blob/81ad32e3a4005be16a4403a5f1edef342a16113e/test/e2e/common/container_probe.go#L227-L241

**Comment by andrewsykim** [comment]
Bug fix here https://github.com/kubernetes/kubernetes/pull/96495, @hasheddan can you help me run that failing job against that PR?
