### ISSUE TITLE
Ability to get list of overridable registries in e2e.test

### ISSUE THREAD

**Issue by wilsonehusin** [kubernetes/kubernetes#96475]
**What would you like to be added**:

A way to list [known YAML keys to override registries with `KUBE_TEST_REPO_LIST`][registry-yaml] without having to look inside the code.

**Why is this needed**:

To run conformance test on airgapped cluster, users need to prepare for the images being used by conformance test suite in registries which are accessible by their cluster. From what I have gathered, the workflow today is:

1. Look at the code mentioned above (`RegistryList struct`)
1. Write override YAML based on the keys listed
1. Pass the YAML as `KUBE_TEST_REPO_LIST`

My desired workflow would be:

1. Run `./e2e.test -list-registries`
1. Save the output above into a file & modify as needed
1. Pass the file as `KUBE_TEST_REPO_LIST`

Which would help me automate things and be aware whenever registries consumed by the test suite changes.

**Possible outcome**:

```
❯ ./e2e.test -list-registries
buildImageRegistry: k8s.gcr.io/build-image
dockerGluster: docker.io/gluster
dockerLibraryRegistry: docker.io/library
e2eRegistry: gcr.io/kubernetes-e2e-test-images
e2eVolumeRegistry: gcr.io/kubernetes-e2e-test-images/volume
gcRegistry: k8s.gcr.io
promoterE2eRegistry: k8s.gcr.io/e2e-test-images
sigStorageRegistry: k8s.gcr.io/sig-storage
```

**Notes**:

I'm using `-list-registries` as a placeholder for the feature, definitely open to be discussed

---

/kind feature
/sig testing

[registry-yaml]: https://github.com/kubernetes/kubernetes/blob/0469db9fe792784368e113ba6578faafb116665d/test/utils/image/manifest.go#L28-L43

**Comment by spiffxp** [comment]
I don't like the idea of registry variable / constant names being exposed as some kind of API, but I guess that horse has already left the barn.  

We're planning on consolidating images down into k8s.gcr.io. Images may move from one registry to another, and registries may be removed.  As long as you ensure whatever you code is tolerant to that I'm willing to review the PRs.

It would be nice if we could convert that from a struct to a map of registry->replacement, and get rid of the variable names. 
 Presumably your workflow would need to use output from `--list-images`, which also has enough information to let you know if new registries are being added.

**Comment by wilsonehusin** [comment]
@spiffxp thanks for the comment!

> I don't like the idea of registry variable / constant names being exposed as some kind of API

Agreed -- my approach is sort of working around the fact it's already there 😬 

> We're planning on consolidating images down into k8s.gcr.io. Images may move from one registry to another, and registries may be removed. As long as you ensure whatever you code is tolerant to that I'm willing to review the PRs.

My understanding of #96770 is that all images for e2e testing will be hosted in `k8s.gcr.io/e2e-test-images`, such that all entries in `test/utils/image/manifest.go` will use the same variable, e.g.
```go
configs[Nginx] = Config{e2eTestRegistry, "nginx", "1.14-alpine"}
```

If that's accurate, then I think my only ask is to have some way to override that registry, doesn't necessarily have to be exactly the same as previous releases with `KUBE_TEST_REPO_LIST`.

> It would be nice if we could convert that from a struct to a map of registry->replacement, and get rid of the variable names.
Presumably your workflow would need to use output from --list-images, which also has enough information to let you know if new registries are being added.

I'm not sure I follow on this part -- are you implying that we should provide the ability to override the individual images, i.e.
```yaml
---
Nginx: some.dockerhub.mirror.corp/library/nginx:1.14-alpine
```
instead of by registries like we have today? i.e.
```yaml
---
dockerLibraryRegistry: some.dockerhub.mirror.corp/library
```

**Comment by spiffxp** [comment]
The map I had in mind was something like:
```yaml
k8s.gcr.io/e2e-test-images: my-registry/k8s-test-images
docker.io/library: my-registry/docker-mirror
```

**Comment by wilsonehusin** [comment]
Seems like there has been a similar effort to mitigate this by @smarterclayton in https://github.com/kubernetes/kubernetes/pull/93510, which I think would solve my use case as well (no need to care about the list of registries if I can override globally!)

**Comment by dims** [comment]
ok let's close this and drive that one . https://github.com/kubernetes/kubernetes/pull/93510
