### ISSUE TITLE
Add SCTP support to the e2e DialFromNode method

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#96482]
The method `DialFromNode()` is used in the e2e tests to check the connectivity from the node

https://github.com/kubernetes/kubernetes/blob/a5bce462d095d3bf1ad91a6ebbc2c7a6ce3a314e/test/e2e/framework/network/utils.go#L420-L433

However, it only supports UDP and TCP, panicing if we try to use SCTP.

Adding support for SCTP will allow to enable e2e tests for those testcases

**Comment by cmluciano** [comment]
It looks like netcat has the option for `--sctp` but the image we use does not have the most up to date version.
