### ISSUE TITLE
APIListChunking - feature gate to GA?

### ISSUE THREAD

**Issue by tengqm** [kubernetes/kubernetes#96497]
**What would you like to be added**:

Shall we graduate APIListChunking to GA? The feature has been on since v1.9 and we are not getting a lot of complaints/issues on this feature (I may be wrong).

**Why is this needed**:

```go
	// owner: @smarterclayton
	// alpha: v1.8
	// beta: v1.9
	//
	// Allow API clients to retrieve resource lists in chunks rather than
	// all at once.
	APIListChunking featuregate.Feature = "APIListChunking"
```

**Comment by pacoxu** [comment]
The KEP-Issue is kubernetes/enhancements#365, Taken from kubernetes/kubernetes#49338. Original discussion in kubernetes/kubernetes#2349
The KEP is https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/365-paginated-lists 
The original design is [kubernetes/community](in https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/api-chunking.md)  which is created by https://github.com/kubernetes/community/pull/896.

Implementation PR is 

alpha 1.8 initialized by  @smarterclayton
- Disable default paging in list watches #51876 
- Alpha list paging implementation #48921
beta 1.9 promoted by  @smarterclayton
- Enable API chunking and promote to beta for 1.9 #52949
- Support api chunking in kubectl get #53768
- Table printers and server generation should always copy ListMeta #55835
1.15 enhanced by @jpbetz
- Paginate watch cache->etcd List calls & reflector init/resync List calls not served by watch cache #75389
- Add ListPager.EachListItem util #75849
1.18 fix issues by @wojtek-t 
- Don't paginate in listwatch #86790
- Avoid thundering herd of relists on etcd #86430
1.20 new consumers
- Switch GCP list calls to paginated calls. #96278


/cc   @wojtek-t  @jpbetz @smarterclayton

**Comment by pacoxu** [comment]
As the current process, it needs a PPR process in https://github.com/kubernetes/enhancements to decide whether this feature should be GA in the next release cycle.

You should get feedbacks and answer the questions in KEP PRR to make sure whether the feature should be promoted.

**Comment by JohnRusk** [comment]
I've logged a concern about the current behaviour in the linked issue #102672

**Comment by wojtek-t** [comment]
I'm going to take it - will send out KEP update after code freeze to address the pagination in watchcache which seems to be the biggest blocker now.

**Comment by wojtek-t** [comment]
This was graduated to GA in 1.29 with: https://github.com/kubernetes/kubernetes/pull/119503

**Comment by davidopp** [comment]
Is this feature used in the golang or Java client library? If not, is there a plan to use it?

**Comment by jpbetz** [comment]
> Is this feature used in the golang or Java client library? If not, is there a plan to use it?

It has been in use for a long time in client-go. I don't know about the Java client offhand.

**Comment by wojtek-t** [comment]
> It has been in use for a long time in client-go. 

You need to set the limit though if you want to use it.
