### ISSUE TITLE
Inconsistent behavior when creating pods with different gpu limits

### ISSUE THREAD

**Issue by llhuii** [kubernetes/kubernetes#96506]
**What happened**:
```bash
# kubectl create -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  generateName: cuda-vector-add-
spec:
  restartPolicy: OnFailure
  nodeName: edge1
  containers:
    - name: cuda-vector-add
      # https://github.com/kubernetes/kubernetes/blob/v1.7.11/test/images/nvidia-cuda/Dockerfile
      image: "k8s.gcr.io/cuda-vector-add:v0.1"
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
EOF

pod/cuda-vector-add-9jlgn created

# kubectl create -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  generateName: cuda-vector-add-
spec:
  restartPolicy: OnFailure
  nodeName: edge1
  containers:
    - name: cuda-vector-add
      # https://github.com/kubernetes/kubernetes/blob/v1.7.11/test/images/nvidia-cuda/Dockerfile
      image: "k8s.gcr.io/cuda-vector-add:v0.1"
      resources:
        limits:
          alpha.kubernetes.io/nvidia-gpu: 1 # requesting 1 GPU
EOF

pod/cuda-vector-add-d8wmf created

# kubectl get pod
NAME                                    READY   STATUS                                RESTARTS   AGE
cuda-vector-add-d8wmf                   0/1     OutOfalpha.kubernetes.io/nvidia-gpu   0          33m
cuda-vector-add-9jlgn                   0/1     CrashLoopBackOff                      11         33m
```

**What you expected to happen**:
Expect these status of the pods `cuda-vector-add-d8wmf` and `cuda-vector-add-d8wmf` have same behaviors.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools: keadm
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by lingsamuel** [comment]
Can you describe `cuda-vector-add-9jlgn`?

**Comment by lingsamuel** [comment]
Are you install your device plugin properly?
K8s will remove missing extended resource. `nvidia.com/gpu` is extended resource, `alpha.kubernetes.io/nvidia-gpu` isn't because it contains `kubernetes.io/`.

https://github.com/kubernetes/kubernetes/blob/307278029cbf69bc35a7795594d970b7781de2b8/pkg/kubelet/lifecycle/predicate.go#L87-L95

**Comment by llhuii** [comment]
> Are you install your device plugin properly?
> K8s will remove missing extended resource. `nvidia.com/gpu` is extended resource, `alpha.kubernetes.io/nvidia-gpu` isn't because it contains `kubernetes.io/`. If you haven't installed nvidia device plugin properly, the limit is ignored.
> 
> https://github.com/kubernetes/kubernetes/blob/307278029cbf69bc35a7795594d970b7781de2b8/pkg/kubelet/lifecycle/predicate.go#L87-L95

No device plugin installation in this issue.

**Comment by lingsamuel** [comment]
Then this behavior is by design.
Your nodes don't have resource `nvidia.com/gpu`, so when scheduling `cuda-vector-add-9jlgn`, the limit is ignored. Then the pod is scheduled normally - and it crashes later.
The another one `cuda-vector-add-d8wmf` has a resource limit contains `kubernetes.io/`, which considered as an "internal" resource, won't be removed even if it doesn't exist in nodes. So it failed to schedule, cause the error `OutOfXXX`.

**Comment by llhuii** [comment]
I don't understand why the limit should be ignored?  I think it's better to tell the user the wrong or not enought limits?  Any discussions?

**Comment by lingsamuel** [comment]
Currently it doesn't
> kubelet will not fail admission while it should. This issue will be addressed with the Resource Class API **in the future.**

/kind feature
