### ISSUE TITLE
Node labels set by Topology keys are not removed after uninstalling CSI Driver 

### ISSUE THREAD

**Issue by prashantcfc** [kubernetes/kubernetes#96505]
**We are writing a CSI driver SP (on prem) and during the NodeGetInfo RPC we return certain topology keys as part of the response which are set on the CSINode and in turn, on the Kubernetes Node. However, when the driver is uninstalled, these node labels are removed from the CSINode object but not removed from the Kubernetes Node.**:

**Since the node labels are removed from the CSINode, expected them to be successfully removed from the Node as well.**:

**Should be able to reproduce this by a CSI driver that sets topology keys by returning them as part of a NodeGetInfo RPC response & the same are applied on the CSINode & Node. Something along the following lines:

	return &csi.NodeGetInfoResponse{
		NodeId: nodeID,
		AccessibleTopology: &csi.Topology{
			Segments: topology,
		},
	}

**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.19.0
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): RHEL 7.9
- Kernel (e.g. `uname -a`): Linux 3.10.0-1160.el7.x86_64 #1 SMP Tue Aug 18 14:50:17 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm 
- Network plugin and version (if this is a network-related bug): Flannel
- Others: N/A

**Comment by harishp8889** [comment]
Hello, I am also facing this problem in one of our CSI driver due to the labels not getting removed after driver removal, Due to this scheduling is happening in the wrong nodes(Topology keys) currently we are managing by removing the node labels manually.

**Comment by pohly** [comment]
I was told that this is intentional. The reasoning is that a CSI driver might report a topology that is driver independent (for example, "zone: A, rack: B") and then removing those labels could break other usages of those labels.

Why do you depend on the node labels for pod scheduling? Is the assumption that if the driver runs on a node, it can always provide volumes there?
