### ISSUE TITLE
[Flaking] gce-cos-master-alpha-features Up 

### ISSUE THREAD

**Issue by RobertKielty** [kubernetes/kubernetes#96511]
**Which jobs are flaking**:
gce-cos-master-alpha-features

**Which test(s) are flaking**:
Up 

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-alpha-features&exclude-non-failed-tests=&width=90

**Reason for failure**:
`error during ./hack/e2e-internal/e2e-up.sh: exit status 1`

**Anything else we need to know**:
Flaked between 9223413a7 and bdac36b57 
Failing since 9223413a7
- links to go.k8s.io/triage appreciated  

**Triage is not capturing results from this job**

- links to specific failures in spyglass
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1326849222233821184
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1326839403028418560
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1326829587740495872
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1326819771273973760
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1326809706429157376
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1326779000554524672
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1326749051764346880
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1326739492727427072
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1326729675606593536

**Comment by RobertKielty** [comment]
gce-cos-master-alpha-feature and the Up "test" (really a Cluster Provisioning Step) is now back working. 

From my review of the logs this _appeared_ to be a test infrastructural issue provisioning a 4 node cluster using kubetest 

Error message was too vague to allow me to escalate this to an appropriate team.

I will monitor today and escalate withing sig-release of needs be.

**Comment by neolit123** [comment]
> From my review of the logs this appeared to be a test infrastructural issue provisioning a 4 node cluster using kubetest

yes, seems like so:
> I1112 20:36:39.093] [0;33mDetected 0 ready nodes, found 0 nodes out of expected 4. Your cluster may not be fully functional.[0m

owner google/gce:
https://github.com/kubernetes/test-infra/blob/bbcd71888bc301fd9017234d54beb85e0e13bb14/config/jobs/kubernetes/sig-cloud-provider/gcp/gcp-gce.yaml#L671-L674

/sig cloud-provider
/area provider/gcp

**Comment by liggitt** [comment]
fixed by https://github.com/kubernetes/kubernetes/pull/96444

/close
