### ISSUE TITLE
Scheduler should consider pod capacity of fully terminated but not deleted pods explicitly

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#96515]
The scheduler currently waits for full pod deletion (pod removed from the apiserver) to stop accounting the pod resources to the node.  The Kubelet stops accounting for consumed resources on the node once all these conditions are reached:

a) the pod is marked as deleted
b) the pod sync loop observes that deletion
c) the pod sync loop observes that all containers are stopped (internal container status has 'terminated' state for all containers in the pod)

After these conditions are reached, the Kubelet notifies the apiserver by updating pod status (and this is now formally part of the pod lifecycle guarantee, described in https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1748-pod-resource-metrics#describe-the-pod-resource-model).  Once this happens, the scheduler may assume that the node has released those resources (since other callers, like Job controllers or statefulsets may also assume the pod is terminal).  At this point the Kubelet may still be cleaning up resources like volumes or disk space for logs under the covers, but these are explicitly garbage collected resources of the pod model and the scheduler should be able to discount them.  The final delete call of the Kubelet may be arbitrarily delayed for other reasons, so in dense / busy clusters this would result in more accurate and efficient resource usage.

The scheduler should consider detecting this state (terminal as defined in the KEP) and releasing those resources in its scheduling model at that time.  Other components may assume that as well.  Conversely, if we decide not to consider these terminal, we should update the KEP and explicitly define that in the API resource model.

**Comment by Huang-Wei** [comment]
So this suggests scheduler to exclude "terminating" Pods in its model, this is not a small change.

What's the concrete semantics of "terminal" Pods? In terms of API: is it good enough to check if Pods carry nil deletionTimestamp? or need to additionally check some status conditions?

**Comment by smarterclayton** [comment]
The KEP describes it but it's marked deleted and all containers that are listed in spec (init and regular) having state terminated, and when ephemeral lands also ephemeral containers in status.

Depending on how busy a kubelet is it might be 5-20s before a terminal pod is deleted, or potentially more when some CSI volumes are taken into account.  I think you can view this as an optimization that should improve general resource usage of a cluster, but isn't strictly required for correctness.

**Comment by Huang-Wei** [comment]
> The KEP describes it but it's marked deleted and all containers that are listed in spec (init and regular) having state terminated, and when ephemeral lands also ephemeral containers in status.

Thanks. It makes sense to categorize the Pods that don't occupy resources as `Completed` (or "terminal/terminated") - no matter they're regular physically deleted or terminating Pods, or succeeded/failed Job Pods.

cc/ @ahg-g @alculquicondor

**Comment by smarterclayton** [comment]
Some risks I could see with this is that it triggers higher resource contention (from pods that are tearing down and new pods that are landing faster) and exposes issues.  However, those issues are latent anyway for batch workloads (run-once pods would trigger any of those issues the same way, since the kubelet reports Succeeded or Failed before it begins cleanup of volumes), and in general that's the kubelet's responsibilty to manage that.

It might make sense for us to report a `Completed` condition on pods from the Kubelet once the kubelet has identified that processes from the pod are no longer running and the resources requested are released.  We might also have to dig deeper to verify that some aspects of pod resource tracking like "volumes mounted per node" that might be impacted like this are correctly handled by the Kubelet.  So it could be that trying this in a perf run identifies a number of problems and gives us better understanding of what might need to get fixed first.

**Comment by alculquicondor** [comment]
@smarterclayton it seems to me that you are thinking that kube-scheduler accounts for Pods until they are deleted. This is not the case. It stops accounting for Pods once they are in Succeeded or Failed phase.

Unless kubelet actually doesn't update the phase until everything is garbage collected?

**Comment by Huang-Wei** [comment]
@alculquicondor Succeeded or Failed are specific terms for run-to-completion Pods (spawned and managed by Job controller). In terms of regular long-running Pods, kube-scheduler does retain them until they're physically deleted (via a Delete event from API server) - i.e., even when it's being garbaged collected in kubelet, or kubelet hasn't reported the pod's status to API server.

**Comment by alculquicondor** [comment]
> or kubelet hasn't reported the pod's status to API server.

Is that not a phase then?

**Comment by ahg-g** [comment]
> Succeeded or Failed are specific terms for run-to-completion Pods (spawned and managed by Job controller)

Any idea who sets those phases? is it the controller or kubelet?

**Comment by alculquicondor** [comment]
/remove-lifecycle stale

> Any idea who sets those phases? is it the controller or kubelet?

It is kubelet.

The request seems reasonable to me

/triage accepted

**Comment by alculquicondor** [comment]
If I'm understanding correctly, in the case of Jobs, where Pods are not removed until explicitly deleted (or by the new TTL controller), those resources are being held. If so, that's pretty bad for batch use cases.

**Comment by ahg-g** [comment]
> If I'm understanding correctly, in the case of Jobs, where Pods are not removed until explicitly deleted (or by the new TTL controller), those resources are being held. If so, that's pretty bad for batch use cases.

but the scheduler doesn't account for succeeded or failed pods, the final status of job pods...

**Comment by alculquicondor** [comment]
Oh right, I got confused again.

So, to summarize (and please correct me if I got anything wrong) only Job Pods get Succeeded or Failed status. When that happens, kube-scheduler doesn't account for them.

https://github.com/kubernetes/kubernetes/blob/3e9611297192748eed66d41a36cced25e9a6e494/pkg/scheduler/scheduler.go#L665

For other kinds of Pods, kubelet marks all containers as terminated, but **it doesn't change the phase to Succeeded or Terminated**. Once all resources have been collected, kubelet deletes the Pod from the API. From the KEP:

```
 The transition to the Completed state occurs when the Kubelet records the terminal state of the pod in the apiserver by setting the Succeeded or Failed phase in status, or when the pod is marked for deletion and all containers are given a status and termination state.
```

So the request is to account for this case in scheduler and consider the Pod removed.

@smarterclayton did I get all the facts right?

**Comment by Huang-Wei** [comment]
@alculquicondor For run-to-completion pods, if it's succeeded or failed, a Deletion event will be issued, so in scheduler side, that pod's holding resource will be removed from scheduler cache; otherwise, we'd have been in big trouble :)

Here was [one example](https://github.com/Huang-Wei/tryout-watch-completed-pod) (in particular the "A Pod spawned by Job" section) to verify the case.

**Comment by alculquicondor** [comment]
/remove-lifecycle stale

For separation of concerns, I believe the scheduler shouldn't do this calculations. It should just rely on the phase set by the kubelet.
One particular reason: if the kubelet stopped accounting for this terminated pod and the node crashes and restarts, the pod will be restarted. So the kubelet should signal somehow to the apiserver that it's no longer accounting for the Pod: either removing it or updating the phase.

@smarterclayton wdyt?

**Comment by ahg-g** [comment]
I don't think the concern is about kubelet restarts. I think it is more about the dependency on the pod's restart policy, which the scheduler should be agnostic to since restartPolicy is a node-level feature.

Specifically, looking at the container status is not enough to determine if the resources can be reclaimed or that the pod will eventually be deleted. For example, for pods with restart policy=always, we can't exclude pods with containers with "LastTerminationState=Terminated" because the pod will get restarted on the same node. 

I don't think this optimization is necessary, the scheduler for the most part is pod-centric and should continue to be as such.

/remove-kind bug
/kind feature

**Comment by alculquicondor** [comment]
/reopen

@smarterclayton do you still think we should do this?
