### ISSUE TITLE
windows kube-proxy: fall back to node-local terminating endpoints for external traffic

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#96514]
Windows analog for #96371

kube-proxy Should fallback to terminating endpoints `iff`:
* externalTrafficPolicy: Local
* traffic is from an external source
* there are no ready and not terminating endpoints on the node 

This prevents packet loss in scenarios where a load balancer sends traffic to a node that recently terminated all it's endpoints.  

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:**

**Comment by robscott** [comment]
@jayunit100 Thanks for filing this issue and taking this on! One small nit - the issue itself is a bit confusing. It has content like `Which issue(s) this PR fixes:` and `Does this PR introduce a user-facing change?:` and `fixes #` that should probably be removed.

**Comment by thockin** [comment]
Yeah, it looks like you meant to open a PR from a branch?

**Comment by jayunit100** [comment]
Fixed, I meant to file an issue but had some PR text in it..

**Comment by jayunit100** [comment]
hiya folks, been wading through a huge backlog , havent gotten a chance to look at this. 
anyone else want to take it?
