### ISSUE TITLE
cheking UID's in windows, follow on (quick pr)

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#96512]
**What happened**:

follow on to https://github.com/kubernetes/kubernetes/pull/96172

Need to comment and avoid checking UID on windows.  requires some research into what we **should** be checking so that we can add appropriate TODO.

**What you expected to happen**:

Lets also check this at the call site, https://github.com/kubernetes/kubernetes/blob/199d48728f33692dc5a5e8b808a064bd3e40b51a/cmd/kubelet/app/server.go#L757 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): master
- OS (e.g: `cat /etc/os-release`): windows

**Comment by jlsong01** [comment]
Hi @perithompson   are you working on this issue already? If not I'd like to tackle this issue :)

**Comment by perithompson** [comment]
Hi @jlsong01 yeah I am already working on this :)

**Comment by perithompson** [comment]
Started branch for this here @jayunit100 
https://github.com/perithompson/kubernetes/tree/windows-check-permissions

**Comment by jayunit100** [comment]
thanks @perithompson

**Comment by Aut0R3V** [comment]
Hey guys is there anything I can do here?

**Comment by jayunit100** [comment]
If you want to test perks patch that would be great ?

**Comment by lauchokyip** [comment]
Hi @jayunit100, I am new to Kubernetes and I just submitted a PR for fixing the golint error. Do you mind explaining what test perks patch is and how I can help with that ? Thanks!

**Comment by Aut0R3V** [comment]
> If you want to test perks patch that would be great ?
That sounds great @jayunit100. Where do I get started?

**Comment by coderfornow** [comment]
Hey @perithompson !
is there anything I can help with? and how?

**Comment by perithompson** [comment]
I dont think there is anything left to do @jayunit100 anything more that you think we need to do to get this merged?

**Comment by perithompson** [comment]
Tested this with containerd as well, I think its good to test @jayunit100
