### ISSUE TITLE
GCE L4 ILB forwarding rules getting recreated upon master restart

### ISSUE THREAD

**Issue by prameshj** [kubernetes/kubernetes#96513]
**What happened**:
I created a GCE k8s cluster from HEAD and a LoadBalancer service with "Internal" annotation. Restarting the master VM deletes and recreates the forwarding rule after startup, even if nothing changed in the service.

**What you expected to happen**:
The forwarding rule should not be deleted.

**How to reproduce it (as minimally and precisely as possible)**:
Create a k8s cluster via kubetest and create an ILB service. Restart the master VM after the service has gotten IP assignment.

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`): 1.20
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig network
/kind bug

**Comment by thockin** [comment]
Assigned - can GCP owners please triage this and see if it reproduces as described?

**Comment by prameshj** [comment]
/assign @prameshj 

Yes, I found the issue and am working on the fix as well.
