### ISSUE TITLE
CSIDriver object is not validating objectmeta

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#96520]
**What happened**:
See https://github.com/kubernetes/kubernetes/blob/295010c30b6f30f88b766a710c7eadda77577761/pkg/apis/storage/validation/validation.go#L396

Means that labels/annotations, etc are not being validated.

ref: https://github.com/kubernetes/kubernetes/pull/95739#discussion_r522320695

**Comment by liggitt** [comment]
We run object meta validation in BeforeCreate/BeforeUpdate for just this reason:

https://github.com/kubernetes/kubernetes/blob/5f1e5cafd33a8863c5dfe9f36c9cba836f0e981b/staging/src/k8s.io/apiserver/pkg/registry/rest/create.go#L111-L114

https://github.com/kubernetes/kubernetes/blob/5f1e5cafd33a8863c5dfe9f36c9cba836f0e981b/staging/src/k8s.io/apiserver/pkg/registry/rest/update.go#L77-L78

**Comment by liggitt** [comment]
the name validation is extremely minimal (ValidatePathSegmentName), but all object meta fields are validated

**Comment by liggitt** [comment]
validated in BeforeCreate in 1.1+ in https://github.com/kubernetes/kubernetes/pull/15975

validated in BeforeUpdate in 1.2+ in be0754750f7dac811bc8375714a043deae6709c0

**Comment by liggitt** [comment]
it looks like the name was validated by the specific CSIDriver validation:

https://github.com/kubernetes/kubernetes/blob/5f1e5cafd33a8863c5dfe9f36c9cba836f0e981b/pkg/apis/storage/validation/validation.go#L398

**Comment by msau42** [comment]
Phew, thanks Jordan from 2015!

We've added the ValidateObjectMeta call back into the ValidateCSIDriver function in #95739 anyway to be consistent.

/close
