### ISSUE TITLE
kube-apiserver/options/validation.go: test different combinations of APF runtime config parameters

### ISSUE THREAD

**Issue by adtac** [kubernetes/kubernetes#96537]
ref: https://github.com/kubernetes/kubernetes/pull/96527#discussion_r522440243

/sig api-machinery
/kind feature
/cc @lavalamp @MikeSpreitzer 
/assign

(I'll do this in a follow-up PR.)

**Comment by fedebongio** [comment]
@adtac is this only for your own tracking or you need help? Thanks!

**Comment by lavalamp** [comment]
This can probably be merged with #96648?

**Comment by adtac** [comment]
ack, closing in favour of https://github.com/kubernetes/kubernetes/issues/96648 which is more detailed in its description
