### ISSUE TITLE
Memory increases over time ( low to none activity on the cluster)

### ISSUE THREAD

**Issue by oana-s** [kubernetes/kubernetes#96554]
Without much activity I see that memory increases over time(within 1 week from 50 to 90%) and it clearly affects the latency
![image](https://user-images.githubusercontent.com/60611170/99090152-8df3fc00-25ce-11eb-8078-70aab7648ec9.png)

I see that buff/cache is growing but I cannot identify what is going wrong;  even so I do not think that this alone is the cause
![image](https://user-images.githubusercontent.com/60611170/99062460-5459cb80-25a3-11eb-86d0-25971cd6d586.png)
 kubernetes version: v1.19.3

Could you help me out to identify what is causing this memory to increase so drastically (even there is no load whatsoever, this remains the same)?

**Comment by neolit123** [comment]
hi,

potentially related:
https://stackoverflow.com/questions/56528876/kafka-memory-leak

please try the support forums:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

we try to keep the issue tracker for bugs / features. if you find a bug in core kubernetes related to the memory increase, please re-open the ticket and update the details.

i don't see a #kafka channel in the Kubernetes slack, but you can also try their issue tracker:
https://issues.apache.org/jira/projects/KAFKA/issues/KAFKA-10687?filter=allopenissues

thanks.
/close
