### ISSUE TITLE
after delete statefulset，pod is not delete

### ISSUE THREAD

**Issue by davidstack** [kubernetes/kubernetes#96557]
**What happened**:
in my cluster,most pod will be deleted after the statefulset is deleted. but there is one pod is not deleted, while the statefulset has been deleted.  
**What you expected to happen**:
the pod should be deleted.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
the pod of the statefulset is 6imo2tilh9igb,  two same pod (6imo2tilh9igb-0) are created, two same statefulset (6imo2tilh9igb) are deleted

![image](https://user-images.githubusercontent.com/5036200/99072075-48dfc200-25ee-11eb-84d1-8b632843e5cf.png)

some controller-manager-log
![image](https://user-images.githubusercontent.com/5036200/99072223-93613e80-25ee-11eb-8b6c-1b7e3e9b8ad3.png)
![image](https://user-images.githubusercontent.com/5036200/99072247-9ceaa680-25ee-11eb-9c75-6d44a79b0d7a.png)

**Environment**:
- Kubernetes version (use `kubectl version`):
1.14.8
- Cloud provider or hardware configuration:
hardware
- OS (e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`):
3.10.0-862.el7.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
calico
- Others:

**Comment by davidstack** [comment]
when k8s delete statefulset, the api server will patch the statefulset and pod with metadata
`  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2020-11-13T06:48:53Z"
  finalizers:
  - orphan`

but the pod does not has this metadata, and the ownerreference of the pod is missing.very strange thing.

**Comment by krmayankk** [comment]
@davidstack is this reproducible ?

**Comment by davidstack** [comment]
@krmayankk  i can not find one method to reproduce this problem, but i have serveral clusters have this problem

**Comment by davidstack** [comment]
maybe because  i use the orphan delete policy,so sometimes, my cluster have this problem.close it
