### ISSUE TITLE
Add 'nodeSelector' to --field-selector supported query options

### ISSUE THREAD

**Issue by EthanSedgwick** [kubernetes/kubernetes#96569]
**What would you like to be added**: To allow us to select pods and deployments that are using specific nodeSelectors, for example in our use case we are trrying to find pods that we have scheudled to use role=stable (which puts them on stable EC2 instances, versus the default of spot EC2 instances)

**Why is this needed**: Currently the only way to do so is to get all pods and then filter that out via jsonpath or jq, which both occur on the clientside, thus making this a slow and expensive query.
`
kubectl get deploy --all-namespaces -o json | jq '.items[] | select(.spec.template.spec.nodeSelector.role=="stable") | .metadata | { name, namespace }'
`

**Comment by brendandonnellysc** [comment]
Can this open reviewed again. This would be highly helpful in the AWS EKS setup
