### ISSUE TITLE
PreStart lifecycle hook Required

### ISSUE THREAD

**Issue by shinytang6** [kubernetes/kubernetes#96560]
**What would you like to be added**:
Currently k8s supports `postStart` and `preStop` lifecycle hook, but in my scenario what I need is actually `preStart`.
And l think `PreStart` is very useful in many scenarios, I don’t understand why it is not supported...

I found some discussions here #140. And a few years have passed, are there any updates/plans for that?

ps: My scenario is simple, l need to create the Linux user in the container based on the value set by the user dynamically before the container's commands running.

**Comment by Cweiping** [comment]
Why not use initContainer? @shinytang6

**Comment by shinytang6** [comment]
@Cweiping What l need is to execute my command at the beginning of the main container ...  `initContainer ` can not do that

**Comment by pacoxu** [comment]
You may add your command to the start of your entypoint.sh in Dockerfile during image building.

**Comment by Cweiping** [comment]
> @Cweiping What l need is to execute my command at the beginning of the main container ... `initContainer ` can not do that

Override entrypoint or rebuild image is a more appropriate choice, which is more reasonable than the implementation of PreStart.

**Comment by shinytang6** [comment]
My scenary is to dynamically insert the command to create a user based on the user's input (e.g.username), l actually don't know what the real command is, so l cannot hack it by inserting a script at the beginning of the Command or Dockerfile.

**Comment by shinytang6** [comment]
> > @Cweiping What l need is to execute my command at the beginning of the main container ... `initContainer ` can not do that
> 
> Override entrypoint or rebuild image is a more appropriate choice, which is more reasonable than the implementation of PreStart.

l cannot override entrypoint or rebuild image as l described before, l think `preStart` hook is very useful in some cases, is there any reason/side effect not implementing the `preStart` hook?

**Comment by pacoxu** [comment]
Another workaround: Add env INIT_COMMAND in your Dockerfile and execute it in your entrypoint.sh.

BTW, this is not best practise .

### init container 
You can use initContainer with the same image and use same path as the main container. Mount a path to both containers.

**Comment by shinytang6** [comment]
> Another workaround: Add env INIT_COMMAND in your Dockerfile and execute it in your entrypoint.sh.
> 
> BTW, this is not best practise .
> 
> ### init container
> You can use initContainer with the same image and use same path as the main container. Mount a path to both containers.

The first approach is indeed possible, but it pollutes the mirror to some extent.
To the second approach, the command l actually executed is like `useradd xxx`, l am not sure if it will cause some problem if l do that.. But l can have a try, Thanks!

**Comment by pacoxu** [comment]
I'm afraid that it is not good to share /etc/passwd as user info is save in  /etc/passwd .

I think `Add env USER_NAME in Dockerfile` may be a better way.

**Comment by shinytang6** [comment]
> Another workaround: Add env INIT_COMMAND in your Dockerfile and execute it in your entrypoint.sh.
> 
> BTW, this is not best practise .
> 
> ### init container
> You can use initContainer with the same image and use same path as the main container. Mount a path to both containers.

Update: I tried it briefly, no matter whether it is mounting the / directory or the /etc/passwd directory, there will be some errors. My need is not as simple as sharing a file.. it's also really trick using that method..

**Comment by shinytang6** [comment]
> I'm afraid that it is not good to share /etc/passwd as user info is save in /etc/passwd .
> 
> I think `Add env USER_NAME in Dockerfile` may be a better way.

make sense to me in some way, but in my situation I think using `prestart` is much more reasonable :)

**Comment by pacoxu** [comment]
http://iocanel.com/2017/09/using-init-containers-to-handle-openshifts-arbitrary-user-ids/
Openshift user suffered the same.

**Comment by shinytang6** [comment]
> I'm afraid that it is not good to share /etc/passwd as user info is save in /etc/passwd .
> 
> I think `Add env USER_NAME in Dockerfile` may be a better way.

Sorry, I found that this method still does not work, because it needs to specify username env in the image. But l am actually writing a k8s controller, l want to hijack the k8s pod creation event and insert the user add command before the main pod command...

**Comment by pacoxu** [comment]
> >  hijack the k8s pod creation event and insert the `useradd` command before the main pod command... 

Override command like `bash -c "useradd xxxx  &&  origin-command "`. 
You have to get the Image command if it is not specified in the pod yaml.

**Comment by shinytang6** [comment]
> > > hijack the k8s pod creation event and insert the `useradd` command before the main pod command...
> 
> Override command like `bash -c "useradd xxxx && origin-command "`.
> You have to get the Image command if it is not specified in the pod yaml.

lt's really hard to do that because image EntryPoint/CMD may be overided by Command  inside pod yaml

**Comment by navratiljan** [comment]
Is there a plan to implement this ? We would also like to use this feature

**Comment by gallyamb** [comment]
I really miss this feature. My use case: export env variable with secrets from Hashicorp Vault. In our organization Vault is not synced with k8s secrets, so there is no way to use them. initContainers could not modify main container's env. Modifying entrypoint forces me to duplicate entrypoint from Docker image, which I do not own, therefore could not modify (and do not want to support future updates and resolve conflicts) their entrypoint
