### ISSUE TITLE
The extended scheduler with webhook will retry bind pod forever when the pod is bind successed but the bind request timeout

### ISSUE THREAD

**Issue by chenyw1990** [kubernetes/kubernetes#96579]
**What happened**:
The extended scheduler with webhook will retry bind pod forever when the pod is bind successed but the bind request timeout

![](https://user-images.githubusercontent.com/1468240/99137266-939c2100-2664-11eb-86c4-89f4aace3e6b.png)

**What you expected to happen**:
Do not perform repeated scheduling when the nodename of the pod is not empty.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
In the code of v1.18, before a pod is scheduled again, the scheduler checks whether the nodename of the pod is empty.
![](https://user-images.githubusercontent.com/1468240/99137930-ee834780-2667-11eb-97c8-a04f382e2517.PNG)

**Environment**:
- Kubernetes version (use `kubectl version`): "v1.19.0"
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): "EulerOS 2.0 (SP9)
- Kernel (e.g. `uname -a`): Linux 4.19.90-vhulk2009.2.0.h269.eulerosv2r9.aarch64 #1 SMP Sun Sep 27 12:47:01 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by chenyw1990** [comment]
/assign @chenyw1990
I will fix it

**Comment by chendave** [comment]
May I know how that could happen? bind success while got request is timeout, is that checking by `wait.Poll`? where is the code for this check?

**Comment by chenyw1990** [comment]
@chendave 

what happened?
Our cluster has 2000 nodes, and some pods use extender scheduler, the response of kube-apiserver becomes slow during batch application deployment.

the default HTTPExtender timeout is 5s,  sametimes bind request will timeout.

![image](https://user-images.githubusercontent.com/1468240/99356250-d409d200-28e4-11eb-97c4-2ba5856df8d1.png)

**Comment by Huang-Wei** [comment]
@chenyw1990 Thanks for the explanation. Would you mind summarizing it as a comment in your PR?

**Comment by chenyw1990** [comment]
the fix pr #96582 has been merged，close this issue
