### ISSUE TITLE
Kubelet not coming up after reboot "exit status is 255"

### ISSUE THREAD

**Issue by gseidel** [kubernetes/kubernetes#96589]
**What happened**:

After I reboot a node (Reproducible for another node as well). The docker container and kubelet didn't start again.

The logs in ``journalctl -xeu kubelet`` says:

```
main.main()
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/kubelet.go:41 +0xe5
goroutine 19 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x6cfe140)
        /workspace/anago-v1.19.3-rc.0.69+37babbd0e76c11/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1131 +0x8b
created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
        /workspace/anago-v1.19.3-rc.0.69+37babbd0e76c11/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:416 +0xd8
goroutine 64 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:147 +0x9d
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
        /usr/local/go/src/os/signal/signal.go:150 +0x45
goroutine 33 [select]:
k8s.io/kubernetes/vendor/go.opencensus.io/stats/view.(*worker).start(0xc000576780)
        /workspace/anago-v1.19.3-rc.0.69+37babbd0e76c11/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/go.opencensus.io/stats/view/worker.go:154 +0x105
created by k8s.io/kubernetes/vendor/go.opencensus.io/stats/view.init.0
        /workspace/anago-v1.19.3-rc.0.69+37babbd0e76c11/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/go.opencensus.io/stats/view/worker.go:32 +0x57
goroutine 78 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4799428, 0x4bf2280, 0xc0007f99b0, 0x1, 0xc00010e0c0)
        /workspace/anago-v1.19.3-rc.0.69+37babbd0e76c11/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x149
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x4799428, 0x12a05f200, 0x0, 0xc000b1f901, 0xc00010e0c0)
        /workspace/anago-v1.19.3-rc.0.69+37babbd0e76c11/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
        /workspace/anago-v1.19.3-rc.0.69+37babbd0e76c11/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Forever(0x4799428, 0x12a05f200)
        /workspace/anago-v1.19.3-rc.0.69+37babbd0e76c11/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:81 +0x4f
created by k8s.io/kubernetes/vendor/k8s.io/component-base/logs.InitLogs
        /workspace/anago-v1.19.3-rc.0.69+37babbd0e76c11/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/logs/logs.go:58 +0x8a
goroutine 65 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.SetupSignalContext.func1(0xc000858ef0)
        /workspace/anago-v1.19.3-rc.0.69+37babbd0e76c11/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/signal.go:48 +0x36
created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.SetupSignalContext
        /workspace/anago-v1.19.3-rc.0.69+37babbd0e76c11/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/signal.go:47 +0xf3
kubelet.service: Main process exited, code=exited, status=255/EXCEPTION

-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- An ExecStart= process belonging to unit kubelet.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 255. kubelet.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- The unit kubelet.service has entered the 'failed' state with result 'exit-code'.
```

I try ``swapoff -a`` but it also didin't help.

**What you expected to happen**:

After reboot the system or kubelet, the container runs again.

**How to reproduce it (as minimally and precisely as possible)**:

Install kubernetes with get started guide. Reboot.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.19.3
- Cloud provider or hardware configuration: hcloud, 1 master with 3 worker nodes
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.1
- Kernel (e.g. `uname -a`): 5.4.0-40-generic
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
/sig node
/milestone v1.20
adding milestone to gather more attention.

- what options are you passing to the kubelet either via KubeletConfiguration or flags?
- are your components matching versions kubelet / apiserver / ... etc?
- can you show the whole kubelet log - e.g. at https://pastebin.com ?

**Comment by panpan0000** [comment]
When if the problem caused by improper the kubelet config/arguments, attach the begining part of the kubelet log would be helpful than go-lang dump .  @gseidel

**Comment by erismaster** [comment]
👋  Hi, Bug Triage here. We're pretty late into code freeze for 1.20, going to bump this to 1.21. Thanks!

/milestone 1.21

**Comment by erismaster** [comment]
👋 Hi, Bug Triage here. We're pretty late into code freeze for 1.20, going to bump this to 1.21. Thanks!

/milestone v1.21

**Comment by neolit123** [comment]
@erismaster i left this one in 1.20 so that SIG Node can potentially triage it.
panics usually imply critical-urgent fixes.

**Comment by derekwaynecarr** [comment]
I don't think this should block 1.20 as the report is on 1.19 and lacks sufficient details for further analysis.

**Comment by gseidel** [comment]
My problem as a beginner to kubernetes was to get the informations about what is going wrong if something don't work as expected. I miss to pass more information to this ticket because it's hard to get . 

The command `journalctl -u kubelet` just prints everything since installation. And `journalctl -xeu kubelet` to less to help me seeing any problem.

For me, the best way, to get the information what is going wrong here, was to check the daemon file:
`/etc/systemd/system/kubelet.service.d/10-kubeadm.conf`

And build the executed command from it and start the kubelet on the command line.

```
$ /usr/bin/kubelet \
--kubeconfig=/etc/kubernetes/kubelet.conf \
--config=/var/lib/kubelet/config.yaml \
--network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.2
```

Now I was able to see what is going wrong and could find some solutions on other pages, so I don't think it make sense to post here, because i guess the problem is individuell (And I don't have the output anymore).

Hope that helps other to better debug their problem. I try to find something like this in the documentation, but I couldn't find. Maybe someone can share a link or I could add a documentation entry if you guys said this is worth it.

I will close that issue, because my problem is solved.

**Comment by prawen** [comment]
@gseidel You don't know how much this has helped me. I faced the exact issue. Thanks a ton.
