### ISSUE TITLE
Insufficient cpu - virtual-kubelet - GKE + Azure ACI Provider

### ISSUE THREAD

**Issue by Romiko** [kubernetes/kubernetes#96592]
Environment summary
Provider ACI
https://github.com/virtual-kubelet/azure-aci/tree/master/charts

Version latest

K8s Master Info
1.16.13-gke.401

Helm Chart

Issue Details
I deployed the Virtual-Kubelet in GKE to use the Azure Container Instances. I am able to successfully schedule pods to Azure.

However the virtual-kubelet is causing an issue in the GKE cluster. Existing pods that run on physical nodes such as prometheus get unscheduled due to insufficient CPU.

e.g.
alertmanager-prometheus-operator-alertmanager-0
Warning FailedScheduling 7m12s (x33 over 12m) default-scheduler 0/4 nodes are available: 1 node(s) didn't match node selector, 3 Insufficient cpu.

The above looks good, I have 3 physical nodes and 1 virtual node with taints to not allow scheduling.

I though I needed to scale out the cluster, which I did, but GKE even warned me that I have too many nodes as I am not using much CPU. So I think this is a bug since the cluster is under utilized. It seems the the Kubernetes cluster in GKE is miss calculating CPU requirements when there is a virtual node?

Any ideas why the Virtual Node would cause my other pods scheduled for normal nodes to stop working, why would GKE interpret insufficient CPU as soon as I have a virtual node? I double checked the cluster and CPU utilization is very low.

Repo Steps
Setup a GKE cluster.
Setup an Azure subscription, with VNET and Subnet.

Run the helm chart with values similar to below.

`
nodeName: "virtual-node-australia-east"

provider: azure

rbac:
install: true

providers:
azure:
targetAKS: false
clientId: dasd
clientKey: "{{ requiredEnv "VIRTUAL_KUBELET_SERVICE_PRINCIPAL_KEY" }}"
tenantId: aasdasd
subscriptionId: 2b588asdasd
aciResourceGroup: sc_dev_aci_aae
aciRegion: australiaeast
masterUri: https://3x.x.x.x
vnet:
enabled: true
vnetResourceGroup: sc_dev_aci_aae
vnetName: sc_dev_aci_aae
subnetName: aci-shared
subnetCidr: 10.0.0.0/16
clusterCidr: 10.176.0.0/14
kubeDnsIp defaults to 10.0.0.10 if not specified
kubeDnsIp: 10.179.240.10
`

Any help is appreciated.

/sig scheduling

**Comment by Romiko** [comment]
The prometheus pod that got unscheduled has the following limits.

   Limits:
      cpu:     100m
      memory:  25Mi
    Requests:
      cpu:        100m
      memory:     25Mi

Looking at the cluster, there is over 90% cpu available on all nodes. When I remove the aci  virtual node, pods return back to normal.

**Comment by Romiko** [comment]
Update. I think I found the cause. When deploying the virtual-kubelet chart for ACI provider, it causes a lot of kube-dns pods to spawn. Not sure why...

![image](https://user-images.githubusercontent.com/579058/99162531-c6bcde00-2752-11eb-8ab3-dfa0a026aa99.png)

**Comment by Romiko** [comment]
Temporary fix
`
kubectl scale --replicas=0 deployment/kube-dns-autoscaler --namespace=kube-system
kubectl scale --replicas=1 deployment/kube-dns --namespace=kube-system
`

**Comment by neolit123** [comment]
> However the virtual-kubelet is causing an issue in the GKE cluster.

hello, virtual kubelet is not a project originating from kubernetes/kubernetes.
it is a fork of the regular kubelet and it's repository is located here:
https://github.com/virtual-kubelet/virtual-kubelet

you can also try contacting Azure ACI / GKE support.

if you find a bug in core kubernetes, please open a new issue.

thanks
/remove-kind bug
/kind support
/close
