### ISSUE TITLE
[Failing Test] ci-kubernetes-kubemark-100-gce-scheduler

### ISSUE THREAD

**Issue by jkaniuk** [kubernetes/kubernetes#96612]
**Which jobs are failing**:
ci-kubernetes-kubemark-100-gce-scheduler
**Which test(s) are failing**:
pod-affinity
**Since when has it been failing**:
2020-11-14
**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-100-scheduler
**Reason for failure**:
```
ClusterLoaderV2: pod-affinity overall (testing/density/config.yaml) expand_less | 27m44s
[measurement call WaitForControlledPodsRunning - WaitForRunningSaturationDeployments error:
1 objects timed out: Deployments: test-3uha63-1/saturation-deployment-0
measurement call PodStartupLatency - SaturationPodStartupLatency error:
pod startup: too high latency 99th percentile: got 16m42.425444861s expected: 5m30s]
```
**Anything else we need to know**:
/sig scheduler
/sig scalability
/cc @adtac

**Comment by adtac** [comment]
Looking at the job history, it appears that problems with pod-affinity's performance began some time around the 21st of October: https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-100-gce-scheduler?buildId=1323327322832506880

There weren't any changes to interpodaffinity around that time: https://github.com/kubernetes/kubernetes/commits/master/pkg/scheduler/framework/plugins/interpodaffinity

The failure definitely has something to do with the scheduler being really slow. After scheduling the first 2,000 pods quickly, the throughput drops quickly as shown in this graph of number of scheduled pods vs time:

![chart](https://user-images.githubusercontent.com/7521600/99973467-cd101300-2d6d-11eb-8de6-d62222462075.png)

**Comment by jkaniuk** [comment]
Testgrid is green now
