### ISSUE TITLE
Enabling AlwaysPullImages admission causes existing Pods cannot be updated

### ISSUE THREAD

**Issue by bjrara** [kubernetes/kubernetes#96624]
**What happened**:
We enabled AlwaysPullImages admission in an existing cluster, and found annotations/labels/finalizers of existing Pods whose  imagePullPolicy configured as `IfNotPresent` could not be updated.

AlwaysPullImages admission mutated containerSpec by [changing imagePullPolicy from `IfNotPresent` to `Always`](https://github.com/kubernetes/kubernetes/blob/205d5c58296357365bfa834ecabb384c1c1042c3/plugin/pkg/admission/alwayspullimages/admission.go#L69). And this change later got denied by Pod validation. 
```
# * spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)
#   core.PodSpec{
#       Containers: []core.Container{
#               {
#                       ... // 15 identical fields
#                       TerminationMessagePath:   "/dev/termination-log",
#                       TerminationMessagePolicy: "File",
# -                     ImagePullPolicy:          "Always",
# +                     ImagePullPolicy:          "IfNotPresent",
```
It also caused terminating Pods with finalizers stuck forever until we removed AlwaysPullImages admission. 

**What you expected to happen**:
Existing Pods are not affected by AlwaysPullImages admission controller.

**How to reproduce it (as minimally and precisely as possible)**:
1. Configure the kube-apiserver with AlwaysPullImages admission controller disabled
2. Create a Pod with imagePullPolicy configured as `IfNotPresent` in its containers
3. Enable AlwaysPullImages admission controller
4. Add annotation to Pod

**Anything else we need to know?**:
If this is confirmed a bug, I can submit a PR to fix this.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-290+09322e8676124e", GitCommit:"09322e8676124e3928db73ebdf5238f3c562dda7", GitTreeState:"clean", BuildDate:"2020-11-05T23:18:55Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
seems to be a bug. 
/assign

**Comment by pacoxu** [comment]
@bjrara try to fix it in #96668

When AlwaysPullImages is disabled, you cannot update imagePullPolicy of pod. The error message is the same as yours. imagePullPolicy is immutable.

When AlwaysPullImages is enabled, old pod(with imagePullPolicy=ifNotPresent) update will change imagePullPolicy as well. 

Workaround: recreated pod -_-

**Comment by bjrara** [comment]
@pacoxu Thanks for the fixes. I still have questions regarding the PR.
Why don't we just ignore Update in the admission, but choose update spec instead?

**Comment by pacoxu** [comment]
> @pacoxu Thanks for the fixes. I still have questions regarding the PR.
> Why don't we just ignore Update in the admission, but choose to update spec instead?

This is another fix option. I'm not sure which is better. 
The pod will be still ifNotPresent after updating,  even if the AlwaysPullImages is enabled.

Which is expected behavior?

**Comment by bjrara** [comment]
@pacoxu In my case, I would expect the admission not to touch existing Pods. Just want to make sure if there's any concerns.

**Comment by liggitt** [comment]
> Why don't we just ignore Update in the admission

I would recommend ignoring pod updates in AlwaysPullImages *if* the update does not change the set of image names referenced by containers in the pod.

**Comment by pacoxu** [comment]
> > Why don't we just ignore Update in the admission
> 
> I would recommend ignoring pod updates in AlwaysPullImages _if_ the update does not change the set of image names referenced by containers in the pod. Changing images inline in a pod update is unusual, and that change would allow unrelated updates (to annotations, labels, etc) to proceed

Agree.  @liggitt

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/pull/96668 is updated .

**Comment by bjrara** [comment]
This issue is fixed by https://github.com/kubernetes/kubernetes/pull/96668
