### ISSUE TITLE
Support registering restclient metrics against non-legacyregistry prometheus registry

### ISSUE THREAD

**Issue by adammw** [kubernetes/kubernetes#96621]
**What would you like to be added**:
A register method or similar which takes in a registry as an argument, so that restclient metrics can be exposed to other prometheus registries without having to either duplicate the logic, or force the use of the legacyregistry which is marked as deprecated.

**Why is this needed**:
Currently the `k8s.io/component-base/metrics/prometheus/restclient` package registers all metrics on pkg init on the component-base legacyregistry, making it impossible to use with other prometheus default registries. 

/sig api-machinery

**Comment by leilajal** [comment]
cc @logicalhan
