### ISSUE TITLE
Calico is frequently down

### ISSUE THREAD

**Issue by popooja-8** [kubernetes/kubernetes#96625]
I am installing 3 node k8s cluster, calico will be stable for 1 or 2 days, again after that it goes down. After describing POD it says BGP not established, but Internal IPs are pinging.(after rebooting calico will come up, but again it goes down, rebooting as rework is not possible since some of the suites are running in background).

[root@master ~]# kubectl describe po calico-node-nwvgh -n kube-system
Name:                 calico-node-nwvgh
Namespace:            kube-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 worker1/192.168.56.71
Start Time:           Tue, 10 Nov 2020 09:23:32 +0530
Labels:               controller-revision-hash=6bfdf56d8
                      k8s-app=calico-node
                      pod-template-generation=1
Annotations:          <none>
Status:               Running
IP:                   192.168.56.71
IPs:
  IP:           192.168.56.71
Controlled By:  DaemonSet/calico-node
Init Containers:
  upgrade-ipam:
    Container ID:  docker://cc001dc5ed7f203677993f899e06a83ccd14a1aff59df93671335eb867bc1d30
    Image:         calico/cni:v3.15.2
    Image ID:      docker-pullable://docker.io/calico/cni@sha256:ab530cb190ef2cffba9e82260b69604705d7dc838b538a134761f59b15be7221
    Port:          <none>
    Host Port:     <none>
    Command:
      /opt/cni/bin/calico-ipam
      -upgrade
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 10 Nov 2020 09:23:47 +0530
      Finished:     Tue, 10 Nov 2020 09:23:47 +0530
    Ready:          True
    Restart Count:  0
    Environment:
      KUBERNETES_NODE_NAME:        (v1:spec.nodeName)
      CALICO_NETWORKING_BACKEND:  <set to the key 'calico_backend' of config map 'calico-config'>  Optional: false
    Mounts:
      /host/opt/cni/bin from cni-bin-dir (rw)
      /var/lib/cni/networks from host-local-net-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-sxxcq (ro)
  install-cni:
    Container ID:  docker://994d33ffd3b35c33b4c4b3753bcbc77f53feb71c4fd60f5567a8ca6c06e37f69
    Image:         calico/cni:v3.15.2
    Image ID:      docker-pullable://docker.io/calico/cni@sha256:ab530cb190ef2cffba9e82260b69604705d7dc838b538a134761f59b15be7221
    Port:          <none>
    Host Port:     <none>
    Command:
      /install-cni.sh
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 10 Nov 2020 09:23:48 +0530
      Finished:     Tue, 10 Nov 2020 09:23:48 +0530
    Ready:          True
    Restart Count:  0
    Environment:
      CNI_CONF_NAME:         10-calico.conflist
      CNI_NETWORK_CONFIG:    <set to the key 'cni_network_config' of config map 'calico-config'>  Optional: false
      KUBERNETES_NODE_NAME:   (v1:spec.nodeName)
      CNI_MTU:               <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      SLEEP:                 false
    Mounts:
      /host/etc/cni/net.d from cni-net-dir (rw)
      /host/opt/cni/bin from cni-bin-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-sxxcq (ro)
  flexvol-driver:
    Container ID:   docker://af5bbe5ae14cce12956af331ec08ae42e801b16a29373a0a7c04d3013b9bc70f
    Image:          calico/pod2daemon-flexvol:v3.15.2
    Image ID:       docker-pullable://docker.io/calico/pod2daemon-flexvol@sha256:3ad57e6bf32098e61909cc3bfc7266500a610d9ea4309ec6f8e6275fc132102a
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 10 Nov 2020 09:24:06 +0530
      Finished:     Tue, 10 Nov 2020 09:24:07 +0530
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /host/driver from flexvol-driver-host (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-sxxcq (ro)
Containers:
  calico-node:
    Container ID:   docker://d5af93f4ea7d3270a77601d2b1654e174f80c998a482f263ee4ecc66123f1a24
    Image:          calico/node:v3.15.2
    Image ID:       docker-pullable://docker.io/calico/node@sha256:b03990be48e252c3b046b2f56bd7bbc2ed35c6026c0dcee3b50a1c834deb0bfb
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Tue, 10 Nov 2020 09:24:26 +0530
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:      250m
    Liveness:   exec [/bin/calico-node -felix-live -bird-live] delay=10s timeout=1s period=10s #success=1 #failure=6
    Readiness:  exec [/bin/calico-node -felix-ready -bird-ready] delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      DATASTORE_TYPE:                     kubernetes
      WAIT_FOR_DATASTORE:                 true
      NODENAME:                            (v1:spec.nodeName)
      CALICO_NETWORKING_BACKEND:          <set to the key 'calico_backend' of config map 'calico-config'>  Optional: false
      CLUSTER_TYPE:                       k8s,bgp
      IP:                                 autodetect
      CALICO_IPV4POOL_IPIP:               Always
      CALICO_IPV4POOL_VXLAN:              Never
      FELIX_IPINIPMTU:                    <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      FELIX_VXLANMTU:                     <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      FELIX_WIREGUARDMTU:                 <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      CALICO_DISABLE_FILE_LOGGING:        true
      FELIX_DEFAULTENDPOINTTOHOSTACTION:  ACCEPT
      FELIX_IPV6SUPPORT:                  false
      FELIX_LOGSEVERITYSCREEN:            info
      FELIX_HEALTHENABLED:                true
    Mounts:
      /lib/modules from lib-modules (ro)
      /run/xtables.lock from xtables-lock (rw)
      /var/lib/calico from var-lib-calico (rw)
      /var/run/calico from var-run-calico (rw)
      /var/run/nodeagent from policysync (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-sxxcq (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  lib-modules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:
  var-run-calico:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/calico
    HostPathType:
  var-lib-calico:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/calico
    HostPathType:
  xtables-lock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/xtables.lock
    HostPathType:  FileOrCreate
  cni-bin-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/cni/bin
    HostPathType:
  cni-net-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/cni/net.d
    HostPathType:
  host-local-net-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/cni/networks
    HostPathType:
  policysync:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/nodeagent
    HostPathType:  DirectoryOrCreate
  flexvol-driver-host:
    Type:          HostPath (bare host directory volume)
    Path:          /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds
    HostPathType:  DirectoryOrCreate
  calico-node-token-sxxcq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  calico-node-token-sxxcq
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     :NoSchedule
                 :NoExecute
                 CriticalAddonsOnly
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason            Age                            From              Message
  ----     ------            ----                           ----              -------
  Warning  DNSConfigForming  19m (x8095 over 7d1h)          kubelet, worker1  Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 10.43.2.5 10.158.100.6 10.53.69.69
  Warning  Unhealthy         <invalid> (x34280 over 4d23h)  kubelet, worker1  (combined from similar events): Readiness probe failed: 2020-11-17 05:38:39.529 [INFO][1814] confd/health.go 180: Number of node(s) with BGP peering established = 0
calico/node is not ready: BIRD is not ready: BGP not established with 192.168.56.70,192.168.56.72

**Comment by pacoxu** [comment]
@popooja-8  

If it is a calico issue, you may open issue in https://github.com/projectcalico/calico/issues.

If this is a kube issue, please add more logs or cluster info in the description.

**Comment by neolit123** [comment]
hi, please log a ticket in the Calico issue tracker.
if the Calico maintainers think this is a bug in core k8s, please open a new issue here with the feedback from them and reproduction steps.

thanks

/kind support
/close
