### ISSUE TITLE
Towards a definition of Windows Conformance

### ISSUE THREAD

**Issue by adelina-t** [kubernetes/kubernetes#96639]
As Kubernetes on Windows continues to grow, there is a growing need to be able to define Conformance for clusters containing Windows Nodes.

### Current conformance definition & process

Details: https://github.com/cncf/k8s-conformance

> All vendors are invited to submit conformance testing results for review and certification by the CNCF, which formally certifies conformant implementations.

> This program gives end users the confidence that when they use a Certified Kubernetes product they can rely on a high level of common functionality. It gives Independent Software Vendors (ISVs) confidence that if their customer is using a Certified Kubernetes platform that their software will behave as expected.

The current process to have a certified **conformant** distribution:

- https://github.com/cncf/k8s-conformance/blob/master/instructions.md
- Summary: tests are run via Sonobuy & submitted via PR to the cncf/k8s-conformance repo in a specific format described in docs.

GoldenList of all conformance tests: https://github.com/kubernetes/kubernetes/blob/master/test/conformance/testdata/conformance.yaml

Is this a goal?

#### NodeConformance vs Conformance

Currently there is no exact definition on what NodeConformance means. An ongoing discussion can be found [here](https://github.com/kubernetes/test-infra/issues/18973) and [here](https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg/edit), in the sig-node meeting notes.

Highlights of discussion: 
> **Tests tagged with NodeConformance were intended to include sig-node e2e tests agnostic of cloud providers, OS distributions and container runtimes and expected to pass for every PR**

> **Today, the NodeConformance tag is rarely added to new tests and details on it can only be found here in the documentation. One test was added July 8th, 2020, and prior to that, November 6th, 2019 was the last time it was added.**

As well, there is no current process by which you describe a node as conformant.
There is no process by which one test gets promoted to NodeConformance ( However, there is a Conformance promotion process ).

Open questions:
- Does the fact that a cluster containing Windows Nodes pass all NodeConformance tagged tests make it Conformant?

##### State of e2e tests covering a K8s Node:

- There are 145 tagged NodeConformance tests in e2e suite, out of which only 98 can run on Windows.

- There is overlap in Conformance & NodeConformance tests:
    - 89 tests are marked both Conformance & NodeConformance. 

- There are 28 separate tests marked sig-windows, that test Windows specific features ( GMSA ) or attempt to replace NodeConformance tests marked ( LinuxOnly ).

##### What does conformance mean for a Windows Node / Cluster Containing Windows nodes?

- Pass Conformance & NodeConformance tagged tests ( except LinuxOnly )
- Pass sig-windows tagged tests?
	- some sig-windows tests are testing specific features like GMSA, this most likely shouldn't be part of a Windows Conformance suite.
- CNI: does passing all sig-networking tagged tests from the Conformance suite make the node conformant? Are there specific tests to cover for Windows?
- Isolation Mode: Process vs HyperV Containers.
	- Can we have both at the same time in a cluster?
- Hybrid Clusters: ?
- CSI: ?
- Future Features: Privileged Containers, LCOW

Related: https://github.com/kubernetes/enhancements/issues/1618

**Comment by BenTheElder** [comment]
/sig architecture
/sig testing
/area conformance

The #k8s-conformance group is almost certainly the right place to discuss this, that team owns the conformance program from the kubernetes side, sponsored by SIG arch with input from testing.

AIUi NodeConformance is currently just a set of tests SIG node expects to pass and is not under the conformance program etc.
I think node intended for it to be eventually but this is not the case.

This thread sounds like another pass at "profiles cc @spiffxp.

**Comment by jayunit100** [comment]
Good points thanks for summarizing , 

1) since There are only 15 or so sig-windows tests .... I wonder what the right model would be for including the 98 other tests you mentioned into a conformance definition ? 

2) Do  we need a new OS neutral conformance definition , so that we can get away from the Linux/Windows semantics ? I think maybe that’s the only way out .... otherwise we’ll constantly be juggling windows and Linux definitions and we won’t be able to ever account for different OSs of the future if one were to arrive .

3) on the CNI front this is also tricky bc different vendors support different network policy semantics for named port and loopback and so on... so we haven’t fully solved that problem yet but in general your answer is mostly right ... passing all non disruptive sig-network tests is the defacto standard . So I think .....short term..... that working on ' ' making sig-network test tags comprehensive is sufficient  unless we ever get a “OS neutral conformance suite “

**Comment by BenTheElder** [comment]
2) nice idea but I'm personally going to say no. There are core behaviors that are expected on Linux that have long been in conformance predating any windows functionality that windows cannot replicate (think host resolution in pods). We'd be remiss to allow clusters to start failing this.

There's also no such thing as a purely windows cluster, and the portability of workloads leveraging Linux functionality is still important and likely touched the majority of Kubernetes usage (think things like fsGroup, PID limit ...), removing this sort of thing from conformance would be a pretty major regression.

I think windows will need its own definition similar to what is suggested in the OP, and I think that discussion needs to be had with the conformance working group.

**Comment by adelina-t** [comment]
I agree with @BenTheElder , I don't think there is a way to abstract core behaviours when it comes to Linux vs. Windows. The fact of the matter remains, despite the effort in bridging the gap between the two, they are two differently designed systems. For example, even when considering something as simple as file permissions, the two OSes use very different models. Also, we will have situations where Windows will have it's own functionality that would need to be validated as conformance. We must also be mindful that in future, there are other scenarios, like LCOW ( Linux Containers on Windows ) that would need to be validated by the Linux conformance tests, though that is a little bit further into the future.

I will keep this issue updated as the discussions are ongoing with conformance working group.

**Comment by jayunit100** [comment]
Ok, makes sense. So the definition of conformance for a mixed OS cluster ... is going to be that the "OS specific" conformance tests pass, and the Linux ones pass as well?

**Comment by dims** [comment]
cc @lachie83

**Comment by jayunit100** [comment]
Working with peri on a Kep for this, anyone want to own part of the story ?
