### ISSUE TITLE
Deamonset pods.status = "Ready"  even though a node is off line

### ISSUE THREAD

**Issue by joeburke30** [kubernetes/kubernetes#96641]
**What happened**:
Pods show "Ready" but node is NotReady / offline

**What you expected to happen**:
The pods assigned to the "NotReady" node should should not listed as Ready

**How to reproduce it (as minimally and precisely as possible)**:
see above.
1. 3 node kubernetes (1.18.3) cluster in a VMWare environment.
2. Running 4 Daemonsets.   
3. Pods deployed and running as expected with Ready state.
4. 1 VM/Node is turned off
5. get nodes = shows the turned off node as NotReady 
6. get pods = shows all 12 pod entries, and all are Ready
7. describe ds = shows a replica count of 2 (because there are 2 active nodes) which is accurate

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:  VMWare nodes 
- OS (e.g: `cat /etc/os-release`): Debian Buster
- Kernel (e.g. `uname -a`):  
- Install tools:   Rancher/RKE to install the kubernetes environment
- Network plugin and version (if this is a network-related bug):   N/A
- Others:

**Comment by krmayankk** [comment]
@joeburke30 how long did you wait ? There is an eviction period , after which the pod on the not ready node will get evicted

**Comment by joeburke30** [comment]
I should have added that to the original ticket...  This is seen consistently.  I waited several hours on one test and a day+ on a second test.

Where can I find the evicted time configuration?

**Comment by ruiwen-zhao** [comment]
> I should have added that to the original ticket... This is seen consistently. I waited several hours on one test and a day+ on a second test.
> 
> Where can I find the evicted time configuration?

See `--pod-eviction-timeout duration` on https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/, which is 5 min by default.

**Comment by joeburke30** [comment]
thanks for the response....  however at times well beyond the 5 minute mark, the pods are still showing as Ready.    This feels like its a bug.  What additional information can I provide to show this is the case?

**Comment by joeburke30** [comment]
Based upon the link, I see that the kube controller  is monitoring:  replication controller, endpoints controller, namespace controller, and serviceaccounts controller.    My case is a DaemonSet which, based upon the replication controller docs, is out of scope.

**Comment by chentaoz** [comment]
The Daemonset is not evicted by default. So your observation is the intention of k8. Please refer to https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions
