### ISSUE TITLE
edit quota silent fail.

### ISSUE THREAD

**Issue by sobngwi** [kubernetes/kubernetes#96645]
**What happened**:
- I create a resource quota successfully
- I test a pod creation to figure out the resource quota limitation : OK
- i run the command : kubectl edit quota my-res-quota    NotOK ( for updated any value eg hard.pods , or hard.requests.cpu ). The command successfully ended with the message : resourcequota/bug-on-edit-quota-updated edited .
However the kubectl describe quota quota still display the old values 

**What you expected to happen**:
I expect the modified vale to be updated : eg hard.pods initially at value 1 to be updated to 2 as i have changed it during the edit session.
**How to reproduce it (as minimally and precisely as possible)**:
- create a resource quota withe requests.cpu, requests.memory and pods values.
- check the creation is ok with the kubectl describe command
- update the value of pods (eg 1 to 2) with the kubectl edit quota command.
- check that the update is NotOK is ok with the kubectl describe command
- create a pod, old quota before update sill applying.
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`):
Linux control2.example.com 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by sobngwi** [comment]
Hi, new information on this bug. I thing, i updated the wrong field ( in the status , not in the spec) : 
spec:
  hard:
    pods: "2"
    requests.cpu: "1"
    requests.memory: 2G
status:
  hard:
    pods: "2"
    requests.cpu: "1"
    requests.memory: 2G
  used:
    pods: "0"
    requests.cpu: "0"
    requests.memory: "0"
--- 
However the edit was successfull 
As  the following  message is displayed  : 
resourcequota/bug-on-edit-quota-updated edited

--- But the : 
used field value have not been changed as shown in the describe command result.

Definitively, I thing the modification of the edit value should not be allow to avoid this misunderstanding .

regards.

**Comment by pacoxu** [comment]
Do you mean that you edit the status part of quota?

`editing the status` is not acceptable.

```
apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: "2021-03-29T03:42:46Z"
  name: webs-compute-resources
  namespace: default
  resourceVersion: "2047"
  uid: 1542afe9-e08b-4bcd-be61-bc9eb0c89b57
spec:
  hard:
    limits.cpu: "26"
    limits.memory: 62Gi
    pods: "10"
status:
  hard:
    limits.cpu: "26"
    limits.memory: 62Gi
    pods: "10"
  used:
    limits.cpu: "3"
    limits.memory: 600m
    pods: "3"
```

You can only edit the `spec.hard` part in this example.

If you modify the `status.hard.pods`, it shows `resourcequota/webs-compute-resources edited` but nothing is changed.

An easy way to debug into the process is running `kubectl edit quota --v=9`.
```
I0329 11:48:51.472975   77933 request.go:1107] Request Body: {"status":{"hard":{"pods":"11"}}}
```
