### ISSUE TITLE
Test APF beta with enablement combos

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#96648]
I think we know the most common combos work, but we should verify that apiserver either does something reasonable or refuses to start with a polite error message in the following flag combinations:

| | enablement flag | feature gate | beta api group | alpha api group |
|---|---|---|---|---|
| [ ] | on | on | on | on |
| [ ] | on | on | on | off |
| [ ] | on | on | off | on |
| [ ] | on | on | off | off |
| [ ] | on | off | on | on |
| [ ] | on | off | on | off |
| [ ] | on | off | off | on |
| [ ] | on | off | off | off |
| [ ] | off | on | on | on |
| [ ] | off | on | on | off |
| [ ] | off | on | off | on |
| [ ] | off | on | off | off |
| [ ] | off | off | on | on |
| [ ] | off | off | on | off |
| [ ] | off | off | off | on |
| [ ] | off | off | off | off |

Additionally we should verify that on/off/on combos work.

We've already documented that you can't run 1.19 with alpha on and 1.20 in the same cluster simultaneously.

**Comment by adtac** [comment]
wouldn't it be 3^4 combinations? one could leave out some flags from the command line entirely, but I suppose that scenario would be covered by the row in the table corresponding to the default value

**Comment by lavalamp** [comment]
I don't think we need to be 100% exhaustive unless it's really easy.

**Comment by MikeSpreitzer** [comment]
@MikeSpreitzer
