### ISSUE TITLE
generateEvent timestamp is ignored

### ISSUE THREAD

**Issue by bboreham** [kubernetes/kubernetes#96642]
`timestamp` is defined here but never used. https://github.com/kubernetes/kubernetes/blob/62321af7ab1c8abb44f5d99e7af560b22bd0a7c6/staging/src/k8s.io/client-go/tools/record/event.go#L326

As this is an unexported method it doesn't affect anyone, just a small point of confusion for the reader.

/sig api-machinery
/kind bug

**Comment by fedebongio** [comment]
/triage accepted
removing triage since the PR seem to be fixing the issue
/assign @bboreham 
Please close when merged! thank you
