### ISSUE TITLE
Verify/enforce user/group invariant

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#96647]
While moving APF to beta (see comments on https://github.com/kubernetes/kubernetes/pull/96527), we discovered that the integration tests commonly present users which are not members of any groups. We had thought that the system enforced membership in either the authenticated or unauthenticated group.

If this is supposed to be a system invariant (as we thought), we'd like to ask SIG Auth:
* Please fix the integration tests
* Please add e.g. logging so that if real, operational clusters hit this there's at least a log message and people will file bugs.

/sig auth

**Comment by MikeSpreitzer** [comment]
Can I suggest also, if this is a real invariant, that it be documented in some place(s) likely to be read?

**Comment by ian-fox** [comment]
Is anybody working on this? Seems like a good first issue and I'd like to contribute.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/107276 fixes the authenticator configured in one of the integration test API server startup helpers which resolved this issue for [most integration tests](https://github.com/kubernetes/kubernetes/pull/107276#issuecomment-1016538912).

Remaining tests that still need fixing that are encountering unexpected users look to be ones set up to specifically test auth paths:

```
egrep 'apf_controller.*string\(nil\).*catch-all' junit.stdout  | jq -r '"\(.Package)#\(.Test)"' | sort | uniq

k8s.io/kubernetes/test/integration/auth#TestBootstrapTokenAuth
k8s.io/kubernetes/test/integration/auth#TestLocalSubjectAccessReview
k8s.io/kubernetes/test/integration/auth#TestRBAC
k8s.io/kubernetes/test/integration/auth#TestSelfSubjectAccessReview
k8s.io/kubernetes/test/integration/auth#TestSubjectAccessReview
k8s.io/kubernetes/test/integration/auth#TestWebhookTokenAuthenticator
k8s.io/kubernetes/test/integration/auth#TestWebhookTokenAuthenticatorCustomDial
k8s.io/kubernetes/test/integration/serviceaccount#TestServiceAccountAutoCreate
k8s.io/kubernetes/test/integration/serviceaccount#TestServiceAccountTokenAuthentication
k8s.io/kubernetes/test/integration/serviceaccount#TestServiceAccountTokenAutoCreate
k8s.io/kubernetes/test/integration/serviceaccount#TestServiceAccountTokenAutoMount
```

**Comment by liggitt** [comment]
#107644 open to fix remaining integration test users
