### ISSUE TITLE
kubeadm.exe join --node-name is ignored

### ISSUE THREAD

**Issue by ag3man** [kubernetes/kubernetes#96654]
**What happened**:
running kubeadm.exe join --node-name ip-10-xxx-65-130.ec2.internal is ignored during bootstrapping of a Windows node in AWS.

While using the aws-cloud-controller-manager this node is then rejected from joining the cluster because it is looking for the EC2 hostname rather then the AWS Private DNS name.

You can see in the logs below that **ec2amaz-1atkhmi** is an existing instance that was joined prior to deploying aws-cloud-controller-manager to the cluster. Whereas **ec2amaz-vstpi3i** is a new node joining then being rejected because it cannot be found and it is likely consider rogue.

```
E1117 22:23:33.532276       1 node_controller.go:251] error fetching node by provider ID: Invalid format for AWS instance (), and error by node name: getInstanceByNodeName failed for "ec2amaz-1atkhmi" with "instance not found"
I1117 22:24:59.838264       1 node_controller.go:320] This node ec2amaz-vstpi3i is registered without the cloud taint. Will not process.
I1117 22:25:03.818918       1 node_lifecycle_controller.go:156] deleting node since it is no longer present in cloud provider: ec2amaz-vstpi3i
I1117 22:25:03.819233       1 event.go:291] "Event occurred" object="ec2amaz-vstpi3i" kind="Node" apiVersion="" type="Normal" reason="Deleting node ec2amaz-vstpi3i because it does not exist in the cloud provider" message="Node ec2amaz-vstpi3i event: DeletingNode"
```

```
NAME                            STATUS   ROLES    AGE     VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                    KERNEL-VERSION                  CONTAINER-RUNTIME
ec2amaz-1atkhmi                 Ready    <none>   2d16h   v1.19.4   10.xxx.67.192   <none>        Windows Server Datacenter   10.0.17763.1577                 docker://19.3.12
ip-10-xxxx-65-213.ec2.internal   Ready    master   2d17h   v1.19.4   10.xxx.65.213   <none>        Amazon Linux 2              4.14.193-149.317.amzn2.x86_64   docker://19.3.13
```

**What you expected to happen**:
Windows Node to join with --node-name provided

**How to reproduce it (as minimally and precisely as possible)**:
deploy Master node 

Windows Node:
    curl https://github.com/kubernetes-sigs/sig-windows-tools/releases/latest/download/PrepareNode.ps1 -o C:\k\PrepareNode.ps1
    C:\k\PrepareNode.ps1 -KubernetesVersion v1.19.4
join Windows node to cluster with kubeadm join --node-name --token xxx --discovery-token-ca-cert-hash xxx

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`):  Windows Server Datacenter   10.0.17763.1577
- Kernel (e.g. `uname -a`): na
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
hi, please log this ticket in https://github.com/kubernetes-sigs/sig-windows-tools/

/close
/sig cluster-lifecycle
