### ISSUE TITLE
Allow the configuration of the interval of container runtime healthcheck 

### ISSUE THREAD

**Issue by Mriesewijk2** [kubernetes/kubernetes#96664]
**What would you like to be added**:

Currently the interval between health checks from the kubelet to the container runtime seems to be hardcoded here: 
https://github.com/kubernetes/kubernetes/blob/147a120948482e49f93e7d8896f8e32b0418c2d8/pkg/kubelet/kubelet.go#L124-L125
And used for a healthcheck here: 
https://github.com/kubernetes/kubernetes/blob/147a120948482e49f93e7d8896f8e32b0418c2d8/pkg/kubelet/kubelet.go#L651-L656
This value should be configurable through the kubelet config file.

**Why is this needed**:
AFAIK, we cannot influence how fast Kubernetes recognizes that the container runtime has failed. How fast a node is marked NotReady when the kubelet stops posting status updates can be influenced, but in case the container runtime fails (and the node therefore becomes unresponsive to (re)starting pods) the hardcoded value is used, this hardcoded value is (a lot) longer than the values that can be configured for NodeStatusFrequencyUpdate, for example. I think this is important for the container runtime healthcheck to be configurable as well.
The current comment  ` // Max amount of time to wait for the container runtime to come up.`  suggest to me that the value is used as a timeout when the node is starting. A fixed timeout during starting of the node makes sense to me, but using that value for healthchecks during operation does not.

**Comment by tharun208** [comment]
I like to work on this

**Comment by ehashman** [comment]
Hi @tharun208, if you are interested in working on this, can you please bring this up for discussion with SIG Node? You add it to the [agenda for the next meeting](https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg/edit) or ask people on Slack to asynchronously indicate interest on this issue.
