### ISSUE TITLE
Exec command via API is no longer supported?

### ISSUE THREAD

**Issue by aqualovers** [kubernetes/kubernetes#96663]
As I remember, there was a API operation corresponding to `kubectl exec`,

seems like `POST /api/v1/namespaces/{namespace}/pods/{name}/exec`.

But in current API Reference Doc, I cannot find contents about that.

I checked `kubectl exec` command still works fine, but how about API?

That feature has removed in recent versions of kubernetes?

**Comment by krmayankk** [comment]
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#exec i see this, i dont see anything documented here https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/ . But for sure exec is not being removed from the API. 

/sig docs might have some info
