### ISSUE TITLE
kubectl wait "pod" --for=delete errors out if no matching resources are found

### ISSUE THREAD

**Issue by trondhindenes** [kubernetes/kubernetes#96676]
**What happened**:
given an empty namespace (no pods), if running:
`kubectl wait "pod" --selector app.kubernetes.io/name=myapp --for=delete --timeout=500s`, kubectl errors with the message `error: no matching resources found`.

**What you expected to happen**:
kubectl should exit with status 0, since the condition to wait for is for all pods to be deleted, and that condition is already satisfied.

**How to reproduce it (as minimally and precisely as possible)**:
run the example kubectl command

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-16T17:18:52Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
Taking the liberty of skipping other version information, since this is (I assume) purely a client-side bug

**Comment by lingsamuel** [comment]
Seems like #90969 didn't fix it correctly:
https://github.com/kubernetes/kubernetes/blob/e64ebe01314b41fa68cff827a31ab133ec6963a4/staging/src/k8s.io/kubectl/pkg/cmd/wait/wait.go#L258-L260


#87747 #93365

**Comment by trondhindenes** [comment]
thanks for the quick fix!

**Comment by trondhindenes** [comment]
/remove-lifecycle stale - still an issue, I believe the PR is waiting for re-review
