### ISSUE TITLE
Incorrect behavior on scaling up when using behaviors config on HPA

### ISSUE THREAD

**Issue by DmitrySemchenok** [kubernetes/kubernetes#96671]
When configuring new behaviors section in HPA I faced two scenarios that I think are incorrect.
First one:
stabilizationWindowSeconds set up to 5 minutes for both scale up and scale down
min replica count 2
Application consumes big amount of resources during warm-up
0 minute: current replica count: 2
1 minute: desired replica count: 3 - no scale up stabilization window worked
2 minute: desired replica count: 1 (!) - scale up to  3 (max number from previous recommendations during stabilization window period)
![Algorithm](https://user-images.githubusercontent.com/13302750/99520165-d2ebaa00-29a3-11eb-8089-b088120ad182.png)

Second one 
Stabilization window for scale up 0
Stabilization window for scale down 5 minutes
min replica count 2
behavior set to scale up new pod in 2 minutes
scaleUp:
        policies:
        - type: Pods
          value: 1
          periodSeconds: 120
What happens:
0 minute: 2 replicas
1 minute : performance spike scale up to 3 (desired value 4)
2 minute : no spike no scale up
3 minute: no spike scale up to 4(!) - supposedly desired value 1 and supposedly worked this way because of scale down window set to 5 minutes picking max value from that 5 minutes window that was 4 replicas

Expected behaviors
1 Scenario no scale up for 5 minutes
2 Scenario correct measurement and no scale up when there is no need for it

**Environment**:
- Kubernetes version (use `kubectl version`): client 1.19.3 Server 1.19.0
- Cloud provider or hardware configuration: Azure aks

**Comment by josephburnett** [comment]
The HPA controller keeps a flat history of recommendations for stabilization.
![image](https://user-images.githubusercontent.com/1103629/102333122-4675dc80-3f8d-11eb-9248-e1eb7ddfb843.png)

When downscale stabilizing the maximum recommendation is selected.  Purple is pre-stabilized recommendation.  Green is final recommendation.  Blue is max recommendation within window.
![image](https://user-images.githubusercontent.com/1103629/102353206-0cb2cf00-3fa9-11eb-8b7b-b53bdd270251.png)

When upscale stabilization the minimum recommendation is selected. 
![image](https://user-images.githubusercontent.com/1103629/102353288-248a5300-3fa9-11eb-9cf3-25c8396cb68f.png)

However when both up and down scale stabilization is configured, the interpretation of the history changes depending on the direction of movement.  Red is the undesired, actuated recommendation.
![image](https://user-images.githubusercontent.com/1103629/102353793-dcb7fb80-3fa9-11eb-910a-5eca20eefc66.png)

What we want is to keep the stabilized recommendation within the envelope of the minimum and maximum over configured stabilization windows.  We should only move when the envelope forces a move.
![image](https://user-images.githubusercontent.com/1103629/102353952-20ab0080-3faa-11eb-9365-7dd38eac8099.png)

We first stabilize up and down, and check if the current value fits within it. If it does (or the range is "inverted"), we do nothing. If it does not, we emit the "nearest possible" value, which will be lower or upper bound, depending on where the current size is in relation to the range.

(thanks @konryd and kgolab@ for the paragraph above)
