### ISSUE TITLE
[Server-Side Apply] Prevent mutating admission controllers from corrupting managedFields

### ISSUE THREAD

**Issue by kwiesmueller** [kubernetes/kubernetes#96688]
This issue is meant as a space for discussing mutating webhooks regarding Server-Side Apply.

Primarily the problem recently reported in https://github.com/kubernetes/kubernetes/issues/96351.
As discovered in the issue it is possible for a mutating admission webhook to change the managedFields in a way that would break apply.

This can be "achieved" accidentally by running a webhook with an outdated version of client-go that doesn't understand managedFields yet.

In the specific case it seemed like the webhook did not know about managedFields and as a result computed a patch to remove them. The exact process is not clear yet, as we don't have access to the specific webhook.

In general, we should make it impossible to set invalid managedFields in the admission chain.

We have a few options to do that:
1. Validate managedFields after the admission chain and reset them to the state before admission on invalid fields.
  This would hide an error like an outdated admission hook. Right now we still have the chance to not hide errors, before going GA.
2. Validate managedFields after the admission chain and fail the request on invalid fields.
  Failing the request directly would break the user for something they can't directly fix and might need a Cluster-Admin for.
3. Validate managedFields after every admission controller and return an error to the controller on invalid fields.
  This might be better than failing the request itself, as the request could still succeed depending on the failure policy of the webhook.
4. [Track managedFields for admission controllers](https://github.com/kubernetes/enhancements/pull/1085) and overwrite changes done to them in the admission chain.
  It's still open for discussion if admission controllers should be able to change managedFields.
  If not, tracking their changes directly should be the goal eventually.
5. Always reset managed fields after mutation, i.e. discard any changes made by mutation, what-so-ever.

/sig api-machinery
/wg api-expression
/cc @apelisse

**Comment by apelisse** [comment]
I think one option that you possibly missed: Always reset managed fields after mutation, i.e. discard any changes made by mutation, what-so-ever.

**Comment by kwiesmueller** [comment]
Added, might be a small step towards 4. as we "fix" or workaround the error until we can track mutations.

**Comment by apelisse** [comment]
Let me attempt to split this issue into a few separate dimensions, which are not strictly orthogonal:
1. Do we want to track fields changed by admission-chain, and give them their own "managedfields"
   a. If we have managedFields for admission-chain, is there a relationship between the admission-change and the request that initiated the change or not?
2. Do we want to allow admission-chain to alter managedFields?
  a. If we do so, should we fail the request when the managedFields is corrupted
  b. If we don't, should we reject the request when they try

The problem in this issue is mostly related to that "2." I think.
