### ISSUE TITLE
Please take versioning seriously. 1.16 broke extensions/v1beta configs without any serious warning.

### ISSUE THREAD

**Issue by nojvek** [kubernetes/kubernetes#96682]
**What happened**:
GCP upgraded one of the clusters from 1.15 to 1.16

**What you expected to happen**:
minor version upgrades are backwards compatible and don't break things.

If you have a breaking change, update the major version. semver is a thing https://semver.org/. We should be able to know when k8s is going to break us. 

**How to reproduce it (as minimally and precisely as possible)**:
deployments with `apiVersion: "extensions/v1beta1",` don't work anymore.

**Anything else we need to know?**:
This broke the whole eng org from being able to deploy.

**Comment by wilsonehusin** [comment]
@nojvek we publish deprecations and removals on every minor release. [In 1.16 release notes](https://v1-16.docs.kubernetes.io/docs/setup/release/notes/#deprecations-and-removals), your specific issue was announced
> `daemonsets`, `deployments`, `replicasets` resources under `extensions/v1beta1` - use `apps/v1`

**Comment by nojvek** [comment]
Yeah, but why not cut a major version if you're gonna make breaking changes? 

One would assume 1.15 -> 1.16 is backwards compatible. Even cloud providers sometimes auto upgrade thinking this is harmless, but a breaking change is breaking change. 

The ask is to increase major version when you make a backwards incompatible change.

**Comment by liggitt** [comment]
Individual APIs included in Kubernetes releases graduate independently, and the pre-GA versions are deprecated and removed as described in https://kubernetes.io/docs/reference/using-api/deprecation-policy/

The versions removed in 1.16 were deprecated 18-24 months earlier, and the removal timeframes highlighted in release notes for multiple releases as well.

Not that it helps for the 1.16 APIs, but we have added better ways to raise visibility to use of deprecated APIs. Starting in 1.19, users of deprecated APIs receive warnings at time of use via kubectl with information about the future release in which the deprecated API will no longer be served, and what replacement version should be used. See https://kubernetes.io/blog/2020/09/03/warnings/ for details.

**Comment by nojvek** [comment]
Could someone explain why kubernetes doesn’t adopt semver?

I understand the need to close issues but this doesn’t address the core
issue.

Kubernetes versions have little meaning to them even though they look like
semver.

If kubernetes makes a breaking change, what is wrong with calling it v2?

Who cares if we’re at version 140. There is no automated way to know when a
kube version will bring down a cluster.

My ask is simple: please adopt semver. If you make a breaking change,
increase the major version.

Removing apis is a big deal.

**Comment by liggitt** [comment]
> Could someone explain why kubernetes doesn’t adopt semver?

A single semver doesn't map well to a release that includes multiple APIs at different maturity levels evolving independently. 

> If kubernetes makes a breaking change, what is wrong with calling it v2?

That is done on the individual API level.

> Who cares if we’re at version 140.

Frequently incrementing the major version due to dropping pre-release features/versions that are not actually used by a particular cluster muddies the signal semver is intended to provide.

> There is no automated way to know when a kube version will bring down a cluster.

Along those lines, the metrics published as part of the deprecation warnings feature in 1.19 allow introspecting which APIs will be removed in the next release, and whether there are active users of those APIs. Those can be used to gain automated visibility to whether an API about to be removed is being used. See https://kubernetes.io/blog/2020/09/03/warnings/#metrics for details.
