### ISSUE TITLE
kubectl explain redirect to a 404 page

### ISSUE THREAD

**Issue by survivant** [kubernetes/kubernetes#96697]
**What happened**:
````
 kubectl explain pod.spec.containers.resources.limits

KIND:     Pod
VERSION:  v1

FIELD:    limits <map[string]string>

DESCRIPTION:
     Limits describes the maximum amount of compute resources allowed. More
     info:
     https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
....
````

the URL (https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/) return a 404.

**What you expected to happen**:

I expect the link in the documentation to be valid

**How to reproduce it (as minimally and precisely as possible)**:

kubectl explain pod.spec.containers.resources.limits

**Anything else we need to know?**:

**Environment**:
````
kubectl version

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by lingsamuel** [comment]
I can access this URL.

**Comment by survivant** [comment]
but the URL in the docs from kubectl explain is : https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
 not https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/

there is "compute" as difference

**Comment by wawa0210** [comment]
Their final addresses are the same and redirected

**Comment by lingsamuel** [comment]
That's why there is a redirection. But sure, it should be changed.

**Comment by survivant** [comment]
wierd.  I was able to get it redirect 1-2 times now, but most of the time it's not.  probably a plugin in firefox that block the redirect 
![image](https://user-images.githubusercontent.com/191879/99610208-60002480-29df-11eb-9115-5d44b61f93f3.png)

**Comment by wawa0210** [comment]
/assign
I can try to fix this
