### ISSUE TITLE
Cleanup conformance image

### ISSUE THREAD

**Issue by wilsonehusin** [kubernetes/kubernetes#96692]
**What would you like to be modified**:
`k8s.gcr.io/conformance` image to be based on anything other than Docker Hub sourced `debian:stretch-slim`
https://github.com/kubernetes/kubernetes/blob/1c49b4425bf8c5b144e3ce7378b63351364ae8c6/cluster/images/conformance/Makefile#L34

**Why is this needed**:
With Docker Hub rate-limit policy in-place, we probably should consider removing this dependency to stay in sync with other base images in Kubernetes project. Folks building their own binaries (i.e. with `make quick-release`) might run into this as well.

**Notes**:
- Prior discussion happened on [#sig-release Slack channel](https://kubernetes.slack.com/archives/C2C40FMNF/p1605728704106400)
- An idea from @BenTheElder is to use [`go-runner`](https://github.com/kubernetes/release/tree/master/images/build/go-runner) which was based on [`distroless`](https://github.com/GoogleContainerTools/distroless/)
- the [`go-runner` under `conformance/` folder in k/k](https://github.com/kubernetes/kubernetes/tree/master/cluster/images/conformance/go-runner) should probably be renamed to avoid confusion with k/release `go-runner` (h/t @justaugustus)
- Currently, [conformance `entrypoint`](https://github.com/kubernetes/kubernetes/blob/1c49b4425bf8c5b144e3ce7378b63351364ae8c6/cluster/images/conformance/Dockerfile#L33) is set to [`run_e2e.sh` Bash script](https://github.com/kubernetes/kubernetes/blob/master/cluster/images/conformance/run_e2e.sh), so migrating to `go-runner` may not be a drop-in move
    - However, [`run_e2e.sh` is already providing an option for it](https://github.com/kubernetes/kubernetes/blob/1c49b4425bf8c5b144e3ce7378b63351364ae8c6/cluster/images/conformance/run_e2e.sh#L39-L45), so maybe we don't have to start from scratch

/sig testing
/area conformance

/sig release
(cc'ing because `make quick-release` builds conformance image, though my quick search seem to show there isn't any build pipelines referencing `make quick-release`)

**Comment by saschagrunert** [comment]
> With Docker Hub rate-limit policy in-place, we probably should consider removing this dependency to stay in sync with other base images in Kubernetes project. Folks building their own binaries (i.e. with `make quick-release`) might run into this as well.

@BenTheElder @wilsonehusin do we still want to do this? I read somewhere that the images built in Google Cloud are being mirrored from Docker Hub, right? This would mean that the API rate limiting will not hit us any more.

**Comment by wilsonehusin** [comment]
Womp yeah I think DockerHub rate limit is not really the big motivator at this point. However, I think I still want to consider using distroless / go-runner to build and produce conformance image to reduce the noise from CVE scanning done in downstream places. What do you think?

**Comment by saschagrunert** [comment]
> However, I think I still want to consider using distroless / go-runner to build and produce conformance image to reduce the noise from CVE scanning done in downstream places. What do you think?

Yeah I think this seems a valuable addition. Are you planning to work on this issue? :)

**Comment by wilsonehusin** [comment]
I will, though probably won't start until next week. If you have ideas and would like to start early feel free to go for it! Otherwise, I'd be happy to work on and deliver this.

**Comment by saschagrunert** [comment]
Thank you Wilson! Feel free to ping again if you need any assistance. 

/assign @wilsonehusin

**Comment by wilsonehusin** [comment]
one thing I need a little help with is to find a reference for using go-runner image that's used everywhere -- the one that I've found is inside conformance directory which seems to be different from what everyone else is using

**Comment by saschagrunert** [comment]
> one thing I need a little help with is to find a reference for using go-runner image that's used everywhere -- the one that I've found is inside conformance directory which seems to be different from what everyone else is using

We maintain a go-runner in k/release: https://github.com/kubernetes/release/tree/d19bdf5169a8fd9e4ab74fd86b728fcac4bccf77/images/build/go-runner

**Comment by wilsonehusin** [comment]
@saschagrunert oops, I forgot to get back on this last week -- I meant to say that I need a reference for `go-runner` image which I can use as `BASEIMAGE`, so something like `FROM k8s.gcr.io/...` on Dockerfile. Is that a possible thing to do?

**Comment by wilsonehusin** [comment]
after searching around, I found this -- https://github.com/kubernetes/k8s.io/blob/79d3eaeb40e36c238abac666b1ed09026fbbc625/k8s.gcr.io/images/k8s-staging-build-image/images.yaml#L205-L218

going to try and use `latest-buster` and see how it works :smile:

**Comment by wilsonehusin** [comment]
Started a PR #99178 -- plenty of things I'd like to be discussed but we should probably have the discussions there 😄

**Comment by wilsonehusin** [comment]
/remove-lifecycle stale

there is work in progress 😄
