### ISSUE TITLE
node is down ,but apiserver pod is running

### ISSUE THREAD

**Issue by ldk273427673** [kubernetes/kubernetes#96700]
**What happened**:
node is down ,but i find the apiserver pod is running ,and kube-controller-manager，kube-scheduler is also running

**What you expected to happen**:
why ?

**How to reproduce it (as minimally and precisely as possible)**:
1,when is shutdonw m1(master1 node)
[root@m1 ~]#init 0

2,test the network is down
[root@m2 ~]#ping 192.168.50.11
PING 192.168.50.11 (192.168.50.11) 56(84) bytes of data.

3,show the nodes status
m1==noready
[root@m2 ~]#kubectl get nodes
NAME   STATUS     ROLES    AGE     VERSION
c1     Ready      <none>   3h9m    v1.18.0
c2     Ready      <none>   3h9m    v1.18.0
m1     NotReady   master   3h11m   v1.18.0
m2     Ready      master   3h10m   v1.18.0
m3     Ready      master   3h10m   v1.18.0

4,show the pods status in kube-system ns
all pod is running ,and the cluster is running ok

[root@m2 ~]#kubectl get pods -n kube-system
NAME                                       READY   STATUS    RESTARTS   AGE
calico-kube-controllers-84445dd79f-xblmp   1/1     Running   0          59m
calico-node-54pg7                          1/1     Running   0          3h10m
calico-node-6g5ng                          1/1     Running   0          3h11m
calico-node-fdwps                          1/1     Running   0          3h10m
calico-node-fvwjs                          1/1     Running   1          3h11m
calico-node-zqnhh                          1/1     Running   0          3h10m
coredns-66bff467f8-5c2j5                   1/1     Running   0          59m
coredns-66bff467f8-fk89t                   1/1     Running   0          59m
etcd-m1                                    1/1     Running   1          3h11m
etcd-m2                                    1/1     Running   0          3h10m
etcd-m3                                    1/1     Running   0          3h10m
kube-apiserver-m1                          1/1     Running   1          3h11m
kube-apiserver-m2                          1/1     Running   0          3h11m
kube-apiserver-m3                          1/1     Running   0          3h9m
kube-controller-manager-m1                 1/1     Running   2          3h11m
kube-controller-manager-m2                 1/1     Running   1          3h11m
kube-controller-manager-m3                 1/1     Running   0          3h9m
kube-proxy-995bq                           1/1     Running   0          3h10m
kube-proxy-bx4zv                           1/1     Running   0          3h11m
kube-proxy-gm6cw                           1/1     Running   0          3h10m
kube-proxy-lmbjx                           1/1     Running   1          3h11m
kube-proxy-qcq75                           1/1     Running   0          3h10m
kube-scheduler-m1                          1/1     Running   2          3h11m
kube-scheduler-m2                          1/1     Running   1          3h11m
kube-scheduler-m3                          1/1     Running   0          3h9m
kube-sealyun-lvscare-c1                    1/1     Running   0          3h8m
kube-sealyun-lvscare-c2                    1/1     Running   0          3h8m
kuboard-c54fb6b48-ml5vt                    1/1     Running   0          123m
metrics-server-677dcb8b4d-2hjq4            1/1     Running   0          141m

**Anything else we need to know?**:
no 

**Environment**:
5 centos7.8 Vmware machine, 3master,2node

Version:"v1.18.0"

m1:192.168.50.11
m2:192.168.50.12
m3:192.168.50.13
c1:192.168.50.14
c2:192.168.50.15

**Comment by fedebongio** [comment]
@ldk273427673 can you confirm you are shutting down the Master Node? if that is the case, seems impossible that you can even do a Kubectl. Do you have more than one master? 

/assign @fedebongio 
/triage accepted

**Comment by ldk273427673** [comment]
> @ldk273427673 can you confirm you are shutting down the Master Node? if that is the case, seems impossible that you can even do a Kubectl. Do you have more than one master?
> 
> /assign @fedebongio
> /triage accepted

yes, iam sure ,i shutdown the master node,and when i descirbe the pod , the ready status is false ,but status is running

**Comment by tharun208** [comment]
@fedebongio I like to work on this, can i work on this ?

**Comment by NoBugBoy** [comment]
I also encountered a similar problem. When one of the master servers is closed, get nodes displays not ready, but the corresponding pods such as apiserver and controller manager are still ready and running

**Comment by oldthreefeng** [comment]
somehow , this is incredible!  but I do meet this problem.  node is done by poweroff and even ipv4 is  not reachable ,  when use `kubectl get pod -n kube-system` on other master .  the apiserver pod with this ipv4 is ready.
