### ISSUE TITLE
CRD creation fails with "Forbidden: must not specify anything other than name and generateName"

### ISSUE THREAD

**Issue by whalecold** [kubernetes/kubernetes#96709]
**What happened**:

I have the a CRD file (crd.yaml) generated with controller-tools v0.4.0 and the tools will add `type` and `description` filed for `metadata` default, the [type](https://github.com/kubernetes/kubernetes/blob/e64ebe01314b41fa68cff827a31ab133ec6963a4/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/validation.go#L162) has been neglected, should we neglect the `description` either ?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig api-machinery
/assign
/kind bug

**Comment by whalecold** [comment]
This issue may be similar with [91395](https://github.com/kubernetes/kubernetes/issues/91395), we can also remove the `description` field under `metadata` in controller-tools. Do you have any suggestions?  @sttts

**Comment by liggitt** [comment]
This was previously discussed and decided against in https://github.com/kubernetes/kubernetes/issues/86800

Dropping the description that would not be used would be the recommendation.
