### ISSUE TITLE
Failed to create object with non-retriable error

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubernetes#96703]
**What happened**:
When I run some integration test in `scheduler_perf`, I often got the below error message like below,
```
make test-integration WHAT=./test/integration/scheduler_perf KUBE_TEST_VMODULE="''" KUBE_TEST_ARGS="-alsologtostderr=false -logtostderr=false -run=^$$ -benchtime=1ns -bench=BenchmarkPerfScheduling/Preemption/500Nodes/2000InitPods/500PodsToSchedule"
...
--- FAIL: BenchmarkPerfScheduling/Preemption/500Nodes
    scheduler_perf_test.go:367: op 1: Error creating pod: Failed to create object with non-retriable error: The POST operation against Pod could not be completed at this time, please try again.
```

How these object is created is called into `RetryWithExponentialBackOff`, but the code there simply return a `error` to say that is `non-retriable`. 

e.g. 

https://github.com/kubernetes/kubernetes/blob/e64ebe01314b41fa68cff827a31ab133ec6963a4/test/utils/create_resources.go#L56-L68

In this example, the pod will either got created successfully in the first try or just return a error to indicate the pod creation is not retriable, the `RetryWithExponentialBackOff` which implemented the retry mechanism is not effective at all.

**What you expected to happen**:
we have two choice here, 
- Make the object creation real retriable, i.e. when we got some error after the API calling, will continue to try until the `retryBackoffSteps` is reached.
- Discard the retry mechanism, and remove all those related code if we believe it does `non-retriable`.

**How to reproduce it (as minimally and precisely as possible)**:
Run below integration several times,
```
make test-integration WHAT=./test/integration/scheduler_perf KUBE_TEST_VMODULE="''" KUBE_TEST_ARGS="-alsologtostderr=false -logtostderr=false -run=^$$ -benchtime=1ns -bench=BenchmarkPerfScheduling/Preemption/500Nodes/2000InitPods/500PodsToSchedule"
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by chendave** [comment]
/sig testing
/sig scheduling

label this as scheduling since this bug impacts the `scheduler_perf`.

**Comment by aojea** [comment]
@liggitt I'd love your opinion here, is there a concept of "retriable" and "non-retriable" errors in the API?

**Comment by chendave** [comment]
@xiaopeng-han  just  a head up, the PR is out https://github.com/kubernetes/kubernetes/pull/96704, let's see if you have any comment here.

**Comment by aojea** [comment]
hmm @chendave this is a duplicate of https://github.com/kubernetes/kubernetes/pull/96696
I think we should close this in favor of #96696 , the other was open before

**Comment by chendave** [comment]
@aojea yeah, looks like I step on @Huang-Wei 's toes :)

/close in favor of https://github.com/kubernetes/kubernetes/issues/96651
