### ISSUE TITLE
Object.Raw is nil for a delete request to webhook server

### ISSUE THREAD

**Issue by windayski** [kubernetes/kubernetes#96715]
I set up a webhook server in my kubernetes cluster. 
This webhook server will check each delete request of resource and decide whether to approve this delete request.
Everything is ok but I always got a nil in req.OldObject.Raw or req.Object.Raw of a delete request.

I don't know why. I need this OldObject.Raw. And I have been stuck here for days.

Anyone knows why? Thanks in advance.

Here are my codes:

```
func (whsvr *WebhookServer) validate(ar *v1beta1.AdmissionReview) *v1beta1.AdmissionResponse {
	req := ar.Request
	var result *metav1.Status
	
		//...some codes
		
	if req.Operation == v1beta1.Delete {
		switch req.Kind.Kind {
		case "CkeCluster":
			if ckeClusterEnabled {
				var ckeCluster v1alpha1.CkeCluster
				glog.Infof("Validate req.OldObject.Raw: %s", string(req.Object.Raw))
				
				//here, req.OldObject.Raw is always empty, why?
				
				if err := json.Unmarshal(req.OldObject.Raw, &ckeCluster); err != nil {
					//... some codes
				}
				//some codes
			}

		//....some codes
	}

	return &v1beta1.AdmissionResponse{
		Allowed: true,
		Result:  result,
	}
}
```

**Comment by neolit123** [comment]
hi, we try to close support tickets and direct users to the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

you could try #kubernetes-users on k8s slack.


if you find a bug in core kubernetes, please open a new issue.
thanks
/close
