### ISSUE TITLE
log container name alongside id in kuberuntime_container.go

### ISSUE THREAD

**Issue by bazzargh** [kubernetes/kubernetes#96725]
**What would you like to be added**:
In log messages that log the container id (which is really just kuberuntime_container.go), consistently also log the container name. 

**Why is this needed**:
Consider this example:
```
E1117 11:46:08.912579    6262 kuberuntime_container.go:590] Container "docker://bf4aa6b4abffbd2bddc4f13b4cde1b978b05a93bdc462f5f6e84ff2c21c417fb" termination failed with gracePeriod 360: rpc error: code = Unknown desc = operation timeout: context deadline exceeded
```

This is what is currently logged by kuberuntime_container.go. We'd like to track this back to a specific container name, pod or deployment that had a problem (in this case poor signal handling by pid 1). However, the only identifier in the message is the container id...which has just been deleted. So we cannot even go back and find this in the cluster.

Looking at the code in this method:
https://github.com/kubernetes/kubernetes/blob/1ea29cec9c923f18774092df9c3b7d0de7a193c2/pkg/kubelet/kuberuntime/kuberuntime_container.go#L588-L646
the container _name_ was available for logging, but not used. Only one of the messages in this method outputs both the container name and the id, but it's not on the normal execution path, so we can't find anything to associate the two and trace back the other messages. The name and id are both passed to the "Stopping container" event... which then removes the id
https://github.com/kubernetes/kubernetes/blob/1ea29cec9c923f18774092df9c3b7d0de7a193c2/pkg/kubelet/kuberuntime/kuberuntime_container.go#L82-L87
(removing the id is reasonable in the events, for the reasons given there, however we do need it in the logs somewhere).

In some cases the log messages are useful, but it's inconsistent. This one is exactly what I'd like to see throughout the file - give both the name and id. It goes one better and even names the pod:
https://github.com/kubernetes/kubernetes/blob/1ea29cec9c923f18774092df9c3b7d0de7a193c2/pkg/kubelet/kuberuntime/kuberuntime_container.go#L592
```
			return fmt.Errorf("failed to get containerSpec %q(id=%q) in pod %q when killing container for reason %q",
				containerName, containerID.String(), format.Pod(pod), message)
```

FWIW: replacing container id with container name in these messages would not be a good solution, debugging these issues we also need to trace back the messages from docker, which only has the container id to log, eg, for one of our problems with this pod:
```
time="2020-11-17T11:50:56.583289191Z" level=info msg="Container 540a970fd3428f917d9ea5569d7cdd8341ed9f6b4245e93365a501e69e8113ce failed to exit within 30 seconds of signal 15 - using the force"
```

**Comment by wawa0210** [comment]
/assign 

I can try to fix this

**Comment by chenyw1990** [comment]
I have add a pr add containername and podName to log.
and i think it's useful to replace containerID to containerName in func recordContainerEvent,  in large clusters, it is necessary to optimize the number of events。
