### ISSUE TITLE
kubelet report wrong DiskPressure

### ISSUE THREAD

**Issue by nxyy-22** [kubernetes/kubernetes#96732]
One Node in cluster report DiskPressure but the usage of rootfs is 73%, and imagefs (I set docker data root: /data/docker/ instead of  the original dir /var/lib/docker/ ) usage is 4%.
when I check kubelet's log,  I find kubelet check the dir /var/lib/docker/overlay2/ instead of the correct dir /data/docker/ which means kubelet didn't read the right Imagefs from docker .
And this will cause all pods on this node evicted and never recovery.
When I restart kubelet.service, it will fix the problem, so I wanna know why this condition happened and how to resolve this forever.

**Enviroment**:
- kubenetes version 1.16.3
- docker version 19.03.13
- OS centos7.3
- Kernel centos7.3-514

**Comment by lingsamuel** [comment]
That could be inode issue. Could you post output of `df -i`?

**Comment by lingsamuel** [comment]
DiskPressure could be inode issue, too. Could you post output of `df -i`?

**Comment by lingsamuel** [comment]
What's your container runtime? Docker or remote CRI?

**Comment by lingsamuel** [comment]
`cadvisor` only init DockerRootDir once. I guess you change your docker config without restart kubelet?

**Comment by lingsamuel** [comment]
FYI cadvisor init DockerRootDir from unix sock, you can get it by this:
```bash
mkfifo dsfifo
nc -lkv 1111 <dsfifo | nc -Uv /var/run/docker.sock >dsfifo
```

Then `curl localhost:1111/info`, you will find a `DockerRootDir`.

ps: make sure `rm dsfifo` later.
