### ISSUE TITLE
Pod should be deleted after volume unstage finished if no other pods using the volume

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#96734]
For pod deletion, currently as long as volume is unpublished (unmount), pod might be deleted right after unmount. It is possible that pod is deleted before volume is unstaged (UnmountDevice). This behavior might cause snapshot test fail especially on Windows where unstage takes longer time.

1. volume is created and pod writes data to volume
2. nodeUnpublish finished and pod is deleted, 
3. create a snapshot out of volume
4. nodeUnstage starts and succeeded
4. restore a new volume from the snapshot
5. create a pod to read volume

The test might fail because the new volume restored form snapshot does not contain data written before. The root cause is that after first pod finishes writing data, the data might be in cache. NodeUnstageVolume should flush the data to the disk. (In linux, unmount device; in Windows, unstagevolume will explicitly call write-cache command). However, pod might be deleted before nodeUnstage, and snapshot is taken before data can be flushed into disk.

Proposal: pod final deletion should wait until volume unstage finishes if no other pods using this volume

**Comment by jingxu97** [comment]
cc @msau42 @mattcary @xing-yang

**Comment by msau42** [comment]
I thought @saikat-royc is trying to fix this issue with https://github.com/kubernetes/kubernetes/pull/94737?

**Comment by msau42** [comment]
In terms of fixing this specific test case, what if the test pod does a fsync after it writes?

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs

**Comment by jingxu97** [comment]
> I thought @saikat-royc is trying to fix this issue with #94737?

He is fixing a related but different issue. The race is between unstage and delete volume. But if this issue is fixed, I think it will also fix the issue mentioned in #94737, the ordering will be

```
NodeunPublish --> NodeunStage -->last pod using volume deleted --> pvc finalizer can be removed
```

Current possible race 
```
NodeunPublish --> pod deleted -->  pvc is deleted
                         --> NodeunStage --> ControllerUnstage (detach)
```

**Comment by msau42** [comment]
In terms of best practices, applications should call fsync to flush their data to disk. Can we fix the test to fsync the data before deleting the pod?

**Comment by jingxu97** [comment]
For linux, it seems possible. But windows, it is harder. Need to figure out how to enable write through mode for writing files
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/0e0b734b-2b73-414d-8833-8d2eed7043f6/sync-directories-on-windows?forum=windowsgeneraldevelopmentissues

**Comment by saikat-royc** [comment]
Agree with @msau42  here, that ideally the workload should fsync the data before deletion. Pod delete after node unpublish looks to be the right behavior. Unstage of volume is initiated when no resource (pod in this case), has a reference to it.

**Comment by jingxu97** [comment]
I think this is an interesting topic worth further discussing. Thinking of the concept of pod, a Pod wraps containers, storage resources, and an ephemeral network identity together as a single unit. So during a Pod deletion, it makes sure the relevant resources are cleaned up. Looking at the pod deletion workflow, it checks  whether pod resources including pod volumes and cgroups are released. Now it is a question of how to define a resource e.g., is cleaned up. For volume, should it include nodeUnstageVolume, or just nodeUnpublishVolume. 
Choosing different definition will result in other consequences because different objects have certain dependency during cleanup. In this example, pod deletion will be used as a condition for volume deletion ... and there will be other such examples, I think.
