### ISSUE TITLE
error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /vනෙවැ 20 10:28:55 master-2 kubelet[5890]: goroutine 1 [running]

### ISSUE THREAD

**Issue by godomainz** [kubernetes/kubernetes#96741]
1) Followed this documentation  https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
2) Started the master node using "sudo kubeadm init"
3) Received successful message and "kubeadm join" commands
4) Ran "journalctl -u kubelet" command on master node to see the status of kubelet
6) I can see below error

` F1120 10:28:55.554344    5890 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /vනෙවැ 20 10:28:55 master-2 kubelet[5890]: goroutine 1 [running]:
නෙවැ 20 10:28:55 master-2 kubelet[5890]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc000010001, 0xc0000c0840, 0xfb, 0x14d)
නෙවැ 20 10:28:55 master-2 kubelet[5890]:         /workspace/anago-v1.19.4-rc.0.51+5f1e5cafd33a88/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:996 +0xb9
නෙවැ 20 10:28:55 master-2 kubelet[5890]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x6d00180, 0xc000000003, 0x0, 0x0, 0xc000b0d5e0, 0x6b52d81, 0x9, 0xc6, 0xc000890300)
නෙවැ 20 10:28:55 master-2 kubelet[5890]:         /workspace/anago-v1.19.4-rc.0.51+5f1e5cafd33a88/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:945 +0x191
නෙවැ 20 10:28:55 master-2 kubelet[5890]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0x6d00180, 0x3, 0x0, 0x0, 0x1, 0xc000abfd00, 0x1, 0x1)
නෙවැ 20 10:28:55 master-2 kubelet[5890]:         /workspace/anago-v1.19.4-rc.0.51+5f1e5cafd33a88/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:718 +0x165
නෙවැ 20 10:28:55 master-2 kubelet[5890]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).print(...)
නෙවැ 20 10:28:55 master-2 kubelet[5890]:         /workspace/anago-v1.19.4-rc.0.51+5f1e5cafd33a88/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:703
නෙවැ 20 10:28:55 master-2 kubelet[5890]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.Fatal(...)
නෙවැ 20 10:28:55 master-2 kubelet[5890]:         /workspace/anago-v1.19.4-rc.0.51+5f1e5cafd33a88/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1436
නෙවැ 20 10:28:55 master-2 kubelet[5890]: k8s.io/kubernetes/cmd/kubelet/app.NewKubeletCommand.func1(0xc00037e840, 0xc00004e090, 0x3, 0x3)
නෙවැ 20 10:28:55 master-2 kubelet[5890]:         /workspace/anago-v1.19.4-rc.0.51+5f1e5cafd33a88/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:198 +0xa05
නෙවැ 20 10:28:55 master-2 kubelet[5890]: k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc00037e840, 0xc00004e090, 0x3, 0x3, 0xc00037e840, 0xc00004e090)
නෙවැ 20 10:28:55 master-2 kubelet[5890]:         /workspace/anago-v1.19.4-rc.0.51+5f1e5cafd33a88/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846 +0x2c2
නෙවැ 20 10:28:55 master-2 kubelet[5890]: k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00037e840, 0x16491e8d93a1a66e, 0x6cffca0, 0x409b05)
නෙවැ 20 10:28:55 master-2 kubelet[5890]:         /workspace/anago-v1.19.4-rc.0.51+5f1e5cafd33a88/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:950 +0x375
නෙවැ 20 10:28:55 master-2 kubelet[5890]: k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
නෙවැ 20 10:28:55 master-2 kubelet[5890]:         /workspace/anago-v1.19.4-rc.0.51+5f1e5cafd33a88/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:887
නෙවැ 20 10:28:55 master-2 kubelet[5890]: main.main()`

**Environment**:
- Kubernetes version :1.19.4
- Cloud provider or hardware configuration: VirtualBox
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.5 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`): Linux master-2 5.4.0-53-generic #59~18.04.1-Ubuntu SMP Wed Oct 21 12:14:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm  (followed steps here https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/)

**Comment by neolit123** [comment]
hi, please try asking on the support channels and #kubeadm on k8s slack:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

> failed to read kubelet config file "/var/lib/kubelet/config.yaml"

this indicates that kubeadm init/join did not finish writing the /var/lib/kubelet/config.yaml file.

/close
