### ISSUE TITLE
Pod Topology Spread constraints should be taken into account on scale down

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#96748]
**What would you like to be added**:
Pod topology spread constraints are currently only evaluated when scheduling a pod. 

The ask is to do that in kube-controller-manager when scaling down a replicaset. The logic would select the failure domain with the highest number of pods when selecting a victim.

The risk is impacting kube-controller-manager performance.

**Why is this needed**:
To maintain the spread.

This is a special case of https://github.com/kubernetes/enhancements/pull/1828 and https://github.com/kubernetes/enhancements/pull/1888

/sig apps
/sig scheduling

**Comment by ahg-g** [comment]
This means that controller-manager should start watching nodes, I am not sure if it does that already.

Other Questions:
- How would this combine with delete-priority (#1828)? 
- Should we also consider other constraints like inter-pod (anti)affinity, node affinity and taints? 
- If so, how should the rankings of different constraints be combined? additively just like we do in the scheduler?

I am inclined to say that topology spread is a special enough case to have native support for it in core k8s since it is critical for HA, and for all other cases perhaps delete-priority is the answer?

**Comment by alculquicondor** [comment]
> - How would this combine with delete-priority (#1828)?

delete-priority should take precedence.

As for performance, the current logic already takes into consideration active Pods per Node. So it wouldn't be much of a increase to do the same for other topologies.

**Comment by Huang-Wei** [comment]
> * How would this combine with delete-priority (#1828)?

+1 to Aldo that delete-priority should take precedence.

I think delete-priority, if approved, acts as an extensible hook for 3rd-party integrator to impact the down-scaling, for any feature. As it's not convinced (yet) how compelling that could be, I think for GAed feature like PodTopologySpread which have clear API semantics, the down-scaling optimization logic should be implemented in a more controllable and deterministic way.

> * Should we also consider other constraints like inter-pod (anti)affinity, node affinity and taints?

I guess we have to consider case by case. We can start with PodTopologySpread.

> * If so, how should the rankings of different constraints be combined? additively just like we do in the scheduler?

Are we talking about hard constraints, or soft? It'd be easier to only cover the hard constraints.

**Comment by ahg-g** [comment]
> Are we talking about hard constraints, or soft? It'd be easier to only cover the hard constraints.

we should do both in the same way, best effort.

**Comment by alculquicondor** [comment]
> Are we talking about hard constraints, or soft? It'd be easier to only cover the hard constraints.

We could choose to somehow honor `maxSkew`, but that's just going to make the algorithm unnecessarily complicated. We can simply select the Pods from topologies with less instances. In that sense, there wouldn't be any difference between hard and soft constraints.

Going into implementation details, we only need to change the Rank https://github.com/kubernetes/kubernetes/blob/78318c7a26928bdabe2491cf022cf9e61be32188/pkg/controller/controller_utils.go#L855

Today, the rank is the number of Pods in the same Node
https://github.com/alculquicondor/kubernetes/blob/4ae11dac2e2cc8594c528a679db5861c0926b514/pkg/controller/replicaset/replica_set.go#L823

**Comment by ahg-g** [comment]
one nit here is that pod topology spread constraints could define a different set of selectors than the replicaset.

**Comment by alculquicondor** [comment]
I was pondering in the code and started thinking that the overhead won't be negligible as we would need to add a Node informer, and perhaps a Node labels converted into a slice to reduce map accesses.

While that implementation is still worth exploring, I was playing around with an idea that I've had for a while: relax the timestamp comparisons to a logarithmic scale (rounded to the nearest integer). Changes are pretty compact #96898

**Comment by damemi** [comment]
I will let @soltysh speak more on the controller implementation side, but for the selection algorithm I agree with @ahg-g that a best-effort case shouldn't need to differentiate between hard and soft constraints.

I also don't think considering MaxSkew would be too difficult, it could probably use the same algorithm we added for this in descheduler (or something similar).

It would be great to have this balancing able to react on scale-down though. Perhaps this could also tie into our work to export the scheduling framework, so that the controller-manager could use the logic right from the plugins?

**Comment by alculquicondor** [comment]
I think it might be too hard to reuse plugins logic while keeping the replicaset controller performant. But I'd be very pleased if you prove me wrong 😅

**Comment by alculquicondor** [comment]
I'm starting a KEP on this kubernetes/enhancements#2185

I'll pass down the implementation

**Comment by Huang-Wei** [comment]
Are we going to treat this issue resolved by #99212 **completely**? Or prefer to still leave it open and explore other solutions in the future?

**Comment by ahg-g** [comment]
I think #99212 and if necessary https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/2255-pod-cost (with a webhook to randomly set the cost) can address this issue reasonably ok.
