### ISSUE TITLE
Increase supported pod deletion rate

### ISSUE THREAD

**Issue by mborsz** [kubernetes/kubernetes#96752]
**What would you like to be added**:

Currently garbage collector is using two api calls per a single object deletion. Given that the performance of controllers is limited by --kube-api-qps flag (set to 100 e.g. in our scalability tests), we can create pods with 100 pods/s churn, they are deleted with only 50 pods/s churn.

**Why is this needed**:
* Supporting high pod churn workloads
* Making scalability tests faster (while we are able to create pods with 100 pods/s which takes ~30m in our tests, deletion of them happens with 50 pods/s (even less as garbage collector also removes other object types than pods), so it takes over hour).

**How to do that**:
Ref: https://github.com/kubernetes/kubernetes/blob/50db32cf8c3301d27bb71b9e59f9449c18c944ba/pkg/controller/garbagecollector/garbagecollector.go#L412-L429

IIUC this code correctly the additional get (and not using cache) has two purposes:
* making it possible to handle "virtual" objects (checking if they can be deleted): added in https://github.com/kubernetes/kubernetes/pull/38676
* getting rid of stale virtual objects: https://github.com/kubernetes/kubernetes/pull/57503

We can change the logic in attemptToDeleteItem to:
 * if the object is present in cache, use it
 * if it's not, fallback to API call 

This way, for most of the cases we will skip api call and we will support both cases: attemptToDeleteItem will handle correctly "not yet observed by cache" objects (api call will return some object) and will make it possible to get rid of stale virtual objects (api call will return 404 and we will remove the virtual object from graph). 

Alternatively, we can try something like:
 * in attemptToDeleteItem, simply using cached object, if it doesn't exist, drop the object from queue (when we will observe the virtual object by watch, it will be added back)
* add a dedicated worker queue for removing stale virtual objects: if we observe a new virtual object, adding to that queue, each queue loop will:
   * check if the node is still virtual (not observed by cache): if not, drop it from queue
   * otherwise api call to validate if it still exists on apiserver:
     * if it does, requeue object with some backoff
     * if not, drop object from graph

The second solution seems to be a little bit more clear to me (it decouples two purposes of the attemptToDeleteItem call)  and it avoids unnecessary API calls in case of watch delay (e.g. attemptToDeleteItem called on the pod that has been deleted and watch doesn't reflect this fact yet).

@liggitt @caesarxuchao @wojtek-t WDYT?

**Comment by wojtek-t** [comment]
Re "why":
- high-churn workloads is something that we should be focused
- I wouldn't explicitly mention speeding up tests as the goal itself, we probably could come up with other ways to solve that too.
But the first one is a compelling enough reasons and I fully support it.


Re solution itself:
- option 1: what if the option present in cache is stale?
    We currently don't set any preconditions on ResourceVersion, so we would have to start doing that, then retry on failures, etc.]
  [All of that seems doable, but I'm just trying to point that it's not necessary as easy as it seems]

- option 2:
(a) it has the same problem as above
(b) you're suggesting an additional periodic polling for virtual objects, which doesn't scale if we have many of those

**Comment by mborsz** [comment]
Re option 1 comment:
* I think this is an issue also today: it is possible that between GET and DELETE calls the object has been modified. I agree that with moving to cache this may happen more often.
* Is there any way to DELETE api object conditionally (i.e. delete only if it has a given resourceVersion?)?

Re comment 2b: In fact we currently do periodic polling for virtual objects ([here](https://github.com/kubernetes/kubernetes/blob/50db32cf8c3301d27bb71b9e59f9449c18c944ba/pkg/controller/garbagecollector/garbagecollector.go#L313-L318)). I just suggest moving this logic to a separate place.

**Comment by wojtek-t** [comment]
Yes - you can set Preconditions in DeleteOptions:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L506
and you can set RV in Preconditions:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L623


> Re comment 2b: In fact we currently do periodic polling for virtual objects (here). I just suggest moving this logic to a separate place.

But unless I'm misreading it (sorry, didn't have time to look deep enough), this is happening on deletions.
The way how I understood your proposal is to poll them periodically for the whole lifetime?

**Comment by mborsz** [comment]
I think it makes sense to start setting RV precondition anyway (so that if a given object changes between GET and DELETE, we will know that the DELETE is still up to date decision).



> But unless I'm misreading it (sorry, didn't have time to look deep enough), this is happening on deletions.
> The way how I understood your proposal is to poll them periodically for the whole lifetime?

My proposal is to "do whatever we are doing now, but in a separate loop". This way we will avoid doing API call on a standard code path only to support virtual objects. I understand that we are requeing all virtual objects, not only on deletions, but maybe I'm wrong.

**Comment by liggitt** [comment]
> I think it makes sense to start setting RV precondition anyway (so that if a given object changes between GET and DELETE, we will know that the DELETE is still up to date decision).

That will help in not taking action on stale data, but introduces the possibility that a frequently written object will never be garbage collected.

> I understand that we are requeing all virtual objects, not only on deletions

Correct, virtual objects are already polled until they are observed present (via an informer event) or verified absent (via a 404 on the live lookup) and a virtual delete event is queued.

Having just [spent a lot of time in the GC code](https://github.com/kubernetes/kubernetes/pull/92743), I'm not sure a third queue will simplify things.

**Comment by wojtek-t** [comment]
>>I think it makes sense to start setting RV precondition anyway (so that if a given object changes between GET and DELETE, we will know that the DELETE is still up to date decision).

> That will help in not taking action on stale data, but introduces the possibility that a frequently written object will never be garbage collected.

@liggitt - aren't we afraid that we delete something that we shouldn't delete in this case? I would assume that if something is supposed to be GC-ed it shouldn't be frequently changing (or at least it should eventually stop being updated frequently).
Setting preconditions here would make sense to me.

**Comment by mborsz** [comment]
> > I think it makes sense to start setting RV precondition anyway (so that if a given object changes between GET and DELETE, we will know that the DELETE is still up to date decision).
> 
> That will help in not taking action on stale data, but introduces the possibility that a frequently written object will never be garbage collected.
> 

Good point. Frequent object changes may cause gc starvation. This can be resolved by proper "precondition failed" error handing (i.e. retrying with GET API call)

**Comment by mborsz** [comment]
Another idea: maybe in fact we don't need to get rid of GET call -- it's cheap and it's not a problem itself. The only problem about a GET call is that it consumes token from rate limiter. Maybe we can somehow change qps limit for gc collector only to allow it e.g. 200 qps while other controllers will be still using 100 qps?

**Comment by wojtek-t** [comment]
So that will go away with Priority&Fairness eventually, because we want to get rid of qps-limits once this will prove to be stable.
[Also note that they are cheaper than modifying requests, but they are still not super cheap (e.g. they are linearized in etcd)]

**Comment by liggitt** [comment]
> @liggitt - aren't we afraid that we delete something that we shouldn't delete in this case?

Yes, but only if the updates are modifying ownerReferences

> I would assume that if something is supposed to be GC-ed it shouldn't be frequently changing (or at least it should eventually stop being updated frequently).

I don't think that's necessarily true. Imagine a controller updating some status on an object as long as it exists, but which is depending on the object to go away when its owner does.

**Comment by zorro786** [comment]
@mborsz I am interested to increase deletion rate too, trying to understand your issue here. Does it mean with default settings at controller manager (--kube-api-qps=30), in one second only max 15 pods will go from RUNNING->TERMINATED? Or is this rate about after TERMINATED to removal from API Server?

**Comment by mborsz** [comment]
> Maciej Borsz I am interested to increase deletion rate too, trying to understand your issue here. Does it mean with default settings at controller manager (--kube-api-qps=30), in one second only max 15 pods will go from RUNNING->TERMINATED? Or is this rate about after TERMINATED to removal from API Server?

In that case, only 15 pods will be marked to be deleted (by setting deletetionTimestamp != 0; pod phase will not change IIUCC). Then kubelets will remove objects from API server, once they terminate the process running on the node.

**Comment by zorro786** [comment]
> In that case, only 15 pods will be marked to be deleted (by setting deletetionTimestamp != 0; pod phase will not change IIUCC). Then kubelets will remove objects from API server, once they terminate the process running on the node.

I see okay, I was interested to increase the rate at which pod status changes from RUNNING -> TERMINATED after deletion. If I delete say 1000 pods at once, their state changes from RUNNING -> TERMINATED in small batches.

**Comment by mborsz** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/104966

/close
