### ISSUE TITLE
Strange behavior of kubectl cp

### ISSUE THREAD

**Issue by steffakasid** [kubernetes/kubernetes#96755]
**What happened**:
Running kubectl cp two times isn't idempotent.
````
$ ls -lR test
total 8
-rw-r--r--  1 steffenrumpf  staff  457 21 Feb  2020 test.yml
$ kubectl cp test <somepod>:/tmp/test2
$ kubectl exec  <somepod> -- ls -lR /tmp
/tmp:
total 0
drwxr-xr-x 2 app users 29 Nov 20 15:13 test2

/tmp/test2:
total 4
-rw-r--r-- 1 app users 457 Nov 20 15:13 test.yml
$ kubectl cp test <somepod>:/tmp/test2
$ kubectl exec  <somepod> -- ls -lR /tmp
/tmp:
total 0
drwxr-xr-x 3 app users 41 Nov 20 15:14 test2

/tmp/test2:
total 4
-rw-r--r-- 1 app users 457 Nov 20 15:13 test.yml
drwxr-xr-x 2 app users  29 Nov 20 15:14 test

/tmp/test2/test:
total 4
-rw-r--r-- 1 app users 457 Nov 20 15:14 test.yml
````
**What you expected to happen**:
I would expect that the second command would just overwrite the existing files (might also be useful if could be defined via -f option) or give an error:
````
$ ls -lR test
total 8
-rw-r--r--  1 steffenrumpf  staff  457 21 Feb  2020 test.yml
$ kubectl cp test <somepod>:/tmp/test2
$ kubectl exec  <somepod> -- ls -lR /tmp
/tmp:
total 0
drwxr-xr-x 2 app users 29 Nov 20 15:13 test2

/tmp/test2:
total 4
-rw-r--r-- 1 app users 457 Nov 20 15:13 test.yml
$ kubectl cp test <somepod>:/tmp/test2
$ kubectl exec  <somepod> -- ls -lR /tmp
/tmp:
total 0
drwxr-xr-x 3 app users 41 Nov 20 15:14 test2

/tmp/test2:
total 4
-rw-r--r-- 1 app users 457 Nov 20 15:13 test.yml
````

**How to reproduce it (as minimally and precisely as possible)**:
````
$ ls -lR test
total 8
-rw-r--r--  1 steffenrumpf  staff  457 21 Feb  2020 test.yml
$ kubectl cp test <somepod>:/tmp/test2
$ kubectl exec  <somepod> -- ls -lR /tmp
/tmp:
total 0
drwxr-xr-x 2 app users 29 Nov 20 15:13 test2

/tmp/test2:
total 4
-rw-r--r-- 1 app users 457 Nov 20 15:13 test.yml
$ kubectl cp test <somepod>:/tmp/test2
$ kubectl exec  <somepod> -- ls -lR /tmp
/tmp:
total 0
drwxr-xr-x 3 app users 41 Nov 20 15:14 test2

/tmp/test2:
total 4
-rw-r--r-- 1 app users 457 Nov 20 15:13 test.yml
drwxr-xr-x 2 app users  29 Nov 20 15:14 test

/tmp/test2/test:
total 4
-rw-r--r-- 1 app users 457 Nov 20 15:14 test.yml
````

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-eks-2ba888", GitCommit:"2ba888155c7f8093a1bc06e3336333fbdb27b3da", GitTreeState:"clean", BuildDate:"2020-07-17T18:48:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
AWS EKS
- OS (e.g: `cat /etc/os-release`): n/a (let me know if you need this information)
- Kernel (e.g. `uname -a`): n/a (let me know if you need this information)
- Install tools: n/a
- Network plugin and version (if this is a network-related bug): n/a
- Others: n/a

/sig cli

**Comment by lingsamuel** [comment]
This behavior doesn't "strange".
If the dest path `/tmp/test2` doesn't exist, `cp` create it and mapping src to it. If dest path exists, `cp` put src inside it.
`docker cp` has similar behavior and no one guarantees that it is idempotent.
