### ISSUE TITLE
When both requests and limits are specified on a POD, What does kubernetes take into consideration to schedule the pod? 

### ISSUE THREAD

**Issue by vikaskoppineedi** [kubernetes/kubernetes#96765]
Hello Team, 

I have a question, could be a dumb one. When both Limits (more than requests) and Requests (less than limits) are specified on a POD. What does scheduler take into consideration for scheduling, is it Requests or limits? 

I feel its definitely limits because, that is what the container can use max, if it was requests , if the pod wanted to use all the available specs mentioned in limits , if the node does not have the required resources, then there is no point in mentioning limits, except to put a max use.

**Comment by Huang-Wei** [comment]
> I have a question, could be a dumb one. When both Limits (more than requests) and Requests (less than limits) are specified on a POD. What does scheduler take into consideration for scheduling, is it Requests or limits?

It's requests.

> I feel its definitely limits because, that is what the container can use max, if it was requests , if the pod wanted to use all the available specs mentioned in limits , if the node does not have the required resources, then there is no point in mentioning limits, except to put a max use.

That's not the case. A Pod specifying requests less than limits indicates it's a burstable Pod. Requests specifies its minimum/guaranteed usage, while Limits specifies its maximum/burstable usage. A Pod that occupies exceeded requests may NOT be evicted (by kubelet) if kubelet doesn't fall into a resource shortage. More details can be found https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#how-pods-with-resource-requests-are-scheduled.
