### ISSUE TITLE
ServiceStatus.LoadBalancer should be a pointer

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#96760]
`omitempty` doesn't do what we want on a struct, so we always see this stanza in under `status`.  To fix this we'd need to fix the places that use it internally, obviously.

Minor, but persistently annoying.  I think we can do this with low impact internally but it would change to Go signature and so needs at least a relnote.

**Comment by tiloso** [comment]
Hey, I'd like to take this one.
/assign

**Comment by aojea** [comment]
@thockin do you want to persist on this?
See Jordan's comment https://github.com/kubernetes/kubernetes/pull/97547#issuecomment-754639388
