### ISSUE TITLE
[Kubectl set image --force] option?

### ISSUE THREAD

**Issue by MushuEE** [kubernetes/kubernetes#96767]
**What would you like to be added**:
I have a pod with:
```
        image: gcr.io/k8s-testimages/kettle:latest
        imagePullPolicy: Always
```
It will always pull a new image on deploy but this same behavior doesn't seem to happen with `kubectl set image deployment/kettle kettle=***/kettle:<tag>`

If <tag> image was updated over the previous image <tag> it will not re-pull and recreate the deployment

**Why is this needed**:
When I want to redeploy with a new image of the same tag I need to either change the tag or switch to a different tag than back

**Comment by wawa0210** [comment]
/assign

I can investigate

**Comment by wawa0210** [comment]
Looking at the source code, when the tag of the pod image has not changed, executing patch or apply multiple times has no effect. Because the yaml is the same during the check.
If we want to implement this feature, apiserver should also need to be adjusted, I have no better idea

**Comment by MushuEE** [comment]
Thank you for looking into it
