### ISSUE TITLE
concurrent map writes in VolumeBinding plugin during Filter

### ISSUE THREAD

**Issue by mateuszlitwin** [kubernetes/kubernetes#96772]
**What happened**:

`fatal error: concurrent map writes` during `Filter` phase from the `VolumeBinding` plugin when the `podVolumesByNode` is updated:

```
func (pl *VolumeBinding) Filter(ctx context.Context, cs *framework.CycleState, pod *v1.Pod, nodeInfo *framework.NodeInfo) *framework.Status {
        ...
	cs.Lock()
	state.podVolumesByNode[node.Name] = podVolumes
	cs.Unlock()
        ...
}
```

**What you expected to happen**:

Not crash.

**How to reproduce it (as minimally and precisely as possible)**:

I am suspecting that the issue is in the naive implementation of the `stateData`'s `Clone()` method:

```
func (d *stateData) Clone() framework.StateData {
	return d
}
```

Most likely the `CycleState` is cloned during filter phase, e.g. in the `addNominatedPods(...) ` called during `PodPassesFiltersOnNode(...)` in the `generic_scheduler.go`:

https://github.com/kubernetes/kubernetes/blob/809556517611e8bb78383a077d6f326c0fb355fa/pkg/scheduler/core/generic_scheduler.go#L388 

... and when `CycleState` is cloned during filtering, new mutex is created, but `stateData` is not cloned properly, this mean that potentially there are two or more different mutexes protecting the same `state.podVolumesByNode` map from writes.

**Anything else we need to know?**:
I think potential solution is to have mutex in the `stateData` or change the `stateData`'s `Clone()`.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.0
- Cloud provider or hardware configuration: not relevant
- OS (e.g: `cat /etc/os-release`): not relevant
- Kernel (e.g. `uname -a`): not relevant
- Install tools: not relevant
- Network plugin and version (if this is a network-related bug): not relevant
- Others: not relevant

/sig scheduling

**Comment by mateuszlitwin** [comment]
It looks like relevant code is from https://github.com/kubernetes/kubernetes/pull/92222 and mutex per `stateData` was considered intially. CC @cofyc @ahg-g

**Comment by Huang-Wei** [comment]
There are two-level state: the first one in scheduler framework level, which is passed to `Filter()` via `cs *framework.CycleState`; the second is managed by plugin itself, in term of VolumeBinding it's `volume_binding.go#stateData`.

Given that multiple goroutines may run Filter() on different nodes simultaneously, the following code are not protecting the second-level state:

https://github.com/kubernetes/kubernetes/blob/8c7cd8a8cc9f115f8b7223000604c653619c6c76/pkg/scheduler/framework/plugins/volumebinding/volume_binding.go#L208-L210

We should define a plugin specific lock protecting its own state. #96777 is the right fix IMO, but the explanation doesn't look accurate as even if `clone()` is implemented in a deep-copy manner, its clone data are still not protected during simultaneous calls to Filter().

/assign @cofyc 
/priority critical-urgent

**Comment by cofyc** [comment]
> There are two-level state: the first one in scheduler framework level, which is passed to `Filter()` via `cs *framework.CycleState`; the second is managed by plugin itself, in term of VolumeBinding it's `volume_binding.go#stateData`.
> 
> Given that multiple goroutines may run Filter() on different nodes simultaneously, the following code are not protecting the second-level state:
> 
> https://github.com/kubernetes/kubernetes/blob/8c7cd8a8cc9f115f8b7223000604c653619c6c76/pkg/scheduler/framework/plugins/volumebinding/volume_binding.go#L208-L210
> 
> We should define a plugin specific lock protecting its own state. #96777 is the right fix IMO, but the explanation doesn't look accurate as even if `clone()` is implemented in a deep-copy manner, its clone data are still not protected during simultaneous calls to Filter().
> 
> /assign @cofyc
> /priority critical-urgent

IIUC, the `framework.CycleState` will be duplicated in `addNominatedPods` for every node before passing to `Filter` extension point.

https://github.com/kubernetes/kubernetes/blob/ece591f7226696790cd27a4386b128082b268462/pkg/scheduler/core/generic_scheduler.go#L442-L460

https://github.com/kubernetes/kubernetes/blob/ece591f7226696790cd27a4386b128082b268462/pkg/scheduler/core/generic_scheduler.go#L378-L401

So we cann't rely on `framework.CycleState`'s lock to prevent the state from being modified concurrently. Am I right?

**Comment by Huang-Wei** [comment]
Exactly, for now, all other Filter plugins are reading from CycleState without reading lock. This was debatable, we noticed out-of-tree plugin developers raised this concern, see #95887. But now this issue provides a strong data point to prove reading lock is necessary for all in-tree Filter/Score plugins - which I'm following on a fix and benchmark results, but unfortunately it's too late to catch 1.20.

And technically, as I described in https://github.com/kubernetes/kubernetes/issues/95887#issuecomment-722187136, after we apply the read lock (the TBD item), there are 2 options to prevent racing of plugin-specific state. My option is that it's still favorable to add plugin-specific mutex to protect its cycle state as it would reduce/eliminate the period of write locks on the global CycleState. WDYT?

**Comment by Huang-Wei** [comment]
@cofyc I may have given an incorrect analysis as VolumeBinding's plugin-specific state are always using the same pointer, sorry for the confusion. I removed the confusing comments. It's actually different from what was discussed in #95887.

Your and @mateuszlitwin 's analysis make more sense to me. For nodes that have nominated nodes (cloned CycleState) or not (original CycleState), the original mutex may not be able to protect the CycleState:

https://github.com/kubernetes/kubernetes/blob/ece591f7226696790cd27a4386b128082b268462/pkg/scheduler/framework/cycle_state.go#L74-L85

I will take another look tomorrow.

**Comment by ahg-g** [comment]
@mateuszlitwin can you please post the actual core dump, the description in the original comment doesn't seem complete.

If the "concurrent map" fatal error is indeed happening at `state.podVolumesByNode[node.Name] = podVolumes`, then it means we are operating on two different CycleStates instances at the same time, which may happen when adding nominated pods (https://github.com/kubernetes/kubernetes/blob/b2ecd1b3a3192fbbe2b9e348e095326f51dc43dd/pkg/scheduler/core/generic_scheduler.go#L388)

Using the CycleState lock to synchronize access to the plugin's state in the map is not proper, the plugin state itself should have its private lock, this is certainly a bug.

**Comment by ahg-g** [comment]
please fix the lint issue (indentation of the comment)
