### ISSUE TITLE
Use k8s.gcr.io/e2e-test-images instead of gcr.io/kubernetes-e2e-test-images for e2e test images

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#96770]
Part of umbrella to migrate kubernetes e2e test images/registries to community-owned infrastructure: https://github.com/kubernetes/k8s.io/issues/1458

We should migrate away from the google.com-owned gcr.io/kubernetes-e2e-test-images and instead use the community-owned k8s.gcr.io/e2e-test-images repository.

Affected images are those that use `E2eRegistry` or `E2eVolumeRegistry`.  ~We may also want to consider pushing `DockerLibraryRegistry` images into k8s.gcr.io/e2e-test-images~ (moved to https://github.com/kubernetes/kubernetes/issues/97027)

https://github.com/kubernetes/kubernetes/blob/1d4c0ad6f33f2bc42555becdb5d74e570c0730f3/test/utils/image/manifest.go#L203-L245

My guess at the steps required:
- push old images from `gcr.io/kubernetes-e2e-test-images` to `gcr.io/k8s-staging-e2e-test-images`
- promote images used by latest supported patch releases and in-development release
- create postsubmit jobs for each test/image dir (done via https://github.com/kubernetes/kubernetes/issues/96432)
- PR change values of `E2eRegistry` and `E2eVolumeRegistry` to `k8s.gcr.io/e2e-test-images`, remove `PromoterE2eRegistry`
- subsequent trial PRs to run through building/promoting an e2e image

This is release-notes worthy and possibly announcement worthy.

/sig testing
/sig release
/wg k8s-infra
/area test-infra
/area test
/area images-registry
/priority important-soon

FYI @aojea @claudiubelu 
FYI @kubernetes/release-engineering

**Comment by misterikkit** [comment]
+1 to pushing `DockerLibraryRegistry` images to k8s.gcr.io as I have been seeing tests fail due to dockerhub rate limiting this week.

**Comment by wyike** [comment]
+1 to push DockerLibraryRegistry images to k8s.gcr.io, seeing test failure recently:
`[It] should provide container's limits.cpu/memory and requests.cpu/memory as env vars  [Conformance]
  /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:674
STEP: Creating a pod to test downward api env vars
Nov 23 10:23:27.785: INFO: Waiting up to 5m0s for pod "downward-api-ed1abd4e-2d75-11eb-b27c-4a6a22fc83cc" in namespace "e2e-tests-downward-api-gvcl6" to be "success or failure"
……
Nov 23 10:28:31.615: INFO: At 2020-11-23 10:23:31 +0000 UTC - event for downward-api-ed1abd4e-2d75-11eb-b27c-4a6a22fc83cc: {kubelet 5b5f58f6-bf78-4a69-ad33-7ae95a1f01b1} Pulling: Pulling image "busybox"
Nov 23 10:28:31.615: INFO: At 2020-11-23 10:23:33 +0000 UTC - event for downward-api-ed1abd4e-2d75-11eb-b27c-4a6a22fc83cc: {kubelet 5b5f58f6-bf78-4a69-ad33-7ae95a1f01b1} Failed: Failed to pull image "busybox": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit`

**Comment by claudiubelu** [comment]
So, the images that are under the ``e2eRegistry``, more explicitly, the images under ``kubernetes/test/images/`` could easily be migrated to ``k8s.gcr.io/e2e-test-images`` via the Image Promoter once that is running again.

As for the other ``DockerLibraryRegistry`` images, what are the jobs that are failing because of this? In any case, I know there were some PRs that configured the test jobs (or at least some of them) to use ``mirror.gcr.io`` as a registry mirror (basically, it'll check ``mirror.gcr.io`` for the image instead of pulling from dockerhub directly).

Looking around, it seems that there is a plan to mirror dockerhub images to staging: https://github.com/kubernetes/k8s.io/pull/1441

**Comment by spiffxp** [comment]
PR to trigger a rebuild for all relevant images: https://github.com/kubernetes/kubernetes/pull/98190

**Comment by spiffxp** [comment]
More image references that will need migrating:

https://github.com/kubernetes/kubernetes/blob/8a8282044c7cf8a0f1c73b8c143ab9a8d1bb88d9/test/e2e_node/image_list.go#L53-L67

**Comment by claudiubelu** [comment]
> 
> 
> More image references that will need migrating:
> 
> https://github.com/kubernetes/kubernetes/blob/8a8282044c7cf8a0f1c73b8c143ab9a8d1bb88d9/test/e2e_node/image_list.go#L53-L67

The node-perf images have been built, and I'm currently checking if any presubmit job fails with them here: https://github.com/kubernetes/kubernetes/pull/87607

When you say that more image references that will need migrating, do you also mean ``google/cadvisor:latest``, and ``k8s.gcr.io/stress:v1``, and that busybox image too (which actually makes me wonder - why do we use 2 different busybox images in testing?)

**Comment by chemikadze** [comment]
Drive-by: we've tried to use `k8s.gcr.io/e2e-test-images` with 1.16 e2e.test, and it causes `[sig-cli] Kubectl client Guestbook application should create and stop a working application [Conformance]` to fail with the following in logs:

```
Feb 19 23:57:15.048: INFO: Failed to get response from guestbook. err: <nil>, response: <br />
<b>Fatal error</b>:  Uncaught exception 'Predis\Response\ServerException' with message 'DENIED Redis is running in protected mode because protected mode is enabled, no bind address was specified, no authentication password is requested to clients. In this mode connections are only accepted from the loopback interface. If you want to connect from external computers to Redis you may adopt one of the following solutions: 1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 2) Alternatively you can just disable the protected mode by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 4) Setup a bind address or an authen in <b>/usr/local/lib/php/Predis/Client.php</b> on line <b>370</b><br />
```

Closer examination of `k8s.gcr.io/e2e-test-images/redis:5.0.5-alpine` image shows that it's actually using redis *3.2.12*. Is that intentional?

**Comment by BenTheElder** [comment]
IIRC the new registry does not support mutating tags so I don't think we can do anything about it at this point.

**Comment by spiffxp** [comment]
Unfortunately 1.16 is out of support at this point, as is 1.17 (ref: https://kubernetes.io/docs/setup/release/version-skew-policy/#supported-versions)

But we haven't pushed anything new lately, so this is probably still the case for supported releases.

The version of redis used isn't pinned at image build time for most arch builds: https://github.com/kubernetes/kubernetes/blob/599e7778b2a38452a15603b900fb3d931d71315c/test/images/redis/Dockerfile#L20

Looks like the windows version pins to 3.2: https://github.com/kubernetes/kubernetes/blob/599e7778b2a38452a15603b900fb3d931d71315c/test/images/redis/Dockerfile_windows#L20

/assign @claudiubelu 
any thoughts? (this might need to turn into a separate issue)

/assign @chewong 
(who has also done work toward this issue, thanks!)
/assign @spiffxp 
not currently pushing PRs related to this, but I'll start tracking what remains to be done soon

**Comment by chewong** [comment]
I see that we were originally using `redis:5.0.5-alpine` from dockerhub before we switched to using k8s.gcr.io (https://github.com/kubernetes/kubernetes/commit/40713f7666730d09fc50e3ce66d5528d741acc5c#diff-fa4ddc33013d1e57259726a4c1c327903e058453aece262eecfb48300e946c93L246). I believe that we wanted to change the test image registry without changing the tag and the Linux version of Redis we built from [test/images/redis](https://github.com/kubernetes/kubernetes/tree/master/test/images/redis) is kind of legacy, which causes the version discrepancy between the image tag and the actual Redis version.

I'd love to fix this but https://github.com/kubernetes/test-infra/issues/20884 is blocking me :/. For now, I'd recommend fetching the test image from dockerhub.

**Comment by desponda** [comment]
👋 Hello! The code freeze is starting March 9th, 2021 (about 1 week from now). As the Issue is tagged for 1.21, is it still planned for this release?

**Comment by spiffxp** [comment]
Yes, still being worked on, I have yet to review what remains to be done. This is also not subject to code freeze, but test freeze

**Comment by pacoxu** [comment]
- Only gcr.io/kubernetes-e2e-test-images/cuda-vector-add:1.0  is E2eRegistry
- cuda-vector-add:2.2 is using promoted registry now.
Why not promote 1.0 to k8s.gcr.io/e2e-test-images as 2.2?

**Comment by BobyMCbobs** [comment]
Made a PR https://github.com/kubernetes/kubernetes/pull/100470 to address the image repo name change in various files in the repo. It appears that some image tags are unavailable or newer tags are available for existing image repos.

**Comment by palnabarun** [comment]
@spiffxp -- friendly heads up, Tomorrow March 24th Wednesday is the v1.21 Test Freeze. :)

**Comment by spiffxp** [comment]
I'll look into the feasibility of landing https://github.com/kubernetes/kubernetes/pull/100470 today and evaluate where that leaves us

**Comment by erismaster** [comment]
@spiffxp We're past Test Freeze now - should this be moved to 1.22?

**Comment by claudiubelu** [comment]
> 
> 
> More image references that will need migrating:
> 
> https://github.com/kubernetes/kubernetes/blob/8a8282044c7cf8a0f1c73b8c143ab9a8d1bb88d9/test/e2e_node/image_list.go#L53-L67

From this list, only ``google/cadvisor:latest`` remains. Should that image also be in ``k8s.gcr.io`` registry? If so, I can send a few PRs for that.

As for this specific issue, only 2 commits remain:

- https://github.com/kubernetes/kubernetes/pull/100886 (should be mergeable, the ``cuda-vector-add:1.0`` image has been promoted)
- https://github.com/kubernetes/kubernetes/pull/100470 (needs to be rebased)

**Comment by BenTheElder** [comment]
IMHO that one is problematic because we are not going to host a `:latest` tag in k8s.gcr.io.

**Comment by claudiubelu** [comment]
> 
> 
> IMHO that one is problematic because we are not going to host a `:latest` tag in k8s.gcr.io.

True. We can give it a specific tag, which would make it more consistent too. The current latest image is this:

```
ubuntu@ubuntu:~/run_e2e/kubernetes$ docker run google/cadvisor:latest --version
cAdvisor version v0.32.0 (8949c822)
```

**Comment by BenTheElder** [comment]
I guess what I'm really getting at is that's a perhaps desirable but bigger change and probably we need to be talking to SIG Node

**Comment by voigt** [comment]
Hi there (@spiffxp, @claudiubelu, @chewong),
Bug-Triage here: given the current state of v1.22 release, does it make sense to move this issue to `milestone v1.23` (or even clear the milestone)?

**Comment by spiffxp** [comment]
There is one pending PR I would like to consult with release team on, I will link later

**Comment by dims** [comment]
@spiffxp which one is it?

**Comment by spiffxp** [comment]
@dims it's this one: https://github.com/kubernetes/kubernetes/pull/103724 but I think I've lost my fire to get really pushy about this so late in the cycle, so I'm going to punt to next milestone
