### ISSUE TITLE
shortname for clusterrolebindings 

### ISSUE THREAD

**Issue by marianopw** [kubernetes/kubernetes#96795]
**What would you like to be added**: It would be great to have a shortname for clusterrolebindings 

**Why is this needed**:  Because clusterrolebindings is one of the longest api-resources to type

**Comment by clarkmcc** [comment]
We should be able to fix this by implementing the `rest.ShortNamesProvider` for the `ClusterRoleBinding` `RESTStorage`. Anyone opposed to me making a PR for this?

```go
// Implement ShortNamesProvider
var _ rest.ShortNamesProvider = &REST{}

// ShortNames implements the ShortNamesProvider interface. Returns a list of short names for a resource.
func (r *REST) ShortNames() []string {
	return []string{"crb"}
}
```

**Comment by pacoxu** [comment]
dup with https://github.com/kubernetes/kubernetes/pull/44716 ? 

**Other solutions 1:**
There are some kube alias scripts like https://github.com/ahmetb/kubectl-aliases/blob/master/.kubectl_aliases

**Other solutions 2:**
https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-bash-completion
BTW, `bash completion` is very helpful .

**Comment by troy0820** [comment]
/close 
Closing in favor of response in https://github.com/kubernetes/kubernetes/pull/44716#issuecomment-296046596
