### ISSUE TITLE
inappropriate event logs during namespace destroy

### ISSUE THREAD

**Issue by dominicpg** [kubernetes/kubernetes#96793]
**What happened**:
events generated during namespace destroy is inappropriate. 

**What you expected to happen**:
appropriate event logs are expected

**How to reproduce it (as minimally and precisely as possible)**:
1) create namespace and initiate pod ( I have supplied ns in pod manifest )
2)  watch events. 
3) No resource clean-up (ie no kubectl delete pod) , just delete namespace created in step 1.

The same set of events generated during new POD spin will echo if I destroy the namespace without resource cleanup. Sample events

NAMESPACE   LAST SEEN   TYPE     REASON      OBJECT           MESSAGE
testns      33s         Normal   Scheduled   pod/testns-pod   Successfully assigned testns/testns-pod to node4
testns      32s         Normal   Pulling     pod/testns-pod   Pulling image "nginx"
testns      28s         Normal   Pulled      pod/testns-pod   Successfully pulled image "nginx" in 3.448607696s
testns      28s         Normal   Created     pod/testns-pod   Created container testns-container
testns      27s         Normal   Started     pod/testns-pod   Started container testns-container

**Environment**:

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

- OS :
NAME="CentOS Linux"
VERSION="7 (Core)"

- Kernel :
Linux node1 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pacoxu** [comment]
If you watch events, the watcher will get the deleted event when you delete it.

Event is a namespaced resource, so event cannot be created in a terminating namespace. 

You can refer to 
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#namespacelifecycle

The pod deletion events are recorded by kubelet. You can find you  kubelet logs for 
```
Nov 23 16:19:16 daocloud-master kubelet[59633]: E1123 16:19:16.129851   59633 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"nginx-deployment-latest-57846c4555-m2jdm.164a153a09adb4a5", GenerateName:"", Namespace:"testns", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"testns", Name:"nginx-deployment-latest-57846c4555-m2jdm", UID:"d9bcbf31-fe75-41a9-982c-dbe95f9fc95a", APIVersion:"v1", ResourceVersion:"1831334", FieldPath:"spec.containers{nginx}"}, Reason:"Killing", Message:"Stopping container nginx", Source:v1.EventSource{Component:"kubelet", Host:"daocloud-master"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbfe6fa01077d8ca5, ext:335546352208717, loc:(*time.Location)(0x6cfdc60)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbfe6fa01077d8ca5, ext:335546352208717, loc:(*time.Location)(0x6cfdc60)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "nginx-deployment-latest-57846c4555-m2jdm.164a153a09adb4a5" is forbidden: unable to create new content in namespace testns because it is being terminated' (will not retry!)
```

Event for the terminating namespace is unable to create new content in namespace testns because it is being terminated.

**Comment by dominicpg** [comment]
thanks for pointing the reason why I get old events in watcher.

> **2. Why no new events are generated?**
> Event is a namespaced resource, so event cannot be created in a terminating namespace.

If my understanding is correct, deletion process will cleanup the resources including pod even before ns dismantle and imo it's nice to have pod kill events in watcher to understand what's going on. Well, on the other hand, I agree that there's no point in capturing pod deletion event of a dying namespace!.

**Comment by pacoxu** [comment]
The detailed process would be

1. Delete Namespace Api sent
2. Namespace's deletionTimestamp is set, and the object's metadata.finalizers  is set.
3. ApiServer start to watch the ns finalizer
4. all resource are deleted in the ns, including pods and events. like`kubectl delete all --all -n xxx`
5. when no finalizer there, apiserver will delete the ns finally.

No event can be generated after the ns's deletionTimestamp is set.

To gain your goal, the fourth step above would change to something like delete pod firstly, generate pod killing events and delete events at the end.(IMO, it's necessary that no resources should be  created in the namespace, or we have to delete all things in a specified order. For instance, pod deletion should after rs/deployment/statefulset deletion. It will make the deletion of a namespace very complex. )

**Comment by dominicpg** [comment]
well, it seems any adjustment to reorder the deletion process will complicate things. I am happy with the knowledge you have shared and will open/re-open issue in future if required.  Thanks @pacoxu
