### ISSUE TITLE
[Flaking Test][sig-api-machinery] API priority and fairness should ensure that requests can be classified by testing flow-schemas/priority-levels

### ISSUE THREAD

**Issue by ScrapCodes** [kubernetes/kubernetes#96803]
**Which jobs are flaking**:
kind-master-parallel
ci-kubernetes-kind-e2e-parallel

**Which test(s) are flaking**:

 [sig-api-machinery] API priority and fairness should ensure that requests can be classified by testing flow-schemas/priority-levels

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#kind-master-parallel

**Reason for failure**:

```
test/e2e/apimachinery/flowcontrol.go:47
Nov 17 23:29:20.695: matching user doesnt received UID for the testing priority-level and flow-schema
vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113
```

**Anything else we need to know**:
- links to go.k8s.io/triage appreciated

https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=API%20priority%20and%20fairness%20should%20ensure%20that%20requests%20can%20be%20classified%20by%20testing%20flow-schemas%2Fpriority-levels

- links to specific failures in spyglass appreciated

  * https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1329161280430280704
  * https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1328838932024004608

**Comment by ScrapCodes** [comment]
Some interesting facts: Last failure was on 2020-11-18 20:37:19.

But this was changed (significantly) around the same time: https://github.com/kubernetes/kubernetes/commit/bcd3db095f8fcd0199b0b4efde6adb48fd7f54fe#diff-8272553f8f7c5ecaedd448a76b5688cec1eb280c5cd46cc85a0555e6bdf3b445

So, may be I should wait more, to have logs from the runs of latest code.

cc @adtac FYI.

**Comment by adtac** [comment]
cc @yue9944882

**Comment by thejoycekung** [comment]
Test also flaked here but with a different error: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1330803766412185600

```
test/e2e/apimachinery/flowcontrol.go:48
Nov 23 09:30:45.959: Unexpected error:
    <*errors.StatusError | 0xc002017e00>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "prioritylevelconfigurations.flowcontrol.apiserver.k8s.io \"e2e-testing-prioritylevel\" already exists",
            Reason: "AlreadyExists",
            Details: {
                Name: "e2e-testing-prioritylevel",
                Group: "flowcontrol.apiserver.k8s.io",
                Kind: "prioritylevelconfigurations",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 409,
        },
    }
    prioritylevelconfigurations.flowcontrol.apiserver.k8s.io "e2e-testing-prioritylevel" already exists
occurred
test/e2e/apimachinery/flowcontrol.go:232
```

**Comment by yue9944882** [comment]
> Test also flaked here but with a different error: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1330803766412185600

@thejoycekung thanks for providing the clue, #96798 will be fixing this

**Comment by RobertKielty** [comment]
Hi @saschagrunert could PTAL at the attached PR as it may fix this flake.

**Comment by saschagrunert** [comment]
> Hi @saschagrunert could you PTAL at the attached PR as it may fix this flake.

Hey, to which one of the linked PRs are you referring to?

**Comment by BenTheElder** [comment]
This is one of the few sources of flakes in some of our release blocking CI:

`Kubernetes e2e suite: [sig-api-machinery] API priority and fairness should ensure that requests can be classified by testing flow-schemas/priority-levels`


https://testgrid.k8s.io/sig-release-master-blocking#kind-master-parallel
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1347258532365340672
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1347181977345724416

AFAICT https://github.com/kubernetes/kubernetes/pull/96798 went in but we still have flakes.

I see a log like this each time:
> Jan  7 19:27:20.419: matching user doesnt received UID for the testing priority-level and flow-schema

see also https://github.com/kubernetes/kubernetes/issues/97511, it happens in presubmit too.

**Comment by liggitt** [comment]
This is still flaking frequently. The latest update in #96966 did not improve things (failed twice in the three hours since merge)

**Comment by mkorbi** [comment]
/milestone v1.22
/remove-lifecycle stale
still flaking

**Comment by mkorbi** [comment]
looks solved, thank you!
