### ISSUE TITLE
The ContainerStatuses of pod does not change to not ready when the container without readinessprobe exits abnormally

### ISSUE THREAD

**Issue by chenyw1990** [kubernetes/kubernetes#96804]
What happened:
The ContainerStatuses of pod does not change to not ready when the container without readnessprobe exits abnormally

![image](https://user-images.githubusercontent.com/1468240/99946556-804e2b80-2db1-11eb-9c9b-e157bb3a4165.png)

What you expected to happen:
ContainerStatuses change to not ready when  the container without readnessprobe exits abnormally

How to reproduce it (as minimally and precisely as possible):

Anything else we need to know?:

https://github.com/kubernetes/kubernetes/pull/92196/commits/64d42542174d22968c424ba4b976b5e1055647cd
I think we should change the ready to false when container is not started.

Environment:

Kubernetes version (use kubectl version): "v1.19.0"
Cloud provider or hardware configuration:
OS (e.g: cat /etc/os-release): "EulerOS 2.0 (SP9)
Kernel (e.g. uname -a): Linux 4.19.90-vhulk2009.2.0.h269.eulerosv2r9.aarch64 #1 SMP Sun Sep 27 12:47:01 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
Install tools:
Network plugin and version (if this is a network-related bug):
Others:

**Comment by andrewsykim** [comment]
@chenyw1990 can you share the pod spec you used to reproduce this bug?
