### ISSUE TITLE
Non socket files should be ignored while a kubelet plugin is been unregistering.

### ISSUE THREAD

**Issue by mcsos** [kubernetes/kubernetes#96827]
**What happened**:

In pluginmanager of Kubelet, the handleDeleteEvent() is triggered when a file in /var/lib/kubelet/plugins_registry/ has been deleted. But the Watcher does not check whether the file is a socket file or not, just as it does in handleCreateEvent().

And the log may also make people confused.

https://github.com/kubernetes/kubernetes/blob/ad2bf99f9b8f27113cd3b0c9e0ad72e568947e43/pkg/kubelet/pluginmanager/pluginwatcher/plugin_watcher.go#L205-L211

**What you expected to happen**:

Verify the file is a socket file before executing the desiredStateOfWorld.RemovePlugin function in handleDeleteEvent().

**How to reproduce it (as minimally and precisely as possible)**:

1. Set the log level of Kubelet to level 6.
2. touch /var/lib/kubelet/plugins_registry/x.txt
3. rm -f /var/lib/kubelet/plugins_registry/x.txt
4. We will get the the following log:
  ```
  20:43:23 kubelet[4253]: I1123 16:43:23.891399    4253 plugin_watcher.go:160] Handling create event: "/var/lib/kubelet/plugins_registry/x.txt": CREATE
  20:43:23 kubelet[4253]: I1123 16:43:23.891448    4253 plugin_watcher.go:178] Ignoring non socket file x.txt
  20:43:37 kubelet[4253]: I1123 16:43:37.123243    4253 plugin_watcher.go:206] Handling delete event: "/var/lib/kubelet/plugins_registry/x.txt": REMOVE
  20:43:37 kubelet[4253]: I1123 16:43:37.123280    4253 plugin_watcher.go:209] Removing socket path /var/lib/kubelet/plugins_registry/x.txt from desired state cache
  ```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
  ```
  # kubectl version
  Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.0-beta.2.30+e64ebe01314b41-dirty", GitCommit:"e64ebe01314b41fa68cff827a31ab133ec6963a4", GitTreeState:"dirty", BuildDate:"2020-11-20T06:09:55Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.0-beta.2.30+e64ebe01314b41-dirty", GitCommit:"e64ebe01314b41fa68cff827a31ab133ec6963a4", GitTreeState:"dirty", BuildDate:"2020-11-20T06:09:55Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
  ```
  # cat /etc/os-release
  NAME="CentOS Linux"
  VERSION="7 (Core)"
  ID="centos"
  ID_LIKE="rhel fedora"
  VERSION_ID="7"
  PRETTY_NAME="CentOS Linux 7 (Core)"
  ANSI_COLOR="0;31"
  CPE_NAME="cpe:/o:centos:centos:7"
  HOME_URL="https://www.centos.org/"
  BUG_REPORT_URL="https://bugs.centos.org/"

  CENTOS_MANTISBT_PROJECT="CentOS-7"
  CENTOS_MANTISBT_PROJECT_VERSION="7"
  REDHAT_SUPPORT_PRODUCT="centos"
  REDHAT_SUPPORT_PRODUCT_VERSION="7"
  ```
- Kernel (e.g. `uname -a`):
  ```
  # uname -a
  Linux node1 3.10.0-1160.2.2.el7.x86_64 #1 SMP Tue Oct 20 16:53:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
  ```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by matthyx** [comment]
@mcsos I am wondering what could create non-socket files in `/var/lib/kubelet/plugins_registry/` ?

**Comment by mcsos** [comment]
@matthyx  Thank you for your reply.

Well, while reading code, I noticed the log may make people confused.
If there is no need for that, I'll close the issue and the pr.
