### ISSUE TITLE
kubeadm upgrade (v1.19+) does not retain coredns configmap

### ISSUE THREAD

**Issue by darthcorsair** [kubernetes/kubernetes#96833]
**What happened**:
`kubeadm upgrade apply -y v1.19.3` does not retaining coredns configmap

```
...
[dryrun] Would perform action GET on resource "configmaps" in API group "core/v1"
[dryrun] Resource name: "coredns"
[dryrun] Returning faked GET response:
	apiVersion: v1
	data:
	  Corefile: |
	    consul {
	        errors
	        forward . 10.106.96.16:8600 10.106.96.17:8600 10.106.96.18:8600
	        loadbalance
	        cache 5
	        reload
	    }
...
[dryrun] Would perform action CREATE on resource "configmaps" in API group "core/v1"
[dryrun] Attached object:
	apiVersion: v1
	data:
	  Corefile: |
	    .:53 {
	        errors
	        health {
	           lameduck 5s
	        }
	        ready
	        kubernetes cluster.local in-addr.arpa ip6.arpa {
	           pods insecure
	           fallthrough in-addr.arpa ip6.arpa
	           ttl 30
	        }
	        prometheus :9153
	        forward . /etc/resolv.conf {
	           max_concurrent 1000
	        }
	        cache 30
	        loop
	        reload
	        loadbalance
	    }
	kind: ConfigMap
	metadata:
	  creationTimestamp: null
	  name: coredns
	  namespace: kube-system
...
```
using v1.19.4 makes no difference

**What you expected to happen**:

`kubeadm upgrade apply` should  follow documentation and retain coredns configmap

**How to reproduce it (as minimally and precisely as possible)**:
upgrading from v1.18.6 to v1.19.3

**Anything else we need to know?**:
`kubeadm upgrade apply -y v1.18.12` works like a charm

```
[dryrun] Resource name: "coredns"
[dryrun] Attached patch:
	{"spec":{"template":{"spec":{"volumes":[{"name": "config-volume", "configMap":{"name": "coredns", "items":[{"key": "Corefile-backup", "path": "Corefile-backup"}]}}]}}}}
W1124 12:32:32.521106   19721 dns.go:282] the CoreDNS Configuration was not migrated: unable to migrate CoreDNS ConfigMap: start version '1.7.0' not supported. The existing CoreDNS Corefile configuration has been retained.
[dryrun] Would perform action GET on resource "configmaps" in API group "core/v1"
...
[dryrun] Would perform action UPDATE on resource "configmaps" in API group "core/v1"
[dryrun] Attached object:
	apiVersion: v1
	data:
	  Corefile: |
	    consul {
	        errors
	        forward . 10.106.96.16:8600 10.106.96.17:8600 10.106.96.18:8600
	        loadbalance
	        cache 5
	        reload
	    }
...
```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.6
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): CentOS 7
- Kernel (e.g. `uname -a`): 4.20.13-1.el7.elrepo.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
seems to be a regression ?

**Comment by pacoxu** [comment]
@darthcorsair Would you check you dns configmap for `federation` ?

As https://github.com/kubernetes/kubernetes/pull/92716/files#diff-b15061fc6de5ba90bf53e91855f1a4b752bc7e382aed6f5691265e86001f2b03L48 , federation is removed from coredns. 

If you have federation enabled in your coredns configmap, the check may fail in https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/upgrade/preflight.go#L74

**Comment by darthcorsair** [comment]
We don't have any `federation` parameter in our coredns configmap, or any kube-dns parameters in kubeadm config

**Comment by chrisohaver** [comment]
Looking closely at the dry run messages above, this may not be a regression. The apparent reason it works in 1.18.12 is that support for CoreDNS 1.7.0 was not added until 1.19.  i.e. 1.18 sees an unsupported version of CoreDNS and therefore skips the corefile migration.  Whereas in  1.19, CoreDNS 1.7.0 _is_ supported, and the migration takes place.

@darthcorsair, What does your complete Corefile look like before the migration?

**Comment by rajansandeep** [comment]
@darthcorsair If it's possible, can you also attach the entire dry run logs?

**Comment by darthcorsair** [comment]
> @darthcorsair, What does your complete Corefile look like before the migration?
https://gist.github.com/darthcorsair/02fbc51b1c7eebe9c17ca26e22b8d95a

> @darthcorsair If it's possible, can you also attach the entire dry run logs?
 Sure. https://gist.github.com/darthcorsair/ae9ae7d9272dd771fb7fc0403edba0d4

**Comment by chrisohaver** [comment]
Thanks.  I think the issue may be in the detection of the "default" configuration. That is, in the upgrade process, if it detects that you are using the "default" coredns corefile, it simply installs the new default over top of it, rather than migrating the existing one.  If i'm right, the fix could either go in the `coredns/corefile-migration` package (should at least eventually be fixed there), and/or kubeadm could just always migrate the existing config instead of deploying the default over top of the existing one.

**Comment by chrisohaver** [comment]
> Thanks. I think the issue may be in the detection of the "default" configuration.

I just tested against the package manually - and it correctly identifies the config as "non-default", so that's not it...
And I also tested a migration on the Corefile, and the result included the extra stanzas as expected.  So, the issue doesn't _appear_ to lie in the migration package.

**Comment by pacoxu** [comment]
After testing with the code, I find the issue in https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/upgrade/preflight.go#L132-L134, I fixed it in #96860 .

A workaround for you is to create a empty kube-dns configmap.

**Comment by darthcorsair** [comment]
Thanks, I'll try it

**Comment by darthcorsair** [comment]
empty kube-dns configmap doesn't helped.

```
[dryrun] Would perform action CREATE on resource "configmaps" in API group "core/v1"
[dryrun] Attached object:
	apiVersion: v1
	data:
	  Corefile: |
	    .:53 {
	        errors
	        health {
	           lameduck 5s
	        }
	        ready
...
```

**Comment by pacoxu** [comment]
@darthcorsair  sorry for my mistake.

According to my test, the create or update will  trigger is no migrating. 
Even your corefile will meet some `newdefault` dep that need to be migrated. 
```
        forward . 10.10.0.140 10.10.0.240 10.10.51.40 {
            max_concurrent 1000
        }
```
max_concurrent is new default. However, there is a typo in #96907.

 Below is a workaround(not good one), add upstream to your  corefile in kubernetes. 
```
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
          upstream
        }
```
![image](https://user-images.githubusercontent.com/2010320/100436811-d33e2080-30da-11eb-9f10-d6fa72f92a69.png)

It works for me.

**Comment by pacoxu** [comment]
if your current coredns is 1.6.7, upstream is  deprecated but not removed.

In new 1.7.0 coredns, upstream is removed.

https://github.com/kubernetes/kubernetes/blob/5ed4b76a03b5eddc62939a1569b61532b4a06a72/vendor/github.com/coredns/corefile-migration/migration/plugins.go#L189-193

**Comment by neolit123** [comment]
thanks for the discussion and PRs @pacoxu 

this one is mergable for 1.21 as non critical:
https://github.com/kubernetes/kubernetes/pull/96860

@chrisohaver @rajansandeep what do you think about this one and should we backport it as critical (also, to which k8s versions)?
https://github.com/kubernetes/kubernetes/pull/96907

**Comment by chrisohaver** [comment]
It's not obvious to me how this relates to #96907. 

The kubeadm dry run log appears to be replacing the existing config with the default.
https://gist.github.com/darthcorsair/ae9ae7d9272dd771fb7fc0403edba0d4#file-kubeadm-log-L8599-L8628

It should only be doing this if the existing config is semantically the same as a default Corefile, i.e. if `migration.Default()` is true.

**Comment by neolit123** [comment]
> It's not obvious to me how this relates to #96907.

#96907 just explains that the migration is not triggered at all.
@pacoxu if #96907 is not a fix for this issue, please remove this line from the PR description.

> Fixes #96833

**Comment by chrisohaver** [comment]
I think issue here is in/around `isCoreDNSConfigMapMigrationRequired`, and how the result is interpreted...

The code _correctly_ assumes that if a Corefile is a default Corefile, then no migration is required.
However later it _incorrectly_ assumes the reciprocal: If migration is not required, then the corefile must be a default.
Hence, it ends up replacing any Corefile that does not require migration with a default… even if it wasn't a default to begin with.

**Comment by pacoxu** [comment]
@chrsohaver yes. The `isCoreDNSConfigMapMigrationRequired ` need be fixed as well, I will learn to fix it later. 

@neolit123  I changed releaseNote to None.
