### ISSUE TITLE
K8s creates too many Security Groups for NLB Health Check | Reloaded!

### ISSUE THREAD

**Issue by nsmith5** [kubernetes/kubernetes#96840]
**What happened**:

For each NLB created, K8s creates an ingress rule on the node group's security group for each port exposed for each NLB subnet to allow health checks to succeed.

AWS limits the number of rules per security group to 60 by default. This quota is adjustable but multiplied by the quota for security groups per network interface cannot exceed 1000.
https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html#vpc-limits-security-groups

If, for instance, you have a VPC with 1 CIDR block and 3 NLB subnets (a common design). This means that we would have 4 new rules per NLB port exposed (3 Health Check and 1 Client). This caps the number of NLB ports exposed to 15, which is easily reached.

**What you expected to happen**:
I expect more reasonable limits than 15 exposed ports via NLB in the common situation of a 3 AZ VPC with one CIDR block.

**How to reproduce it (as minimally and precisely as possible)**:

Create a VPC with 1 CIDR block (e.g. 10.0.0.0/16) and 3 subnets (one per AZ). Install an EKS cluster running 1.16 eks.4 (this is 1.16.15 and there for contains the change https://github.com/kubernetes/kubernetes/pull/93515 that reproduces this issue). Attempt to create 15 NLB `LoadBalancer` Services with one port each in the cluster.

**Anything else we need to know?**:

Due to https://github.com/kubernetes/kubernetes/pull/93515, we now use NLB subnet CIDRs to create health check security groups. This means that the rules are now proportional to NLB availability zones instead of VPC CIDR blocks. In the common case of few (e.g one) VPC CIDR blocks and multiple NLB availability zones, this leads to worse outcomes than those prior to https://github.com/kubernetes/kubernetes/pull/93515.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.15 (1.16 eks.4)
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g: `cat /etc/os-release`): Amazon Linux
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by nsmith5** [comment]
Other version that are likely affects:
- [1.17.11+](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md#changelog-since-v11711)
- [1.18.8+](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#changelog-since-v1188)
- [1.19.0+](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#changelog-since-v1190)

**Comment by bgdnlp** [comment]
Just got bit by this on 1.19. Is there any resolution or workaround?

Is it possible to disable adding rules at all maybe, let us create a blanket rule in advance instead?

Or allow specifying a SG to attach to the load balancers, which is already given access to all ephemeral ports o the cluster, instead of creating a set of 3-6 rules for each port?

**Comment by nsmith5** [comment]
Yeah, the work around my team was suggested by our AWS rep was to use this AWS Load Balancer controller instead: https://github.com/kubernetes-sigs/aws-load-balancer-controller. It manages security groups slightly differently and ends up having more capacity as a result

**Comment by bgdnlp** [comment]
Just to confirm, as far as I see that's the "old" ALB Ingress Controller. It also works with NLBs now and it plays nice with the VPC CNI when both of them are active?

I could ask support, but I imagine others might hit this page too.

**Comment by kishorj** [comment]
@nsmith5, the in-tree controller is deprecated and new changes are limited to critical bug fixes only. We recommend setting up the [AWS Load balancer controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller) for NLB. The recent v2.2.0 release of the AWS LB controller has support for NLB instance targets, and if the health check port and traffic port are the same and traffic is allowed from 0.0.0.0/0, the health check rules don't get added. The AWS LB controller also doesn't add MTU rules for NLB.

I'm closing this issue.

/close
