### ISSUE TITLE
Storage: Failed to provision volume with StorageClass on Vsphere

### ISSUE THREAD

**Issue by zhoudayongdennis** [kubernetes/kubernetes#96847]
observe below error message during volume creation, and error was reported in pv_controller#1568, but not quite clear why "folder 'AA/BB' not found" and what's possible cause?

https://github.com/kubernetes/kubernetes/blob/c678434623be4957d892a9865e5649f887a40c49/pkg/controller/volume/persistentvolume/pv_controller.go#L1568

 Warning  ProvisioningFailed  73s (x22 over 34m)  persistentvolume-controller  Failed to provision volume with StorageClass "vsphere": folder 'AA/BB' not found
--> cloud.conf

root@sqmct01 cloud-user]# cat /etc/kubernetes/cloud.conf
[Global]
insecure-flag = "1"
secret-name = "vcconf"
secret-namespace = "kube-system"
port = 443
[VirtualCenter "1.2.3.4"]
[Workspace]
datacenter = ZKW_Cloud_DataCenter
server = 1.2.3.4
folder = AA/BB
default-datastore = BB_Containers_Data
resourcepool-path = BB_Resource_Pool

 

[Disk]
scsicontrollertype = pvscsi

--> GOVC - NOKIA/SQM folder exist and was never changed:

CLCM-19.12.1 root@sqmdep:~/CSF-CLCM]$ govc ls /ZKW_Cloud_DataCenter/vm/AA/BB
/ZKW_Cloud_DataCenter/vm/AA/BB/bcmt-deployserver
/ZKW_Cloud_DataCenter/vm/AA/BB/sqmbackup
/ZKW_Cloud_DataCenter/vm/AA/BB/sqmdep
/ZKW_Cloud_DataCenter/vm/AA/BB/sqmedg01

**Comment by zhoudayongdennis** [comment]
in k8s controller logs, there were below errors

E1123 14:52:12.494110       1 datacenter.go:231] Failed to get the folder reference for NOKIA/SQM. err: folder 'NOKIA/SQM' not found
E1123 14:52:12.494182       1 vsphere.go:1358] failed to set VM options required to create a vsphere volume. err: folder 'NOKIA/SQM' not found
E1123 14:52:12.494281       1 goroutinemap.go:150] Operation for "provision-sqm/datadir-csf-csdc-dependencies-csdc-0[8fec3ed6-2079-41e2-bb1c-fb09385c58f3]" failed. No retries permitted until 2020-11-23 14:52:16.49426318 +0000 UTC m=+1647746.629786419 (durationBeforeRetry 4s). Error: "folder 'NOKIA/SQM' not found"

searched the source code, but not sure what's the issue, **full path??**

// GetFolderByPath gets the Folder Object from the given folder path
// folderPath should be the full path to folder
func (dc *Datacenter) GetFolderByPath(ctx context.Context, folderPath string) (*Folder, error) {
	finder := getFinder(dc)
	vmFolder, err := finder.Folder(ctx, folderPath)
	if err != nil {
		**klog.Errorf("Failed to get the folder reference for %s. err: %+v", folderPath, err)**
		return nil, err
	}
	folder := Folder{vmFolder, dc}
	return &folder, nil
}

**Comment by zhoudayongdennis** [comment]
it seems only one level path supported by K8s, and AA/BB path could NOT handle well currently.

please consider the enhance for that.

**Comment by pacoxu** [comment]
/sig cloud-provider
/area provider/vsphere
?
