### ISSUE TITLE
Kubelet disconnects from apiserver after etcd read-only, not recovering

### ISSUE THREAD

**Issue by sfudeus** [kubernetes/kubernetes#96842]
**What happened**:

When the storage quota of etcd is reached, it goes into a read-only state, which must be recovered by defragging and disarming the alarm. While read-only the apiserver cannot persist any data. 
When the etcd recovers into a writeable state, the apiserver gets usable again. If the read-only time has been too long (e.g. > 7 minutes during tests), at least some kubelets had been disconnected from the apiserver and would not recover the connection on their own. Restarting the kubelets would solve the problem. 
The behaviour even changed between 1.18.10 and 1.18.12. 
With 1.18.10, the node status went into non-ready state. 
With 1.18.12, all nodes stayed ready in the apiserver, despite them being detached. Pods stayed in terminating or pending state (scheduler still scheduled pods there, since they were marked ready). 
A maybe secondary bug here even was that our monitoring only noticed some kubelets being not scrapable, other could be scraped. Being able to scrape a kubelet was not a guarantee that it is properly processing pods. 

**What you expected to happen**:

When etcd recovers, nodes should go into not-ready state if kubelet connection is broken. Kubelets would reconnect and update their health status without manual intervention. Ideally, to prevent all endpoint being marked unhealthy and kube-proxy removing all endpoints, the kubelets would reconnect fast enough. 

**How to reproduce it (as minimally and precisely as possible)**:

* Use low storage quota in etcd and do something which writes data into etcd (either bypass k8s oder e.g. create a large deployement with many endpoints). 
* Keep etcd in read-only state for a bit (some minutes in our case, not sure how long is required). 
* Compact etcd and disarm the alarm - you can observe nodes becoming not ready in 1.18.10. 
* E.g. deploy a daemon set and observe which pods are getting scheduled but not started as an indicator which kubelets have a broken connection. 

**Anything else we need to know?**:

Partially, restarting kube-controller-manager was required as well, its connection seemed stuck, too. We didn't do so much testing when/if that was required. Restarting controller-manager alone was no solution to the problem. 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.10 and 1.18.12
- Cloud provider or hardware configuration: bare-metal, 20-50 physical cores, 390G RAM, 
- OS (e.g: `cat /etc/os-release`): FlatCar 2605.7.0
- Kernel (e.g. `uname -a`): 5.4.72-flatcar
- Install tools: custom (using FlatCar, Matchbox, consul-template, ...)
- Network plugin and version (if this is a network-related bug): calico 3.16.5
- Others: etcd 3.4.10

**Comment by sfudeus** [comment]
This might be related to #87615, but we couldn't trigger the same behavior when rejecting or dropping kubelet/apiserver interaction, this happened only by etcd in read-only.

**Comment by fedebongio** [comment]
ccing a group of people that may have thoughts on this one:
@caesarxuchao @wojtek-t 
also @jingyih just to confirm that is not an etcd problem

**Comment by lfwelty** [comment]
fyi - we saw the same issue on k8s v1.18.10 - we reverted to k8s v1.18.9 and believe we are no longer seeing the problem.

**Comment by sfudeus** [comment]
I tried to reproduce this with a mixed cluster of 1.19.9 and 1.19.13, but failed. Maybe this was fixed with the 1.19. 
In another cluster with 1.20.8, I couldn't reproduce either. 

From my perspective, this can be closed.
