### ISSUE TITLE
application/apply-patch+yaml does not retain ResourceVersion when patching v1/Secret:stringData

### ISSUE THREAD

**Issue by synox** [kubernetes/kubernetes#96841]
**What happened**:
When using `kubectl apply` with the "stringData" property, a new resourceVersion is created after each run with the same YAML. 

**What you expected to happen**:
The resourceVersion should stay the same. 

**How to reproduce it (as minimally and precisely as possible)**:
```
cat <<EOF > hello-node.json
{
    "apiVersion": "v1",
    "stringData": {         "accessKey": "asdf"    },
    "kind": "Secret",
    "metadata": {
        "name": "hello-node",
        "namespace": "default"
    },
    "type": "Opaque"
}
EOF

# create 
minikube kubectl -- apply --server-side -f hello-node.json
minikube kubectl -- get secret/hello-node -o custom-columns="NAME:.metadata.name,VERSION:.metadata.resourceVersion"
NAME         VERSION
hello-node   193917

# update 
minikube kubectl -- apply --server-side -f hello-node.json
minikube kubectl -- get secret/hello-node -o custom-columns="NAME:.metadata.name,VERSION:.metadata.resourceVersion"
NAME         VERSION
hello-node   193977
```

**Anything else we need to know?**:
If you replace the `stringData:` with `"data": {        "accessKey": "YXNkZg=="    },` it works. 

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: local with minikube v1.14.2
- OS (e.g: `cat /etc/os-release`): macOs 10.15.7 (19H15)
- Kernel (e.g. `uname -a`): Darwin asdf-macOS 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64

- Install tools: -
- Network plugin and version (if this is a network-related bug): -
- Others:

**Comment by pacoxu** [comment]
it may be related with auto convert between core secret with v1 secret. 

Will read the code later.

**Comment by synox** [comment]
@pacoxu can you recommend a workaround?

**Comment by pacoxu** [comment]
After reading the comments from https://github.com/kubernetes/kubernetes/issues/89938#issuecomment-656206971 , it seems to be not expected to update secrets using `kubectl apply` since the feature discussions. 

As I tried, apply with same data fields will not change the resource version. apply with same StringData would change the resource version as the conversion fo v1 secret to core secret only happened in server side later.

> apelisse commented on 9 Jul • 
> From #22059 (comment), a good prediction from Brian ;-):
> 
> I definitely would not want to do this anywhere else, since it would break kubectl apply and probably other things. However, users shouldn't use kubectl apply on secrets, so that reason isn't relevant in this case.
> 
> I still have no idea how to fix that.


**Suggested Workaround/Solution**
Do not use kubectl apply to edit secrets, use kubectl edit or kubectl replace.

Suggestions from https://github.com/kubernetes/kubernetes/issues/89938#issue-596195483

**Comment by synox** [comment]
Thank you for the information and workaround. It should also be noted that Secrets should be created as immutable: https://kubernetes.io/docs/concepts/configuration/secret/#secret-immutable
