### ISSUE TITLE
Pods receive traffic from load balancer whilst in terminating state for >60s

### ISSUE THREAD

**Issue by eddspencer** [kubernetes/kubernetes#96858]
**What happened**:
Pods are not being removed swiftly enough from the load balancer when terminating, this is causing 502 errors when the application on the pod eventually stops, ~2 minutes after pod enters Terminating state, as the load balancer is still trying to route traffic to it. 

N.B. we believe this to not be a duplicate of https://github.com/kubernetes/kubernetes/issues/88236 as this takes >60s and seems heavily reliant on the 'idle timeout' configuration of the load balancer.

**What you expected to happen**:
When a pod is terminated by EKS (due to a deployment or scale down) the pod is swiftly removed from the load balancer and all traffic is directed at one of the remaining 'Running' pod, as we can see from https://learnk8s.io/graceful-shutdown:

First, the endpoint should be removed from the Endpoint (object).
This time the Readiness probe is ignored, and the endpoint is removed immediately from the control plane.
That, in turn, fires off all the events to kube-proxy, Ingress controller, DNS, service mesh, etc.
Those components will update their internal state and stop routing traffic to the IP address.
Since the components might be busy doing something else, there is no guarantee on how long it will take to remove the IP address from their internal state.
For some, it could take less than a second; for others, it could take more.

There is no guarantee of the time taken to remove the IP as it specifies but do not expect this to be >60s.

**How to reproduce it (as minimally and precisely as possible)**:
EKS deployment with horizontal pod autoscaling and application load balancer configured via ingress (v1.1.9), we have also tested this with the newer Load Balancer Controller v2.0 receiving the same results.

1. Idle timeout set to 300 in controller:
```
    alb.ingress.kubernetes.io/load-balancer-attributes: "idle_timeout.timeout_seconds=300"
```

2. Add sleep in preStop:
```
        lifecycle:
          preStop:
            exec:
              command: [
                "sh", "-c", "sleep 120"
              ]
```

3. Send steady stream of traffic to load balancer (we have been using rate of 1 request/s from a single client to test this)

4. Terminate pod (manually or via deployment)

5. Check access logs, can see traffic routed to terminated pod right up to the 120s mark.

**Anything else we need to know?**:

Health probe of the deployment will return 200 provided the application is running and can serve requests, this continues to happen during our 'graceful shutdown' period, although when the graceful shutdown starts we are expecting no new requests.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.17.9-eks-4c6976
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g: `cat /etc/os-release`): Alpine Linux 3.9.4
- Kernel (e.g. `uname -a`): Linux ws-main 4.14.198-152.320.amzn2.x86_64
- Install tools: helm
- Network plugin and version (if this is a network-related bug): N/A
- Others:

**Comment by WarheadsSE** [comment]
@eddspencer We bumped into [something similar at GitLab](https://gitlab.com/gitlab-com/gl-infra/delivery/-/issues/1358#note_459061429), and went digging. We found this issue, which rang quite a few bells with what we were seeing.

In the end, testing showed that the ingress proxy itself (in our case, NGINX Ingress' own NGINX daemon) may _rightly_ hold open a connection to the original pod, re-using that for future client requests. We simply need to better tune this, unless we can convince that proxy controller to actively prune based on Endpoint changes.

**Comment by thockin** [comment]
Just to be clear - was it correctly removed from Endpoints?  This sounds like an EKS issue not a k8s issue?

**Comment by jayunit100** [comment]
Hi @eddspencer  ... this is an interesting issue, have seen it before on different LBs as well, so I talked to  @mattfenwick some about it... I believe he has seen this on different clouds as well. 

- So - your talking about, specifically , the elastic-load-balancer, which is https://github.com/kubernetes-sigs/aws-load-balancer-controller, right ?   

- I dug around and saw https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1131 which seems similar (node scaling resulted in pods that were terminating **not** being removed fast enough).

- Qouting from that issue...  looks like its really an AWS LB issue, and the workaround is , as mentioned by @WarheadsSE is similar to that for other LBs, tuning of the LB itself.   To quote from 1131:

```
However, I still feel that merging of #955 will not solve the issue, because there will still potentially be a delay between Kubernetes terminating a pod and a delay in ingress controller removing the target from ALB. That delta in time can potentially lead to 502s or 504s in the service. Unless we get to an RCA of this lag, I don't see that issue getting fixed. Do let me know if I could help in any way.
```
So I think...  It sounds like there are different flavors of this, but they generally are in the category, as you suggest, of changing the options to https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html 

Is that sufficient as a workaround, or do you specifically think there's a **kubernetes** bug?  If the former, then I guess we can close this?

**Comment by eddspencer** [comment]
Many thanks for your responses, let me try to answer all questions:

- Yes, we are talking about the interaction with elastic-load-balancer controller. New traffic is being directed from the load balancer to the terminating pod for over a minute after the pod state changed to `Terminating`.
- I am not sure if it is being correctly removed from the Endpoints, are there some steps I can run to check this? In general have found it hard to track the propagation of events after the pod is terminated so any help here would be greatly appreciated.
- As mentioned in the initial description we can 'control' this using the `idle timeout` configuration of the load balancer, however, we need a large idle timeout for our business logic. We do not expect this idle timeout to effect the speed new requests are routed away from terminating pods as this is related to long running 'current' requests.

So unfortunately that is not a sufficient workaround for us, however, that does not make it a bug directly with kubernetes. Is there some process/logs I can run/check to see the correct events are sent from kubernetes to the load balancer confirming it is on that end?

**Comment by thockin** [comment]
> New traffic is being directed from the load balancer to the terminating pod for over a minute after the pod state changed to Terminating

So that seems like "clearly" an LB controller bug unless...

> I am not sure if it is being correctly removed from the Endpoints, are there some steps I can run to check this? 

`kubectl get endpoints <svcname>`- the terminating endpoint should be gone (may need `-o yaml` to see a large list)

**Comment by eddspencer** [comment]
Thanks @thockin that seems pretty conclusive the me - the endpoints are updated as soon as the pod is changed to the terminated state. 

Just so I am clear what does that mean exactly so I know who to contact on this? It is my understanding that the endpoints define which pods a service can connect to, and so is it guaranteed that if the endpoint list is correct we have sent the command to the actual load balancer to remove the pod/instance?

**Comment by eddspencer** [comment]
So in case anyone stumbles across this and are having a similar problem - specifically the time taken to remove a pod from and AWS application load balancer being dependant on the `idle timeout` set - then we seem to have stumbled across the solution.

We had the ingress-controller `target-type` set to `instance` - which came from when we were using a classic load balancer. Setting the `target-type` to `ip` solves the issue and the pod is removed within 15s as expected.

Many thanks for your help.

**Comment by foriequal0** [comment]
Hi @eddspencer! Would you check out the controller that I've made to solve this issue? https://github.com/foriequal0/pod-graceful-drain

**Comment by constantineZum** [comment]
> So in case anyone stumbles across this and are having a similar problem - specifically the time taken to remove a pod from and AWS application load balancer being dependant on the `idle timeout` set - then we seem to have stumbled across the solution.
> 
> We had the ingress-controller `target-type` set to `instance` - which came from when we were using a classic load balancer. Setting the `target-type` to `ip` solves the issue and the pod is removed within 15s as expected.
> 
> Many thanks for your help.

@eddspencer or anyone else, do you understand why this happened?
