### ISSUE TITLE
k8s unit tests fail with a mismatch in error message while run with master golang

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [kubernetes/kubernetes#96853]
**What happened**:
Below k8s UT fail when run with master-golang.
1. k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/state: TestCheckpointStateRestore/Restore_checkpoint_with_invalid_JSON
error:=== RUN   TestCheckpointStateRestore/Restore_checkpoint_with_invalid_JSON
I1124 05:38:14.686883   60889 state_mem.go:36] [cpumanager] initializing new in-memory state store
    state_checkpoint_test.go:236: unexpected error while creatng checkpointState: could not restore state from checkpoint: json: unexpected end of JSON input, please drain this node and delete the CPU manager checkpoint file "/tmp/cpumanager_state_test479660663/cpumanager_checkpoint_test" before restarting Kubelet
    --- FAIL: TestCheckpointStateRestore/Restore_checkpoint_with_invalid_JSON (0.00s)
2. k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers: TestStrategicMergePatchInvalid
error:=== RUN   TestStrategicMergePatchInvalid
    rest_test.go:127: expected "invalid character 'b' looking for beginning of value", got "json: invalid character 'b' looking for beginning of value"
--- FAIL: TestStrategicMergePatchInvalid (0.00s)
3. k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers: TestJSONPatch
error:=== RUN   TestJSONPatch
    rest_test.go:175: invalid-syntax: expected error invalid character 'i' looking for beginning of value, but got json: invalid character 'i' looking for beginning of value
--- FAIL: TestJSONPatch (0.00s)
4. k8s.io/kubernetes/vendor/k8s.io/client-go/tools/remotecommand: TestV4ErrorDecoder expand_less
error:=== RUN   TestV4ErrorDecoder
    v4_test.go:68: wrong error for message "{": want="error stream protocol error: unexpected end of JSON input in \"{\"", got="error stream protocol error: json: unexpected end of JSON input in \"{\""
--- FAIL: TestV4ErrorDecoder (0.00s

**What you expected to happen**: The tests should pass with no error.

**How to reproduce it (as minimally and precisely as possible)**:
1. Have a stable version of golang installed
2. Install master go from upstream
git clone https://github.com/golang/go.git
cd go/src
./make.bash
cd ../..
cp -r ./go /usr/local
export PATH=/usr/local/go/bin:$PATH
3. Clone kubernetes repo and run the unit tests. (https://github.com/kubernetes/kubernetes)
**Anything else we need to know?**:
These failures are occurring due to mismatch of error messages between upstream go and the k8s tests.
There is an addition "json:" prefix to SyntaxError messages after this below commit:
https://github.com/golang/go/commit/6af088bfc66c13143c9ef46b4cf0805df77a8fbe
```
In Go 1.15, scanner.go:
func (e *SyntaxError) Error() string { return e.msg }
In Go master, scanner.go:
func (e *SyntaxError) Error() string { return "json: " + e.msg }
```
**Environment**:
- Kubernetes version (use `kubectl version`): latest source code from upstream
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`):  "CentOS Linux 8 (Core)"
- Kernel (e.g. `uname -a`): Linux rajalakshmi-workspace 4.18.0-193.19.1.el8_2.ppc64le #1 SMP Mon Sep 14 14:48:04 UTC 2020 ppc64le ppc64le ppc64le GNU/Linux
- Install tools: 
[root@rajalakshmi-workspace go]# go version
go version devel +c72a448881 Fri Nov 20 00:54:43 2020 +0000 linux/ppc64le
[root@rajalakshmi-workspace go]#
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
https://github.com/golang/go/issues/42675  will fix it in Go 1.16 as release-blocker.

**Comment by liggitt** [comment]
I would fix the test here to be more tolerant. exact string matches on error messages aren't really an API… I would not expect that to block the golang release

**Comment by mkumatag** [comment]
> I would fix the test here to be more tolerant. exact string matches on error messages aren't really an API… I would not expect that to block the golang release

Agree too, we can think about having a substring match to avoid these issues instead!

**Comment by mkumatag** [comment]
/assign @Rajalakshmi-Girish 
Lets see if we can fix this in the k8s tests
