### ISSUE TITLE
k8s persistent volume data gets deleted after pod recreation many times with all ReclaimPolicy:Retain,Recycle,Delete

### ISSUE THREAD

**Issue by samdgoyal123** [kubernetes/kubernetes#96859]
1) i created one PV(persistent volume) using .yaml file 5G on hostpath locally "/mnt/data-pv2/pv0003"
2) created PVC of 3G pf PV
3) created pod deployment using deploy.yaml file.
4) entered to pod using "kubectl exec -it pv-deploy1-598f45f7d6-qqv9p -- bash" to access bash of pod created.
5) In mount path created a file "/mnt/data-pv2/file1" and exited from pod bash.
6) now deleted the pod using "kubectl delete pod pv-deploy1-598f45f7d6-qqv9p
7) now again new pod gets created after deleting above pod and i accessed the bash of new pod again
8) And i don't see file created inside mount path  "/mnt/data-pv2/file1" < this file got deleted.
9) now i tried again deleting recreated same pod and it will again recreate the pod.
10) after accessing above newly created pod mount path i am able to see the "/mnt/data-pv2/file1" < this file exist now

**What happened**:
 after every alternate deletion of pod it shows the data once and next time of deletion data doesn't exist. 

**What you expected to happen**:
retain policy: data should be available after every pod recreation unless PV is deleted.
delete or recycle policy: data should be clean after every pod recreation unless PV deleted.
**How to reproduce it (as minimally and precisely as possible)**:
1) create a namespace
2) create PV / PVC / and deployment kind pod with local mount path without using any other storage location.
3)Access the pod bash console and  write a file inside the mount path of the pod and exit
4) delete the pod and it will automatically recreate the pod.
5) now again access bash of newly recreated pod and check file exist or not.
 
**Anything else we need to know?**:
attached below .yaml file used for creating PV,PVC,deployment  

1) pv.yaml
``` 
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    volume: pv0003
  name: pv0003
  #resourceVersion: "227035"
  selfLink: /api/v1/persistentvolumes/pv0003
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: myclaim2
    namespace: pv-snap
    #resourceVersion: "227033"
  hostPath:
    path: /mnt/data-pv/pv0003
    type: ""
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
status:
  phase: Bound
``` 
2) pvc.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim2
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi

3) deploy.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pv-deploy1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypv1
  template:
    metadata:
      labels:
        app: mypv1
    spec:
      containers:
      - name: shell
        image: centos:7
        command:
        - "bin/bash"
        - "-c"
        - "sleep 10000"
        volumeMounts:
        - name: mypd1
          mountPath: "/mnt/data-pv2"
          #mountPath: "/tmp/persistent"
      volumes:
      - name: mypd1
        persistentVolumeClaim:
          claimName: myclaim2

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
provider:  aws/minio 
- OS (e.g: `cat /etc/os-release`): Centos7.X
- Kernel (e.g. `uname -a`):  3.10.0-1127.19.1.el7.x86_64
- Install tools: k8s,velero, docker
- Network plugin and version (if this is a network-related bug):
- Others:1 master node with 2 worker nodes in cluster.
![Screenshot (89)](https://user-images.githubusercontent.com/25818699/100219915-9fc58f80-2f3c-11eb-8e01-7730634c5abb.png)
![Screenshot (92)](https://user-images.githubusercontent.com/25818699/100220538-840eb900-2f3d-11eb-8b0e-61fbb7c37c67.png)
![Screenshot (93)](https://user-images.githubusercontent.com/25818699/100220648-aaccef80-2f3d-11eb-87e0-265a86ff9133.png)

Above 3 screenshots you can find out the output of what has happened exactly.

Any suggestion or i missed any steps please let me know the gaps or solution.

**Comment by pacoxu** [comment]
hostPath？ are all pods scheduled on the same node？

**Comment by samdgoyal123** [comment]
yes it is hostPath and only one pod scheduled on the node so far.

**Comment by samdgoyal123** [comment]
Hi all,

Any update on this ?

**Comment by gongwei1027** [comment]
You use hostpath. The first time you create f1 is because pod is scheduled on node1. When the pod is deleted and rebuilt, it is scheduled to node2. At this time, the hostpath on node2 is used, so there is no f1. When you have f1 again The pod is scheduled to node1 again

After testing, it is consistent with my guess
