### ISSUE TITLE
Pod stuck in "ContainerCreating" status in K8 v.14.3

### ISSUE THREAD

**Issue by heartTorres** [kubernetes/kubernetes#96855]
Kubernetes v.14.3
Amazon Web Services

**What happened**:
I have storageclass defined. Pod stuck in "ContainerCreating" as the volume cannot be attached and error "instance not found" error in the logs.

<img width="1421" alt="Screen Shot 2020-11-25 at 4 39 32 PM" src="https://user-images.githubusercontent.com/65100615/100202939-ed41fc80-2f3c-11eb-897b-5c5c07f35e8f.png">

**What you expected to happen**:
Volume should be attached successfully and status of pod should be "Running"

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): kubernetes v1.14.3
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
/sig aws
/sig cloud-provider

similar with #77920 and @slconley meet it recently (https://github.com/kubernetes/kubernetes/issues/77920#issuecomment-668899515)

Some comments in the code: https://github.com/kubernetes/kubernetes/blob/48a0ef6a396f84ec93a8e68d9843c6fe27c4e848/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L2316-L2327
```
	// We want to fetch the hostname via the EC2 metadata service
	// (`GetMetadata("local-hostname")`): But see #11543 - we need to use
	// the EC2 API to get the privateDnsName in case of a private DNS zone
	// e.g. mydomain.io, because the metadata service returns the wrong
	// hostname.  Once we're doing that, we might as well get all our
	// information from the instance returned by the EC2 API - it is a
	// single API call to get all the information, and it means we don't
	// have two code paths.
```

There's some analysis in  https://dzone.com/articles/fixing-kubernetes-failedattachvolume-and-failed-mo#:~:text=The%20Warning%20FailedAttachVolume%20error%20occurs,cannot%20be%20attached%20to%20another.&text=You%20can%20see%20in%20the,attached%20to%20an%20existing%20node. According to is, aws will do something like forcing detach it and schedule it to another ec2 instance later? Are you using esb volumes ?

**Comment by heartTorres** [comment]
> /sig cloud-provider
> 
> similar with #77920 and @slconley meet it recently ([#77920 (comment)](https://github.com/kubernetes/kubernetes/issues/77920#issuecomment-668899515))
> 
> Some comments in the code:
> 
> https://github.com/kubernetes/kubernetes/blob/48a0ef6a396f84ec93a8e68d9843c6fe27c4e848/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L2316-L2327
> 
> ```
> 	// We want to fetch the hostname via the EC2 metadata service
> 	// (`GetMetadata("local-hostname")`): But see #11543 - we need to use
> 	// the EC2 API to get the privateDnsName in case of a private DNS zone
> 	// e.g. mydomain.io, because the metadata service returns the wrong
> 	// hostname.  Once we're doing that, we might as well get all our
> 	// information from the instance returned by the EC2 API - it is a
> 	// single API call to get all the information, and it means we don't
> 	// have two code paths.
> ```
> 
> There's some analysis in https://dzone.com/articles/fixing-kubernetes-failedattachvolume-and-failed-mo#:~:text=The%20Warning%20FailedAttachVolume%20error%20occurs,cannot%20be%20attached%20to%20another.&text=You%20can%20see%20in%20the,attached%20to%20an%20existing%20node. According to is, aws will do something like forcing detach it and schedule it to another ec2 instance later? Are you using esb volumes ?

Hi, yes I am using ebs volumes. Does this mean that this is still bug in K8 1.14 version?
