### ISSUE TITLE
Scheduler: Retire volume in-tree plugins in scheduler nodevolumelimits

### ISSUE THREAD

**Issue by gavinfish** [kubernetes/kubernetes#96852]
**What would you like to be added**:

Currently scheduler uses plugins including `AzureDiskLimits`, `CinderLimits`, `EBSLimits` and `GCEPDLimits` to filter nodes by in-tree volume plugin limitation in non-csi scenarios. Meantime, `NodeVolumeLimits` plugin also takes in-tree volume plugins and csi migration feature into consideration for compatibility.

According to [Kubernetes In-Tree to CSI Volume Migration timeline](https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-feature-csi-migration-beta/#what-is-the-timeline-status), all the in-tree volume plugins considered in scheduler will be remove in kubernetes 1.21. So propose two changes here.

1. Retire the `AzureDiskLimits`, `CinderLimits`, `EBSLimits` and `GCEPDLimits` plugins.

2. Remove `NodeVolumeLimits` plugin compatible logic with in-tree volume plugins. Scheduler `NodeVolumeLimits` plugin used to handle both Node and CSINode to filter nodes according to volume limit for compatibility. And I think CSINode info is enough now to get the limit. It is time to remove legacy logic in NodeVolumeLimits 
plugin.

https://github.com/kubernetes/kubernetes/blob/c678434623be4957d892a9865e5649f887a40c49/pkg/scheduler/framework/plugins/nodevolumelimits/csi.go#L285-L299

**Why is this needed**:

- Remove legacy logic
- Remove dependency on csi util, part of #89930

/sig scheduling
/sig storage

**Comment by damemi** [comment]
@ahg-g, you mentioned before that the volumebinder dependency would block (or rather not help) the changes in https://github.com/kubernetes/kubernetes/pull/90007#issuecomment-612147942. Would this be enough to unstick that?

If so, @gavinfish feel free to work on this :)

**Comment by ahg-g** [comment]
We will still depend on volumebinder, until volumebinder is moved to the new staging repo, we can't cut that dependency.

@cofyc can you please verify that the TODO mentioned in the issue can be removed?

**Comment by cofyc** [comment]
we can stop reading values from Node object now, see the original discussion (https://github.com/kubernetes/kubernetes/pull/80084#discussion_r304171466)

**Comment by gavinfish** [comment]
/retitle Scheduler: Retire volume in-tree plugins in scheduler nodevolumelimits
/assign

@msau42 Is the  Kubernetes In-Tree to CSI Volume Migration timeline still valid today? If so, does it make sense for scheduler to retire the scheduler plugins for in-tree volume plugins in version 1.21 too?

**Comment by msau42** [comment]
CSI migration timeline is slipping. I think 1.23 will be the earliest that we can start considering removing this logic (on a plugin-by-plugin basis).

@kubernetes/sig-storage-feature-requests 
cc @Jiawei0227 to add this to list of things we can remove once csi migration is GA.

**Comment by msau42** [comment]
/reopen
/remove-lifecycle rotten

CSI migration is still in progress.
