### ISSUE TITLE
this test is wierd to set `expected` twice, and the last set is not correct

### ISSUE THREAD

**Issue by titanxxh** [kubernetes/kubernetes#96862]
https://github.com/kubernetes/kubernetes/blob/c1f36fa6f28d3618c03b65799bc3f58007624e5f/staging/src/k8s.io/client-go/tools/cache/index_test.go#L79
```go
	expected := map[string]sets.String{}
	expected["ernie"] = sets.NewString("one", "tre")
	expected["bert"] = sets.NewString("one", "two")
	expected["elmo"] = sets.NewString("tre")
	expected["oscar"] = sets.NewString("two")
	expected["elmo"] = sets.NewString() // let's just make sure we don't get anything back in this case
```
second `expected["elmo"] ` will cancel the first set, as a result, the `!found.HasAll(items...)` is checking empty list which will always be true.
this test should fail.

**Comment by piper41955** [comment]
A set is immutable, and by definition cannot support two of the same key name. We should have to change the data structure for this to pass, no?
