### ISSUE TITLE
Ipvs: NodePort entries for localhost (127.0.0.1, ::1) are created but can't be used

### ISSUE THREAD

**Issue by uablrek** [kubernetes/kubernetes#96879]
**What happened**:

For services with type NodePort (and LoadBalancer) ipvs entries for localhost (ipv4 and ipv6) are created. Here is an example for a service with `ipFamilyPolicy: PreferDualStack` so the same nodeport is used for ipv4 and ipv6;

```
$ ipvsadm -Ln | grep 31201
TCP  192.168.0.2:31201 rr
TCP  192.168.1.2:31201 rr
TCP  11.0.2.1:31201 rr
TCP  127.0.0.1:31201 rr
TCP  [::1]:31201 rr
TCP  [1000::1:c0a8:2]:31201 rr
TCP  [1000::1:c0a8:102]:31201 rr
TCP  [1100::201]:31201 rr
$ curl -s -D - http://192.168.1.2:31201 | grep -F "200 OK"
HTTP/1.1 200 OK
$ curl -s -D - http://127.0.0.1:31201
(hangs)
$ curl -s -D - http://[1000::1:c0a8:102]:31201 | grep -F "200 OK"
HTTP/1.1 200 OK
$ curl -s -D - http://[::1]:31201
(hangs)
```

The localhost entries can't be used and most likely they never will.

**What you expected to happen**:

Since "::1" most likely will never work and 127.0.0.1 will not work without an unlikely Linux kernel update these entries must not be created.

Further, since the use of localhost addresses for nodeports is the only know reason to require `net.ipv4.conf.all.route_localnet=1` (#90259), this requirement shall be removed for proxy-mode=ipvs.

**How to reproduce it (as minimally and precisely as possible)**:

* Start a cluster with proxy-mode=ipvs and some services
* Do; `ipvsadm -Ln | grep 127.0.0.1`

**Anything else we need to know?**:

That ipv6 access to [::1]:nodeport does not work (and most likely never will) is discussed in https://github.com/kubernetes/kubernetes/issues/90236.

For 127.0.0.1 is is a bit more complicated as discussed in https://github.com/kubernetes/kubernetes/issues/67730, with the excellent deep-dive into the kernel by @chendotjs in https://github.com/kubernetes/kubernetes/issues/67730#issuecomment-578859752.

This may seem like a minor issue but clean-up of useless things is always good. I also have (vague) plans to propose improvements for the address handling for proxy-mode=ipvs and the localhost entries becomes an unwanted problem.

If this issue is accepted as a bug I'll be happy to do a PR.

**Environment**:

- Kubernetes version (use `kubectl version`): all supporting proxy-mode=ipvs
- Cloud provider or hardware configuration: any
- OS (e.g: `cat /etc/os-release`): any
- Kernel (e.g. `uname -a`): any
- Install tools: none
- Network plugin and version (if this is a network-related bug): any
- Others:

/kind cleanup
/sig network
/area ipvs

**Comment by pacoxu** [comment]
test in ipv6 + iptables , ::1 is not work for NodePort. 

/assign

**Comment by uablrek** [comment]
/remove-lifecycle stale

<sigh...>

**Comment by uablrek** [comment]
Since it is highly unlikely that the kernel will be updated to allow this for ipv4 and it will never work for ipv6 I would *really* want to remove this from the ipvs proxier.

**Comment by uablrek** [comment]
@aojea @thockin Do you think I can go ahead and disable the setup for localhost node-ports in the ipvs proxier?

Since it have never worked it would not be a user facing change.

Or should we discuss it on the sig/network meeting?

**Comment by aojea** [comment]
I personally think that this was implicitly discussed and confirmed here https://github.com/kubernetes/kubernetes/pull/92938 , it is an implementation detail of IPVS and a known issue that never worked in IPVS, so it will be safe to disable directly without further discussion.
However, I defer to @thockin for a final decision
/assign @thockin

**Comment by uablrek** [comment]
I made a PR. It's just 3 lines :smile:
