### ISSUE TITLE
Is there a plan to add rbd csimigration controller?

### ISSUE THREAD

**Issue by huchengze** [kubernetes/kubernetes#96880]
**What would you like to be added**:

Add rbd csimigration controller in kubernetes.

**Why is this needed**:

Some [in-tree storage plugins](https://github.com/kubernetes/kubernetes/blob/c1f36fa6f28d3618c03b65799bc3f58007624e5f/pkg/volume/csimigration/plugin_manager.go#L80) has already completed csimigration, and looks like there is no plan to add rbd csimigration controller in [kubernetes's blog](https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-feature-csi-migration-beta/#what-is-the-timeline-status).

**Comment by pacoxu** [comment]
dup with issue #91246  which is WIP in PR #95361 ?

**Comment by huchengze** [comment]
@pacoxu Thanks!
