### ISSUE TITLE
Revisit etcd liveness probe

### ISSUE THREAD

**Issue by mborsz** [kubernetes/kubernetes#96886]
Currently, etcd livenessProbe is defined here: 
https://github.com/kubernetes/kubernetes/blob/c1f36fa6f28d3618c03b65799bc3f58007624e5f/cluster/gce/manifests/etcd.manifest#L66-L73
This means that it proves /health endpoint 3 times (default failureThreshold value) and if all of them fails, it restarts etcd server.

/health endpoint returns "unhealthy" if one of the conditions is met ([src](https://github.com/etcd-io/etcd/blob/v3.4.14/etcdserver/api/etcdhttp/metrics.go#L95)):
* there is an active Alarm (there are two kinds of alarm: NOSPACE and CORRUPT)
* there is no raft leader
* the latency of a QGET request doesn't exceed 1s

The problem is that in most of those cases, etcd's restart **isn't** a right behavior:
* if there is NOSPACE alarm, the restart will not free that space
* if there is no raft leader, it means that it cannot talk to other etcd members, so restart will not fix them
* if the request latency > 1s, the etcd cluster is overloaded which is bad, but after restart we will get similar amount of requests (if not more), so restart isn't a right action

e.g. in https://github.com/kubernetes/kubernetes/issues/96038 we see that event-etcd gets restarted by kubelet when it's overloaded. If we do not restart etcd at that point, we will likely simply finish work to be done and heal ourselves.

I think we should change livenessProbe to detect cases where restart will actually help.

/cc @wojtek-t @jpbetz @mm4tt @ptabor

**Comment by wojtek-t** [comment]
> if there is no raft leader, it means that it cannot talk to other etcd members, so restart will not fix them

I think that's not necessary true, that may potentially help sometimes. But I agree that's probably pretty rare.

/sig api-machinery

**Comment by mm4tt** [comment]
Do we have an analysis of why the 3 healthchecks in row failed in https://github.com/kubernetes/kubernetes/issues/96038?
Was it timeout, timeout, timeout or something else? 

> if the request latency > 1s, the etcd cluster is overloaded which is bad, but after restart we will get similar amount of requests.

Do you say that if etcd is overloaded then restarting it will help? Wouldn't it be even more overloaded and run into restart-loop because it will never become /healthy in time again?

**Comment by mborsz** [comment]
> Do we have an analysis of why the 3 healthchecks in row failed in #96038?
> Was it timeout, timeout, timeout or something else?
> 
Given that the cluster in our tests is zonal, it must be 3x timeout (we had no alarm, as the event-etcd would crashloop until the end of the test, there is a single raft member so it must be a leader).

> > if the request latency > 1s, the etcd cluster is overloaded which is bad, but after restart we will get similar amount of requests.
> 
> Do you say that if etcd is overloaded then restarting it will help? Wouldn't it be even more overloaded and run into restart-loop because it will never become /healthy in time again?

Sorry, typo. I tried to say that in none of those cases restart will help (including >1s latency), but in fact I wrote something else. I changed initial post.

**Comment by ptabor** [comment]
1. We should fix etcd such that it does not declares as unhealthy as a result of overload (while its still making a progress).
  Ideally the not-healthchecking traffic should be throttled / load-shed, such that healthcheck stays responsive. 

2. Till this is implemented, I would consider giving higher timeout (e.g. 30sec), such that HC request have higher chance to reach beginning of the processing queue and get responded. 

3. There is a usual disjoint between 2 purpuses of healthchecking: 
  a) autohealing -> by restart    -> where we need to be very conservative about timeouts, as cost is high.
  b) measuring SLO & alerting     -> where we want to measure customer's happiness, and we cannot consider request waiting for 15s+ seconds as healthy/happy state. The lower tolerance more represents customers needs. 

In practical application  we should optimize etcd healthcheck for a), while b) should be based on prometheous metrics. 

@GFilipek

**Comment by wojtek-t** [comment]
This is basically the difference between "livez" and "readyz".
"livez" is whether the app is running (for autohealing)
"readyz" is whether it's useful from customer point of view (e.g. for SLO)

In the ideal world, those should be two separate handlers.

**Comment by mm4tt** [comment]
In addition to doubling the timeout we can also consider halving the probing period (from default 10s to 5s) and doubling failure thresholds (from 3 failed probes in row to 6). It would decrease the probability of etcd being restarted in case of temporarily overloaded master.

**Comment by mborsz** [comment]
> 1. We should fix etcd such that it does not declares as unhealthy as a result of overload (while its still making a progress).
>    Ideally the not-healthchecking traffic should be throttled / load-shed, such that healthcheck stays responsive.
> 2. Till this is implemented, I would consider giving higher timeout (e.g. 30sec), such that HC request have higher chance to reach beginning of the processing queue and get responded.

There is no option to keep using "/health" endpoint and changing timeout to something higher, as this is hardcoded in etcd:



> 3. There is a usual disjoint between 2 purpuses of healthchecking:
>    a) autohealing -> by restart    -> where we need to be very conservative about timeouts, as cost is high.
>    b) measuring SLO & alerting     -> where we want to measure customer's happiness, and we cannot consider request waiting for 15s+ seconds as healthy/happy state. The lower tolerance more represents customers needs.
> 
> In practical application we should optimize etcd healthcheck for a), while b) should be based on prometheous metrics.
>
