### ISSUE TITLE
cAdvisor in containerized Kubelet can't find Docker to move it into a container

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#9689]
Testing containerized Kubelet and seeing:

```
W0611 21:27:27.828300       1 container_manager_linux.go:68] [ContainerManager] Failed to ensure Docker is in a container: failed to find pid of Docker container: exit status 1
```

This is normal because Docker isn't in the pid namespace of the kubelet - but either cAdvisor needs to use the same pid namespace escape tricks that the kubelet uses for mounts, or we need to run the kubelet outside of a pid namespace, which makes other things regarding the container much harder.

Started with https://github.com/google/cadvisor/issues/770 then @rjnagal explained this was in container-manager.

From Rohit

---

This bit of code is in kubelet. It creates a new cgroup and tries to move docker processes there.

I think the problem is that kubelet is execing pidof docker to find docker processes. In cadvisor, we mount system root at /rootfs and use that to proxy process listing.

kubelet can do the same with chroot /rootfs pidof docker

Three lines of change, but needs to go in kubelet :)

Are the namespaced kubelet changes getting in? I can make the kubelet change if someone is willing to merge it in.

---

Answers no, this was us testing in OpenShift in preparation for enabling containerized workflows.  Not a huge deal on our end, this is mostly for development and kick the tires workflows.

**Comment by dchen1107** [comment]
cc/ @vmarmol @rjnagal

**Comment by rjnagal** [comment]
Wasn't sure if anyone wanted it right now? @dchen1107 Is anyone actively working on putting kubelet intoa container. I can make this change, but there might be other places that need updating.

**Comment by dalanlan** [comment]
I C. Thx a lot. 
Noted that `-containerized` flag of kubelet is designed for that purpose, not fully prepared though, i guess.
