### ISSUE TITLE
kubelet's healthz return OK even when api is unreachable

### ISSUE THREAD

**Issue by Frankkkkk** [kubernetes/kubernetes#96891]
**What happened**:
When the kubelet cannot reach the apiserver, the healthz route continues returning `ok`

**What you expected to happen**:
healthz route should not return OK

**How to reproduce it (as minimally and precisely as possible)**:
```
# Verify that health is good
$ curl http://[::1]:10248/healthz
ok

# blackhole the apiserver IP (e.g. there is some network outage)
$ ip r add blackhole 2001:1600:1337::1

# verify that we can't reach the IP:
$ ping6 -c1 2001:1600:1337::1
ping6: connect: Invalid argument

# Check health again after some time (> 1h):
$ curl http://[::1]:10248/healthz
ok
# Health should not be okay. `kubectl get nodes` marks the node as NotReady as expected
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.3
- Cloud provider or hardware configuration: bare metal
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.1 LTS
- Kernel (e.g. `uname -a`): 5.4.0-51
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): cilium

Cheers :-)

**Comment by Cweiping** [comment]
As you said, this case is in line with expectations. Kubelet can tolerate short-term inability to link to `APIServer`, and a heartbeat check will confirm the connectivity of `APIServer`.

**Comment by Frankkkkk** [comment]
Hi @Cweiping , maybe I've misunderstood your reply, but in my case the healthcheck URL still returns "ok" even after 2 hours of "outage".

Is there a better way to detect non-connectivity (or node NotReadyness ) from within a node ?

**Comment by Cweiping** [comment]
Maybe you should perceive node status from `APIServer`.What scene needs to be asked directly by `kubelet`?

**Comment by Frankkkkk** [comment]
My use case if of a program that runs on the nodes themselves (kinda metallb-like). It talks BGP and announces IPs if the node is ready.
It this case, I assume kubelet ok = node ready.
However, if for some reason the node is not able to reach the apiserver, then the IPs should not be announced.

That's why I thought it was ok to ask the status to the kubelet.

Cheers

**Comment by wzshiming** [comment]
I can’t reproduce this bug on 1.21, after the blackhole, this node becomes unready with `kubectl get node`.

is bug doesn't seem to have enough details to reproduce or further investigate. You must include your cluster version, the container runtime, kubelet logs, and any relevant Kubernetes manifests along with clear steps to reproduce so we can help with your issue.

Please re-open this bug once you have provided more information.

/triage needs-information
/close
