### ISSUE TITLE
Make health check adding methods in GenericAPIServer public 

### ISSUE THREAD

**Issue by serathius** [kubernetes/kubernetes#96896]
**What would you like to be added**:
When using GenericAPIServer you can only add new checks via `AddHealthChecks` function which adds them to all `healthz`, `readyz`, and `livez` endpoints. All other methods like `addReadyzChecks` are private. [Code](https://github.com/kubernetes/kubernetes/blob/7acb066dbcd7d05106609711fc4ec110fec1d1a4/staging/src/k8s.io/apiserver/pkg/server/healthz.go)

I would like to request those methods to be made public:
* `addReadyzChecks`
* `addLivezChecks`

**Why is this needed**:

Developers of apiservers should be able to define their readiness probes add them to specific endpoint of their choosing. For example in case of Metrics Server we defined probes:
* Readiness - Metrics cache is full. As MS serves data only from cache, traffic will be only sent after cache is full. 
* Liveness - Metric scraping loop is not deadlocked.

It doesn't make sense to have those probes added to both endpoints. Not ready metric cache should not cause MS being killed via liveness probe. Delayed scrape should not cause traffic not being served from cache due failing readiness probe.

/assign @logicalhan

**Comment by sttts** [comment]
I can see this. PR welcome.
