### ISSUE TITLE
 @reboot in Kubernetes CronJob 

### ISSUE THREAD

**Issue by shekhar-rajak** [kubernetes/kubernetes#96912]
Hi,

We have a scenerio, where job needs to be run when pod restarts/deleted and scheduled again. Once it start running the instance, we have to make sure that job runs, which is good usecase of cronjob @reboot 

Can anyone help me how to use `@reboot ` in Kubernetes CronJob ? I do not see any example related to it : https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/ here.

**Comment by troy0820** [comment]
/sig apps
/sig scheduling

@ shekhar-rajak If your job is dependent on restart/deleted pods, maybe the resource you need is something that can watch the pod.  Maybe an init container that can do the work you need for the pod when it restarts. Maybe a controller that will watch the pod and do something when it gets deleted. CronJobs are triggered on a schedule and having it respond to a trigger of pod behavior sounds like another resource.

**Comment by shekhar-rajak** [comment]
Thanks @troy0820 , just curious to understand CronJob doc: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

says "One CronJob object is like one line of a crontab (cron table) file. It runs a job periodically on a given schedule, written in Cron format." and the wiki page it redirect is https://en.wikipedia.org/wiki/Cron where 

`@reboot | Run at startup` is also mentioned. So should we make a note in the doc. that the reboot is not supported in CronJob Kubernetes object ? and can tell the alternate options for doing the same ( run at startup) ?

**Comment by lingsamuel** [comment]
Crontab `@` syntax is nonstandard. On the wiki page it appears in
> **Nonstandard** predefined scheduling definitions
section.

**Comment by shekhar-rajak** [comment]
Thanks @lingsamuel for clarification.

**Comment by shekhar-rajak** [comment]
Is it good idea to have some common Non Standard scheduling expressions like monthly, daily, yearly, reboot something  ?

**Comment by lingsamuel** [comment]
Init containers can do the work you want (run job when pod restart), I don't think its a cronjob matter.

`@reboot` means a system-wide reboot. But I can't find any use case because things in k8s is declarative...
Others like `@daily` we could just use its equivalent (`0 0 * * *`).

**Comment by pacoxu** [comment]
it is similar to a daemon job， which would run on every node，and will be triggered after os/docker starts up.  
If the RestartPolicy of the job container is set to restart：Always， it would work？ 

I use compose to do similar thing before， and run an agent pod on a server which will start automaticly on reboot.
