### ISSUE TITLE
Inconsistent casing of AGE column in describeNodeResource() in kubectl/describe.go

### ISSUE THREAD

**Issue by bl-ue** [kubernetes/kubernetes#96919]
At line 3775 in `describe.go` (`kubectl describe node`), the last column is "AGE", all uppercase, while the other columns are sentence case.  Is this intentional or an oversight?

https://github.com/kubernetes/kubernetes/blob/2c58deffa87bf464293fe80c80b7fec31d0aae7c/staging/src/k8s.io/kubectl/pkg/describe/describe.go#L3775

**Comment by bl-ue** [comment]
If this is a mistake I will open a PR to fix it.

**Comment by lovejoy** [comment]
@bl-ue  yes ,should be Age
