### ISSUE TITLE
kubernetes ingress  Port 80 not open

### ISSUE THREAD

**Issue by kaikai136** [kubernetes/kubernetes#96927]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
spec:
  replicas: 2
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
      imagePullSecrets:
        - name: kaikai.txt-regcred
---
apiVersion: v1
kind: Service
metadata:
  name: svc-1
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30902
    protocol: TCP
  selector:
    name: nginx
  type: NotePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress1
spec:
  rules:
  - host: www1.kaikai.txt.com
    http:
      paths:
      - path: /
        backend:
          serviceName: svc-1
          servicePort: 80
--------------------------------------------------------

Port mapping should be 80

[root@master ~]# ss -ntl
State      Recv-Q Send-Q                             Local Address:Port                                            Peer Address:Port              
LISTEN     0      128                                            *:22                                                         *:*                  
LISTEN     0      4096                                   127.0.0.1:10248                                                      *:*                  
LISTEN     0      4096                                   127.0.0.1:10249                                                      *:*                  
LISTEN     0      4096                               192.168.99.34:2379                                                       *:*                  
LISTEN     0      4096                                   127.0.0.1:2379                                                       *:*                  
LISTEN     0      4096                               192.168.99.34:2380                                                       *:*                  
LISTEN     0      4096                                   127.0.0.1:2381                                                       *:*                  
LISTEN     0      4096                                   127.0.0.1:10257                                                      *:*                  
LISTEN     0      4096                                   127.0.0.1:43665                                                      *:*                  
LISTEN     0      4096                                   127.0.0.1:10259                                                      *:*                  
LISTEN     0      128                                         [::]:22                                                      [::]:*                  
LISTEN     0      4096                                        [::]:30905                                                   [::]:*                  
LISTEN     0      4096                                        [::]:10250                                                   [::]:*                  
LISTEN     0      4096                                        [::]:10251                                                   [::]:*                  
LISTEN     0      4096                                        [::]:6443                                                    [::]:*                  
LISTEN     0      4096                                        [::]:10252                                                   [::]:*                  
LISTEN     0      4096                                        [::]:10256                                                   [::]:*        

Domain name not accessible

**Comment by neolit123** [comment]
hi, please try the support channels first:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

thanks
/close
