### ISSUE TITLE
How to install this  weave net add on behind proxy

### ISSUE THREAD

**Issue by neeson-lee** [kubernetes/kubernetes#96930]
Im beginner this kubenetes. and I want to learn this
I use my company's proxy 

when I try to this

kubectl apply -f "https://cloud.weave.works/k8s/scope.yaml?k8s-version=$(kubectl version | base64 | tr -d '\n')"

The connection to the server cloud.weave.works was refused - did you specify the right host or port?

I took this result how to solve this problem??

i use centos 18.4 docker 19.03.13

**Comment by neolit123** [comment]
hi, please try the support channels first:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

thanks
/close
