### ISSUE TITLE
instead of "-f", we should use "--force" to delete the git working tree

### ISSUE THREAD

**Issue by tanjing2020** [kubernetes/kubernetes#96943]
https://github.com/kubernetes/kubernetes/blob/e3de62298a730415c5d2ab72607ef6adadd6304d/hack/verify-generated-files-remake.sh#L37

### **git version**
git version 2.17.1 linux

### **phenomenon:**
Verifying verify-generated-files-remake.sh

+++ Running case: verify.generated-files-remake 
+++ working dir: /usr1/k8s/src/k8s.io/kubernetes
+++ command: bash "hack/make-rules/../../hack/verify-generated-files-remake.sh"
Preparing /tmp/verify-generated-files.DSZIZr/go/src/k8s.io/kubernetes (identifier kubernetes)
Checking out files:  69% (15805/22744)   
Checking out files:  70% (15921/22744)   
Checking out files:  71% (16149/22744)   
Checking out files:  72% (16376/22744)   
Checking out files:  73% (16604/22744)   
Checking out files:  74% (16831/22744)   
Checking out files:  75% (17058/22744)   
Checking out files:  76% (17286/22744)   
Checking out files:  77% (17513/22744)   
Checking out files:  78% (17741/22744)   
Checking out files:  79% (17968/22744)   
Checking out files:  80% (18196/22744)   
Checking out files:  81% (18423/22744)   
Checking out files:  82% (18651/22744)   
Checking out files:  83% (18878/22744)   
Checking out files:  84% (19105/22744)   
Checking out files:  85% (19333/22744)   
Checking out files:  86% (19560/22744)   
Checking out files:  87% (19788/22744)   
Checking out files:  88% (20015/22744)   
Checking out files:  89% (20243/22744)   
Checking out files:  90% (20470/22744)   
Checking out files:  91% (20698/22744)   
Checking out files:  92% (20925/22744)   
Checking out files:  93% (21152/22744)   
Checking out files:  94% (21380/22744)   
Checking out files:  95% (21607/22744)   
Checking out files:  96% (21835/22744)   
Checking out files:  97% (22062/22744)   
Checking out files:  98% (22290/22744)   
Checking out files:  99% (22517/22744)   
Checking out files: 100% (22744/22744)   
Checking out files: 100% (22744/22744), done.
HEAD is now at d20e3246bad Merge pull request #96574 from hasheddan/cleanup-resource-tests
error: unknown switch `f'
usage: git worktree add [<options>] <path> [<commit-ish>]
   or: git worktree list [<options>]
   or: git worktree lock [<options>] <path>
   or: git worktree move <worktree> <new-path>
   or: git worktree prune [<options>]
   or: git worktree remove [<options>] <worktree>
   or: git worktree unlock <path>

    --force               force removing even if the worktree is dirty

+++ exit code: 0

**Comment by neolit123** [comment]
i think your version of git is just outdated; what is it?

`-f` is valid as noted here:
https://git-scm.com/docs/git-worktree#_options

**Comment by BenTheElder** [comment]
git 2.17 is from April 2018, 2.29.2 is current.
we generally target relatively current tools for the development scripts. using --force here seems harmless but I'm not sure we want to target multi-year old git generally.

**Comment by tanjing2020** [comment]
yea, after updating the git version, there is no error using "-f"
