### ISSUE TITLE
In cetos 7.6 arm V8 64 environment, kubemark always crashes due to null pointer exception

### ISSUE THREAD

**Issue by li-yi-cloud** [kubernetes/kubernetes#96949]
**kubemark always crashes due to null pointer exception**:

**this is hollow-kubelet's log**:
I1130 06:27:21.071145       7 fake_cpu_manager.go:46] [fake cpumanager] RemoveContainer (container id: 1c2c6c98a6132aeb)
I1130 06:27:21.071165       7 kuberuntime_container.go:586] Killing container "docker://1c2c6c98a6132aeb" with 30 second grace period
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x17ca090]

goroutine 1092 [running]:
k8s.io/kubernetes/pkg/kubelet/dockershim.(*NativeExecHandler).ExecInContainer(0x66b1638, 0x43929c0, 0x40001f8600, 0x4000d6bb90, 0x4000de52c0, 0x2, 0x2, 0x0, 0x0, 0x4288b40, ...)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/dockershim/exec.go:118 +0x3c8
k8s.io/kubernetes/pkg/kubelet/dockershim.(*streamingRuntime).exec(0x400079c2a0, 0x4000d730c0, 0x10, 0x4000de52c0, 0x2, 0x2, 0x0, 0x0, 0x4288b40, 0x4000e704f0, ...)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_streaming.go:57 +0xf4
k8s.io/kubernetes/pkg/kubelet/dockershim.(*dockerService).ExecSync(0x40006e8210, 0x42f4880, 0x40012d7620, 0x4000d749c0, 0x40006e8210, 0x10e3024, 0x37a7480)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_streaming.go:81 +0x1e4
k8s.io/kubernetes/vendor/k8s.io/cri-api/pkg/apis/runtime/v1alpha2._RuntimeService_ExecSync_Handler(0x3b46720, 0x40006e8210, 0x42f4880, 0x40012d7620, 0x4000f30a80, 0x0, 0x42f4880, 0x40012d7620, 0x4000a5d5c0, 0x36)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.pb.go:7843 +0x1c0
k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0x40007bac60, 0x4351380, 0x400082d200, 0x40007fc000, 0x4000675a40, 0x65a0150, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/server.go:995 +0x384
k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).handleStream(0x40007bac60, 0x4351380, 0x400082d200, 0x40007fc000, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/server.go:1275 +0xb0c
k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0x400062f530, 0x40007bac60, 0x4351380, 0x400082d200, 0x40007fc000)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/server.go:710 +0x94
created by k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/server.go:708 +0x8c

**How to reproduce it (as minimally and precisely as possible)**:
Based on the kubernetes release-1.16 branch, I built the kubelet image in centos7.6 arm V8 64 environment.

The dockerfile content is:
```
FROM debian:9
COPY kubemark /kubemark
```

This is the document I used to build the image：https://github.com/kubernetes/community/blob/master/contributors/devel/sig-scalability/kubemark-setup-guide.md

go:
1.13.9
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.9
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):centos7.6
- Kernel (e.g. `uname -a`):4.18.0-80.7.2.el7.aarch64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by chenyw1990** [comment]
this bug has fix in commit d46daf891cc57c3ca8128d467a834277df1cbd48

**Comment by neolit123** [comment]
> Kubernetes version (use kubectl version): 1.16.9

> this bug has fix in commit d46daf8

we cannot backport it to 1.16 as it's out of support.
you may have to patch your 1.16 version and build or upgrade to the version that has the fix (1.17+)

/close
