### ISSUE TITLE
Custom logging message for fake pod GetLogs in go-client

### ISSUE THREAD

**Issue by zbrookle** [kubernetes/kubernetes#96957]
**What would you like to be added**:

I would like a way to have a custom string be retrieved from the fake pod GetLogs method.

**Why is this needed**:

This is needed because currently the fake GetLogs method always results in a log message "fake logs", and it would be better for testing if a log message set by the user could be retrieved instead.

(This would probably involve adding a portion to the fake container where the custom logs can be placed)

**Comment by AdamSLevy** [comment]
This would be a useful feature in my unit testing.

/remove-lifecycle rotten

**Comment by cognifloyd** [comment]
Can we reopen this? It would be very very helpful to have this feature.
