### ISSUE TITLE
Broken symlink /etc/mtab --> /proc/mounts in kubernetes 1.19.3

### ISSUE THREAD

**Issue by rajsshah86** [kubernetes/kubernetes#96961]
**What happened**:
After mounting the volumes ( be it a NFS or any persistence volume ) , you cannot list the mount points using df -h . This is because the /etc/mtab which used to be symlink of /proc/mounts is now just a regular file with no entries of the volume.

This is working on older version like 1.17.11 . But on higher version 1.19.3 it is not working.

**What you expected to happen**:
/etc/mtab must be symlink to /proc/mounts file.

**How to reproduce it (as minimally and precisely as possible)**:
on kubernets 1.19.3 , create a deployment and mount any volume . Then log on to pod and execute df -h . You should see the filesystem that you mounted . 
Now check /etc/mtab will be a regular file . It should be symlink to /proc/mounts.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-16T20:43:08Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}`

- Cloud provider or hardware configuration: AKS 
- OS (e.g: `cat /etc/os-release`):
`Red Hat Enterprise Linux Server release 6.10 (Santiago)`
- Kernel (e.g. `uname -a`): `Linux xxx-xxx-ss-1 5.4.0-1031-azure #32~18.04.1-Ubuntu SMP Tue Oct 6 10:03:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by msau42** [comment]
I am not aware of Kubernetes setting up/modifying these OS files. At first glance I suspect this is a distro issue rather than a Kubernetes issue.
