### ISSUE TITLE
Egress nodes contain egress IPs within the Kubelet CSR

### ISSUE THREAD

**Issue by rphillips** [kubernetes/kubernetes#96981]
**What happened**:
When an egress IP is assigned to the node the Kubelet will use the egress IP within the Node's CSR request. Since Egress IPs are most often public, the egress IP being in the Kubelet's CSR should not be there. Machine Approver Controllers must allow for additional IPs within the CSRs.

**What you expected to happen**:
The CSR to be requested by the Kubelet and not contain the egress IPs.

**How to reproduce it (as minimally and precisely as possible)**:
* Add an egress ip to a Node
* force or wait for the kubelet to renew the Kubelet serving certificate
* note that the CSR contains the egress IP

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.17 and later

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
RHCOS
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig node

**Comment by michaelgugino** [comment]
Egress IP's aren't the only IPs that cause problems.  Anything that adds an IP to an instance for whatever reason will show up in the CSR, and that is undesireable.  Ideally, just the hostname shows up.

**Comment by danwinship** [comment]
> Anything that adds an IP to an instance for whatever reason will show up in the CSR, and that is undesireable.

Specifically, with `--cloud-provider={aws/azure/gce/openstack}`, if you add a second IP or second network interface to the node via the cloud APIs then those IPs will show up in `node.Status.Addresses`, and from there the CSR, even though you may not have intended those IPs to be used for reaching kubelet. With `--cloud-provider=vsphere`, if you even just add an extra IP to the node with `ip addr add` then it gets reflected in `node.Status.Addresses` and the CSR. (With no cloud provider/"bare metal", only the primary IP (or 2 primary IPs for dual-stack) ever shows up in `node.Status.Addresses` and the CSR.)

AFAICT none of the clouds let you attach much metadata to secondary IPs, so there's no way we could require the admin to indicate in the cloud API somehow whether an IP was intended for kubelet use or not.

**Comment by ehashman** [comment]
/remove-kind bug
/kind feature

I think the best way to implement this would be to add a configuration option to the kubelet that limits what information is included in CSRs (e.g. node hostname/FQDN only, specific IPs).
