### ISSUE TITLE
Container, name and image labels are missing in CAdvisor metrics.

### ISSUE THREAD

**Issue by anoop2503** [kubernetes/kubernetes#96980]
**What happened**:

**Container**, **name** and **image** labels are missing in CAdvisor metrics.
Sample metrics: 
```
container_cpu_usage_seconds_total, 
container_memory_usage_bytes
```

**What you expected to happen**:

**Container**, **name** and **image** labels should be present in the CAdvisor metrics.

**How to reproduce it (as minimally and precisely as possible)**:
Verify below sample metrics to check the label values.
```
container_cpu_usage_seconds_total,
container_memory_usage_bytes
```

**Environment**:
- Kubernetes version (use `kubectl version`):  1.19 and above

**Comment by chenyw1990** [comment]
I think the bug is fixed in PR https://github.com/kubernetes/kubernetes/pull/96849
can you merge the patch to your code, and test again.

**Comment by pacoxu** [comment]
can reproduce in 1.20.1
