### ISSUE TITLE
Add `exec` equivalent to kubectl.kubernetes.io/default-logs-container

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#96986]
**What would you like to be added**:

A way to specify the default container for `kubectl exec`, mirroring `kubectl.kubernetes.io/default-logs-container`. Alternatively, a way to generic describe the default container for anything that happens to need a "default", which could also be used by external tooling.

**Why is this needed**:

Mainly for the same reasons `kubectl.kubernetes.io/default-logs-container` is useful. For our use case, we transparently inject a sidecar container. This means all calls to `kubectl logs` without `-c` fail now, and `kubectl exec` displays a warning (`Defaulting container name to xyz`).

However, it gets worse because aside from a warning, this couples the default exec container to the container ordering. The container ordering also happens to have an impact on container startup ordering. We have started offering an option to inject our sidecar as the first container (previously, it was the last one), which has resulted in users running `kubectl exec` and getting the "wrong" container.

/sig cli

**Comment by pacoxu** [comment]
Can it be reproduced with a pod yaml ?

**Comment by howardjohn** [comment]
@pacoxu I am not sure what you are asking to be reproduced? There is no bug here, AFAIK, I am requesting a new feature to specify the default container (for exec, at least, maybe a more general one).

**Comment by pacoxu** [comment]
sorry for misunderstanding. 

If sidecar container can be identified, the default container can be found. 

Or should we add an admission controller to add default-container annotation during pod creation?

**Comment by howardjohn** [comment]
We are already using the default-log-conrainer annotation, we automatically inject it in our mutating webhook. However, there is no way to set a default for `exec`

**Comment by pacoxu** [comment]
#95293 is asking for a way to set default container.(some discussions in #61333 on adding `default-container` field.)
In https://github.com/kubernetes/kubernetes/issues/95293#issuecomment-709202321 .

I may open a pr to work on this as #87809(PR for `kubectl.kubernetes.io/default-logs-container`) . However, it may be effected by the decision of #95293

**Comment by pacoxu** [comment]
/reopen 
I will close it after implementation in .#97099
