### ISSUE TITLE
IPAM range allocator hotlooping on non-existent node

### ISSUE THREAD

**Issue by sjenning** [kubernetes/kubernetes#96992]
**What happened**:
KCM hotloop on
```
range_allocator.go:338] Failed while getting node node1 for updating Node.Spec.PodCIDRs: node "node1" not found
```
Looking in the code it is obvious that this can happen as the error case writes into the channel the select is reading
https://github.com/kubernetes/kubernetes/blob/61dc69ac2cf936ccafb51e9d946097b62b4ead07/pkg/controller/nodeipam/ipam/range_allocator.go#L188-L200

**What you expected to happen**:
range allocator should detect when the Node retrieval fails because the Node doesn't exist and not requeue.  Also requeue should be rate limited.

**How to reproduce it (as minimally and precisely as possible)**:
Seems to be a timing window.  The node has to be created and deleted quickly before the range allocator can process it.

fyi @deads2k @thockin

**Comment by deads2k** [comment]
> **How to reproduce it (as minimally and precisely as possible)**:
> Seems to be a timing window. The node has to be created and deleted quickly before the range allocator can process it.
> 
> fyi @deads2k @thockin

could it simply be updated for the standard error stanza of `AddRateLimited`?

**Comment by sjenning** [comment]
Yes, I think we need to do that transient failures, but also retire the work item when the node is not found i.e. a case that will never succeed.

**Comment by deads2k** [comment]
> Yes, I think we need to do that transient failures, but also retire the work item when the node is not found i.e. a case that will never succeed.

the default backoff will backoff to about 15 minutes.  I think you could change the hotloop without changing the eventual consistency as a first, less controversial step

**Comment by prashanth26** [comment]
Is there a plan to fix this issue via https://github.com/kubernetes/kubernetes/pull/97021? As we are running into this issue on our cluster.
