### ISSUE TITLE
Enforce CPU throttling at pod level

### ISSUE THREAD

**Issue by matthyx** [kubernetes/kubernetes#97007]
**What would you like to be added**:
A mechanism that enforces coherent throttling between an application container and its sidecars.

**Why is this needed**:
As seen in the talk [10 More Weird Ways to Blow Up Your Kubernetes](https://kccncna20.sched.com/event/ek9r/10-more-weird-ways-to-blow-up-your-kubernetes-jian-cheung-joseph-kim-airbnb) engineers at Airbnb have seen their application container being throttled while the Envoy sidecar was still accepting traffic.

**Comment by matthyx** [comment]
cc @SergeyKanzhelev

**Comment by SergeyKanzhelev** [comment]
Do you suggest to implement per-pod limits?

[Documentation today](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-requests-and-limits-of-pod-and-container:~:text=Although%20requests%20and%20limits%20can%20only,for%20each%20Container%20in%20the%20Pod.) is:

> Although requests and limits can only be specified on individual Containers, it is convenient to talk about Pod resource requests and limits. A Pod resource request/limit for a particular resource type is the sum of the resource requests/limits of that type for each Container in the Pod.

**Comment by matthyx** [comment]
I don't suggest much... as this one is a tricky problem to solve.

If we implement a pod limit, the expected behavior would be to throttle all containers in the pod and then we start getting the same kind of noisy neighbor issue (inside the pod) as the one we had on node level before quotas.

I think the only way to handle that would be in the context of sidecar containers and put an option where we enforce synchronized throttling, where main (application) container throttling also freezes its sidecars.

**Comment by SergeyKanzhelev** [comment]
BTW, found this: https://github.com/kubernetes/enhancements/pull/1592 for the context

**Comment by n4j** [comment]
/triage accepted
KEP https://github.com/kubernetes/enhancements/pull/1592

**Comment by n4j** [comment]
/assign
Since I am pursuing https://github.com/kubernetes/enhancements/pull/1592, I am assigning to myself

**Comment by SergeyKanzhelev** [comment]
I suggest we track this as a KEP: https://github.com/kubernetes/kubernetes/issues/97007 not as an issue on k/k

/close
