### ISSUE TITLE
[Flaky Test][sig-scheduling] SchedulerPreemption [Serial] validates lower priority pod preemption by critical pod [Conformance] 

### ISSUE THREAD

**Issue by ScrapCodes** [kubernetes/kubernetes#97039]
**Which jobs are flaking**:
conformance-ga-only
**Which test(s) are flaking**:
[sig-scheduling] SchedulerPreemption [Serial] validates lower priority pod preemption by critical pod [Conformance] 
**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#conformance-ga-only
**Reason for failure**:
```
test/e2e/framework/framework.go:629
Nov 29 06:30:05.181: Unexpected error:
    <*errors.errorString | 0xc0001f81f0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
test/e2e/scheduling/predicates.go:932
```

**Anything else we need to know**:
- links to go.k8s.io/triage appreciated
   * https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=SchedulerPreemption%20.*%20validates%20lower%20priority%20pod%20preemption%20by%20critical%20pod

- links to specific failures in spyglass appreciated
  
 * https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-conformance-kind-ga-only/1332912971508092928

/sig scheduling
@kubernetes/ci-signal

**Comment by oomichi** [comment]
@ScrapCodes Thanks for reporting this.
I checked the conformance test code and the specified timeout doesn't seem good by comparing the other callers of e2epod.WaitTimeoutForPodRunningInNamespace().
I submitted the above PR for making the timeout longer like the other callers.
Happy if you take a look at that.

**Comment by Huang-Wei** [comment]
This should have been greatly mitigated by #96990. Feel free to reopen it.

/close
