### ISSUE TITLE
Could not resolve host: kubernetes.default.svc.cluster.local; Unknown error

### ISSUE THREAD

**Issue by yangjinlogic** [kubernetes/kubernetes#97043]
The version is 1.18
I use " kubectl exec -i -t dnsutils -n kube-system -- nslookup kubernetes.default" can get 
Server:		10.96.0.10
Address:	10.96.0.10#53

Name:	base-page.default.svc.cluster.local
Address: 10.96.245.157

but I  "curl kubernetes.default.svc.cluster.local"
 show this 

 Could not resolve host: kubernetes.default.svc.cluster.local; Unknown error

can you help me ? please

**Comment by neolit123** [comment]
please try the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

if you find a confirmed bug, open a new issue.

thanks
/kind support
/close
