### ISSUE TITLE
CRI: More flexibility for CRI shims

### ISSUE THREAD

**Issue by dionysius** [kubernetes/kubernetes#97050]
[Since kubernetes drops support to "direct" docker in 1.20](https://twitter.com/Dixie3Flatline/status/1334188913724850177), how much "dockerness" will be removed with it? Can we please talk about giving CRI more responsibility and remove various pre-decisions in the kubernetes code?

**What would you like to be added**:
- Remove hard-coded ignore of hostname when `hostNetwork=true`: https://github.com/kubernetes/kubernetes/issues/67019, the runtime can decide what combinations can work and not
- Forward the image name to the CRI **as is** and don't manipulate the string to "conform some specific format": https://github.com/kubernetes/kubernetes/blob/5b8c3b90f3c74ba79f4bfa5be560d011694a7da0/pkg/util/parsers/parsers.go#L31. We could discuss validating the image name string using the CRI or similiar.
- Remove docker specificness of CRI AuthConfig: https://github.com/kubernetes/cri-api/blob/3094f92ca2a23915931d9345285a6721be06cf62/pkg/apis/runtime/v1/api.pb.go#L5412. There are more authentication methods than just username, password. How about secret hashes? certificates?

**Why is this needed**:
It depends what kubernetes wants to be. Fully runtime independent orchestrator of containers? Then we should be flexible with alternative image formats, alternative naming references and alternative authentication methods.

I'm developer of [LXE](https://github.com/automaticserver/lxe), a CRI shim, which is completely built around [LXD](https://github.com/lxc/lxd), supporting networking with CNI as well. And I just wanted to let you know what I was confronted with when building a Runtime which is completely different from the docker ecosystem.

**Comment by hanlins** [comment]
cc @dims

**Comment by BloodyIron** [comment]
Being able to define hostname when "hostNetwork: True" is really needed in esoteric scenarios, otherwise the pod takes the hostname of the node itself, and if you have multiple pods with the same hostname, that's a bad time. Why would we want that?
