### ISSUE TITLE
who use apiserver endpoints?  

### ISSUE THREAD

**Issue by MarryZhang** [kubernetes/kubernetes#97067]
HA apiserver can use ngx implementation，Who does the API Server endpoints serve?

**Comment by fedebongio** [comment]
Hi @MarryZhang thank you for your issue. Could you help us better understand the question? Maybe providing more context to your use case and what would you like to be responded? Thank you!

**Comment by fedebongio** [comment]
Ping!

**Comment by MarryZhang** [comment]
thank for you reply. I mean kubernetes has default service named kubernetes  int default namespace, the service  has a clusterIp, and this service has endpoint for apiserver, then who can use the default service or why need default service.

**Comment by MarryZhang** [comment]
thank for you reply @fedebongio  . I mean kubernetes has default service named kubernetes int default namespace, the service has a clusterIp, and this service has endpoints for apiserver, then who can use the default service or why need default service.

 what's the impact If I set apiserver endpoint-reconciler-type=none?

**Comment by lavalamp** [comment]
Most pods in the cluster connect to apiserver via the kubernetes service. So, if you disable that, the endpoints won't be updated, and the service will not get the right IP addresses in it, and then pods will not be connecting to the right IP addresses. Note that it might be accidentally correct for a while if your apiservers IP addresses don't change.

I wouldn't mess with this unless you know for sure your cluster handles things another way.
