### ISSUE TITLE
Node cpu capacity inside limited LXD container detected wrong in 1.19

### ISSUE THREAD

**Issue by wirwolf** [kubernetes/kubernetes#97066]
**What happened**:
When installing node in LXD container with limited CPU, kublet detect all CPUs  after merge https://github.com/kubernetes/kubernetes/pull/92967  
**What you expected to happen**:
Node cpu capacity should be detected correctly inside limited LXD container.

**How to reproduce it (as minimally and precisely as possible)**:
1. Limit LXD container that is used as k8s node:
```
lxc config show --expanded node-worker-1

  limits.cpu: "8"
```
2. Check limits inside linux container:
```
grep -c processor /proc/cpuinfo
4
```
3. Check limits with node describe (detected without limits):
kubectl describe node node-worker-1
```
...
Capacity:
  cpu:                12
```

4. Check kubelet logs (detected without limits):
```
I1202 08:50:29.885465 2916759 manager.go:213] Machine: {Timestamp:2020-12-02 08:50:29.885051244 +0000 UTC m=+0.122488081 NumCores:12 NumPhysicalCores:4 NumSockets:1 CpuFrequency:3600000 MemoryCapacity:8192000000
```
cadvisor info in this container: [img](https://user-images.githubusercontent.com/8457572/100901641-b6d02880-34cc-11eb-83ca-5ed71f44369c.png)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: dedicated server
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.4 LTS
- Kernel (e.g. `uname -a`): Linux node-worker-1. 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 **GNU/Linux**
- Install tools: 
* lxc version: 4.8
* rke version: v1.2.3
Related issue: https://github.com/kubernetes/kubernetes/issues/92638

**Comment by pacoxu** [comment]
dup with #92638 ？

`set kubeReserved in kubelet ` is a workaround.

**Comment by wirwolf** [comment]
@pacoxu nope, this issue observed in 1.19

**Comment by connde** [comment]
I also observed that on 1.20, using RKE

**Comment by ehashman** [comment]
Per https://github.com/kubernetes/kubernetes/issues/92638#issuecomment-651836545 running the kubelet inside a container is not supported. It should be run directly on the host.

/close
