### ISSUE TITLE
how to config devices of docker container by k8s?

### ISSUE THREAD

**Issue by YaShanBoy** [kubernetes/kubernetes#97079]
my docker run command:
    docker run  -u root 
 --device=/dev/bm-tpu0:/dev/bm-tpu0 
 --device=/dev/bmdev-ctl:/dev/bmdev-ctl 
 --device=/dev/ion:/dev/ion 
 --device=/dev/jpu:/dev/jpu 
 --device=/dev/vpu:/dev/vpu 
 --device=/dev/bm-vpp:/dev/bm-vpp   
 -v /system/lib:/system/lib 
 -itd 
 --name='test' 
 -p 9999:9999  
 iotproject:1.0   
 
what should i do with k8s？ 
Thank you for your attention

**Comment by pacoxu** [comment]
> Kubernetes provides a device plugin framework that you can use to advertise system hardware resources to the Kubelet. https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/

Fro vpu management, refer to https://intel.github.io/intel-device-plugins-for-kubernetes/README.html#plugins. Code in https://github.com/intel/intel-device-plugins-for-kubernetes.

**Comment by YaShanBoy** [comment]
> > Kubernetes provides a device plugin framework that you can use to advertise system hardware resources to the Kubelet. https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/
> 
> Fro vpu management, refer to https://intel.github.io/intel-device-plugins-for-kubernetes/README.html#plugins. Code in https://github.com/intel/intel-device-plugins-for-kubernetes.

thanks。My server is a customized edge box. I don't know what kind of device it belongs to。issue #5607 is what I need，But I don't get how to do it. I try the second method, mount the paths and set Privileged mode true, but it not work for me.

**Comment by YaShanBoy** [comment]
now I use fabric8 dependency，i find io.fabric8.kubernetes.api.model.VolumeDevice class。i guess this is what i need，but i don't know how to use it。

**Comment by YaShanBoy** [comment]
i find the question，ffmpeg use udp by default，so it can't read stream. use tcp. it's all right!
