### ISSUE TITLE
Admission controller to set default scheduler name

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#97072]
**What would you like to be added**:

An admission controller in kube-apiserver to set the default scheduler name, when it's not set.

To discuss, from users feedback:

- How should it be configured?
  1. [Preferred] Through a ConfigMap or a new resouce, similar to [LimitRange](https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace/#create-a-limitrange-and-a-pod)
  2. Through apiserver component config
- How to determine which Pods are affected?
  1. Pod selectors?
  2. Namespace label selectors?
- How to determine if "default-scheduler" was intended? #93067
  1. If #95203 is not accepted, we can add a new well-known name "k8s.io/default-scheduler", which should have the same configurations as "default-scheduler"

**Why is this needed**:

While this can be achieved through webhooks, the HTTP hop for every pod creation can be detrimental to performance.

/sig scheduling
/sig api-machinery

**Comment by alculquicondor** [comment]
cc @ahg-g @Huang-Wei @thockin

**Comment by deads2k** [comment]
We allow custom admission plugins by using mutating admission webhooks.  There are also existing projects like OPA which provide admission webhooks and ways to configure them to set default fields.  I don't see us adding this option to the core product.

/close
