### ISSUE TITLE
[Flaky test] [sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Pre-provisioned PV (xfs)][Slow] volumes should store data

### ISSUE THREAD

**Issue by tosi3k** [kubernetes/kubernetes#97071]
**Which jobs are flaking**:
gce-master-scale-correctness

**Which test(s) are flaking**:
`[sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Pre-provisioned PV (xfs)][Slow] volumes should store data`

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-master-scale-correctness

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volumes.go:151
Dec  4 12:39:05.233: Failed to create injector pod: timed out waiting for the condition
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volumes.go:182
```

**Anything else we need to know**:
Today's job failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1334830154144288768.

This test has also failed on October 22nd: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1319247469246156800.

Stdout from today's job's flake: https://pastebin.com/aQBJ0ecj.
Lots of lines like these:
```
Dec  4 12:39:05.869: INFO: error deleting PD "gce-scale-cluster-ced40298-49d6-4213-9d55-c0247d079da3": googleapi: Error 400: The disk resource 'projects/kubernetes-scale/zones/us-east1-b/disks/gce-scale-cluster-ced40298-49d6-4213-9d55-c0247d079da3' is already being used by 'projects/kubernetes-scale/zones/us-east1-b/instances/gce-scale-cluster-minion-heapster', resourceInUseByAnotherResource
Dec  4 12:39:05.869: INFO: Couldn't delete PD "gce-scale-cluster-ced40298-49d6-4213-9d55-c0247d079da3", sleeping 5s: googleapi: Error 400: The disk resource 'projects/kubernetes-scale/zones/us-east1-b/disks/gce-scale-cluster-ced40298-49d6-4213-9d55-c0247d079da3' is already being used by 'projects/kubernetes-scale/zones/us-east1-b/instances/gce-scale-cluster-minion-heapster', resourceInUseByAnotherResource
```

/sig storage
/sig scalability

**Comment by tosi3k** [comment]
CCing storage folks for visibility on this flake.

/cc @jingxu97 @mattcary

**Comment by mattcary** [comment]
Could this be a dup of #94108?

**Comment by jingxu97** [comment]
I checked the kubelet log, looks like xfs format on new disk hung. I see the log it starts to format, but it never returns (not fail, not succeeded).

I1204 12:34:03.818217    2242 mount_linux.go:390] Disk "/dev/disk/by-id/google-gce-scale-cluster-ced40298-49d6-4213-9d55-c0247d079da3" appears to be unformatted, attempting to format as type: "xfs" with options: [/dev/disk/by-id/google-gce-scale-cluster-ced40298-49d6-4213-9d55-c0247d079da3]

Searched online, here it mentioned mkfs might hung https://access.redhat.com/solutions/727333

Because of the hung, kubelet never retries to issue format again. Not sure whether it can help (safe) if we have a timeout for formatting job, and retries it.

**Comment by jingxu97** [comment]
cc @msau42  @saad-ali

**Comment by marseel** [comment]
/remove-lifecycle stale
We have new run that failed again with similar errors: 
[sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Inline-volume (xfs)][Slow] volumes should store data
[sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Pre-provisioned PV (xfs)][Slow] volumes should store data

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1379403890172104704

**Comment by lambdanis** [comment]
We had another failure today: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1418179484372176896

There are more tests flaking with the same error. https://github.com/kubernetes/kubernetes/issues/100331 looks like a potential duplicate, but mentions other tests in the same job, also in comments. [Triage search](https://storage.googleapis.com/k8s-gubernator/triage/index.html?text=Failed%20to%20create%20injector%20pod%3A%20timed%20out%20waiting%20for%20the%20condition) shows many similar failures in windows jobs, too.

My working hypothesis is that the issue is common for "volumes should store data" tests run with:
* gcepd driver and xfs
* windows-gcepd driver and ntfs

Flakes in `ci-kubernetes-e2e-gce-scale-correctness` (`gce-master-scale-correctness`) job are more painful, it's a master-informing job that's run only once a day.

/cc @kubernetes/sig-storage-test-failures

**Comment by msau42** [comment]
/assign @mauriciopoppe @jingxu97 
for windows failure

@mattcary any progress on the xfs issue?

**Comment by mattcary** [comment]
> @mattcary any progress on the xfs issue?

Not yet, we have a fixit 1st week of August focused on test failures.

**Comment by mauriciopoppe** [comment]
I've tried to open the [triage search](https://storage.googleapis.com/k8s-gubernator/triage/index.html?text=Failed%20to%20create%20injector%20pod%3A%20timed%20out%20waiting%20for%20the%20condition) but the JavaScript is failing with:

```
Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at interactive.js:338
```

Anyways I don't think this job is running in windows nodes https://github.com/kubernetes/test-infra/blob/2cdd0d0a4b52b08cdb6371ae94453e896fc06412/config/jobs/kubernetes/sig-scalability/sig-scalability-release-blocking-jobs.yaml#L3-L53, @jingxu97 do you know in what prow job would this error arise?

**Comment by lambdanis** [comment]
@mauriciopoppe Triage is crashing on Chrome at the moment (https://github.com/kubernetes/test-infra/issues/22906), but it's working on Firefox.

**Comment by lambdanis** [comment]
Windows jobs failing with `Failed to create injector pod: timed out waiting for the condition` are:
[ci-kubernetes-e2e-windows-containerd-gce](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-containerd-gce/1418180995550547968)
[ci-kubernetes-e2e-windows-containerd-gce-1-21](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-containerd-gce-1-21/1418105999616643072)
[ci-kubernetes-e2e-windows-gce-2019-1-20](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-2019-1-20/1414532462775635968)
[ci-gce-pd-csi-driver-latest-k8s-master-windows-2019-migration](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-gce-pd-csi-driver-latest-k8s-master-windows-2019-migration/1415742546386096128)
[ci-kubernetes-e2e-windows-gce-2004](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-2004/1416914826931736576)
But in all of these jobs there are many tests failing with different errors as well, I don't know how related that is.

**Comment by mauriciopoppe** [comment]
Awesome, thank you @lambdanis for finding the individual jobs!

I know a few things about them:

- ci-kubernetes-e2e-windows-containerd-gce never succeeded in the past
- ci-kubernetes-e2e-windows-containerd-gce-1-21 never succeeded in the past
- ci-kubernetes-e2e-windows-gce-2019-1-20 has some flakes but most of the storage e2e tests pass
- ci-gce-pd-csi-driver-latest-k8s-master-windows-2019-migration has some flakes too, here's where I saw a flake in one run where the error matched the description.

I'm going to try reproducing this one: `[sig-storage] In-tree Volumes [Driver: windows-gcepd] [Testpattern: Dynamic PV (ntfs)][Feature:Windows] volumes should store data`, it sometimes flakes with the `create injector pod` error

**Comment by jkaniuk** [comment]
We have few more flakes lately: 
![image](https://user-images.githubusercontent.com/5487158/128049507-fa4903ca-a64a-4237-9dc6-02885ac130e2.png)


> Not yet, we have a fixit 1st week of August focused on test failures.

Fingers crossed

**Comment by mattcary** [comment]
#104282 is out to fix the linux versions of this test. Is there anyone here who can authoritively say that mkfs -K is the right thing to do? If so, please comment on the PR :-)

**Comment by johngmyers** [comment]
Could this be a dup of 89178?

**Comment by mattcary** [comment]
We think this is due to mkfs having problems on PD, see #104282 for the conversation.
