### ISSUE TITLE
PVC and PV to become Bound, but PVC and PV Protection finalizer is set []

### ISSUE THREAD

**Issue by chymy** [kubernetes/kubernetes#97097]
**What happened**:
k8s version: v1.19.4
I create pv and pvc, PVC and PV to become Bound, but PVC and PV Protection finalizer is set []
```
# kubectl get pvc
NAME           STATUS   VOLUME        CAPACITY   ACCESS MODES   STORAGECLASS   AGE
hostpath-pvc   Bound    hostpath-pv   1Gi        RWO                           45s
```
describe the pvc result:
```
~]# kubectl describe pvc hostpath-pv
Name:          hostpath-pvc
Namespace:     default
StorageClass:
Status:        Bound
Volume:        hostpath-pv
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
Finalizers:    []
Capacity:      1Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    pod-pvc-test
Events:        <none>
```

**What you expected to happen**:
Finalizers is set [kubernetes.io/pv-protection]

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.19.4

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
I think this is expected.

According to https://kubernetes.io/docs/concepts/storage/persistent-volumes/#storage-object-in-use-protection ， the finalizer is added when it is terminating.

IMO, pvc deleting process:
1. send delete resource request to apiserver. 
2. the pvc enters `Terminating` status and protection finalizer `kubernetes.io/pv-protection` is added
3. PVC removal is postponed until the PVC is no longer actively used by any Pods. Then the finalizer is remove.
4. the pvc is removed finally after the finalizer is an empty list.

**Comment by chymy** [comment]
e2e test: 
PVC is become Bound.
`Checking that PVC Protection finalizer is set` is failed.
```
[BeforeEach] [sig-storage] PVC Protection
  /workspace/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:174
�[1mSTEP�[0m: Creating a kubernetes client
Dec  5 12:49:23.260: INFO: >>> kubeConfig: /root/.kube/config
�[1mSTEP�[0m: Building a namespace api object, basename pvc-protection
�[1mSTEP�[0m: Waiting for a default service account to be provisioned in namespace
[BeforeEach] [sig-storage] PVC Protection
  /workspace/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/storage/pvc_protection.go:71
Dec  5 12:49:23.320: INFO: Waiting up to 30m0s for all (but 0) nodes to be schedulable
�[1mSTEP�[0m: Creating a PVC
Dec  5 12:49:23.329: INFO: Default storage class: "gluster-heketi"
Dec  5 12:49:23.329: INFO: Warning: Making PVC: VolumeMode specified as invalid empty string, treating as nil
�[1mSTEP�[0m: Creating a Pod that becomes Running and therefore is actively using the PVC
�[1mSTEP�[0m: Waiting for PVC to become Bound
Dec  5 12:49:33.432: INFO: Waiting up to 3m0s for PersistentVolumeClaims [pvc-protection877bw] to have phase Bound
Dec  5 12:49:33.437: INFO: PersistentVolumeClaim pvc-protection877bw found and phase=Bound (4.874505ms)
�[1mSTEP�[0m: Checking that PVC Protection finalizer is set
Dec  5 12:49:33.440: FAIL: PVC Protection finalizer(kubernetes.io/pvc-protection) is not set in []
Expected
    <bool>: false
to equal
    <bool>: true
```

@pacoxu

**Comment by pacoxu** [comment]
After reading the logic, it is added by the admission controller `StorageObjectInUseProtection` which is enabled by default.
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#storageobjectinuseprotection

Another logic to add finalizer to old pvc is in 
https://github.com/kubernetes/kubernetes/blob/ff3e5e06a79bc69ad3d7ccedd277542b6712514b/pkg/controller/volume/pvcprotection/pvc_protection_controller.go#L184-L191

I think you need to check the admission controller configuration in apiserver firstly.

**Comment by chymy** [comment]
> After reading the logic, it is added by the admission controller `StorageObjectInUseProtection` which is enabled by default.
> https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#storageobjectinuseprotection
> 
> Another logic to add finalizer to old pvc is in
> https://github.com/kubernetes/kubernetes/blob/ff3e5e06a79bc69ad3d7ccedd277542b6712514b/pkg/controller/volume/pvcprotection/pvc_protection_controller.go#L184-L191
> 
> I think you need to check the admission controller configuration in apiserver firstly.


I've set  `--enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota,DefaultStorageClass,Priority,EventRateLimit,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,StorageObjectInUseProtection`, but the `Finalizers` is still [].

**Comment by chymy** [comment]
I know why, apiserver is set `--feature-gates=StorageObjectInUseProtection=false`. Thanks @pacoxu .
