### ISSUE TITLE
Add a new metric to measure scheduling latency 

### ISSUE THREAD

**Issue by yuanchen8911** [kubernetes/kubernetes#97111]
**What would you like to be added**:

kube-scheduler provides a metric `PodSchedulingDuration` to measure the duration from the time the pod was first observed by the scheduler (InitialAttemptTimestamp) to the time the binding request is successfully done.  However, the metrics can  only measure those pods that are finally successfully scheduled. If a pod is pending forever or deleted, its contribution to the latency will be zero. Can we add a metric that measures the duration from the the pod submission (InitialAttempTimestamp) to the current time?

**Why is this needed**:

The new metric can give us a better idea about the durations incoming pods wait to be scheduled.

**Comment by yuanchen8911** [comment]
cc @ahg-g

**Comment by adtac** [comment]
>Can we add a metric that measures the duration from the the pod submission (InitialAttempTimestamp) to the current time?

we append new metric samples but we cannot update old/existing metric samples. as a result, I'm not sure how feasible it is to include a metric measuring the time from pod submission to _current time_.

you probably already know this, but for the sake of completion, would a combination of `e2e_scheduling_duration_seconds` and `pending_pods` solve your needs? I know that the former metric doesn't include pending pods, but perhaps you can look at the pending_pods metric to infer _some_ relevant information?

**Comment by yuanchen8911** [comment]
> > Can we add a metric that measures the duration from the the pod submission (InitialAttempTimestamp) to the current time?
> 
> AFAICT we can append new metric samples but we cannot update old/existing metric samples. as a result, I'm not sure how feasible it is to include a metric measuring the time from pod submission to _current time_.
> 
> you probably already know this, but for the sake of completion, would a combination of `e2e_scheduling_duration_seconds` and `pending_pods` solve your needs? I know that the former metric doesn't include pending pods, but perhaps you can look at the pending_pods metric to infer _some_ relevant information?


Thanks for the feedback, @adtac! By pending_pods, do you mean the number of pending pods or the waiting time of pending pods? I'm not sure we can get the latter. Thanks!

**Comment by yuanchen8911** [comment]
A related question is per priority-class scheduling latency. In many cases, users want to provide guarantees or SLOs for pods in top priorities only. Per-priority class performance metrics would be useful. Is it something we should add?  Thanks.

**Comment by ahg-g** [comment]
I commented on the other issue regarding scheduling latency and priority class. Regarding this one, we have two options: 

1) do something similar to pod resource metrics: https://github.com/kubernetes/kubernetes/pull/94866
2) you could query the api server directly, list all pending pods, and calculate how long they have been pending (each pod has a creation timestamp)

I don't think we have strong use case for option 1 compared to resource metrics, so would option 2 work for you?

**Comment by yuanchen8911** [comment]
> I commented on the other issue regarding scheduling latency and priority class. Regarding this one, we have two options:
> 
> 1. do something similar to pod resource metrics: #94866
> 2. query the api server directly, list all pending pods (ones with nodename not set for example), and calculate how long they have been pending (each pod has a creation timestamp)
> 
> I don't think we have strong use case for option 1 compared to resource metrics, so would option 2 work for you?

Thanks, it's helpful. We'll look at both options and have more discussions if needed.

**Comment by yuanchen8911** [comment]
@ahg-g @Huang-Wei  Here is an update on per priority_class scheduling latency metric. 

We have a prototype implementation. Per the discussion in #97983, we added a new metric with priority_class label instead of changing the existing one.   The implementation is straightforward: create a new` HistogramVec` metric and update  its value with the priority_class in schedulerOne. 

1. Create a `HistogramVec` metric in `pkg/scheduler/metrics/metrics.go`
   
```
    //  e2e scheduling latency with priority_class label
    E2eSchedulingLatencyWithPriorityClass = metrics.NewHistogramVec(
        &metrics.HistogramOpts{
            Subsystem:      SchedulerSubsystem,
            Name:           "e2e_scheduling_duration_with_priority_class_seconds",
            Help:           "Per priority class e2e scheduling latency in seconds (scheduling algorithm + binding)",
            Buckets:        metrics.ExponentialBuckets(0.001, 2, 15),
            StabilityLevel: metrics.ALPHA,
        },
        []string{"priority_class"})
```
   2. Update the metric (scheduleOne in `kubernetes/pkg/scheduler/scheduler.go`)
```
metrics.E2eSchedulingLatencyWithPriorityClass.WithLabelValues(pod.Spec.PriorityClassName).Observe( metrics.SinceInSeconds(start))
```

We don't think the number of priority classes would be issues. 

1. There are typically a predefined and small number of priority classes in production environments. 
2. A bucket for a new priority_class will be automatically created on demand.  

 If the solution is reasonable, we'd like to file a PR to add two new metrics with priority_class information. 
- `E2eSchedulingLatencyWithPriorityClass` 
- `PodSchedulingLatencyWithPriorityClass`

Thanks!

**Comment by Huang-Wei** [comment]
> If the solution is reasonable, we'd like to file a PR to add two new metrics with priority_class information.
> 
> * `E2eSchedulingLatencyWithPriorityClass`
> * `PodSchedulingLatencyWithPriorityClass`

Given the limited number of PriorityClasses, can we just reuse the existing `{E2e|Pod}SchedulingLatency` metric?

> We have a prototype implementation. Per the discussion in #97983, we added a new metric with priority_class label instead of changing the existing one.

IMO this issue is a bit different with #97983 - the metric discussed in #97983 involves type change (Histogram->HistogramVec); while in this issue the existing `{E2e|Pod}SchedulingLatency` metrics are already `HistogramVec`, so I suppose we can reuse it by introducing a new label. @ahg-g @adtac @alculquicondor I think adding new labels to an existing metric is backward compatible, WDYT?

**Comment by alculquicondor** [comment]
> I think adding new labels to an existing metric is backward compatible, WDYT?

It depends if your ingesting pipeline can handle a new label. So generally no.

I'm still not convinced that we can assume that all clusters have a limited amount of priority classes. It's possible that some clusters might use a wide range of priorities to do some kind of FIFO scheduling, even though that is discouraged.

Instead, I would favor an approach like #94866, which has an opt-in nature.

**Comment by ahg-g** [comment]
> IMO this issue is a bit different with #97983 - the metric discussed in #97983 involves type change (Histogram->HistogramVec); while in this issue the existing {E2e|Pod}SchedulingLatency metrics are already HistogramVec, so I suppose we can reuse it by introducing a new label. @ahg-g @adtac @alculquicondor I think adding new labels to an existing metric is backward compatible, WDYT?

Existing metrics don't work for this use case. OP wants metrics for pods that aren't scheduled yet. The source of truth for this is the API server. We have two options presented in https://github.com/kubernetes/kubernetes/issues/97111#issuecomment-742846015. I wouldn't mind going for option 1, I think the metric is useful to have it exported by a core component.
