### ISSUE TITLE
clusterinformations.crd.projectcalico.org "default" not found

### ISSUE THREAD

**Issue by LeslieRan** [kubernetes/kubernetes#97117]
I used `kubectl create` to create a pod with the name "sidecar-verification", but then the containers in the pod were not running and the status of the pod is always `ContainerCreating`. So I used `kubectl describe` to check the status of the pod, as the following picture shows:
![pod-warning](https://user-images.githubusercontent.com/33219197/101459383-233aa400-3973-11eb-90c3-f3a5078c3f97.png)
I have no idea about this problem.
thanks for any anwers!

**Comment by pacoxu** [comment]
seems to be a calico issue

open issue in 
https://github.com/projectcalico/calico/issues may help. similar to https://github.com/projectcalico/calico/issues/2485

you may check calico-node version and status on that node.

**Comment by LeslieRan** [comment]
> seems to be a calico issue
> 
> open issue in
> https://github.com/projectcalico/calico/issues may help. similar to [projectcalico/calico#2485](https://github.com/projectcalico/calico/issues/2485)
> 
> you may check calico-node version and status on that node.

Thank you very much! I have found out the exact reason. Calio just fits the network interfaces whose names start with `eno` and `ens` described in `YAML` file, but my network interface's name starts with `enp`. It could works normally after I added `enp` to the yaml file.

**Comment by pacoxu** [comment]
@LeslieRan  👍

/close

**Comment by lizheray** [comment]
Same problem but different reason.
