### ISSUE TITLE
Optimize rbac/bootstrap-roles post-startup-hook

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/kubernetes#97119]
The [rbac/bootstrap-roles post startup-hook](https://github.com/kubernetes/kubernetes/blob/9bf7fcfc76eb809ac74ce1f5f36f95de5e3a06ba/pkg/registry/rbac/rest/storage_rbac.go#L141) is slooooow. 

**Why:** It needs to reconcile ~100 roles/clusterroles/rolebings/clusterrolebindings, each of them requiring 1-2 api calls (get + optional update). It does all operations serially and in case of any error it starts from the beginning. In case of overloaded api-server it may legitimately take O(minutes) for this post-startup hook to complete.

**Why important:** Api-server won't become healthy/ready as long as all post-startup-hook completes. As a result, an overloaded kube-apiserver that was restarted may require O(minutes) to become healthy again. This may cause unexpected issues if the liveness probe is not configured to allow that, e.g. it may end up in kube-apiserver going into restart loop. 

**What would you like to be added**:
Luckily, there are two low-hanging-fruits that should allow to significantly speed up:

- [ ] Increase parallelism - while we cannot execute all api-call in parallel (some may depend on each other, e.g. creating role before role-binding) we can definitely do better than executing everything serially
- [ ] Fix error handling to not start from the beginning - we could resume from the failed operations

/sig api-machinery
/sig scalability

**Comment by fedebongio** [comment]
label:priority/longterm

**Comment by fedebongio** [comment]
label:priority/important-longterm

**Comment by shyamjvs** [comment]
Just looking at this issue and have couple thoughts:

These roles/bindings that are part of bootstrap typically need to be created as one-off during cluster creation iiuc (maybe few new ones during version updates). If that's the case, can we instead just check those bootstrap roles/bindings exist before making any update calls? This might help avoiding those update calls altogether (or most of them) rather than adding parallelism. Also for getting those objects, we probably can do it through 4 list calls rather than 100 individual gets? Just throwing out an idea there.

**Comment by mm4tt** [comment]
> If that's the case, can we instead just check those bootstrap roles/bindings exist before making any update calls?

We do that already in the current implementation. It's not the udpate calls that are problematic but the overall number of calls and the fact they're executed in serial

> Also for getting those objects, we probably can do it through 4 list calls rather than 100 individual gets? Just throwing out an idea there.

That's a really interesting idea. If it can work this way then big +1 to it

**Comment by gavinfish** [comment]
> Just looking at this issue and have couple thoughts:
> 
> These roles/bindings that are part of bootstrap typically need to be created as one-off during cluster creation iiuc (maybe few new ones during version updates). If that's the case, can we instead just check those bootstrap roles/bindings exist before making any update calls? This might help avoiding those update calls altogether (or most of them) rather than adding parallelism. Also for getting those objects, we probably can do it through 4 list calls rather than 100 individual gets? Just throwing out an idea there.

ah, thanks for sharing this idea, let me have a try.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/97123#issuecomment-821322913 seems this is pending someone rebasing that PR and a bit of follow-up

/remove-lifecycle rotten
I think we still want this.
