### ISSUE TITLE
Specify PersistentVolumeClaimSource by Selector, not Name

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#9712]
My understanding is that when we want a cluster of e.g. 3 pods with persistent storage, the best we can do today is to launch 3 RCs, specifying a different persistent volume for each.   We can still group those into one service.

I think it would be nice to be able to just specify one RC, and have it map to a group of persistent volumes.

One way to do that would be to specify a list of persistent volumes in the RC, with some sort of parameterization to say "this PV is for pod 1, this PV for pod 2, etc"

An alternative which would be "more k8s" would be to allow specifying a selector, which would match labels on our PersistentVolumeClaims.  The "identity" of a pod would be determined not by the rc passing down an identifier to the pod, but by whatever PV it ended up with.

For unaware databases, this might require a smarter management process in the pod, but I'm thinking about that separately ;-)

One downside would be that it would be hard to specify groupings; for example we might want a data-volume and a log-volume to be assigned together.  We could specify a further list of fields that must match across all volume allocations to a single pod, but there may be neater solutions (and this may not be that important).

Is this a good idea?  Or is there a trick I am missing to do this today?

**Comment by markturansky** [comment]
+1.

Yes, we need a way for replicas from a replication controller to get their own volume but use the same single claim in the RC.  That was out of scope for the original implementation but it is a known limitation that will be worked post 1.0.

A good use case is MongoDB where each node in the mongo cluster requires its own volume.

**Comment by thockin** [comment]
It's the right direction, we just (as you know :) ran out of time for 1.0.

**Comment by smarterclayton** [comment]
xref #260

**Comment by fd** [comment]
What is the status of this feature?

/cc @markturansky @thockin

**Comment by thockin** [comment]
Nobody has worked on speccing this any further yet.  The most immediate problem I see is that we don't currently track which claims are used by pods, so we need a way to back-link and not select PVCs that are "in use".

**Comment by fd** [comment]
How hard would the back-link be to implement. I might want to give that a shot.

**Comment by thockin** [comment]
I think it's more a caseof whether we want to build that backlink, or find
a different solution.  Inter-object linkages are tricky to get right and
keep right

**Comment by justinsb** [comment]
Closing, we did PetSets instead
