### ISSUE TITLE
kubectl does not preserve YAML formatting

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#97121]
**What happened**:

go-yaml library stopped preserving the textual YAML format. As a result, `kubectl label --local` command automatically reformats the yaml removing empty newlines and converting multiline strings into one line. 

See:
- https://github.com/mikefarah/yq/issues/465
- https://github.com/go-yaml/yaml/issues/627

I was previously using kubectl 1.17.x where old version of go-yaml parser was used and formatting was preserved. After I upgraded to kubectl 1.19.x, formatting is not preserved anymore.

Can we keep the old version of go-yaml parser library and preserve the format?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
Do you have a failed example? 

```
kubectl label  pod task-pv-pod foo=1
kubectl label --local -f pod-pvc.yaml pod task-pv-pod foo=2 -o yaml
```
Simple demo works for me
