### ISSUE TITLE
UnexpectedAdmissionError

### ISSUE THREAD

**Issue by rojinsafavi** [kubernetes/kubernetes#97131]
My code was working fine last night, but this morning it started giving me this error when I created my YAML. I have to mention that the error was there last night as well, but I was able to get rid of the error by deleting and creating the job again. But this no longer works today.

the pod description gives this message:

`Message:        Pod Allocate failed due to device plugin GetPreferredAllocation rpc failed with err: rpc error: code = Unknown desc = Unable to retrieve list of available devices: error creating nvml.Device 5: nvml: GPU is lost, which is unexpected
`

bash$ kubectl get pods
NAME          READY   STATUS                     RESTARTS   AGE
rojin-2q6ld   0/1     UnexpectedAdmissionError   0          4s

**Comment by troy0820** [comment]
/remove-kind bug
/kind support
It's difficult to reproduce the issue @rojinsafavi.  Can you provide us with the version of Kubernetes, OS, what pods you are trying to run?
