### ISSUE TITLE
kube-apiserver v1.17.3 consume high memory until it is exhausted

### ISSUE THREAD

**Issue by qd19zzx** [kubernetes/kubernetes#97142]
We have a kubernetes cluster with 3 masters, and it has running stable for almost 3 months. But from 2 days before, we found the api-server on each masters has consume high memory until the memory is exhausted.  It seems bytes.makeSlice has consumes a lot. But I am newer of k8s, I have no idea of how to resolve this situation. So could anyone provide some clues to solve this problem

 ```
Showing nodes accounting for 11123.22MB, 95.76% of 11616.18MB total
Dropped 890 nodes (cum <= 58.08MB)
Showing top 20 nodes out of 113
      flat  flat%   sum%        cum   cum%
 9226.15MB 79.43% 79.43%  9226.15MB 79.43%  bytes.makeSlice
 1122.61MB  9.66% 89.09%  1243.65MB 10.71%  k8s.io/kubernetes/vendor/k8s.io/api/core/v1.(*ConfigMap).Unmarshal
  139.55MB  1.20% 90.29%   153.05MB  1.32%  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1.(*ObjectMeta).Unmarshal
  120.53MB  1.04% 91.33%   165.03MB  1.42%  encoding/json.(*decodeState).objectInterface
  117.29MB  1.01% 92.34%   117.29MB  1.01%  reflect.unsafe_NewArray
  108.03MB  0.93% 93.27%   108.03MB  0.93%  reflect.mapassign
   66.51MB  0.57% 93.84%    66.51MB  0.57%  k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*Iterator).ReadString
   62.51MB  0.54% 94.38%    62.51MB  0.54%  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic.ObjectMetaFieldsSet
   61.51MB  0.53% 94.91%    61.51MB  0.53%  k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/registry/customresource.objectMetaFieldsSet
   43.01MB  0.37% 95.28%   137.03MB  1.18%  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime.structToUnstructured
      18MB  0.15% 95.43%   183.61MB  1.58%  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.(*watchCache).Replace
   13.50MB  0.12% 95.55%   137.03MB  1.18%  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime.toUnstructured
       9MB 0.077% 95.63%   237.54MB  2.04%  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.unstructuredJSONScheme.decodeToUnstructured
    7.50MB 0.065% 95.69%   144.53MB  1.24%  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime.(*unstructuredConverter).ToUnstructured
       6MB 0.052% 95.74%   123.29MB  1.06%  reflect.MakeSlice
    1.50MB 0.013% 95.76%  8944.02MB 77.00%  encoding/json.mapEncoder.encode
```

[pprof.kube-apiserver.alloc_objects.alloc_space.inuse_objects.inuse_space.004.pb.gz](https://github.com/kubernetes/kubernetes/files/5663210/pprof.kube-apiserver.alloc_objects.alloc_space.inuse_objects.inuse_space.004.pb.gz)
[profile001.pdf](https://github.com/kubernetes/kubernetes/files/5663722/profile001.pdf)

**Comment by qd19zzx** [comment]
I got the root cause, some app has sync the ldap data and create a configmap for each account in k8s. So there is more than 100K+ configmap in one namespace. After delete these configmaps, the memory has decrease.

**Comment by qd19zzx** [comment]
Is there a memory leak in kube-apiserver v1.17.3？Although we have 170K+ configmaps, the memory has never decreased. Why this memory cannot be gc.

**Comment by roycaihw** [comment]
> After delete these configmaps, the memory has decrease
> Although we have 170K+ configmaps, the memory has never decreased

Could you clarify your question? I assume that you expect the memory to eventually decrease while you have the 170k+ configmaps, but you're not seeing it happening. If so, I think it's expected. I think the memory consumption is from the watch cache (which loads all the objects in memory). You can try disable the watch cache (`--watch-cache false`) to verify.
