### ISSUE TITLE
Need to be able to change the  "Internal IP" of worker nodes.

### ISSUE THREAD

**Issue by 842Mono** [kubernetes/kubernetes#97143]
Hi.

We have a master node and two worker nodes. (The master node and one of the worker nodes are on "GENI". The other worker node is an AWS node).

We are able to connect the GENI worker node to the GENI master node without issues. However, when we try to connect the AWS worker node to the GENI master node, the internal IP that is set needs to be changed.

The AWS node has a public IP address and a private IP address. The internal IP address is being set to the private IP address of the AWS node. The master node therefore is not able to reach the  AWS worker node.

**What would you like to be added**:
We need to be able to modify the "internal IP" address of worker nodes. Maybe provide it as a command line argument to the `kubeadm join` command that we run on the worker node?

**Why is this needed**:
We are not able to correctly connect a worker node to the master node.

Maybe another thing that can be done is to correctly detect the public IP address of the worker node?

Why not detect the IP address that's in the headers of the packets that are being sent from worker nodes to the master node?

**Comment by aojea** [comment]
> We are able to connect the GENI worker node to the GENI master node without issues. However, when we try to connect the AWS worker node to the GENI master node, the internal IP that is set needs to be changed.

what is GENI and how it connects to the AWS node?

**Comment by 842Mono** [comment]
GENI is a cloud provider for research.

**Comment by aojea** [comment]
and the AWS node has direct connectivity to the GENI master?

> Maybe another thing that can be done is to correctly detect the public IP address of the worker node?

you need to use the aws cloud provider for the node IP autodetection https://theithollow.com/2020/01/13/deploy-kubernetes-on-aws/, but I honestly don't know which IP it takes

```
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: aws
```

If you want to configure the IP manually you can pass it as a kubelet flag `--node-ip`, in kubeadm it will be something like this:

```
kind: JoinConfiguration
nodeRegistration:
  kubeletExtraArgs:
    node-ip: 172.
```

**Comment by 842Mono** [comment]
@aojea do I do this on the worker node? Do I add these to the config file that I pass to `kubeadm join`?

**Comment by aojea** [comment]
> @aojea do I do this on the worker node? Do I add these to the config file that I pass to `kubeadm join`?

I gave you same options because I thought you were experimenting with multicluster  or something like that, but if you don't know how to use those options, I suggest you to start with something simpler, getting more familiar with Kubernets architecture and, in this case, networking is going to be important, since you have to provide connectivity end to end between all the pods in all the workers.

**Comment by neolit123** [comment]
/remove-kind feature
/kind support

as aojea noted, `kubelet ... --node-ip` already supports this.
you need to do this on all nodes where you want to pin an IP.

**Comment by 842Mono** [comment]
Hi. Sorry for the late reply. Here's what I'm trying to do.

@aojea I'm trying to connect a node on AWS to a master (or a cluster) that is on GENI.

On the AWS node, I tried setting just the `--node-ip` flag. I edited the file `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` like so:

    ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS --node-ip 3.134.96.90
    
Then I connect to our cluster using the join command like I do normally. However this doesn't seem to work. When I do `kubectl get nodes -o wide` I get something like this:

    NAME                                                       STATUS   ROLES    AGE   VERSION   INTERNAL-IP      EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION       CONTAINER-RUNTIME
    ip-172-31-47-3.us-east-2.compute.internal                  Ready    <none>   27s   v1.19.4   <none>           <none>        Ubuntu 20.04.1 LTS   5.4.0-1030-aws       docker://19.3.8

You can see that the INTERNAL-IP field of the node is <none>.

Also, I'm checking the logs generated in `journalctl` on the AWS node I'm trying to connect. I get this line:
    
    Dec 30 20:06:35 ip-172-31-47-3.us-east-2.compute.internal kubelet[2891632]: E1230 20:06:35.420485 2891632 kubelet_node_status.go:560] Failed to set some node status fields: failed to validate nodeIP: node IP: "3.134.96.90" not found in the host's network interfaces

I'm thinking that this issue has to do with that there's like a NAT between the AWS node and the internet.

Any ideas? What can I do to get this to work? I might try to follow the steps in the link you posted more thoroughly, but I'm thinking that our scenario is a little bit different than theirs in that they're connecting nodes together and they are all on AWS, right?

> and the AWS node has direct connectivity to the GENI master?

I think I should describe AWS and GENI as "two separate clouds". The only way they can communicate is just through the internet.

**Comment by 842Mono** [comment]
@aojea @neolit123 Can I get anymore help on this?

**Comment by aojea** [comment]
you are going through a very complex and unsupported scenarios, suggestions can help but I'm not confident that will fully work, as I said in https://github.com/kubernetes/kubernetes/issues/97143#issuecomment-742110316
 I suggest you to start small and iterate

**Comment by MohammedNoureldin** [comment]
For new clusters that are initialized using `kubeadm`, the approach I am showing below is recommended way, as stated in the file /etc/systemd/system/kubelet.service.d/10-kubeadm.conf:

> Preferably, the user should use the .NodeRegistration.KubeletExtraArgs object in the configuration files instead.

The cluster has to initialized using this command

    kubeadm init --config=/tmp/kubeadm-init-config.yaml

with this config file /tmp/kubeadm-init-config.yaml:

```
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    ########## NOTICE THIS ########## < < < < < < < < < <
    node-ip: {{ internal_ip_address }}
patches:
  directory: /tmp/kubelet-patches
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
clusterName: {{ domain_name }}
controlPlaneEndpoint: {{ control_plane_endpoint }}
networking:
  dnsDomain: cluster.local
  podSubnet: {{ pod_network_cidr }}
```

The same approach can be followed for Join, but with JoinConfiguration.
