### ISSUE TITLE
damonset pod age aren't changed when I upgrade the cluster/node version

### ISSUE THREAD

**Issue by kshke** [kubernetes/kubernetes#97154]
I have pod niginx which has pod's disruption budget. Then I upgrade the cluster from 1.7.11 to 1.18.10. As shown below, the pod age didn't change. 
sarah@Azure:~$ kubectl get pods
NAME                     READY   STATUS    RESTARTS   AGE
nginx-86c57db685-22tpr   1/1     Running   0          14d
nginx-86c57db685-gmmrv   1/1     Running   0          14d

The damonset pod omsagent's also don't change.
omsagent-2skwm                              1/1     Running   0          7d11h   10.244.2.2    aks-agentpool-14560875-vmss000001   <none>           <none>
omsagent-6zb7q                              1/1     Running   0          7d11h   10.244.1.2    aks-agentpool-14560875-vmss000000  

is it by designed?

**Comment by pacoxu** [comment]
`Age = now - createdTimeStamp`
If the pod is not recreated, the createdTimeStamp will not be changed.

**Comment by kshke** [comment]
@pacoxu  The createdTimestamp is not changed, too. but when I upgrade k8s cluster in azure, the node was restart so all the pods must have recreated.

For the other pods which are not ds or don't have pdb, the age of pod are changed.

**Comment by pacoxu** [comment]
You may compare the container inspect info(docker ps -a && docker inspect container-id) and pod status(kubectl get pod -o yaml) as well for detailed date time.

Read more in https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/

**Comment by liggitt** [comment]
Restarting a node does not necessarily recreate all the Pod objects running on it.

**Comment by kshke** [comment]
@liggitt  we have recreated the node,  will all pods recreated in this scenario？

**Comment by liggitt** [comment]
If draining the node is part of the replacement process (which is recommended), then yes. 

If the node is absent for long enough and you are running a cloud provider that notices the node is gone (takes ~15 minutes by default, I think), the original pods will be deleted.

 If you quickly delete and recreate the node without touching the Node or Pod API objects, I don't think the Pod objects are guaranteed to be recreated.

**Comment by neolit123** [comment]
@kshke please re-open if you have more questions.

/close
