### ISSUE TITLE
DualStack e2e Services TestJig

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#97156]
The e2e testing framework uses the TestJib object for Services testing

https://github.com/kubernetes/kubernetes/blob/10744811f51cef741948676758563cfe04bb7ef2/test/e2e/framework/service/jig.go#L61-L68

With the new Dual Stack API changes in 1.20, the Services API has 3 new fields:

https://github.com/kubernetes/kubernetes/blob/10744811f51cef741948676758563cfe04bb7ef2/pkg/apis/core/types.go#L3605-L3633

The e2e tests for DualStack are currently living separately in this file:

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/dual_stack.go

However, since the intention is to move DualStack to beta this cycle, maybe we should start to adapt current tests to support DualStack, starting for adapting the TestJig object, so we can later adapt current tests and avoid having multiple files for similar tests

**Comment by aojea** [comment]
dibs on @cmluciano :)
pinging @khenidak @aramase and @thockin

**Comment by GeorgeTsilias** [comment]
I'd love to grab this if no one is currently working on this; I'm looking to get my first contribution into Kubernetes.

Could you please provide some guidance on what should be done in order for current tests to support DualStack? 

If I'm getting this right, the idea is to allow accessing the new fields via the TestJig object methods and then integrate testing for IPV6 in the [jig.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/service/jig.go) file.

**Comment by aojea** [comment]
> If I'm getting this right, the idea is to allow accessing the new fields via the TestJig object methods and then integrate testing for IPV6 in the [jig.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/service/jig.go) file.

hi @GeorgeTsilias , thanks for stepping up, if you take a look to the current dual_stack tests, they use the `TestJig` object, but since it it doesn't support dual stack, they have to use additional helper functions like in

https://github.com/kubernetes/kubernetes/blob/b860d08e4ba0c89724046f4ead26b9a535ebdad0/test/e2e/network/dual_stack.go#L671-L697

the goal is to modify the `TestJig` object so we can test `DualStack` services using it directly

**Comment by aojea** [comment]
/close
I thought that this was a good idea at that time, but it doesn't seem so, or maybe in the future ...
