### ISSUE TITLE
How do I get the status of a POD? Instead of using SSH, execute the Kubectl get POD command.

### ISSUE THREAD

**Issue by Gefuxing** [kubernetes/kubernetes#97152]
Could you please tell me how to get the running, Terminating, Pending and other states of POD? The state obtained by JavaAPI is not consistent with the actual running state of POD. I want to get a lot of pod states in namespace.Hope to get help.Thank you very much! Instead of using SSH, execute the Kubectl get POD command.
mq-rabbitmq-0                                    1/1     Running             0          10m
mq-rabbitmq-1                                    1/1     Running             0          9m39s

**Comment by pacoxu** [comment]
/kind support

To get java kubernetes client, refer to https://github.com/kubernetes-client/java 

To know pod status, read https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/

**Comment by pacoxu** [comment]
Please try asking on the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

if there is a confirmed kubernetes bug, open a new issue with reproduction steps and good details.

thanks
/close
