### ISSUE TITLE
Support ArrayJob semantics in the job api

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#97169]
**What would you like to be added**:
ArrayJob semantics to the job api (like completions index). It is also worth considering having stable dns names for the pods (similar to StatefulSet).

**Why is this needed**:
The current k8s Job model supports a range of [patterns](https://kubernetes.io/docs/concepts/workloads/controllers/job/#job-patterns), but it still has some drawbacks:
- It supports embarrassingly parallel batch jobs, but through the work-queue model, which is not easy to use:
  -  It requires setting up an external message queue service.
  - It requires changes to the job binary to link the message queue client library needed to pull work from the message queue.
  - It is prone to race conditions when coordinating which pod works on which work item.
  - Doesn’t support MPI (Message Passing Interface) type HPC workloads.

“Array Job” model complements the existing Job API model: Array Job represents an array of identical tasks (pods) differentiated by an ordinal index passed as an environment variable (via the downward API) to the pod. Array Job has the following advantages:
- Conforms to how other batch frameworks represent parallel jobs, including slurm, qsub, and AWS Batch
- It is simpler to use: 
  - doesn’t require a message queue service, 
  - doesn’t require changing the binary to link special libraries, the container just needs to read an environment variable storing the index
  - less prone to race conditions since pods have pre-assigned work items identified by the index.
  - Makes it easier to support MPI-type workloads: index 0 serves as the leader and the rest as the workers

The work-queue and array job models complement each other. Work-queue will be more efficient to use for workloads with many small work items, but for other types of workloads array job should be significantly easier to use. 

/sig apps

**Comment by ahg-g** [comment]
Related issues/PRs:

- https://github.com/kubernetes/community/issues/458
- https://github.com/kubernetes/kubernetes/issues/14186
- https://github.com/kubernetes/kubernetes/issues/14188
- https://github.com/kubernetes/kubernetes/pull/66105

**Comment by alculquicondor** [comment]
cc  @soltysh

**Comment by ahg-g** [comment]
@kubernetes/sig-apps-proposals

**Comment by alculquicondor** [comment]
Design from erictune still available here https://github.com/kubernetes/community/blob/master/contributors/design-proposals/apps/indexed-job.md

AFAIK, it was never ported to the enhancements repo
