### ISSUE TITLE
error: no objects passed to create

### ISSUE THREAD

**Issue by Aashrutisingh** [kubernetes/kubernetes#97160]
Was trying create an argo dag which shows `error: no objects passed to create  `while running the job. What can be the possible issue ?
PS: My parameters are in place also checked the apiVersion everything is in order 
/sig apiserver

**Comment by neolit123** [comment]
hi, please try the support channels for general questions:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
thanks
