### ISSUE TITLE
list events --all-namespaces not hit apiserver cache and return by paged

### ISSUE THREAD

**Issue by yuanhuaiwang** [kubernetes/kubernetes#97161]
**What happened**:
when i get events in all-namespaces , i found the result is paged and not hit apiserver cache
kubectl get events --all-namespaces --v=6
>
I1209 21:48:36.424972   23288 loader.go:359] Config loaded from file /root/.kube/config
I1209 21:48:36.455227   23288 round_trippers.go:438] GET https://xx8:6443/api/v1/events?limit=500 200 OK in 18 milliseconds
I1209 21:48:36.479700   23288 round_trippers.go:438] GET https://xx:6443/api/v1/events?continue=eyJ2IjoibWV0YS5rOHMuaW8vdjEiLCJydiI6NzU4ODczNzg5LCJzdGFydCI6ImRlZmF1bHQvdHN0NC10Y2tub2RlLWhvbGxvdy0xLjE2NGYwZjhmMDZjNTVjY2NcdTAwMDAifQ&limit=500 200 OK in 12 milliseconds
I1209 21:48:36.502572   23288 round_trippers.go:438] GET https://xx:6443/api/v1/events?continue=eyJ2IjoibWV0YS5rOHMuaW8vdjEiLCJydiI6NzU4ODczNzg5LCJzdGFydCI6ImRlZmF1bHQvdHN0NC10Y2tub2RlLWhvbGxvdy0xMDEwLjE2NGYwZWE1MzU4M2ZlMzhcdTAwMDAifQ&limit=500 200 OK in 12 milliseconds
I1209 21:48:36.526364   23288 round_trippers.go:438] GET https://xx:6443/api/v1/events?continue=eyJ2IjoibWV0YS5rOHMuaW8vdjEiLCJydiI6NzU4ODczNzg5LCJzdGFydCI6ImRlZmF1bHQvdHN0NC10Y2tub2RlLWhvbGxvdy0xMDIxLjE2NGYxMDcwZWQyMTYwZmFcdTAwMDAifQ&limit=500 200 OK in 13 milliseconds
>

**What you expected to happen**:
list evnets in a signle, not paged, so list all events in all-namespaces shuld be hit apiserver cache
**How to reproduce it (as minimally and precisely as possible)**:
kubectl get events --all-namespaces --v=6
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14

**Comment by yuanhuaiwang** [comment]
@wojtek-t @liggitt  please take a look , thanks a lot

**Comment by wojtek-t** [comment]
kubectl by design is listing from etcd - this is working as intended.

**Comment by liggitt** [comment]
Agreed, this is working as intended

**Comment by yuanhuaiwang** [comment]
but why list from a signle  namespace is not paged, while list from all-namespaces is paged
