### ISSUE TITLE
Out of order tags across active branches are causing tests to fail

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#97178]
_Note: this is the same issue we encountered in https://github.com/kubernetes/kubernetes/issues/86182._

For the `v1.20.0` release, as well as the subsequent patch releases for `v1.17.15` / `v1.18.13` / `v1.19.5`, the release version was tagged either on the same or a later commit than the `rc.0` tag, causing subsequent builds to fail the version regex check in `get-kube.sh`. As summarized in @justaugustus [email to k-dev](https://groups.google.com/g/kubernetes-dev/c/angCw-zHejE/discussion) the last time this happened:

> We use a combination of git describe and regexes (of course) to determine the tag and whether or not the tag is a CI tag. As the tags landed on the same commit, our git describe was ambiguous and picked up something in the form of v1.y.z-<number-of-commits-past-tag>+<commit-ish>, which makes our CI version regex unhappy.

This will likely need to be solved by manually tagging new versions. This issue thread will be updated with progress towards resolution.

An example test failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sbeta-default/1336844198506139648

_Very long_ slack thread from last time this happened with rationale behind doing manual tag and push: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1576268807016400

/cc @kubernetes/release-managers 
/assign
/assign @justaugustus 
/priority critical-urgent

**Comment by hasheddan** [comment]
Was able to find root cause with @puerco here. If we look at the v1.20.0 [stage logs](https://console.cloud.google.com/cloud-build/builds/427a26e6-5056-4288-933e-c620b36dd15e?project=kubernetes-release-test):

```
Step #2: INFO[2020-12-08T17:50:19Z] Tagging repository                            step=6/9
Step #2: INFO[2020-12-08T17:50:19Z] Preparing version v1.20.0                    
Step #2: INFO[2020-12-08T17:50:19Z] Checking out commit af46c47ce925f4           
Step #2: INFO[2020-12-08T17:50:19Z] Tagging version v1.20.0                      
Step #2: INFO[2020-12-08T17:50:19Z] Preparing version v1.20.1-rc.0               
Step #2: INFO[2020-12-08T17:50:19Z] Checking out commit af46c47ce925f4           
Step #2: INFO[2020-12-08T17:50:19Z] Tagging version v1.20.1-rc.0 
```

We are skipping the logic to create the empty commit:

https://github.com/kubernetes/release/blob/46bf0f9c5aadf60abaac0e252611dbc6d8514958/pkg/anago/stage.go#L408

```
		if strings.HasPrefix(branch, "release-") {
			logrus.Infof("Creating empty release commit for tag %s", version)
			if err := d.impl.CommitEmpty(
				repo,
				fmt.Sprintf("Release commit for Kubernetes %s", version),
			); err != nil {
				return errors.Wrap(err, "create empty release commit")
			}
		}
```

Due to the fact that we have [checked out a commit](https://github.com/kubernetes/release/blob/46bf0f9c5aadf60abaac0e252611dbc6d8514958/pkg/anago/stage.go#L367) and are in detached HEAD and not on a branch.

**Comment by brandond** [comment]
I had pointed this out after 1.20 but before the rest of today's releases, was there a better way I could have called attention to it?
https://kubernetes.slack.com/archives/C2C40FMNF/p1607459733061600

**Comment by puerco** [comment]
Sorry for missing it @brandond . Speaking personally, I think it was right to surface the issue to the channel, only until @tpepper brought your message again today for discussion I noticed it :( 

If you ever feel a notice like this gets lost in the chatter, please feel free to ping me directly as on other occasions. Thank you and apologies again :)

**Comment by justaugustus** [comment]
Sorry for missing your note, @brandond!

A little contrary to what @puerco said, to make sure something doesn't get lost in Slack, please first file a bug in either kubernetes/kubernetes or kubernetes/release.

After that, the Release Managers group (which works on Release Engineering issues like this) can be contacted as follows: https://github.com/kubernetes/sig-release/blob/master/release-managers.md#contact

**Comment by Nuru** [comment]
FWIW, my check of `kubectl` suggests that 1.18.13 and 1.19.5 were released properly, and this bug only affects 1.17.15 and 1.20.0

**Comment by Sh4d1** [comment]
Hum, not sure it is linked but:
```
docker run -it k8s.gcr.io/kube-apiserver:v1.17.15 kube-apiserver --version
Unable to find image 'k8s.gcr.io/kube-apiserver:v1.17.15' locally
v1.17.15: Pulling from kube-apiserver
4ba180b702c8: Already exists
6ee365b570ec: Pull complete
Digest: sha256:608ecba244ef7ee997b1384fc8840c057954dabd0c91168696206b696073a07d
Status: Downloaded newer image for k8s.gcr.io/kube-apiserver:v1.17.15
Kubernetes v1.17.16-rc.0
```

**Comment by jackfrancis** [comment]
Hi folks, do we know if we're going to cut an alternate build for 1.17.15? Or just skip it and go to 1.17.6?

**Comment by hasheddan** [comment]
@jackfrancis the plan right now is to roll forward to the next patch release

**Comment by kfox1111** [comment]
Since this has happened before, could a unit test of some kind be added to check the output of the built kubectl version before pushing any artifacts?

**Comment by liggitt** [comment]
has this been resolved to the point where the priority can be dropped?

**Comment by justaugustus** [comment]
> has this been resolved to the point where the priority can be dropped?

Yep! Opened a separate issue to track @kfox1111's request: https://github.com/kubernetes/release/issues/1898
/close
