### ISSUE TITLE
How to prevent potential leaked goroutines in ProxyServer

### ISSUE THREAD

**Issue by lzhfromustc** [kubernetes/kubernetes#97181]
There are two places where we just block a goroutine and never let it proceed again:

https://github.com/kubernetes/kubernetes/blob/ccd29ea264535fa2ef36cf4dfb004fed99c99fbf/cmd/kube-proxy/app/server.go#L586-L606

https://github.com/kubernetes/kubernetes/blob/ccd29ea264535fa2ef36cf4dfb004fed99c99fbf/cmd/kube-proxy/app/server.go#L630-L643

This might bring unnecessary overhead to the runtime and memory. Could we just kill the two goroutines? Like calling runtime.Goexit() to kill the current goroutine without side effects.

```Go
--- blockCh := make(chan error)
--- <-blockCh
+++ runtime.Goexit()
```

**Comment by thockin** [comment]
Both of those are in the "hardfail" path and will exit() the whole process imminently.  In the non-hardfail, we just log and exit the goroutine.

Working as intended, I think.

**Comment by lzhfromustc** [comment]
Hi. I see there is no need to change anything and will close the issue later. 
I am still really curious about why we block the goroutines here, instead of just return or kill the goroutine? Is there anything special to keep a goroutine blocked forever? This might update my knowledge of Golang
