### ISSUE TITLE
pod access apiserver through http

### ISSUE THREAD

**Issue by qiyuxin** [kubernetes/kubernetes#97189]
kubernetes cluster use insecure port  8080  to provide service，and It is successful to access the api server through http on the cluster node，but Containers started by kubelet access apiserver through https protocol，so it failed.
What do I need to do to make pod access apiserver through http?

kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
kubeconfig  for kubelet:
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: http://10.172.X.X:8080
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: ""
  name: system:node:kube-master
current-context: system:node:kube-master
kind: Config
preferences: {}
users: []

**Comment by neolit123** [comment]
> Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", 

this version has not been in support for a very long time. please upgrade to 1.18+.
for general questions try the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
