### ISSUE TITLE
We need formmatted the result of exec the command of "kubectl get pod $POD_NAME -o yaml" 

### ISSUE THREAD

**Issue by haiwfu** [kubernetes/kubernetes#97186]
We need formmatted the result of exec the command of "kubectl get pod $POD_NAME -o yaml"

**Comment by haiwfu** [comment]
Usually, the first we need show the pod name in the first line of spec section.

**Comment by pacoxu** [comment]
The YAML spec clearly says that the key order within a mapping is a "representation detail" that cannot be relied on.
https://stackoverflow.com/a/13299006/1926952

To get pod name directly
- kubectl get -o template pod  nginx-deployment-6ddf7bdf96-k4tbv --template={{.metadata.name}}
- kubectl get pod  nginx-deployment-6ddf7bdf96-k4tbv  -o  jsonpath={.metadata.name}

You may have to do your specified representation on the pod yaml. (change key order, etc.)
