### ISSUE TITLE
The Calico running failed

### ISSUE THREAD

**Issue by yangjinlogic** [kubernetes/kubernetes#97185]
I have a Kubernetes cluster deploy in Openstack ,the calico ip is belong to Openstack virtual network,such as 192.168.0.87,everything look perfect,but now I add a physical machine in the cluster,the calico ip belong to LAN,such as 172.16.2.110 ,the caclio cant running ,it show "Liveness probe failed: calico/node is not ready: Felix is not live: Get http://localhost:9099/liveness: dial tcp 127.0.0.1:9099: connect: connection refused"

**Comment by pacoxu** [comment]
please log a ticket in the [Calico issue tracker](https://github.com/projectcalico/calico/issues).
if the Calico maintainers think this is a bug in core k8s, please open a new issue here with the feedback from them and reproduction steps.

You read calico-node container logs for further investigation.

/kind support
/close

thanks
