### ISSUE TITLE
About CNTT tests，I want to know which test cases in k8s correspond to these use cases？

### ISSUE THREAD

**Issue by beiying-6282** [kubernetes/kubernetes#97195]
**Which jobs are flaking**:  CNTT tests  

**Which test(s) are flaking**:  Testsuit：cnf  cnf_conformance

**Testgrid link**:

**Reason for failure**:    I want to know which test cases in k8s correspond to these use cases？

- functest_kubernetes.cnf_conformance.conformance - INFO - |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | --
+-------------------------------------------------------------+----------------+ |   |   |   |   |   |   |   |  
\|                             NAME                            \|     STATUS     \| |   |   |   |   |   |   |   |  
+-------------------------------------------------------------+----------------+ |   |   |   |   |   |   |   |  
\|                          privileged                         \|     passed     \| |   |   |   |   |   |   |   |  
\|                      increase_capacity                      \|     failed     \| |   |   |   |   |   |   |   |  
\|                      decrease_capacity                      \|     failed     \| |   |   |   |   |   |   |   |  
\|                         ip_addresses                        \|     passed     \| |   |   |   |   |   |   |   |  
\|     hardcoded_ip_addresses_in_k8s_runtime_configuration     \|     passed     \| |   |   |   |   |   |   |   |  
\|                     install_script_helm                     \|     passed     \| |   |   |   |   |   |   |   |  
\|                       helm_chart_valid                      \|     failed     \| |   |   |   |   |   |   |   |  
\|                     helm_chart_published                    \|     failed     \| |   |   |   |   |   |   |   |  
\|                         helm_deploy                         \|     failed     \| |   |   |   |   |   |   |   |  
\|                   reasonable_startup_time                   \|     failed     \| |   |   |   |   |   |   |   |  
+-------------------------------------------------------------+----------------+ |   |   |   |   |   |   |   |  

**Anything else we need to know**:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

**Comment by BenTheElder** [comment]
I don't know what CNTT tests are but that doesn't sound like anything we own upstream. `helm_chart_valid` is also not something we do in any upstream tests.

https://cntt-n.github.io/CNTT/ appears to be something third party, please file an issue with them?

Alternatively if you're looking for upstream tests related to this, here's the answer:

- we don't test helm, helm is not part of kubernetes
- we have thousands of test cases upstream, it's not practical to discuss them all, if you wish to run them I recommend starting with the Kubernetes conformance tests, which have lots of documentation
