### ISSUE TITLE
Add per-priorityclass scheduling metrics

### ISSUE THREAD

**Issue by yuanchen8911** [kubernetes/kubernetes#97208]
**What would you like to be added**:

Add  per priority-class scheduling metrics, specifically per-priority PodSchedulingDuration

**Why is this needed**:

In may cases,  users want to provide guarantees or SLOs for pods in top priorities only. The current overall scheduling latency of  all pods  is insufficient. Per-priorityclass performance metrics would be useful.

**Comment by alculquicondor** [comment]
In general, this is achieved through metric labels. However, since priority classes can be arbitrary, there might be performance concerns.

**Comment by ahg-g** [comment]
I considered this before, as Aldo mentioned in theory pod priority can be any int number (bounded by some large range). However, in practice, the number of classes in a cluster should be really limited. @logicalhan wdyt? is there a best practice for this use case?

**Comment by yuanchen8911** [comment]
We currently have 6 priority classes and want to define SLOs for pods with top 2 priority classes.

**Comment by adtac** [comment]
exponential bucketing {[0, 1), [1, 2), [2, 4), [4, 8), ...} would limit the cardinality of the label to a handful (what base to use is debatable). I don't think anyone would want to meaningfully differentiate between priority 995 and 996, for example.

**Comment by alculquicondor** [comment]
Priority can be negative as well. Not sure if the bucketing is confusing though.

**Comment by ahg-g** [comment]
> exponential bucketing {[0, 1), [1, 2), [2, 4), [4, 8), ...} would limit the cardinality of the label to a handful (what base to use is debatable). I don't think anyone would want to meaningfully differentiate between priority 995 and 996, for example.

The actual number doesn't matter, what matters is the rank (whether by 1 or by a 1000), users usually create few priority levels, and they may well create them differentiated by 1. So I don't think bucketing makes sense at all.

**Comment by yuanchen8911** [comment]
> > exponential bucketing {[0, 1), [1, 2), [2, 4), [4, 8), ...} would limit the cardinality of the label to a handful (what base to use is debatable). I don't think anyone would want to meaningfully differentiate between priority 995 and 996, for example.
> 
> The actual number doesn't matter, what matters is the rank (whether by 1 or by a 1000), users usually create few priority levels, and they may well create them differentiated by 1. So I don't think bucketing makes sense at all.

It seems `priority_class` label is created on demand.  If you have 3 priority classes with values of 1000, 2000 and 3000 and only three priority_class labels will be created. So I don't think it would be an issue. 

We have a prototype implementation. Per the discussion in #97983, we added a new metric with priority_class label instead of changing the existing one.   The implementation is straightforward: create a new` HistogramVec` metric and update  its value with the priority_class in schedulerOne. 

1. Create a `HistogramVec` metric in `pkg/scheduler/metrics/metrics.go`
   
```
    //  e2e scheduling latency with priority_class label
    E2eSchedulingLatencyWithPriorityClass = metrics.NewHistogramVec(
        &metrics.HistogramOpts{
            Subsystem:      SchedulerSubsystem,
            Name:           "e2e_scheduling_duration_with_priority_class_seconds",
            Help:           "Per priority class e2e scheduling latency in seconds (scheduling algorithm + binding)",
            Buckets:        metrics.ExponentialBuckets(0.001, 2, 15),
            StabilityLevel: metrics.ALPHA,
        },
        []string{"priority_class"})
```
   2. Update the metric (scheduleOne in `kubernetes/pkg/scheduler/scheduler.go`)
```
metrics.E2eSchedulingLatencyWithPriorityClass.WithLabelValues(pod.Spec.PriorityClassName).Observe( metrics.SinceInSeconds(start))
```

We don't think the number of priority classes would be issues. 

1. There are typically a predefined and small number of priority classes in production environments. 
2. A bucket for a new priority_class will be automatically created on demand.  

 If the solution is reasonable, we'd like to file a PR to add two new metrics with priority_class information. 
- `E2eSchedulingLatencyWithPriorityClass` 
- `PodSchedulingLatencyWithPriorityClass`

Thanks!

**Comment by ahg-g** [comment]
I agree that typically a cluster includes few classes, but you can never be too cautious when thinking about control plane reliability and resilience. 

Here is one suggestion to avoid high cardinality in clusters with thousands of priority classes: in component config we allow defining the set of priorities that the metrics will be broken down into. We set a reasonable limit, like 20. We add those to the following set of default priorities that we always track: 0 (default), `system-critical-priority`, `node-critical-priority` and other (all other priorities not in the default set nor in the set defined in component config). 

@wojtek-t what do you think? are we being too paranoid :)?

**Comment by logicalhan** [comment]
> I considered this before, as Aldo mentioned in theory pod priority can be any int number (bounded by some large range). However, in practice, the number of classes in a cluster should be really limited. @logicalhan wdyt? is there a best practice for this use case?

Two ideas:

You can bound it in the implementation directly while setting values. Instead of setting the pod priority directly, you can parse it and store 10+ (for instance) for all priorities 10 and up. 

Alternatively, you can use a histogram and use pod priorities buckets.

**Comment by yuanchen8911** [comment]
> I agree that typically a cluster includes few priority classes, but you can never be too cautious when thinking about control plane reliability and resilience.
> 
> Here is one suggestion to avoid high cardinality in clusters with thousands of priority classes: in component config we allow defining the set of priorities that the metrics will be broken down into. We set a reasonable limit, like 20. We add those to the following set of default priorities that we always track: 0 (default), `system-critical-priority`, `node-critical-priority` and other (all other priorities not in the default set nor in the set defined in component config).
> 
Yes, it makes sense to limit the cardinality.  As suggested above, only a predefined set of priority-classes will be monitored with priority_class label or we can simply limit the maximum number of priority_class labels. The latter would be more flexible. 

BTW, not a Prometheus expert. How to get the number of existing labels/values of a Prometheus vector metric?  Thanks.

**Comment by ahg-g** [comment]
doing dynamically is more flexible, but will lead to nondeterministic behavior in clusters with large number of priorities, the set of priorities tracked will depend on which pods get scheduled first.

**Comment by yuanchen8911** [comment]
agree! @xujyan also pointed out "users can dynamically create and delete PriorityClass and metrics should vary moment by moment."  It would be harder to handle it unless the scheduler explicitly tracks and processes these events.

**Comment by yuanchen8911** [comment]
So I think we agree using a pre-defined set of priority classes makes more sense?

**Comment by ahg-g** [comment]
I am ok with that, @alculquicondor @Huang-Wei wdyt?

**Comment by alculquicondor** [comment]
agree, limiting to around 20

**Comment by Huang-Wei** [comment]
LGTM, and make some sane defaults (like 0 and system-level priorities class values).

Are we going to expose this option in KubeSchedulerConfiguration as a new field? (I don't think a pluginArgs would fit)

**Comment by ahg-g** [comment]
yeah, it would be a global CC parameter.

**Comment by logicalhan** [comment]
Is this a metric that people will (one day) possibly want to create an SLO against?

**Comment by ahg-g** [comment]
yes, possibly.

**Comment by logicalhan** [comment]
> yes, possibly.

We should be extremely diligent about the labels and label-values then.. is this a completely new metric?

**Comment by ahg-g** [comment]
yes, we will create a new metric and deprecate the old ones.

**Comment by yuanchen8911** [comment]
Thanks, folks! I'll submit a PR.

**Comment by ahg-g** [comment]
@logicalhan pointed me to https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2305-metrics-cardinality-enforcement

I guess this KEP makes the implementation of what we are proposing easier, but it is achieving the same semantics.

**Comment by yuanchen8911** [comment]
> @logicalhan pointed me to https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2305-metrics-cardinality-enforcement
> 
> I guess this KEP makes the implementation of what we are proposing easier, but it is achieving the same semantics.

Thanks, @logicalhan , @ahg-g. With the cardinality support, we can simply add a list of priority classes to the allowlist!

**Comment by Huang-Wei** [comment]
> I guess this KEP makes the implementation of what we are proposing easier, but it is achieving the same semantics.

+1. sig-instrumentation has spot it to be a common requirement :)

@logicalhan Is this KEP already implemented? If so, could you share some pointers showcasing how it's used? so that we can use this approach instead of "hack"ing the implementation using scheduler configuration parameters.

**Comment by logicalhan** [comment]
/cc @YoyinZyc 

> @logicalhan Is this KEP already implemented? If so, could you share some pointers showcasing how it's used? so that we can use this approach instead of "hack"ing the implementation using scheduler configuration parameters. 

It's not implemented yet, we're building out the alpha implementation for 1.21 which will actually only allow us to configure this via CLI flags. Tentatively, we're planning on supporting loading this from a file (i.e. component-config) for the beta release. 

This use-case is actually not exactly what we had in mind when we decided on this feature, which was primarily motivated by reliability issues caused by unbounded metric dimensions. But thinking about this use-case has been helpful for me in thinking more specifically on mapping patterns (the negative priorities is an interesting one). 

For now, I'd actually go ahead and use the priorities in the label values by default, if they are bounded in a practical sense (since that means the unboundedness shouldn't cause issues). Then we should sync between SIGs to get the API worked out so that you can specify what you want to target in your component config.

**Comment by yuanchen8911** [comment]
"_which was primarily motivated by reliability issues caused by unbounded metric dimensions_.",  I think that's exactly what we are concerned and trying to solve. We want to add priority_class label to a few scheduling metrics, but we want to avoid generating too many labels when a user (intentionally or by mistake) creates a large number of priority classes. Dynamism is another issue. `Allowlist `described in the KEP will help solve the problem.

**Comment by yuanchen8911** [comment]
Shall we just go ahead and implement a simple allowList for priorityclass in scheduler and update it when the carnality enforcement feature is available later? @ahg-g  @Huang-Wei ?

**Comment by logicalhan** [comment]
> We'd like to add priority_class label to a few scheduling metrics, but we want to avoid generating too many labels when a user (intentionally or by mistake) creates a large number of priority classes. 

We have another feature in progress which can also help with that (https://github.com/kubernetes/kubernetes/issues/98381) but it basically shunts off the entire metric. 

I'd say, if the number of priorities is practically bounded, then I would forgo hand-grouping them and wait for the instrumentation feature since it means less work on your side, since the off-switch allows you to address reliability issues around the metric in the case that it does go berserk.

**Comment by Huang-Wei** [comment]
@logicalhan 's suggestion sounds promising to me, so we don't need to add/remove particular args back and forth.

**Comment by yuanchen8911** [comment]
Sounds good, please keep us updated,  @logicalhan Thanks!

**Comment by alculquicondor** [comment]
#98381 does not seem very useful when managing a fleet, where you don't know which clusters will be problematic.

Rather, have you considered extending [Metrics cardinality enforcement](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2305-metrics-cardinality-enforcement) to do custom mapping instead of just changing the label to "unknown"?

**Comment by logicalhan** [comment]
> Rather, have you considered extending [Metrics cardinality enforcement](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2305-metrics-cardinality-enforcement) to do custom mapping instead of just changing the label to "unknown"?

Yeah the custom mapping was the thing I was alluding to when I said:

> This use-case is actually not exactly what we had in mind when we decided on this feature...

Specifically because it sounded like this issue was describing controlling inputs into multiple buckets.
