### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by aliceroy** [kubernetes/kubernetes#97218]
**What happened**:
Dec  9 17:22:01 k8smaster1 kubelet: I1209 17:22:01.925640    7591 kubelet.go:1821] Starting kubelet main sync loop.
Dec  9 17:22:01 k8smaster1 kubelet: E1209 17:22:01.925746    7591 kubelet.go:1845] skipping pod synchronization - [container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet to be successful]
Dec  9 17:22:01 k8smaster1 kubelet: E1209 17:22:01.926611    7591 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.RuntimeClass: Get "https://apiserver.cluster.local:6443/apis/node.k8s.io/v1beta1/runtimeclasses?limit=500&resourceVersion=0": dial tcp 10.161.30.22:6443: connect: connection refused
Dec  9 17:22:01 k8smaster1 kubelet: E1209 17:22:01.927232    7591 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.RuntimeClass: Get "https://apiserver.cluster.local:6443/apis/node.k8s.io/v1beta1/runtimeclasses?limit=500&resourceVersion=0": dial tcp 10.161.30.22:6443: connect: connection refused
Dec  9 17:22:01 k8smaster1 kubelet: W1209 17:22:01.951145    7591 docker_container.go:353] ignore error image "sha256:3c08ed554c533a9c982c1d5d6fdc5007c44b5fdfa4d58affbed57d6f4861e542" not found while inspecting docker container "c3e94e6469ce16e2417fdb98bee688bbd1a6a4c2a87ceab157ffc358ee40b956": no such image: "sha256:3c08ed554c533a9c982c1d5d6fdc5007c44b5fdfa4d58affbed57d6f4861e542"
Dec  9 17:22:01 k8smaster1 kubelet: panic: runtime error: invalid memory address or nil pointer dereference
Dec  9 17:22:01 k8smaster1 kubelet: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x319cff5]
Dec  9 17:22:01 k8smaster1 kubelet: goroutine 303 [running]:
Dec  9 17:22:01 k8smaster1 kubelet: k8s.io/kubernetes/pkg/kubelet/dockershim.(*dockerService).ContainerStatus(0xc000d7e000, 0x4957700, 0xc000af04e0, 0xc001507040, 0xc000d7e000, 0xc000af04e0, 0xc0012d5b78)
Dec  9 17:22:01 k8smaster1 kubelet: /home/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_container.go:418 +0x6f5
Dec  9 17:22:01 k8smaster1 kubelet: k8s.io/kubernetes/vendor/k8s.io/cri-api/pkg/apis/runtime/v1alpha2._RuntimeService_ContainerStatus_Handler(0x41193a0, 0xc000d7e000, 0x4957700, 0xc000af04e0, 0xc0006d81e0, 0x0, 0x4957700, 0xc000af04e0, 0xc0008103c0, 0x42)
Dec  9 17:22:01 k8smaster1 kubelet: /home/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.pb.go:7882 +0x217
Dec  9 17:22:01 k8smaster1 kubelet: k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000f01200, 0x49abdc0, 0xc000dd8000, 0xc00167e100, 0xc001162bd0, 0x6dfe6c8, 0x0, 0x0, 0x0)
Dec  9 17:22:01 k8smaster1 kubelet: /home/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/server.go:1024 +0x501
Dec  9 17:22:01 k8smaster1 kubelet: k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000f01200, 0x49abdc0, 0xc000dd8000, 0xc00167e100, 0x0)
Dec  9 17:22:01 k8smaster1 kubelet: /home/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/server.go:1313 +0xd3d
Dec  9 17:22:01 k8smaster1 kubelet: k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000592460, 0xc000f01200, 0x49abdc0, 0xc000dd8000, 0xc00167e100)
Dec  9 17:22:01 k8smaster1 kubelet: /home/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/server.go:722 +0xa1
Dec  9 17:22:01 k8smaster1 kubelet: created by k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
Dec  9 17:22:01 k8smaster1 kubelet: /home/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/server.go:720 +0xa1
Dec  9 17:22:01 k8smaster1 systemd: kubelet.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Dec  9 17:22:01 k8smaster1 systemd: Unit kubelet.service entered failed state.
Dec  9 17:22:01 k8smaster1 systemd: kubelet.service failed.
Dec  9 17:22:12 k8smaster1 systemd: kubelet.service holdoff time over, scheduling restart.
Dec  9 17:22:12 k8smaster1 systemd: Stopped kubelet: The Kubernetes Node Agent.
Dec  9 17:22:12 k8smaster1 systemd: Starting kubelet: The Kubernetes Node Agent...

**What you expected to happen**:
Kubelet is up and working
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
The first installation of k8s failed. The above is the error log. It will be successful if you try again
**Environment**:
Kubernetes version: v1.18.0
Cloud provider or hardware configuration: Bare Metal
CentOS Linux release 7.7.1908 (Core)
kernel: 3.10.0-1062.el7.x86_64
Install tools: sealos 3.3.8
Network plugin and version: kube-router v0.4.0
Others:
Docker version 18.09.5, build e8ff056

**Comment by pacoxu** [comment]
This is fixed in #88348

**Comment by neolit123** [comment]
```
/close
```

actually please re-open if needed and if this has not been backported to 1.18.

**Comment by aliceroy** [comment]
Reopen
@pacoxu 
@neolit123 
This problem will occur in the first installation of k8s, and the re installation is successful. When the above problem occurs, the image corresponding to the query exists, which is different from the problem in  #88348 , and should not be the same problem

**Comment by aliceroy** [comment]
Reopen issue #97218 @k8s-ci-robot

**Comment by pacoxu** [comment]
I suggest you to try v1.18.13(latest version of 1.18) or 1.19 to whether it is reproducible.

The log you provided is the same as https://github.com/kubernetes/kubernetes/issues/84214#issuecomment-588421448
```
Dec 9 17:22:01 k8smaster1 kubelet: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x319cff5]
Dec 9 17:22:01 k8smaster1 kubelet: goroutine 303 [running]:
Dec 9 17:22:01 k8smaster1 kubelet: k8s.io/kubernetes/pkg/kubelet/dockershim.(*dockerService).ContainerStatus(0xc000d7e000, 0x4957700, 0xc000af04e0, 0xc001507040, 0xc000d7e000, 0xc000af04e0, 0xc0012d5b78)
``` 

As this error message shows, please check your disk `df -h` and images `docker images` on the server.

**Comment by ehashman** [comment]
@neolit123 this was backported to 1.18: https://github.com/kubernetes/kubernetes/pull/89536

**Comment by ehashman** [comment]
@aliceroy as @pacoxu suggested can you please upgrade to 1.18.3+ and confirm that does not fix the problem?

I'm going to close this as I believe the issue was fixed, there is just some confusion about the backport.

/close
