### ISSUE TITLE
kubernetes service failed to maintain session

### ISSUE THREAD

**Issue by JokerDevops** [kubernetes/kubernetes#97226]
**What happened**:

I set `sessionAffinity: ClientIP` , But he did not keep my session, when I log in to my application, he always prompts me to log in again.

**What you expected to happen**:

I want to log in to my application service normally. Way four through session authentication.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 
```

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

```
- Kernel (e.g. `uname -a`):
```
Linux node47 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
/sig network
(move to another sig if needed)

**Comment by mattfenwick** [comment]
hi @JokerDevops !  👋 

Can you provide details about how we can reproduce this behavior?

**Comment by aojea** [comment]
> I set `sessionAffinity: ClientIP` , But he did not keep my session, when I log in to my application, he always prompts me to log in again.

this depends on the Services implementation, usually is kube-proxy but some CNI plugins replace kube-proxy.

@JokerDevops please provide more details about your environment, CNI plugin and if you are using kube-proxy or other implementation for Kubernetes Services

**Comment by thockin** [comment]
When you say "log in" do you mean like an app-level username and password?  That's not what this does.  All this does is ensure that subsequent connections will go to the same backend.  It's still a new TCP session, so unless you have some sort of cookie or token built into your app protocol, you may still get treated as a new client.

Am I misunderstanding the report?

**Comment by thockin** [comment]
Hi, is there more we can do here, or shall we close this?
