### ISSUE TITLE
[Flaky test] [sig-network] Networking Granular Checks: Services should update nodePort: http

### ISSUE THREAD

**Issue by tosi3k** [kubernetes/kubernetes#97239]
**Which jobs are flaking**:
gce-master-scale-correctness

**Which test(s) are flaking**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1337366985960329216

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/networking.go:367
Dec 11 12:27:01.533: Error dialing http from node: failed to find expected endpoints, 
tries 130
Command curl -g -q -s --max-time 15 --connect-timeout 1 http://34.74.8.60:32080/hostName
retrieved map[netserver-0:{}]
expected map[]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113
```

/sig scalability
/sig network

**Comment by aojea** [comment]
it failed once, and we have a patch to improve the test
https://github.com/kubernetes/kubernetes/pull/97249

let's see how it evolves

**Comment by aojea** [comment]
@wojtek-t before going into the specific failures, the job is timing out multiple times 8/15 last runs,
can you PTAL?
https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness

**Comment by wojtek-t** [comment]
@aojea - it started timing out after merging this PR: https://github.com/kubernetes/kubernetes/pull/97345/

I'm fairly sure it's the reason of that.

Those are both networking tests - I'm just wondering if we want to revert it to prove or we want to keep them enabled to have more debugging info?

**Comment by aojea** [comment]
> @aojea - it started timing out after merging this PR: #97345
> 
> I'm fairly sure it's the reason of that.
> 
> Those are both networking tests - I'm just wondering if we want to revert it to prove or we want to keep them enabled to have more debugging info?

Let me check them, we had recently a similar issue with the network policy jobs ...

**Comment by aojea** [comment]
ups

**Comment by aojea** [comment]
There are taking more than 20 mins to run, this graph is really useful 
https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness&graph-metrics=test-duration-minutes&width=5

I´ve submitted https://github.com/kubernetes/kubernetes/pull/97839 to fix one of those, but as wojtek pointed out, the trigger is #97345 , and based on the graph

![image](https://user-images.githubusercontent.com/6450081/103996465-2c00de80-519a-11eb-9507-406dc83bff0c.png)

I will say it is caused by https://github.com/kubernetes/kubernetes/issues/93932

**Comment by aojea** [comment]
great, we have a green, let's see if it keeps up, but there are some test that still take more than 30 mins to run, maybe we should revisit some of them

**Comment by wojtek-t** [comment]
> great, we have a green, let's see if it keeps up, but there are some test that still take more than 30 mins to run, maybe we should revisit some of them

I think that is somewhat expected. If the test is programming LB for 5k-node cluster couple times (which is what some of these tests are doing), each of this operation can take couple minutes, which together sums up for half-an-hour +.

I'm not sure we can do much about it. And given the nature of scalability tests (things are expected to take longer in those very large tests), I think we're fine here (as long as they don't take hours to run - and it seems the longest take ~1h, which I'm fine for now]

WDYT?

**Comment by aojea** [comment]
> I'm not sure we can do much about it. And given the nature of scalability tests (things are expected to take longer in those very large tests), I think we're fine here (as long as they don't take hours to run - and it seems the longest take ~1h, which I'm fine for now]

I couldn´t dig too much into the tests, but I think that there are several places that test the connectivity iterating over each node, the guys that implemented the new network policy tests parallelised the probing using N workers, we can do the same, just reducing by 2 or 3 (40 mins -> 20 or13 mins) the time seems a big win

**Comment by wojtek-t** [comment]
> I couldn´t dig too much into the tests, but I think that there are several places that test the connectivity iterating over each node, the guys that implemented the new network policy tests parallelised the probing using N workers, we can do the same, just reducing by 2 or 3 (40 mins -> 20 or13 mins) the time seems a big win

If that's the case, then this definitely seems like a good suggestion. Can you point me to those?

**Comment by aojea** [comment]
I couldn´t spend time on this, so take it with a grain of salt, but this seems to be used in a lot of tests

https://github.com/kubernetes/kubernetes/blob/cb8ad64243d48d9a3c26b11b2e0945c098457282/test/e2e/framework/service/jig.go#L946-L979

and in `should only target nodes with endpoints` ~ 25 mins this seems related

https://github.com/kubernetes/kubernetes/blob/334b426a6be3c09b475ae8b481809c579435ad0f/test/e2e/network/service.go#L3114-L3119

I will try to dig more into this later this week

**Comment by wojtek-t** [comment]
This test seems fine for me. Basically this line makes the trick:
https://github.com/kubernetes/kubernetes/blob/334b426a6be3c09b475ae8b481809c579435ad0f/test/e2e/network/service.go#L3064

We're taking only 3 nodes and iterating over these 3 nodes. So that test shouldn't be proportional to cluster size.

What makes it long is that (re)programming load balancer on 5k-node cluster takes minutes...

**Comment by PriyankaH21** [comment]
Is this issue resolved? I saw another flaky test today -
**Triage:** https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=Networking%20Granular%20Checks%3A%20Services%20should%20update%20nodePort , 
**Spyglass:** https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1337366985960329216

**Comment by wojtek-t** [comment]
It's not resolved.

**Comment by aojea** [comment]
@wojtek-t this looks pretty green and running under 10 mins now
https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness&graph-metrics=test-duration-minutes&width=5&include-filter-by-regex=should%20update%20nodePort
should we close?

**Comment by wojtek-t** [comment]
Yeah - we can close. We can open a new one when we will observe flakes.
