### ISSUE TITLE
Confusing comment on DeltaFIFO

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#97248]
**What happened**:
The implementation of DeltaFIFO was generalized in #96797 to the point where there is no longer any restriction on producers.  But there remains a comment saying "single producer" and Reflector being the only intended producer, which suggests that there is some limit on functionality or support for other cases.

**What you expected to happen**:
I expected the comments to be updated with the code.

**How to reproduce it (as minimally and precisely as possible)**:
Read the source.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs
@jqmichael

**Comment by jqmichael** [comment]
Thanks @MikeSpreitzer!
