### ISSUE TITLE
GCE Serial Kube-DNS jobs are failing due to some [Disruptive] tests

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#97268]
**Which jobs are failing**:

https://testgrid.k8s.io/sig-network-gce#gci-gce-serial-kube-dns
https://testgrid.k8s.io/sig-network-gce#gci-gce-serial-kube-dns-nodecache

**Which test(s) are failing**:

some new [Disruptive] tests were added recently that seems to fail

**Since when has it been failing**:

It seems it started to fail 12/12

**Comment by aojea** [comment]
/sig network
ping @MrHohn @prameshj

**Comment by prameshj** [comment]
looks like these new tests never passed.

One of the failures is due to mount failing:

```
Dec 13 14:43:17.136: INFO: At 2020-12-13 14:38:12 +0000 UTC - event for pod-5ab2c50f-dc48-4cb7-9cbc-1ef72b71bf9f: {kubelet bootstrap-e2e-minion-group-drkj} FailedMapVolume: MapVolume.MapBlockVolume failed for volume "local-g2xs6" : blkUtil.MapDevice failed. devicePath: /tmp/local-driver-f3549306-3c79-4ed7-a12c-5ce476cbdecb-backend, globalMapPath:/var/lib/kubelet/plugins/kubernetes.io~local-volume/volumeDevices/local-g2xs6, podUID: 1ae28808-52fd-4ec8-9fa1-c7f4ac6020d9, bindMount: true: failed to bind mount devicePath: /tmp/local-driver-f3549306-3c79-4ed7-a12c-5ce476cbdecb-backend to linkPath /var/lib/kubelet/plugins/kubernetes.io~local-volume/volumeDevices/local-g2xs6/1ae28808-52fd-4ec8-9fa1-c7f4ac6020d9: mount failed: exit status 32
Mounting command: mount
```

These tests are failing in the gce-serial tab as well - https://testgrid.k8s.io/sig-network-gce#gci-gce-serial

Passing on to sig storage to help triage. We can skip those tests in our gce test config, if that is the recommendation.

**Comment by aojea** [comment]
> looks like these new tests never passed.

Those tests seems new, there is no previous history, maybe they were added recently ?

**Comment by prameshj** [comment]
Seems like the tests are now flaky due to connectivity issues:

```
I0107 12:19:59.408] Jan  7 12:19:59.397: INFO: Ignoring unexpected output wgetting endpoints of service 10.0.217.40: map[wget: download timed out:{}]
```

**Comment by aojea** [comment]
the disruptive tests are not flaking, there are other failures but I think this issue can be closed, I don't like to use this as a placeholder :)

Thanks @prameshj for looking into it
