### ISSUE TITLE
Scheduler: Do not take nil plugin status as success

### ISSUE THREAD

**Issue by gavinfish** [kubernetes/kubernetes#97267]
Currently a `Status` struct is also considered as success in scheduler framework. This is tricky and confused. Find a way to clean it up.

https://github.com/kubernetes/kubernetes/blob/87984d84d18c7816835e5efedebb17ed13aa2509/pkg/scheduler/framework/interface.go#L95-L104

/sig scheduling
/kind cleanup
/priority backlog

**Comment by ahg-g** [comment]
I don't understand the confusion here, a nil status is success.

**Comment by CKchen0726** [comment]
// Code returns code of the Status.
func (s *Status) Code() Code {
	if s == nil {
		return Success  **// NOTE: A nil Status is also considered as Success. I am not sure another status code will be better.**
	}
	return s.code
}

**Comment by gavinfish** [comment]
@ahg-g I think it is more clear to return a `framework.NewStatus(framework.Success)` whenever we need a success status. I know there are cases when we want to let both uninitialized  status and success status to pass, in such cases we check `status == nil || status.IsSuccess()` instead of taking `nil.IsSuccess()` as success. So that we can prevent anyone use use nil as success status when it is unnecessary.

**Comment by ahg-g** [comment]
In golang we treat nil error as success, framework.Status is following the same pattern.
