### ISSUE TITLE
Optimize the memory usage.

### ISSUE THREAD

**Issue by ximenzaoshi** [kubernetes/kubernetes#97262]
**What would you like to be added**:
- Pod managed by deployment can be stored in memory in a more memory friendly way. As all the pod specs are almost the same(except for the `Nodename` field?). We can share one copy in the memory, instead of thousands of it. And we can even store less information in etcd by the same way.
- Optimize the serialization. Most of the memory are consumed by serializations triggered by all kinds of requests. The client fetches all the information about the object from apiserver, but in most situations, the client only needs a few field about the object, and the apiserver has to serialize the whole object, which is both cpu-intensive and memory-intensive. Can we provide a more flexible API to provide only the information the client needs?

**Why is this needed**:
We have an 2000-node-cluster in our production environment. The apiserver consumes too much memory.  As the cluster grows much bigger, the situation can be much worse. We already scaled the apiserver number to 6, each was deloyed on a physical machine of 200GB memory. We want to find some way to optimize the memory usage instead of adding more machines.

**Comment by lavalamp** [comment]
> Pod managed by deployment can be stored in memory in a more memory friendly way. As all the pod specs are almost the same(except for the Nodename field?). We can share one copy in the memory, instead of thousands of it. And we can even store less information in etcd by the same way.

This is easy to say, but I can't think of a practical implementation. And note that the status is different for each pod, and UID, and ResourceVersion, and the timestamp(s), ....


> Optimize the serialization. Most of the memory are consumed by serializations triggered by all kinds of requests. The client fetches all the information about the object from apiserver, but in most situations, the client only needs a few field about the object, and the apiserver has to serialize the whole object, which is both cpu-intensive and memory-intensive. Can we provide a more flexible API to provide only the information the client needs?

Are your clients requesting the proto format? There's also a tabular output format. Serialization is already very optimized.

You may want to experiment with settings, like enabling / disabling the watch cache for various resources.


> We have an 2000-node-cluster in our production environment. The apiserver consumes too much memory. As the cluster grows much bigger, the situation can be much worse. We already scaled the apiserver number to 6, each was deloyed on a physical machine of 200GB memory.

You should not need 6x200GB machines to run 2000 nodes. How many pods and at what churn rate? Do you know what is driving the majority of your API requests?

How many etcd replicas are you running? note that adding additional replicas makes write latency slightly worse.

Have you tried enabling API Priority and Fairness? (beta in 1.20, alpha prior to that)

@wojtek-t do you know of good materials re: running big clusters?

/kind support

**Comment by ximenzaoshi** [comment]
@lavalamp 
Thanks for the reply. Let me try to explain my thoughts more clearly.

1. For the pod thing, my main idea is that pods can share some invariable fields, and these invariable fields are often have relatively big size, such as the `PodTemplate` part. And the env variables are often the biggest part in `PodTemplate`. I think these can be shared in some way. I haven't thought too much about the implementation. The optimization may be not worth it comparing the complexity brought to the code, but I think it is worthy to have  a try.
2. Maybe there is some misleading about the serialization thing I mentioned. What I really wanted is a more flexible Resource API. For example, when I list pods, I actually do not need all the fields about a pod, I only need the labels part and the status part. The less fields the server need to serialize, the less memory and cpu pressure the server may have I think. Or is there already a way to do things like this?

>You should not need 6x200GB machines to run 2000 nodes. How many pods and at what churn rate? 

We do have 6X200 GB machines and a five-node etcd cluster for now. We hava about 60,000 pods in our cluster. Deployments happen in almost every hour in our environment. 

>Do you know what is driving the majority of your API requests?

There are `List pods` and `List nodes` requests in the log. But we can not find where are these request comes from. `tcpdump` doesn't work as the communication is secure, and it seems that there is not enough memory for apiserver to run with `audit log` enabled. Do you have any suggestions? 

>Have you tried enabling API Priority and Fairness? (beta in 1.20, alpha prior to that)

I'm going to learn about this, thank you!

**Comment by wojtek-t** [comment]
> We do have 6X200 GB machines and a five-node etcd cluster for now. We hava about 60,000 pods in our cluster. Deployments happen in almost every hour in our environment.

You definitely shouldn't need that much.
We're more-or-less continuously running tests on 5000-node clusters with 150,000 pods. Which seem to be visibly more than what you have. And we are at small tens of GBs there.

> There are List pods and List nodes requests in the log. 

That might be potentially problematic. If you're listing a lot (especially from etcd) then you need to serialize/deserialize a lot of stuff, even if that is not eventually being returned to the user (due to selectors).

**Comment by Jeffwan** [comment]
@wojtek-t @lavalamp  Do you know if community talks about other storage like documentDB(I know kubernetes is totally on etcd now.)? Seem label selector, field selector can be mapped to DB level then. APIServer will become lightweight and won't have that many unnecessary serializations. I am not sure if watch/release is major blocker to move to that way.

**Comment by wojtek-t** [comment]
> . I am not sure if watch/release is major blocker to move to that way.

Yes - watch is must have. K8s depends on watch pretty much everywhere.

**Comment by lavalamp** [comment]
Yes it would be a major undertaking to change this.

We don't have any plans to work on this currently. The bottleneck is not thinking of the idea (e.g. as recorded above) it is (finding people to do the) designing and implementing / reviewing.

/close
