### ISSUE TITLE
Kubernetes packages.cloud.google.com repo sometimes returns 404

### ISSUE THREAD

**Issue by aporcupine** [kubernetes/kubernetes#97264]
**What happened**:

1. Add `deb https://apt.kubernetes.io/ kubernetes-xenial main` to /etc/apt/sources.list
2. Run an apt update
3. 1/2 of the time an error occurs showing a 404 from `https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-arm64/by-hash/SHA256/b7b1a18f5c904c827f404ea5d6be989d6132654e6e3854e398c266ed5fe1ad00`
4. Manually completing a curl of this URL results in either a list of packages, or a 404.

**What you expected to happen**:

URL not to 404 and apt update to succeed.

**How to reproduce it (as minimally and precisely as possible)**:

Keep making requests to https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-arm64/by-hash/SHA256/b7b1a18f5c904c827f404ea5d6be989d6132654e6e3854e398c266ed5fe1ad00

**Anything else we need to know?**:

I've attached the result of a verbose curl during a successful call and and an un-successful call:
[success.txt](https://github.com/kubernetes/kubernetes/files/5684496/success.txt)
[404.txt](https://github.com/kubernetes/kubernetes/files/5684497/404.txt)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20
- Cloud provider or hardware configuration: Bare Metal Ubuntu arm64
- OS (e.g: `cat /etc/os-release`): 
```
PRETTY_NAME="Debian GNU/Linux bullseye/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel (e.g. `uname -a`): Linux penguin 5.4.74-10576-gb6cc41974db3 #1 SMP PREEMPT Sun Nov 8 15:08:12 PST 2020 x86_64 GNU/Linux

- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): n/a
- Others:

**Comment by neolit123** [comment]
/sig release
this is google owned infra.
there was already an issue for this logged in kubernetes/release about the flakes but i cannot find it.

**Comment by saschagrunert** [comment]
Referenced this issue in an open Slack discussion since I see not much what we can do from a SIG Release perspective: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1612887586202400

**Comment by saschagrunert** [comment]
As discussed with the build admin, there is not much what we can do from our side since we do not host the packages directly. Can you please reopen if you encounter the issue again?

/close

**Comment by BenTheElder** [comment]
There's an ongoing effort to move this to community owned infrastructure where the project can have discretion over all aspects of the infra.

As it stand while my team at Google do perform builds and upload them to the existing host for the project, we don't own the host and it really nominally exists to host Google packages (like the GCP SDK) / isn't a product offering AIUI, we can pass along reports but I don't think there's a ton we can do here.

If we see widespread issues I will try harder to escalate, but in the meantime I'd like to continue focusing on unblocking community controlled infrastructure for the health of the project. We've been trying to eliminate anything that bottlenecks on us from that perspective (we don't mind doing it, but the project strongly prefers to have openly managed infra anyone can help with and audit, see: https://github.com/kubernetes/k8s.io)

**Comment by taxilian** [comment]
As a data point, I'm seeing this issue now; trying to resolve.

```
Get:4 https://packages.cloud.google.com/apt kubernetes-xenial InRelease [9,383 B]
Ign:6 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 Packages
Ign:6 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 Packages
Ign:6 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 Packages
Err:6 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 Packages
  404  Not Found [IP: 172.217.164.14 443]
Fetched 214 kB in 1s (206 kB/s)
Reading package lists... Done
E: Failed to fetch https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-amd64/by-hash/SHA256/6a386d103a1f74d6eb56422ee64a9d26a47f0125d87717beb1ba3c499b5b1ba4  404  Not Found [IP: 172.217.164.14 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by holdenk** [comment]
I've been running into this a bunch the past week.

**Comment by 5t33** [comment]
Also seeing this problem.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/release/issues/913, the project does not control this infrastructure and should be moving to community managed infrastructure in the future

**Comment by nmallar** [comment]
I saw the following today while executing sudo apt-add-repository "deb [http](https://apt.kubernetes.io/)[s](https://apt.kubernetes.io/)[://apt.kubernetes.io/](https://apt.kubernetes.io/) kubernetes-xenial main"

Hit:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:4 https://download.docker.com/linux/ubuntu focal InRelease
Ign:5 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
Err:6 https://packages.cloud.google.com/apt kubernetes-xenial Release
  404  Not Found [IP: 172.253.62.139 443]
Hit:7 http://security.ubuntu.com/ubuntu focal-security InRelease
Reading package lists... Done
E: The repository 'https://apt.kubernetes.io kubernetes-xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Any help on how to fix this ?

**Comment by AnilKumar107** [comment]
I am also facing same issue
Could someone please help on this

**Comment by tycol7** [comment]
Could this be the problem?

https://github.com/kubernetes/release/issues/3485

**Comment by BenTheElder** [comment]
Yes, this is no longer where the project hosts releases, there are more details in https://github.com/kubernetes/release/issues/3485 and there were announcements + a banner on kubernetes.io and again in the release announcement(s) https://kubernetes.io/blog/2023/12/13/kubernetes-v1-29-release/#legacy-linux-package-repositories

Please see the current TLDR in https://github.com/kubernetes/release/issues/3485

**Comment by flavian-anselmo** [comment]
facing the same problem

**Comment by flavian-anselmo** [comment]
> facing the same problem

https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/

**Comment by vikashmuktha** [comment]
@AnilKumar107 , @flavian-anselmo
Please follow official document 
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl
i think it works for you

**Comment by aak1247** [comment]
Same error here

**Comment by aak1247** [comment]
> @AnilKumar107 , @nmallar Please follow official document https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl i think it works for you

We might need older version

**Comment by krishna-wstf** [comment]
# Add the Kubernetes v1.29 repo
sudo apt install -y apt-transport-https ca-certificates curl
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | \
  sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /" | \
  sudo tee /etc/apt/sources.list.d/kubernetes.list > /dev/null

# Install kubelet, kubeadm, kubectl
sudo apt update
sudo apt install -y kubelet kubeadm kubectl
sudo apt-mark hold kubelet kubeadm kubectl
------------------
use this , work for me
-----------

**Comment by wandrey7** [comment]
> sudo apt-mark hold kubelet kubeadm kubectl

tks, it's working

**Comment by BenTheElder** [comment]
Note: https://kubernetes.io/releases

All currently supported releases have been on pkgs.k8s.io for some time now, see:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl

Debian also has some upstream packages again (not maintained by the Kubernetes project)
https://packages.debian.org/trixie/kubectl
