### ISSUE TITLE
Iptables creates reject entries in KUBE-SERVICES chain.

### ISSUE THREAD

**Issue by angelosanramon** [kubernetes/kubernetes#97260]
**What happened**:
Installed kubernetes-dashboard on a newly deployed kubernetes 1.19.4 cluster. The kubernetes-dashboard pod is stuck in a crashloopbackoff. A reject entry is getting created in iptables on KUBE-SERVICES chain. I get the following error:
```
[root@k8scp1 kubernetes]# KUBECONFIG=/etc/kubernetes/admin.conf kubectl get pods -n kubernetes-dashboard
NAME                                         READY   STATUS             RESTARTS   AGE
dashboard-metrics-scraper-79c5968bdc-cn4rk   1/1     Running            0          99s
kubernetes-dashboard-6f65cb5c64-28dbn        0/1     CrashLoopBackOff   3          99s
```
The kubernetes-dashboard pod logs shows:
```
[root@k8scp1 kubernetes]# KUBECONFIG=/etc/kubernetes/admin.conf kubectl logs kubernetes-dashboard-6f65cb5c64-28dbn -n kubernetes-dashboard
2020/12/12 07:59:36 Starting overwatch
2020/12/12 07:59:36 Using namespace: kubernetes-dashboard
2020/12/12 07:59:36 Using in-cluster config to connect to apiserver
2020/12/12 07:59:36 Using secret token for csrf signing
2020/12/12 07:59:36 Initializing csrf token from kubernetes-dashboard-csrf secret
panic: Get "https://10.32.0.1:443/api/v1/namespaces/kubernetes-dashboard/secrets/kubernetes-dashboard-csrf": dial tcp 10.32.0.1:443: connect: no route to host

goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/client/csrf.(*csrfTokenManager).init(0xc00000cf00)
	/home/runner/work/dashboard/dashboard/src/app/backend/client/csrf/manager.go:41 +0x413
github.com/kubernetes/dashboard/src/app/backend/client/csrf.NewCsrfTokenManager(...)
	/home/runner/work/dashboard/dashboard/src/app/backend/client/csrf/manager.go:66
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).initCSRFKey(0xc0004ed500)
	/home/runner/work/dashboard/dashboard/src/app/backend/client/manager.go:502 +0xc6
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).init(0xc0004ed500)
	/home/runner/work/dashboard/dashboard/src/app/backend/client/manager.go:470 +0x47
github.com/kubernetes/dashboard/src/app/backend/client.NewClientManager(...)
	/home/runner/work/dashboard/dashboard/src/app/backend/client/manager.go:551
main.main()
	/home/runner/work/dashboard/dashboard/src/app/backend/dashboard.go:105 +0x21c
```
iptables reject entries gets created after install:
```
[root@k8scp1 kubernetes]# iptables -L KUBE-SERVICES
Chain KUBE-SERVICES (3 references)
target     prot opt source               destination
REJECT     tcp  --  anywhere             10.41.157.72         /* kubernetes-dashboard/kubernetes-dashboard has no endpoints */ tcp dpt:https reject-with icmp-port-unreachable
```
**What you expected to happen**:
The kubernetes-dashboard pod should be in `Running` status.

**How to reproduce it (as minimally and precisely as possible)**:
Install kubernetes-dashboard by running `kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.1.0/aio/deploy/recommended.yaml`

**Anything else we need to know?**:
The kubernetes-dashboard is deployed to a cluster with Calico CNI version 3.17.0
 
**Environment**:
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: VirtualBox VMs
- OS (e.g: `cat /etc/os-release`): CentOS 8
- Kernel (e.g. `uname -a`): `Linux k8scp1.cluster.local 4.18.0-80.el8.x86_64 #1 SMP Tue Jun 4 09:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: `kubeadm version: &version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:15:05Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}`
- Network plugin and version (if this is a network-related bug): Calico 3.17.0
- Others:

**Comment by qsyqian** [comment]
I think it is not the situation what you said.
your kubernetes-dashboard CrashLoopBackOff because in pod you have no route to your kube-apiServer(in your env the service IP of kube-apiServer is 10.32.0.1). what you shoud do is to dig why it has no route to tcp 10.32.0.1:443 in your dashboard container.
the iptables you said above is created by kube-proxy because your kubernetes-dashboard service has not endpoints, the dashboard pod is CrashLoopBackOff.

**Comment by angelosanramon** [comment]
I have not a clue why kube-proxy is creating an iptables reject rule in KUBE-SERVICES chain. To go around this I just turned off iptables and created calico global network policies to secure my cluster network.
