### ISSUE TITLE
Controller-manager and Scheduler is not listening on ports 10251-10252

### ISSUE THREAD

**Issue by vipinjn24** [kubernetes/kubernetes#97269]
Hi,

I have installed kubernetes using kubeadm tool and has version 1.20.0

but it seems that the controller-manager and scheduler is not listening on 10251 and 10252 ports.
due to this prometheus is unable to etch the metrics from both of them.

I tried to use custom values file for kubeadm init and added 0.0.0.0 as addresses for both of them but it seems that it is still not listening and these 2 ports are still not being used.

I checked for 10257 and 10259 ports but it does not gives us metrics.

kindly help me resolve this issue.

**Comment by neolit123** [comment]
the insecure ports (10251-10252) will be removed in a future version.

> I checked for 10257 and 10259 ports but it does not gives us metrics.

these do export metrics, but they need authentication.
for support questions try #kubernetes-users and the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close

**Comment by vipinjn24** [comment]
@neolit123 thanks for clearing the authentication doubt.
