### ISSUE TITLE
DualStack: IPv6 not accessible from outside the cluster

### ISSUE THREAD

**Issue by brianmay** [kubernetes/kubernetes#97275]
On my dual stack cluster, I have a service that has an external IPv6 address:

```
$ kubectl get service ingress-nginx-controller-ipv6       
NAME                            TYPE        CLUSTER-IP   EXTERNAL-IP               PORT(S)          AGE
ingress-nginx-controller-ipv6   ClusterIP   fc01::5e88   2001:44b8:4112:8a03::13   80/TCP,443/TCP   66s
```

This has been added as an address to my `kube-ipvs0` network device on the pods, same as for IPv4:

```
5: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default 
    link/ether 5e:29:65:57:ca:3b brd ff:ff:ff:ff:ff:ff
[...]
    inet6 2001:44b8:4112:8a03::13/128 scope global 
       valid_lft forever preferred_lft forever
[...]
```

But this address is not accessible from outside the cluster. As in IPv6 NDP requests get ignored. If I manually add the address to my Ethernet device, it works. And continues to work after I delete the address, presumably until the NDP value expires.

I thought maybe this was some sort of Linux kernel issue, which I can reproduce on other boxes. I would expect an global IPv6 address on one interface to work on the other interfaces also. But I have been told, so far without any real evidence, it is expected behavior:

https://unix.stackexchange.com/questions/623274/ipv6-addresses-on-interface-not-responding-to-ndp-packets-on-other-interface

I guess I could create a bridge device, and add my Ethernet device and kube-ipvs0 to the bridge device on all my nodes. I imagine that will work. But before I try to work out how to do that, I would like to be able to understand why this is required.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.0 (also previous versions)
- Cloud provider or hardware configuration: own hardware
- OS (e.g: `cat /etc/os-release`): Debian buster
- Kernel (e.g. `uname -a`): 4.19.0-13-amd64
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): ipvs 1.29

**Comment by aojea** [comment]
> As in IPv6 NDP requests get ignored.

Because the addresses is added to an internal inteface you have to "route" it, is not in the same broadcast/local domain so NDP will not work. You have to add a route to that IP through one of the nodes-

@uablrek what is a good way to expose externalIP with IPVS? using metallb is a good one, right? or is better to use LoadBalancers instead of externalIPs?

**Comment by uablrek** [comment]
Metallb is a good one, yes.

The normal way to get external traffic, ipv4 or ipv6 (no difference), to the cluster is to configure an external router to send traffic to the K8s nodes. This can be done by static routes or some protocol like BGP.

But you seem to want to use L2 networking.

If it works for ipv4 you are probably using proxy-arp. If you use e.g proxy-arp all nodes will respond and traffic can basically go anywhere. If it works, you are just lucky or you have only one node. Better to use the metallb L2 speaker.

Metallb have an "L2" mode as an alternative to BGP. It responds to neigbor-discovery on ipv4 and ipv6 but ensures that just one node responds for an external address.

But this is _not_ a K8s bug.

**Comment by brianmay** [comment]
Proxy arp is turned off for IPv4, I haven't changed that.

```
root@kube-node-4:~# cat /proc/sys/net/ipv4/conf/*/proxy_arp
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
```

So I am guessing maybe this is a difference betweeen IPv4 and IPv6 support. I also see a reference in https://metallb.universe.tf/installation/ to "strict arp" which could be related too I guess.

Hmmm. Related (but reverse) question for IPv4: https://serverfault.com/questions/834512/why-does-linux-answer-to-arp-on-incorrect-interfaces

I am not entirely clear what metallb does. If it does what I think it does - then yes, it does sound like a good match. I will try.

My problem has always been trouble finding documentation. There is no mention of any of this for example https://kubernetes.io/docs/concepts/services-networking/dual-stack/. I guess I should write a blog post when I am finished :-)

For now, I agree this isn't a bug (except maybe in documentation...), so will close.
