### ISSUE TITLE
How to verify that the yaml format syntax is correct?

### ISSUE THREAD

**Issue by Mrpingdan** [kubernetes/kubernetes#97281]
How to verify that the yaml format syntax is correct?

**Comment by sftim** [comment]
@Mrpingdan, GitHub is not the right place for support requests.

For help, check the [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)
or our [Discussion Forums](https://discuss.kubernetes.io).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

**Comment by angelosanramon** [comment]
> You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

@sftim, can anyone invited to the kubernetes slack channel? I have trying to join via the URL you provided, but instead of getting and email invite I get redirected to kubernetes slack login page. How can I get an invite? Thanks.
