### ISSUE TITLE
Remove use of "minion" from graphic

### ISSUE THREAD

**Issue by RichieEscarez** [kubernetes/kubernetes#9729]
~~https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/ovs-networking.md~~
 https://github.com/kubernetes/kubernetes/blob/master/docs/admin/ovs-networking.md

Related: #8599, #9176, #1111

**Comment by mikedanese** [comment]
#1111

**Comment by zhengguoyong** [comment]
@RichieEscarez 
hi Richie, i think i can make some fix for this issues  :)

**Comment by RichieEscarez** [comment]
Thanks @zhengguoyong!
FYI: That file and graphic as since moved to here: https://github.com/kubernetes/kubernetes/blob/master/docs/admin/ovs-networking.md

**Comment by bgrant0607** [comment]
Done.
