### ISSUE TITLE
Need containerd variations for pull-kubernetes-e2e-azure-* presubmit jobs

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#97304]
A [WIP for removing dockershim](https://github.com/kubernetes/kubernetes/pull/97252) will fail for the following CI jobs:

Test name 
--- |
pull-kubernetes-e2e-azure-disk-windows |
pull-kubernetes-e2e-azure-file-windows |

A few months ago we had `pull-kubernetes-e2e-gce` which was using docker runtime, so we added `pull-kubernetes-e2e-gce-ubuntu-containerd`, stabilized it and then dropped `pull-kubernetes-e2e-gce` and switched to the containerd variation. 

We did the similar kind of changes to the scalability jobs and switched them over to containerd. Can we please do the same for these?

Also looks like there are a few more with the similar names [`pull-kubernetes-e2e-(azure|aks).*`](https://cs.k8s.io/?q=pull-kubernetes-e2e&i=nope&files=config%2Fjobs%2Fkubernetes-sigs%2Fsig-windows%2Fsig-windows-config.yaml&repos=kubernetes/test-infra). So we may have to tackle them as well.

/sig windows

**Comment by dims** [comment]
cc @marosset @craiglpeters

**Comment by marosset** [comment]
We have **pull-kubernetes-e2e-aks-engine-windows-contianerd**

https://github.com/kubernetes/test-infra/blob/6e5682ed8bf931e69692296abcfaee43a45e4a86/config/jobs/kubernetes-sigs/sig-windows/sig-windows-config.yaml#L78

But yes, we should add some storage specific jobs for azure-disk/azure-files as well.

**Comment by andyzhangx** [comment]
run azure disk & file test on containerd is a to-do work item

**Comment by andyzhangx** [comment]
fixed by https://github.com/kubernetes/test-infra/pull/20657
not always run in the beginning, should trigger manually:
```
/test pull-kubernetes-e2e-azure-disk-windows-containerd
/test pull-kubernetes-e2e-azure-file-windows-containerd
```

**Comment by marosset** [comment]
I don't think `/test pull-kubernetes-e2e-azure-disk-windows-containerd` works.

I only see 1 run which failed on https://testgrid.k8s.io/sig-windows-presubmit#pr-k8s-azure-disk-e2e-master-windows-containerd and also think I just root-caused an issue with windows + contianerd + azure disk -> https://github.com/kubernetes/kubernetes/issues/99342
