### ISSUE TITLE
Cannot remove types from API and then run code gen tools

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#9731]
I am trying to remove ContainerManifest from the API package. There are some references to it in deep_copy_generated.go. So I thought I'd just delete it from types.go, and then run the tool to regenerate that file.

It turns out that the generation tool depends on the API package? So I can't build it:

``` shell
> go build cmd/gendeepcopy/*
# github.com/GoogleCloudPlatform/kubernetes/pkg/api
pkg/api/deep_copy_generated.go:210: undefined: ContainerManifest
pkg/api/deep_copy_generated.go:262: undefined: ContainerManifestList
pkg/api/deep_copy_generated.go:270: undefined: ContainerManifest
```

I imagine I can just delete these manually, then build and run the tool. But the tool shouldn't fail like this. I took a look and it seems to be using reflection instead of stuff like the go/ast, go/build, go/format, go/parser, and go/token packages. Using the source code seems like a better approach to code generation since you wouldn't have to depend on properly generated code to build the generation tool.

**Comment by krousey** [comment]
Now that I've manually removed the functions, I get this:

```
> hack/test-go.sh pkg/runtime
Running tests for APIVersion: v1beta3 with etcdPrefix: registry
+++ [0615 09:45:12] Running unit tests without code coverage
--- FAIL: TestNoManualChangesToGenerateDeepCopies (0.02s)
	conversion_generation_test.go:126: please update conversion functions; generated: api.deep_copy.txt; first diff: 
		expected: 	"github.com/GoogleCloudPlatform/kubernetes/pkg/api/resource"
		
		     got: 	"time"
FAIL
FAIL	github.com/GoogleCloudPlatform/kubernetes/pkg/runtime	0.083s
!!! Error in hack/test-go.sh:159
  'go test "${goflags[@]:+${goflags[@]}}" ${KUBE_RACE} ${KUBE_TIMEOUT} "${@+${@/#/${KUBE_GO_PACKAGE}/}}" "${testargs[@]:+${testargs[@]}}"' exited with status 1
Call stack:
  1: hack/test-go.sh:159 runTests(...)
  2: hack/test-go.sh:221 main(...)
Exiting with status 1
```

I think it will go away if I re-run the gen tool now that I can build it. Ideally there shouldn't be this much friction to remove a deprecated type.

**Comment by bgrant0607** [comment]
cc @wojtek-t
