### ISSUE TITLE
Running 500 pod per node

### ISSUE THREAD

**Issue by m-yosefpor** [kubernetes/kubernetes#97328]
**What would you like to be added**:
In Kubernetes docs, it states that Kubernetes supports no more than 100 pods per node [link](https://kubernetes.io/docs/setup/best-practices/cluster-large/#:~:text=No%20more%20than%20100%20pods,more%20than%20300000%20total%20containers) . 

Although it is possible to run more pods (even more than 250 pods) with passing flags to kubelet, however the performance severely drops.

**Why is this needed**:
Our baremetals are pretty much large (512GiB Memory) and deploying k8s on them needs at least about 500 pods per node. It is ok for us to provide enough resources for kubelet if it needs it for scaling, however there seems to be a technical issue which prevents kubelet to scale.

**Further information:**
K8s version: 1.19.0
Runtime: CRI-O v1.19.0
OCI runtime: runc version 1.0.0-rc92
OS: Fedora CoreOS (FCOS) version 32.20201104.3.0
linux kernel: 5.9.9

**Comment by k82cn** [comment]
we have similar requirement on that, running more pods on the node.

**Comment by vsxen** [comment]
run two or more kubelet with different port & config in one node?

**Comment by m-yosefpor** [comment]
> run two or more kubelet with different port & config in one node?

I'm not sure what are the impacts oc running two kubelets within an OS.. there might be some race condition between them.. esp for memory management (OOM, eviction, etc).. also both might  be seen as two different nodes (2*512Gi nodes) from scheduler point of view and cause some issues for scheduling. Have you tried this in production?

**Comment by chenyw1990** [comment]
we have similar requirement on that, running more pods on the node,  When the number of pods increases, some problems will occur in the cadvisor, dockershim, volumemgr, and pleg, For example, the CPU usage is too high, the pleg relist is too slow, and the gRPC communication is congested, the kubelet is not ready because it is too busy.

**Comment by m-yosefpor** [comment]
From what I have found so far, docker seems to have some scalability issues for high densities. Although docker event stream has made situation better, but still it has issues with high number of pods per node. However crio-o can easily handle +500 pod per node. 

I found some interesting docs from redhat, which succeeded to run 500 pod per nodes with CRI-O. It seems the limiting factor would be rate limitings and QoS of  kubelet API calls. This can be solved with increasing default values in `kubelet.conf`

https://www.openshift.com/blog/500_pods_per_node

**Comment by matthyx** [comment]
This is definitely for sig scalability...

/remove-sig node

**Comment by Frankkkkk** [comment]
Related to #23349

**Comment by umialpha** [comment]
please reopen this issue. We have the same requirement.

**Comment by dims** [comment]
@umialpha https://github.com/kubernetes/kubernetes/issues/23349 is still open
