### ISSUE TITLE
Unit Test "TestSPDYExecutorStream" is Flaking

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [kubernetes/kubernetes#97331]
**Which test(s) are flaking**:
kubernetes/staging/src/k8s.io/client-go/tools/remotecommand/remotecommand_test.go:TestSPDYExecutorStream

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-node-ppc64le#unit-tests

**Reason for failure**:
```
================================================================================
FAIL: //staging/src/k8s.io/client-go/tools/remotecommand:go_default_test (run 1 of 2) (see /root/.cache/bazel/_bazel_root/7989b31489f31aee54f32688da2f0120/execroot/io_k8s_kubernetes/bazel-out/ppc-fastbuild/testlogs/staging/src/k8s.io/client-go/tools/remotecommand/go_default_test/run_1_of_2/test.log)

FAILED: //staging/src/k8s.io/client-go/tools/remotecommand:go_default_test (Summary)
      /root/.cache/bazel/_bazel_root/7989b31489f31aee54f32688da2f0120/execroot/io_k8s_kubernetes/bazel-out/ppc-fastbuild/testlogs/staging/src/k8s.io/client-go/tools/remotecommand/go_default_test/run_2_of_2/test.log
      /root/.cache/bazel/_bazel_root/7989b31489f31aee54f32688da2f0120/execroot/io_k8s_kubernetes/bazel-out/ppc-fastbuild/testlogs/staging/src/k8s.io/client-go/tools/remotecommand/go_default_test/run_1_of_2/test.log
INFO: From Testing //staging/src/k8s.io/client-go/tools/remotecommand:go_default_test (run 1 of 2):
==================== Test output for //staging/src/k8s.io/client-go/tools/remotecommand:go_default_test (run 1 of 2):
E1215 21:52:19.670414  239900 v2.go:105] client crashed after 1 second
E1215 21:52:19.670784  239900 v2.go:151] return err
--- FAIL: TestSPDYExecutorStream (32.93s)
    remotecommand_test.go:145: stderrBlockTest: expected [], got [execute timeout]
FAIL
================================================================================
```

**Anything else we need to know**:
Test run with BAZEL_VERSION=2.2.0
 bazel test --test_timeout=600 --config=unit --features=-race --host_javabase=@local_jdk//:jdk --test_verbose_timeout_warnings //... -- -//build/... -//vendor/...

**Comment by Rajalakshmi-Girish** [comment]
@mkumatag

**Comment by BenTheElder** [comment]
/remove-sig testing
SIG Testing own the test frameworks, CI infrastructure etc. SIGs own their own test cases, in this case I think SIG API Machinery for the clients
/sig api-machinery

**Comment by yliaog** [comment]
$ cat /usr/local/google/home/yliao/.cache/bazel/_bazel_yliao/22feabd09ed7500b895ae722021d89a6/execroot/io_k8s_kubernetes/bazel-out/k8-fastbuild/testlogs/staging/src/k8s.io/client-go/tools/remotecommand/go_default_test/run_14_of_1000/test.log
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //staging/src/k8s.io/client-go/tools/remotecommand:go_default_test
-----------------------------------------------------------------------------
E0108 03:24:23.847326      20 v2.go:151] return err
E0108 03:24:23.848250      20 v2.go:105] client crashed after 1 second
--- FAIL: TestSPDYExecutorStream (32.03s)
    remotecommand_test.go:145: stderrBlockTest: expected [], got [execute timeout]
FAIL

**Comment by yliaog** [comment]
bazel test --runs_per_test=1000 //staging/src/k8s.io/client-go/tools/remotecommand/...

**Comment by yliaog** [comment]
the error: "client crashed after 1 second" is from https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/remotecommand/remotecommand_test.go#L58

the error: "return err" is from https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/remotecommand/remotecommand_test.go#L63

**Comment by yliaog** [comment]
/assign @adamzhoul

please take a look

**Comment by adamzhoul** [comment]
let me have a look.

**Comment by adamzhoul** [comment]
@yliaog @Rajalakshmi-Girish 

logs below are normal,  they are simulating client err.  
`E1215 21:52:19.670414  239900 v2.go:105] client crashed after 1 second`
`E1215 21:52:19.670784  239900 v2.go:151] return err`

the only reason why it failed with a timeout is it's blocked in :
`errorChan := watchErrorStream(p.errorStream, &errorDecoderV2{})`

notice,  the test failed occasionally. there might be some case that triggered the block.
will do the test and fix it soon.

**Comment by aojea** [comment]
it seems the bot didn´t closed it automatically
fixed by https://github.com/kubernetes/kubernetes/pull/97909
/close
