### ISSUE TITLE
Support plaintext HTTP2 probes

### ISSUE THREAD

**Issue by rickardp** [kubernetes/kubernetes#97330]
**What would you like to be added**:

HTTP2 without TLS requires prior knowledge (handshake is part of TLS). By supporting a way of specifying to use HTTP2 plaintext (maybe "scheme: HTTP2"?), this would support the usecase.

**Why is this needed**:
 I have a couple of gRPC services with external TLS termination, so by allowing HTTP2 I can reuse the same server and ports for the health checks. As a workaround I have to also serve HTTP1.1 on a different ports from my container just for the probes.

/sig node

**Comment by matthyx** [comment]
I don't quite see how to probe http2 without tls... and what you'll gain by doing so (but I am not a specialist in this area).

/triage needs-information
/close

**Comment by lol768** [comment]
I'm not sure why this was closed without some research.

It's fairly common to run a `h2c` service (not necessarily a gRPC one) behind a load balancer. .NET's Kestrel can't support unencrypted HTTP/2 in `HttpProtocols.Http1AndHttp2` mode - incoming connections get treated as if they were `HTTP/1.1`, so there is a valid use-case for wanting to be able to probe these services in this way.
