### ISSUE TITLE
Incorrect Mock Implementation azure legacy-cloud-provider

### ISSUE THREAD

**Issue by nearora-msft** [kubernetes/kubernetes#97341]
**What happened**:
ListByResourceGroup  method in the azure diskClient mock makes a call to Delete

**What you expected to happen**:
ListByResourceGroup  method in the azure diskClient mock should call ListByResourceGroup  

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: azure
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by nilo19** [comment]
fixed by https://github.com/kubernetes/kubernetes/pull/97307
/close
