### ISSUE TITLE
job status is already active but pod status is pending

### ISSUE THREAD

**Issue by chenwenjun-github** [kubernetes/kubernetes#97342]
at present, when a job is createed, it's status is already active, using 'kubectl describe job xxx' find that "Pods Statuses" is "1 Running"
![image](https://user-images.githubusercontent.com/46237364/102326746-c157eb00-3fbf-11eb-9718-826859934494.png)

but actually the pod status is pending
![image](https://user-images.githubusercontent.com/46237364/102326931-fbc18800-3fbf-11eb-9b37-bcadcf29a135.png)

so, I suggest job status should keep sync with pod status, when the job'spod stauts is pending, the job's status shouldn't be active
thanks~~

**Comment by chentaoz** [comment]
Hey, can you share how to duplicate the issue, I created a job and saw consistent status between the  job and its pod

**Comment by chenwenjun1995** [comment]
it happend when CPU and memory resources I applied for this job exceed the upper limit of the machine, it cause pod can't start and status keep pending, but job become active

**Comment by chentaoz** [comment]
ok, I see that. there is a ticket to add the pending status of job https://github.com/kubernetes/kubernetes/issues/95940

**Comment by neolit123** [comment]
please fill the issue template correctly:
https://raw.githubusercontent.com/kubernetes/kubernetes/master/.github/ISSUE_TEMPLATE/bug-report.md

/sig apps

**Comment by chenwenjun1995** [comment]
---
name: Bug Report
about: Report a bug encountered while operating Kubernetes
labels: kind/bug

---




**job status is already active but pod status is pending**:

**job status keep sync with pod stauts, while one of pods status isn't running, job status shouldn't be active**:

**it happend when CPU and memory resources I applied for this job exceed the upper limit of the machine, it cause pod can't start and status keep pending, but job become active**:

**no**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.12", GitCommit:"a8b52209ee172232b6db7a6e0ce2adc77458829f", GitTreeState:"clean", BuildDate:"2019-10-15T12:04:30Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:

- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic



- Kernel (e.g. `uname -a`):
Linux mlf-test-0 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
none

- Network plugin and version (if this is a network-related bug):
none

- Others:
none

**Comment by CuriousVini** [comment]
which version is this fixed? I am facing same issue and as per job status doc, seems like it includes both pending and active pods. It would be good to distinguish those 2 pod status. 
https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/V1JobStatus.md
