### ISSUE TITLE
list custom resources in `kubectl get all -n <namespace>`

### ISSUE THREAD

**Issue by iam-veeramalla** [kubernetes/kubernetes#97347]
**What would you like to be added**:
Custom Resources have become the crucial resources because of its flexibility and adoptability. A namespace might have multiple CRDs/Custome Resources, It would be a good option to list them using `kubectl get all` option. 

**Why is this needed**:
This option is already available for ingress, routes, deploy, svc, pods e.t.c .,. It will be great to add CRs to this list.

**Comment by troy0820** [comment]
/sig cli
@iam-veeramalla I am trying to understand the use for this.  `kubectl api-resources` already shows the crds installed on the cluster.  Also, some CRDs are not namespaced scoped and including these objects in `kubectl get all` would provide some issues where cluster objects are expressed in the namespace you are looking in.

**Comment by iam-veeramalla** [comment]
> kubectl api-resources

Hi @troy0820 , Thanks for the response.  `kubectl api-resources` would only list the CRDs(along with the other api-resources) in the cluster. `But my ask pretty much regarding list of Custom Resources in a namespace`.

Let me give you some more information. As a user or admin I want to look at all the resources(pods, svc, ingress, vs) that are installed  in my namespace, to do that I find `kubectl get all` very useful as I don't have to waste time in getting each of the resource using `kubectl get`. This is also valid incase of some script that is monitoring a namespace to see what resources are being created. Does it make clear?

**Comment by troy0820** [comment]
@iam-veeramalla Rather than have this change be made widely, there is a plugin that exists that provides this functionality.  
https://github.com/corneliusweig/ketall.  This is available now and wouldn't need to be added to the core of Kubernetes.

**Comment by fOO223Fr** [comment]
@troy0820  Using a plugin is great and is a good interim but to stick to the meaning of "all" `kubectl get all` should return all and not exclude anything because all means everything.

Happy to work on it if consider worthwhile

**Comment by troy0820** [comment]
@fOO223Fr @iam-veeramalla I understand what you are saying but this discussion has happened in this thread https://github.com/kubernetes/kubernetes/pull/28955#issuecomment-232737113 and more recently in this thread here. https://github.com/kubernetes/kubectl/issues/151.  It is clear that going forward that this will not be implemented.  The provided plugin provides the mechanism to get "all" the resources per namespace.

**Comment by fOO223Fr** [comment]
@iam-veeramalla i guess this comment sums it up! https://github.com/kubernetes/kubectl/issues/151#issuecomment-410306145
I would suggest, no point fixating on it because people have done that in past for 3 years  (here [28955](https://github.com/kubernetes/kubernetes/pull/28955)) leading to nowhere.
@troy0820 thank you for addressing this issue. I guess it can be closed now
