### ISSUE TITLE
Improve testing coverage on unit test level

### ISSUE THREAD

**Issue by oomichi** [kubernetes/kubernetes#97355]
We have many separated issues on github to add unit tests for each package.
This issue is for tracking what packages are not covered with unit tests easily.
 
**How to know what packages are not covered with unit tests**:

We can see it with the following script:
```
#!/bin/bash

SEARCH_PATH=${1:-"./pkg"}
VERBOSITY=${VERBOSITY:-""}

DIRS=$(find ${SEARCH_PATH} -maxdepth 1 -mindepth 1 -type d)
for dir in ${DIRS}
do
        PKGS=$(find ${dir} -name "*.go" | grep -v "_test.go" | grep -v "doc.go" | grep -v "test" | grep -v "fake" | grep -v "sample" | grep -v "stub")
        COUNT=0
        for pkg in ${PKGS}
        do
                UNIT_TEST=$(echo $pkg | sed s@\.go@_test.go@)
                if [ -f ${UNIT_TEST} ]; then
                        continue
                fi
                if [ -n "${VERBOSITY}" ]; then
                        echo "$UNIT_TEST doesn't exist"
                fi
                COUNT=$(expr ${COUNT} + 1)
        done
        echo "${dir}: ${COUNT} files are not tested on unit tests."
done
```

**Current status**:

Under `./pkg`, the following is current status of each directory at the point 12/16/2020

- [ ] ./pkg/ssh: All packages are tested
- [ ] ./pkg/serviceaccount: 2 files are not tested on unit tests.
- [ ] ./pkg/controlplane: 7 files are not tested on unit tests.
- [ ] ./pkg/fieldpath: All packages are tested
- [ ] ./pkg/controller: 206 files are not tested on unit tests.
- [ ] ./pkg/kubelet: 160 files are not tested on unit tests.
- [ ] ./pkg/apis: 295 files are not tested on unit tests.
- [ ] ./pkg/features: 1 files are not tested on unit tests.
- [ ] ./pkg/auth: 1 files are not tested on unit tests.
- [ ] ./pkg/api: 1 files are not tested on unit tests.
- [ ] ./pkg/windows: 1 files are not tested on unit tests.
- [ ] ./pkg/printers: 3 files are not tested on unit tests.
- [ ] ./pkg/registry: 67 files are not tested on unit tests.
- [ ] ./pkg/kubeapiserver: 7 files are not tested on unit tests.
- [ ] ./pkg/capabilities: All packages are tested
- [ ] ./pkg/client: 1 files are not tested on unit tests.
- [ ] ./pkg/util: 30 files are not tested on unit tests.
- [ ] ./pkg/security: 10 files are not tested on unit tests.
- [ ] ./pkg/probe: 2 files are not tested on unit tests.
- [ ] ./pkg/credentialprovider: 2 files are not tested on unit tests.
- [ ] ./pkg/quota: 2 files are not tested on unit tests.
- [ ] ./pkg/volume: 63 files are not tested on unit tests.
- [ ] ./pkg/cluster: 1 files are not tested on unit tests.
- [ ] ./pkg/proxy: 28 files are not tested on unit tests.
- [ ] ./pkg/generated: 1 files are not tested on unit tests.
- [ ] ./pkg/kubectl: 1 files are not tested on unit tests.
- [ ] ./pkg/routes: 2 files are not tested on unit tests.
- [ ] ./pkg/kubemark: 3 files are not tested on unit tests.
- [ ] ./pkg/securitycontext: All packages are tested
- [ ] ./pkg/scheduler: 36 files are not tested on unit tests.
- [ ] ./pkg/cloudprovider: All packages are tested

**Comment by gavinfish** [comment]
/assign 
for ./pkg/scheduler part

**Comment by pacoxu** [comment]
Is there latest code coverage report ? 

So we can easily know which part is urgent for tests.

**Comment by oomichi** [comment]
@pacoxu 
> Is there latest code coverage report ?
The description shows it at the point 12/16/2020.
You can see it locally by running the script which is written on the description.

**Comment by s-ito-ts** [comment]
I created #98958 for adding unit test of /pkg/kubeapiserver/admission.
