### ISSUE TITLE
ERROR： /root/kubespray/roles/etcd/tasks/check_certs.yml': line 57, column 3

### ISSUE THREAD

**Issue by anzejiang** [kubernetes/kubernetes#97358]
![image](https://user-images.githubusercontent.com/39078062/102440852-00d41500-405c-11eb-884a-bf060b182ac3.png)

Approach taken：
	1、jinja2 1.10.1  update 2.11.2
	2、yum -y install python-jinja2.noarch
	Doesn't work

**Comment by anzejiang** [comment]
![image](https://user-images.githubusercontent.com/39078062/102454370-dcd2fc80-4078-11eb-83db-074a2af9bcb3.png)
Test failed！！！

**Comment by neolit123** [comment]
please try asking the kubespray maintainers first.
thanks

/close
