### ISSUE TITLE
Azure LB NIC regex too restrictive

### ISSUE THREAD

**Issue by michaelgugino** [kubernetes/kubernetes#97352]
**What happened**: https://github.com/kubernetes/kubernetes/pull/95542 introduced new regex which is too restrictive for some existing installations: https://github.com/kubernetes/kubernetes/pull/95542/files#diff-0414c3aba906b2c0cdb2f09da32bd45c6bf1df71cbb2fc55950743c99a4a5fe4R79

This new restriction causes LBs to fail to sync if just one ipConf fails regex.

**What you expected to happen**:

This change was to enable optional behavior, any ipConf that fails regex should just be ignored.  This will allow existing installs to work as they did prior to the change.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by michaelgugino** [comment]
Suggest putting a continue here: https://github.com/kubernetes/kubernetes/pull/95542/files#diff-6000121b1f9282a8bb5c767e3b5f935da6cebdb2c6a0fcd2e5dd36aee1845671R1040

This will restore previous functionality and appears to have no undesirable impact.

**Comment by michaelgugino** [comment]
Unclear if we should also put a continue here as well: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go#L311

**Comment by feiskyer** [comment]
@michaelgugino could you share an example of resourceID (please replace your subscription/resourceName with fake ones)? 

/triage accepted

**Comment by michaelgugino** [comment]
Here's the error we're seeing:

```

level=error msg=Cluster operator ingress Degraded is True with IngressControllersDegraded: Some ingresscontrollers are degraded: ingresscontroller "default" is degraded: DegradedConditions: One or more other status conditions indicate a degraded state: LoadBalancerReady=False (SyncLoadBalancerFailed: The service-controller component is reporting SyncLoadBalancerFailed events like: Error syncing load balancer: failed to ensure load balancer: invalid ip config ID /subscriptions/<redacted>/resourceGroups/big-long-string-rg/providers/Microsoft.Network/networkInterfaces/big-long-string-master0-nic/ipConfigurations/pipConfig
```
