### ISSUE TITLE
Pods on different nodes cannot communicate with each other

### ISSUE THREAD

**Issue by Mac24** [kubernetes/kubernetes#97357]
## Expected Behavior

1.master
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether fe:fc:fe:9e:1a:b6 brd ff:ff:ff:ff:ff:ff
    inet 10.33.188.138/24 brd 10.33.188.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::4f24:bc58:8b18:9347/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:87:f7:10:df brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
17: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default
    link/ether 4e:fd:7c:9e:aa:63 brd ff:ff:ff:ff:ff:ff
    inet 	 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::4cfd:7cff:fe9e:aa63/64 scope link
       valid_lft forever preferred_lft forever
18: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default qlen 1000
    link/ether e6:e1:eb:7b:af:f1 brd ff:ff:ff:ff:ff:ff
    inet 10.244.0.1/24 brd 10.244.0.255 scope global cni0
       valid_lft forever preferred_lft forever
    inet6 fe80::e4e1:ebff:fe7b:aff1/64 scope link
       valid_lft forever preferred_lft forever
19: veth7f0200ac@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether 2e:eb:99:eb:99:cc brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::2ceb:99ff:feeb:99cc/64 scope link
       valid_lft forever preferred_lft forever
20: veth78bbefb8@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether ca:99:40:ad:23:d0 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::c899:40ff:fead:23d0/64 scope link
       valid_lft forever preferred_lft forever

2.node
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether fe:fc:fe:f8:d9:f5 brd ff:ff:ff:ff:ff:ff
    inet 10.33.188.142/24 brd 10.33.188.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::90d3:df96:b229:4425/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:6d:fb:ff:69 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
15: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default
    link/ether ba:f7:29:8b:3e:65 brd ff:ff:ff:ff:ff:ff
    inet 10.244.1.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::b8f7:29ff:fe8b:3e65/64 scope link
       valid_lft forever preferred_lft forever
16: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default qlen 1000
    link/ether 52:13:13:c7:51:d7 brd ff:ff:ff:ff:ff:ff
    inet 10.244.1.1/24 brd 10.244.1.255 scope global cni0
       valid_lft forever preferred_lft forever
    inet6 fe80::5013:13ff:fec7:51d7/64 scope link
       valid_lft forever preferred_lft forever
19: veth145eb13c@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether 9e:1a:0a:fe:a3:15 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::9c1a:aff:fefe:a315/64 scope link
       valid_lft forever preferred_lft forever
20: vethf480bfd2@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether ce:13:a0:49:52:b5 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::cc13:a0ff:fe49:52b5/64 scope link
       valid_lft forever preferred_lft forever
21: veth6bf7078f@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether ea:69:15:56:35:3b brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::e869:15ff:fe56:353b/64 scope link
       valid_lft forever preferred_lft forever
22: veth5285a9a2@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether 56:b7:6b:cd:7e:37 brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet6 fe80::54b7:6bff:fecd:7e37/64 scope link
       valid_lft forever preferred_lft forever
Summarized as follows：
master | node
-- | --
eth0 | 10.33.188.138/24 | 10.33.188.142/24
docker0 | 172.17.0.1/16 | 172.17.0.1/16
flannel.1 | 10.244.0.0/32 | 10.244.1.0/32
cni0 | 10.244.0.1/24 | 10.244.1.1/24

1.master rourt
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         gateway         0.0.0.0         UG    100    0        0 eth0
10.33.188.0     *               255.255.255.0   U     100    0        0 eth0
10.244.0.0      *               255.255.255.0   U     0      0        0 cni0
10.244.1.0      10.244.1.0      255.255.255.0   UG    0      0        0 flannel.1
172.17.0.0      *               255.255.0.0     U     0      0        0 docker0

2.node route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         gateway         0.0.0.0         UG    100    0        0 eth0
10.33.188.0     *               255.255.255.0   U     100    0        0 eth0
10.244.0.0      10.244.0.0      255.255.255.0   UG    0      0        0 flannel.1
10.244.1.0      *               255.255.255.0   U     0      0        0 cni0
172.17.0.0      *               255.255.0.0     U     0      0        0 docker0

## Current Behavior

Pods on different nodes cannot communicate normally
[root@k8s-master1 flannel]# docker exec -it 0ffdb1809598 sh
/ # ping 10.33.188.142
PING 10.33.188.142 (10.33.188.142): 56 data bytes
64 bytes from 10.33.188.142: seq=0 ttl=63 time=0.500 ms
64 bytes from 10.33.188.142: seq=1 ttl=63 time=0.481 ms
64 bytes from 10.33.188.142: seq=2 ttl=63 time=0.401 ms
64 bytes from 10.33.188.142: seq=3 ttl=63 time=0.433 ms
64 bytes from 10.33.188.142: seq=4 ttl=63 time=1.336 ms
64 bytes from 10.33.188.142: seq=5 ttl=63 time=0.752 ms

--- 10.33.188.142 ping statistics ---
6 packets transmitted, 6 packets received, 0% packet loss
round-trip min/avg/max = 0.401/0.650/1.336 ms

/ # ping 10.244.1.5
PING 10.244.1.5 (10.244.1.5): 56 data bytes

--- 10.244.1.5 ping statistics ---
49 packets transmitted, 0 packets received, 100% packet loss
## Steps to Reproduce (for bugs)

1.Communication between different nodes
[root@k8s-master1 flannel]# ping 10.33.188.142
PING 10.33.188.142 (10.33.188.142) 56(84) bytes of data.
64 bytes from 10.33.188.142: icmp_seq=1 ttl=64 time=0.354 ms
64 bytes from 10.33.188.142: icmp_seq=2 ttl=64 time=0.372 ms
64 bytes from 10.33.188.142: icmp_seq=3 ttl=64 time=0.365 ms
64 bytes from 10.33.188.142: icmp_seq=4 ttl=64 time=0.773 ms

[root@k8s-node2 ~]# ping 10.33.188.138
PING 10.33.188.138 (10.33.188.138) 56(84) bytes of data.
64 bytes from 10.33.188.138: icmp_seq=1 ttl=64 time=1.17 ms
64 bytes from 10.33.188.138: icmp_seq=2 ttl=64 time=0.574 ms
64 bytes from 10.33.188.138: icmp_seq=3 ttl=64 time=0.775 ms
64 bytes from 10.33.188.138: icmp_seq=4 ttl=64 time=0.988 ms

2.Pods on the same node can communicate
[root@k8s-node2 ~]# ping 10.244.1.5
PING 10.244.1.5 (10.244.1.5) 56(84) bytes of data.
64 bytes from 10.244.1.5: icmp_seq=1 ttl=64 time=0.125 ms
64 bytes from 10.244.1.5: icmp_seq=2 ttl=64 time=0.086 ms
64 bytes from 10.244.1.5: icmp_seq=3 ttl=64 time=0.089 ms
64 bytes from 10.244.1.5: icmp_seq=4 ttl=64 time=0.069 ms

3.Pod on the master node can communicate with node, but cannot communicate with pod on node
[root@k8s-master1 flannel]# docker exec -it 0ffdb1809598 sh
/ # ping 10.33.188.142
PING 10.33.188.142 (10.33.188.142): 56 data bytes
64 bytes from 10.33.188.142: seq=0 ttl=63 time=0.500 ms
64 bytes from 10.33.188.142: seq=1 ttl=63 time=0.481 ms
64 bytes from 10.33.188.142: seq=2 ttl=63 time=0.401 ms
64 bytes from 10.33.188.142: seq=3 ttl=63 time=0.433 ms
64 bytes from 10.33.188.142: seq=4 ttl=63 time=1.336 ms
64 bytes from 10.33.188.142: seq=5 ttl=63 time=0.752 ms

--- 10.33.188.142 ping statistics ---
6 packets transmitted, 6 packets received, 0% packet loss
round-trip min/avg/max = 0.401/0.650/1.336 ms

/ # ping 10.244.1.5
PING 10.244.1.5 (10.244.1.5): 56 data bytes

--- 10.244.1.5 ping statistics ---
49 packets transmitted, 0 packets received, 100% packet loss

## Your Environment

* Flannel version:v0.12.0-amd64
* Backend used (e.g. vxlan or udp):vxlan
* Etcd version:v3.4.3
* Kubernetes version (if used):v1.18.8
* Operating System and version:centos7

**Comment by uablrek** [comment]
Tested with;
```
  09:19:09 Server Version: v1.18.14
  09:19:09 CNI-plugin; flannel:v0.12.0-amd64
```
And works. What seems to be missing in your setup is "onlink" routes;
```
$ ip ro
...
11.0.0.0/24 dev cni0 proto kernel scope link src 11.0.0.1 
11.0.1.0/24 via 11.0.1.0 dev flannel.1 onlink 
11.0.2.0/24 via 11.0.2.0 dev flannel.1 onlink 
11.0.3.0/24 via 11.0.3.0 dev flannel.1 onlink 
192.168.0.0/24 dev eth0 proto kernel scope link src 192.168.0.2 
192.168.1.0/24 dev eth1 proto kernel scope link src 192.168.1.2 
```
These are the routes directing packets to pod cidr's on other nodes.

**Comment by uablrek** [comment]
This is not a bug or a support case in K8s but in the `flannel` CNI-plugin. Please try a `flannel` forum or issue.

**Comment by jayunit100** [comment]
can we close this since its flannel specific ?

**Comment by Mac24** [comment]
> Tested with;
> 
> ```
>   09:19:09 Server Version: v1.18.14
>   09:19:09 CNI-plugin; flannel:v0.12.0-amd64
> ```
> 
> And works. What seems to be missing in your setup is "onlink" routes;
> 
> ```
> $ ip ro
> ...
> 11.0.0.0/24 dev cni0 proto kernel scope link src 11.0.0.1 
> 11.0.1.0/24 via 11.0.1.0 dev flannel.1 onlink 
> 11.0.2.0/24 via 11.0.2.0 dev flannel.1 onlink 
> 11.0.3.0/24 via 11.0.3.0 dev flannel.1 onlink 
> 192.168.0.0/24 dev eth0 proto kernel scope link src 192.168.0.2 
> 192.168.1.0/24 dev eth1 proto kernel scope link src 192.168.1.2 
> ```
> 
> These are the routes directing packets to pod cidr's on other nodes.
[root@k8s-master1 ~]# ip ro
default via 10.33.188.254 dev eth0 proto static metric 100 
10.33.188.0/24 dev eth0 proto kernel scope link src 10.33.188.138 metric 100 
10.244.0.0/24 dev cni0 proto kernel scope link src 10.244.0.1 
10.244.1.0/24 via 10.244.1.0 dev flannel.1 onlink 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1


[root@k8s-node2 ~]# ip ro
default via 10.33.188.254 dev eth0 proto static metric 100 
10.33.188.0/24 dev eth0 proto kernel scope link src 10.33.188.142 metric 100 
10.244.0.0/24 via 10.244.0.0 dev flannel.1 onlink 
10.244.1.0/24 dev cni0 proto kernel scope link src 10.244.1.1 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1
