### ISSUE TITLE
[Request]: listing all allowed actions should also be able to list the respective namespaces

### ISSUE THREAD

**Issue by Nokel81** [kubernetes/kubernetes#97351]
**What would you like to be added**:
Add an option to `authorizationv1client.AuthorizationV1Interface`'s `SelfSubjectRulesReviews()`'s `Create` called "any namespace" (or something similar).

This flag would mean that that the request returns one item for every namespace that the user has access do (and which namespace it is).

**Why is this needed**:
There currently isn't a way for a user locked down by RBAC to query a find out what it is allowed to do. This would be that solution.

This would allow for something like the following to exist: `kubectl auth can-i --list --any-namespace`

**Security**:
I don't believe that this introduces a security whole as it doesn't leak to the user any information about the system that they wouldn't be able to access anyway. I know that this sort of bypasses the `list` `namespaces` RBAC but I don't think that it breaks that as the user could try to brute force the namespace names.

**Comment by liggitt** [comment]
> This flag would mean that that the request returns one item for every namespace that the user has access do (and which namespace it is).

Thanks for the request, but to accomplish this, the authorizer would need to be queried once for every namespace in the cluster. This could involve a remote call if a webhook authorizer was configured. Allowing a single API request to trigger an unbounded number of cluster-wide server-side requests is not desired.

/close
