### ISSUE TITLE
kube-apiserver ran out of memory on aws c5.9xlarge instance

### ISSUE THREAD

**Issue by bjethwan** [kubernetes/kubernetes#97365]
**What happened**:
kube-apiserver ran out of memory
The update of the nodelocaldns daemonset, caused the kube-api-server to become unavailable.

Meanwhile, I'm thinking to add resource/memory limits on kube-apiserver.
However, I don't like setting up the hard-limits on our k8s provisioning scripts.
Is there a way to set the memory limits in terms of % of available memory on the node, especially for static pods?

**What you expected to happen**:
kube-apiserver should have lived.

**How to reproduce it (as minimally and precisely as possible)**:
Kubernetes Version: 1.17.11
update of the nodelocaldns daemonset

**Anything else we need to know?**:
Meanwhile, I'm thinking to add resource/memory limits on kube-apiserver.
However, I don't like setting up the hard-limits on our k8s provisioning scripts.
Is there a way to set the memory limits in terms of % of available memory on the node, especially for static pods?

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.11
- Cloud provider or hardware configuration: aws c5.9xlarge
- OS (e.g: `cat /etc/os-release`): Flatcar Container Linux by Kinvolk 2512.2.1 (Oklo)
- Kernel (e.g. `uname -a`): Linux ip-10-223-13-158.ds.dtveng.net 4.19.128-flatcar #1 SMP Tue Jun 16 10:17:17 -00 2020 x86_64 Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz GenuineIntel GNU/Linux
- Install tools: nodelocaldns
- Network plugin and version (if this is a network-related bug): calico
- Others:

**Comment by bjethwan** [comment]
I am unable to guess/pick the right SIG

**Comment by bjethwan** [comment]
I can say that it's happening for clusters with a size of more than 200 worker nodes.

**Comment by neolit123** [comment]
> Is there a way to set the memory limits in terms of % of available memory on the node, especially for static pods?

for similar questions best to ask on the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

> Kubernetes Version: 1.17.11

this version is no longer in support, if you see a bug in 1.18+ the maintainers can have a look.

thanks
/close
/kind support
/remove-kind bug
