### ISSUE TITLE
Priviledge escalation for ServiceAccount and RoleBinding in kubernetes v1.19.4

### ISSUE THREAD

**Issue by matsonkepson** [kubernetes/kubernetes#97369]
**What happened**:

While creating ServiceAccount and assigning privileges with RoleBinding only to one namespace I can list/access/modify all resources / all namespaces
gist here > https://gist.github.com/matsonkepson/6d4a076ec5a97beb50f9e724fa332ff3

**What you expected to happen**:

ServiceAccount gets admin access ONLY within one namespace 
gist here > https://gist.github.com/matsonkepson/68f874db443b60c485304b103e594337

**How to reproduce it (as minimally and precisely as possible)**:

Works fine with microk8s  v1.18.13 
NOT working for Kubernetes v1.19.4 (rancher 2.5.3 edition) 
gist here > https://gist.github.com/matsonkepson/ea64d35c9260d81d93994ab197d5d3d4

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): kubectl --kubeconfig 5610934-kubeconfig version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: self hosted vmware 

- OS (e.g: `cat /etc/os-release`):  NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- Install tools: rancher 2.5.3

**Comment by liggitt** [comment]
/sig auth
/remove-sig security
/kind support

Do you get the same results if you omit creating the role/rolebinding? That would indicate something else in the cluster is granting broad permissions to all service accounts. You can check `kubectl get clusterrolebindings -o yaml` to see if there are any grants to system:serviceaccounts or system:authenticated groups.

**Comment by matsonkepson** [comment]
> Do you get the same results if you omit creating the role/rolebinding?

Yes that is correct , i got very same result

> You can check kubectl get clusterrolebindings -o yaml to see if there are any grants to system:serviceaccounts or system:authenticated groups.

After running this command (with the new ServiceAccount and its freshly created token and cert ) i got 1 occurrence of system:serviceaccounts and 3 occurrences of system:authenticated.

How can i check what is unwittingly giving me those broad permissions ?

**Comment by matsonkepson** [comment]
okay , this is dump, but looks like there was a clusterrolebinding (i was not aware of that and was sure that cluster was clean) which was bounding all service accounts to the cluster-admin role

sorry for that :|
