### ISSUE TITLE
 Why the service that don't have Endpoints, that need add a rule "KUBE-EXTERNAL-SERVICES" to input chains

### ISSUE THREAD

**Issue by zhifei92** [kubernetes/kubernetes#97360]
### case
Access to process that normally listen on ports on the physical machine is denied , the reason is that iptables rules rejected client. the rule is generated by a no endpoints service.
```
-A KUBE-EXTERNAL-SERVICES -p tcp -m comment --comment "default/traefik-1566557461:http has no endpoints" -m addrtype --dst-type LOCAL -m tcp --dport 32445 -j REJECT --reject-with icmp-port-unreachable
```

kube-proxy code : proxier.go
```
		} else {
			// No endpoints.
			writeLine(proxier.filterRules,
				"-A", string(kubeServicesChain),
				"-m", "comment", "--comment", fmt.Sprintf(`"%s has no endpoints"`, svcNameString),
				"-m", protocol, "-p", protocol,
				"-d", utilproxy.ToCIDR(svcInfo.ClusterIP),
				"--dport", strconv.Itoa(svcInfo.Port),
				"-j", "REJECT",
			)
		}
```
### doubt
Why the service that don't have Endpoints, that need add a rule "-A KUBE-EXTERNAL-SERVICES -p tcp -m comment --comment "xxx has no endpoints" -m addrtype --dst-type LOCAL -m tcp --dport xxxx -j REJECT --reject-with icmp-port-unreachable " to input chains
@freeformz

**Comment by aojea** [comment]
> ### doubt
> Why the service that don't have Endpoints, that need add a rule "-A KUBE-EXTERNAL-SERVICES -p tcp -m comment --comment "xxx has no endpoints" -m addrtype --dst-type LOCAL -m tcp --dport xxxx -j REJECT --reject-with icmp-port-unreachable " to input chains

I don´t know if I get the question correctly, so let me give you some details on the rationale about this:
if the Service doesn´t have endpoints, all the traffic that you send to the ClusterIP of the service can´t be forwarded, so it will be blackholed and the client have to wait until the socket timeout expires to detect that there is no way to connect to it.

Using a reject rule, the client that tries to connect, will know that the service is not ready to receive traffic.

**Comment by thockin** [comment]
@aojea is correct.  Also, we decided overall that it was less surprising to users to REJECT such accesses than to let them "fall through" and route to things that would not be possible if that service had endpoints.

In short - we claim complete ownership of the port, and if you have a local process listening on a node-port a) we have a bug (we try to hold those ports) and b) you're doing something weird.

**Comment by seamaner** [comment]
can icmp unreachable (`--reject-with icmp-port-unreachable `) changed to other options  ?
