### ISSUE TITLE
About the source of the basic build image

### ISSUE THREAD

**Issue by houfangdong** [kubernetes/kubernetes#97363]
Hello, I currently want to build the go-runner:v2.0.0 mirror locally, but I cannot find the code repository. Where is the code repository for go-runner:v2.0.0?
/sig release
@justaugustus

**Comment by neolit123** [comment]
it's here:
https://github.com/kubernetes/release/blob/d19bdf5169a8fd9e4ab74fd86b728fcac4bccf77/images/build/go-runner/README.md

/close
