### ISSUE TITLE
Azure LB Availability Set assumptions too restrictive

### ISSUE THREAD

**Issue by wking** [kubernetes/kubernetes#97375]
**What happened**: #96111 introduced new dependency on Availability Sets which is too restrictive for some existing installations: https://github.com/kubernetes/kubernetes/pull/96111/files#diff-0414c3aba906b2c0cdb2f09da32bd45c6bf1df71cbb2fc55950743c99a4a5fe4R1071

**What you expected to happen**: Azure cloud provider to successfully manage LBs, like it had been doing before.  Instead, it died [with][1]:

```
azure_loadbalancer.go:193] reconcileLoadBalancer(openshift-ingress/router-default) failed: cannot get the availability set ID from the virtual machine with node name ci-op-bpk9gm56-2dc90-lw6kr-master-1
```

**How to reproduce it (as minimally and precisely as possible)**: Fails every time in OpenShift CI.  Can you point us to documentation around the infrastructure options that the Azure cloud provider expects for LB management?  https://kubernetes-sigs.github.io/cloud-provider-azure/topics/loadbalancer/#load-balancer-selection-modes doesn't say anything about NIC names, and it doesn't have specifics around what things should look like without Availability Sets, or whether "without Availability Sets" is not supported (when previous iterations of the cloud provider had no problem with our lack of Availability Sets).

Documenting cloud-provider assumptions about host hardware would have also helped avoid #97352; CC @nilo19

/sig cloud-provider
/area provider/azure

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1908389#c11

**Comment by wking** [comment]
Notes on OpenShift's Azure infrastructure in ARM templates [here][1], in case that helps clarify the infra we use today.  Those are OpenShift 4.6 docs, and 4.6 is based on Kubernetes 1.19, and things worked fine.  The trouble we've been having when we took the same Azure-infra approach and tried to use it with Kubernetes 1.20, after openshift/kubernetes#471.

[1]: https://docs.openshift.com/container-platform/4.6/installing/installing_azure/installing-azure-user-infra.html

**Comment by feiskyer** [comment]
@wking could you share an example of resourceID (please replace your subscription/resourceName with fake ones)?

**Comment by wking** [comment]
Example CI run [here][1] from the NIC-renaming openshift/installer#4490.  Installer logs [here][2] include:

```
time="2020-12-17T21:57:59Z" level=debug msg="module.master.azurerm_network_interface.master[1]: Creation complete after 34s [id=/subscriptions/d38f1e38-4bed-438e-b227-833f997adf6a/resourceGroups/ci-op-67x6pb5c-2dc90-n68qc-rg/providers/Microsoft.Network/networkInterfaces/ci-op-67x6pb5c-2dc90-n68qc-master-nic-1]"
```

I'm hoping that the subscription name is not sensitive, because we've been dumping them in public logs for a long time now 🤞.  Should be IDs for any other resources you're interested in in those logs as well.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_installer/4490/pull-ci-openshift-installer-master-e2e-azure/1339686626586005504
[2]: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_installer/4490/pull-ci-openshift-installer-master-e2e-azure/1339686626586005504/artifacts/e2e-azure/ipi-install-install/

**Comment by nilo19** [comment]
Looks like this is about the master node. Are you using standard LB or a basic one? For standard LB, the master node would be excluded by default.

**Comment by wking** [comment]
> Are you using standard LB or a basic one?

[Standard][1] (and [here][2]).

> For standard LB, the master node would be excluded from the LB by default.

Is this documented somewhere?  We've been using standard LBs [for years][3], with no problems until the bump to the Kube 1.20 Azure cloud-provider.

[1]: https://github.com/openshift/installer/blob/41059581b9ba1f932f3e36fff2099930e97a30ff/data/data/azure/vnet/public-lb.tf#L54
[2]: https://github.com/openshift/installer/blob/41059581b9ba1f932f3e36fff2099930e97a30ff/data/data/azure/vnet/internal-lb.tf#L7
[3]: https://github.com/openshift/installer/commit/2c40ae8dcf5fe0d29c10ae6b89da19c4dc60614b#diff-3e2dd8cf77b5da42c3423b5c2a10eea81f5d0b55e698220b0e505d65dee4c2a6R20

**Comment by alvaroaleman** [comment]
> For standard LB, the master node would be excluded from the LB by default.

Are you referring to the built-in logic of Kube to never target master nodes with a service type LoadBalancer?

**Comment by wking** [comment]
> Are you referring to the built-in logic of Kube to never target master nodes with a service type LoadBalancer?

That used to be a problem (#65618), but my understanding is that it has since been fixed.

**Comment by wking** [comment]
Can we re-open this?  kubernetes-sigs/cloud-provider-azure#443 was [not sufficient][1] to get the cloud-provider happy on our infra, which again, contains no Availability Sets.  There are some more notes about our infrastructure [here][2] (with discussion in [rhbz#1794839][3]), in case that helps.

[1]: https://github.com/kubernetes-sigs/cloud-provider-azure/pull/443#discussion_r547438803
[2]: https://docs.microsoft.com/en-us/azure/openshift/concepts-networking#whats-new-in-openshift-45
[3]: https://bugzilla.redhat.com/show_bug.cgi?id=1794839

**Comment by wking** [comment]
@staebler, who has a better grasp on this than me, also just opened #97467.  Sounds like fixing that broader issue might obsolete this ticket, because "the cloud-provider expects Availability Sets which OpenShift infra doesn't have in order to figure out which nodes to remove" doesn't matter if the cloud-provider isn't removing any OpenShift nodes in the first place.

**Comment by CecileRobertMichon** [comment]
@feiskyer @nilo19 can you please confirm the standalone VM scenario is supported? It's a critical use case for CAPZ (our control plane VMs in zone-enabled regions are _not_ placed in availability sets)
