### ISSUE TITLE
kube-proxy nf_conntrack_tcp_timeout_close_wait default value 60min is too large

### ISSUE THREAD

**Issue by house0128** [kubernetes/kubernetes#97377]
We deployed an NginxPlus on a Node node, found that a large number of packets were lost in the system around qps1300.
The error message is "nf_conntrack:table full,dropping packet."
The param net.netfilter.nf_conntrack_max is 655,360.

We found a large number of close_wait records in the conntrack table, but netstat don't show close_wait.like this :
![image](https://user-images.githubusercontent.com/18210121/102566500-a1890a00-411a-11eb-90e7-54941bde8ca9.png)

Then,we found the ttl is 3600,b/c kube-proxy change the defulat params from 60 to 3600. The reason is https://github.com/kubernetes/kubernetes/issues/32551

So,how to solve this problem? reduce the  nf_conntrack_tcp_timeout_close_wait ? 
And also don't know why  are the conntrack table  and netstat results inconsistent?

**Comment by aojea** [comment]
/sig network

> So,how to solve this problem? reduce the nf_conntrack_tcp_timeout_close_wait ?

it seems that conntrack is not able to see the packet closing the connection, or one of the sides is leaking, that remembers me this bug that involves nginx https://blog.cloudflare.com/this-is-strictly-a-violation-of-the-tcp-specification/

@thockin @bowei based on https://github.com/kubernetes/kubernetes/issues/32551 seems you have good insights in the topic, is not 60 minutes excessive for the conntrack state?

> And also don't know why are the conntrack table and netstat results inconsistent?

netstat shows the current socket status and conntrack shows the "observed" TCP status.

There is a good explanation here on how conntrack works and the close_wait status https://bugzilla.redhat.com/show_bug.cgi?id=1215927#c10 ,

**Comment by thockin** [comment]
I recall the bug with metadata and it was exceedingly difficult to find.  I don't know why the other end of the connection doesn't get closed properly - when it does, the records should be released, right?

In this case, at 1300 QPS you'll open about 78000 connections per minute, which wilkl last you 8.4 minutes until you overflow your 655360 record table.  That's bad.

With a 60s timeout you'd open about 78000 connections per minute, and each minute after the first, you will retire 78000 records.  So for very short lived connections, you should peak at about 78000*2=156000 records, assuming they are not properly closed.  Good.

So ... why are they not properly closed?  Can we fix that?

There is a kube-proxy knob (--conntrack-tcp-timeout-close-wait or config.Conntrack.TCPCloseWaitTimeout.Duration) which you can twist to change this.  Unfortunately it's a very coarse param at the kernel level.

@bowei - maybe we should revisit https://github.com/kubernetes/kubernetes/issues/32551 and see if we can fix this at the source, and lower the default, maybe gradually over a few releases.

**Comment by house0128** [comment]
@thockin  
thanks.
We have reviewed the configuration of nginxplus , found the keepAlive of the reverse proxy is not working.
We fixed it and change  nf_conntrack_tcp_timeout_close_wait  from 3600 to 300.It looks OK now.

**Comment by freehan** [comment]
Cool! Closing this issue. Reopen if needed.

**Comment by aojea** [comment]
> In this case, at 1300 QPS you'll open about 78000 connections per minute, which wilkl last you 8.4 minutes until you overflow your 655360 record table. That's bad.


> We fixed it and change nf_conntrack_tcp_timeout_close_wait from 3600 to 300.It looks OK now.

Should we lower the timeout?
600 seems a good middle ground to me
