### ISSUE TITLE
kubectl exec doesn´t work for pods on master node

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#97383]
**What happened**:

This has been seen in the CI, I can´t say if this is a bug, a configuration problem or "works as intended.

- Kubernetes CI deployment in GCE (pull-kubernetes-e2e-gce-ubuntu-containerd job)
- schedule pods in each node (master and workers)
- execute a command in each pod `kubectl exec -it pod sh -c ...` 
- commands in workers nodes work perfectly
- the command fails in the master node with the error

> Dec 17 19:22:58.019: failed to execute command in pod iperf2-clients-sprp5, container iperf2-client: unable to upgrade connection: Debug endpoints are disabled.
> Unexpected error:
>     <*errors.errorString | 0xc0037417d0>: {
>         s: "unable to upgrade connection: Debug endpoints are disabled.",
>     }
>     unable to upgrade connection: Debug endpoints are disabled.
> occurred
 
- and the kubelet logs the following stacktrace

> 1217 19:22:57.641647    9610 http.go:134] Probe succeeded for https://127.0.0.1:443/readyz, Response: {200 OK 200 HTTP/2.0 2 0 map[Audit-Id:[eedd2523-7171-4f44-9271-4f40db0a8bb3] Cache-Control:[no-cache, private] Content-Length:[2] Content-Type:[text/plain; charset=utf-8] Date:[Thu, 17 Dec 2020 19:22:57 GMT] X-Content-Type-Options:[nosniff] X-Kubernetes-Pf-Flowschema-Uid:[1ec14649-a452-4c49-82bf-0da43243c306] X-Kubernetes-Pf-Prioritylevel-Uid:[53a09561-9f78-4cef-af60-77d0d40be39a]] 0xc001094e20 2 [] false false map[] 0xc001efee00 0xc001ad9290}
> I1217 19:22:57.642535    9610 prober.go:126] Readiness probe for "kube-apiserver-e2e-6c743b05a4-a7d53-master_kube-system(a6f384c06cc6716cb7ade7feb1282b68):kube-apiserver" succeeded
> I1217 19:22:57.996327    9610 httplog.go:89] "HTTP" verb="POST" URI="/exec/network-perf-9630/iperf2-clients-sprp5/iperf2-client?command=%2Fbin%2Fsh&command=-c&command=iperf+-v+%7C%7C+true&error=1&output=1" latency="152.125Âµs" userAgent="e2e.test/v1.21.0 (linux/amd64) kubernetes/70e7497 -- [sig-network] Networking IPerf2 should run iperf2" srcIP="10.40.0.2:36406" resp=405 statusStack="\ngoroutine 17908 [running]:\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc00073ed90, 0x195)\n\tstaging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go:237 +0xcf\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc00073ed90, 0x195)\n\tstaging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go:216 +0x35\nnet/http.Error(0x4f978c0, 0xc00073ed90, 0x49268ae, 0x1d, 0x195)\n\tGOROOT/src/net/http/server.go:2054 +0x1f6\nk8s.io/kubernetes/pkg/kubelet/server.(*Server).InstallDebuggingDisabledHandlers.func1(0x4f978c0, 0xc00073ed90, 0xc001eff400)\n\tpkg/kubelet/server/server.go:531 +0x53\nnet/http.HandlerFunc.ServeHTTP(0x4a880d0, 0x4f978c0, 0xc00073ed90, 0xc001eff400)\n\tGOROOT/src/net/http/server.go:2042 +0x44\nk8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).HandleWithFilter.func1.1(0xc001538b40, 0xc00073ee00)\n\tvendor/github.com/emicklei/go-restful/container.go:322 +0x4a\nk8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc001538ab0, 0xc001538b40, 0xc00073ee00)\n\tvendor/github.com/emicklei/go-restful/filter.go:21 +0x8c\nk8s.io/kubernetes/pkg/kubelet/server.(*Server).InstallAuthFilter.func1(0xc001538b40, 0xc00073ee00, 0xc001538ab0)\n\tpkg/kubelet/server/server.go:287 +0x635\nk8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc001538ab0, 0xc001538b40, 0xc00073ee00)\n\tvendor/github.com/emicklei/go-restful/filter.go:19 +0x66\nk8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).HandleWithFilter.func1(0x4f978c0, 0xc00073ed90, 0xc001eff400)\n\tvendor/github.com/emicklei/go-restful/container.go:324 +0x292\nnet/http.HandlerFunc.ServeHTTP(0xc0012fba40, 0x4f978c0, 0xc00073ed90, 0xc001eff400)\n\tGOROOT/src/net/http/server.go:2042 +0x44\nnet/http.(*ServeMux).ServeHTTP(0xc0012a05c0, 0x4f978c0, 0xc00073ed90, 0xc001eff400)\n\tGOROOT/src/net/http/server.go:2417 +0x1ad\nk8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc0012433b0, 0x4f978c0, 0xc00073ed90, 0xc001eff400)\n\tvendor/github.com/emicklei/go-restful/container.go:303 +0x4d\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.WithLogging.func1(0x4f9b240, 0xc0012f0380, 0xc001eff300)\n\tstaging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go:91 +0x322\nnet/http.HandlerFunc.ServeHTTP(0xc000b3c2e0, 0x4f9b240, 0xc0012f0380, 0xc001eff300)\n\tGOROOT/src/net/http/server.go:2042 +0x44\nk8s.io/kubernetes/pkg/kubelet/server.(*Server).ServeHTTP(0xc001233e00, 0x4f9b240, 0xc0012f0380, 0xc001eff300)\n\tpkg/kubelet/server/server.go:931 +0x61c\nnet/http.serverHandler.ServeHTTP(0xc0012f0460, 0x4f9b240, 0xc0012f0380, 0xc001eff300)\n\tGOROOT/src/net/http/server.go:2843 +0xa3\nnet/http.(*conn).serve(0xc00195afa0, 0x4f9eec0, 0xc001e61b00)\n\tGOROOT/src/net/http/server.go:1925 +0x8ad\ncreated by net/http.(*Server).Serve\n\tGOROOT/src/net/http/server.go:2969 +0x36c\n" addedInfo="\nlogging error output: \"Debug endpoints are disabled.\\n\"\n"

I don´t know if the error msg `Debug endpoints are disabled` is a red herring, but the kubelet starts with the following flag set to true

> I1217 19:06:31.972049    9610 flags.go:59] FLAG: --enable-debugging-handlers="true"

I´m more worried for the `unable to upgrade connection` message

Full logs here:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/94015/pull-kubernetes-e2e-gce-ubuntu-containerd/1339644964253995008/

**Comment by aojea** [comment]
/sig api-machinery
due to the `unable to upgrade connection` error, that is present
https://github.com/kubernetes/kubernetes/blob/cea1d4e20b4a7886d8ff65f34c6d4f95efcb4742/staging/src/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper.go#L353

/sig node
for the kubelet error ` Debug endpoints are disabled` 
https://github.com/kubernetes/kubernetes/blob/f5abe26a198d845f0a3cd6bd13ab9a37adda90b5/pkg/kubelet/server/server.go#L528-L532

Thanks @mattfenwick for finding it

**Comment by aojea** [comment]
seen again in another job


> Kubernetes e2e suite: [sig-network] NoSNAT [Feature:NoSNAT] [Slow] Should be able to send traffic between Pods without SNAT expand_less | 2m32s
> -- | --
> /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/no_snat.go:63 Dec 21 23:31:11.360: Unexpected error:     <exec.CodeExitError>: {         Err: {             s: "error running /workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://35.247.30.246 --kubeconfig=/workspace/.kube/config --namespace=no-snat-test-4967 exec no-snat-testh555v -- /bin/sh -x -c curl -q -s --connect-timeout 30 10.64.1.210:8080/clientip:\nCommand stdout:\n\nstderr:\nerror: unable to upgrade connection: Debug endpoints are disabled.\n\nerror:\nexit status 1",         },         Code: 1,     }     error running /workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://35.247.30.246 --kubeconfig=/workspace/.kube/config --namespace=no-snat-test-4967 exec no-snat-testh555v -- /bin/sh -x -c curl -q -s --connect-timeout 30 10.64.1.210:8080/clientip:     Command stdout:          stderr:     error: unable to upgrade connection: Debug endpoints are disabled.          error:     exit status 1 occurred /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/util.go:132
> 
>

**Comment by fedebongio** [comment]
As we quickly looked at this one during the triage, we suggest looking at the kube_up script. It might be working as intended (probably the Kubelet is being set to not allow exec). 

 In GCE all nodes should be in the same network, so not clear why this would be happening. 
/triage accepted

**Comment by knight42** [comment]
The kubelet on master nodes starts with `enableDebuggingHandlers: false`: https://github.com/kubernetes/kubernetes/blob/94be86aaa242969bf20df91d68f9ac09619ecdb0/cluster/gce/util.sh#L1004-L1006

while the kubelet on worker nodes starts with debugging handlers enabled: https://github.com/kubernetes/kubernetes/blob/94be86aaa242969bf20df91d68f9ac09619ecdb0/cluster/gce/util.sh#L1028-L1030

looks like this is expected. Perhaps we should ensure the pod is not scheduled to master nodes?

**Comment by aojea** [comment]
> probably the Kubelet is being set to not allow exec)

TIL, so `/exec` is a debugging handler, got it thanks
https://github.com/kubernetes/kubernetes/blob/f11c3b475d852ec8b6075fb2899a795f52d1be8f/pkg/kubelet/server/server.go#L407-L439

> The kubelet on master nodes starts with `enableDebuggingHandlers: false`:

@knight42 should this be reflected somewhere in the kubelet logs?  if you see the logs of the kubelet in the master node it shows the flag to true but I can´t see other place where shows it to false https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/94015/pull-kubernetes-e2e-gce-ubuntu-containerd/1339644964253995008/artifacts/e2e-6c743b05a4-a7d53-master/kubelet.log

**Comment by aojea** [comment]
/close
This is working as expected,
 maybe the kubelet should log somehwere that the handlers are disabled? 
but that is something cosmetic, because the error log clearly says that the debugging handlers are disabled
Thanks all

**Comment by knight42** [comment]
> should this be reflected somewhere in the kubelet logs?

yes, it might be better to log the config if a config file is provided.
