### ISSUE TITLE
Improve lifecycle event handlers documentation

### ISSUE THREAD

**Issue by Anticom** [kubernetes/kubernetes#97387]
**What would you like to be added**:
1. The documentation about [lifecycle event handlers](https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/) currently does not say anything about whether pods get re-scheduled when lifecycle.postStart.exec.command returns a non 0 exit code.
2. Furthermore it does not explicitly state, whether the commands run in the very same container they're attached to or not.

**Why is this needed**:
To me those points are not clear. I'm assuming that both the exit code does matter and the commands are indeed running in the very same container, to me it's not 100% clear. IMHO more verbosity in the docs on those topics can't hurt.

---

If the docs are somewhere here at github as well let me know and I can prepeare a PR if needed.

**Comment by Clivern** [comment]
hey @Anticom, you can edit the docs from here https://github.com/kubernetes/website/edit/master/content/en/docs/tasks/configure-pod-container/attach-handler-lifecycle-event.md & open a PR if u interested
