### ISSUE TITLE
Volume affinity error

### ISSUE THREAD

**Issue by yatintaluja** [kubernetes/kubernetes#97386]
We have an EKS cluster with multi-AZ enabled. We have stateful sets services running with multiple replicas. 

Whenever we make a release for a stateful set service and the pod restart, one of the pod will go into a pending state because of volume affinity error, i.e. pod will get scheduled on a different node than initial setup, where volume is not present.

We should have a property to always schedule a stateful set pod on the same node.

**Comment by neolit123** [comment]
please correctly fill the issue template and then re-open this issue:
https://raw.githubusercontent.com/kubernetes/kubernetes/master/.github/ISSUE_TEMPLATE/bug-report.md

thanks
/sig-storage
/area provider/azure
/sig cloud-provider
/close
