### ISSUE TITLE
Kubectl describe formatting in JSON

### ISSUE THREAD

**Issue by mayankagg9722** [kubernetes/kubernetes#97391]
I am using "kubectl describe nodes {nodename}", and facing issues in parsing the text and it also doesn't support json formatting.

Please give us support for json formatting example: "kubectl describe nodes {nodename} -o json".

Few same issues already have been raised here:
https://stackoverflow.com/questions/37464518/how-to-format-the-output-of-kubectl-describe-to-json

**Comment by liggitt** [comment]
Thanks for the request. This was previously requested in https://github.com/kubernetes/kubernetes/issues/25353 and declined. The APIs the describe command uses to obtain data about the object can be used and output in JSON format, but new multi-object APIs to output structured describe content are planned.
