### ISSUE TITLE
Does kubernetes service ClusterIP type support forward proxy

### ISSUE THREAD

**Issue by chew351** [kubernetes/kubernetes#97401]
here is my deployment

                                                       
client(cip)  <---------service(vip)-------|-----pod1 (rip1)  
                                                             
                                                          

when client init request to vip, ipvs will do dnat via rr to pods in backend and pods respose can snat to vip, then transfer 
is completed. but

when pod init request to client, service do MASQUERADE to snat source ip, this will snat the IP of interface which not vip to 
send to client, my expect is :
when pod init request, kube-proxy shall snat the request will vip.

does kube-proxy supported? if supported, what is the configuration

Thanks all
chew

**Comment by uablrek** [comment]
Short answer; No, egress VIPs are not supported in K8s.

There are several projects attempting to implement this e.g https://github.com/nirmata/kube-static-egress-ip, but they all have shortcomings. Some may work in your env though.

Usually public cloud providers have support for egress VIP in their own way, outside K8s. See for instance https://docs.microsoft.com/en-us/azure/aks/egress

I close this issue. If you want to influence K8s in this direction a Kubernetes Enhancement Proposal (KEP) is the way to go. Be warned however that a solution in K8s would have to be generic and work with all (at least almost all) CNI-plugins, which is _not_ simple.

IMHO this is better solved in the cloud-environment (see above) or may be supported by some CNI-plugins.

/close

**Comment by chew351** [comment]
> Short answer; No, egress VIPs are not supported in K8s.
> 
> There are several projects attempting to implement this e.g https://github.com/nirmata/kube-static-egress-ip, but they all have shortcomings. Some may work in your env though.
> 
> Usually public cloud providers have support for egress VIP in their own way, outside K8s. See for instance https://docs.microsoft.com/en-us/azure/aks/egress
> 
> I close this issue. If you want to influence K8s in this direction a Kubernetes Enhancement Proposal (KEP) is the way to go. Be warned however that a solution in K8s would have to be generic and work with all (at least almost all) CNI-plugins, which is _not_ simple.
> 
> IMHO this is better solved in the cloud-environment (see above) or may be supported by some CNI-plugins.
> 
> /close

Hi uablrek ,

  thanks for reply
 I use iptable to insert snat for my environment, it looks work well for me.

merry X'mas

chew
