### ISSUE TITLE
docker complains "Authentication is required" and fails to pull image when running k8s on local cluster

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#9742]
I use hack/local-cluster-up.sh to start a local cluster. Then I run example/k8pestore/k8petstore.sh, which starts several pods and pull images. Then docker complains "Authentication is required" and fails to pull the images. Furthermore, I cannot manually pull a docker image on the local machine. The docker on my local machine was v1.5.0. After I updated docker to v1.6.2, I can pull images manually, but k8s still cannot pull images due to the same "Authentication is required" problem.

@dchen1107 

Here is the kubelet.log: 
http://paste.ubuntu.com/11704524/

**Comment by sferich888** [comment]
This might be related to https://github.com/kubernetes/kubernetes/issues/2860

Have you reviewed https://github.com/kubernetes/kubernetes/wiki/User-FAQ and https://github.com/kubernetes/kubernetes/wiki/User-FAQ#how-do-i-pull-i

**Comment by yujuhong** [comment]
@caesarxuchao can we close this or are you still experiencing the bug after two years?

**Comment by caesarxuchao** [comment]
close due to age
