### ISSUE TITLE
Scale Down Behavior is ignored

### ISSUE THREAD

**Issue by rindoze** [kubernetes/kubernetes#97420]
**What happened**:
When using the scale down behavior "pods", the behavior is ignored. Period appears to be the default 15 seconds, and replicas are not scaled down by fixed pod amount as defined.

Annotations:                                                                <none>
CreationTimestamp:                                                          Tue, 17 Nov 2020 16:03:03 -0500
Reference:                                                                  Deployment/myDeployment
Metrics:                                                                    ( current / target )
  "myKakfkaTopic-myConsumer" (target average value):  <unknown> / 1
Min replicas:                                                               1
Max replicas:                                                               200
Behavior:
  Scale Up:
    Stabilization Window: 0 seconds
    Select Policy: Max
    Policies:
      - Type: Pods  Value: 200  Period: 1 seconds
  Scale Down:
    Stabilization Window: 300 seconds
    Select Policy: Max
    Policies:
      - Type: Pods  Value: 200  Period: 600 seconds
Deployment pods:    0 current / 0 desired
Conditions:
  Type            Status  Reason              Message
  ----            ------  ------              -------
  AbleToScale     True    SucceededGetScale   the HPA controller was able to get the target's current scale
  ScalingActive   False   ScalingDisabled     scaling is disabled since the replica count of the target is zero
  ScalingLimited  False   DesiredWithinRange  the desired count is within the acceptable range
Events:
  Type    Reason             Age                From                       Message
  ----    ------             ----               ----                       -------
  Normal  SuccessfulRescale  23m (x2 over 13h)  horizontal-pod-autoscaler  New size: 200; reason: external metric myKakfkaTopic-myConsumer(&LabelSelector{MatchLabels:map[string]string{scaledObjectName: myDeployment-scaledobject,},MatchExpressions:[]LabelSelectorRequirement{},}) above target
  Normal  SuccessfulRescale  3m26s              horizontal-pod-autoscaler  New size: 170; reason: All metrics below target
  Normal  SuccessfulRescale  3m11s              horizontal-pod-autoscaler  New size: 103; reason: All metrics below target
  Normal  SuccessfulRescale  2m55s              horizontal-pod-autoscaler  New size: 102; reason: All metrics below target
  Normal  SuccessfulRescale  2m40s              horizontal-pod-autoscaler  New size: 101; reason: All metrics below target
  Normal  SuccessfulRescale  2m24s              horizontal-pod-autoscaler  New size: 68; reason: All metrics below target
  Normal  SuccessfulRescale  114s               horizontal-pod-autoscaler  New size: 67; reason: All metrics below target
  Normal  SuccessfulRescale  99s                horizontal-pod-autoscaler  New size: 39; reason: All metrics below target
  Normal  SuccessfulRescale  69s                horizontal-pod-autoscaler  New size: 23; reason: All metrics below target

**What you expected to happen**:
Pods should scale down by 200 when threshold is met.

**How to reproduce it (as minimally and precisely as possible)**:
Create a scaler with the same behavior as defined

**Anything else we need to know?**:

      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Pods
            value: 200
            periodSeconds: 600
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type: Pods
            value: 200
            periodSeconds: 1 
          selectPolicy: Max  

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.3
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by umialpha** [comment]
Hi I think this is due to [Implicit maintenance-mode deactivation](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#implicit-maintenance-mode-deactivation).

**Comment by umialpha** [comment]
Hi from the logs you offered, I haven't found any misbehaviors. 

> Normal SuccessfulRescale 69s horizontal-pod-autoscaler New size: 23; reason: All metrics below target

From this line, hpa has set `scale.Spec.Replicas = desiredReplicas`

Could you offer more logs or completed hpa infos?

**Comment by rindoze** [comment]
The HPA's behavior is defined in the logs I had provided:
Scale Down:
Stabilization Window: 300 seconds
Select Policy: Max
Policies:
- Type: Pods Value: 200 Period: 600 seconds

As I understand from this defined behavior the HPA _should_ scale replicas from 200 down to 0 in 1 scaling operation. Instead it is gradually down scaling and doing it every 15 seconds instead of 10 minutes.

**Comment by umialpha** [comment]
Oh, I think you misunderstand "Type: Pods Value: 200 Period: 600 seconds" meaning. It means for 600 seconds, it could remove **at most** 200 pods :).

**Comment by rindoze** [comment]
It appears that even with a shorter period, the scale down behavior still is ignored:

Reference:                                                                  Deployment/myDeployment
Metrics:                                                                    ( current / target )
  "myKakfkaTopic-myConsumer" (target average value):  0 / 1
Min replicas:                                                               1
Max replicas:                                                               200
Behavior:
  Scale Up:
    Stabilization Window: 0 seconds
    Select Policy: Max
    Policies:
      - Type: Pods  Value: 200  Period: 1 seconds
  Scale Down:
    Stabilization Window: 300 seconds
    Select Policy: Max
    Policies:
      - Type: Pods  Value: 200  Period: 15 seconds
Deployment pods:    1 current / 1 desired
Conditions:
  Type            Status  Reason               Message
  ----            ------  ------               -------
  AbleToScale     True    ScaleDownStabilized  recent recommendations were higher than current one, applying the highest recent recommendation
  ScalingActive   True    ValidMetricFound     the HPA was able to successfully calculate a replica count from external metric myKakfkaTopic-myConsumer(&LabelSelector{MatchLabels:map[string]string{scaledObjectName: myDeployment-scaledobject,},MatchExpressions:[]LabelSelectorRequirement{},})
  ScalingLimited  False   DesiredWithinRange   the desired count is within the acceptable range
Events:
  Type    Reason             Age                  From                       Message
  ----    ------             ----                 ----                       -------
  Normal  SuccessfulRescale  8m54s (x2 over 19h)  horizontal-pod-autoscaler  New size: 8; reason: external metric myKakfkaTopic-myConsumer(&LabelSelector{MatchLabels:map[string]string{scaledObjectName: myDeployment-scaledobject,},MatchExpressions:[]LabelSelectorRequirement{},}) above target
  Normal  SuccessfulRescale  95s                  horizontal-pod-autoscaler  New size: 7; reason: All metrics below target
  Normal  SuccessfulRescale  80s                  horizontal-pod-autoscaler  New size: 6; reason: All metrics below target
  Normal  SuccessfulRescale  64s                  horizontal-pod-autoscaler  New size: 5; reason: All metrics below target
  Normal  SuccessfulRescale  31s                  horizontal-pod-autoscaler  New size: 4; reason: All metrics below target
  Normal  SuccessfulRescale  11s                  horizontal-pod-autoscaler  New size: 1; reason: All metrics below target

**Comment by umialpha** [comment]
> Oh, I think you misunderstand "Type: Pods Value: 200 Period: 600 seconds" meaning. It means for 600 seconds, it could remove **at most** 200 pods :).

Hi, it means it removes **at most** 200 pods. From the [algorithm](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#algorithm-details),  the new size "7", "6", etc. not "1".
