### ISSUE TITLE
kubectl fails to apply strategic merge patch to custom resource

### ISSUE THREAD

**Issue by caboteria** [kubernetes/kubernetes#97423]
**What happened**:
Attempting to add a finalizer to a custom resource using a strategic merge patch fails:

```
$ kubectl patch --type=strategic foos.samplecontroller.k8s.io example-foo -p '{"metadata":{"finalizers": ["sample.acnodal.io/fooFinalizer"]}}'
Error from server (UnsupportedMediaType): the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json, application/apply-patch+yaml
```
kubectl sends the request with a media type (`application/strategic-merge-patch+json`) that the server rejects:
```
I1221 11:05:25.909248  168287 request.go:1107] Request Body: {"metadata":{"finalizers": ["sample.acnodal.io/fooFinalizer"]}}
I1221 11:05:25.909366  168287 round_trippers.go:422] PATCH https://192.168.1.40:6443/apis/samplecontroller.k8s.io/v1alpha1/namespaces/default/foos/example-foo?fieldManager=kubectl-patch
I1221 11:05:25.909387  168287 round_trippers.go:429] Request Headers:
I1221 11:05:25.909403  168287 round_trippers.go:433]     Accept: application/json
I1221 11:05:25.909416  168287 round_trippers.go:433]     Content-Type: application/strategic-merge-patch+json
I1221 11:05:25.909433  168287 round_trippers.go:433]     User-Agent: kubectl/v1.20.1 (linux/amd64) kubernetes/c4d7527
I1221 11:05:25.913937  168287 round_trippers.go:448] Response Status: 415 Unsupported Media Type in 4 milliseconds
I1221 11:05:25.913967  168287 round_trippers.go:451] Response Headers:
I1221 11:05:25.913983  168287 round_trippers.go:454]     Cache-Control: no-cache, private
I1221 11:05:25.913994  168287 round_trippers.go:454]     Content-Type: application/json
I1221 11:05:25.914001  168287 round_trippers.go:454]     X-Kubernetes-Pf-Flowschema-Uid: 82d5ee12-c69e-46d0-96e3-4907c57bde7d
I1221 11:05:25.914014  168287 round_trippers.go:454]     X-Kubernetes-Pf-Prioritylevel-Uid: ae04b648-f87e-4232-b3eb-2e0365ed3f7d
I1221 11:05:25.914022  168287 round_trippers.go:454]     Content-Length: 293
I1221 11:05:25.914029  168287 round_trippers.go:454]     Date: Mon, 21 Dec 2020 16:05:25 GMT
I1221 11:05:25.914064  168287 request.go:1107] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json, application/apply-patch+yaml","reason":"UnsupportedMediaType","code":415}
I1221 11:05:25.914432  168287 helpers.go:216] server response object: [{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json, application/apply-patch+yaml",
  "reason": "UnsupportedMediaType",
  "code": 415
}]
F1221 11:05:25.914487  168287 helpers.go:115] Error from server (UnsupportedMediaType): the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json, application/apply-patch+yaml

```

**What you expected to happen**:
kubectl sends the patch with a media type that the server accepts.

**How to reproduce it (as minimally and precisely as possible)**:
Apply the example custom resource definition from the sample controller project:
```
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/sample-controller/master/artifacts/examples/crd.yaml
```
Create a sample custom resource:
```
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/sample-controller/master/artifacts/examples/example-foo.yaml
```
Attempt to patch the CR:
```
$ kubectl patch --type=strategic foos.samplecontroller.k8s.io example-foo -p '{"metadata":{"finalizers": ["sample.acnodal.io/fooFinalizer"]}}'
Error from server (UnsupportedMediaType): the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json, application/apply-patch+yaml
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:00:47Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: libvirt virtual machine
- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
- Kernel (e.g. `uname -a`):
Linux egw 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
/assign 
Will look into this.

**Comment by pacoxu** [comment]
```
[root@daocloud ~]# kubectl patch --type=strategic foos.samplecontroller.k8s.io example-foo -p '{"metadata":{"finalizers": ["sample.acnodal.io/fooFinalizer"]}}' --dry-run=client
error: cannot apply strategic merge patch for samplecontroller.k8s.io/v1alpha1, Kind=Foo locally, try --type merge
[root@daocloud ~]#
[root@daocloud ~]# kubectl patch --type=strategic foos.samplecontroller.k8s.io example-foo -p '{"metadata":{"finalizers": ["sample.acnodal.io/fooFinalizer"]}}' --dry-run=server
Error from server (UnsupportedMediaType): the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json, application/apply-patch+yaml
[root@daocloud ~]#
[root@daocloud ~]# kubectl patch --type=merge foos.samplecontroller.k8s.io example-foo -p '{"metadata":{"finalizers": ["sample.acnodal.io/fooFinalizer"]}}'
foo.samplecontroller.k8s.io/example-foo patched
```

When you run it with `--dry-run=client`, it suggests to use --type=merge and it works. 

- `--type= strategic` uses `-H "Content-Type: application/strategic-merge-patch+json"`
- `--type= merge`  uses `-H "Content-Type: application/merge-patch+json"`

**Comment by pacoxu** [comment]
@neolit123 This seems to work as expected. 
Do you think we need to make the server response more friendly as the message of `kubectl client --dry-run=client`.

**Comment by caboteria** [comment]
Thank you, Paco, for looking into this!

The problem is that merge patch is unable to do some important operations (for example, safely removing a finalizer from an object's metadata) so it's not a substitute for strategic merge.

The error message suggesting that the client switch to merge patch is unhelpful, but a clear message indicating that strategic merge patch is unsupported *would* be helpful, and documentation that strategic merge patch is unsupported for Custom Resource objects would also be helpful. For most use cases the proper workaround is update with retry, not merge patch.

Thank you!

**Comment by neolit123** [comment]
> The error message suggesting that the client switch to merge patch is unhelpful, but a clear message indicating that strategic merge patch is unsupported would be helpful, and documentation that strategic merge patch is unsupported for Custom Resource objects would also be helpful. For most use cases the proper workaround is update with retry, not merge patch.

this is topic for sig api machinery.
/sig api-machinery

**Comment by nikhita** [comment]
> @neolit123 @nikhita This seems to work as expected.
Do you think we need to make the server response more friendly as the message of kubectl client --dry-run=client.

Apologies for the really late response on this. I've created https://github.com/kubernetes/kubernetes/pull/99143 to improve the message.

/assign
