### ISSUE TITLE
The Kubectl Reference Guide for the kubectl run command incorrectly specifies that a deployment or job can be created by specifying --restart=OnFailure, or --restart=Never respectively.

### ISSUE THREAD

**Issue by ryan-chase** [kubernetes/kubernetes#97426]
The Kubectl Reference Guide for the kubectl run command (https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#run), has incorrect information provided for the --restart flag specifically. The page says:

The restart policy for this Pod. Legal values [Always, OnFailure, Never]. If set to 'Always' a deployment is created, if set to 'OnFailure' a job is created, if set to 'Never', a regular pod is created. For the latter two --replicas must be 1. Default 'Always', for CronJobs Never.

...however, running each of the following commands returns kind: Pod :

kubectl run nginx --image=nginx --restart=Never --dry-run=client - o yaml | grep kind
kubectl run nginx --image=nginx --restart=Always --dry-run=client - o yaml | grep kind
kubectl run nginx --image=nginx --restart=OnFailure --dry-run=client - o yaml | grep kind

**Comment by Clivern** [comment]
I can see the docs got updated https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#run to `--restart='Always': The restart policy for this Pod.  Legal values [Always, OnFailure, Never].`

kubectl too since it used to be like this

```bash
$ kubectl run --help

    ... etc

    --restart='Always': The restart policy for this Pod.  Legal values [Always, OnFailure, Never].  If set to 'Always'
a deployment is created, if set to 'OnFailure' a job is created, if set to 'Never', a regular pod is created. For the
latter two --replicas must be 1.  Default 'Always', for CronJobs `Never`.
```

If u update to latest version

```bash
$ kubectl run --help
    
    ....etc

      --restart='Always': The restart policy for this Pod.  Legal values [Always, OnFailure, Never].
```
Do u think something still missing @ryan-chase or this can be closed?

**Comment by dougsland** [comment]
No answer more than 20 days, closing for now. 
/close
