### ISSUE TITLE
Fix comments and describe PodCache and K8sModel in netpol tests

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#97425]
**What happened**:

minor issue but we should improve the comments on the netpol framework tests. @mattfenwick , esp the lifecycle around pod cache clearing, and the godoc for `getK8sModel` which is stateless.

**What you expected to happen**:

the `getK8sModel` comments would dovetail with the idempotency of how we get the networkpolicy abstract model and poll around it.

**Environment**:
- Kubernetes version (use `kubectl version`): master

**Comment by jayunit100** [comment]
cc @mattfenwick can you do this in a follow on to #91592   ?

**Comment by mattfenwick** [comment]
Yes np @jayunit100 !
