### ISSUE TITLE
ResourceQuota at the cluster level support?

### ISSUE THREAD

**Issue by Belyenochi** [kubernetes/kubernetes#97436]
I would like to ask how to restrict reasourceQuota at the cluster level instead of the namespace level (because there are multiple clusters sharing etcd),thx~

**Comment by Belyenochi** [comment]
sig/cluster-lifecycle

**Comment by neolit123** [comment]
you should use the support channels for this:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/remove-sig cluster-lifecycle
/close
