### ISSUE TITLE
Creation of cluterip fails due to quota on nodeports

### ISSUE THREAD

**Issue by b10s** [kubernetes/kubernetes#97437]
Having 2 services of type nodeports I do set a hard quota limiting services.nodeports to 0.
Then I'm failing to create clusterip service with error:
```
$ k create svc clusterip cip --tcp=1234:1234
Error from server (Forbidden): services "cip" is forbidden: exceeded quota: default-quota, requested: services.nodeports=0, used: services.nodeports=2, limited: services.nodeports=0
```
Do I understand right that the creation of clusterip service requires 0 services of nodeports, therefore in total, taking in account 2 already existed, I exceed the quota?
If so why clusterip requires 0 services of nodeports ?

Is it seems as a bug or there is some rationale behind?

**Environment**:
all k8s versions, any env including minikube

**Comment by pacoxu** [comment]
It only happens when you create  quota after nodeports was created.


Per https://kubernetes.io/docs/concepts/policy/resource-quotas/#enabling-resource-quota 
```
Neither contention nor changes to quota will affect already created resources.
```

**Comment by b10s** [comment]
@pacoxu I see.  Why clusterip requires 0 services of nodeports ?

**Comment by pacoxu** [comment]
`kubectl describe quota ` and `kubectl get quota -o yaml` in your namespace to see the resource quota.

**Comment by pacoxu** [comment]
Still the link above https://kubernetes.io/docs/concepts/policy/resource-quotas/


name | descriptions
-- | --
services | The total number of Services that can exist in the namespace.
services.loadbalancers | The total number of Services of type LoadBalancer that can exist in the namespace.
services.nodeports | The total number of Services of type NodePort that can exist in the namespace.

**Comment by b10s** [comment]
The way to reproduce is below. You can try on latest k8s on minikube.

```
$ minikube start
..
$ k create svc nodeport svc1 --tcp=1234:1234
service/svc1 created

$ k create svc nodeport svc2 --tcp=1234:1234
service/svc2 created

$ k create -f /tmp/q.yml 
resourcequota/default-quota created

$ k create svc clusterip cip --tcp=1234:1234
Error from server (Forbidden): services "cip" is forbidden: exceeded quota: default-quota, requested: services.nodeports=0, used: services.nodeports=2, limited: services.nodeports=0
```

/tmp/q.yml  is:
```
$ cat /tmp/q.yml 
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-quota
  namespace: default
spec:
  hard:
    services.nodeports: "0"
```

**Comment by pacoxu** [comment]
what's your expectation?

**Comment by b10s** [comment]
To be able to create a `clusterip` service since I have limited only `nodeports`

**Comment by pacoxu** [comment]
/assign 

It seems to be an admission controller bug in 

https://github.com/kubernetes/kubernetes/blob/cea1d4e20b4a7886d8ff65f34c6d4f95efcb4742/staging/src/k8s.io/apiserver/pkg/admission/plugin/resourcequota/controller.go#L393
evaluator is set to the cluster ip service's group resource service.

It matches with the nodeport quota as well.
https://github.com/kubernetes/kubernetes/blob/cea1d4e20b4a7886d8ff65f34c6d4f95efcb4742/staging/src/k8s.io/apiserver/pkg/admission/plugin/resourcequota/controller.go#L449-L453

I will bring a pr for this ASAP.

**Comment by b10s** [comment]
@pacoxu thank you for fast reaction!

**Comment by yliaog** [comment]
https://github.com/kubernetes/kubernetes/issues/73628

**Comment by yliaog** [comment]
please see the discussion in the issue #73628
