### ISSUE TITLE
When a pod has more than one container, it cannot resolve the FQDN domain name

### ISSUE THREAD

**Issue by ktpktr0** [kubernetes/kubernetes#97434]
k8s version: 1.17.3
docker version: 19.03

Recently, when using STS to deploy applications, I found that when a pod has only one container, I can get the IP of the pod through the dig command; when a pod has two containers, I can't use the dig command to get the IP of the pod. Here are the details:

1、When there is only one container in the pod

![image](https://user-images.githubusercontent.com/41657218/102837506-deb10d00-4436-11eb-9470-7dc1d46dd3eb.png)

2.、When there are two containers in the pod
![image](https://user-images.githubusercontent.com/41657218/102837475-cfca5a80-4436-11eb-9a53-b81fec9024b1.png)
![image](https://user-images.githubusercontent.com/41657218/102837492-d789ff00-4436-11eb-9f2a-d4419fbea490.png)

**Comment by pacoxu** [comment]
is this a coredns issue? 
Would you open an issue on https://github.com/coredns/coredns/issues?

**Comment by aojea** [comment]
/sig network
ping @chrisohaver

**Comment by ktpktr0** [comment]
@紫杉 I've found the cause of the problem. When a pod has multiple containers (STS deployment mode) and only one SVC, dig is used to resolve the FQDN domain name. The back-end does not know which container needs to be accessed, so there is no IP return. When I configure a separate SVC for each container, the dig command can normally resolve the FQDN domain name.

**Comment by chrisohaver** [comment]
A StatefulSet and a Pod with multiple containers are unrelated:  Any Pod can have multiple containers regardless of how it was deployed.  And a StatefulSet can create Pods with a single container or multiple containers.  

CoreDNS builds FQDN records for Pods (endpoints) based on Endpoints objects in Kubernetes.   Endpoints objects are usually created by Kubernetes based on the Service's `selector`. If the Endpoints objects do not exist for a given Service CoreDNS will not produce records for it.

I suspect in this case the Service not selecting the StatefulSet's Pods via the `selector` in the Service's spec.

@ktpktr0, can you share your Service and StatefulSet definitions?

**Comment by ktpktr0** [comment]
`apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
  name: redis
  namespace: redis-cluster
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
  - name: prom
    port: 9121
    targetPort: 9121
  clusterIP: None
  
---
apiVersion: v1
kind: Service
metadata:
  name: redis-access
  namespace: redis-cluster
  labels:
    app: redis
spec:
  selector:
    app: redis
    appCluster: redis-cluster
  ports:
  - name: redis-access
    protocol: TCP
    port: 6379
    targetPort: 6379

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis-cluster
  annotations:
    prometheus.io/scrape: 'true'
spec:
  serviceName: redis
  replicas: 6
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 20
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - redis
              topologyKey: kubernetes.io/hostname
      containers:
      - name: redis
        image: redis:latest
        imagePullPolicy: IfNotPresent
        command:
          - "redis-server"
        args:
          - "/etc/redis/redis.conf"
          - "--protected-mode"
          - "no"
        resources:
          requests:
            cpu: "200m"
            memory: "200Mi"
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        - containerPort: 16379
          name: cluster
          protocol: TCP
        volumeMounts:
        - name: conf
          mountPath: /etc/redis
        - name: data
          mountPath: /var/lib/redis
      - name: redis-exporter
        image: oliver006/redis_exporter:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9121
      volumes:
      - name: conf
        configMap:
          name: redis-conf
          items:
          - key: redis.conf
            path: redis.conf
  volumeClaimTemplates:
  - metadata:
      name: data
      namespace: redis-cluster
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 1Gi`

**Comment by ktpktr0** [comment]
@chrisohaver Thank you for your help。Each condition in the selector needs to be met before endpoints can be created successfully, that is, the value is not < none > and
