### ISSUE TITLE
Azure legacy-cloud-provider incorrectly removes nodes from LB backend pools

### ISSUE THREAD

**Issue by staebler** [kubernetes/kubernetes#97467]
**What happened**:
When creating a service, the Azure legacy-cloud-provider attempts to remove nodes that do not match the labels for the service from the backend pool of the standard loadbalancer. This behavior should only happen when
1) the provider is configured to use multiple loadbalancers, 
2) the node is labeled with node.kubernetes.io/exclude-from-external-load-balancers, and
3) the ServiceNodeExclusion feature gate is on.

**What you expected to happen**:
The Azure legacy-cloud-provider skips the code for removing nodes from the backend pool when using a single standard LB.
https://github.com/kubernetes/kubernetes/blob/d815833a308b7c37389218f712511f6713a47570/staging/src/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go#L1124-L1158

**How to reproduce it (as minimally and precisely as possible)**:
1) Add a label *L* on one node.
2) Create a Service associated with nodes that have the label *L*.
3) Observe that the Azure legacy-cloud-provider attempts to remove nodes without the label *L* from the backend pool of the single standard LB.

**Anything else we need to know?**:
This is seen on every install attempt of OpenShift 4.7.
This was introduced in https://github.com/kubernetes/kubernetes/pull/95542.
/cc @nilo19 

**Environment**:
- Kubernetes version (use `kubectl version`): v1.20
- Cloud provider or hardware configuration: Azure
- Install tools: OpenShift 4.7

/kind bug
/sig cloud-provider
/area provider/azure

**Comment by feiskyer** [comment]
@staebler have you enabled `enableMultipleStandardLoadBalancers` when observed this issue?

**Comment by staebler** [comment]
> @staebler have you enabled `enableMultipleStandardLoadBalancers` when observed this issue?

No

**Comment by feiskyer** [comment]
@staebler thanks, could you share the details of repro steps 1 and 2?

**Comment by feiskyer** [comment]
Kindly ping @staebler. Do you have the detailed steps of repro?

**Comment by feiskyer** [comment]
I'm closing this issue since there's no update for a long time. @staebler feel free to reopen if you still see the same issue.

/close
