### ISSUE TITLE
Potential runtime error:  "negative WaitGroup counter" in NodeMapper.GenerateNodeMap()

### ISSUE THREAD

**Issue by nicolasdilley** [kubernetes/kubernetes#97461]
**What happened**:

I think that there is a potential runtime error in method `NodeMapper.GenerateNodeMap()` at lines 62-142 in [test/e2e/storage/vsphere/nodemapper.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/vsphere/nodemapper.go#L62). 

The bug can arise when `len(nodeList.Item) > 0` and the goroutine spawned at [line 110](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/vsphere/nodemapper.go#L110) calls `wg.Done()` before the main goroutine executes `wg.Add(1)` in the first iteration of the range statement at [line 134](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/vsphere/nodemapper.go#L134).  
In which case, you would get the following `error: panic: sync: negative WaitGroup counter`

I have found this bug with my tool [Gomela](https://github.com/nicolasdilley/gomela) which is a static analyser for concurrent Go programs. I hope you find this useful!

**What you expected to happen**:
A potential fix would be to move the line `wg.Add(1)` before spawning the goroutine at line 110. 

**How to reproduce it (as minimally and precisely as possible)**:
(See above)

**Anything else we need to know?**:
NA

**Environment**:
Run static analyser [Gomela](https://github.com/nicolasdilley/gomela) on branch [3aa59f7](https://github.com/kubernetes/kubernetes/commit/3aa59f7f3077642592dc8a864fcef8ba98699894)

**Comment by BenTheElder** [comment]
/sig storage
/remove-sig testing
either the VMware group under SIG cloud provider or SIG storage own these tests, SIG testing own the test frameworks and CI infrastructure.

**Comment by bl-ue** [comment]
Darn.  Not enough resources, no attention :(
