### ISSUE TITLE
Add networkPolicy test for ingress/egress rule combination

### ISSUE THREAD

**Issue by NillsF** [kubernetes/kubernetes#97489]
[In reference to conversation on #sig-network-policy-api. 
](https://kubernetes.slack.com/archives/C01CWSHQWQJ/p1608751193216700)
**What would you like to be added**:
Add a test to the netpol validation framework to validate a scenario where traffic between two pods has egress and ingress rules defined.

|       | **Ingress allowed**     | **Ingress denied**     |
| :------------- | :----------: | :-----------: |
|  **Egress allowed** | Allow   | Deny    |
| **Egress denied**  | Deny | Deny |

**Why is this needed**:
To ensure consistent behavior between different implementations of networkPolicy. For example, [this issue](https://github.com/Azure/AKS/issues/1158) describes different behavior between Calico networkPolicy and Azure networkPolicy

@jayunit100 @neaggarwMS

**Comment by jayunit100** [comment]
@NillsF thanks for offering to hack on this

**Comment by jayunit100** [comment]
cc @mattfenwick

**Comment by NillsF** [comment]
@jayunit100 I reviewed the current networkpolicy tests, and I believe this case is already captured in the currents tests. 

https://github.com/kubernetes/kubernetes/blob/9858bc2925c5894b46c1f01df231818ea868387f/test/e2e/network/netpol/network_policy.go#L589-L625

**Comment by jayunit100** [comment]
I think you want to do `Egress rules take precedent over Ingress rules`, right?   In that case, 
- Egress rule is *specifically* created that disallows `x/a->y/` but  
- Ingress rules explicitly allow `x/a->y/`
- And the result is that Egress wins, and traffic is blocked

**Comment by mattfenwick** [comment]
This is an interesting test case, I'd be happy to hack on this and look at adding a table-driven netpol test case but don't want to step on your toes if you're already looking into @NillsF @jayunit100 !  Definitely see the value of illuminating this corner case with a clear test scenario!

**Comment by NillsF** [comment]
Thx @jayunit100 for the feedback. You are right that it's still a different case. 

@mattfenwick : I'm looking at what I can throw together today. Stay tuned, and would love your input.

**Comment by NillsF** [comment]
[I created the initial version of the test. 
](https://github.com/NillsF/kubernetes/blob/4428df27346f7d110eb2c8b51bd9997f6b948ee1/test/e2e/network/netpol/network_policy.go#L626-L696)

The code (and comments) are likely a bit verbose at this point.

Should I open a PR against this repo now, or do you want me to make changes to that code prior to the PR?

**Comment by mattfenwick** [comment]
Looks awesome, I'd go ahead with the PR!

**Comment by jayunit100** [comment]
can you reference this issue in your new PR @NillsF ?
