### ISSUE TITLE
Dynamic storage is unavailable due to the removal of SelfLink

### ISSUE THREAD

**Issue by zhuchance** [kubernetes/kubernetes#97484]
**What happened**:
 I am seeing the issue that since installing the latest version (v1.20.1) I have the problem that my 'testclaim' pvc is no longer able to claim storage from the storageclass (managed-nfs-storage), which worked fine before 1.20.1

**What you expected to happen**:
I want to be able to use dynamic storage，such as NFS, OpenEBS

**How to reproduce it (as minimally and precisely as possible)**:

Apply the example custom resource definition from the sample controller project:

kubectl apply -f https://github.com/kubernetes-retired/external-storage/blob/master/nfs-client/deploy/deployment.yaml

kubectl logs -f nfs-client-provisioner-64597768d6-7jws4 
I1223 07:26:44.544567       1 leaderelection.go:185] attempting to acquire leader lease  default/fuseim.pri-ifs...
E1223 07:27:01.969864       1 event.go:259] Could not construct reference to: '&v1.Endpoints{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"fuseim.pri-ifs", GenerateName:"", Namespace:"default", SelfLink:"", UID:"b5a42eb2-9b14-4ab8-9114-c5e625cfe73a", ResourceVersion:"164217", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63744226452, loc:(*time.Location)(0x1956800)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"control-plane.alpha.kubernetes.io/leader":"{\"holderIdentity\":\"nfs-client-provisioner-64597768d6-7jws4_3581561e-44f0-11eb-8f64-0e9e382e10fd\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2020-12-23T07:27:01Z\",\"renewTime\":\"2020-12-23T07:27:01Z\",\"leaderTransitions\":5}"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Subsets:[]v1.EndpointSubset(nil)}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'LeaderElection' 'nfs-client-provisioner-64597768d6-7jws4_3581561e-44f0-11eb-8f64-0e9e382e10fd became leader'
I1223 07:27:01.970024       1 leaderelection.go:194] successfully acquired lease default/fuseim.pri-ifs
I1223 07:27:01.970129       1 controller.go:631] Starting provisioner controller fuseim.pri/ifs_nfs-client-provisioner-64597768d6-7jws4_3581561e-44f0-11eb-8f64-0e9e382e10fd!
I1223 07:27:02.070407       1 controller.go:680] Started provisioner controller fuseim.pri/ifs_nfs-client-provisioner-64597768d6-7jws4_3581561e-44f0-11eb-8f64-0e9e382e10fd!
I1223 07:27:21.772763       1 controller.go:987] provision "test/test-mysql-claim" class "managed-nfs-storage": started
E1223 07:27:21.774802       1 controller.go:1004] provision "test/test-mysql-claim" class "managed-nfs-storage": unexpected error getting claim reference: selfLink was empty, can't make reference

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
kubernetes version :v1.20.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
Linux localhost.localdomain 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
kubeasz
- Network plugin and version (if this is a network-related bug):
flannel
- Others:

**Comment by pacoxu** [comment]
https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/25#issuecomment-742616668 

Add the feature gate would help.
```
- --feature-gates=RemoveSelfLink=false
```

**Comment by wojtek-t** [comment]
@zhuchance  - what version of the provisioner you're using?

Assuming I'm not missing something, this has already been fixed quite long time ago in newer versions of the provisioner.
Ref https://github.com/kubernetes/kubernetes/issues/81403
Ref https://github.com/kubernetes/kubernetes/pull/81620

**Comment by wojtek-t** [comment]
@msau42 - FYI

**Comment by msau42** [comment]
We fixed this for csi provisioner but not the deprecated provisioners in external-storage. We migrated 4 of the provisioners to new repos: nfs-subdir-external-provisioner, nfs-ganesha-external-provisioner, gluster-file-external-provisioner and gluster-block-external-provisioner. Those repos need to be updated similarly like:
https://github.com/kubernetes-csi/external-provisioner/pull/323

@kmova @humblec can you handle updating those repos?

**Comment by msau42** [comment]
Oh actually, https://github.com/kubernetes/kubernetes/pull/81620 was already done for the old external-storage repo. We need to check why this didn't get propagated when we migrated them to the new repos.

**Comment by msau42** [comment]
Ah, it is because https://github.com/kubernetes-retired/external-storage/pull/1208/files only updated nfs ganesha provisioner, and not the subdir one.

**Comment by wojtek-t** [comment]
@msau42 - can I assign it to you for coordination, I'm not familiar with all provisioners (I though we did for all), so we need someone familiar with that.

**Comment by msau42** [comment]
/assign

Yes, I'll work with @kmova to make the fix.

**Comment by wojtek-t** [comment]
Thank you!

**Comment by pacoxu** [comment]
/remove-lifecycle stale
@kmova @msau42 
any update? or I may take a look. 😄

**Comment by msau42** [comment]
This has been addressed in https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/26.

So this should be fixed.

/close
