### ISSUE TITLE
AKS Upgrade to 1.19 Causing my complete environment down. Containerd is failing to load my PODS which runs on side car 

### ISSUE THREAD

**Issue by SamaChandra** [kubernetes/kubernetes#97481]
**What happened**:Upgraded from Azure Kubernetes Version 1.18.10 to 1.19.03

**What you expected to happen**:All micro services should work as how they are working earlier.

**How to reproduce it (as minimally and precisely as possible)**:I am unable to reproduce or do any changes now. the total cluster was down due to this containerd.

**Anything else we need to know?**:My whole cluster is down which is a high priority issue.

**Environment**: Production Environment 
- Kubernetes version (use `kubectl version`): 1.19.03
- Kubernetes version (use kubectl version): Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T07:38:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-16T20:43:08Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: Azure Kubernetes Version  containerd://1.4.1+azure
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.5
- Kernel (e.g. `uname -a`): LTS 5.4.0-1032-azure 
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:There are total 25 micro-services failed as "Back off restarting failed container" , We have Consul service mesh sider car proxy container and consul-connect-inject acl token container to create mTLS certificates fetch from vault. There is a connectivity from Ambassador Endpoint API gateway to consul resolveer.
![ambassador2](https://user-images.githubusercontent.com/68558191/102958483-fd50eb80-44aa-11eb-94cd-667fb92c9c27.jpeg)
![Ambassador](https://user-images.githubusercontent.com/68558191/102958486-fe821880-44aa-11eb-9835-b9945c598f1e.jpeg)

![image](https://user-images.githubusercontent.com/68558191/102958494-0477f980-44ab-11eb-97bb-98d77f55b061.png)

**Comment by neolit123** [comment]
> Upgraded from Azure Kubernetes Version 1.18.10 to 1.19.03

you should first contact AKS support.
if they confirm this is a core k8s bug, re-open this issue.

you can also chat to other users on these channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
