### ISSUE TITLE
【not support ????】How to pass different arguments to different pod in Job resource?

### ISSUE THREAD

**Issue by zhangxiao696** [kubernetes/kubernetes#97504]
When I created a job in Kubernetes, I want to pass different arguments to different pod, so that I can execute different command in different pod.
But I think that It's not supported in Kubernetes now.

So is there any method?

**Comment by victor-timofei** [comment]
If I understood correctly on a job creation, you also want to run a specific command on an already running pod?
AFAIK there's no such feature.
/sig api-machinery

**Comment by umialpha** [comment]
You can put different args into a queue and pods fetch args from the queue.

**Comment by holooooo** [comment]
Job is a stateless workload，maybe you need start multiple job. Or start a standalone queue for parallel execute job https://kubernetes.io/zh/docs/tasks/job/coarse-parallel-processing-work-queue/#%E5%AE%9A%E4%B9%89-job
