### ISSUE TITLE
kubectl logs --all-containers --previous - failure to report all logs before erroring

### ISSUE THREAD

**Issue by consideRatio** [kubernetes/kubernetes#97530]
**What happened**:

Running `kubectl logs --all-containers --previous <pod name>` on a pod with two containers, of which one has restarted but the other hasn't results in a undesired behavior.

I get an inconsistent outcome, sometimes just a report of `Error from server (BadRequest): previous terminated container "<container name>" in pod "<pod name>" not found`, other times I get the other containers logs followed by the error.

**What you expected to happen**:

I expect to get to see the full response of all containers, even though one container without any --previous logs throwed an error.

**How to reproduce it (as minimally and precisely as possible)**:

```shell
# 1. Create a pod with two containers, where one may error
kubectl create deployment --image=bash random-crash --dry-run=client -o yaml -- bash -c "echo reliable && sleep infinity" | kubectl patch --dry-run=client -o yaml -f=- --type=json --patch='[{"op": "replace", "path": "/spec/template/spec/terminationGracePeriodSeconds", "value": 0}, {"op": "add", "path": "/spec/template/spec/containers/1", "value": {"name": "error-container", "image": "bash", "command": ["bash", "-c", "echo unreliable; [ ${RANDOM:2:1} -lt 4 ] && exit 1 || sleep infinity"]}}]' | kubectl apply -f-

# 2.1 Inspect if one container randomly crashed
kubectl get pod random-crash-...

# 2.2 If not, restart and go back to 2.1
kubectl rollout restart deploy/random-crash

# 3. Observe failure to report all logs before erroring, except sometimes...
#    Run this multiple times to observe that you can get "unreliable" showing up
#    sometimes but othertimes not because the error is thrown.
kubectl logs --all-containers --previous deploy/random-crash
```

The output can look like this...

```shell
$ kubectl logs random-crash-6bbd8c9c66-4vksf --all-containers --previous
Error from server (BadRequest): previous terminated container "bash" in pod "random-crash-6bbd8c9c66-4vksf" not found

$ kubectl logs random-crash-6bbd8c9c66-4vksf --all-containers --previous
unreliable
Error from server (BadRequest): previous terminated container "bash" in pod "random-crash-6bbd8c9c66-4vksf" not found
```

**Anything else we need to know?**:

The `--ignore-errors` flag by itself ("If watching / following pod logs, allow for any errors that occur to be non-fatal") doesn't influence this, but a workaround is to use `--follow --ignore-errors` to be able to see the full output.

- Kubernetes version (use `kubectl version`):
  ```
  Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.13-gke.2001", GitCommit:"00c919adfe4adf308bcd7c02838f2a1b60482f02", GitTreeState:"clean", BuildDate:"2020-11-06T18:24:02Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Cloud provider or hardware configuration: GKE
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04
- Kernel (e.g. `uname -a`): 5.4.0-58-generic

**Comment by bl-ue** [comment]
@consideRatio do you have an example yaml file to create these containers?

**Comment by consideRatio** [comment]
@bl-ue yikes I feared I'd be asked this question :) Well, I provided a minimal example in the original post.

**Comment by bl-ue** [comment]
@consideRatio Thank you very much.  I'll take a look.

**Comment by bl-ue** [comment]
Hmm... @consideRatio I can replicate this issue with the example you provided.  Very explanatory instructions! 👍 I'll investigate tomorrow.

**Comment by navist2020** [comment]
@consideRatio I used the example to reproduce this issue. Created pod through above. The state of pod is Running. I guess the reason is that none of the containers in pod have Terminated state.Only when one of containers is Terminated. The param --previous will return the result normally.
https://github.com/kubernetes/kubernetes/blob/0a839c6c3b9489716e216b4fc9dd2f9c17948c16/pkg/kubelet/kubelet_pods.go#L1288-L1291

**Comment by bl-ue** [comment]
@consideRatio @navist2020 looking at these lines...

https://github.com/kubernetes/kubernetes/blob/4425569da6f252dccb15ee8244a33df908e958b6/staging/src/k8s.io/kubectl/pkg/cmd/logs/logs.go#L319-L337

...I discovered that adding the `--follow` option significantly increases the frequency that the "bash" container's logs are printed (the numbers are how many times `unreliable` was printed out of 100 `kubectl` runs):
```console
$ function try_follow { for i in {0..$1}; do kubectl logs --previous deploy/random-crash --all-containers --follow; done |& grep -i unreliable | wc -l }
$ function try_nofollow { for i in {0..$1}; do kubectl logs --previous deploy/random-crash --all-containers; done |& grep -i unreliable | wc -l }
$ for i in {0..20}; do try_nofollow 100; done
      18
      10
      13
       9
      12
      11
      15
      17
       9
      12
      12
      11
      11
      15
       7
       9
      18
      14
      14
      11
      10
$ for i in {0..20}; do try_follow 100; done
      28
      40
      40
      44
      38
      38
      39
      47
      35
      38
      38
      36
      45
      40
      36
      39
      37
      36
      35
      39
      34
```

**Comment by wzshiming** [comment]
Can i work on this issue?

**Comment by bl-ue** [comment]
Go ahead @wzshiming I'd love for you too.  Hopefully my notes help!
