### ISSUE TITLE
can client-go reuse exec request connection

### ISSUE THREAD

**Issue by jiayouxujin** [kubernetes/kubernetes#97545]
when I use client-go to "exec" my pod in cluster,how to reuse the idle http connection?

**Comment by pacoxu** [comment]
You may create issues in https://github.com/kubernetes/client-go/issues like https://github.com/kubernetes/client-go/issues/912.

Per comments in code https://github.com/kubernetes/client-go/blob/master/plugin/pkg/client/auth/exec/exec.go#L454-L455, you can also find some examples in https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/exec_util.go

**Comment by fedebongio** [comment]
/cc @caesarxuchao 
Would be good to understand what you are trying to accomplish so we can give you a better answer, thanks!

**Comment by caesarxuchao** [comment]
Can you tell us more on what you want to achieve?

**Comment by jiayouxujin** [comment]
In my project,I use client-go to exec my pod-container.Can I reuse the connect(the original connect is closed),when another request arriverd?

**Comment by caesarxuchao** [comment]
Do you mean reusing the underlying TCP connection? That's managed by the golang http library. This [post](https://stackoverflow.com/questions/17948827/reusing-http-connections-in-golang) might be helpful.

**Comment by jiayouxujin** [comment]
yes.but I find the k8sclient use the apimachine libirary's transport which don't use the idle connection.

**Comment by jiayouxujin** [comment]
yes.but I find the client-go use the apimachine libirary's transport which don't use the idle connection.

**Comment by jiayouxujin** [comment]
yes.but I find the k8sclient use the apimachine library's transport which don't use the idle connection.

**Comment by jiayouxujin** [comment]
yes.but I find the client-go use the apimachine library's transport which don't use the idle connection.

**Comment by caesarxuchao** [comment]
@jiayouxujin can you elaborate on why the transport is preventing reusing connections?

client-go uses the regular golang [http.Transport](https://github.com/kubernetes/kubernetes/blob/b6958b2b1bb2cdf9a7c1ef78f525a5305e455f54/staging/src/k8s.io/client-go/transport/cache.go#L112) AFAIK.

**Comment by pacoxu** [comment]
/close
since not active.
feel free to reopen if you still have further questiosn.
