### ISSUE TITLE
Support exec in `kubectl port-forward`

### ISSUE THREAD

**Issue by FranciscoKurpiel** [kubernetes/kubernetes#97549]
**What would you like to be added**:
Ability to run a local command with port-forward. Example of use-case:

```bash
kubectl port-forward service/postgres 5432 -- psql -h localhost -p 5432 -c "select 1"
```

That would:

1. Start port-forwarding;
2. Execute the provided command. It will have access to the port
3. When the command returns, `kubectl` itself returns with the status code from the provided command.

For some cases we might need more than one port. Currently we have to use two instances of `kubectl port-forward`, but this approach won't work for the proposed feature. Ideally we would need the ability to port-forward multiple ports. If this is not trivial to implement, it would be fine to leave it for a future feature.

**Why is this needed**:
This would allow scripting around port-forwarding. That will be specially useful for developers, but can also be useful in production. Currently we can do that, but we have to use one terminal to create the port-forwarding, use another to run any tool that uses the port, then finally go back to the first terminal and terminate the forwarding. This is not _scriptable_.

**Comment by carlory** [comment]
I'm happy to work on it if the  `triage/accepted` label is added.

/assign

**Comment by FranciscoKurpiel** [comment]
I would like to add two small considerations to the behavior of local commands, regarding the standard streams. It would be nice if the behavior of

```
foo | \
    kubectl port-forward service/abc 1234 -- bar |
    baz
```

And

```
foo | \
    kubectl port-forward -q service/my-service 80 -- bar > out.log 2>err.log
```

For that it might make sense to send by default all outputs of kubectl to `stderr` by default when used with the local command, so  that `stdout` is always from `bar`. If I also care about stderr (second case above) I propose a `-q` flag, that will silence `kubectl`, allowing me to capture the undisturbed `stdout` and `stderr` from `bar`.

Regarding `stdin`, it would be very useful if if I could pipe from `foo` into `bar` as shown above. There are alternative ways of doing that, but they would be a lot harder to read and would result in a huge mess if for some reason I have to do something like this:

```
kubectl port-forward service/svc1 8888:80 -- curl http://localhost:8888 | \
    xz -9e |
    kubectl port-forward service/svc2 8889:80 -- curl -X POST --data-binary @- http://localhost:8889
```

This last construct is *very* powerful and useful, and fully adheres to the unix filosophy.

**Comment by brianpursley** [comment]
You could run the port forward in the background, something like this script:
```
#!/bin/sh

kubectl port-forward postgres 5432 >/dev/null 2>&1 & 
pid=$! 

# Use netcat to wait for port forward to take effect (or just sleep for a second if you want)
timeout 5s sh -c 'until nc -z $0 $1; do sleep .1; done' localhost 5432

psql -h localhost -p 5432 -U postgres -c "select 1" 

kill $pid
```

**Comment by FranciscoKurpiel** [comment]
You are right. But it is quite a stretch. The code is hard to read, full of corner cases and and fragile. Some issues:

- If the script has a `set -e` and psql fails, then `kubectl` will be leaked running
- if the script gets interrupted, `kubectl` will be leaked running
- the example code will have to be made even more complex to properly handle the timeout condition
- it uses `nc` to connect to the socket, meaning it can't be used if the server closes the socket after the first connection

Adding the missing support for `set -e` will require at least one additional `if` statement, and handling script interruption will require a trap + a function, and we sill might leak a `kubectl` if the script is terminated with a _non-trappable` signal (like `SIGKILL`). The `if` statement might be avoided if we trap the exit of the script.

**Comment by pwittrock** [comment]
Let's write this up more formally as what is being proposed in another issue.  The proposed user documentation would be a helpful starting point.

**Comment by steve-marmalade** [comment]
Came across this issue while searching for exactly the proposed functionality. @FranciscoKurpiel did anything ever come of this?

**Comment by FranciscoKurpiel** [comment]
Unfortunately not, I never managed to put it in a more formal form, as it was requested.
