### ISSUE TITLE
Sig windows Main branch tests are failing since merge of Device manager for Windows

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes/kubernetes#97554]
**Which jobs are failing**:
Flakes:
https://testgrid.k8s.io/sig-windows-containerd#aks-engine-azure-windows-master-containerd
https://testgrid.k8s.io/sig-windows-releases#aks-engine-azure-windows-master-staging 

Full failure:
https://testgrid.k8s.io/sig-windows-releases#aks-engine-azure-windows-master-staging-serial-slow 

**Which test(s) are failing**:

**Since when has it been failing**:
Since merging https://github.com/kubernetes/kubernetes/pull/93285

**Testgrid link**:

**Reason for failure**:

Serial slow tests are failing with: 

```
manager.go:270]
 failed to listen to socket while starting device plugin registry, with
error listen unix C:\var\lib\kubelet\device-plugins\kubelet.sock: bind:
Only one usage of each socket address (protocol/network address/port) is
 normally permitted.
```

and the parallel tests are flaking with:

```
 cri_stats_provider.go:583] Unable to fetch container log stats: failed to get fsstats for "\\var\\log\\pods\\kube-system_directx-device-plugin-zhmh8_788b6352-0117-43d6-95dd-1ec82da6b196\\hostdev\\0.log": failed to get FsInfo due to error The directory name is invalid.
```

**Anything else we need to know**:
I would not expect kubelet to crash if the node if the plugin is not present.

/sig windows

cc: @ddebroy @thomacos @aarnaud

**Comment by thomacos** [comment]
> I would not expect kubelet to crash if the node if the plugin is not present.

It seems to me that it is not related to a plugin being not present, but that it cannot open the endpoint where potential plugins could register to. In other words, I suspect this error happens independently from any plugins.

If we can trust this message `Only one usage of each socket address (protocol/network address/port) is normally permitted.`, then this would indicate that it tries to open that listening socket twice.
This would mean that https://github.com/aarnaud/kubernetes/blob/dc86fb93901f089bb1a72cba8691f7ce93c035eb/pkg/kubelet/cm/devicemanager/manager.go#L240 is called twice.
If this is the case, the question would be: Why?

> ```
> manager.go:270]
>  failed to listen to socket while starting device plugin registry, with
> error listen unix C:\var\lib\kubelet\device-plugins\kubelet.sock: bind:
> Only one usage of each socket address (protocol/network address/port) is
>  normally permitted.
> ```

Which log exactly do you get this error from?
It would be interesting to see if /cm/devicemanager/manager.go#L241 shows twice.

**Comment by aarnaud** [comment]
There is an issue on some Windows not updated. When you restart kubelet and the socket file `C:\var\lib\kubelet\device-plugins\kubelet.sock`

So the workarround, is to remove `C:\var\lib\kubelet\device-plugins\kubelet.sock` before restart kubeblet

**Comment by aarnaud** [comment]
And why tests on the PR didn't trigger this error ?

**Comment by thomacos** [comment]
Question:
Is it legal that https://github.com/aarnaud/kubernetes/blob/dc86fb93901f089bb1a72cba8691f7ce93c035eb/pkg/kubelet/cm/devicemanager/manager.go#L240 is called twice?

It seems that the `Start` function is called from https://github.com/aarnaud/kubernetes/blob/dc86fb93901f089bb1a72cba8691f7ce93c035eb/pkg/kubelet/cm/container_manager_windows.go#L88, which is analogous to the Linux implementation https://github.com/aarnaud/kubernetes/blob/dc86fb93901f089bb1a72cba8691f7ce93c035eb/pkg/kubelet/cm/container_manager_linux.go#L666.

Calling `Start` twice looks fishy to me. 
It seems to me that this problem https://github.com/kubernetes/kubernetes/issues/97554 is not caused by, but only exposed by the device plugin change https://github.com/kubernetes/kubernetes/pull/93285.

**Comment by thomacos** [comment]
> There is an issue on some Windows not updated. When you restart kubelet and the socket file `C:\var\lib\kubelet\device-plugins\kubelet.sock`
> 
> So the workarround, is to remove `C:\var\lib\kubelet\device-plugins\kubelet.sock` before restart kubeblet

You mean that kubelet is initialized twice on the same computer, causing this error the second time?

How is this handled on Linux?

If this is allowed we could simply delete `C:\var\lib\kubelet\device-plugins\kubelet.sock` if present before opening it again.

**Comment by aarnaud** [comment]
Are you sure it's call twice ? 

because on windows `container_manager_linux.go` is not present but replace by `/container_manager_windows.go` you can see the first line comment `// +build windows` and `// +build linux`.

A simple test is:
1. stop kubelet and check the socket file is still present
2. start kubelet you got the error, stop it
3. remove socket file
4. start kubelet again, normally it's working

Maybe the fix can be add in `https://github.com/microsoft/SDN/blob/master/Kubernetes/windows/start-kubelet.ps1`

**Comment by thomacos** [comment]
> Are you sure it's call twice ?

I think your explanation is very plausible:
That it is not called twice within a single kubelet initialization, but kubelet is initialized again for some reason on the same node.

**Comment by thomacos** [comment]
> Maybe the fix can be add in `https://github.com/microsoft/SDN/blob/master/Kubernetes/windows/start-kubelet.ps1`

There are various ways of fixing it.
But I would be interested in learning how this is handled under Linux.
To choose the same path for Windows, too.

**Comment by jsturtevant** [comment]
Thanks for your quick response and analysis :+1: 

> Which log exactly do you get this error from?
It would be interesting to see if /cm/devicemanager/manager.go#L241 shows twice.

You can find the kubelet logs (and many others) for the windows nodes in the "artifacts" tab on https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-staging-windows-serial-slow/1343693191026577408

> That it is not called twice within a single kubelet initialization, but kubelet is initialized again for some reason on the same node.
> 
> (It still means that it is called twice, but I didn't think about the possibility that kubelet is initialized twice.)

This set of tests runs configuration for GMSA tests which as part of the set up of the domain controller, causes a node resets.  This explains why one of the nodes seems ok (it isn't randomly selected as part of the domain machines) and why the parallel tests don't cause a full failure (they don't cause node resets).  

https://github.com/kubernetes-sigs/windows-testing/blob/abb08b4bbcf3f2605370908d580d773b0903a345/extensions/gmsa-dc/v1/Setup-gMSA.ps1#L276

https://github.com/kubernetes-sigs/windows-testing/blob/abb08b4bbcf3f2605370908d580d773b0903a345/extensions/gmsa-member/v1/Join-Domain.ps1#L99

> Maybe the fix can be add in https://github.com/microsoft/SDN/blob/master/Kubernetes/windows/start-kubelet.ps1

Not all clusters use that script.  This set of tests don't use them either (uses aks-engine which has a different start up script). IMHO this is a breaking change scince any cluster that has a node restart would fail to come back online. and kubelet should be able to restart (because of node restart or crash for another reason, etc.)  

> But I would be interested in learning how this is handled under Linux.
> To choose the same path for Windows, too.

It looks like there is code to clean up old sockets but it is not working on windows: https://github.com/kubernetes/kubernetes/blob/b860d08e4ba0c89724046f4ead26b9a535ebdad0/pkg/kubelet/cm/devicemanager/manager.go#L262-L266

Given there is clean up code there and it's a breaking change I think this this should be fixed in kubelet.

**Comment by thomacos** [comment]
> It looks like there is code to clean up old sockets but it is not working on windows:
> 
> https://github.com/kubernetes/kubernetes/blob/b860d08e4ba0c89724046f4ead26b9a535ebdad0/pkg/kubelet/cm/devicemanager/manager.go#L262-L266

Oh yes, I missed that! (I should have looked only a few lines above the line causing the error.)

It at least _looks_ exactly like the code we need.
The function is implemented in the same file: https://github.com/kubernetes/kubernetes/blob/b860d08e4ba0c89724046f4ead26b9a535ebdad0/pkg/kubelet/cm/devicemanager/manager.go#L198-L230

But why it is failing to work under Windows?
Do you have an idea?

> Given there is clean up code there and it's a breaking change I think this this should be fixed in kubelet.

Yes, sounds good.

**Comment by aarnaud** [comment]
Ok so on windows `removeContents` failed here https://github.com/kubernetes/kubernetes/blob/b860d08e4ba0c89724046f4ead26b9a535ebdad0/pkg/kubelet/cm/devicemanager/manager.go#L214

**Comment by aarnaud** [comment]
So this exemple https://gist.github.com/aarnaud/6fcec8238f37fe067d722aae512e1e8b reproduce the error.

the `os.Stat` failed only on socket file not on regular file !

**Comment by aarnaud** [comment]
It's bug on windows 1903 https://github.com/golang/go/issues/33357#issuecomment-520518431 not present on windows 1809

The fix can be replace `os.Stat` by `os.Lstat`

**Comment by thomacos** [comment]
@aarnaud 👍 Very cool!

Just for interest, how did you find https://github.com/golang/go/issues/33357#issuecomment-520518431?

**Comment by aarnaud** [comment]
> Just for interest, how did you find [golang/go#33357 (comment)](https://github.com/golang/go/issues/33357#issuecomment-520518431)?

I hate Windows ;-) and I googled `os.Stat socket windows`

**Comment by jsturtevant** [comment]
>It's bug on windows 1903 golang/go#33357 (comment) not present on windows 1809

> The fix can be replace os.Stat by os.Lstat

This set of tests are running on 2019 LTSC (also known as 1809).  If this is only an issue on 1903 is there something else happening?

**Comment by aarnaud** [comment]
Sorry, I read to quickly, there is a change of behaviour between 1809 and 1903 about unix socket, If my understanding is good on 1903 unix socket is like regular file but not on 1809, so it's why os.Stat failed on 1809. but I tested on Windows 10 20H2 and the issue still here with `os.Stat`

**Comment by thomacos** [comment]
So in summary, the key point is:
PR https://github.com/kubernetes/kubernetes/pull/97576 fixes this issue https://github.com/kubernetes/kubernetes/issues/97554.
