### ISSUE TITLE
Support M1 MacBooks darwin/arm64

### ISSUE THREAD

**Issue by yoav-orca** [kubernetes/kubernetes#97550]
**What would you like to be added**:
When trying to build kubectl from tip (#0a839c6c3b9489716e216b4fc9dd2f9c17948c16) on a M1 Macbook:
```
$ make WHAT=cmd/kubectl
+++ [1228 14:35:00] Building go targets for darwin/arm64:
    ./vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen
touch: _output/bin/prerelease-lifecycle-gen: No such file or directory
make[1]: *** [_output/bin/prerelease-lifecycle-gen] Error 1
make: *** [generated_files] Error 2
```

**Why is this needed**:
M1 MacBooks are a new major client platform that many developers will use. brew listed kubectl (kubernetes-cli) is one of the major packages still not supported on M1 (https://github.com/Homebrew/brew/issues/10152)
Since it's supported by go, it's only required to add it to the supported client list

Locally I managed to add support using the following patch:
```patch
diff --git a/hack/lib/golang.sh b/hack/lib/golang.sh
index bef1d837..154eecfd 100755
--- a/hack/lib/golang.sh
+++ b/hack/lib/golang.sh
@@ -49,6 +49,7 @@ readonly KUBE_SUPPORTED_CLIENT_PLATFORMS=(
   linux/s390x
   linux/ppc64le
   darwin/amd64
+  darwin/arm64
   windows/amd64
   windows/386
 )
```

**Comment by mirageglobe** [comment]
Any updates on this? cheers

**Comment by neolit123** [comment]
> Any updates on this? cheers

you can watch the PR:
https://github.com/kubernetes/kubernetes/pull/97743

**Comment by engow** [comment]
it works, nice!!!

**Comment by bl-ue** [comment]
Done!!! 🚀
