### ISSUE TITLE
kube-apiserver exited abnormaly，how to find the reason？

### ISSUE THREAD

**Issue by yangjunmyfm192085** [kubernetes/kubernetes#97555]
kube-apiserver exited abnormaly，but no valid log，how can i analyse the problem further more？
only find the log   "Shutting down kubernetes service endpoint reconciler"

**Comment by pacoxu** [comment]
More `apiserver logs`、 `etcd logs`、`docker inspect` would help.

BTW, the error `Shutting down kubernetes service endpoint reconciler` is related with https://github.com/kubernetes/kubeadm/issues/1047#issuecomment-427564287 
` - --endpoint-reconciler-type=lease`

please try the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

**Comment by yangjunmyfm192085** [comment]
> More `apiserver logs`、 `etcd logs`、`docker inspect` would help.
> 
> BTW, the error `Shutting down kubernetes service endpoint reconciler` is related with [kubernetes/kubeadm#1047 (comment)](https://github.com/kubernetes/kubeadm/issues/1047#issuecomment-427564287)
> ` - --endpoint-reconciler-type=lease`
> 
> please try the support channels:
> https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

I can't find  any valid logs in apiserver and etcd logs。 Maybe someone other processor stopped the container？

**Comment by lunhuijie** [comment]
Could you describe this problem clearly.  What is the scene?

**Comment by yangjunmyfm192085** [comment]
> Could you describe this problem clearly. What is the scene?

This is a scenes of ci  ，run pvc test  failed，kube-apiserver mirror pod restarted at this time。 I only found valid log “Shutting down kubernetes service endpoint reconciler” in apiserver log file。

**Comment by neolit123** [comment]
please use the support forums for similar discussions:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
