### ISSUE TITLE
managedfields to fieldPath

### ISSUE THREAD

**Issue by allenhaozi** [kubernetes/kubernetes#97559]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:replicas: {}
    manager: Controller-2
    operation: Update
    time: "2020-12-28T08:10:40Z"
```

is there a way can translator the `fieldsV1` values to fieldPath `spec.replicas`

**Comment by allenhaozi** [comment]
+ /sig api-machinery

**Comment by allenhaozi** [comment]
> Can I help you make sure you're doing the right thing?
> 
> You can convert the json in `FieldsV1` directly into a "Set": https://github.com/kubernetes-sigs/structured-merge-diff/blob/master/fieldpath/serialize.go#L168
> 
> The `Set` is made of multiple `Path`s: https://github.com/kubernetes-sigs/structured-merge-diff/blob/master/fieldpath/set.go#L164

thank u @apelisse 

Now I'm using it the way you said

But I got `.spec.template.spec.containers[name="simple-web-0"].resources.limits.cpu`
Actually, my expected value is `.spec.template.spec.containers[0].resources.limits.cpu` if simple-web-0 is the first container in spec.containers

I'm looking for a better way to transform, because I need to do a few pre-patch things before calling `Client. patch` according to ManagedField, in our scenario

**Comment by apelisse** [comment]
> But I got `.spec.template.spec.containers[name="simple-web-0"].resources.limits.cpu`
Actually, my expected value is `.spec.template.spec.containers[0].resources.limits.cpu` if simple-web-0 is the first container in spec.containers

We can't positively identify a list element by its position, that's why we're using the key instead.

> I'm looking for a better way to transform, because I need to do a few pre-patch things before calling Client. patch according to ManagedField, in our scenario

It's still hard for me to know if you're doing the right thing :-)

**Comment by allenhaozi** [comment]
> > But I got `.spec.template.spec.containers[name="simple-web-0"].resources.limits.cpu`
> > Actually, my expected value is `.spec.template.spec.containers[0].resources.limits.cpu` if simple-web-0 is the first container in spec.containers
> 
> We can't positively identify a list element by its position, that's why we're using the key instead.
> 
> > I'm looking for a better way to transform, because I need to do a few pre-patch things before calling Client. patch according to ManagedField, in our scenario
> 
> It's still hard for me to know if you're doing the right thing :-)

this is the relevant  issue [Server-side Apply problem](https://github.com/kubernetes-sigs/controller-runtime/issues/1311) 

In short we have multiple controllers manage one resource 

controller Workload and Scaler manage deployment, 

Workload is responsible for create or update deployment
Scaler is responsible for deployment's replicas

once deployment's replicas update by Scaler, expect Workload can not update replicas field

**Comment by apelisse** [comment]
Let's try to discuss this further, I don't think you should be hacking your way into a non-generic solution.

**Comment by allenhaozi** [comment]
thank u @apelisse 

In our internal scenario, We developed a PaaS platform based on [OAM](https://github.com/oam-dev/spec)
our business simply declare the Workload and Traits they use
There are two types of Workload, `ServerWorkload`(online) and `TaskWorkload`(offline)
Traits include `ManualScalerTrait`,`AutoScalerTrait`,`LoadBalanceTrait`, `FlaggerTrait`, etc.

The ServerWorkload renders a Deployment and creates it
When the `ManualScalerTrait` observes that this Deployment has been created, it changes the replicas of this Deployment

In practice, however, we found that once our Operator was restarted, the POD that was already under the running deployment would be restarted too.

found the following event
```
Events:
  Type    Reason             Age                  From                   Message
  ----    ------             ----                 ----                   -------
  Normal  ScalingReplicaSet  13s (x12 over 5h5m)  deployment-controller  Scaled down replica set simple-web-33-5d759bd4cf to 0
  Normal  ScalingReplicaSet  12s (x15 over 5h7m)  deployment-controller  Scaled up replica set simple-web-33-5d759bd4cf to 3
```

Because the replicas of Deployment rendered by ServerWorkload is 0 But the number of ManualScaler is 3, the deployment changes from 3 to 0 and then to 3 again, Caused a restart

Based on the implementation mechanism, it is difficult for ServerWorkload to patch Deployment because it renders a complete Deployment template.

If APIServer can provide this parameter `client.SkipConflictFields`, perfect solution

```
ao := []client.PatchOption{ client.FieldOwner(c1.GetUID()),client.SkipConflictFields}
err := r.Patch(ctx, deploy, client.Apply, ao...)
```

**Comment by kwiesmueller** [comment]
Thanks for the details, that helps already.
What I think you'd want to do is making sure your ServerWorkload uses Apply to send all the fields it cares about, but not replicas.
Then your scaling traits can send partial applys that only specify replicas (nothing else) and force ownership (controllers should force ownership in general).

I'm not a 100% sure right now, but you might have to do a Create if the resource does not exist and only then, including your desired default replicas. But aside from that you should be able to handle what you are doing with apply.

Very important is, that you use apply correctly. Right now you can not send typed Go objects into apply as it will try to set fields you didn't specify. Therefore you need to use an unstructured and only define the fields your current workflow really cares about.
Also make sure all the traits/operands/operators use their own fieldManager.

So as an example:
You want to create a deployment that does not exist.
You send an apply with the resource you want to either Apply or Create. Only do this once, do not run it when the resource exists already.

Then, in your scale trait you send an apply like:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
spec:
  replicas: 3
```
to the Apply endpoint with fieldManager set to e.g. "manualScale" and ForceOwnership=true.

If you want to also reconcile other fields in a different workflow, make sure you also use apply and only specify partial objects that do not include replicas.
Like you want an operand that sets a label, so you'd send only:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  labels:
    newLabel: "foo"
```

Apply works around this concept of sending what you or better, your workflow (fieldManager) intend or cares about.
Those fields are then assigned to said fieldManager. You do not want to skip conflicts as they mean you have conflicting intentions in your code (two workflows wanting different things).
So the goal would be to build your operator in a way that each group of intentions is managed by its own workflow that only sends applies with those fields.

Does that make sense?
It's a lot of text and right now the need to specify your apply configuration as JSON or YAML is not great, but I think what you want to do is perfectly doable with what we have right now.
To make it a bit easier, we're working on a Go client that understands apply configs right now.

**Comment by allenhaozi** [comment]
thank u @kwiesmueller 

It's very clear

Now all of my traits work just like you said, 

but workload 
> What I think you'd want to do is making sure your ServerWorkload uses Apply to send all the fields it cares about, but not replicas.

based on the implementation mechanism, It's a little bit complicated, 

This is also the purpose of creating this issue, I'm looking for an easier way to solve this problem

My online strategy is I will do pre-patch by the managedFields of existing, as the following code

```go
func (a *Applicator) Apply(ctx common.Context, parent, desired oam.Object, ao ...client.PatchOption) error {
	if err := a.preApply(ctx, parent, desired); err != nil {
		return errors.Wrap(err, "pre apply failure")
	}
	
	ao = append(ao, client.ForceOwnership)
	
	ownerRef := utils.GenOwnerReferenceByObject(parent)
	crmeta.AddOwnerReference(desired, ownerRef)
	
	// Server-side Apply, only set field which manage
	return errors.Wrap(a.Patch(ctx, desired, client.Apply, ao...), "cannot patch object:apply")
}

func (a *Applicator) preApply(ctx common.Context, parent, desired oam.Object) error {

	existing, err := a.GetResourceByObject(ctx, desired)
	// if not found, need create, just return
	if apierrors.IsNotFound(err) {
		return nil
	}
	// if occur error return
	if resource.IgnoreNotFound(err) != nil {
		return err
	}
	// get current resource ManagedFields
	managedFields := existing.GetManagedFields()
	for _, item := range managedFields {
		// skip kube controller manager managed
		if item.Manager == common.ManagedFieldsControllerManager {
			continue
		}
		own := utils.GenFieldOwnerByObject(parent)
		// if this resource is managed by this parent resource, skip
		if item.Manager == own {
			continue
		}
		if item.FieldsV1 == nil {
			continue
		}
		// this resource is controlled by multi controller, (one workload and one or more traits)
		patchedDesired, err := a.predicate.PreApply(item, desired, existing)
		if err != nil {
			return err
		}

		if patchedDesired != nil && len(patchedDesired) > 0 {
			// assign patched desired to desired
			if err = json.Unmarshal(patchedDesired, desired); err != nil {
				return errors.Wrapf(err, "unmarshal patched json failure")
			}
		}
	}

	return nil
}
```

**Comment by kwiesmueller** [comment]
I think you should almost never need to look at managedFields for the usual operator case.
I'd just do
```
// pseudo code
res, err := getResource()
if isNotFound(err) {
  return createFullResourceIncludingReplicas()
}
// here the usual reconcile loop comes in
return ApplyPartialObjectWithoutSpecifyingReplicas()
```

In `createFullResourceIncludingReplicas` you can use apply, but don't need to.
It should only do this once anyways. The reason I'd do a create on the full object is, because I'm not sure the replica field can be missing or will be correctly defaulted. So better to create the object with it and disown the creation later.

Apply can create objects it's missing, you just have to make sure it does not exist, otherwise you're stealing back the replicas field what you want to avoid. I think I'd want to avoid the GET+CREATE requests, but would have to try around a bit first. Maybe just sending a CREATE is enough as it would fail with already exists. @apelisse might have a better idea?

In `ApplyPartialObjectWithoutSpecifyingReplicas` you only specify the things this flow should manage (so not replicas) in a forced apply.

Please tell me if I can make anything clearer.

**Comment by allenhaozi** [comment]
```go
package apply

import (
	"encoding/json"

	"github.com/oam-dev/kubevela/pkg/oam"

	"k8s.io/apimachinery/pkg/api/meta"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/util/jsonmergepatch"
	"k8s.io/apimachinery/pkg/util/mergepatch"
	"k8s.io/apimachinery/pkg/util/strategicpatch"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

var k8sScheme = runtime.NewScheme()
var metadataAccessor = meta.NewAccessor()

func init() {
	_ = clientgoscheme.AddToScheme(k8sScheme)
}

// threeWayMergePatch creates a patch by computing a three way diff.
func threeWayMergePatch(currentObj, modifiedObj runtime.Object) (client.Patch, error) {
	current, err := json.Marshal(currentObj)
	if err != nil {
		return nil, err
	}
	original, err := getOriginalConfiguration(currentObj)
        	if err != nil {
		return nil, err
	}
	modified, err := getModifiedConfiguration(modifiedObj, true)
	if err != nil {
		return nil, err
	}

	var patchType types.PatchType
	var patchData []byte
	var lookupPatchMeta strategicpatch.LookupPatchMeta

	versionedObject, err := k8sScheme.New(currentObj.GetObjectKind().GroupVersionKind())
	switch {
	case runtime.IsNotRegisteredError(err):
		// use JSONMergePatch for custom resources
		// because StrategicMergePatch doesn't support custom resources
		patchType = types.MergePatchType
		preconditions := []mergepatch.PreconditionFunc{
			mergepatch.RequireKeyUnchanged("apiVersion"),
			mergepatch.RequireKeyUnchanged("kind"),
			mergepatch.RequireMetadataKeyUnchanged("name")}
		patchData, err = jsonmergepatch.CreateThreeWayJSONMergePatch(original, modified, current, preconditions...)
		if err != nil {
			return nil, err
		}
	case err != nil:
		return nil, err
	default:
		// use StrategicMergePatch for K8s built-in resources
		patchType = types.StrategicMergePatchType
		lookupPatchMeta, err = strategicpatch.NewPatchMetaFromStruct(versionedObject)
		if err != nil {
			return nil, err
		}
		patchData, err = strategicpatch.CreateThreeWayMergePatch(original, modified, current, lookupPatchMeta, true)
                 		if err != nil {
			return nil, err
		}
	}
	return client.RawPatch(patchType, patchData), nil
}
```

find a way by  @captainroy-hy  [patch.go](https://github.com/oam-dev/kubevela/blob/c13ed36e32a82972b07dcfa17566e101874c9173/pkg/utils/apply/patch.go)

I can get the patch data that is changed 

thank u @apelisse @kwiesmueller
