### ISSUE TITLE
Add pod info to device plugin request

### ISSUE THREAD

**Issue by zwpaper** [kubernetes/kubernetes#97568]
**What would you like to be added**:

Add pod info to device plugin request.

**Why is this needed**:

currently kubelet only send [device IDs](https://github.com/kubernetes/kubelet/blob/0013c8763bb0863e996c32d555cb764f92c83a46/pkg/apis/deviceplugin/v1beta1/api.proto#L158) to device plugin,

if `device plugin` what to make some decision base on the pod configuration, there is not any way for this, for example choose different GPU Models in one node.

if we added the pod info to request, `device plugin` can read the info from such as `labels`, `annotations` or something else and did some extra logic

**Comment by AlexeyPerevalov** [comment]
I think the problem you described is possible to solve by GetPreferredAllocation endpoint of the DevicePlugin api  https://github.com/kubernetes/enhancements/pull/1121/files
