### ISSUE TITLE
docker-containerd have renamed to containerd, but EnsureDockerInContainer check not update

### ISSUE THREAD

**Issue by zgfh** [kubernetes/kubernetes#97565]
**What happened**:
docker-containerd have renamed to containerd, but EnsureDockerInContainer check not update,so it not work

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/container_manager_linux.go#L74
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/container_manager_linux.go#L843

**What you expected to happen**:
Is this check still needed？

**How to reproduce it (as minimally and precisely as possible)**:
no need

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`): 
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`): 
- Install tools: 
- Network plugin and version (if this is a network-related bug): 
- Others:

**Comment by dims** [comment]
cc @SergeyKanzhelev

**Comment by dims** [comment]
@zgfh feel free to send an PR update with new name for the process and the location of the pid file.
