### ISSUE TITLE
Job exited but the completion status is still 0/1

### ISSUE THREAD

**Issue by raul1991** [kubernetes/kubernetes#97588]
**What happened**:

My job exited with success (returned exit 0) yet the completion status says 0/1

**What you expected to happen**:
After the completion the completion status should have been updated.

**How to reproduce it (as minimally and precisely as possible)**:

Here is all that I can share about my env and the code.

I have a job that has the default backoff limit set to 6. In the first 5 attempts it fails and in the last attempt it passes.

As per the logs, I see it passed but the completion status is still 0/1

Here is the snippet of code which is running inside the container.

    for i in $entities_to_load; do
      IS_SUCCESS=$(load_config "$i") # returns 0 or 1 (failure)
      log_info "Exit status for load config [$i]: ${IS_SUCCESS}"
      if [[ ${IS_SUCCESS} -eq 1 ]]; then
        log_info "Failed to load $i entity"
        cat response.txt
        exit ${IS_SUCCESS}
      else
        log_info "Successfully loaded the ${i} entity"
    exit 0

Here are the logs from the last attempt which passed

    + eric-bss-coba-cm-baseconfig-job-xd7bz › baseconfig-provisioner-job
    eric-bss-coba-cm-baseconfig-job-xd7bz baseconfig-provisioner-job {"version":"0.3.0","timestamp":"2020-12-29T07:16:13.649+00:00","severity":"info","service_id":"eric-bss-coba-cm","message":"Successfully loaded the Currency entity"}
    eric-bss-coba-cm-baseconfig-job-xd7bz baseconfig-provisioner-job {"version":"0.3.0","timestamp":"2020-12-29T07:16:14.545+00:00","severity":"info","service_id":"eric-bss-coba-cm","message":"Successfully loaded the Measure entity"}
    eric-bss-coba-cm-baseconfig-job-xd7bz baseconfig-provisioner-job {"version":"0.3.0","timestamp":"2020-12-29T07:16:16.633+00:00","severity":"info","service_id":"eric-bss-coba-cm","message":"Successfully loaded the UnitOfMeasurement entity"}
    eric-bss-coba-cm-baseconfig-job-xd7bz baseconfig-provisioner-job {"version":"0.3.0","timestamp":"2020-12-29T07:16:16.875+00:00","severity":"info","service_id":"eric-bss-coba-cm","message":"Successfully loaded the EventReportingInterval entity"}
    eric-bss-coba-cm-baseconfig-job-xd7bz baseconfig-provisioner-job {"version":"0.3.0","timestamp":"2020-12-29T07:16:17.357+00:00","severity":"info","service_id":"eric-bss-coba-cm","message":"Successfully loaded the NumberingScheme entity"}
    - eric-bss-coba-cm-baseconfig-job-xd7bz

Here is what the completions say

    NAME                                       COMPLETIONS   DURATION   AGE
    eric-bss-bam-faultmap-mutator-1609226700   1/1           3s         3m44s
    eric-bss-coba-cm-baseconfig-job            0/1           18m        18m
    eric-bss-coba-integration-schema-job       1/1           18s        18m

Here are logs from the `kubectl describe jobs.batch/my-job`

    Completions:    1
    Start Time:     Tue, 29 Dec 2020 12:40:08 +0530
    Pods Statuses:  0 Running / 0 Succeeded / 0 Failed

Here are the events from kubectl

    Events:
      Type     Reason                Age                From            Message
      ----     ------                ----               ----            -------
      Normal   SuccessfulCreate      25m                job-controller  Created pod: eric-bss-coba-cm-baseconfig-job-xd7bz
      Normal   SuccessfulDelete      19m                job-controller  Deleted pod: eric-bss-coba-cm-baseconfig-job-xd7bz
      Warning  BackoffLimitExceeded  19m (x2 over 19m)  job-controller  Job has reached the specified backoff limit

Here is my Dockerfile

    FROM <base-image>
    WORKDIR /baseconfig
    COPY . $WORKDIR
    RUN chmod +x baseconfig.sh
    CMD ["tail", "-f", "/dev/null"]

Here is my invocation of this script from the helm job spec

    command: [ "sh" ]
    args: [ "-c", "/baseconfig/baseconfig.sh SERVICE_NAME {{.Values.service.port}}"]

As you can see that the logs printed fine and it should have exited with 0 status, the job should have marked it as completed and the same should have been visible in the completions but it didn't. It instead, said, "BackoffLimitExceeded" and failed the deployment.

I am unable to identify the problem here.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-21T13:03:39Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
can you provide the job yaml ?

I build two image daocloud.io/daocloud/paco:test-sleep-20-exit-0 and daocloud.io/daocloud/paco:test-sleep-20-exit-1 
Then I create a job with `exit 1` and backoffLimit=5, then I watch the pod and events and wait for about 60s after job tried 4 times to run the exit-1 image.
At the time, I tag exit-0 image to exit-1. As I have only one worker in my cluster. The fifth pod of the job completed.

I get 1/1 in this test. So I think there would be some information missing in your description.

```
[root@daocloud job]# cat Dockerfile
FROM daocloud.io/centos
COPY . /
RUN chmod +x /baseconfig.sh
CMD ["bash", "/baseconfig.sh"]
[root@daocloud job]# cat baseconfig.sh
sleep 20
exit 1
[root@daocloud job]# cat job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: pi-with-ttl
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: pi
        image: 10.6.151.61/daocloud/paco:test-sleep-20-exit-1
      restartPolicy: OnFailure
  backoffLimit: 5

[root@daocloud job]# kubectl get job
NAME          COMPLETIONS   DURATION   AGE
pi-with-ttl   1/1           3m17s      10m
```


watch job pod to see the restart count.
```
[root@daocloud job]# kubectl get pod -o wide  -w  | grep pi-with-ttl
pi-with-ttl-j2d8f                   0/1     Terminating       5          5m14s   172.32.126.178   dce-10-7-177-91   <none>           <none>
```
If it is more than or equal to backoffLimit, the job failed.
If the restart count is less than backoffLimit, the job success.

**Comment by raul1991** [comment]
I haven't set the Backoff limit myself so that would be 6 in my case.
Also, my job succeeded (as per the logs) in 6th attempt and I saw 5 restarts before that.

**Comment by raul1991** [comment]
Seems like the job is no more present in the `kubectl get jobs.batch` list . I am assuming it correctly exited and hence not present. So let's close this issue.
