### ISSUE TITLE
Not an issue: PHP-maintained package

### ISSUE THREAD

**Issue by rennokki** [kubernetes/kubernetes#97602]
Not an actual issue!

I have built a package for PHP and I'd like to know how to currently evolve it into an officially-supported client since I got with him to Silver & Beta.

- Min v1.17 supported and continuously keeping the latest three stable versions as Minikube does
- Authentication of any form
- Some resources are on the roadmap ([Entire documentation is here](https://github.com/renoki-co/php-k8s/blob/master/docs/RESOURCES.md))
- Currently looking onto including exec and pod attach, watchers are already included

https://github.com/renoki-co/php-k8s

**Comment by neolit123** [comment]
hi, this repository is about issuess in core k8s.
please try the support channels instead for support questions:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

thanks
/close
