### ISSUE TITLE
Getting error in connection of Master and node ( Not able to connection of master and node) 

### ISSUE THREAD

**Issue by surendrakrp08** [kubernetes/kubernetes#97636]

**Comment by surendrakrp08** [comment]
Hi,
    How can you add appropriate labels using/ please tell me some examples.

Please add an appropriate label by using one of the following commands:

   - /sig <group-name>
   - /wg <group-name>
   - /committee <group-name>

**Comment by neolit123** [comment]
please use the support forums:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

if there is a confirmed k8s core bug, log a new ticket.

/close
