### ISSUE TITLE
Not able to join master and nodes

### ISSUE THREAD

**Issue by surendrakrp08** [kubernetes/kubernetes#97637]
error execution phase preflight: couldn't validate the identity of the API Server: Get "https://172.31.12.232:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) To see the stack trace of this error execute with --v=5 or higher

After sumtime  using “kubeadm token create” on the master node to create a new valid token. again getting this error.

I am using both master and nodes using beloe configutration

Ubuntu 18.4
2 Cpus
4 gb  ram memory

please help me,

**Comment by surendrakrp08** [comment]
Hi,
    How can you add appropriate labels using/ please tell me some examples.

Please add an appropriate label by using one of the following commands:

   - /sig <group-name>
   - /wg <group-name>
   - /committee <group-name>

**Comment by neolit123** [comment]
/close
/remove-sig multicluster

please use the support forums instead:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
