### ISSUE TITLE
Cnot not switch to other From branches/tags from URL: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md 

### ISSUE THREAD

**Issue by jerryzhyliu** [kubernetes/kubernetes#97647]
**What happened**:
From URL:   https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md
switch to  any branches/tags 
web link lost: 404 error

**What you expected to happen**:
go to correct link

**How to reproduce it (as minimally and precisely as possible)**:
click the https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md
switch to  any branches/tags 

**Anything else we need to know?**:
no

**Environment**: no
- Kubernetes version (use `kubectl version`):no
- Cloud provider or hardware configuration:no
- OS (e.g: `cat /etc/os-release`):no
- Kernel (e.g. `uname -a`):no
- Install tools:no
- Network plugin and version (if this is a network-related bug):no
- Others:no

**Comment by PI-Victor** [comment]
hey @jerryzhyliu, i'm not sure i follow the issue here, can you please explain? Why would i see the changelog for v1.20 in any other branches beside the release branch for that version and master?

**Comment by PI-Victor** [comment]
i'll attempt to explain, the CHANGELOG-1.xx.md should reside in the release branch of that version and the master branch, so i consider this not to be an issue.
/close
