### ISSUE TITLE
Increase Netpol E2E tests

### ISSUE THREAD

**Issue by knabben** [kubernetes/kubernetes#97640]
**What would you like to be added**:
Add missing unit test cases based on these [recipes](https://github.com/ahmetb/kubernetes-network-policy-recipes/) and fair deviations when applied.

- [x] <strike>[2a](https://github.com/kubernetes/kubernetes/pull/97616) - Allow Ingress traffic to an application</strike>
- [x] <strike>[4](https://github.com/kubernetes/kubernetes/pull/98390) - DENY all traffic from other namespaces (w/o NS selector)</strike>
- [x] [5](https://github.com/kubernetes/kubernetes/pull/98389) - Allow traffic from other namespaces (w/o NS selector)
- [x] [10](https://github.com/kubernetes/kubernetes/pull/97701) - Allow traffic multiple selector (OR)
- [x] <strike>[11](https://github.com/kubernetes/kubernetes/pull/97736) - DENY default-deny-egress from an app</strike>
- [x] <strike>[12](https://github.com/kubernetes/kubernetes/pull/97738) - DENY default-deny-all-egress from a namespace</strike>
- [x] <strike>[UDP coverage](https://github.com/kubernetes/kubernetes/pull/98636)</strike>

**Why is this needed**:
Increase the coverage of netpol tests 

Ref #97553

**Comment by knabben** [comment]
https://docs.google.com/document/d/1Vyv-andfj13exXf36FsMTG0QnB4Id8BQB4mo49f0oW8/edit#

**Comment by needkopi** [comment]
hello @knabben can i take this issue?

**Comment by knabben** [comment]
@needkopi feel free to come up with the ones in the list, just raise here the one you'll get and I update the comment.

**Comment by needkopi** [comment]
@knabben maybe i take number 4
``` 
4 - DENY all traffic from other namespaces (w/o NS selector)
```

**Comment by knabben** [comment]
@needkopi great, we are aiming at the new netpol e2e framework, some other examples:

https://github.com/kubernetes/kubernetes/pull/97616
https://github.com/kubernetes/kubernetes/pull/97524

**Comment by rikatz** [comment]
/triage accepted
/assign @knabben 

Amin, do you think this is a good first issue, with the current framework? If so we can gather some new contributors, and use your and @jayunit100 skills for the review of the PRs :D

**Comment by jayunit100** [comment]
Can we carve this into 5 separate PRs ? I know @mattfenwick was planning on taking a couple , but not sure which ones he was doing

**Comment by rikatz** [comment]
YEap, this is the idea :D 1 issue, 5 or more PRs, good first issue, each people that wants pick one :)

**Comment by knabben** [comment]
@rikatz absolutely, I think it applies since we have a lot of examples already

/good-first-issue

**Comment by jayunit100** [comment]
@knabben can you add a checkbox for windows tests as well ? Im going to hack on that w @mattfenwick   we can consolidate the work into this mega-issue

**Comment by knabben** [comment]
@jayunit100 sure. LMK if you guys need more granularity on the list

**Comment by sheetalsingala** [comment]
Can I take up 5 - Allow traffic from other namespaces (w/o NS selector) ?

**Comment by knabben** [comment]
@sheetalsingala sure, LMK if you have any questions

**Comment by jayunit100** [comment]
great sounds like this is all carved up :) thanks

**Comment by jayunit100** [comment]
important note: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/netpol/network_policy.go <-- @sheetalsingala @needkopi  can you also please make sure your test cases arent already covered ?    We have about 31 test cases in the new framework now.  So, you might only need to verify that the tests exist/add a comment to them to describe them properly, in some cases.

( Lets try not to add redundant tests )

**Comment by knabben** [comment]
we are good to go.

/remove good-first-issue

**Comment by knabben** [comment]
we are good to go.

/remove-good-first-issue

**Comment by knabben** [comment]
https://hackmd.io/He6sagihRySJKHPlC-vjWw - Getting the diff between the new and old suites coverage.

1. New one has one more test - `should enforce policy based on Multiple PodSelectors and NamespaceSelectors`
2. New one has UDP - `should not allow access by TCP when a policy specifies only UDP`

The new ones under `netpol/` have more tests.

**Comment by knabben** [comment]
@needkopi @sheetalsingala any progress here? I'm available on Slack if you guys want to chat.

**Comment by knabben** [comment]
/close

Windows tests are on https://github.com/kubernetes/kubernetes/issues/97751

**Comment by knabben** [comment]
Using this issue as umbrela to:

`NetworkPolicyPort with Protocol but not Ports means "any port with that protocol"`

https://github.com/kubernetes/kubernetes/issues/46625

**Comment by rikatz** [comment]
Can we add the endPort test here, just to increase this coverage?

**Comment by knabben** [comment]
@rikatz moved the port range tests to https://github.com/kubernetes/kubernetes/issues/99551
