### ISSUE TITLE
how to find CPU/Mem consumption of pods running on a specific node

### ISSUE THREAD

**Issue by missioin-peaks** [kubernetes/kubernetes#97641]
I am trying to find a way to figure out each pod consumption (CPU/Mem) running on any given k8s worker node for eg. 

So basically, when we do $kubectl top nodes, we get the CPU/Mem consumption of each node in the cluster. Now, if I want to drill down on a specific node, and see how much each Pod running on a given node is consuming the CPU/Mem resources. How would I find this, using any kubectl or any shell script ?

Please help or point me to any reference docs.

Regards,
Raj

**Comment by hritvikpatel4** [comment]
Do these links help you in any way?

1) https://github.com/kubernetes/kubernetes/issues/17512#issuecomment-385803939
2) https://github.com/kubernetes/kubernetes/issues/17512#issuecomment-317757388
3) https://stackoverflow.com/questions/58917468/how-to-get-cpu-utilization-memory-utilization-of-namespaces-pods-services-in-k
4) https://github.com/kubernetes/kubernetes/issues/17512#issuecomment-587431461

**Comment by neolit123** [comment]
please use the support forums:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
