### ISSUE TITLE
remove or comment `FromPort` in netpol tests

### ISSUE THREAD

**Issue by mattfenwick** [kubernetes/kubernetes#97657]
**What would you like to be added**:

Remove or comment `FromPort` from new netpol tests https://github.com/kubernetes/kubernetes/blob/43fcd50d50429e469b501ac7774ad2ffb3235b60/test/e2e/network/netpol/reachability.go#L28

**Why is this needed**:

The `FromPort` field is confusing and undocumented -- we should clarify its role or remove it.

**Comment by qfen** [comment]
+1

**Comment by jayunit100** [comment]
Ahhh I need to build a new dev box that one is busted now

**Comment by qfen** [comment]
The TestCase.FromPort member isn't passed to the Probe function (as expected; you'd normally not bother with calling bind(2) for a client TCP connection). Working on separating the unnecessary uses from when it's actually desired.

**Comment by qfen** [comment]
Looks like it's superfluous, I'll remove FromPort
