### ISSUE TITLE
Support for arbitrary FQDN as `hostname` inside a pod

### ISSUE THREAD

**Issue by JorjBauer** [kubernetes/kubernetes#97662]
**What would you like to be added**:

The ability for a pod to set its _internal_ `hostname` arbitrarily.

**Why is this needed**:

Older (admittedly not well-designed) services may use `hostname` to determine licensing or service operation characteristics. When migrating services in to k8s, the migration path is muddied by hostname restrictions within the pod itself.

An example service that would benefit from this is Kerberos, which uses a combination of DNS, reverse DNS, and hostname to determine what authentication credentials are to be used for any given connection.

Currently, when a pod is configured for any hostname, it gets a name like foo.subdomain.namespace.pod.cluster-suffix. The namespace is inexorably part of the hostname; and changing the cluster-suffix would affect other services already running in the cluster. Making the two match is nigh impossible.

Spelling out a piece of this, to make this use case clearer: kpropd, the Kerberos replication daemon, uses `hostname` on the receiving end to determine what service credential it should be using for authentication purposes (e.g. "foo-0.default.pod.cluster-local"). On the sending side, however, it uses the hostname that it's connecting to (e.g. "kdc1.example.com") to generate the cryptographic secret that travels over the wire - and that hostname has nothing to do with the internal coredns state at all. If these do not match, then the cryptography involed cannot reproduce the same data on both ends, and authentication fails.

So migrating a Kerberos kpropd service in to Kubernetes requires an onerous hack in one of these areas:

1. upstream changes to the Kerberos code, so the kpropd can be told explicitly what hostname it should expect incoming authentication to be against (it does not do this at all today);
2. reconfiguration of the cluster _and_ the existing service, so its internal hostname exactly matches the external hostname;
3. an enhancement in k8s to support setting the externally-connectable hostname as the internal kernel hostname for a pod.

The internal pod hostname should only matter to the pod's running application(s). It should have no bearing on the outside state of the pod itself; and, if that is true, the regimented enforcement of any internal pod hostname is an arbitrary restriction that limits what software might be able to run in this environment.

**Comment by thockin** [comment]
Discussed a bit in sig-net today.  Historically I was a big proponent of keeping tight control of this, but it has come up enough times that I am willing to consider a more complete escape hatch.

The only thing that worries me is to define the complete gamut of options.

If I specify nothing, what hostname can I expect?

If I specify `hostname` what can I expect?

If I specify `hostname` and `subdomain` what can I expect?

If I specify `setHostnameAsFQDN` with the above cases, what can I expect?

If I specify this new field *and* any of the above, what can I expect?

Who wants to write a KEP?

**Comment by JorjBauer** [comment]
Some quick thoughts, which you've probably had, but I'm still climbing up this hill.

I don't have any substantive arguments against the existing naming model, although as a greybeard it was a bit puzzling that a pod has a potential FQDN, but internally doesn't seem to know about its own DNS zone (just knows about its short hostname). But as that seems to have been the norm in k8s for some time - and so many Linux distros have muddied the water with /etc/hostname coupled with both "hostname -s" and "hostname -f" for so long - it's not a hill I'm not willing to die on and also seems to have become standard expectation despite the ambiguity it's caused.

So I see no particular reason to upset the apple cart. I would think that, with no (let's call it) **forceHostname**: argument, both with and without **setHostnameAsFQDN** should behave as they do today (<pod name>, and <pod name>.<service>.<namespace>.<clusterdomain> respectively).

I think there are two obvious sane models that could extend from that.

First - **setHostnameAsFQDN** can be interpreted as "postpend the coredns zone", where it's always going to want to add .service.namespace.clusterdomain. If that's the case, then it doesn't matter if you specify a suffix in **forceHostname** or not: if **setHostnameAsFQDN** is set, then the coredns zone is always postpended to what you provided. If I set **forceHostname** to "foo.bar.default.cluster.local" and **setHostnameAsFQDN** as true, the pod's hostname becomes something like "foo.bar.default.clusterlocal.bar.default.clusterlocal".

Second - **forceHostname** could be considered an authoritative override. Whatever you set in **forceHostname** completely overrides anything else, which means that **setHostnameAsFQDN** is meaningless and ignored if **forceHostname** is provided.

Personally I prefer the second, but mostly because of the name used for **setHostnameAsFQDN**. The option's name ties it to the functionality of the default hostname-setting behavior, where k8s is the decision maker. It's also why I used 'force' in the new example moniker; to logically separate the two (k8s sets what it wants automatically unless it's forced to do otherwise). But I could see an implementor preferring the first behavior, in which case maybe they'd call the option **setHostname** to make it obvious that the two are paired (although it still might make sense to rename the **setHostnameAsFQDN** option to be **setHostnameWithFQDN** at some point).

My experience with k8s has only been about 2 years, and only in two specific bare metal models, so I'd certainly like to hear opinions of people that have been using it longer or in different scenarios.

**Comment by thockin** [comment]
> it was a bit puzzling that a pod has a potential FQDN, but internally doesn't seem to know about its own DNS zone (just knows about its short hostname)

Mistakes were made.  In hindsight there are things that could perhaps have been done differently, though I think the decisions all make sense in the context of the maturity and goals of the project :)

We could position it as `forceHostname` and say that it overriddes other fields.  Or we could say it is mutually incompatible with the other fields, and fail validation.  There are implications in that latter that I don't like - the existing `hostname` field is also used for programming DNS, so I don't think mutual-incompat works (I would want to see this discussed in the KEP's "alternatives" section :)

Let me think out loud on another approach.

Suppose we add a field which, for the sake of discussion and being different from your sketch, I will call `actualPodHostname`.  Kubelet will always respect that field if it is set (otherwise fall back on legacy behavior).  In defaulting or in REST logic, we could see that `actualPodHostname` was not set, and so look at `hostname` and `setHostnameAsFQDN` and the cluster suffix and write the result into `actualPodHostname`.  If the user set it themselves, we would leave it alone and treat it as an override.

This could eventually simplify kubelet as it could remove the legacy behavior, but it would mean teaching the apiserver about the cluster suffix and if we ever got more clever about that (there were some other discussions around configurable zone configs).  @prameshj

Having written it out, I don't know if I like the implications so much - I would seek more input.

Ergo - who's going to write the KEP?

**Comment by HirazawaUi** [comment]
/assign 
I'm willing to push it forward, but since switching roles has resulted in me no longer having access to this area in my actual job, I may not be able to provide some unique perspective in KEP.

**Comment by aojea** [comment]
was this fixed by https://github.com/kubernetes/kubernetes/pull/91699 ?

**Comment by HirazawaUi** [comment]
> was this fixed by #91699 ?

ref: https://github.com/kubernetes/enhancements/issues/4762#issuecomment-2230896402

**Comment by JorjBauer** [comment]
By my reading, no - #91699 sets the pod's hostname to the existing FQDN. This request is for arbitrary FQDNs, not the existing FQDN of the cluster.

**Comment by aojea** [comment]
yeah, was already clarified, my mistake , sorry for the noise

**Comment by thockin** [comment]
Now that we have KEP, I will close this issue.  Anyone who finds this can go read https://github.com/kubernetes/enhancements/issues/4762
