### ISSUE TITLE
kubeadm error log

### ISSUE THREAD

**Issue by CaoDonghui123** [kubernetes/kubernetes#97679]
**What happened**:
when run with containerd
```
# kubeadm config print init-defaults > k8s-init.yaml
W0104 16:58:41.462495   29081 kubelet.go:200] cannot automatically set CgroupDriver when starting the Kubelet: cannot execute 'docker info -f {{.CgroupDriver}}': executable file not found in $PATH

```

**What you expected to happen**:

no log

**How to reproduce it (as minimally and precisely as possible)**:
```
kubeadm config print init-defaults > k8s-init.yaml
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by wangyysde** [comment]
Have you installed docker kubelet on the system? The error message of "executable file not found in $PATH"  means you have not installed docker package or installed incorrectly.

**Comment by pacoxu** [comment]
Per https://github.com/kubernetes/kubeadm/issues/2364, try to rm /var/run/docker-shim.sock and /var/run/docker.sock.

**Comment by neolit123** [comment]
this is just a warning.
lets track the problem in https://github.com/kubernetes/kubeadm/issues/2364

/close

**Comment by CaoDonghui123** [comment]
@neolit123  Thank you very much
