### ISSUE TITLE
kubectl proxy support multi-cluster

### ISSUE THREAD

**Issue by wanghaoran1988** [kubernetes/kubernetes#97676]
**What would you like to be added**:
`kubectl proxy` commands support multi-cluster
**Why is this needed**:
Currently, `kubectl proxy` only support proxy to the `currentContext` in the kubeconfig.
When we have multiple clusters to manage, if we already have multiple contexst in the kubeconfig, multiple clusters support  will be much easier for us to manage the clusters through proxy.

**Comment by wzshiming** [comment]
Try this and see if it meets your needs
`kubectl config view -o template --template='PIDS=""{{"\n"}}{{range $index, $elem := .contexts}}kubectl proxy --context={{$elem.name}} --port=1000{{$index}} &{{"\n"}}PIDS="$! $PIDS"{{"\n"}}{{end}}trap "kill $PIDS" 0{{"\n"}}wait' | sh -`

**Comment by wanghaoran1988** [comment]
@wzshiming i'd prefer expose different url path for those clusters using the same port, eg we have two context "cluster1" & "cluster2", we can expose the proxy api like "/clusters/<cluster_name>/", so to access cluster1, the proxy url is: "http://localhost:8080/clusters/cluster1".

**Comment by wzshiming** [comment]
@wanghaoran1988 If the prefix is added, it is not an implementation of the ApiServer interface! Or does kubectl/client-go need to add a path prefix to the request?

**Comment by wanghaoran1988** [comment]
> it is not an implementation of the ApiServer interface!

What do you mean about that? it just gonna be an  api proxy that supports multiple cluster.

**Comment by wzshiming** [comment]
@wanghaoran1988 
![image](https://user-images.githubusercontent.com/6565744/103968601-1b9f3280-519f-11eb-8ecc-4af4112c4af6.png)
I mean something like this.
