### ISSUE TITLE
TopologySpreadConstraints related query

### ISSUE THREAD

**Issue by sunchill06** [kubernetes/kubernetes#97687]
**What happened**:
kube-scheduler scheduled the incoming pod on a node where non-standard node labels/keys were not applied.

**What you expected to happen**:
I expect the incoming pods should be in pending state if the topology spread constraints are not satisifed. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Created a cluster with **8** worker nodes. Apply custom labels to 6 nodes out of the 8 nodes.
2. Labelled the first 2 nodes with custom labels: zone=zone1, nodepool=np1
3. Labelled the next 2 nodes with custom labels: zone=zone1, nodepool=np2
4. Labelled the last 2 nodes with custom labels: zone=zone2, nodepool=np3
5. Provided the following topology constraints in the stateful-set's spec:

    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            foo: bar

       - maxSkew: 1
         topologyKey: nodepool
         whenUnsatisfiable: ScheduleAnyway
         labelSelector:
           matchLabels:
             foo: bar

      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
        matchLabels:
          foo: bar

Outcome of applying the above stateful-set's spec with a replicaCount of 6 
pod-1 is scheduled on node1 - zone1 - np1
pod-2 is scheduled on node3 - zone1 - np2
pod-3 is scheduled on node4 - zone1 - np2
pod-4 is scheduled on node5 - zone2 - np3
pod-6 is scheduled on node6 - zone2 - np3

**Problem is that pod-5 is getting scheduled on node7 or node8 that doesn't have any zone/nodepool labels. Also this can be replicated when I scale-out the stateful-set.** 

Now I expected that with the topology spread constraints provided, the incomings can only be scheduled or tried to be scheduled on the nodes that have the specific labels provided. Is the behavior that I am experiencing expected?

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.9
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 
-NAME="SLES"
VERSION="15-SP1"
VERSION_ID="15.1"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP1"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp1"

- Kernel (e.g. `uname -a`): 
Linux  4.12.14-195-default #1 SMP Tue May 7 10:55:11 UTC 2019 (8fba516) x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by sunchill06** [comment]
@Huang-Wei @ahg-g , please assist.

**Comment by gavinfish** [comment]
@sunchill06 `EvenPodsSpread` is disabled by default in 1.18.9, have you enabled its feature gate on both Api server and scheduler?

**Comment by Huang-Wei** [comment]
@sunchill06 thanks for the report.

This bug should have been fixed by #95812, and backported to 1.19 (#95880) and 1.18 (#95883). So give a try on the latest 1.18 patch release and let me know if it still exists.

**Comment by sunchill06** [comment]
Thanks @Huang-Wei , will that be 1.18.14?

**Comment by Huang-Wei** [comment]
> Thanks @Huang-Wei , will that be 1.18.14?

I think it's available on 1.18.12 and onwards.

```
⇒  git tag --contains 70f209cfe8d0bfebd666f25e0e611008795b9a48
v1.18.12-rc.1
```

**Comment by sunchill06** [comment]
Thanks a lot @Huang-Wei . I don't have the setup with 1.18.12 as of now, but soon will have it. I will test it then and come back if any issues.

**Comment by sunchill06** [comment]
Hi @Huang-Wei ,

one more follow-up query here:

**Kubernetes version:** v1.19.3

I have 4 worker nodes in a cluster where pods can be scheduled, and I am trying to apply only kubernetes.io/hostname topology spread constraint.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  labels:
    foo: bar
spec:
  replicas: 2
  selector:
    matchLabels:
      foo: bar
  template:
    metadata:
      labels:
        foo: bar
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            foo: bar
      containers:
      - name: pause
        image: k8s.gcr.io/pause:3.1

Here when I scale upto 4 pods, all the pods are equally distributed across 4 nodes i.e.1 pod on each node.

But as soon as I scale the deployment to 5 pods, the 5th pod is in pending state with following event msg:

**4 node(s) didn't match pod topology spread constraints.**

Any suggestions why this is happening?

**Comment by sunchill06** [comment]
Just to elaborate on this issue:

Kubernetes version: v1.19.3
Total worker nodes: 4

**Labels on the worker nodes:**

node1         Ready    worker   5d18h   v1.19.3   kubernetes.io/hostname=pool-1-ccd-stag-worker-1,node-pool=pool-1,topology.kubernetes.io/zone=zone1
node3         Ready    worker   5d18h   v1.19.3   kubernetes.io/hostname=pool-1-ccd-stag-worker-3,node-pool=pool-1,,topology.kubernetes.io/zone=zone1
node2         Ready    worker   5d18h   v1.19.3   kubernetes.io/hostname=pool-2-ccd-stag-worker-2,node-pool=pool-2,topology.kubernetes.io/zone=zone2
node4         Ready    worker   5d18h   v1.19.3   kubernetes.io/hostname=pool-2-ccd-stag-worker-4,node-pool=pool-2,topology.kubernetes.io/zone=zone2

**Note:**  Only showing the relevant labels.

**Case 1. deployment with only**

**Comment by Huang-Wei** [comment]
@sunchill06 I guess that's because of the master node. Suppose you have 1 master + 4 worker nodes, when you're trying to schedule the 5th Pod among `kubernetes.io/hostname`, the 5th Pod will be attempted to be scheduled to master. If you want to limit the context of "PodTopologySpread" to worker nodes only, you can specify a nodeSelector/nodeAffinity to exclude the master node. Hope this helps.

**Comment by sunchill06** [comment]
@Huang-Wei , thanks for your inputs. 

I actually tried this with nodeAffinity or zone as an additional topology constraint and then it works as expected.

Also, **what about case 2 (with only node-pool constraint),** why isn't that working because with node-pool, we are limiting the scope of the deployment to specific nodes with non-standard label node-pool only?

**Comment by Huang-Wei** [comment]
The master node doesn't have node-pool label, right?

**Comment by sunchill06** [comment]
my bad, master also did have the node-pool labels. thanks for clarifying all these doubts @Huang-Wei .
