### ISSUE TITLE
apiserver does not respect ip addresses in no_proxy when connecting to ingress-controller

### ISSUE THREAD

**Issue by laopisai** [kubernetes/kubernetes#97704]
**What happened**:
I set up a kubernetes cluster behind corporate proxy, one master node and one worker node. I configured the proxy setting in `/etc/environment` before running `kubeadm`.

contain of `/etc/environment`:
http_proxy="http://corporate.proxy"
https_proxy="http://corporate.proxy"
no_proxy="localhost,127.0.0.1,192.168.0.1/24,10.96.0.0/12,172.16.0.0/16"

node: 192.168.0.1/24
pod: 172.16.0.0/16
service: 10.96.0.0/12

I proceed to deploy ingress-nginx using baremetal yaml file

When I try to deploy an ingress resource, I get this error

> Error from server (InternalError): error when creating "ingress-myapp.yaml": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post https://ingress-nginx-controller-admission.ingress-nginx.svc:443/extensions/v1beta1/ingresses?timeout=30s: Gateway Timeout

I checked `/etc/kubernetes/manifest/kube-apiserver.yaml` and find that the environment variable is set the same as `/etc/environment`.

I append `ingress-nginx-controller-admission.ingress-nginx.svc` to `no_proxy` in `/etc/kubernetes/manifest/kube-apiserver.yaml` and the ingress resource is applied successfully.

**What you expected to happen**:
Ingress resource can be applied without adding `ingress-nginx-controller-admission.ingress-nginx.svc` to `no_proxy`

**How to reproduce it (as minimally and precisely as possible)**:
1) set proxy in `/etc/environment`
2) run `kubeadm` in master
3) run `kubeadm join` in worker
4) deploy ingress-nginx using [baremetal yaml](https://github.com/kubernetes/ingress-nginx/blob/master/deploy/static/provider/baremetal/deploy.yaml)
5) apply an ingress resource

**Anything else we need to know?**:
Nothing

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:00:47Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: private setup
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.1 LTS
- Kernel (e.g. `uname -a`): 5.4.0-58-generic
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): calico
- Others:

**Comment by wzshiming** [comment]
Try adding `*.svc` to no_proxy before creating the cluster (eg. no_proxy="*.svc,localhost,127.0.0.1,192.168.0.1/24,10.96.0.0/12,172.16.0.0/16")

**Comment by laopisai** [comment]
> Try adding `*.svc` to no_proxy before creating the cluster (eg. no_proxy="*.svc,localhost,127.0.0.1,192.168.0.1/24,10.96.0.0/12,172.16.0.0/16")

Thanks for the suggestion. Maybe this should be part of  `kubeadm init` pre-flight warning?

**Comment by wzshiming** [comment]
> > Try adding `*.svc` to no_proxy before creating the cluster (eg. no_proxy="*.svc,localhost,127.0.0.1,192.168.0.1/24,10.96.0.0/12,172.16.0.0/16")
> 
> Thanks for the suggestion. Maybe this should be part of `kubeadm init` pre-flight warning?

@neolit123  What do you think? Is it possible to add this pre-flight warning?

**Comment by neolit123** [comment]
i don't like the idea of adding this in preflight because it's setup specific.

**Comment by neolit123** [comment]
closing this as it's not a bug and a support ticket.
in the future please use:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
