### ISSUE TITLE
Unable to create deployment

### ISSUE THREAD

**Issue by Huangsh17** [kubernetes/kubernetes#97703]
We have been unable to create a deployment. Here is a screenshot of the log output
![image](https://user-images.githubusercontent.com/27496367/103601803-69206300-4f45-11eb-977a-54d17d19e875.png)

**Comment by wzshiming** [comment]
The log looks normal! Can you provide an example of replication?

**Comment by yangjunmyfm192085** [comment]
Provide more information？

**Comment by wzshiming** [comment]
Yes, Follow the bug-report template!  What happened? What you expected to happen?

**Comment by neolit123** [comment]
please use the support forums instead:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
/close
