### ISSUE TITLE
Getting Started with vagrant broken

### ISSUE THREAD

**Issue by tback** [kubernetes/kubernetes#9771]
I was following the [Getting started with Vagrant](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/vagrant.md) guide.
`curl -sS https://get.k8s.io | bash` fails silently with error code 5.
I suspect wget is to blame:

```
curl -sS https://get.k8s.io | bash -x
+ set -o errexit
+ set -o nounset
+ set -o pipefail
+ [[ -n '' ]]
++ get_latest_version_number
++ local -r latest_url=https://storage.googleapis.com/kubernetes-release/release/stable.txt
+++ which wget
++ [[ -n /usr/local/bin/wget ]]
++ wget -qO- https://storage.googleapis.com/kubernetes-release/release/stable.txt
+ release=
```

wget was installed through homebrew: GNU Wget 1.16.3 built on darwin14.1.0.

**Comment by tback** [comment]
Workaround: uninstall wget it works with curl

**Comment by roberthbailey** [comment]
(This seems to be a problem with the script rather than something specific to vagrant)

**Comment by roberthbailey** [comment]
Closing as obsolete as this hasn't been updated in almost two years.
