### ISSUE TITLE
In order to keep the code clean, it is better not to add useless parameters when writing and invoking functions

### ISSUE THREAD

**Issue by heqg** [kubernetes/kubernetes#97724]
**What would you like to be added**:
In order to keep the code clean, it is better not to add useless parameters when writing and invoking functions. 
However, the actual situation may not meet this requirement.It should be relatively easy to audit these and fix-up.
for example,  (ns *v1.Namespace , syncPeriod time.Duration) is not userd in function createAdClients[kubernetes/test/integration/volume/attach_detach_test.go]

**Why is this needed**:
/kind cleanup

**Comment by Aut0R3V** [comment]
Seems interesting, anything I can do here?

**Comment by BenTheElder** [comment]
/remove-sig testing
/sig storage
SIG storage owns there test, SIG testing owns the CI tools and test frameworks etc.

**Comment by heqg** [comment]
> s interesting, any

Thank you for your support.
For the above problems, I have submited two PRs. 
https://github.com/kubernetes/kubernetes/pull/97561,
https://github.com/kubernetes/kubernetes/pull/97567
Can you help me to review them? 
If reasonable, it is better to merge into master
thanks very much

> Seems interesting, anything I can do here?

**Comment by heqg** [comment]
> /remove-sig testing
> /sig storage
> SIG storage owns their tests, SIG testing owns the CI tools and test frameworks etc.

ok, i have got it, 
thanks
