### ISSUE TITLE
deleting the built-in cluster admin clusterrole does not seem to have any impact on authentication and authorization

### ISSUE THREAD

**Issue by liyongxin** [kubernetes/kubernetes#97758]
**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
CentOS-7
- **Kernel** (e.g. `uname -a`):
3.10.0-1127.10.1.el7.x86_64
- **Others**:

## What happened?
I installed the kubernetes cluster with kubedm, and then deleted the default cluster admin cluster role, but the kubectl command still works

## What you expected to happen?
After deleting the cluster admin clusterrole, kubectl should report an error and the authentication failed

## How to reproduce it (as minimally and precisely as possible)?
 mkdir -p $HOME/.kube
 sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
 sudo chown $(id -u):$(id -g) $HOME/.kube/config
 kubectl delete clusterrole cluster-admin

## Anything else we need to know?
config file uses kubernetes admin user and system:masters Group k8s authentication and authorization, but deleting the built-in cluster admin clusterrole does not seem to have any impact on authentication and authorization

**Comment by liggitt** [comment]
kubeadm creates superuser credentials with the built-in superuser group (`system:masters`):

https://github.com/kubernetes/kubernetes/blob/v1.20.0/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go#L418-L424

this group is automatically authorized to perform any action, regardless of RBAC configuration (or even RBAC enablement):

https://github.com/kubernetes/kubernetes/blob/v1.20.0/staging/src/k8s.io/apiserver/pkg/server/config.go#L852
