### ISSUE TITLE
kubelet: don't check for the Docker cgroup driver on Windows

### ISSUE THREAD

**Issue by henrik-m** [kubernetes/kubernetes#97759]
**What happened**:

I have a Kubernetes Cluster with 2 Windows Server 2019 Core VMs as worker nodes. I upgraded first the cluster, and then the first Windows node following the docs here: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes/

Every step ran without issue, but the kubelet service was not started. This was not immediately obvious, since "restart-service kubelet" does not propagate the error. I think "start-service kubelet" would be better advice.

The logs said: 

```
F0106 11:58:32.006122   17508 server.go:269] failed to run Kubelet: misconfiguration: kubelet cgroup driver: "systemd" is different from docker cgroup driver: "cgroupfs"
```

After changing the value of cgroupDriver manually in ```c:\var\lib\kubelet\config.yaml``` from "systemd" to "cgroupfs", the kubelet started successfully.

**What you expected to happen**:

One of 2 things: Either the Windows upgrade docs telling me what I need to do to fix this, or the kubeadm not breaking the configuration for windows in the first place.

**How to reproduce it (as minimally and precisely as possible)**:

1. Add a windows node to a Kubernetes v1.19 cluster via kubeadm
2. Upgrade the cluster via kubeadm
3. Upgrade the Windows node following the docs [here](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes/)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Windows Server 2019 Core
- Kernel (e.g. `uname -a`):
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:

/sig windows

**Comment by pacoxu** [comment]
this may cause by the default value of defaultCgroupDriver  cgroupfs

Would you provide the `docker info` from Windows node?

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/blob/a439bc55724f6560c14bf4e025946c0e6312629b/pkg/kubelet/dockershim/docker_service.go#L258-L274

/assign

**Comment by neolit123** [comment]
> One of 2 things: Either the Windows upgrade docs telling me what I need to do to fix this, or the kubeadm not breaking the configuration for windows in the first place.

kubeadm doesn't do anything about cgroup drivers on Windows because cgroups don't exist on Windows.
ideally the kubelet checks about this should be skipped entirely in dockershim for non-Linux.

**Comment by pacoxu** [comment]
![image](https://user-images.githubusercontent.com/2010320/103771871-84819000-5063-11eb-9d35-9d7b377483f5.png)
However, windows docker return `cgroup driver` as cgroupfs.

**Comment by neolit123** [comment]
probably `docker info`'s output is the same structure on all OSes with `cgroupfs` being a default value.
this field should not be checked on Windows at all.

**Comment by neolit123** [comment]
/retitle kubelet: don't check for the Docker cgroup driver on Windows

**Comment by neolit123** [comment]
adding `accepted` since the PR is favorable.
/triage accepted
