### ISSUE TITLE
When using Vagrant, I can't access my services (guestbook)

### ISSUE THREAD

**Issue by Industrial** [kubernetes/kubernetes#9776]
Hi. I'm using vagrant with virtualbox to run kubernetes.

    $ kubectl get pods
    NAME                 READY     REASON    RESTARTS   AGE
    frontend-80ru5       1/1       Running   0          10m
    frontend-kx4lk       1/1       Running   0          10m
    frontend-u708s       1/1       Running   0          10m
    kube-dns-o3i40       3/3       Running   0          13m
    redis-master-sy7z6   1/1       Running   0          11m
    redis-slave-h3hty    1/1       Running   0          10m
    redis-slave-v6hm7    1/1       Running   0          10m

    $ kubectl get services
    NAME           LABELS                                                              SELECTOR            IP(S)            PORT(S)
    frontend       name=frontend                                                       name=frontend       10.100.67.183    80/TCP
    kube-dns       k8s-app=kube-dns,kubernetes.io/cluster-service=true,name=kube-dns   k8s-app=kube-dns    10.100.0.10      53/UDP
                                                                                                                            53/TCP
    kubernetes     component=apiserver,provider=kubernetes                             <none>              10.100.0.1       443/TCP
    redis-master   name=redis-master                                                   name=redis-master   10.100.109.44    6379/TCP
    redis-slave    name=redis-slave                                                    name=redis-slave    10.100.147.147   6379/TCP

So I have this all running.

If I do a `vagrant ssh node-01` and then inside the vm do `curl 10.100.67.183:80` then I get the HTML output I'm looking for.

1. What I don't understand is which part of this architecture I should now edit in order to expose the frontend service over HTTP to the rest of my local network or at least my host machine.
2. Do I have to keep doing this port forwarding every time I deploy a service (or re-deploy it and it gets a different ip)?
3. Would a solution be possible in which all ports are just opened so I could just run any service in a dock and access it from the host machine?

**Comment by thockin-cc** [comment]
If you set your service.spec.type = NodePort, it will allocate you a port
on your VM's IP. You can find the allocated port number in
service.spec.ports[*].nodePort. Hitting that port on any node's main IP
should transport you to your service.

**Comment by Industrial** [comment]
Thanks.

I now have

```json
{
   "kind":"Service",
   "apiVersion":"v1",
   "metadata": {
      "name":"frontend",
      "labels": {
         "name":"frontend"
      }
   },
   "spec": {
      "type": "NodePort",
      "ports": [
        {
          "nodePort": 8080,
          "port": 80
        }
      ],
      "selector": {
         "name": "frontend"
      }
   }
}
```

but when I create the service I get:

`The Service "frontend" is invalid:spec.ports[0].nodePort: spec.ports[0].nodePort: invalid value '8080': provided port is not in the valid range`

**Comment by thockin-cc** [comment]
You don't get to pick any old NodePort.  It has to come out of a
master-configured range.  That's why it is easier to let the master
allocate it for you, just like the "portal" IP.  Otherwise it conflicts
with pod host ports and anything else running on nodes.

**Comment by Industrial** [comment]
@thockin-cc: I'm not sure what to do now. I don't know where I can configure this range of ports in the master. It does the delegation of ports if you dont specify a `service.spec.ports[0].nodePort`?

Having some piece give me a new host/port to view the service on would be nice. I don't mind if it would be random.

**Comment by thockin** [comment]
Set type=NodePort and that's all.  The master has a default port range
which should almost always be safe.  Submit your Service, then read it back
to see what NodePort you got.  Once you have a port assigned, it is yours
until you destroy the Service.

**Comment by Industrial** [comment]
frontend       name=frontend                                                       name=frontend       10.100.67.149    80/TCP

is the line printed for this service, but it doesnt include this random port :(

**Comment by thockin** [comment]
Try 'kubectl get -o json' or -o yaml
