### ISSUE TITLE
Object count quotas API has sharp edges

### ISSUE THREAD

**Issue by willdeuschle** [kubernetes/kubernetes#97765]
**What would you like to be added**:
Validation of object count quotas would help prevent misuse. The syntax is currently `count/<resource>.<group>` for non-core groups, meaning a count quota like `count/jobs` or `count/deployments` will be accepted but have no effect.

**Why is this needed**:
This recently bit us when quotas for a resource in a non-core group exceeded what we thought to be our configured limit. We were not applying count limits properly (leaving off the group for non-core resources) and did not have any feedback that our quotas were misformatted.

**Comment by neolit123** [comment]
/sig api-machinery
?

**Comment by yliaog** [comment]
a very specific validation rule to fail the resourcequota creation request for count/jobs or count/deployments are surely helpful to avoid the misconfigure issue you mentioned.
