### ISSUE TITLE
Azure disk PVC failing to detach/reattach when a pod in a deployment changes nodes

### ISSUE THREAD

**Issue by ebehar-openai** [kubernetes/kubernetes#97778]
**What happened**:

A pod with a successfully attached and mounted Azure Disk from a PersistentVolumeClaim was restarted on a different node. When it restarted, the volume that the pod was meant to have attached and mounted to it failed to reattach due to a multi-attachment error. This error never resolved, and so the pod was unable to access the PV referenced by the claim.

**What you expected to happen**:

The PV referenced by the PVC should detach and reattach to the pod correctly even when the pod moves across nodes.

**How to reproduce it (as minimally and precisely as possible)**:

Create an Azure disk storage class, and a new PVC with access mode `ReadWriteOnce` that uses that storage class. Create a deployment whose template both attaches and mounts the new PVC you've created, and that has a `nodeSelector` attribute specifying a test attribute, such as `pvc-test-candidate: true`

Label one node with the test attribute you used in the template `nodeSelector` attribute. Once the pod has scheduled and begun to run, delete the test attribute from the node and add it to a different node. Then, delete the pod associated with the deployment (not the deployment itself)

When the replacement pod schedules, it will be forced to a different node, however the disk will fail to attach to the new instance of the pod.

**Anything else we need to know?**:

We didn't see this issue on other cloud providers, so it's unusual to see it crop up with Azure disks.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.5
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04

**Comment by andyzhangx** [comment]
@ebehar-openai  could you paste the detailed error?
could be related to this issue: https://github.com/andyzhangx/demo/blob/master/issues/azuredisk-issues.md#25-multi-attach-error, and there is workaround in that issue
