### ISSUE TITLE
pull-kubernetes-e2e-azure-disk-vmss CI is failing

### ISSUE THREAD

**Issue by Jiawei0227** [kubernetes/kubernetes#97781]
**Which jobs are failing**: pull-kubernetes-e2e-azure-disk-vmss

**Which test(s) are failing**: pull-kubernetes-e2e-azure-disk-vmss

**Since when has it been failing**:

**Testgrid link**:
Example: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/97777/pull-kubernetes-e2e-azure-disk-vmss/1346890657825820672

**Reason for failure**:

**Anything else we need to know**:

This CI job for presubmit seems to be failing. I have created an empty PR to verify it
https://github.com/kubernetes/kubernetes/pull/97777

It seems there is something wrong in the cloud provider configuration

I found this in the event:
```
ProvisioningFailed: Failed to provision volume with StorageClass "azuredisk-1528-kubernetes.io-azure-disk-dynamic-sc-7hrjn": AzureDisk -  failed to get Azure Cloud Provider. GetCloudProvider returned <nil> instead
```

**Comment by Jiawei0227** [comment]
@msau42 Can you help to find an Azure team owner to take a look?

**Comment by msau42** [comment]
@andyzhangx can you help take a look?

**Comment by andyzhangx** [comment]
should be related to this PR: https://github.com/kubernetes/test-infra/pull/20398, incorrect prow config

**Comment by andyzhangx** [comment]
already fixed by https://github.com/kubernetes/test-infra/pull/20398

**Comment by Jiawei0227** [comment]
Thanks for the quick fix Andy!
