### ISSUE TITLE
Socket operation on non-socket kubelet error

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#9778]
Hello everyone,

I'm trying to make a Raspberry Pi 2 Kubernetes cluster. I've installed etcd, merged the patches (coreos/etcd#2308), cloned kubernetes and started hack/local-up-cluster.sh (with some modifications, e.g. I built my own kubernetes/pause, removed sudo, because of arch linux).

I'm using arch linux arm. 
***Everything start up fine if I start it via plain docker, e. g. my alpine image or resin/rpi-raspbian, but not if I start via kubernetes***

Some system info:
```
uname -a

Linux b827eb039fa1 3.18.14-2-ARCH #1 SMP PREEMPT Thu May 28 07:19:33 MDT 2015 armv7l GNU/Linux
```
```
docker version

Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/arm
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/arm
```
```
docker info

Containers: 3
Images: 10
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 3.18.14-2-ARCH
Operating System: Arch Linux ARM
CPUs: 4
Total Memory: 924.4 MiB
Name: b827eb039fa1
ID: A7E6:CAD3:7R3C:2ODB:WG75:BERV:QT6O:3KLN:BTOV:DDSM:A25P:EZSH
WARNING: No memory limit support
WARNING: No swap limit support
```

But, if I run this
```
cluster/kubectl.sh run my-test --image=luxas/alpine
```
it won't start the pod

When I check the events it says:
```
Sun, 14 Jun 2015 19:03:06 +0300   Sun, 14 Jun 2015 19:03:06 +0300   1         alp-3fc9x  Pod       spec.containers{alp}   created   {kubelet 127.0.0.1}   Created with docker id 41633d313a81f67ca49156e82108c10db885dfa62cbb7401bc0f15df559668d5
Sun, 14 Jun 2015 19:03:06 +0300   Sun, 14 Jun 2015 19:03:06 +0300   1         alp-3fc9x   Pod       spec.containers{alp}   failed    {kubelet 127.0.0.1}   Failed to start with docker id 41633d313a81f67ca49156e82108c10db885dfa62cbb7401bc0f15df559668d5 with error: API error (500): Cannot start container 41633d313a81f67ca49156e82108c10db885dfa62cbb7401bc0f15df559668d5: [8] System error: socket operation on non-socket
```

Is this a known issue with kubelet?
It would be good to get kubernetes up and running :smile:

**Comment by miekg** [comment]
This maybe: https://github.com/docker/docker/issues/14184

**Comment by luxas** [comment]
Thanks! Will check this out...

**Comment by luxas** [comment]
@miekg Can you explain to me what arguments kubelet sends to docker or how it starts the containers?
I didn't find for now that place in the source code...

Checked issue 14184 out and they now have solved the problem with **docker 1.7**, I wonder if kubelet gives some strange args to docker that makes it fail already in v1.6.2.

Thanks for the help

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

**Comment by luxas** [comment]
Yeah, I was thinking about closing it, it may work now with newer k8s (1.0.1) and docker (1.7.1)
Will try again

**Comment by luxas** [comment]
Yeah, I got k8s up and running for half a month ago! :smile:
It works with my own-built hyperkube, etcd and flannel images.
Kubernetes is v1.0.1 and Docker is v1.7.1

Please get in touch if you are interested in running Kubernetes on ARM. 
Maybe one could upload some instructions about that to  `/contrib` some day?
