### ISSUE TITLE
AWS: Instance using aufs fails to restart (after kernel upgrade)

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#9779]
The error from aws ec2 get-console-output says that the /mnt/docker device is not found or not ready.

**Comment by ngbinh** [comment]
I think I am hit with the same problem. Now if I restart a node, it will never come back. I cannot even ssh into it. 

https://gist.github.com/ngbinh/f42340600cc2007c9995

**Comment by davidopp** [comment]
@justinsb I moved this to P1, please move it to P2 if you think it is not a release blocker.

**Comment by justinsb** [comment]
This is fixed now :-)
