### ISSUE TITLE
How to recover user data

### ISSUE THREAD

**Issue by govadasrinivasa** [kubernetes/kubernetes#97790]
Hi,
 
Requirement/scenario - Microservice receive around 1000 user data records each time from the queue and will process data from to store in the respective databases. Once all the records processed then insert these 1000 records data into the respective database tables. 
Issue - How to recover/protect user processing data if Pod crashed suddenly in between processing (say 800 records processed out of 1000) due to some reason. I don't want my newly created Pod to start processing records from the beginning again.
Please let me the solution to this problem.

Thanks,
Srinivas

**Comment by neolit123** [comment]
please try the support forums instead:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
