### ISSUE TITLE
audit.k8s.io/v1 leakes 'kubectl exec' args to audit log when level=Metadata

### ISSUE THREAD

**Issue by djboris9** [kubernetes/kubernetes#97795]
**What happened**:
When audit.k8s.io/v1 Policy is configured with level=Metadata for resource pods/exec, it will create events in the form of:

	{
	  apiVersion: audit.k8s.io/v1
	  kind: Event
	  level: Metadata
	  objectRef: {
	    apiVersion: v1
		name: pod-example
		namespace: appl-example
		resource: pods
		subresource: exec
	  }
	  requestURI: /api/v1/namespaces/appl-example/pods/pod-example/exec?command=%2Fopt%2Fx%2Fadmincli&command=--token%3DMYSECRET&container=example&stderr=true&stdout=true
	  stage: ResponseComplete
	  userAgent: kubectl/v1.20.1 (linux/amd64) kubernetes/c4d7527
	  verb: create
	  ...
	}

for a command like: `kubectl exec pod-example -- /opt/x/admincli --token=MYSECRET`.

Therefore it leaks the arguments (which can contain sensitive information) of the command to the audit `Event` even if it's on level=Metadata.

In my opinion `kubectl exec` should only be used for debugging but nothing prevents users to misuse it to "control" the application, often requiring supplied tokens.

From a wrong `kubectl exec` usage this exposes more information to the audit log as there should be. It can lead to information exposure like:
- Security departement gets access to customer data (need-to-know principle violated)
- Regulated informations leaked to the log (GDPR, PCI-DSS etc. compliance violated)
- Log system contains higher classified data (classifications violated)

**What you expected to happen**:
An audit log of level=Metadata shouldn't expose the command of a `kubectl exec`. Other API calls expose fieldSelectors etc. to the RequestURI, but in my opinion, this is not comparable to the exec command arguments as it is more like a payload.

A way to improve this behaviour could be achived by:
- Stripping the query part from RequestURI away for level=Metadata.
  But this will also strip away field query arguments like resourceVersion or fieldSelector for other calls.
- Masking parts of the RequestURI only in the case of resource=pods/exec.
  But this will introduce an unconsistent behaviour compared to other events.
- Change the API for `kubectl exec` to use the POST Body to transfer the command.
  But this will be a breaking change.

I see currently three workarounds for this scenario:
- Disable logs for pods/exec
  But this will make you blind on such a critical call
- Create a custom sanitizing pipeline before logs are shipped away
- Disable permissions for pods/exec

**How to reproduce it**:
1. Create a kind configuration with auditing and host mounts configured:

```
$ cat kind.yaml 
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  metadata:
	name: config
  apiServer:
	extraArgs:
	  "audit-policy-file": "/media/host/audit-policy.yaml"
	  "audit-log-path": "/media/host/audit.json"
	extraVolumes:
	- name: "host"
	  hostPath: "/media/host"
	  mountPath: "/media/host"
	  readOnly: false
	  pathType: DirectoryOrCreate
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /tmp/kindmnt
	containerPath: /media/host
```

2. Create audit-policy with only metadata logs on pods/exec:

```
$ cat /tmp/kindmnt/audit-policy.yaml 
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
- level: Metadata
  resources:
  - group: ""
	resources: ["pods/exec"]
```

3. Create the kind cluster:

```
kind create cluster --config kind.yaml
```

4. Do a 'kubectl exec' to a pod:

```
kubectl -n kube-system exec etcd-kind-control-plane -- sh -c "echo 'mysecret'"
```

5. Verify the contents of the audit log (including the `mysecret` string):

```
$ tail -n 1 /tmp/kindmnt/audit.json | jq -r .requestURI
/api/v1/namespaces/kube-system/pods/etcd-kind-control-plane/exec?command=sh&command=-c&command=echo+%27mysecret%27&container=etcd&stderr=true&stdout=true
```

**Anything else we need to know?**:
Before creating this issue, I've written to security@kubernetes.io, to make sure this isn't considered a vulnerability that should be tracked privately. The outcome is that it's not considered as a sensitive vulnerability.

I'm not sure if this is just works-as-designed. But I guess, this should be documented at least as I don't think this is the expected behaviour for many users.

The question is if there should be any sanitizing implemented in the audit system or some other technical solution for it. I'm happy to create a PR if such a sanitizing should be implemented or the documentation should be extended.

**Environment**:
- Kubernetes version: v1.20.1
- Cloud provider or hardware configuration: On-Prem, official binaries
- OS: Red Hat Enterprise Linux 7.9
- Kernel (e.g. `uname -a`): `Linux [redacted] 5.8.6-2.el7.elrepo.x86_64 #1 SMP Thu Sep 3 11:33:31 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): N/A

**Comment by tallclair** [comment]
/remove-lifecycle stale

IMO this is working as intended. I definitely want to know the full set of arguments that are being passed to exec. Where there's a problem is that exec arguments are passed through query params. https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/1898-hardened-exec proposes requiring a POST request for exec, and moving the exec params into the request body. If we go that route, then the parameters would only be logged for the `Request` or `RequestResponse` log levels.
