### ISSUE TITLE
Scheduler: Reduce unnecessary PodInfo struct initialization

### ISSUE THREAD

**Issue by gavinfish** [kubernetes/kubernetes#97813]
**What would you like to be added**:

Originated from @ahg-g's TODO `AddPod/RemovePod should pass a *framework.PodInfo type instead of *v1.Pod.`. Some discussions at https://github.com/kubernetes/kubernetes/pull/97599#discussion_r550214325.

In scheduler, we use `PodInfo` to wrap pod with additional pre-computed information to accelerate processing. This issue is trying to reduce the construction of unnecessary PodInfo.

I will break this task into below items to make this more clearer. Now we have several places use `NewPodInfo`:

- [x] `NodeInfo.AddPod(pod *v1.Pod)`, caller of this function may call some of below functions as well, so we can pass PodInfo to this function and reuse it from some the callers sometimes.
- [x] `preFilterState.updateWithPod` -> `InterPodAffinity.Add/RemovePod` -> `PluginsRunner.RunPreFilterExtensionAdd/RemovePod`-> `frameworkImpl.RunFilterPluginsWithNominatedPods` | `DefaultPreemption.FindCandidates` (skip some private functions in the path), in both of the final callers, they will call `NodeInfo.AddPod(pod *v1.Pod)` as well.

`NewPodInfo` will also be called in `InterPodAffinity.PreFilter` and `InterPodAffinity.PreScore`, they will be called in `genericScheduler.Schedule`, but InterPodAffinity may be disabled, so I think there is no need to change them.

- [ ] ~~`PodNominator.NominatedPodsForNode` do not call `NewPodInfo` directly, but it relates with both`frameworkImpl.RunFilterPluginsWithNominatedPods` and `DefaultPreemption.FindCandidates`. We can track it with PodInfos rather than pods~~

**Why is this needed**:

This can help with scheduler performance with reducing complicated object construction.

/cc @ahg-g  @alculquicondor @chendave 
/sig scheduling
/assign

**Comment by gavinfish** [comment]
Hi @ahg-g after all these work, I am a little bit confused about your word ` nominated pods will need to be tracked as PodInfos rather than pods.`. I am afraid it will not help to reduce PodInfo construction now. Could you please explain more about it?

**Comment by ahg-g** [comment]
I was referring to the possibility of removing this instantiation: https://github.com/kubernetes/kubernetes/blob/d54e4498fcd37ac96f215d13ea1306f1f219a68f/pkg/scheduler/framework/runtime/framework.go#L673

to do this, we will need to change the [nominatedPodMap](https://github.com/kubernetes/kubernetes/blob/d54e4498fcd37ac96f215d13ea1306f1f219a68f/pkg/scheduler/internal/queue/scheduling_queue.go#L728) to have framework.PodInfo as value rather than v1.Pod.
