### ISSUE TITLE
kubernetes can create ingress with empty rule

### ISSUE THREAD

**Issue by like-inspur** [kubernetes/kubernetes#97825]
**What happened**:
kubernetes can create ingress with empty rule

**How to reproduce it (as minimally and precisely as possible)**:
ingree yaml like below,
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  rules:
  - {}
```
kubernetes create this successfully like below
```
root@mgt01:~# kubectl get ingress test -o yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  creationTimestamp: "2021-01-07T09:36:58Z"
  generation: 1
  name: test
  namespace: default
  resourceVersion: "177661752"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/test
  uid: e3433b3c-50cb-11eb-ba04-5254009197f9
spec:
  rules:
  - {}
status:
  loadBalancer: {}
```
**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.3

**Comment by pacoxu** [comment]
document here https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#ingressspec-v1-networking-k8s-io shows

Field | Description
-- | --
rulesIngressRule array | A list of host rules used to configure the Ingress. If unspecified, or no rule matches, all traffic is sent to the default backend.

**Comment by CaoDonghui123** [comment]
I don't think this is a bug

**Comment by neolit123** [comment]
> A list of host rules used to configure the Ingress. If unspecified, or no rule matches, all traffic is sent to the default backend.

/close
/sig network
