### ISSUE TITLE
Expose cloudCIDRAllocator as a cloud-provider interface

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#97835]
**What would you like to be added**:

cloudCIDRAllocator is part of nodeipam, which allows cloud provider to allocate node CIDRs according to IP address aliases:

https://github.com/kubernetes/kubernetes/blob/cea1d4e20b4a7886d8ff65f34c6d4f95efcb4742/pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go#L55-L61

But the current implementation is GCE only. We should expose the interface for out-of-tree cloud providers, so that all cloud providers could custom node CIDRs allocation.

And since we're going the delete legacy cloud providers in the future, the nodeipam logic shouldn't depend on cloud specific implementations.

**Why is this needed**:

Custom node CIDRs allocation based on cloud provider implementations.

/sig cloud-provider

cc @andrewsykim @cheftako

**Comment by cheftako** [comment]
Hi @feiskyer When the cloud provider extraction plan was put in place, Google was the only cloud provider with any interest in supporting the cloud cidr allocator. As such the community decided it would like a pared down version for the node ipam controller for the general case. Then Google (and anyone) else interested in more custom ipam control could run their own controller in the cloud controller manager using the provided extension mechanisms. This part of what is going into https://github.com/kubernetes/cloud-provider-gcp/pull/178. The longer term plan in fact includes moving the current cloud cidr allocator out of K/K and into K/cloud-provider-gcp. Please feel free to add an item to either the sig cloud provider meeting or cloud provider extraction meeting and lets chat about it. If those meeting times do not work for you please reach out to either myself or @andrewsykim and we can see about having a special meeting.

**Comment by cheftako** [comment]
Along the previously mentioned lines. https://github.com/kubernetes/kubernetes/pull/97925#issuecomment-758173011

**Comment by feiskyer** [comment]
@cheftako thanks for the response. it makes sense to add this in out-of-tree cloud provider. I would log an issue in cloud-provider-azure to support cloudCIDRAllocator.

/close
