### ISSUE TITLE
Should the taint manager permanently delete a pod without a controller?

### ISSUE THREAD

**Issue by lingsamuel** [kubernetes/kubernetes#97832]
**What happened**:

Pods created directly (without a controller) may be permanently evicted by taint manager.

**What you expected to happen**:

Just a discussion, [per the doc](https://kubernetes.io/docs/concepts/workloads/pods/#working-with-pods):

> This is because Pods are designed as **relatively ephemeral**, disposable entities. 
> ...
> The Pod remains on that node until the Pod finishes execution, the Pod object is deleted, the Pod is evicted for lack of resources, or the node fails.

The eviction is reasonable, but there is no controller to restart it.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a pod without toleration, scheduled to nodeX
2. Taint the nodeX NoExecute
3. The pod is deleted and never come back

**Anything else we need to know?**:

The taint manager behavior is simply delete the pod.

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Install tools: minikube v1.16.0

/sig node

**Comment by pacoxu** [comment]
[Doc: Evicting end-user Pods](https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#evicting-end-user-pods)
> The kubelet ranks Pods for eviction first by whether or not their usage of the starved resource exceeds requests, then by Priority, and then by the consumption of the starved compute resource relative to the Pods' scheduling requests.

`Create Pods with priorityClassName` would change the eviction order. To avoid eviction, `system-node-critical` priorityClassName is a choice.


If a pod without controller have a higher priority, it will not be evicted even it uses lots of compute resource. (IMO, this is not expected.) [Pods are considered to be relatively ephemeral. ](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-lifetime)

**Comment by lingsamuel** [comment]
IMO pod is considered ephemeral because most of them are managed by controllers. Users may not expect their "orphan" pods to be deleted permanently.
