### ISSUE TITLE
Support multi namespaces list-watch

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/kubernetes#97831]
**What would you like to be added**:

Provide label selector for namespaces when list-watching resources.

**Why is this needed**:

It is very common for an operator or to manage some resources selectively mostly by namespaces. Currently, they have to either create one informer per namespace or one informer but filter out resources that do not belong to them. It is very helpful if this could be done in kube-apiserver.

**Comment by lavalamp** [comment]
For the foreseeable future I recommend just watching the namespaces individually with the client.

Somewhat ironically, we just accepted https://github.com/kubernetes/enhancements/pull/2162 which will add namespace labels and let you filter by them. But it will be *extremely* inefficient if you use that in a watch of all objects, because apiserver will examine every change in the system.

@wojtek-t could the indexing feature we added help this?

**Comment by wojtek-t** [comment]
> Somewhat ironically, we just accepted kubernetes/enhancements#2162 which will add namespace labels and let you filter by them. But it will be extremely inefficient if you use that in a watch of all objects, because apiserver will examine every change in the system.
@wojtek-t could the indexing feature we added help this?

Didn't read the KEP recently so I'm not sure how exactly it looks like, but is the namespace-label going to be added to every single object? [I think that initially it was supposed to only add the label for the `Namespace` object.]
If that is really the case, then I don't think it's particularly helpful - we would need this label to be added for every resource...

Re indexing - yes, we can try doing that. I have a bit hacky WIP PR opened for the list case: https://github.com/kubernetes/kubernetes/pull/88072, but we can potentially do something similar for the watch indexes too:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go#L81

**Comment by lavalamp** [comment]
Oh, you're right, it's of course only namespace objects. 🤦 

I still think this is close to impossible, since the watch cache is not on for all resources.

I guess we can leave this request open for a while in case someone has a brainstorm.
