### ISSUE TITLE
kubectl describe should reuse already fetched API objects instead of making another API call

### ISSUE THREAD

**Issue by ankeesler** [kubernetes/kubernetes#97852]
/sig cli

**What would you like to be added**:

- The `kubectl describe` code makes live API calls for each object it wants to describe (e.g., https://github.com/kubernetes/kubernetes/blob/cc09a6df5805574394e2eff285756d2886b34805/staging/src/k8s.io/kubectl/pkg/describe/describe.go#L4024).
- However, the object that it wants to describe has already been fetched from the API (i.e., https://github.com/kubernetes/kubernetes/blob/9a386cdd5d703d310ef82e892501621665c5eb00/staging/src/k8s.io/kubectl/pkg/cmd/describe/describe.go#L167).
- I would like for those already fetched API objects to be reused, whenever possible, in each `describe.ResourceDescriber` (i.e., https://github.com/kubernetes/kubernetes/blob/9a386cdd5d703d310ef82e892501621665c5eb00/staging/src/k8s.io/kubectl/pkg/describe/interface.go#L44).

**Why is this needed**:

- When running on my machine with a `kind` cluster and 100 ConfigMaps's, `kubectl describe cm cm- 1>/dev/null 2>/dev/null` takes  about `38s` because a live API call is made for every `ConfigMap` that is being described.
- When I make a code change to pass the `info.Object` directly to the `ConfigMapDescriber` and run the same test as I did above with 100 ConfigMap's, I get a runtime of about `18s`.
- Using that same code change, if I pass `--show-events=false`, the runtime goes down to about `2s`.

**Notes**

- This was brought up in PR review here: https://github.com/kubernetes/kubernetes/pull/97811#discussion_r553450064.

**Comment by knight42** [comment]
I would like to help.
/assign

**Comment by liggitt** [comment]
note that `describe` can be used with a file input (e.g. `kubectl describe -f file.yaml`), in which case the expected behavior is for the object in the file to be fetched from the server and described. we need to ensure that behavior is not modified as part of optimizing the case where the object was already fetched from the server

**Comment by knight42** [comment]
> note that describe can be used with a file input

@liggitt I believe we could invoke `.Latest()` on `resource.Builder` to enforce it to fetch objects from the server.

**Comment by knight42** [comment]
@ankeesler I just realize there is lots of refactoring to do to make `kubectl describe` reused the fetched objects, let alone updating the tests... I am unavailable to finish all the work within a single PR, is it possible to do this progressively?

**Comment by ankeesler** [comment]
@knight42:

Short answer - yes, I think doing this progressively is a healthy way to go about it.

Long answer - I only have a very elementary mental mode of this `kubectl describe` code, and therefore I may not be the best resource for how to do this progressively. One way that does come to mind, though, is updating the `describe.ResourceDescriber` interface method to take an optional `runtime.Object` (i.e., a `*resource.Info`) in a first commit, and then updating each `describe.ResourceDescriber` implementation in the following commits. Note that someone with more experiencing with and knowledge about the `kubectl describe` code (maybe that is you!) may want this to move in a separate direction.
