### ISSUE TITLE
kubectl top pods -o wide

### ISSUE THREAD

**Issue by joshkurz** [kubernetes/kubernetes#97859]
I'd like to add this feature to top pods. 

Its often very useful to grep out hungry pods by nodes that we know have high utilization. 
Currently I have to get pods -o wide | grep nodeip, to see the pods on that node. then top those pods to find the hungry ones on a specific node. It would be useful if top had a wide option for pods.

Let me know if this is a useful feature and I can write up a PR for it.

**Comment by matucker-msft** [comment]
I'm a big fan of the kube-capacity plugin: https://github.com/robscott/kube-capacity

**Comment by Ogguz** [comment]
> Let me know if this is a useful feature and I can write up a PR for it.

Sorry, I haven't noticed it. /unassign

**Comment by eddiezane** [comment]
/triage accepted

@joshkurz we'd like to see a demo of this to decide if it'd make sense.
