### ISSUE TITLE
Support PKCS#11 in kubelets 

### ISSUE THREAD

**Issue by chris13524** [kubernetes/kubernetes#97851]
kubelets should support storing kubeconfig certificate private keys inside an HSM using PKCS#11. This is particularly useful for IoT scenarios.

Ref:
 - https://github.com/kubernetes/kubernetes/issues/64783
 - https://github.com/kubernetes/enhancements/pull/1749

**Comment by sftim** [comment]
Combined with SoftHSM, this also allows a bit more security even without hardware support.

**Comment by iamruhua** [comment]
Same here, my current project requires to store Root certificate in system like HSM.
It's acceptable to ask for a middleware like KMS or other https program to adapt with k8s infrastructure to create Root of Trust mechanism.

**Comment by liggitt** [comment]
hoisting from the [linked enhancement proposal](https://github.com/kubernetes/enhancements/pull/1749#issuecomment-755738311):

> Following discussion in the December 9th and January 6th sig-auth meetings, rather than adding APIs around external TLS signing, using a local proxy (kubectl -> local proxy -> apiserver) is preferred. This proxy could be configured globally via proxy envvars or per-cluster with the proxy-url field in a kubeconfig file. This would allow the proxy to use any method it desired to establish the TLS connection to the API server, as well as do any other desired transformations.
> 
> If there are gaps that would block doing this in a reasonable way (for example, supporting talking to a proxy over a unix domain socket), requests/proposals to address those specific gaps would be welcome.

/close
