### ISSUE TITLE
The token of the DeploymentController will not be consistent with the token-controller while the token-controller makes an error and recreate the secrets again

### ISSUE THREAD

**Issue by Yuan-Junliang** [kubernetes/kubernetes#97876]
**What happened**:
A Deployment can't be deployed, and show “Unauthorized” fail info. 
The kube-controller-manager output the following log:
I1227 02:21:51.732634       1 event.go:281] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"default", Name:"xxx-webhook", UID:"ac20477e-b092-4dd6-8c1e-e018f9f1f472", APIVersion:"apps/v1", ResourceVersion:"585", FieldPath:""}): type: 'Warning' reason: 'ReplicaSetCreateError' Failed to create new replica set "xxx-webhook-5b8fcdc68f": Unauthorized

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
There is "etcdserver: request time out " in DeploymentController starting log
I1227 02:21:10.052598       1 deployment_controller.go:152] Starting deployment controller
I1227 02:21:10.052606       1 shared_informer.go:197] Waiting for caches to sync for deployment
E1227 02:21:21.858057       1 tokens_controller.go:260] error synchronizing serviceaccount kube-system/deployment-controller: etcdserver: request timed out

At the same time there is Delete Secrets info in kube-apiserver log
I1227 02:21:21.857727       1 trace.go:116] Trace[1007764599]: "Delete" url:/api/v1/namespaces/kube-system/secrets/deployment-controller-token-tc5f2,user-agent:kube-controller-manager/v1.17.9 (linux/amd64) kubernetes/59603c6/tokens-controller,client:1111::3c78 (started: 2020-12-27 02:21:20.982215484 +0800 CST m=+31.635596762) (total time: 875.473857ms):
Trace[1007764599]: [875.441361ms] [875.385615ms] Object deleted from database

tokens_controller.go
ensureReferencedToken()
We think that DeploymentController secret is created, but when updating the secret to service account  kube-apiserver happen "etcdserver request time out", so token_controller delete the secret.
token_controller will retry, and create a new secret
but DeploymentController secret is old that is the same as the first created in token_controller

Do you think so?

How to deal with this situation?
retry after updating secret fail to SA
or add a goroutin to refresh secret in DeploymentController

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
What version and deployment are you seeing this on? Versions since 1.15 use renewable bound service account tokens (see #72179 ) if that feature is enabled (which it is required to be in 1.20)

**Comment by liggitt** [comment]
I think the most likely next step is to remove use of secret-based tokens from the controller manager in 1.21, since non-secret-based tokens are available starting in 1.20

**Comment by liggitt** [comment]
cc @zshihang

**Comment by liggitt** [comment]
will likely be resolved in 1.21 as part of https://github.com/kubernetes/kubernetes/issues/98885

**Comment by liggitt** [comment]
this is resolved in 1.21 by https://github.com/kubernetes/kubernetes/pull/99324
