### ISSUE TITLE
kubectl drain keep going when one node failed

### ISSUE THREAD

**Issue by pandaamanda** [kubernetes/kubernetes#97907]
**What would you like to be added**:
`kubectl drain` on multiple nodes, if one node failed, the command aborting. Without special purpose, maybe it's better to continue processing other nodes.

```
[root@node24 /]# kubectl drain --selector="kubernetes.io/arch=amd64" --ignore-daemonsets
node/10.229.87.57 cordoned
node/10.229.87.58 cordoned
node/10.229.87.60 cordoned
error: unable to drain node "10.229.87.57", aborting command...

There are pending nodes to be drained:
 10.229.87.57
 10.229.87.58
 10.229.87.60
error: cannot delete Pods not managed by ReplicationController, ReplicaSet, Job, DaemonSet or StatefulSet (use --force to override): default/test
```

**Why is this needed**:
Follow the pattern of other `kubectl` subcommand, such as kubectl delete.

**Comment by pandaamanda** [comment]
done
/close

**Comment by dougsland** [comment]
> done
> /close

I would wait the patch get merged before closing :)
