### ISSUE TITLE
The deployments can't be created, it's stuck all the time, and the pod hasn't been created

### ISSUE THREAD

**Issue by Huangsh17** [kubernetes/kubernetes#97910]
The deployments can't be created, it's stuck all the time, and the pod hasn't been created
![image](https://user-images.githubusercontent.com/27496367/104167307-15c37e80-5437-11eb-80fe-3ee3f62dc9c5.png)
![image](https://user-images.githubusercontent.com/27496367/104167331-1b20c900-5437-11eb-91ac-a6aa6d48ed35.png)

**Comment by pandaamanda** [comment]
@Huangsh17  can you execute the command `kubectl describe rs whoami-5548dd78bb`  to get more info?

**Comment by NovaHe** [comment]
Looks like the api-server muting/validating failed. 
Run the following command to check whether the muting/validating server is running:
```bash
kubectl get mutatingwebhookconfigurations.admissionregistration.k8s.io
kubectl get validatingwebhookconfigurations.admissionregistration.k8s.io
```

**Comment by Huangsh17** [comment]
> @ Huangsh17 您可以执行命令`kubectl describe rs whoami-5548dd78bb` 以获取更多信息吗？

![image](https://user-images.githubusercontent.com/27496367/104258354-587a6a80-54ba-11eb-8de1-1b78ba2b907a.png)

**Comment by Huangsh17** [comment]
> 看起来api服务器静音/验证失败。
> 运行以下命令，检查是否存在屏蔽/验证Webhook配置：
> 
> ```shell
> kubectl获取mutatingwebhookconfigurations.admissionregistration.k8s.io 
> kubectl获取验证的webhookconfigurations.admissionregistration.k8s.io
> ```
> 
> 并检查静音/验证webhook服务器是否工作

![image](https://user-images.githubusercontent.com/27496367/104258450-8c559000-54ba-11eb-8662-dd5445010ec0.png)
