### ISSUE TITLE
Stop using bazel for unit tests

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#97921]
**What would you like to be added**:

Switch the unit test job to use go test (e.g. `make test`) instead of using bazel.

**Why is this needed**:

The unit test job is one of the few remaining places we use bazel (https://github.com/kubernetes/kubernetes/issues/88553)

**Comment by liggitt** [comment]
cc @BenTheElder

**Comment by spiffxp** [comment]
/milestone v1.21
Focus on doing this for the v1.21 tests first

Depending on how much test-gap/fix work this uncovers, decide whether to backport or age-out for supported release branches

**Comment by BenTheElder** [comment]
This is done. See: https://github.com/kubernetes/enhancements/pull/2420

**Comment by BenTheElder** [comment]
context on what all actually had to happen: https://github.com/kubernetes/enhancements/issues/2420#issuecomment-785663043
