### ISSUE TITLE
kube-proxy should not intercept LB traffic when the LB type Service has no Selector

### ISSUE THREAD

**Issue by maplain** [kubernetes/kubernetes#97928]
**What happened**:
When Service has loadBalancerIP allocated, access to LB VIP from the cluster nodes is intercepted by kube-proxy. Requests are routed the same as clusterIP traffic.

However, when the Service selector is explicitly undefined and Endpoints manually populated by an external component, kube-proxy should NOT serve the LB traffic as the backend IPs are not managed by K8s, and probably non-local.

**What you expected to happen**:
Access to LB VIP from the cluster nodes should be routed normally and served by the LB directly when Service doesn't have Selector defined

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Service without Selector;
2. Manually populate the Endpoints with backend IPs;
3. Query the LB IP from any one of the cluster nodes;
4. Check the access log on LB and expect to see no record for the queries in #3;

**Anything else we need to know?**:
No

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1+vmware.2", GitCommit:"9d9a7637ad75801f9296a1cebe63120c020305d4", GitTreeState:"clean", BuildDate:"2020-09-22T22:55:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
NAME="VMware Photon OS"
VERSION="3.0"
ID=photon
VERSION_ID=3.0
PRETTY_NAME="VMware Photon OS/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://vmware.github.io/photon/"
BUG_REPORT_URL="https://github.com/vmware/photon/issues"
```
- Kernel (e.g. `uname -a`):
``` 
Linux tkg-cluster-wc-743-md-0-8bdb9cc86-z7qwd 4.19.145-2.ph3 #1-photon SMP Wed Sep 23 02:26:04 UTC 2020 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by uablrek** [comment]
This is expected behaivor from `kube-proxy`. It does not know anything about the "selector" it cares only about endpoints (and endpointslices), no matter how they are set.

However there are other ways. It seems you want to setup load-balancing yourself and keep `kube-proxy` out of it. If so use the `service.kubernetes.io/service-proxy-name` label;
```
apiVersion: v1
kind: Service
metadata:
  name: special-need-service
  labels:
    service.kubernetes.io/service-proxy-name: custom-proxy
```
Kube-proxy checks this label and will ignore the service completely. This mean that no load-balancing for clusterIP is made either of course, but you can create a service dedicated for external traffic.

Your own load-balancer setup should also filter on the label and only setup load-balancing for "its own" services.

I hope these tools will allow you to setup custom load-balancing the way you want.

**Comment by thockin** [comment]
Agree with @uablrek  - the behavior you describe is expected.

We will soon support a way to tell the proxy to not intercept an IP (https://github.com/kubernetes/kubernetes/pull/97681) but the above is a complete solution.  What benefit are you getting from Services here?
