### ISSUE TITLE
Switch to new location and version for cfssl and cfssljson (cfssl and cfssljson installed via ./hack/local-cluster-up.sh broken)

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#97929]
Looks like the hardcoded URL - `https://pkg.cfssl.org/R1.2/cfssl_linux-amd64` is not working anymore and returns:

```
<html>
<head><title>522 Origin Connection Time-out</title></head>
<body bgcolor="white">
<center><h1>522 Origin Connection Time-out</h1></center>
<hr><center>cloudflare-nginx</center>
</body>
</html>
```

Having said that - installation from https://github.com/cloudflare/cfssl works.

**Comment by dims** [comment]
looks like we have a bunch of locations to fix:
https://cs.k8s.io/?q=pkg.cfssl.org&i=nope&files=&repos=kubernetes/kubernetes,kubernetes/test-infra,kubernetes/website

Looks like this was their plan all along:
https://github.com/cloudflare/cfssl/issues/995#issuecomment-548473012

They have yum/apt repos in:
https://pkg.cloudflare.com/

**Comment by nickysemenza** [comment]
Sorry that page is offline, we're looking at it internally (https://github.com/cloudflare/cfssl/issues/1165#issuecomment-758277988) 

It's also worth nothing that http://pkg.cfssl.org/ (http _does_ work) only has versions from 2018 and prior (I see 1.2.0 is being used here), newer + current versions are available at https://github.com/cloudflare/cfssl/releases, but i'm not sure if there's changes between versions that would break your workflows. (Unfortunately we haven't gotten around to publishing debs for cfssl on pkg.cloudflare.com yet.)

**Comment by Haleygo** [comment]
Seems like "https://pkg.cfssl.org" can't be used but "http://pkg.cfssl.org" works fine. 
Since the version 1.2.0 is old, I replace them with latest 1.5.0 installation from https://github.com/cloudflare/cfssl in https://github.com/kubernetes/kubernetes/pull/97947.
Is that ok? @gnufied @dims

**Comment by dims** [comment]
@Haleygo yes, 1.5.0 will do. thanks!
