### ISSUE TITLE
Cleanup the networkpolicy tests folder

### ISSUE THREAD

**Issue by knabben** [kubernetes/kubernetes#97920]
**What would you like to be added**:
Remove the `test/e2e/networking/networkpolicy` folder in favor of `test/e2e/networking/netpol`.

**Why is this needed**:
With the refactoring from the Netpol validation [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1611-network-policy-validation), the tests from `networkpolicy` folder are deprecated and duplicated at this point. 

Action items:

- [x] <strike>Ensure the same coverage of the old netpol tests</strike>
- [x] [Move SCTP](https://github.com/kubernetes/kubernetes/pull/97897) tests
- [x] [Move Netpol API](https://github.com/kubernetes/kubernetes/pull/97898) tests
- [x] [Delete the `test/e2e/networking/networkpolicy` folder](https://github.com/kubernetes/kubernetes/pull/98341)

**Comment by jayunit100** [comment]
thank you @knabben ... !
