### ISSUE TITLE
[ERROR] plugin/errors: 2 staging-gondor-api.postgres.database.azure.com. A: dial tcp 168.63.129.16:53: i/o timeout

### ISSUE THREAD

**Issue by RSE132** [kubernetes/kubernetes#97927]
**What happened**:
TCP DNS query is failing. Only works with UDP

**What you expected to happen**:
Expecting name resolution using tcp as well

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

PODs using ExternalName type service to querry staging-gondor-api.postgres.database.azure.com. Query using tcp fails when queried against ExternalName. 

ExternalName = gondor-sql-db.captainpeter-staging.svc.cluster.local

bash-5.0# dig gondor-sql-db.captainpeter-staging +search +tcp

; <<>> DiG 9.16.6 <<>> gondor-sql-db.captainpeter-staging +search +tcp
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 50117
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: b27c3be7eccae938 (echoed)
;; QUESTION SECTION:
;gondor-sql-db.captainpeter-staging.svc.cluster.local. IN A

But if I use staging-gondor-api.postgres.database.azure.com the the tcp query is successful

bash-5.0# dig staging-gondor-api.postgres.database.azure.com +search +tcp

; <<>> DiG 9.16.6 <<>> staging-gondor-api.postgres.database.azure.com +search +tcp
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48960
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;staging-gondor-api.postgres.database.azure.com.	IN A

;; ANSWER SECTION:
staging-gondor-api.postgres.database.azure.com.	30 IN CNAME cr8.westeurope1-a.control.database.windows.net.
cr8.westeurope1-a.control.database.windows.net.	30 IN A	104.40.169.187

;; Query time: 216 msec
;; SERVER: 169.254.20.21#53(169.254.20.21)
;; WHEN: Mon Jan 11 19:48:15 UTC 2021
;; MSG SIZE  rcvd: 243

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17
- Cloud provider or hardware configuration: azure AKS
- OS (e.g: `cat /etc/os-release`): Ubuntu

**Comment by neolit123** [comment]
> Kubernetes version (use kubectl version): 1.17

1.17 is out of support.

> PODs using ExternalName type service to querry staging-gondor-api.postgres.database.azure.com. Query using tcp fails when queried against ExternalName.

this doesn't look like a bug in core k8s.

please try the support channels instead:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
