### ISSUE TITLE
Install gce-pd-csi-driver by default in the kube-up script

### ISSUE THREAD

**Issue by Jiawei0227** [kubernetes/kubernetes#97985]
CSI Migration has been beta for a few releases. We are planning to move forward and progress CSI Migration towards GA. CSI Migration is a multi-cloud-provider and multi-driver effort project. So we are planning to move gce-pd in-tree plugin to CSIMigrationGCE GA first. 

A very first step we can do is to install the gce-pd-csi-driver into the OSS kubernetes distribution. 

cluster/kube-up.sh has been used for bringing up clusters and tests. So it is a good place to start by installing the GCE PD CSI Driver there in order to move forward. 

/sig storage
/cc @msau42 @mattcary

**Comment by Jiawei0227** [comment]
@mattcary Is anyone on your team going to work on this?

**Comment by mattcary** [comment]
/assign @mattcary 

This is in our wheelhouse. Before we do this, though, we should probably have a complete timeline including when PD CSI becomes the default storageclass.

It's also not clear to me who uses kube-up outside of kubetest and when k/k/cluster/gce is going away in favor of cloud-provider-gcp?

**Comment by verult** [comment]
Adding another related task here: Once PD CSI driver installation is in kube-up, we should remove the separate installation in e2e tests.

https://github.com/kubernetes/kubernetes/blob/4a8b2d377ba51124c0277ed4e25afe2eeefda085/test/e2e/storage/drivers/csi.go#L480

**Comment by Jiawei0227** [comment]
@mattcary As we discussed offline, maybe we should target it in 1.21

**Comment by mattcary** [comment]
/lifecycle frozen

Targeting 1.22 now.
