### ISSUE TITLE
Expose retry-after HTTP response header variable as a kube-apiserver cli option

### ISSUE THREAD

**Issue by rackeric** [kubernetes/kubernetes#97991]
**What would you like to be added**:

There is a hardcoded variable for the HTTP response header "retry-after" that I would like to have exposed as a cli option for the kube-apiserver binary. The "retry-after" is internally set to 1s which can cause issues on clusters as large as 1k nodes. Allowing this to be tuned could allow us to minimize, if not eliminate, the issue described below.

**Why is this needed**:

Working with large clusters we have had several issues where the large number of kubelets reconnecting and causing the entire kube-apiserver to become unavailable. This retry-after HTTP response header is already being sent to clients, but with a hardcoded 1s value. We want to expose this so we can tune it to meet our needs and help our thundering herd issue.

I understand that more work will need be done on kubelet side to implement an exponential backup as well but I believe both this change and the change described in this issue should be pursued. 

I've submitted the following: https://github.com/kubernetes/kubernetes/pull/97430

**Comment by yue9944882** [comment]
instead of tuning retry-after intervals, this issue should be solved by [APIPriorityAndFairness](https://kubernetes.io/docs/concepts/cluster-administration/flow-control/). what's your server version?

**Comment by lavalamp** [comment]
The current 1s delay is hot-loop protection, not ddos / thundering herd protection.

The actual solution is the API priority and fairness feature that we're working on. It's beta in 1.20, so you can try now to see if it helps your situation--if not we'd like to know.
