### ISSUE TITLE
Configuration option for CA certificate chain

### ISSUE THREAD

**Issue by coboluxx** [kubernetes/kubernetes#97994]
We need a way to provide the full CA chain with the service account token when using an intermediate CA from a private PKI. This is required because some clients may try to validate the full chain when talking to the API. 

Currently we have to provide a custom configmap and config but I think there could be an easy universal solution.

Background: The CA certificate is provided trough the --root-ca-argument. For the --root-ca-file argument of the controller manager, the documentation states:

> --root-ca-file string
> If set, this root certificate authority will be included in service account's token secret. This must be a valid PEM-encoded CA bundle.

The term bundle let me believe that this file could contain the full chain. Unfortunately providing more than one certificate results in an error:

> error starting controllers: failed to start kubernetes.io/kubelet-serving certificate controller: error reading CA cert file "csr-controller::/etc/kubernetes/pki/ca.crt::/etc/kubernetes/pki/ca.key": expected 1 certificate, found 4

To my surprise new secrets received the full chain even with the controller-manager in a crashloop.

The next option I found was the rootcacertpublisher (controller/certificates/rootcacertpublisher/publisher.go) which 
automatically creates a kube-root-ca.crt configmap in every namespace. I couldn't find any documentation for this feature and 
while I am not familiar with the kubernetes source, it seems to use the same root-ca-file argument (from
cmd/kube-controller-manager/app/options/serviceaccountcontroller.go). 

This keeps me wondering about the purpose of the rootcacertpublisher because the ca certificate itself can be retrieved on several other ways.

From my understanding so far, the --root-ca-file should have a companion argument called --root-ca-bundle which is 
used by the service account controller to include in tokens and a third argument --ca-bundle which is used by the
rootcacertpublisher to provide arbitrary CA certificates.

**Comment by coboluxx** [comment]
Turns out this is a non issue. Problem was sitting right in front of the terminal. For everyone stumbling about the same thing: I forgot about the cluster-signing-cert-file. My setup had root-ca-file and cluster-signing-cert-file pointing to the same file. cluster-signing-cert-file must include the CA only.

**Comment by potulabe** [comment]
Thank you very much!!!

> Turns out this is a non issue. Problem was sitting right in front of the terminal. For everyone stumbling about the same thing: I forgot about the cluster-signing-cert-file. My setup had root-ca-file and cluster-signing-cert-file pointing to the same file. cluster-signing-cert-file must include the CA only.
