### ISSUE TITLE
kubelet --root-dir use nfs dir give error "could not find device with major: 0, minor: 38 in cached partitions map"

### ISSUE THREAD

**Issue by sunnoy** [kubernetes/kubernetes#98009]
**What happened**:
when kubelet --root-dir use nfs dir , it give error :
```bash
F0113 14:56:47.804328   14588 kubelet.go:1359] Failed to start ContainerManager failed to get rootfs info: failed to get device for dir "/mnt/xylink/kubelet_root": could not find device with major: 0, minor: 38 in cached partitions map
```

**What you expected to happen**:

kubelet runing

**How to reproduce it (as minimally and precisely as possible)**:

when kubelet --root-dir use nfs dir 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.1
- Cloud provider or hardware configuration:  
- OS (e.g: `cat /etc/os-release`):
CentOS Linux release 7.3.1611 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-514.el7.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
The error message is similar to #94335 and #95826.

**Comment by gjkim42** [comment]
The cadvisor can't get the filesystem info of nfs.
