### ISSUE TITLE
systemd Cgroup driver cause error:  applying cgroup configuration for process caused \"No such device or address\"

### ISSUE THREAD

**Issue by oldthreefeng** [kubernetes/kubernetes#98006]
env like
```
$ uname -a
4.19.90-17.ky10.aarch64 #1 SMP Sun Jun 28 14:27:40 CST 2020 aarch64 aarch64 aarch64 GNU/Linux

$ cat /etc/os-release
NAME="Kylin Linux Advanced Server"
VERSION="V10 (Tercel)"
ID="kylin"
VERSION_ID="V10"
PRETTY_NAME="Kylin Linux Advanced Server V10 (Tercel)"
ANSI_COLOR="0;31"

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:30Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:01:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/arm64"}

$ docker info | grep Cgroup
 Cgroup Driver: systemd
```

my coredns like 
```
$ kubectl get pod -n kube-system  |grep cor
coredns-f9fd979d6-bgggv                      1/1     CrashLoopBackOff 249        21h
coredns-f9fd979d6-dhdqd                      1/1     CrashLoopBackOff 250        21h
```

when descirbe coredns

```
$ kubectl describe pod -n kube-system coredns-f9fd979d6-bgggv
...
OCI message: "process_linux.go:264: applying cgroup configuration for process caused \"No such device or address\""
...
```

For solving the problem

step 1: 
delete  `"exec-opts": ["native.cgroupdriver=systemd"],` in `/etc/docker/daemon.json `
```
$ cat /etc/docker/daemon.json 
{
  "registry-mirrors": [
     "https://bxsfpjcb.mirror.aliyuncs.com"
  ],
  "max-concurrent-downloads": 10,
  "log-driver": "json-file",
  "log-level": "warn",
  "log-opts": {
    "max-size": "10m",
    "max-file": "3"
    },
  "insecure-registries":
        ["127.0.0.1"],
  "data-root":"/var/lib/docker"
}

```
step: 2 , reload docker

```
$ systemctl daemon-reload && systemctl restart docker 
```
xref: https://github.com/cri-o/cri-o/issues/832

so ,  there some bug still exist. why recommand systemd not Using cgroupfs??

**Comment by neolit123** [comment]
a partial explanation is here:
https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cgroup-drivers

if you are not running the kubelet via systemd you can use cgroupfs, but otherwise you should use the systemd driver so that you don't have 2 cgroup managers running at the same time.

> delete "exec-opts": ["native.cgroupdriver=systemd"], in /etc/docker/daemon.json

note that changing a cgroup driver on the fly is completely unsupported.
your pods may or may not run after that...

> OCI message: "process_linux.go:264: applying cgroup configuration for process caused \"No such device or address\"

systemd as the driver is working fine for most setups.
so this could be caused by something else.

/sig node

**Comment by oldthreefeng** [comment]
> note that changing a cgroup driver on the fly is completely unsupported.

Using systemed driver in docker and  Install kubernetes by `kubeadm init xxxx` . somehow cause the error 
```
"process_linux.go:264: applying cgroup configuration for process caused \"No such device or address\""
```

so change docker driver to cgroupfs works well.  

finally.  should I define some thing on Environmet like this ? @neolit123 
 
```
cat > /etc/systemd/system/kubelet.service.d/cgroup.conf << eof
[Service]
Environment="KUBELET_EXTRA_ARGS=--cgroup-driver=systemed"
eof
```

**Comment by neolit123** [comment]
I saw a recent report that the cgroupfs driver is leaking memory, so use at
your own risk.

Yes. You need to pass the systemd driver to the kubelet. You have a typo in
your example btw.

**Comment by mioyui88** [comment]
so how to resolve coredns failed when use systemd as cgroup drivers?
i use kubeadm-1.15.7 and kubelet also is 1.15.7

**Comment by oldthreefeng** [comment]
> so how to resolve coredns failed when use systemd as cgroup drivers?

any logs @mioyui88 ?

**Comment by mioyui88** [comment]
the same log like yours:

kubectl describe pod coredns-xxx -n kube-system
...
OCI message: "process_linux.go:264: applying cgroup configuration for process caused \"No such device or address\""
...

When i choose "cgroupfs" ,the coredns pod is OK

**Comment by mioyui88** [comment]
ps: my linux kernel is 4.19

**Comment by mioyui88** [comment]
> the same log like yours:
> 
> kubectl describe pod coredns-xxx -n kube-system
> ...
> OCI message: "process_linux.go:264: applying cgroup configuration for process caused "No such device or address""
> ...
> 
> When i choose "cgroupfs" ,the coredns pod is OK

Update runc version, it works!!
I  think 4.19 kernel use cgroup2, so the older runc can't work.

**Comment by oldthreefeng** [comment]
sloved by Update runc version

**Comment by neolit123** [comment]
well, runc is definitely part of the equation, but we currently don't document anything about it at k/website.
PRs for this page are welcome https://kubernetes.io/docs/setup/production-environment/container-runtimes/

**Comment by 123shang60** [comment]
If it is `Kylin Linux Advanced Server V10 (Tercel)` operating system, you can try to delete `/use/local/bin/runc` , and reinstall docker

**Comment by wuhuaniu707** [comment]
升级docker-runc到203-p01版本。方法参考：https://kylinos.cn/support/update/64.html

**Comment by Lao-Bee** [comment]
> 升级docker-runc到203-p01版本。方法参考：https://kylinos.cn/support/update/64.html

This method solved the problem.

``` shell
[root@6D147 ~]# cat /etc/os-release 
NAME="Kylin Linux Advanced Server"
VERSION="V10 (Tercel)"
ID="kylin"
VERSION_ID="V10"
PRETTY_NAME="Kylin Linux Advanced Server V10 (Tercel)"
ANSI_COLOR="0;31"

```
