### ISSUE TITLE
SignerName in CSR v1beta1 API is not defaulted when nil

### ISSUE THREAD

**Issue by shravan-achar** [kubernetes/kubernetes#98000]
**What happened**:

We are using client-go's certificate manager utility [code link](https://github.com/kubernetes/kubernetes/blob/release-1.18/staging/src/k8s.io/client-go/util/certificate/certificate_manager.go#L207) to configure and rotate certificates for a webhook server. The certificate config does not specify any signerName [code link](https://github.com/kubernetes/kubernetes/blob/release-1.18/staging/src/k8s.io/client-go/util/certificate/certificate_manager.go#L90). This uses v1beta1 version of `certificates.k8s.io` API

Then there is the defaulting [code](https://github.com/kubernetes/kubernetes/blob/release-1.18/pkg/apis/certificates/v1beta1/defaults.go#L46) for v1beta1 that sets various defaults including signerName. 
Until [this](https://github.com/kubernetes/kubernetes/pull/86476) code was merged, CSRs worked fine as expected. Even after it was merged, it should have worked with defaulting in place. [Documentation](https://v1-18.docs.kubernetes.io/docs/setup/release/notes/#urgent-upgrade-notes) mentions the field is optional. Curious to understand why the server defaults are not applied to the CSRs created through this utility.

**What you expected to happen**:

Expected the signerName to be defaulted to `kubernetes.io/legacy-unknown`. Instead got `CertificateSigningRequest.certificates.k8s.io "csr-abcde" is invalid: spec.signerName: Required value: signerName must be provided`

**How to reproduce it (as minimally and precisely as possible)**:

Create a certificate manager that uses client-go's certificate manager utility (kubernetes-1.18) to request certs from k8s. Make sure signerName is empty [here](https://github.com/kubernetes/kubernetes/blob/release-1.18/staging/src/k8s.io/client-go/util/certificate/certificate_manager.go#L90)

**Anything else we need to know?**:

CSR, with empty signerName, created with 1.18 Kubectl client on 1.19 API-Server does have this field defaulted to  `kubernetes.io/legacy.unknown`. Server-side defaults(?) are not applied only when using the utility mentioned above.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19 Server, 1.18 Client(Kubectl)
- Cloud provider or hardware configuration: AWS 
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by jqmichael** [comment]
@liggitt

**Comment by liggitt** [comment]
The short version is that absent != "". 

Using the client utility, you must specify a signerName. Sending an empty string (which is what that utility does in 1.18+ if you do not specify which signer you want) is not the same as omitting the field entirely (which is what earlier versions of client-go would do).

**Comment by jqmichael** [comment]
Ah I see. Thanks @liggitt 

Is it a convention in k8s API to enforce an "optional" field not to be empty? In other words, new "optional" field is **required** to set to a non-empty value in the client starting from the k8s version when it is introduced (in this case 1.18) ?

**Comment by liggitt** [comment]
> Is it a convention in k8s API to enforce an "optional" field not to be empty? In other words, new "optional" field is **required** to set to a non-empty value in the client starting from the k8s version when it is introduced (in this case 1.18) ?

Not in the API types directly, only in this utility helper method

**Comment by jqmichael** [comment]
Thanks @liggitt. 

I was reading the "optional vs required" section from [k8s API convention](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#optional-vs-required) 

> In most cases, optional fields should also have the omitempty struct tag (the omitempty option specifies that the field should be omitted from the json encoding if the field has an empty value). 

And I noticed `SignerName` from [`v1beta1` API ](https://github.com/kubernetes/kubernetes/blob/f9f5262cfb79cad5e6e8b121921cbb756f8430b7/staging/src/k8s.io/api/certificates/v1beta1/types.go#L67) contains the json `omitempty` tag. 
```
SignerName *string `json:"signerName,omitempty" protobuf:"bytes,7,opt,name=signerName"`
```

Any hints why an empty value wasn't treated as omitted field?

**Comment by liggitt** [comment]
the empty value for a pointer field is nil, not &""

**Comment by jqmichael** [comment]
> the empty value for a pointer field is nil, not &""

Aha. Didn't notice [that util library](https://github.com/kubernetes/kubernetes/blob/c2367bd5da68112ad3031dd33933859dacf8db58/staging/src/k8s.io/client-go/util/certificate/csr/csr.go#L59) did a string to pointer conversion. 
```
		Spec: certificates.CertificateSigningRequestSpec{
			Request:    csrData,
			Usages:     usages,
			SignerName: &signerName,
		},
```

A simple code snippet to reproduce:
```
type csr struct {
	SignerName *string `json:"signerName,omitempty" protobuf:"bytes,7,opt,name=signerName"`
}

func main() {
	signerName := ""
	csr_with_string := csr{
		SignerName: &signerName,
	}
	bytes, _ := json.Marshal(csr_with_string)
	fmt.Printf("csr_with_string:%s\n", string(bytes))

	var signerNamePtr *string
	csr_with_pointer := csr{
		SignerName: signerNamePtr,
	}
	bytes, _ = json.Marshal(csr_with_pointer)
	fmt.Printf("csr_with_pointer:%s\n", string(bytes))
}
```
```
csr_with_string:{"signerName":""}
csr_with_pointer:{}
```
https://play.golang.org/p/SDu7G28lLDM

Much appreciate all the insights @liggitt !
