### ISSUE TITLE
error: error upgrading connection: error dialing backend: dial tcp: lookup ms on 127.0.0.11:53: no such host

### ISSUE THREAD

**Issue by thomas1984** [kubernetes/kubernetes#98011]
I use three servers to deploy the kubernetes master, and now I publish pods on the three node machines. The following is the situation of pods that I query through kubectl.
![Screenshot from 2021-01-13 17-20-02](https://user-images.githubusercontent.com/6303182/104432243-c65e8900-55c3-11eb-98e1-8c6a0e1e5ca1.png)
But when you want to configure port forwarding, the following happens:
![Screenshot from 2021-01-13 17-23-43](https://user-images.githubusercontent.com/6303182/104432576-20f7e500-55c4-11eb-8c72-2e6450058221.png)
Each node uses the ubuntu 18.04 system, each machine has been configured with hosts, and the physical IP resolution through name is successful. Hope to get help。
kube-apiserver version is:v1.19.0

**Comment by neolit123** [comment]
please try the support forums:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
