### ISSUE TITLE
GracefulNodeShutdown No mechanism to remove pods in the shutdown state

### ISSUE THREAD

**Issue by wzshiming** [kubernetes/kubernetes#98012]
**What happened**:

![image](https://user-images.githubusercontent.com/6565744/104433778-71bc0d80-55c5-11eb-8c6b-39c17f967412.png)

**What you expected to happen**:

like drain.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.20.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 7
- Kernel (e.g. `uname -a`):  Linux zsm-test-2 3.10.0-1160.11.1.el7.x86_64 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by bobbypage** [comment]
This is expected, when node is shutdown kubelet will mark the pods as "Shutdown" and in v1.PodFailed phase:

https://github.com/kubernetes/kubernetes/blob/ac0b0378df23b6a68452b8577fd6fed265306615/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go#L222-L225

This is same behavior as during pod eviction. The pods will stick around in that FailedPhase until either they are deleted manually or the kube-controller-manager pod garbage collector will run when terminated pods reaches `--terminated-pod-gc-threshold` (default: 12500).
