### ISSUE TITLE
EndpointSliceMirroring controller does not mirror annotations from endpoints

### ISSUE THREAD

**Issue by sgreene570** [kubernetes/kubernetes#98026]
**What happened**:
The [endpointslice mirroring controller](https://github.com/kubernetes/kubernetes/tree/master/pkg/controller/endpointslicemirroring) does not copy over annotations from endpoints resources to endpointslice resources (although it does [mirror endpoint labels](https://github.com/kubernetes/kubernetes/pull/93442)). Additionally, annotations applied by hand to endpointslices owned by the endpointslice mirroring controller are overwritten by the mirroring controller when the corresponding endpoint is modified. Essentially applying persistent custom annotations to endpointslices resources mirrored from endpoints is not possible to my understanding.

**Anything else we need to know?**:
It is unclear to me whether or not this functionality is intentional. Since labels are mirrored, I don't see any harm in annotations being mirrored as well (or at least having the endpointslice mirroring controller permit custom annotations on it's owned endpointslice resources, rather than remove them when syncing endpoints). Note that as is, the [endpointslices KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/0752-endpointslices#mirroring-details) does not mention annotations when describing the responsibility of the endpointslice mirroring controller.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20

**Comment by aojea** [comment]
just curious, is there any special use case to mirror annotations from endpoints to endpoint slices?

/assign @robscott

**Comment by robscott** [comment]
I don't see any harm in doing this, had not thought of annotations being used this way. They were not intentionally being left out or overwritten.

**Comment by robscott** [comment]
I'm pretty overrun right now but may have time to take this on if no one else can. I do think this is a good opportunity for new k8s contributors to jump in though, so if anyone's interested, let me know.

/good-first-issue

**Comment by sgreene570** [comment]
> just curious, is there any special use case to mirror annotations from endpoints to endpoint slices?

In OpenShift, `oc idle` annotates endpoints so the ingress controller knows it shouldn't serve them. Would be nice to be able to check for this annotation on endpointslices directly. @aojea

**Comment by robscott** [comment]
Was looking into what would be involved and may not be a good first issue after all. It's very straightforward to ensure that new EndpointSlices have appropriate annotations, it's less straightforward to ensure that updates to annotations are mirrored across.

/remove-good-first-issue

**Comment by aojea** [comment]
> In OpenShift, `oc idle` annotates endpoints so the ingress controller knows it shouldn't serve them. Would be nice to be able to check for this annotation on endpointslices directly. @aojea 

`endpoints` will not be dual stack, for for dual-stack services, annotations will only work for one of the IP Families, however, there will be endpoint slices for IPv4 and IPv6.
 I think we have to modify `oc idle` to annotate endpoint slices directly, if we want to support dual stack.

**Comment by frobware** [comment]
> I think we have to modify `oc idle` to annotate endpoint slices directly, if we want to support dual stack.

I think this is fine as long as the mirroring service doesn't remove any annotations. I actually implemented the change (i.e., oc idle) this way to begin with but got caught out when the annotation was subsequently removed.

**Comment by aojea** [comment]
@frobware I'm not familiar with `oc idle`, so forgive me if this is wrong.
What I try to mean is, if you have a dual stack service:

```
spec:
  clusterIP: 10.104.110.128
  clusterIPs:
  - 10.104.110.128
  - fd00:10:96::1364
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: RequireDualStack
  ports:
```

it has only Endpoints in one family:

```
$ kubectl get endpoints test -o wide                                                                                                                                                        
NAME   ENDPOINTS       AGE
test   10.244.0.5:80   5m42s
```

but one endpoint slice has the notion of IP family:
```
$ kubectl get endpointslices  -o wide
NAME         ADDRESSTYPE   PORTS     ENDPOINTS    AGE
kubernetes   IPv4          6443      172.19.0.5   8m47s
test-m57qg   IPv4          80        10.244.0.5   7m22s
test-tjfc8   IPv6          80       fd00:1:2:3::5      6m53s
```

what I don't know is how the mirroring will deal with the IPFamilies of the endpoints

**Comment by aojea** [comment]
/assign
/remove help-wanted
/remove good-first-issue

https://github.com/kubernetes/kubernetes/issues/98026#issuecomment-760213790

I think we have a bug with dual-stack endpoints

```
$ kubectl get endpointslices
NAME         ADDRESSTYPE   PORTS   ENDPOINTS    AGE
kubernetes   IPv4          6443    172.19.0.3   28h
$ kubectl get endpoints
NAME         ENDPOINTS                            AGE
kubernetes   172.19.0.3:6443                      28h
test-dual    172.19.0.3:6443,[fd00:1:2::3]:6443   3m59s
$ kubectl -n kube-system logs kube-controller-manager-ovn-control-plane | grep mirroring
I0116 17:58:00.323404       1 endpointslicemirroring_controller.go:273] syncEndpoints("default/test-dual")
I0116 17:58:00.323435       1 endpointslicemirroring_controller.go:299] default/test-dual Service not found, cleaning up any mirrored EndpointSlices
I0116 17:58:00.323454       1 endpointslicemirroring_controller.go:270] Finished syncing EndpointSlices for "default/test-dual" Endpoints. (61.568µs)
I0116 18:01:51.319713       1 endpointslicemirroring_controller.go:273] syncEndpoints("default/test")
```

**Comment by robscott** [comment]
@aojea That's an interesting use case. Are endpoints used without a corresponding service?

**Comment by aojea** [comment]
> @aojea That's an interesting use case. Are endpoints used without a corresponding service?

don't know honestly, just did it this way for testing
