### ISSUE TITLE
Getting empty resource list with RemoveSelfLink=true causes API to return items: null

### ISSUE THREAD

**Issue by gryf** [kubernetes/kubernetes#98022]
**What happened**:

On Kubernetes 1.18 and 1.19, with passed `--feature-gates=RemoveSelfLink=true` parameter, result for query the API for a list of non-existent resources gives null as an items value:

```
$ curl http://localhost:8080/api/v1/pods
{
  "kind": "PodList",
  "apiVersion": "v1",
  "metadata": {
    "resourceVersion": "266"
  },
  "items": null
}
```

**What you expected to happen**:

It should return `"items": []` like:

```
$ curl http://localhost:8080/api/v1/pods
{
  "kind": "PodList",
  "apiVersion": "v1",
  "metadata": {
    "resourceVersion": "266"
  },
  "items": []
}
```

similar to version 1.20. 
Documentation says, that for PodList type, `items` must be an array[1], which API convention[2] specify that ”Any kind that has the "items" field must be a list kind.” There is no `null` mentioned as a possible value.

**How to reproduce it (as minimally and precisely as possible)**:

The only difference is the  `--feature-gates=RemoveSelfLink=true` parameter - without it everything works as expected.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.6, 1.18.0
- Cloud provider or hardware configuration: n/a
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04 LTS
- Kernel (e.g. `uname -a`): 4.15.0-88
- Install tools: manual
- Network plugin and version (if this is a network-related bug): n/a
- Others: n/a

[1] https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#podlist-v1-core
[2] https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#types-kinds

**Comment by knight42** [comment]
This should be fixed by https://github.com/kubernetes/kubernetes/pull/94397/files#diff-4519926a750520e1d319f4931197f61b4b9c277740f46e8f4b514bec746e2647 in v1.20.

**Comment by gryf** [comment]
Right, but 1.18 and 1.19 are broken.

**Comment by knight42** [comment]
@wojtek-t Is it okay to backport #94397 to 1.18 and 1.19?

**Comment by wojtek-t** [comment]
Thanks for reporting this bug!

We can't backport the whole #94397 - we should just backport that part that is fixing that issue.

Let me take care of it.

**Comment by wojtek-t** [comment]
FTR - I'm already looking into it - I just wanted to ensure that it's also tested...

**Comment by gryf** [comment]
Thanks!

**Comment by wojtek-t** [comment]
FTR - see this discussion: https://github.com/kubernetes/kubernetes/pull/98064#discussion_r557448075 - it's highly possible that it will not get backported.
