### ISSUE TITLE
Pods on Master cant use InternalIP ExternalIP Hostname and configs.

### ISSUE THREAD

**Issue by Trackhe** [kubernetes/kubernetes#98038]
**What happened**:

I setup an Kubernetes Cluster with these [Guide](https://github.com/Trackhe/Raspberry64bitKubernetesServerDualstack).

After i Setup Calico v3.14 Metrics v.0.4.1  and the Dashboard v2.1.0 on 5 Ubuntu arm64 / 64bit RPis. 

my hostnames are
raspnode00
raspnode01
and so on.

The Metrics Pod say in log 
```
E0113 23:05:53.556639       1 server.go:132] unable to fully scrape metrics: unable to fully scrape metrics from node raspnode00: unable to fetch metrics from node raspnode00: unable to extract connection information for node "raspnode00": node raspnode00 had no addresses that matched types [InternalIP ExternalIP Hostname] 
```
And Calico Pod on Master (raspnode00)
```
no preferred addresses found; known addresses: []
```
After Installing Mettallb they Pod (Speaker) says that too:
```
no preferred addresses found; known addresses: []
```
**What you expected to happen**:
Working as the pods on the slaves. and working Like the v1.19 on that version it was working Fine. now Kubernetes v1.20.1 is it not working now.

**How to reproduce it (as minimally and precisely as possible)**:
Follow the [Guide](https://github.com/Trackhe/Raspberry64bitKubernetesServerDualstack) exactly on a Ubuntu 64bit Server on Raspberrypi 4 4gb.
[Guide](https://github.com/Trackhe/Raspberry64bitKubernetesServerDualstack)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version 1.20.1
- Cloud provider or hardware configuration:
- NAME="Ubuntu"
- VERSION="20.10 (Groovy Gorilla)"
- ID=ubuntu
- ID_LIKE=debian
- Kernel  Linux raspnode00 5.8.0-1011-raspi #14-Ubuntu SMP PREEMPT Tue Dec 15 08:53:29 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
- Install tools: Dashboard v2.1.0
- Network plugin and version Calico v3.14

**Comment by neolit123** [comment]
/kind support

this should work, but you should try contacting the authors of the https://github.com/Trackhe/Raspberry64bitKubernetesServerDualstack guide since it's not a k8s official one.

if they confirm that this is core k8s bug please re-open this ticket.

thanks
/close

**Comment by Trackhe** [comment]
@neolit123 this is confirmed. i create it more then 3 times everytime again. and this is my guide. 
I wrote it down and tried it out according to the official instructions.
since kubernetes 1.20.1 this no longer works.

**Comment by neolit123** [comment]
> since kubernetes 1.20.1 this no longer works.

did it work in 1.20.0?

**Comment by neolit123** [comment]
i recall some related changes in 1.20 related to IPs but don't recall all the details there.

/reopen
/sig network

leaving the SIG network team to triage.

**Comment by Trackhe** [comment]
I try it in 1.20.0 and give feedback.

**Comment by Trackhe** [comment]
the answer is no its not working with 1.20.0

**Comment by Trackhe** [comment]
my kubeadm init file was wrong i set a old ip. ... i m srry for this. my bad. thank you for your time.

/close
