### ISSUE TITLE
Docker images which work with *docker run* *docker-compose* won't work with kubernetes

### ISSUE THREAD

**Issue by MrAmbiG** [kubernetes/kubernetes#98048]
**What happened**:
https://github.com/MrAmbiG/shorty/tree/k8s
There were no k8s native url shorteners which were active so I wrote one. The code, dockerized image all work with
`docker run --name shorty -it --env-file .env -p 80:8000 gajuambi/shorty` works    
`doker-compose up` works
Same image when used with k8s/helm, you can never access it from outside. SSH to the pod and curl localhost works just fine, so the app server itself runs fine inside. LoadBalancer service is also created mapping to the correct port.

**What you expected to happen**:
Access the service from k8s.

**How to reproduce it (as minimally and precisely as possible)**:
- Get into the directory shorty/Deployment/k8s/helm
- Replace the values to be set from the following helm command `helm install shorty shorty --set "SHORTY_PG_DB=dbname,SHORTY_PG_USERNAME=dbuser,SHORTY_PG_PASSWORD=dbpassword,SHORTY_PG_HOST=dbhost,SHORTY_PG_PORT=5432,DJANGO_SECRET_KEY=djangosecretkey"`
**Anything else we need to know?**:
I did see many such instances where an image works with docker run and docker compose but not with k8s/helm.  Ex: https://github.com/shlinkio/shlink. They are not even bothering to even attempt to create k8s manifest file. I tried and it didnt work.
https://github.com/ajanvier/docker-polr    
https://github.com/ajanvier/docker-polr    
polr is another url shortener and you have a lot of docker compose files and docker images but nothing for k8s. 
**Environment**: 
- Kubernetes version (use `kubectl version`): 1.18
- Cloud provider or hardware configuration: on prem k8s + metal lb
- OS (e.g: `cat /etc/os-release`): ubuntu 18.04
- Kernel (e.g. `uname -a`): Linux build-hq-36 4.4.0-193-generic #224-Ubuntu SMP Tue Oct 6 17:15:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: RKE
- Network plugin and version (if this is a network-related bug): canal
- Others:
Sidenote: If dockerizing an app is a guarantee that it works with k8s too when it works with docker run and docker compose then should there be a guideline for k8s compatible dockerization/containerization?
my dockerfile
```
FROM python:3.6-buster
RUN mkdir shorty
COPY shorty shorty
COPY requirements.txt /
COPY run.sh /
EXPOSE 8000
RUN pip install -r requirements.txt
ENTRYPOINT ["/bin/bash", "/run.sh"]

```
run.sh file

```
#!/bin/bash
cd shorty
python manage.py collectstatic --noinput
python manage.py makemigrations
python manage.py migrate
daphne shorty.asgi:application -b 0 -p 8000
```
More info is in the repo [here](https://github.com/MrAmbiG/shorty/tree/k8s)

/sig architecture

**Comment by neolit123** [comment]
do you have related error logs from the kubelet?
`journalctl -xeu kubelet`

/sig node

**Comment by MrAmbiG** [comment]
> do you have related error logs from the kubelet?
> `journalctl -xeu kubelet`
> 
> /sig node

The most baffling thing is there are no errors, images gets pulled successfully, if I check the pod logs itself it is exactly the same as
docker run
docker-compose
running the app inside a VM.
If I ssh into the pod and do a curl localhost I do see that my django app is running well but we cannot access it from outside though... The loadbalancer IP is assigned and service is created.

**Comment by MrAmbiG** [comment]
I was able to take care of this by changing the image and disabling probes of helm.
