### ISSUE TITLE
Build easy to use CSI tools to detect and resolve k8s storage issues and tools to run speed/stress test against k8s storage/CSI driver

### ISSUE THREAD

**Issue by SandeepPissay** [kubernetes/kubernetes#98076]
**What would you like to be added**:

Kubernetes community has built ks8 storage features, CSI, sidecars, etc. to manage the lifecycle of storage volumes. Many cloud and storage vendors leverage this to build CSI drivers that work for their cloud and/or storage solutions. The k8s storage components and cloud software are complex and when the entire stack is put to use by the end user, they will face few operational issues in the long run. Sometimes the issues are complex to resolve and we need some tools to help identify issues and also resolve them to keep the system running.

There are also cloud vendors and customers/end users who perform a thorough evaluation of the product to see if it fits the storage SLA for their workloads. We do not have easy to use tools in the community that focuses on tools for such personas to perform such activities. Note: there are E2E tests for stress tests but they are more focused on the developers.

The aim of filing this enhance request is to solve the above described problems by building easy to use tools in the community that is appealing to the end users, CSI driver developers, etc. It should also offer extensions for cloud/storage providers wherever needed.

Here are few use cases -
**Orphan volume detection and removal:**
In a few corner cases, the CSI driver ends up creating more than one volume in the cloud infra for a PVC. The volumes that are not used in the cloud infra are left unused and the end user or cloud SRE wouldn't even know that there are orphan volumes occupying space on the infra. We need tools that can tell us where we have such stale orphan volumes and whether it is safe to clean them up.

**Orphan Volume Attachment detection and removal**
In this case we have VolumeAttachment CRs that are referencing a non existent PV. It’s not clear how the end user ends up with this state. It will be useful to clear such VolumeAttachments when it’s safe. We need tools that can tell us whether we have such stale VolumeAttachment objects and whether it is safe to clean them up.

**Speed/stress test k8s storage/CSI driver**
- The end user wants an easy to use tool to evaluate the performance of storage control operations(create, delete, attach, detach, etc) in Kubernetes.
- The end user wants to stress the system to know how much load the system can take.
- CSI driver development team wants to evaluate the performance of their driver.
- CSI driver development team wants to evaluate how their solution behaves under stress.

**Proposal**
Build open source tools to support the above use cases. The tool should provide extensions(wherever needed) for the cloud/storage providers. This is useful for broader adoption of the tool.

**Comment by xing-yang** [comment]
CC @saad-ali @msau42 @jsafrane @gnufied
