### ISSUE TITLE
Quotas not displayed and not updated anymore

### ISSUE THREAD

**Issue by ledroide** [kubernetes/kubernetes#98071]
#### What happened:

* quotas were working well during months with the same configuration
* the same issue happens on multiple namespaces
* existing quotas are displayed, but changes in settings and usage are ignored, current usage looks frozen

##### quota status and settings are not displayed anymore

```
$ cat quotas.yaml
```
```yaml
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: webs-compute-resources
spec:
  hard:
    pods: "18"
    limits.cpu: "26"
    limits.memory: "52Gi"
```
```
$ kubectl apply -f quotas.yaml
resourcequota/webs-compute-resources configured
```
```
$ kubectl describe quota webs-compute-resources
Name:       webs-compute-resources
Namespace:  webs
Resource    Used  Hard
--------    ----  ----
$
```
```
$ kubectl get quota webs-compute-resources -n webs -o yaml
(...)
spec:
  hard:
    pods: "18"
    limits.cpu: "26"
    limits.memory: "52Gi"
status: {}
```
```
$ kubectl describe namespace webs
Name:         webs
Labels:       team=webs
              webs.tree.hnc.x-k8s.io/depth=0
Annotations:  <none>
Status:       Active

Resource Quotas
 Name:     webs-compute-resources
 Resource  Used  Hard
 --------  ---   ---

Resource Limits
 Type       Resource  Min   Max   Default Request  Default Limit  Max Limit/Request Ratio
 ----       --------  ---   ---   ---------------  -------------  -----------------------
 Container  cpu       50m   2     150m             500m           -
 Container  memory    16Mi  18Gi  32Mi             64Mi           -
```

##### events claim limits.memory=62Gi (an old setting)

```
kubectl get event -n webs -w
61m         Warning   FailedCreate             replicaset/workspace-7cc88789c5                      Error creating: pods "workspace-7cc88789c5-fmcxm" is forbidden: exceeded quota: compute-resources, requested: limits.memory=10Gi, used: limits.memory=60544Mi, limited: limits.memory=62Gi
```

#### What I have tried

* delete quota resource with `kubectl delete quota --all` and recreate -> no effect
* delete namespace, recreate namespace, apply quota -> no effect
* change values for specs.hard -> no effect
* check metrics-server behavior (kubectl top pods, kubectl top nodes) -> works as expected
* check metrics-server logs -> nothing relevant
* restart kubelets -> no effect
* restart kube-controller-manager in kube-system namespace, delete quotas, apply quotas -> no effect
* reboot all nodes including masters -> no effect

#### System Info

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:01:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
$
$ kubelet --version
Kubernetes v1.19.6
$
$ kubectl api-resources | grep resourcequotas
NAME               SHORTNAMES    APIVERSION      NAMESPACED      KIND
resourcequotas         quota        v1             true         ResourceQuota
```

Other info :
* On premise CentOS 7 & CentOS 8 and servers
* Install tools: kubespray
* Network plugin: calico 3.16.5

**Comment by ledroide** [comment]
/sig api-machinery
?

**Comment by ledroide** [comment]
/wg component-standard
?

**Comment by pacoxu** [comment]
/assign 

@ledroide  Could you give an example yaml of `workspace` deployment ?
I may look into it this weekend.

**Comment by ledroide** [comment]
> Do you mean that you failed to update quota like `kubectl edit quota webs-compute-resources`?

Hello @pacoxu, thanks for your answer.
I can edit the values and add lines to my quota. The value is what I have configured locally and applied.
If I edit again, I can see it is "commited".

I can edit, change `limits.memory: 52Gi` to `limits.memory: 58Gi`, and add `secrets: "24"`.
If I edit again, I can see `limits.memory: 58Gi`, and `secrets: "24"`, as expected.

```yaml
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
apiVersion: v1
kind: ResourceQuota
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ResourceQuota","metadata":{"annotations":{},"name":"webs-compute-resources","namespace":"webs"},"spec":{"hard":{"limits.memory":"52Gi"}}}
  creationTimestamp: "2021-01-14T16:35:54Z"
  name: webs-compute-resources
  namespace: webs
  resourceVersion: "83088102"
  selfLink: /api/v1/namespaces/webs/resourcequotas/webs-compute-resources
  uid: 307e35b2-b4f5-4c8e-aff8-eef0431d9727
spec:
  hard:
    limits.memory: 58Gi
    secrets: "24"
status: {}
```

The issue is about what the system sees and reports about quotas and current usage of resources :
* events still think the memory limits are set to old values
* I can create 50 new secrets, whereas my new configuration limits secrets to 24, all 50 secrets are accepted, none is shown in the quotas status.
* when I ask the API to describe the namespace or resourcequota/webs-compute-resources, the API tells me wrong (empty) information  
```
$ kubectl describe resourcequota/webs-compute-resources 
Name:       webs-compute-resources
Namespace:  webs
Resource    Used  Hard
--------    ----  ----
$
$ kubectl get quotas -o wide
NAME                     AGE   REQUEST   LIMIT
webs-compute-resources   1h             
```

> Could you give an example YAML of `workspace` deployment?
> I may look into it this weekend.

For sure the issue is not the deployment itself. 
Please find the manifest at [this gist URL](https://gist.github.com/ledroide/849e6dfd2d41072b5db8f374523abcb2) if you want to have a look.

But he issue is clearly that the quota resources : 
* are recorded correctly and can be edited 
* are not performed by the controller despite this
* seem to remember old settings and old statuses that does not exist anymore, just like there is no updates about running resources and no updates in settings.

**Comment by pacoxu** [comment]
I cannot easily reproduce the problem.

Quota Status update logic is in 
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/resourcequota/resource_quota_controller.go

Would you check logs in controller-manager? 

BTW, there are two param for kube-controller-manager
```
--concurrent-resource-quota-syncs int32     Default: 5
  | The number of resource quotas that are allowed to sync concurrently. Larger number = more responsive quota management, but more CPU (and network) load
--resource-quota-sync-period duration     Default: 5m0s
The period for syncing quota usage status in the system

```

**Comment by ledroide** [comment]
Hello @pacoxu 
I have discovered other issues that appeared with no reason on the same cluster. All of them may be linked to the kube-controller-manager, but I don't know how to solve it.
* when deleting deployments, daemonsets, statefulsets ; replicaSets under their control are not deleted as expected.
* when deleting manually replicaSets, many controlled pods are still running (whatever is their state, ready or not) - that means pods are still running without any replicaSet
* namespaces are not properly deleted : they "remember" some old resources when re-created
* some resources (like role bindings), when applied and created (or modified), are taken into account actually

I can't see anything unusual about kube-controller-manager pods, or logs, in kube-system.
I tried to reboot etcd nodes (they are running on master nodes) -> no effect.
Also upgraded to Kubernetes v1.19.7 -> no effect.

**Comment by pacoxu** [comment]
```

E0119 11:37:53.532226       1 shared_informer.go:243] unable to sync caches for garbage collector
E0119 11:37:53.532261       1 garbagecollector.go:228] timed out waiting for dependency graph builder sync during GC sync (attempt 73)

I0119 11:37:54.680276       1 request.go:645] Throttling request took 1.047002085s, request: GET:https://10.150.233.43:6443/apis/configuration.konghq.com/v1beta1?timeout=32s
I0119 11:37:54.831942       1 shared_informer.go:240] Waiting for caches to sync for garbage collector
I0119 11:38:04.722878       1 request.go:645] Throttling request took 1.860914441s, request: GET:https://10.150.233.43:6443/apis/acme.cert-manager.io/v1alpha2?timeout=32s
E0119 11:38:04.861576       1 shared_informer.go:243] unable to sync caches for resource quota
E0119 11:38:04.861687       1 resource_quota_controller.go:447] timed out waiting for quota monitor sync

```
According to your logs from slack, the error shows that resource_quota_controller stuck here.

https://github.com/kubernetes/kubernetes/blob/19b15b2fc2a1c3d5d334a64026c9bd2c0335cbac/pkg/controller/garbagecollector/garbagecollector.go#L242

https://github.com/kubernetes/kubernetes/blob/f2ed1b55803177c9b02b0acf134a011a5fb20544/pkg/controller/resourcequota/resource_quota_controller.go#L448


Per comments from https://github.com/kubernetes/kubernetes/issues/94293#issuecomment-687816166, 

> maybe you could check Pod.OwnerRefernece and Finalizer settings.

>I think it was too many resources that caused a timeout.

**Comment by ledroide** [comment]
SOLVED.
Thanks to @pacoxu who investigated my logs from kube-controller-manager, we have found this : 
```
I0121 11:15:54.467098       1 shared_informer.go:240] Waiting for caches to sync for garbage collector
I0121 11:16:39.867524       1 graph_builder.go:272] garbage controller monitor not yet synced: hnc.x-k8s.io/v1alpha2, Resource=hierarchyconfigurations
```
The root cause comes from the HNC (Hierarchical Namespace Controller).

After removing HNC and manually its resources remaining in validatingwebhookconfigurations, customresourcedefinitions and subnamespaceanchors ; and restarting kube-controller-manager with option `--concurrent-gc-syncs=60` (not sure I is necessary, actually), quotas and other resources comes back to expected behavior.

**Comment by pacoxu** [comment]
After some investigation,  HNC's webhook will block when HNC controller has some problems. 
My namespace cannot be created or deleted after the webhook was created.

The cluster resumed after I delete the HNC controller webhook.

**Comment by marwatk** [comment]
Because this is the top google result for quotas misbehaving, we wanted to add our issue and resolution here as well (Openshift 4.9, k8s 1.22.15).

Our quotas stopped releasing when resources were freed but were usage would still increase for new workloads resulting in namespaces unable to provision new resources (specifically we hit the memory limit). Additionally, resource deletion was not cascading (e.g. deleting a Deployment wouldn't delete the associated pods).

In our case the only hint we had was the `kube-controller-manager` log spitting out messages like this:

```
garbagecollector.go:242] timed out waiting for dependency graph builder sync during GC sync (attempt 1821)
```

It wasn't until we bumped the logs on that to debug that we saw:

```
I0118 19:26:42.656087       1 graph_builder.go:279] garbage controller monitor not yet synced: serving.kubeflow.org/v1beta1, Resource=inferenceservices
I0118 19:26:42.678120       1 resource_quota_monitor.go:294] quota monitor not synced: serving.kubeflow.org/v1beta1, Resource=inferenceservices
```

Which led us to discover that we had a broken CRD:

```
$ kubectl get inferenceservices --all-namespaces
Error from server (InternalError): Internal error occurred: error resolving resource
```

Deleting that CRD fixed the garbage collector and the cluster returned to normal operation.

Hope this helps someone in the future.
