### ISSUE TITLE
Exercise hostPort test in scheduler e2e for both Windows and Linux nodes

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#98075]
**Which jobs are failing**:
We want to change ownership of a test from scheduler to network
**Which test(s) are failing**:
[sig-scheduling] SchedulerPredicates [Serial] validates that there is no conflict between pods with same hostPort but different hostIP and protocol [Conformance]

**Since when has it been failing**:

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-windows-releases#aks-engine-azure-windows-master-staging-serial-slow
**Reason for failure**:
Once #97003 merges, we will exclude hostPort test on Windows. This is because of how the hostPort test is structured where we are relying on hostNetwork pod to test the communication between hostPort pods. This will not work on Windows as hostNetwork is not supported.

I think it is better to have this test in sig-network and test the communication as scheduler should be responsible only for assigning a pod to node. This also ensures that hostPort on Windows is exercised properly. 

**Anything else we need to know**:
More context [here](https://github.com/kubernetes/kubernetes/pull/96627#issuecomment-736978866)

**Comment by ravisantoshgudimetla** [comment]
/sig scheduling
/sig network

cc @spiffxp @jayunit100 @jsturtevant @marosset

**Comment by spiffxp** [comment]
/area conformance
/area test
/sig windows
since windows
