### ISSUE TITLE
Conformance image v1.18.0  still fails on arm64

### ISSUE THREAD

**Issue by Jerry-Ge** [kubernetes/kubernetes#98086]
**What happened**:
Per this PR #97982 which fixed #89554, I have tried run 
```bash
docker run --rm -it --entrypoint bash gcr.io/google-containers/conformance:v1.18.0 -c "echo ok"
```
I still got this error message: 
```bash
standard_init_linux.go:211: exec user process caused "exec format error"
```

I can see the manifest file from gcr.io/google-containers/conformance:v1.18.0 which has the arm64 digest and I tried to run with digest:
```bash
docker run --rm -it --entrypoint bash gcr.io/google-containers/conformance@sha256:53fbfa42f02ea9ea086ecfb0a436ec52b8584047c65244fe7ee18f76f39645fa -c "echo ok"
```

And I still got the same error as above:
```bash
Status: Downloaded newer image for gcr.io/google-containers/conformance@sha256:53fbfa42f02ea9ea086ecfb0a436ec52b8584047c65244fe7ee18f76f39645fa
standard_init_linux.go:211: exec user process caused "exec format error"
```

**What you expected to happen**:
The conformance test on arm64 should be launched. 

**How to reproduce it (as minimally and precisely as possible)**:
```bash
docker run --rm -it --entrypoint bash gcr.io/google-containers/conformance@sha256:53fbfa42f02ea9ea086ecfb0a436ec52b8584047c65244fe7ee18f76f39645fa -c "echo ok"
```

**Anything else we need to know?**:
I am pretty new to the k8s community and I am trying to figure out which lines of code trigger this [Makefile](https://github.com/kubernetes/kubernetes/blob/master/cluster/images/conformance/Makefile)

**Environment**:
- Kubernetes version (use `kubectl version`):
```bash
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/arm64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```bash
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
```
- Kernel (e.g. `uname -a`):
```bash
Linux entos-softiron-01 5.6.0-050600-generic #202003292333 SMP Sun Mar 29 23:49:51 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by BenTheElder** [comment]
note that the fix will apply to *new* images, our images are *not* mutable.

if you need this in 1.18.x, it needs to be cherry-picked back and then it will be in the next release.

**Comment by Jerry-Ge** [comment]
Thanks @BenTheElder. I will close this issue.

**Comment by Jerry-Ge** [comment]
@BenTheElder 

Could you answer this question if necessary?

####  Anything else we need to know?:
"I am pretty new to the k8s community and I am trying to figure out which lines of code trigger this [Makefile](https://github.com/kubernetes/kubernetes/blob/master/cluster/images/conformance/Makefile)"

**Comment by BenTheElder** [comment]
> "I am pretty new to the k8s community and I am trying to figure out which lines of code trigger this Makefile"

If you mean to build one yourself, the docs for how to do that are in the adjacent README.
If you're asking for how this happens in the release process, it's overly complicated 🙃 

https://github.com/kubernetes/kubernetes/blob/d5a75dc7e8d1ff4cea27502da8ae4dc7f47f69af/build/lib/release.sh#L410 is a hint for the latter. which happens when `make release KUBE_BUILD_CONFORMANCE=y` (or the much cheaper but single-platform `make quick-release KUBE_BUILD_CONFORMANCE=y`).

Hope that helps!

**Comment by Jerry-Ge** [comment]
Definitely! Thanks, Ben and I will investigate. 

Jerry

**Comment by Jerry-Ge** [comment]
Sorry Ben I got another question raised in my mind 😅: I did a quick skim in the "release.sh" and am curious about where we created & pushed the manifest file to make this conformance image to be Multi-Arch in the full release process? I guess maybe somewhere in `kubernetes/release/*` ? 

Thanks so much in advance, 

Jerry

**Comment by BenTheElder** [comment]
the image build method used in release here
https://github.com/kubernetes/kubernetes/blob/d5a75dc7e8d1ff4cea27502da8ae4dc7f47f69af/build/lib/release.sh#L306-L313

specifically this part builds the images:
https://github.com/kubernetes/kubernetes/blob/d5a75dc7e8d1ff4cea27502da8ae4dc7f47f69af/build/lib/release.sh#L313

it does not appear to me that we do build a multi-arch image, rather multiple images, one for each arch.

us.gcr.io/k8s-artifacts-prod does show multi-arch manifests though 😕 

I think the above PR _may_ have fixed building for these other platforms, but I don't think multi-arch has been done correctly. IMHO the correct change is to use buildx, like we do for the core images.

**Comment by BenTheElder** [comment]
in the PR you can see here that the x86 image gets tagged with the conformance image (no arch) tag https://github.com/kubernetes/kubernetes/pull/97982/files#diff-eccea3a18c013ee3078173f18a067bdbe6cbdd13e45427e5b671184bd81867b4L66

the registry appears to have manifest lists though, which I can't explain

**Comment by BenTheElder** [comment]
also: you should not be using gcr.io/google-containers/, the correct host for all official images is `k8s.gcr.io/` so `k8s.gcr.io/conformance:v1.18.0`

**Comment by Jerry-Ge** [comment]
Thanks for all of those comments! Pretty valuable info and I will continue the investigation to see are there any multi-arch improvements I can contribute 🙂
