### ISSUE TITLE
[Flaking Test][sig-windows] /home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/dynamic_provisioning_test.go

### ISSUE THREAD

**Issue by wawa0210** [kubernetes/kubernetes#98084]
**Which jobs are flaking**:
pull-kubernetes-e2e-azure-disk-windows

**Which test(s) are flaking**:

**Testgrid link**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/97141/pull-kubernetes-e2e-azure-disk-windows/1349895908019408896

**Reason for failure**:

**Anything else we need to know**:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

**Comment by ehashman** [comment]
AzureDisk  CSI Driver End-to-End Tests: Dynamic Provisioning [single-az] should  create a statefulset object, write and read to it, delete the pod and  write and read to it again [kubernetes.io/azure-disk]  [disk.csi.azure.com] [Windows] expand_less | 2m36s
-- | --
```/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/dynamic_provisioning_test.go:684 Unexpected error:     <*errors.errorString \| 0xc00033b130>: {         s: "Failed to find \"hello world\r\nhello world\r\n\", last result: \"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00hello world\r\n\"",     }     Failed to find "hello world     hello world     ", last result: "�������������hello world     " occurred /home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/testsuites/testsuites.go:639```


https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/96531/pull-kubernetes-e2e-azure-disk-windows/1354162112401772544

**Comment by fromanirh** [comment]
It seems I'm hitting this flake from my PR95734. PR history: https://prow.k8s.io/pr-history/?org=kubernetes&repo=kubernetes&pr=95734

**Comment by fromanirh** [comment]
Link to test failure logs: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/95734/pull-kubernetes-e2e-azure-disk-windows/1368902141430730752
