### ISSUE TITLE
Cannot install Kubernetes on Bare-metal Ubuntu Nodes

### ISSUE THREAD

**Issue by mpilant** [kubernetes/kubernetes#9808]
I'm trying to install Kubernetes on a collection of three virtual machines and am running into all sorts of problems.  The instructions I'm following are here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md.

First, after updating config-default.sh and trying to invoke kube-up.sh, I get complaint ("Could not find or add an SSH identity") about ssh-add not "working".  There is nothing in the instructions about ssh-anything.  So after some searching I manage to discover ssh-start.  One down.

Second attempt with kube-up.sh fails with "Can't find gcloud in PATH".  Odd, as the instructions say nothing about gdloud.  But I go ahead and install the SDK.  After updating .bashrc, the SDK install fails with the same error.  Strange, as I would have expected the PATH environment variable to have been updated as well as the .bashrc file.  So I log out and back in.  Two down.

Third attempt with kube-up.sh appears to do some more gcloud installations, and then fails because a Google Cloud Platform project was not detected.  HUH?  What does this have to do with Kubernetes?

I would have thought the "Kubernetes Deployment On Bare-metal Ubuntu Nodes" would have contained *all* the instructions about how to deploy Kubernetes on Ubuntu.  Have I missed something?

- Mark

**Comment by luxas** [comment]
Could you try hack/local-up-cluster.sh? 
I'm running on bare metal Raspberry Pis

It sounds like kube-up is designed for Google Compute Engine. 
Installing gcloud SDK solves nothing.

Try with hack/local-up-cluster.sh :)

**Comment by mpilant** [comment]
While I expect I could edit scripts, add software, and generally do what is needed to get Kubernetes running, it would really be counter to the purpose of being able to "easily" install Kubernetes on a host (Linux) system.  Indeed, it would be counter to the purpose of the task for which I was attempting to deploy Kubernetes.

For the moment, it would appear this particular set of instructions needs additional proofing (i.e., performed by someone not intimately familiar with Linux, Kubernetes, etc.) to demonstrate it works.

**Comment by resouer** [comment]
@mpilant As for the ubuntu part, Bare-metal Ubuntu Nodes means any ubuntu cluster you already have (no matter VMs or physical servers). Then the `kube-up.sh` will ssh to & deploy k8s on those machines. Apparently, in your case, you don't have `ssh` properly set up. Can you ssh those target machines may I ask?

**Comment by mpilant** [comment]
As far as I remember, I did have SSH up and running on the systems.
Unfortunately, I had to abandon this approach as I simply did not have the time, and had to move on to other tasks.

**Comment by luxas** [comment]
@mpilant Could @resouer then close this issue?
Because it was opened quite long time ago (in the Kubernetes world)
It was sad that you didn't begin to use Kubernetes, but maybe you'll test it again in the future.

**Comment by resouer** [comment]
@roberthbailey I think we can close this issue, as 1) it is actually a combination of a batch of beginner's problem, 2) the author is not playing with it recently 3) we can not do anything to improve it, because it is not a specific problem.

Please feel free to fire up new issue when you back to this work and encountered specific problem @mpilant

**Comment by roberthbailey** [comment]
Sounds good to me. @mpilant please re-open (or create a new issue) if you disagree.

**Comment by baiyunping333** [comment]
only execute "ssh-keygen"

**Comment by frank-productops** [comment]
I'm having similar issues. I am following the instructions [`here`](https://deis.com/docs/workflow/quickstart/provider/aws/boot/). However, I don't see a `local_up_cluster.sh` file as luxas mentioned. I am running Ubuntu 14.04 in VMware on a Windows 10 host.
