### ISSUE TITLE
imagePullPolicy and :latest defaulting doesn't interact well with declarative API

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#98108]
**What happened**:

Apply a deployment with `:latest`, then switch the image to not use `:latest`.
Remove the deployment, then apply the image without `:latest` again. This time, imagePullPolicy is different.

```
$ cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell
spec:
  selector:
    matchLabels:
      app: shell
  template:
    metadata:
      labels:
        app: shell
    spec:
      containers:
      - name: shell
        image: howardjohn/alpine-shell
        args:
          - /bin/sleep
          - infinity
EOF
deployment.apps/shell created
$ kubectl get deployment shell -oyaml | grep ' imagePullPolicy:'
        imagePullPolicy: Always
$ kubectl set image deployment/shell shell=howardjohn/alpine-shell:v0.0.4
deployment.apps/shell image updated
$ kubectl get deployment shell -oyaml | grep ' imagePullPolicy:'
        imagePullPolicy: Always
$ kubectl delete deployment shell
deployment.apps "shell" deleted
$ cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell
spec:
  selector:
    matchLabels:
      app: shell
  template:
    metadata:
      labels:
        app: shell
    spec:
      containers:
      - name: shell
        image: howardjohn/alpine-shell:v0.0.4
        args:
          - /bin/sleep
          - infinity
EOF
deployment.apps/shell created
$ kubectl get deployment shell -oyaml | grep ' imagePullPolicy:'
        imagePullPolicy: IfNotPresent
```

**What you expected to happen**:

API is fully declarative; applying pod v1 then pod v2 should be the same as applying pod v2 directly.

I think I know *why* this happens, the default is applied and then "sticky", but I am not sure its the expected user behavior?

**How to reproduce it (as minimally and precisely as possible)**: See above

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T22:31:47Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: kind
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
This is caused by a special logic for "latest" image.
https://kubernetes.io/docs/concepts/containers/images/#updating-images
- default ImagePullPolicy is `IfNotPresent`
- if the image tag is none or  `latest`, the ImagePullPolicy will be `Always`.

We may add a tip or warning for users when`kubectl set image deployment/shell shell=howardjohn/alpine-shell:v0.0.4` on a deployment that is using `latest` tag image? However, the check may be on the server-side and the notice is just a warning.

**Comment by howardjohn** [comment]
@pacoxu my concern is not the special behavior of `:latest` mentioned in https://kubernetes.io/docs/concepts/containers/images/#updating-images, its that applying `:latest` then `v0.0.4` is not the same as applying `v0.0.4` directly. This makes it non-deterministic in a CI pipeline, for example, and in my opinion violates the declarative-ness of the API

**Comment by howardjohn** [comment]
Also the inverse is true. If I go from a concrete tag to latest, I may get my `:latest` tag not pulled with `imagePullPolicy` not set. This led to me using a stale image with `:latest` even though I followed https://kubernetes.io/docs/concepts/containers/images/#updating-images

**Comment by jpbetz** [comment]
+ @apelisse

Is this any better when using server side apply?

**Comment by apelisse** [comment]
> This makes it non-deterministic in a CI pipeline, for example, and in my opinion violates the declarative-ness of the API

Yeah, I think in general that's what we get for trying to be smart :-(.

I would argue that if you want to be declarative and you have a strong opinion about the value of the `ImagePullPolicy`, you should specify it in your config file?

> Is this any better when using server side apply?

Unfortunately, no.

**Comment by howardjohn** [comment]
> I would argue that if you want to be declarative and you have a strong opinion about the value of the ImagePullPolicy, you should specify it in your config file?


That is fair, it does become tricky when you are taking arbitrary images (from helm, kustomize, mutating webhooks, etc) and want the default behavior of setting ImagePullPolicy based on the image. Of course the tooling might take on the complexity but it is not always feasible in some cases
