### ISSUE TITLE
Kubectl on Windows does not support wildcards

### ISSUE THREAD

**Issue by joedborg** [kubernetes/kubernetes#98100]
**What happened**:

I get an error when I try to use wildcards with kubectl.

```
C:\Users\joe\Documents>kubectl apply -f *.yaml
error: the path "*.yaml" cannot be accessed: CreateFile *.yaml: The filename, directory name, or volume label syntax is incorrect.

```

**What you expected to happen**:

`cmd` does support wildcards and so does the *nix kubectl.

```
C:\Users\joe\Documents>dir *.yaml
 Volume in drive C has no label.
 Volume Serial Number is 940D-7023

 Directory of C:\Users\joe\Documents

15/01/2021  09:14               260 pod.yaml
               1 File(s)            260 bytes
               0 Dir(s)  305,194,307,584 bytes free
```

**How to reproduce it (as minimally and precisely as possible)**:

Run example above.

**Environment**:
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.1-34+e7db93d188d0d1", GitCommit:"e7db93d188d0d12f2fe5336d1b85cdb94cb909d3", GitTreeState:"clean", BuildDate:"2021-01-11T23:50:46Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by 11janci** [comment]
I would like to look at this

**Comment by rikatz** [comment]
/assign @11janci 

Go for it, let me know if you need something

**Comment by liggitt** [comment]
> so does the *nix kubectl.

is that accurate? the expansion is done by the shell, right? also, if *.yaml expands to more than one file, that command does not work:

```sh
touch foo{1,2,3}.yaml

kubectl create -f *.yaml
error: Unexpected args: [foo2.yaml foo3.yaml]
```

**Comment by eddiezane** [comment]
/close

Multiple `-f`'s can be passed and workarounds can be done with other commands to generate them. `-f` also works with a directory `-f .` will grab all yaml files in current dir..
