### ISSUE TITLE
Unable to set kernel.core_pattern for the pods

### ISSUE THREAD

**Issue by dkatipamula** [kubernetes/kubernetes#98106]
Hi,
I am trying to modify the kernel.core_pattern but I am unable to modify it as it is Read-Only.

I have tried:
_echo 'kernel.core_pattern=/tmp/core-%e.%p.%h.%t' >> /etc/sysctl.conf_
Reload sysctl:
_sysctl --system_

* Applying /etc/sysctl.conf ...
sysctl: setting key "kernel.core_pattern": Read-only file system

cat /proc/sys/kernel/core_pattern 
|/usr/share/apport/apport %p %s %c %d %P %E

I am no able to add it to the pod yaml either:
spec:
      securityContext:
        sysctls:
        - name: kernel.core_pattern
          value: "/tmp/core-%e.%p.%h.%t"

I keep getting this:
**SysctlForbidden**

I created a PodSecurityPolicy as well:
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: sysctl-psp
spec:
  privileged: false  # Don't allow privileged pods!
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  allowedUnsafeSysctls:
  - kernel.*

Still no luck. 

Any suggestions?

**Comment by pacoxu** [comment]
You may refer to https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/

`kubelet` need to start with `--allowed-unsafe-sysctls xxxx`

/sig node
/kind support

**Comment by dkatipamula** [comment]
Thanks @pacoxu for your reply.
I added the kubelet flag as specified in the link:
> ps -Af | grep kubelet 

root     31396     1  3 21:55 ?        00:00:00 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --network-plugin=cni --allowed-unsafe-sysctls=kernel.core_pattern --pod-infra-container-image=k8s.gcr.io/pause:3.2
root     31575 13430  0 21:55 pts/0    00:00:00 grep --color=auto kubelet

I can see --allowed-unsafe-sysctls=kernel.core_pattern.

Then I tried to set the sysctl in the pod:
> sysctl -w kernel.core_pattern=/tmp/core-%e.%p.%h.%t
sysctl: setting key "kernel.core_pattern": Read-only file system

I also tried to add it to the yaml file:
spec:
  securityContext:
    sysctls:
    - name: kernel.core_pattern
      value: "/tmp/core-%e.%p.%h.%t"

When I apply the modified yaml file, it keep trying to create a new pod but fails endlessly with the following error:
pod/cbng-79dd8cfb85-wm7mj   0/1     SysctlForbidden   0          9s
pod/cbng-79dd8cfb85-xgtb4   0/1     SysctlForbidden   0          1s
pod/cbng-79dd8cfb85-xvp4m   0/1     SysctlForbidden   0          21s
pod/cbng-79dd8cfb85-zf27p   0/1     SysctlForbidden   0          8s

I am not sure what I am doing wrong.

**Comment by pacoxu** [comment]
I think this is not supported yet. Only namesapced sysctls are supported with prefix like https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/sysctl/namespace.go#L41-L46
```
Jan 20 11:47:57 daocloud kubelet[124905]: F0120 11:47:57.068626  124905 server.go:269] failed to run Kubelet: failed to create kubelet: the sysctl "kernel.core_pattern" are not known to be namespaced
```

https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/#setting-sysctls-for-a-pod
> Sysctls with no namespace are called node-level sysctls. If you need to set them, you must manually configure them on each node's operating system, or by using a DaemonSet with privileged containers.

**Comment by tcervi** [comment]
Hi @dkatipamula, just out of curiosity did you manage to put kernel.core_pattern changes to work using manual configs or DaemonSet with privileged containers?
