### ISSUE TITLE
[Flaky Test] [sig-network] Services should be able to change the type from ClusterIP to ExternalName

### ISSUE THREAD

**Issue by thejoycekung** [kubernetes/kubernetes#98104]
**Which jobs are flaking**:
- `ci-kubernetes-e2e-ubuntu-gce-containerd`
- `ci-kubernetes-e2e-gci-gce`

**Which test(s) are flaking**:
`[sig-network] Services should be able to change the type from ClusterIP to ExternalName`

**Testgrid link**:
- https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-ubuntu-master-containerd
- https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-default

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:640
Jan 15 09:43:10.121: Unexpected error:
    <*errors.errorString | 0xc002cf2840>: {
        s: "ExternalName service \"services-5563/execpod4sxhv\" must resolve to IP",
    }
    ExternalName service "services-5563/execpod4sxhv" must resolve to IP
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1773
```

**Anything else we need to know**:
Having some trouble with finding this in Triage, but here are two example failures:

- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1350010433976668160
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1349741395811766272

/sig network

**Comment by JornShen** [comment]
/assign
I'll take time to see it.

**Comment by thockin** [comment]
Any updates on this?  Should we triage-accept it?
