### ISSUE TITLE
Kubernetes Elasticsearch logging discovery

### ISSUE THREAD

**Issue by zzzwjZhang** [kubernetes/kubernetes#98120]
when i deploy it in k8s-v1.20.0,it cant work and show nothing just Kubernetes Elasticsearch logging discovery, i have no idea and no wrong could see
![微信截图_20210117201640](https://user-images.githubusercontent.com/46548177/104840500-165d8880-5901-11eb-9ae3-0911b0e14abb.png)

**Comment by neolit123** [comment]
please try the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
