### ISSUE TITLE
Failed to run Kubelet when using a valid cpuset specified by --reserved-cpus when not all CPUs are turned on

### ISSUE THREAD

**Issue by yanirq** [kubernetes/kubernetes#98121]
**What happened**:
On a node that has a topology of more than 1 numa node, If some or all of the CPUs of a numa node are turned off (mostly for testing purposes)  a valid `--reserved-cpus` set can cause the Kubelet  service to fail on:
`failed to run Kubelet: Invalid cpuset "<cpu set>" specified by --reserved-cpus`

This failure has occurred on a node that has 2 numa nodes with hyperthreading enabled. 

**What you expected to happen**:
When setting a valid  `--reserved-cpus`  set, the Kubelet service should pass validations and function properly even if some CPU cores are turned off but the reserved cpus are still under a valid range. 

**How to reproduce it (as minimally and precisely as possible)**:
1. A minimal cluster should have 1 master and 1 worker node.
2. The worker node should have 2 Numa nodes and hyperthreading enabled(BIOS setting)
   **Important**:  The CPUs divided between the numa nodes cannot be sequential in order to reproduce the issue
3. Set `--reserved-cpus` that are under Numa node 0 only (under kubelet.conf)
4. Restart Kubelet service
5. Turn off all CPUs that belong to numa node 1 (`echo 0 > /sys/devices/system/cpu/cpu#/online`)
6. Restart Kubelet service
7. Check systemctl status kubelet.service and journal logs that will present:
   `failed to run Kubelet: Invalid cpuset "<cpu set>" specified by --reserved-cpus`

**Anything else we need to know?**:
The scenario of split ranges of Numa nodes might occur only with Hyperthreading enabled. 

**Environment**:
- Kubernetes version (use `kubectl version`):
`Kubernetes Version: v1.19.0+9f84db3`
- Cloud provider or hardware configuration:
 `Bare metal node, Node server type:  HPE ProLiant DL380 Gen10`
- OS (e.g: `cat /etc/os-release`):
```
NAME="Red Hat Enterprise Linux CoreOS"
VERSION="46.82.202010301241-0"
VERSION_ID="4.6"
OPENSHIFT_VERSION="4.6"
RHEL_VERSION="8.2"
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 46.82.202010301241-0 (Ootpa)"
ID="rhcos"
ID_LIKE="rhel fedora"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::coreos"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.6"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.6"
OSTREE_VERSION='46.82.202010301241-0'
```
- Kernel (e.g. `uname -a`):
  `Linux 4.18.0-193.39.1.rt13.89.el8`  (real time kernel)
- Install tools:
   `Openshift , iLO5`

**Comment by yanirq** [comment]
Here is a real example where the error occurred:
For the following CPU layout (after turning off numa node 1 CPUs)
```
[core@cnfdb3 ~]$ lscpu
Architecture:         x86_64
CPU op-mode(s):       32-bit, 64-bit
Byte Order:           Little Endian
CPU(s):               80
On-line CPU(s) list:  0-19,40-59
Off-line CPU(s) list: 20-39,60-79
Thread(s) per core:   2
Core(s) per socket:   20
Socket(s):            1
NUMA node(s):         2
Vendor ID:            GenuineIntel
CPU family:           6
Model:                85
Model name:           Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz
Stepping:             7
CPU MHz:              2800.002
BogoMIPS:             4200.00
Virtualization:       VT-x
L1d cache:            32K
L1i cache:            32K
L2 cache:             1024K
L3 cache:             28160K
NUMA node0 CPU(s):    0-19,40-59
NUMA node1 CPU(s):    
Flags:                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear flush_l1d arch_capabilities
```
```
$ lscpu --all --extend
CPU NODE SOCKET CORE L1d:L1i:L2:L3 ONLINE
0   0    0      0    0:0:0:0       yes
1   0    0      1    1:1:1:0       yes
2   0    0      2    2:2:2:0       yes
3   0    0      3    3:3:3:0       yes
4   0    0      4    4:4:4:0       yes
5   0    0      5    5:5:5:0       yes
6   0    0      6    6:6:6:0       yes
7   0    0      7    7:7:7:0       yes
8   0    0      8    8:8:8:0       yes
9   0    0      9    9:9:9:0       yes
10  0    0      10   10:10:10:0    yes
11  0    0      11   11:11:11:0    yes
12  0    0      12   12:12:12:0    yes
13  0    0      13   13:13:13:0    yes
14  0    0      14   14:14:14:0    yes
15  0    0      15   15:15:15:0    yes
16  0    0      16   16:16:16:0    yes
17  0    0      17   17:17:17:0    yes
18  0    0      18   18:18:18:0    yes
19  0    0      19   19:19:19:0    yes
20  -    -      -    :::           no
21  -    -      -    :::           no
22  -    -      -    :::           no
23  -    -      -    :::           no
24  -    -      -    :::           no
25  -    -      -    :::           no
26  -    -      -    :::           no
27  -    -      -    :::           no
28  -    -      -    :::           no
29  -    -      -    :::           no
30  -    -      -    :::           no
31  -    -      -    :::           no
32  -    -      -    :::           no
33  -    -      -    :::           no
34  -    -      -    :::           no
35  -    -      -    :::           no
36  -    -      -    :::           no
37  -    -      -    :::           no
38  -    -      -    :::           no
39  -    -      -    :::           no
40  0    0      0    0:0:0:0       yes
41  0    0      1    1:1:1:0       yes
42  0    0      2    2:2:2:0       yes
43  0    0      3    3:3:3:0       yes
44  0    0      4    4:4:4:0       yes
45  0    0      5    5:5:5:0       yes
46  0    0      6    6:6:6:0       yes
47  0    0      7    7:7:7:0       yes
48  0    0      8    8:8:8:0       yes
49  0    0      9    9:9:9:0       yes
50  0    0      10   10:10:10:0    yes
51  0    0      11   11:11:11:0    yes
52  0    0      12   12:12:12:0    yes
53  0    0      13   13:13:13:0    yes
54  0    0      14   14:14:14:0    yes
55  0    0      15   15:15:15:0    yes
56  0    0      16   16:16:16:0    yes
57  0    0      17   17:17:17:0    yes
58  0    0      18   18:18:18:0    yes
59  0    0      19   19:19:19:0    yes
60  -    -      -    :::           no
61  -    -      -    :::           no
62  -    -      -    :::           no
63  -    -      -    :::           no
64  -    -      -    :::           no
65  -    -      -    :::           no
66  -    -      -    :::           no
67  -    -      -    :::           no
68  -    -      -    :::           no
69  -    -      -    :::           no
70  -    -      -    :::           no
71  -    -      -    :::           no
72  -    -      -    :::           no
73  -    -      -    :::           no
74  -    -      -    :::           no
75  -    -      -    :::           no
76  -    -      -    :::           no
77  -    -      -    :::           no
78  -    -      -    :::           no
79  -    -      -    :::           no

```

using :  
`"reservedSystemCPUs": "0-2,40-42"`
will result in:
```
Invalid cpuset specified by --reserved-cpus
failed to run Kubelet: Invalid cpuset "0-2,40-42" specified by --reserved-cpus
```

CPUs 0-2 and 40-42 are all under numa node 0 and are active.

The validation fails here:
https://github.com/kubernetes/kubernetes/blob/3b38f6a08e255b3eb2e34ffb3c3cecacc081f334/cmd/kubelet/app/server.go#L668
In this scenario we have 40 active CPUs (all from numa node 0)  but the range check will fail on the last item in reserved CPUs:
42 (last time) >= 40 (NumCores)

**Comment by yanirq** [comment]
This is probably not just strictly related to NUMA. The same behaviour could  happen when offlining CPUs on any multi-core system, for example: disabling HT on a single numa node  may end up with a very similar scenario (depends on the CPU specifics).
The kubelet validation is too naive; it needs to be aware (and act accordingly to) the online CPU set. The emerging hidden assumption in kubelet is all the physical cpus are always online.

**Comment by jianzzha** [comment]
I wasn't able to recreate with all cpus on numa 1 offline, 
On-line CPU(s) list:   0-11,24-35
Off-line CPU(s) list:  12-23,36-47

with HT  enabled, --reserved-cpus=0-3, kubelet restart fine

but as mentioned by @yanirq, this option kubelet validation didn't consider the situation where some cpus are offline.

**Comment by jianzzha** [comment]
Ok I was able to reproduce when I used --reserved-cpus=28-35.

**Comment by jianzzha** [comment]
@yanirq @fromanirh Just a FYI, even with the validation update, if you take certain CPUs offline, you need to delete /var/lib/kubelet/cpu_manager_state before restart kubelet. This state check is done by cpumanager, see https://github.com/kubernetes/kubernetes/blob/cf2fceb11f7df1ab050159a5d70d2b0edfd980fb/pkg/kubelet/cm/cpumanager/policy_static.go#L182
