### ISSUE TITLE
`kubectl patch` error message mentions of a non-existent flag

### ISSUE THREAD

**Issue by surajssd** [kubernetes/kubernetes#98143]
**What happened**:

Kubectl patch sub-command shows wrong error help message if an input is wrong. The error message says `error: resource(s) were provided, but no name, label selector, or --all flag specified` and when I try to use `--all` flag it says `Error: unknown flag: --all`.

**What you expected to happen**:

I expected either the first error message to not have `--all` or `kubectl patch` should have a flag `--all`.

**How to reproduce it (as minimally and precisely as possible)**:

If you run the following command without a node name you get this error:

```console
$ kubectl patch nodes  -p '{"spec":{"providerID":"external"}}'
error: resource(s) were provided, but no name, label selector, or --all flag specified
```

As the above error said you can specify `--all`, you specify that. This fails with another error saying `--all` is unknown flag:

```console
$ kubectl patch nodes --all -p '{"spec":{"providerID":"external"}}'

Error: unknown flag: --all
See 'kubectl patch --help' for usage.
```

And in the help there is no `--all` flag:

```console
$ kubectl patch --help | grep '\-\-all'
      --allow-missing-template-keys=true: If true, ignore any errors in templates when a field or map key is missing in the template. Only applies to golang and jsonpath output formats.
```

**Environment**:
- Kubernetes version (use `kubectl version`):

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by pandaamanda** [comment]
I think we need to decide whether to add flag --all and --selector to kubectl patch.

**Comment by rikatz** [comment]
on my queue, will look tomorrow :D

**Comment by eddiezane** [comment]
/triage accepted

Probably just need to update error message here.

**Comment by rikatz** [comment]
oh sorry, missed that one. Will look now

**Comment by rikatz** [comment]
OK, so we decided to correct the error message per the PR right? :)

**Comment by rikatz** [comment]
@pandaamanda as you're dealing with this PR, I'll left you as assignee and follow the PR review :)

/unassign
