### ISSUE TITLE
kubelet: improve error messages about expired certificates

### ISSUE THREAD

**Issue by thanatos** [kubernetes/kubernetes#98150]
**What happened**: the `kubelet` fails to start; it logs,

```
Jan 18 17:33:58 aura kubelet[1457370]: E0118 17:33:58.888700 1457370 bootstrap.go:265] part of the existing bootstrap client certificate is expired: 2020-12-06 18:55:55 +0000 UTC
Jan 18 17:33:58 aura kubelet[1457370]: F0118 17:33:58.888743 1457370 server.go:271] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
Jan 18 17:33:58 aura systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
Jan 18 17:33:58 aura systemd[1]: kubelet.service: Failed with result 'exit-code'.
```

**What you expected to happen**: either the `kubelet` starts, *or it produces a *useable* diagnostic*

It tells me that a certificate is expired. If you Google the error, you'll hit SO questions like [this one](https://stackoverflow.com/questions/59825118/kubelet-unable-to-load-bootstrap-kubeconfig), which helpfully suggest you run `kubeadm alpha certs renew`¹. That runs successfully, but afterwards, the `kubelet` continues to fail to start. A bit more digging, and one might learn about `kubeadm alpha certs check-expiration`, and think, ah-ha! That'll tell me _which_ cert has expired, and thus, where to look for guidance on renewing it.

As we've already run `renew`, it will tell us that …
```
# kubeadm alpha certs check-expiration
CERTIFICATE                EXPIRES                  RESIDUAL TIME   EXTERNALLY MANAGED
admin.conf                 Jan 18, 2022 22:30 UTC   364d            no      
apiserver                  Jan 18, 2022 22:30 UTC   364d            no      
apiserver-etcd-client      Jan 18, 2022 22:30 UTC   364d            no      
apiserver-kubelet-client   Jan 18, 2022 22:30 UTC   364d            no      
controller-manager.conf    Jan 18, 2022 22:30 UTC   364d            no      
etcd-healthcheck-client    Jan 18, 2022 22:30 UTC   364d            no      
etcd-peer                  Jan 18, 2022 22:30 UTC   364d            no      
etcd-server                Jan 18, 2022 22:30 UTC   364d            no      
front-proxy-client         Jan 18, 2022 22:30 UTC   364d            no      
scheduler.conf             Jan 18, 2022 22:30 UTC   364d            no      
```
…nothing is expired. (But still the `kubelet` refuses to start.)

So we just run every `*.crt` in `/etc/kubernetes` through `openssl x509` manually with `find`:

```
# find -iname '*.crt' -print0 | xargs -0 -n1 openssl x509 -noout -text -in | grep Not\ After
```

…and they're all fine.

After some further digging, I did find it. It's in `kubelet.conf`, but it's wrapped in YAML config so the `find` can't see it. It isn't clear to me why `kubeadm` should miss it. But at the very least, **`kubelet` needs to emit a usable diagnostic**, minimally including *which* certificate is expired, and ideally with enough information for me to determine the correct way to fix it.

(Eventually, I hit [this comment on a closed issue](https://github.com/kubernetes/kubernetes/issues/84252#issuecomment-545622426), which contains the additional command to regenerate `kubelet.conf`.)

**How to reproduce it (as minimally and precisely as possible)**: run a cluster for ~1 yr, let the cert expire…

**Anything else we need to know?**:

¹it instills much confidence that renewing the certs is "alpha".

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.8
- Cloud provider or hardware configuration: N/A, single `kubeadm`-made node
- OS (e.g: `cat /etc/os-release`): Gentoo
- Kernel (e.g. `uname -a`): `5.4.60-gentoo`
- Install tools: `kubeadm`?
- Network plugin and version (if this is a network-related bug): N/A, but Calico
- Others:

**Comment by pacoxu** [comment]
It seems that the certs are renewed today.

You may need to restart kube-apiserver、kube-controller、kube-scheduler、etcd & kubelet on each node.

**Comment by neolit123** [comment]
> Kubernetes version (use kubectl version): 1.16.8

this version is no longer in support.

> It tells me that a certificate is expired. If you Google the error, you'll hit SO questions like this one, which helpfully suggest you run kubeadm alpha certs renew
> ...
> (Eventually, I hit this comment on a closed issue, which contains the additional command to regenerate kubelet.conf.)

you seem to have sufficient information on how to recover.

> But at the very least, kubelet needs to emit a usable diagnostic, minimally including which certificate is expired,

arguably it does need better messaging.
i will keep this open with a "feature" label, but if you want this changed you might have to send the PR yourself.

>  and ideally with enough information for me to determine the correct way to fix it.

the guide to create certs is here:
https://kubernetes.io/docs/setup/best-practices/certificates/

kubeadm makes it easier to users, but the kubelet error messages should not mention kubeadm.

/remove-kind bug
/kind feature
/area kubelet

**Comment by neolit123** [comment]
/retitle kubelet: improve error messages about expired certificates

**Comment by neolit123** [comment]
also leaving this to SIG Node to decide if the want the feature or not. (via "triage accepted" vs "close")

**Comment by SataQiu** [comment]
@thanatos If you don't mind, I sent a PR  #98230 to improve the error message.
