### ISSUE TITLE
Kube-scheduler can't send event because Note field too large

### ISSUE THREAD

**Issue by gitirabassi** [kubernetes/kubernetes#98175]
**What happened**:
When a pod can't be scheduled and the cardinality of taints on nodes is high, the Note field in the event can become bigger than the 1024 allowed and the event isn't sent. The pod stays in a state of `Pending` without en event which makes the User Experience very bad

**What you expected to happen**:
I would expect the Kube-scheduler to be able to send the event no matter how many different taints are on nodes

**How to reproduce it (as minimally and precisely as possible)**:
add many different taints to nodes and then trying to schedule something which can't be successfully scheduled (higher CPU/memory than any node has)

**Anything else we need to know?**:
```
E0108 16:18:50.017679  762538 event_broadcaster.go:238] Server rejected event '&v1beta1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"<redacted: Pod name>", GenerateName:"", Namespace:"<redacted: Namespace>", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, EventTime:v1.MicroTime{Time:time.Time{wall:0xbff63f5a80f49a60, ext:65938071707113, loc:(*time.Location)(0x2b40280)}}, Series:(*v1beta1.EventSeries)(nil), ReportingController:"default-scheduler", ReportingInstance:"default-scheduler-<redacted: Hostname>", Action:"Scheduling", Reason:"FailedScheduling", Regarding:v1.ObjectReference{Kind:"Pod", Namespace:"<redacted: Namespace>", Name:"<redacted: Podname>", UID:"<redacted: UUID>", APIVersion:"v1", ResourceVersion:"<redacted: Rev version>", FieldPath:""}, Related:(*v1.ObjectReference)(nil), Note:"0/100 nodes are available: 1 node(s) had taint {<redacted: Taint Key>}, that the pod didn't tolerate, 1 node(s) had taint {<redacted: Taint Key>: }, that the pod didn't tolerate, 1 node(s) had taint {<redacted: Taint Key>: }, that the pod didn't tolerate, 11 node(s) had taint {<redacted: Taint Key>: }, that the pod didn't tolerate, 11 node(s) had taint {<redacted: Taint Key>: }, that the pod didn't tolerate, 87 Insufficient cpu, 34 node(s) had taint {<redacted: Taint Key>: }, that the pod didn't tolerate, 12 pod has unbound immediate PersistentVolumeClaims, 12 Too many pods, 2 node(s) had taint {<redacted: Taint Key>: }, that the pod didn't tolerate, 21 node(s) had taint {<redacted: Taint Key>: }, that the pod didn't tolerate, 65 node(s) had taint {<redacted: Taint Key>: }, that the pod didn't tolerate, 39 node(s) had taint {<redacted: Taint Key>: true}, that the pod didn't tolerate, 39 node(s) had taint {<redacted: Taint Key>: }, that the pod didn't tolerate, 5 node(s) had taint {<redacted: Taint Key>: }, that the pod didn't tolerate, 6 Insufficient memory, 8 node(s) had taint {<redacted: Taint Key>: }, that the pod didn't tolerate, 23 node(s) were unschedulable, 9 node(s) had taint {<redacted: Taint Key>}, that the pod didn't tolerate.", Type:"Warning", DeprecatedSource:v1.EventSource{Component:"default-scheduler", Host:""}, DeprecatedFirstTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeprecatedLastTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeprecatedCount:0}': 'Event "<redacted: event ID>" is invalid: message: Invalid value: "": can have at most 1024 characters' (will not retry!)
```

In this case the length of the message was 1334 characters.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.9
- Cloud provider or hardware configuration: bare metal

**Possible solutions**:
- make event `Note` size configurable, it's now hardcoded to 1024 characters [here](https://github.com/kubernetes/kubernetes/blob/564b0e55c7007745500d579356897848aaacb9dd/pkg/apis/core/validation/events.go#L38)
- make scheduler note aware of that limit and work around I, if length > 1024 then
  - truncate the string (so at least something is shown)
  - produce N events splitting the text
  - (preferred one): change event Note to be to something like: `Couldn't schedule pod because of this taint, this taint and N more taints` (the whole complete information would still be present in the pod status field. for debugging purposes)

**Comment by gitirabassi** [comment]
I could provide the fix in case we define which solution is best

**Comment by alculquicondor** [comment]
This is a consequence of #87250

I think we can just drop some reasons when we are building the status message if the message is too large.

This comes from here https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/types.go#L107

/help

**Comment by ahg-g** [comment]
how many different taints did you have?

I think in all cases we should truncate the message as well: https://github.com/kubernetes/kubernetes/blob/09f4baed35865d410febb3220811ca5c2fe1cf42/pkg/scheduler/scheduler.go#L336

**Comment by Huang-Wei** [comment]
Another remidiation is to supress outoutping nil fields (such as GenerateName:"", SelfLink:"", UID:"", ResourceVersion:"", etc.) in the EventRecorder side.

**Comment by gitirabassi** [comment]
> Another remidiation is to supress outoutping nil fields (such as GenerateName:"", SelfLink:"", UID:"", ResourceVersion:"", etc.) in the EventRecorder side.

The size limit we're hitting is specifically on the `Note` field

**Comment by gitirabassi** [comment]
> how many different taints did you have?
> 
> I think in all cases we should truncate the message as well:
> 
> https://github.com/kubernetes/kubernetes/blob/09f4baed35865d410febb3220811ca5c2fe1cf42/pkg/scheduler/scheduler.go#L336

Completely agreed

**Comment by WxySupn** [comment]
good issue
