### ISSUE TITLE
create longhorn snapshot error

### ISSUE THREAD

**Issue by yyt6200** [kubernetes/kubernetes#98170]
My k8s version number is 1.18.8, using Longhorn as storage. When creating the snapshot, report the following error, please help to see, provide some guidance，thank you.

**----------------------------------------------------------log-------------------------------------------------------------------------------**
I0119 08:23:23.076483 1 snapshot_controller_base.go:144] enqueued "snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef" for sync

I0119 08:23:23.076511 1 snapshot_controller_base.go:159] contentWorker[snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef]

I0119 08:23:23.076523 1 util.go:141] storeObjectUpdate: adding content "snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef", version 4296313

I0119 08:23:23.076531 1 snapshot_controller.go:58] synchronizing VolumeSnapshotContent[snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef]

I0119 08:23:23.076537 1 snapshot_controller.go:569] Check if VolumeSnapshotContent[snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef] should be deleted.

I0119 08:23:23.076541 1 snapshot_controller.go:78] syncContent: Call CreateSnapshot for content snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef

I0119 08:23:23.076546 1 snapshot_controller.go:133] createSnapshot for content [snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef]: started

I0119 08:23:23.076551 1 snapshot_controller.go:112] scheduleOperation[create-snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef]

I0119 08:23:23.076576 1 snapshot_controller.go:305] createSnapshotWrapper: Creating snapshot for content snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef through the plugin ...

I0119 08:23:23.076586 1 snapshot_controller.go:218] getCSISnapshotInput for content [snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef]

I0119 08:23:23.076591 1 snapshot_controller.go:477] getSnapshotClass: VolumeSnapshotClassName [longhorn]

I0119 08:23:23.076607 1 snapshot_controller.go:606] setAnnVolumeSnapshotBeingCreated: set annotation [snapshot.storage.kubernetes.io/volumesnapshot-being-created:yes] on content [snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef].

I0119 08:23:23.082136 1 snapshot_controller_base.go:144] enqueued "snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef" for sync

I0119 08:23:23.082171 1 snapshot_controller_base.go:159] contentWorker[snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef]

I0119 08:23:23.082184 1 util.go:169] storeObjectUpdate updating content "snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef" with version 4296314

I0119 08:23:23.082198 1 snapshot_controller.go:58] synchronizing VolumeSnapshotContent[snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef]

I0119 08:23:23.082204 1 snapshot_controller.go:569] Check if VolumeSnapshotContent[snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef] should be deleted.

I0119 08:23:23.082214 1 snapshot_controller.go:78] syncContent: Call CreateSnapshot for content snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef

I0119 08:23:23.082218 1 snapshot_controller.go:133] createSnapshot for content [snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef]: started

I0119 08:23:23.082224 1 snapshot_controller.go:112] scheduleOperation[create-snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef]

I0119 08:23:23.082232 1 snapshot_controller.go:118] operation "create-snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef" is already running, skipping

I0119 08:23:23.090758 1 snapshot_controller.go:179] updateContentStatusWithEvent[snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef]

I0119 08:23:23.094933 1 snapshot_controller.go:200] updating VolumeSnapshotContent[snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef] error status failed Operation cannot be fulfilled on volumesnapshotcontents.snapshot.storage.k8s.io "snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef": the object has been modified; please apply your changes to the latest version and try again

E0119 08:23:23.094953 1 snapshot_controller.go:139] createSnapshot [create-snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef]: error occurred in createSnapshotWrapper: failed to add VolumeSnapshotBeingCreated annotation on the content snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef: "snapshot controller failed to update snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef on API server: Operation cannot be fulfilled on volumesnapshotcontents.snapshot.storage.k8s.io \"snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef\": the object has been modified; please apply your changes to the latest version and try again"

E0119 08:23:23.094987 1 goroutinemap.go:150] Operation for "create-snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef" failed. No retries permitted until 2021-01-19 08:23:23.594959571 +0000 UTC m=+354916.017256934 (durationBeforeRetry 500ms). Error: "failed to add VolumeSnapshotBeingCreated annotation on the content snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef: \"snapshot controller failed to update snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef on API server: Operation cannot be fulfilled on volumesnapshotcontents.snapshot.storage.k8s.io \\\"snapcontent-e3e91dad-b7da-4bd1-91e7-e5e7ee7033ef\\\": the object has been modified; please apply your changes to the latest version and try again\""

**Comment by neolit123** [comment]
please try the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
