### ISSUE TITLE
new kubectl exec with two args isn't answearing it right

### ISSUE THREAD

**Issue by Cividati** [kubernetes/kubernetes#98179]
**What happened**:
When I type ```kubectl exec $POD_NAME -- echo hi && bash```, i got the message 'hi', and logged in into bash. But the terminal doesn't show that i'm connected to the pod, it shows my current bash session. 
When I type ```whoami``` or ```pwd``` it shows my current user and folder.
When I type ```exit``` its shows the message 'exit', meaning that I exitted the pod connection, and came back to my original session. 
I don't know if i'm doing it wrong or it's a bug, so I reported here.

**What you expected to happen**:
I expected to get message hi, and bash on the pod.

**How to reproduce it (as minimally and precisely as possible)**:
Just type the commad 
```kubectl exec $POD_NAME -- echo hi && bash```

**Anything else we need to know?**:
I love k8s ^^

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

- Kernel (e.g. `uname -a`): Linux ITSD040 5.8.0-38-generic #43~20.04.1-Ubuntu SMP Tue Jan 12 16:39:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by wzshiming** [comment]
try this `kubectl exec $POD_NAME -- sh -c "echo hi && bash"`

**Comment by Cividati** [comment]
> kubectl exec $POD_NAME -- sh -c "echo hi && bash"

Unfortunatelly it didn't work here :(.  
Thanks for the help ^^

**Comment by wzshiming** [comment]
`kubectl exec -it $POD_NAME -- sh -c "echo hi && bash"`

**Comment by neolit123** [comment]
> kubectl exec -it $POD_NAME -- sh -c "echo hi && bash"

this should work as long as the container has `bash` or `sh`:

these discussions are best suited for the support forums:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
