### ISSUE TITLE
Kubelet flag `--cloud-provider` is marked deprecated but missing corresponding KubeletConfiguration field

### ISSUE THREAD

**Issue by surajssd** [kubernetes/kubernetes#98185]
**What happened**:

Flag `--cloud-provider` is marked as deprecated but does not have a corresponding [`KubeletConfiguration`](https://github.com/kubernetes/kubernetes/blob/release-1.20/staging/src/k8s.io/kubelet/config/v1beta1/types.go) field. 

> `--cloud-provider string`
> The provider for cloud services. Set to empty string for running with no cloud provider. If set, the cloud provider determines the name of the node (consult cloud provider documentation to determine if and how the hostname is used). (DEPRECATED: will be removed in 1.23, in favor of removing cloud provider code from Kubelet.)

source: [kubelet CLI reference](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/).

**What you expected to happen**:

I expected a field like `cloudProvider` which corresponds to the above flag.

**Anything else we need to know?**:

It can be easy to confuse the flag `--cloud-provider` with the field `providerID` in the `KubeletConfiguration`, but they are not the same because there is a flag corresponding to this field `--provider-id`.

```
// providerID, if set, sets the unique id of the instance that an external provider (i.e. cloudprovider)
// can use to identify a specific node.
// Dynamic Kubelet Config (beta): If dynamically updating this field, consider that
// it may impact the ability of the Kubelet to interact with cloud providers.
// Default: ""
// +optional
ProviderID string `json:"providerID,omitempty"`
```

source: [k8s source code](https://github.com/kubernetes/kubernetes/blob/release-1.20/staging/src/k8s.io/kubelet/config/v1beta1/types.go#L794-L800)

> `--provider-id string`
> Unique identifier for identifying the node in a machine database, i.e cloud provider. (DEPRECATED: This parameter should be set via the config file specified by the Kubelet's `--config` flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.)

source: [kubelet CLI reference](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/).

/sig node

**Comment by neolit123** [comment]
this is already tracked here:
https://github.com/kubernetes/kubernetes/issues/86843

/close
