### ISSUE TITLE
Offline installer for Kubernetes

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kubernetes#9819]
Need a fully offline installer for Kubernetes that can work in a closed network. Currently, it requires a network connection to upload/download to a storage bucket.

**Comment by erictune** [comment]
have you seen https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/bare_metal_offline.md

**Comment by roberthbailey** [comment]
Closing as fixed based on @erictune's last comment.
