### ISSUE TITLE
Is it possible to allow label to contain blank '  '  ?

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/kubernetes#98202]
**What would you like to be added**:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L166  is regex for `label` and in https://github.com/kubernetes/cloud-provider-openstack/pull/1380  openstack cloud provider use Availability zone (which allow blank ) to fill `topology.kubernetes.io/zone` label, and this lead to potential error because label in k8s doesn't allow blank

so this just raise the question to see whether blank might be accepted or we need think about update
the availility zone settings to avoid blank 

**Why is this needed**:

**Comment by ramineni** [comment]
underlying cloud (in our case Openstack) , do allow spaces while defining nova AZ/flavor name, multiple issues reported , node initializing fails in such cases.

Labels affected: topology.kubernetes.io/zone, node.kubernetes.io/instance-type

Eg: https://github.com/kubernetes/cloud-provider-openstack/pull/1213#issuecomment-757008618
https://github.com/kubernetes/cloud-provider-openstack/issues/1379

could we add support to allow spaces, or need a workaround or doc update we cant support spaces as valid identifier
@dims Any thoughts on this?

**Comment by dims** [comment]
@ramineni probably best to doc that we can't support spaces for these labels. I don't think there is any room to relax the validation.

**Comment by jichenjc** [comment]
based on feedback, I will close this one, thanks @dims @ramineni ~
