### ISSUE TITLE
Autoscaling e2e test for k8s 1.19 will fail 

### ISSUE THREAD

**Issue by krzysied** [kubernetes/kubernetes#98219]
**Which jobs are failing**:
N/A. There are only tests for head version running.

**Which test(s) are failing**:
 [HPA] Horizontal pod autoscaling (scale resource: Custom Metrics from Stackdriver) .*

**Since when has it been failing**:
 11/30/20

**Testgrid link**:
N/A. There are only tests for head version running.

**Reason for failure**:
Missing cherr-pick.

There was https://github.com/kubernetes/kubernetes/pull/94609 that changed the RunKubectl method. https://github.com/kubernetes/kubernetes/pull/94823 fix the issue in the head version. https://github.com/kubernetes/kubernetes/pull/94609 was [cherry-picked to 1.19](https://github.com/kubernetes/kubernetes/pull/96434), however the https://github.com/kubernetes/kubernetes/pull/94823 was not. This broke autoscaling e2e tests for 1.19.

**Anything else we need to know**:

**Comment by liggitt** [comment]
cc @julianvmodesto

**Comment by julianvmodesto** [comment]
Ack my bad :( will cherry-pick for 1.19

**Comment by julianvmodesto** [comment]
/close

Fixed by https://github.com/kubernetes/kubernetes/pull/98493
