### ISSUE TITLE
Rolling updates interfere with Pod Topology Spread Constraints

### ISSUE THREAD

**Issue by roizentner** [kubernetes/kubernetes#98215]
**Background**:
We define Pod Topology Spread Constraints on our Deployment (labeled `app: app1`), as follows:
>       topologySpreadConstraints:
>       - maxSkew: 1
>         topologyKey: kubernetes.io/hostname
>         whenUnsatisfiable: DoNotSchedule
>         labelSelector:
>           matchLabels:
>             app: app1

The deployment is defined with 5 replicas.

**What happened**:
Triggering a rolling update on the running deployment will sometimes result in a skewed spread, not honoring the maxSkew=1.
Our theory is that the scheduler "sees" the old pods when deciding how to spread the new pods over nodes. When the old nodes are eventually terminated, we sometimes see three pods in node-1, two pods in node-2 and none in node-3.

**What you expected to happen**:
The maxSkew value in Pod Topology Spread Constraints should always be honored.

**How to reproduce it (as minimally and precisely as possible)**:
It reproduces randomly, so it takes a few attempts until reproduced.
I'm running `kubectl rollout restart deployment <deployment-name>` a few times until it reproduces.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.7
- Cloud provider or hardware configuration: self deployed cluster with kubeadm on on-premises VMs (vmware)
- OS (e.g: `cat /etc/os-release`): CentOS 7
- Kernel (e.g. `uname -a`): 3.10.0-1160.6.1.el7.x86_64
- Other: cluster consists of 3 master nodes which also act as workers

**Comment by zhanghe9702** [comment]
from source code comments, `A constraint is considered "Unsatisfiable" for an incoming pod if and only if every possible node assigment for that pod would violate "MaxSkew" on some topology.` @roizentner , in your case, node-1(3) - node-2(2) = 1 don't violate this rule

**Comment by roizentner** [comment]
> from source code comments, `A constraint is considered "Unsatisfiable" for an incoming pod if and only if every possible node assigment for that pod would violate "MaxSkew" on some topology.` @roizentner , in your case, node-1(3) - node-2(2) = 1 don't violate this rule

@zhanghe9702, in my case, node-1(3) - node-3(0) = 3 and node-2(2) - node-3(0) = 2, both considered a violation.

**Comment by zhanghe9702** [comment]
i think ,   node-1(3)/node-2(2)/node-3(0) just one of satisfiable cases , node-1(3)/node-2(1)/node-3(1) also satisfiable

**Comment by Huang-Wei** [comment]
@roizentner This case may possibly happen and is actually a general scale-down / rolling update problem - choosing which replicas to delete is controlled by controller-manager instead of scheduler, so controller manager may not have the context to choose the most optimal replicas to remove.

Back to this issue, in particular 5-replicas on 3 nodes, the chances to result in a violated distribution should be very rare. I tried ~10 times in latest code, but no luck to reproduce.

1. Could you paste the output of `k get pod -o wide -w` when you're able to reproduce? (start the command before performing rolling update, and stop until the update is complete)
2. Also, I'm suspicious you have a non-default setting on `maxSurge` or(and) `maxUnavailable`. If so, could you change it to the following settings and retry?
    ```yaml
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    ```

**Comment by ahg-g** [comment]
One hack to avoid this race condition between the old and new ReplicaSet is to update the topology-spread selector with each deployment update:

The pod template could look like the following, with each update to the deployment, change the version:

`
metadata:                                                                                                                                                                                                     
    labels:                                                                                                                                                                                                     
      app: app1
      version: v1                                                                                                                                                                                             
  spec:                       
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: app1
            version: v1
`

**Comment by roizentner** [comment]
@Huang-Wei, thank you for the reply.
> 1. Could you paste the output of `k get pod -o wide -w` when you're able to reproduce? (start the command before performing rolling update, and stop until the update is complete)

This time it took quite a few attempts to reproduce. I have noticed that this is more easily reproduced when the cluster nodes are almost out of available resources (e.g. other pods requesting almost all the cpu the nodes have). Attached is the output you asked for (I removed the RESTARTS, IP, NOMINATED NODE and READINESS GATES columns for better readability).
Close to the end of the output you should be able to see that the 5 running pods are spread as follows:
```
app-1-65b59b6969-kkgkm   kdpipva-1
app-1-65b59b6969-w85km   kdpipva-2
app-1-65b59b6969-5j7wp   kdpipva-3
app-1-65b59b6969-9c565   kdpipva-3
app-1-65b59b6969-cbfrp   kdpipva-3
```
[get-pods-output.txt](https://github.com/kubernetes/kubernetes/files/5862029/get-pods-output.txt)


> 2. Also, I'm suspicious you have a non-default setting on `maxSurge` or(and) `maxUnavailable`. If so, could you change it to the following settings and retry?
>    ```yaml
>    strategy:
>      rollingUpdate:
>        maxSurge: 1
>        maxUnavailable: 1
>      type: RollingUpdate
>    ```
You were right. Both maxSurge and maxUnavailable are set to 50%.
Using your suggested values, I wasn't able to reproduce the issue. What does this mean? Could this lead help resolve the issue?

**Comment by roizentner** [comment]
@ahg-g I love your idea!
Is there a way to dynamically set a label's value?
I mean, if I run `kubectl scale` or `kubectl set image` for example, that would trigger a rolling update so I would need to set the selector's new value simultaneously somehow. Is there a way to do that?

**Comment by ahg-g** [comment]
> I mean, if I run `kubectl scale` or `kubectl set image` for example, that would trigger a rolling update so I would need to set the selector's new value simultaneously somehow. Is there a way to do that?

You can pause the deployment using `kubectl rollout pause deployment.v1.apps/<deployment-name>`, then 
make the changes you want, like setting a new scale, image or updating pod labels and pod-topology selectors, then resume: `kubectl rollout resume deployment.v1.apps/<deployment-name>` 

See [pausing and resuming a deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#pausing-and-resuming-a-deployment)

**Comment by roizentner** [comment]
> > 2. Also, I'm suspicious you have a non-default setting on `maxSurge` or(and) `maxUnavailable`. If so, could you change it to the following settings and retry?
> >    ```yaml
> >    strategy:
> >      rollingUpdate:
> >        maxSurge: 1
> >        maxUnavailable: 1
> >      type: RollingUpdate
> >    ```
> 
> You were right. Both maxSurge and maxUnavailable are set to 50%.
> Using your suggested values, I wasn't able to reproduce the issue. What does this mean? Could this lead help resolve the issue?

@Huang-Wei just a quick update: after changing all of our services to use the values you suggested for maxSurge and maxUnavailable, we are still encountering this issue. It is less frequent, but is still there. Any other suggestions?

**Comment by alisharifi76** [comment]
> One hack to avoid this race condition between the old and new ReplicaSet is to update the topology-spread selector with each deployment update:
> 
> The pod template could look like the following, with each update to the deployment, change the version:
> 
> ```
> metadata:                                                                                                                                                                                                     
>     labels:                                                                                                                                                                                                     
>       app: app1
>       version: v1                                                                                                                                                                                             
>   spec:                       
>     topologySpreadConstraints:
>       - maxSkew: 1
>         topologyKey: kubernetes.io/hostname
>         whenUnsatisfiable: DoNotSchedule
>         labelSelector:
>           matchLabels:
>             app: app1
>             version: v1
> ```

It still may cause deadlock when we rollout restart manually, is it possible to use hash of replicaSet for the version label automatically?

**Comment by roim** [comment]
Having the same issue (https://stackoverflow.com/questions/66510883/k8s-pod-topology-spread-is-not-respected-after-rollout). I'm considering running a descheduler (which can deschedule pods violating topology spread) to mitigate this.

**Comment by Alexander-Bartosh** [comment]
At certain moment in time the skew will be proper.
But when the pods that are to be removed will be removed the skew might be skewed :)
Essentially you are facing the limitation described here:

[Scaling down a Deployment may result in imbalanced Pods distribution.](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/)
One simple workaround I apply is **scale it down + restart/deploy + scale it up.**

Then the skew is perfectly fine!

**Comment by dbmathis** [comment]
The following might be of interest to those in this thread.

My cluster and topology is:
`master/449d1d0f-8e51-49d0-8759-41dcd8d64450:~$ k get nodes -o wide --show-labels | grep  windows | awk -F' |=' '{print $1 " " $17 " " $48}'
3ebcdcd1-d647-4814-a14d-66ca3bd85313 172.42.129.8 az2
41300042-c376-42e9-b7bb-d40f2330f18e 172.42.129.7 az2
92db06e7-1258-417f-9bd7-e8644059aa7b 172.42.129.6 az1
9cd0d589-f959-4117-8c01-a1b0eb5d931e 172.42.129.9 az3`
