### ISSUE TITLE
Scheduler should evict pods to honor Pod Disruption Budgets

### ISSUE THREAD

**Issue by roizentner** [kubernetes/kubernetes#98214]
**Background**
Our product consists of several deployments (apps), each with its own `app` label.
Each deployment has its own number of pods/replicas.
Our solution requires at least **one** pod of each app running at all times to work properly.
We want to achieve high-availability, even in the case of a node failure.
We've been hoping Pod Disruption Budgets with minAvailable=1 will help us achieve this.

**What happened**:
With all PDBs in place (one for each selector `app=x`), we aggressively shut down one of the nodes, making sure it was running a pod belonging to a deployment with only 1 replica. We also make sure that the other nodes can't schedule all the downed node's pods due to insufficient resources.
The single replica pod stays pending since the available nodes have insufficient resources.

**What you expected to happen**:
Scheduler should have evicted a pod belonging to a deployment with 2 or 3 replicas, making resources available for pods belonging to other deployments that don't have any replicas running at the moment.
All PDBs should be honored.

**How to reproduce it (as minimally and precisely as possible)**:
In a 3-node cluster with 2 cpu per node, define two deployments:
1. app1 with 5 replicas and 850m cpu requests (two pods will get scheduled in node-1, two in node-2 and one in node-3)
2. app2 with 1 replica and 500m cpu requests (the pod will get scheduled in node-3 because the other nodes don't have enough cpu resources to fulfil the request).

Define two PDBs, specifying the app label as selector and minAvailable=1.

Shut down the node that's running app2 pod.
NOTE: You can use your own numbers and hardware specs to achieve this state.

![image](https://user-images.githubusercontent.com/24566282/105161776-6cf1df00-5b1a-11eb-8f9b-38ae7c554976.png)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.7
- Cloud provider or hardware configuration: self deployed cluster with kubeadm on on-premises VMs (vmware)
- OS (e.g: `cat /etc/os-release`): CentOS 7
- Kernel (e.g. `uname -a`): 3.10.0-1160.6.1.el7.x86_64
- Other: cluster consists of 3 master nodes which also act as workers

**Comment by roizentner** [comment]
@Huang-Wei you helped me in the other issue I've created, maybe you can shed some light here as well?

**Comment by michaelgugino** [comment]
If you must always have 1 of something, you should deploy 2.

If you want pod-2 to cause another pod to be evicted, pod priorities can preempt a lower priority pod to make room for pod-2.  PDBs are supported best-effort there, so your scenario should work provided pod-2 has a higher priority than pod-1.

I don't think deployments or replicasets support a 'degrading priority' where the first pod has the highest priority of the set, and the rest have a lower priority (this would be a cool feature).  To achieve something similar today, you could have 2 deployments for each application.  1 deployment each with 1 pod (or 2 pods if you want to use PDBs), and the balance of the workload in an 'overflow' deployment.

**Comment by roizentner** [comment]
Hi @michaelgugino,
Thank you for the insights. I have some comments:
> If you must always have 1 of something, you should deploy 2.

Says who? For the sake of argument, let's change "always" to _almost always_.
I can live with a few seconds of 0 of something, as long as some mechanism makes an effort to minimize that time.

> If you want pod-2 to cause another pod to be evicted, pod priorities can preempt a lower priority pod to make room for pod-2. PDBs are supported best-effort there, so your scenario should work provided pod-2 has a higher priority than pod-1.

I am aware of pod priorities, but in my case, all deployments are born equal. I want 1 of each and can't afford giving up on one for another.

> I don't think deployments or replicasets support a 'degrading priority' where the first pod has the highest priority of the set, and the rest have a lower priority (this would be a cool feature). To achieve something similar today, you could have 2 deployments for each application. 1 deployment each with 1 pod (or 2 pods if you want to use PDBs), and the balance of the workload in an 'overflow' deployment.

I also thought of this idea but it would be a nightmare to maintain a double deployment yaml of each of our services.

**Comment by michaelgugino** [comment]
@roizentner Some of what I wrote is for posterity.  Others might view this issue and need a work around, so I tried to put out some ideas to make things work as they are today.

I think the priority/preemption is the correct way to solve this issue.  You're asking the scheduler to prioritize some workload over another workload, this abstraction already exists.  What is missing from this abstraction is some kind of prioritization budget.  Something like:

```
# replicaset.spec
priorityBudget:
  amount: 1
  class: Super-Critical
  default: normal
```

So the replicaset controller would apply Super-Critical to a single pod, and 'normal' to all the others.

I think the scheduler also supports webhooks and plugins, so that might be an option as well.

**Comment by roizentner** [comment]
> @roizentner Some of what I wrote is for posterity.

@michaelgugino, your ideas are great and could help others, I agree.
I just wanted to let you know that they are not suitable for my scenario.

I love your proposed solution! Wish it could be developed...

**Comment by michaelgugino** [comment]
I think scheduling should be included on this issue as well.  Something like this might be possible today with scheduling plugins.

/sig scheduling
