### ISSUE TITLE
dockershim: auto-detect and match the Docker cgroup driver

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#98222]
**What would you like to be added**:

auto-detect and match the docker service cgroup driver in dockershim.

https://github.com/kubernetes/kubernetes/pull/97764#discussion_r556595741
https://github.com/kubernetes-sigs/cluster-api/issues/866#issuecomment-478728323

dockershim is already detecting the cgroup driver using `docker info`:
https://github.com/pacoxu/kubernetes/blob/71d70f7a8320e971892cc92b29baefc37fcf8152/pkg/kubelet/dockershim/docker_service.go#L262-L272

but it errors out if the user did not configure a matching cgroup driver for the kubelet.
https://github.com/pacoxu/kubernetes/blob/71d70f7a8320e971892cc92b29baefc37fcf8152/pkg/kubelet/dockershim/docker_service.go#L274

proposing that we match the drivers and print a message that we are doing that.

this is not a breaking change, since if the drivers did not match previously one would get an error and a driver mismatch is not usable.

**Why is this needed**:

over the years, too many users have reported failures because of this low level detail leaking in their user space. we do document that cgroup drivers must be matching between the CR and the kubelet, but it feels we can improve the UX one step further by simply matching the drivers.

**Comment by neolit123** [comment]
cc @derekwaynecarr @pacoxu

**Comment by pacoxu** [comment]
sounds good. will work on it if this is expected behavior

**Comment by neolit123** [comment]
created PR for kubeadm to remove the detection from there if the kubelet PR merges:
https://github.com/kubernetes/kubernetes/pull/99647

**Comment by neolit123** [comment]
UPDATE: this change might not be possible / so simple:
https://github.com/kubernetes/kubernetes/pull/98357#issuecomment-790949603

**Comment by neolit123** [comment]
logged https://github.com/kubernetes/kubernetes/issues/99808
which is what we really want.

**Comment by neolit123** [comment]
/milestone clear
untagging 1.21,.

**Comment by neolit123** [comment]
^ closing in favor of the new ticket.
