### ISSUE TITLE
Kubelet cAdvisor API not working on windows nodes

### ISSUE THREAD

**Issue by perithompson** [kubernetes/kubernetes#98235]
**What happened**:
When browsing to the cadvisor metrics API on a Windows node running contained, no metrics are returned about the underlying pods and containers. 

```
curl -X GET https://<windows-node-ip>:10250/metrics/cadvisor --header "Authorization: Bearer $TOKEN" --insecure

# HELP cadvisor_version_info A metric with a constant '1' value labeled by kernel version, OS version, docker version, cadvisor version & cadvisor revision.
# TYPE cadvisor_version_info gauge
cadvisor_version_info{cadvisorRevision="",cadvisorVersion="",dockerVersion="",kernelVersion="10.0.17763.1697",osVersion="Windows Server 2019 Standard"} 1
# HELP container_scrape_error 1 if there was an error while getting container metrics, 0 otherwise
# TYPE container_scrape_error gauge
container_scrape_error 0
``` 

However running this on a Linux Node on the same cluster returns correctly

```
curl -X GET https://<linux-node-ip>:10250/metrics/cadvisor --header "Authorization: Bearer $TOKEN" --insecure
...
# HELP container_network_transmit_packets_total Cumulative count of packets transmitted
# TYPE container_network_transmit_packets_total counter
container_network_transmit_packets_total{container="",id="/",image="",interface="antrea-gw0",name="",namespace="",pod=""} 551458 1611166320528
container_network_transmit_packets_total{container="",id="/",image="",interface="eth0",name="",namespace="",pod=""} 2.226427e+06 1611166320528
container_network_transmit_packets_total{container="",id="/",image="",interface="genev_sys_6081",name="",namespace="",pod=""} 332835 1611166320528
...
```

**What you expected to happen**:
Expect the container metrics to be returned.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a windows node using the containerd runtime (using kubernetes-sig/image-builder) and join cluster.
- Browse to the nodes cadvisor endpoint :10250/metrics/cadvisor or api/proxy/node/<node-name>/metrics/cadvisor endpoint

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.19.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Windows 2019 Standard LTSC
- Kernel (e.g. `uname -a`): 10.0.17763.1697  
- Install tools:
- Others: 
      containerd://1.4.3

**Comment by perithompson** [comment]
I will add some more detail to this later but wanted to get this filed

/sig windows
@jayunit100

**Comment by bobbypage** [comment]
/retitle Kubelet cAdvisor API not working with containerd on windows node

**Comment by jsturtevant** [comment]
This also occurs with docker.  If you turn up the kubelet logs to -v=5 you will get:

```
I found many errors `I0107 00:30:40.123717    2448 cri_stats_provider.go:208] Unable to find cadvisor stats for "b7d6fb98845bea2f821770103a76b243f6d115a60c294eca16d2c1f45c5ba65d"

**Comment by jsturtevant** [comment]
fyi - some metrics for Windows can be found at: `/stats/summary` and there are also some at `/metrics/resource`

**Comment by perithompson** [comment]
Thanks @jsturtevant  I didn't know about /stats/summary, that's interesting though! I think the Prometheus operator checks cadvisor so it would be good to get that endpoint fixed? Unless we need to change the prom operator of course!

**Comment by perithompson** [comment]
/retitle Kubelet cAdvisor API not working on windows nodes

**Comment by perithompson** [comment]
@jsturtevant updated the title to reflect this is a windows node issue not just containerd

**Comment by jsturtevant** [comment]
>  think the Prometheus operator checks cadvisor so it would be good to get that endpoint fixed? Unless we need to change the prom operator of course!

I don't have enough context to know how/if we should fix this. Would need to dig into it more. I know that cadvisor doesn't run on windows.  There is another project called https://github.com/prometheus-community/windows_exporter that is the windows replacement.

It also looks like the `metrics/resource` endpoint is preferred long term: https://github.com/prometheus-operator/kube-prometheus/issues/745

**Comment by jsturtevant** [comment]
Looked into this alittle and found that there is cadvisor "shim" for Windows which is why we get some information like `kernel` number and such in the stats.  

The Windows specific cadvisor overrides: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cadvisor/cadvisor_windows.go

The "shim" that does the work: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/winstats/winstats.go#L19

It would be _possible_ to either get more metrics but the overall desire is to use the cri api: https://github.com/google/cadvisor/issues/1394 (and many linked prs from that).  Do you have a specify use case that `/stats/summary` and `/metrics/resource` don't meet?

I also found https://github.com/kubernetes/kubernetes/issues/68522#issuecomment-724928827 which outlines the current state and goals from sig-node.  It would be awesome if someone wanted to connect with the right folks and help move this forward from a Windows perspective :smile:

**Comment by jsturtevant** [comment]
There is now a kep for moving all of the stats to the cri: https://github.com/kubernetes/enhancements/pull/2364

**Comment by perithompson** [comment]
Thanks for this @jsturtevant I don't have any specific examples, but one thing I have noticed is memory allocation to pods seems to be missing from wavefront, but that could be their collector, I will test with prometheus and come back.  I think I've seen similar with prometheus previously but its been a while!
