### ISSUE TITLE
Unable to retrieve init container logs

### ISSUE THREAD

**Issue by mgoltzsche** [kubernetes/kubernetes#98236]
**What happened**:
Apparently init container logs cannot be retrieved after the Pod terminated.
While a Pod is running I can fetch an init container's logs successfully.
It seems that init containers are deleted on (successful) termination (and the logs with them).
However I'd like to fetch their logs directly after the Pod terminated.

**What you expected to happen**:
After running a (short-lived) Pod I'd like to be able to fetch its init container's logs - at least directly afterwards.
In case init containers are deleted on termination by design the documentation should mention that (e.g. [here](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#detailed-behavior)).
Are init containers deleted on (successful) termination by design?

**How to reproduce it (as minimally and precisely as possible)**:
The problem manifests itself as follows (assuming `mypod` specifies the init container `myinitcontainer` and a regular container and successfully terminated seconds ago):
```sh
$ kubectl logs mypod -c myinitcontainer
unable to retrieve container logs for containerd://61a93aa17bfb193bc125b151ec643c85a9edbcd6fd993f5f1164f2015f6361a3
```
At that point `kubectl logs mypod` still provides the logs of the main container correctly.

**Anything else we need to know?**:
I am using kind 0.9.0 / Kubernetes 1.19.1 with containerd 1.4.0

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.1
- Cloud provider or hardware configuration: kind 0.9.0
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04 host with docker 19.03
- Kernel (e.g. `uname -a`): 5.4.0-62-generic Ubuntu
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ArshiAAkhavan** [comment]
any update on this issue?

i do have the same problem. i cant retrieve logs from my completed/error pods

**Comment by mgoltzsche** [comment]
FWIW I don't have this problem anymore on Kubernetes 1.20 and/or with kind. Though not sure what caused it in the first place.

**Comment by fr6nco** [comment]
Facing the same issue with kubernetes version v1.24.2 and containerd v1.6.6. It was a short lived pod too, a job that runs once a day and takes a few seconds to finish. No idea how to tackle down the issue tho.
