### ISSUE TITLE
proposal: add a helper function to convert labels.selector to v1.NodeSelector

### ISSUE THREAD

**Issue by ggaaooppeenngg** [kubernetes/kubernetes#98256]
**What would you like to be added**:
A converter that converts selector to v1.NodeSelectorRequirement
**Why is this needed**:
In fact `k8s.io/apimachinery/pkg/labels.Selector` has the same syntax as `k8s.io/api/core/v1.NodeSelector`

Example:

```Go
  func convertOperator(sop selection.Operator) v1.NodeSelectorOperator {
          switch sop {
          case selection.In:
                  return v1.NodeSelectorOpIn
          case selection.NotIn:
                  return v1.NodeSelectorOpNotIn
          case selection.Exists:
                  return v1.NodeSelectorOpExists
          case selection.DoesNotExist:
                  return v1.NodeSelectorOpDoesNotExist
          case selection.GreaterThan:
                  return v1.NodeSelectorOpGt
          case selection.LessThan:
                  return v1.NodeSelectorOpLt
          default:
                  return v1.NodeSelectorOpIn
          }
  }

  func convertSelector(s string) v1.NodeSelector {
          selector, err := labels.Parse(s)
          if err != nil {
                  panic(err)
          }

          nreqs := []v1.NodeSelectorRequirement{}
          reqs, _ := selector.Requirements()
          for _, req := range reqs {
                  nreq := v1.NodeSelectorRequirement{
                          Key:      req.Key(),
                          Operator: convertOperator(req.Operator()),
                          Values:   req.Values().List(),
                  }
                  nreqs = append(nreqs, nreq)
          }
          nodeSelector := v1.NodeSelector{
                  NodeSelectorTerms: []v1.NodeSelectorTerm{
                          {
                                  MatchExpressions: nreqs,
                          },
                  },
          }
          return nodeSelector
  }
```

**Comment by yliaog** [comment]
what is the use case for this converter?

**Comment by ggaaooppeenngg** [comment]
A string like `k1=v1,k2=v2` or `k1 in (v1,v2)` can be parsed as a labels selector, but there is no way to parse this string as a node selector. In some cases like command line and web ui, it can be nice to have a helper function to utilize the abbreviation instead of giving a full JSON format selector.

**Comment by yliaog** [comment]
which repo do you plan to add this helper function?  or it's even better if you could open a pull request

**Comment by ggaaooppeenngg** [comment]
I am not sure where to add this helper function, maybe add it in apis/core/helper/helpers.go, if it's ok I can send a pr.

**Comment by mauriciovasquezbernal** [comment]
https://github.com/kubernetes/kubernetes/commit/7093b10416f6073f3e0531b8cc1d71aa5d9ed3d2 introduced `NodeSelectorAsSelector()`, I suppose having its `SelectorAsNodeSelector()` counterpart makes sense. If you folks agree I can open a PR to implement this function.
