### ISSUE TITLE
kubectl alpha debug node does not work on tainted nodes

### ISSUE THREAD

**Issue by ymmt2005** [kubernetes/kubernetes#98253]
**What happened**:

`kubectl alpha debug node` does not work for nodes with NoExecute taints.

```console
$ kubectl alpha debug node/mynode -it --image=ubuntu
Creating debugging pod node-debugger-mynode-mnn2s with container debugger on node mynode.
Error from server (NotFound): pods "" not found
```

We have several types of Node hardware, and some of them are tainted
to keep away normal pods.

**What you expected to happen**:

A debug pod is created with tolerations for the taints.

**How to reproduce it (as minimally and precisely as possible)**:

1. Add a NoExecute taint to a node
2. Run `kubectl alpha debug node` on the node

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.7
- OS (e.g: `cat /etc/os-release`):
    ```
    NAME="Flatcar Container Linux by Kinvolk"
    ID=flatcar
    ID_LIKE=coreos
    VERSION=2605.11.0
    VERSION_ID=2605.11.0
    BUILD_ID=2021-01-08-2026
    PRETTY_NAME="Flatcar Container Linux by Kinvolk 2605.11.0 (Oklo)"
    ANSI_COLOR="38;5;75"
    HOME_URL="https://flatcar-linux.org/"
    BUG_REPORT_URL="https://issues.flatcar-linux.org"
    FLATCAR_BOARD="amd64-usr"
    ```
- Kernel (e.g. `uname -a`): `Linux hostname 5.4.87-flatcar #1 SMP Fri Jan 8 19:54:07 -00 2021 x86_64 Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz GenuineIntel GNU/Linux`
- Install tools: CKE
- Network plugin and version (if this is a network-related bug): Coil v2.0.5
- Others:

**Comment by wawa0210** [comment]
This is my test feedback

```
[root@10-7-106-201 ~]# kubectl get no
NAME           STATUS   ROLES                  AGE   VERSION
10-7-106-201   Ready    control-plane,master   33d   v1.20.1
10-7-106-202   Ready    <none>                 33d   v1.20.1
10-7-106-203   Ready    <none>                 33d   v1.20.1
[root@10-7-106-201 ~]# kubectl  cordon 10-7-106-201
node/10-7-106-201 cordoned
[root@10-7-106-201 ~]# kubectl get no
NAME           STATUS                     ROLES                  AGE   VERSION
10-7-106-201   Ready,SchedulingDisabled   control-plane,master   33d   v1.20.1
10-7-106-202   Ready                      <none>                 33d   v1.20.1
10-7-106-203   Ready                      <none>                 33d   v1.20.1
[root@10-7-106-201 ~]# kubectl debug node/10-7-106-201 -it --image=busybox:1.29.3
Creating debugging pod node-debugger-10-7-106-201-4s55q with container debugger on node 10-7-106-201.
If you don't see a command prompt, try pressing enter.
/ # hostname
10-7-106-201
/ # exit
```

@ymmt2005 This scenario cannot be reproduced in version 1.20. Can you describe your test steps in detail?

**Comment by ymmt2005** [comment]
@wawa0210 
Our nodes have `NoExecute` taint like this:

```
kubectl taint nodes mynode mykey=myvalue:NoExecute
```

I updated the description.  Sorry for the lack of clarity.

**Comment by wawa0210** [comment]
```
[root@10-7-106-201 ~]# kubectl get no
NAME           STATUS   ROLES                  AGE   VERSION
10-7-106-201   Ready    control-plane,master   34d   v1.20.1
10-7-106-202   Ready    <none>                 34d   v1.20.1
10-7-106-203   Ready    <none>                 34d   v1.20.1
[root@10-7-106-201 ~]# kubectl taint no 10-7-106-201  node-role.kubernetes.io/master:NoSchedule
node/10-7-106-201 tainted
[root@10-7-106-201 ~]# kubectl get no 10-7-106-201 -o yaml | grep -i -3 'taint'
  podCIDR: 10.244.0.0/24
  podCIDRs:
  - 10.244.0.0/24
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
status:
[root@10-7-106-201 ~]# kubectl debug node/10-7-106-201 -it --image=busybox:1.29.3
Creating debugging pod node-debugger-10-7-106-201-m6tjx with container debugger on node 10-7-106-201.
If you don't see a command prompt, try pressing enter.
/ # hostname
10-7-106-201
/ # exit
```

It seems that it still cannot be reproduced. Is our testing process consistent?

@ymmt2005

**Comment by ymmt2005** [comment]
@wawa0210 Could you please change `NoSchedule` to `NoExecute`?

I'm considering this might be the right behavior for Nodes with `NoExecute` taint, though...

**Comment by wawa0210** [comment]
I reproduced it, if the node has `NoExecute`, this problem does occur~~ This should be the expected behavior once the node is marked as `NoExecute`. Maybe we need to give clear tips, the current error message is not clear

/assign

**Comment by verb** [comment]
This is great, thanks for bringing this to our attention, @ymmt2005.

@wawa0210 I think we should always just generate the node debugging pod with the appropriate `NoExecute` tolerations to execute on the node. The user has asserted to us that they want to execute something on this node, and taints aren't access control. We've already got the `Node` when we're generating the pod, so it should be simple to generate the tolerations.

There's a second problem in the error message:

```
$ kubectl alpha debug node/mynode -it --image=ubuntu
Creating debugging pod node-debugger-mynode-mnn2s with container debugger on node mynode.
Error from server (NotFound): pods "" not found
```

Something went wrong that caused kubectl to attempt to fetch an empty pod name. This bug may affect other use cases as well.

**Comment by wawa0210** [comment]
>  We've already got the `Node` when we're generating the pod, so it should be simple to generate the tolerations.

Got it, I will try to submit a pr to fix this issue

**Comment by chymy** [comment]
>if there is at least one un-ignored taint with effect `NoExecute` then the pod will be evicted from the node (if it is already running on the node), and will not be scheduled onto the node (if it is not yet running on the node).

ref: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/

you can add `-v` test, will print log:
```sh
kubectl alpha debug node/mynode -it --image=ubuntu -v 8
```

You can see that pod has been scheduled to that node, then vist the pod from apiserver, but pod can't tolerate that node, so it will be deleted.
```sh
#kubectl get po -w
node-debugger-mynode-wr8tt   0/1     Pending   0          0s    <none>        mynode   <none>           <none>
node-debugger-mynode-wr8tt   0/1     Terminating   0          0s    <none>        mynode   <none>           <none>
node-debugger-mynode-wr8tt   0/1     Terminating   0          0s    mynode   mynode   <none>           <none>
node-debugger-mynode-wr8tt   0/1     Terminating   0          1s    mynode   mynode   <none>           <none>
node-debugger-mynode-wr8tt   0/1     Terminating   0          1s    mynode   mynode   <none>           <none>
```

so print:
```
Error from server (NotFound): pods "" not found
```

**Comment by wawa0210** [comment]
> > if there is at least one un-ignored taint with effect `NoExecute` then the pod will be evicted from the node (if it is already running on the node), and will not be scheduled onto the node (if it is not yet running on the node).

Even if the node is tainted by `NoExecute`, we should add tolerance to let the pod run normally. Therefore, I think your pr cannot fix this issue. I will try to submit pr to fix

**Comment by verb** [comment]
@chymy That makes sense, thanks for debugging. So it looks like we need a better error message [here](https://github.com/kubernetes/kubernetes/blob/release-1.20/staging/src/k8s.io/kubectl/pkg/cmd/debug/debug.go#L669)
