### ISSUE TITLE
Consider marking pre-go-module k8s.io/client-go versions as retracted

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#98267]
**What would you like to be added**:

**Why is this needed**:

Current k8s.io/client-go releases are tagged as v0.x.y corresponding to kubernetes 1.x.y (e.g. v0.20.2, corresponding to kubernetes v1.20.2).

`go get k8s.io/client-go` fetches the latest semantic version. That is either v1.5.1 (corresponding to kubernetes 1.5) or v11.0.0+incompatible (corresponding to kubernetes 1.14). Releasing new k8s.io/client-go versions as v1.x.y is misleading, since they do not guarantee go signature compatibility. Releasing new k8s.io/client-go versions as `v<X>.0.0` > v11 is not possible without renaming the module to `k8s.io/client-go/v<X>`

go 1.16 will allow marking versions as retracted (xref https://play-with-go.dev/retract-module-versions_go116_en/)

We should investigate marking the obsolete v1 stream versions as retracted so that the latest version of k8s.io/client-go would resolve to the latest releases (matching other k8s.io/... libraries).

From https://pkg.go.dev/k8s.io/client-go?tab=versions, that would appear to be:

* v1.5.1 – Feb 8, 2017
* v1.5.0 – Oct 23, 2016
* v1.4.0 – Oct 17, 2016
* v11.0.0+incompatible – Mar 13, 2019
* v10.0.0+incompatible – Dec 4, 2018
* v9.0.0+incompatible – Oct 4, 2018
* v9.0.0-invalid+incompatible – Sep 27, 2018
* v8.0.0+incompatible – Jun 28, 2018
* v7.0.0+incompatible – Mar 27, 2018
* v6.0.0+incompatible – Dec 7, 2017
* v5.0.1+incompatible – Oct 16, 2017
* v5.0.0+incompatible – Oct 16, 2017
* v4.0.0+incompatible – Jul 28, 2017
* v4.0.0-beta.0+incompatible – Jul 7, 2017
* v3.0.0+incompatible – Jul 5, 2017
* v3.0.0-beta.0+incompatible – Mar 31, 2017
* v2.0.0+incompatible – Feb 13, 2017
* v2.0.0-alpha.1+incompatible – Dec 20, 2016

TODO:
- [x] verify the `retract` directives don't cause more problems for go versions < 1.16
- [x] verify a release retracting itself is permitted (
  - explicitly described as a use case in https://play-with-go.dev/retract-module-versions_go116_en/
  - tested with go1.16beta1 and https://github.com/liggitt/retract20210126
- [x] verify the format for retracting an "+incompatible" major version tag (tag is "v2.0.0", module version is "v2.0.0+incompatible", which do we use?)
  - `go mod tidy` on `go1.16beta1` complains about retracting a `v2.0.0` version saying the tag is not compatible. Must retract `v2.0.0+incompatible`, etc

/area code-organization
/cc @sttts

**Comment by liggitt** [comment]
retractions are only read from the go.mod file of latest semver release

I *think* we would create a v1.5.2 release identical to v1.5.1 with one additional commit of a go.mod file containing retractions of all legacy versions (including v1.5.2):
```
retract (
 v1.5.2
 v1.5.1
 v1.5.0
 v1.4.0
 v11.0.0+incompatible
 v10.0.0+incompatible
 v9.0.0+incompatible
 v9.0.0-invalid+incompatible
 v8.0.0+incompatible
 v7.0.0+incompatible
 v6.0.0+incompatible
 v5.0.1+incompatible
 v5.0.0+incompatible
 v4.0.0+incompatible
 v4.0.0-beta.0+incompatible
 v3.0.0+incompatible
 v3.0.0-beta.0+incompatible
 v2.0.0+incompatible
 v2.0.0-alpha.1+incompatible
)
```

We'll validate that this works as expected on a test repo prior to doing it on client-go

**Comment by liggitt** [comment]
This should not be done prior to release of go1.16

**Comment by liggitt** [comment]
pushed a test repo at https://github.com/liggitt/retract20210126/tags containing identical pre-module tags / go.mod presence to k8s.io/client-go

**Comment by liggitt** [comment]
1. Consumed that test repo using go1.15 and verified the behavior matches what we currently see for client-go (selects v11.0.0+incompatible):

```
go version
go version go1.15 darwin/amd64

go clean -modcache

GOPROXY=direct go get github.com/liggitt/retract20210126
go: github.com/liggitt/retract20210126 upgrade => v11.0.0+incompatible

cat go.mod
...
require github.com/liggitt/retract20210126 v11.0.0+incompatible
```

2. pushed a v1.5.2 tag to the test repo matching the proposed approach for k8s.io/client-go

```
# base on the latest valid semver for the v1 stream - v1.5.1
git checkout -b retract_non_module v1.5.1

# ... add go.mod file containing only retract directives, indicating it was constructed with go1.16
git add go.mod && git commit -m "Retract non-module versions"

# tag as v1.5.2
git tag v1.5.2
git push origin v1.5.2
```

The result: https://github.com/liggitt/retract20210126/blob/v1.5.2/go.mod

3. Checked version preference when consumed from go1.15 and go1.16beta1:

go1.15 now prefers v1.5.2 (not particularly worse than preferring v11.0.0+incompatible which doesn't work at all with preferred versions of `k8s.io/{api,apimachinery}`):

```
go version
go version go1.15 darwin/amd64

go clean -modcache

GOPROXY=direct go get github.com/liggitt/retract20210126
go: downloading github.com/liggitt/retract20210126 v1.5.2

cat go.mod
...
require github.com/liggitt/retract20210126 v1.5.2 // indirect
```

go1.16 now prefers v0.20.2:

```
go version
go version go1.16beta1 darwin/amd64

go clean -modcache

GOPROXY=direct go get github.com/liggitt/retract20210126
go: downloading github.com/liggitt/retract20210126 v0.20.2
go get: added github.com/liggitt/retract20210126 v0.20.2

cat go.mod
...
require github.com/liggitt/retract20210126 v0.20.2 // indirect
```

**Comment by liggitt** [comment]
explicitly requesting a retracted version with go1.16beta1 is allowed, but complains:

```
go version
go version go1.16beta1 darwin/amd64

GOPROXY=direct go get github.com/liggitt/retract20210126@v11.0.0+incompatible
go: downloading github.com/liggitt/retract20210126 v11.0.0+incompatible
go: warning: github.com/liggitt/retract20210126@v11.0.0+incompatible: retracted by module author: pre-module versions are obsolete
go: run 'go get github.com/liggitt/retract20210126@latest' to switch to the latest unretracted version

go run .
v11.0.0
```

running the suggested command gets the latest unretracted version correctly:
```
go get github.com/liggitt/retract20210126@latest
go get: downgraded github.com/liggitt/retract20210126 v11.0.0+incompatible => v0.20.2

go run .
v0.20.2
```

explicitly requesting a retracted version with go1.15 works fine without complaint:
```
go version
go version go1.15 darwin/amd64

GOPROXY=direct go get github.com/liggitt/retract20210126@v11.0.0+incompatible
go: downloading github.com/liggitt/retract20210126 v11.0.0+incompatible

go run .
v11.0.0
```

**Comment by liggitt** [comment]
I'm happy with the results of the investigation, once go1.16 is released we can revisit this, verify the results still hold, and plan if we want to proceed

**Comment by liggitt** [comment]
/cc @sttts 

would like a second set of eyes on the approach and test I ran. if you approve, I'd like to do this once go1.16 is released and we re-verify the test with the final go behavior.

**Comment by liggitt** [comment]
I'd also be curious if you think we should base the v1.5.2 containing retractions (including retracting itself) on v1.5.1 or v11.0.0.

Basing on v11.0.0 would preserve existing behavior for go versions prior to 1.16 (which currently fetch `v11.0.0+incompatible`) if an unqualified `go get k8s.io/client-go` is run

**Comment by BenTheElder** [comment]
tiny note: I expect a pretty strong push to ship go 1.16 in kubernetes immediately following release, for darwin/arm64 support, if nothing else 🙃 
It looks like 1.16 is expected to release this month, so we probably will get 1.21 with 1.16, this looks like a very nice change to ship along with that.

**Comment by sttts** [comment]
Did this change in rc1?
```
$ GOPROXY=direct go get github.com/liggitt/retract20210126
go: downloading github.com/liggitt/retract20210126 v1.5.2
go: warning: github.com/liggitt/retract20210126@v1.5.2: retracted by module author: pre-module versions are obsolete
go: to switch to the latest unretracted version, run:
	go get github.com/liggitt/retract20210126@latest
```

**Comment by sttts** [comment]
With `@latest` it works.

**Comment by liggitt** [comment]
hmm... still working for me with go1.16rc1:

```
$ go version
go version go1.16rc1 darwin/amd64

$ more go.mod
module dep

go 1.15

$ GOPROXY=direct go get github.com/liggitt/retract20210126

go: downloading github.com/liggitt/retract20210126 v0.20.2
go get: added github.com/liggitt/retract20210126 v0.20.2
```

**Comment by dims** [comment]
go1.16 is now out!!

**Comment by liggitt** [comment]
Verified the experiment still works identically on the released version of go1.16, and lets an unqualified `go get ...` call fetch the desired version.

@sttts also verified it was working for him; he already had v1.5.2 explicitly referenced in his go.mod file. Once that was removed, the expected version was auto-selected.

I think this is the remaining question: should we base the v1.5.2 `k8s.io/client-go` containing retractions (including retracting itself) on v1.5.1 or v11.0.0?

* Basing on v11.0.0 would result in identical content for go versions prior to 1.16 doing an unqualified go get k8s.io/client-go (which currently resolve to v11.0.0+incompatible)
* Basing on v1.5.1 would return dramatically different content (packages were nested under a v1.5 subdirectory - https://github.com/kubernetes/client-go/tree/release-1.5)

Since unqualified `go get k8s.io/client-go` calls don't work today for either version (v11.0.0 of client-go doesn't work with master of k8s.io/api and k8s.io/apimachinery), I don't think there's a big functional difference in using v1.5.2 content for v1.5.1, but there would certainly be *more* errors returned by an old go version fetching and expecting to use v1.5.2.

@sttts @deads2k @lavalamp, would like to hear your thoughts.

I'd like to resolve this question and plan to make the proposed change mid-week next week.

**Comment by liggitt** [comment]
kubernetes/client-go#932 shows what it would look like to create a v1.5.2 based on v1.5.1 that retracts the pre-module versions.

**Comment by deads2k** [comment]
marking retracted makes sense to me. Given how old both versions are, I don't think it matters which one we choose to base the retracted 1.5.2 on

**Comment by dims** [comment]
+1 to plan to make the proposed change mid-week next week

**Comment by liggitt** [comment]
after discussing with @lavalamp and @deads2k, using the v1.5.1 content as the base is the least disruptive for dependency management tools other than go modules that were still pointing to very old versions.

https://github.com/kubernetes/client-go/pull/932 contains the proposed change

**Comment by liggitt** [comment]
resolved in https://github.com/kubernetes/client-go/releases/tag/v1.5.2
