### ISSUE TITLE
CSI Migration Metrics

### ISSUE THREAD

**Issue by Jiawei0227** [kubernetes/kubernetes#98279]
**What would you like to be added**:

Currently for CSI migration feature, there is no metric for both in-tree/CSI that can indicate the call is a migration enabled feature or not.

**Why is this needed**:
This can be hard for the support of this feature. From both usage and stability perspective. It would be good if we can add something in the current metrics.

/sig storage
/cc @msau42 @xing-yang @saad-ali

**Comment by Jiawei0227** [comment]
I am wondering if there is any discussion already exist for the metrics for CSI migration?

The only thing I can find in the CSI migration KEP is:

> If migration is on for that plugin, the test framework will inspect kube-controller-manager and kubelet metrics to make sure that the CSI driver is servicing the operations. This enables the test suite to programatically confirm migration status. The framework must also observe through metrics that none of the in-tree code is being called.
> 
> The above is done by checking that no in-tree plugin code is emitting metrics when migration is on. We will also confirm that metrics are being emitted in general by confirming the existence of an indicator metric.

I am wondering if adding a field in the current CSI sidecar operation metric to indicate migration is something worth doing..

**Comment by mattcary** [comment]
I put this on the agenda for the migration meeting tomorrow. If there's no objections or interesting discussion we should go ahead and start adding things to the sidecars, IMHO.

**Comment by msau42** [comment]
/triage accepted

Conclusion was metrics would be good to have. Adding a new field to the the existing storage_operations metric may be sufficient. Ideally we should make changes to existing metrics this release (1.21) as we're making some other breaking changes to the metric. https://github.com/kubernetes/kubernetes/pull/98089

**Comment by Jiawei0227** [comment]
To sum up, three aspects of the metrics we have done:

1. Add migrated field to storage_operation_duration_seconds
  - PR: https://github.com/kubernetes/kubernetes/pull/99050
2. Add migrated field to csi_sidecar_operations_seconds
  - https://github.com/kubernetes-csi/csi-lib-utils/pull/77
  - https://github.com/kubernetes-csi/external-provisioner/pull/560
  - https://github.com/kubernetes-csi/external-attacher/pull/292
  - https://github.com/kubernetes-csi/external-resizer/pull/138
3. Add new metric csi_kubelet_operations_seconds to kubelet
  - https://github.com/kubernetes/kubernetes/pull/98979
