### ISSUE TITLE
Additional security group rules removed with NLB

### ISSUE THREAD

**Issue by robisoh88** [kubernetes/kubernetes#98278]
**What happened**:

This happens when a new rule to ALL Traffic is manually added (or existing rule is modified to ALL traffic) with a description set to the k8s.io/rule/nlb/...=<nlb name>. Once a new worker node is added, it will delete the rule, but in addition it will delete other rules that have ALL traffic configured even though the description is not set to the nlb generated string. this will cause downtime as it can remove security group rule that allow communication between node and api-server.

**What you expected to happen**:
If a new rule is added (or an existing rule is modified) to a worker node SG including a description which match a string of that are generated automatically [[e.g.](https://github.com/kubernetes/kubernetes/blob/release-1.15/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L70)], when a new node is added it should remove any rule it identifies that do not belong ONLY if the rule has a matching description. 

**How to reproduce it (as minimally and precisely as possible)**:

*Prereq*: 
Created a deployment and Loadbalancer service with 'nlb' annotation.

Normal operation:
1. First tested by adding security group rule (on the Worker node SG) that allow all traffic to its SG ID with description "Cluster Traffic allow all".
2. Then deleted a worker node. This did not remove any security group rules as expected.

Controller Manager Logs:

    W0120 15:35:46.650390       1 aws.go:1639] the instance i-xxxxxxxxxxxxxx is terminated
    ...
    I0120 15:35:51.426171       1 controller_utils.go:167] Recording Removing Node ip-172-31-40-189.us-east-2.compute.internal from Controller event message for node ip-172-31-40-189.us-east-2.compute.internal

Reproducible scenario:
1. Add a rule to worker node SG that allow ALL traffic to a CIDR with description "kubernetes.io/rule/nlb/client=<NLB NAME HERE>". In addition add a rule that allow ALL traffic to itself with a description "Cluster Traffic allow all" (for example)

SG rules example: 

    Type                  Protocol         Port range        Source              Description - optional

    All traffic          All                 All             172.32.0.0/16   kubernetes.io/rule/nlb/client=<NLB NAME HERE>
    All traffic          All                 All             sg-xxxxxxx      Cluster Traffic allow all

     ^ two rules created by me

    Custom TCP            TCP               31678          172.32.0.0/16     kubernetes.io/rule/nlb/client=<NLB NAME HERE>
    Custom TCP            TCP               31678          0.0.0.0/0         kubernetes.io/rule/nlb/client=<NLB NAME HERE>
    Custom ICMP -IPv4  Dest unreachable  fragmentation     0.0.0.0/0         kubernetes.io/rule/nlb/client=<NLB NAME HERE>
                                           required, 
                                           DF flag set         

     ^ three rules automatically created from controller

2. Terminate a worker node so it launched a new node. This time is will remove both rules that were added manually including the rule w/out kubernetes generated description. 

Controller Manager Logs:

    W0120 15:45:47.335031       1 aws.go:1639] the instance i-xxxxxxxxxxxxxx is terminated
    ...
    I0120 15:46:14.236866       1 aws.go:3218] Removing security group ingress: sg-xxxxxxxxxxxxxxxx [{  IpProtocol: "-1",  IpRanges: [{      CidrIp: "172.31.0.0/16",      Description: "kubernetes.io/rule/nlb/client=<NAME OF NLB>"    }],  UserIdGroupPairs: [{      Description: "Cluster Traffic allow all",      GroupId: "sg-xxxxxxxxxxxxxx",      UserId: "xxxxxxxxxxxxxxxx"    }]}]

**Anything else we need to know?**:
- Tested on 1.15, 1.16, 1.18. 

- Further tests: 

Test 1
1. This time testing with ALL TCP rule with k8s.io description along with a another rule of ALL TCP w/out k8s description. This is to test if it will delete rules without matching description as long as the protocol (ALL TCP) matches.
 2. Once new worker node is ready, it deletes the all TCP rule w/ description along with the all TCP rule w/out description.
 
Test 2
1. Now testing with Custom TCP type on a random port with k8s description along with Custom TCP type w/ custom port range w/out k8s description.
2. In this case, it will not delete the custom tcp type rule w/out k8s description and only delete the rule that was manually added with k8s description

**Environment**:
- Kubernetes version (use `kubectl version`): N/A
- Cloud provider or hardware configuration: EKS
- OS (e.g: `cat /etc/os-release`): EKS Optimized AMI latest
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
> Cloud provider or hardware configuration: EKS

please report to EKS first.
if they confirm that this is an upstream k8s bug, re-open this ticket.

/sig cloud-provider
/area provider/aws
/close

**Comment by robisoh88** [comment]
Reported to EKS and they believe this is an upstream bug.
