### ISSUE TITLE
ExportOptions was planed to removal in 1.18 while still used now

### ISSUE THREAD

**Issue by lala123912** [kubernetes/kubernetes#98289]
https://github.com/kubernetes/kubernetes/blob/88c652c154c1e3e68699a3e6d57a752a35e156ea/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L438
```
// ExportOptions is the query options to the standard REST get call.
// Deprecated. Planned for removal in 1.18.
type ExportOptions struct {
	TypeMeta `json:",inline"`
	// Should this value be exported.  Export strips fields that a user can not specify.
	// Deprecated. Planned for removal in 1.18.
	Export bool `json:"export" protobuf:"varint,1,opt,name=export"`
	// Should the export be exact.  Exact export maintains cluster-specific fields like 'Namespace'.
	// Deprecated. Planned for removal in 1.18.
	Exact bool `json:"exact" protobuf:"varint,2,opt,name=exact"`
}
```

ExportOptions  seems to be still useful in the project. If that is true, the notes here will bring side effects when developers deal with the code.

**Comment by lala123912** [comment]
@deads2k Could you double check whether the comments here can be deleted or not? If the comments is deprecated， I would like to update it. Thank you.

**Comment by pacoxu** [comment]
Option `--export ` for `kubectl get` is removed in 1.19 after #88649 . It is deprecated in #73787.

**Comment by deads2k** [comment]
> @deads2k Could you double check whether the comments here can be deleted or not? If the comments is deprecated， I would like to update it. Thank you.

Rather than remove the comments, we will complete the removal of the deprecated API entirely.  I have opened https://github.com/kubernetes/kubernetes/pull/98312 to complete the removal of this long deprecated API.
