### ISSUE TITLE
build kubernetes binaries failed

### ISSUE THREAD

**Issue by JoshuaAndrew** [kubernetes/kubernetes#98294]
**What happened**:
```
joshua:kubernetes joshua$ build/run.sh make all KUBE_BUILD_PLATFORMS=linux/amd64 GOLDFLAGS=""
build/../build/common.sh: line 579: conditional binary operator expected

joshua:kubernetes joshua$ build/run.sh make all KUBE_BUILD_PLATFORMS=linux/amd64 GOLDFLAGS="-s -w"
build/../build/common.sh: line 579: conditional binary operator expected

joshua:kubernetes joshua$ build/run.sh make all KUBE_BUILD_PLATFORMS=linux/amd64 
build/../build/common.sh: line 579: conditional binary operator expected
```
**What you expected to happen**:

build kubernetes binaries successfully

**How to reproduce it (as minimally and precisely as possible)**:
```
joshua:kubernetes joshua$ build/run.sh make all KUBE_BUILD_PLATFORMS=linux/amd64 GOLDFLAGS=""
build/../build/common.sh: line 579: conditional binary operator expected

joshua:kubernetes joshua$ build/run.sh make all KUBE_BUILD_PLATFORMS=linux/amd64 GOLDFLAGS="-s -w"
build/../build/common.sh: line 579: conditional binary operator expected

joshua:kubernetes joshua$ build/run.sh make all KUBE_BUILD_PLATFORMS=linux/amd64 
build/../build/common.sh: line 579: conditional binary operator expected
```

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`):  k8s v1.18.15+ , k8s v1.19.7 , k8s v1.20.2+
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):   my host environment: MacOS
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by JoshuaAndrew** [comment]
@dims

**Comment by JoshuaAndrew** [comment]
@dims 
this issue caused by [97699](https://github.com/kubernetes/kubernetes/pull/97699) 
or my usage is incorrect ？

```
 # use GOLDFLAGS only if it is set explicitly.
  if [[ -v GOLDFLAGS ]]; then
    docker_run_opts+=(
      --env "GOLDFLAGS=${GOLDFLAGS:-}"
    )
  fi
```

**Comment by BenTheElder** [comment]
I think -v is a relatively new flag (bash 4.2?), but `build/run.sh` should run this in a container with recent bash ...

`build/run.sh --version` shows `5.0.3(1)-release (x86_64-pc-linux-gnu)` @ 44f8fcfe948 and `v1.20.2`.

On my own machine:
```
build/run.sh make all KUBE_BUILD_PLATFORMS=linux/amd64 GOLDFLAGS="" KUBE_VERBOSE=0
```

Works fine 🤔 

There's a different way to implement this test for earlier versions, but we shouldn't need to.

On the off chance something is funny with your kube-build image can you possibly:
- delete images from your local docker (to ensure you don't have some strange version of any of the base images somehow?)
- `make clean`
- try again?

And **before** you do:
- What does `build/run.sh --version` show?
- What is your host environment?

**Comment by JoshuaAndrew** [comment]
@BenTheElder 

```
joshua:kubernetes joshua$ build/run.sh --version
build/../build/common.sh: line 579: conditional binary operator expected
joshua:kubernetes joshua$ 
joshua:kubernetes joshua$ 
joshua:kubernetes joshua$ make clean
build/../build/common.sh: line 579: conditional binary operator expected
make: *** [clean] Error 2
joshua:kubernetes joshua$ build/make-clean.sh 
build/../build/common.sh: line 579: conditional binary operator expected
joshua:kubernetes joshua$ build/run.sh make all KUBE_BUILD_PLATFORMS=linux/amd64 GOLDFLAGS="" KUBE_VERBOSE=0
build/../build/common.sh: line 579: conditional binary operator expected
```

**Comment by JoshuaAndrew** [comment]
@BenTheElder  you are right, the root cause of the problem has been found.

my macOS High Sierra 10.13.2 (17c88)  bash version is 3.2 , after ```brew install  --build-from-source  bash```,  my bash version is bash version 5.1.4

everything works fine ^_^

We should record it in the development documentation

**Comment by JoshuaAndrew** [comment]
@BenTheElder

**Comment by JoshuaAndrew** [comment]
@BenTheElder Thank you very much for your timely advice.

**Comment by JoshuaAndrew** [comment]
As @BenTheElder suggested:  ```we should have a method to check and require a minimum bash version, probably that needs to be called somewhere here```

**Comment by BenTheElder** [comment]
I just realized that might be a bit ambiguous: we *do* have a method that checks this, we're either not calling it early enough here or we're not setting the right value. we should fix that.

**Comment by JoshuaAndrew** [comment]
@BenTheElder  Agree with you.
