### ISSUE TITLE
In the kubelet flags validity check, is it reasonable to use klog.Fatal？

### ISSUE THREAD

**Issue by yangjunmyfm192085** [kubernetes/kubernetes#98292]
**What would you like to be added**:
In the flag verification of the kubelet component, if the verification fails, call klog.fatal directly to print the log and exit. At this time, all trace information will be printed out,  I think it  is no need.
For example，Kubelet execution with an unknown flag --hh， then print
...........
F0122 13:11:28.521365   30211 server.go:156] unknown flag: --hh
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc000010001, 0xc000d639c0, 0x40, 0x40)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x730afe0, 0xc000000003, 0x0, 0x0, 0xc000d515e0, 0x6f6950f, 0x9, 0x9c, 0x411000)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:975 +0x19b
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0x730afe0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc00004b580, 0x1, 0x1)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:732 +0x16f
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).print(...)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:714
k8s.io/kubernetes/vendor/k8s.io/klog/v2.Fatal(...)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1482
k8s.io/kubernetes/cmd/kubelet/app.NewKubeletCommand.func1(0xc000903340, 0xc00000e070, 0x1, 0x1)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:156 +0x147b
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc000903340, 0xc00000e070, 0x1, 0x1, 0xc000903340, 0xc00000e070)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000903340, 0x165c75cc9fe893dd, 0x730aa00, 0x409085)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958 +0x375
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
main.main()
        _output/local/go/src/k8s.io/kubernetes/cmd/kubelet/kubelet.go:41 +0xe5

goroutine 6 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x730afe0)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf

goroutine 95 [select]:
k8s.io/kubernetes/vendor/go.opencensus.io/stats/view.(*worker).start(0xc000113450)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.opencensus.io/stats/view/worker.go:154 +0x105
created by k8s.io/kubernetes/vendor/go.opencensus.io/stats/view.init.0
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.opencensus.io/stats/view/worker.go:32 +0x57

goroutine 102 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4a94b40, 0x4f31fe0, 0xc000ae93b0, 0x1, 0xc0000c2120)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x149
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x4a94b40, 0x12a05f200, 0x0, 0xc000b67901, 0xc0000c2120)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Forever(0x4a94b40, 0x12a05f200)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:81 +0x4f
created by k8s.io/kubernetes/vendor/k8s.io/component-base/logs.InitLogs
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/logs/logs.go:58 +0x8a

**Why is this needed**:
Similar to other components, no trace information is printed.
Or only the current trace is printed.

For example，Kubelet execution with an unknown flag --hh， then print
E0122 13:27:14.369473   15611 server.go:156] unknown flag: --hh
or
F0122 13:19:37.055696    3781 server.go:156] unknown flag: --hh
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc000010000, 0xc0009d4e40, 0x40, 0x40)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1027 +0xb9
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x730afe0, 0xc000000003, 0x0, 0x0, 0xc0008b2000, 0x6f6950f, 0x9, 0x9c, 0x411000)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:976 +0x19b
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0x730afe0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc000c12a10, 0x1, 0x1)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:732 +0x16f
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).print(...)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:714
k8s.io/kubernetes/vendor/k8s.io/klog/v2.Fatal(...)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1483
k8s.io/kubernetes/cmd/kubelet/app.NewKubeletCommand.func1(0xc00053fb80, 0xc00000e070, 0x1, 0x1)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:156 +0x147b
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc00053fb80, 0xc00000e070, 0x1, 0x1, 0xc00053fb80, 0xc00000e070)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00053fb80, 0x165c763e5ea79f2b, 0x730aa00, 0x409085)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958 +0x375
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
main.main()
        _output/local/go/src/k8s.io/kubernetes/cmd/kubelet/kubelet.go:41 +0xe5

**Comment by wawa0210** [comment]
/assign 
I can research it and give feedback
