### ISSUE TITLE
How to change the service account token mount file permission inside a pode kubernetes

### ISSUE THREAD

**Issue by jobin-AT** [kubernetes/kubernetes#98308]
hi team,

we are trying to change the default permission of service account token that is mounted inside pods, by default the permission is 644  other users also get read access to the token so we need to reduce the risk from our containers 

please let me know if we have any  solution for this issue

**Comment by pacoxu** [comment]
/kind support
Refer to https://stackoverflow.com/questions/43544370/kubernetes-how-to-set-volumemount-user-group-and-file-permissions and https://kubernetes.io/docs/concepts/storage/volumes/. Hope it can help

**Comment by neolit123** [comment]
the stackoverflow answer seems valid.

/close

**Comment by neolit123** [comment]
for more questions please use: https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
