### ISSUE TITLE
Kubeadm documentation: note in docs that the cert renew command requires some restarts

### ISSUE THREAD

**Issue by mowings** [kubernetes/kubernetes#98310]
**What happened**:
Used `kubeadm alpha certs renew all` command on the masters in my ha cluster. `show-expiration` showed all certs renewed. 

Unfortunately, when the expiration date rolled around, the kube-api servers stopped responding with "certificate expired error". This was easily fixed by restarting the kube-api server on all masters. However, the need to do this was not noted n the documentation. I also restarted the kube-controllermanager and kube-scheduler processes for good measure.

**What you expected to happen**:
I expected that the cluster would continue to function and the cert changes would be picked up automatically. 

**How to reproduce it (as minimally and precisely as possible)**:

See above

**Anything else we need to know?**:

**All this really requires is a note in the documentation for kubeadm cert renew.**

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.4
- Cloud provider or hardware configuration: bare metal (various configurations)
- OS (e.g: `cat /etc/os-release`): ubuntu 18.04
- Kernel (e.g. `uname -a`): 4x
- Install tools: kubeadm

**Comment by neolit123** [comment]
> Kubernetes version (use kubectl version): 1.16.4

note, this version is out of support.

> Unfortunately, when the expiration date rolled around, the kube-api servers stopped responding with "certificate expired error". This was easily fixed by restarting the kube-api server on all masters. However, the need to do this was not noted n the documentation. I also restarted the kube-controllermanager and kube-scheduler processes for good measure.

version 1.16 and newer of the renew command prints you a note that you should restart:
https://github.com/kubernetes/kubernetes/blob/release-1.16/cmd/kubeadm/app/cmd/alpha/certs.go#L53-L54

you can log an issue in kubernetes/website for the docs or even better, send a PR to add this note.

thanks
/close
