### ISSUE TITLE
"kubeadm init" does not auto-detect CRI-O as documentation states

### ISSUE THREAD

**Issue by jdwx** [kubernetes/kubernetes#98335]
**What happened**:

"kubeadm init" fails looking for docker when CRI-O is installed:

```
# kubeadm init --config /tmp/kubeadm.yaml
W0124 05:38:16.668343  110816 kubelet.go:200] cannot automatically set CgroupDriver when starting the Kubelet: cannot execute 'docker info -f {{.CgroupDriver}}': executable file not found in $PATH
[init] Using Kubernetes version: v1.20.0
[preflight] Running pre-flight checks
[preflight] WARNING: Couldn't create the interface used for talking to the container runtime: docker is required for container runtime: exec: "docker": executable file not found in $PATH
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
error execution phase preflight: docker is required for container runtime: exec: "docker": executable file not found in $PATH
To see the stack trace of this error execute with --v=5 or higher
```

**What you expected to happen**:

kubeadm init completes successfully.

**How to reproduce it (as minimally and precisely as possible)**:

Use CRI-O as the container runtime, and follow the directions on this page: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

Use a minimal /tmp/kubeadm.yaml, which is needed only for the cgroupDriver: systemd setting.

**Anything else we need to know?**:

At https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-runtime the documentation states:

> If you don't specify a runtime, kubeadm automatically tries to detect an installed container runtime by scanning through a list of well known Unix domain sockets.

However, it does not seem to do this.  Instead, specifying the socket manually is required:

```kubeadm init --config /tmp/kubeadm.yaml --cri-socket=/var/run/crio/crio.sock```

even though /var/run/crio/crio.sock is on the list ofwell-known Unix domain sockets provided.  (And none of the others exist.)

It's not clear if this is a documentation error or a bug in the software.

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:

Bare metal.

- OS (e.g: `cat /etc/os-release`):

NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

- Kernel (e.g. `uname -a`):

Linux 5.4.0-64-generic #72-Ubuntu SMP Fri Jan 15 10:27:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
I fixed a similar issue in #97847 and kubernetes/kubeadm#2364.
A work-around there is to `remove /var/run/docker-shim.sock and /var/run/docker.sock`.
Would you try?

**Comment by jdwx** [comment]
Neither socket file exists.  Docker is not installed on this system.

**Comment by neolit123** [comment]
can you help us debug this?

```
# install latest go

git clone --depth=1 https://github.com/kubernetes/kubernetes.git
cd kuberenetes
git checkout release-1.20

# add this line
#   klog.Infof("---> found sockets: %v", foundCRISockets)
# here: https://github.com/kubernetes/kubernetes/blob/release-1.20/cmd/kubeadm/app/util/runtime/runtime.go#L217

make all WHAT=cmd/kubeadm
# use the kubeadm binary from _output/local/go...

# show us the output of `kubeadm init`
```

/area kubeadm
/sig cluster-lifecycle
/priority awaiting-more-evidence

we don't have e2e tests for CRI-O, but we know for sure that containerd detection works.

**Comment by jdwx** [comment]
OK, that tracked down the issue.

I did as you requested, with these changes and quickly learned that that function was never being called.

Then I figured out what was supposed to call it (SetNodeRegistrationDynamicDefaults in util/config/initconfiguration.go) and determined that it was skipped if cfg.CRISocket is set.  So I tracked that back to this in the kubeadm.yaml file:

```
nodeRegistration:
  criSocket: /var/run/dockershim.sock
```

Which was generated by:

```
# kubeadm config print init-defaults >/tmp/kubeadm.yaml
# cat >>/tmp/kubeadm.yaml <<ZZZ
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
ZZZ
```

So it seems there's a discrepancy between what's printed by init-defaults aren't in sync with the defaults used by init.

(If that's intentional, then there may be a documentation gap here: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#configure-cgroup-driver-used-by-kubelet-on-control-plane-node because it specifies that config file must be used, but the excerpt provided is insufficient. 

It links here:  https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#config-file

That page says to use kubeadm config print to get the defaults.  But to describe that, it links to the top of this page: https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-config/

Scrolling down to "kubeadm config print init-defaults" 

There's some stuff there about sensitive values being replaced with placeholders, which is probably important but not relevant as criSocket doesn't meet that definition.

So while I think I understand the issue here enough to work around it, I do think it's not clear how to get a config that matches what "kubeadm init" alone would do but adds the (now-required) KubeletConfiguration with cgroupDriver as the docs instruct.

(At a minimum, it seems necessary to remove advertiseAddress and criSocket.  But those sensitive tokens are now bothering me too.)

**Comment by jdwx** [comment]
For this case, the relevant line appears to be:

https://github.com/kubernetes/kubernetes/blob/release-1.20/cmd/kubeadm/app/cmd/config.go#L214

**Comment by neolit123** [comment]
thanks for testing.

> So it seems there's a discrepancy between what's printed by init-defaults and the defaults used by init.

there is no discrepancy, there is the concept of dynamic and static defaulting.
`config print` gives you the static defaulting just to showcase what fields there are in the kubeadm config.

on init/join runtime, if the socket field is empty kubeadm will run the dynamic defaulting.

> kubeadm config print init-defaults >/tmp/kubeadm.yaml

note, nowhere in the docs does it say that you should pass the output of this command directly to "kubeadm init/join"
it says:
>> The default configuration can be **printed** out using the kubeadm config print command.

printed, but not used directly.
[some of the values are just populated so that it passes validation](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-config/#cmd-config-print-init-defaults)
it will include IPs, tokens and sockets that are the default values but will not work for all cases.

> https://github.com/kubernetes/kubernetes/blob/release-1.20/cmd/kubeadm/app/cmd/config.go#L214

this is intended - re: static defaulting.

if you wish to clarify something in the docs please open a PR in the kubernetes/website repository.
/close

**Comment by jdwx** [comment]
If the values printed by "config print init-defaults" are not the defaults used by init -- which these are not -- then that command is extremely misleading to new users such as myself.  Those sound more like examples than defaults.

But I can see that it is unlikely that I will change your mind about that.

Entirely separate from that, if Docker is deprecated, then using it as a default value (as shown in the line I quoted) is an odd choice.

**Comment by neolit123** [comment]
> If the values printed by "config print init-defaults" are not the defaults used by init -- which these are not -- then that command is extremely misleading to new users such as myself. Those sound more like examples than defaults.

i don't disagree - these are the static defaults and should be used as examples that should not be passed directly to kubeadm without user editing them out.

in fact the bootstrap token static defaults make your cluster insecure until that token expires.

clarification PRs for this page are welcome:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-config/#cmd-config-print-init-defaults

> Entirely separate from that, if Docker is deprecated, then using it as a default value (as shown in the line I quoted) is an odd choice.

our latest survey said that around 60% of kubeadm users are still using docker.
i can see us defaulting it to containerd in the future.
