### ISSUE TITLE
Does V1.20.2 not support Redhat8.3?

### ISSUE THREAD

**Issue by zzguang520** [kubernetes/kubernetes#98331]
**What happened**:
kubelet service can't start on redhat8.3

**What you expected to happen**:
worker on redhat8.3

**How to reproduce it (as minimally and precisely as possible)**:
first step:dnf install -y kubeadm kubelet kubelet containerd.io-1.4.3
next step: containerd config default > /etc/containerd/config.toml
3rd step: systemctl start containerd 
4th step: systemctl start kubelet

error info:
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: activating (auto-restart) (Result: exit-code) since Sat 2021-01-23 14:18:29 CST; 1s ago
     Docs: https://kubernetes.io/docs/
  Process: 210435 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS (code=exited, status>
 Main PID: 210435 (code=exited, status=255)

details:
-- Logs begin at Fri 2021-01-22 16:05:23 CST, end at Sat 2021-01-23 14:20:42 CST. --
Jan 23 14:20:32 node2 kubelet[210718]: F0123 14:20:32.009578  210718 server.go:198] failed to load Kubelet config file /var/lib/kubelet/con>
Jan 23 14:20:32 node2 kubelet[210718]: goroutine 1 [running]:
Jan 23 14:20:32 node2 kubelet[210718]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc000010001, 0xc0000be840, 0xfb, 0x14d)
Jan 23 14:20:32 node2 kubelet[210718]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/k>
Jan 23 14:20:32 node2 kubelet[210718]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x70d14c0, 0xc000000003, 0x0, 0x0, 0xc000>
Jan 23 14:20:32 node2 kubelet[210718]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/k>
Jan 23 14:20:32 node2 kubelet[210718]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0x70d14c0, 0xc000000003, 0x0, 0x0, 0x>
Jan 23 14:20:32 node2 kubelet[210718]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/k>
Jan 23 14:20:32 node2 kubelet[210718]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).print(...)
Jan 23 14:20:32 node2 kubelet[210718]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/k>
Jan 23 14:20:32 node2 kubelet[210718]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.Fatal(...)
Jan 23 14:20:32 node2 kubelet[210718]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/k>
Jan 23 14:20:32 node2 kubelet[210718]: k8s.io/kubernetes/cmd/kubelet/app.NewKubeletCommand.func1(0xc00016adc0, 0xc00004e090, 0x3, 0x3)
Jan 23 14:20:32 node2 kubelet[210718]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app>
Jan 23 14:20:32 node2 kubelet[210718]: k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc00016adc0, 0xc00004e090, 0x3, >
Jan 23 14:20:32 node2 kubelet[210718]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.c>
Jan 23 14:20:32 node2 kubelet[210718]: k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00016adc0, 0x165cc825f30e94b6>
Jan 23 14:20:32 node2 kubelet[210718]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.c>
Jan 23 14:20:32 node2 kubelet[210718]: k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
Jan 23 14:20:32 node2 kubelet[210718]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.c>
Jan 23 14:20:32 node2 kubelet[210718]: main.main()
Jan 23 14:20:32 node2 kubelet[210718]:         _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/kubelet.go:41 +0xe5
Jan 23 14:20:32 node2 kubelet[210718]: goroutine 6 [chan receive]:
Jan 23 14:20:32 node2 kubelet[210718]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x70d14c0)
Jan 23 14:20:32 node2 kubelet[210718]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/k>
Jan 23 14:20:32 node2 kubelet[210718]: created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
Jan 23 14:20:32 node2 kubelet[210718]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/k>
Jan 23 14:20:32 node2 kubelet[210718]: goroutine 87 [select]:
Jan 23 14:20:32 node2 kubelet[210718]: k8s.io/kubernetes/vendor/go.opencensus.io/stats/view.(*worker).start(0xc000112cd0)
Jan 23 14:20:32 node2 kubelet[210718]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/go.openc>
Jan 23 14:20:32 node2 kubelet[210718]: created by k8s.io/kubernetes/vendor/go.opencensus.io/stats/view.init.0
Jan 23 14:20:32 node2 kubelet[210718]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/go.openc>
Jan 23 14:20:32 node2 kubelet[210718]: goroutine 107 [select]:
Jan 23 14:20:32 node2 kubelet[210718]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4a77d40, 0x4f11e00, 0xc000>
Jan 23 14:20:32 node2 kubelet[210718]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/a>
Jan 23 14:20:32 node2 kubelet[210718]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x4a77d40, 0x12a05f200, 0x0, >
Jan 23 14:20:32 node2 kubelet[210718]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/a>
Jan 23 14:20:32 node2 kubelet[210718]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
Jan 23 14:20:32 node2 kubelet[210718]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/a>
Jan 23 14:20:32 node2 kubelet[210718]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Forever(0x4a77d40, 0x12a05f200)
Jan 23 14:20:32 node2 kubelet[210718]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/a>
Jan 23 14:20:32 node2 kubelet[210718]: created by k8s.io/kubernetes/vendor/k8s.io/component-base/logs.InitLogs
Jan 23 14:20:32 node2 kubelet[210718]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/c>

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
root:~# cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.3 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.3"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.3 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.3:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.3"

root:~# uname -a
Linux node2 4.18.0-193.14.3.el8_2.x86_64 #1 SMP Mon Jul 20 15:02:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

root:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

root:~# cat /etc/containerd/config.toml |grep systemd
    systemd_cgroup = true

**Comment by pacoxu** [comment]
> failed to load Kubelet config file /var/lib/kubelet/con>

Could you check this file first?
by default, the config path should be /var/lib/kubelet/config.yaml

**Comment by neolit123** [comment]
> Jan 23 14:20:32 node2 kubelet[210718]: F0123 14:20:32.009578 210718 server.go:198] failed to load Kubelet config file /var/lib/kubelet/con>

once you install the kubelet on a node it will crashloop until something (e.g. kubeadm) writes the config file.
this is already explained in kubeadm documentation.
so if you run `kubeadm init/join` it should stop failing.

closing as i don't see a bug here.
/close
/remove-kind bug
/kind support
