### ISSUE TITLE
Provide an API interface for dynamically setting the klog log level.

### ISSUE THREAD

**Issue by chymy** [kubernetes/kubernetes#98356]
**What would you like to be added**:
Provide an API interface for dynamically setting the klog log level.
**Why is this needed**:
You can call the interface directly to set the log level without restarting the component.
eg:
```golang
flag.Lookup("v").Value.Set(loglevel)
```

**Comment by neolit123** [comment]
please create this ticket in the kubernetes/klog repository.

/close

**Comment by neolit123** [comment]
actually, sorry i misread this.
you are asking that we should allow users to tell components to dynamically reconfigure log level without a restart.

/reopen
/sig instrumentation
you might get more responses on slack / mailing lists.
https://github.com/kubernetes/community/tree/master/sig-instrumentation#contact

**Comment by ehashman** [comment]
I don't think we're going to do this but pulling in people with more context...

/cc @thockin @DirectXMan12 
can you provide a little more context on how this will look in the logr world?

/priority awaiting-more-evidence

**Comment by logicalhan** [comment]
This is already possible through the debug API (if it's enabled)

`curl -XPUT http://localhost:8001/debug/flags/v --data 10`

**Comment by logicalhan** [comment]
(at least for the apiserver)
