### ISSUE TITLE
Go 1.16: TestHandlePackage fails due to a change in error message

### ISSUE THREAD

**Issue by eclipseo** [kubernetes/kubernetes#98354]
**Which test(s) are failing**:
```
--- FAIL: TestHandlePackage (0.00s)
    main_test.go:139: code:
        package test
        var a = map[string]interface{}{"num1": 9223372036854775807}
        got  test.go:2:40: cannot use 9223372036854775807 (untyped int constant) as int value in map literal (overflows)
        want test.go:2:40: 9223372036854775807 (untyped int constant) overflows int
FAIL
exit status 1
```

**Since when has it been failing**:
Since Go 1.16 beta 1 has been introduced

**Reason for failure**:
This commit https://github.com/golang/go/commit/05568315f2ae8fb86112e63966b46c2dcc8ab6e2 changes the error message:
```
 if err := check.canConvertUntyped(x, target); err != nil { 
 	msg := check.sprintf("cannot use %s as %s value in %s", x, target, context) 
 	code := _IncompatibleAssign 
 	var ierr Error 
 	if errors.As(err, &ierr) { 
 		// Preserve these inner errors, as they are informative. 
 		switch ierr.go116code { 
 		case _TruncatedFloat: 
 			msg += " (truncated)" 
 			code = ierr.go116code 
 		case _NumericOverflow: 
 			msg += " (overflows)" 
 			code = ierr.go116code 
 		} 
 	} 
 	check.error(x.pos(), code, msg) 
 	x.mode = invalid 
 	return 
 }

**Comment by BenTheElder** [comment]
Where are you seeing this? Which file?
 
 Kubernetes really only supports a specific go version for development, but we should certainly fix this. However from your report I can't tell where this is, and a quick search doesn't turn up this test name in the current sources.

**Comment by BenTheElder** [comment]
In fact, I can find this *not* in this repo but only in CSI's outdated vendor of kubernetes https://cs.k8s.io/?q=HandlePackage&i=nope&files=&repos=

I suspect you're referencing that, but this was removed in https://github.com/kubernetes/kubernetes/commit/d187d7effa2794926cc11a5d5dffc9a4d9db5cda#diff-be8a5acec326aa61910578e0afdab2e2412d6a74888cd047d0e72c1d76688fa2

which merged back in 1.19 (1.21 is under development) back in June of last year https://github.com/kubernetes/kubernetes/pull/92212#event-3488608173

**Comment by eclipseo** [comment]
Sorry I am still on 1.18.x, I will try to backport this commit.

**Comment by BenTheElder** [comment]
1.18 is built with go 1.13.15 currently.
I don't think SIG release has any intent to support go 1.16 in release Kubernetes 1.18.

**Comment by eclipseo** [comment]
I have successfully backported the patch. I know I have to update to 1.20 but no timeto do it yet.

Thanks all for your help.
