### ISSUE TITLE
Pods and replicat set dispatching

### ISSUE THREAD

**Issue by GH-Djeff** [kubernetes/kubernetes#98360]
Hello,
I have 3 nodes and 45 pods and replicaset.
Must of them are on node-2.
I would like to have 15 pods per node.
Can you help me with this please ?

Regards,
Djeff

**Comment by pandaamanda** [comment]
3 nodes have same cpu memory configuration? 
you can use `kubectl describe node ` to see the node info to find some different places.

**Comment by GH-Djeff** [comment]
Hello,
All nodes have the same configuration
8 vCPU
8 GB (RAM)
256 GB (vdisk)
One master node and two worker nodes, all untainted.
Here joint the result of the command "kubectl describe node kn1"

[node kn1 description.txt](https://github.com/kubernetes/kubernetes/files/5867444/node.kn1.description.txt)

**Comment by damemi** [comment]
Hi,
Have you considered pod topology spread constraints? https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/

**Comment by manikantavasupalli** [comment]
> Hi,
> Have you considered pod topology spread constraints? https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/

This doc making much sense with the ask.
Instead of zone labelling, you may just need to change topologyKey to "node" so as to distribute the Pods evenly across nodes.

**Comment by damemi** [comment]
> Instead of zone labelling, you may just need to change topologyKey to "node" so as to distribute the Pods evenly across nodes.

`topologyKey` can be any label on the node, for example `kubernetes.io/hostname`, or your custom zone key if you wish
