### ISSUE TITLE
Containers fail to start if memory limit set but memory cgroup not (fully?) enabled

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#9837]
On Debian Jessie, we need to boot with these options:
`GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"`

https://docs.docker.com/installation/ubuntulinux/#memory-and-swap-accounting

Without it though, I can still run docker directly passing memory limits, although I am warned those limits are ignored:
```
docker run -it -m=1024m ubuntu:14.04
WARNING: Your kernel does not support memory limit capabilities. Limitation discarded.
root@7af1efe3ccfd:/#
```

However, kubelet cannot start containers:

```
Jun 16 01:02:07 ip-172-20-0-9 kubelet[11332]: ; Skipping pod "etcd-server-i-480454e2_default"
Jun 16 01:02:07 ip-172-20-0-9 kubelet[11332]: E0616 01:02:07.590762   11332 pod_workers.go:108] Error syncing pod bfaad5678acb9b3625969fe556cd0ee5, skipping: API error (500): Cannot start container bcf563c9e5d1164a7321839c44f5d2385cc73432a7f2258fd841ab0c8fdb85a9: [8] System error: mountpoint for memory not found
Jun 16 01:02:07 ip-172-20-0-9 kubelet[11332]: I0616 01:02:07.590796   11332 event.go:203] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"etcd-server-i-480454e2", UID:"bfaad5678acb9b3625969fe556cd0ee5", APIVersion:"v1", ResourceVersion:"", FieldPath:"implicitly required container POD"}): reason: 'failed' Failed to start with docker id bcf563c9e5d1164a7321839c44f5d2385cc73432a7f2258fd841ab0c8fdb85a9 with error: API error (500): Cannot start container bcf563c9e5d1164a7321839c44f5d2385cc73432a7f2258fd841ab0c8fdb85a9: [8] System error: mountpoint for memory not found
Jun 16 01:02:07 ip-172-20-0-9 kubelet[11332]: I0616 01:02:07.590812   11332 event.go:203] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"etcd-server-i-480454e2", UID:"bfaad5678acb9b3625969fe556cd0ee5", APIVersion:"v1", ResourceVersion:"", FieldPath:""}): reason: 'failedSync' Error syncing pod, skipping: API error (500): Cannot start container bcf563c9e5d1164a7321839c44f5d2385cc73432a7f2258fd841ab0c8fdb85a9: [8] System error: mountpoint for memory not found
Jun 16 01:02:07 ip-172-20-0-9 kubelet[11332]: E0616 01:02:07.593428   11332 manager.go:1464] Failed to create pod infra container: API error (500): Cannot start container 1f1b47b4f29df32504b8b071cec06957e07b8f2c21ad2c5d80b9aa77a8c3d839: [8] System error: mountpoint for memory not found
Jun 16 01:02:07 ip-172-20-0-9 kubelet[11332]: ; Skipping pod "kube-controller-manager-i-480454e2_default"
Jun 16 01:02:07 ip-172-20-0-9 kubelet[11332]: E0616 01:02:07.593444   11332 pod_workers.go:108] Error syncing pod 0bdeeea7537d393e0f6014f0e05ec5d2, skipping: API error (500): Cannot start container 1f1b47b4f29df32504b8b071cec06957e07b8f2c21ad2c5d80b9aa77a8c3d839: [8] System error: mountpoint for memory not found
Jun 16 01:02:07 ip-172-20-0-9 kubelet[11332]: I0616 01:02:07.593478   11332 event.go:203] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"kube-controller-manager-i-480454e2", UID:"0bdeeea7537d393e0f6014f0e05ec5d2", APIVersion:"v1", ResourceVersion:"", FieldPath:"implicitly required container POD"}): reason: 'failed' Failed to start with docker id 1f1b47b4f29df32504b8b071cec06957e07b8f2c21ad2c5d80b9aa77a8c3d839 with error: API error (500): Cannot start container 1f1b47b4f29df32504b8b071cec06957e07b8f2c21ad2c5d80b9aa77a8c3d839: [8] System error: mountpoint for memory not found
```

I haven't been able to track down exactly what is going on here (why Docker can run but we can't - surely they didn't implement the warning client-side!)  Can we / should we ignore memory limits if the kernel can't honor them?

**Comment by dchen1107** [comment]
I believe docker CLI ignore those failures, but remote API doesn't. I reported a similar issue to docker / libcontainer related to swap limit.

**Comment by dchen1107** [comment]
1.1: We decide to check cgroup mount status at kubelet boot time, and report NodeNotReady on failed.

**Comment by dchen1107** [comment]
cc/ @vishh

**Comment by fgrzadkowski** [comment]
@vishh What's the status of this issue? Our [docker local setup](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker.md) contains some really unreadable prerequisites that verifies that memcg is enabled etc (see PR #12046 for details). I'd like to get rid of them (as part of fixing #12722).

AFAIU your PR #14395 will cause kubelet to fail to start with appropriate error message if memcg/swap is not enabled. Is that the case? How user can understand where is the problem?

**Comment by vishh** [comment]
Are most of the distros still being shipped with memcg disabled?

If kubelet fails node setup, it is expected to generate an appropriate
event and set the node condition to `NotReady`. Working around kernel
limitations is possible, but will add unnecessary complexity to the node.

**Comment by fgrzadkowski** [comment]
@vishh Thanks for the clarification! In that case I assume it's fine to assume that either memcg is enabled or it's possible to debug the failure by reading events. I'll send you a PR to simplify docker based setup.

**Comment by vishh** [comment]
Thanks Filip!

**Comment by vishh** [comment]
Since #14395 has been merged, I don't see what else we can do for this issue. Closing this.
