### ISSUE TITLE
Does *VolumeSource need to be optimized?

### ISSUE THREAD

**Issue by njuptlzf** [kubernetes/kubernetes#98396]
When I use nfs volume, **`volumes.nfs`**, I found that there are no more mount parameters defined, such as **`soft`**. 
Use **`pv,pvc`** to solve.

**`pv pvc`** is very useful. Why are there so many volumeSources? Is it worth adding more parameters?

For example, **`NFSVolumeSource`** adds **`mountOptions`**

// Represents an NFS mount that lasts the lifetime of a pod.
// NFS volumes do not support ownership management or SELinux relabeling.
type **NFSVolumeSource** struct {
        // Server is the hostname or IP address of the NFS server.
        // More info: https://kubernetes.io/docs/concepts/storage/volumes#nfs
        Server string `json:"server" protobuf:"bytes,1,opt,name=server"`

        // Path that is exported by the NFS server.
        // More info: https://kubernetes.io/docs/concepts/storage/volumes#nfs
        Path string `json:"path" protobuf:"bytes,2,opt,name=path"`

        // ReadOnly here will force
        // the NFS export to be mounted with read-only permissions.
        // Defaults to false.
        // More info: https://kubernetes.io/docs/concepts/storage/volumes#nfs
        // +optional
        ReadOnly bool `json:"readOnly,omitempty" protobuf:"varint,3,opt,name=readOnly"`
}

**Comment by neolit123** [comment]
you can also ask in #sig-storage on k8s slack

**Comment by njuptlzf** [comment]
thx,
/close
