### ISSUE TITLE
Enable profiling by default in kube-proxy

### ISSUE THREAD

**Issue by borgerli** [kubernetes/kubernetes#98410]
**What would you like to be added**:

Enable profiling by default in kube-proxy.

**Why is this needed**:
Profiling is a very useful feature when debugging performance issues. Except kube-proxy, other k8s components all enable profile by default. 

kube-apiserver, kubelet and kube-scheduler also support dynamically setting log level, which depends on enabling profiling.

**Comment by bowei** [comment]
Can you link in how this is done in the other components?

What impact does this have on kube-proxy?

Does this create any security concerns?

**Comment by borgerli** [comment]
@bowei Thanks for your reply.
1. scheduler: https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/apis/config/v1beta1/defaults.go#L154
  Other components: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/config/v1alpha1/defaults.go#L86

2. This will enable the /debug/pprof endpoint on kube-proxy metrics server: https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-proxy/app/server.go#L618

3.  I think there should be no security problems here, since by default the metrics server is bound to localhost(127.0.0.1:10249)

**Comment by jayunit100** [comment]
Amim is working w/ the component standard folks, so he volunteered to help look at this.
/assign @knabben

**Comment by knabben** [comment]
Kube-proxy configuration library is in `v1alpha1`, defaults values go to the external API on https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/apis/config/v1alpha1/defaults.go#L38 function. Technically a pointer on `EnableProfiling` can differentiate between values and empty, so a default can be applied.

@bowei I can open a PR and discuss further on slack if there're some concerns about it.
