### ISSUE TITLE
Build failed due to the check of bash version to be 5.x+

### ISSUE THREAD

**Issue by borgerli** [kubernetes/kubernetes#98419]
**What happened**:
On our Ubuntu 18.04 build machines(with bash 4.2), build failed with error: `ERROR: This script requires a minimum bash version of 5.0`

**What you expected to happen**:
build succeeds without error.

**How to reproduce it (as minimally and precisely as possible)**:

On a Ubuntu 18.04 machine with the latest bash installed from official repo, do make by `make kubelet`

**Anything else we need to know?**:
This is related to PR #98309

**Comment by neolit123** [comment]
version 5 was forced here:
https://github.com/kubernetes/kubernetes/pull/98309
https://github.com/kubernetes/kubernetes/issues/98294

**Comment by borgerli** [comment]
> 
> 
> version 5 was forced here:
> #98309
> #98294

#neolit123 The support of `-v` test was added in bash version 4.2.  It would be better to limit the mimimum verison to 4.2+, since some peple, like us, are using Ubuntu 18.04 with bash 4.x to do the build. Thanks.

**Comment by uablrek** [comment]
Or better yet use another method like;
```bash
if test -n "$GOLDFLAGS"; then
...
```

BTW I removed this flawed test and build happily on Ubuntu 18 without any problem.

**Comment by neolit123** [comment]
> @neolit123 The support of -v test was added in bash version 4.2. It would be better to limit the mimimum verison to 4.2+, since some people, including us, are using Ubuntu 18.04 with bash 4.x to do the build. Thanks.

i do not disagree with that. looks like the right people are already assigned to your PR.

**Comment by aojea** [comment]
This is breaking downstream CIs, I´ve found this today in one of thems
```
ERROR: error building node image: failed to build kubernetes: failed to build binaries: command "build/run.sh make all 'WHAT=cmd/kubeadm cmd/kubectl cmd/kubelet'" failed with error: exit status 1
Command Output: ERROR: This script requires a minimum bash version of 5.0
```

@BenTheElder @dims  is not possible to relax this to 4.2?

/sig-testing

**Comment by uablrek** [comment]
Better to not use the "test -v" options at all since it is completely unnecessary, see https://github.com/kubernetes/kubernetes/issues/98419#issuecomment-768122324.

It is not very user-friendly to enforce a global upgrade when there is absolutely no need. Ubuntu 18 has 4.2 but others may not.

**Comment by nikhita** [comment]
> @BenTheElder @dims is not possible to relax this to 4.2?

@aojea https://github.com/kubernetes/kubernetes/pull/98420 :)

**Comment by aojea** [comment]
He , that was fast :)

**Comment by BenTheElder** [comment]
> if test -n "$GOLDFLAGS"; then

this is actually not an equivilant check, but it is possible to implement one without using -v

I left a comment on the original PR with how to do this.

**Comment by BenTheElder** [comment]
see: https://github.com/kubernetes/kubernetes/pull/97699#discussion_r562415136

`test -v` reports _if the variable was set_, which includes `FOO=""`

```console
[bentheelder@bentheelder:~·2021-01-28T23:39:53-0800]
$ (export FOO=""; test -v FOO; echo $?)
0
[bentheelder@bentheelder:~·2021-01-28T23:40:18-0800]
$ (test -v FOO; echo $?)
1
```

In this case I do think the intent was to check if the variable was set or not.

It's still possible to do without `test -v` but it's a big more ... arcane.

Kubernetes has long required a reasonably up to date bash FWIW, on macOS you cannot use the system mac, and for a while you couldn't use debian stable's bash to build kubernetes as it had an array bug (4.0 IIRC).

I don't think we have a clear support policy here, and I think this is a good reason to reconsider writing large volumes of bash 🙃
