### ISSUE TITLE
DualStack: apiserver pod has only single IP address

### ISSUE THREAD

**Issue by emike922** [kubernetes/kubernetes#98411]
**What happened**:
Admission requests sent to IPv6 webhook services fail/time out in dual-stack cluster. Default (first) IP family in the cluster is IPv4.
Analysis has led me to the apiserver, which is making the requests to the webhook service. The apiserver pods have ONLY an IPv4 pod IP, no IPv6 pod IP, and thus presumably cannot make IPv6 requests.

`
$ k logs -n kube-system -lcomponent=kube-apiserver
I0122 14:47:28.493919       1 trace.go:116] Trace[1294786590]: "Call validating webhook" configuration:istiod-istio-system,webhook:validation.istio.io,resource:networking.istio.io/v1alpha3, Resource=gateways,subresource:,operation:CREATE,UID:47fc868c-ba8f-4c11-838e-d6fa805f0bad (started: 2021-01-22 14:46:58.492968374 +0000 UTC m=+254615.394818866) (total time: 30.000780641s):
Trace[1294786590]: [30.000780641s] [30.000780641s] END
W0122 14:47:28.494133       1 dispatcher.go:128] Failed calling webhook, failing open validation.istio.io: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=30s: context deadline exceeded
E0122 14:47:28.494271       1 dispatcher.go:129] failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=30s: context deadline exceeded
I0122 14:47:28.514005       1 trace.go:116] Trace[1064104022]: "Create" url:/apis/networking.istio.io/v1alpha3/namespaces/istio-system/gateways,user-agent:pilot-discovery/v0.0.0 (linux/amd64) kubernetes/$Format,client:10.117.142.10 (started: 2021-01-22 14:46:58.48938819 +0000 UTC m=+254615.391238690) (total time: 30.024481551s):
Trace[1064104022]: [30.023708536s] [30.022993263s] Object stored in database
$ k get pods -n kube-system -lcomponent=kube-apiserver -o jsonpath={.items[*].status.podIPs}
[{"ip":"10.117.142.5"}] [{"ip":"10.117.142.6"}] [{"ip":"10.117.142.7"}]
`

**What you expected to happen**:
Apiserver pods should get IPv4 AND IPv6 pod IPs, like all regular pods in dual-stack clusters
Admission requests sent to IPv6 (secondary IP family) webhook service by apiserver should succeed
(Other kube pods in kube-system namespace should also get two IP addresses?)

**How to reproduce it (as minimally and precisely as possible)**:
- Use dual-stack cluster with default IP family IPv4
- Create webhook service with IP family IPv6
- Create validating webhook config resource, pointing at IPv6 webhook service by DNS name
- Create/update a resource, triggering webhook (will hang/time out)
- Check apiserver log for failure

**Anything else we need to know?**:
I briefly tried kubernetes v1.20.2 in an Ubuntu VirtualBox using kubeadm. Enabled the DR feature gate, set IPv4+IPv6 pod and service cidrs.
The apiserver pod is just as described above, so I did not do further testing / finish the setup.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.2
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): SLES 15 SP1
- Kernel (e.g. `uname -a`): Linux 4.12.14-197.56-default
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
Usually, apiserver is run in hostNetwork, the IP of apiserver pod is the node ip. 
Node ip dual stack is supported in 1.20 after PR #95239. 

I need more investigation later.

**Comment by sftim** [comment]
Is this actually more of a SIG Cluster Lifecycle / documentation issue?

**Comment by danwinship** [comment]
> Usually, apiserver is run in hostNetwork, the IP of apiserver pod is the node ip.
> Node ip dual stack is supported in 1.20 after PR #95239. Configure kubelet like`kubelet --node-ip 10.1.0.5,fd01::0005`.

It doesn't matter what _kubelet_ thinks the node IP is; if the apiserver is running hostNetwork, then it has access to all of the node's addresses/routing automatically.

It seems like the problem here is either that the nodes themselves are not dual-stack, or that there is no IPv6 routing between the nodes and the pod network (or whatever network the webhook is on).

Actually, I see references to Istio; note that Istio does not have dual-stack support yet, so if you are depending on Istio doing something with the IPv6 address, it might not work.

**Comment by thockin** [comment]
> The apiserver pods have ONLY an IPv4 pod IP, no IPv6 pod IP, and thus presumably cannot make IPv6 requests.

Did we get clarity on whether the apiserver has a v6 IP and is not reporting it or whether it really doesn't have one?

@emike922

**Comment by emike922** [comment]
Sorry for the delay, got pulled into something else entirely...
You have a very good point, in our setup the cluster nodes' `.status.addresses` lists contain only one single InternalIP, and that is IPv4, but `.spec.podCIDRs` has IPv4 and IPv6 as it should.
So I take it, from your explanation @danwinship, that the lack of an IPv6 node IP will result in the described behavior?

**Comment by pacoxu** [comment]
> Is this actually more of a SIG Cluster Lifecycle / documentation issue?
@sftim  We need to add some documentation for kubeadm dual-stack install before 1.21 release as it is beta now.
I will working on it https://github.com/kubernetes/kubeadm/issues/1612#issuecomment-773906850 this week or next.

**Comment by thockin** [comment]
What's next on this?

**Comment by pacoxu** [comment]
I wrote a document for kubeadm installation in https://github.com/kubernetes/website/pull/26675 on how to enable dual-stack via kubeadm.
