### ISSUE TITLE
Increase the log level for the message showing that static pod status has been updated.

### ISSUE THREAD

**Issue by jvanz** [kubernetes/kubernetes#98422]
**What would you like to be added**:

I would like to ask to increase the log level for this line:

https://github.com/kubernetes/kubernetes/blob/889cf714c17163e2a787db9c474652514a18d52f/pkg/kubelet/kubelet_getters.go#L176-L181

**Why is this needed**:

I do not see the necessity to show every time the static pod has the status updated. It can flood the logs with the message.

I do not know if there is a reason for that. I believe it is a matter of taste. Furthermore, the [original merge request](https://github.com/kubernetes/kubernetes/pull/77661/files) adding this piece of code, the log was not there. The log line has being added in a [later merge request](https://github.com/kubernetes/kubernetes/pull/84951/files)

**Comment by jvanz** [comment]
I'll be happy to send a merge request for this issue. But I just need to know if this make sense to the community or not.

**Comment by pacoxu** [comment]
According to my quick research, this log is added in #84951  during fixing a regression issue.
 I think it make sense to use low level log as the bug is already fixed.

**Comment by SergeyKanzhelev** [comment]
@jvanz is the issue that it logs the same status over and over? Or that status being changed very often?

**Comment by ehashman** [comment]
/triage accepted

I agree V(2) seems a bit high for this. Feel free to submit a PR to drop to 3.

**Comment by SergeyKanzhelev** [comment]
> I agree V(2) seems a bit high for this. Feel free to submit a PR to drop to 3.

what is the reason for rapid status change?

**Comment by jvanz** [comment]
> @jvanz is the issue that it logs the same status over and over? Or that status being changed very often?

**Comment by tallclair** [comment]
/reopen
/assign

This is still an issue.

**Comment by vaibhav2107** [comment]
/remove-lifecycle rotten
As PR #125834 is still open
