### ISSUE TITLE
portforward audit logs do not include target port information

### ISSUE THREAD

**Issue by glenjamin** [kubernetes/kubernetes#98440]
**What happened**:

Check the audit log for a portforward event, it looks something like this:

```js
...
"requestURI": "/api/v1/namespaces/default/pods/pod-name/portforward",
"verb": "create",
"objectRef": {
    "resource": "pods",
    "namespace": "default",
    "name": "pod-name",
    "apiVersion": "v1",
    "subresource": "portforward"
},
...
```

Which doesn't include any information about the target port.

**What you expected to happen**:

The target port to be included in the audit event

**Anything else we need to know?**:

Based on some spelunking, this appears to be because although [the docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#create-connect-portforward-pod-v1-core) say that the ports are specified in the query string, they actually get passed via [a custom header over the portforwarding protocol](https://github.com/kubernetes/client-go/blob/b72204b2445de5ac815ae2bb993f6182d271fdb4/tools/portforward/portforward.go#L336) - which makes them invisible to the audit controller

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20
- Cloud provider or hardware configuration: n/a
- OS (e.g: `cat /etc/os-release`): n/a
- Kernel (e.g. `uname -a`): n/a
- Install tools: n/a
- Network plugin and version (if this is a network-related bug): n/a
- Others: n/a

**Comment by glenjamin** [comment]
I'm not sure about this, but going to take a punt on API Machinery

/sig api machinery

**Comment by glenjamin** [comment]
aha, i'm now reliably informed that audit is part of the auth group

/sig auth

**Comment by enj** [comment]
We do not seem to track headers or parameters via audit today.

https://github.com/kubernetes/kubernetes/blob/0aa2e975a472698a52d2db6db5d718c4214b2f7b/staging/src/k8s.io/api/core/v1/types.go#L5234-L5247

https://github.com/kubernetes/kubernetes/blob/d74ab9e1a4929be208d4529fd12b76d3fcd5d546/staging/src/k8s.io/apiserver/pkg/audit/request.go#L46-L164

**Comment by enj** [comment]
I misspoke a bit above - we do not audit log the parsed version of the query parameters (i.e. `PodPortForwardOptions`) but we do log the query parameters themselves via `RequestURI: req.URL.RequestURI()`.  So it is just the header info that we are missing.

**Comment by liggitt** [comment]
It looks like there's two things in play:

1. we don't log options structs passed to Connect REST handlers. That would be easy to add:

```diff
diff --git a/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go b/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
index 783ab96b9b9..eab8f13608a 100644
--- a/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
+++ b/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
@@ -31,6 +31,7 @@ import (
 	grpccodes "google.golang.org/grpc/codes"
 	grpcstatus "google.golang.org/grpc/status"
 
+	"k8s.io/apiserver/pkg/audit"
 	apiequality "k8s.io/apimachinery/pkg/api/equality"
 	"k8s.io/apimachinery/pkg/api/errors"
 	"k8s.io/apimachinery/pkg/api/meta"
@@ -180,6 +181,8 @@ func ConnectResource(connecter rest.Connecter, scope *RequestScope, admit admiss
 			scope.err(err, w, req)
 			return
 		}
+		audit.LogRequestObject(ae, opts, scope.Resource, scope.Subresource, scope.Serializer)
+
 		if admit != nil && admit.Handles(admission.Connect) {
 			userInfo, _ := request.UserFrom(ctx)
 			// TODO: remove the mutating admission here as soon as we have ported all plugin that handle CONNECT
```

2. As mo points out, SPDY portforward requests don't serialize a PodPortForwardOptions request; they open a SPDY stream all the way to the kubelet and initialize individual port forwarding streams over an upgraded SPDY connection. That wouldn't be possible to audit log without the API server intercepting the SPDY stream and doing protocol-level auditing. I don't anticipate that happening easily.

**Comment by glenjamin** [comment]
Does the API server accept standard query parameters for the port forward endpoint? The API docs seem to suggest it does, but the code takes a very different approach.

**Comment by njuptlzf** [comment]
I verified `option 1`. As @liggitt said, SPDY will not serialize PodPortForwardOptions,
The simple way I can think of to get the `remotePort ` is to insert it into `req.Header`.
