### ISSUE TITLE
Adding alpha/beta/GA metadata to generated openapi swagger.json

### ISSUE THREAD

**Issue by hh** [kubernetes/kubernetes#98449]
**What would you like to be added**:

Recording OpenAPI metadata as to the 'alpha', 'beta', or 'GA' state of every *operationId* in the generated swagger.json

**Why is this needed**:

A set of Alpha APIs were recently added that included `/api/v1/*` prefix in their path, and a lack of alpha or beta in the name of the operationId itself.

https://github.com/kubernetes/kubernetes/pull/97276

We've hit this a few times and finding it difficult to programatically discover the api level of operations as we currently make exemptions from `Conformance` for endpoints that don't match any documented logic for being GA or not.

We have looked into alternative ways of recording this information, but in multiple conversations the source of truth and authority here is the OpenAPI definition itself.

**Possible Approach**

Use a Swagger Extension:
https://swagger.io/docs/specification/2-0/swagger-extensions/

`x-kubernetes-apilevel: alpha` 
`x-kubernetes-apilevel: beta` 
`x-kubernetes-apilevel: GA`

**Comment by hh** [comment]
@liggitt noted that the existing swagger.json is generated from an APIserver with all apis enabled. It might make sense to generate another one with only stable APIs enabled allowing a comparison, or shortcut without necessarily needing to add generate the metadata within the OpenAPI spec.

https://kubernetes.slack.com/archives/C0EG7JC6T/p1611614187033600

**Comment by lavalamp** [comment]
I'm not convinced we can easily add this, but maybe @apelisse or @sttts has an idea.

We don't version things separately at the "operation" level so it's confusing to be asked for that. (e.g. even with subresources it's a group of verbs not individual "operations").

**Comment by hh** [comment]
@lavalamp I wrote up my understanding of how @ii would map resources (k8s kinds?) back to `operationIds` here:
https://github.com/kubernetes/kubernetes/pull/99307#issuecomment-783641817

Is that accurate?
