### ISSUE TITLE
LDAP Authentication for Kubernetes Cluster

### ISSUE THREAD

**Issue by agvaliente** [kubernetes/kubernetes#98448]
Hello

I have a kubernetes cluster on bare metal, and I need integrate the authentication with the LDAP server.

Please, I need help to identify the steps to the implementation.

Best regards.

**Comment by liggitt** [comment]
An LDAP-aware authenticating proxy can be placed in front of the API server to deal with LDAP-based authentication, and forward identity info to the API server in request headers. Details of the support for an authenticating proxy are at https://kubernetes.io/docs/reference/access-authn-authz/authentication/#authenticating-proxy


/sig auth
/close

**Comment by agvaliente** [comment]
> An LDAP-aware authenticating proxy can be placed in front of the API server to deal with LDAP-based authentication, and forward identity info to the API server in request headers. Details of the support for an authenticating proxy are at https://kubernetes.io/docs/reference/access-authn-authz/authentication/#authenticating-proxy
> 
> /sig auth
> /close

Hello

Could you send me a guide with the steps ?
