### ISSUE TITLE
Limit the number of containers per pod

### ISSUE THREAD

**Issue by kfirfer** [kubernetes/kubernetes#98450]
Hello

Would be nice to see a configuration option on `kubelet`, that restrict the number of containers can be deployed per pod.
For security and stability.
What do you think ?

**Comment by pacoxu** [comment]
If there is a resource quota of CPU/memory for the namespace and min limit range for container level, the number of containers in the namespace would be limited.

BTW, why add the limit in kubelet , not in apiserver or an admission-controller like `limit ranger` or `resource quota`?

- what is the default limit, 5 or 10 or ? 
- need we count init-containers or ephemeral containers?

**Comment by kfirfer** [comment]
Hi @pacoxu 
Yes, you right, limit on the resource quota seems more appropriate place instead kubelet config
And counting init/ephemeral containers as-well sounds good

I have setup resources limits of CPU/Ram, and also min limit-range, 
But its harder to mitigate abuses if the min limit-range is small

**Comment by wzshiming** [comment]
This can be done with admissionWebhook to limit the number of containers per Pod. e.g. https://github.com/kyverno/kyverno/

Kubernetes does not use issues on this repo for support requests. If you have a question on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/).

/remove-kind bug
/kind support
/close
