### ISSUE TITLE
kubelet_volume* / persistent volume metrics missing for ceph rbd

### ISSUE THREAD

**Issue by sunchill06** [kubernetes/kubernetes#98476]
**What happened**:

I am trying to get kubelet_volume_* metrics., but don't see any.

`k get sc
NAME                    PROVISIONER    RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
sc-rbd (default)     ceph.com/rbd   Delete          Immediate           false                  50d`

`curl -s http://localhost:9090/metrics -k|grep kubelet_volume|wc -L 
0`

**What you expected to happen**:
I except that kubelet should expose prometheus volume metrics to /metrics path as well. Then it is easy to read with prometheus and to monitor the persistent volume usage status

**How to reproduce it (as minimally and precisely as possible)**:
Created ceph storage class and a persistent-volume-claim but no persistent volume metrics will be published

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): "v1.18.9"
- Cloud provider or hardware configuration: Baremetal
- OS (e.g: `cat /etc/os-release`): 
NAME="SLES"
VERSION="15-SP1"
VERSION_ID="15.1"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP1"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp1"

- Kernel (e.g. `uname -a`): 4.12.14-195-default 
- GNU/Linux
- Install tools: 
- Network plugin and version (if this is a network-related bug):
- Others:
kubernetes version:

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-23T07:48:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-23T07:40:51Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by pacoxu** [comment]
maybe similar with #97138 （1.19.0-1.19.4 not work）&（1.19.5+ work）

**Comment by sunchill06** [comment]
@pacoxu I don't think its related to 97138  as I can see the local PV stats but not the dynamic PVs created by ceph rbd storage class.

**Comment by nehatomar12** [comment]
@sunchill06 did you find anything to get `kubelet_volume_stats_available_bytes` metrics ?

**Comment by jicki** [comment]
kubelet_volume* / persistent volume metrics missing for ceph rbd 

me too
