### ISSUE TITLE
secret was deleted due to failure of update serviceaccount.Secrets after is was used or referenced by pod

### ISSUE THREAD

**Issue by sanwishe** [kubernetes/kubernetes#98474]
**What happened**:

```
I0120 17:35:46.590403       1 trace.go:116] Trace[1835007712]: "Delete" url:/api/v1/namespaces/admin/secrets/k8sconfig-sa-token-6c8hz,user-agent:kube-controller-manager/v1.17.9 (linux/amd64) kubernetes/59603c6/tokens-controller,client:1111::d15f (started: 2021-01-20 17:35:45.193170835 +0800 CST m=+196.151374014) (total time: 1.397188005s):
Trace[1835007712]: [1.397148638s] [1.397101146s] Object deleted from database
```

```
E0120 17:35:47.026101   70870 nestedpendingoperations.go:290] Operation for "\"kubernetes.io/secret/ab1566ee-5d8a-4c24-825d-fc2ee7cc37f8-k8sconfig-sa-token-6c8hz\" (\"ab1566ee-5d8a-4c24-825d-fc2ee7cc37f8\")" failed. No retries permitted until 2021-01-20 17:35:48.02606438 +0800 CST m=+183.395522570 (durationBeforeRetry 1s). Error: "MountVolume.SetUp failed for volume \"k8sconfig-sa-token-6c8hz\" (UniqueName: \"kubernetes.io/secret/ab1566ee-5d8a-4c24-825d-fc2ee7cc37f8-k8sconfig-sa-token-6c8hz\") pod \"op-containers-k8sconfig-1-jz7pb\" (UID: \"ab1566ee-5d8a-4c24-825d-fc2ee7cc37f8\") : secret \"k8sconfig-sa-token-6c8hz\" not found"
E0120 17:37:55.849529   70870 secret.go:195] Couldn't get secret admin/k8sconfig-sa-token-6c8hz: secret "k8sconfig-sa-token-6c8hz" not found
```

I found in the code of `tokenController` that a secret may be deleted due to various reasons, such as failed  updating the secret reference in service account:

```
		// Try to add a reference to the token
		liveServiceAccount.Secrets = append(liveServiceAccount.Secrets, v1.ObjectReference{Name: secret.Name})
		if _, err := serviceAccounts.Update(context.TODO(), liveServiceAccount, metav1.UpdateOptions{}); err != nil {
			return err
		}

		addedReference = true
		return nil
	})

	if !addedReference {
		// we weren't able to use the token, try to clean it up.
		klog.V(2).Infof("deleting secret %s/%s because reference couldn't be added (%v)", secret.Namespace, secret.Name, err)
		deleteOpts := metav1.DeleteOptions{Preconditions: &metav1.Preconditions{UID: &createdToken.UID}}
		if err := e.client.CoreV1().Secrets(createdToken.Namespace).Delete(context.TODO(), createdToken.Name, deleteOpts); err != nil {
			klog.Error(err) // if we fail, just log it
		}
	}
``` 

But the are many scenes, kubeClient create a serviceaccount, and then it watches secrets until it find the first secret passes kube-apiserver's authentication(For example, the `SAControllerClientBuilder.Config(name string) (*restclient.Config, error)` method create a controller's sa and watch its secret to build a sa based controller client). In the tokenController's main goroutine, this secret was deleted after that, this case the newly build client failed with Unauthorized error.

**What you expected to happen**:

Once the secret of a sa is created, we cannot  restrict user use it before tokenController successfully updates the sa's secret reference. 

Is that possible to:

- make the secret failed to authenticate  before tokenController successfully updates the sa's secret reference?
- treat the creation of secret and the update of sa's secret reference as a transaction?
- do not delete the secret until tokenController update sa's secret reference successfully?

**How to reproduce it (as minimally and precisely as possible)**:

This may happens etcd works at a low IO disks or some other processes squeeze the disk IO.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  v1.19.4  
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Centos 7
- Kernel (e.g. `uname -a`): 3.10.0-693.21.1.el7.x86_64 #1 SMP Sat Dec 12 11:46:01 CST 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
in 1.20+, SAControllerClientBuilder will use bound tokens rather than secret-based tokens. I think we should work to reduce use of the secret-based tokens rather than make significant changes to the token controller cleanups.

/assign @zshihang

**Comment by zshihang** [comment]
looks like the issue happened when mounting a sa secret-based token in the pod. due to the non-atomicity in token controller, i'd suggest using `BoundServiceAccountTokenVolume`(enable by default starting 1.21). as a workaround for now, you can 
1. either turn on `BoundServiceAccountTokenVolume` feature gate(prior to 1.21) on both kube-apiserver and kube-controller-manager
2. or starting in 1.20, disable the auto mounting of legacy secret-based token using `automountServiceAccountToken: false` on a sa or pod and then manually add projected volumes for token and ca:
```
    &api.ProjectedVolumeSource{
		Sources: []api.VolumeProjection{
			{
				ServiceAccountToken: &api.ServiceAccountTokenProjection{
					Path:              "token",
					ExpirationSeconds: 3607,
				},
			},
			{
				ConfigMap: &api.ConfigMapProjection{
					LocalObjectReference: api.LocalObjectReference{
						Name: "kube-root-ca.crt",
					},
					Items: []api.KeyToPath{
						{
							Key:  "ca.crt",
							Path: "ca.crt",
						},
					},
				},
			},
			{
				DownwardAPI: &api.DownwardAPIProjection{
					Items: []api.DownwardAPIVolumeFile{
						{
							Path: "namespace",
							FieldRef: &api.ObjectFieldSelector{
								APIVersion: "v1",
								FieldPath:  "metadata.namespace",
							},
						},
					},
				},
			},
		},
	}
```

we are reducing the usage of secret-based tokens.
