### ISSUE TITLE
Allow changing pod log directory

### ISSUE THREAD

**Issue by lorenz** [kubernetes/kubernetes#98473]
**What would you like to be added**:
Kubelet currently hardcodes the path of pod log dirs here: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L62

It would be nice if this was configurable.

**Why is this needed**:
Not having this configurable is quite annoying for locked-down systems with read-only filesystems where one needs tight controls over where software can write to.
Kubelet's RootDir is already configurable, but that is not particularly helpful if the log directory is hardcoded and no containers can start if the mkdir call for it fails.

**Comment by pacoxu** [comment]
Two workarounds would be 

- mount your path to /var/log/pods
-  or make a  symbolic link to your path

However this is still a nice feature request.

**Comment by pacoxu** [comment]
/area kubelet
will send a PR after feature approve.

**Comment by lorenz** [comment]
I just patched the hardcoded path as this project builds K8s itself anyways. But it would be nice if this wasn't necessary, that's why I opened this feature request.
