### ISSUE TITLE
serviceSpreadPriority not properly scoring nodes after being mapped to podTopologySpread

### ISSUE THREAD

**Issue by damemi** [kubernetes/kubernetes#98480]
**What happened**:
`SelectorSpreadPriority` and `ServiceSpreadPriority` were mapped to `PodTopologySpread` in https://github.com/kubernetes/kubernetes/pull/95448. However, in some scheduling runs with `serviceSpreadPriority` enabled, the (newly mapped) topology spread plugin reports `score: 0` for all nodes, leading to pods being scheduled on the same node instead of being spread.

```
I0125 15:53:53.585512       1 generic_scheduler.go:504] Plugin PodTopologySpread scores on kxxx/service-spreading-d7bt9 => [{kxxx25-vnvkw-worker-scvsw 0} {kxxx25-vnvkw-worker-w6wvw 0}]
```

**What you expected to happen**:
Nodes to be scored relative to the appropriate selector spreading.

**How to reproduce it (as minimally and precisely as possible)**:
Enable `serviceSpreadPriority` in the scheduler `policy.cfg` (and disable everything else)
```
$ cat policy.cfg 
{
"kind" : "Policy",
"apiVersion" : "v1",
"predicates" : [
],
"priorities" : [ 
        {"name" : "ServiceSpreadingPriority", "weight" : 1}
        ]
}
```

Create an RC and Service matching:
```
{
    "apiVersion": "v1",
    "kind": "List",
    "items": [
        {
            "apiVersion": "v1",
            "kind": "ReplicationController",
            "metadata": {
                "labels": {
                    "name": "service-spreading"
                },
                "name": "service-spreading"
            },
            "spec": {
                "replicas": 5,
                "template": {
                    "metadata": {
                        "labels": {
                            "name": "service-spreading"
                        }
                    },
                    "spec": {
                        "containers": [
                            {
                                "image": "openshift/hello-openshift",
                                "name": "service-pod"
                            }
                        ]
                    }
                }
            }
        },
        {
            "apiVersion": "v1",
            "kind": "Service",
            "metadata": {
                "labels": {
                    "name": "service-spreading"
                },  
                "name": "service-spreading"
            },
            "spec": {
                "ports": [
                    {
                        "name": "http",
                        "port": 27017,
                        "protocol": "TCP",
                        "targetPort": 8080
                    }
                ],  
                "selector": {
                    "name": "service-spreading"
                }   
            }
        }
    ]
}
```

See scores in scheduler logs (with `v=10`):
```
I0125 15:53:53.585512       1 generic_scheduler.go:504] Plugin PodTopologySpread scores on kxxx/service-spreading-d7bt9 => [{kxxx25-vnvkw-worker-scvsw 0} {kxxx25-vnvkw-worker-w6wvw 0}]
```

**Anything else we need to know?**:
We understand that both policy and serviceSpread are deprecated. If the simple solution is "don't use them", that is acceptable :) Just raising this bug to get more info.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig scheduling

**Comment by alculquicondor** [comment]
Can you show the output of the component config?
Nice thing that you added it :)

**Comment by ingvagabund** [comment]
```
I0121 12:33:56.933501       1 configfile.go:72] Using component config:
apiVersion: kubescheduler.config.k8s.io/v1beta1
clientConnection:
  acceptContentTypes: ""
  burst: 100
  contentType: application/vnd.kubernetes.protobuf
  kubeconfig: /etc/kubernetes/static-pod-resources/configmaps/scheduler-kubeconfig/kubeconfig
  qps: 50
enableContentionProfiling: true
enableProfiling: true
healthzBindAddress: 0.0.0.0:10251
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: true
  leaseDuration: 15s
  renewDeadline: 10s
  resourceLock: configmaps
  resourceName: kube-scheduler
  resourceNamespace: openshift-kube-scheduler
  retryPeriod: 2s
metricsBindAddress: 0.0.0.0:10251
parallelism: 16
percentageOfNodesToScore: 0
podInitialBackoffSeconds: 1
podMaxBackoffSeconds: 10
profiles:
- pluginConfig:
  - args:
      apiVersion: kubescheduler.config.k8s.io/v1beta1
      kind: DefaultPreemptionArgs
      minCandidateNodesAbsolute: 100
      minCandidateNodesPercentage: 10
    name: DefaultPreemption
  - args:
      apiVersion: kubescheduler.config.k8s.io/v1beta1
      kind: NodeResourcesLeastAllocatedArgs
      resources:
      - name: cpu
        weight: 1
      - name: memory
        weight: 1
    name: NodeResourcesLeastAllocated
  - args:
      apiVersion: kubescheduler.config.k8s.io/v1beta1
      defaultingType: System
      kind: PodTopologySpreadArgs
    name: PodTopologySpread
  plugins:
    bind:
      enabled:
      - name: DefaultBinder
        weight: 0
    filter:
      enabled:
      - name: NodeUnschedulable
        weight: 0
      - name: TaintToleration
        weight: 0
    permit: {}
    postBind: {}
    postFilter:
      enabled:
      - name: DefaultPreemption
        weight: 0
    preBind: {}
    preFilter: {}
    preScore:
      enabled:
      - name: PodTopologySpread
        weight: 0
    queueSort:
      enabled:
      - name: PrioritySort
        weight: 0
    reserve: {}
    score:
      enabled:
      - name: NodeResourcesLeastAllocated
        weight: 2
      - name: PodTopologySpread
        weight: 10
  schedulerName: default-scheduler
```

**Comment by alculquicondor** [comment]
oh, I think I know why. Do your nodes have zone label?

This might be related to the Note here: https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/#internal-default-constraints

Unfortunately, that means that you cannot use policy API and configure default spreading, which is technically a regression.

**Comment by alculquicondor** [comment]
The workaround would be to add a zone to all the nodes.

But perhaps we can do something more in code (effectively lifting the note above). If `defaultingType: System`, ignore non-existing labels. @Huang-Wei WDYT?

**Comment by ingvagabund** [comment]
We have `failure-domain.beta.kubernetes.io/zone:` and `topology.kubernetes.io/zone:` label keys set. Any other labels missing?

**Comment by alculquicondor** [comment]
`topology.kubernetes.io/zone` and`kubernetes.io/hostname` are the correct ones.

Does this reproduce without the Policy API?

**Comment by damemi** [comment]
> Does this reproduce without the Policy API?

Is `ServiceSpreadPriority` available as a CC plugin? I thought the only way to set that was with policy API

**Comment by alculquicondor** [comment]
TopologySpreadConstraints with `defaultingType: System` is the ServiceSpreadPriority

**Comment by alculquicondor** [comment]
I'm trying to reproduce while introducing a few log lines in scoring. However, my docker installation is somehow busted, so I can't run kind.

Earlier I noticed a log line in kube-scheduler indicating that it didn't have permission to list ReplicationControllers, so maybe that's related. However, the Service should cover for that. Have you tried creating the Service ahead of time?

And again, also worth testing if default spreading works without Policy API (no configuration should be enough for that).

**Comment by Huang-Wei** [comment]
> Is `ServiceSpreadPriority` available as a CC plugin?

@damemi It's available as a plugin. And you have to enable it explicitly via CC, and also ensure the args.affinityLables is not nil.

**Comment by Huang-Wei** [comment]
> But perhaps we can do something more in code (effectively lifting the note above). If `defaultingType: System`, ignore non-existing labels. @Huang-Wei WDYT?

So the root cause is that the cluster has both legacy topology labels (failure-domain.beta.kubernetes.io/*) and the up-to-date ones?

**Comment by alculquicondor** [comment]
We haven't found the root cause. My guess was that the nodes didn't have the required labels, but that's not the case.

> It's available as a plugin. And you have to enable it explicitly via CC (disabled by default), and also ensure the args.affinityLables is not nil.

I think you are referring to the ServiceAffinity?

**Comment by alculquicondor** [comment]
@ingvagabund can you check the scheduler logs to see if it has any issues listing ReplicationControllers and Services?

**Comment by ingvagabund** [comment]
There are no issues though checking the nodes in this particular case I don't see any zone labels set :-| Looks like we don't see zone labels in every cloud provider instalation.

**Comment by alculquicondor** [comment]
Awesome!

We can still think about https://github.com/kubernetes/kubernetes/issues/98480#issuecomment-768365650
as this is a breaking change.

**Comment by Huang-Wei** [comment]
> I think you are referring to the ServiceAffinity?

oops, indeed. Nvm :)

**Comment by Huang-Wei** [comment]
@alculquicondor If users specify SelectorSpreadPriority, internally we set the defaulting type of PodTopologySpread to `System`, and that [pluginConfig](https://github.com/kubernetes/kubernetes/blob/2b38078de1c655221b16dfd8f953b628ea7abe93/pkg/scheduler/framework/plugins/legacy_registry.go#L340-L342) will be valid for [Filter](https://github.com/kubernetes/kubernetes/blob/d4418c1402188947cac992de96c04e44ad639997/pkg/scheduler/framework/plugins/podtopologyspread/filtering.go#L211-L216) as well. So does that mean in this case, non-existing topology labels will even blocking regular pods from scheduling? (why Mike and Jan didn't run into this is just b/c they disabled PodTopologySpread in Filter?)

**Comment by alculquicondor** [comment]
> So does that mean in this case, non-existing topology labels will even blocking regular pods from scheduling?

No, because the System default doesn't have hard pod affinity.

**Comment by Huang-Wei** [comment]
> No, because the System default doesn't have hard pod spreading.

Thanks, I see `systemDefaultConstraints` is with WhenUnsatisfiable=ScheduleAnyway.

**Comment by alculquicondor** [comment]
Given that, before moving to pod topology spread, this used to work when zone labels where not set, my recommendation would be to do https://github.com/kubernetes/kubernetes/issues/98480#issuecomment-768365650 so that this is not a breaking change for some clusters

@Huang-Wei wdyt? any takers?

**Comment by alculquicondor** [comment]
/close
in favor of #102136
