### ISSUE TITLE
How to renew certificates on Kubernetes?

### ISSUE THREAD

**Issue by avarf** [kubernetes/kubernetes#98483]
**What happened**:
Yesterday I found out that kubectl commands are not working on our k8s cluster and after some digging, I found out that the reason is our certificates have been expired after 1 year. Based on K8s documentation (https://v1-16.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/) you can renew your certificates manually by running `kubeadm alpha certs renew` which I did but still kubectl was not able to connect to the cluster but the cluster was up and pods were working.

Then I found this answer https://stackoverflow.com/a/56334732/5553963 which creates new certificates and config files. After following that kubectl started to work but `kubelet` on the master node went down and it said that it cannot authenticate and all nodes became `Not Ready`.

After digging even more in the kubernetes github issues I found a solution that deleting the `/var/lib/kubelet/pki` certificates might help (in addition to editing the `/etc/kubernetes/kubelet.conf`) and after deleting those certificates and when they got recreated automatically again kubelet was able to start and master node became ready.

Then I had to find out how to renew the certificates for the workers but I couldn't find anything that directly was a solution for workers so I created a new join token with the below command on the master and I ran it on the worker nodes but I got below error:
```bash
# on Master
kubeadm token create --print-join-command  --ttl=0

# on worker
$ sudo kubeadm join 10.203.20.160:6443 --token fecjk7.ni262bvxx8zwmn5k     --discovery-token-ca-cert-hash sha256:02c76ff08c29a6d65ec580f8988a21ac75f77cc3ea655615e02d7331cf5ffb34 --v=5

I0127 14:44:57.968121   13747 token.go:199] [discovery] Trying to connect to API Server "10.203.20.160:6443"
I0127 14:44:57.970371   13747 token.go:74] [discovery] Created cluster-info discovery client, requesting info from "https://10.203.20.160:6443"
I0127 14:44:57.973778   13747 token.go:202] [discovery] Failed to connect to API Server "10.203.20.160:6443": cluster CA found in cluster-info configmap is invalid: none of the public keys "sha256:1e202253d5bc97848fdd3a3d3a00961bcce7f29b86d494a248ec953e7bfab73e" are pinned
I0127 14:45:02.973962   13747 token.go:199] [discovery] Trying to connect to API Server "10.203.20.160:6443"
I0127 14:45:02.974873   13747 token.go:74] [discovery] Created cluster-info discovery client, requesting info from "https://10.203.20.160:6443"
I0127 14:45:02.978465   13747 token.go:202] [discovery] Failed to connect to API Server "10.203.20.160:6443": cluster CA found in cluster-info configmap is invalid: none of the public keys "sha256:1e202253d5bc97848fdd3a3d3a00961bcce7f29b86d494a248ec953e7bfab73e" are pinned

# on master checking the public key again
$ openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'
02c76ff08c29a6d65ec580f8988a21ac75f77cc3ea655615e02d7331cf5ffb34
```
I double-checked the published key of that token on the master again, rebooted the worker, deleted the kubectl and `kubeadm` and everything else that I could think of but with no success.

Now I just gave up and we need the cluster so I want to reinstall the K8s again but since we have another cluster that its certificates will be expired in 22 days I have some questions:
1. Can someone please write all the steps on how to renew the certificates on all nodes?
2. We just created a cluster on AWS EKS to test it, how EKS manages the certificates and how we shall renew the certificates on EKS?

**What you expected to happen**:
- The commands in the documentation work
- The token that I generate with the `kubeadm` work properly
- The logs in the `kubeadm join` gives more information because I don't have any idea why the public key is wrong
- The documentation contains a clear, step by step guideline on how to solve this issue (look at this pdf from cisco: https://www.cisco.com/c/en/us/support/docs/cloud-systems-management/cloudcenter/215299-ccs-kubernetes-certificates-expire-c.pdf)

**How to reproduce it (as minimally and precisely as possible)**:
Since I don't know exactly why I faced so many issues especially with `kubelet` and `kubeadm` join I don't know exactly how to reproduce this but having a cluster with expired certificates is a good start.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Bare metal Linux machines
- OS (e.g: `cat /etc/os-release`):
```bash
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
```bash
$ uname -a
Linux serflex-giant-7 4.15.0-132-generic #136-Ubuntu SMP Tue Jan 12 14:58:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:

/sig docs
/sig cluster-lifecycle

**Comment by neolit123** [comment]
hello, support questions should go on the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

you can also try #kubeadm on k8s slack.

/kind support
/close
