### ISSUE TITLE
in-tree storage driver for Windows has issues when create container: mount point does not exist

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#98492]
Starting from v1.20, many storage tests with in-tree driver start to flake. Checking the log, it shows that volume attach/mount all succeeded, but when creating container, get the error message

Failed: Error: Error response from daemon: invalid volume specification: 'c:\var\lib\kubelet\pods\7173f517-76c4-48e7-894d-bd9e6d92ca51\volumes\kubernetes.io~azure-disk\pvc-6ece396b-2beb-4fc2-8265-5deed43d9e90:c:/mnt/test-1':   invalid mount config for type "bind": bind source path does not exist: c:\var\lib\kubelet\pods\7173f517-76c4-48e7-894d-bd9e6d92ca51\volumes\kubernetes.io~azure-disk\pvc-6ece396b-2beb-4fc2-8265-5deed43d9e90

Jan 23 23:54:59.151: INFO: At 2021-01-23 23:49:10 +0000 UTC - event for azuredisk-volume-tester-6597z-0: {kubelet 6312k8s000} SandboxChanged: Pod sandbox changed, it will be killed and re-created.

This error appeared for both gce pd and azure disk drivers.

testgrid
https://testgrid.k8s.io/sig-windows-azure#aks-engine-azure-windows-azure-disk
https://testgrid.k8s.io/sig-windows-gce#gce-windows-2019-containerd-master

**Comment by jsturtevant** [comment]
just had this fail in a pr: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/98510/pull-kubernetes-e2e-azure-disk-windows/1354911040021729280

**Comment by jsturtevant** [comment]
fyi @andyzhangx @feiskyer

**Comment by andyzhangx** [comment]
it's an intermittent issue, happens more frequently in statefulset e2e test:
https://testgrid.k8s.io/provider-azure-windows#pr-k8s-azure-disk-e2e-master-windows

**Comment by jsturtevant** [comment]
another failure: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/101047/pull-kubernetes-e2e-aks-engine-azure-disk-windows-dockershim/1382743018188050432

**Comment by andyzhangx** [comment]
> pull-kubernetes-e2e-aks-engine-azure-disk-windows-

already fixed by https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/794

**Comment by msau42** [comment]
Wrong issue is referenced? This issue is not related to csi windows feature right?

**Comment by jingxu97** [comment]
> Wrong issue is referenced? This issue is not related to csi windows feature right?

oh, I messed up the copy/paste. Updated.
