### ISSUE TITLE
Restarting containerd (and kubelet) does not impact "runtime" startTime in summary API

### ISSUE THREAD

**Issue by karan** [kubernetes/kubernetes#98494]
**What happened**: Containerd (and optionally the kubelet) was restarted.

**What you expected to happen**: `runtime`'s `startTime` should be the restart time.

```
$ curl -s localhost:10255/stats/summary | grep -i runtime -A 2
    "name": "runtime",
    "startTime": "2021-01-22T01:29:09Z",
    "cpu": {
```

**How to reproduce it (as minimally and precisely as possible)**:

```
# Note the current startTime
$ curl -s localhost:10255/stats/summary | grep -i runtime -A 2

# Restart containerd
$ sudo systemctl restart containerd

# Note the current startTime
$ curl -s localhost:10255/stats/summary | grep -i runtime -A 2
```

I would expect the time to change. The reason why it does not is because cAdvisor is looking in the cgroup fs and finding the oldest modified time of `cgroup.clone_children` in all subsystems. In other words, for each of the [supported subsystems](https://github.com/google/cadvisor/blob/730e7df6dbddf323b4cdd54cc91156cfdd9cf127/container/libcontainer/helpers.go#L110-L120), it's looking at the oldest mtime of `/sys/fs/cgroup/$subsystem/system.slice/containerd.service/cgroup.clone_children`. When containerd is restarted, that file is unchanged.

https://github.com/google/cadvisor/blob/730e7df6dbddf323b4cdd54cc91156cfdd9cf127/container/common/helpers.go#L74-L91

In this code, for the `runtime`:
* `cgroupPaths` is a map (eg `{ cpu: /sys/fs/cgroup/cpu/system.slice/containerd.service/, memory: /sys/fs/cgroup/memory/system.slice/containerd.service/ }`)
* `spec.CreationTime` [is set](https://github.com/kubernetes/kubernetes/blob/4b3d6369dd204c38959d4f508c7a3a3d3d81eb35/pkg/kubelet/server/stats/summary_sys_containers.go#L56) as the `startTime` in summary API

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): At least 1.16+ just from reading it and experiments.
- Cloud provider or hardware configuration: GKE
- OS (e.g: `cat /etc/os-release`): `Container-Optimized OS ` however this seems OS-agnostic
- Kernel (e.g. `uname -a`): `5.4.49+` however kernel shouldn't matter
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by vnev** [comment]
Hi, I'd like to take up this issue if possible. Thanks!

**Comment by ehashman** [comment]
> **What happened**: Containerd (and optionally the kubelet) was restarted.
> 
> **What you expected to happen**: `runtime`'s `startTime` should be the restart time.

I would not this expect this to happen because restarting containerd should not restart containers. The data plane should be resilient to control plane failures.

/close

**Comment by liggitt** [comment]
The `runtime` metrics are supposed to be metrics for the container runtime itself. This is related to the ability to monitor container runtime health, not saying that all containers should have been restarted.

**Comment by liggitt** [comment]
it looks like this was a cadvisor bug that had activity in https://github.com/google/cadvisor/pull/2800

if that's resolved the issue, can we use this to track when the fixed cadvisor version is included in k/k?

/cc @bobbypage

**Comment by ehashman** [comment]
Ah! My bad.

This was fixed in cadvisor v0.39.0 which landed in https://github.com/kubernetes/kubernetes/pull/99875 so I think this can _actually_ be closed.

/close

**Comment by ehashman** [comment]
/remove-lifecycle rotten

someone should feel free to reopen if they can still repro this; we also have https://github.com/kubernetes/kubernetes/issues/101902 concerned with the container metrics as opposed to the runtime itself.

**Comment by bobbypage** [comment]
Just to leave a note -- the root issue here is that summary API reports a field `StartTime` which is actually populated from cAdvisor _creation_ time leading to confusion of why "startTime" is not updated on container restarts.

https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/kubelet/stats/helper.go#L145

google/cadvisor#2800 did update logic for finding _creation_ time, but this didn't affect the confusion between creationTime being reported as startTime on summary API. More discussion in https://github.com/kubernetes/kubernetes/issues/101902

**Comment by ehashman** [comment]
Should this be reopened then?

**Comment by bobbypage** [comment]
I think we can use #101902 to track this instead.
