### ISSUE TITLE
'kubectl get nodes' returns unknown command

### ISSUE THREAD

**Issue by adyanthaya17** [kubernetes/kubernetes#9850]
So I reinstalled the ubuntu kubernetes setup of master and minion node. I have installed docker on both the nodes as it behaves as minion nodes. I have a new error this time.

When I run the command 'KUBERNETES_PROVIDER=ubuntu ./kube-up.sh', it reads as cluster validation succeeded. Even it's able to fetch the node state that reads 'Ready' during the command process when it ends.

The thing is when I issue the command 'kubectl get nodes' it comes as command not found. I'm issuing it in the directory that has kubectl but I have no clue what to do. All the services are up and running.

**Comment by adyanthaya17** [comment]
I ran the command in kubernetes/cluster/ubuntu/binaries and it gives me unknown command.

**Comment by luxas** [comment]
Could this be something like #9808? 
Are you running from source?

**Comment by adyanthaya17** [comment]
Hi, only the first issue regarding the ssh-identity is similar but I fixed it by adding the key to ssh-add. I'm working on ubuntu. Yesterday I configured the file and ran the kube-up command and I was able to get my environment up and running. When I tried fetching the details of the nodes it gave me unknown error.

Today I brought down the environment by kube-down.sh but now it reads:

Kubernetes cluster is running. The master is running at:
http://10.x.x.x.

Using master 10.x.x.x
./../cluster/ubuntu/util.sh: line 356: create-kubeconfig: command not found

**Comment by adyanthaya17** [comment]
No it's not. I did get the ssh-identity but I fixed it. How I know according to the document of ubuntu I don't need to configure anything related to kubectl but here I'm getting 'command not found'. Not sure if the codes were changed or modified.
