### ISSUE TITLE
[Flaky Test] [sig-apps] CronJob should delete failed finished jobs with limit of one job

### ISSUE THREAD

**Issue by PriyankaH21** [kubernetes/kubernetes#98501]
**Which jobs are flaking**: `ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd` 

**Which test(s) are flaking**: `CronJob should delete failed finished jobs with limit of one job`

**Testgrid link**:   https://testgrid.k8s.io/sig-release-master-informing#aks-engine-azure-windows-master-containerd&include-filter-by-regex=CronJob%20should%20delete%20failed%20finished%20jobs%20with%20limit%20of%20one%20job

**Reason for failure**:

```
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/cronjob.go:273
Jan 21 16:39:28.714: Failed to ensure that job does not exists anymore in namespace cronjob-3469
Unexpected error:
    <*url.Error | 0xc0023ae000>: {
        Op: "Get",
        URL: "https://api.e2e-kops-calico-u2004-k20-docker.test-cncf-aws.k8s.io/apis/batch/v1/namespaces/cronjob-3469/jobs",
        Err: {
            s: "http2: client connection lost",
        },
    }
    Get "https://api.e2e-kops-calico-u2004-k20-docker.test-cncf-aws.k8s.io/apis/batch/v1/namespaces/cronjob-3469/jobs": http2: client connection lost
occurred
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/cronjob.go:308
```
```
[sig-apps] CronJob
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/framework.go:23
  should delete failed finished jobs with limit of one job [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/cronjob.go:273
  Jan 26 00:01:27.067: Expected
      
      <int>: 2
  to equal
      <int>: 1
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/cronjob.go:302
------------------------------
{"msg":"FAILED [sig-apps] CronJob should delete failed finished jobs with limit of one job","total":-1,"completed":32,"skipped":529,"failed":1,"failures":["[sig-apps] CronJob should delete failed finished jobs with limit of one job"]}
Jan 26 00:03:32.146: INFO: Running AfterSuite actions on all nodes
```

**Anything else we need to know**:

Triage links: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=%20CronJob%20should%20delete%20failed%20finished%20jobs%20with%20limit%20of%20one%20job

Spyglass link: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1353842985720090624

**NOTE**: 
Similar issue was closed in Jan 2020 with a fix in [#86348 ](https://github.com/kubernetes/kubernetes/pull/86348): link to closed issue - https://github.com/kubernetes/kubernetes/issues/86179

/sig apps

**Comment by soltysh** [comment]
/assign 

I looked at it and from what I've check the last failures from 05/17 each one of them was related with nodes not being ready for tests. I'm going ahead and close this, feel free to re-open if you still see this issue happening.
