### ISSUE TITLE
[Failing Test] bazel-build-master process timeout

### ISSUE THREAD

**Issue by mkorbi** [kubernetes/kubernetes#98512]
**Which jobs are failing**:
* Overall
**Which test(s) are failing**:
The overall pipeline is failing 100% 

**Since when has it been failing**:
Jan 27 3:28 PST
**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#bazel-build-master
https://testgrid.k8s.io/sig-release-master-informing#bazel-build-master

**Reason for failure**:
Process timeout

` {"component":"entrypoint","file":"prow/entrypoint/run.go:165","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 2h0m0s timeout","severity":"error","time":"2021-01-28T03:18:37Z"}
Traceback (most recent call last):
  File "../test-infra/scenarios/kubernetes_bazel.py", line 288, in <module>
    main(parse_args())
  File "../test-infra/scenarios/kubernetes_bazel.py", line 189, in main
    bazel.check('build', *buildables)
  File "../test-infra/scenarios/kubernetes_bazel.py", line 55, in check
    check(*self._commands(cmd, *args, **kw))
  File "../test-infra/scenarios/kubernetes_bazel.py", line 33, in check
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 1099, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 125, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt `

**Anything else we need to know**:

**Comment by mkorbi** [comment]
just had a short chat with @saschagrunert seems like its part of the RelEng
/sig release

**Comment by saschagrunert** [comment]
Alright, so the job should usually not take longer than ~10min. There is not much useful information within the logs as far as I can see…

**Comment by spiffxp** [comment]
May be related to https://github.com/kubernetes/test-infra/issues/20628

**Comment by spiffxp** [comment]
/area release-eng
/sig testing
/triage accepted
FWIW I consider the ci bazel build jobs to be less critical (I'm not sure their output artifacts are consumed by anything) and was going to open a PR moving them to release-informing today.  WDYT @kubernetes/release-engineering ?

There is an open issue to move them off RBE and over to community-owned infra (ref: https://github.com/kubernetes/test-infra/issues/18653) if anyone wants to help out

**Comment by saschagrunert** [comment]
> FWIW I consider the ci bazel build jobs to be less critical (I'm not sure their output artifacts are consumed by anything) and was going to open a PR moving them to release-informing today. WDYT @kubernetes/release-engineering ?

Yeah we already have a `bazel-build-master` job on `sig-release-master-informing`: https://testgrid.k8s.io/sig-release-master-informing#bazel-build-master, so I'm in favor of that.

**Comment by BenTheElder** [comment]
this sort of build timeout is usually resource starvation in CI, I'm guessing these aren't in the guaranteed QOS cluster?

**Comment by saschagrunert** [comment]
/close

The issue seemed to be transient and is now gone, let's revisit if the failure occurs again.
