### ISSUE TITLE
New resource versions in k8s upgrade can cause namespaces stuck in terminating

### ISSUE THREAD

**Issue by willdeuschle** [kubernetes/kubernetes#98548]
**What happened**:
We operate clusters with 3 apiservers. We also run 3 kube-controller-managers, colocated on the same node as the apiserver, but only one of those is the leader. k-c-m only every communicates with the apiserver on its local node.

During upgrades, we roll one host at at a time (meaning there is a brief period of time < 1hr during which we're running apiservers/k-c-m on two different k8s versions). When upgrading from 1.18.8 to 1.19.5, we noticed that there was a long period of time during which namespaces stuck in terminating was elevated. This persisted until all apiservers/k-c-m had upgraded. In the meantime, the leader k-c-m (which was running k8s 1.18.8) was consistently logging:

```
deletion of namespace XXX failed: unable to retrieve the complete list of server APIs: certificates.k8s.io/v1: the server could not find the requested resource, events.k8s.io/v1: the server could not find the requested resource
```

Both of these resources were made stable in k8s 1.19. Furthermore, these errors from the namespace controller only began after the first apiserver upgraded to 1.19.5 (when `certificates.k8s.io/v1` and `events.k8s.io/v1` were first registered).

The apiserver running 1.18.8, where k-c-m was running and logging these errors, had already picked up the creation of these new resources, as it had logged `Adding v1.certificates.k8s.io` in both the available_controller and apiservice_controller.

Despite this, the namespace controller was unable to query these resources, which prevented it from being able to terminate namespaces. This is confirmed by k8s audit logs showing 404s on GET requests to `/apis/certificates.k8s.io/v1` and `/apis/events.k8s.io/v1` from the user `system:serviceaccount:kube-system:namespace-controller`. I believe these GET requests are initiated [here](https://github.com/kubernetes/kubernetes/blob/v1.18.8/staging/src/k8s.io/client-go/discovery/discovery_client.go#L187) in the discovery client, traced from the `deleteAllContent` method [here](https://github.com/kubernetes/kubernetes/blob/v1.18.8/pkg/controller/namespace/deletion/namespaced_resources_deleter.go#L500) on the `namespacedResourcesDeleter`.

**What you expected to happen**:
The apiserver running 1.18.8 should not 404 on GET requests to `/apis/certificates.k8s.io/v1` or `/apis/events.k8s.io/v1` after they have been registered by the apiserver running 1.19.5. 

**How to reproduce it (as minimally and precisely as possible)**:
Running 2 or more apiservers on 1.18.8, upgrade one of them, and then curl the server running 1.18.8 at `/apis/certificates.k8s.io/v1` or `events.k8s.io/v1`. Make sure those versions are not registered prior to the upgrade.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.5
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04
- Kernel (e.g. `uname -a`): Linux 4.15.0-1092-aws
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
/sig api-machinery
The failure message is added after #73405. 

This is similar to https://github.com/kubernetes/kubernetes/issues/60807#issuecomment-678704071. 
Would you share the result of `kubectl get apiservice|grep False` from the upgraded apiserver as well as the old apiserver ?

Most likely, one of the kube-controller-manager is the leader, and you could find some error logs in that kube-controller-manager. Would you share that?

If the api-service is registered again on 1.19 apiserver, I think the namespace may be deleted after the 1.19 kube-controller-manager became leader. Any errors in the new kube-controller-manager log?

**Comment by lavalamp** [comment]
Yeah this does look to be a dup.

I'm not sure what to do here, namespace lifecycle controller behavior is correct, it shouldn't delete something it can't confirm is empty.

OTOH it's kind of a mystery how the client got mismatched discovery doc and apiserver version, I feel like there's a caching bug or something there.

Oh, actually I know how that happened. @deads2k should know also. Any brilliant ideas?

In the short term the mitigation is going to be to keep deleting the controller manager lease until one colocated with a "new" apiserver picks it up.

This is actually really hard to fix for real.
