### ISSUE TITLE
 Is it reasonable that apiserver sets the timeout period for etcd's health check to 2s?

### ISSUE THREAD

**Issue by yangjunmyfm192085** [kubernetes/kubernetes#98557]
**What happened**:
kubelet use livenessProbe to probe the health status of kube-apiserver container.
When probe  kube-apiserver container,if etcd continues to respond to health requests very slowly 
will cause detection failure.
Eventually the apiserver container will be restarted.
**What you expected to happen**:
kube-apiserver can tolerate slow response of etcd health check.
**How to reproduce it (as minimally and precisely as possible)**:
etcd is busy, and the response to the health request exceeds 2s
**Anything else we need to know?**:
Is it reasonable to extend the timeout period? or other good idea？
Otherwise when etcd is already very busy,the situation is worse if restart kube-apiserver.

Related changes:
https://github.com/kubernetes/kubernetes/pull/65027

**Comment by yangjunmyfm192085** [comment]
If need to deal with,I will fix it.

**Comment by pacoxu** [comment]
2s for `/healthz` check api is really long enough in my opinion.
etcd will log a warning message if any request costs more than 100ms and there is a hardware requirement in https://etcd.io/docs/v3.5/op-guide/hardware/#disks.

If the cluster is really slow, I think there are many params that should be tuned, not only the health check here. 

/remove-sig node
As livenessProbe is configured for the Pod, kubelet(sig-node) just does the right thing to kill it if the check failed. I works as expected.
