### ISSUE TITLE
Add kube-apiserver metrics for non-resource URLs

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#98585]
**What would you like to be added**:
Request metrics for non-resource-URL endpoints on kube-apiserver. AFAICT we don't have any (based on poking /metrics). Example endpoint: `$API_SERVER/.well-known/openid-configuration` wrt https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/1393-oidc-discovery.

Or I'm wrong and there's actually metrics for (some) of this stuff and there's something simple I can do to add them, which would be excellent.

**Why is this needed**:
It's useful to admins:
- for determining feature usage
- for detecting/diagnosing issues

Today, seems like you'd pretty much have to look at kube-apiserver/audit logs for this stuff.

Ref: https://github.com/kubernetes/enhancements/pull/2363#discussion_r567122917

/cc @liggitt @johnbelamaric @lavalamp

**Comment by liggitt** [comment]
The issue with adding a metric for an arbitrary non-resource endpoint is that the labels you would have to add to the metric to make it identifiable would make the cardinality of the metric essentially unbounded (you could DOS the server by requesting  slight variants of an allowed prefix and make the API server create unbounded metric series labeled with all the paths you requested).

@logicalhan can confirm, but I think the "bounded set of labels" and "metrics for generic nonResourceURL paths" are contradictory

**Comment by lavalamp** [comment]
We would have to canonicallize all paths to make that work.

Normally features add metrics for exactly the things they need to care about and aren't so interested in page hits. I recommend just making a metric that counts what you want to monitor rather than adding a general system.

**Comment by logicalhan** [comment]
> @logicalhan can confirm, but I think the "bounded set of labels" and "metrics for generic nonResourceURL paths" are contradictory

Yeah, that's correct.

> I recommend just making a metric that counts what you want to monitor rather than adding a general system.

Yeah, this would probably be the easier approach..

**Comment by mtaufen** [comment]
Ok, thanks for the tips. I can see if I can add some feature-specific metrics.

If someone has a link to a kube-apiserver example, that'd be helpful.
