### ISSUE TITLE
[kube-controller-manager] Operation cannot be fulfilled, the object has been modified

### ISSUE THREAD

**Issue by kfirfer** [kubernetes/kubernetes#98605]
Kubernetes version: 1.20.2
Provisioned with kubeadm
Control plane nodes: 3
Worker nodes: 0

Im getting from `kube-controller-manager` component time-to-time this logs:

```
Unable to update status for kube-system/descheduler (rv = 6911157): Operation cannot be fulfilled on cronjobs.batch "descheduler": the object has been modified; please apply your changes to the latest version and try again
```

I also get those logs from different objects and different workloads

Don't know what is the root cause

**Comment by snowplayfire** [comment]
Maybe the reason is watch delay. https://github.com/kubernetes/kubernetes/issues/98692
