### ISSUE TITLE
Kubelet knob for housekeepingPeriod

### ISSUE THREAD

**Issue by hasethuraman2** [kubernetes/kubernetes#98607]
**What would you like to be added**:
Knob for housekeeping

**Why is this needed**:
https://github.com/kubernetes/kubernetes/blob/release-1.18/pkg/kubelet/kubelet.go#L145

When a node has 80-100 pods, and regularly the pod is being restarted for development purpose / crashloop/ other reasons for pod to get deleted and recreate; the housekeeping in syncloop takes between 15-45 seconds and sometimes 1.5mins when there is an issue on third party CRI. So by this time if the pod update channel receives many pod creation events, resulting the container creation delay and sometimes the creation starts after 30 mins and pod stuck in pending. The pod update channel is very slowly draining and one main factor is housekeepingPeriod.

If we have knob, till it is addressed in third party  CRI, it will be really helpful

**Comment by pacoxu** [comment]
https://github.com/google/cadvisor/blob/ef7e64f9efab1257e297d7af339e94bb016cf221/manager/container.go#L49

https://github.com/kubernetes/kubernetes/blob/8b7003aff4c81f124851041eafb8899ea7e83ffd/pkg/kubelet/kubelet.go#L139-L141

**Comment by pacoxu** [comment]
/remove-lifecycle rotten
/triage accepted

We have met an issue for `--volume-stats-agg-period` is by default 1m and there are so many du that cannot be finished in my node with many pods using some nfs/other volumes.
We decide to change it to 1h to make it use less process/cpu resources.

+1 for adding a flag. Currently, we may add it in `/var/lib/kubelet/config.yaml`.

**Comment by RPing** [comment]
@pacoxu have you already worked on this?
If no, I hope to try adding it.

**Comment by pacoxu** [comment]
I just give one possible idea on it and don't start on working it out.
Feel free to assign and work on it.
