### ISSUE TITLE
Completed job and Running pod have the same IP Address

### ISSUE THREAD

**Issue by kfirfer** [kubernetes/kubernetes#98611]
Kubernetes version: 1.20.2
Provisioned with kubeadm
Control plane nodes: 3
Worker nodes: 0

I don't think this is expected behavior, but Completed pod and Running pod has the same IP Address

```
$ kubectl get po --all-namespaces -o wide | grep 172.16.206.237             
kubernetes-dashboard   dashboard-metrics-scraper-8654549cdd-g8prs                  1/1     Running     0          3m8s    172.16.206.237    nuc03   <none>           <none>
monitoring             mysql-stack-mysqldump-1612029600-2rlcf                      0/1     Completed   0          5h15m   172.16.206.237    nuc03   <none>           <none>
```

Even though completed job isnt running, would be nice to see a config flag that avoid such thing

**Comment by gjkim42** [comment]
I would love to address this.
/assign

**Comment by gjkim42** [comment]
Previous works:
https://github.com/kubernetes/kubernetes/issues/47265
https://github.com/kubernetes/kubernetes/pull/47806

According to the previous works, displaying the last available IP of that pod is intended. However, I think we should show blank IP to users if that pod's IP is not available.

/sig node

**Comment by aojea** [comment]
ping @dcbw since he is the author of https://github.com/kubernetes/kubernetes/pull/47806 and may have a better understanding and more context

**Comment by BenTheElder** [comment]
Complete pods don't become running again, they can't actually use the IP..? Why would we exhaust the IP pool by letting complete pods continue to hold IPs?

**Comment by aojea** [comment]
> Why would we exhaust the IP pool by letting complete pods continue to hold IPs?

Those IPs are provided by CNI, and is an Status field, there is no exhaustion since those IPs are not hold by any Kubernetes components, are informative from the CRI/CNI subsystem.

**Comment by gjkim42** [comment]
> Complete pods don't become running again, they can't actually use the IP..? Why would we exhaust the IP pool by letting complete pods continue to hold IPs?

As @BenTheElder did, I think the users can misunderstand that the IPs are actually assigned if k8s shows the last available IP.

**Comment by aojea** [comment]
> As @BenTheElder did, I think the users can misunderstand that the IPs are actually assigned if k8s shows the last available IP.

... or others will want to know which IP was using that pod to check in the logs of other pod what happened ... I see this can go both ways :smile: , it seems easy to justify one or the other

**Comment by BenTheElder** [comment]
> As @BenTheElder did, I think the users can misunderstand that the IPs are actually assigned if k8s shows the last available IP.

Er no, I'm aware of the distinction between status of a completed pod an an in-use IP.

I did misunderstand this however:
> I don't think this is expected behavior, but Completed pod and Running pod has the same IP Address

A reader might think this suggests that we want to avoid a new pod to have the IP of a completed pod, which would I read as implying that completed pod IPs should continue to be reserved, which I do not think we should do.

I missed https://github.com/kubernetes/kubernetes/issues/98611#issuecomment-770370880 suggesting we should blank out the completed pod instead.

I think either of those would be a mistake.

Completed pods are no longer running and don't consume resources (except disk space on the host node, and etcd space for the object in API server). It's still very valid to want to know all of the details of the pod at its final space for debugging.

For example in Kubernetes's CI we dump the full pod details from our job like CR when a pod completes to permanent storage for follow-up debugging. I would want to continue to have the real IP of the pod for debugging purposes.

**Comment by kfirfer** [comment]
In my opinion is better giving the cluster administrator the ability to choose if the IPs will reserve or not will

**Comment by aojea** [comment]
> In my opinion is better giving the cluster administrator the ability to choose if the IPs will reserve or not

there is no IP reservation, take that as a logfile, it is just informative

**Comment by kfirfer** [comment]
now there is no capability to reserve , but would be nice to see a flag config (kubelet?) that holds them until the job object in etcd is deleted

**Comment by kfirfer** [comment]
nevermind , it does not do important , closing , if anyone want to have the ability to choose comment and ill reopen

thanks
