### ISSUE TITLE
[Failing Test] [sig-network] HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol

### ISSUE THREAD

**Issue by thejoycekung** [kubernetes/kubernetes#98648]
**Which jobs are failing**:
- `ci-kubernetes-e2e-ubuntu-gce`

**Which test(s) are failing**:
- `[sig-network] HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance]`

**Since when has it been failing**:
952e6f445

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-ubuntu-master-default

**Reason for failure**:
```
I0129 14:50:03.948] STEP: checking connectivity from pod e2e-host-exec to serverIP: 10.138.0.4, port: 54321
I0129 14:50:03.948] Jan 29 14:49:53.197: INFO: ExecWithOptions {Command:[/bin/sh -c curl -g --connect-timeout 5 http://10.138.0.4:54321/hostname] Namespace:hostport-5032 PodName:e2e-host-exec ContainerName:e2e-host-exec Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false Quiet:false}
I0129 14:50:03.948] Jan 29 14:49:53.198: INFO: >>> kubeConfig: /workspace/.kube/config
I0129 14:50:03.948] Jan 29 14:49:54.749: INFO: pods must have different hostname: pod1 has hostname pod2, pod2 has hostname pod2
I0129 14:50:03.949] Jan 29 14:49:54.750: FAIL: Failed to connect to exposed host ports
```

**Anything else we need to know**:
Related to #98299 

Spyglass link: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce/1355160798921494528

/sig network
/cc @aojea

**Comment by aojea** [comment]
/assign
So, this job is different that the one that we have in presubmit?
ping @BenTheElder

**Comment by aojea** [comment]
I see , this is in informing, the problem is that HostPort implementation in dockershim has a known bug, but since we started the deprecation is not worth the effort to fix it https://github.com/kubernetes/kubernetes/pull/94382

**Comment by liggitt** [comment]
the failing test is a conformance test ... are we saying that deployments using dockershim cannot be conformant in 1.20?

**Comment by BenTheElder** [comment]
> So, this job is different that the one that we have in presubmit?

I mean, the spec for a presubmit and any other type of job is not identical, so yes. But this job should more or less be the same IIRC.

**Comment by liggitt** [comment]
do any of our presubmits running this test use dockershim? cc @dims

**Comment by BenTheElder** [comment]
I don't think we are running blocking presubmits with dockershim currently, but we also can't run presubmits with all implementations of pluggable bits.

https://github.com/kubernetes/kubernetes/pull/94382#issuecomment-685188550 would seem to suggest we should actually fix dockershim though, i'm not sure where the implication otherwise is coming from.

**Comment by aojea** [comment]
To be clear, dockershim never passed this test, it only did because the test was wrong

**Comment by hasheddan** [comment]
Linking to a prior example of presubmit / periodic container runtime mismatch example (https://github.com/kubernetes/kubernetes/pull/96495). @liggitt @BenTheElder at the time we were working on the referenced bug we considered whether we should be consistent with various plugins we were testing against in presubmit vs periodic. However, in many cases such as this one, we are getting more coverage by testing against different ones. It would be nice to establish some policy around to what extent we test against various CRI / CNI / etc., similar to how we are formalizing our rigor around testing various platforms (https://github.com/kubernetes/sig-release/issues/1337).

**Comment by BenTheElder** [comment]
> Linking to a prior example of presubmit / periodic container runtime mismatch example (#96495). @liggitt @BenTheElder at the time we were working on the referenced bug we considered whether we should be consistent with various plugins we were testing against in presubmit vs periodic. 

In this case I don't think there's any mismatch, dockershim is just not in cluster e2e presubtmit

> However, in many cases such as this one, we are getting more coverage by testing against different ones. It would be nice to establish some policy around to what extent we test against various CRI / CNI / etc., similar to how we are formalizing our rigor around testing various platforms (kubernetes/sig-release#1337).

We've intentionally not advertised these to avoid some kind of favored vendor status or vendors trying to cram every last option into presubmit. SIG node started the policy of not supporting / endorsing / advertising any of the runtimes IIRC.

KIND goes one step further and ships a stripped down networking implementation ourselves.
