### ISSUE TITLE
Missing performance tests setup information

### ISSUE THREAD

**Issue by zorro786** [kubernetes/kubernetes#98659]
**What would you like to be added**: Currently there is no page/section which provides information on K8s cluster configuration for 5000 nodes [support claim](https://kubernetes.io/docs/setup/best-practices/cluster-large/) in v1.20.
Some things which are important but not limited to these:

1. Control plane network topology, node resources configuration
2. HA topology setup (external or stacked etcd)
2. etcd DB and disk storage size
3. Worker nodes configuration
4. Application workload
...

**Why is this needed**: 
1. Scale support numbers don't mean much without providing setup information.
2. Helps users compare scalability numbers from their own setups and contribute to the community.

**Comment by dims** [comment]
@zorro786 the support claim link says "No more than 5000 nodes" :) you can read more about the activities of sig-scalability here:
https://github.com/kubernetes/community/tree/master/sig-scalability#details-about-sig-scalability-sub-projects

Currently there is no plan to update the main documentation. Interested folks can reach out to the SIG. thanks! yes, we need more hands in this SIGs, if you are interested, please do help out.

/close

**Comment by zorro786** [comment]
@dims More appropriately "up to 5000 nodes" :). I can help out to update the documentation if you can provide details/pointers on where I can find the requested information. [Here](https://kubernetes.slack.com/archives/C09QZTRH7/p1612168294019100) is the thread I posted in #sig-scalability
