### ISSUE TITLE
Why need kube-apiserver to check etcd health when using kubernetes livenessProbe to detect kube-apiserver container

### ISSUE THREAD

**Issue by yangjunmyfm192085** [kubernetes/kubernetes#98662]
Why need kube-apiserver to check etcd health when using kubernetes livenessProbe to detect kube-apiserver container and
Why Set the timeout time to 2s？

	return func() error {
		if errMsg := clientErrMsg.Load().(string); len(errMsg) > 0 {
			return fmt.Errorf(errMsg)
		}
		client := clientValue.Load().(*clientv3.Client)
		ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
		defer cancel()
		// See https://github.com/etcd-io/etcd/blob/c57f8b3af865d1b531b979889c602ba14377420e/etcdctl/ctlv3/command/ep_command.go#L118
		_, err := client.Get(ctx, path.Join("/", c.Prefix, "health"))
		if err == nil {
			return nil
		}
		return fmt.Errorf("error getting data from etcd: %v", err)
	}, nil

**Comment by neolit123** [comment]
https://github.com/kubernetes/kubernetes/blob/e9dba7a627520f89778b367fc0d955776f220638/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go#L90

**Comment by yangjunmyfm192085** [comment]
I think apiserver does not need to detect etcd.
The negative impact of detection is greater than the positive.
Need fix it?
I can fix it.

**Comment by lavalamp** [comment]
Please don't change the liveness code, a lot of installations depend on it being the way it is even if that doesn't make much sense.

You can turn off individual checks (if that makes sense in your installation) by passing query parameters to the healthz/livez/readyz pages.
