### ISSUE TITLE
[Failing Test] ci-cloud-provider-openstack-acceptance-test-e2e-conformance Overall reporting fails

### ISSUE THREAD

**Issue by n3wscott** [kubernetes/kubernetes#98666]
**Which jobs are failing**:

`Overall` on ci-cloud-provider-openstack-acceptance-test-e2e-conformance

**Which test(s) are failing**:

The tests pass but the end of the script fails to report correctly. Maybe out of date? See this message:

```
k/k version of the log-dump.sh script is deprecated!
Please migrate your test job to use test-infra's repo version of log-dump.sh!
Migration steps can be found in the readme file.
----------------------------------------------------------------------------------------------------
Sourcing kube-util.sh
Detecting project
Skeleton Provider: detect-project not implemented
```

**Since when has it been failing**:

Jan 18, 2021

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-informing#Conformance%20-%20OpenStack
see
- https://prow.k8s.io/view/gcs/k8s-conformance-openstack/periodic-logs/ci-cloud-provider-openstack-acceptance-test-e2e-conformance/1611497393
- https://prow.k8s.io/view/gcs/k8s-conformance-openstack/periodic-logs/ci-cloud-provider-openstack-acceptance-test-e2e-conformance/1611410914
- https://prow.k8s.io/view/gcs/k8s-conformance-openstack/periodic-logs/ci-cloud-provider-openstack-acceptance-test-e2e-conformance/1611583703

**Reason for failure**:

```
Ran 305 of 5667 Specs in 7762.529 seconds
SUCCESS! -- 305 Passed | 0 Failed | 0 Pending | 5362 Skipped
PASS

Ginkgo ran 1 suite in 2h9m24.225229479s
Test Suite Passed
Checking for custom logdump instances, if any
----------------------------------------------------------------------------------------------------
k/k version of the log-dump.sh script is deprecated!
Please migrate your test job to use test-infra's repo version of log-dump.sh!
Migration steps can be found in the readme file.
----------------------------------------------------------------------------------------------------
Sourcing kube-util.sh
Detecting project
Skeleton Provider: detect-project not implemented
Dumping logs from master locally to '/home/zuul/workspace/logs/kubernetes'
Skipping dumping of node logs
Jan 23 17:03:58.999: DONE
```

**Anything else we need to know**:

This job has not been running in the last week (since 1/25/2021)

According to https://testgrid.k8s.io/sig-release-master-informing#Conformance%20-%20OpenStack&grid=old the jobs are still passing. Is there a new way to report to testgrid that this job is not using?

**Comment by thejoycekung** [comment]
cc @michelle192837 you might know something about this?
I remember we had an opposite issue here: https://github.com/GoogleCloudPlatform/testgrid/issues/248

**Comment by mkorbi** [comment]
are there any actions planned? the job fails frequently and the test called pod quits at every run
