### ISSUE TITLE
ensure secret pulled images

### ISSUE THREAD

**Issue by mikebrow** [kubernetes/kubernetes#98665]
**What would you like to be added**:
Support for ensuring images pulled with pod imagePullSecrets are always authenticated even if cached. With this feature always pull would not be required to ensure authentication for images pulled with secrets based auth. Instead kublet will check if the image was pulled with an image pull secret and if so would force a pull of the image to ensure the image pulled with the secret is not used by another pod unless that pod also has the proper auth.

**Why is this needed**:
Some images require pull secrets in order to be used by the Kubelet. Pull secrets are per namespace. Imagine the following scenario:

If a pod in namespaceA has valid pull secrets for foo/bar:stable, when it is scheduled to a given node, the Kubelet uses the pull secrets to pull the image to the node
If a pod in namespaceB also refers to foo/bar:stable but does not have valid pull secrets for it, if it happens to be scheduled to the same node as the pod in step 1, the Kubelet respects the image pull policy
Because the image already exists on the node, if the pull policy is Never or IfNotPresent, the Kubelet runs the pod, even though namespaceB shouldn't be able to use that image.

Carry over for issue #18787
Enhancement: https://github.com/kubernetes/enhancements/pull/1608
PR: https://github.com/kubernetes/kubernetes/pull/94899

**Comment by adisky** [comment]
closing this issue as the tracking issue for the KEP as I have opened a tracking issue in k/enhancements
/close
