### ISSUE TITLE
Windows nodes behind Loadbalancer going OutOfService when the no. of pods is 65 or more

### ISSUE THREAD

**Issue by lalwanin2020** [kubernetes/kubernetes#98680]
**What happened**: 
When the number of windows pods in the Kubernetes cluster are scaled to a number of 65 or more, then the Windows nodes behind a classic loadbalancer service are going OutOfService. A kube-proxy error was reported in the logs which is as follows: "E1208 04:52:16.756196 4268 proxier.go:1212] Policy creation failed: hcnCreateLoadBalancer failed in Win32: The parameter is incorrect. (0x57) {"Success":false,"Error":"The parameter is incorrect. Unable to initialize VFP LB rule: invalid number of destinations.","ErrorCode":2147942487}"   

**What you expected to happen**:
We expected the windows pods to scale beyond 65 without the Windows nodes behind the loadbalancer reporting their status as OutOfService or nodes becoming unhealthy.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an AWS EKS Cluster with Windows support.
2. Scale the number of nodes to a number that supports 66 pods or more.
3. Deploy a sample Windows application with 65 replicas. You will be able to see the issue in the LoadBalancer section.
4. Scaling the number of deployments back to 64 or less, will revert the status of EKS Windows nodes back to InService.

**Anything else we need to know?**:
1. Enabling DSR (Direct Server Return) mode on all the Windows nodes didn't solve the issue.
2. Enabling Jumbo frames on all the Windows nodes didn't solve the issue.

**Environment**:
- Kubernetes version (use `kubectl version`): "v1.18.0"
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g: `cat /etc/os-release`): Windows Server 2004 Core
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig windows

**Comment by jsturtevant** [comment]
@lalwanin2020 Is this using docker?  

@daschott are you aware of this?

**Comment by lalwanin2020** [comment]
@jsturtevant Yes the windows worker nodes are using Docker.

**Comment by daschott** [comment]
This is indeed a limitation in the Windows OS and a change has to go through Microsoft. 

Can you file a feature request on Windows containers repo with details of your scenario? 
https://github.com/microsoft/Windows-Containers/issues

**Comment by lalwanin2020** [comment]
Thank you for the reply. I have opened the issue for a feature request on the Microsoft Windows Containers repo.

**Comment by perithompson** [comment]
@daschott is this also the case with containerd?

**Comment by daschott** [comment]
Yes, on Windows a single service can only support up to 64 backend pods / unique destination IPs

**Comment by perithompson** [comment]
I thought this probably should be called out in the [docs](https://github.com/kubernetes/website/pull/26465)

**Comment by jsturtevant** [comment]
this is limitation of the Windows OS and the feature will be tracked in microsoft/Windows-Containers#93.  If anyone comes across this later and has use cases or urgent needs please update that issue so we can collect information for prioritization at the OS layer

Thanks @perithompson for updating the docs!

/close

**Comment by daschott** [comment]
[KB5011551](https://support.microsoft.com/en-us/topic/march-22-2022-kb5011551-os-build-17763-2746-preview-690a59cd-059e-40f4-87e8-e9139cc65de4) released to support >64 backends per Kubernetes service (up to 1024)
