### ISSUE TITLE
In CSI Migration, volumes attached before migration will be re-attach（detached by in-tree plugin and then attached by csi driver）and re-mount when upgrading kubelet to migration version

### ISSUE THREAD

**Issue by ivan-cai** [kubernetes/kubernetes#98687]
**What would you like to be added**:
When upgrading kcm and kubelet to migration version，the volumes those attached before migration will not be re-attach(detached by in-tree plugin and then attached by csi driver) and re-mount(unmounted by in-tree plugin and then mounted by csi driver) .

**Why is this needed**:
We also have a in-tree volume plugin，we want to support csi migration，and volumes attached before migration will not be re-attach and re-mount. Sometimes, if application is writing volume，some problems will happen while detaching/unmounting.

The ad controller logic when we upgrading kcm and kubelet：
- At first，we will upgrade `kube-controller-manager` to migration version，with feature gate `CSIMigrationQcloudCbsComplete` will be set to "false"
    - now, volumename in `asw` and `dsw` both are in-tree（e.g.  kubernetes.io/qcloud-cbs/disk-3l07ikyo） 
- then, we upgrade one `kubelet` to  migration version，`desiredStateOfWorldPopulator` in `kube-controller-manager` will add csi volumename(kubernetes.io/csi/com.tencent.cloud.csi.cbs^disk-3l07ikyo) to dsw。（because `isCSIMigrationSupportedOnNode` will be "true"。volumespec in`dsw` will be translate to csi, volumename also with csidrivername）
- at the end，`reconciler` in ad controller will detach kubernetes.io/qcloud-cbs/disk-3l07ikyo and then attach kubernetes.io/csi/com.tencent.cloud.csi.cbs^disk-3l07ikyo. The same thing also happen in volumemanager.(unmount/mount)

 Is it a design flaws？How to not affect the writing applications in migration upgrading phase.

**Comment by ivan-cai** [comment]
kind/bug

**Comment by ivan-cai** [comment]
@sig-storage

**Comment by ivan-cai** [comment]
@saad-ali @jsafrane

**Comment by ivan-cai** [comment]
@saad-ali @jsafrane pls!

**Comment by jsafrane** [comment]
It seems that you're restarting kubelet with migration enabled without draining the node first. This is not supported, please check the upgrade / feature enablement procedure in https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/csi-migration.md#upgradedowngrade-migrateunmigrate-scenarios

Draining the nodes before flipping the feature gate is important to unmount / detach the volumes in the "in-tree" way and as result the disappear both in attach-detach controller and kubelet mount manager caches.

**Comment by ivan-cai** [comment]
@jsafrane Thank you very much. But if should we have a mechanism to upgrade to migration without restarting pod and detaching volume？I think it is a necessary feature. In upgrading phase, we hope the upgrade is lossless，hope not affect anyone pod.

**Comment by jsafrane** [comment]
No, it is not possible to have CSI migration without node drain. We though hard about it when designing CSI migration - It's quite complex already now, when it's somehow hidden in the volume plugins. If we fully exposed it to A/D controller and kubelet, it would be unmanageable and very error prone.

Even during regular upgrade you should take nodes one by one and drain them, upgrade kubelet and uncordon them: https://kubernetes.io/docs/tasks/administer-cluster/cluster-upgrade/#manual-deployments. CSI migration enablement requires exactly the same process, so you can reuse your tooling.

**Comment by ivan-cai** [comment]
@jsafrane Thank you very much.
