### ISSUE TITLE
After a container is restarted docker ps shows the image ID instead of the repository name

### ISSUE THREAD

**Issue by 2ZZ** [kubernetes/kubernetes#98689]
**What happened**:
When a container is terminated due to error the replacement container shows the docker image id instead of the repository name in the image field of docker ps. This behaviour changed after moving from Amazon EKS 1.15 to Amazon EKS 1.18.

```
## Column 2 shows the image name correctly
docker ps | grep k8s_myapp
14e0a8cf7b09        docker-registry.xxx/myapp     "/bin/sh -c /docker-…"   4 hours ago         Up 4 hours                              k8s_myapp_myapp-f74749454-4mddp_dev_4ecb6d25-5049-4742
-b56e-5d6435e2b0af_0

## Force the container to be recreated
docker exec -it 14e0a8cf7b09 bash
kill -9 1

## Replacement container shows image id in column 2 rather than the image name
docker ps | grep k8s_myapp
d30d1d3c7df8        0b96a74c44db                                                             "/bin/sh -c /docker-…"   1 second ago        Up Less than a second                       k8s_myapp_myapp-f74749454-4mddp_dev_4ecb6d25-5049-
4742-b56e-5d6435e2b0af_1

## 0b96a74c44db == docker-registry.xxx/myapp
docker images | grep 0b96a74c44db
docker-registry.xxx/myapp     fc048298608ebea82474cd8c4aaa73fd44d98af3   0b96a74c44db        7 weeks ago         335MB
```

**What you expected to happen**:
The container retains the same information in column 2

**How to reproduce it (as minimally and precisely as possible)**:
As above

**Anything else we need to know?**:
n/a

**Environment**:
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: Amazon EKS
- OS (e.g: `cat /etc/os-release`): Amazon Linux 2
- Kernel (e.g. `uname -a`): 4.14.198-152.320.amzn2.x86_64
- Network plugin and version (if this is a network-related bug): aws-cni

**Comment by neolit123** [comment]
> Cloud provider or hardware configuration: Amazon EKS

please communicate this with the EKS support team first.
if they confirm this as an upstream k8s bug, you can reopen this ticket.

/close
