### ISSUE TITLE
Tools for evaluating dependency updates to Kubernetes

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#98698]
NOTE: This is part of the [LFX mentorship program](https://www.cncf.io/blog/2021/02/03/cncf-lfx-projects-are-open-for-spring-term-2021-apply-now-for-a-mentorship-opportunity/)

Implement command line utilities that can help Kubernetes developers evaluate new dependencies by capturing statistics/metrics and estimating cost of adding something new. This will involve diving deep into golang dependency chains (transitive/shared dependencies) and coming up with new metrics to estimate how burdensome something new can be or how much we will save by getting rid of something so we can prioritize work and get more efficient from a developer workflow perspective.

For more context see these [code-organization meeting notes](https://docs.google.com/document/d/1HtTI0rJEGP_MSf6eO87aCmx_tzpovPAAg7U2Zxwm8FE/edit?ts=5c9d0a4c#heading=h.gw9a54igofrk) and this [one](https://docs.google.com/document/d/1HtTI0rJEGP_MSf6eO87aCmx_tzpovPAAg7U2Zxwm8FE/edit?ts=5c9d0a4c#heading=h.d9wef8aemxoa)

![image](https://user-images.githubusercontent.com/23304/106650408-de8d4c80-6560-11eb-9500-e554cdb36425.png)

**Comment by alenkacz** [comment]
OMG this is amazing, I want this. I've spent last couple of weeks upgrading bunch of kubernetes related deps in several projects and I was thinking about something like this a lot. 🙏 

I wish I could work on this :)

**Comment by dims** [comment]
Prior art / background research:
- https://github.com/kubernetes/kubernetes/issues/76395
- https://golang.org/ref/mod (search for "go list")
- https://seankhliao.com/blog/12020-10-03-go-list-patterns/
- https://www.alexedwards.net/blog/an-overview-of-go-tooling
- https://github.com/loov/goda
- https://github.com/KyleBanks/depth
- https://github.com/google/godepq

**Comment by navidshaikh** [comment]
I've some experience in writing command line utilities and I'd like to collaborate on this. Going to parse the references linked above.

**Comment by alenkacz** [comment]
@navidshaikh feel free to sign up to this project via https://www.cncf.io/blog/2021/02/03/cncf-lfx-projects-are-open-for-spring-term-2021-apply-now-for-a-mentorship-opportunity/ if you're interested in this

**Comment by abhaykatheria** [comment]
I think if we can get the metadata of all the dependencies (existing and the new one) using [goda](https://github.com/loov/goda/), and then classify them as incoming or shared.
After getting the metadata we can create a report with some investigatory features like :
- sort by  LoC.
- sort by no. of deps (new incoming deps)
- and maybe some other metric.

Then to make it less sore to the eyes, create an HTML report for the same with a dependency graph and features listed above, it can also have links to the respected module repositories where developers can go check out how active the module development is. 
After proper investigation developer can decide whether or not to bring in the new dep.
Please point out if I am missing something. 
P.S: I am writing this under the assumption that we are currently only concerned with adding new modules not deleting them.

**Comment by dims** [comment]
@abhaykatheria good find, yes we want to highlight cost of adding things, but also celebrate the wins when we drop something.

**Comment by hammad13060** [comment]
I'd like to contribute to this issue. How can I get started?

**Comment by RinkiyaKeDad** [comment]
@dims can we close this now? 🙂

**Comment by dims** [comment]
yes! thanks a ton @RinkiyaKeDad 

/close
