### ISSUE TITLE
Kubectl get pod cannot be displayed. Client go can get it correctly

### ISSUE THREAD

**Issue by aimuz** [kubernetes/kubernetes#98714]
**What happened**:

I have a problem. I don't know if this description is correct. I use `informers`, and I get the data by calling it

This is an a'p `informers` based on information

![image](https://user-images.githubusercontent.com/17666471/106706033-f7156980-6629-11eb-9ac2-27e4fad2a9bd.png)

Until I got the data through kubectl, I found that their data were not consistent

```bash
kubectl -n wisecloud-controller get pod
```
![image](https://user-images.githubusercontent.com/17666471/106705455-f29c8100-6628-11eb-8149-ed378ee83f1a.png)

I get the same data through API server

![image](https://user-images.githubusercontent.com/17666471/106705566-2a0b2d80-6629-11eb-80bf-991e7d5a7cf7.png)

Until now, I can get the same data as `informers` by setting the `resourceversion` parameter

![image](https://user-images.githubusercontent.com/17666471/106705589-37c0b300-6629-11eb-8708-7f26f6dfbb55.png)

By checking, `replicaset` also processes this data

![image](https://user-images.githubusercontent.com/17666471/106706623-eadddc00-662a-11eb-96ab-035f4fca024c.png)

![image](https://user-images.githubusercontent.com/17666471/106706606-e31e3780-662a-11eb-9730-4cd6bdd5da0c.png)

The only difference between them is that **ui-7f594b7ffc-c475t**

I checked the endpoints again, and he also dealt with it normally，And '10.42.1.195' is the IP of 'ui-7f594b7ffc-c475t'

![image](https://user-images.githubusercontent.com/17666471/106706863-44dea180-662b-11eb-9d16-42294fe70c6c.png)

And I set nodeport for service, so I can access it normally

I tried to delete the container from the host in the past. After a while, I found that the container was rebuilt, but the 'service' could not be accessed normally

I also tried to delete 'replicaset', but the pod did not change

For these problems, I just modified a mirror image, and I don't know how to reproduce it.

**What you expected to happen**:

**ui-7f594b7ffcc-c475t** Will be deleted

**How to reproduce it (as minimally and precisely as possible)**:

To be honest, I don't know how to reproduce it. I just updated a deployment image

**Anything else we need to know?**:

I use ` v1.19.3+k3s2`, 

If you need additional information, please feel free to contact me

**Environment**:
- Kubernetes version (use `kubectl version`):
   ```
    Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
    Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3+k3s2", GitCommit:"f8a4547bec36b4d1597c19c86b5063756d4c150e", GitTreeState:"clean", BuildDate:"2020-10-30T19:30:45Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by yliaog** [comment]
could you check the status of ui-7f5fd98579-zwl5q when you use client-go to get it? that would help understand what state ui-7f5fd98579-zwl5q was at, and why it was not present using kubectl, but showed up using client-go.

**Comment by aimuz** [comment]
`client-go` Yes, it can be obtained

**Comment by aimuz** [comment]
When I restart the host, I find that kubectl can get the data, and apiserver also returns the correct data, but I think this is a problem.
