### ISSUE TITLE
apiserver making unnecessary log rows

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kubernetes#98720]
**What happened**: we are running apiserver with loglevel 1. However, we are seeing still quite much logs coming from apiserver. ~1800 rows/hour in empty cluster (3 masters, so one apiserver making ~600 rows/hour)

Example:
```
I0203 10:14:19.900720       1 client.go:360] parsed scheme: "passthrough"
I0203 10:14:19.900827       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://127.0.0.1:4001  <nil> 0 <nil>}] <nil> <nil>}
I0203 10:14:19.900852       1 clientconn.go:948] ClientConn switching balancer to "pick_first"
I0203 10:14:39.006912       1 client.go:360] parsed scheme: "passthrough"
I0203 10:14:39.007410       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://127.0.0.1:4002  <nil> 0 <nil>}] <nil> <nil>}
I0203 10:14:39.007496       1 clientconn.go:948] ClientConn switching balancer to "pick_first"
I0203 10:15:04.039426       1 client.go:360] parsed scheme: "passthrough"
I0203 10:15:04.039475       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://127.0.0.1:4001  <nil> 0 <nil>}] <nil> <nil>}
I0203 10:15:04.039486       1 clientconn.go:948] ClientConn switching balancer to "pick_first"
I0203 10:15:18.503137       1 client.go:360] parsed scheme: "passthrough"
I0203 10:15:18.503646       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://127.0.0.1:4002  <nil> 0 <nil>}] <nil> <nil>}
I0203 10:15:18.503746       1 clientconn.go:948] ClientConn switching balancer to "pick_first"
I0203 10:15:35.433542       1 client.go:360] parsed scheme: "passthrough"
I0203 10:15:35.434150       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://127.0.0.1:4001  <nil> 0 <nil>}] <nil> <nil>}
I0203 10:15:35.434266       1 clientconn.go:948] ClientConn switching balancer to "pick_first"
I0203 10:15:51.576054       1 client.go:360] parsed scheme: "passthrough"
I0203 10:15:51.576135       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://127.0.0.1:4002  <nil> 0 <nil>}] <nil> <nil>}
I0203 10:15:51.576169       1 clientconn.go:948] ClientConn switching balancer to "pick_first"
I0203 10:16:15.297590       1 client.go:360] parsed scheme: "passthrough"
I0203 10:16:15.298185       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://127.0.0.1:4001  <nil> 0 <nil>}] <nil> <nil>}
I0203 10:16:15.298208       1 clientconn.go:948] ClientConn switching balancer to "pick_first"
I0203 10:16:28.082442       1 client.go:360] parsed scheme: "passthrough"
I0203 10:16:28.082472       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://127.0.0.1:4002  <nil> 0 <nil>}] <nil> <nil>}
I0203 10:16:28.082479       1 clientconn.go:948] ClientConn switching balancer to "pick_first"
```

**What you expected to happen**: I expect that if we run apiserver with loglevel 1 we should only see log rows that we are interested of and are important. As I see it, these log rows are not really important and should not be visible.

**How to reproduce it (as minimally and precisely as possible)**: put apiserver to loglevel 1 and check the log files after that.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.2
- Cloud provider or hardware configuration: openstack
- OS (e.g: `cat /etc/os-release`): debian buster
- Kernel (e.g. `uname -a`):
- Install tools: kops
- Network plugin and version (if this is a network-related bug):
- Others:

/kind bug

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/issues/95893 and https://github.com/kubernetes/kubernetes/issues/98778

**Comment by BenTheElder** [comment]
Any update on this? This makes debugging more painful. There's a *lot* of noise. cc @thockin.

**Comment by zetaab** [comment]
@BenTheElder the problem is that these log rows are not coming from this repository. Instead these are coming from vendor/google.golang.org/grpc

for instance 
```
I0203 10:15:35.434266       1 clientconn.go:948] ClientConn switching balancer to "pick_first"
```

is coming from https://github.com/kubernetes/kubernetes/blob/v1.20.2/vendor/google.golang.org/grpc/clientconn.go#L674

https://pkg.go.dev/google.golang.org/grpc/grpclog#Infof ... which means that it does not matter what loglevel that lib has, it will be always printed still.

they have changed logging stuff in latest grpc-go https://github.com/grpc/grpc-go/blob/master/clientconn.go#L707 and there are some new env variables https://github.com/grpc/grpc-go#how-to-turn-on-logging but no idea can those still be ignored. perhaps not

**Comment by BenTheElder** [comment]
I don't think GRPC logs klog style lines on its own?, wherever we have the logging adapter we could handle this on our end.

**Comment by BenTheElder** [comment]
Our shim should probably map GCPC info => V(N) for some N > 1.

**Comment by zetaab** [comment]
I found similar issue with PR https://github.com/kubernetes/kubernetes/pull/84061 I think it could solve this issue also.

**Comment by liggitt** [comment]
still an issue after update to etcd 3.5.0 and latest grpc in https://github.com/kubernetes/kubernetes/pull/100488

**Comment by liggitt** [comment]
@gyuho @ptabor is there a recommended way to quiet the etcd client logs with the new logging setup in 3.5.0?

**Comment by liggitt** [comment]
potential solution in https://github.com/kubernetes/kubernetes/pull/102896

**Comment by ptabor** [comment]
@liggitt @serathius 
Do you understand the source of this logs ? 

From the high-level glance they might be a syndrome / optimization opportunity: 

1. etcd-3.5. configures clientv3 to use 'roundrobin' balancer by default: 
  https://github.com/etcd-io/etcd/blob/76df94a8399eafb48eb8a02d6b1b90868d6b4277/client/v3/internal/resolver/resolver.go#L43
    is it aware decision of api-server to override it to 'pick_first' ? Or the logs are from pre-3.4 and the 3.5 spams with different messages ? 

2. I assume each of this log-lines is somewhat related to creation of clientv3 object instances (or at least connection management within each client, that do not share the connections pool). Taking in consideration that mTLS shandhake on connection is computationally costly, there might be an area for perf improvement.

**Comment by serathius** [comment]
Integration with third party logging should be in scope of SIG Instrumentation and WG structured logging.
/sig instrumentation
/wg structured-logging

**Comment by liggitt** [comment]
> 1. is it aware decision of api-server to override it to 'pick_first' ? Or the logs are from pre-3.4 and the 3.5 spams with different messages ?

the API server sets up the etcd client here, and doesn't override options like that:

https://github.com/kubernetes/kubernetes/blob/0bc75afcf262e20a23966c10a3224f8acd1cc117/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go#L153-L162

The specific messages in the description were from an older etcd client, the messages were different in 3.5.0, but still spammy

> Integration with third party logging should be in scope of SIG Instrumentation and WG structured logging.

the issue with excessive logging is resolved. If we want a different issue to track log integration, let's open one specifically for that purpose.

/close

**Comment by KeithTt** [comment]
It seems I should upgrade kubernetes version to 1.22 to solve this problem...
