### ISSUE TITLE
Addon manager defaults prune whitelist to extensions/v1beta1 Ingress

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#98723]
**What happened**:

Sweeping uses of extensions/v1beta1 in preparation for [stopping serving this API group in 1.22](https://github.com/kubernetes/kubernetes/issues/43214), the addon manager stood out as using extensions/v1beta1 Ingress by default:

```
		*pruneResources = []pruneResource{
			{"", "v1", "ConfigMap", true},
			{"", "v1", "Endpoints", true},
			{"", "v1", "Namespace", false},
			{"", "v1", "PersistentVolumeClaim", true},
			{"", "v1", "PersistentVolume", false},
			{"", "v1", "Pod", true},
			{"", "v1", "ReplicationController", true},
			{"", "v1", "Secret", true},
			{"", "v1", "Service", true},
			{"batch", "v1", "Job", true},
			{"batch", "v1beta1", "CronJob", true},
			{"extensions", "v1beta1", "Ingress", true},
			{"apps", "v1", "DaemonSet", true},
			{"apps", "v1", "Deployment", true},
			{"apps", "v1", "ReplicaSet", true},
			{"apps", "v1", "StatefulSet", true},
		}
```

```
  KUBECTL_PRUNE_WHITELIST=(
    core/v1/ConfigMap
    core/v1/Endpoints
    core/v1/Namespace
    core/v1/PersistentVolumeClaim
    core/v1/PersistentVolume
    core/v1/Pod
    core/v1/ReplicationController
    core/v1/Secret
    core/v1/Service
    batch/v1/Job
    batch/v1beta1/CronJob
    apps/v1/DaemonSet
    apps/v1/Deployment
    apps/v1/ReplicaSet
    apps/v1/StatefulSet
    extensions/v1beta1/Ingress
  )
```

**What you expected to happen**:

All components shipped in 1.21 must use networking.k8s.io/v1 Ingress in order to work properly against a 1.22 API server.

/sig networking

cc @MrHohn per cluster/addons/addon-manager/OWNERS
cc @robscott 

I'm not sure what the addon manager does if given a prune list of networking.k8s.io/v1 Ingress objects while still using a manifest containing extensions/v1 Ingress objects... this needs to be tested.

/milestone v1.21
/priority important-soon
/lifecycle frozen

**Comment by rikatz** [comment]
@liggitt how "urgent" is this? Can wait until next tuesday? Otherwise I can work on the tests this weekend :)

**Comment by liggitt** [comment]
important, not urgent. it should happen early in the 1.21 cycle, but does not require work out of business hours

**Comment by erismaster** [comment]
Hello! I am from the Bug Triage team! This issue has not been updated for a few weeks, so I'd like to check on the status. Code freeze is starting March 9th, 2021 (about 1 week from now). We want to ensure that each PR has a chance to be merged before code freeze.
As the Issue is tagged for 1.21, is it still planned for this release?

**Comment by rikatz** [comment]
@erismaster we're waiting to the PR to get merged :) 

I guess it's important for the v1.21 release, for the sake of extensions apiGroup deprecation :)

Will ping reviewers on the PR
