### ISSUE TITLE
Can't create a new ServiceAccount for Kubernetes v1.20.2

### ISSUE THREAD

**Issue by vacheli** [kubernetes/kubernetes#98743]
**What happened**:
```
ubuntu@master01:~$ kubectl create sa tt -n velero
Error from server (Forbidden): serviceaccounts "tt" is forbidden: unable to create new content in namespace velero because it is being terminated
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
```
1. Installing Velero
2. kubectl delete namespace velero
3. kubectl get namespace velero -o json > logging.json
4. Remove `kubernetes` from the `finalizers` array:
5. kubectl replace --raw "/api/v1/namespaces/velero/finalize" -f ./logging.json
```
**Anything else we need to know?**:

```
kubectl get namespace velero -o json > logging.json
Remove `kubernetes` from the `finalizers` array:
kubectl replace --raw "/api/v1/namespaces/velero/finalize" -f ./logging.json

ubuntu@master01:~$ kubectl get ns
NAME              STATUS   AGE
default           Active   19d
kube-node-lease   Active   19d
kube-public       Active   19d
kube-system       Active   19d
velero            Active   16d
```
**Environment**:
- Kubernetes version (use `kubectl version`): v1.20.2
- Cloud provider or hardware configuration: 2c 4g
- OS (e.g: `cat /etc/os-release`):  20.04.1 LTS (Focal Fossa)
- Kernel (e.g. `uname -a`): 5.4.0-60-generic
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
It seems to be expected as the message supposed `unable to create new content in namespace velero because it is being terminated`.  And you may see more information here in comments of https://github.com/kubernetes/kubernetes/issues/96793#issuecomment-732637004

**Comment by vacheli** [comment]
> It seems to be expected as the message supposed `unable to create new content in namespace velero because it is being terminated`. And you may see more information here in comments of [#96793 (comment)](https://github.com/kubernetes/kubernetes/issues/96793#issuecomment-732637004)

**Comment by vacheli** [comment]
> It seems to be expected as the message supposed `unable to create new content in namespace velero because it is being terminated`. And you may see more information here in comments of [#96793 (comment)](https://github.com/kubernetes/kubernetes/issues/96793#issuecomment-732637004)

It's different from this, I  can't create a new ServiceAccount in velero namespace that is active status.

**Comment by neolit123** [comment]
please ask the Valero maintainers:
https://github.com/vmware-tanzu/velero
this doesn't seem like a bug in core k8s.

/close
