### ISSUE TITLE
job failed but active is still 1

### ISSUE THREAD

**Issue by jshen28** [kubernetes/kubernetes#98741]
**What happened**:

As shown below, job succeeded but active is , and it appears to be no job related port existing

```console
# kubectl get job -n rook-ceph rook-ceph-osd-prepare-storage03 -ojson | jq '.status'
{
  "active": 1,
  "completionTime": "2020-05-26T06:45:53Z",
  "conditions": [
    {
      "lastProbeTime": "2020-05-26T06:45:53Z",
      "lastTransitionTime": "2020-05-26T06:45:53Z",
      "status": "True",
      "type": "Complete"
    }
  ],
  "startTime": "2020-05-26T06:35:44Z",
  "succeeded": 1
}
```

**What you expected to happen**:

Either succeeded or active not both set.

**How to reproduce it (as minimally and precisely as possible)**:

No idea...

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): "v1.14.3"
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): ubuntu 18.04.2 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`):  4.15.0-45-generic
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
> Kubernetes version (use kubectl version): "v1.14.3"

this version has been out of support for a long time.
please try to reproduce with 1.18+ and reopen if this is still a problem.

/close
