### ISSUE TITLE
A single scoring plugin for node resources

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#98746]
We have four score plugins that implement different strategies for preferred resource allocation. Those plugins should not be enabled together, only one.

I propose we deprecate those and combine them under one Score plugin, the same one used for filtering (`NodeResourcesFit`), and add a `FitStrategy` parameter to `NodeResourcesFit` that allows users to select which exact scoring strategy to run.

I also suggest that we go ahead and implement four other strategies: `LeastAllocatable`, `MostAllocatable`, `BestFit` and `WorstFit`. The first two are basically a graduation of https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/pkg/noderesources, the latter two are common scheduling placement strategies that k8s currently don't support. `BestFit` for example is important to achieve higher utilization in clusters that have different VM shapes. 

In the future, I think we can explore adding `FitStrategy` to the pod spec, and make it a workload parameter rather than a static scheduler configuration. This can be useful when we have a mix of serving and batch workloads running on the same cluster. Although scheduling profiles may be an alternative for this, albeit a less flexible one.

Previous discussion on this topic: https://github.com/kubernetes/kubernetes/issues/93547

/sig scheduling

**Comment by Huang-Wei** [comment]
ref: https://github.com/kubernetes/enhancements/pull/2144

**Comment by yuzhiquan** [comment]
It's likely already has an sample plugin in [scheduler-plugins/#36](https://github.com/kubernetes-sigs/scheduler-plugins/pull/36), it;s reimplement for that plugin?

**Comment by alculquicondor** [comment]
SGTM.

Should we hold v1beta2 component config to next release to account for this?

**Comment by ahg-g** [comment]
> Should we hold v1beta2 component config to next release to account for this?

I would hold it, any downsides to delaying it?

**Comment by alculquicondor** [comment]
not really, we are not under pressure of API deprecation like REST APIs are

**Comment by ahg-g** [comment]
> ref: [kubernetes/enhancements#2144](https://github.com/kubernetes/enhancements/pull/2144)

Ah, I missed this one. The above proposal tries to support every single combination, which I think is an overkill. 

We can make reasonable assumptions that we bake into each strategy to avoid the over-proliferation of options. For example, `LeastAllocatable` is always associated with `LeastAllocated` as a second scoring key (as in nodes with the same least allocatable are differentiated by least allocated)

**Comment by alculquicondor** [comment]
Should we have a KEP for this?

**Comment by ahg-g** [comment]
Yes, I was thinking we could target 1.22

**Comment by ahg-g** [comment]
I can put a KEP together in an hour, do we have time to review and merge before the deadline tomorrow? I don't think this needs PRR if we focus this cycle on the config API change to support existing plugins through `NodeResourcesFit`, wdyt?

**Comment by ahg-g** [comment]
this will help us deprecate the existing plugins in v1beta2 in 1.22 if all goes to plan and the community is happy with the new api.

**Comment by alculquicondor** [comment]
Fine with me to do a review last minute, but PRR is a hard requirement now.

**Comment by ahg-g** [comment]
ok, lets leave it to 1.22 then..

**Comment by damemi** [comment]
> In the future, I think we can explore adding FitStrategy to the pod spec, and make it a workload parameter rather than a static scheduler configuration.

+1 this as a longer-term goal, I like exposing scheduler config options in the pod spec because it gives users better control over their app placement.

**Comment by ahg-g** [comment]
I opened https://github.com/kubernetes/enhancements/issues/2458

**Comment by alculquicondor** [comment]
So that't the placeholder for the 1.22 work, right?

**Comment by ahg-g** [comment]
I will send a PR in 30min, if it gets reviewed by tomorrow, then good, if not then we will delay to 1.22.

**Comment by ahg-g** [comment]
I sent out https://github.com/kubernetes/enhancements/pull/2461

@Huang-Wei @alculquicondor @damemi  timing is too tight, so please feel free to push back... we may not get a PRR too, so...

**Comment by wangyanghack** [comment]
[https://github.com/kubernetes/kubernetes/issues/98746#issue-800877111](url) 
sry,I don't understand what is difference in (LeastAllocatable and BestFit) or (MostAllocatable and WorstFit)?

**Comment by ahg-g** [comment]
Here is the plan:

1. [] Add Score extension point for Fit plugin. This needs to be added to both v1beta1 and v1beta2. 
1. [] Add validation in v1beta1 such that Fit Score plugin is not used with LeastAllocated, MostAllocated or RequestedToCapacityRatio.
1. [] Deprecate leastAllocated, mostAllocated or requestedToCapacityRatio in v1beta2
1. [] One of the following two: 
 - Make algorithmProvider.Registry versioned (pass in the component version to `NewRegistry`). In v1beta2, Fit replaces LeastAllocated score plugin.
 - Remove algorithmProvider flag (it has been marked as deprecated since 1.17), and move the set of default plugins to be set in the CC defaulting logic

**Comment by ahg-g** [comment]
I created https://github.com/kubernetes/kubernetes/issues/102151 to remove algorithmProvider pkg.

**Comment by ahg-g** [comment]
/close

This is now done.
