### ISSUE TITLE
Handling Deprecation of `pod-infra-container-image`

### ISSUE THREAD

**Issue by adisky** [kubernetes/kubernetes#98765]
**What would you like to be added**:

To prevent sandbox image from getting evicted for all container runtimes, a new flag needs to be introduced `pod-sandbox-image`/ `pod-pause-image` in kubelet, so that kubelet GC can use this information and prevent pause image eviction.

**Why is this needed**:

`pod-infra-container-image` is going to be removed with docker-shim removal. https://github.com/kubernetes/kubernetes/pull/98730
It is intended to be used with docker only.
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L191

But eventually Kubelet GC started using it for all container runtimes to prevent sandbox image from getting evicted.
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/images/image_gc_manager.go#L212-L216
and people started using it for other container runtimes, see here https://github.com/kubernetes/kubernetes/issues/81756#issuecomment-523710417

With the deprecation/ removal of 'pod-infra-container-image', We need some way to inform Kubelet GC about the pause image. We have following options -
- Introduce a new flag.
- Keep `pod-infra-container-image` and update the description and its purpose
- Kubelet get this information from container runtime using CRI.

**Comment by neolit123** [comment]
isn't it a better option to just keep the flag and not remove it because of the GC factor?
if we are going to add more knobs those should be in the v1beta1 KubeletConfiguraiton only and not as flags.
cc @mtaufen

**Comment by adisky** [comment]
@neolit123 I too agree on that, keep the flag and update its description. However i don't know what's the correct way would be. I created the issue as there is a PR to mark it deprecated https://github.com/kubernetes/kubernetes/pull/98730

**Comment by neolit123** [comment]
i can comment on the PR.

**Comment by adisky** [comment]
@neolit123 Updated the Title and description with all the options available.

**Comment by adisky** [comment]
closing this issue, `pod-infra-container-image` is removed from deprecation and its description is updated.
https://github.com/kubernetes/kubernetes/pull/98730/
/close
