### ISSUE TITLE
[kube-apiserver] log floods without any info

### ISSUE THREAD

**Issue by kfirfer** [kubernetes/kubernetes#98778]
Hello

Im running K8s 1.20.2, and there are some logs that kube-apiserver is printing quite a lot :

This are the logs:
```
ccResolverWrapper: sending update to cc: {[{https://127.0.0.1:2379  <nil> 0 <nil>}] <nil> <nil>}
parsed scheme: "passthrough"
ClientConn switching balancer to "pick_first"
```

I dont know how to disable them, nor their meanings
Only thing that I know of, is that all 3 of those logs are verbosity 0 (v=0)

**Comment by kfirfer** [comment]
From kubelet im getting flooded by those logs :

```
{"ts":1612477221356.5254,"msg":"ClientConn switching balancer to \"pick_first\"\n","v":0}
{"ts":1612477221356.5432,"msg":"blockingPicker: the picked transport is not ready, loop back to repick\n","v":0}
{"ts":1612477222853.2627,"msg":"parsed scheme: \"\"\n","v":0}
{"ts":1612477222853.3098,"msg":"scheme \"\" not registered, fallback to default scheme\n","v":0}
{"ts":1612477222853.3252,"msg":"ccResolverWrapper: sending update to cc: {[{/var/lib/kubelet/plugins/topolvm.cybozu.com/node/csi-topolvm.sock  <nil> 0 <nil>}] <nil> <nil>}\n","v":0}
```

Also I dont know how to disable them, nor their meanings

**Comment by pacoxu** [comment]
/remove-kind feature
is the cluster health and work well？
It seems some log messages are not proper

**Comment by kfirfer** [comment]
@pacoxu yes the cluster works well

**Comment by BenTheElder** [comment]
this is also https://github.com/kubernetes/kubernetes/issues/95893

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/issues/98720 is a bit earlier filed and has someone assigned, I'm going to dedupe these.
/triage duplicate
/close
