### ISSUE TITLE
Docs on Running Production Cluster on AWS

### ISSUE THREAD

**Issue by iterion** [kubernetes/kubernetes#9877]
It would be nice to have some docs on setting up and running a production cluster on AWS, and maybe in general. I know there is some stuff about HA masters, which is great. But, it might also be nice to have some recommendations on best practices for adding nodes to the cluster after it's running. In the context of AWS does that mean utilizing Auto Scaling Groups? If so, maybe we should include an example?

@justinsb @bakins Any thoughts on this? Any other Kubernetes production best practices we should communicate?

**Comment by bakins** [comment]
I haven't done Kubernetes on AWS with ASG. I generally spin up a cluster of sufficient size and up/down number of replicas as just adding nodes to the cluster isn't that useful unless you do that anyway.  Would love to hear other's experience in this area.

**Comment by justinsb** [comment]
_If_ I can get all my PRs etc in shape and landed, we will have ASG for the minions.

I don't know if we can automate the HA master stuff; probably not.

I do want to make sure that we are attaching a persistent disk to our master; I don't think we are and that is a rather big problem if it isn't HA.

**Comment by iterion** [comment]
> If I can get all my PRs etc in shape and landed, we will have ASG for the minions.

I have faith in you. :) Guessing these are the nodename/hostname and routing PRs?

> I don't know if we can automate the HA master stuff; probably not.
>
> I do want to make sure that we are attaching a persistent disk to our master; I don't think we are and that is a rather big problem if it isn't HA.

Yeah, I don't think we are mounting a persistent disk, it would probably be a good idea.

I'm also seeing issues after running a cluster for a while where the disk on all of my nodes gets filled up and they basically become unresponsive. Perhaps that is connected to the aufs/btrfs question? Regardless, maybe for production clusters should we recommend (or automatically create) nodes with larger disks, perhaps another config in kube-up?

 I can take a shot at mounting a persistent disk or config for minion disk size if you're swamped with other PRs ATM.

**Comment by justinsb** [comment]
Persistent disk on master is definitely needed - if you have time to have a look, that would be great.  GCE does this, so we have a model to work from.  We should tag this with the normal ClusterId tag.  If we do this, we can add more features later.

The disk-filling up and locking is definitely related to old kernels & btrfs.  Newer kernels make these problems better, though not necessarily entirely fixed.  But running out of disk space is bad on any kernel.  I don't know that adding extra storage is particularly compatible with ASGs.  My gut feel is that the actual Docker storage should be small, and people should use volumes for bigger data storage.

I am working to find a good OS/filesystem combination.  It seems the kernels available with Ubuntu 14.04 is too old to be stable with aufs, has disk-full problems with btrfs; Debian Wheezy & Jessie would need a reboot which is painful; Ubuntu Vivid actually looks good, but Salt has serious problems with it.  I'm trying to work around those salt problems, but I think running on Vivid might be the best option unless we want to get into custom AMIs or upgrading kernels (neither of which I am wild about).  That kernel should work with aufs, overlayfs (although I believe a pretty bad security flaw was just found here) and btrfs...

**Comment by iterion** [comment]
Cool, I'll take a look at PD on master and model it after GCE.

I sshd to a node and was able to regain ~4GB of disk from clearing unused docker images.

Extra storage on the root can be accomplished by modifying that block device on init:
From the run-instances docs:
```
--block-device-mappings "[{\"DeviceName\":\"/dev/sda1\",\"Ebs\":{\"DeleteOnTermination\":true,\"SnapshotId\":\"snap-b047276d\",\"VolumeSize\":100,\"VolumeType\":\"gp2\"}}]"
```
I believe ASG also allows modifying those mappings. Disk space is pretty cheap, so, it probably wouldn't hurt to have a buffer. Though we still need to find a tenable solution to filesystem.

FYI, did find this when researching: http://stackoverflow.com/questions/19146271/increase-the-root-device-size-in-cloudformation-autoscaling-group
Not sure if it would be needed.

Vivid seems like it might be the best choice if we can get salt working. If I get the PD on master knocked out quickly I can try to help out there too.

**Comment by iterion** [comment]
@justinsb I realized that I was using c4 instances for minions and ephemeral devices are not available there, so docker was being mounted on my root device which filled up very quickly! It's an interesting gotcha, it would probably be nice to support these instance types in the future by mounting ebs volumes for the ephemeral storage. But, I'm guessing that will be a post-1.0 item.

I'll create a PR with a note in the AWS readme saying that any "EBS-only" instances have this issue. For the current generation, that's `t2`, `m4`, and `c4` instance types.

**Comment by erulabs** [comment]
I've added a config option to make tweaking the root disk size easier - see PR #11459

**Comment by hjacobs** [comment]
:+1: for documentation regarding production clusters on AWS --- I already [asked on "kubernetes-users" mailing list](https://groups.google.com/forum/#!topic/kubernetes-users/WRsVjG7vc9Y), but there was only one response so far. I would appreciate to hear from any production "Kubernetes on AWS" users out there :smile:

**Comment by hjacobs** [comment]
Overview of how Zalando runs Kubernetes on AWS in production (in the hope that this is useful to someone): http://kubernetes-on-aws.readthedocs.io/en/latest/admin-guide/kubernetes-in-production.html
