### ISSUE TITLE
Determining pod QoS should keep consistent with kubelet in kubectl library

### ISSUE THREAD

**Issue by mYmNeo** [kubernetes/kubernetes#98782]
**What happened**:
In kubectl library, `GetPodQOS` logic is not the same as the one in `pkg/apis/core/helper/qos/qos.go`
**What you expected to happen**:
`GetPodQOS` logic should be the same.
**How to reproduce it (as minimally and precisely as possible)**:
Create a pod with a guaranteed QoS class and a best-effort QoS initcontainer.
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/kubectl/pkg/util/qos/qos.go#L35-L38

https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/apis/core/helper/qos/qos.go#L37-L40

It seems to be duplicate functions here.

**Comment by soltysh** [comment]
The intention for duplicates is coming from the fact that kubectl can't rely on packages from kuberentes main repository. Either way they should both be identical except for the fact that the internval version will use internal APIs, whereas kubectl's version will use versioned. @pacoxu feel free to open a PR updating kubectl version updating it to match both versions.
