### ISSUE TITLE
Admission control factory pattern needs to allow additional constructor arguments

### ISSUE THREAD

**Issue by csrwng** [kubernetes/kubernetes#9879]
The admission control factory should allow passing additional clients and other objects needed by the admission controller to do its work.

**Comment by csrwng** [comment]
@derekwaynecarr @smarterclayton

**Comment by smarterclayton** [comment]
I would prefer if admission control was factored like the other plugins (which were later) - a method that instantiates an object that exposes the interface.  I.e. `NewAdmissionControllers()` which could be `package.NewAdmissionControllers(*kube.Client)` or `mypackage.NewAdmissionControllers(*my.Client, someTunables)`.

When you want to use a plugin, you should be passing in the configuration and parameterizable parts to the constructor, and then using the interface of the controller elsewhere.

**Comment by smarterclayton** [comment]
In general, we should get lists of plugins and pass them into the things that need to use them as a slice of interfaces (or a slice of structs if there is additional data to them).  This applies to volumes, admission controllers, authorizers, etc.

**Comment by smarterclayton** [comment]
In practice, what's happening right now is that OpenShift is registering its own admission controllers, but needs to pass our client, not the Kube client, to the admission controller.  We have to do a really crazy hacky "implement client.Interface" thing that is pretty disgusting to ensure our admission controller has our client object.

**Comment by derekwaynecarr** [comment]
I agree that this should be revisited post Kube 1.0.

**Comment by smarterclayton** [comment]
Blocks https://github.com/openshift/origin/issues/2884 from being fixed

**Comment by bprashanth** [comment]
I'm going to call this either team csi for https://github.com/kubernetes/kubernetes/issues/9879#issuecomment-112502552 or control-plane for admission controller

@kubernetes/goog-csi

**Comment by davidopp** [comment]
Moving to next-candidate milestone

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by deads2k** [comment]
Resolved with plugin initializers
