### ISSUE TITLE
Investigate exercising Ephemeral Container creation in upgrade tests

### ISSUE THREAD

**Issue by verb** [kubernetes/kubernetes#98807]
**What would you like to be added**: If it's feasible, ephemeral containers should be exercised in the automated upgrade/downgrade tests https://testgrid.k8s.io/google-gce-upgrade

**Why is this needed**: Ephemeral Containers are targeted for beta in 1.21, it would be nice, but not required, to exercise this path in upgrade/downgrade tests.

/sig node
/priority important-longterm

**Comment by SergeyKanzhelev** [comment]
/area test
/remove-kind feature
/kind cleanup

this is a request for test, not a new feature. Changing kind

**Comment by SergeyKanzhelev** [comment]
@verb are you still working on it? if not, please unassign. If you can convert this into "good-first-issue" by providing some details on what needs to be done, it will be much appreciated

**Comment by verb** [comment]
@SergeyKanzhelev thanks for pinging me. I'm short of time these days so I'll unassign myself.

I'm not sure it would be a good first issue. It's still incomplete because I couldn't figure out how to do it. :disappointed: 

If you can point me towards docs or examples of upgrade/downgrade tests I'd be happy to write lots of context about ephemeral containers.

/unassign

**Comment by SergeyKanzhelev** [comment]
/close

seems it's too late for this
