### ISSUE TITLE
Scheduler PriorityQueue Update function 

### ISSUE THREAD

**Issue by NickrenREN** [kubernetes/kubernetes#98828]
**What happened**:

When we find the pod in podBackoffQ, we delete it from podBackoffQ and add it to the active queue directly, which doesn't match the comment.
Also, when we find the pod in unschedulableQ, we don't respect the backoff policy, we delete the pod from unschedulableQ and add it to the active queue directly.

**What you expected to happen**:

If the pod is in the backoff queue, update it there.
Also, when the pod is in the unschedulable queue, respect the backoff policy too.

**Anything else we need to know?**:

Not sure if this works as expected or is a bug, i guess it is a bug, so i send a PR for this.

**Comment by Huang-Wei** [comment]
When a Pod update event arrives, its spec that is associated with its schedulability may or may not have changed. In the current logic, we assume it to have changed, and hence remove it from backoffQ/unschedulableQ, and re-add it in the activeQ. IMO this logic is accurate, I'd prefer to keep it as is - unless we can find a cost-efficient way to check whether the updatedPod's scheduling attributes remain unchanged or not.

BTW: I'm curious about the background/context of this issue. Did you encounter a case that some Pods get updated (resourceVersion changed and spec changed) frequently and sort of churn the cluster heavily? If so, could you elaborate on how those Pods get updated?

**Comment by NickrenREN** [comment]
Thanks for your comment @Huang-Wei 
IIUC, when events which may make unschedulable pods become schedulable again come, we respect the backoff policy when we try to move pods to active queue at MoveAllToActiveOrBackoffQueue ,  for pod update events here, why do we want to delete the pod from backoff queue directly, ignoring the backoff stuff ?

> Did you encounter a case that some Pods get updated (resourceVersion changed and spec changed) frequently and sort of churn the cluster heavily? 

yes, we will also update other fields when scheduling pods failed in our local kubernetes env.

**Comment by Huang-Wei** [comment]
> yes, we will also update other fields when scheduling pods failed in our local kubernetes env.

Can you be more specific? Annotations, labels, or other fields?

---

I noticed some inconsistency in the code: if the updated Pod is not an assumedPod (i.e., [skipPodUpdate] returned false), the behavior differs upon which queue it's present:

- if it's in backoffQ, it's moved unconditionally to activeQ
- if it's in unschedulableQ, it firstly check [isPodUpdated], and then update in place (if unchanged), or moved to activeQ (if intact)

We should unify the two behaviors - i.e., if it's in backoffQ, it should also check [isPodUpdated] first. This may eliminate frequent pod movings (from backoffQ to activeQ) in your case. WDYT?

[skipPodUpdate]: https://github.com/kubernetes/kubernetes/blob/9e5fcc49ec568f222a5274f443903d89fec3e591/pkg/scheduler/eventhandlers.go#L177-L179
[isPodUpdated]: https://github.com/kubernetes/kubernetes/blob/bcfa3a0a36223a24891c7b49ff33dc51bde6ec31/pkg/scheduler/internal/queue/scheduling_queue.go#L446

**Comment by ahg-g** [comment]
The fields that `isPodUpdated` and `skipPodUpdate` are not synced, we should factor out the diff logic into a separate function. This function should be invoked in the event handler instead of doing it inside the queue update logic (i.e., we don't need to check if the pod is assumed etc., this is only needed for the check at the beginning of the scheduling cycle).

In summary:

```
func isAssumedAndUpdatedPod(pod *v1.Pod) {
    isAssumed, err := sched.SchedulerCache.IsAssumedPod(pod)
    if err != nil {
      utilruntime.HandleError(fmt.Errorf("failed to check whether pod %s/%s is assumed: %v", pod.Namespace, pod.Name, err))
    return false
    }
    if !isAssumed {
      return false
    }

    // Gets the assumed pod from the cache.
    assumedPod, err := sched.SchedulerCache.GetPod(pod)
    if err != nil {
      utilruntime.HandleError(fmt.Errorf("failed to get assumed pod %s/%s from cache: %v", pod.Namespace, pod.Name, err))
      return false
    }

   return isUpdatedPod(pod, assumedPod)
}

func isUpdatedPod(newPod, oldPod *v1.Pod) bool {
	f := func(pod *v1.Pod) *v1.Pod {
		p := pod.DeepCopy()
		// ResourceVersion must be excluded because each object update will
		// have a new resource version.
		p.ResourceVersion = ""
		// Spec.NodeName must be excluded because the pod assumed in the cache
		// is expected to have a node assigned while the pod update may nor may
		// not have this field set.
		p.Spec.NodeName = ""
		// Annotations must be excluded for the reasons described in
		// https://github.com/kubernetes/kubernetes/issues/52914.
		p.Annotations = nil
		// Same as above, when annotations are modified with ServerSideApply,
		// ManagedFields may also change and must be excluded
		p.ManagedFields = nil
		// The following might be changed by external controllers, but they don't
		// affect scheduling decisions.
		p.Finalizers = nil
		p.Status.Conditions = nil
		return p
	}
	newPodCopy, oldCopy := f(newPod), f(oldPod)
	return !reflect.DeepEqual(assumedPodCopy, podCopy)
}

```

**Comment by ahg-g** [comment]
I feel that we need to be consistent with `MoveAllToActiveOrBackoffQueue`, which moves pods from unschedulable to backoff or active. So I kinda agree with @NickrenREN on this one: If it was in the backoff queue, update there; if it was in the unschedulable queue and it is a `MaterialUpdate`, move either to backoff or active, if not `MaterialUpdate`, update in it place.

**Comment by Huang-Wei** [comment]
> I suggest we replace `skipPodUpdate` and `isPodUpdated` with the following two functions respectively:

I agree with most of this. Except for "Annotations", I'm not 100% sure excluding annotation update in isPodUpdated()/MaterialUpdate() is a great idea - AFIAK, some custom scheduling pluigns expect annotation changes to trigger a rescheduling. So that's why I asked @NickrenREN which fields are frequently changed.

> I feel that we need to be consistent with `MoveAllToActiveOrBackoffQueue`, which moves pods from unschedulable to backoff if the backoff wasn't done.

`MoveAllToActiveOrBackoffQueue` more represents a 1 event to N pods relationship, so we were cautious on this to hold the N pods in backoffQ if it's appropriate. However, PodUpdate is a 1 event to 1 pod relationship, so I think the original design, which moves it from backoffQ/unschedulableQ to activeQ, is more desirable - if we believe a MaterialUpdate makes it more a _brand new Pod_. This is also based on the assumption that it's not common to expect a batch PodUpdate events to update N pods at the same time.

**Comment by ahg-g** [comment]
> I agree with most of this. Except for "Annotations", I'm not 100% sure excluding annotation update in isPodUpdated()/MaterialUpdate() is a great idea - AFIAK, some custom scheduling pluigns expect annotation changes to trigger a rescheduling. So that's why I asked @NickrenREN which fields are frequently changed.

I agree, annotations are sometimes used as an API. Why doesn't this apply to `skipPodUpdate`? @alculquicondor who I think added the annotations to the list.

> MoveAllToActiveOrBackoffQueue more represents a 1 event to N pods relationship, so we were cautious on this to hold the N pods in backoffQ if it's appropriate. However, PodUpdate is a 1 event to 1 pod relationship, so I think the original design, which moves it from backoffQ/unschedulableQ to activeQ, is more desirable - if we believe a MaterialUpdate makes it more a brand new Pod. This is also based on the assumption that it's not common to expect a batch PodUpdate events to update N pods at the same time.

I would rather have a consistent behavior, but I don't object to keeping it as is apart from trying unifying how we check for material updates.

**Comment by NickrenREN** [comment]
>Can you be more specific? Annotations, labels, or other fields?

We will update pod annotations, but we don't want this to affect backoff policy.  
If we have some high priority pods which can't be scheduled, moving them to active queue directly will let the low priority pods get less chance to be scheduled.

>if we believe a MaterialUpdate makes it more a brand new Pod.

It is quite hard to find a general solution to define the `brand new pod`, different use cases may have different results. so why not follow backoff policy ? I don't think the event to pods relationship is the reason to skip backoff policy. unless we can say: PodUpdate can definitely create a brand new pod and it will not happen frequently.

**Comment by alculquicondor** [comment]
I was not involved in that :)
Issue: #52914
PRs: #54008 #86230
It looks like the challenge was to avoid logging an error when we try to schedule a Pod that was already scheduled (when an extender modifies annotations during binding).

That said, I agree that we should always respect the backoff policy.

**Comment by ahg-g** [comment]
Any idea why do we care about pod updates for assumed pods? Assumed pods are waiting to be bound, if that fails, their latest version will be put back into the unschedulable queue anyways.

**Comment by Huang-Wei** [comment]
It seems we cannot control how users update a pending Pod, and also cannot easily determine its real semantics (e.g., does a annotation/label update indicate the pod is more schedulable or not, etc.), so I kinda agree adhering to backoff policy is a mild option, in which case the downside is a Pod may have a delayed latency; while moving it immediately to activeQ may delay/block low-priority pods' scheduling.

Let's move it to this week's weekly meeting to get more thoughts.

> Any idea why do we care about pod updates for assumed pods? Assumed pods are waiting to be bound, if that fails, their latest version will be put back into the unschedulable queue anyways.

I think the key issue is that it may generate a "phantom" Pod, and hence may cause unexpected behavior. For example, when a pod is its binding cycle, and meanwhile some party updates the pod (e.g., annotation). If we call PriorityQueue#Update() unconditionally, it will be added to activeQ as a pod being bound doesn't belong to any queue. Next,
- if the scheduling for the "phantom" pod happens first, it may hit error in Assume() b/c there is already one (the original pod) being assumed
- if the scheduling for "phantom" pod happens after the binding of original pod, it may fail in the binding phase - I think apiserver will reject the duplicated binding (but I haven't tested). If so, it may live inside scheduler queues forever.

**Comment by ahg-g** [comment]
Right, so my point is why do we need to put back an assumed pod in the queues at all on an update event? Is there any drawback to simply skip all assumed pod updates?

**Comment by Huang-Wei** [comment]
> Is there any drawback to simply skip all assumed pod updates?

Not any I'm aware of. If the binding goroutine runs successfully, it indicates API server already handles potential conflicts properly if there is any; if the binding goroutine failed, we always fetch the latest version from podLister and add it back into queue:

https://github.com/kubernetes/kubernetes/blob/9d7d3eb820c5297b5fcd5ffa21399c8bf2da744a/pkg/scheduler/factory.go#L341

**Comment by ahg-g** [comment]
> > Is there any drawback to simply skip all assumed pod updates?
> 
> Not any I'm aware of. If the binding goroutine runs successfully, it indicates API server already handles potential conflicts properly if there is any; if the binding goroutine failed, we always fetch the latest version from podLister and add it back into queue:
> 
> https://github.com/kubernetes/kubernetes/blob/9d7d3eb820c5297b5fcd5ffa21399c8bf2da744a/pkg/scheduler/factory.go#L341

Yup, that was my conclusion as well here https://github.com/kubernetes/kubernetes/issues/98828#issuecomment-783803840. I think then we can simplify that and simply ignore the update and scheduling of assumed pods then, and keep the pod diffing for non assumed pods when moving them out of the unachedulable queue.

**Comment by alculquicondor** [comment]
Another justification for skipping assumed pods is an a solved issue #91249
Note that the workaround for this was to skip updates to `.status.conditions`

**Comment by ahg-g** [comment]
ok, I guess we have agreement on the following:
1) ignore updates to assumed pods
2) move pods from unschedulable to backoff on pod update if their backoff period wasn't done.

**Comment by Huang-Wei** [comment]
> 2\. move pods from unschedulable to backoff on pod update if their backoff period wasn't done.

@NickrenREN Could you tweak #98829 a bit to adhere to this semantics?

**Comment by NickrenREN** [comment]
>@NickrenREN Could you tweak #98829 a bit to adhere to this semantics?

Sure, how about update events for backoff queue pods ? Updating them there ?

**Comment by alculquicondor** [comment]
#98829 is not handling 1 yet.

> Sure, what about update events for backoff queue pods ? Updating them there ?

You could check if the backoff period finished, but it sounds like an overkill, because the routine that checks backoffs will eventually do it.

**Comment by Huang-Wei** [comment]
> Sure, what about update events for backoff queue pods ? Updating them there ?

Yes.

> #98829 is not handling 1 yet.

Prefer to handle this in a separate PR.

**Comment by NickrenREN** [comment]
@Huang-Wei  FYI ,  #98829 updated

**Comment by ahg-g** [comment]
Created https://github.com/kubernetes/kubernetes/issues/100261 to track the 1
