### ISSUE TITLE
Fake client does not generate UUID or CreationTimestamp

### ISSUE THREAD

**Issue by erir910** [kubernetes/kubernetes#98833]
`k8s.io/client-go/kubernetes/fake` or any CRD fake client does not generate UUID or CreationTimestamp for the created objects. This makes unit testing basically impossible for many cases especially for controllers checking such fields. The only solution for this is to write extremely slow and hard to manage e2e tests just to emulate a simple and lightweight unit test.

**Comment by neolit123** [comment]
this seems more like a feature request.
/kind feature

**Comment by deads2k** [comment]
The fake client just provides semantics close to, but not identical to, a real client. UUID and CreationTimestamp fall outside the current boundary of the mocks.  Given common usage in unit tests where exact equality is desired, it's not even a sure thing that most callers would like to have these fields filled in and those who would are likely to want conflicting things
1. dynamic
2. dynamic with seed
3. controlled with fake clock
4. controlled with exact value.

I don't see us changing the existing contract to set these field.  You can create a reactor for the fake client using `AddReactor` to get the behavior you want for your test.

/close

**Comment by gmolau** [comment]
Can this be reopened? The fake (!= mock) should behave as similarly to the real client as possible, so here it should simply generate a new UUID and use the real creation time. I was quite surprised that it doesn't do this, and now have to do some tinkering to get around this.

**Comment by SleepyBrett** [comment]
would also like this reopened.
