### ISSUE TITLE
Latency of starting a pod

### ISSUE THREAD

**Issue by lanthias** [kubernetes/kubernetes#9883]
We would like to spin up pods quickly on our cluster, to handle 'one-off' tasks (the idea being that each task has a new pod every time it runs).

Currently, it takes about 10-15 seconds from a Pod creation API call -> completion. This is running on 3x m3 xlarge on AWS, with images that have already been cached. We are running with restartPolicy = Never, as they are one-off tasks. To confirm this performance, I have also run the task on GCE, with 3x nodes, and had the same results. There are no other pods of note running (apart from etcd, dns, elastic-search -- the default stuff that comes with the aws script).

I've tried fiddling with the imagePullPolicy (= Never) and resource options with no avail. It appears that the 10 second delay happens in the 'Running' phase, after Kubernetes has handed it off to a Pod, but before docker on that node has started the container:

``Tue, 16 Jun 2015 18:49:15 +0100	Tue, 16 Jun 2015 18:49:15 +0100	1	{kubelet k8s-cluster-1-25cbca09-node-6cb3}	spec.containers{9be1bbd9-ea74-414b-9e08-b4ffa1ae4946started		Started with docker id 0ff6b4b70e5a2845a9edd0f255df35941f2132d6f3135f7bfa3720c30b4fc7d5
  Tue, 16 Jun 2015 18:49:25 +0100	Tue, 16 Jun 2015 18:49:25 +0100	1	{kubelet k8s-cluster-1-25cbca09-node-6cb3}	implicitly required container POD			killing		Killing 7612f02ff4f139023f5cde1dc0496be932e06811512b31a25c457e9abc6d746e
``

I can confirm the container operation itself is very quick: if I ssh and manually docker run the container on the actual node takes, it takes 0.5 seconds. Moreover, if I inspect the container called by Kubernetes on the node, after it has finished, StartedAt and FinishedAt is 0.5 seconds -- so the delay is happening prior to this (I can also confirm this b/c I am uploading a file to s3 before exit, and the missing 10 seconds is already there). Doing a docker pull of the image on the node is also quick.

I'm running v0.18.2 on the EC2 cluster, and Google Container Engine to confirm.

Here is a lifecycle of a Pod creation from my kubelet logs: http://pastebin.com/eXtX3pyY

Is this standard behaviour / is there anyway to speed it up?

**Comment by jayunit100** [comment]
e2e test for instant pod startup, @timothysc @rrati  after this is addressd

**Comment by dchen1107** [comment]
cc/ @ArtfulCoder

**Comment by timothysc** [comment]
So this doesn't really surprise me at all, do you have your pod submission somewhere?

**Comment by lanthias** [comment]
Thanks a lot guys, here is an example pod definition which exhibits the behaviour:
``
{
  "id": "e40354c1-d53d-4462-87d7-4621632a0966",
  "spec": {
    "containers": [{
      "name": "e40354c1-d53d-4462-87d7-4621632a0966",
      "image": "busybox",
      "cpu": 100
    }],
    "restartPolicy": "Never"
  },
  "metadata": {
    "name": "e40354c1-d53d-4462-87d7-4621632a0966",
    "generateName": "imageproc"
  },
  "kind": "Pod",
  "apiVersion": "v1beta3"
}
``
Am I correct to presume that this is pretty normal / k8s isn't built for what I'm trying to achieve?

**Comment by yujuhong** [comment]
> Currently, it takes about 10-15 seconds from a Pod creation API call -> completion
@lanthias, if 10-15s is the duration of from pod creation to pod termination observed from the apiserver, I have a better explanation for you.

From your log, kubelet actually started the pod pretty quickly and then reported the Running state. However, because kubelet checked the container state for changes every 10s, it'd only discover that the container has terminated after 10s.

We are working on addressing a few performance issues for kubelet, which would also speed up discovery of container state changes. The umbrella issue for this is #12540 (with no details yet), which I will update shortly.

**Comment by yujuhong** [comment]
Once we switch to docker event generator, the container termination should be discovered rather quickly. Please follow #12540 instead. Thanks!
