### ISSUE TITLE
Only a single pod can be called through the browser

### ISSUE THREAD

**Issue by liujing1995** [kubernetes/kubernetes#98849]
**What happened**:
Hello everyone, this is my first time using k8s as a container orchestration tool.Encountered some problems when using load balancing. The question is that only a single pod can be called through a browser, but I can use curl commands on my laptop to access different pods under a service.

**Anything else we need to know?**:

1. I set sessionAffinity to None in the service.yaml file
2. this bug has nothing to do with the browser’s cache
3. The load balancer is the default and has not been modified

**Environment**:
- Kubernetes version 1.17.1 (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
hi, please try the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
