### ISSUE TITLE
After the node is down, the POD migration is abnormal

### ISSUE THREAD

**Issue by heqg** [kubernetes/kubernetes#98851]
**What happened**:
1. when a node is down, the POD migration is abnormal

**What you expected to happen**:
1. when a node is down, the pods on the node  should moved to other nodes at the expected time(node-monitor-grace-period + pod's tolerance time).

**How to reproduce it (as minimally and precisely as possible)**:
1. First deploy a three-node cluster
2. create some pods
3. stop the kubele.service of someone node。
4. Wait a short time（node-monitor-grace-period: default 40s + pod's tolerance time: default 300s, we set 0s）
5. Exec a command: **_kubectl get pods -o wide_**   then found :

```
[root@node01:/home/version/yaml_my]$ kubectl get node && kubectl get pod -o wide
NAME            STATUS     ROLES    AGE   VERSION
10.229.87.100   NotReady   <none>   21m   v1.19.4
10.229.87.97    Ready      <none>   21m   v1.19.4
10.229.87.99    Ready      <none>   21m   v1.19.4

NAME                        READY   STATUS    RESTARTS   AGE     IP               NODE            NOMINATED NODE   READINESS GATES
my-kubia-5c846979c7-2pknr   1/1     Running   0          2m14s   172.22.98.67     10.229.87.99    <none>           <none>
my-kubia-5c846979c7-4kbbf   1/1     Running   0          2m14s   172.22.35.66     10.229.87.100   <none>           <none>
my-kubia-5c846979c7-bn6h6   1/1     Running   0          2m14s   172.22.132.131   10.229.87.97    <none>           <none>
my-kubia-5c846979c7-jvx2t   1/1     Running   0          2m14s   172.22.35.67     10.229.87.100   <none>           <none>
my-kubia-5c846979c7-kqjfd   1/1     Running   0          2m14s   172.22.98.65     10.229.87.99    <none>           <none>
my-kubia-5c846979c7-m9gf5   1/1     Running   0          2m14s   172.22.132.130   10.229.87.97    <none>           <none>
my-kubia-5c846979c7-mr5jx   1/1     Running   0          2m14s   172.22.35.65     10.229.87.100   <none>           <none>
my-kubia-5c846979c7-p8ltq   1/1     Running   0          2m14s   172.22.132.129   10.229.87.97    <none>           <none>
my-kubia-5c846979c7-zj7tx   1/1     Running   0          2m14s   172.22.98.66     10.229.87.99    <none>           <none>

```

6. Then the problem occurred

**Anything else we need to know?**:
1. After the problem occurred，we exec a command：kubectl describe nodes  nodeAA |  grep Taints
we only found :
       **Taints:             node.kubernetes.io/unreachable:NoSchedule**
 but expected:
       **Taints:             node.kubernetes.io/unreachable:NoExecute**
                                   **node.kubernetes.io/unreachable:NoSchedule**
so， we lost a Taint(unreachable:NoExecute)

2. we debug the related code , found that the length of **_q.queue_**  is always more than our expected value ( this queue should save the nodes that were down )
3. After further analysis， we found that the code: q.queue.RemoveFromQueue(val.Value)   never had a chance to execute。
4. After Continue to debug， we found that the process often break out at line：_**if !q.limiter.TryAccept()**_

the code as below:
```
func (q *RateLimitedTimedQueue) Try(fn ActionFunc) {
val, ok := q.queue.Head()


q.limiterLock.Lock()
defer q.limiterLock.Unlock()
for ok {
// rate limit the queue checking
if !q.limiter.TryAccept() {
klog.V(10).Infof("Try rate limited for value: %v", val)
// Try again later
break
}

now := now()
if now.Before(val.ProcessAt) {
break
}

if ok, wait := fn(val); !ok {
val.ProcessAt = now.Add(wait + 1)
q.queue.Replace(val)

} else {
q.queue.RemoveFromQueue(val.Value)
}
val, ok = q.queue.Head()
}
}
```

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by lunhuijie** [comment]
we tried to fix this bug though this way:
delete rate limit func the queue checking
```
func (q *RateLimitedTimedQueue) Try(fn ActionFunc) {
val, ok := q.queue.Head()
q.limiterLock.Lock()
defer q.limiterLock.Unlock()
for ok {
// rate limit the queue checking
**//**if !q.limiter.TryAccept() {
**//**klog.V(10).Infof("Try rate limited for value: %v", val)
**//** Try again later
**//**break
**//**}

now := now()
if now.Before(val.ProcessAt) {
break
}

if ok, wait := fn(val); !ok {
val.ProcessAt = now.Add(wait + 1)
q.queue.Replace(val)

} else {
q.queue.RemoveFromQueue(val.Value)
}
val, ok = q.queue.Head()
}
}
```
the the problem is never occurred !!!

this way is reasonable？maybe there are another better way to solve it ?
and we understand about  rate limit few.
Can you give me some suggestions？

/assign：@gmarek
/assign：@bowei

**Comment by heqg** [comment]
the value of  nc.zoneNoExecuteTainter[k]  in node_lifecycle_controller.go 
( line: [nc.zoneNoExecuteTainter[k].Try(func(value scheduler.TimedValue) (bool, time.Duration) {] )

In abnormal scenarios, the following information will be printed：
doNoExecuteTaintingPass:nc.zoneNoExecuteTainter[k]  ------ &{{{0 0} [0xc001731950 0xc001e42c30 0xc0013f9400 0xc000b6d180 0xc0015eba40 0xc0005c2f00 0xc001826460 0xc000b6dcc0 0xc0020f6140 0xc000eefea0 0xc000eefa40 0xc001ab0e10 0xc002155860 0xc0018ffdb0 0xc001730280 0xc0000b3270 0xc0020ac9b0 0xc0020ad5e0 0xc0020f6d70 0xc000b15b30 0xc0015eaf50 0xc001e42230 0xc0009df310 0xc000277360 0xc0015eb400 0xc0005c25a0 0xc0015ea410 0xc0020f7720 0xc0005c3c20 0xc0015eac80 0xc001e43f90 0xc0005c2320] map[10.229.87.100:{}]} {0 0} 0xc000edd8a0} ------

**Comment by heqg** [comment]
**In normal scenarios,** ，when the node is down, after a few time   (time time period = node-monitor-grace-period), the following information will be printed **only one time**：
------ &{{{0 0} [0xc000c1fdb0] map[10.229.87.100:{}} {0 0} 0xc00103f860} ------
and then only print the following information ( 0xc000c1fdb0 is cleared)
------ &{{{0 0} [] map[10.229.87.100:{}} {0 0} 0xc00103f860} ------

**Comment by heqg** [comment]
the value of nc.zoneNoExecuteTainter[k] in node_lifecycle_controller.go
( line: [nc.zoneNoExecuteTainter[k].Try(func(value scheduler.TimedValue) (bool, time.Duration) {] )

**In abnormal scenarios**, the following information will be printed：
doNoExecuteTaintingPass:nc.zoneNoExecuteTainter[k] ------ &{{{0 0} [0xc001731950 0xc001e42c30 0xc0013f9400 0xc000b6d180 0xc0015eba40 0xc0005c2f00 0xc001826460 0xc000b6dcc0 0xc0020f6140 0xc000eefea0 0xc000eefa40 0xc001ab0e10 0xc002155860 0xc0018ffdb0 0xc001730280 0xc0000b3270 0xc0020ac9b0 0xc0020ad5e0 0xc0020f6d70 0xc000b15b30 0xc0015eaf50 0xc001e42230 0xc0009df310 0xc000277360 0xc0015eb400 0xc0005c25a0 0xc0015ea410 0xc0020f7720 0xc0005c3c20 0xc0015eac80 0xc001e43f90 0xc0005c2320] map[10.229.87.100:{}]} {0 0} 0xc000edd8a0} ------

**Comment by lunhuijie** [comment]
https://github.com/kubernetes/kubernetes/pull/96876/files
the pr solved this problem, but there is a little question letf. Why  alway run "rate limit the queue checking" make it break and let the quene couldn't removed.

**Comment by yangjunmyfm192085** [comment]
I think rate limit mechanism is vaild, should not be deleted.
Now the problem is:
confirm which process has the problem,fix it.

**Comment by matthyx** [comment]
Hi folks, is this still a valid bug?
/area kubelet
