### ISSUE TITLE
[Flaky Test]  [sig-scheduling] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run [Conformance]

### ISSUE THREAD

**Issue by PriyankaH21** [kubernetes/kubernetes#98857]
**Which jobs are flaking**: `ci-kubernetes-e2e-gci-gce-serial `

**Which test(s) are flaking**: `SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run [Conformance] `

**Testgrid link**: https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-serial&include-filter-by-regex=validates%20resource%20limits%20of%20pods%20that%20are%20allowed%20to%20run

**Reason for failure**:

```
I0202 03:26:23.256]     <*errors.errorString | 0xc000471150>: {
I0202 03:26:23.256]         s: "pod ran to completion",
I0202 03:26:23.256]     }
I0202 03:26:23.256]     pod ran to completion
I0202 03:26:23.256] occurred
skipped 127 lines unfold_more
I0202 03:26:26.402] Feb  2 03:26:26.402: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
I0202 03:26:26.441] STEP: Destroying namespace "sched-pred-7838" for this suite.
I0202 03:26:26.479] [AfterEach] [sig-scheduling] SchedulerPredicates [Serial]
I0202 03:26:26.480]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:81
I0202 03:26:26.480] 
I0202 03:26:26.480] • Failure [14.201 seconds]
I0202 03:26:26.480] [sig-scheduling] SchedulerPredicates [Serial]
I0202 03:26:26.481] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/framework.go:40
I0202 03:26:26.481]   validates resource limits of pods that are allowed to run  [Conformance] [It]
```

**Anything else we need to know**:
Spyglass: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1356440010672312320
Triage: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=validates%20resource%20limits%20of%20pods%20that%20are%20allowed%20to%20run

/sig scheduling

**Comment by mkorbi** [comment]
/remove-lifecycle stale
this test runs very infrequently are there any actions planned to either fix this or remove it?

besides this looks green for now

**Comment by alculquicondor** [comment]
It looks like this was failing while trying to get nodes running. So not really a failure of the test itself, but the infra.
Since it's green, it should be safe to close.
