### ISSUE TITLE
[Flaky Test] [[sig-cli] Kubectl client Simple pod should return command exit codes

### ISSUE THREAD

**Issue by PriyankaH21** [kubernetes/kubernetes#98854]
**Which jobs are flaking**:  `ci-kubernetes-kind-ipv6-e2e-parallel`

**Which test(s) are flaking**: 
- `Kubectl client Simple pod should return command exit codes`
- `Kubectl client Simple pod should support inline execution and attach`

**Testgrid link**:  https://testgrid.k8s.io/sig-release-master-blocking#kind-ipv6-master-parallel&include-filter-by-regex=%20Kubectl%20client%20Simple%20pod%20should%20return%20command%20exit%20codes

**Reason for failure**:

```
• Failure [83.784 seconds]
[sig-cli] Kubectl client
test/e2e/kubectl/framework.go:23
  Simple pod
  test/e2e/kubectl/kubectl.go:382
    should return command exit codes [It]
    test/e2e/kubectl/kubectl.go:502
    Feb  7 16:23:48.033: Unexpected error:
      
        <exec.CodeExitError>: {
            Err: {
                s: "error running /home/prow/go/src/k8s.io/kubernetes/bazel-out/k8-fastbuild-ST-5e46445d989a/bin/cmd/kubectl/kubectl_/kubectl --server=https://[::1]:37209 --kubeconfig=/root/.kube/kind-test-config --namespace=kubectl-7185 run -i --image=docker.io/library/busybox:1.29 --restart=Never success -- /bin/sh -c exit 0:\nCommand stdout:\n\nstderr:\nerror: timed out waiting for the condition\n\nerror:\nexit status 1",
            },
            Code: 1,
        }
        error running /home/prow/go/src/k8s.io/kubernetes/bazel-out/k8-fastbuild-ST-5e46445d989a/bin/cmd/kubectl/kubectl_/kubectl --server=https://[::1]:37209 --kubeconfig=/root/.kube/kind-test-config --namespace=kubectl-7185 run -i --image=docker.io/library/busybox:1.29 --restart=Never success -- /bin/sh -c exit 0:
        Command stdout:
        
        stderr:
        error: timed out waiting for the condition
        
        error:
        exit status 1
    occurred
skipped 55993 lines unfold_more
[Fail] [sig-cli] Kubectl client Simple pod [It] should return command exit codes 
test/e2e/kubectl/kubectl.go:515
```

**Anything else we need to know**:

> NOTE: 7 clusters of 86 failures (8 in last day) out of 146571 builds from **_1/23/2021_**

Test Owner: **yifan-gu** -> https://github.com/kubernetes-csi/driver-registrar/blob/master/vendor/k8s.io/kubernetes/test/test_owners.csv#L216

Triage: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=Kubectl%20client%20Simple%20pod%20should%20return%20command%20exit%20codes

Spyglass failures: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-ipv6-e2e-parallel/1358448260980674560

/sig cli

**Comment by BenTheElder** [comment]
GCE flake https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1361815019435593728

**Comment by thejoycekung** [comment]
More recent flakes:
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-ipv6-e2e-parallel/1370851171178123264
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-ipv6-e2e-parallel/1370590201994285056
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-ipv6-e2e-parallel/1370498097053962240
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-ipv6-e2e-parallel/1370283223451439104
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-ipv6-e2e-parallel/1369930104012017664
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-ipv6-e2e-parallel/1369853366850555904
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-ipv6-e2e-parallel/1369837990431428608

/cc @kubernetes/sig-cli-test-failures

**Comment by dims** [comment]
cc @aojea @BenTheElder

**Comment by thejoycekung** [comment]
More instances:

- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1371281239268397056
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1371143081566408704
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1371081675559145472
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1371020275025448960

**Comment by aojea** [comment]
heh, at least is no ipv6 only, that is a relieve :stuck_out_tongue: 

Analysing this occurrence 
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1371143081566408704

and the containerd logs 
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1371143081566408704/artifacts/logs/kind-worker2/containerd.log

it seems a timing issue, the test times out at 17:30:28
```
Mar 14 17:29:27.944: INFO: Running '/home/prow/go/src/k8s.io/kubernetes/_output/bin/kubectl --server=https://127.0.0.1:44469 --kubeconfig=/root/.kube/kind-test-config --namespace=kubectl-2800 run -i --image=k8s.gcr.io/e2e-test-images/busybox:1.29 --restart=Never failure-4 --leave-stdin-open -- /bin/sh -c exit 42'
Mar 14 17:30:28.074: INFO: rc: 1
Mar 14 17:30:28.074: FAIL: Unexpected error:
    <exec.CodeExitError>: {
        Err: {
```
The pod runs at 17:30:36
```
Mar 14 17:30:36 kind-worker2 containerd[173]: time="2021-03-14T17:30:36.417349915Z" level=info msg="RunPodSandbox for &PodSandboxMetadata{Name:failure-4,Uid:aab07c30-c6f0-4aad-a1d6-ac476bad3e54,Namespace:kubectl-2800,Attempt:0,} returns sandbox id \"222b5f5eda72b2b7949509cc9e239ed9cc79065c6467acfefd8bb0933d6a4adf\""
```

ping @spiffxp @BenTheElder , we've talked about this several times, bumping timeouts vs improving the performance in this kind jobs :shrug:

**Comment by BenTheElder** [comment]
See above that this also fails in GCE. And see https://github.com/kubernetes/kubernetes/issues/100047 where pod timeouts turn out to be an actual Kubernetes bug and a test bug ...

**Comment by aojea** [comment]
great :+1: , I mean, great is not only a kind jobs problem and we know the cause :upside_down_face:

**Comment by jsturtevant** [comment]
another instance: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/99866/pull-kubernetes-e2e-kind/1371887802538528768

```
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:496
Mar 16 18:52:06.408: Expected
    <int>: 1
to equal
    <int>: 42
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:515
```

**Comment by thejoycekung** [comment]
more instances:
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1374151566793117696
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1374105513444249600
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1374013425532801024
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1373445428850200576
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1373368673007308800
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1373337968990752768
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1373261217233113088

some have the error message @jsturtevant put above, some have the error message @PriyankaH21 put in the original description

**Comment by palnabarun** [comment]
/milestone v1.21

(marking in the current milestone until we get confirmation whether it is relevant to the release or not)

**Comment by eddiezane** [comment]
These failures appear to be the pod failing to start.

The assertions are very basic:

1. Run pod with `sh -c "exit 42"`
2. Check if exit code is 42

It's exiting with a code of 1 which probably means the pod is failing to start. I'll add some logging of the output and then we can figure it out from there. Most likely a timeout issue with the test cluster?

I would say this is not release blocking.

**Comment by palnabarun** [comment]
Thank you @eddiezane for checking it so quickly. 🚀 

/milestone clear

**Comment by liggitt** [comment]
this is failing in 5% of e2e runs - https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2021-04-13&pr=1&job=pull-kubernetes-e2e-kind&test=should%20return%20command%20exit%20codes#464986d09bc22437562b

**Comment by liggitt** [comment]
and is the top flake per http://storage.googleapis.com/k8s-metrics/flakes-latest.json

**Comment by rikatz** [comment]
/assign

Will take a look with Eddie :)

**Comment by eddiezane** [comment]
Will continue to monitor this one. We started with a slightly higher grace period (2 mins from 1 min) for pods to start. If it still flakes we can adjust.

https://github.com/kubernetes/kubernetes/pull/101295/files#r618594831

**Comment by eddiezane** [comment]
This is failing aggressively since May 7th.

https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=Simple%20pod%20should%20return%20command%20exit%20codes

/reopen

**Comment by eddiezane** [comment]
Failures appear to be down outside of mass group failures. If this creeps back up [this](https://github.com/kubernetes/kubernetes/pull/101295/files#r618594831) is our next option.

/close
