### ISSUE TITLE
kubectl logs -f         Forbidden

### ISSUE THREAD

**Issue by KNWBIN** [kubernetes/kubernetes#98852]
kubeadm  1.18.15

kubectl logs -f calico-kube-controllers-8586758878-b88gd -nkube-system -v=10

I0207 19:27:16.057638   12466 round_trippers.go:424] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.18.15 (linux/amd64) kubernetes/73dd5c8" 'https://127.0.0.1:6443/api/v1/namespaces/kube-system/pods/calico-kube-controllers-8586758878-b88gd/log?follow=true'
I0207 19:27:16.066255   12466 round_trippers.go:444] GET https://127.0.0.1:6443/api/v1/namespaces/kube-system/pods/calico-kube-controllers-8586758878-b88gd/log?follow=true 500 Internal Server Error in 8 milliseconds
I0207 19:27:16.066272   12466 round_trippers.go:450] Response Headers:
I0207 19:27:16.066282   12466 round_trippers.go:453]     Cache-Control: no-cache, private
I0207 19:27:16.066288   12466 round_trippers.go:453]     Content-Type: application/json
I0207 19:27:16.066295   12466 round_trippers.go:453]     Content-Length: 237
I0207 19:27:16.066301   12466 round_trippers.go:453]     Date: Sun, 07 Feb 2021 11:27:16 GMT
I0207 19:27:16.066318   12466 request.go:1068] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Get https://x.x.x.x:10250/containerLogs/kube-system/calico-kube-controllers-8586758878-b88gd/calico-kube-controllers?follow=true: Forbidden","code":500}
I0207 19:27:16.066665   12466 helpers.go:216] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "Get https://x.x.x.x:10250/containerLogs/kube-system/calico-kube-controllers-8586758878-b88gd/calico-kube-controllers?follow=true: Forbidden",
  "code": 500
}]

kubectl logs -f calico-kube-controllers-8586758878-b88gd -nkube-system
Error from server: Get https://x.x.x.x:10250/containerLogs/kube-system/calico-kube-controllers-8586758878-b88gd/calico-kube-controllers?follow=true: Forbidden

**Comment by neolit123** [comment]
you can try showing this to the Calico maintainers:
https://github.com/projectcalico/calico

i doubt this is a bug in core kubernetes.

/close
