### ISSUE TITLE
Add possibility to specify docker TLS client authentication via secrets

### ISSUE THREAD

**Issue by kostrahb** [kubernetes/kubernetes#98871]
**What would you like to be added**:

The possibility to specify docker TLS client authentication (probably somehow via imagePullSecrets or other similar field which would allow specifying TLS secrets instead of docker secrets?)

**Why is this needed**:

We have a private nexus repository in our company with pretty tight security - meaning that authentication with credentials is not enough and TLS verification was recommended.

Note: According to what I studied so far the configuration via the docker config file is theoretically possible (you can still specify names of files with TLS key and cert), it is just very inconvenient to get the key and certificates to the right place - if I'm correct, it would need something like daemonset with the volume connected to the right place on the host machine and init container which would copy the certificates and keys.

**Comment by liggitt** [comment]
node-level runtime configuration driven via the API would be sig-node's domain

/remove-sig auth

**Comment by wzshiming** [comment]
According to my understanding, docker will be abandoned in the future, and it is recommended to migrate to Containerd, which added the ability to encrypt images in 1.5

Kubernetes does not use issues on this repo for support requests. If you have a question on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/).

/remove-kind bug
/kind support
/close
