### ISSUE TITLE
Make `allowPrivilegeEscalation: true` override dockerd's `--no-new-privileges`

### ISSUE THREAD

**Issue by wc-s** [kubernetes/kubernetes#98876]
**What would you like to be added**:
`dockerd` allows you to use the `--no-new-privileges` option to "Set no-new-privileges by default for new containers" (https://docs.docker.com/engine/reference/commandline/dockerd/).

Testing with docker version 19.03.14, I see that it is possible to override this, on a per-container basis, by doing eg. `docker run --security-opt="no-new-privileges:false" <...snip...>`

However, using k8s version 1.19, even if I have `allowPrivilegeEscalation: true` in a container securityContext, the `NoNewPrivs` flag is still `true` (ie. it won't override the dockerd default).

I think `allowPrivilegeEscalation` should be able to do this override.

Testing results for context:
dockerd | securityContext | NoNewPrivs (as seen from /proc/<proc_id>/status)
------------ | ------------- | -------------
without `--no-new-privileges`  | allowPrivilegeEscalation undefined | 0
without `--no-new-privileges`  | allowPrivilegeEscalation: true | 0
without `--no-new-privileges`  | allowPrivilegeEscalation: false | 1
with `--no-new-privileges`  | allowPrivilegeEscalation undefined | 1
with `--no-new-privileges`  | allowPrivilegeEscalation: true | 1
with `--no-new-privileges`  | allowPrivilegeEscalation: false | 1

**Why is this needed**:

The dockerd `--no-new-privileges` flag is a recommended setting from CIS. It would be great if it can be applied so that we restrict privilege escalation daemon-wide by default, but allow individual k8s-managed containers to override that explicitly.

**Comment by shevelevs** [comment]
Can this issue be looked into? Is there some documentation that clearly says this is by design and is not a bug. From the code here https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/security_context.go#L138 it doesn't look like this is necessarily intentional.

**Comment by jgalliers** [comment]
@wc-s please /reopen this as we are hitting this exact issue. CIS Docker hardening requires the `--no-new-privileges` flag on the docker daemon but we need a specific pod to launch with `sudo` access.

`allowPrivilegeEscalation` does not satisfy this, despite what seems to be documentation to the contrary
