### ISSUE TITLE
Secrets encryption not working

### ISSUE THREAD

**Issue by CharmingSteve** [kubernetes/kubernetes#98877]
**What happened**:
I followed the directions for setting up secrets encryption https://kubernetes.io/docs/concepts/configuration/secret/ 

**What you expected to happen**:
It should have encrypted the secrets  created after enabling

**How to reproduce it (as minimally and precisely as possible)**:
I installed kubernetes with kubeadmin. IN your order to reproduce follow the directions
create a new secret like 

kubectl create secret generic secret1 -n default --from-literal=mykey=mydata

now log into an etcd image with access to your certs for connecting to etcd

docker run -u root -it  --rm --entrypoint bash  -v /etc/kubernetes/:/etc/kubernetes/ bitnami/etcd
run

 ETCDCTL_API=3 etcdctl get /registry/secrets/default/secret1  --endpoints=https://YOUR_ETCD_URL:2379    --cacert=/etc/kubernetes/pki/etcd/ca.crt    --cert=/etc/kubernetes/pki/etcd/server.crt    --key=/etc/kubernetes/pki/etcd/server.key |  hexdump -C

I had to add hexdump with apt update && apt install bsdmainutils

Now you can see your secret in plain text

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
-
[steve.gindi@kube1 ~]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-09T11:10:32Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
[steve.gindi@kube1 ~]$

- Cloud provider or hardware configuration:
- Baremetal
- OS (e.g: `cat /etc/os-release`):
- Centos 8
- Kernel (e.g. `uname -a`):
-  uname -a
Linux kube1.datagen.tech 4.18.0-193.28.1.el8_2.x86_64 #1 SMP Thu Oct 22 00:20:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[steve.gindi@kube1 ~]$
- Install tools:
- Network plugin and version (if this is a network-related bug):
- flannel
- 
- Others:
enclosed is a log 
[api-server-log--1466ebab10066092135e4d32c9aa6e45d2b86271a199fdf94f9eec72253eab38ea-json.log](https://github.com/kubernetes/kubernetes/files/5943685/api-server-log--1466ebab10066092135e4d32c9aa6e45d2b86271a199fdf94f9eec72253eab38ea-json.log)

**Comment by liggitt** [comment]
Did you follow the instructions in https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data to enable at-rest encryption? Can you provide the encryption config file (scrubbing any secret key data) and the kube-apiserver invocation you are using?

**Comment by CharmingSteve** [comment]
@liggitt Yes, I followed the instructions there several times  https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data . It simply  did not encrypt, the secrets stayed readable clear text.

**Comment by liggitt** [comment]
Can you provide the encryption config file (scrubbing any secret key data) and the kube-apiserver invocation you are using?
