### ISSUE TITLE
Uplift cadvisor version to include fix for Incorrect CPU topology generated on Single NUMA and Multi socket system

### ISSUE THREAD

**Issue by hanamantagoudvk** [kubernetes/kubernetes#98870]
**What happened**:

Incorrect CPU topology generated by cadvisor on Single NUMA and Multi socket system leads to performance degradation for POD.

https://github.com/google/cadvisor/issues/2798

**What you expected**:

cadvisor team is working on fix for the above mentioned issue.

Current k8s release v1.20 should uplift the cadvisor version to include the above fix.

Backport the fix to older version of k8s release v.1.19.3 , when cadvisor backport the fix older version on cadvisor (probably 0.37.x)

**Environment**:
- Kubernetes version (use `kubectl version`): v.1.19.3

**Comment by hanamantagoudvk** [comment]
cadvisor fix for this issue is available in 0.38.8 and 0.37.5

k8s version 1.20.3 patch release uses cadvisor 0.38.7. 

So we request for new k8s patch release with cadvisor 0.38.8

**Comment by ehashman** [comment]
Does this also affect 1.18?

**Comment by hanamantagoudvk** [comment]
No it does not affect k8s 1.18 version because both kubelet (v1.18) and cadvisor (v0.35) think Topology represents sockets.

Whereas ,
a) k8s version 1.19.3, cAdvisor version 0.37.0: k8s still thinks that Topology represents sockets, cAdvisor now returning NUMA Nodes
b) k8s version master (thanks to that commit [0]) ,  cAdvisor 0.37.0+: now both thinks that Topology represents NUMA Nodes.

For k8s 1.20+ which references cadvisor 0.38.7 , we need backport of fix [0] from master.

[0] https://github.com/kubernetes/kubernetes/pull/90980/commits/a047e8aa1b705bb7e5be881fb63cf90a218b60d0

**Comment by iwankgb** [comment]
@ehashman I think that @hanamantagoudvk is half-right:
* `release-1.19` is missing a047e8aa1b705bb7e5be881fb63cf90a218b60d0 but code cherry-picks cleanly. Both changes (to cAdvisor and Kubernetes) constitute a bug fix and it would be great if we could cherry-pick.
* a047e8aa1b705bb7e5be881fb63cf90a218b60d0 **is already available** on `release-1.20`

**Comment by ehashman** [comment]
No issue with the 1.19 cherry-pick here (I LGTM'd), thanks for confirming N/A for 1.18. Just trying to keep the branches relatively in sync :)
