### ISSUE TITLE
[Failing Test] [sig-storage] CSI Volumes pd-csi driver tests failing

### ISSUE THREAD

**Issue by thejoycekung** [kubernetes/kubernetes#98880]
**Which jobs are failing**:
`ci-kubernetes-e2e-gci-gce-serial`

**Which test(s) are failing**:

- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)(allowExpansion)] volume-expand Verify if offline PVC expansion works`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (block volmode)(allowExpansion)] volume-expand Verify if offline PVC expansion works`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (block volmode)(allowExpansion)] volume-expand should resize volume when PVC is edited while pod is using it`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)(allowExpansion)] volume-expand should resize volume when PVC is edited while pod is using it`

**Since when has it been failing**:
Feb 6 16:57PST
5fa704c6a

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-serial&include-filter-by-regex=CSI%20Volumes

**Reason for failure**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1358218259307958272#1:build-log.txt%3A1759
```
I0207 01:13:51.104] STEP: creating a StorageClass volume-expand-40955dxt2
I0207 01:13:51.149] STEP: creating a claim
I0207 01:13:51.150] Feb  7 01:13:51.149: INFO: Warning: Making PVC: VolumeMode specified as invalid empty string, treating as nil
I0207 01:13:51.254] STEP: Creating a pod with dynamically provisioned volume
I0207 01:13:51.964] WARNING: pod log: csi-gce-pd-node-m2c4h/csi-driver-registrar: the server does not allow this method on the requested resource ( pods/log csi-gce-pd-node-m2c4h)
I0207 01:13:52.005] WARNING: pod log: csi-gce-pd-node-m2c4h/gce-pd-driver: the server does not allow this method on the requested resource ( pods/log csi-gce-pd-node-m2c4h)
```

This warning repeats until we get to ... here https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1358218259307958272#1:build-log.txt%3A1773
```
I0207 01:14:29.413] STEP: Deleting the previously created pod
I0207 01:14:29.413] Feb  7 01:14:29.413: INFO: Deleting pod "pod-0016e560-e9c7-4d49-bb59-03de4438d5a8" in namespace "volume-expand-4095"
I0207 01:14:29.454] Feb  7 01:14:29.454: INFO: Wait up to 5m0s for pod "pod-0016e560-e9c7-4d49-bb59-03de4438d5a8" to be fully deleted
I0207 01:14:39.532] STEP: Expanding current pvc
I0207 01:14:39.533] Feb  7 01:14:39.532: INFO: currentPvcSize {{5368709120 0} {<nil>} 5Gi BinarySI}, newSize {{6442450944 0} {<nil>}  BinarySI}
I0207 01:14:39.619] STEP: Waiting for cloudprovider resize to finish
I0207 01:19:20.523] WARNING: pod log: csi-gce-pd-node-m2c4h/csi-driver-registrar: the server does not allow this method on the requested resource ( pods/log csi-gce-pd-node-m2c4h)
I0207 01:19:20.563] WARNING: pod log: csi-gce-pd-node-m2c4h/gce-pd-driver: the server does not allow this method on the requested resource ( pods/log csi-gce-pd-node-m2c4h)
```

And it just repeats those two warnings until it times out.

**Anything else we need to know**:
Most likely related to #98805 ? 
/sig storage
/priority important-soon

**Comment by msau42** [comment]
This was introduced as part of #98805, but unfortunately the pull-kubernetes-e2e-gce-csi-serial job that would have caught this was optional, so the PR merged without waiting for it to complete.

**Comment by thejoycekung** [comment]
Looks to be resolved now

/close
