### ISSUE TITLE
[Flaky] //pkg/kubelet TestSyncPodsDeletesWhenSourcesAreReadyPerQOS

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#98893]
**Which jobs are flaking**:

pull-kubernetes-bazel-test

**Which test(s) are flaking**:

TestSyncPodsDeletesWhenSourcesAreReadyPerQOS

**Testgrid link**:

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-bazel-test&include-filter-by-regex=%2F%2Fpkg%2Fkubelet:go

**Reason for failure**:

```
    kubelet_test.go:469: 
        	Error Trace:	kubelet_test.go:469
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 0
```

**Anything else we need to know**:

This seems to be the most flaky test in the testgrid.

/sig node

**Comment by BenTheElder** [comment]
seen again in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/98896/pull-kubernetes-bazel-test/1359018213857300480 https://github.com/kubernetes/kubernetes/pull/98896

**Comment by BenTheElder** [comment]
http://go.k8s.io/triage?pr=1&text=TestSyncPodsDeletesWhenSourcesAreReadyPerQOS is not showing a lot, but we cache test results, and any amount of flakiness is too much for a "unit" test ...

**Comment by pacoxu** [comment]
failed again in #98547 😓

**Comment by BenTheElder** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/98912/pull-kubernetes-bazel-test/1359057099899801600 https://github.com/kubernetes/kubernetes/pull/98912 and here.

**Comment by adisky** [comment]
This has been added in this PR https://github.com/kubernetes/kubernetes/pull/98424/files

**Comment by adisky** [comment]
Tried stress testing locally.
```
/tmp/go-stress-20210209T121227-514198642
W0209 12:14:19.093666 1169958 kubelet_getters.go:311] Path "/tmp/kubelet_test.506507027/pods/12345678/volumes" does not exist
W0209 12:14:19.095074 1169958 kubelet_getters.go:311] Path "/tmp/kubelet_test.506507027/pods/12345678/volumes" does not exist
--- FAIL: TestSyncPodsDeletesWhenSourcesAreReadyPerQOS (6.01s)
    kubelet_test.go:469: 
        	Error Trace:	kubelet_test.go:469
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 2
        	Test:       	TestSyncPodsDeletesWhenSourcesAreReadyPerQOS
        	Messages:   	Expect only 1 destroy
FAIL


ERROR: exit status 1

1m55s: 68 runs so far, 15 failures (22.06%)
2m0s: 68 runs so far, 15 failures (22.06%)
```
/triage accepted

**Comment by wzshiming** [comment]
https://github.com/kubernetes/kubernetes/pull/98919

It should be caused by using the same temporary folder.

**Comment by gjkim42** [comment]
I think my PR(https://github.com/kubernetes/kubernetes/pull/98923) addresses the issue.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/90405 https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/90405/pull-kubernetes-bazel-test/1359278391253012480 (continuing to show evidence that this is quite flaky)

thanks @gjkim42

**Comment by alculquicondor** [comment]
@rphillips it seems that this is still failing: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/98817/pull-kubernetes-bazel-test/1359610999572795392

The error looks different than original post.

**Comment by gjkim42** [comment]
> @rphillips it seems that this is still failing: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/98817/pull-kubernetes-bazel-test/1359610999572795392
> 
> The error looks different than original post.

Maybe related to https://github.com/kubernetes/kubernetes/pull/98956#issuecomment-777098717.

**Comment by gjkim42** [comment]
I think https://github.com/kubernetes/kubernetes/pull/98956 already deflaked this issue.

**Comment by ehashman** [comment]
/cc @rphillips 
/close

I think this was fixed.
