### ISSUE TITLE
Ideas of optimizing scheduler perf testing framework

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#98898]
Some ideas to optimizing scheduler perf testing framework:

### 1. Zero values in ThroughputCollector

Currently, we start to calculate the pods being scheduled right after pods' creation. This results in, esp. in a large-scale test (5000 nodes), the first N buckets are all zeros (means 0 pods scheduled so far). The N can be very large in some cases and results in the P50 (even P90) to be 0.

Solution: eliminate buckets that are zero (e.g., start the sampling only after the 1st Pod gets scheduled).

### 2. Value order in ThroughputCollector

Like MetricCollector, ThroughputCollector also keep the small values ahead of large values. It works, but to some extent, it's against natural human being's understanding in P90 and P99 - P99, which should more describe an extreme case and hence behaves badly, holds a large value than P90. While in current testing, P90 can be sth. like "100 pods/s", and P90 be "125 pods/s".

Solution: we may need to **reverse** the ordering.

### 3. Simulate behavior of pods rescheduling

Pods rescheduling (internally from unschedulableQ/backoffQ) are pretty common cases in a real-world cluster. We don't have a good way to simulate this behavior yet.

Solution: Introduce an operator to churn the cluster.

/sig scheduling

**Comment by Huang-Wei** [comment]
cc @adtac @ahg-g @alculquicondor @damemi

**Comment by adtac** [comment]
>1. Zero values in ThroughputCollector

I agree that the p50=0 can makes the test useless, but one can also argue that the current behaviour is also "natural". That is, if scheduler_perf discards zero samples and reports a non-zero p50, when I try to create X pods in prod, I may be surprised by a much lower throughputthan whatever scheduler_perf reported (because that initial latency is still going to be present) .

I don't know what the right solution is because there are problems with both approaches. I'm slightly in favour of your proposed change.

>2. Value order in ThroughputCollector

Ack, I think we can simply report p10% and p1% in addition to p50, p90 and p99 to achieve the same effect without changing the order. This is probably good practice in statistical reporting in general (I believe the term is "confidence interval", but I'm not sure).

>3. Simulate behavior of pods rescheduling

Ack, great idea :+1:

**Comment by alculquicondor** [comment]
Re 1:
The existing problem is that we are recording low throughput when the system just doesn't have that many Pods yet. I agree that discarding 0s is fine.

> I may be surprised by a much lower throughput than whatever scheduler_perf reported 

I don't think that would happen. We will still see a bit of low throughput for the first recordings where there are only a handful of Pods present. But we can re-evaluate later. And, in general, we want to report how the system behaves when it's under stress. We know our latency is good when there are only few pods, so I don't think users are concerned there.

**Comment by Huang-Wei** [comment]
> I may be surprised by a much lower throughput than whatever scheduler_perf reported

Another angle: the performance framework is essentially an integration test, and hence can be easily setup and run on a single machine. The result may vary _a lot_ (esp. if we eliminate the QPS limit) from a Mac developer machine to a powerful Linux server. So I'm using the performance framework more as a handy tool to compare the delta performance results; instead of treating the result as universally applicable.

**Comment by minbaev** [comment]
HI I'm interested in working on the first two items of the issue, since the third item is already being worked on.
It will be my first contribution to k8s

**Comment by minbaev** [comment]
Can work on the first item of the issue since it reached consensus

**Comment by alculquicondor** [comment]
/triage accepted
Feel free to send a PR

**Comment by Huang-Wei** [comment]
> Can work on the first item of the issue since it reached consensus

Yes, feel free to raise a PR. And you can first walk through the scheduler performance doc for an overall understanding on how it's built.

- https://github.com/kubernetes/kubernetes/blob/master/test/integration/scheduler_perf/README.md#benchmark-tests
