### ISSUE TITLE
manage pause image properly as a whole

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#98902]
During I update the pause image to 3.4.1 and update the changelogs/tests/cri configurations, Benjamin pointed out that the approach to managing this image is not that proper.  

I listed some action items for updating the image in https://github.com/kubernetes/kubernetes/pull/98205

**What would you like to be added**:

Add documentation or general process to update/promote/testing the pause image.
Maybe a checkout list or script to check all updates.

**Why is this needed**:
https://github.com/kubernetes/kubernetes/pull/98205#issuecomment-775505191

1. - **build image**: update the pause image
2. - **track image history**: pause image changelog: https://github.com/kubernetes/kubernetes/blob/master/build/pause/CHANGELOG.md
3. - **windows update**: for windows and Linux updating
4. - **e2e testing**: for k/k testing/e2e data
5. - **install configuration**: kubeadm/kubelet configuration
6. - **CRI runtimes**: cri-o/containerd/kind/minikube
7. - **Libs related**: others like containers/common
8. - **websites/docs**: update k8s.io website and some other related docs
9. - **further cases**: kubelet GC should not remove pause image, and so on

**Comment by ehashman** [comment]
/remove-lifecycle rotten
/triage accepted

need a plan for pause.

**Comment by pacoxu** [comment]
After https://github.com/kubernetes/community/blob/06fcf734d74705a8d725770a18fc5280e9e3c484/contributors/devel/sig-node/updating-pause-images.md is merged, I think we can close this.

- #104890 for 3.6 tracking
