### ISSUE TITLE
cleanup docker image building

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#98908]
/kind cleanup
/assign

There's some cleanup we should do of the "docker wrapped binary" image building for the Kubernetes core images
- [x] ~we should properly initialize buildx + qemu _when cross building_  (this should allow us to do e.g. `RUN setcap ...` https://github.com/kubernetes/kubernetes/pull/96134)~ EDIT: we no longer need this, came up with a different solution
   - see also: https://github.com/kubernetes/kubernetes/pull/98672#issuecomment-771110925
- [x] we should use a Dockerfile on-disk for the images + `--arg`, instead of an on the fly generated file with stuff like `sed`
  - fix in https://github.com/kubernetes/kubernetes/pull/99015, https://github.com/kubernetes/kubernetes/pull/99022, https://github.com/kubernetes/kubernetes/pull/99024 @vinayakankugoyal 
- [x] we should use buildx consistently, instead of for certain architectures (see: https://github.com/kubernetes/kubernetes/pull/97459#discussion_r564078148

**Comment by justaugustus** [comment]
(Moved to the Release Engineering board, instead of SIG Release)
/area release-eng

**Comment by vinayakankugoyal** [comment]
Few more PRs related to task 2:
https://github.com/kubernetes/kubernetes/pull/99067
https://github.com/kubernetes/kubernetes/pull/99059

**Comment by BenTheElder** [comment]
/remove-lifecycle stale
I think we're actually done with the points here and follow-up, thanks in particular to @vinayakankugoyal
