### ISSUE TITLE
Can we remove this line at rbac.go

### ISSUE THREAD

**Issue by AlphaWong** [kubernetes/kubernetes#98945]
Hi engineers,

I have a question about the usage of this line at `isSimpleResourceRule` function
https://github.com/kubernetes/kubernetes/blob/2289b02ea30e473dbc89c8160a7a6bb75922a0e7/staging/src/k8s.io/kubectl/pkg/util/rbac/rbac.go#L85 

It does not cover any test case in `policy_compact_test.go`
https://github.com/kubernetes/kubernetes/blob/2289b02ea30e473dbc89c8160a7a6bb75922a0e7/pkg/registry/rbac/validation/policy_compact_test.go#L148

# suggestion
it is safe for us to remove this line? Or this checking has a special purpose to serve.
As I find the struct actually only contains a few simple string type
```go
// https://github.com/kubernetes/kubernetes/blob/7a7778941b50b8854575d943dd72521112509d81/pkg/apis/rbac/types.go#L45
type PolicyRule struct {Eric Chiang, 5 years ago: • pkg/apis: rbac types added
	Verbs []string
	APIGroups []string
	Resources []string
	ResourceNames []string
	NonResourceURLs []string
}
```

Best,
Alpha

**Comment by liggitt** [comment]
that check ensures that any other attributes added to that struct in the future don't silently break the isSimpleResourceRule and CompactRules functions

/close
