### ISSUE TITLE
Unable to modify deployment due to error: map: map[] does not contain declared merge key: name

### ISSUE THREAD

**Issue by curtisr7** [kubernetes/kubernetes#98963]
#### What happened: 

I messed up when I creating a deployment and `spec.template.spec.imagePullSecrets` that was missing a value 

```
...
    spec:
      imagePullSecrets: 
      - name:
...
```

Once I realized my mistake I tried to update the deployment via `kubectl edit` and received the following error:
```
$ kubectl edit deploy
A copy of your changes has been stored to "/var/folders/4r/rr0xd1zs2nbbd1t95dz3jd8m0000gn/T/kubectl-edit-f7f0m.yaml"
error: map: map[] does not contain declared merge key: name
```

Slightly different error if I `kubectl apply -f` an updated deployment

```
warning: error calculating patch from openapi spec: map: map[] does not contain declared merge key: name
error: error when applying patch:

to:
Resource: "apps/v1, Resource=deployments", GroupVersionKind: "apps/v1, Kind=Deployment"
Name: "nginx-deployment", Namespace: "default"
for: "./deployment.yaml": error when creating patch with:
original:
{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"nginx-deployment","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx:1.14.2","name":"nginx","ports":[{"containerPort":80}]}],"imagePullSecrets":[{"name":null}]}}}}

modified:
{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"name\":\"nginx-deployment\",\"namespace\":\"default\"},\"spec\":{\"replicas\":2,\"selector\":{\"matchLabels\":{\"app\":\"nginx\"}},\"template\":{\"metadata\":{\"labels\":{\"app\":\"nginx\"}},\"spec\":{\"containers\":[{\"image\":\"nginx:1.14.2\",\"name\":\"nginx\",\"ports\":[{\"containerPort\":80}]}],\"imagePullSecrets\":[{\"name\":\"value\"}]}}}}\n"},"name":"nginx-deployment","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx:1.14.2","name":"nginx","ports":[{"containerPort":80}]}],"imagePullSecrets":[{"name":"value"}]}}}}

current:
{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1","kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"name\":\"nginx-deployment\",\"namespace\":\"default\"},\"spec\":{\"replicas\":2,\"selector\":{\"matchLabels\":{\"app\":\"nginx\"}},\"template\":{\"metadata\":{\"labels\":{\"app\":\"nginx\"}},\"spec\":{\"containers\":[{\"image\":\"nginx:1.14.2\",\"name\":\"nginx\",\"ports\":[{\"containerPort\":80}]}],\"imagePullSecrets\":[{\"name\":null}]}}}}\n"},"creationTimestamp":"2021-02-10T12:47:40Z","generation":1,"name":"nginx-deployment","namespace":"default","resourceVersion":"492","uid":"cef5a428-f39f-449a-acc4-ab565ec5f0e5"},"spec":{"progressDeadlineSeconds":600,"replicas":2,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"nginx"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx:1.14.2","imagePullPolicy":"IfNotPresent","name":"nginx","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":2,"conditions":[{"lastTransitionTime":"2021-02-10T12:47:52Z","lastUpdateTime":"2021-02-10T12:47:52Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2021-02-10T12:47:41Z","lastUpdateTime":"2021-02-10T12:47:52Z","message":"ReplicaSet \"nginx-deployment-7d46b76957\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":1,"readyReplicas":2,"replicas":2,"updatedReplicas":2}}

for: "./deployment.yaml": map: map[] does not contain declared merge key: name
```

I found that I can cleanup this error by creating patch and applying via - `kubectl patch deploy --type=merge`

#### What you expected to happen:

1. I shouldn't have been able to create this deployment in the first place
2. I should be able to modify the deployment without jumping through additional hoops

#### How to reproduce it (as minimally and precisely as possible):

See description. Net - create a deployment with 

```
...
    spec:
      imagePullSecrets: 
      - name:
...
```

#### Anything else we need to know?:

I encountered this while using helm[1]

[1] https://github.com/helm/helm/issues/9259

#### Environment:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T08:38:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
```
$ minikube version
minikube version: v1.16.0
commit: 9f1e482427589ff8451c4723b6ba53bb9742fbb1
```

**Comment by yliaog** [comment]
please take a look at https://github.com/kubernetes/kubernetes/issues/85332

**Comment by yliaog** [comment]
https://github.com/kubernetes/kubernetes/blob/b1a2a99f1fe1622d20b68abaa99348e19a35c704/staging/src/k8s.io/api/core/v1/types.go#L3040

	// +patchMergeKey=name
	// +patchStrategy=merge
	ImagePullSecrets []LocalObjectReference `json:"imagePullSecrets,omitempty" patchStrategy:"merge" patchMergeKey:"name" protobuf:"bytes,15,rep,name=imagePullSecrets"`

**Comment by yliaog** [comment]
https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/ has explanations about strategic merge patch vs json merge patch.

the default is 'strategic merge patch', and it requires that the merge key 'name' must be present.

"kubectl patch deploy --type=merge" uses json merge patch instead.

**Comment by yliaog** [comment]
i agree it's better to add more validation to prevent this kind of error

**Comment by curtisr7** [comment]
> i agree it's better to add more validation to prevent this kind of error

Whatever validation is performed on update should also be applied on create

**Comment by parmjassal** [comment]
As i am new to contributing, Can i work on this issue?
After some greping found the validation. Do i need to add the validation over [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L3041) to prevent the name to be empty. 
If not, please guide to solve this.

**Comment by curtisr7** [comment]
It seems odd that this misconfiguration would result in a warning rather than an error, but closing is fine by me

**Comment by andrei-verdes** [comment]
@curtisr7 It will result in a warning so it can remain backwards compatible. If we threw an error, objects created without a spec.imagePullSecrets.name value, wouldn't be deletable in the cluster after applying my commit.

Can you please confirm that the issue is tracked in https://github.com/kubernetes/kubernetes/issues/94626 and close this issue yourself by commenting "/close"
