### ISSUE TITLE
kubelet: all docker calls should have timeouts

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#9896]
@ArtfulCoder and I observed a situation where kubelet's syncLoop was not running. The action item here is to make sure that any calls to e.g. docker have timeouts, so that syncLoop can't get stuck.

@dchen1107

**Comment by dchen1107** [comment]
This is really a good idea, and we should do this. But I am not sure we can make it for the first 1.0 cut. Basically we are using fsouza/go-dockerclient for the Docker remote API which doesn't have an option to specify timeout for those calls. I can improve such library, but don't think it can be done in v1.0, which means this week or next week. :-)

**Comment by dchen1107** [comment]
Assign it to myself. I will try to update the library as soon as possible.

**Comment by bprashanth** [comment]
We should also be able to rate limit the requests to docker at 30qps (think this is easily achievable for 1.0, if we want it). That is arguably better than timing out a client request that leads to further retries.

**Comment by smarterclayton** [comment]
The scenario we hit was a hanging docker call that blocked other code.  Max timeouts should probably be enforced at very high time limits (minutes) to reduce the risk of wedges

**Comment by dchen1107** [comment]
For 1.3 release, we are talking about switching to use docker client library which has timeout for most of docker API calls.

**Comment by yujuhong** [comment]
Prerequisites: switch to using the docker engine-api client #20895

**Comment by yujuhong** [comment]
Closing this as the work has been completed. There is only one call (image pull) without any timeout, and that will be addressed in #26300

**Comment by Random-Liu** [comment]
@yujuhong Thanks! :)
