### ISSUE TITLE
Allow deletion of a collection of services in the REST API

### ISSUE THREAD

**Issue by kieranjbrown** [kubernetes/kubernetes#98994]
#### What would you like to be added:
The Kubernetes REST API offers some great functionality for managing the resources in a given cluster, and I use it to automatically delete resources that are no longer needed. However, whilst most of the major resources offer a `deletecollection` option (e.g. deployments, ingress, configmaps), services don't. As verified by executing `kubectl api-resources -o wide`, services only has a `delete` option, not a `deletecollection` option. Likewise this is also verifiable in the REST API docs (https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#delete-service-v1-core), having a `delete` endpoint but no `deletecollection`

#### Why is this needed:
Mass deletion of resources is something I do regularly by deleting anything with a matching flag (I use this for deleting deployments of pull request branches regularly). It's easy enough to achieve for deployments, but for services this step involves doing a `GET` for all the services matching my label then individually deleting them. I can't see why services wouldn't have this simple functionality that others do

**Comment by liggitt** [comment]
/remove-sig api-machinery
/sig networking

this is because the service REST handler overrides standard deleting handling to customize endpoint cleanup

**Comment by liggitt** [comment]
Some of the work @thockin did recently to allow moving endpoint and lease cleanup logic into the strategy would likely make this more possible, but needs to be carefully tested. 

/assign @thockin

**Comment by thockin** [comment]
Is this the same as https://github.com/kubernetes/kubernetes/pull/85802 ?

**Comment by kieranjbrown** [comment]
Appears so yes - although that has been left for quite a while

**Comment by astefanutti** [comment]
I can try to allocate some time to work/help on it. Some guidance will definitely help me, and/or any pointers to that new lease cleanup logic @liggitt mentioned.

**Comment by thockin** [comment]
The "cleanup" is https://github.com/kubernetes/kubernetes/pull/96684, but
it's kind of huge.  I need to finish porting tests (for update) to the
newer approach and do a bunch of straggler cleanup.  Help is welcome, but
it's daunting to jump into such a large change.

I'll have to look at this and see if it makes sense to do before finishing
the cleanup.

**Comment by astefanutti** [comment]
Thanks. I'll wait then for your feedback on how best to move forward on this.

**Comment by thockin** [comment]
Full transparency - that major PR is semi-stalled until I can find time to
finish it.

**Comment by jayunit100** [comment]
i think we can leave this open for now... its just hanging ... will be a long tail issue
