### ISSUE TITLE
Multiple Pull Policies (Fallback to secondary pull policy)

### ISSUE THREAD

**Issue by Starttoaster** [kubernetes/kubernetes#99009]
#### What would you like to be added:

A container spec that allows for a list of pull policies, where the first pull policy in the list is selected by default. But after a certain number of failures to pull, falls back to the next pull policy in the list.

#### Why is this needed:

Many people want to use the `Always` image pull policy to ensure that their pods are always getting the latest image version of a given tag on start. The `Always` pull policy assumes that the container registry is 100% available with 0 downtime. In the event that the registry is not available, instead of falling back on a local cache, the pod will fail to start up.

Instead of failing to start up, which a user might expect from the `Always` pull policy, there might be times when the user would rather kubernetes to fall back to a secondary pull policy like `IfNotPresent`

GitLab has already implemented this in their GitLab Runner project for the docker-machine executor: https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/2587

And they are also working to implement this in their Kubernetes executor: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/27298

**Comment by haircommander** [comment]
CRI-O provides this feature through registry mirroring in [registries.conf](https://github.com/containers/image/blob/main/registries.conf), as does [containerd](https://github.com/containerd/containerd/blob/main/docs/cri/registry.md) I believe. Would either of those meet your needs @Starttoaster

**Comment by trastle** [comment]
/reopen (if I am allowed)

Having looked at the above container runtime features mentioned by @haircommander I don't think they quite cover the case mentioned above. 

Setting the image pull policy to Always with a fallback of IfNotPresent would allow the use of the latest image from the remote registry with a fallback to a locally cached copy of the image if the remote registry pull is temporarily unavailable.

The features referenced above in the container runtime reference multiple remote registries. If one fails, another will be used.

To me these seem like different solutions to the problem.

**Comment by haircommander** [comment]
yeah that is a good point, I am not sure I properly understood the request when making that comment :upside_down_face: 

However, wouldn't having a local cache registry for the mirror satisfy this need? It could basically serve the images the node currently has, so if the pull failed, it would fall back to the local image. It is a roundabout way of satisfying this need, but it is possible now and doesn't require adding a kubernetes feature

**Comment by clayvan** [comment]
Looks like I'm a couple years too late, but this seems to be the only place discussing this important feature.

My understanding is that ImagePullPolicy: Always is part of the CIS benchmark hardening (and probably the STIG).

However, if the registry is down or credentials are expired, and your container crashes and restarts (not a human initiated pod rescheduling event), that container will attempt to re-pull and fail, causing a downtime.

So now we are faced with the decision of following K8s hardening OR ensuring we have zero downtime.

My proposal would be the same as the above, there should be either a fallback pull policy, or a new one for `Always-if-present` or the like.

Am I missing something? Is there another solution out there?

**Comment by haircommander** [comment]
@clayvan another option would be to utilize CRI implementation registry mirroring so there could be a fallback registry. Personally, I don't know if `always-if-present` would be broadly useful enough to be worth implementing, it seems like a narrow use case to me
