### ISSUE TITLE
Use helper functions to clean up test-cases (specifically net but not really specific)

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#99005]
Inspired by #98726

There are a lot of tests (pkg/apis/networking/validation/validation_test.go in that PR) that have tables of structures like Service or NetworkPolicy, where the struct has to be complete enough (e.g. to pass validation) but each test-case only modifies one tiny section of the otherwise boilerplate struct.

The result is a LOT of noise which makes the actual differences hard to see.

Compare to something like pkg/registry/core/service/strategy_test.go `TestDropTypeDependentFields`, where all the boilerplate is wrapped up in a helper function, and specifically named "tweaks" are run against the result.  The net result is that the test-case only emphasizes things it is changing and is WAY shorter and less noisy.

I'm filing this because I look at a lot of sig-net tests, but it can apply anywhere we have repeated struct initializers eating tons of LOC.

This pattern can be applied incrementally - one test function or file at a time.  Good opportunity to rack up some cleanup PRs.

**Comment by danielamlins** [comment]
I would like to take this one, at least for net. This will be my first time contributing to kubernetes, so I might take a while.

**Comment by rclemsmith** [comment]
Hi, Im a newbie to Open Source Contribution. Can more than one person work on solving an issue. If so, I would like to help on fixing this issue. And can you direct me where to start ?

**Comment by danielamlins** [comment]
Right now I am working on TestValidateNetworkPolicy in pkg/apis/networking/validation/validation_test.go. I think you can grab another test or another test file if you wish, let's just write it down here in the issue.

**Comment by JornShen** [comment]
There are two methods `TestValidateIngressClass ` and `TestValidateIngressClassUpdate` inpkg/apis/networking/validation/validation_test.go  ,  I think you can try to refactor. 

Other method I see already have related tweaks operation.

@rclemsmith

**Comment by mowangdk** [comment]
It seems like there are a lot of tests need to clean up.  can i take ```pkg/apis/storage/validation``` part?

**Comment by mauricepoirrier** [comment]
Hey guys, as @mowangdk says, there are a lot of boilerplate on other tests, should I take `/pkg/apis/apps/validation/validation_test.go` ?

**Comment by BLasan** [comment]
@thockin Anyone working on this?

**Comment by danielamlins** [comment]
Sorry, I just started in a new job and I have been very busy. I plan to get back to this when I have more time :)

**Comment by vivekab** [comment]
I want to take this one. Are there any open tweaks that I can work with?

**Comment by libaoan** [comment]
Hi, guys
I'm a newguy, let me try agian
/assign

**Comment by MorrisLaw** [comment]
/assign @MannyGutierrez98

Here's a good first issue to work on.

**Comment by mgutierrez98** [comment]
@MorrisLaw hey i think you @'d the wrong account, feel free to assign me to this now that iv commented.

**Comment by vikramcse** [comment]
Hello @MorrisLaw 
This will my first contribution to Kubernetes.
I am working on two methods `TestValidateIngressClass ` and `TestValidateIngressClassUpdate` in pkg/apis/networking/validation/validation_test.go
