### ISSUE TITLE
[Flake][IPVS][sig-network] ESIPP [Slow] should work from pods

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#99018]
The test failure rate is ... bad :(
https://testgrid.k8s.io/sig-network-gce#gci-gce-ipvs&width=5

##### Error text:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/loadbalancer.go:1035
Jan 29 03:31:00.492: Source IP not preserved from pause-pod-deployment-776586b75-8gxg8, expected '10.64.3.218' got ''
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113
```
#### Recent failures:
[2/12/2021, 7:42:41 AM ci-kubernetes-e2e-gci-gce-ipvs](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ipvs/1360117037086543872)
[2/12/2021, 5:00:45 AM ci-kubernetes-e2e-gci-gce-ipvs](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ipvs/1360076286965321728)
[2/12/2021, 3:54:51 AM ci-kubernetes-e2e-gci-gce-ipvs](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ipvs/1360059702611808256)
[2/12/2021, 2:52:40 AM ci-kubernetes-e2e-gci-gce-ipvs](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ipvs/1360044052346572800)
[2/12/2021, 12:47:40 AM ci-kubernetes-e2e-gci-gce-ipvs](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ipvs/1360012595322425344)

/kind failing-test
/kind flake
/sig network

**Comment by aojea** [comment]
tagging main ipvs folks for visibility @andrewsykim @uablrek @lbernail

**Comment by uablrek** [comment]
```
+ curl -q -s --connect-timeout 30 35.203.144.104:80/clientip
command terminated with exit code 7
```
until timeout. From "man curl";
```
       7      Failed to connect to host.
```

**Comment by uablrek** [comment]
Are the originating POD and the server-pod on the same node?

Otherwise you will hit https://github.com/kubernetes/kubernetes/issues/93456

**Comment by aojea** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ipvs/1360117037086543872
:eyes: 
server
```
Feb 12 07:28:44.969: INFO: external-local-pods-9gghc  bootstrap-e2e-minion-group-2nkx  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2021-02-12 07:17:42 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2021-02-12 07:17:46 +0000 UTC  } {ContainersReady True 0001-01-01 00:00:00 +0000 UTC 2021-02-12 07:17:46 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2021-02-12 07:17:42 +0000 UTC  }]
```
client
```
ï¿½[1mSTEPï¿½[0m: Hitting external lb 35.203.144.104 from pod pause-pod-deployment-788dcdc5d6-j4skr on node bootstrap-e2e-minion-group-hnzn
```
it seems they are using different nodes

**Comment by uablrek** [comment]
Ok, the reason is sorted out, but what to do about it?

If #93456 is a bug that shall be fixed the test _should_ fail.

**Comment by jayunit100** [comment]
```I0212 10:15:42.876] Command stdout:
I0212 10:15:42.876] 
I0212 10:15:42.876] stderr:
I0212 10:15:42.876] + curl -q -s --connect-timeout 30 35.233.235.76:80/clientip
I0212 10:15:42.876] command terminated with exit code 7```

exit code 7, i guess nothing is listening?

**Comment by jayunit100** [comment]
I agree, i guess we should just leave this test as failing - until the IPVS thing is fixed, but at  least in the time being we should add a wanring in the test logs, to capture the reality of the situation, right `framework.Logf("this failure is expected due to a bug in ipvs load balancing, see #93456 for details")` or whatever...

**Comment by jayunit100** [comment]
- oddly looking at this job , we still use `docker` for the ipvs tests...
![image](https://user-images.githubusercontent.com/826111/107784723-c87a4b80-6d19-11eb-8758-69fa32d0d7da.png)

- but we use `containerd` of course for all the other tests
![image](https://user-images.githubusercontent.com/826111/107784683-ba2c2f80-6d19-11eb-81aa-e61909e4993f.png)

**Comment by thockin** [comment]
ping @jayunit100

**Comment by thockin** [comment]
ping @jayunit100

**Comment by jayunit100** [comment]
Ok, looking back, 
- why are we still using `docker` for these tests ? 
- do we need to update test-grid for these  ?
- are people ok with making the test more self-explanatory as noted above?

**Comment by aojea** [comment]
> Ok, looking back,
> 
> * why are we still using `docker` for these tests ?
> * do we need to update test-grid for these  ?
> * are people ok with making the test more self-explanatory as noted above?

yeah, well, that is the so called "maintenance" :)

**Comment by jayunit100** [comment]
## relaying discussion from sig-network today

ok, so i guess at the next sig-network meeting we need to make a call ~ i.e.  does someone want to maintain IPVS on testgrid, or not.  IF not i guess as @aojea suggested - we need to make a long term plan on wether its part of the overall tested/supported matrix.

**Comment by uablrek** [comment]
For the problem reported in this issue I must check if `internalTrafficPolicy: PreferLocal` really helps as described in https://github.com/kubernetes/kubernetes/pull/97081#discussion_r568101316.

If not, I would like https://github.com/kubernetes/kubernetes/pull/97081 to be reconsidered.

The more general discussions about proxy-mode=ipvs maintencance should be taken else where IMHO.

**Comment by uablrek** [comment]
And BTW we have a use-case where proxy-mode=ipvs works but proxy-mode=iptables doesn't;

Source-based policy routing can be used, like: "all traffic _from_ a loadBalancer ip routed to oam-router".

In some setups this can replace _very many_ destination routing rules. However this works _only_ with proxy-mode=ipvs since the reversed NAT is made before the routing decision.

**Comment by aojea** [comment]
> For the problem reported in this issue I must check if `internalTrafficPolicy: PreferLocal` really helps as described in [#97081 (comment)](https://github.com/kubernetes/kubernetes/pull/97081#discussion_r568101316).
> 
> If not, I would like #97081 to be reconsidered.
> 
> The more general discussions about proxy-mode=ipvs maintencance should be taken else where IMHO.


Thanks Lars for digging into it, based on your comment we can skip the test as known issue.
We can reenable it once 97081 is solved
https://github.com/kubernetes/test-infra/pull/21447
