### ISSUE TITLE
Admission controller to attach additional secrets to a service account

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#9902]
The following does not work but I would like it to:

```
# Make secret
$ kubectl create -f - <<EOF
apiVersion: v1
data:
  thing: dGVzdAo=
kind: Secret 
metadata:
  name: test-secret
type: Opaque
EOF
secrets/test-secret
# Make non-default service account
$ kubectl create -f - <<EOF
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa
EOF
serviceaccounts/test-sa
# Verify creation and get the existing token name
$ kubectl get serviceaccounts/test-sa -oyaml 
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: 2015-06-16T21:52:39Z
  name: test-sa
  namespace: default
  resourceVersion: "313260"
  selfLink: /api/v1/namespaces/default/serviceaccounts/test-sa
  uid: 02348e46-1572-12e5-afc2-41010ae0021f
secrets:
- name: test-sa-token-wr9j3
#  Update service account to have another secret
$ kubectl update -f - <<EOF
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa
secrets:
- name: test-sa-token-wr9j3
- name: test-secret
EOF
serviceaccounts/test-sa
# Create a pod that uses test-sa and both its secrets 
$ kubectl create -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: p1
spec:
  containers:
  - image: progrium/busybox
    name: c
    command: [ "ls", "-lR", "/var/run/secrets/"]
  serviceAccount: test-sa
  restartPolicy: Never
EOF
# Sadly, only one secret got mounted.
$kubectl get pods/p1 -oyaml | grep volumes -A 3
  volumes:
  - name: test-sa-token-wr9j3
    secret:
      secretName: test-sa-token-wr9j3
```

@liggitt is there a way to talk the service account controller into mounting the second secret?

**Comment by liggitt** [comment]
No… there's no place to indicate default mount points or intent to auto mount. I think @pmorie had one or more issues open about that specifically related to secrets, aside from service accounts, but not much happened with them yet

**Comment by erictune** [comment]
Do you and pmorie agree this is something that we'd want to do in kubernetes, aside from the issue of agreeing on default mount points for ad-hoc secrets?

**Comment by ibotty** [comment]
Regarding the mount point: What about using an annotation in the secret and if none is given, mounting below `/run/secrets/kubernetes.io/secrets/<name>`?

**Comment by ibotty** [comment]
Oh, and that should definitely be opt-in per container in the pod: Privilege separation within a pod!

**Comment by erictune** [comment]
If it is opt in per container, then there is nothing left to do here!

**Comment by liggitt** [comment]
[automountServiceAccountToken](https://github.com/kubernetes/kubernetes/pull/37953) option was added to service account and to pod spec

[PodPresets](https://kubernetes.io/docs/user-guide/pod-preset/) allow automounting additional secrets/configmaps

**Comment by erictune** [comment]
@droot
