### ISSUE TITLE
weird error message for ip6tables-save / restore in ipvs kube proxy logs

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#99031]
#### What happened:

(update: likely this is benign, but it seems really weird when your reading kube proxy logs) 

- in healthy, IPTABLES jobs, the various ip6tables-restore commands are happy.... 
```

I0212 11:19:29.343337       1 iptables.go:416] running ip6tables-restore [-w 5 -W 100000 --noflush --counters]
I0212 11:19:29.345654       1 proxier.go:1651] "Deleting conntrack stale entries for Services" ips=[]
I0212 11:19:29.345723       1 proxier.go:1657] "Deleting conntrack stale entries for Services" nodeports=[]
I0212 11:19:29.345765       1 proxier.go:1664] "Deleting stale endpoint connections" endpoints=[]
I0212 11:19:29.345779       1 proxier.go:830] "syncProxyRules complete" elapsed="53.750935ms"
```
- MEANWHILE  in ipvs jobs (healthy, or non healthy, we see that some of the iptables dont exist which makes sense...   why is ipvs kube proxy tyrying to do iptables-restore operations on  the `nat` table ?  why is it trying to do iptables stuff *at all* ?  
```
I0212 11:16:50.747339       1 iptables.go:416] running ip6tables-restore [-w 5 -W 100000 --noflush --counters]
E0212 11:16:50.751646       1 proxier.go:1619] Failed to execute iptables-restore: exit status 2 (ip6tables-restore v1.8.5 (legacy): ip6tables-restore: unable to initialize table 'nat'
```

It seems like we get `iptables-restore` error messages when running ipv6.  not sure why though? in particular i found these errors when looking at the test failures for https://github.com/kubernetes/kubernetes/issues/99018 

#### What you expected to happen:

You wouldnt see error messages for ip6tables-restore when running ipvs tests.  This may be my own ignorance however, i.e. maybe this is normal. 

#### How to reproduce it (as minimally and precisely as possible):

I guess every job has this (wether or not the job passes or fails) ?  Here is an example from a passing test.... 
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ipvs/1360184247821799424/artifacts/bootstrap-e2e-minion-group-0q7f/kube-proxy.log 

Similar logs from a failing tests that i originally saw this message ...

- https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ipvs/1360165096948502528/artifacts/bootstrap-e2e-minion-group-kj6x/kube-proxy.log 
- https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ipvs/1360165096948502528/artifacts/bootstrap-e2e-minion-group-1l3l/kube-proxy.log
- https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ipvs/1360165096948502528/artifacts/bootstrap-e2e-minion-group-m52w/kube-proxy.log

has this failure, it is reproduced via the corresponding ci job ...

the logs in the kube-proxy for one of the nodes look like this:

```
I0212 10:03:39.735971       1 bounded_frequency_runner.go:304] sync-runner: 1.022588529s since last run, possible in 8.977411471s, scheduled in 8.977434941s
I0212 10:03:41.058181       1 config.go:351] Calling handler.OnServiceUpdate
I0212 10:03:41.058238       1 service.go:279] Service esipp-4128/external-local-pods updated: 1 ports
I0212 10:03:41.058268       1 bounded_frequency_runner.go:304] sync-runner: 2.344886585s since last run, possible in 7.655113415s, scheduled in 7.655135774s
I0212 10:03:41.181710       1 config.go:260] Calling handler.OnEndpointSliceUpdate
I0212 10:03:43.685594       1 config.go:260] Calling handler.OnEndpointSliceUpdate
I0212 10:03:43.685696       1 bounded_frequency_runner.go:304] sync-runner: 4.972312847s since last run, possible in 5.027687153s, scheduled in 5.027702757s
I0212 10:03:44.147732       1 config.go:260] Calling handler.OnEndpointSliceUpdate
I0212 10:03:44.147818       1 bounded_frequency_runner.go:304] sync-runner: 5.43443661s since last run, possible in 4.56556339s, scheduled in 4.565586328s
I0212 10:03:47.619505       1 config.go:334] Calling handler.OnServiceAdd
I0212 10:03:47.619552       1 utils.go:179] Skipping service test in namespace statefulset-4758 due to clusterIP = "None"
I0212 10:03:47.619574       1 utils.go:179] Skipping service test in namespace statefulset-4758 due to clusterIP = "None"
I0212 10:03:47.619592       1 bounded_frequency_runner.go:304] sync-runner: 8.906210899s since last run, possible in 1.093789101s, scheduled in 1.093830216s
I0212 10:03:48.206917       1 proxier.go:1063] Syncing ipvs Proxier rules
I0212 10:03:48.206970       1 iptables.go:351] running ip6tables-save [-t filter]
I0212 10:03:48.209648       1 iptables.go:351] running ip6tables-save [-t nat]
E0212 10:03:48.213253       1 proxier.go:1949] Failed to execute iptables-save, syncing all rules: exit status 1
E0212 10:03:48.216444       1 proxier.go:1907] Failed to ensure that nat chain KUBE-MARK-DROP exists: error creating chain "KUBE-MARK-DROP": exit status 3: ip6tables v1.8.5 (legacy): can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
I0212 10:03:48.261278       1 iptables.go:416] running ip6tables-restore [-w 5 -W 100000 --noflush --counters]
E0212 10:03:48.264469       1 proxier.go:1619] Failed to execute iptables-restore: exit status 2 (ip6tables-restore v1.8.5 (legacy): ip6tables-restore: unable to initialize table 'nat'

Error occurred at line: 1
Try `ip6tables-restore -h' or 'ip6tables-restore --help' for more information.
)
Rules:
*nat
-A KUBE-SERVICES -m addrtype --dst-type LOCAL -j KUBE-NODE-PORT
-A KUBE-LOAD-BALANCER -j KUBE-MARK-MASQ
-A KUBE-FIREWALL -j KUBE-MARK-DROP
-A KUBE-POSTROUTING -m mark ! --mark 0x00004000/0x00004000 -j RETURN
-A KUBE-POSTROUTING -j MARK --xor-mark 0x00004000
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -j MASQUERADE --random-fully
-A KUBE-MARK-MASQ -j MARK --or-mark 0x00004000
COMMIT
*filter
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding rules" -m mark --mark 0x00004000/0x00004000 -j ACCEPT
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding conntrack pod source rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding conntrack pod destination rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A KUBE-NODE-PORT -m comment --comment "Kubernetes health check node port" -m set --match-set KUBE-6-HEALTH-CHECK-NODE-PORT dst -j ACCEPT
COMMIT
I0212 10:03:48.264493       1 proxier.go:1042] syncProxyRules took 57.601179ms
```
#### Anything else we need to know?:

ill add more links as i collect more data.  

#### Environment:
- Kubernetes version (use `kubectl version`): prow (main branch as of feb 12 2021)

**Comment by jayunit100** [comment]
maybe this is just part of https://github.com/kubernetes/kubernetes/issues/93456

**Comment by jayunit100** [comment]
@uablrek  any idea on why those ipv6 errors are printed in ipvs code ?

**Comment by aojea** [comment]
The proxier is configured in dual-stack mode in the CI

> I0212 19:59:52.549380       1 server_others.go:260] creating dualStackProxier for ipvs.

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ipvs/1360316009235353600/artifacts/bootstrap-e2e-minion-group-nhc7/kube-proxy.log

**Comment by uablrek** [comment]
I don't get similar printouts myself so I can't say anything for sure.

By first check the old re-occuring (and very annoying) "KUBE-MARK-DROP" problem. This chain is usually created by "kubeadm" but so far kubeadm is unaware of dual-stack and has only created this chain for ipv4 (in iptables). Then it needs to be created for IPv6 before kube-proxy is started;
```
ip6tables -t nat -N KUBE-MARK-DROP
```
In my test cluster I _always_ do this in a prep-stage before starting K8s.

**Comment by aojea** [comment]
The ci nodes doesn't have the kernel ip6tables nat modules loaded, hence they fail all the operation related

**Comment by jayunit100** [comment]
hmmm ok so is the issue here that we need to load that module in the CI jobs?

**Comment by rikatz** [comment]
signing here because I want to at least find why ip6tables restore is called on kube-proxy ipvs things :D

**Comment by aojea** [comment]
> hmmm ok so is the issue here that we need to load that module in the CI jobs?

I think that kube-proxy should implement something similar to what @danwinship implemented in kubelet https://github.com/kubernetes/kubernetes/pull/95378

The nat table for IPv6 was added in 3.7

>                nat:
>                   This table is consulted when a packet that creates a new connection is encountered.  It consists  of  four  built-ins:  PREROUTING  (for
>                   altering  packets as soon as they come in), INPUT (for altering packets destined for local sockets), OUTPUT (for altering locally-gener‐
>                   ated packets before routing), and POSTROUTING (for altering packets as they are about to go out).  IPv6 NAT support is  available  since
>                   kernel 3.7.

and it seems that it may be not present in some systems.


/cc @thockin

**Comment by danwinship** [comment]
> The nat table for IPv6 was added in 3.7 ... and it seems that it may be not present in some systems.

I think it's mostly just about whether IPv6 is enabled, not about the kernel version.

**Comment by aojea** [comment]
> I think it's mostly just about whether IPv6 is enabled, not about the kernel version.

IIRC this specific error in the CI is about the nat module only

Anyway, you fixed it :clap: 
/unassign
/assign @danwinship
