### ISSUE TITLE
Move filesystem resize code to kubernetes/mount-utils

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#99039]
#### What would you like to be added:
Volume resizing code (https://github.com/kubernetes/kubernetes/blob/master/pkg/util/resizefs/) should be available in kubernetes/mount-utils

#### Why is this needed:
It can be shared among with CSI drivers, reducing code duplication.

/sig storage

**Comment by gavinfish** [comment]
/assign
ramp up storage sig
