### ISSUE TITLE
Windows httpd and httpd-new test images breaks due to incorrect architecture for PHP library.

### ISSUE THREAD

**Issue by jeremyje** [kubernetes/kubernetes#99047]
#### Which test(s) are failing:
* Kubernetes e2e suite: [sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should have a working scale subresource [Conformance]
* Kubernetes e2e suite: [sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should perform canary updates and phased rolling updates of template modifications [Conformance]

and a few others.

#### Reason for failure: httpd and httpd-new images startup immediately crashing with
`httpd.exe: Syntax error on line 73 of C:/usr/local/apache2/conf/httpd.conf: Cannot load c:/tools/php74/php7apache2_4.dll into server: %1 is not a valid Win32 application. `

**Comment by jsturtevant** [comment]
/cc @claudiubelu @chewong

should be resolved by #99030

**Comment by chewong** [comment]
Currently blocked because there are some issues pushing the httpd test images to `gcr.io/k8s-staging-e2e-test-images`. Slack thread: https://kubernetes.slack.com/archives/CCK68P2Q2/p1613471846127000

**Comment by jsturtevant** [comment]
Latest thread: https://app.slack.com/client/T09NY5SBT/C7J9RP96G/thread/C7J9RP96G-1613494782.046800

**Comment by jsturtevant** [comment]
The job failing is: https://prow.k8s.io/?job=post-kubernetes-push-e2e-httpd-new-test-images

**Comment by jsturtevant** [comment]
https://github.com/kubernetes/test-infra/issues/20884 is where the fixes for publishing this image is being tracked
