### ISSUE TITLE
Alternative to AWS lambda serverless concept in Kubernetes.

### ISSUE THREAD

**Issue by ajaysg94** [kubernetes/kubernetes#99041]
I am new to devops world and forgive me if my question doesn't sound logical. My usecase is as follows.
I have 100's of AI models stored in AWS s3 bucket. My organization currently using Kubernetes containers to serve all its different microservices.
How I want my microservice to be implemented using Kubernetes:
When a request comes to a container with a particular model name, corresponding model from the s3 should be loaded in the container memory and the user will start the inference. Similarly if another request comes with another model name, new container should spin off and start the inference. For n model requests, n containers should spin off and serve each session. Containers should automatically scale up with different requests.

When I found out the above logic is similar to how AWS lambda function works, I was recommending lambda to my devops team. "They informed that they cannot use AWS lambda for a single microservice since it is serverless and all other microservices of my organization runs in Kubernetes"

My question is can the same concept be implemented with Kubernetes?. If so please suggest a method or doc.

Thanks in advance.

**Comment by neolit123** [comment]
hi, this tracker is for bugs / features.
please try discuss / slack / stackoverflow for this:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
/close
