### ISSUE TITLE
Backport APIService SSA fix to older versions of kubernetes

### ISSUE THREAD

**Issue by kevindelgado** [kubernetes/kubernetes#99046]
Server-side apply for APIService was previously broken (https://github.com/kubernetes/kubernetes/issues/89264) and fixed by https://github.com/kubernetes/kubernetes/pull/98576

Controllers that run on older clusters and want to migrate to SSA need this to work (https://github.com/kubernetes/kubernetes/pull/98576#issuecomment-778492399)

Conflicts might arise due to changes since those previous k8s versions were released (specificially https://github.com/kubernetes/kubernetes/pull/95736)

/cc @apelisse @Liujingfang1 
/sig api-machinery
/kind bug

**Comment by liggitt** [comment]
Before we backport, it looks like the dual-registration of the openapi/v2 handler for kube-aggregator is producing a spurious error message in the log:

```
E0215 14:39:12.859889    6038 pathrecorder.go:107] registered "/openapi/v2" from goroutine 2024 [running]:
runtime/debug.Stack(0x4dd06e0, 0xc00798aff0, 0x56a7bf0)
	/Users/liggitt/.gvm/gos/go1.15/src/runtime/debug/stack.go:24 +0x9f
k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).trackCallers(0xc007678620, 0x56a7bf0, 0xb)
	/Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:109 +0x78
k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).Handle(0xc007678620, 0x56a7bf0, 0xb, 0x5ed1300, 0xc00c99e120)
	/Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:173 +0x85
k8s.io/kube-openapi/pkg/handler.(*OpenAPIService).RegisterOpenAPIVersionedService(0xc00af91080, 0x56a7bf0, 0xb, 0x5ecbd60, 0xc007678620, 0x0, 0x0)
	/Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/kube-openapi/pkg/handler/handler.go:221 +0x1cd
k8s.io/apiserver/pkg/server/routes.OpenAPI.Install(0xc000c243f0, 0xc000f8acf0, 0xc007678620, 0x1d, 0xc0077ae2b0)
	/Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/routes/openapi.go:47 +0x2a5
k8s.io/apiserver/pkg/server.(*GenericAPIServer).PrepareRun(0xc00746fc00, 0x56f42de)
	/Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/genericapiserver.go:295 +0x377
k8s.io/kube-aggregator/pkg/apiserver.(*APIAggregator).PrepareRun(0xc00761be80, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go:336 +0x52
k8s.io/kubernetes/test/integration/etcd.StartRealMasterOrDie.func1(0xc000782f00, 0xc00761be80, 0xc0010bc0c0)
	/Users/liggitt/go/src/k8s.io/kubernetes/test/integration/etcd/server.go:135 +0x5a
created by k8s.io/kubernetes/test/integration/etcd.StartRealMasterOrDie
	/Users/liggitt/go/src/k8s.io/kubernetes/test/integration/etcd/server.go:127 +0xa0b
```

probably want to resolve that before backporting

**Comment by apelisse** [comment]
So this doesn't affect the behavior but still panics?

**Comment by liggitt** [comment]
it's not a panic, it's logging the stack trace of the handler that was overwritten

**Comment by pacoxu** [comment]
The stack trace is also found in my apiserver. 

> E0215 14:39:12.859889    6038 pathrecorder.go:107] registered "/openapi/v2" from goroutine 2024 [running]:

**Comment by liggitt** [comment]
@kevindelgado, can you take a look at resolving the stack trace? While it's mostly cosmetic and doesn't seem to cause any problems, that would be good to resolve before 1.21 releases if possible.

**Comment by kevindelgado** [comment]
looking

**Comment by kevindelgado** [comment]
@liggitt what are your thoughts on adding a field to the GenericAPIServer to skip OpenAPI handler installation like [this](https://github.com/kevindelgado/kubernetes/commit/0e0248817b9f396b041295bc78486908e426e1d0)?

This seems like the simplest approach and doesn't feel any hackier than the original solution of [nilling out](https://github.com/kubernetes/kubernetes/issues/89264#issuecomment-601301639) the `GenericConfig.OpenAPIConfig` in `completedConfig.NewWithDelegate`. Maybe we can clean it up by adding a `BuildAndPruneOpenAPISpec()` helper in the routes package or something.

The alternatives I could think of were to 

1. break up GenericAPIServer#PrepareRun or OpenAPI#Install into separate calls and ensure the aggregator doesn't call the path that actually registers the OpenAPI versioned service or 
2. pass in a parameter to PrepareRun that skips the installation 

but these both seem like heavy handed breaking changes to publicly exposed methods. Let me know if you have any other ideas.

**Comment by liggitt** [comment]
a "skip installation field" approach seems ok... made one suggestion about location and flow in https://github.com/kevindelgado/kubernetes/commit/0e0248817b9f396b041295bc78486908e426e1d0#r48352264

**Comment by kevindelgado** [comment]
Backported to 1.18 (#100715), 1.19 (#100713), and 1.20 (#100714)
