### ISSUE TITLE
Support 20H2 on kube 1.20 and main branches

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#99044]
#### What you expected to happen:
Windows 20H2 is the latest SAC. As a community, we decided to support 2 latest SAC releases, so it is better to get 20H2 tests working in 1.20 along with 1909.

/sig windows
cc @marosset @jayunit100 @jsturtevant

**Comment by jsturtevant** [comment]
@jeremyje has started some work on the GCE side: https://testgrid.k8s.io/sig-windows-sac#gce-windows-20h2-master
