### ISSUE TITLE
make build-integration-test-image fails in cluster/images/etcd.

### ISSUE THREAD

**Issue by vinayakankugoyal** [kubernetes/kubernetes#99058]
#### What happened:
Building the etcd integration-test-image fails with the following err:
Failure Log:
```
...
Successfully built 36c5619814a0
Successfully tagged k8s.gcr.io/etcd-amd64:3.4.13-1
cp -r /tmp/tmp.qMWcPYXO68 /tmp/tmp.qMWcPYXO68_integration_test
cp Dockerfile /tmp/tmp.qMWcPYXO68_integration_test/Dockerfile
cd /tmp/tmp.qMWcPYXO68_integration_test && sed -i.bak 's|BASEIMAGE|golang:1.12.17|g' Dockerfile
docker build --pull -t etcd-integration-test /tmp/tmp.qMWcPYXO68_integration_test
Sending build context to Docker daemon  250.2MB
Step 1/10 : FROM golang:1.12.17 as builder
1.12.17: Pulling from library/golang
Digest: sha256:851bb81dad374c1abae45bc89e157fae4d5ebbf0f76f5dce16a81dbac0a26c6b
Status: Image is up to date for golang:1.12.17
 ---> ffcaee6f7d8b
Step 2/10 : RUN apt-get update -y       && apt-get -yy -q install --no-install-recommends --no-install-suggests --fix-missing           bash-static
 ---> Using cache
 ---> 23406a1a44ac
Step 3/10 : RUN cp /bin/bash-static /sh
 ---> Using cache
 ---> 3ec8e9d25343
Step 4/10 : FROM RUNNERIMAGE
invalid reference format: repository name must be lowercase
make: *** [Makefile:185: build-integration-test-image] Error 1
```

#### What you expected to happen:
Expected the image build to pass.
#### How to reproduce it (as minimally and precisely as possible):
1. Sync k/k
2. cd cluster/images/etcd
3. make build-integration-test-image
#### Anything else we need to know?:
Change that probably broke it: https://github.com/kubernetes/kubernetes/pull/91171
#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by wenjiaswe** [comment]
@vinayakankugoyal is working on this in #99059.
