### ISSUE TITLE
API plugin design thread

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#991]
I'm thinking a binary (for example, replication controller) does this to set itself up as a plugin:
1. On startup, registers itself with apiserver.
   a. POST to `/api/<version>/plugins`
   b. Need following information: plugin name, object type, object version, api call destination, more?
   c. We use something similar to Brendan's master election code to store all this in etcd. key is the resource name (e.g., replicationController). We set ttl to something shortish, so the plugin has to dial in to an apiserver periodically to verify that it's still around.
2. The plugin binary runs its own apiserver to server its plugin objects.
   a. Need to think about where it stores them. Do we expose a resource from the main apiserver to allow plugins to store their objects in etcd? IMO we should not give plugins direct access to etcd.
3. The plugin binary also runs whatever go routines necessary to support its activities.
   a. For example, watches, polls, etc...

We'd try to provide enough high level support that an individual plugin can be very concisely written.

Thoughts?

**Comment by bgrant0607** [comment]
@smarterclayton @lavalamp I think this has been superseded by apiserver federation for the most part. Is there any reason to keep this issue open?

I never had time to look at Openstack's APIs in detail. Is there anything worth learning from them in this area?

**Comment by smarterclayton** [comment]
We've mostly followed a similar path - discovery, here hosted natively, in
openstack hosted in keystone, with some level of service doc per service.
Keystone provides authentication integration by each service delegating
tokens, while we're considering multiple options including an auth proxy.
Having native swagger docs also helps in terms of describing generic
resources.  We have the concept of server standard behavior that allows
generic clients to work across multiple backends.  I think this can be
closed.

**Comment by lavalamp** [comment]
I agree we're not going to solve this as listed in the OP.
