### ISSUE TITLE
Pod is restarting with exit code 137 although there is no memory issue

### ISSUE THREAD

**Issue by daganida88** [kubernetes/kubernetes#99100]
#### What happened:
Getting the following errors in kubelet:
kuberuntime_manager.go:920] PodSandboxStatus of sandbox "b6055868eff0f21515055bec2c5662a9d53b6a09eb41d01bef3f83d27d1bb216" for pod "k8sapi-64cf86488d-c7sgx_trax(f2a8a616-24b1-41a8-a4b8-32efd55c9571)" error: rpc error: code = Unknown desc = Error: No such container: b6055868eff0f21515055bec2c5662a9d53b6a09eb41d01bef3f83d27d1bb216

#### What you expected to happen:
Not getting it..
#### How to reproduce it (as minimally and precisely as possible):
Happens sporadically.
#### Anything else we need to know?:
The pod is restarting a lot, it is a flask web application running with gunicorn.
#### Environment:
- Kubernetes version v1.16.15
- AWS EKS
- Linux
- Kernel x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug): AWS CNI 602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon-k8s-cni:v1.7.5
- Others:

**Comment by neolit123** [comment]
> Kubernetes version v1.16.15

this version is no longer in support in upstream k8s. the oldest supported is 1.18

> AWS EKS

please contact the EKS support and get feedback from them.
if this is a problem with 1.18, reopen the issue with more details.

/remove-kind bug
/kind support
/close
