### ISSUE TITLE
[Question] podaffinity / pin pods to specific to availibility zones

### ISSUE THREAD

**Issue by haroonb** [kubernetes/kubernetes#99116]
![image](https://user-images.githubusercontent.com/62880411/108065114-d273b580-705d-11eb-8d31-7658a8311bfa.png)
/sig architecture
Hello everyone,
I'm trying to understand, if it is possible ( and how ) to pin pods of statefulsets to specific availibility zones. In the example above I would like to explicitly configure, that elastic pod 1 runs in availibility zone 1, pod 2 in availibility zone 2 and so forth. I also don't want the pods to run outside of their availibility zones, if one goes down.

I read this [doc](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/) on the matter. If I understand it correctly, I can only specify, that a statefulset shouldn't run it's pods in the same availibility zone, but not, that it always runs the pod in a specific availibility zone.

Thanks to anyone who can educate me in this matter.

**Comment by neolit123** [comment]
for support questions please use:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

or in this case you can try #sig-scheduling on k8s slack.

/close
/remove-sig architecture
/sig scheduling
/kind support
