### ISSUE TITLE
Gluster Error - backup-volfile-servers suspect

### ISSUE THREAD

**Issue by amehub** [kubernetes/kubernetes#99129]
#### What happened:
4 node gluster, replica 3.  Mount gluster volume in pod fails with

E [glusterfsd.c:825:gf_remember_backup_volfile_server] 0-glusterfs: failed to set volfile server: File exists

#### What you expected to happen:
The pod to mount the volume.

#### How to reproduce it (as minimally and precisely as possible):
Create 4 node gluster with Heketi
Create storage class with replica 3
Create PVC using storage class
Create pod that uses storage class

#### Anything else we need to know?:
The message and error is mentioned here 

https://github.com/kubernetes/kubernetes/commit/63cb1d65ca3db178cccdbfce59f4277978e990d4

I am not sure that this code is removing ip from the list assigned to backup-volfile-servers.

`options = append(options, "backup-volfile-servers="+dstrings.Join(addrlist[:], ":"))  
`

addrlist is used.  Should this be addr.List() or backups instead?  

#### Environment:
- Kubernetes version (use `kubectl version`):   v1.19.7
- Cloud provider or hardware configuration:  Bare Metal On Prem with Disaggregated storage.
- OS (e.g: `cat /etc/os-release`):  ubuntu 20.0.4
- Kernel (e.g. `uname -a`): 
- Install tools: Kubespray
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by humblec** [comment]
@amehub are you still facing this ussue even in latest versions of kube clusters?

**Comment by holmesb** [comment]
In our case this was caused by a node without a storage-vlan IP assignment, wasn't k8-related.
