### ISSUE TITLE
Failing test `Deployment deployment should support proportional scaling

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#99123]
#### Which jobs are failing:
aks-engine-azure-windows-master-containerd
#### Which test(s) are failing:
Kubernetes e2e suite.[sig-apps] Deployment deployment should support proportional scaling [Conformance]
#### Since when has it been failing:
02/11
#### Testgrid link:
https://testgrid.k8s.io/sig-release-master-informing#aks-engine-azure-windows-master-containerd
#### Reason for failure:
``` BackOff: Back-off restarting failed container
Feb 16 13:27:51.570: INFO: At 2021-02-16 13:22:58 +0000 UTC - event for webserver-deployment-5859b5dbbb-nknch: {kubelet 7597k8s000} BackOff: Back-off restarting failed container
Feb 16 13:27:51.570: INFO: At 2021-02-16 13:22:58 +0000 UTC - event for webserver-deployment-5859b5dbbb-vp726: {kubelet 7597k8s001} BackOff: Back-off restarting failed container
Feb 16 13:27:51.570: INFO: At 2021-02-16 13:23:03 +0000 UTC - event for webserver-deployment-5859b5dbbb-njdp8: {kubelet 7597k8s001} BackOff: Back-off restarting failed container
Feb 16 13:27:51.570: INFO: At 2021-02-16 13:23:03 +0000 UTC - event for webserver-deployment-5859b5dbbb-zpr24: {kubelet 7597k8s001} BackOff: Back-off restarting failed container```
#### Anything else we need to know:

/sig windows

**Comment by jsturtevant** [comment]
This test was using the httpd image similiar to https://github.com/kubernetes/kubernetes/issues/99124 and should be fixed by #99030.  closing in favor of #99124 

/close
