### ISSUE TITLE
ValidateLabelSelector() allows selectors that error when passed to metav1.LabelSelectorAsSelector

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#99139]
#### What happened:

A PDB object with an invalid selector was allowed to be created. This was the root cause of https://github.com/kubernetes/kubernetes/issues/98702

#### What you expected to happen:

Invalid selectors to be rejected by API validation, and all selectors that pass `ValidateLabelSelector()` to be able to be passed to `LabelSelectorAsSelector` without error.

#### How to reproduce it (as minimally and precisely as possible):

create the following PDB:
```yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
 name: mypdb
spec:
 minAvailable: 2
 selector:
   matchExpressions:
   - key: name
     operator: In
     values: ["test","bad#value"]
```

Observe events emitted by the controller manager because the selector is invalid:

`4s          Warning   NoPods   poddisruptionbudget/mypdb   Failed to get pods: values[1][name]: Invalid value: "bad#value": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')`

#### Anything else we need to know?:

Tightening this validation function in place will be almost impossible to do compatibly.

A second method that validates the delta will need to be created (or changing the signature of this function to indicate if label values should be validated) . Validation methods that want to tighten validation will have to do so using validation ratcheting:
* apply tighter validation on create
* apply tighter validation on update *only* if the existing object also passes the tighter validation

/sig api-machinery 
as primary owner of the package

There are many APIs that use this validation method. Tagging other sigs with affected APIs:

* admission webhook namespace and object selectors
* statefulset, daemonset, deployment, replicaset, job selectors
* pvc selector
* pod affinity selector
* network policy pod and namespace selectors
* pdb pod selector
* rbac AggregationRule selector
* csi NodeTopology selector

/sig auth apps networking storage

**Comment by knight42** [comment]
I have submitted a PR #99490 to finish the PDB part.

**Comment by damemi** [comment]
/sig scheduling
we also hit a similar problem before, and as @liggitt pointed out [tightening the validation in place](https://github.com/kubernetes/kubernetes/pull/92714) is not possible for compatibility reasons, which led to https://github.com/kubernetes/kubernetes/pull/93660 (where we just solved the problem at the point of consumption)

We did briefly discuss ratcheting the change in as mentioned before pivoting from that. Does this mean that path has more suitability now? Getting this in API validation would remove some unnecessary code from the scheduler

**Comment by alculquicondor** [comment]
There are 2 basic requirements for tightening validation:

1. We should allow an invalid field if the old object didn't pass the tighter validation. We can reject during create.
2. We can only do it for things that wouldn't have worked down the line (in kcm, scheduler, etc). In the case of the scheduler, if an invalid Pod ends up being unschedulable, then tightening validation doesn't make things worse (you don't have a runnable pod anyways). In that sense, we probably can't tighten validation for things like preferred affinity.

**Comment by harshitasao** [comment]
Hello @liggitt, with the code freeze approaching, is this still on track for v1.25?
Thanks!

**Comment by liggitt** [comment]
I hope so, trying to get #107531 reviewed

**Comment by SubhasmitaSw** [comment]
Hello @liggitt Just checking in to see if this is still on schedule for K8s 1.26, Bug Triage Shadow here. 
Thanks!

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/107531 is pending updates from the author
