### ISSUE TITLE
cluster autoscaler not working well with Pod Topology constraints

### ISSUE THREAD

**Issue by sikasam** [kubernetes/kubernetes#99148]
We have 2 pods with deployment mode per node with max skew as 1.
When a node is unready/meets scale up condition, a new node is getting created using CA and a pod is created there. similarly, lets say more than 2 nodes are created. now demand is reduced and hpa reduced. so, instead of optimizing all the pods across all the nodes with 2 pods per node, all pods are getting distributed across all the nodes and scale down is never happening. 
Max skew is respected since some nodes have 2 pods and some have 1. But i want that to optimize to 2 pods on all the nodes and scale down the unused nodes. How can i achieve that?

**Comment by neolit123** [comment]
please fill the issue template correctly and reopen this ticket.
https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE/bug-report.md

/close
/kind bug
