### ISSUE TITLE
Do stuff with cloud provider's DNS

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#9914]
In #9682, @pnovotnak wrote:
_I'd like to create resources that are accessible within my private network at my cloud provider (though outside my Kubernetes cluster), but not to the outside internet, that are resolvable via DNS within the cluster. Ironically it seems like endpoint IPs fit the bill (although they change and are not resolvable) whereas service IPs, which are stable and what, are not accessible from outside the cluster._

to which @thockin responded:
_Reaching up into the cloud-provider's DNS is in the cards for sometime after 1.0_

**Comment by cmluciano** [comment]
I think this may be covered by cloudprovider’s interfaces. Is there anything left here?
