### ISSUE TITLE
Better error reporting when using a mismatched Windows pause container

### ISSUE THREAD

**Issue by aravindhp** [kubernetes/kubernetes#99157]
#### What would you like to be added:
Windows pause containers need to be matched with the Windows host OS. In the case of a Windows node using a pause container that does not support the underlying host the error that is thrown is `The container operating system does not match the host operating system`. From the error message it is not clear whether the mismatch with image used in the Pod spec or the pause image. 

#### Why is this needed:
To ease the debugging of such scenarios it will help if the kubelet was able to differentiate a mismatched pause container image from a mismatched Pod container image and throw a more appropriate error message.

**Comment by marosset** [comment]
There should probably be an issue filed at https://github.com/microsoft/windows-containers.

@immuzz ^^

**Comment by jsturtevant** [comment]
Where was the error message displayed? In the describe pod output? 

I think you would see it was the puase image via the error log in kubelet: https://github.com/kubernetes/kubernetes/blob/b2860a360441d15a2f1a7b63e9ca247e5b0ec784/pkg/kubelet/cri/remote/remote_runtime.go#L120-L124

Is it the event that isn't descriptive enough?

**Comment by aravindhp** [comment]
The error was present in the pod describe output. I feel it would be a better UX if we didn't have to look at the kubelet logs. `PodSandboxId is not set for sandbox` did not immediately resolve to incorrect pause image in my head 😄 The hint for me was looking at the kubelet logs and noticing the pod container image had not yet been pulled. But if there is consensus that current error is descriptive enough, I am fine closing the issue.

**Comment by aravindhp** [comment]
Here is full error log as seen with `kubectl describe pod`:
```
  Warning  FailedCreatePodSandBox  6m23s      kubelet, winworker-4k2t5  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "win-webserver-d5977bf65-52g4g": Error response from daemon: hcsshim::CreateComputeSystem bf6b9866d7edfb64b641ad68458ae18bd2c9e8f11971e13fe38225b9bff470e5: The container operating system does not match the host operating system.
(extra info: {"SystemType":"Container","Name":"bf6b9866d7edfb64b641ad68458ae18bd2c9e8f11971e13fe38225b9bff470e5","Owner":"docker","VolumePath":"\\\\?\\Volume{bf4b0605-6af6-46cf-8fa8-37659aa0a532}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\bf6b9866d7edfb64b641ad68458ae18bd2c9e8f11971e13fe38225b9bff470e5","Layers":[{"ID":"23125b6a-3912-51f7-aaf9-5a7112e714e8","Path":"C:\\ProgramData\\docker\\windowsfilter\\2511ff1187b87dc34a4b71c28d4033c9da36f7ad7d50eab08ec94c447cf337ec"},{"ID":"ec2fd8f7-3bb7-50f6-b0ba-8b022d6785bd","Path":"C:\\ProgramData\\docker\\windowsfilter\\e27d54940322339c33e313e2c7efa6f67e026e9987b54371b189e3e9303aa79d"},{"ID":"5c6c8f8d-7ca3-59d8-b24d-761a817e4ff6","Path":"C:\\ProgramData\\docker\\windowsfilter\\1f00ae0427ad4d0e19551dd0fa61385512a74214a702375428d7982c99974d0d"},{"ID":"cb4e1f0e-7cd0-5cc0-835e-81d4da0afa7b","Path":"C:\\ProgramData\\docker\\windowsfilter\\1e5af07aa90dbd8747bd4de04d1a463aa2d2962d4c03a25700fb31a2ae375ade"},{"ID":"78025910-fb47-549c-8de7-bfb74894da5f","Path":"C:\\ProgramData\\docker\\windowsfilter\\325d266d478a3e64093a1577906370e8dd5649437138350f04055b9f76e0a581"}],"ProcessorWeight":2,"HostName":"win-webserver-d5977bf65-52g4g","HvPartition":false})
```

**Comment by marosset** [comment]
I'm surprised this didn't error out during image pulling.

**Comment by jsturtevant** [comment]
I guess there is a bit of a miss match in terminology around pause container and sandbox.  If you know that failing to create the `pod sandbox` == `pause container` then the error message is right in the pod describe, no kubelet logs required.  If you don't know what a pod sandbox or pause image is then it is difficult to find. 

Maybe we could improve the docs https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#pause-image or https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#troubleshooting to explain those concepts better? 

Not sure if there would be interest in change the event message but you could open a PR to change the event wording to start the conversation.

**Comment by aravindhp** [comment]
You are right, @jsturtevant. Thinking more and reading the error message more closely, I don't see a need for changing the event message.

/close
