### ISSUE TITLE
Removing dependency on go-bindata

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#99150]
In golang 1.16, there's a new package `embed` https://golang.org/pkg/embed/ we currently use a package named go-bindata https://cs.k8s.io/?q=go-bindata&i=nope&files=&repos=kubernetes/kubernetes that the embed package can effectively replace. So the ask here is to figure out where all we are using go-bindata and switch all these places over to the new API.

Also to be noted is that we've had trouble with go-bindata in the past as it was not supported and we had to keep changing references, example in https://github.com/kubernetes/kubernetes/pull/96300. So this is a good thing if we can switch to what's available in golang itself

/area code-organization
/sig architecture

NOTE: https://github.com/kubernetes/kubernetes/pull/98572 will have to land first before we can use 1.16 in the master/main branch.

**Comment by wzshiming** [comment]
/assign
I think both the test and the document need to be modified accordingly, I am happy to work for this.

**Comment by wzshiming** [comment]
Is it possible to create a new repositories for translations. the current translation is under kubernetes/kubernetes, if embed is used, kubectl needs to quote the translation
