### ISSUE TITLE
sig-windows - Unable to fetch container log stats: failed to get fsstats

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes/kubernetes#99173]
#### What happened:

Since 1.21+ the logs have the following error:

```
kubelet.err.log:55217:E0217 22:31:38.504066    5040 cri_stats_provider.go:583] Unable to fetch container log stats: 
failed to get fsstats for  "\\var\\log\\pods\\default_iis-1809-668c5b9c87-44vpx_195e99c4-a5d0-4908-9835-9b89a9b3e453\\iis\\0.log": 
failed to get FsInfo due to error The directory name is invalid.                                                           
```

#### What you expected to happen:
no error for pods

#### How to reproduce it (as minimally and precisely as possible):
Deploy iis image and check the kubelet logs:

```
k apply -f https://gist.githubusercontent.com/jsturtevant/5f49c3bd9218666af877927a674b7645/raw/fb042ff14b689c308c9404422e08cf85c56b6ff1/deployment.yaml
```

#### Anything else we need to know?:

looks like it is erroring out here:

https://github.com/kubernetes/kubernetes/blob/b2860a360441d15a2f1a7b63e9ca247e5b0ec784/pkg/kubelet/stats/host_stats_provider.go#L133-L135

looks like it might be related to changes in https://github.com/kubernetes/kubernetes/pull/97042

#### Environment:
- Kubernetes version (use `kubectl version`): 1.21+
- Cloud provider or hardware configuration: aks-engine
- OS (e.g: `cat /etc/os-release`): windows 2019
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others: containerd 1.4.3 or Docker EE 19.03.11

/sig windows
/assign

**Comment by pacoxu** [comment]
The key error message would be `The directory name is invalid`. The pod log dir is not correct for windows?

**Comment by jsturtevant** [comment]
Might be thought the path names did not change between 1.20 and 1.21. It's possible this didn't work prior but didn't log the error

1.20:
```
Path
----
C:\var\log\pods\default_iis-1809-668c5b9c87-p9wk8_30bd6f3e-0aed-4d51-aa95-ecab08da22b8  
```

1.21:
```
Path
----
C:\var\log\pods\default_iis-1809-668c5b9c87-9bj6m_196192c1-2281-4337-8ce8-b3921a6cd6a3
```

**Comment by jsturtevant** [comment]
The host_stats_provider is using `metrics_du.go` to get stats on individual files:

https://github.com/kubernetes/kubernetes/blob/b2860a360441d15a2f1a7b63e9ca247e5b0ec784/pkg/kubelet/stats/host_stats_provider.go#L124-L133

`metrics_du.go` calls out to fs.Info():

https://github.com/kubernetes/kubernetes/blob/f1829a7744a1c4d2211188e67a1d2d4231edd103/pkg/volume/metrics_du.go#L90

which uses [GetDiskFreeSpaceExW](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getdiskfreespaceexw) : 

https://github.com/kubernetes/kubernetes/blob/f1829a7744a1c4d2211188e67a1d2d4231edd103/pkg/volume/util/fs/fs_windows.go#L44

Ran some tests and the syscall `GetDiskFreeSpaceExW` doesn't work on individual files returning the error: `The directory name is invalid`

Sample gist (must run on windows): https://gist.github.com/jsturtevant/1d86d47fbda4b2cb89e7d2d65360c71a

**Comment by jsturtevant** [comment]
beyond the error messages for every pod on a windows node the result is missing pod log stats via cri.

Linux pod stats: http://localhost:8001/api/v1/nodes/k8s-linuxpool1-27331026-vmss000000/proxy/stats/summary

```
{
   "podRef": {
    "name": "busybox",
    "namespace": "default",
    "uid": "44080b5d-4792-4eae-a6e7-c5a18e33519d"
   },
   "startTime": "2021-02-18T22:50:57Z",
   "containers": [
    {
     "name": "busybox",
     "startTime": "2021-02-18T22:51:01Z",
     "cpu": {
      "time": "2021-02-18T22:51:01Z",
      "usageNanoCores": 0,
      "usageCoreNanoSeconds": 17140805
     },
     "memory": {
      "time": "2021-02-18T22:51:01Z",
      "usageBytes": 667648,
      "workingSetBytes": 667648,
      "rssBytes": 102400,
      "pageFaults": 297,
      "majorPageFaults": 0
     },
     "rootfs": {
      "time": "2021-02-18T22:51:06Z",
      "availableBytes": 17177198592,
      "capacityBytes": 31036686336,
      "usedBytes": 36864,
      "inodesFree": 3643731,
      "inodes": 3870720,
      "inodesUsed": 12
     },
     "logs": {
      "time": "2021-02-18T22:51:12Z",
      "availableBytes": 17177198592,
      "capacityBytes": 31036686336,
      "usedBytes": 0,
      "inodesFree": 3643731,
      "inodes": 3870720,
      "inodesUsed": 1
     }
    }
   ],
```

Windows pod stats (note missing logs field): http://localhost:8001/api/v1/nodes/2733k8s01000000/proxy/stats/summary

```
{
   "podRef": {
    "name": "iis-1809-668c5b9c87-s249v",
    "namespace": "default",
    "uid": "50690818-0a8d-439d-a75a-81899c85c2fd"
   },
   "startTime": "2021-02-18T20:11:56Z",
   "containers": [
    {
     "name": "iis",
     "startTime": "2021-02-18T20:11:57Z",
     "cpu": {
      "time": "2021-02-18T22:51:58Z",
      "usageNanoCores": 0,
      "usageCoreNanoSeconds": 17812500000
     },
     "memory": {
      "time": "2021-02-18T22:51:58Z",
      "workingSetBytes": 58486784
     },
     "rootfs": {
      "time": "2021-02-18T22:51:56Z",
      "availableBytes": 9418027008,
      "capacityBytes": 31687962624,
      "usedBytes": 104857600,
      "inodesUsed": 0
     }
    }
   ],
```
