### ISSUE TITLE
Support for checkpoint / restore on Windows as well

### ISSUE THREAD

**Issue by tfenster** [kubernetes/kubernetes#99170]
#### What would you like to be added:
With support for checkpoint / restore seemingly on the way for K8s (kubernetes/kubernetes#97689 and kubernetes/kubernetes#3949 (comment)), I am wondering whether there is anything planned for Windows as well? As far as I can see, the work is restricted to Linux until now?

#### Why is this needed:
As k8s is now supporting Windows as well, it would make sense to support checkpoint/restore there as well

This is a followup of https://github.com/microsoft/Windows-Containers/issues/88 where I was told to open the issue here

**Comment by perithompson** [comment]
Thanks for raising this!

**Comment by marosset** [comment]
@dcantah @kevpar - FYI
