### ISSUE TITLE
watch.RetryWatcher: avoid printing misleading logs

### ISSUE THREAD

**Issue by ash2k** [kubernetes/kubernetes#99177]
#### What would you like to be added:

I'm using `watch.RetryWatcher` and occasionally I need to restart the watches. When that happens, I get a lot of log lines like below:

```
Watch failed: Get \"https://10.30.160.1:443/api/v1/serviceaccounts?allowWatchBookmarks=true&resourceVersion=50759146&watch=true\": context canceled
Watch failed: Get \"https://10.30.160.1:443/apis/autoscaling/v1/horizontalpodautoscalers?allowWatchBookmarks=true&resourceVersion=50759156&watch=true\": context canceled
Watch failed: Get \"https://10.30.160.1:443/apis/storage.k8s.io/v1/volumeattachments?allowWatchBookmarks=true&resourceVersion=50759158&watch=true\": context canceled
Watch failed: Get \"https://10.30.160.1:443/apis/admissionregistration.k8s.io/v1/validatingwebhookconfigurations?allowWatchBookmarks=true&resourceVersion=50759171&watch=true\": context canceled
Watch failed: Get \"https://10.30.160.1:443/apis/networking.gke.io/v1beta1/frontendconfigs?allowWatchBookmarks=true&resourceVersion=50759146&watch=true\": context canceled
Watch failed: Get \"https://10.30.160.1:443/api/v1/secrets?allowWatchBookmarks=true&resourceVersion=50759146&watch=true\": context canceled
Watch failed: Get \"https://10.30.160.1:443/api/v1/persistentvolumeclaims?allowWatchBookmarks=true&resourceVersion=50759146&watch=true\": context canceled
Watch failed: Get \"https://10.30.160.1:443/api/v1/services?allowWatchBookmarks=true&resourceVersion=50759146&watch=true\": context canceled
Watch failed: Get \"https://10.30.160.1:443/apis/apps/v1/statefulsets?allowWatchBookmarks=true&resourceVersion=50759154&watch=true\": context canceled
Watch failed: Get \"https://10.30.160.1:443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?allowWatchBookmarks=true&resourceVersion=50759156&watch=true\": context canceled
Watch failed: Get \"https://10.30.160.1:443/apis/storage.k8s.io/v1beta1/csidrivers?allowWatchBookmarks=true&resourceVersion=50759160&watch=true\": context canceled
Watch failed: Get \"https://10.30.160.1:443/apis/apps/v1/controllerrevisions?allowWatchBookmarks=true&resourceVersion=50759162&watch=true\": context canceled
Watch failed: Get \"https://10.30.160.1:443/apis/apiextensions.k8s.io/v1/customresourcedefinitions?allowWatchBookmarks=true&resourceVersion=50759164&watch=true\": context canceled
Watch failed: Get \"https://10.30.160.1:443/apis/node.k8s.io/v1beta1/runtimeclasses?allowWatchBookmarks=true&resourceVersion=50759168&watch=true\": context canceled
Watch failed: Get \"https://10.30.160.1:443/apis/migration.k8s.io/v1alpha1/storageversionmigrations?allowWatchBookmarks=true&resourceVersion=50759173&watch=true\": context canceled
```

I think there is no need to print this. Would be great to change [the behavior](https://github.com/kubernetes/kubernetes/blob/442a69c3bdf6fe8e525b05887e57d89db1e2f3a5/staging/src/k8s.io/client-go/tools/watch/retrywatcher.go#L123-L132) to recognize that the watcher is stopped and that the error is `context canceled` and skip printing the message.

#### Why is this needed:

To reduce the log volume and to not distract the cluster/application operator with misleading messages (it's working as intended but there is an `error`-level log line).

/sig api-machinery

**Comment by pacoxu** [comment]
```
klog.V(5).Infof(msg, err)
```
It is not a high level log IMO.

**Comment by ash2k** [comment]
@pacoxu It's not a timeout and not a EOF, it's logging at `error` level. Full log line looks like this:

```
{"level":"error","time":"2021-02-17T12:37:22.978Z","msg":"Watch failed: Get \"https://10.9.96.1:443/apis/networking.istio.io/v1alpha3/destinationrules?allowWatchBookmarks=true&resourceVersion=96923945&watch=true\": context canceled\n"}
```

**Comment by pacoxu** [comment]
@ash2k 

So what we should do is log an info level log when the request returns `request canceled`.

I will update the PR.

**Comment by caesarxuchao** [comment]
@ash2k can you confirm how to reproduce the issue?

You said that this happened when you "restarted the watches". Did you call [Stop()](https://github.com/kubernetes/kubernetes/blob/031f2afbba6a3bade6e729e1709a0e792a1e6637/staging/src/k8s.io/client-go/tools/watch/retrywatcher.go#L283) and then recreate a RetryWatcher?

**Comment by ash2k** [comment]
@caesarxuchao Yes, when `Stop()` is called it aborts the http call [within the client](https://github.com/kubernetes/kubernetes/blob/bc66d3d137d3600b117be390ccb253a9dbcde25e/staging/src/k8s.io/client-go/rest/request.go#L674-L739) and it returns an error to the `RetryWatcher`. Re-creating it later is irrelevant for reproduction, it's just what my program does.

**Comment by pacoxu** [comment]
@ash2k Sorry for the delay. I opened #102356 for this issue.
