### ISSUE TITLE
Make kubelet cadvisor optional to read every open FDs of every container.

### ISSUE THREAD

**Issue by xinfengliu** [kubernetes/kubernetes#99183]
#### What would you like to be added:
When running `elasticsearch` workload,  it's possible that `elasticsearch` has huge number of open files. This causes `kubelet` CPU usage extremely high and impacts the application responsiveness. 

CPU profiling data shows the hot code is here: 
https://github.com/kubernetes/kubernetes/blob/release-1.18/vendor/github.com/google/cadvisor/container/libcontainer/handler.go#L163-L182
```go
	for _, pid := range pids {
		dirPath := path.Join(rootFs, "/proc", pid, "fd")
		fds, err := ioutil.ReadDir(dirPath)
		if err != nil {
			klog.V(4).Infof("error while listing directory %q to measure fd count: %v", dirPath, err)
			continue
		}
		fdCount += uint64(len(fds))
		for _, fd := range fds {
			fdPath := path.Join(dirPath, fd.Name())
			linkName, err := os.Readlink(fdPath)
			if err != nil {
				klog.V(4).Infof("error while reading %q link: %v", fdPath, err)
				continue
			}
			if strings.HasPrefix(linkName, "socket") {
				socketCount++
			}
		}
	}
``` 
Is counting files and sockets absolutely necessary for k8s to be functional? If not,  is it possible to add a kubelet flag to disable above code path? 

#### Why is this needed:
Reduce the resource usage of kubelet to make the application run well.

**Comment by pacoxu** [comment]
According to code https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/server/server.go#L346-L361 and https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cadvisor/cadvisor_linux.go#L91-L103, there is no flag for it.

And DisableAcceleratorUsageMetrics feature gate is a good example: Disable accelerator metrics collected by the kubelet.
```
	// Only add the Accelerator metrics if the feature is inactive
	// Note: Accelerator metrics will be removed in the future, hence the feature gate.
	if !utilfeature.DefaultFeatureGate.Enabled(features.DisableAcceleratorUsageMetrics) {
		includedMetrics.Add(cadvisormetrics.MetricKind(cadvisormetrics.AcceleratorUsageMetrics))
	}
```

Not sure, can we add a similar feature gate for ProcessMetrics ?

Another way to solve this it to add a configurable list for `include metrics` in kubelet configuration. I'm not sure which is better?

**Comment by pacoxu** [comment]
/sig node 
IMO as it is related to kubelet code and cadvisor.

**Comment by xinfengliu** [comment]
@pacoxu Thank you very much for your help. 

>Not sure, can we add a similar feature gate for ProcessMetrics ?
Another way to solve this it to add a configurable list for include metrics in kubelet configuration. I'm not sure which is better?

I don't have strong opinion on this. It seems that using `include metrics` in kubelet configuration is more flexible and using the feature gate is clearer to users.

**Comment by pacoxu** [comment]
/remove-lifecycle rotten
/assign
/triage accepted
I will raise it in sig-node meeting or send a KEP for it in the next release cycle if I have enough time.

**Comment by pacoxu** [comment]
/cc @bobbypage  @dashpole 
Do you agree that we can add a simple feature gate to disable 'cadvisormetrics.ProcessMetrics'?
Or is there another way to configure cadvisor metrics list ?

https://github.com/kubernetes/kubernetes/blob/985ac8ae5089d3312640b0fca795469fb8025f2a/pkg/kubelet/server/server.go#L357-L372

**Comment by pacoxu** [comment]
Or like `--volume-stats-agg-period` flag. It can determine the frequency of `du ` a pod.

We can add a new flag in kubelet config file like `processCheckInterval` to make it configurable.

**Comment by bobbypage** [comment]
New flag or kubelet config makes sense if we want to provide ability to disable collecting these stats. What is the impact of not collecting these stats by the way? Is it only used for the /metrics/cadvisor endpoint or are these fd stats also used internally by kubelet (e.g. for summary API?)

**Comment by robszy** [comment]
What about https://github.com/kubernetes/enhancements/pull/1921 because it seams next incarnation of options to disable or enable selected metrics where today configurable options is just none.

**Comment by xinfengliu** [comment]
/remove-lifecycle rotten

Hi maintainers, 
Is this issue addressed in other places or still under discussion?

**Comment by pacoxu** [comment]
@xinfengliu  I will send a PR for it. But it still needs to be reviewed and approved by sig-node approvers. I will try to push this forward.

**Comment by pacoxu** [comment]
@xinfengliu  I will send a PR for it. But it still needs to be reviewed and approved by sig-node approvers. I will try to push this forward.

**Comment by xinfengliu** [comment]
@pacoxu Thank you so much!

**Comment by pacoxu** [comment]
> What is the impact of not collecting these stats by the way? Are these metrics only used for the /metrics/cadvisor endpoint or are these fd stats also used internally by kubelet (e.g. for summary API?)

@bobbypage 
Process metrics include `container_processes`, `container_file_descriptors`, `container_sockets`, `container_threads_max`, `container_threads`, `container_ulimits_soft`.

If I search correctly, they are not used in other apis.
```
	c.containerMetrics = append(c.containerMetrics, []containerMetric{
			{
				name:      "container_processes",
				help:      "Number of processes running inside the container.",
				valueType: prometheus.GaugeValue,
				getValues: func(s *info.ContainerStats) metricValues {
					return metricValues{{value: float64(s.Processes.ProcessCount), timestamp: s.Timestamp}}
				},
			},
			{
				name:      "container_file_descriptors",
				help:      "Number of open file descriptors for the container.",
				valueType: prometheus.GaugeValue,
				getValues: func(s *info.ContainerStats) metricValues {
					return metricValues{{value: float64(s.Processes.FdCount), timestamp: s.Timestamp}}
				},
			},
			{
				name:      "container_sockets",
				help:      "Number of open sockets for the container.",
				valueType: prometheus.GaugeValue,
				getValues: func(s *info.ContainerStats) metricValues {
					return metricValues{{value: float64(s.Processes.SocketCount), timestamp: s.Timestamp}}
				},
			},
			{
				name:      "container_threads_max",
				help:      "Maximum number of threads allowed inside the container, infinity if value is zero",
				valueType: prometheus.GaugeValue,
				getValues: func(s *info.ContainerStats) metricValues {
					return metricValues{
						{
							value:     float64(s.Processes.ThreadsMax),
							timestamp: s.Timestamp,
						},
					}
				},
			},
			{
				name:      "container_threads",
				help:      "Number of threads running inside the container",
				valueType: prometheus.GaugeValue,
				getValues: func(s *info.ContainerStats) metricValues {
					return metricValues{
						{
							value:     float64(s.Processes.ThreadsCurrent),
							timestamp: s.Timestamp,
						},
					}
				},
			},
			{
				name:        "container_ulimits_soft",
				help:        "Soft ulimit values for the container root process. Unlimited if -1, except priority and nice",
				valueType:   prometheus.GaugeValue,
				extraLabels: []string{"ulimit"},
				getValues: func(s *info.ContainerStats) metricValues {
					values := make(metricValues, 0, len(s.Processes.Ulimits))
					for _, ulimit := range s.Processes.Ulimits {
						values = append(values, metricValue{
							value:     float64(ulimit.SoftLimit),
							labels:    []string{ulimit.Name},
							timestamp: s.Timestamp,
						})
					}
					return values
				},
			},
```
