### ISSUE TITLE
Kubernetes doesn't honor pod anti-affinity across different statefulset deployments

### ISSUE THREAD

**Issue by rahultoraskarr** [kubernetes/kubernetes#99198]
I have 6 statefulsets with 1 replica each. so 6 pods in total. Each having label 'pod-type: xyz' 
I used below pod anti-affinity rule on each statefulset and I deployed this on AKS cluster with 6 nodes. 

Even with this rule multiple pods were getting scheduled on few nodes.

affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: pod-type
                operator: In
                values:
                - xyz
            topologyKey: "kubernetes.io/hostname"

#### What you expected to happen:

Only one pod with label 'pod-type: xyz'  to get scheduled on each VM.

#### How to reproduce it (as minimally and precisely as possible):

Deploy multiple statefulsets with pod anti-affinity rule as per above.

#### Environment:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.13", GitCommit:"39a145ca3413079bcb9c80846488786fed5fe1cb", GitTreeState:"clean", BuildDate:"2020-07-15T16:18:19Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"5de7fd1f9555368a86eb0f8f664dc58055c17269", GitTreeState:"clean", BuildDate:"2021-01-18T09:31:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: Azure AKS 
- OS (e.g: `cat /etc/os-release`): Ubuntu
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
will let sig-scheduling to check, but note that:

> Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14",

this server version is in support.

> Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.13",

this is an supported skew between client and server:
https://kubernetes.io/docs/setup/release/version-skew-policy/#kubectl

**Comment by rahultoraskarr** [comment]
Issue was due to deployments across namespaces. It got resolved when list of namespaces mentioned in the affinity rule.
