### ISSUE TITLE
Expose  HighestUserDefinablePriority via scheduler config

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#99203]
#### What would you like to be added:
I'd like  [`HighestUserDefinablePriority`](HighestUserDefinablePriority) to be exposed via scheduler config so that a cluster admin can set that value. Without it, the range 1B-2B is not being useful for people.
#### Why is this needed:
We recently noticed that once a priority class with 1B max value we allow for `HighestUserDefinablePriority`  is created, the values between 1B-2B range which are reserved for critical components cannot be used. Further, we cannot update existing priority class's value, we had to delete and recreate it. So wondering if it is ok to expose the `HighestUserDefinablePriority` to be exposed via config but ensure that it will always less than `system-*` components

**Comment by adtac** [comment]
>Without it, the range 1B-2B is not being useful for people.

Does this mean there are systems that exhaust the first billion priority levels? :O

Also what should happen when the admin configures this to such a high value that there aren't enough priority classes for system pods?

**Comment by ravisantoshgudimetla** [comment]
> Does this mean there are systems that exhaust the first billion priority levels? :O

Nope, we used  highest workload priority for a pod. After few days, we realized that there are other pods that need higher priority than this one but we don't have any other way to allocate a value greater than 1B, except for deleting the old priority class and creating new one. We were wondering if this was made configurable, it would help us.

>Also what should happen when the admin configures this to such a high value that there aren't enough priority classes for system pods?

The validation code should reject setting such high values, `system-node-critical` and `system-cluster-critical` should still be highest ones.

**Comment by ravisantoshgudimetla** [comment]
cc @wking @damemi @soltysh

**Comment by wking** [comment]
> After few days, we realized that there are other pods that need higher priority than this one but we don't have any other way to allocate a value greater than 1B...

In hindsight, creating a PriorityClass consuming the highest user-definable level was clearly a mistake.  But mistakes happen ;).  Making the cap configurable would give you one way to recover after making that mistake.  #99205 would provide an alternative path to recovering.

**Comment by damemi** [comment]
> > After few days, we realized that there are other pods that need higher priority than this one but we don't have any other way to allocate a value greater than 1B...
> 
> In hindsight, creating a PriorityClass consuming the highest user-definable level was clearly a mistake. But mistakes happen ;). Making the cap configurable would give you one way to recover after making that mistake. #99205 would provide an alternative path to recovering.

Wouldn't a configurable cap enable users to make the same mistake, with potentially even higher risk since it now affects system components? I think that's the same point as @adtac made above:
> Also what should happen when the admin configures this to such a high value that there aren't enough priority classes for system pods?

**Comment by wking** [comment]
> ...with potentially even higher risk since it now affects system components?...

System levels [start at 2B][1], so there's plenty of space for folks who accidentally pick 1B for a user level to slowly ease that cap up and recover space for the newly-discovered priority class.  And there would still be room for the next generation of dev on the cluster to make the same mistake, need to grow the cap again, and still have room.  I'm absolutely opposed to allowing the configurable cap to rise up to `SystemCriticalPriority` and into the system space.  So "configurable, but still capped to protect the system classes".

[1]: https://github.com/kubernetes/kubernetes/blob/cea1d4e20b4a7886d8ff65f34c6d4f95efcb4742/pkg/apis/scheduling/types.go#L32

**Comment by adtac** [comment]
I'm in favour of making priority class levels configurable instead of allowing admins to configure the maximum user level. Allowing users to raise the limit to 2 billion will likely result in the same problem later down the line, but this time with the highest user class being 2B instead of 1B. That is just patching the symptom IMO.

famous last words, but ~~640k~~ 1 billion ought to be enough for anybody :)

**Comment by adtac** [comment]
Also I'm curious: system *critical* levels start at 2B. Are there any system pods that aren't critical but neither are user pods?

**Comment by ingvagabund** [comment]
Allowing to update priority class priority is more preferable

**Comment by ahg-g** [comment]
I don't see too much value in making this configurable. I think we need to update our docs to suggest using a priority value in the middle range to start with so there is room to go to either direction.

**Comment by ravisantoshgudimetla** [comment]
I want to use [Terry Lambert's famous quote here](https://www.google.com/search?client=firefox-b-1-d&ei=30EwYKr0BtDN_Aa3_5SACw&q=terry+lambert%27s+Mr.foot+mr.bullet&oq=terry+lambert%27s+Mr.foot+mr.bullet&gs_lcp=Cgdnd3Mtd2l6EANQyExYyExg6U5oAXAAeACAAesBiAHcApIBBTAuMS4xmAEAoAEBqgEHZ3dzLXdpesABAQ&sclient=gws-wiz&ved=0ahUKEwjq3_rIhffuAhXQJt8KHbc_BbAQ4dUDCAw&uact=5). However I see both the arguments. I am fine as long as we choose to go with this approach or https://github.com/kubernetes/kubernetes/issues/99205

**Comment by alculquicondor** [comment]
-1 on this proposal as well.
I don't think there is any API validation that is configurable today. Plus, the component config for kube-apiserver would still need to be validated with a maximum value.
So, configuring the validation doesn't really prevent you from making the same mistake at a different level.
 I doubt that api-reviewers would subscribe to the idea.
