### ISSUE TITLE
Not able to mount folders inside a container

### ISSUE THREAD

**Issue by shubhtrivedi** [kubernetes/kubernetes#99200]
Hi.. I am deploying a bpf container for which I need to mount some folders onto the container which I am trying to do through this file.

<pre>
apiVersion: v1
kind: Pod
metadata:
  name: test3
  namespace: test
spec:
#  shareProcessNamespace: true
  containers:
  - args:
    - sleep
    - "10000000"
    image: centos:centos6
    name: test
  - args:
    - sleep
    - "10000000"
    image: quay.io/iovisor/bpftrace
    name: test1
    securityContext:
      capabilities:
        add:
        - SYS_RESOURCE
        drop:
        - ALL
      allowPrivilegedContainer: true
      allowHostDirVolumePlugin: true
      allowHostIPC: true
      allowHostNetwork: true
      allowHostPID: true
      allowHostPorts: true
#      allowPrivilegeEscalation: true
#    stdin: true
#    tty: true
    volumeMounts:
    - name: sys
      mountPath: /sys/kernel
      readOnly: false
    - name: headers
      mountPath: /usr/src
      readOnly: true
    - name: modules
      mountPath: /lib/modules
      readOnly: true
  volumes:
  - name: sys
    hostPath:
    path: /sys/kernel
  - name: headers
    hostPath:
    path: /usr/src
  - name: modules
    hostPath:
    path: /lib/modules/
  serviceAccountName: bpf

</pre>

The container is created successfully but the folders are not mounted.
<pre>
root@test3:/# cd /usr/src
root@test3:/usr/src# ls
root@test3:/usr/src#

</pre>
 can someone please point out where I am going wrong?

**Comment by neolit123** [comment]
please try the support forums:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
/close
