### ISSUE TITLE
Multiple schedule policies for different pods.

### ISSUE THREAD

**Issue by HaiyangDING** [kubernetes/kubernetes#9920]
In production, we need multiple schedule policies to meet the requirements of different pods. For instance, some pods may prefer a schedule policy in which ServiceSpreading is considered to be import, while some other pods just want themselves to be deployed on the nodes with more free resources regardless of the ServiceSpreading. To meet these "conflict" requirement, different schedule policies should be allowed when kube-scheduler is up.

How should we do this? 

An initial discussion at https://groups.google.com/forum/#!topic/google-containers/wyn8dNXq6xI.

**Comment by davidopp** [comment]
Two ideas were suggested in that thread:
1) Run multiple schedulers, each with one policy configuration and each responsible for a disjoint set of pods
2) Run a single scheduler, which figures out which policies to apply for each pod it is scheduling

We haven't tried either of these, but you are definitely welcome to try it out and let us know if you have problems.

**Comment by HaiyangDING** [comment]
OK. I am going to try them and I will let you know if there is any progress/problem.

**Comment by mikeln** [comment]
I have a similar issue.  My first thought was multiple schedulers, then add to the podspec/rcspec to allow the pod to specify the scheduler to use for it.  Resort to the default (with some warning message) if the desired scheduler isn't available.   In my case, it may be viable to just allow multiple default scheduler instances, each with their own configuration file and name (label).

**Comment by timothysc** [comment]
Please see https://github.com/GoogleCloudPlatform/kubernetes/issues/367 , but I'm all for multiple schedulers too ;-)

**Comment by HaiyangDING** [comment]
After a rough consideration, I would prefer to go for a single scheduler with multiple policies each specific pods. I am working on the codes and hope to show something sooner:)
