### ISSUE TITLE
Kube-proxy's conntrack-max was set lower than desired with static CPU Policy

### ISSUE THREAD

**Issue by xh4n3** [kubernetes/kubernetes#99225]
#### What would you like to be added:
A new flag indicating how kube-proxy gets the number of CPUs, either from goruntime or `/proc/cpuinfo`.

#### Why is this needed:
In kube-proxy, we can use `--conntrack-max-per-core` to set node's `conntrack-max`, the resulting `conntrack-max` is `int(*config.MaxPerCore) * goruntime.NumCPU()`.

https://github.com/kubernetes/kubernetes/blob/f49385d05a38d0dec06be6a324fb4fe3a720f4db/cmd/kube-proxy/app/server.go#L787

##### Case 1
We have nodes where pods with none CPU policy and static CPU policy are running together. Pods like kube-proxy are running in none CPU policy by default, and they only gets CPUs left by static CPU policy pods. If static CPU policy pods take away most CPUs cores, kube-proxy can only get one or two cores, then `conntrack-max` will be set to a very small values. In this case, a lot packet failure can occur.

##### Case 2
When we set kube-proxy to work in static CPU policy, kube-proxy only gets the number of CPUs selected by the CPU policy, not the number of total CPUs on the node. This may *surprise* users who are only trying to limit kube-proxy's CPU usages, but resulting in some conntrack fulls faults.

Please let me know if this enhancement is reasonable, so I can send a pr later. Thanks!

**Comment by JornShen** [comment]
Is it refer to deploy order of kube-proxy? If kube-proxy deploy first in node, will it get just one or two core? @xh4n3

**Comment by xh4n3** [comment]
> Is it refer to deploy order of kube-proxy? If kube-proxy deploy first in node, will it get just one or two core? @xh4n3

By one or two I mean kube-proxy gets a small number of CPU cores, because most of CPU cores are allocated to static policy pods, sorry for the misunderstanding.
The number of conntrack-max depends on the CPU cores when kube-proxy started, even kube-proxy was first deployed, it can get restarted or redeployed by some reasons. Then the conntrack-max will change.

**Comment by JornShen** [comment]
yeah, when kube-proxy deploy firstly, Maybe it can see the whole cpu nums from shared cpu(/var/lib/kubelet/cpu_manage_state when kubelet start with static cpu policy). But I think it is a bug for kube-proxy. The cpu info can also get from node resource info. So will it be suitable to add a flag to set cpu num?

**Comment by xh4n3** [comment]
Maybe, or we can add a flag for user to choose where kube-proxy should get CPU informations from. There maybe some multi-tenant scenarios where kube-proxy are deployed for per tenant so they would like to limit conntrack-max by CPU cores allocated to each tenant.

**Comment by thockin** [comment]
I think the simple fix is to replace `goruntime.NumCPU()` with something that counts /proc/cpuinfo.  I don't know of anyone running multiple proxies, and I don't think it would work well.  The intention was "all the CPUs on the node".

PRs welcome!
