### ISSUE TITLE
Rapid release of 1.20.3, 1.20.4

### ISSUE THREAD

**Issue by gohmc** [kubernetes/kubernetes#99224]
#### Anything else we need to know:

For the mentioned releases above; their changelog have no content, number (1924 ) of committed to master are exact same, and neither release appear in Kubernetes repo.

This looks like the overnight built, is this intentional?

Thanks.

/sig release

**Comment by gohmc** [comment]
just to add that kubeadm installed using Kubernetes repo will not able to apply v1.20.4 as the version skew above 2.

**Comment by pacoxu** [comment]
> just to add that kubeadm installed using Kubernetes repo will not able to apply v1.20.4 as the version skew above 2.

Would you share the error message? 
I can install cluster with kubeadm in my env.

**Comment by BenTheElder** [comment]
@kubernetes/release-managers
1.20.3 should have one less commit (a revert).

**Comment by gohmc** [comment]
@pacoxu When this issue was first reported, neither 1.20.3 nor 1.20.4 is in the repo. I reckon someone is working on it now as 1.20.4 starts to appear, but you can see 1.20.3 was "skipped". For me this is quite unusual to Kubernetes release.

![image](https://user-images.githubusercontent.com/46994372/108483145-54b9df00-72d5-11eb-887f-2db0a08ce25a.png)

Anyway, I just performed an upgrade with 1.20.4 with calico 3.17.3 and they works as expected.

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

$ calicoctl version
Client Version:    v3.17.3
Git commit:        5eb50600
Cluster Version:   v3.17.3
Cluster Type:      k8s,bgp,kubeadm,kdd
```

I think the issue has been taken care of; I am happy to close it if no one else need to track it.

**Comment by saschagrunert** [comment]
Hey @gohmc, thank you for raising the question!

Indeed we had an issue with v1.20.3 which was the reason we stopped the process and did not publish any deb/rpm packages. We announced it on the Kubernetes developer/contributor discussion mailing list, too:
https://groups.google.com/g/kubernetes-dev/c/oUpY9vWgzJo/m/zPNyUO6dAQAJ

I think since v1.20.4 is now released we should be fine on the upgrade paths. So I propose to close this one, feel free to reopen if there is anything else not covered. :blush: 

/close
