### ISSUE TITLE
Kubelet panics when trying to set structured logging

### ISSUE THREAD

**Issue by rphillips** [kubernetes/kubernetes#99239]
#### What happened:
When I attempt to start the kubelet with the structured logging flag (--logging-format=json) the kubelet panics with a `panic: failed to lookup unsupported log flag` error.

#### What you expected to happen:
I expect the Kubelet to start with structured logging enabled.

#### How to reproduce it (as minimally and precisely as possible):
```
KUBELET_FLAGS=--logging-format=json hack/local-up-cluster.sh
```

Adding the following yaml within hack/local-up-cluster.sh for the kubelet config fails in the same manner:
```
logging:
  format: json
```

#### Environment:
- Kubernetes version (use `kubectl version`): master 25aa6cf0c58067656dd6e4c1e2c28efb259ab08c
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by serathius** [comment]
Looks like flag validation was broken unintentionally with https://github.com/kubernetes/kubernetes/pull/98524
Revisiting this code make me think that we should add e2e tests as Beta requirements.

**Comment by serathius** [comment]
Proposed to add e2e periodics https://github.com/kubernetes/enhancements/pull/2529#event-4355198197

**Comment by liggitt** [comment]
> Flag handling logic for klog is super complex, as there are some runtime modification of klog registered flags just to make them have same naming and register conventions as other k/k flags.

cc @dims

**Comment by dims** [comment]
@serathius @liggitt ACK, any changes here will be klog v3 ... yes, it's been really bad for a long time now. 

@serathius please open a fresh issue in kubernetes/klog with some notes on what you would like to see that will make things better.

**Comment by serathius** [comment]
Copying discussion from https://github.com/kubernetes/kubernetes/pull/99257#discussion_r580330690

First all klog initialization should be unified under `component-base/logs` https://github.com/kubernetes/kubernetes/issues/99265

Next step we should, wrap klog by component-base/logs and forbid direct import of klog library. That way we remove chance of components invoking klog without initializing it.

**Comment by ehashman** [comment]
/kind regression
/priority critical-urgent

We have a PR at #99257.

/milestone v1.21
