### ISSUE TITLE
Overflow when the resource is negative

### ISSUE THREAD

**Issue by spyyang** [kubernetes/kubernetes#99231]
#### What happened:

Get the size difference of the resources:
```
// import "k8s.io/apimachinery/pkg/api/resource"

res1 := resource.MustParse("1.0Gi")
res2 := resource.MustParse("10.0Gi")
res1.Sub(res2)
fmt.Println(res1.Value())
```

Result: `8783067658`

#### What you expected to happen:

The correct value should be -9.0Gi: `-9663676416`

#### Anything else we need to know?:

Solution：

Replace `unscaled.Cmp(maxInt64) < 0` with `unscaled.CmpAbs(maxInt64) < 0` in [scale_int.go](https://github.com/kubernetes/kubernetes/blob/release-1.20/staging/src/k8s.io/apimachinery/pkg/api/resource/scale_int.go#L61)

/sig api-machinery

**Comment by fedebongio** [comment]
Hello @spyyang thank you for opening the issue. Are you planning to send a PR to fix it since you've identified the fix?
Thanks!

**Comment by fedebongio** [comment]
thank you for the pr!
/triage accepted
