### ISSUE TITLE
addon-manager: make path to kube-addons.sh injectable

### ISSUE THREAD

**Issue by johanot** [kubernetes/kubernetes#99232]
Sorry for being late out, but we're only about to bump to v1.20.X now.

https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/addon-manager/kube-addons-main.sh#L20-L30

There's some logic here ^ that tries to determine where to find the kube-addons.sh to source. Unfortunately, this is a little too inflexible for us using NixOS, since the addon-manager is run as a standalone systemd-unit (not using the Dockerfile), and since the packaged scripts doesn't necessarily reside in the context of the same working directory when executed.

https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/addon-manager/kube-addons.sh#L29 has means for injection of the path for kubectl ($KUBECTL_BIN). Is it possible to do something similar for the kube-addons "lib"-file? e.g. introduce an environment variable like: $ADDONMANAGER_LIB with default value = `$(pwd)/kube-addons.sh` (if unset)?

ping @spencer-p

**Comment by neolit123** [comment]
> There's some logic here ^ that tries to determine where to find the kube-addons.sh to source. Unfortunately, this is a little too inflexible for us using NixOS, since the addon-manager is run as a standalone systemd-unit (not using the Dockerfile), and since the packaged scripts doesn't necessarily reside in the context of the same working directory when executed.

deferring to its current owners, but FYI, we claim this addon manager as deprecated (that's why it's called the "legacy addon manager") which hints you should not be using it in production.

similar applies to anything under /cluster. it's something that k8s maintainers use for e2e testing and similar.

there were plans to revive it as something better in the kubernetes-sigs/cluster-addons repository but this work is currently stale.

**Comment by spencer-p** [comment]
I will second what @neolit123 said above - the kube-addon-manager is legacy software and is best avoided.

I also don't think it would be unreasonable to make a PR with some change like

```bash
KUBECTL_LIB=${KUBECTL_LIB:-${PWD}}
if [ -f "${KUBECTL_LIB}/kube-addons.sh" ]; then
  # shellcheck disable=SC1091
  source "${KUBECTL_LIB}/kube-addons.sh"
# etc..
```

but I think what would be most preferable is to avoid any kube-addon-manager changes. NixOS could use the `WorkingDirectory=` feature of systemd units to work around this. [see systemd docs](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#WorkingDirectory=).
