### ISSUE TITLE
Add ability to pull all build images through external registry

### ISSUE THREAD

**Issue by Joseph-Goergen** [kubernetes/kubernetes#99238]
There seems to be an environment variable called `KUBE_DOCKER_REGISTRY` which only seems to partially do what I'm asking, but it is not implemented throughout the entirety of Kubernetes.

Here are a couple of examples throughout Kubernetes that are easily greped but there are plenty more examples
- https://github.com/kubernetes/kubernetes/blob/c2e90d8baf65b23df4f2b833834916c965fb57cd/build/workspace.bzl#L128
- https://github.com/kubernetes/kubernetes/blob/e05f4a3facd4106bccdc5ef9eb9401c38391857d/build/build-image/Dockerfile#L18

/sig release

**Comment by rtheis** [comment]
A couple points of clarification on this issue:
- We would like to build Kubernetes from a mirrored registry
- We would like to pull all dependencies through Artifactory

Providing these inputs to the build process would likely enable us to do this.

**Comment by BenTheElder** [comment]
- bazel is on the way out and is not relevant: https://github.com/kubernetes/enhancements/issues/2420
- `KUBE_DOCKER_REGISTRY` is meant to allow overriding `k8s.gcr.io` *as the output* registry:
https://github.com/kubernetes/kubernetes/blob/0a5e4a0d9bd44f262538eef048a7198203445c17/build/root/Makefile#L437
https://github.com/kubernetes/kubernetes/blob/0a5e4a0d9bd44f262538eef048a7198203445c17/build/lib/release.sh#L341-L350 there is not currently anything intended to support altering the source images

`KUBE_BASE_IMAGE_REGISTRY` OTOH supports overriding the registry for the base images for the core build, both are documented in the makefile (which is the symlinked ./Makefile in the repo root):
https://github.com/kubernetes/kubernetes/blob/0a5e4a0d9bd44f262538eef048a7198203445c17/build/root/Makefile#L438

There are many arbitrary build things in the broader project, which parts are you trying to build?

**Comment by rtheis** [comment]
Thanks @BenTheElder, we missed `KUBE_BASE_IMAGE_REGISTRY`.  That will likely provide much of what we need.  We are trying to build Kubernetes API server, scheduler and controller manager images and the kubelet and kube-proxy binaries.  Are there any other knobs that would allow use to pull package dependencies for these builds?

**Comment by BenTheElder** [comment]
What package dependencies?

- Go source code is fully vendored.
- Image builds use base images from Kubernetes (fairly good about being parameterized here) but those are prebuilt elsewhere, none of the core image builds in this repo do e.g. apt install, they just need the base images

**Comment by rtheis** [comment]
@BenTheElder Thank you.  Using KUBE_DOCKER_REGISTRY and KUBE_BASE_IMAGE_REGISTRY will give us what we want.  I incorrectly assumed that the image builds would pull in additional dependencies.  And finally, thank you for catching https://github.com/kubernetes/kubernetes/pull/99145.  I think we can close this issue.

**Comment by Joseph-Goergen** [comment]
@BenTheElder By blocking off my network from `k8s.gcr.io`, I was able to verify that not everything is pulled from the variable, I was able to verify it does with the PR I just submitted
