### ISSUE TITLE
Use multi-arch images in cluster setup

### ISSUE THREAD

**Issue by liu-cong** [kubernetes/kubernetes#99245]
#### What would you like to be added:
Instead of using architecture specific image tags, using multi-arch images provides a seamless experience.
For example, [kube-proxy](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/kube-proxy/kube-proxy-ds.yaml#L37) manifest doesn't need to specify the architecture.

#### Why is this needed:
Helps making cluster setup manifests and scripts architecture independent.

sig/cloud-provider

**Comment by BLasan** [comment]
@liu-cong Is this still opened?

**Comment by neolit123** [comment]
unclear if this is resolved.
the issue details are insufficient and unclear which images are lacking multi-arch.

re-open if needed and if more details are provided.

/close
