### ISSUE TITLE
ValidateClusterSize

### ISSUE THREAD

**Issue by karlkfi** [kubernetes/kubernetes#9925]
Why is cluster size being validated both in [bash](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/kube-up.sh#L40) and [go](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/hack/e2e.go#L270) during e2e tests?

It looks like it's validating cluster size twice when you run `go run hack/e2e.go -up`.

I ask because I need to disable it for Mesos testing (minion nodes do not exist until pods have been created). Disabling via `-check_cluster_size=false` in e2e.go makes sense. Disabling with an env var in bash could work too, but is messy. Having to disable both is just silly.

**Comment by roberthbailey** [comment]
@karlkfi Is this still a problem or have found a workaround in the last 2 months?

**Comment by karlkfi** [comment]
@roberthbailey yes, this is still a problem. For the mesos/docker cluster we have disabled the use of `cluster/validate-cluster.sh` because it uses `/componentsstatus` which is fundamentally flawed and assumes that all components are on localhost. This has the side effect of not checking cluster size, which is desirable because on Mesos, there are no kublets until pods have been scheduled. 

I was trying to address the `/componentsstatus` problem with the Component Registration Proposal #13216, but that got a bit derailed because certain parties wanted to augment services/endpoints instead of adding a new API resource.

In the mean time, `hack/e2e-internal/e2e-cluster-size.sh` used by `hack/e2e.go` just happens to work because the mesos/docker cluster bootstraps with kube-dns and kube-ui pods, which (almost always) get scheduled onto both mesos-slave nodes, launching 2 kubelets.

So, yes we have a temporary workaround, but I still think that cluster-size for e2e tests needs to be re-evaluated. There was talk of making test-specific runtime requirements for tests that needed more than 2 nodes. I know the GCE e2e tests, for example, now run with 3 nodes to work around an issue where certain tests caused side-effects which flakily broke subsequent tests... It's kind of a mess.

**Comment by roberthbailey** [comment]
The Go check isn't done on normal cluster creation since that only uses the bash script, and we need to ensure that we check cluster size on cluster creation somewhere along the line. Making it optional (via an environment variable) seems reasonable, and then it should also be possible for the Go e2e wrapper to set that variable when you pass `-check_cluster_size=false` while creating an e2e cluster. 

/cc @davidopp @fgrzadkowski
