### ISSUE TITLE
[Flake][Sig-Storage]  failed a lot today test/e2e/storage/persistent_volumes-local.go

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#99252]
563 test failures (78 today) look like
->
**569 test failures (81 today) look like (after just 4 hours)**

 https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=storage#9926332667bd1934ccf0

> Kubernetes e2e suite: [sig-storage] PersistentVolumes-local [Volume type: dir-link] One pod requesting one prebound PVC should be able to mount volume and read from pod1 expand_less | 2m6s
> -- | --
> test/e2e/storage/persistent_volumes-local.go:214 Feb 20 04:29:39.410: Unexpected error:     <*errors.errorString \| 0xc00302d670>: {         s: "pod \"pod-8f6a7475-fcdb-4e2d-a810-96489d7e6383\" is not Running: timed out waiting for the condition",     }     pod "pod-8f6a7475-fcdb-4e2d-a810-96489d7e6383" is not Running: timed out waiting for the condition occurred test/e2e/storage/persistent_volumes-local.go:217

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pull-kubernetes-e2e-kind | 2c89fa4a5949c2a8a9e76daada71a18b5afea20e | [link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/99194/pull-kubernetes-e2e-kind/1362976092486373376) | `/test pull-kubernetes-e2e-kind`

[Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes&repo=kubernetes&pr=99194). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3Apacoxu). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

_Originally posted by @k8s-ci-robot in https://github.com/kubernetes/kubernetes/issues/99194#issuecomment-782558528_

**Comment by pacoxu** [comment]
failed in #98960 as well today.

**Comment by pacoxu** [comment]
```
3590: 2021-02-20T06:49:45.704712599Z stderr F I0220 06:49:45.704601       1 eventhandlers.go:164] "Add event for unscheduled pod" pod="persistent-local-volumes-test-1190/pod-655bc831-6e5c-41be-a935-77728c6697e3"
 3591: 2021-02-20T06:49:45.704894582Z stderr F I0220 06:49:45.704775       1 scheduling_queue.go:805] "About to try and schedule pod" pod="persistent-local-volumes-test-1190/pod-655bc831-6e5c-41be-a935-77728c6697e3"
 3592: 2021-02-20T06:49:45.704931121Z stderr F I0220 06:49:45.704869       1 scheduler.go:457] "Attempting to schedule pod" pod="persistent-local-volumes-test-1190/pod-655bc831-6e5c-41be-a935-77728c6697e3"
 3593: 2021-02-20T06:49:45.705215439Z stderr F I0220 06:49:45.705075       1 scheduler_binder.go:801] All bound volumes for Pod "persistent-local-volumes-test-1190/pod-655bc831-6e5c-41be-a935-77728c6697e3" match with Node "kind-worker"
 3594: 2021-02-20T06:49:45.705230352Z stderr F I0220 06:49:45.705094       1 scheduler_binder.go:795] PersistentVolume "local-pvxpz44", Node "kind-worker2" mismatch for Pod "persistent-local-volumes-test-1190/pod-655bc831-6e5c-41be-a935-77728c6697e3": no matching NodeSelectorTerms
 3595: 2021-02-20T06:49:45.705265647Z stderr F I0220 06:49:45.705173       1 scheduler_binder.go:355] AssumePodVolumes for pod "persistent-local-volumes-test-1190/pod-655bc831-6e5c-41be-a935-77728c6697e3", node "kind-worker"
 3596: 2021-02-20T06:49:45.705272866Z stderr F I0220 06:49:45.705197       1 scheduler_binder.go:365] AssumePodVolumes for pod "persistent-local-volumes-test-1190/pod-655bc831-6e5c-41be-a935-77728c6697e3", node "kind-worker": all PVCs bound and nothing to do
 3597: 2021-02-20T06:49:45.705398216Z stderr F I0220 06:49:45.705314       1 default_binder.go:51] "Attempting to bind pod to node" pod="persistent-local-volumes-test-1190/pod-655bc831-6e5c-41be-a935-77728c6697e3" node="kind-worker"
 3598: 2021-02-20T06:49:45.710235152Z stderr F I0220 06:49:45.710055       1 eventhandlers.go:201] "Delete event for unscheduled pod" pod="persistent-local-volumes-test-1190/pod-655bc831-6e5c-41be-a935-77728c6697e3"
 3599: 2021-02-20T06:49:45.710253419Z stderr F I0220 06:49:45.710100       1 eventhandlers.go:221] "Add event for scheduled pod" pod="persistent-local-volumes-test-1190/pod-655bc831-6e5c-41be-a935-77728c6697e3"
 3600: 2021-02-20T06:49:45.710436253Z stderr F I0220 06:49:45.710296       1 scheduler.go:602] "Successfully bound pod to node" pod="persistent-local-volumes-test-1190/pod-655bc831-6e5c-41be-a935-77728c6697e3" node="kind-worker" evaluatedNodes=3 feasibleNodes=1
 4434: 2021-02-20T06:51:52.136537582Z stderr F I0220 06:51:52.136426       1 eventhandlers.go:279] "Delete event for scheduled pod" pod="persistent-local-volumes-test-1190/pod-655bc831-6e5c-41be-a935-77728c6697e3"
```

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/persistent_volumes-local.go#L199
create pv/pvc with node0

Pod create with config:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/persistent_volumes-local.go#L172
config.node0
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/persistent_volumes-local.go#L767

/sig scheduling

/assign
This may be a bug in scheduling and sig-scheduling may look into it.

I try to fix it with a node-affinity for local volume pod temperorily.

**Comment by pacoxu** [comment]
563 test failures (78 today) look like
->
569 test failures (81 today) look like (after just 4 hours)

/priority important-soon 
I think it is important to fix it soon. I encounter it about 5-8 times today in several PR testings.

Feel free to change the priority if you think it is not that important.

**Comment by msau42** [comment]
This PR may help with some of the flakiness:
https://github.com/kubernetes/kubernetes/pull/99320#issuecomment-783665180

cc @aojea

**Comment by Jiawei0227** [comment]
Are we sure this is caused by timeout?

**Comment by aojea** [comment]
I analysed a few failures and all of them were related to the test failing because the pod wasn't running.
This is one occurrence, quoted from https://kubernetes.slack.com/archives/CN0K3TE2C/p1614023847004200?thread_ts=1614021732.000800&cid=CN0K3TE2C

```

Feb 22 19:09:16.068: FAIL: Unexpected error:
    <*errors.errorString | 0xc00274b2c0>: {
        s: "pod \"pod-f081ab68-b003-4ed3-848d-c56833aa4cb4\" is not Running: timed out waiting for the condition",

Feb 22 19:09:23 kind-worker containerd[173]: time="2021-02-22T19:09:23.100562223Z" level=info msg="RunPodSandbox for &PodSandboxMetadata{Name:pod-f081ab68-b003-4ed3-848d-c56833aa4cb4,Uid:2055d560-61c5-4149-a86e-52b140f8ff3d,Namespace:persistent-local-volumes-test-8740,Attempt:0,} returns sandbox id \"bea65f48429b5512b8420cb13b154af3ef21303646800bef97530c342702fdcc\""

7 seconds gap

this is the creation
Feb 22 19:07:17 kind-worker containerd[173]: time="2021-02-22T19:07:17.610014685Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:pod-f081ab68-b003-4ed3-848d-c56833aa4cb4,Uid:2055d560-61c5-4149-a86e-52b140f8ff3d,Namespace:persistent-local-volumes-test-8740,Attempt:0,}"
```

**Comment by alculquicondor** [comment]
I'm seeing the same error for:

```
Kubernetes e2e suite: [sig-storage] PVC Protection Verify that scheduling of a pod that uses PVC that is being deleted fails and the pod becomes Unschedulable
```

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-kind&include-filter-by-regex=PVC%20Protection

**Comment by alculquicondor** [comment]
@pacoxu could you clarify why you think there's a problem with scheduling?

**Comment by pacoxu** [comment]
> @pacoxu could you clarify why you think there's a problem with scheduling?

The error that I found in my failure is like below, which is a scheduling problem in volume test case.

> 3594: 2021-02-20T06:49:45.705230352Z stderr F I0220 06:49:45.705094 1 scheduler_binder.go:795] PersistentVolume "local-pvxpz44", Node "kind-worker2" mismatch for Pod "persistent-local-volumes-test-1190/pod-655bc831-6e5c-41be-a935-77728c6697e3": no matching NodeSelectorTerms


@aojea is working on it. #99320 increased the pod start timeout from 2min to 5min. It is merged yesterday.
I'd like to see whether it fixed most failure of this later.

**Comment by aojea** [comment]
> @aojea is working on it. #99320 increased the pod start timeout from 2min to 5min. It is merged yesterday.
> I'd like to see whether it fixed most failure of this later

It seems it is much better now
https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=kind&test=One%20pod%20requesting%20one%20prebound%20PVC%20should%20&xjob=-1-

**Comment by pacoxu** [comment]
/close
As it may be fixed by  #99320.
I works better now.

**Comment by alculquicondor** [comment]
@cofyc WDYT of https://github.com/kubernetes/kubernetes/issues/99252#issuecomment-784681180 ?

**Comment by msau42** [comment]
I think that error is expected. The volume was provisioned on node "kind-worker", and this message is from the scheduler predicate evalutating "kind-worker-2". I think what happened in these tests is that the pod did get scheduled to "kind-worker" but was slow to come up and timed out.

**Comment by eddiezane** [comment]
I think this is still failing.

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/100541/pull-kubernetes-e2e-kind/1374800857081581568

https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=One%20pod%20requesting%20one%20prebound%20PVC%20should%20be%20able%20to%20mount%20volume%20and%20read%20from%20pod1

/reopen

**Comment by msau42** [comment]
Looking at kubelet logs from https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/100541/pull-kubernetes-e2e-kind/1374800857081581568

All volumes were mounted successfully:
```
Mar 24 19:43:22 kind-worker kubelet[247]: I0324 19:43:22.199279     247 volume_manager.go:404] All volumes are attached and mounted for pod "pod-febb089d-4438-4246-bf15-f7d2f93949a4_persistent-local-volumes-test-3221(82693c6c-7e2b-4940-887d-3704b34f2103)"
```

But it looks like the container was not able to come up:
```
Mar 24 19:45:21.323: INFO: pod-febb089d-4438-4246-bf15-f7d2f93949a4  kind-worker  Pending  30s    [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2021-03-24 19:43:21 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2021-03-24 19:43:21 +0000 UTC ContainersNotReady containers with unready status: [write-pod]} {ContainersReady False 0001-01-01 00:00:00 +0000 UTC 2021-03-24 19:43:21 +0000 UTC ContainersNotReady containers with unready status: [write-pod]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2021-03-24 19:43:21 +0000 UTC  }]
```

**Comment by pacoxu** [comment]
![image](https://user-images.githubusercontent.com/2010320/115852767-05ba3280-a45b-11eb-9b0b-99da61ee10ce.png)
I will take a look next week if I have some time then.
