### ISSUE TITLE
Move Logs options to component-base/config

### ISSUE THREAD

**Issue by serathius** [kubernetes/kubernetes#99267]
#### What would you like to be added:

Migrate https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/component-base/logs/options.go to https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/config

/kind cleanup

#### Why is this needed:

Configuration of logs is split between Options in component-base/logs/options.go used for control plane components and LoggingConfiguration in component-base/config/types.go. Having two flows for initialization flags can lead to them going out of sync leading to bugs.

Part of work for Structured Logging.

Previous attempt https://github.com/kubernetes/kubernetes/pull/92732
/sig instrumentation
/cc @ehashman 
/priority important-soon
/help

**Comment by jmguzik** [comment]
@serathius why the previous attempt has failed? Could you cast more light?
If you do not expect some tricky corner cases, I could give it a try. It will be my first work in k8s though, so let me know if you consider this a good first job.

**Comment by serathius** [comment]
I think there were problem with test failures, also this code touches API (delicate and slow to review) and code of a lot of components complicating implementation.

**Comment by serathius** [comment]
It's pretty complicated issue so I would not recommend it for first contribution. If you're interested in other work in sig-instrumentation/structured logging area, I can recommend helping with migrating kubelet to structured logging.  https://github.com/kubernetes/kubernetes/issues/98976

**Comment by serathius** [comment]
Options now use Config internally so this solved problem of duplicated code by Kubelet. Thanks @mengjiao-liu for help with that.
