### ISSUE TITLE
Exiting due to RSRC_INSUFFICIENT_SYS_MEMORY: System only has 0MiB available, less than the required 1800MiB for Kubernetes

### ISSUE THREAD

**Issue by Jiu-hong** [kubernetes/kubernetes#99271]
#### What happened:
I am installing minikube on ubuntu 20.04 according to this instruction:
https://phoenixnap.com/kb/install-minikube-on-ubuntu

Then I start this command **minikube start**
it failed with **Exiting due to RSRC_INSUFFICIENT_SYS_MEMORY: System only has 0MiB available, less than the required 1800MiB for Kubernetes
**

This is the storage usage in ubuntu
```
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/root        8065444 2332272   5716788  29% /
devtmpfs          495236       0    495236   0% /dev
tmpfs             501048       0    501048   0% /dev/shm
tmpfs             100212     808     99404   1% /run
tmpfs               5120       0      5120   0% /run/lock
tmpfs             501048       0    501048   0% /sys/fs/cgroup
/dev/loop0         33152   33152         0 100% /snap/amazon-ssm-agent/2996
/dev/loop1         56832   56832         0 100% /snap/core18/1944
/dev/loop2         71552   71552         0 100% /snap/lxd/19032
/dev/loop3         31872   31872         0 100% /snap/snapd/10707
tmpfs             100208       0    100208   0% /run/user/1000
ubuntu@ip-172-31-24-69:~$ pwd

```

#### What you expected to happen:
Can you help fix this issue?
#### How to reproduce it (as minimally and precisely as possible):
reproduce it according exactly to this instruction
https://phoenixnap.com/kb/install-minikube-on-ubuntu
#### Anything else we need to know?:
no
#### Environment:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

- Cloud provider or hardware configuration: AWS EC2
- OS (e.g: `cat /etc/os-release`): 
- NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

- Kernel (e.g. `uname -a`):
Linux ip-172-31-24-69 5.4.0-1037-aws #39-Ubuntu SMP Thu Jan 14 02:56:06 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
try logging this issue in the kubernetes/minikube repository or ask in the #minikube channel on k8s slack.

/close
/kind support
/remove-kind bug
/sig cluster-lifecycle
