### ISSUE TITLE
Json format should support same set of feature flags as klog

### ISSUE THREAD

**Issue by serathius** [kubernetes/kubernetes#99270]
#### What would you like to be added:
 
 To move json logging format to Beta it should support same set of features as klog. As it doesn't make sense to reimplement all features for all logging formats we should start from discussing what klog flags we want to support long term and what we should be deprecated. Plan:
 * Start discussion about set of features that should be supported
 * Propose a plan for deprecating remaining klog flags
 * Implement missing features for Json format

#### Why is this needed:

Logging formats should support same features.

/sig instrumentation
/help
/priority important-soon
/cc @ehashman

**Comment by ehashman** [comment]
What is the current feature diff?

**Comment by serathius** [comment]
Looking into what klog flags, only -v was implemented, we are missing:
`--add-dir-header, --alsologtostderr, --log-backtrace-at, --log-dir, --log-file, --log-file-max-size, --logtostderr, --one-output, --skip-headers, --skip-log-headers, --stderrthreshold, --vmodule, --log-flush-frequency.

**Comment by yuzhiquan** [comment]
if have another log format in the future, we also need to implement all of these  flags?

**Comment by serathius** [comment]
> As it doesn't make sense to reimplement all features for all logging formats we should start from discussing what klog flags we want to support long term and what we should be deprecated

**Comment by yuzhiquan** [comment]
fix #96314 [klog/203](https://github.com/kubernetes/klog/issues/203)

**Comment by adammw** [comment]
Also not a flag per-se, but klog prints the go file and line writing the log, whereas the json logger does not.

**Comment by sladyn98** [comment]
I guess for this issue as specified @serathius we would need to first discuss which flags would we like to support, are there any factors to consider while having this discussion ? 
1) --add-dir-header
2) --alsologtostderr
3) --log-backtrace-at
4) --log-dir
4) --log-file
5) --log-file-max-size
6) --logtostderr
7) --one-output
8 --skip-headers
9 --skip-log-headers
10 --stderrthreshold
11 --vmodule
12) --log-flush-frequency.

**Comment by yuzhiquan** [comment]
I will have enough time in next week, may we can move on this @serathius

**Comment by sladyn98** [comment]
@yuzhiquan Great, I could help you with implementing some of these flags as well. Let me know and we can sync up on this

**Comment by serathius** [comment]
First would be good to analyse which flags makes sense for JSON, for example `--skip-headers` seems specific to klog format. 
Discussion on what flags to support should be done in more open space, for example we could send an email to k8s-dev email list with a proposal.

**Comment by Priyankasaggu11929** [comment]
cc: @Priyankasaggu11929

**Comment by serathius** [comment]
## Analysis of features in both solutions

### Klog

Flags https://github.com/kubernetes/klog/blob/69472594defe33aee4442f9266aadfddc89fe4b0/klog.go#L429-L443

Klog flags grouped by features:
* Writing to files: --log-dir, --log-file, 
* Log sinks: --logtostderr, --alsologtostderr, --one-output, --stderrthreshold
* File log rotation: --log-file-max-size, --skip-log-headers
* Configuring basic log metadata: --add-dir-header, --skip-headers
* Verbosity:  --v, --vmodule, 
* Adding Stacktrace: --log-trace-location
* Flushing logs: --log-flush-frequency.

ouput:
```
I0605 22:03:07.224378 3228948 logger.go:59] "Log using InfoS" key="value"
```
Analysis:
* `I` - log severity, can be IWEF
* `0605` - month day part of date
* `22:03:07.224378` - time with microsecond resolution
* `logger.go:59` - source of the log line
* `"Log using InfoS"` - log message
* `key="value"` - key value argument pair

**Comment by serathius** [comment]
# JSON

Flags: `--v` - setting verbosity

output: 
```
{"ts":1622923409719.5403,"msg":"Log using InfoS","v":0,"key":"value"}
```

Analysis of json keys:
* `ts` - timestamp in UNIX time represented as float64
* `msg` - log message
* `v` - log verbosity
* `key` - log argument key

**Comment by serathius** [comment]
Existing feature request for json format:
* Support `--vmodule` - https://github.com/kubernetes/klog/issues/203 - 
* Missing caller information - https://github.com/kubernetes/klog/issues/211 https://github.com/kubernetes/kubernetes/issues/102353

**Comment by serathius** [comment]
Based on this information we should create a proposal that list what features we want to add and what we want to drop. @yuzhiquan are you still interested in working on this issue?

**Comment by yuzhiquan** [comment]
> Based on this information we should create a proposal that list what features we want to add and what we want to drop. @yuzhiquan are you still interested in working on this issue?

Sure, so i need add an KEP for this feature first?

**Comment by serathius** [comment]
I would start from discussing options here, when we have a proposal we can weigh how big impact it is by sending email k8s-dev googlegroup. If it turns out that it requires a more formal proposal then we would go with KEP, but I don't think that proposing to add/remove flags should start with a KEP.

**Comment by sladyn98** [comment]
**JSON**

Flags: -log-flush-frequency - setting frequency between log flushes


**Output:**

Kubernetes logs are written to stdout
Zap internal errors are written to stderr

**Format:**

{"ts":1622923409719.5403,"msg":"Log using InfoS","v":0,"key":"value", "f":35}
Analysis of json keys:

ts - timestamp in UNIX time represented as float64
msg - log message
v - log verbosity
f - log flush frequency in seconds
key - log argument key

**Comment by serathius** [comment]
@sladyn98 Not sure I understand your comment, in comments above I tried to describe what current features JSON format currently supports, currently only `-v` flag is supported no others. I will post a proposal for changes separetly.

**Comment by serathius** [comment]
@yuzhiquan I don't see any progress on the issue from your side, are you still planning to continue the work? I would be happy to take over the issue. This issue is needed to graduate JSON format to Beta so we should target it for 1.22.
/milestone v1.22

**Comment by sladyn98** [comment]
@serathius I could help pick up some of the implementation as well. Happy to do so

**Comment by serathius** [comment]
## Proposal
 
Kubernetes system component logs should be treated as a event streams like defined by 12 factor app standard  https://12factor.net/. This is something that Kubernetes already encourages by collecting stdout and stderr by default and making them available via `kubectl logs`. As so it's confusing that K8s system components doesn't itself comply to it's own best practices.

As so I propose to that Kubernetes core components (kube-apiserver, kube-scheduler, kube-controller-manager, kubelet) should drop flags that extend logging over events streams or klog specific features. This change should be scoped to only those components and not affect broader klog community. Goal of this change it define a small core set of logging features allowing for easier development and growth of alternative logging formats. For example Kubelet which is frequently run under systemd would greatly benefit from direct integration with journal.

Flags that should be deprecated:
*  --log-dir, --log-file, --log-flush-frequency - writing to files and how frequently files should be synced
*  --logtostderr, --alsologtostderr, --one-output, --stderrthreshold - enabling/disabling if writing to stderr
*  --log-file-max-size, --skip-log-headers - configuration of log rotation
* --add-dir-header, --skip-headers - klog format specific flags that don't apply to other formats
*  --log_backtrace_at - a klog specific feature

If those flags would be deprecated in 1.22, they could be removed in 1.25 to comply with K8s deprecation policy.

This leaves that two flags:
* -v - control global log verbosity of Info logs 
* --vmodule - control log verbosity of Info logs on per file level


This is an early proposal that is meant to start discussion in community. Please let me know what you think.

**Comment by yuzhiquan** [comment]
> @yuzhiquan I don't see any progress on the issue from your side, are you still planning to continue the work? I would be happy to take over the issue. This issue is needed to graduate JSON format to Beta so we should target it for 1.22.
> /milestone v1.22

Sorry for lately reply, i am still interested in this implement, but if the timeline is matter of some urgency, i think @serathius can take this from here.
I DO have enough time this week, and happy to working with you.

**Comment by BenTheElder** [comment]
> Keep supporting klog features - This makes removing global flags much harder as it requires to move all klog flags into

I don't think that's true, klog has an explicit `InitFlags`, we can just have an `InitFlags` that does not register flags Kubernetes is not supporting? Or bounce them through a temporary flagset and only copy over specific flags to the global / command flagset?

Removing these also potentially breaks consumers that are not the core Kubernetes binaries. I'm sure we have lots of those:
https://cs.k8s.io/?q=%22k8s.io%2Fklog%22&i=nope&files=&excludeFiles=&repos=

I think for starters we should check which flags are being used in-org against the k8s components (kubeadm, kops, etc.).

**Comment by serathius** [comment]
Started thread https://groups.google.com/g/kubernetes-dev/c/dAzHAdxe6ok


> > Keep supporting klog features - This makes removing global flags much harder as it requires to move all klog flags into
>
>I don't think that's true, klog has an explicit InitFlags, we can just have an InitFlags that does not register flags Kubernetes is not supporting? Or bounce them through a temporary flagset and only copy over specific flags to the global / command flagset?

One of goals of this change is to move logging configuration to Options/Configuration format from k8s.io/component-base/logs as this is the standard not global way to configure components. If we kept all klog flags it would be much harder to remove them in future. 

> Removing these also potentially breaks consumers that are not the core Kubernetes binaries.

That's why I want changes to be implemented on k8s.io/component-base/logs side and not in klog. We might expose some additional interface for convenience, but not affect klog.

> I think for starters we should check which flags are being used in-org against the k8s components (kubeadm, kops, etc.).

That's a great idea, let me take a look.

**Comment by BenTheElder** [comment]
Sorry I misread this to removing the flags in klog directly, not component base. I agree https://github.com/kubernetes/kubernetes/issues/99270#issuecomment-865293966 sounds reasonable 👍

**Comment by serathius** [comment]
Did a quick search on k/k and kops repo. [Search](https://cs.k8s.io/?q=%22log-dir%7Clog-file%7Clog-flush-frequency%7Cone-output%7Cstderrthreshold%7Clog-file-max-size%7Cskip-log-headers%7Cadd-dir-header%7Cskip-headers%7Clog-backtrace-at%22&i=nope&files=&excludeFiles=CHANGELOG%7Cconfigure-helper.sh%7C(%5C.md%24)&repos=kubernetes/kops,kubernetes/kubernetes)

Looks like both kops and kubeup use log-file to write logs on host. However in 1.19 kubernetes images stop using klog to write logs to files, instead they use go-runnger. Context: https://github.com/kubernetes/kubernetes/pull/90804 

@dims Could you shed some light why klog using klog caused scalability problems? Would using go-runner be acceptable fallback?

**Comment by dims** [comment]
@serathius we never got enough debugging on the scalability jobs to nail that down, we tried several things and had to revert multiple times :(

So ended up coding go-runner to keep the same contract as before and that worked fine the first time we tried it :)

**Comment by liggitt** [comment]
> Flags that should be deprecated:
> 
> * --log-dir, --log-file, --log-flush-frequency - writing to files and how frequently files should be synced
> * --logtostderr, --alsologtostderr, --one-output, --stderrthreshold - enabling/disabling if writing to stderr
> * --log-file-max-size, --skip-log-headers - configuration of log rotation

Of the options, the one that seems most concerning to deprecate/remove is file/stderr/stdout destination switching in favor of writing only to stdout.

Have we determined how much use there is of these three options today? (not just in the images we build, but broadly... people run these components using their own scripts)

Collapsing to a single output stream and then allowing switching that stream to structured logging implies that we can guarantee all writers to that stream will write in the structured format (otherwise we break json parsers reading from that stream). Do we have that level of control over all writers to stdout in these components and all their dependencies at all verbosity levels?

**Comment by yuzhiquan** [comment]
> > Flags that should be deprecated:
> > 
> > * --log-dir, --log-file, --log-flush-frequency - writing to files and how frequently files should be synced
> > * --logtostderr, --alsologtostderr, --one-output, --stderrthreshold - enabling/disabling if writing to stderr
> > * --log-file-max-size, --skip-log-headers - configuration of log rotation
> 
> Of the options, the one that seems most concerning to deprecate/remove is file/stderr/stdout destination switching in favor of writing only to stdout (and if we support selecting a file output, rotating that file seems required to avoid "disk-full" foot guns).
> 
> Have we determined how much use there is of these three options today? (not just in the images we build, but broadly... people run these components using their own scripts)
> 
> Collapsing to a single output stream and then allowing switching that stream to structured logging implies that we can guarantee all writers to that stream will write in the structured format (otherwise we break json parsers reading from that stream). Do we have that level of control over all writers to stdout in these components and all their dependencies at all verbosity levels?

We set  log-dir in kubernetes core compoent，such as `kubelet`|`kube-scheduler`|`kube-controler-manager`, if we change to `json` or other log format, the log file will gone, sounds like a breaking change for log file.

**Comment by serathius** [comment]
> Have we determined how much use there is of these three options today? (not just in the images we build, but broadly... people run these components using their own scripts)

We have looked into usage of those flags in kubernetes org repos [Search](https://cs.k8s.io/?q=--(log-dir%7Clog-file%7Clog-flush-frequency%7Cone-output%7Cstderrthreshold%7Clog-file-max-size%7Cskip-log-headers%7Cadd-dir-header%7Cskip-headers%7Clog-backtrace-at)&i=nope&files=&excludeFiles=CHANGELOG%7Cconfigure-helper.sh%7C(%5C.md%24)&repos=kubernetes-sigs/kind,kubernetes/kops,kubernetes/kubernetes,kubernetes/minikube). We found out file flags are still used by kops, but looks like kubeup (used to run gce&scalability) moved to external tool go-runner. Klog implementation of file destination caused scalability problems. I think this is one example 
 Do you have any proposal how we can verify this broadly?

**Comment by serathius** [comment]
Missclick

**Comment by serathius** [comment]
> Have we determined how much use there is of these three options today? (not just in the images we build, but broadly... people run these components using their own scripts)

@liggit We have looked into usage of those flags in kubernetes org repos [Search](https://cs.k8s.io/?q=--(log-dir%7Clog-file%7Clog-flush-frequency%7Cone-output%7Cstderrthreshold%7Clog-file-max-size%7Cskip-log-headers%7Cadd-dir-header%7Cskip-headers%7Clog-backtrace-at)&i=nope&files=&excludeFiles=CHANGELOG%7Cconfigure-helper.sh%7C(%5C.md%24)&repos=kubernetes-sigs/kind,kubernetes/kops,kubernetes/kubernetes,kubernetes/minikube). We found out file flags are still used by kops, but looks like kubeup (used to run gce&scalability) moved to external tool go-runner. Klog implementation of file destination caused scalability problems.

I think this is good argument for simplification of klog features. The maintainers of klog are not able to maintain quality of exposed features as re-implementing them in external project is easier than debugging the underlying problem. Fact that we quickly implemented a golang wrapping process that can handle apiserver log volume from 5000 node cluster is also testament to external log routing being a viable option. Kubernetes components are complicated enough themselves, we should not invest in maintaining a full blown logging libraries just because user doesn't want to run an additional binary. Giving community go-runner and allowing development of more advanced features should be more beneficial to community when compared to forcing closed list of features on everyone.

As we this is only only based on Kubernetes Org repos, do you have any proposal how we can verify this broadly?

> Collapsing to a single output stream and then allowing switching that stream to structured logging implies that we can guarantee all writers to that stream will write in the structured format (otherwise we break json parsers reading from that stream). Do we have that level of control over all writers to stdout in these components and all their dependencies at all verbosity levels?

For klog format this should not be a problem as already all parses assume multi line format where lines without klog header belong to previous log line. In case of JSON we should be able to assume that each log is on separate line. Streams readers should be able to handle non-Json lines and have some fallback behavior.
Still having a pure JSON output is rudimentary for JSON format success. We are not there yet, but we are working on both integration and e2e tests (https://github.com/kubernetes/kubernetes/issues/102237, https://github.com/kubernetes/kubernetes/issues/100748) that should validate if there are any non-json logs produced. Additionally we should cosider adding a static analysis that will verify that there are no direct calls to `os.Stdout` or `fmt.Printf`. We should be ready before klog flags removal.

> We set log-dir in kubernetes core compoent，such as kubelet|kube-scheduler|kube-controler-manager, if we change to json or other log format, the log file will gone, sounds like a breaking change for log file.

As mentioned above, all K8s core containers come with `go-runner` binary that is used as component process parent that reads the stdout/stderr and writes them to file. It is a breaking change as users might need to change the configuration they use, but it's not a regression as we provide an alternative.

**Comment by liggitt** [comment]
https://grep.app is a good tool for searching across github repos/orgs, though the flag collision with old glog flags likely makes this much harder to determine usage for

**Comment by liggitt** [comment]
> we are working on both integration and e2e tests (#102237, #100748) that should validate if there are any non-json logs produced

I'm skeptical integration or e2e tests have sufficient coverage of exceptional cases to prove nothing writes to stdout

**Comment by BenTheElder** [comment]
That also seems tricky to statically analyze accurately, e.g. we have components that link to CGO?

Not sure what the answer is here.

**Comment by serathius** [comment]
First I don't think having guarantee that K8s components generate pure JSON logs is requirement for removal of klog flags and migration to depend on external process to route logs to files. Like klog formatted logs, json format splits output in separate lines. As long as log stream consumer reads each line separately and has some fallback logic for non correctly formatted lines we are good to go. This is already an expected behavior for klog consumers as there are some multi line logs in Kubernetes (for example apiserver trace logs), for klog fallback for lines without header is to append them to last line with header. Of course eliminating not correctly formatted output is important for alternative log formats, but it's not something we should block.

> That also seems tricky to statically analyze accurately, e.g. we have components that link to CGO?

If that's true, then we should invest more time in solving this. SIG Security is already depending using static analysis to secure Kubernetes logs from leaking secrets https://github.com/kubernetes/enhancements/tree/master/keps/sig-security/1933-secret-logging-static-analysis. If you know any obstacles (like CGO you mentioned), maybe we should start working on eliminating them. For example reach out to SIG release and agree that CGO should never be used to build canonical K8s binaries.

**Comment by neolit123** [comment]
i searched for a solution about detecting CGO one time and found this:
https://www.reddit.com/r/golang/comments/655kax/how_to_figure_out_whats_using_cgo/dg85l1d/

**Comment by BenTheElder** [comment]
Sorry, I didn't mean that we have to catch every possible case for it to be worthwhile, that problem is no different than from today where some random library could write gibberish to stdout/stderr (or a file) already, CGO or otherwise.

For the record though, why I don't think you can 100% catch it like this if you wanted to:

<details>

> If that's true, then we should invest more time in solving this.  SIG Security is already depending using static analysis to secure Kubernetes logs from leaking secrets https://github.com/kubernetes/enhancements/tree/master/keps/sig-security/1933-secret-logging-static-analysis. 

Yeah, I've been reviewing the govet-levee scripts, it's a good approach but it depends on how sensitive we are to the possibility of anything writing to this. Static analysis makes sense for defense in depth but isn't a total guarantee. In that KEP's case it also requires manual tagging of secret sources.

Besides CGO, Anything can grab the well-known FDs and write to them directly? And of course the analysis does not cover the C libraries we're linking to.

`os.Stderr` in go is just an alias to opening a file to this well known fd (`2`).

```
var (
    Stdin  = NewFile(uintptr(syscall.Stdin), "/dev/stdin")
    Stdout = NewFile(uintptr(syscall.Stdout), "/dev/stdout")
    Stderr = NewFile(uintptr(syscall.Stderr), "/dev/stderr")
)
```

So you could just have some go code dynamically compute one of the fds and open to it without using `os.Stdin` and not really be able to catch this.

An e2e almost seems more likely to detect this.

> For example reach out to SIG release and agree that CGO should never be used to build canonical K8s binaries.

Where possible we build without CGO because it lets us cross compile more easily, but this is impractical for kubelet at least currently (links to selinux, maybe nvidia libraries for monitoring).

When building in CGO mode, this also means libc / using the system DNS resolver calls in the network stack at minimum. I would think that code should not be writing to stdout/stderr, but it will not be covered by straightforward analysis and is dynamically linked anyhow.

</details>

(details hidden because while it might be interesting to some, I'm not sure it's _overly_ relevant that 100% guarantee is challenging, again this problem already exists ...)

**Comment by voigt** [comment]
Due to v1.22 code freeze, I'm moving this issue to the next release.

/milestone v1.23

**Comment by serathius** [comment]
KEP to deprecate klog specific flags was accepted. Work will be tracked in https://github.com/kubernetes/enhancements/issues/2845
