### ISSUE TITLE
Provide downward API for Node's ProviderID and System UUID

### ISSUE THREAD

**Issue by amit4alcide** [kubernetes/kubernetes#99285]
#### What would you like to be added:
kubectl describe node provides ProviderID and System UUID information,
however there is no supported downard API allowing to pass them to Pod
like in case of spec.nodeName 

#### Why is this needed:
add ProviderID and System UUID to downward API node spec so pod can have node information when needed.

although labelled as "feature", any guidance on how to achieve this information from within the pod could help.

/sig api
/sig node

**Comment by haircommander** [comment]
hey @amit4alcide, thanks for opening the issue. I am not sure I see the general applicability of passing this information to every pod. What is your use-case that makes the node name insufficient?

**Comment by amit4alcide** [comment]
Hi. Mainly for allowing to pass unique node identifiers such as the full
providerID, systemUUID to the pods being executed over the same node. The
nodeName is usually a shorter version of the full providerUUID so it might
be repeating between different clusters while other UUIDs mentioned above
do not.
