### ISSUE TITLE
ephemeral-storage limit not working.

### ISSUE THREAD

**Issue by patricio-dorantes** [kubernetes/kubernetes#99280]
#### What happened:
As reported on [https://github.com/kubernetes/kubernetes/issues/78865](#78865) spec.template.spec.containers[].limits.ephemeral-storage is not working as expected. Pod is not being evicted when this limit is surpassed. 

#### What you expected to happen:
[https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/](Official documentation) goes like this: 
"If a Pod is using more ephemeral storage than you allow it to, the kubelet sets an eviction signal that triggers Pod eviction."

Either  official documentation should tell this is intended only when /var/lib/kubelet and "root" + "state" are on the same filesystem, OR enforce this limits even when kubelet is not on the same fs.

#### How to reproduce it (as minimally and precisely as possible):

- Install k8s node with containerd 
- Set containerd "root" and "state" on a filesystem different that kubelet (/var/containers in my case)
- Create a deployment with spec.template.spec.containers[].limits.ephemeral-storage parameter >= than container size
- Exec into the container a command that fills ephemeral storage (dd, fallocate, any log, etc)
- Watch your pod not being evicted after days

#### Anything else we need to know?:
andreamaruccia did the comment on the first report on how to reproduce, she fixed it moving /var/lib/kubelet. I moved "root" and "state" to the /var/lib system and 
I did the read on metrics (even thought this was a prometheus/metrics problem before Andrea spare some minutes for me) but kubelet is correctly reporting on both cases. 

#### Environment:
- version.Info {Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:00:47Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
- Red Hat Enterprise Linux Server 7.9 (Maipo) (3.10.0-1160.2.1.el7.x86_64)
- Install tools: kubeadm
- Others: containerd://1.3.7

**Comment by pacoxu** [comment]
/sig node storage
link to #78865

**Comment by patricio-dorantes** [comment]
I'm afraid this ticket will get old. Is using multiple filesystem not considered a best practice?

**Comment by matthyx** [comment]
I suggest we follow up in #98935
/close
