### ISSUE TITLE
kube-proxy iptables wrong configuration externalTrafficPolicy Local in large clusters

### ISSUE THREAD

**Issue by juliantaylor** [kubernetes/kubernetes#99299]
#### What happened:

In our cluster of about 260 nodes and 9000 pods we sometimes have the kube-proxy wrongly configures iptables for services with externalTrafficPolicy Local during phases of high endpoint activity (rolling redeploy).
This occurs only sometimes so it is probably some kind of race condition or caused by intermittent errors like connection resets.

The node in question has (according to the API) several local pods so kube-proxy should configure iptables to forward traffic to them, but instead if drops the traffic.

The problem manifests itself as following iptables configuration for an ingress controller with externaltrafficpolicy Local, it configures it as if there is no local endpoint (which are running) so it drops the non local traffic:
```
-A KUBE-SERVICES -d ipaddress/32 -p tcp -m comment --comment "ingress-controller/traefik-ingress-service-team-xyz:http loadbalancer IP" -m tcp --dport 80 -j KUBE-FW-LWUTJB5ULEARB6TO
-A KUBE-FW-LWUTJB5ULEARB6TO -m comment --comment "ingress-controller/traefik-ingress-service-team-xyz:http loadbalancer IP" -j KUBE-XLB-LWUTJB5ULEARB6TO
-A KUBE-FW-LWUTJB5ULEARB6TO -m comment --comment "ingress-controller/traefik-ingress-service-team-xyz:http loadbalancer IP" -j KUBE-MARK-DROP
-A KUBE-XLB-LWUTJB5ULEARB6TO -s 100.64.0.0/13 -m comment --comment "Redirect pods trying to reach external loadbalancer VIP to clusterIP" -j KUBE-SVC-LWUTJB5ULEARB6TO
-A KUBE-XLB-LWUTJB5ULEARB6TO -m comment --comment "masquerade LOCAL traffic for ingress-controller/traefik-ingress-service-team-xyz:http LB IP" -m addrtype --src-type LOCAL -j KUBE-MARK-MASQ
-A KUBE-XLB-LWUTJB5ULEARB6TO -m comment --comment "route LOCAL traffic for ingress-controller/traefik-ingress-service-team-xyz:http LB IP to service chain" -m addrtype --src-type LOCAL -j KUBE-SVC-LWUTJB5ULEARB6TO
-A KUBE-XLB-LWUTJB5ULEARB6TO -m comment --comment "ingress-controller/traefik-ingress-service-team-xyz:http has no local endpoints" -j KUBE-MARK-DROP

-A KUBE-SVC-LWUTJB5ULEARB6TO -m statistic --mode random --probability 0.02127659554 -j KUBE-SEP-WNJ5QKGUHPD3B7I5
-A KUBE-SVC-LWUTJB5ULEARB6TO -m statistic --mode random --probability 0.02173913037 -j KUBE-SEP-2LQWVHEBN6SLQ7SO
... more svcs to endpoints on other nodes

```

In this case the node had 5 local pods available as endpoints, none of the 10 endpoints show up in the KUBE-SEP rules, only the 48 non-local endpoints (for src local traffic).

The endpoint object in the API had the 5 local endpoints listed as ready (in .subsets[].addresses[]). The pod objects were also ready.

The node still gets traffic as the ip announcement (metallb) does see the local endpoints in the api and annouces the ip but kube-proxy/iptables drops it.

The kube-proxy logs show no errors or anything helpful for the issue, just the usual adding service, opening healthcheck/nodeport also for the service with the wrong configuration.

#### How to reproduce it (as minimally and precisely as possible):

Hard to reproduce, happens randomly and only in our largest clusters. Not reproduced in smaller test environments yet.

#### Environment:
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"89182bdd065fbcaffefec691908a739d161efc03", GitTreeState:"clean", BuildDate:"2020-12-18T12:02:35Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

kube-proxy in iptables mode with default settings

- bare metall
- flatcar linux 2605.12.0
- 5.4
- Install tools:
- Network plugin and version (if this is a network-related bug): kube-proxy 1.18.14, calico 3.17.1

**Comment by aojea** [comment]
> In our cluster of about 260 nodes and 9000 pods we sometimes have the kube-proxy wrongly configure externalTrafficPolicy Local services during phases of high endpoint activity (rolling redeploy).

does this mean that the Service object literally switches the field to "Local" ?

**Comment by juliantaylor** [comment]
Yes, the service object has following set:

```
spec:
  externalTrafficPolicy: Local
```

**Comment by juliantaylor** [comment]
Sorry I misunderstood, no the service is supposed to be externalTrafficPolicy Local, it does not change, but the iptables configuration kube-proxy does for this type of service is wrong.

**Comment by thockin** [comment]
Are the pods coming up or restarting during this? 

@andrewsykim has some work to make that more resilient

**Comment by sfudeus** [comment]
Workload and kube-proxy pods are running fine, just the routing via iptables is incorrect.

**Comment by caseydavenport** [comment]
@juliantaylor do you happen to know if your kube-proxy has been configured to use the beta EndpointSlice API instead of the Endpoints API? https://kubernetes.io/docs/tasks/administer-cluster/enabling-endpointslices/

For v1.18 it should default to using Endpoints, but can be changed to EndpointSlices via a feature gate. I don't have any reason to suspect that's the issue - just gathering information about the setup.

**Comment by juliantaylor** [comment]
We also suspected this might be caused by endpoint slices, but no we have *not* explicitly enabled them in the kube-proxy and are using the default, which according to the documentation of 1.18 is endpointslices usage disabled.

**Comment by aojea** [comment]
> We also suspected this might be caused by endpoint slices, but no we have _not_ explicitly enabled them in the kube-proxy and are using the default, which according to the documentation of 1.18 is endpointslices usage disabled.

you'll be able to confirm it in the kube-proxy logs

**Comment by juliantaylor** [comment]
there is no logging of any endpoint slice reflector setups in the kube-proxy logs (now and when the problem occured)
```
$ kubectl -n kube-system logs kube-proxy-tfks8 | grep -i endpoint
I0315 03:48:50.499570       1 config.go:133] Starting endpoints config controller
I0315 03:48:50.499598       1 shared_informer.go:223] Waiting for caches to sync for endpoints config
I0315 03:48:50.499851       1 reflector.go:175] Starting reflector *v1.Endpoints (15m0s) from k8s.io/client-go/informers/factory.go:135
I0315 03:48:50.599778       1 shared_informer.go:230] Caches are synced for endpoints config 
$ kubectl -n kube-system logs kube-proxy-tfks8 | grep -i slice
<nothing>
```

**Comment by thockin** [comment]
@andrewsykim is working on better handling of terminating pods.  It's not clear that is happening here.

It might be worthwhile to spend some time inspecting the code and adding logs and/or metrics that might be useful to catch this in the wild...

**Comment by thockin** [comment]
This could be a fun way to learn more about kube-proxy internals for someone...

**Comment by thockin** [comment]
@aojea volunteers to help if someone picks this up

**Comment by VigneshSP94** [comment]
@thockin  @aojea I would like to pick this up. Can I get it assigned?

**Comment by aojea** [comment]
/assign @VigneshSP94 

some tips, kube-proxy expose some prometheus metrics and, when used with log lever > 4 logs much more detailed information.
I think that we should leverage that to try to solve this particular problem, and improve our logging and metrics based on this experience.

**Comment by aojea** [comment]
> For v1.18 it should default to using Endpoints, but can be changed to EndpointSlices via a feature gate.

@juliantaylor @VigneshSP94 I've just realised you are using Endpoints instead of EndpointSlices.
Since practically all new development in kube-proxy has moved to endpoint slices, I suggest to try to switch to EndpointSlices first, because if the bug only happens with Endpoints it's going to be more difficult to fix

**Comment by VigneshSP94** [comment]
@juliantaylor @thockin @aojea 

I tried to reproduce this issue -

- Spun a 6 node k8s cluster, 1 master and 5 worker.
- Created an app with LoadBalancer to expose service and set the external traffic policy to local.
- Started logging available endpoints on all worker nodes, iptables rules for this service, kube-proxy logging at level 4.
- Using haproxy as my load balancer.

Started sending traffic to this service and started rolling updates every 30 seconds.
After sometime haproxy started logging http 50x.

```
root@vignesh-kube:~# tail -f /var/log/haproxy.log | grep " 50"
Apr 20 13:17:16 vignesh-kube haproxy[835]: 192.168.56.1:52194 [20/Apr/2021:13:17:12.780] http-in webservers/worker2 0/0/4043/-1/4043 502 213 - - SH-- 4/4/3/3/1 0/0 "GET / HTTP/1.1"
```

In the above haproxy, I could see worker2 has given a 502.

In the master node, I was logging what are the endpoints available for this service in the cluster. I used the below command for this -
```
 while true; do  date +"%D.%T.%3N"; kubectl get endpoints mywebapp -o json | jq '.subsets'| jq '.[] | .addresses' | jq '.[] | .ip,.nodeName'; echo "------"; done >> avl.log
```

By the time haproxy thrown a 502, I could see the node worker2 didn't have any pods available for this service.
```
------
04/20/21.13:17:12.550
"189.0.182.31"
"worker3"
"189.0.182.42"
"worker3"
"189.0.182.51"
"worker3"
"189.0.199.183"
"worker4"
"189.0.35.27"
"worker6"
"189.0.35.8"
"worker6"
"189.0.42.85"
"worker5"
"189.0.42.98"
"worker5"
```

In the iptables rule of worker2 node, I see the below rules for the time we received a 502. It drops all the queries for the service we use for testing.

```
-----
04/20/21.13:17:12.120
Chain KUBE-XLB-KKMN4RDWQORQYJQZ (1 references)
target     prot opt source               destination
KUBE-SVC-KKMN4RDWQORQYJQZ  all  --  189.0.0.0/16         0.0.0.0/0            /* Redirect pods trying to reach external loadbalancer VIP to clusterIP */
KUBE-MARK-MASQ  all  --  0.0.0.0/0            0.0.0.0/0            /* masquerade LOCAL traffic for default/mywebapp:http LB IP */ ADDRTYPE match src-type LOCAL
KUBE-SVC-KKMN4RDWQORQYJQZ  all  --  0.0.0.0/0            0.0.0.0/0            /* route LOCAL traffic for default/mywebapp:http LB IP to service chain */ ADDRTYPE matc
h src-type LOCAL
KUBE-MARK-DROP  all  --  0.0.0.0/0            0.0.0.0/0            /* default/mywebapp:http has no local endpoints */
```

in the kube-proxy logs -
```
20T13:17:12.01588952Z"}
{"log":"I0420 13:17:12.009624       1 endpointslicecache.go:354] Setting endpoints for \"default/mywebapp:http\" to [189.0.182.31:80 189.0.182.42:80 189.0.182.51:80 189.0.189.103:80 189.0.199.183:80 189.0.35.27:80 189.0.35.8:80 189.0.42.85:80 189.0.42.98:80]\n","stream":"stderr","time":"2021-04-20T13:17:12.01590308Z"}
{"log":"I0420 13:17:12.009643       1 endpointslicecache.go:354] Setting endpoints for \"default/mywebapp:http\" to [189.0.182.31:80 189.0.182.42:80 189.0.182.51:80 189.0.199.183:80 189.0.35.27:80 189.0.35.8:80 189.0.42.85:80 189.0.42.98:80]\n","stream":"stderr","time":"2021-04-20T13:17:12.01590533Z"}
{"log":"I0420 13:17:12.009656       1 proxier.go:854] \"Syncing iptables rules\"\n","stream":"stderr","time":"2021-04-20T13:17:12.01590737Z"}
```

I could see the kube-proxy to remove a couple of endpoints and updating the iptable rules.

I've run this test for multiple times and this is the only scenario where I lose proper response from k8s. I suspect this could be the reason for you seeing errors in your environment.

We notice that you have tried capturing endpoints during the rolling redeploys, and I discussed with @aojea , its possible that your pod restarts so fast that you do not notice the change in number of available local pods. I suspect what I experience is valid, if no local pods available at a point of time, the external traffic policy is local, the iptables sets to drop traffic, in this case we are expected to see errors until your load balancer finds out that your service on a given backend server is down and mark it down by using health checks?

Can you let us know how did you capture the available endpoints and iptables rule of a node in question when this occurred?
Also, do you have any setting to make sure that kube maintains at least one pod on any given node at all time?

Thanks !

**Comment by andrewsykim** [comment]
Should be fixed from https://github.com/kubernetes/kubernetes/pull/97238 but feature gate is still alpha and off by default in v1.22
