### ISSUE TITLE
Unable to mount the specified Limit size emptydir volume(tmpfs) using medium as memory in all PODs

### ISSUE THREAD

**Issue by raghawendram** [kubernetes/kubernetes#99309]
Hi,

There is a requirement in my environment to restrict the size limit of a tmpfs mount point inside the kubernetes POD.
As per the official K8S docs, if we create the tmpfs mount using emptydir volume and medium as "Memory", by default it allocates the mount point size as 50% of the worker Node Memory.
So, to restrict the Mount point size with some Limit, need to enable the below feature gate. This option will allocate the mount point size as desired Limit.

But, After spawn the POD with the below parameters, still the TMPFS mount point has allocated with 50% of the Worker Node Memory.

Request some one could help me on this.

**Official Kubernetes EmptyDir Document Link for reference:**
https://kubernetes.io/docs/concepts/storage/volumes/#emptydir
**Feature Gate Name:** SizeMemoryBackedVolumes=true
Info in reference Link:
"Note: If the SizeMemoryBackedVolumes feature gate is enabled, you can specify a size for memory backed volumes. If no size is specified, memory backed volumes are sized to 50% of the memory on a Linux host. "

###########################################################################
**POD Manifest File:**
apiVersion: apps/v1
kind: Pod
metadata:
  name: XXXX
spec:
  serviceName: "nginx"
  replicas: 2
  selector:
    matchLabels:
      tier: XXXXXX
  template:
    metadata:
      labels:
        tier: XXXXXX
        app: XXXXX
    spec:
      containers:
      - name: nginx1
        image: docker.io/centos:latest
        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
        ports:
          - containerPort: 8443
            name: XXX-Web
        **volumeMounts:
        - mountPath: /demo
          name: demo-volume
      volumes:
      - name: demo-volume
        emptyDir:
          medium: Memory
          sizeLimit: "100M"**
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 1.2.3.4
          - 5.6.7.8
        searches:
          - abc.com
      restartPolicy: Always

###########################################################################
**Memory of the worker Node:**
[root@k8s-dualstack-2-node1 ~]# cat /proc/meminfo | grep MemTotal
MemTotal:       32780688 kB

After successful execution of the POD with above manifest file, Here is the Output of DEMO Volume size in a POD.

root@XXXXX:/# df -h /demo
Filesystem      **Size**  Used Avail Use% Mounted on
tmpfs            **16G**     0   16G   0% **/demo**

Note: Still the size of the /demo file system is 16G.

**Comment by neolit123** [comment]
this seems like a request for support.
please use:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

if you find a bug please open a new issue.
/kind support
/close
