### ISSUE TITLE
performance degradation in the scheduler 5k nodes throughput test

### ISSUE THREAD

**Issue by adtac** [kubernetes/kubernetes#99304]
#### What happened:

The scheduler throughput tests in perf-dash (see link below) show a serious, consistent 35-40% drop in performance since around 10-Feb-2021. I'm not sure what caused this. I'm going to bisect.

![Screenshot_2021-02-22 Screenshot](https://user-images.githubusercontent.com/7521600/108709448-b7f77b80-7538-11eb-9a23-b87a524a6495.png)

#### What you expected to happen:

Not drop in performance.

#### How to reproduce it (as minimally and precisely as possible):

See http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=Scheduler&metricname=SchedulingThroughput&TestName=load

/sig scheduling
cc @Huang-Wei @alculquicondor @ahg-g

**Comment by ahg-g** [comment]
The scheduling latencies graphs are not conclusive.

Things to do to help us root cause the issue:
1) run integration tests benchmarks before and after the drop in throughput.
2) compare scheduler profiles (we can find them in the artifacts of the benchmark runs) before and after the dip.

Followup fixes:
1) bind latency plugin is not showing up on the dashboard.
2) e2e scheduling latency is not showing up on the 5k dashboard, it shows up on the 100node-master though.

**Comment by Huang-Wei** [comment]
@adtac which tool (clusterloader2) generates this graph? I guess we have to understand the underlying mechanism it's collecting and workloads, and then use the lightweight way (integration test benchmark) to bisect. But be aware of some bugs I spotted recently in the integration test benchmark, like HistogramVec not supported well, initialized Pods' metric also counted into benchmark results, etc. So be aware of this.

@ahg-g I think it'd be good to come up with a doc in k/community explaining all the metrics showing in perf-dash.

**Comment by adtac** [comment]
>which tool (clusterloader2) generates this graph?

the data is generated by clusterloader2. it does not use kubemark; instead it creates 5k real VMs on GCP.

>But be aware of some bugs I spotted recently in the integration test benchmark, like HistogramVec not supported well, initialized Pods' metric also counted into benchmark results, etc. So be aware of this.

Right, but SchedulingBasic should imitate most aspects of the clusterloader2 test in this issue.

**Comment by adtac** [comment]
unfortunately git bisect on scheduler_perf wasn't useful. I'm going to run git bisect on the clusterloader test but that's going take a while.

**Comment by adtac** [comment]
commits between known good and first known bad: https://github.com/kubernetes/kubernetes/compare/7a7778941b50b8...f48972e671e5f3

**Comment by ahg-g** [comment]
Adi, can you try and just look at the profiles and compare two data points, anyone before (https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1358823239299633152/artifacts/) and anyone after (https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1363534223436156928/artifacts/).

**Comment by adtac** [comment]
@ahg-g thanks, I'll dig into that.

looping in @wojtek-t for a SIG scalability perspective. anything change in the test infra recently (~10-Feb) that might be relevant?

**Comment by adtac** [comment]
https://github.com/kubernetes/test-infra/pull/20817 enabled HUGE_SERVICES which is possibly the reason:

https://github.com/kubernetes/perf-tests/blob/e8e24c42240e9bb103bc3f75c83d9f1c42e424e7/clusterloader2/testing/load/config.yaml#L451-L462

**Comment by wojtek-t** [comment]
Yes - huge-services can definitely impact that, as those can be heavily saturating CPU on the control-plane.

That said - it's something we want to test, so I guess we can probably close that as "working as intended".
Thanks a lot for debugging this!

@jkaniuk @mborsz - for your thoughts too

**Comment by alculquicondor** [comment]
What does the workload do? Does it create a big amount of services or just a few big services?

If the former, maybe what @Huang-Wei is working on might help https://github.com/kubernetes/kubernetes/pull/98241
But it could also be related to default topology spreading, which has to identify which services relate to the pod being scheduled.

It would be nice to replicate this load test in integration performance tests.

**Comment by mborsz** [comment]
HUGE_SERVICES flag enables wrapping all scheduler throughput pods (5000?) in a single huge service. The main goal is to validate endpoints programming for such large services.

Enabling this may cause scheduling throughput regression (sending endpoints updates is quite expensive and will reduce cpu available), but I don't think anyone expected the regression to be that large.

We are discussing internally options we have.

**Comment by adtac** [comment]
thanks for looking into this.

just curious, is this going to be a temporary test?

>But it could also be related to default topology spreading, which has to identify which services relate to the pod being scheduled.

The flamegraphs of CPU profiles for known-good and known-bad executions are very similar percentage wise. Particularly, time spent in pod topology spread is around the same percentage in both cases, so I don't think it's that. IMO it looks very much like this is the case:

>sending endpoints updates is quite expensive and will reduce cpu available

**Comment by ahg-g** [comment]
This graphs confirms that the scheduler is getting lower cpu share: http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=E2E&metricname=LoadResources&PodName=kube-scheduler-gce-scale-cluster-master%2Fkube-scheduler&Resource=CPU

**Comment by jkaniuk** [comment]
> This graphs confirms that the scheduler is getting lower cpu share at the peak

I do not think that change in peak usage of scheduler affects 50% percentile regression of throughput

There is much more visible increase on controller-manager usage graph: http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=E2E&metricname=LoadResources&PodName=kube-controller-manager-gce-scale-cluster-master%2Fkube-controller-manager&Resource=CPU

However that is more recent

**Comment by adtac** [comment]
>This graphs confirms that the scheduler is getting lower cpu share at the peak

perhaps I'm repeating what @jkaniuk said, but the median CPU usage of kube-scheduler seems to be mostly the same. it's only the 90% and 99%ile lines that have dropped. I'm not sure how to interpret that.

**Comment by ahg-g** [comment]
Sure, my point is that the graph confirms the hypothesis that the test is having an effect on CPU usage.

**Comment by dims** [comment]
cc @navidshaikh

**Comment by wojtek-t** [comment]
> I do not think that change in peak usage of scheduler affects 50% percentile regression of throughput

I actually think it can.
The key point here is that those aren't exactly aligned. The resource usage is measured across the whole tests (hours), whereas the throughput for a minute or so. If the peak is exactly during that time (which actually may easily be the case), it may affect even low percentiles of the throughput.

**Comment by Huang-Wei** [comment]
Another metric to look into this issue: how long (minutes) the throughput test spent, and is it getting an increase? As from the graph, the P99 number doesn't look that worse, but the P90 and P50 do. So if the overall time spent on scheduling doesn't change much, it may be just b/c more pods are observed to be scheduled in high percentiles.

**Comment by Huang-Wei** [comment]
> [kubernetes/test-infra#20817](https://github.com/kubernetes/test-infra/pull/20817) (cc @tosi3k) enabled HUGE_SERVICES which is possibly the reason:

Thanks @adtac for spotting this. As @alculquicondor mentioned, the current scheduler code responds to Service events in an aggressive manner - it moves all unschedulable pods upon each Service event. (We're working on #98241 to help on this. But it's not finished yet.)

So after HUGE_SERVICES is enabled, **how frequent** the Service events get spawned?

**Comment by ahg-g** [comment]
@Huang-Wei based on https://github.com/kubernetes/kubernetes/issues/99304#issuecomment-785133569, it is a single service, so this shouldn't have an impact on generating many unnecessary events (unless that single service is being updated frequently, which doesn't seem to be the case).

**Comment by Huang-Wei** [comment]
> @Huang-Wei based on [#99304 (comment)](https://github.com/kubernetes/kubernetes/issues/99304#issuecomment-785133569), it is a single service, so this shouldn't have an impact on generating many unnecessary events (unless that single service is being updated frequently, which doesn't seem to be the case).

Thanks for the confirmation. If it's just one Service and it stays intact, then it won't churn the unschedulable pods.

**Comment by adtac** [comment]
/unassign
the regression still exists, but I won't have the time to work on this
