### ISSUE TITLE
Move scheduler http extender to pulgin

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#99302]
#### What would you like to be added:

For some latency scheduler extender, they also use HttpExtender to work with default scheduler; it's better to have an http-extender plugin of scheduler framework to support them.

#### Why is this needed:

Support latency scheduler extender; and make http-extender-plugin import-able by 3rd part scheduler.

**Comment by k82cn** [comment]
@kubernetes/sig-scheduling-feature-requests

**Comment by ahg-g** [comment]
We thought about this before, factoring it out as a plugin is not as straightforward as one may think, but feel free to submit a more concrete proposal.

**Comment by ahg-g** [comment]
Bind may map ok, but because we need to make a single call for all nodes, the extender filter would need to be implemented as PreScore while the prioritize will be implemented as a `NormalizeScore` of the Score extension point. It is not going to look pretty ...

**Comment by k82cn** [comment]
> but feel free to submit a more concrete proposal. 

Sure, I'll check that :)

/cc @wpeng102
