### ISSUE TITLE
Env valueFrom ServiceAccountToken

### ISSUE THREAD

**Issue by ademariag** [kubernetes/kubernetes#99311]
#### What would you like to be added:

It would be useful to allow an env to be populated with the token from [ServiceAccountTokenProjection](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#serviceaccounttokenprojection-v1-core) either directly of through ProjectedVolumeSource

Currently [EnvVarSource](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#envvarsource-v1-core) does not include a way to reference the service token 

#### Why is this needed:

My use case is around the use of ServiceAccountTokenProjection with [CloudSql Postgres IAM authentication](https://cloud.google.com/sql/docs/postgres/iam-logins). It would be great if an env variable was populated with the token to use

```
envs:
- PGPASSWORD:
  valueFrom:
    projectedVolumeSource:
      key: token 
```

**Comment by liggitt** [comment]
I would not expect projected service account tokens to support injection via envvar for the following reasons:
* envvars appear in unsecured output of the container runtime environment (e.g. `docker inspect`, `crictl inspect`)
* envvars are only set on container start, and the projected tokens are time-bound and require refreshing

cc @kubernetes/sig-auth-feature-requests @mikedanese @zshihang - thoughts?

**Comment by ademariag** [comment]
thank you @liggitt, you make very valid points, but the same applies to secrets keys: they are also "sensitive" and they are also subject to being refreshed/updated out of band.

**Comment by liggitt** [comment]
That's true, but secrets are a generic mechanism, so for secrets that are not modified, envvar injection could be reasonable. Projected service account tokens are known to be time-bound, so I would not expect to support injecting them via a mechanism that does not support that property.

It is reasonable for users to expect the API surface provided to them to not compromise the security properties of the credential injection mechanism. I regret the envvar support for secrets, and don't think we should repeat that approach with projected tokens.

**Comment by ademariag** [comment]
I fully understand your point of view, but the concerns you are raising are limited to long lived services, and would not necessarily apply for a large class of workloads with limited lifespan, much shorted than the token itself (or when the token is only needed to bootstrap the service), and for which it would make a great sense to be able to leverage the same generic approach already available for secrets. 

For instance, this mechanism could be extremely useful for jobs, init-containers and in general short lived services.

**Comment by zshihang** [comment]
storing tokens in EnvVar makes them easier to be logged/exposed. not all users are security-aware, we'd not advocate this approach by not providing the API.

**Comment by liggitt** [comment]
I've added this to the agenda for the March 3rd sig-auth meeting to see what other folks in the sig-auth community think.


> My use case is around the use of ServiceAccountTokenProjection with [CloudSql Postgres IAM authentication](https://cloud.google.com/sql/docs/postgres/iam-logins). It would be great if an env variable was populated with the token

Specifically for that use case, would setting PGPASSFILE to `/var/run/secrets/kubernetes.io/serviceaccount/token` work? Notably, the psql documentation also recommends against use of PGPASSWORD:

> PGPASSWORD behaves the same as the password connection parameter. Use of this environment variable is not recommended for security reasons, as some operating systems allow non-root users to see process environment variables via ps; instead consider using the ~/.pgpass file (see Section 31.14).

**Comment by ademariag** [comment]
hi @zshihang, I am sorry I do not understand the last sentence:
> ..we'd not advocate this approach by not providing the API.

Could you please explain what you mean? Do you also agree this feature should not be implemented?

**Comment by ademariag** [comment]
Thank you @liggitt I will try your approach as well :)

**Comment by zshihang** [comment]
yea, in my opinion we should not implement this feature. in general, it is not a good idea to sacrifice security for convenience.

**Comment by ademariag** [comment]
Thank you @zshihang and @liggitt for your opinions and for discussing this at the sig-auth meeting.

I fully understand you concerns, so much so that If you want, feel free to close now this request.

But I am still somehow puzzled by the inconsistency between this feature request and the already present `secretRefKey` support.

As @liggitt says, if sharing `secrets` through EnvVar is always to be considered a security concern, perhaps the right thing to do would be to remove support for it, or at least actively discourage its use?

On the other hand, if sharing a secret in EnvVar is an accepted practice, I think it should be up to the user to decide how to make use of the API. 

Thank you both so much for your time

**Comment by enj** [comment]
IIRC, the envvar support for secrets was added in the early days of Kube to have feature parity with platforms like Heroku.  If we had the chance to do it all over again, I think we would not support this functionality.  At the same time, we cannot go around breaking users of a stable v1 API.  Maybe something to consider if we ever attempt a v2 API.

Security considerations aside, this comment from Jordan:

> envvars are only set on container start, and the projected tokens are time-bound and require refreshing

is enough for me to say that such functionality does not make sense in the context of project tokens.

**Comment by enj** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/70679#issue-377670415

> Tokens provisioned into the new volumes are not referable in environment variables via the Downward API.

**Comment by ademariag** [comment]
Thanks, I'm not interested in this change as it turns out it wouldn't solve my use case anyway.

Will close the ticket, I agree with the points you have raised.

Thank you for looking into this
