### ISSUE TITLE
Scheduling Framework testing helpers don't preserve PluginConfig

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#99318]
/sig scheduling
/triage accepted

The method `RegisterPluginAsExtensionsWithWeight` in `pkg/scheduler/testing/framework_helpers.go` only modifies the slice of PluginConfig internally.
Instead, the method should return the appended slice so that callers can override the original. For example, here:

https://github.com/kubernetes/kubernetes/blob/5b5445c4fb8d57d5d005d2885c8b17310ffdc6a0/pkg/scheduler/testing/framework_helpers.go#L31

**Comment by ahg-g** [comment]
ref: https://github.com/kubernetes/kubernetes/pull/99288#discussion_r579892155

**Comment by MadhavJivrajani** [comment]
Hey @AliceZhang2016, are you still working on this, if not I'd like to try it out!

**Comment by AliceZhang2016** [comment]
Hi @MadhavJivrajani, I'm still working on this. Thanks for your interest about this issue.
