### ISSUE TITLE
Set up exponential backoff, retry and limits on AWS STS call in aws cloud providor

### ISSUE THREAD

**Issue by chaochn47** [kubernetes/kubernetes#99328]
When starting kube-controller-manager with `--cloud-provider=aws --cloud-config=/var/lib/kubernetes/aws.config` and the following config, any operations related to sync worker nodes, persistent volumes, elastic network interfaces in the aws account will require aws sts client to get the credentials. 

```cat /var/lib/kubernetes/aws.config
[Global]
VPC=VPC_ID
RoleArn=CUSTOMER_PROVIDED_ROLE_ARN
KubernetesClusterID=CLUSTER_NAME
```
https://github.com/kubernetes/kubernetes/blob/48a0ef6a396f84ec93a8e68d9843c6fe27c4e848/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L1174

#### What happened:
For example, if the customer account is marked as Fraud account or the trust policy of the IAM role is reclaimed, 
for each node, node_lifecycle_controller will do monitorNodes every 5s, in a HA setting it will generate 3600s /5s * 2 = 1,440 sts call volume in an hour. 

https://github.com/kubernetes/kubernetes/blob/ddf3eb5a1877338da806c2be15b53f456b6342c9/staging/src/k8s.io/cloud-provider/controllers/nodelifecycle/node_lifecycle_controller.go#L121

#### What you expected to happen:
Expect a way to protect service account from hitting AWS STS API call limit. 
Expect cloud providor to call STS evey 5s and negatively cached the "Access Denied" until 1 min later to call STS again to get the credentail. In this way, it can reduce 12x less API usage. 

#### How to reproduce it (as minimally and precisely as possible):
Revoke the trust policy of the RoleArn specified in the `/var/lib/kubernetes/aws.config`

#### Environment:
EKS

**Comment by cheftako** [comment]
Nick?

**Comment by nckturner** [comment]
Migrated to https://github.com/kubernetes/cloud-provider-aws/issues/284

/close
