### ISSUE TITLE
Push the CoreDNS 1.8.0 image in gcr.io

### ISSUE THREAD

**Issue by g1bl3t** [kubernetes/kubernetes#99321]
Attempting to pull `k8s.gcr.io/coredns:1.8.0` and I noticed the tag doesn't exist on gcr.io, yet it does on the dockerhub repo. I noticed a few issues opened in this fashion requesting the latest image be pushed to gcr.io. Could someone do the needful?

See: https://github.com/kubernetes/kubernetes/issues/88343

------

Need to push the latest CoreDNS image to gcr.io
The 1.8.0 image is available in docker coredns/coredns:1.8.0

This is the script used for pushing the image:
```
#!/bin/sh

if [ -z "$1" -o -z "$2" -o -z "$3" -o -z "$4" ]; then
    echo "usage: $0 <src-reg> <image> <tag> <dst-reg>" > /dev/stderr
    echo "example: $0 coredns coredns 1.6.7 staging-k8s.gcr.io" > /dev/stderr
    exit 1
fi

SRC_REG="$1"
IMG="$2"
TAG="$3"
DST_REG="$4"
TMP="/tmp/$RANDOM"
JSON="$TMP.json"

echo "Fetching source manifest"
docker manifest inspect ${SRC_REG}/${IMG}:${TAG} > ${JSON}

echo
echo "Pulling source images by SHA"
cat ${JSON} \
    | jq -j ".manifests[] | \"${SRC_REG}/${IMG}@\", .digest, \"\n\" " \
    | while read X; do docker pull $X; done

echo
echo "Tagging images with ARCH and OS"
cat ${JSON} \
    | jq -j ".manifests[] | \"docker tag ${SRC_REG}/${IMG}@\", .digest, \" ${DST_REG}/${IMG}:${TAG}__\", .platform.architecture, \"_\", .platform.os, \"\n\"" \
    | while read X; do $X; done

echo
echo "Pushing images"
cat ${JSON} \
    | jq -j ".manifests[] | \"gcloud docker -- push ${DST_REG}/${IMG}:${TAG}__\", .platform.architecture, \"_\", .platform.os, \"\n\"" \
    | while read X; do $X; done

echo
echo "Creating and pushing manifest"
PLATFORMS=$(cat ${JSON} | jq -j ".manifests[] | .platform.os, \"/\", .platform.architecture, \"\n\"" | paste -sd,)
echo manifest-tool push from-args \
    --platforms "${PLATFORMS}" \
    --template ${DST_REG}/${IMG}:${TAG}__ARCH_OS \
    --target ${DST_REG}/${IMG}:${TAG}
manifest-tool push from-args \
    --platforms "${PLATFORMS}" \
    --template ${DST_REG}/${IMG}:${TAG}__ARCH_OS \
    --target ${DST_REG}/${IMG}:${TAG}
```

**Comment by rajansandeep** [comment]
From v1.7.1, [the image promotion is no longer done in the legacy way](https://github.com/kubernetes/k8s.io/pull/1405#issuecomment-725631498)

v1.8.0 should be available under `k8s.gcr.io/coredns/coredns:v1.8.0`

**Comment by pacoxu** [comment]
> From v1.7.1, [the image promotion is no longer done in the legacy way](https://github.com/kubernetes/k8s.io/pull/1405#issuecomment-725631498)
> 
> v1.8.0 should be available under `k8s.gcr.io/coredns/coredns:v1.8.0`

This is fixed IMO
/close
Feel free to reopen if I am wrong.


k8s.gcr.io/coredns/coredns:v1.8.3 was promoted as well.
You can see kubernetes/k8s.io#1725 for some details about the promotion of coredns.
I opened https://github.com/kubernetes/kubernetes/issues/99751 to summarize the dns promotions.

**Comment by fanglijun** [comment]
why  `k8s.gcr.io/coredns/coredns:v1.8.0` instead of `k8s.gcr.io/coredns:v1.8.0` ? 

this is causing problem when use kubeadm to pull images with custom proxy 

see [CoreDNS image cannot be pulled when use --image-repository](https://github.com/kubernetes/kubeadm/issues/2714)
