### ISSUE TITLE
In-Tree storage plugin disk mounting does not work with Windows and containerD

### ISSUE THREAD

**Issue by marosset** [kubernetes/kubernetes#99342]
#### What happened:
When attempting to use in-tree storage plugin that mount/partition/formation disks (ex: Azure-Disk) containers creation fails on Windows nodes with something like

```bash
Error: failed to generate container "298d625236f058f6deefc1935adff04b1f203600779b7576e322c42ac6eab1a0" spec: 
failed to generate spec: failed to resolve symlink "": 
readlink c:\var\lib\kubelet\plugins\kubernetes.io\azure-disk\mounts\m3917425770: The system cannot find the path specified.
```

#### What you expected to happen:
Container creation show succeed

#### How to reproduce it (as minimally and precisely as possible):
- Create a k8s cluster with a Windows node configured to use in-tree azue disk volume plugin
- Create an azure disk PVC
- Schedule a pod that uses the azure disk PVC

#### Anything else we need to know?:
The issue is related to both how the volume mounting code provisions the disk/volume on the Windows and and also how containerD calls golang's EvalSymLink on the source path of the container volume mount.

When the volume mounting code provisions a disk it creates a new disk volume and then creates a symlink to that volume using a UNC path like `\\?\Volume{4e68c962-0000-0000-0000-100000000000}\` .

It looks like the behavior of EvalSymLinks on Windows is to look up a drive letter when it encounters a UNC path for a volume like above. If the disk volume is not assigned a letter the error `failed to resolve symlink ""` gets returned.

Manually assigning a drive letter with diskpart.exe while the Pod is stuck in a crash-loop will cause future containers to create successfully.

This scenario works on Docker because Docker does not call EvalSymLinks when setting up volume mounts for containers.

Unfortunately we cannot assign drive letters when disk volumes are created because Windows has a limitation of 26 drive letters and this would restrict the number of volumes used by containers/pods on a node.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.19, 1.20, probably 1.21
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): Windows Server 2019
- Kernel (e.g. `uname -a`): 
- Install tools:
- Network plugin and version (if this is a network-related bug): n/a
- Others:

/sig windows
/sig storage

**Comment by marosset** [comment]
cc @ravisantoshgudimetla @andyzhangx @kevpar @ddebroy @jingxu97 

This probably impacts csi-proxy and CSI plugins as well (haven't had a chance to confirm yet)

**Comment by andyzhangx** [comment]
here is the error msg returned by azure disk CSI driver on Windows containerd, looks like there is similar issue in csi-proxy:
```
event for azuredisk-volume-tester-cl9xv: {kubelet 1592k8s000} Failed: Error: failed to generate container "daf387e6d862e8d30823d9834b1b8340976da771213f490afca9b66cd20491a2" spec: failed to generate spec: failed to resolve symlink "": EvalSymlinks: too many links
```

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/702/pull-azuredisk-csi-driver-e2e-windows-containerd/1355114435349319680

**Comment by jingxu97** [comment]
I had a PR to fix eval symlink issue for subPath. They might be related. https://github.com/kubernetes/kubernetes/pull/93707

**Comment by andyzhangx** [comment]
so we need similar fix for `EvalSymLink` on Windows?

**Comment by jingxu97** [comment]
My fix is for Windows actually. There is also some discussion related EvalSymLink issue in Windows in golang https://github.com/golang/go/issues/40180

**Comment by andyzhangx** [comment]
> I had a PR to fix eval symlink issue for subPath. They might be related. #93707

@jingxu97 so if I replace `EvalSymLinks` func with Windows version, it would work for in-tree disk driver?

https://github.com/kubernetes/kubernetes/blob/b538d230661ff12577a720713cae9c06645d609e/staging/src/k8s.io/mount-utils/mount.go#L200
https://github.com/kubernetes/kubernetes/blob/b538d230661ff12577a720713cae9c06645d609e/staging/src/k8s.io/mount-utils/mount.go#L247

**Comment by jingxu97** [comment]
I hope so. But I am surprised that this issue was not discovered before. This mount util should be used by many storage including gce pd? Why I only see the issue in subPath..

**Comment by andyzhangx** [comment]
I think we need to fix it in containerd, not in k8s:
```
Mar 17 10:49:12.144: INFO: At 2021-03-17 10:39:03 +0000 UTC - event for azuredisk-volume-tester-fxxt9: {kubelet 9195k8s000} Failed: Error: failed to generate container "a23d0dd87d60ff1da680cbd51e70d89b0cb27e7a97c58160069e57ff049a58aa" spec: failed to generate spec: failed to resolve symlink "": readlink c:\var\lib\kubelet\plugins\kubernetes.io\azure-disk\mounts\m2286602339: The system cannot find the path specified.
```

**Comment by andyzhangx** [comment]
actually azure file driver(smb protocol) does not work on Windows containerd either, 
just type `/test pull-kubernetes-e2e-aks-engine-azure-file-windows-containerd` in k/k PR, you will get test failures:

```
Apr 16 13:14:24.256: INFO: At 2021-04-16 13:09:39 +0000 UTC - event for azurefile-volume-tester-97zvr-7fdc84d8fd-c68gb: {kubelet 2710k8s000} Failed: Error: failed to create containerd task: hcsshim::CreateComputeSystem volume-tester: The directory name is invalid.
(extra info: {"Owner":"containerd-shim-runhcs-v1.exe","SchemaVersion":{"Major":2,"Minor":1},"Container":{"GuestOs":{"HostName":"azurefile-volume-tester-97zvr-7fdc84d8fd-c68gb"},"Storage":{"Layers":[{"Id":"0d9d58e6-47b6-5091-a552-7cc2027ca06f","Path":"C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\14"},{"Id":"6715ca06-295b-5fba-9224-795ca5af71b9","Path":"C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\13"},{"Id":"75e64a3b-69a5-52cf-b39f-ee05718eb1e2","Path":"C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\12"},{"Id":"8698c4b4-b092-57c6-b1eb-0a7ca14fcf4e","Path":"C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\11"},{"Id":"7c9a6fb7-2ca8-5ef7-bbfe-cabbff23cfa4","Path":"C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\10"},{"Id":"a10d4ad8-f2b1-5fd6-993f-7aa642762865","Path":"C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\9"},{"Id":"f2f3e63e-ba3b-5e5d-a46d-4c1b86766dc6","Path":"C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\8"},{"Id":"dc6e4d16-f2d3-50b0-84ad-b520078bac65","Path":"C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\7"},{"Id":"bbb3b587-52e4-534d-b0e8-708d7ad7f642","Path":"C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\6"},{"Id":"72acf0d2-9a33-5e03-b759-c5255b23480c","Path":"C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\5"}],"Path":"\\\\?\\Volume{94440617-baa9-4353-8170-1729218c0ac1}\\"},"MappedDirectories":[{"HostPath":"\\\\f436eb460d54642e8b1f39e.file.core.windows.net\\kubetest-7qglpj9c-dyna-pvc-2794ed95-604f-47c0-8318-3398ac45279e\\","ContainerPath":"c:\\mnt\\test-1"},{"HostPath":"c:\\var\\lib\\kubelet\\pods\\faf7d2af-9d5a-4d3b-9d45-742c97889b40\\containers\\volume-tester\\ad20a5fd","ContainerPath":"c:\\dev\\termination-log"},{"HostPath":"c:\\var\\lib\\kubelet\\pods\\faf7d2af-9d5a-4d3b-9d45-742c97889b40\\volumes\\kubernetes.io~projected\\kube-api-access-hpwbr","ContainerPath":"c:\\var\\run\\secrets\\kubernetes.io\\serviceaccount","ReadOnly":true},{"HostPath":"c:\\var\\lib\\kubelet\\pods\\faf7d2af-9d5a-4d3b-9d45-742c97889b40\\etc-hosts","ContainerPath":"C:\\Windows\\System32\\drivers\\etc\\hosts"}],"Networking":{"Namespace":"fd16ace8-0cc1-4f56-879c-2b4684e42dcd"}},"ShouldTerminateOnLastHandleClosed":true}): unknown
```


https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/100297/pull-kubernetes-e2e-aks-engine-azure-file-windows-containerd/1383035484594245632

**Comment by marosset** [comment]
Azure file was working w/ containerd on Windows at some point :(

Looks like azure disk w/ dockershim on Windows is also failing tests regularly too
https://testgrid.k8s.io/sig-windows-presubmit#pull-kubernetes-e2e-aks-engine-azure-disk-windows-dockershim

**Comment by andyzhangx** [comment]
the containerd issue has been fixed by https://acs-mirror.azureedge.net/containerd/windows/v0.0.41/binaries/containerd-v0.0.41-windows-amd64.tar.gz

**Comment by andyzhangx** [comment]
containerd windows tests pass for in-tree azure disk & file drivers now:
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-aks-engine-azure-file-windows-containerd
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-aks-engine-azure-disk-windows-containerd

Will run a few days, enable it by default if it's stable enough

**Comment by andyzhangx** [comment]
special thanks to @kevpar for the containerd fix, really appreciate that!
