### ISSUE TITLE
Helm3 Error: constructing many client instances from the same exec auth

### ISSUE THREAD

**Issue by danielo-directeam** [kubernetes/kubernetes#99353]
Hi,

After upgrading my Helm from V2 to V3 (using the latest both plugin and Helm versions) I faced this issue:
When I execute the command "helm3 upgrade prod prod/ -f prod/values.yaml -n prod" I see warnings appear:
W0211 14:37:45.549273    2095 exec.go:271] constructing many client instances from the same exec auth config can cause performance problems during cert rotation and can exhaust available network connections; 1010 clients constructed calling "aws"

The chart seems to be working but I am not familiar with this error means I can not deploy that to prod.
Neither AWS support nor looking on the internet led me to find a solution for that issue.

Has someone faced with that?

Thanks in advanced 

/sig helm
/triage accepted

**Comment by pacoxu** [comment]
no helm sig here😅

you may open an issue in https://github.com/helm/helm/issues

/close

feel free to reopen if it is a kubernetes bug.
