### ISSUE TITLE
xpu-plugin

### ISSUE THREAD

**Issue by ProgramerGu** [kubernetes/kubernetes#99359]
Is this a BUG REPORT or FEATURE REQUEST?:

/kind feature

What happened:
Kubernetes has supported a variety of heterogeneous device management plugins, such as GPU plugin and GPU share. This issuse mainly focuses on the Kunlun chip device XPU developed by Baidu company
What you expected to happen:
A new device-plugin for xpu
How to reproduce it (as minimally and precisely as possible):
XPU Device-plugin deploy by DaemonSet
Anything else we need to know?:
Need Baidu self research drive support
Environment:

Volcano Version:to add
Kubernetes version (use kubectl version):1.10+
Cloud provider or hardware configuration:baidu-xpu
OS (e.g. from /etc/os-release):centos:7 and ubuntu:16.04
Kernel (e.g. uname -a):4.15.0-72-generic
Install tools:insmod ubuntu_1804_xpu_driver.ko
Others:

**Comment by pacoxu** [comment]
/sig node
https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#examples
here are some examples.

**Comment by SergeyKanzhelev** [comment]
@ProgramerGu is this a request to develop the plugin for this device? Device plugins are not hosted in this repository. This issue looks like a support request. Kubernetes does not use issues on this repo for support requests. For this question you may visit our [forums](https://discuss.kubernetes.io/). Or try to get support [from Baidu](https://intl.cloud.baidu.com/doc/CCE/s/Uk0dm2q76-en#:~:text=supports%20the%20use%20of%20kunlun%20cloud%20server%20(baidu%20self-developed%20xpu%20chip%20)%20to%20create%20clusters) directly

/remove-kind bug
/kind support
/close
