### ISSUE TITLE
Pod Evicting When Hugepages Are Used and Resources Are Insufficient

### ISSUE THREAD

**Issue by zhangle-dev** [kubernetes/kubernetes#99356]
I have a question. When I looked at the source code related to pod eviction, I found that when available < threshold, the eviction action was triggered. available = capacity-workingset. When hugepage is configured in the system, if available contains hugepage, will the remaining memory be insufficient and cannot be evicted?

**Comment by ehashman** [comment]
Kubernetes does not use issues on this repo for support requests. If you have a question on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/).

/close
