### ISSUE TITLE
Windows cross-build image in Pause is a hosted on docker hub image causing builds to fail

### ISSUE THREAD

**Issue by perithompson** [kubernetes/kubernetes#99360]
#### What happened:
When including windows in a pause build I get a rate limit error as it tries to pull dockcross/windows-static-x64:latest. This causes the build to fail.  
```+ make container
mkdir -p bin
docker run --rm -u $(id -u):$(id -g) -v $(pwd):/build \
dockcross/windows-static-x64:latest \
/bin/bash -c "\
cd /build && \
86_64-w64-mingw32.static-gcc -Os -Wall -Werror -static -DVERSION=v3.2-b8911046376 -o bin/pause-windows-amd64 windows/pause.c && \
x86_64-w64-mingw32.static-strip  bin/pause-windows-amd64.exe"
Unable to find image 'dockcross/windows-static-x64:latest' locally
 docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
```

#### What you expected to happen:
This image should be stored and pulled from k8s.gcr.io/build-image as there should be a copy of this in k8s.gcr.io/build-image to mimic kube-cross for Linux images

#### How to reproduce it (as minimally and precisely as possible):
cd build/pause 
make all-push

#### Environment:
- Kubernetes version : v1.20.1
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): Build running on Linux (includes cross compiling for windows)
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by perithompson** [comment]
@dims @claudiubelu Are you either of you able help with getting this image into the k8s gcr or if there is a reason why it can't be put there??

**Comment by jayunit100** [comment]
context - this might be due to use pulling from a small # of  vmware internal IPs

**Comment by jayunit100** [comment]
goal from sig-windows ~ move this into GCR eventually ~ @BenTheElder would that be ok ?

**Comment by jsturtevant** [comment]
@claudiubelu do you know any history for this image?

**Comment by claudiubelu** [comment]
> 
> 
> @claudiubelu do you know any history for this image?

That image carried over from the original work from @benmoss . I have asked sig-testing previously if we could include that image's functionality into ``gcb-gcloud-docker`` image, but I think a better fit for that image would be ``kube-cross``, since that image is actually intended for cross-compiling applications in the first place (from a quick look, I didn't find any Windows-related gcc options in the current image). We could add the same functionality by installing ``mingw-w64`` into the image.

I can try this out in the morning, and if it works, I can send some PRs.

**Comment by claudiubelu** [comment]
Seems to work. I have sent 2 PRs for this:

https://github.com/kubernetes/release/pull/1978
https://github.com/kubernetes/kubernetes/pull/100592
