### ISSUE TITLE
github.com/golang/protobuf/protoc-gen-go/generator" is deprecated

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#99384]
We should probably move off of this.

```
WARNING: Package "github.com/golang/protobuf/protoc-gen-go/generator" is deprecated.
	A future release of golang/protobuf will delete this package,
	which has long been excluded from the compatibility promise.
```

EDIT: warning logged when running `make test`

Taking a guess at the SIG

**Comment by liggitt** [comment]
cc @sttts @smarterclayton

**Comment by fedebongio** [comment]
cc @lavalamp @yliaog 
Didn't we discuss this one (or related) in a past API Machinery meeting? 
/triage accepted

**Comment by lavalamp** [comment]
@ptabor

**Comment by liggitt** [comment]
removed in https://github.com/kubernetes/kubernetes/pull/100488
