### ISSUE TITLE
Many error logs in kube-controller-manager about storing status for daemon set

### ISSUE THREAD

**Issue by tnqn** [kubernetes/kubernetes#99397]
#### What happened:
Almost every update to a DaemonSet can lead to 2~3 error logs in kube-controller-manager even when the DaemonSet manages very few Pods, for example, there were 3 error logs when updating a daemonset in a small cluster of 2 Nodes.
```
E0224 11:45:58.101426       1 daemon_controller.go:320] kube-system/antrea-agent failed with : error storing status for daemon set &v1.DaemonSet{...} :Operation cannot be fulfilled on daemonsets.apps "antrea-agent": the object has been modified; please apply your changes to the latest version and try again
E0224 11:46:43.871336       1 daemon_controller.go:320] kube-system/antrea-agent failed with : error storing status for daemon set &v1.DaemonSet{...} :Operation cannot be fulfilled on daemonsets.apps "antrea-agent": the object has been modified; please apply your changes to the latest version and try again
E0224 11:46:43.906964       1 daemon_controller.go:320] kube-system/antrea-agent failed with : error storing status for daemon set &v1.DaemonSet{...} :Operation cannot be fulfilled on daemonsets.apps "antrea-agent": the object has been modified; please apply your changes to the latest version and try again
```
Other controllers like deployment don't have this issue when they manage much more Pods.

After looking at DaemonSet controller code, it seems the retry logic in "storeDaemonSetStatus" was not implemented correctly. It never really retried and always made an useless GET call.
https://github.com/kubernetes/kubernetes/blob/4cc1127e9251fff364d5c77e2a9a9c3ad42383ab/pkg/controller/daemon/daemon_controller.go#L1043-L1065

#### What you expected to happen:
DaemonSet controller should produce less error logs in normal case.

#### How to reproduce it (as minimally and precisely as possible):
Create or update a DaemonSet to trigger Pod recreation.

#### Environment:
- Kubernetes version (use `kubectl version`): v1.20.4
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by cmssczy** [comment]
Same problem with me. https://github.com/kubernetes/kubernetes/issues/101362#issuecomment-827345106
> Other controllers like deployment don't have this issue when they manage much more Pods.

Could you explain why other controllers is **not** easy to get conflict when updating status?  I think there are many `worker` in every controller.
https://github.com/kubernetes/kubernetes/blob/5663875648cea3b7da1870181c59ed5b99bcc270/pkg/controller/daemon/daemon_controller.go#L291-L293

**Comment by tnqn** [comment]
@cmssczy the number of workers doesn't matter here as the workqueue guarantees that they will not process the same resource at the same time. The conflict comes from multiple successive processing of a resource because of the update delay of the resource's cache in `Lister`. For example, when a DaemonSet manages 2 Pods and they are getting ready.
1. the first Pod is ready and triggers updating Daemonset, whose resourceVersion is 10000 in Lister.
2. worker updates DaemonSet's ready count to 1 with resourceVersion set to 10000 and it succeeds. The resourceVersion in server becomes 10100 and the Informer/Lister hasn't received the update.
3. the second Pod is ready and triggers updating Daemonset, whose resourceVersion is still 10000 in Lister.
4. worker updates DaemonSet's ready count to 2 with resourceVersion set to 10000 and it fails with the "the object has been modified" error.

To avoid this error, retry is the most straightforward way but it is implemented differently in controllers. In deployment controller, it actually has the same conflict but it only logs the error with `klog.V(2)` so normally you don't see it, and it requeues the resource and re-processes it upon conflict. https://github.com/kubernetes/kubernetes/blob/cb303e613a121a29364f75cc67d3d580833a7479/pkg/controller/deployment/deployment_controller.go#L489-L493
DaemonSet controller and Replicaset controller retry directly when calling `UpdateStatus` fails. However, the former made a mistake when checking the loop's boundary condition and it never retried. #99398 is fixing it.

**Comment by cmssczy** [comment]
Very clear explanation. Thanks.
