### ISSUE TITLE
Users with list secrets permission can get the value of the secret

### ISSUE THREAD

**Issue by raulbarreto-delivion** [kubernetes/kubernetes#99405]
#### What happened:

If a user, that only has the permission to list secrets, execute the following command:

kubectl get secrets -o yaml

It will be able to get the value of the secrets

#### What you expected to happen:

Do not show the value of the secrets.

#### How to reproduce it (as minimally and precisely as possible):

Create a role with the permissions:

rule {
    api_groups = [""]
    resources  = ["secrets"]
    verbs      = ["list", "delete"]
}

And using this role, execute the command kubectl get secrets -o yaml

#### Environment:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-eks-ad4801", GitCommit:"ad4801fd44fe0f125c8d13f1b1d4827e8884476d", GitTreeState:"clean", BuildDate:"2020-10-20T23:27:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: AWS/EKS
- OS (e.g: `cat /etc/os-release`): MacOS
- Kernel (e.g. `uname -a`):
Darwin MacBook-Pro 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
viewing an object by listing it is by design.
leaving the ticket if sig api-machinery / sig auth wish to comment.

/sig api-machinery auth
/remove-kind bug
/kind support

**Comment by liggitt** [comment]
correct, list requests include the full object content

https://kubernetes.io/docs/reference/access-authn-authz/authorization/#determine-the-request-verb

> GET, HEAD | get (for individual resources), list (for collections, including full object content), watch (for watching an individual resource or collection of resources)

See also https://github.com/kubernetes/website/issues/14872 and https://github.com/kubernetes/dashboard/issues/4139#issuecomment-517094869
