### ISSUE TITLE
Add hint/suggestion in "kubectl get" command

### ISSUE THREAD

**Issue by m14815** [kubernetes/kubernetes#99432]
#### What would you like to be added:
Add hint or notification while using cmd line "kubetctl get resource"
#### Why is this needed:
Sometimes, users have some many instances under a kind of resource, such as lots of pods, and the user wants to get a detail of a pod, but the user forgets the namespace of the pod, while user use a command with wrong namespace, such as "kubetctl get pod -n namespace podname -oyaml", the user cannot get expected result, if the "kubectl get" command can give a suggestion about correct namespce, the user can save some steps to get expected result.

**Comment by eddiezane** [comment]
This is a reasonable request but not feasible to implement at this time.

[Cobra](https://github.com/spf13/cobra/) implements this for commands but to implement this for your cluster we'd need to make a bunch of requests to build a dictionary to check against.

/close
