### ISSUE TITLE
[Flake][sig-node] Pods should run through the lifecycle of Pods and PodStatus

### ISSUE THREAD

**Issue by robscott** [kubernetes/kubernetes#99437]
#### Which jobs are flaking:
- ci-kubernetes-kind-e2e-parallel
- ci-kubernetes-e2enode-ubuntu2-k8sstable1-gkespec

#### Which test(s) are flaking:
Pods should run through the lifecycle of Pods and PodStatus

#### Testgrid link:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/99345/pull-kubernetes-e2e-kind/1364771671973564416

#### Reason for failure:
>failed to see Pod pod-test in namespace

#### Anything else we need to know:
- Triage: https://storage.googleapis.com/k8s-gubernator/triage/index.html?text=failed%20to%20see%20Pod%20pod-test%20in%20namespace&test=Pods%20should%20run%20through%20the%20lifecycle%20of%20Pods%20and%20PodStatus

/sig node

**Comment by matthyx** [comment]
I cannot reproduce (despite trying hard!) on my PC...

I wonder if that flake wasn't greatly improved by:
https://github.com/kubernetes/kubernetes/pull/101931

Now it looks like it fails rarely:
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=Pods%20should%20run%20through%20the%20lifecycle%20of%20Pods%20and%20PodStatus

**Comment by ehashman** [comment]
/remove-kind flake
/kind failing-test

Appears to only be failing on the node-kubelet-orphans job: https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-orphans

/priority important-soon
/remove-priority important-longterm

Next steps: check Prow config for this job, doesn't appear to be failing on any other jobs.

**Comment by matthyx** [comment]
Now let's wait 12h to have the next run of kubelet-orphans
/reopen

**Comment by ehashman** [comment]
/assign @cynepco3hahue 
/unassign @matthyx 

MemoryManager tests probably shouldn't be running on these jobs, if we adjust the job configs this should fix the failures.

**Comment by cynepco3hahue** [comment]
@ehashman I updated the orphans job config to exclude `[Feature:.+]` - https://github.com/kubernetes/test-infra/pull/22902

**Comment by SergeyKanzhelev** [comment]
update: @cynepco3hahue will keep looking into it

**Comment by cynepco3hahue** [comment]
I think we can close it now, the orphans job is looking green now.
https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-orphans

**Comment by cynepco3hahue** [comment]
Feel free to re-open if you will encounter issues with the reported test under a different job.
