### ISSUE TITLE
kubelet thinks number of NUMA nodes and sockets are same 

### ISSUE THREAD

**Issue by hanamantagoudvk** [kubernetes/kubernetes#99457]
#### What happened:

There was a difference in the meaning of MachineInfo.Topology between k8s and cAdvisor.

k8s version 1.18.9, cAdvisor version 0.35.0: both think that Topology represents sockets.

k8s version 1.19.3, cAdvisor version 0.37.0: k8s still thinks that Topology represents sockets, cAdvisor now returning NUMA Nodes

k8s version 1.20.0+, cAdvisor 0.37.0+: now both thinks that Topology represents NUMA Nodes. 
( thanks to that commit, https://github.com/kubernetes/kubernetes/pull/90980/commits/a047e8aa1b705bb7e5be881fb63cf90a218b60d0 )

Corresponding cadvisor uplift issue in k8s is : https://github.com/kubernetes/kubernetes/issues/98870

But still on 1.20+ and master , kubelet while determining CPUToplogy , still has a code at one place where it thinks number of sockets is same as number of NUMA nodes 

NumSockets = len(machineInfo.Topology)

#### What you expected to happen:

It needs to be modified to 

NumSockets = machineInfo.NumSockets

**Comment by tech-geek29** [comment]
This bug appears to have been addressed now that #99464 &  #99493 have merged.

/close
