### ISSUE TITLE
Is there a plan to support RedHat 8.2

### ISSUE THREAD

**Issue by andy-wolf168** [kubernetes/kubernetes#99459]
#### Why is this needed:
RHEL 6 is going EOL 11/30/2020 and RHEL 7 going EOL 6/30/2024.
https://access.redhat.com/discussions/2399461

**Comment by neolit123** [comment]
hi, this is not really a topic for the Kubernetes issue tracker.
from what i've seen 8.x just works, but i haven't tried it myself.

also Kubernetes itself doesn't claim support for a matrix of Linux distributions.

you can talk to other users about this on the support forums:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
/kind support
