### ISSUE TITLE
Improve Configurability of Generated Firewall Rules to Load Balancer Services

### ISSUE THREAD

**Issue by DeanBrunt** [kubernetes/kubernetes#99451]
#### What would you like to be added:
Ability to better configure the firewall rules generated by load balancer services in GKE (specifically for internal load balancers) such that stronger senses of identity can be used (i.e: source service account) for the firewall restrictions.
Likely through the use of annotations.

#### Why is this needed:
At Ziglu we run a number of Kubernetes cluster on GKE that are not available publicly, instead being accessed for their use cases by internal only networking in GCE.

In all of these cases, our traffic comes from sources with clearly defined service account identities.
Unfortunately, as we can't express this to the Kubernetes load balancer service, we either have to:
- Manually create firewall rules with the stricter service account based sources
    - This is not totally foolproof as the controller will still create a (potentially) wider IP based rule in addition to this or,
    - In the case of XPN usage, will spew lots of `DENY` GCE firewall change events as well as raising manual Kubernetes events indicating required changes (even though valid rules exist, it's of course unable to assert that these pertain to what it requires)
- Relent and use IP based sources for the firewall rules which we can express to the controller via the load balancer service.

It would be great if a feature was added to allow us to indicate to the controller to either:
- Set up the firewall rules with service account sources we specify (likely via annotation)
- Not bother creating firewall rules and assume the operator is getting valid ones in place via some other means so not to bother duplicating effort.

**Comment by thockin** [comment]
Assigning to Minhan, but @bowei for viz.

Should this request move to a Google-specific CCM repo now?

**Comment by freehan** [comment]
Thank you very much for the write up.  We have similar feature request on the roadmap. We will evaluate and come back. 

+1 to move this into Google CCM repo. 

@skmatti

**Comment by cheftako** [comment]
https://github.com/kubernetes/cloud-provider-gcp/tree/master/cmd/cloud-controller-manager for reference

**Comment by thockin** [comment]
@skmatti and @freehan - did we move this ?

**Comment by cheftako** [comment]
/assign 
Look to move to cloud-provider-gcp

**Comment by DeanBrunt** [comment]
/reopen

This is still an issue as far as I can see and I don't think this got moved to the cloud provider issue log.

**Comment by thockin** [comment]
This is more of a GCE cloud-provider feature request than k8s proper.

An annotation along the lines of "don't manage firewall" should be easy - then you can manage firewall yourself.  Is that sufficient?

Making an annotation that is more configurable (e.g. "don't do source ranges, but source tags or source SA's) is much more complex.
