### ISSUE TITLE
Kuberenetes Endpoints becoming unreachable

### ISSUE THREAD

**Issue by naresh-makhija** [kubernetes/kubernetes#99466]
In our K8 cluster, We are facing very tricky issue wherein applications endpoints becomes unreachable which is seen from kg endpoints. Also same gets reflected in iptables -L where these application endpoints reports unreachable.
Simultaneously we see high load on the server when this is happening. We are trying to identify what is causing heavy load on the cluster. Till now we haven't got anything concreate from logs to point to faulty component.

Environment details :
1) Single Node K8 1.16.1 cluster (kubelet version 1.16.3)
2) CPU 8 core
3) Memory 32GB

[root@XXXXXX storage]# kg endpoints
NAMESPACE          NAME                                                             ENDPOINTS                                                             AGE
redis              redis                                                                                                                                  343d
ssl                self-service-lite                                                                                                                      203d
topology           topology-gal                                                                                                                           343d
topology           topology-service                                                                                                                       343d

iptables -L (output)

Chain KUBE-SERVICES (3 references)
target     prot opt source               destination
REJECT     tcp  --  anywhere             10.106.93.160        /* redis/redis:tcp has no endpoints */ tcp dpt:6379 reject-with icmp-port-unreachable
REJECT     tcp  --  anywhere             10.108.76.233        /* ssl/self-service-lite:https has no endpoints */ tcp dpt:https reject-with icmp-port-unreachable
REJECT     tcp  --  anywhere             10.100.52.8          /* topology/topology-gal:http has no endpoints */ tcp dpt:10204 reject-with icmp-port-unreachable
REJECT     tcp  --  anywhere             10.101.26.230        /* jaeger/jaeger-jaeger-operator-metrics:cr-metrics has no endpoints */ tcp dpt:sun-as-jmxrmi reject-with icmp-port-unreachable
REJECT     tcp  --  anywhere             10.108.76.233        /* ssl/self-service-lite:http has no endpoints */ tcp dpt:http reject-with icmp-port-unreachable
REJECT     tcp  --  anywhere             10.108.14.43         /* topology/topology-service:http has no endpoints */ tcp dpt:10203 reject-with icmp-port-unreachable
REJECT     tcp  --  anywhere             10.110.198.18        /* olm/operatorhubio-catalog:grpc has no endpoints */ tcp dpt:50051 reject-with icmp-port-unreachable
REJECT     tcp  --  anywhere             10.101.26.230        /* jaeger/jaeger-jaeger-operator-metrics:metrics has no endpoints */ tcp dpt:m2mservices reject-with icmp-port-unreachable

**Comment by aojea** [comment]
This, most probabl, is caused because the pods are not ready, and kube-proxy will insert reject rules to the services
You have to check your pod status
/kind support

**Comment by ehashman** [comment]
Kubernetes does not use issues on this repo for support requests. If you have a question on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/).

/close
