### ISSUE TITLE
hack/update-vendor.sh can exit with error code 1 and no indication of failure

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#99461]
#### What happened:

Seen while running on https://github.com/kubernetes/kubernetes/pull/98572

```
$ hack/update-vendor.sh 
+++ [0225 09:14:27] logfile at /tmp/update-vendor.rLjX/update-vendor.log
+++ [0225 09:14:27] go.mod: update staging references
$ echo $?
1
$ tail /tmp/update-vendor.rLjX/update-vendor.log
warning: ignoring symlink /Users/liggitt/go/src/k8s.io/kubernetes/cluster/gce/ubuntu
warning: ignoring symlink /Users/liggitt/go/src/k8s.io/kubernetes/third_party/etcd
go: finding module for package google.golang.org/grpc/naming
k8s.io/kubernetes/pkg/registry/registrytest imports
	k8s.io/apiserver/pkg/storage/etcd3/testing imports
	go.etcd.io/etcd/integration imports
	go.etcd.io/etcd/proxy/grpcproxy imports
	google.golang.org/grpc/naming: module google.golang.org/grpc@latest found (v1.36.0, replaced by google.golang.org/grpc@v1.31.0), but does not contain package google.golang.org/grpc/naming
```

#### What you expected to happen:

If hack/update-vendor.sh fails, the output should make it clear

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/area code-organization
/sig architecture
/cc @justaugustus 
/assign

**Comment by SataQiu** [comment]
Maybe we can add a `trap` to check the exit code.
```sh
--- a/hack/update-vendor.sh
+++ b/hack/update-vendor.sh
 LOG_FILE="${LOG_FILE:-${TMP_DIR}/update-vendor.log}"
 kube::log::status "logfile at ${LOG_FILE}"
 
+trap '[[ $? -eq 0 ]] || echo "An error has occurred. Please see more details in ${LOG_FILE}"' EXIT

 if [ -z "${BASH_XTRACEFD:-}" ]; then
   exec 19> "${LOG_FILE}"
   export BASH_XTRACEFD="19"
```

**Comment by liggitt** [comment]
something like that seems like a good idea

**Comment by BenTheElder** [comment]
usually when we want to do stuff like that we instead record the exit code for specific steps with something like `command || ret=$?` so we can check after and inform the user of the specific failure (and suggest what to do), then `exit $ret`
