### ISSUE TITLE
Serialization Test Failure Output Completely Unreadable

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/kubernetes#9946]
TestDeepCopyApiObjects: This test outputs ~14k lines of failure dumps and is absolutely impossible to do anything with - the output should be throttled or optional.

**Comment by stevekuznetsov** [comment]
TestRoundTripTypes has similar output

**Comment by stevekuznetsov** [comment]
Perhaps only the diffs of the objects in question can be dumped instead of the raw JSON for the entire object?

**Comment by pmorie** [comment]
@stevekuznetsov I noticed that the equivalent test in origin has been made a little more readable.  I have made some improvements recently debugging this test, but I would like to get the side-by-side diff that origin has in.  Perhaps if you have some bandwidth you can work on this?

**Comment by stevekuznetsov** [comment]
@pmorie I'll take a look

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is important.  I improved some of this.
