### ISSUE TITLE
how to make the self defined controllers watching mutually exclusive

### ISSUE THREAD

**Issue by 2339478391** [kubernetes/kubernetes#99489]
#### What would you like to be added:

two scenes

all the controllers watching the same resource
when the resource changes
all the controllers will get the event

all the controllers watching the same resource
when the resource changes
one of the controllers per "group" will get the event

#### Why is this needed:

two controller are mutual backups, both are working, that's a cluster
one fail down or restart, another is still working
when the resource changes
only one of two controller is needed to work for the change

**Comment by neolit123** [comment]
hi, this seems like a request for support on custom controllers.
you can try asking in #kubernetes-users on k8s slack or the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
