### ISSUE TITLE
pod with hugepage can not write if kubelet start earlier than node hugepage ready

### ISSUE THREAD

**Issue by smileusd** [kubernetes/kubernetes#99483]
/sig node

#### What happened:
pod with hugepage could not work when node restart.
need restart kubelet to fix this issues.

#### How to reproduce it (as minimally and precisely as possible):
```
1. start kubelet with enable hugepage
2. echo xxxx > /proc/sys/vm/nr_hugepages
3. create pod with emptydir with hugepage
4. pod running but can not mmap write 
root@spdk-pod-test8:~# ./hugepage
Returned address is 0x7f6f7a200000
Bus error (core dumped)
5. restart kubelet. mmap write works
root@spdk-pod-test8:~# ./hugepage
Returned address is 0x7ff3a8a00000
First hex is 0
First hex is 3020100
```
hugepage C program: https://github.com/torvalds/linux/blob/master/tools/testing/selftests/vm/hugepage-mmap.c
#### Environment:
- Kubernetes version (use `kubectl version`):
k8s 1.18
- OS (e.g: `cat /etc/os-release`): 
Centos 8
- Kernel (e.g. `uname -a`):  
Linux tess-node-bffrk-tess86.stratus.rno.ebay.com 5.4.0-34.generic.x86_64 #1 SMP Wed Jul 1 21:44:10 -07 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pacoxu** [comment]
/remove-lifecycle stale
/triage accepted

Something similar that I know is #99305 that is for ephemeral storage. (cadvisor is not ready but kubelet started)

**Comment by smileusd** [comment]
@pacoxu @bunniseng Does any update for this? I think it is not only cadvisor not ready in kubelet, because the real space in container also not ready. Maybe need some policies to find whether hugepage has been allocated finished and reflect to kubelet and scheduler.

**Comment by cynepco3hahue** [comment]
@smileusd IIUC correctly we just mount hugepages under the relevant container, so the container already should start with configured hugepages under it.
Also, some reproduce steps are not clear for me
```
1. start kubelet with enable hugepage
2. echo xxxx > /proc/sys/vm/nr_hugepages
```
What do you mean by `start kubelet with enable hugepage`?
`echo xxxx > /proc/sys/vm/nr_hugepages`, once you updated a number of hugepages under the node, you should restart the kubelet, it is similar to CPU and memory resources.

Can you please provide the pod spec and also the output of node describe command where the pod is running?
