### ISSUE TITLE
CronJob unit tests are flaky

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#99505]
#### Which jobs are flaking:
pull-kubernetes-unit 

#### Which test(s) are flaking:
k8s.io/kubernetes/pkg/controller/cronjob: TestController2_updateCronJob/spec.schedule_changed 
k8s.io/kubernetes/pkg/controller/cronjob: TestController2_updateCronJob 

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/98582/pull-kubernetes-unit/1365354170114117632

/sig apps
/assign @soltysh

**Comment by liggitt** [comment]
This is important to resolve before promotion to v1

**Comment by liggitt** [comment]
looks like the cause was https://github.com/kubernetes/kubernetes/pull/97098

**Comment by gavinfish** [comment]
This function should be related.
https://github.com/kubernetes/kubernetes/blob/c410910c1f3d17c1f35a1c1d59a59d167ddf8935/pkg/controller/cronjob/cronjob_controllerv2.go#L607-L615

**Comment by ahg-g** [comment]
Another one: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/99163/pull-kubernetes-unit/1366558208847515648

**Comment by pacoxu** [comment]
When the flake happen, there are messages like

> E0301 13:05:15.008917   49566 cronjob_controller.go:270] Cannot determine if snazzycats/mycronjob needs to be started: too many missed start time (> 100). Set or decrease .spec.startingDeadlineSeconds or check clock skew

https://github.com/kubernetes/kubernetes/blob/c198632a12971efa55f9d659bcc9f59b79651edc/pkg/controller/cronjob/utils.go#L128-L148

When the system is overloaded, it would happen.

https://github.com/kubernetes/kubernetes/pull/99553#pullrequestreview-601130026
@soltysh is trying to replace the current queue in tests with a mock.

**Comment by soltysh** [comment]
Yeah, I spoke with @alaypatel07 to make sure we use a mock of the queue so we only get the most important bit of information ignoring the remaining parts
