### ISSUE TITLE
make build should support a smaller / faster target for core component development / testing

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#99517]
`make quick-release` is one of the more reasonable options for development builds

and yet it builds lots of things like:
`cmd/linkcheck`
`cmd/genyaml`
`cmd/gendocs`
`cmd/genman`
`cmd/genkubedocs`
`cmd/genswaggertypedocs`
`cluster/images/conformance/go-runner` (even though `cluster/images/conformance` has it's own makefile)

and something to probably deprecate and remove entirely:
`cluster/gce/gci/mounter`

I'm also not sure `cmd/kubemark` should be by default instead of opt-in.

If not altering this target further, we should probably introduce a new target that builds the components necessary to create and test a cluster, with the ability to *add* additional targets.

/sig testing
cc @liggitt

**Comment by BenTheElder** [comment]
basically the only thing "quick" about "quick-release" is that we don't build for all platforms. we can do quicker than that.

**Comment by BenTheElder** [comment]
Thinking about this some more: I think this wants for a different make target.

**Comment by BenTheElder** [comment]
first thought: https://github.com/kubernetes/kubernetes/pull/100046

**Comment by BenTheElder** [comment]
Tracking this as a follow up to https://github.com/kubernetes/enhancements/issues/2420 as this is a regression over bazel (which had fine grained target groups and none of the rsync shenanigans).

**Comment by spiffxp** [comment]
/milestone v1.22
@BenTheElder please move back if you think it's feasible to land this by today

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/100046 is not bad, but I think we should move this to v1.22 to give time to consider doing something a bit more.

**Comment by voigt** [comment]
Hey there (@BenTheElder ), Bug-Triage here 👋 ,
looks like this issue hasn't received any update since it has been assigned to milestone 1.22. Given the fact that the code freeze for this release already started, do you think this one is still realistic for 1.22?

If not I'd suggest moving the issue to 1.23 or even clear the milestone label to put back responsibility to the community. wdyt?

**Comment by spiffxp** [comment]
Moving this to blocked because I'm not sure what the status is on this

**Comment by spiffxp** [comment]
Are we planning on landing this prior to code freeze or should we kick out of milestone?

**Comment by BenTheElder** [comment]
this isn't going to land, there's just too many other higher priority things to work on.

**Comment by BenTheElder** [comment]
builds got a lot faster https://github.com/kubernetes/kubernetes/pull/112819#issuecomment-1267350746
