### ISSUE TITLE
rolling update strategy maxSurge 0 not respected

### ISSUE THREAD

**Issue by rittneje** [kubernetes/kubernetes#99513]
#### What happened:

I created a deployment with a rolling update strategy with maxSurge=0 and maxUnavailable=1. I then restarted the deployment via `kubectl rollout restart`.

It unexpectedly started scheduling a new pod before one of the old pods finished terminating. This in turn triggered the cluster-autoscaler to provision a new node, which is exactly what we are trying to prevent.

#### What you expected to happen:

I expected it to follow a sequence of first terminating an old pod, then replacing it with a new pod, and so on.

#### How to reproduce it (as minimally and precisely as possible):

Create a deployment with:
```yaml
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
```

Use `kubectl rollout restart` on the deployment. Monitor the pods for the deployment.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.16.15
- Cloud provider or hardware configuration: EKS
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by jtslear** [comment]
I'm seeing the same running a cluster 1.20.8 inside of GKE.

The issue I'm linking is fully of cruft from and exploration that has taken me on a journey, however, going down, specifically to the thread I'm linking too outlines that a replicaset is being modified PRIOR to the new replicaset being created.  Something tells the old replicaset to scale back up while the deploy progresses.  This introduces some interesting havoc as now we have the old replicaset scaling back up, which must bring online new pods, the new replicaset is attempting to scale up its new pods, while that one mistake caused some number of Pods to go into a Terminated state.  

This is problematic on a few fronts:

1. Administrators taking full advantage of autoscaling are potentially seeing workloads plummet as a large amount of Pods are switched into Terminating state causing existing Pods to take on more load, potentially more than what they are designed to handle.
2. In environments where administrators are taking full advantage of node autoscaling, the old Pods that have a lengthy turn down procedures are hanging onto resources, this causes the old (now scaling back up again) and the new replicasets to both request new nodes.  This is unnecessarily driving up cloud costs and the time it takes for a deploy to complete.

I should point out that of the 4 deploys I performed an investigation, 3 of the 4 are suffering this problem.  I currently cannot explain what would be different for this 1 deployment that appears to behave as desired.

Reference my own investigation in our environment here: https://gitlab.com/gitlab-com/gl-infra/delivery/-/issues/1992#note_673922768

**Comment by jippeholwerda** [comment]
Can confirm this is an issue for us as well. It seems like `maxSurge: 0` isn't respected at all. In our case we are hitting resources quotas and restarting the deployment takes forever...

**Comment by stephen-swensen** [comment]
See thing issue too. I'm disturbed: this ticket is over 2 years old and I see bot comments like "The Kubernetes project currently lacks enough contributors to adequately respond to all issues and PRs."... this is a pretty basic issue, I thought Kubernetes was a mature, Google supported project?

**Comment by dims** [comment]
Some history: https://en.wikipedia.org/wiki/Kubernetes

**Comment by passing** [comment]
The observation is exactly what's documented:
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#updating-a-deployment

> Note: Kubernetes doesn't count terminating Pods when calculating the number of availableReplicas, which must be between replicas - maxUnavailable and replicas + maxSurge. As a result, you might notice that there are more Pods than expected during a rollout, and that the total resources consumed by the Deployment is more than replicas + maxSurge until the terminationGracePeriodSeconds of the terminating Pods expires.

You could use a StatefulSet to ensure that the number of Pods (including ones in Terminating state) never exceeds the number of replicas configured:
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#rolling-updates

> When a StatefulSet's .spec.updateStrategy.type is set to RollingUpdate, the StatefulSet controller will delete and recreate each Pod in the StatefulSet. It will proceed in the same order as Pod termination (from the largest ordinal to the smallest), updating each Pod one at a time.
