### ISSUE TITLE
GCE Persistent Disk pdName field is not useful

### ISSUE THREAD

**Issue by pbaumbacher** [kubernetes/kubernetes#99516]
#### What would you like to be added:

The `gcePersistentDisk` used in persistent volumes looks like this:
```
gcePersistentDisk:
      pdName: my-data-disk
      fsType: ext4
```

It would be more useful if it matched the format used by in a node's `providerId` field, like below:
```
gcePersistentDisk:
      pdName: gce://my-project/us-central1-b/my-data-disk
      fsType: ext4
```

#### Why is this needed:
The current name format is not useful programmatically, since you can't interact with the disk through the GCE API without also knowing the project and zone.

Additionally, it is inconsistent with the `providerId` used for nodes, and with the other persistent volume sources. For example, the `awsElasticBlockStore` source's `volumeId` is formatted `aws://us-west-2a/vol-aaaa0000`, which does match the `providerId`, and is useful

**Comment by msau42** [comment]
Thanks for the feedback. We are not making any more changes to the in-tree PD driver at this time as it is deprecated and replaced by the PD CSI driver. It looks like the PD CSI driver volume handle format may better suit your needs: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/docs/kubernetes/user-guides/pre-provisioned.md

**Comment by msau42** [comment]
If you have any further suggestions, you can open an issue in https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/. Thanks!

/close
