### ISSUE TITLE
Rework Error Types to Avoid Conflation

### ISSUE THREAD

**Issue by satnam6502** [kubernetes/kubernetes#9953]
As pointed out in #9803 to address #9721 we have situations where separate peieces of error information get conflated into one string which is troublesome when we just want one of the conflated items. For example, we have

```
type ValidationError struct {
    Type     ValidationErrorType
    Field    string
    BadValue interface{}
    Detail   string
}
```

which stores the `Detail in a separate filed e.g.`may not update fields other than container.image `. Later, when we need this information we appears in the field:

```
err.(*errors.StatusError).Status().Details.Causes[i].Message
```

by which point it is conflated into the string:

```
'{Volumes:[{Name:secret-volume VolumeSource:
{HostPath:<nil> EmptyDir:<nil> GCEPersistentDisk:<nil> AWSElasticBlockStore:<nil> GitRepo:<nil>
 Secret:<*>(0xc20a477cc0){SecretName:gh-secret} NFS:<nil> ISCSI:<nil> Glusterfs:<nil> 
PersistentVolumeClaimVolumeSource:<nil> RBD:<nil>}} {Name:default-token-04gjq VolumeSource:
{HostPath:<nil> EmptyDir:<nil> GCEPersistentDisk:<nil> AWSElasticBlockStore:<nil> GitRepo:<nil> 
Secret:<*>(0xc20a477cf0){SecretName:default-token-04gjq} NFS:<nil> ISCSI:<nil> Glusterfs:<nil> 
PersistentVolumeClaimVolumeSource:<nil> RBD:<nil>}}] Containers:[{Name:test-container 
Image:progrium/busybox Command:[sh -c mkdir /tmp/git; which git; cd /tmp/git; pwd; which git; ] Args:
<nil> WorkingDir: Ports:<nil> Env:<nil> Resources:{Limits:map[cpu:100m] Requests:map[]} 
VolumeMounts:[{Name:secret-volume ReadOnly:false MountPath:/etc/secret-volume} {Name:default-
token-04gjq ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount}] LivenessProbe:
<nil> ReadinessProbe:<nil> Lifecycle:<nil> TerminationMessagePath:/dev/termination-log 
ImagePullPolicy:IfNotPresent SecurityContext:<*>(0xc20964e020){Capabilities:<*>(0xc20a0cd080){Add:
<nil> Drop:<nil>} Privileged:<*>(0xc20a477c3c)false SELinuxOptions:<nil> RunAsUser:<nil>}}] 
RestartPolicy:Never TerminationGracePeriodSeconds:<nil> ActiveDeadlineSeconds:<nil> 
DNSPolicy:ClusterFirst NodeSelector:<nil> ServiceAccount:foo NodeName:kubernetes-minion-z282 
HostNetwork:false ImagePullSecrets:<nil>}': may not update fields other than container.image
```

We should really avoid this conflation and try to keep the spec separate from the detail error message.

@mikedanese

**Comment by feihujiang** [comment]
I would like to do some work on this

**Comment by mikedanese** [comment]
@caesarxuchao

**Comment by caesarxuchao** [comment]
@feihujiang, are you working on this? I'm working on it as well.

**Comment by caesarxuchao** [comment]
For the update error message, because `ValidationError.field` is `spec` in most cases (see [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/validation/validation.go#L998)), the error message will still be verbose even if we pass the struct instead of a string. 

We will need the strategic diff (https://github.com/GoogleCloudPlatform/kubernetes/pull/8662) to pinpoint the field that got updated.

**Comment by feihujiang** [comment]
@caesarxuchao  No, I'm not working on this now. I was just back from a business trip. If there is somthing left in this issue, next week I'll do it .

**Comment by caesarxuchao** [comment]
Thank you @feihujiang. I submitted #12114 to fix the issue.

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is important.
