### ISSUE TITLE
Add E2E tests for Port Ranges on Network Policy

### ISSUE THREAD

**Issue by knabben** [kubernetes/kubernetes#99551]
#### What would you like to be added:
Add E2E tests for Port Ranges on Network Policy
Enhancement proposal:

https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/2079-network-policy-port-range/README.md

#### Why is this needed:
In order to increase test coverage for the Port Range network policy feature.

**Comment by JornShen** [comment]
@knabben  what the process of this ?  IF not starting, I think I can do help :)

**Comment by knabben** [comment]
> @knabben what the process of this ? IF not starting, I think I can do help :)

Sure, this can be split into two parts:

1) Create an API test with port range here - https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/netpol/network_policy_api.go#L36, this is straightforward and is applicable with the master code.

2) Create a Netpol functional test, which will depend on the next release version of Calico with the range port feature added

**Comment by JornShen** [comment]
> > @knabben what the process of this ? IF not starting, I think I can do help :)
> 
> Sure, this can be split into two parts:
> 
> 1. Create an API test with port range here - https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/netpol/network_policy_api.go#L36, this is straightforward and is applicable with the master code.
> 2. Create a Netpol functional test, which will depend on the next release version of Calico with the range port feature added

thanks for guide :)
/assign
