### ISSUE TITLE
Add E2E tests for immutable label selector for namespace

### ISSUE THREAD

**Issue by knabben** [kubernetes/kubernetes#99552]
#### What would you like to be added:
Add E2E tests for the immutable label selector for NS

Enhancement proposal:
https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/2161-apiserver-default-labels

#### Why is this needed:
In order to increase test coverage for the default namespace label feature

**Comment by JornShen** [comment]
@knabben have you start it? If no, I think I can help for it
:)

**Comment by knabben** [comment]
Sure. This is sig api machinery test though
