### ISSUE TITLE
hack/tools/go.mod transitively imports this repo at v1.13.0

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#99562]
See: https://github.com/kubernetes/kubernetes/pull/98845/files#r584370625

We should not have cycles like this.

**Comment by dims** [comment]
https://github.com/kubernetes-sigs/zeitgeist/pull/29#issuecomment-787559461 :( 

@hasheddan @saschagrunert @justaugustus

**Comment by ams0** [comment]
Hello! I am from the Bug Triage team! Friendly reminder that code freeze is starting March 9th, 2021 (today!).

I can see the linked urgent PR is merged and the dependency is update, if no more work is needed, I'd suggest to close this issue for the 1.21.

**Comment by justaugustus** [comment]
> I can see the linked urgent PR is merged and the dependency is update, if no more work is needed, I'd suggest to close this issue for the 1.21.

Closed via https://github.com/kubernetes/kubernetes/pull/99679.
Thanks for checking in, @ams0!

/close
