### ISSUE TITLE
scheduler failed to start due to the custom plugin config in scheduler config file

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubernetes#99580]
#### What happened:
Start the scheduler with a scheduler config file which has a custom configuration for a specific plugin, the scheduler will fail to start and throw below exception, 

*kube-scheduler.yaml*
```yaml
apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
profiles:
- schedulerName: default-scheduler
  plugins:
    score:
      enabled:
        - name: InterPodAffinity
          weight: 2
   ...
```

error message, 
```
W0301 18:07:50.432541   26557 authorization.go:184] No authorization-kubeconfig provided, so SubjectAccessReview of authorization tokens won't work.
couldn't create scheduler using provider "DefaultProvider": initializing profiles: creating profile for scheduler name default-scheduler: plugin "InterPodAffinity" already registered as "ScorePlugin"
Process 26557 has exited with status 1
```

#### What you expected to happen:
custom plugin config should take precedence over default plugin config.

#### How to reproduce it (as minimally and precisely as possible):
start a scheduler with a config file.

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by adtac** [comment]
Does disabling the plugin and re-enabling the same plugin with a different weight work as a workaround?

**Comment by alculquicondor** [comment]
This is WAI.
You have to explicitly disable the default configuration.

**Comment by chendave** [comment]
> Does disabling the plugin and re-enabling the same plugin with a different weight work as a workaround?
I think so.

**Comment by chendave** [comment]
> This is WAI.
> You have to explicitly disable the default configuration.

I not sure I agree with this,  particularly, for someone who doesn't know details of code IMPL,  e.g. an operator, 
- Why bother to disable the plugin first and then re-enable the same plugin? there is no pointer to show they are different in a config file, as a developer, we know the reason behind the scenes, can we assume operator also know what that means to define a schedule config?
- By disabling the plugin and re-enable it means the operator has the knowledge this plugin is a default enabled plugin, should the operator check the source code to confirm this plugin's configuration?
- When this happens, given a different config for a specific plugin, should this deserve a corruption?  I think scheduler should more robust to tolerate this.

**Comment by alculquicondor** [comment]
> By disabling the plugin and re-enable it means the operator has the knowledge this plugin is a default enabled plugin, should the operator check the source code to confirm this plugin's configuration?

We can improve the docs to include the default plugins.

> When this happens, given a different config for a specific plugin, should this deserve a corruption? I think scheduler should more robust to tolerate this.

It's better for the API to be more predictable (always do the same thing). One thing to think about is order: if we do what your PR proposes, we are altering the order in which plugins are run, not just modifying the "weight" of the plugin.

**Comment by alculquicondor** [comment]
I'm leaning towards closing this

@Huang-Wei ?

**Comment by Huang-Wei** [comment]
> One thing to think about is order: if we do what your PR proposes, we are altering the order in which plugins are run, not just modifying the "weight" of the plugin.

It's the key point I'm concerned about: commented here https://github.com/kubernetes/kubernetes/pull/99582#discussion_r588799737. So let me ask a question: for a given input like:

```go
customPlugins: &Plugins{
	Filter: PluginSet{
		Enabled: []Plugin{
			{Name: "DefaultPlugin2", Weight: 200},
		},
		Disabled: []Plugin{
			{Name: "DefaultPlugin2", Weight: 2},
		},
	},
},
defaultPlugins: &Plugins{
	Filter: PluginSet{
		Enabled: []Plugin{
			{Name: "DefaultPlugin1", Weight: 1},
			{Name: "DefaultPlugin2", Weight: 2},
			{Name: "DefaultPlugin3", Weight: 3},
		},
	},
},
```

What's the expected output?

1. {DefaultPlugin1, 1}, {DefaultPlugin2, 200}, {DefaultPlugin3, 3}, OR
1. {DefaultPlugin1, 1}, {DefaultPlugin3, 3}, {DefaultPlugin2, 200}

**Comment by alculquicondor** [comment]
Today, it is 2.

**Comment by Huang-Wei** [comment]
> Today, it is 2.

So in other words, if a user wants to customize a plugin's weight and keep its order, the only way is to use `disabled:*` and give a full list of plugins? If so, that's not a good UX IMO.

**Comment by alculquicondor** [comment]
Well, order doesn't matter for Score, so not really a problem.

**Comment by Huang-Wei** [comment]
> Well, order doesn't matter for Score, so not really a problem.

All right, so the only case users could disable PluginXYZ while also enabling PluginXYZ is Score plugins, I'm fine with the order issue.

Back to this issue, my 2 cents is to change the semantics of `enabled` to a more enforced manner (proposed in this issue) in a new API version - v1beta2 or GA. As IMO it's a real UX improvement. WDYT?

**Comment by alculquicondor** [comment]
I'm not convinced it's a UX improvement.

If the user "enables" a filter plugin that was a default (say, by mistake), then its order changes. At least first disabling the plugin makes it more explicit.

cc @adtac who has been working on decisions based on CC version

**Comment by alculquicondor** [comment]
I guess it depends on the implementation. What is the full proposal?

**Comment by Huang-Wei** [comment]
> If the user "enables" a filter plugin that was a default (say, by mistake), then its order changes.

That's a fair point, esp. if we adjust default plugins from version to version. I think a good UX is to throw an error/warning to indicate that a default Filter plugin is being **re-enabled** - this's useful no matter which semantic `enabled` employes.

**Comment by Huang-Wei** [comment]
> I guess it depends on the implementation. What is the full proposal?

I'd like to:

- keep current logic to warn users that "PluginXYZ" is already registered (by default), if it's a non-Score plugin
- apply the "overridden" semantics for `enabled` for Score plugins only

**Comment by alculquicondor** [comment]
I propose (only for new version):

- Fail when plugin is already registered in the custom configuration, and only warning if the plugin was already part of defaults.
- Override any weight, preserving order

I think that keeps everything consistent. I think this is what the last iteration of the PR is doing, but I only skimmed through it.

**Comment by Huang-Wei** [comment]
SGTM.

To confirm, by "Fail when plugin is already registered in the custom configuration", this's only possible when users implement an out-of-tree plugin with a name identical to a default one, right?

**Comment by alculquicondor** [comment]
I'm just referring to failing when the user repeats the same value twice.

I think we can't prevent what you say.

**Comment by chendave** [comment]
> If the user "enables" a filter plugin that was a default (say, by mistake), then its order changes. At least first disabling the plugin makes it more explicit.

This might be the reason why the order of the plugins should be reserved.

**Comment by chendave** [comment]
> keep current logic to warn users that "PluginXYZ" is already registered (by default), if it's a non-Score plugin

Unless it's score plugin like this issue, I don't know if there is any point to enable the default plugin in a config file.

> apply the "overridden" semantics to enabled directive, for Score plugins only

I think there is no need to distinguish score plugin with others, this will make the life easier, correct me?

**Comment by chendave** [comment]
> Fail when plugin is already registered in the custom configuration, and only warning if the plugin was already part of defaults.
> Override any weight, preserving order

Yeah, overall, https://github.com/kubernetes/kubernetes/pull/99582 is following this ideas, except that PR doesn't handle the repeated configuration, because if there is repeated value after the default plugin is overridden, it will hit the error below,
 
> creating profile for scheduler name default-scheduler: plugin "InterPodAffinity" already registered as "ScorePlugin"

**Comment by chendave** [comment]
@alculquicondor @Huang-Wei  thanks for those valuable suggestion!

So, we are still with beta1, and you suggest we can make some change in the new version,  beta2?  Is there any plan when this could happen? v1.22?

**Comment by alculquicondor** [comment]
> Unless it's score plugin like this issue, I don't know if there is any point to enable the default plugin in a config file.

You are correct, there is no point, but it's good to have consistency. If it's allowed for Score, it should be allowed for other extension points.

> I think there is no need to distinguish score plugin with others, this will make the life easier, correct me?

I agree

> So, we are still with beta1, and you suggest we can make some change in the new version, beta2? Is there any plan when this could happen? v1.22?

Yes, that is the plan. It was 1.21, but we fall behind due to newer plans for deprecating plugins

#95446

**Comment by adtac** [comment]
let's say there are 3 default non-Score plugins A, B and C (in that order). I want to move B to the end of the list but I want to custom enable C too (for whatever reason; since we want to consistent with score plugins, let's allow this for other extension points too as @alculquicondor said).

if a non-Score plugin is custom disabled AND enabled, we should move it to the end of the list but if it's simply just enabled, then we should preserve order. if it's a score plugin, disabling and re-enabling has the same semantics as just simply enabling; they both will only change the weight.

(idk if this has already been proposed; if it has been, consider this a vote of support :))

**Comment by alculquicondor** [comment]
Are you saying that "disabled and enabled" should be treated the same as just "enabled"? That is, always move to the end of the list?

**Comment by adtac** [comment]
No, just "enabled" wouldn't move things to the end of the list (preserve order), but "disabled and enabled" would move to the end of the list
.

**Comment by alculquicondor** [comment]
ok, that sounds good

**Comment by chendave** [comment]
Another problem here is if we don't want to overridden anything but just config a plugin which is accidently a default plugin, something like below, 

```yaml
apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
...
profiles:
- schedulerName: default-scheduler
  plugins:
    queueSort:
      enabled:
      - name: PrioritySort
...
```

scheduler will fail as well, 

```
W0326 13:33:10.568807   22807 authorization.go:184] No authorization-kubeconfig provided, so SubjectAccessReview of authorization tokens won't work.
couldn't create scheduler using provider "DefaultProvider": initializing profiles: one queue sort plugin required for profile with scheduler name "default-scheduler"
```


```
(dlv) p c.profiles[0].Plugins.QueueSort.Enabled
[]k8s.io/kubernetes/pkg/scheduler/apis/config.Plugin len: 2, cap: 2, [
        {
                Name: "PrioritySort",
                Weight: 0,},
        {
                Name: "PrioritySort",
                Weight: 0,},
]
```

I think we need to De-dup here instead of just a warning here. I guess this PR https://github.com/kubernetes/kubernetes/pull/99582 should already cover this, I will go back to check it again, at least one more testcase is needed to cover this case.

>keep current logic to warn users that "PluginXYZ" is already registered (by default), if it's a non-Score plugin

**Comment by chendave** [comment]
/lifecycle stale

let me revive the PR later.
