### ISSUE TITLE
Ensure eviction respects PDB failsafe

### ISSUE THREAD

**Issue by michaelgugino** [kubernetes/kubernetes#99598]
The PDB controller has logic to 'fail safe' if it cannot determine the correct number of desired replicas, and possibly other scenarios.  Currently, the PDB controller will set status.DisruptionsAllowed = 0, but not offer any other indication that the PDB controller has 'failed safe' to 0.  Since the intent of failing safe is to disallow all disruptions, this previously was sufficient.

Recent changes in the eviction API allow pods that are unready to be evicted if there are otherwise enough CurrentlyHealthy pods according to the associated PDB.  In some scenarios, this means that DisruptionsAllowed==0, and evict will still succeed as long as CurrentHealthy>=DesiredHealthy on the PDB: https://github.com/kubernetes/kubernetes/blob/release-1.20/pkg/registry/core/pod/storage/eviction.go#L208

The eviction API, and possibly other consumers, need a way to determine specifically if the PDB is in 'fail safe' scenario, or if DisruptionsAllowed==0 due to normal circumstances.  Proposed PDB status conditions could provide this.

Related PR: https://github.com/kubernetes/kubernetes/pull/98127/files

**Comment by mortent** [comment]
@liggitt @michaelgugino 
Continuing the thread from https://github.com/kubernetes/kubernetes/pull/98127#discussion_r582369233

So my original thinking around evicting pods that are Running but not Ready is that it should always be safe (as long as we do a conditional delete). This was discussed at length in https://github.com/kubernetes/kubernetes/pull/94381 (and other issues/PRs linked from there) and the current solution was eventually chosen.

Regarding the issues with tolerating the condition being removed/added reliably, that doesn't seem unique to the solution with the condition. Adding a separate field seems to have the same problem. Forcing the value of `CurrentHealthy` to be zero seems slightly better as it a field that will be updated by a v1.20 controller.
An option could be to add the condition in 1.21 and delay adding the additional check for the eviction API until 1.22. In that case we could rely on the condition being handled correctly by both 1.21 and 1.22 clusters. But that means this issue won't be solved until v1.22.

**Comment by michaelgugino** [comment]
I don't have a strong opinion on how we accomplish this, but I consider eviction to currently have a bug (somewhat of an edge case) today, so I'm not sure we need to delay adding the check until 1.22, I don't see why we couldn't ship alongside with the conditions in PDBs (or whatever other mechanism is chosen).

**Comment by mortent** [comment]
So based on the description by @liggitt, it seems like the main challenge would be the second scenario where a PDB could have a condition with `SyncFailed` reason that would never be removed. It would effectively block evictions forever (or until the controller-manager is updated). This would also require that the server that performs the eviction is on 1.21 since the check is not being done on 1.20.
Maybe this is an acceptable solution. I'm not sure I see any other ways to fix this in 1.21.

If we could do away with the check against CurrentHealthy/DesiredHealthy, that would completely fix the issue.

**Comment by michaelgugino** [comment]
We can't do away with the CurrentHealthy/DesiredHealthy check.  Pods can be not-ready for a variety of reasons, it doesn't mean they're down and we are free to evict them.

>  it seems like the main challenge would be the second scenario where a PDB could have a condition with SyncFailed reason that would never be removed.

If the PDB is misconfigured, we want to block indefinitely because we can't be sure if it's safe to evict or not.  I'm not sure what scenario you're talking about specifically, but I don't think PDBs go permanent-failed, they can be adjusted to work again, right?

If conditions ships in 1.21, then I can update the eviction API to check the SyncFailed condition.  If it's not going to ship in 1.21, then we can update eviction whenever it does.

**Comment by liggitt** [comment]
I think it's reasonable to ship conditions in 1.21 and set the SyncFailed condition, then update the eviction API to rely on it in 1.22
