### ISSUE TITLE
PVC protection controller: when is pod shut down?

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#99604]
The implementation of generic ephemeral volumes depended on relaxing the "pod uses PVC" check such that PVC deletion is allowed to proceed even when the pod itself still exist, as long as it is certain that kubelet is done with the pod:

https://github.com/kubernetes/kubernetes/blob/35c233f18d42dd9bfe96fdc08b45c8880b2ac9a2/pkg/controller/volume/pvcprotection/pvc_protection_controller.go#L295-L346

As noted in that comment, there were diverging opinions about what deletionGracePeriodSeconds being zero means. This issue is about double-checking that and if necessary, come up with a better check.

**Comment by pohly** [comment]
Jordan [pointed out the relevant code](https://kubernetes.slack.com/archives/C0EG7JC6T/p1614627038068200?thread_ts=1614626848.068000&cid=C0EG7JC6T) in kubelet which causes `DeletionGracePeriodSeconds` to be set to zero: https://github.com/kubernetes/kubernetes/blob/5404b5a28a2114299608bab00e4292960dd864a0/pkg/kubelet/status/status_manager.go#L580-L592

This is called "after terminating the containers and cleaning up the pod". So `DeletionGracePeriodSeconds = 0` and `pod removed` are indeed equivalent.

@msau42 does this address the concern that you had regarding generic ephemeral volumes and pod shutdown?

Whether "after terminating the containers and cleaning up the pod" is good enough for the PVC protection controller is a different question, but that then is also affecting normal PVCs and not just generic ephemeral volumes.

**Comment by msau42** [comment]
It looks like https://github.com/kubernetes/kubernetes/blob/5404b5a28a2114299608bab00e4292960dd864a0/pkg/kubelet/status/status_manager.go#L579 calls `PodResourcesAreReclaimed` which calls `podVolumesExist`: https://github.com/kubernetes/kubernetes/blob/5404b5a28a2114299608bab00e4292960dd864a0/pkg/kubelet/kubelet_pods.go#L980

So it does look like this waits until pod volumes are successfully unmounted (minus the node unstage issue). This addresses my concern thanks!

**Comment by msau42** [comment]
Only thing left is to clean up the todo in the code.

**Comment by pohly** [comment]
> Only thing left is to clean up the todo in the code.

See https://github.com/kubernetes/kubernetes/pull/99626
