### ISSUE TITLE
Faulty apiserver endpoint blocking launching of static pods

### ISSUE THREAD

**Issue by kvaps** [kubernetes/kubernetes#99602]
#### What happened:

I use haproxy as main loadbalancer for kube-apiservers.
Kubelets are configured to communicate with apiserver via haproxy.

Today I was testing etcd-cluster recovery procedure and all apiservers were unreachable for a while.
At this time haproxy was keeping connections open, but didn't close them because none of apiservers were working.

Kubelets were confused by this behavior and didn't start any static-pods. Especially a new etcd pods, which are so needed to make apiservers working. 🙂

#### What you expected to happen:

Kubelets are starting static-pods despite the inaccessibility of apiserver.

#### How to reproduce it (as minimally and precisely as possible):

- Install haproxy using config from [this article](https://kvaps.medium.com/for-make-this-scheme-more-safe-you-can-add-haproxy-layer-between-keepalived-and-kube-apiservers-62c344283076)
- Stop all apiservers
- Restart docker.service to remove all the containers

You will see that kubelet is not creating any of static pods, even restart of kubelet.service does not make any change.

#### Environment:
- Kubernetes version (use `kubectl version`): `v1.20.2`
- Cloud provider or hardware configuration: bare metal
- OS (e.g: `cat /etc/os-release`): Debian 10
- Kernel (e.g. `uname -a`): `5.4.65-1-pve`
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:
```
HA-Proxy version 1.8.19-1+deb10u3 2020/08/01
```

**Comment by kvaps** [comment]
> shouldn't haproxy close the connections in this case?

Haproxy is waiting for at least one working endpoint to route traffic on it, this is feature of haproxy that no one connection is getting not lost.
I guess it is configurable behavior, but I don't like the fact that some external load balancer can affect kubelets behavior somehow.

> the kubelet would normally start static pods even if the api-server is not reachable.

I can confirm that, but not in the case when load balancer keeping open connections.

**Comment by kvaps** [comment]
Just faced with this problem again:

```bash
# kubelet --version
Kubernetes v1.20.4
```

haproxy config for now includes just single server:

```bash
# cat /etc/haproxy/haproxy.cfg
defaults
    maxconn 20000
    mode    tcp
    option  dontlognull
    timeout http-request 10s
    timeout queue        1m
    timeout connect      10s
    timeout client       86400s
    timeout server       86400s
    timeout tunnel       86400s

frontend k8s-api
    bind :::8443 v4v6
    mode tcp
    default_backend k8s-api

backend k8s-api
    option httpchk GET /readyz HTTP/1.0
    option log-health-checks
    http-check expect status 200
    balance roundrobin
    default-server verify none check-ssl inter 10s downinter 5s rise 2 fall 2 slowstart 60s maxconn 5000 maxqueue 5000 weight 100

    server master 10.36.20.3:6443 check
```

**Comment by neolit123** [comment]
hi, maybe you can add this as an agenda item for sig-network's zoom meeting and talk to them:
https://github.com/kubernetes/community/tree/master/sig-network#contact

**Comment by adisky** [comment]
/triage needs-information
@kvaps can you share kubelet logs? to know whats kubelet is assuming the status of API server.
