### ISSUE TITLE
Exec plugin overrides static certs in kubeconfig (different behavior than over statically configured credentials)

### ISSUE THREAD

**Issue by ankeesler** [kubernetes/kubernetes#99603]
#### What happened:

- My exec plugin overrode the static certs I had in my kubeconfig.

#### What you expected to happen:

- The static certs I had in my kubeconfig should take precedent over whatever is configured by my exec plugin.

#### How to reproduce it (as minimally and precisely as possible):

With admin-like privileges, do the following.
```bash
# Generate CSR.
openssl req -nodes -subj /CN=some-username -newkey rsa:2048 -keyout /tmp/aaa.key -out /tmp/aaa.csr

# Create CSR.
cat <<EOF | kubectl replace -f -
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: aaa
spec:
  request: $(cat /tmp/aaa.csr | base64 | tr -d '\n')
  signerName: kubernetes.io/kube-apiserver-client
  usages: [client auth]
EOF

# Issue certificate.
kubectl certificate approve aaa
kubectl get csr aaa -o jsonpath={.status.certificate} | base64 -d > /tmp/aaa.crt

# Make request with both certificate and exec plugin that returns token.
cat <<EOF >/tmp/aaa.sh
#!/bin/bash
echo '{"kind":"ExecCredential","apiVersion":"client.authentication.k8s.io/v1beta1","status":{"clientKeyData":"bad","clientCertificateData":"bad"}}'
EOF
chmod +x /tmp/aaa.sh
kubectl config set-credentials aaa --client-certificate=/tmp/aaa.crt --client-key=/tmp/aaa.key --exec-api-version client.authentication.k8s.io/v1beta1 --exec-command=/tmp/aaa.sh
kubectl --user aaa get pods
```

#### Anything else we need to know?:

- This seems like unexpected behavior because other statically configured credentials (i.e., basic auth, bearer token) take precedent over the stuff returned by the exec plugin.
- This was pointed out by @enj when he was reviewing some exec plugin integration tests.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.20.0
- Cloud provider or hardware configuration: `kind`, but shouldn't matter
- OS (e.g: `cat /etc/os-release`): Darwin, but shouldn't matter
- Kernel (e.g. `uname -a`): Darwin, but shouldn't matter
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by enj** [comment]
This should also cover the direct case right?

`kubectl get ns --client-...=`

```
$ kubectl options |& grep TLS
      --client-certificate='': Path to a client certificate file for TLS
      --client-key='': Path to a client key file for TLS
```

Precedence should be:

1. CLI flags
2. Static config
3. Exec plugin

**Comment by liggitt** [comment]
is this required for exec auth GA in 1.22?

**Comment by ankeesler** [comment]
> is this required for exec auth GA in 1.22?

I asked @enj that same question week before last (I've been on PTO). @enj posited that this is a "nice to have" (i.e., it shouldn't block GA) since there are other CLI cred override weirdisms.

**Comment by enj** [comment]
> > is this required for exec auth GA in 1.22?
> 
> I asked @enj that same question week before last (I've been on PTO). @enj posited that this is a "nice to have" (i.e., it shouldn't block GA) since there are other CLI cred override weirdisms.

Based on what I observed in https://github.com/kubernetes-sigs/kind/issues/2229#issuecomment-832207205, it looks like `--token` does not override client certs in static config, which is wrong.  In general we need to fix credential precedence handling in `kubectl` per https://github.com/kubernetes/kubernetes/issues/99603#issuecomment-788194837.
