### ISSUE TITLE
hostPort is not published (anymore)

### ISSUE THREAD

**Issue by PEERCRED** [kubernetes/kubernetes#99622]
#### What happened:
I had an ingress controller running on the master node with ports exposed using `hostPort:` mapping:
```yaml
        ports:
          - containerPort: 80
            hostPort: 80
          - containerPort: 443
            hostPort: 443
```
After cluster recreation (`kubeadm reset`/`kubeadm init`), I don't/can't get these ports published on the master node anymore for unknown reasons.
k8s/docker/CNI updates didn't help.

#### Anything else we need to know?:
`docker inspect k8s_POD_traefik-ingress-controller-...` shows:
```json
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "none",
            "PortBindings": {
                "443/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "443"
                    }
                ],
                "80/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "80"
                    }
                ]
            },
```
If I run some other container using `docker -p XXX:YYY`, I see `"NetworkMode": "default"` for it, not `"NetworkMode": "none"`. I guess `"NetworkMode": "none"` is the reason why the ports are not published.

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.17", GitCommit:"f3abc15296f3a3f54e4ee42e830c61047b13895f", GitTreeState:"clean", BuildDate:"2021-01-13T13:13:00Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: self-hosted
- OS (e.g: `cat /etc/os-release`): Debian GNU/Linux 9 (stretch)
- Kernel (e.g. `uname -a`): 4.9.0-4-amd64
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): flannel `v0.11.0` (old/then-current), `v0.13.1-rc2` (tried)
- Others: `portmap` plugin is obviously present in the CNI config.

**Comment by neolit123** [comment]
/sig network

- please try another CNI plugin instead of flannel.
- 1.17 is no longer in support, so you must reproduce the issue with 1.18+.

**Comment by uablrek** [comment]
80 and 443 are "privileged" ports (<1024). Just to rule out some unwanted security restriction please try some ports > 1024, e.g 8080, 8443.

**Comment by thockin** [comment]
Is it that `docker inspect` doesn't show the ports (it shouldn't, we mostly do our own management) or that the port forwards actually do not work?

Which driver mode are you using (kubenet or cni (which one))?

Can you post `iptables-save` output?

**Comment by PEERCRED** [comment]
> Is it that docker inspect doesn't show the ports

It shows:
```
            "PortBindings": {
                "443/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "443"
                    }
                ],
                "80/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "80"
                    }
                ]
            },
```
it is `"NetworkMode": "none",` which looks suspicious.

> or that the port forwards actually do not work?

This. `netstat -ltnup` doesn't show ports, trying to connect to them (with browser or `curl`) hangs for some time and then says that it is unable to connect. When I try to add `hostNetwork: true` to the Ingress YAML, in `netstat -ltnup` I see the 80, 443 and 8080 ports open.

> Which driver mode are you using (kubenet or cni (which one))?

I wrote in the issue description: I've tried flannel `v0.11.0` and `v0.13.1-rc2`

> Can you post `iptables-save` output?

[Here it is](https://pastebin.com/qsde8ZrX). I see that iptables know about the `80` and `443` ports :hushed: 

@uablrek I've tried `hostport: 14443`, it is still not accessible.

**Comment by thockin** [comment]
> it is "NetworkMode": "none", which looks suspicious.

Kubernetes has not used Docker's networking for years and years.  That is normal.

> netstat -ltnup doesn't show ports

That might not show them since they are captured in iptables

> trying to connect to them (with browser or curl) hangs for some time and then says that it is unable to connect

...and it used to work?  What changed?

> I've tried flannel v0.11.0 and v0.13.1-rc2

When you access the nodePort is it via `localhost` or `<nodeIP>`.  I am not a flannel expert - maybe @caseydavenport  can help?  It also seems you're using the CNI port forward which I don't know details any more (@danwinship ?)

```
-A CNI-HOSTPORT-DNAT -p tcp -m comment --comment "dnat name: \"cbr0\" id: \"a04a713cc0f8e834816fcc3d5838f380f07acbd62ea746b192e517bae3e6243e\"" -m multiport --dports 80,443 -j CNI-DN-415d996e0d01b85e97bd3
-A CNI-HOSTPORT-DNAT -p tcp -m comment --comment "dnat name: \"cbr0\" id: \"cf3aca2d5c29459a01fc58f5c56a7698cf76bf52606a76449d450f6c6008ad36\"" -m multiport --dports 80,443 -j CNI-DN-d4097a0f1d2794778db30
-A CNI-HOSTPORT-DNAT -p tcp -m comment --comment "dnat name: \"cbr0\" id: \"3c11fb247f19ca61c88f5bc79958003f238c0c4d0d49ec81b719da0f5ba30403\"" -m multiport --dports 80,443 -j CNI-DN-b78f66d0a75406054cc4e
```

You have three rules trying to claim the same ports, which also seems wrong.  Maybe those are not being cleaned up properly?

**Comment by PEERCRED** [comment]
> ...and it used to work? What changed?

Yes, it used to. I don't think anything changed when I was first trying to re-create the cluster. Later I've tried to update docker, kubelet and flannel, but it didn't help.

> When you access the `nodePort` is it via `localhost` or `<nodeIP>.` 

node's hostname from the outside, both node's hostname or `localhost` from the node itself.
The fact that `kubectl` works (and I successfully able to use `curl` to reach `https://node's hostname:6443`) suggests that it is not a routing issue.

**Comment by PEERCRED** [comment]
I've `kubeadm reset` the master node, rebooted it, `kubeadm init`-ed it, deployed CNI plugin and an Ingress controller and... now I immediately see `404` response from the Ingress web server. [This is how my iptables look now](https://pastebin.com/C6d7zvvE): only one rule with `--dports 80,443`. BTW, there are no `80` and `443` ports in `netstat -ltsp` and `docker inspect` looks the same.

:confused:
