### ISSUE TITLE
Kube-apiserver doesn't pick --etcd-servers values from environment file

### ISSUE THREAD

**Issue by vinusorout** [kubernetes/kubernetes#99636]
Hello,

I am trying to set kube-apiserver.service manually, for that I have create a service file, with environment:

**Service File**
[Unit]
Description=Kubernetes API Server
Documentation=https://github.com/kubernetes/kubernetes

[Service]
EnvironmentFile=/etc/kubernetes/kube-apiserver.env
ExecStart=/usr/local/bin/kube-apiserver
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target

**And /etc/kubernetes/kube-apiserver.env has following variables**

ADVERTISE_ADDRESS=192.168.71.137
ALLOW_PRIVILEGED=true
APISERVER_COUNT=1
AUDIT_LOG_MAXAGE=30
AUDIT_LOG_MAXBACKUP=3
AUDIT_LOG_MAXSIZE=100
AUDIT_LOG_PATH=/var/log/audit.log
AUTHORIZATION_MODE=Node,RBAC
BIND_ADDRESS=0.0.0.0
CLIENT_CA_FILE=/var/lib/kubernetes/ca.pem
ENABLE_ADMISSION_PLUGINS=NamespaceLifecycle,NodeRestriction,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota
ETCD_CAFILE=/var/lib/kubernetes/ca.pem
ETCD_CERTFILE=/var/lib/kubernetes/kcontrol-kube-api-server-crt.pem
ETCD_KEYFILE=/var/lib/kubernetes/kcontrol-key.pem
ETCD_SERVERS=https://192.168.71.137:2379
EVENT_TTL=1h
ENCRYPTION_PROVIDER_CONFIG=/var/lib/kubernetes/encryption-data-config.yaml
KUBELET_CERTIFICATE_AUTHORITY=/var/lib/kubernetes/ca.pem
KUBELET_CLIENT_CERTIFICATE=/var/lib/kubernetes/kcontrol-kube-api-server-crt.pem
KUBELET_CLIENT_KEY=/var/lib/kubernetes/kcontrol-key.pem
KUBELET_HTTPS=true
RUNTIME_CONFIG='api/all=true'
SERVICE_ACCOUNT_KEY_FILE=/var/lib/kubernetes/kcontrol-service-account-crt.pem
SERVICE_ACCOUNT_SIGNING_KEY_FILE=/var/lib/kubernetes/kcontrol-key.pem
SERVICE_ACCOUNT_ISSUER=https://kubernetes.default.svc.cluster.local
SERVICE_CLUSTER_IP_RANGE=10.32.0.0/24
SERVICE_NODE_PORT_RANGE=1-32767
TLS_CERT_FILE=/var/lib/kubernetes/kcontrol-kube-api-server-crt.pem
TLS_PRIVATE_KEY_FILE=/var/lib/kubernetes/kcontrol-key.pem
V=2

After starting the service I am getting following error:
`
Error: [--etcd-servers must be specified, service-account-issuer is a required flag, --service-account-signing-key-file and --service-account-issuer are required flags]
`

I already have specified the values for the variables in file /etc/kubernetes/kube-apiserver.env. But I am still getting this error. 
Please let me know what should I to make it run properly?

**Comment by pacoxu** [comment]
```
[Service]
EnvironmentFile=/etc/kubernetes.env
ExecStart=/opt/bin/kube-apiserver $KUBE_APISERVER_OPTS
```
https://github.com/kelseyhightower/kubestack/blob/41cb43c710e32d056d6a10e59b0cbc25686a9286/terraform/kubernetes.env#L15-L21

A sample is like above.
/kind support
/remove-kind bug

**Comment by pacoxu** [comment]
BTW, current most clusters are using static pod yaml to start up apiserver. What tool are you using to set up the cluster?

**Comment by neolit123** [comment]
closing this as trying to keep the issue tracker for bugs/features only, but feel free to continue the discussion.
/close

for future questions please use:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
