### ISSUE TITLE
NodeAffinity preferredDuringSchedulingIgnoredDuringExecution doesn't work well

### ISSUE THREAD

**Issue by DemonsLu** [kubernetes/kubernetes#99630]
#### What happened:
I have 2 nodes, one label is foo=bar, annother label is foo=car, both of them have enough resources. And I want to use nodeAffinity's preferredDuringSchedulingIgnoredDuringExecution feature to make my pods be assigned in target node. 
I use deployment to manage pods, which setting the pod replica is 2. But when pods are created, I found one pod is created on node (foo=bar), and another pod is created on node (foo=car)

Here is my config content.

```
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: foo
                    operator: In
                    values:
                      - bar
              weight: 100
```

#### What you expected to happen:
All pods are created on node which label is foo=bar.

#### How to reproduce it (as minimally and precisely as possible):
Created a deployment, assigned replica is 2 and add the preferredDuringSchedulingIgnoredDuringExecution.

#### Anything else we need to know?:
Before I report this problem, I read the k8s source code and found all scorePlugin's weight is 1, except nodepreferavoidpods and podtopologyspread. And I noticed the podtopologyspread comment explained `This is a score coming from user preference`, so this scorePlugin's weight is 2. So I wonder know why nodeaffinity coming from user preference too, but Its weight is still set to 1. I think `noderesources.BalancedAllocationName` plugin and `noderesources.LeastAllocatedName` plugin affected the behavior of nodeAffinity. So Is there any plan to change nodeaffinity's weight from 1 to 2?

source code (path: pkg/scheduler/algorithmprovider/registry.go)
```
		Score: schedulerapi.PluginSet{
			Enabled: []schedulerapi.Plugin{
				{Name: noderesources.BalancedAllocationName, Weight: 1},
				{Name: imagelocality.Name, Weight: 1},
				{Name: interpodaffinity.Name, Weight: 1},
				{Name: noderesources.LeastAllocatedName, Weight: 1},
				{Name: nodeaffinity.Name, Weight: 1},
				{Name: nodepreferavoidpods.Name, Weight: 10000},
				// Weight is doubled because:
				// - This is a score coming from user preference.
				// - It makes its signal comparable to NodeResourcesLeastAllocated.
				{Name: podtopologyspread.Name, Weight: 2},
				{Name: tainttoleration.Name, Weight: 1},
			},
		}
```

#### Environment:
- Kubernetes version (use `kubectl version`): v1.18 (but even the code on master branch, nodeaffinity's weight is still set to 1)
- Cloud provider or hardware configuration: EKS
- OS (e.g: `cat /etc/os-release`): 
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
- Kernel (e.g. `uname -a`): x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by DemonsLu** [comment]
sig/ scheduling

**Comment by wangyysde** [comment]
Refer to https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/, "....while the latter specifies preferences that the scheduler will try to enforce but will not guarantee. ....". So should you using requiredDuringSchedulingIgnoredDuringExecution instead of preferredDuringSchedulingIgnoredDuringExecution?

**Comment by wangyysde** [comment]
Refer to https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/, "....while the latter specifies preferences that the scheduler will try to enforce but will not guarantee. ....". So should you using requiredDuringSchedulingIgnoredDuringExecution instead of preferredDuringSchedulingIgnoredDuringExecution?

**Comment by DemonsLu** [comment]
@wangyysde Thanks for your response. 
I have been read the k8s document before I create this issue. The reason why I choose `preferredDuringSchedulingIgnoredDuringExecution` rather than `requiredDuringSchedulingIgnoredDuringExecution` is that I labeled the node in Zone A with the label foo=bar and the node in Zone B with the label foo=car.  As usual, I expect all node created in Zone A as much as possible. And when there is something wrong with Zone A, nodes & pods can be created in Zone B AUTOMATICALLY. So I can't just use `requiredDuringSchedulingIgnoredDuringExecution` to assign a node label.
And by the way, As I described earlier, I noticed `podtopologyspread`'s weight is 2, and source code comment says that because `This is a score coming from user preference`.  So I think `preferredDuringSchedulingIgnoredDuringExecution` is also a user preference, why not set it weight to 2 either?

**Comment by alculquicondor** [comment]
@ahg-g @Huang-Wei  thoughts?

**Comment by alculquicondor** [comment]
@DemonsLu note that topology spreading and node affinity compete in your scenario.

Where are your pods coming from? From a deployment or are they part of a service?
Note that, by default, these pods tend to spread. Starting from 1.19, you can actually lower the "strength" of spreading by setting a big maxSkew (or entirely disabling zone spreading).

Simply changing the weight of a plugin is a non-backwards compatible change.

**Comment by DemonsLu** [comment]
@alculquicondor Thanks for your response.
All my test pods coming from a deployment. 

Indeed, pods are tend to spread by default. But I think that this default behavior should change as expected after the `preferredDuringSchedulingIgnoredDuringExecution` is configured. If this change is not obvious, it will give users a feeling as if this configuration has not taken effect.

**Comment by DemonsLu** [comment]
And not only is there a competition between topology spreading and node affinity, but also all scorePlugins. So I think it's necessary assign a property priority. In my opinion, the user setting's priority should be higher than the priority of the system's internal scheduling.

**Comment by alculquicondor** [comment]
For completion, have you had a chance to test the E2E behavior in newer versions? In particular, 1.20, where we significantly changed the default spreading.

**Comment by ahg-g** [comment]
> @alculquicondor Thanks for your response.
> All my test pods coming from a deployment.
> 
> Indeed, pods are tend to spread by default. But I think that this default behavior should change as expected after the `preferredDuringSchedulingIgnoredDuringExecution` is configured. If this change is not obvious, it will give users a feeling as if this configuration has not taken effect.

You can disable default spreading by using [`ListDefaulting`](https://github.com/kubernetes/kubernetes/blob/c8fe1d9c0699f8d1fd93f47f2a62a4c83ccf5b6f/pkg/scheduler/apis/config/types_pluginargs.go#L97) and keeping [`DefaultConstraints`](https://github.com/kubernetes/kubernetes/blob/c8fe1d9c0699f8d1fd93f47f2a62a4c83ccf5b6f/pkg/scheduler/apis/config/types_pluginargs.go#L112) empty. If you disable default spreading, then `NodeAffinity` will have the highest impact on scoring the nodes.

**Comment by alculquicondor** [comment]
Note that OP is on EKS. Actually, you can just assign pod spreading to your PodSpec that only cares about nodes (and not zones). Setting any pod spreading disables the default spreading.

**Comment by alculquicondor** [comment]
Honestly, I think this is only a problem because OP is setting node affinity based on zones. That is kind of an anti-pattern, as it goes against HA. But if you really know what you are doing, disabling zone spreading should be the recommended way. We can improve the documentation to cover this case.

**Comment by DemonsLu** [comment]
@ahg-g @alculquicondor 

Thanks for your response and help, I will try `using ListDefaulting and keeping DefaultConstraints empty`  and do more test.

And yes, my OP is on EKS, and the latest k8s version is 1.19 on EKS now, so it's hard for me to test the behavior on v1.20...

And about this `setting node affinity based on zones`,  My needs are like this:

I don't want to make all pods deployed on one zone, because there is no doubt that It goes against HA. So I use `preferredDuringSchedulingIgnoredDuringExecution ` rather than `requiredDuringSchedulingIgnoredDuringExecution ` or `node selector`.

Under normal circumstances, most pods can be assigned to nodes with a specific label, and when these nodes collectively fail, I hope pods can be assigned to nodes with another specific label AUTOMATICALLY.

But now the situation is that when the remaining resources of two nodes with different labels are sufficient, using `preferredDuringSchedulingIgnoredDuringExecution` does not make all pods to be assigned to nodes which label is set on `preferredDuringSchedulingIgnoredDuringExecution`

**Comment by alculquicondor** [comment]
I understand your situation, but it still goes against HA. When thinking about HA you should not only care about the current state of your cluster (where there are enough nodes in one zone to "fulfill" your preference). You should also care about the possibility of your preferred zone going down. Then, you still have some backup pods in other zones. That's the reason for the default zone spreading.

So, if you are really sure that you don't need to guard against that scenario, you can disable zone spreading. But for most users, the existing behavior is safer.

**Comment by DemonsLu** [comment]
Thanks for your response, I think I understand why zone spreading must be considered even I config node affinity, It's a wonderful design. 
I will close this issue & pr soon when I finish my test.

**Comment by alculquicondor** [comment]
I'd encourage you to submit a PR to kubernetes/website to cover your use case and recommend disabling zone spreading through https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/

**Comment by DemonsLu** [comment]
Thank you for your patience, I will submit my PR when I sorted out my case statement

**Comment by mirekphd** [comment]
I have encountered the same problem bug in our settings (2 data centers in one multi-node Openshift (k8s v1.11) cluster), weighed 100 for Primary and 1 Secondary center. The problem is that with as little as 6 pod replicas the Secondary center always gets at least 1 pod running. Being forced to set a positive weight (of at least 1 percent) to Secondary center was an obvious hint at how the affinity will work... or rather fight with you:)

But I agree with @alculquicondor that it is safer when at least some pods are constantly available in the other zone/DC/region, as it it removes the dependency on the internal docker registry survival (at least under default `imagePullPolicy` for tagged images).

**Comment by ryshoooo** [comment]
> > @alculquicondor Thanks for your response.
> > All my test pods coming from a deployment.
> > Indeed, pods are tend to spread by default. But I think that this default behavior should change as expected after the `preferredDuringSchedulingIgnoredDuringExecution` is configured. If this change is not obvious, it will give users a feeling as if this configuration has not taken effect.
> 
> You can disable default spreading by using [`ListDefaulting`](https://github.com/kubernetes/kubernetes/blob/c8fe1d9c0699f8d1fd93f47f2a62a4c83ccf5b6f/pkg/scheduler/apis/config/types_pluginargs.go#L97) and keeping [`DefaultConstraints`](https://github.com/kubernetes/kubernetes/blob/c8fe1d9c0699f8d1fd93f47f2a62a4c83ccf5b6f/pkg/scheduler/apis/config/types_pluginargs.go#L112) empty. If you disable default spreading, then `NodeAffinity` will have the highest impact on scoring the nodes.

@ahg-g Do you have any tips/pointers as to how exactly we can disable the default spreading?

**Comment by ryshoooo** [comment]
> > > @alculquicondor Thanks for your response.
> > > All my test pods coming from a deployment.
> > > Indeed, pods are tend to spread by default. But I think that this default behavior should change as expected after the `preferredDuringSchedulingIgnoredDuringExecution` is configured. If this change is not obvious, it will give users a feeling as if this configuration has not taken effect.
> > 
> > 
> > You can disable default spreading by using [`ListDefaulting`](https://github.com/kubernetes/kubernetes/blob/c8fe1d9c0699f8d1fd93f47f2a62a4c83ccf5b6f/pkg/scheduler/apis/config/types_pluginargs.go#L97) and keeping [`DefaultConstraints`](https://github.com/kubernetes/kubernetes/blob/c8fe1d9c0699f8d1fd93f47f2a62a4c83ccf5b6f/pkg/scheduler/apis/config/types_pluginargs.go#L112) empty. If you disable default spreading, then `NodeAffinity` will have the highest impact on scoring the nodes.
> 
> @ahg-g Do you have any tips/pointers as to how exactly we can disable the default spreading?

NM, Found it here https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#cluster-level-default-constraints :)
