### ISSUE TITLE
Failing Test: pull-kubernetes-dependencies

### ISSUE THREAD

**Issue by gjkim42** [kubernetes/kubernetes#99642]
#### Which jobs are failing:

pull-kubernetes-dependencies

#### Anything else we need to know:

Success rate over time: 3h: **_5%_**, 12h: 62%, 48h: 79%
https://prow.k8s.io/?repo=kubernetes%2Fkubernetes&job=pull-kubernetes-dependencies

**Comment by gjkim42** [comment]
Maybe https://github.com/kubernetes/kubernetes/pull/99634 can fix this?

**Comment by neolit123** [comment]
/sig release testing
for triage

**Comment by BenTheElder** [comment]
/cc @justaugustus 
related to go version bump. it's passing 91% past 3 hours

**Comment by damemi** [comment]
Is this still being tracked? Success rate today shows 5% past 3 hours again

**Comment by BenTheElder** [comment]
See: https://github.com/kubernetes/kubernetes/pull/99655#issuecomment-789494480

/assign @justaugustus
