### ISSUE TITLE
Add metadata to images built from test/e2e/images

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#99648]
from https://github.com/kubernetes/kubernetes/pull/99631#issuecomment-788945533

Specify metadata during build vs. hardcoding in Dockerfile to avoid duplication/drift (since we have multiple for linux, windows, etc.)

Specify as ARG in Dockerfile(s) and then can pass in via `--build-arg`

Could include metadata such as:
- git_url
- git_commit
- etc.

/assign @claudiubelu @mkumatag 
Can you flesh this out a bit more for me? I can update the description with more of a proposed spec.  Or if nothing else, here's a tracking issue for following up on the linked comment.
/milestone v1.21
/priority important-soon
I'm assuming this is something you plan on getting done this release, but please feel free to kick this out if not

/wg k8s-infra
/sig testing
/area test
/area artifacts
(side note, I feel like it's time to namespace `area/test`, I want to tag this with something like `area/test/images`, but gonna use `area/artifacts` for now)

**Comment by claudiubelu** [comment]
Currently wondering where to add this metadata:

- image label: we can probably do it using ``docker buildx build --label``, and we'd only have to do it once in ``image-util.sh``.
- image ENV, similar to how it's being done here: https://github.com/kubernetes/test-infra/blob/master/images/gcb-docker-gcloud/Dockerfile#L24 (but this will require touching all the Dockerfiles too)
- both.

**Comment by spiffxp** [comment]
Whatever makes it easier to dump in job logs and export as metadata or some other artifact for the job run

**Comment by desponda** [comment]
@spiffxp is this still being targeted for 1.21 Milestone?

**Comment by spiffxp** [comment]
I'm going to defer to @claudiubelu for the answer as I don't have time to implement this. I think this is reasonable to defer to Test Freeze, but I also don't see this as required for v1.21.

**Comment by mkumatag** [comment]
I think we can defer to next release, need a proper brainstorming about how and what part..

**Comment by claudiubelu** [comment]
Indeed, we can defer it since it's not critical at the moment. It's not breaking anything, but it would still be nice to have. I can take a look at it after the freeze.
