### ISSUE TITLE
Kubelet doesn't use rotated client cert on start

### ISSUE THREAD

**Issue by champtar** [kubernetes/kubernetes#99645]
#### What happened:
Testing how kubelet client rotation works, I discovered that on startup kubelet uses the cert in `--kubeconfig` (`/etc/kubernetes/kubelet.conf`) and not the new cert in ` --cert-dir` (`/var/lib/kubelet/pki/kubelet-client-current.pem`)

This prevent kubelet to start
```
kubelet[740513]: I0101 14:32:07.024330  740513 server.go:838] Client rotation is on, will bootstrap in background
kubelet[740513]: E0101 14:32:07.026281  740513 bootstrap.go:265] part of the existing bootstrap client certificate is expired: 2022-03-01 14:19:03 +0000 UTC
kubelet[740513]: F0101 14:32:07.026322  740513 server.go:274] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
```

#### What you expected to happen:
kubelet uses the latest client certificate

#### How to reproduce it (as minimally and precisely as possible):
1. Deploy a 1 node cluster with kubespray (kubeadm should do)
2. stop ntpd/chronyd
3. set the date 11 months in the future
4. renew master certs
```
kubeadm alpha certs renew all
/usr/bin/cp /etc/kubernetes/admin.conf /root/.kube/config
crictl pods --namespace kube-system --name 'kube-scheduler-*|kube-controller-manager-*|kube-apiserver-*' -q | xargs crictl rmp -f
```
5. restart kubelet
```
systemctl restart kubelet.service
```
6. Confirm that you have a new client cert
```
# ls /var/lib/kubelet/pki/
kubelet-client-2021-03-01-14-18-38.pem  kubelet-client-2022-02-02-14-05-10.pem kubelet-client-current.pem  kubelet.crt  kubelet.key
```
7. push the date 11 months more in the future and restart kubelet
kubelet fails to start because it uses the cert embedded in `/etc/kubernetes/kubelet.conf` instead of `/var/lib/kubelet/pki/kubelet-client-current.pem`
```
kubelet[740513]: I0101 14:32:07.024330  740513 server.go:838] Client rotation is on, will bootstrap in background
kubelet[740513]: E0101 14:32:07.026281  740513 bootstrap.go:265] part of the existing bootstrap client certificate is expired: 2022-03-01 14:19:03 +0000 UTC
kubelet[740513]: F0101 14:32:07.026322  740513 server.go:274] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
```

#### Anything else we need to know?:

Both `--bootstrap-kubeconfig="/etc/kubernetes/bootstrap-kubelet.conf"` and `--kubeconfig="/etc/kubernetes/kubelet.conf"` are set, if I remove `--bootstrap-kubeconfig` kubelet boots but fails to renew the cert
```
kubelet[722691]: I0101 14:00:29.520161  722691 certificate_manager.go:409] Rotating certificates
kubelet[722691]: E0101 14:00:29.522508  722691 certificate_manager.go:434] Failed while requesting a signed certificate from the master: cannot create certificate signing request: Unauthorized
```

Here an easy fix:
```
kubectl config --kubeconfig=/etc/kubernetes/kubelet.conf set-credentials system:node:<nodename> --client-certificate=/var/lib/kubelet/pki/kubelet-client-current.pem --client-key=/var/lib/kubelet/pki/kubelet-client-current.pem
```
Also I noticed that `/etc/kubernetes/kubelet.conf` is RSA where `kubelet-client-current.pem` is EC/P-256

#### Environment:
- Kubernetes version (use `kubectl version`): v1.18.15 (I can retest in more recent version but haven't seen anything in the release notes)
- Cloud provider or hardware configuration: VM
- OS (e.g: `cat /etc/os-release`): `CPE_NAME="cpe:/o:centos:centos:8"`
- Kernel (e.g. `uname -a`): `4.18.0-240.10.1.el8_3.x86_64`
- Install tools: `kubespray 2.15`

**Comment by champtar** [comment]
/sig cluster-lifecycle
(not sure if this is more kubelet or kubeadm)

**Comment by neolit123** [comment]
> Testing how kubelet client rotation works, I discovered that on startup kubelet uses the cert in --kubeconfig (/etc/kubernetes/kubelet.conf) and not the new cert in --cert-dir (/var/lib/kubelet/pki/kubelet-client-current.pem)

is the kubelet.conf embedding certificates?

see the second warning under here:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#check-certificate-expiration

**Comment by neolit123** [comment]
you can call `kubeadm init phase kubelet-finalize. ...` on the same node to make the kubelet.conf point to the rotatable file.

**Comment by neolit123** [comment]
i don't see a core bug here.

> Install tools: kubespray 2.15

i missed that you are using kubespray, which uses kubeadm.
please triage any issues with the kubespray issue tracker first:
https://github.com/kubernetes-sigs/kubespray

/kind support
/close

**Comment by champtar** [comment]
Thanks @neolit123, kubespray indeed doesn't call `kubelet-finalize` anywhere, I'll go look at how to fix that

**Comment by neolit123** [comment]
@champtar like i said, newer versions of `kubeadm init` do this automatically.
this might be the result of an old cluster being upgrade using `kubeadm upgrade` but the `kubelet.conf` is remaining stale.

the manual step in https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#check-certificate-expiration
or calling the `kubelet-finalize` on a node is required.

**Comment by champtar** [comment]
It was a fresh deployment of k8s 1.18 / kubespray 2.15, I'm doing a fresh deployment of k8s 1.20 / kubespray master right now, but maybe kubespray is using kubeadm in weird ways / include old workarounds that leave us with `kubelet.conf` having embedded certs instead of pointing to `kubelet-client-current.pem`.

**Comment by champtar** [comment]
Found the culprit: https://github.com/kubernetes-sigs/kubespray/blob/668bbe0528daab9f9001a64d1ddfe33694adc763/roles/kubernetes/control-plane/tasks/kubeadm-fix-apiserver.yml#L18-L22
Kubespray regenerate the conf files using kubeadm to make sure the server is up to date
Thanks for the help @neolit123 and sorry for the spam

**Comment by neolit123** [comment]
it would make sense to just include the kubelet-finalize phase in there too.

**Comment by champtar** [comment]
I prefer to just change the server using one of lineinfile/sed/kubectl so next time there is a new step like kubelet-finalize we don't break again.
