### ISSUE TITLE
kubelet: setting a negative value in containerLogMaxSize raises an error

### ISSUE THREAD

**Issue by johanfleury** [kubernetes/kubernetes#99650]
Setting a negative value in `containerLogMaxSize` currently makes kubelet crash with a stack trace.

The [`parseMaxSize` function](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/logs/container_log_manager.go#L132) function raises an error when the value is negative, but the comment on [`LogRotatePolicy.MaxSize`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/logs/container_log_manager.go#L69) says that setting a negative value disables log rotation.

At the moment there’s no way to disable log rotation and I believe removing lines 141 to 143 from `parseMaxSize`, would allow this.

**Comment by johanfleury** [comment]
/sig node

(I guess)

**Comment by neolit123** [comment]
/area kubelet

> Setting a negative value in containerLogMaxSize currently makes kubelet crash with a stack trace.

can you show the stack trace?

**Comment by johanfleury** [comment]
The stack trace is 5000 lines long and apart from the following message, I don’t think it is relevant:

```
Mar 02 16:45:57 worker03 kubelet[11512]: F0302 16:45:57.029049   11512 server.go:269] failed to run Kubelet: failed to create kubelet: failed to initialize container log manager: failed to parse container log max size "-1": negative max log size -1
```

**Comment by wangyysde** [comment]
@johanfleury You can try to quote the value with double quotation when the value is negative, like the following:
`syncFrequency: 0s
volumeStatsAggPeriod: 0s
containerLogMaxSize: "-1"`

**Comment by CaoDonghui123** [comment]
@wangyysde I tried "-1", but still error

**Comment by pacoxu** [comment]
> @johanfleury You can try to quote the value with double quotation when the value is negative, like the following:
> `syncFrequency: 0s volumeStatsAggPeriod: 0s containerLogMaxSize: "-1"`

volumeStatsAggPeriod: 0s equals to volumeStatsAggPeriod: 1m
volumeStatsAggPeriod: -1s means disable

**Comment by wangyysde** [comment]
@CaoDonghui123 Which Kubernetes version have you installed? As if on my v1.19.4 system,no errors occured after I quoted the value with double quotation.

**Comment by CaoDonghui123** [comment]
@wangyysde v1.20.2

**Comment by johanfleury** [comment]
I’m on v1.20.4.

> You can try to quote the value with double quotation when the value is negative

That’s already the case.

Also, `containerLogMaxSize` can only be set as a string in kubelet’s configuration, trying to set an integer will raise a parsing error (see [staging/src/k8s.io/kubelet/config/v1beta1/types.go#L719](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubelet/config/v1beta1/types.go#L719)).

The problem is not with the configuration, I’ve linked to the exact line in the code that checks for a negative value and raises the error.

**Comment by wzshiming** [comment]
@johanfleury 
Maybe you can try to disable this featureGate `CRIContainerLogRotation`

**Comment by johanfleury** [comment]
Seem to work, I don’t know why I didn’t find this feature gate before.
