### ISSUE TITLE
Graceful Node Shutdown E2E test failing due to incorrect focus test name 

### ISSUE THREAD

**Issue by bobbypage** [kubernetes/kubernetes#99667]
#### Which jobs are failing:

ci-kubernetes-node-kubelet-serial-graceful-node-shutdown

#### Which test(s) are failing:

GracefulNodeShutdown test

#### Since when has it been failing:

Since https://github.com/kubernetes/test-infra/pull/20937

#### Testgrid link:

https://testgrid.k8s.io/sig-node-kubelet#kubelet-serial-gce-e2e-graceful-node-shutdown

#### Reason for failure:

```
I0303 01:01:26.727] --- FAIL: TestE2eNode (0.00s)
I0303 01:01:26.727] panic: regexp: Compile(`\[[NodeAlphaFeature:GracefulNodeShutdown\]`): error parsing regexp: missing closing ]: `[NodeAlphaFeature:GracefulNodeShutdown\]` [recovered]
I0303 01:01:26.727] 	panic: regexp: Compile(`\[[NodeAlphaFeature:GracefulNodeShutdown\]`): error parsing regexp: missing closing ]: `[NodeAlphaFeature:GracefulNodeShutdown\]`
```

I think there might be a typo with the two opening `[` brackets:

https://github.com/kubernetes/test-infra/blob/25fbbe2109c53aa26b854f35dc5977a2c80bf538/config/jobs/kubernetes/sig-node/node-kubelet.yaml#L380

**Comment by wzshiming** [comment]
Ohhh, my mistake, I didn't notice the extra '['

**Comment by bobbypage** [comment]
No worries, should be a simple fix :)
