### ISSUE TITLE
[sig-node] ineffassign potential race between informer and pod create in test code

### ISSUE THREAD

**Issue by supriya-premkumar** [kubernetes/kubernetes#99673]
#### What happened:
ineffassign was added to the standard linter script as a part of [this PR](https://github.com/kubernetes/kubernetes/pull/99288) and flagged it. 
Creating a sig-node issue as per suggestion [here](https://github.com/kubernetes/kubernetes/pull/99288#discussion_r580297341)

Running ineffassign reports the following issues.
```
./hack/verify-golangci-lint.sh
installing golangci-lint
running golangci-lint
test/e2e/node/pods.go:78:4: ineffectual assignment to `options` (ineffassign)
                        options = metav1.ListOptions{
                        ^
test/e2e/common/pods.go:247:3: ineffectual assignment to `options` (ineffassign)
                options = metav1.ListOptions{
                ^
test/e2e/scheduling/limit_range.go:75:3: ineffectual assignment to `options` (ineffassign)
                options = metav1.ListOptions{
                ^
```
#### What you expected to happen:
./hack/verify-golangci-lint.sh with ineffassign enabled should be successful

#### How to reproduce it (as minimally and precisely as possible):
./hack/verify-golangci-lint.sh

**Comment by adisky** [comment]
> test/e2e/node/pods.go:78:4: ineffectual assignment to `options` (ineffassign)
                        options = metav1.ListOptions{

I think it can be removed, I found the this discussion from @liggitt https://github.com/kubernetes/kubernetes/pull/73064#discussion_r258123083

**Comment by ehashman** [comment]
/assign @adisky

can you take a look at this?

**Comment by ehashman** [comment]
/remove-lifecycle stale

@adisky will create a PR to remove this and we can discuss further there.

**Comment by BenTheElder** [comment]
somehow I thought we were running ineffassign in CI, that probably deserves it's own issue, I imagine it will be painful to enable this repo wide, but, it seems worthwhile as it will probably surface more bugs like this.
