### ISSUE TITLE
[ERROR] Recovered from panic in server: "dns://:53"

### ISSUE THREAD

**Issue by yingjunxu** [kubernetes/kubernetes#99683]
#### What happened:
kubectl logs -n kube-system -l k8s-app=kube-dns

#### What you expected to happen: 

Recovered from panic in server: "dns://:53"

#### Anything else we need to know?:
coredns pod is running
[foot@p_foot-master1 ~]$ kubectl get pod -n kube-system
NAME                                      READY   STATUS              RESTARTS   AGE
coredns-69db54b679-7kfkp                  1/1     Running             0          45m
coredns-69db54b679-twjvg                  1/1     Running             0          45m
coredns-69db54b679-vz89j                  1/1     Running             0          45m
#### Environment:
- Kubernetes version (use `kubectl version`):1.15.6
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):Redhat 7.7
- Kernel (e.g. `uname -a`):3.10.0-1062.el7.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):vmware nsx
- Others:

**Comment by neolit123** [comment]
try logging this issues in the CoreDNS repo first:
https://github.com/coredns/coredns

if the maintainers indicate that this is an upstream kubernetes problem, re-open this ticket.

/close
