### ISSUE TITLE
Container Health check set

### ISSUE THREAD

**Issue by HarshitaJha** [kubernetes/kubernetes#99692]
This is a question, not an issue. 
We are using docker benchmark on our K8s cluster and checking if our containers are compliant by CIS standards. One of the docker benchmarks says that all containers should have the docker healthcheck instruction so that the status of the container, whether healthy (ready for use) or not shows up in the docker inspect command. I was wondering if you could enlighten me if there there is any Kubernetes parameter which can over-write the docker healthcheck and show the health status of the container under docker inspect?
/sig Security

**Comment by heqg** [comment]
So far, I have not found any parameters that can be overwritten, but there are two prs have been submitted in the community, so the docker health check will no longer take effect in the kubenetes cluster.

for：service pods
https://github.com/kubernetes/kubernetes/pull/50796/files

for: sanbox pods
https://github.com/kubernetes/kubernetes/pull/98552
https://github.com/kubernetes/kubernetes/issues/98497

**Comment by HarshitaJha** [comment]
Thank you @heqg , this was helpful.
