### ISSUE TITLE
NodeLocal DNSCache breaks external DNS updates

### ISSUE THREAD

**Issue by stephan2012** [kubernetes/kubernetes#99712]
#### What happened:

Setup [NodeLocal DNSCache as documented](https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/). While this works and avoids DNS resolution errors when nodes or sites are lost, it also prevents RFC 2136 connections from [external-dns](https://github.com/kubernetes-sigs/external-dns) to cluster-external DNS servers.

```text
time="2021-03-03T14:06:35Z" level=info msg="Instantiating new Kubernetes client"
time="2021-03-03T14:06:35Z" level=info msg="Using inCluster-config based on serviceaccount-token"
time="2021-03-03T14:06:35Z" level=info msg="Created Kubernetes client https://172.31.0.1:443"
time="2021-03-03T14:06:37Z" level=info msg="Configured RFC2136 with zone 'xxx.company.com.' and nameserver 'n0211.xxx.company.com:53'"
time="2021-03-03T14:31:58Z" level=error msg="failed to fetch records via AXFR: dial tcp: i/o timeout"
time="2021-03-03T14:32:59Z" level=error msg="failed to fetch records via AXFR: dial tcp: i/o timeout"
time="2021-03-03T14:34:00Z" level=error msg="failed to fetch records via AXFR: dial tcp: i/o timeout"
time="2021-03-03T14:35:00Z" level=error msg="failed to fetch records via AXFR: dial tcp: i/o timeout"
time="2021-03-03T14:36:00Z" level=error msg="failed to fetch records via AXFR: dial tcp: i/o timeout"
time="2021-03-03T14:37:00Z" level=error msg="failed to fetch records via AXFR: dial tcp: i/o timeout"
time="2021-03-03T14:38:01Z" level=error msg="failed to fetch records via AXFR: dial tcp: i/o timeout"
```

Looks like the netfilter rules explicitly deny requests to all other DNS connections:

```text
Chain INPUT (policy ACCEPT 201 packets, 177K bytes)
 pkts bytes target     prot opt in     out     source               destination         
6917K 4056M cali-INPUT  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:Cz_u1IQiXIMmKD4c */
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            172.31.0.10          udp dpt:53
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            172.31.0.10          tcp dpt:53
    2   174 ACCEPT     udp  --  *      *       0.0.0.0/0            169.254.20.10        udp dpt:53
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            169.254.20.10        tcp dpt:53
4002K 2803M KUBE-FIREWALL  all  --  *      *       0.0.0.0/0            0.0.0.0/0           

[…]
Chain OUTPUT (policy ACCEPT 391 packets, 229K bytes)
 pkts bytes target     prot opt in     out     source               destination         
7002K 1893M cali-OUTPUT  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:tVnHkvAo15HuiPy0 */
    0     0 ACCEPT     udp  --  *      *       172.31.0.10          0.0.0.0/0            udp spt:53
    0     0 ACCEPT     tcp  --  *      *       172.31.0.10          0.0.0.0/0            tcp spt:53
 5852 1068K ACCEPT     udp  --  *      *       169.254.20.10        0.0.0.0/0            udp spt:53
    0     0 ACCEPT     tcp  --  *      *       169.254.20.10        0.0.0.0/0            tcp spt:53
7007K 1894M KUBE-FIREWALL  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
```

#### What you expected to happen:

NodeLocal DNSCache should allow connections to (selected) external DNS servers so applications and services can advertise themselves.

#### How to reproduce it (as minimally and precisely as possible):

- Deploy NodeLocal DNSCache as described
- Connect to an external DNS server (e.g., `host 8.8.8.8 8.8.8.8`)

#### Environment:
- Kubernetes version (use `kubectl version`): `v1.19.8`
- Cloud provider or hardware configuration: On-premises, bare-metal
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.5 LTS
- Kernel (e.g. `uname -a`): `Linux n0214 5.4.0-60-generic #67~18.04.1-Ubuntu SMP Tue Jan 5 22:01:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): Calico
- Others: External DNS server is BIND9

(Possibly) related issues:

- https://github.com/projectcalico/calico/issues/3795
- https://github.com/kubernetes/kubernetes/issues/98758

/sig network

**Comment by stephan2012** [comment]
Some more testing showed that NodeLocal DNSCache does not really block traffic to the external DNS server but changes DNS resolution of external FQDN somehow: Changing the external DNS server to an absolute FQDN (e.g., `--rfc2136-host=my-dns-server.company.com.` instead of `my-dns-server.company.com`, note the trailing dot) makes it work again.

For other Pods I noticed occasional delays for FQDN resolution even if the same name has been resolved quickly a second before. With some Alpine Linux based Pods, hostname resolution of cluster-external names sometimes fails completely and only absolute names work.

Weird. I cannot observe any of these effects without NodeLocal DNSCache so far.

**Comment by prameshj** [comment]
@stephan2012 any metrics from node-local-dns that look interesting? Any logs in node-local-dns about i/o timeouts?

**Comment by prameshj** [comment]
Also, what does the dynamic request look like? Does externalDNS send that request to nodelocalip:53 or to the external DNS server, port 53?

**Comment by stephan2012** [comment]
> Also, what does the dynamic request look like? Does externalDNS send that request to nodelocalip:53 or to the external DNS server, port 53?

Yes, external-dns sends update requests via the dynamic DNS protocol on port 53 directly to the external DNS server.

**Comment by thockin** [comment]
Do we have updates or news on this?

**Comment by prameshj** [comment]
> Yes, external-dns sends update requests via the dynamic DNS protocol on port 53 directly to the external DNS server.

Then node-local-dns should not be on the datapath right? Not sure I understand what the issue is. Any packet captures you can share in scenario where NodeLocalDNS is enabled vs not?

**Comment by stephan2012** [comment]
> Then node-local-dns should not be on the datapath right?

Right. Not sure what the intention on the design was: Catch all DNS queries and redirect to the cache, or just kube-dns queries?

> Not sure I understand what the issue is. Any packet captures you can share in scenario where NodeLocalDNS is enabled vs not?

I'll try to arrange a test setup next week. It should include traffic to the external DNS server, I guess? Anything else?

**Comment by thockin** [comment]
Hi!  Just pinging this bug to keep it alive and see if there are updates

**Comment by prameshj** [comment]
> Right. Not sure what the intention on the design was: Catch all DNS queries and redirect to the cache, or just kube-dns queries?

It should just catch queries destined to kube-dns IP address or to the special link-local IP address exclusively reserved for node-local-dns.

> I'll try to arrange a test setup next week. It should include traffic to the external DNS server, I guess? Anything else?

traffic to external DNS server will be a good start. From the description so far, node-local-dns shouldn't be on the path at all.

**Comment by prameshj** [comment]
The other thing that might be related - if requests to externalDNS are being configured via a kube-dns configmap stubdomain, then those will go through node-local-dns. Could that be applicable here?

**Comment by prameshj** [comment]
Any updates on this?

**Comment by stephan2012** [comment]
> The other thing that might be related - if requests to externalDNS are being configured via a kube-dns configmap stubdomain, then those will go through node-local-dns. Could that be applicable here?

Not really sure that I get your point. There are no requests being send to external-dns. Instead, external-dns scrapes data in services and ingresses and registers the discovered name with the external IP address in an external (public) DNS service.

**Comment by prameshj** [comment]
> Not really sure that I get your point. There are no requests being send to external-dns. Instead, external-dns scrapes data in services and ingresses and registers the discovered name with the external IP address in an external (public) DNS service.

Then, I really don't see why node-local-dns is changing anything here. Is external-dns running as a pod within the cluster? It is making HTTP/s calls to the external public DNS service to configure it with services and ingress info? If yes, node-local-dns should not be in the path at all.

**Comment by prameshj** [comment]
Closing this since we don't have enough data if this is a bug in NodeLocalDNS. Please reopen if needed.

/close
