### ISSUE TITLE
RemoveStatusCondition panics with an empty slice

### ISSUE THREAD

**Issue by miquella** [kubernetes/kubernetes#99714]
#### What happened:

Attempting to remove a status condition from an already empty slice panics.

```plaintext
panic: runtime error: makeslice: cap out of range

goroutine 1 [running]:
k8s.io/apimachinery/pkg/api/meta.RemoveStatusCondition(0xc000157f60, 0x93ec68, 0x3)
        /home/mark/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/api/meta/conditions.go:63 +0x73
main.main()
        /home/mark/src/testing/main.go:10 +0x52
exit status 2
```

#### What you expected to happen:

An empty slice should be removed (i.e. removed idempotently) and without panicking.

#### How to reproduce it (as minimally and precisely as possible):

```go
package main

import (
	"k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func main() {
	conditions := []metav1.Condition{}
	meta.RemoveStatusCondition(&conditions, "Foo")
}
```

#### Anything else we need to know?:

Originally found with `k8s.io/apimachinery@v0.20.1`, reproduced with `k8s.io/apimachinery@latest` (`v0.20.4` at the time of writing)

#### Environment:
- Kubernetes version (use `kubectl version`): N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): Pop!_OS 20.04 LTS
- Kernel (e.g. `uname -a`): `Linux mark-l 5.8.0-7642-generic #47~1612288990~20.04~b8113e7-Ubuntu SMP Wed Feb 3 02:25:36 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A

**Comment by liggitt** [comment]
cc @deads2k
