### ISSUE TITLE
Ability to reserve hugepages for system resources

### ISSUE THREAD

**Issue by spkane** [kubernetes/kubernetes#99715]
#### What would you like to be added:

The `--system-reserved` should allow you to reserve hugepages, if they exist on the system

- **Kubelet Flag**: `--system-reserved=[cpu=100m][,][memory=100Mi][,][ephemeral-storage=1Gi][,][pid=1000]`
  - **see**: https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#system-reserved
  - **see**: https://kubernetes.io/docs/tasks/manage-hugepages/scheduling-hugepages/

#### Why is this needed:

For this use case, we are enabling and managing [AWS Nitro Enclaves](https://aws.amazon.com/ec2/nitro/nitro-enclaves/) on a few enclave enabled instances in an EKS cluster on AWS.

This tooling for AWS Nitro Enclave includes a service called the [Nitro Enclave Allocator](https://github.com/aws/aws-nitro-enclaves-cli/blob/main/bootstrap/nitro-enclaves-allocator.service) which takes [a defined number of vCPUs offline and converts a defined memory chunk into at least one huge page](https://github.com/aws/aws-nitro-enclaves-cli/blob/main/bootstrap/allocator.yaml). This is basically reserving these AWS instance resources for the secure enclave VM.

Glancing at t diff of the `kubelet`'s view of the Allocatable Resource on the node before and after this service is run, it looks like this (this example reserved 2 CPU and 1GB of memory):

```diff
-  cpu:                             4
+  cpu:                             2
-  hugepages-1Gi:                   0
+  hugepages-1Gi:                   1Gi
-  memory:                          31736096Ki
+  memory:                          30687520Ki
```

In general, it looks like the `kubelet` dynamically does the right thing regarding CPU and memory availability, but in this case I want to be able to tell the `kubelet` to reserve at least one `hugepages-1Gi` for the system if it exists (so a pod can not use that huge page). The kubelet probably should not care if there are no hugepages available (maybe just log a warning), it should just reserve one if it is there. As far as I am aware there is no way to do something like this without simply being careful about what order things are spun up, etc.

**Comment by chenyw1990** [comment]
/assign
I'm interested in this feature and I'll try to add it.

**Comment by spkane** [comment]
> I'm interested in this feature and I'll try to add it.

@chenyw1990 I am just curious if you have had any time to take a look at this and if so, how that was going?

**Comment by cynepco3hahue** [comment]
I am pretty sure @odinuge worked on something related to add hugepage under the kube and system reserved.

**Comment by odinuge** [comment]
> I am pretty sure @odinuge worked on something related to add hugepage under the kube and system reserved.

Yes! I did that almost two years ago, but it turned stall in lack of approval (I have cherry-picked it and have been using it myself since then). It should be good to go, if people are interested. I can reopen it in case someone are interested in reviewing and getting it merged! :smile: 

The PR: https://github.com/kubernetes/kubernetes/pull/83541

**Comment by spkane** [comment]
@chenyw1990 & @odinuge It appears that you both have worked of functionality around this. Do your PRs duplicate or compliment each other? It would be great to see your work around this issue get into 1.22
