### ISSUE TITLE
Only system-node-critical pods should have low OOM Score

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#99727]
#### What would you like to be added:
I'd like only `system-node-critical` pods to have low OOM score -997.

#### Why is this needed:
https://github.com/kubernetes/kubernetes/pull/73758 introduced a change which ensured all the critical priority classes will have a low OOM score -997. While this helped in relating OOM score to priority of pod, it also allows containers in `system-cluster-critical` pods to have -997 OOM score, making them one of the last processes to be OOMKilled. By definition `system-cluster-critical` pods can be scheduled elsewhere if there is crunch on the node where as `system-node-critical` pods cannot be rescheduled. This was the reason for `system-node-critical` to have higher priority  value than `system-cluster-critical`. So, I think it makes sense for  only `system-node-critical` pods to have low OOM score of -997.

/sig node

cc @rphillips @sjenning

**Comment by sjenning** [comment]
i think this is reasonable since `system-node-critical` is higher priority than `system-cluster-critical` and this would make a distinction between the two making `system-cluster-critical` killable but assured to be rescheduled

**Comment by smarterclayton** [comment]
Note that oomscore has nothing to do with rescheduling.  Eviction looks at priority, oomscore simply controls the killer.  I think that strengthens the argument - the point of node-critical is makinng sure it's killed last, but even then that should be a rare, rare case (a memory leak in kube-proxy will blow out the workload, but if we just killed kube-proxy everything would heal).  We may want to go back to the original justifications for -99x oomscore in system-node-critical and make sure we're still aligning correctly.
