### ISSUE TITLE
Error starting container: Post http://unix.sock/containers/create HTTP/1.x transport connection broken: malformed HTTP response \"\\x00\\x00\\"

### ISSUE THREAD

**Issue by rameshb444** [kubernetes/kubernetes#99722]
Hi,

We are using Azure Kubernetes Service (AKS) to run our Blockchain Hyperledger Fabric application.
Recently we have upgraded kubernetes version from 1.17 to 1.19.7, later we come to know that docker has deprecated in 1.19* versions.
So instead of docker, we are using containerD as runtime.

For that we have done below changes in our deployment file. **Changed unix:///host/var/run/docker.sock to unix:///run/containerd/containerd.sock**
![image](https://user-images.githubusercontent.com/19839852/109861449-96e10a00-7c5f-11eb-9ba2-77b63798a3ea.png)

After creating the pod, we are getting the below error when I try to query 

**Error: endorsement failure during query. response: status:500 message:"failed to execute transaction 84380a33510f814525e871c5418f4761fe6b21c2db528ce2e31b60ba64d591ff: error starting container: error starting container: Post http://unix.sock/containers/create?name=nid1-testcont-cc-4.3: net/http: HTTP/1.x transport connection broken: malformed HTTP response \"\\x00\\x00\\x06\\x04\\x00\\x00\\x00\\x00\\x00\\x00\\x05\\x00\\x00@\\x00\""** 

My issue is I can see containerd.service is active and running, but why I am unable to start the container?
Or Let me know if I need to do any other changes in the deployment file.

**Comment by neolit123** [comment]
> Recently we have upgraded kubernetes version from 1.17 to 1.19.7, later we come to know that docker has deprecated in 1.19* versions.

this is not true, the built-in docker support in the kubelet is deprecated and it will one day move out into standalone binary / service called "dockershim". kubernetes will continue supporting docker.

your are mounting the docker socket from the host which is still a valid use case.

> Error: endorsement failure during query. response: status:500 message:"failed to execute transaction 84380a33510f814525e871c5418f4761fe6b21c2db528ce2e31b60ba64d591ff: error starting container: error starting container: Post http://unix.sock/containers/create?name=nid1-testcont-cc-4.3: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x00\x00\x06\x04\x00\x00\x00\x00\x00\x00\x05\x00\x00@\x00""

this seems to me like something that containerd does not support.

try asking in https://github.com/containerd/containerd and if they think this is a kubernetes bug (unlikely) re-open this issue.

/close
