### ISSUE TITLE
Provide an option to configure watch or listener on ConfigMap and Secret resource

### ISSUE THREAD

**Issue by srinivasev** [kubernetes/kubernetes#99770]
#### What would you like to be added:
Provide an annotation or the way to configure external actions for implementing an internal logic when there is a change in the Configmap / Secret resource object.

kind: ConfigMap
....
data: 
    key1:val1
    key2:val2

When there is a change in ConfigMap resource (key3:val3 is added), provide an annotation/way to configure some action where internal logic can be implemented. My internal logic for example can be rollout restart deployment to take these changes freshly.

#### Why is this needed:
Watching the mounted file system continuously inside the pod/container with a kubelet sync period + cache propagation delay may introduce some delay. This will affect the application logic implementation which has to happen immediately.

@kubernetes/sig-api-machinery-proposals
@derekwaynecarr @dims @johnbelamaric 
@kubernetes/sig-architecture-feature-requests

**Comment by neolit123** [comment]
isn't `kubectl get cm <cm-name> --watch` sufficient?

**Comment by fedebongio** [comment]
assign @yliaog 
/triage accepted

**Comment by yliaog** [comment]
'watch' on ConfigMap or Secret would work

**Comment by srinivasev** [comment]
Required some kind of push model instead of pull model for knowing the change/updates in a resource. As the watch command cannot be invoked from each and every java/python microservice pod brought up during the deployments.
