### ISSUE TITLE
Scheduler: parse pod's node affinity once for PodTopologySpread plugin

### ISSUE THREAD

**Issue by gavinfish** [kubernetes/kubernetes#99786]
Currently PodTopologySpread plugin parses  NodeSelector and NodeAffinity for each nodes. We can just parse them with a pod in one round and check all the nodes.

/cc @Huang-Wei @alculquicondor 
/assign
/sig scheduling

**Comment by alculquicondor** [comment]
Are you referring to Filter? IIRC, we did that for Score, but didn't have time to do it for Filter.

**Comment by alculquicondor** [comment]
Oh, I'm just getting confused with the constraints, rather than affinity and node selector.

Can we split this in 2 PRs, one for Filter and 1 for Score?

@AliceZhang2016 could work in one of them.

/triage accepted

**Comment by alculquicondor** [comment]
And can you @gavinfish take Score right away?

**Comment by gavinfish** [comment]
> And can you @gavinfish take Score right away?

Sure

**Comment by Huang-Wei** [comment]
> Currently PodTopologySpread plugin parses NodeSelector and NodeAffinity for each nodes. We can just parse them with a pod in one round and check all the nodes.

SG. Thanks for driving.

**Comment by mlavacca** [comment]
@alculquicondor the filtering PR is already taken by @AliceZhang2016? If not, may I take it?

**Comment by AliceZhang2016** [comment]
@mlavacca Hi, I'm working on this now, and still waiting #99833 to be merged, which I think can make filtering PR more easier to write. Thanks for your interest.
/assign
