### ISSUE TITLE
kubectl stop rc fails to delete all replicas

### ISSUE THREAD

**Issue by satnam6502** [kubernetes/kubernetes#9979]
```
$ kubectl stop rc counter
replicationcontrollers/counter
$ kubectl get pods | grep counter
counter-3ec6w                             0/1       Failed    0          1h
counter-4b1vq                             0/1       Failed    0          1h
counter-fs1b8                             0/1       Failed    0          1h
counter-odzgg                             0/1       Failed    0          1h
counter-vd7fm                             0/1       Failed    0          1h
$ kubectl get pods | grep counter
counter-3ec6w                             0/1       Failed    0          1h
counter-4b1vq                             0/1       Failed    0          1h
counter-fs1b8                             0/1       Failed    0          1h
counter-odzgg                             0/1       Failed    0          1h
counter-vd7fm                             0/1       Failed    0          1h
$ kubectl get pods | grep counter
counter-3ec6w                             0/1       Failed    0          1h
counter-4b1vq                             0/1       Failed    0          1h
counter-fs1b8                             0/1       Failed    0          1h
counter-odzgg                             0/1       Failed    0          1h
counter-vd7fm                             0/1       Failed    0          1h
```

**Comment by bgrant0607** [comment]
cc @bprashanth

**Comment by satnam6502** [comment]
I was able to kill them manually with `kubectl delete pod`

**Comment by bprashanth** [comment]
The rc doesn't care about failed and succeeded pods. 
Fyi delete rc will do confusing things if you try to delete an rc just after creating it, there's a fix in flight for that (https://github.com/GoogleCloudPlatform/kubernetes/pull/9739, https://github.com/GoogleCloudPlatform/kubernetes/issues/9147).

**Comment by satnam6502** [comment]
So once I am done with my RC how do I clean up after it? I need to do a `stop` and then I need to find all the succeeded and failed pods and kill them manually?

**Comment by bprashanth** [comment]
I believe the intent here is we want people to keep the history (logs, etc) of these pods and manage their lifespans explicitly (@bgrant0607 correct me if I'm wrong). You can put your things in a ns and delete that, it will recursively delete resources.

**Comment by bgrant0607** [comment]
We should eventually GC terminated pods. #7660

**Comment by bgrant0607** [comment]
Arguably, stop rc (and delete rc, now that it kills pods) could delete terminated pods matching the rc selector by default.

**Comment by satnam6502** [comment]
@bprashanth do you want to take this?

**Comment by bprashanth** [comment]
> Arguably, stop rc (and delete rc, now that it kills pods) could delete terminated pods matching the rc selector by default.

I think this should be a post 1.0 discussion, though I'm not against considering it for 1.0. Mostly because stop and delete have always noticed the status.Replicas on an rc, which has never considered failed pods. Changing this should be relatively easy, though if someone should want the behavior we have today they'd have to be careful enough to grab the history of those pods before deleting the rc.

**Comment by bgrant0607** [comment]
I don't expect this to be done by Monday.

I'm fine with waiting for more user feedback that their clusters die after accumulating zillions of dead pods.

**Comment by kargakis** [comment]
stop is deprecated. Is there an issue with delete?

**Comment by kargakis** [comment]
Closing, this shouldn't be an issue right now.
