### ISSUE TITLE
Add an e2e test scenario with json logging enabled for kubelet

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#99802]
Part of https://github.com/kubernetes/enhancements/issues/1602

To ensure that structured logging is working and to prevent issues like https://github.com/kubernetes/kubernetes/issues/99239 we should have an e2e test that tests starting the kubelet with structured logging set to on.

/sig node
/sig instrumentation
/kind cleanup
/help

**Comment by serathius** [comment]
/reopen
@BenTheElder I looked through logs of one of the jobs https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-json-logging/1372319984549629952/artifacts/logs/kind-control-plane/kubelet.log
Looks like json format is not correctly configured. Do you know what can be missing?

**Comment by BenTheElder** [comment]
I will dig into this today

**Comment by BenTheElder** [comment]
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-json-logging/1372949245488795648/artifacts/kind-config.yaml

We can see that it is propagating `json` to the generated kind cluster config, however none of the kubelet extra args are making it down to kubeadm, presumably they're not merging into the generated extra args.

I will fix this.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/pull/2145 should have been the fix but we'll need to confirm still.

**Comment by BenTheElder** [comment]
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-json-logging/1373397897571209216/artifacts/logs/kind-control-plane/kubelet.log

This is working now:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-json-logging/1373397897571209216

**Comment by BenTheElder** [comment]
Note: we're currently grabbing the kubelet log using `jounralctl`, so in addition to some lines not being structured in kubelet yet, lines are prefixed with timestamp etc. by systemd. We can alter this if necessary. Currently the e2e does not inspect the log.

**Comment by serathius** [comment]
Awesome, thanks!!
/close
