### ISSUE TITLE
Max AWS security group rules limit reached for service loadbalancers.

### ISSUE THREAD

**Issue by LiamStorkey** [kubernetes/kubernetes#99813]
#### What happened:
I am currently facing an issue with the aws max security group rules limit reached which now blocks any further application deployments to this cluster as the ensure loadbalancer step now fails. When services to the cluster that are of type loadbalancer, a rule is added to the main nodes. security group to allow access through to the main k8s nodes instances. The issue is, as the number of services (using loadbalancer type) grows, then so does the number of rules in the main nodes security group, quickly reaching the max rules limit.

The main way around this is to apply the following to the cluster config:
```
spec:
    cloudConfig:
       disableSecurityGroupIngress: true
        elbSecurityGroup: sg-123445678
```
`disableSecruityGroupIngress` does the following - disable authorization of ELB security group to Kubernetes Nodes security group. In other words, it will not add security group rule
`elbSecurityGroup` is set to - avoid creating a security group per elb, you can specify a security group id, that will be assigned to your LoadBalancer.

However doing this now requires a manual step of creating a sg rule to allow all traffic from the sg specified in the elbSecurityGroup setting onto the main nodes sg. (not amazing but i can live with it if its a once off).
But where this gets tricky is if you are using a service type loadbalancer and using the annotation to create nlbs. AWS network loadbalancers do not have the ability to attach security groups which means the node port for the service doesn't get added to any security group like it would if disableSecurityGroupIngress was set to false.

#### What you expected to happen:
Need a solution that can either:
- dynamicaly create node<clustername> sgs and attach it to the node instances.
- dynamicaly add sg rules to the sg specified in `elbSecurityGroup` cluster cloudconfig setting for when services are created using the network loadbalancer annotations.

#### How to reproduce it (as minimally and precisely as possible):
Reach sg 50 rules on the main nodes sg.

#### Environment:
- Kubernetes version (use `kubectl version`): 
```
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AWS
- Others: Deployed using KOPS (Version 1.19.1)

/sig cloud-provider

**Comment by LiamStorkey** [comment]
Hey @kishorj Thank you for picking up this issue. is there anything that you would like help with/I can try work on?

**Comment by LiamStorkey** [comment]
Also, I have begun to run into the same issue while using the was load balancer controller for alb's as well.

**Comment by kishorj** [comment]
@LiamStorkey, I'm targeting the ALB fix for the upcoming v2.3.0 release. As for the NLB, the plan is to use similar optimization when support for security group is available.

**Comment by kishorj** [comment]
In case of NLB, using IP targets might help due to higher likelihood of multiple target groups can share the SG rules if the target port value is the same.

**Comment by LiamStorkey** [comment]
@kishorj Thanks for picking this up! is it `v2.3.0` of the alb controller?
