### ISSUE TITLE
k8s init config file

### ISSUE THREAD

**Issue by qiyongxiao** [kubernetes/kubernetes#99819]
There was some FileAvariable error in /etc/kubernetes/ already exists while InitConfiguration's nodeRegistration.ignorePreflightErrors specified:
```
........
ignorePreflightErrors:
   - ContainerRuntime
   - SystemVerification
   - Swap
   - IsPrivilegedUser
   - IsDockerSystemd
   - DirAvailable
   - FileAvailable
   - FileExisting
   - InPath
   - Service
   - Firewalld
   - PortOpen
   - FileContent
   - Hostname
   - HTTPProxy
   - HTTPProxyCIDR
   - KubernetesVersion
   - KubeletVersion
   - ExternalEtcdVersion
   - ImagePull
   - NumCPU
   - Mem
........
`
How to ignored the files in  /etc/kubernetes with kubeadm init --config

**Comment by neolit123** [comment]
the format is `FileAvailable--<filepath>` e.g.:

[ERROR FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml]: /etc/kubernetes/manifests/kube-apiserver.yaml already exists:

```
ignorePreflightErrors:
- FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml
...
```

please comment if it's not working for you.

/kind support
/sig cluster-lifecycle
/area kubeadm
