### ISSUE TITLE
Change the users of IsQualifiedName to ValidateQualifiedName

### ISSUE THREAD

**Issue by XudongLiuHarold** [kubernetes/kubernetes#99828]
After #98277 got merged, we have added new helper function `ValidateQualifiedName` here: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L126. 

It will be good for us to use this simpler helper function to replace previous `IsQualifiedName` function.

/good-first-issue

**Comment by mowangdk** [comment]
I would like to take this one 
/assign

**Comment by creydr** [comment]
@mowangdk I worked in #102074 on this as well, but kept your changed files untouched (as written in my PR description). @GreenApple10: same for you. 
I hope this is OK for you.

**Comment by aojea** [comment]
> This should be reopened until #99883 and #100903 got merged (my PR #102074 excluded the changes from the other PRs).

/reopen
per last comment

**Comment by manavsiddharthgupta** [comment]
can you assign me

**Comment by mangoGoForward** [comment]
I'd love to work on this issue.
/assign

**Comment by mangoGoForward** [comment]
Hi, @XudongLiuHarold , I am a first commitor for kubernetes and I have committed a PR in #108150, could you help me to review it, or give me some suggestions. Thanks a lot.
