### ISSUE TITLE
[Failing Test] [sig-api-machinery] ResourceQuota [Feature:CrossNamespacePodAffinity] [alpha] should verify ResourceQuota with cross namespace pod affinity scope using scope-selectors

### ISSUE THREAD

**Issue by thejoycekung** [kubernetes/kubernetes#99820]
#### Which jobs are failing:
ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd

#### Which test(s) are failing:
[sig-api-machinery] ResourceQuota [Feature:CrossNamespacePodAffinity] [alpha] should verify ResourceQuota with cross namespace pod affinity scope using scope-selectors

#### Since when has it been failing:
https://github.com/kubernetes/kubernetes/compare/da9ea2ea7...f63cac6cd

Looks to be related to #98582 

#### Testgrid link:
https://testgrid.k8s.io/sig-release-master-informing#aks-engine-azure-windows-master-containerd

#### Reason for failure:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/resource_quota.go:1426
Mar  5 01:22:20.463: Unexpected error:
    <*errors.StatusError | 0xc002bd57c0>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "ResourceQuota \"quota-cross-namespace-pod-affinity\" is invalid: spec.scopeSelector.matchExpressions.scopeName: Invalid value: \"CrossNamespacePodAffinity\": unsupported scope",
            Reason: "Invalid",
            Details: {
                Name: "quota-cross-namespace-pod-affinity",
                Group: "",
                Kind: "ResourceQuota",
                UID: "",
                Causes: [
                    {
                        Type: "FieldValueInvalid",
                        Message: "Invalid value: \"CrossNamespacePodAffinity\": unsupported scope",
                        Field: "spec.scopeSelector.matchExpressions.scopeName",
                    },
                ],
                RetryAfterSeconds: 0,
            },
            Code: 422,
        },
    }
    ResourceQuota "quota-cross-namespace-pod-affinity" is invalid: spec.scopeSelector.matchExpressions.scopeName: Invalid value: "CrossNamespacePodAffinity": unsupported scope
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/resource_quota.go:1430
```

#### Anything else we need to know:
Example in Spyglass: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1367634562754023424

/sig api-machinery
/cc @ahg-g

**Comment by ahg-g** [comment]
Any idea where are the yamls files for this test is? This is an alpha feature, and the test shouldn't be running it unless the feature is enabled.

**Comment by thejoycekung** [comment]
I think the YAML for this job should be here - SIG Windows technically owns it. 

https://github.com/kubernetes/test-infra/blob/d44a4a64b0968622fb13f6f26915bce3d68cca25/config/jobs/kubernetes-sigs/sig-windows/sig-windows-config.yaml#L612

**Comment by ahg-g** [comment]
@jsturtevant any idea if this test enable alpha features? If not, then it should skip [Alpha] tagged tests here: https://github.com/kubernetes/test-infra/blob/8f06baa82fab226a0f4bb41a3d1d9a640695a228/config/jobs/kubernetes-sigs/sig-windows/sig-windows-config.yaml#L657

**Comment by jsturtevant** [comment]
Thanks we opened a PR to fix this yesterday: https://github.com/kubernetes/test-infra/pull/21156.

**Comment by jsturtevant** [comment]
We are back to passing: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1367907814768381952
