### ISSUE TITLE
[Flaky] k8s.io/kubernetes/pkg/api/testing

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#99821]
#### Which jobs are flaking:

pull-kubernetes-unit

#### Which test(s) are flaking:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/99817/pull-kubernetes-unit/1367685781799309312

```
=== FAIL: pkg/api/testing  (0.00s)
FAIL	k8s.io/kubernetes/pkg/api/testing	240.331s
```

Two new tests were just added in https://github.com/kubernetes/kubernetes/pull/99012 that take significant amounts of time in CI:

```
--- FAIL: TestUnstructuredRoundTripApplyConfigurations (112.70s)
--- FAIL: TestJsonRoundTripApplyConfigurations (35.82s)
```

~These tests also appear to be flaking regularly: https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&job=kubernetes-unit&test=k8s.io%2Fkubernetes%2Fpkg%2Fapi%2Ftesting~

/assign @jpbetz

**Comment by BenTheElder** [comment]
Related: At some point we should probably adjust the timeout. I'd like to get CI to a point where it uses whatever the default is in make test.

**Comment by liggitt** [comment]
yes.

**Comment by jpbetz** [comment]
This loops each type 50 times, I'll drop that down to say, 3 times. We honestly don't need to fuzz these that hard, they typically catch a problems quick.

**Comment by jpbetz** [comment]
The failures I see in gubernator shouldn't happen now that the PR is merged. Before myPR to add this test was merged, other PRs that added fields (NamespaceSelector) would cause myPR's unit tests to fail and I would need to rebase it and run `hack/update-codegen.sh`. Now that it is merged,`hack/update-codegen.sh` will be run by the PR author that adds a field to a type to keep code in sync.

**Comment by liggitt** [comment]
> The failures I see in gubernator shouldn't happen now that the PR is merged.

ah, so these failures on other PRs mean they needed to regen?

* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/98277/pull-kubernetes-unit/1367606744649306112 
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/99522/pull-kubernetes-unit/1367611137478103040
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/98277/pull-kubernetes-unit/1367628490181971968

**Comment by jpbetz** [comment]
Yeah, the first one adds `LoadBalancerClass` and the fuzzer detected the apply config builder had not been regenerated by `hack/update-codegen.sh`. The others have field changes too.

**Comment by liggitt** [comment]
ok, so it's noise for PRs in progress but not flakes. looks like the runtime/timeout issue is the only flake, which you can drop iterations significantly to solve

**Comment by jpbetz** [comment]
50->3 seems like it should get us to 10-15s total for both new tests https://github.com/kubernetes/kubernetes/pull/99847/files
