### ISSUE TITLE
Headless services get no env vars

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#9983]
It should be possible to create the env var for `FOO_SERVICE_HOST="<service>.<namespace>.svc.cluster.local` based on Kubelet configuration it already has.

**Comment by smarterclayton** [comment]
It's confusing and harder to integrate in those cases.  We assume DNS is present today (or are very close to doing so).

**Comment by thockin** [comment]
So you want to just expose the DNS name as the env var?  Can't we just get
rid of env vars?

**Comment by smarterclayton** [comment]
I'd like to get rid of the automatic env vars and let them be defined via the downward API mechanism - I'd be fine with only exposing the DNS name always (i think we can then remove the watch that the kubelet has on all services as well).

----- Original Message -----

**Comment by thockin** [comment]
That's sort of funny to define the env var to be the DNS name. :)

I think that keeping the master as a proper IP makes sense, though.  Still
discussing how DNS finds the master and I am liking less and less the need
to salt that into DNS config.
