### ISSUE TITLE
Versions of containerd.io, docker-ce, and docker-ce-cli not found

### ISSUE THREAD

**Issue by enyinna1234** [kubernetes/kubernetes#99831]
#### What happened: As per documentation at 'https://kubernetes.io/docs/setup/production-environment/container-runtimes/' installing Docker "sudo apt-get update && sudo apt-get install -y \
  containerd.io=1.2.13-2 \
  docker-ce=5:19.03.11~3-0~ubuntu-$(lsb_release -cs) \
  docker-ce-cli=5:19.03.11~3-0~ubuntu-$(lsb_release -cs) " results in:

```
E: Version '1.2.13-2' for 'containerd.io' was not found
E: Version '5:19.03.11~3-0~ubuntu-groovy' for 'docker-ce' was not found
E: Version '5:19.03.11~3-0~ubuntu-groovy' for 'docker-ce-cli' was not found
```
#### How to reproduce it (as minimally and precisely as possible): Install Docker on Ubuntu 20.10 following the steps here
https://kubernetes.io/docs/setup/production-environment/container-runtimes/

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.10
- Kernel (e.g. `uname -a`): Linux 5.8.0-44-generic x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
the docs is in https://github.com/kubernetes/website/.

**Comment by neolit123** [comment]
i haven't seen bug reports about this, so i wonder if something is wrong with their repositories.
docker 19.03 should be available in Ubuntu 20.x ...or maybe it's not?

**Comment by enyinna1234** [comment]
Works fine on 20.04

**Comment by neolit123** [comment]
@enyinna1234 ok, so this is a problem with?
> OS (e.g: cat /etc/os-release): Ubuntu 20.10

do they only have Docker 20.x in their repository?

**Comment by neolit123** [comment]
we are switching to docker 20.x for Kubernetes 1.21, so it may be time to update https://kubernetes.io/docs/setup/production-environment/container-runtimes/ with docker 20.x instructions.

if you can help us with a PR for k/website it would be great.
