### ISSUE TITLE
Kuberentes fails to create large Gluster PVC

### ISSUE THREAD

**Issue by handrea2009** [kubernetes/kubernetes#99846]
#### What happened:

Kuberentes fails to create very large Gluster PVC and the following error is logged:

ProvisioningFailed  35s (x566 over 20h)  persistentvolume-controller  Failed to provision volume with StorageClass "gluster-heketi": failed to create volume: quantity 134192Gi is too great, overflows int64

#### What you expected to happen:
Kubernetes should be able to create large Gluster PVC

#### How to reproduce it (as minimally and precisely as possible):
I'am running Gluster (as a daemonset) and Heketi as a single pod on a 3 nodes cluster
Then create the PVC using a yaml like the following

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster-heketi
  name: gluster-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 134192Gi

#### Environment:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

- Kernel (e.g. `uname -a`):

Linux hf4 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Others:

gluster --version
glusterfs 7.2

heketi --version
Heketi v10.0.0-51-g70ba652b

**Comment by neolit123** [comment]
> ProvisioningFailed 35s (x566 over 20h) persistentvolume-controller Failed to provision volume with StorageClass "gluster-heketi": failed to create volume: quantity 134192Gi is too great, overflows int64

are you sure you want to create a volume with ~140 TB?
that's a lot...

if you are not getting a response here mention this problem in #sig-storage on k8s slack.

/sig storage
/kind feature

**Comment by humblec** [comment]
@neolit123 considering this https://github.com/kubernetes/kubernetes/pull/100100/ is merged, can you retry and see this still fails or not?

**Comment by neolit123** [comment]
I think that is a question for @handrea2009 ?
