### ISSUE TITLE
Definitive end date for ExecProbeTimeout kubelet feature gate

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes/kubernetes#99854]
#### What would you like to be added:

The `ExecProbeTimeout` feature gate was introduced with this bug fix:

https://github.com/kubernetes/kubernetes/pull/94115

Because the above bug fix had a practical side-effect of introducing new, 1 second exec livenessProbe timeout enforcement for all container specs not otherwise declaring a timeout, the feature gate was provided as a way to optionally opt out of that new timeout enforcment, retaining the old (buggy) behavior.

With the arrival of that feature gate was the understanding that it should be quickly locked and removed in the very next release cycle (it landed prior to the shipment of 1.20.0, and would be locked to true [essentially not usable] in the 1.21.0 release).

#### Why is this needed:

This issue advocates that the Kubernetes user community needs more time to understand the impact of the 1 second default timeout side-effect, and hence to allow folks to continue to opt out of this change if that side-effect has undesirable costs for production workloads running in their environments.

The deliverable for this issue should be a more permissive, final decision on when to disable usage of the `ExecProbeTimeout` feature gate, which would yield two practical work tasks:

1. Update the code comment here with the decision:
  - https://github.com/kubernetes/kubernetes/blob/v1.20.0/pkg/features/kube_features.go#L826
2. Add that decision in the relevant changelog release notes so that it is easier for Kubernetes users to discover how long they may continue to use this feature gate if they wish. Refer to this original comment in the 1.20.0 changelog:
  - https://github.com/kubernetes/kubernetes/blob/v1.20.0/CHANGELOG/CHANGELOG-1.20.md#no-really-you-must-read-this-before-you-upgrade

Specifically, the current official messaging is:

> This gate will be locked and removed in future releases so that exec probe timeouts are always respected.

Let's pick a definitive EOL for this feature gate and publish the decision.

**Comment by SergeyKanzhelev** [comment]
Discussion is here: https://github.com/kubernetes/kubernetes/pull/98085 Also added a note to the KEP about postponing the end date in https://github.com/kubernetes/enhancements/pull/2294

**Comment by jackfrancis** [comment]
Ref: https://github.com/kubernetes/kubernetes/pull/115227#pullrequestreview-1263587854
