### ISSUE TITLE
port-forward fails connecting to pods with IPv6 only listeners

### ISSUE THREAD

**Issue by mcwumbly** [kubernetes/kubernetes#99850]
#### What happened:

Attempting to use port-forward (e.g. via `kubectl port-forward`) to a pod (e.g. `etcd`) that only listens on IPv6 addresses fails with this error:
```
E0305 17:22:44.391325  669306 portforward.go:400] an error occurred forwarding 5000 -> 2379: error forwarding port 
    2379 to pod 816046a9fc24b9c2db624854ac72ff91a170ebf4843ee99771f5ea9c2bc4997f, uid : failed to execute portforward in network namespace "host": failed to dial 2379: dial tcp4 127.0.0.1:2379: connect: connection refused
```

#### What you expected to happen:

I expect it to succeed if there is a listener on the IPv6 localhost equivalent.

##### In brief:

1. create a kind cluster using ipv6
2. use kubectl to portforward to the etcd pod
3. try to curl it
4. see error: `dial tcp4 127.0.0.1:2379: connect: connection refused`:
    ```
    $ kubectl port-forward -n kube-system etcd-ipv6-kind-control-plane 5000:2379 --address ::1
    Forwarding from [::1]:5000 -> 2379
    Handling connection for 5000
    E0305 17:22:44.391325  669306 portforward.go:400] an error occurred forwarding 5000 -> 2379: error forwarding port 
    2379 to pod 816046a9fc24b9c2db624854ac72ff91a170ebf4843ee99771f5ea9c2bc4997f, uid : failed to execute portforward in network namespace "host": failed to dial 2379: dial tcp4 127.0.0.1:2379: connect: connection refused
    ```

##### In more detail:

[enable ipv6 for docker](https://docs.docker.com/config/daemon/ipv6/)

create a kind cluster using ipv6
```
cat <<EOF > ipv6-kind.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv6
EOF

kind create cluster --config ./ipv6-kind.yaml --name ipv6-kind
```

see that etcd is only listening on ipv6 addrs:
```
docker exec -ti ipv6-kind-control-plane bash -c "cat /etc/kubernetes/manifests/etcd.yaml" | grep listen-client-urls
#    - --listen-client-urls=https://[::1]:2379,https://[fc00:f853:ccd:e793::2]:2379
```

use kubectl to portforward to the etc pod
```
kubectl port-forward -n kube-system etcd-ipv6-kind-control-plane 5000:2379 --address ::1
```

get the cert/key for etcd
```
docker exec -ti ipv6-kind-control-plane bash -c "cat /etc/kubernetes/pki/etcd/peer.crt" > peer.crt
docker exec -ti ipv6-kind-control-plane bash -c "cat /etc/kubernetes/pki/etcd/peer.key" > peer.key
```

try to curl etcd's health endpoint
```
curl -k "https://[::1]:5000/health" --cert peer.crt --key peer.key
# curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to ::1:5000
```

see error output from `kubectl port-forward`:
```
kubectl port-forward -n kube-system etcd-ipv6-kind-control-plane 5000:2379 --address ::1
# Forwarding from [::1]:5000 -> 2379
# ...
# Handling connection for 5000
# E0305 17:22:12.325329  668792 portforward.go:400] an error occurred forwarding 5000 -> 2379: error forwarding port 2379 to pod 816046a9fc24b9c2db624854ac72ff91a170ebf4843ee99771f5ea9c2bc4997f, uid : failed to execute portforward in network namespace "host": failed to dial 2379: dial tcp4 127.0.0.1:2379: connect: connection refused
```

add a listener on `127.0.0.1`:
```
docker exec -ti ipv6-kind-control-plane bash -c "sed -i '/listen-client-urls/ s/$/,https:\/\/127.0.0.1:2379/' /etc/kubernetes/manifests/etcd.yaml"
```

try curl again and see it succeed:
```
$ curl -k "https://[::1]:5000/health" --cert peer.crt --key peer.key                                                                                                                                                                                                
{"health":"true"}
```

#### Anything else we need to know?:

I originally encountered this issue when testing cluster-api on IPv6, which relies on the portforward API to proxy to etcd pods on workload clusters to check their health and opened kubernetes-sigs/cluster-api#4253.

A related feature request is kubernetes/kubernetes#72597, requesting the ability for clients to specify the remote address in their request, but the scope of that request is larger than what is needed here.

##### What I think is going on

This is not code I'm familiar with, but from my initial investigations, I believe the error comes from [kubernetes/kubernetes/pkg/kubelet/dockershim/docker_streaming_others.go](https://github.com/kubernetes/kubernetes/blob/18099e1ef7283d9ab09c45c5a4a90e26fdce1161/pkg/kubelet/dockershim/docker_streaming_others.go#L47):
```
 	args := []string{"-t", fmt.Sprintf("%d", containerPid), "-n", socatPath, "-", fmt.Sprintf("TCP4:localhost:%d", port)}
```

 and then gets bubbled up through [kubernetes/kubernetes/pkg/kubelet/cri/streaming/portforward/httpstream.go](https://github.com/kubernetes/kubernetes/blob/cea1d4e20b4a7886d8ff65f34c6d4f95efcb4742/pkg/kubelet/cri/streaming/portforward/httpstream.go#L238-L254):
 ```
 	 	 msg := fmt.Errorf("error forwarding port %d to pod %s, uid %v: %v", port, h.pod, h.uid, err)
 ```
 
 It looks like a similar assumption is made in the windows implementation in [kubernetes/kubernetes/pkg/kubelet/dockershim/docker_streaming_windows.go](https://github.com/kubernetes/kubernetes/blob/18099e1ef7283d9ab09c45c5a4a90e26fdce1161/pkg/kubelet/dockershim/docker_streaming_windows.go#L32): 
 ```
 	err := r.exec(context.TODO(), podSandboxID, []string{"wincat.exe", "127.0.0.1", fmt.Sprint(port)}, stream, stream, ioutils.WriteCloserWrapper(stderr), false, nil, 0)
 ```

#### Environment:
- Kubernetes version (use `kubectl version`): `v1.19.2` and `v1.20.1` so far...
- Cloud provider or hardware configuration: `kind` on Ubuntu and `vSphere` using photon so far...
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.5 LTS and photon v3.0
- Kernel (e.g. `uname -a`): `Linux ubuntu 4.15.0-135-generic #139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Network plugin and version (if this is a network-related bug): ` kindest/kindnetd:v20200725-4d6bea59` and `antrea v0.11.1` so far...
- Others:

**Comment by BenTheElder** [comment]
Do you know what exact images and kind version are in use? https://github.com/kubernetes-sigs/kind/issues/1723 was fixed a while back (last summer) and possibly related.

**Comment by aojea** [comment]
yeah, this is hardcoded because it was using localhost and the resolver on dual-stack environment messed it up
/assign
I think that is time to fix it :factory_worker:

**Comment by aojea** [comment]
it is hardcoded in the runtime

**Comment by aojea** [comment]
containerd 
 https://github.com/containerd/containerd/blob/944e9b70e2204f2fec1c0c02bbac39e1475cbc22/pkg/cri/server/sandbox_portforward_linux.go#L68

crio https://github.com/cri-o/cri-o/blob/c61c691b9c6d00ab18268d1a5d53d2b9c2dd2702/internal/oci/runtime_oci.go#L1023-L1029

**Comment by aojea** [comment]
runtime patches has merged, so it is on the people to install a version with the patches.

@mcwumbly are you able to test with one of those runtimes nigthly package and report back?

**Comment by mcwumbly** [comment]
@aojea I'll circle back after the weekend and take a look.

**Comment by aojea** [comment]
I will do it in my side once I have time next week, but a double ack will be great

**Comment by aojea** [comment]
tested with KIND from HEAD with the containerd version with the fix, and it works

- run a pod and open a server listening only in ::1
```
 # nc -l -p 80 ::1
```
- forward the port from outside
```
 kubectl port-forward pod/test 8080:80
Forwarding from 127.0.0.1:8080 -> 80
Forwarding from [::1]:8080 -> 80

Handling connection for 8080
```
- create a connection
```
$ curl localhost:8080
curl: (1) Received HTTP/0.9 when not allowed
```

**Comment by mcwumbly** [comment]
lgtm. I went through the steps from the original post and can now curl etcd's health endpoint without adding an IPv4 listener.

```
$ ./bin/kind create cluster --config ./ipv6-kind.yaml --name ipv6-kind --image kindest/node:latest
Creating cluster "ipv6-kind" ...
 ✓ Ensuring node image (kindest/node:latest) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-ipv6-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-ipv6-kind

Not sure what to do next? 😅  Check out https://kind.sigs.k8s.io/docs/user/quick-start/
```

```
$ docker exec -ti ipv6-kind-control-plane bash -c "cat /etc/kubernetes/manifests/etcd.yaml" | grep listen-client-urls
    - --listen-client-urls=https://[::1]:2379,https://[fc00:f853:ccd:e793::2]:2379
```

```
$ docker exec -ti ipv6-kind-control-plane bash -c "cat /etc/kubernetes/pki/etcd/peer.crt" > peer.crt
$ docker exec -ti ipv6-kind-control-plane bash -c "cat /etc/kubernetes/pki/etcd/peer.key" > peer.key
```

```
$ kubectl port-forward -n kube-system etcd-ipv6-kind-control-plane 5000:2379 --address ::1
Forwarding from [::1]:5000 -> 2379
Handling connection for 5000
```

```
$ curl -k "https://[::1]:5000/health" --cert peer.crt --key peer.key
{"health":"true"}
```

**Comment by aojea** [comment]
lovely, thanks for double checking, we can close it now
cc: @mikebrow 
/close
