### ISSUE TITLE
Cannot use kubernetes.Clientset as kubernetes.Interface value in struct literal: missing method AdmissionregistrationV1 

### ISSUE THREAD

**Issue by shrinandj** [kubernetes/kubernetes#99878]
#### What happened:
I have a controller which uses the clientSet object returned by `kubernetes.NewForConfig`. This clientSet object is then passed to other objects. These objects are using a `kubernetes.Interface` to receive this object. The main reason for using a `kubernetes.Interface` is to be able to use the `fake.ClientSet` during testing.

However, it turns out that it is not possible to receive the ClientSet object as a `kubernetes.Interface` because of a missing method.

When I try to compile my code, the error I get is:
```
cannot use exc.ClientSet (variable of type kubernetes.Clientset) as kubernetes.Interface value in struct literal: missing method AdmissionregistrationV1 (AdmissionregistrationV1 has pointer receiver)
```

#### What you expected to happen:
The code should compile.

#### How to reproduce it (as minimally and precisely as possible):
```
package main

import (
        "fmt"
        "k8s.io/client-go/tools/clientcmd"
        "k8s.io/client-go/kubernetes"
        "os"
)

type SomeStruct struct {
        ClientSet          kubernetes.Interface
}

func main() {
        kubeconfig := os.Getenv("HOME") + "/.kube/config"
        config, err := clientcmd.BuildConfigFromFlags("", kubeconfig)
        if err != nil {
                panic(err.Error())
        }
        clientSet, err := kubernetes.NewForConfig(config)

        s := SomeStruct{
            ClientSet: *clientSet,
        }

        fmt.Printf("Clientset: %q\n", s)
}
```

#### Anything else we need to know?:
- Client-go version is `v0.20.2`

**Comment by BenTheElder** [comment]
corrected sample:
```go
package main

import (
	"fmt"
	"os"

	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/tools/clientcmd"
)

type SomeStruct struct {
	ClientSet kubernetes.Interface
}

func main() {
	kubeconfig := os.Getenv("HOME") + "/.kube/config"
	config, err := clientcmd.BuildConfigFromFlags("", kubeconfig)
	if err != nil {
		panic(err.Error())
	}
	clientSet, err := kubernetes.NewForConfig(config)

	s := SomeStruct{
		ClientSet: clientSet,
	}

	fmt.Printf("Clientset: %q\n", s)
}
```

Most of the diff is just `gofmt` once this compiled, the main change is just don't deref clientSet, keep it as a pointer.
```go
	s := SomeStruct{
		ClientSet: clientSet,
	}
```
Instead of:
```go
	s := SomeStruct{
		ClientSet: *clientSet,
	}
```

It is expected in go that an interface may only be implemented against a pointer type.
/remove-kind bug
/kind support
/sig api-machinery

**Comment by shrinandj** [comment]
Aah.. that's fantastic!! Thanks @BenTheElder ..
