### ISSUE TITLE
bazel visibility rules need porting to make verify

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#99876]
See: https://github.com/kubernetes/kubernetes/pull/99561#issuecomment-791505243

xref: https://github.com/kubernetes/enhancements/issues/2420

/sig testing
/sig architecture
/area code-organization
/assign

**Comment by BenTheElder** [comment]
/triage accepted
/priority important-soon
(maybe critical? we don't want to lapse on these imports)

**Comment by BenTheElder** [comment]
Not a hard blocker for the release I think, we could backport this, but this should really happen in the milestone, and likely shouldn't take long ™️

**Comment by BenTheElder** [comment]
Tentatively `import-boss` is way too slow for this use case and `importverifier` is only capable of restricting imports within a particular package.

We'll need a different approach.

**Comment by BenTheElder** [comment]
I have a prototype of doing this _much_ faster with ... bash, not sure what to call it yet and whether it's worth making general

It seems the main thing we need here is check that `github.com/prometheus/*` imports are only in this list:
https://github.com/kubernetes/kubernetes/blob/a1f2787897a81c375a4de28482b5eb649851800a/build/visible_to/BUILD#L431-L444

Which we can do with a non-generic script that is pretty simple and fast.

**Comment by spiffxp** [comment]
AFAIK @BenTheElder is planning to land this today

**Comment by BenTheElder** [comment]
filed: https://github.com/kubernetes/kubernetes/pull/100552

**Comment by BenTheElder** [comment]
NOTE: this was implemented for the actively pursued SIG instrumentation restrictions. It was not implemented for all rules, it's not clear that the utility was high enough for all of these. We can add more restrictions using any of these alternative tools in the future as necessary.

**Comment by spiffxp** [comment]
What rules weren't implemented?

Do you want to leave this open and move to v1.22 for those, or close this in v1.21 with a new issue (or not) for those rules?

**Comment by BenTheElder** [comment]
There are a number of package groups in:
https://github.com/kubernetes/kubernetes/blob/a1f2787897a81c375a4de28482b5eb649851800a/build/visible_to/BUILD

It will take a bit to identify if any of them were actually used by any visibility rules, and if any of those are necessary (we have visibility rules on nearly every target, but most of that is pointless or implicit)

**Comment by BenTheElder** [comment]
Er: and the prometheus bit is the only part that was actively worked on in the past few years. Other changes were due to targets referenced by the package groups being moved or removed in the sources and therefore needing updating there as well.

For the most part active import management was done with import boss or importverifier, but I cannot say with certainty yet that there was no other useful visibility usage. I'm looking currently to verify. I looked previously but can't recall the details.

**Comment by BenTheElder** [comment]
these were used in the past during the development of moving kubectl to staging, but now that it is staged that shouldn't be necessary I think. Everything else seems to either be the prometheus effort, or related to the kubectl move.

cc @seans3
