### ISSUE TITLE
unit tests should not require root

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#99881]
#### What happened:

- Some of our unit tests fail when not run as root (locally), currently looking at `cluster/gce/*` but I suspect there are more of these

#### What you expected to happen:

- Our unit tests should not fail as root, any test requiring this has gone well past being a "unit" test
- Our unit tests should probably not run as root in CI to prevent regressions

#### How to reproduce it (as minimally and precisely as possible):

`make test`

/sig testing

cc @liggitt @spiffxp @vinayakankugoyal @cheftako

**Comment by vinayakankugoyal** [comment]
I think we should remove the unit tests in question, configure-helper.sh requires running as root by design.

**Comment by iraj465** [comment]
Hi. Can i work on it?

**Comment by BenTheElder** [comment]
@iraj465 You're ways welcome to look into any issue, but there isn't a specific action to take just yet. You might consider looking for a "help wanted" issue instead which are supposed to be issues with an action plan already agreed and pointers for what to do.

**Comment by iraj465** [comment]
Sure. Thanks for the heads up @BenTheElder

**Comment by BenTheElder** [comment]
/assign
Working on identifying what the complete problem space is.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/100368 fixes most of the unit tests (not my PR). The one remaining is `k8s.io/kubernetes/pkg/volume/csi` `TestAttacherMountDevice` which fails with no logs.

**Comment by msau42** [comment]
@gnufied can you help look into `TestAttacherMountDevice`?

**Comment by gnufied** [comment]
sure.

**Comment by BenTheElder** [comment]
btw `/test pull-kubernetes-unit-experimental` can be used to test this in CI for now. When we figure out this test hopefully I will port this to `pull-kubernetes-unit` and `ci-kubernetes-unit` to shut the door on future regressions.

**Comment by spiffxp** [comment]
/milestone v1.22
@BenTheElder please move back if you think it's feasible to land this today

**Comment by BenTheElder** [comment]
We have maybe 1-2 tests that need help and then we can land it quickly anytime after that ... 

See now also https://github.com/kubernetes/kubernetes/issues/102600

**Comment by vinayakankugoyal** [comment]
We will be adding some unit tests to test functionality that updates the file permissions and owners for kubeadm-rootless work, those will have to run as root.

**Comment by liggitt** [comment]
> We will be adding some unit tests to test functionality that updates the file permissions and owners for kubeadm-rootless work, those will have to run as root.

don't add new unit tests that require root permission to run

**Comment by BenTheElder** [comment]
> don't add new unit tests that require root permission to run

This. Developers should be able to `make test` and it should just work. https://github.com/kubernetes/kubernetes/issues/102607

We can cover rootless in e2e or by other means.

**Comment by liggitt** [comment]
> This. Developers should be able to `make test` and it should just work. #102607

how can we ensure this sticks and we don't regress once we get unit tests runnable as non-root? run the presubmit unit test job in a non-root container?

**Comment by BenTheElder** [comment]
> how can we ensure this sticks and we don't regress once we get unit tests runnable as non-root? run the presubmit unit test job in a non-root container?

Exactly, `pull-kubernetes-unit-experimental` is a copy of the normal job but with UID!=0 for the test container. (https://github.com/kubernetes/kubernetes/issues/99881#issuecomment-804407541 is not very clear on that).

**Comment by BenTheElder** [comment]
specifically currently the delta is:
```yaml
      securityContext:
        runAsUser: 2000
        allowPrivilegeEscalation: false
```
https://github.com/kubernetes/test-infra/blob/f38f16e9b66de7d746e69bcd59fe4c80b08b12ea/config/jobs/kubernetes/sig-testing/make-test.yaml#L49-L52

**Comment by BenTheElder** [comment]
I suspect at least some of the locally recorded failures here are new related issues https://github.com/kubernetes/kubernetes/issues/102607#issuecomment-854985308, e.g. one of the complains about trying to open `/audit` with permission denied.

I am testing in CI here:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/92316/pull-kubernetes-unit-experimental/1400915729829597184

https://github.com/kubernetes/kubernetes/pull/92316#issuecomment-854987231

**Comment by BenTheElder** [comment]
Current CI failures specific to this job:

```
k8s.io/kubernetes/pkg/volume/csi: TestAttacherMountDevice

k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/options: TestAuditValidOptions/default_log
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/options: TestAuditValidOptions/default_log_no_policy
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/options: TestAuditValidOptions/default_union
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/options: TestAuditValidOptions/custom
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/options: TestAuditValidOptions
```

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/92316/pull-kubernetes-unit-experimental/1400915729829597184

**Comment by liggitt** [comment]
audit unit test fix in #102610

**Comment by BenTheElder** [comment]
`k8s.io/kubernetes/pkg/volume/csi: TestAttacherMountDevice` still seems to produce no logs when it fails. 

I noticed it has UID==0 specific codepath(s) but those seem to be to skip certain cases when UID _is_ 0
https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/volume/csi/csi_attacher_test.go#L1191

**Comment by BenTheElder** [comment]
No progress, been chasing other CI issues. Still blocked on `k8s.io/kubernetes/pkg/volume/csi: TestAttacherMountDevice`

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/92316/pull-kubernetes-unit-experimental/1405761564602011648

**Comment by PushkarJ** [comment]
@BenTheElder I was able to reproduce this locally and got a much more readable result. It seems like `user.Current()` returns error, when current user is non-root, but the code skips error checking and uses the `user` value returned (which is nil), which induces the panic in the if condition for `UID != 0` check:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x23d2334]

goroutine 3 [running]:
testing.tRunner.func1.2(0x2627500, 0x399d630)
	/usr/local/go/src/testing/testing.go:1143 +0x49f
testing.tRunner.func1(0xc000001980)
	/usr/local/go/src/testing/testing.go:1146 +0x695
panic(0x2627500, 0x399d630)
	/usr/local/go/src/runtime/panic.go:971 +0x499
k8s.io/kubernetes/pkg/volume/csi.TestAttacherMountDevice(0xc000001980)
	/tmp/_output/local/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_attacher_test.go:1191 +0x10b4
testing.tRunner(0xc000001980, 0x29519d8)
	/usr/local/go/src/testing/testing.go:1193 +0x203
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1238 +0x5d8
FAIL	k8s.io/kubernetes/pkg/volume/csi	1.559s
FAIL
make: *** [Makefile:184: test] Error 1
```
After I added the error check, the tests passed. Will start working on PR to fix this, if there are no concerns

**Comment by BenTheElder** [comment]
THANK YOU!
I keep trying to get to this and something else comes up. That change sounds totally correct: Please do file the PR and I'll try to make sure we get it reviewed 🙏

**Comment by PushkarJ** [comment]
@BenTheElder : Also, do you think adding a command on how to run tests locally as non-root user with `allowPrivilegeEscalation` disabled might be a good idea? Potential update location: [testing.md](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/testing.md#run-unit-tests-from-certain-packages) 

Was able to do this with docker using this command:

```
docker run -u 2000:2000 --security-opt no-new-privileges -it -v /Users/pjoglekar/github-forked/kubernetes/:/tmp --entrypoint=bash gcr.io/k8s-testimages/kubekins-e2e:latest-master`

I have no name!@14eabec7c172:/tmp$ make test GOFLAGS="-v" KUBE_RACE=-race KUBE_TIMEOUT=--timeout=240s
```

**Comment by BenTheElder** [comment]
I would think most users are running the tests locally as non-root but I could be wrong 😅, for me just `make test` encounters the problems. If I'm wrong that would be great!

In CI we will hopefully switch to this there as soon after this last test is fixed.

**Comment by PushkarJ** [comment]
CI job for unit tests, with non-root user is now green: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/103127/pull-kubernetes-unit-experimental/1407797774702874624

**Comment by PushkarJ** [comment]
> I would think most users are running the tests locally as non-root but I could be wrong 😅, for me just `make test` encounters the problems. If I'm wrong that would be great!
> 
> In CI we will hopefully switch to this there as soon after this last test is fixed.

In my local setup I was running as non-root user, but `make test` did not fail for me. Probably absence of user entry with  a name is what (or one of the reasons that) causes the failure as we discussed here: https://github.com/kubernetes/kubernetes/pull/103127#discussion_r657505781

**Comment by BenTheElder** [comment]
thanks to @PushkarJ it's time to roll over the job config and close the gap on this permanently 🎉

**Comment by BenTheElder** [comment]
The CI job wasn't fixed correctly and currently runs as root 😞 

We have at least one unit test that requires root currently.

**Comment by BenTheElder** [comment]
filed https://github.com/kubernetes/kubernetes/issues/114824 for current test requiring root and https://github.com/kubernetes/test-infra/pull/28354 to fixup the -experimental unit test job.

we'll want to copy these settings over to the blocking job once #114824 is resolved

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/28381 now that https://github.com/kubernetes/kubernetes/issues/114824 is fixed and https://github.com/kubernetes/test-infra/pull/28354 is merged and tested

**Comment by BenTheElder** [comment]
OK, they should not be running as root again.
