### ISSUE TITLE
Post generators flags cleanup

### ISSUE THREAD

**Issue by rikatz** [kubernetes/kubernetes#99897]
So with #99733 and #99732 we are almost done cleaning deprecations.

There are some follow ups that need to be done:

* [ ] In staging/src/k8s.io/kubectl/pkg/cmd/autoscale.go the deprecated flag "generator" must be removed - @MadhavJivrajani 
* [ ] In staging/src/k8s.io/kubectl/pkg/cmd/create/create_deployment.go the call to AddGeneratorFlag must be replaced to 	cmdutil.AddDryRunFlag(cmd) and then in staging/src/k8s.io/kubectl/pkg/cmd/util/helpers.go the function AddGeneratorFlags can be removed - @BLasan

This is a good first issue. If you already did any contribution to Kubernetes, **please leave this issue for someone that never contributed!**
If you are a first time contributor, please comment on this issue with what item you wanna work, and I'll assign it to you. Then when the PR is ready, please mark me (/assign @rikatz and /cc @rikatz) and I'll review it for you!

/sig cli
/kind cleanup
/triage accepted
/priority backlog
/good-first-issue

**Comment by MadhavJivrajani** [comment]
Hi! I'm a first-time contributor to k/k, I'd love to work on removing the deprecated `generator` flag!

**Comment by BLasan** [comment]
@rikatz Would like to take up this issue

**Comment by rikatz** [comment]
/remove-help

thanks folks. I’ll update the description today with the items for each one

**Comment by rikatz** [comment]
/assign @rikatz 
Description updated, let me know if you need any help! (can ping me on Slack as well)

**Comment by rikatz** [comment]
/close

Both PRs are merged
