### ISSUE TITLE
Failing Test: [sig-node] Probing container should be restarted with an exec liveness probe with timeout 

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#99909]
#### Which jobs are failing:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-kubelet-1-19-on-latest

this is a skew job:
- kubelet is at the HEAD of release-1.19
- apiserver / test suite are at HEAD of the master branch (to be released as 1.21)

#### Which test(s) are failing:
Kubernetes e2e suite.[sig-node] Probing container should be restarted with an exec liveness probe with timeout [NodeConformance] [Conformance]

the test is here:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/node/container_probe.go#L212-L226

#### Since when has it been failing:
Since the job was added last week.

#### Testgrid link:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-kubelet-1-19-on-latest

#### Reason for failure:
this condition does not pass:
> Description: A Pod is created with liveness probe with a Exec action on the Pod. If the liveness probe call does not return within the timeout specified, liveness probe MUST restart the Pod.

#### Anything else we need to know:

i haven't looked but could be a code failure or just a problem in the test suite at master/HEAD.

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-kubelet-1-19-on-latest/1368323279995015168

```
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:630
Mar  6 22:36:02.848: pod container-probe-1648/busybox-ce66c80f-44c7-48d1-bb91-e9d1902893c3 - expected number of restarts: 1, found restarts: 0
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/common/node/container_probe.go:225
```

looks like the probe is not restarting the pod.

**Comment by neolit123** [comment]
/sig node
/milestone v1.21

please adjust milestone as see fit.

**Comment by BenTheElder** [comment]
Wouldn't it be expected that the cluster fail conformance with a node older than the conformance test?

**Comment by neolit123** [comment]
the test suite and the core APIs / apiserver are versioned the same way.
so i'm assuming that the test-suite has the same N-2 skew guarantee.

**Comment by liggitt** [comment]
that test was promoted to conformance in 1.21 in https://github.com/kubernetes/kubernetes/pull/97619

it exercises a specific bug that was fixed in 1.20, but which modified behavior in a user-facing way, so it wasn't backported, so a 1.19 node won't pass that test

**Comment by liggitt** [comment]
Requiring conformance tests for 1.n to pass against a 1.(n-2) kubelet doesn't seem completely workable. They *usually* pass because the kubelet API surface is actually pretty small, but requiring that for 100% of conformance tests would mean any GA functionality that involves the kubelet would have to simultaneously:
* be added in 1.n to satisfy the "GA function has to have conformance tests" requirement
* wait until 1.(n+2) to satisfy the proposed "must pass against oldest supported kubelet" requirement

I think a better approach would be to tag conformance tests known to have a minimum required kubelet newer than the oldest supported kubelet for 1.n in a way that these tests can filter them out

**Comment by neolit123** [comment]
ok, understood.
we can easily pass flags to the suite to filter specific tests out per job.

i don't think i can come up with a tag name that everybody would like but .e.g something like `[KubeletMaxSkewN-1]` would mean that we skip this test when we are running an N-2 job.

**Comment by liggitt** [comment]
> i don't think i can come up with a tag name that everybody would like but .e.g something like `[KubeletMaxSkewN-1]` would mean that we skip this test when we are running an N-2 job.

I think we'd want a tag that we wouldn't need to change in future releases... something like `[MinimumKubelet:1.20]`

Then the job testing against 1.19 kubelets could `-skip '\[MinimumKubelet:(1.20|1.21)\]'`

**Comment by neolit123** [comment]
there was also the general idea to version tests and skip them when needed:
https://github.com/kubernetes/kubernetes/issues/49313

**Comment by BenTheElder** [comment]
FWIW this test also seems to have issues in node e2e. https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/99912/pull-kubernetes-node-e2e-containerd/1369152530193321984/

**Comment by neolit123** [comment]
> update the test config to exclude tests not expected to work on 1.19 kubelets

i can send the PR for this.

should the tag be `MinimumKubeletVersion` instead of `MinimumKubelet`?

**Comment by liggitt** [comment]
> should the tag be `MinimumKubeletVersion` instead of `MinimumKubelet`?

sgtm

**Comment by neolit123** [comment]
> kinder: skip tests tagged with [MinimumKubeletVersion:VERSION]

https://github.com/kubernetes/kubeadm/pull/2403

**Comment by neolit123** [comment]
> add the tag to the test

https://github.com/kubernetes/kubernetes/pull/100050

**Comment by neolit123** [comment]
> I agree with #99909 (comment) and would like to see a PR to k/community describing this new tag (look for where Feature: is defined)

https://github.com/kubernetes/community/pull/5622

**Comment by SergeyKanzhelev** [comment]
/close

the test was removed from conformance here: #100036
