### ISSUE TITLE
[Flaky] k8s.io/apiserver/pkg/admission/plugin/webhook/mutating: TestAdmit

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#99911]
/kind flake

Examples:
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/99889/pull-kubernetes-unit/1368157032984612864
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/96973/pull-kubernetes-unit/1367986207010590720
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/99857/pull-kubernetes-unit/1367919453429305344
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/99830/pull-kubernetes-unit/1367867407971913728
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/99830/pull-kubernetes-unit/1367857650569580544

Second most frequent unit test job flake currently:

https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2021-03-06&pr=1&job=pull-kubernetes-unit&test=TestAdmit&xtest=TestCompatibility%7CTestPrepareRun%7CTestMain%7CTestController2%7CTestFirewall%7CTestLabelErrors%7CTestJsonRoundTripApplyConfigurations%7CTestUnstructuredRoundTripApplyConfigurations%7CTestAtMostEvery%7CTestResourceErrors#9973b416b2d611ab9b03

```
=== RUN   TestAdmit/match_dry_run_side_effects_None
W0306 20:42:50.473031   82007 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W0306 20:42:50.473220   82007 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
    plugin_test.go:187: 
        	Error Trace:	plugin_test.go:187
        	Error:      	Not equal: 
        	            	expected: map[string]string{"allow/key1":"value1", "mutation.webhook.admission.k8s.io/round_0_index_0":"{\"configuration\":\"test-webhooks\",\"webhook\":\"allow\",\"mutated\":false}"}
        	            	actual  : map[string]string(nil)
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,5 +1,2 @@
        	            	-(map[string]string) (len=2) {
        	            	- (string) (len=10) "allow/key1": (string) (len=6) "value1",
        	            	- (string) (len=49) "mutation.webhook.admission.k8s.io/round_0_index_0": (string) (len=67) "{\"configuration\":\"test-webhooks\",\"webhook\":\"allow\",\"mutated\":false}"
        	            	-}
        	            	+(map[string]string) <nil>
        	            	 
        	Test:       	TestAdmit/match_dry_run_side_effects_None
        	Messages:   	match dry run side effects None: annotations not set as expected.
    --- FAIL: TestAdmit/match_dry_run_side_effects_None (0.02s)
```

I suspect it is related to the test not waiting for the fake data source to be completely synced so the webhook doesn't even see there's a relevant webhook to call.

_Originally posted by @liggitt in https://github.com/kubernetes/kubernetes/pull/99662#issuecomment-792106359_

**Comment by pacoxu** [comment]
I tried to fix it last week. 
https://github.com/kubernetes/kubernetes/compare/master...pacoxu:ut/flake

I suspect it is related to the lock here.

**Comment by spiffxp** [comment]
Listed as 3rd top flake for pull-kubernetes-unit: http://storage.googleapis.com/k8s-metrics/flakes-latest.json

**Comment by roycaihw** [comment]
/assign @roycaihw 
(@k8s-ci-robot please)

I think it's the same issue as https://github.com/kubernetes/kubernetes/issues/94810 (I forgot https://github.com/kubernetes/kubernetes/pull/95783 wasn't merged yet. Sorry for dropping the ball) I will revive that PR. 

/triage accepted

**Comment by liggitt** [comment]
fixed by https://github.com/kubernetes/kubernetes/pull/95783

/close
