### ISSUE TITLE
Race condition between kubelet and scheduler

### ISSUE THREAD

**Issue by cynepco3hahue** [kubernetes/kubernetes#99919]
#### What happened:

The pod passed the scheduler(moved from the Pending phase) and failed to start because of the kubelet with the error:
```
Mar 07 01:37:03 n1-standard-2-ubuntu-gke-1804-1-16-v20200330-317d5885 kubelet[7842]: I0307 01:37:03.668354    7842 predicate.go:143] Predicate failed on Pod: hugepages-q9b44_hugepages-test-5981(a32177e0-ea6e-49f5-8f25-a946530f34f4), for reason: Node didn't have enough resource: hugepages-2Mi, requested: 6291456, used: 6291456, capacity: 10485760
```

It means that the scheduler and kubelet get a different view of requested resources.

#### What you expected to happen:

I expect that if the scheduler passed the pod and the pod was started it should not fail under the kubelet because of insufficient resources.

#### How to reproduce it (as minimally and precisely as possible):

It failed under the CI - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-hugepages/1368372352512954368

Steps:
- configure hugepages under the node(5 - 2Mi-hugepages)
- start the pod, that requests 6Mi of 2Mi-hugepages
- delete the namespace where the pod started
- restart the kubelet
- start an additional pod, that requests 6Mi of 2Mi-hugepages

#### Anything else we need to know?:

It happens very rarely, something around 10%.

The problem that the scheduler and kubelet are using different mechanisms and structs to store active pods requests.

#### Environment:
- Kubernetes version (use `kubectl version`): master
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by bart0sh** [comment]
I think some delay between the time when kubelet discovers the resource and the time when resource value is updated on the API server is expected. We can't guarantee that kubelets sends updated resource to the API server, API server receives the update and updates resource value in no time, can we?

**Comment by cynepco3hahue** [comment]
the scheduler should see the same picture as the kubelet, so why does it pass the scheduler and failed under the kubelet?
Do you know why do we need the same checks under two different places(kubelet and scheduler), why it not enough to check available resources only under the scheduler?

**Comment by ahg-g** [comment]
are there any static pods being created in that test? static pods may cause this.

**Comment by cynepco3hahue** [comment]
> are there any static pods being created in that test? static pods may cause this.

Nope, regular pods with the `RestartPolicy: Never`

**Comment by cynepco3hahue** [comment]
I can not see the issue happens under the 1.21, I will re-open the issue if will encounter it again.

**Comment by bart0sh** [comment]
@cynepco3hahue I can still see it in the recent logs. Here is an example from https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-hugepages/1391989909719355392/build-log.txt:
```
I0511 05:47:52.493] May 11 05:47:40.185: INFO: At 2021-05-11 05:47:36 +0000 UTC - event for hugepages-9grm2: {kubelet n1-standard-2-ubuntu-gke-2004-1-20-v20210401-79fe32e5} OutOfhugepages-2Mi: Node didn't have enough resource: hugepages-2Mi, requested: 6291456, used: 6291456, capacity: 10485760
```

**Comment by cynepco3hahue** [comment]
@bart0sh Feel free to re-open it. I just checked that the hugepages job is much more stable than it was under 1.20.

**Comment by bart0sh** [comment]
@cynepco3hahue I can't reopen it it seems. Can you?

**Comment by bart0sh** [comment]
@cynepco3hahue @odinuge @derekwaynecarr This issue became a showstopper for promoting [multiple sizes huge pages to GA](https://github.com/kubernetes/kubernetes/pull/99144#issuecomment-843964587). Can you help to fix it?

**Comment by bart0sh** [comment]
@cynepco3hahue I've noticed a lot of similar error messages in the kubelet log of **successfull** tests. Here is an example: taken from the latest available test run: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-hugepages/1397069286773624832/artifacts/n1-standard-2-ubuntu-gke-2004-1-20-v20210401-ec1b0cae/kubelet.log:

```
predicate.go:144] "Predicate failed on Pod" pod="hugepages-test-3636/hugepages-fzbc2" err="Node didn't have enough resource: hugepages-1Gi, requested: 1073741824, used: 0, capacity: 0"
...
predicate.go:144] "Predicate failed on Pod" pod="hugepages-test-3328/hugepages-2rvtg" err="Node didn't have enough resource: hugepages-2Mi, requested: 6291456, used: 0, capacity: 0"
```

The fact that node capacity for the requested hugepages is 0 makes me suspect that test creates pods requesting hugepages that are not allocated or something similar.

Can you help to investigate this?
