### ISSUE TITLE
Use Sort and Filter while doing list of any resources

### ISSUE THREAD

**Issue by arjaiswa** [kubernetes/kubernetes#99938]
#### What would you like to be added:
Can we add feature to fetch the resource list using some filters e.g. Latest creation time , Sort by Running time ?
#### Why is this needed:
Using this I can fetch the latest created Pods instead of reading all pods and filter it .

**Comment by iraj465** [comment]
Hey i want to take this up. Can someone please point me where I should be looking?

**Comment by fedebongio** [comment]
/assign @yliaog 
Thanks you!

**Comment by yliaog** [comment]
you may use field selectors on a limited set of fields:
https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/

**Comment by yliaog** [comment]
generic field selectors are not supported, please see discussions https://github.com/kubernetes/kubernetes/issues/1362
