### ISSUE TITLE
Improve concurrency for hack/verify-structured-logging.sh

### ISSUE THREAD

**Issue by adisky** [kubernetes/kubernetes#99934]
#### What would you like to be added:
Improve concurrency for this script https://github.com/kubernetes/kubernetes/blob/master/hack/verify-structured-logging.sh#L52

follow up from this PR: https://github.com/kubernetes/kubernetes/pull/99090

#### Why is this needed:
Speed up the execution time.

/sig instrumentation testing

**Comment by adisky** [comment]
/triage accepted 
(as it is a followup issue)
/good-first-issue

**Comment by BenTheElder** [comment]
To avoid interwoven output we should consider making the tool (in the klog repo) underlying the script able to process a list of packages/sources concurrently in one invocation (versus invoking it multiple times concurrently in the script), which should also be slightly faster (less forking/execing).

**Comment by adisky** [comment]
closing this issue as per @BenTheElder's suggestion, will open an issue in klog/logcheck to make the tool work concurrently.
