### ISSUE TITLE
The output of kubectl top node subcommand is incorrect

### ISSUE THREAD

**Issue by yahaa** [kubernetes/kubernetes#99945]
#### What happened:
In my environment, there is a node whose status is as follows
```yaml
status:
  allocatable:
    cpu: "2"
    memory: 2784868Ki
  capacity:
    cpu: "4"
    memory: 3935844Ki
```
and the real average CPU utilization rate of this node is 8%, detail as the following figure
![image](https://user-images.githubusercontent.com/16364111/110336349-bca35000-805f-11eb-830d-e136501eb987.png)

and the average CPU utilization rate that `kubectl top node` output is 16%, as following figure
![image](https://user-images.githubusercontent.com/16364111/110336742-20c61400-8060-11eb-91c8-4abe40ff8eaa.png)

#### What you expected to happen:
The average CPU utilization rate that `kubectl top node` outpu is approximately equal to the real average CPU utilization rate of nodes.

#### How to reproduce it (as minimally and precisely as possible):
kubelet set the flag `--system-reserved=--system-reserved=cpu=2000m,memory=1Gi`, then run `kubectl top node`.
#### Anything else we need to know?:
I'm not sure if it's a bug, if it's a bug let me fix it.

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by soltysh** [comment]
This is working as designed, we explicitly show the allocatable resources in the output, not the overall capacity to show admins how much space is available to run pods. The overall capacity of a node should be monitored using different tools.
/close
