### ISSUE TITLE
Update AnyVolumeDataSource feature gate to beta

### ISSUE THREAD

**Issue by bswartz** [kubernetes/kubernetes#99955]
#### What would you like to be added:

Update AnyVolumeDataSource feature gate to beta

#### Why is this needed:

KEP: https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/1495-volume-populators/README.md

**Comment by bswartz** [comment]
Superseded by https://github.com/kubernetes/kubernetes/issues/103275

**Comment by markus-wa** [comment]
@bswartz - I think this issue should remain open until the feature gate status is actually set to beta

out of curiosity - do we have an estimated ETA for this?

for some background: currently there is no way to easily clone volumes on GKE as the CSI driver doesn't support it yet, and chances are `AnyVolumeDataSource` moving to beta is more likely to happen sooner than the GKE driver gaining support for cloning.

**Comment by bswartz** [comment]
I'm looking to push the PR to change the feature gate to beta this week or next. I'm currently working on updating the out-of-tree portions of it to beta to support this change. There's every reason to believe 1.24 will ship with the feature gate defaulting to on.

**Comment by markus-wa** [comment]
thanks for the status, that sounds great 😊
