### ISSUE TITLE
csi-hostpath provisioner in e2e runs uses CSINode v1beta1

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#99957]
CSINode.v1beta1 was deprecated in 1.17 and is slated for removal in 1.22.  This will cause many CSI failures in pull-kubernetes-e2e-kind after 1.22 alpha.

https://github.com/kubernetes/kubernetes/pull/99840 is exploring what needs to change when the v1beta1 APIs are automatically removed.

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/99840/pull-kubernetes-e2e-kind/1368986761652342784 shows several issues with storage and analysis suggests that the CSI driver is using v1beta1: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/99840/pull-kubernetes-e2e-kind/1368986761652342784/artifacts/_sig-storage_CSI_Volumes/_Driver_csi-hostpath_/_Testpattern_Dynamic_PV_block_volmode_volume-expand/should_not_allow_expansion_of_pvcs_without_AllowVolumeExpansion_property/csi-hostpath-provisioner-0-csi-provisioner.log

/assign @jsafrane 
@kubernetes/sig-storage-bugs 
/cc @liggitt

**Comment by gnufied** [comment]
Similarly I think CSI mock driver uses some pretty old release of attacher sidecar and hence is failing - https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/99840/pull-kubernetes-e2e-kind/1368986761652342784/artifacts/_sig-storage_CSI_mock_volume/CSI_attach_test_using_mock_driver/should_require_VolumeAttach_for_drivers_with_attachment/csi-mockplugin-attacher-0-csi-attacher.log

**Comment by jsafrane** [comment]
cc @pohly 
How often do we sync manifests from the hostpath driver?

**Comment by BenTheElder** [comment]
I think this will also impact the GCE jobs once we even get cluster bring up to succeed with the removals.

**Comment by liggitt** [comment]
GCE job starts a cluster now in https://github.com/kubernetes/kubernetes/pull/99840 and is blocked on this

/priority important-soon

**Comment by pohly** [comment]
/reopen

https://github.com/kubernetes/kubernetes/pull/100637 dealt with the hostpath driver sidecars, but the mock driver still uses older sidecars (https://github.com/kubernetes/kubernetes/pull/99840#issuecomment-825166188).

/assign @msau42

**Comment by pohly** [comment]
Mock driver updated in https://github.com/kubernetes/kubernetes/pull/101383

/assign

Let's keep this open until https://github.com/kubernetes/kubernetes/pull/99840 passes.

**Comment by msau42** [comment]
hostpath and mock csi tests are passing
/close
