### ISSUE TITLE
sched: cleanup clusterEventReg from pkg/scheduler/internal/queue/events.go

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#99966]
Follow-up of https://github.com/kubernetes/kubernetes/pull/98241#discussion_r572468952. Currently we maintain a local registry for looking up the ClusterEvent obj by specifying a cluste event (string). The registry is not that necessary as we can build that ClusterEvent obj on the fly in movePodsToActiveOrBackoffQueue().

/kind cleanup
/sig scheduling

**Comment by minbaev** [comment]
I can take a look into this

**Comment by BLasan** [comment]
Would like to work on this if @minbaev 's not working

**Comment by BLasan** [comment]
@minbaev pls unassign me if you're working on this

**Comment by minbaev** [comment]
I'm working on this

**Comment by MadhavJivrajani** [comment]
Hey @minbaev! Are you still working on this? If not, I'd like to take a crack at this 😄

**Comment by minbaev** [comment]
Hey @MadhavJivrajani we have a pr that is merge-ready for this
https://github.com/kubernetes/kubernetes/pull/100322

**Comment by nchetan** [comment]
@minbaev Can you please close this if the PR is merged. I was looking for good-first-issue and came across this. I am sure there will be others who will discover it as well :)

**Comment by Huang-Wei** [comment]
This has been fixed by #100322
