### ISSUE TITLE
Relax CSI Node length limitation in 1.22

### ISSUE THREAD

**Issue by Jiawei0227** [kubernetes/kubernetes#99981]
https://github.com/kubernetes/kubernetes/pull/98753 will be used as a preparation for relaxing CSI Node id length limitation, in 1.22, we need to make sure the AllowLongNodeID is set correctly according to the comment https://github.com/kubernetes/kubernetes/pull/98753#discussion_r589441271

/sig storage
/assign @Jiawei0227 
/cc @saad-ali @msau42 @liggitt

**Comment by thockin** [comment]
Can you make a better title - I almost jumped out of my skin :)

**Comment by Jiawei0227** [comment]
> Can you make a better title - I almost jumped out of my skin :)

Oops, sorry about that lol
