### ISSUE TITLE
Auto-delete failed Pods

### ISSUE THREAD

**Issue by qiutongs** [kubernetes/kubernetes#99986]
## Overview

Currently, the only mechanism to auto-delete failed pods is the [garbage collection](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-garbage-collection). However, the default threshold is incredibly high - 12500[1]. Therefore it is useless in practice for most of customers.

There are circumstances that pods become failed due to a k8s bug. I have seen two cases so far: "Predicate NodeAffinity failed" pods[2] and OutOfCPU pods[3].

So my question is about if we want to make some components to auto-delete failed pods, like some controllers or even kubelet.

### Additional Context
1. lower the default threshold for GC https://github.com/kubernetes/kubernetes/issues/78693 
2. Kubelet bug leading to failed pods with "Node affinity" error https://github.com/kubernetes/kubernetes/issues/93338
3. When using kube-proxy as a static pod, there could be a short time that scheduler is not aware of it. Then, scheduler doesn't account for the resource taken by kube-proxy and schedules some pod. But the node rejects the pod because of OutOfCPU.

#### 04/12/2021

A user has to implement a "watcher" to periodically detect and delete failed pods. That is bad because k8s should be able to take that responsibility.

**Comment by alculquicondor** [comment]
cc @kow3ns @derekwaynecarr

**Comment by SergeyKanzhelev** [comment]
Additional consideration here - have a different thresholds for different failure reasons. In case of pods terminated because of node graceful termination - pods will likely be less interesting for troubleshooting. See https://github.com/kubernetes/kubernetes/issues/102820

**Comment by ehashman** [comment]
/remove-kind support

I don't think this is a support request, I think this is a feature request for making this threshold configurable.

/kind feature

**Comment by alculquicondor** [comment]
The threshold is actually configurable. The problem is that setting it low potentially makes Jobs unusable.
I think we can only solve this in 1.23 when kubernetes/enhancements#2307 graduates to beta.

**Comment by schellj** [comment]
> Additional consideration here - have a different thresholds for different failure reasons. In case of pods terminated because of node graceful termination - pods will likely be less interesting for troubleshooting. See #102820

Not sure if this is the best place, but we're being affected by this topic and I'd like to to add some context.

GKE users making use of preemptible nodes, which have a lifetime of ~24 hours, are being affected by the change in graceful node shutdown behavior introduced in 1.20 in that pods scheduled on preemptible nodes that have been shut down do not get deleted. As issue https://github.com/kubernetes/kubernetes/issues/102820 notes, I was indeed confused by this behavior as the pods and nodes are working as intended, yet the pods are considered "failed". This is also causing such nodes themselves to not get deleted and I've seen new pods get scheduled onto them as well.

**Comment by ejose19** [comment]
I'm in the same boat as @schellj, besides the `kubectl get pod` clutter, it also stop other commands from working without any extra steps (like `kubectl logs`) so one needs to manually remove all `shutdown` pods or register a job for it. A configurable threshold for just `shutdown` pods (like @SergeyKanzhelev mentioned) seems like a must (and probably, most users would expect that `shutdown` pods gets auto-deleted by default).

**Comment by alculquicondor** [comment]
Note that if we deliver a solution just for shutdown pods in kubernetes, it would arrive at 1.24 at the earliest (it's a new feature and needs to go through the KEP process). By then, the Job API will be fixed and we can already lower the threshold.

**Comment by schellj** [comment]
Understood. At least in my mind, having a lower gc threshold doesn't entirely solve the issue with shutdown pods as those are pods that have behaved as intended and shouldn't be considered failed and kept around in the first place.

**Comment by alculquicondor** [comment]
cc @bobbypage to answer why the pods are not simply deleted.

**Comment by SergeyKanzhelev** [comment]
> those are pods that have behaved as intended and shouldn't be considered failed

this statement is questionable. We just don't know in some cases. If it was a job that hasn't finished yet, it is failed, even with the clean termination. If the pod failed to clearly terminate, we also want to keep information about that pod around. It is clear that pods that were terminated with the graceful termination are "happier" then ones that crashed on their own. But it is clearly not 100% expected behavior in a general sense.

**Comment by alculquicondor** [comment]
> If it was a job that hasn't finished yet, it is failed, even with the clean termination.

The fixed Job controller will consider any pod deletion a failure, even after the pod is completely removed from the API.

**Comment by SergeyKanzhelev** [comment]
> > If it was a job that hasn't finished yet, it is failed, even with the clean termination.
> 
> The fixed Job controller will consider any pod deletion a failure, even after the pod is completely removed from the API.

How will job controller know that job run to completion vs. was terminated by graceful termination?

**Comment by alculquicondor** [comment]
I should have said: any pod deletion of a pod that doesn't have a Suceeded phase is considered a failure. The full design is here: https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/2307-job-tracking-without-lingering-pods#algorithm

**Comment by schellj** [comment]
@SergeyKanzhelev Pardon me for speaking too generally. In the case affecting me in particular, pods have successfully been gracefully shutdown due to a preemptible node being scheduled for deletion, which is the expected behavior. In this case it would be preferable for the pods to simply be deleted, as they were in prior versions of kubernetes (< 1.21, I believe).

**Comment by bobbypage** [comment]
Thanks @schellj for the feedback. We are looking into the behavior for handling pods on shutdown. 

In the original design of the [graceful node shutdown KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2000-graceful-node-shutdown) it was decided to not explicitly delete pods, but rather pod them into failed phase. This followed the pattern for kubelet evictions and also made it possible for users to see why their pods were terminated. If they were deleted, pods could appear to vanish suddenly without explanation why which could also appear to be confusing. We are seeing if this makes sense as behavior long term.

 >  preferable for the pods to simply be deleted, as they were in versions of kubernetes prior to 1.20.5.

I'm not super clear what you're referring to here... what mechanism are you suggesting was used to delete pods prior to 1.20.5?

**Comment by schellj** [comment]
@bobbypage I'm not entirely sure, but I'm guessing that on GKE prior to [1.20.5-gke.500](https://cloud.google.com/kubernetes-engine/docs/release-notes#May_03_2021), there was a different process that would cordon and drain their preemptible nodes.

**Comment by Elyytscha** [comment]
we had an issue, where we had about 600 failed pods because of 'out of cpu' so basically some deployments had 300/1 replicas, 1 was running, 300 where in failed state.

This issue is capable of bringing clusters down imo. what would happen if the failed pods exceeds the max pod limit of a cluster/node?

i think its absolutely necessary that in such a situation those pods failed pods getting deleted afterwards automated.

**Comment by alculquicondor** [comment]
Failed pods don't count towards the node limit.

**Comment by Elyytscha** [comment]
> Failed pods don't count towards the node limit.

Thanks for clarification. So I think failed pods also do not have a network configuration anymore? so they also haven't allocated an IP?

**Comment by krishnakc1** [comment]
@Elyytscha I noticed that pods in 'error' status do contribute to networking overhead. I have around 107 error pods that put an overhead of 5-7 cores of cpus. Once the pods are deleted, the cpu cores are released. I use calico networking cni plugin. These errored pods come from the kubernetes job type resource. Also note that this issue is in older version of K8s(1.17).  I am not sure if the newer versions have this problem or not.
